from h import *
R=[]
R.append((6169032,{
"es":L("Cuadritos de pan de calabacín con chocolate oscuro","Si tiene antojo de chocolate, ¡pruebe estos cuadritos de pan de calabacín con chocolate oscuro endulzados de forma natural! Húmedos e intensos, estos bocadillos parecidos a los brownies son un excelente postre para personas con diabetes. Además, puede personalizar fácilmente esta receta con sus sabores favoritos. ¿Quiere agregar un poco de textura crujiente? Incorpore pistachos picados, nueces picadas o granos de cacao junto con el calabacín. Nota: los ingredientes opcionales no están incluidos en el análisis nutricional.","15","1 cuadrito",
["1/4 taza + 1/2 cucharadita de aceite de girasol o de aguacate","1 1/2 taza de harina integral para repostería o la harina de su preferencia","1/3 taza de cacao en polvo sin azúcar (compactado)","3/4 cucharadita de polvo de hornear","1/2 cucharadita de bicarbonato de sodio","1/2 cucharadita de sal marina","1 1/2 taza de puré de plátanos (bananas) bien maduros (aprox. 3 plátanos medianos)","2 huevos grandes","1 1/2 cucharadita de extracto puro de vainilla","2 cucharaditas de ralladura de naranja","1 calabacín grande (rallado grueso; no lo escurra)"],
["Precaliente el horno a 350°F. Unte un molde para hornear de 9 por 13 pulgadas con 1/2 cucharadita del aceite. Forre solo el fondo del molde con papel pergamino.","En un tazón mediano, bata juntos la harina, el cacao en polvo, el polvo de hornear, el bicarbonato de sodio y la sal.","En un tazón grande, bata el puré de plátano, los huevos, el 1/4 taza de aceite restante, la vainilla y la ralladura de naranja hasta que estén bien integrados. Agregue la mezcla seca y revuelva solo hasta combinar. Agregue el calabacín y revuelva hasta que se integre de manera uniforme.","Extienda la masa de forma pareja en el molde preparado. Hornee hasta que esté esponjosa al tacto, unos 35 a 38 minutos.","Deje enfriar por completo en el molde sobre una rejilla. Corte en 15 cuadritos y sirva a temperatura ambiente. Guarde en un recipiente hermético en el refrigerador hasta por 1 semana, o en el congelador hasta por 3 meses."]),
"ar":L("مربعات خبز الكوسا بالشوكولاتة الداكنة","إذا كنت تشتهي الشوكولاتة، فجرّب مربعات خبز الكوسا بالشوكولاتة الداكنة المحلّاة طبيعيًا! هذه الحلوى الشبيهة بالبراوني رطبة وغنية، وهي تحلية رائعة لمرضى السكري. كما يمكنك بسهولة تعديل الوصفة حسب نكهاتك المفضلة! هل تريد إضافة قليل من القرمشة؟ أضف الفستق المفروم أو الجوز المفروم أو قطع الكاكاو مع الكوسا. ملاحظة: المكونات الاختيارية غير محسوبة في التحليل الغذائي.","15","1 مربع",
["¼ كوب + ½ ملعقة صغيرة زيت عباد الشمس أو زيت الأفوكادو","1½ كوب دقيق القمح الكامل للمعجنات أو دقيق من اختيارك","⅓ كوب مسحوق الكاكاو غير المحلى (مكبوس)","¾ ملعقة صغيرة بيكنج باودر","½ ملعقة صغيرة بيكربونات الصوديوم","½ ملعقة صغيرة ملح البحر","1½ كوب موز مهروس ناضج تمامًا (حوالي 3 حبات موز متوسطة)","2 بيضة كبيرة","1½ ملعقة صغيرة مستخلص الفانيليا الطبيعي","2 ملعقة صغيرة قشر برتقال مبشور","1 كوسا كبيرة (مبشورة خشنًا، ولا تصفِّها)"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). ادهن صينية خبز بقياس 9 × 13 بوصة بـ½ ملعقة صغيرة من الزيت. بطّن قاع الصينية فقط بورق الزبدة.","في وعاء خلط متوسط، اخفق معًا الدقيق ومسحوق الكاكاو والبيكنج باودر وبيكربونات الصوديوم والملح.","في وعاء كبير، اخفق الموز المهروس والبيض وباقي الزيت (¼ كوب) والفانيليا وقشر البرتقال حتى تمتزج المكونات جيدًا. أضف الخليط الجاف وقلّب حتى يمتزج فقط. أضف الكوسا وقلّب حتى تمتزج بالتساوي.","وزّع العجين بالتساوي في الصينية المجهزة. اخبزه حتى يرتد عند لمسه، لمدة 35 إلى 38 دقيقة تقريبًا.","اتركه يبرد تمامًا في الصينية على رف. قطّعه إلى 15 مربعًا وقدّمه بدرجة حرارة الغرفة. احفظه في وعاء محكم الإغلاق في الثلاجة لمدة تصل إلى 1 أسبوع أو في الفريزر لمدة تصل إلى 3 أشهر."])}))
R.append((6169270,{
"es":L("Pollo frito al horno estilo latino","¡Última hora: se ha descubierto el secreto del buen pollo frito sin freír! Bromas aparte, ¿alguna vez soñó con poder comer pollo frito mientras se alimenta de forma saludable? Me querrá para siempre por esta receta de pollo al horno, crujiente y jugoso. Con nuestro pollo frito al horno podemos vivir felices para siempre. Para preparar su propio sazonador Adobo sin sal, mezcle 1 cucharada de cada uno de los siguientes: pimienta con limón, ajo en polvo, cebolla en polvo, orégano seco, perejil seco y achiote en polvo, y 1/2 cucharada de comino. Guárdelo en un recipiente hermético hasta por 2 semanas.","4","1 filete",
["1 rocío de aceite en aerosol antiadherente","1/4 taza de jugo de limón verde (de 2 limones)","1 clara de huevo","1 cucharadita de salsa de soya baja en sodio","1/2 cucharadita de orégano seco","2 dientes de ajo (picados finamente)","1/2 taza de pan molido panko integral","3/4 cucharadita de sazonador Adobo","1/4 cucharadita de sal","4 filetes (de 5 onzas) de pechuga de pollo cortados en rebanadas finas"],
["Precaliente el horno a 425°F. Rocíe ligeramente una bandeja pequeña para hornear con aceite en aerosol antiadherente.","Coloque la bandeja en el horno durante 10 minutos para que se caliente antes de poner los filetes de pollo.","Bata el jugo de limón, la clara de huevo, la salsa de soya, el orégano y el ajo en un tazón mediano.","Ponga el panko, el sazonador adobo y la sal sobre una hoja de papel encerado. Pase el pollo, una pieza a la vez, primero por la mezcla de limón y luego por la mezcla de panko, presionando ligeramente para que el empanizado se adhiera.","Coloque el pollo en la bandeja para hornear. Rocíe ligeramente con aceite en aerosol antiadherente. Hornee, sin voltear, hasta que la costra esté dorada y el pollo esté bien cocido, unos 20 minutos."]),
"ar":L("دجاج مقلي مخبوز على الطريقة اللاتينية","خبر عاجل: تم اكتشاف سر الدجاج المقلي الرائع دون قلي! حسنًا، بعيدًا عن المزاح، هل خطر ببالك يومًا أن تناول الدجاج المقلي ممكن مع الأكل الصحي؟ ستحب هذه الوصفة إلى الأبد، فهي دجاج مخبوز ومقرمش وطري. يمكننا أن نعيش بسعادة مع دجاجنا المقلي المخبوز. لتحضير توابل أدوبو الخالية من الملح بنفسك، اخلط 1 ملعقة كبيرة من كل من: فلفل الليمون ومسحوق الثوم ومسحوق البصل والأوريجانو المجفف والبقدونس المجفف ومسحوق الأشيوت، مع ½ ملعقة كبيرة من الكمون. احفظها في وعاء محكم الإغلاق لمدة تصل إلى أسبوعين.","4","1 شريحة",
["1 بخّة بخاخ طهي غير لاصق","¼ كوب عصير ليمون أخضر (من 2 حبة ليمون)","1 بياض بيضة","1 ملعقة صغيرة صلصة صويا قليلة الصوديوم","½ ملعقة صغيرة أوريجانو مجفف","2 فص ثوم (مفروم ناعمًا)","½ كوب فتات خبز بانكو من القمح الكامل","¾ ملعقة صغيرة توابل أدوبو","¼ ملعقة صغيرة ملح","4 شرائح (5 أونصات) من شرائح الدجاج الرقيقة"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية). رشّ صينية خبز صغيرة رشًا خفيفًا ببخاخ الطهي غير اللاصق.","ضع الصينية في الفرن لمدة 10 دقائق لتسخن قبل وضع شرائح الدجاج عليها.","اخفق عصير الليمون وبياض البيض وصلصة الصويا والأوريجانو والثوم في وعاء متوسط.","ضع البانكو وتوابل الأدوبو والملح على ورقة شمعية. اغمس الدجاج، قطعة قطعة، في خليط الليمون ثم في خليط البانكو، مع الضغط برفق ليلتصق الفتات.","ضع الدجاج على صينية الخبز. رشّه رشًا خفيفًا ببخاخ الطهي غير اللاصق. اخبزه دون قلبه حتى تصبح القشرة ذهبية ويستوي الدجاج تمامًا، حوالي 20 دقيقة."])}))
R.append((6169737,{
"ar":L("سلطة الكينوا اليونانية","هذه السلطة مصدر قوي للتغذية. الكينوا حبوب خالية من الغلوتين توفر الكربوهيدرات والبروتين، وتضيف الخضراوات القليلة الكربوهيدرات الألياف والبوتاسيوم.","10","½ كوب",
["1 كوب كينوا","2 كوب مرق دجاج قليل الصوديوم (قليل الصوديوم، منخفض الدسم، (أو مرق خالٍ من الغلوتين إذا كنت تطبخ دون غلوتين))","1 حبة خيار كبيرة (مقشرة ومنزوعة البذور ومقطعة مكعبات)","10½ أونصة طماطم عنبية (مقطعة نصفين)","¼ كوب بصل أحمر (مقطع مكعبات صغيرة)","¼ كوب بقدونس طازج (مفروم)","½ كوب جبن فيتا (قليل الدسم، مفتت)","¼ كوب خل النبيذ الأحمر","2 ملعقة كبيرة زيت زيتون","½ ملعقة كبيرة خردل ديجون","1 ملعقة صغيرة بديل سكر قليل السعرات"],
["اطبخ الكينوا حسب تعليمات العبوة مع مرق الدجاج. اتركها تبرد تمامًا.","في وعاء سلطة كبير، اخلط الكينوا الباردة مع باقي مكونات السلطة.","في وعاء صغير، اخفق مكونات التتبيلة معًا. اسكبها على السلطة وقلّب حتى تتغطى. قدّمها باردة."])}))
R.append((6170052,{
"es":L("Batata (camote) al horno","Información nutricional de la batata (camote)","1","1 papa mediana, 6 onzas",["1 batata (camote) mediana (al horno, 6 oz)"]),
"ar":L("بطاطا حلوة مخبوزة","معلومات غذائية عن البطاطا الحلوة","1","1 حبة متوسطة، 6 أونصات",["1 حبة بطاطا حلوة متوسطة (مخبوزة، 6 أونصات)"])}))
R.append((6170402,{
"es":L("\"Nice cream\" de chocolate y menta","¡Este \"nice cream\" no tiene lácteos! Los plátanos (bananas) aportan su deliciosa cremosidad y dulzor. La próxima vez que tenga plátanos muy maduros en la encimera, no los tire: pélelos y córtelos en \"rodajas\", extienda las rodajas en una bandeja para hornear y congele hasta que estén completamente sólidas; luego guárdelas en un recipiente apto para congelador. Mientras procesa el nice cream, al principio se ve desmenuzado, y quizá piense que no va a funcionar. Solo tenga paciencia. De repente se volverá suave como el terciopelo. Los granos de cacao añaden un agradable toque crujiente a chocolate a este postre vegano sin azúcar añadida.","3","1/2 taza",
["2 plátanos (bananas) medianos bien maduros (cortados en rodajas y congelados)","3 cucharadas de cacao en polvo sin azúcar","1/2 cucharadita de extracto de vainilla","1/4 cucharadita de extracto de menta","1 cucharada de granos de cacao"],
["Ponga las rodajas de plátano congeladas, el cacao en polvo y los extractos en un procesador de alimentos. Tape y pulse 10 veces para triturar los plátanos.","Procese la mezcla de plátano a velocidad alta hasta que quede cremosa, unos 2½ minutos. Cada 30 segundos, detenga el procesador y raspe el interior.","Agregue los granos de cacao y pulse 3 veces para combinar.","Disfrútelo de inmediato, como helado suave. O congélelo hasta que esté sólido; a la hora de servir, déjelo a temperatura ambiente durante 15 minutos, sírvalo con una cuchara y disfrute."]),
"ar":L("\"نايس كريم\" بالشوكولاتة والنعناع الفلفلي","لا يحتوي هذا \"النايس كريم\" على أي منتجات ألبان! يمنحه الموز قوامه الكريمي اللذيذ وحلاوته. في المرة القادمة التي يكون لديك فيها موز شديد النضج، لا ترمه، بل قشّره وقطّعه إلى \"أقراص\"، ثم ضع الأقراص على صينية خبز وجمّدها حتى تتجمد تمامًا، ثم احفظها في وعاء مناسب للفريزر. أثناء هرس النايس كريم في المحضّرة، سيبدو في البداية متفتتًا، وقد تظن أنه لن ينجح. فقط تحلَّ بالصبر. سيصبح فجأة ناعمًا كالمخمل. تضيف قطع الكاكاو قرمشة لذيذة بنكهة الشوكولاتة إلى هذه الحلوى النباتية الخالية من السكر المضاف.","3","½ كوب",
["2 حبة موز متوسطة ناضجة تمامًا (مقطعة أقراصًا ومجمدة)","3 ملاعق كبيرة مسحوق كاكاو غير محلى","½ ملعقة صغيرة مستخلص الفانيليا","¼ ملعقة صغيرة مستخلص النعناع الفلفلي","1 ملعقة كبيرة قطع الكاكاو"],
["ضع أقراص الموز المجمدة ومسحوق الكاكاو والمستخلصات في محضّرة الطعام. غطِّها وشغّلها بنبضات قصيرة 10 مرات لتقطيع الموز.","اخلط خليط الموز على أعلى سرعة حتى يصبح كريميًا، حوالي 2½ دقيقة. توقف كل 30 ثانية واكشط الجوانب الداخلية للمحضّرة.","أضف قطع الكاكاو وشغّل المحضّرة بنبضات قصيرة 3 مرات لتمتزج.","استمتع به فورًا بقوام الآيس كريم الطري. أو جمّده حتى يتصلب، وعند التقديم اتركه خارج الفريزر 15 دقيقة ثم اغرفه وقدّمه."])}))
R.append((6172613,{
"es":L("Fresas con glaseado balsámico, pimienta negra y estragón","Puede parecer extraño añadir vinagre balsámico y pimienta negra a las fresas, ¡pero sus papilas gustativas quedarán encantadas! La acidez del glaseado balsámico, que no es más que vinagre balsámico concentrado, resalta el dulzor de las fresas, mientras que la pimienta negra aporta un toque picante. Estas fresas son deliciosas solas, o puede usarlas para cubrir yogur de vainilla. También puede servirlas sobre una cama de espinacas como acompañamiento de la cena.","8","1/2 taza",
["16 oz de fresas (sin el rabito y cortadas por la mitad)","1 1/2 cucharada de glaseado balsámico","1/8 cucharadita de pimienta negra","1 ramita de estragón fresco"],
["En un tazón grande para servir, combine las fresas y el glaseado balsámico. Ralle la pimienta negra por encima y mezcle suavemente. Decore con ramitas de estragón.","* El glaseado balsámico (a veces llamado almíbar balsámico) se encuentra donde se venden los vinagres. Para prepararlo en casa, caliente 3 cucharadas de vinagre balsámico en una cacerola. Deje que hierva ligeramente y cocine, revolviendo de vez en cuando, hasta que el vinagre espese y se reduzca a la mitad de su volumen."]),
"ar":L("فراولة مع صلصة البلسميك المركّزة والفلفل الأسود والطرخون","قد تبدو إضافة خل البلسميك والفلفل الأسود إلى الفراولة غريبة، لكن براعم التذوق لديك ستبتهج! فحموضة صلصة البلسميك المركّزة، وهي خل بلسميك مركّز لا أكثر، تُبرز حلاوة الفراولة، بينما يضيف الفلفل الأسود لمسة من الحرارة. هذه الفراولة رائعة بمفردها، أو يمكنك استخدامها لتغطية الزبادي بالفانيليا. أو قدّمها فوق طبقة من السبانخ كطبق جانبي مع العشاء.","8","½ كوب",
["16 أونصة فراولة (منزوعة الأعناق ومقطعة نصفين)","1½ ملعقة كبيرة صلصة بلسميك مركّزة","⅛ ملعقة صغيرة فلفل أسود","1 غصن طرخون طازج"],
["في وعاء تقديم كبير، اخلط الفراولة مع صلصة البلسميك المركّزة. اطحن الفلفل الأسود فوقها وقلّب برفق. زيّنها بأغصان الطرخون.","* يمكنك العثور على صلصة البلسميك المركّزة (وتسمى أحيانًا شراب البلسميك) في المكان الذي تُباع فيه أنواع الخل. لتحضيرها بنفسك، سخّن 3 ملاعق كبيرة من خل البلسميك في قدر. دعه يغلي بهدوء واطهِه مع التحريك من وقت لآخر حتى يثخن الخل ويتبخر إلى نصف حجمه."])}))
R.append((6174318,{
"es":L("Vinagreta de tres cítricos","Esta vinagreta cítrica y vibrante es perfecta para ensaladas de verano, verduras marinadas o cualquier proteína. Sírvala con la Ensalada de pollo a la parrilla con nueces pecanas caramelizadas.","16","1 cucharada",
["2 cucharaditas de jengibre fresco (pelado y rallado)","1 cucharada de salsa de soya baja en sodio","1 cucharada de mostaza Dijon","1 cucharada de miel","1 cucharada de aceite de oliva","2 cucharadas de jugo de limón","1/3 taza de jugo de toronja (pomelo)","1/4 taza de jugo de naranja recién exprimido"],
["Combine todos los ingredientes en una licuadora y procese hasta que quede suave. Vierta en un tazón, tape y refrigere.","Guarde en un recipiente hermético en el refrigerador hasta por una semana."]),
"ar":L("صلصة الفينيجريت بثلاثة أنواع من الحمضيات","صلصة الفينيجريت المنعشة بالحمضيات هذه مثالية لسلطات الصيف أو الخضراوات المتبّلة أو أي نوع من البروتين. قدّمها مع سلطة الدجاج المشوي بالبيكان المكرمل.","16","1 ملعقة كبيرة",
["2 ملعقة صغيرة زنجبيل طازج (مقشر ومبشور)","1 ملعقة كبيرة صلصة صويا قليلة الصوديوم","1 ملعقة كبيرة خردل ديجون","1 ملعقة كبيرة عسل","1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة عصير ليمون","⅓ كوب عصير جريب فروت","¼ كوب عصير برتقال معصور طازجًا"],
["ضع جميع المكونات في الخلاط وامزجها حتى تصبح ناعمة. اسكبها في وعاء وغطِّه وضعه في الثلاجة.","احفظها في وعاء محكم الإغلاق في الثلاجة لمدة تصل إلى أسبوع."])}))
R.append((6174921,{
"ar":L("صلصة الخوخ والفاصوليا السوداء مع الرقائق","إليك لمسة ممتعة على الصلصة سيحبها الجميع في نزهتك أو حفل الشواء القادم في الصيف.","8","⅓ كوب ممتلئ من الصلصة + 6 رقائق",
["2 ملعقة كبيرة عصير ليمون أخضر (من 1 حبة ليمون تقريبًا)","1 حبة هالابينو صغيرة (حوالي 2 ملعقة كبيرة) (مع بعض البذور، مفرومة ناعمًا)","¼ ملعقة صغيرة ملح البحر، أو حسب الرغبة","¼ ملعقة صغيرة فلفل أسود مطحون طازجًا","1 ملعقة كبيرة زيت الفول السوداني","1 حبة خوخ كبيرة (منزوعة النواة ومقطعة مكعبات صغيرة جدًا)","3 حبات بصل أخضر (كامل) (مقطعة شرائح رفيعة، الجزء الأخضر والأبيض)","½ ملعقة صغيرة أوراق أوريجانو طازجة (مفرومة ناعمًا)","1 علبة فاصوليا سوداء (15 أونصة، مشطوفة برفق ومصفاة (1½ كوب))","48 رقاقة تورتيلا من الذرة الزرقاء أو البطاطا الحلوة"],
["ضع عصير الليمون الأخضر والهالابينو والملح والفلفل في وعاء متوسط. اخفق الزيت معها حتى يمتزج جيدًا. أضف الخوخ والبصل الأخضر والأوريجانو وقلّب حتى تمتزج. أضف الفاصوليا وقلّب، ثم عدّل التتبيل.","رتّب رقائق التورتيلا في طبق تقديم حول وعاء الصلصة، وقدّمها بدرجة حرارة الغرفة. أو قدّم حصصًا فردية من الصلصة مع الرقائق."])}))
R.append((6175376,{
"ar":L("فريتاتا الخضار الصغيرة","هل تبحث عن بداية قليلة الكربوهيدرات ليومك؟ هذه الفريتاتا الصغيرة تصنع إفطارًا سريعًا وصحيًا! هذه الوصفة مجرد بداية، فلا تتردد في تجربة خضراوات مختلفة مثل الكوسا أو الهليون أو السبانخ.","9","1 فريتاتا صغيرة",
["9 قوالب ورقية للمافن","1 بخّة (0.25 غرام) من بخاخ الطهي غير اللاصق","¼ كوب بصل (مقطع مكعبات)","½ كوب فلفل رومي أخضر (مقطع مكعبات)","5 بيضات كبيرة","4 بياضات بيض كبيرة","½ ملعقة صغيرة ملح (اختياري)","¼ ملعقة صغيرة فلفل أسود مطحون طازجًا","3 ملاعق كبيرة جبن بارميزان (مبشور طازجًا)"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية). بطّن صينية المافن بالقوالب الورقية.","رشّ مقلاة بخاخ الطهي وسخّنها على نار متوسطة إلى عالية. أضف البصل والفلفل واطهِهما لمدة 5 دقائق. ضعهما جانبًا.","في وعاء متوسط، اخفق باقي المكونات معًا. أضف الفلفل الأخضر والبصل إلى خليط البيض وقلّب جيدًا.","اسكب خليط البيض في قوالب المافن، واملأ كل قالب حتى ⅔ تقريبًا. اخبز لمدة 20 دقيقة أو حتى يتماسك وسط الفريتاتا."])}))
R.append((6176359,{
"es":L("Peras con cobertura de caramelo y almendras en la Instant Pot","¡Tostar, escalfar y cocer a fuego lento: todo lo que necesita hacer para preparar este sabroso postre lo puede hacer en la Instant Pot! Se usan caramelos sin azúcar para crear una salsa de caramelo rica que cubre estas peras escalfadas con canela. Puede parecer elegante, pero este postre se prepara en menos de 20 minutos.","4","1/2 pera",
["1/4 taza de almendras en tiras","8 caramelos duros sin azúcar sabor caramelo (como Werther's) (triturados)","1/8 cucharadita de sal","3/4 taza de agua","1/4 taza de jugo de manzana","1 rama de canela entera","2 peras medianas firmes (peladas, cortadas por la mitad a lo largo y sin el corazón)","1 cucharadita de mantequilla light con aceite de canola","1/2 cucharadita de extracto de vainilla"],
["Presione el botón Sauté (Saltear) de la olla multicocción. Cuando la olla esté caliente, agregue las almendras y cocine durante 4 minutos, revolviendo de vez en cuando. Reserve para que se enfríen y luego pique grueso.","En un tazón pequeño, ponga las almendras picadas, los caramelos triturados y la sal. Reserve.","Coloque el agua, el jugo y la rama de canela en la olla. Coloque la canasta para vapor en la olla y acomode las peras encima.","Selle la tapa, cierre la válvula y presione el botón Cancel (Cancelar). Seleccione Manual y cocine durante 2 minutos. (Si prefiere una pera muy blanda, cocine un minuto adicional.) Use la liberación rápida de presión.","Cuando baje la válvula, retire la tapa con cuidado. Retire la canasta para vapor y las peras. Coloque las peras, con el lado cortado hacia arriba, en cuatro platos de postre. Retire y deseche la rama de canela.","Presione el botón Cancel y luego el botón Sauté. Lleve a hervor el líquido de la olla. Hierva durante 3 minutos, o hasta que el líquido se reduzca a 1/4 de taza. Incorpore la mantequilla, el extracto de vainilla y la mezcla de almendras y caramelo. Cocine durante 30 segundos, o hasta que el caramelo se derrita, revolviendo constantemente.","Trabajando rápidamente, ponga unas 4 cucharaditas de la salsa de caramelo en el centro de cada mitad de pera."]),
"ar":L("كمثرى مغطاة بالتوفي واللوز في إنستانت بوت","تحميص وسلق وطهي على نار هادئة، كل ما عليك فعله لتحضير هذه التحلية اللذيذة يمكنك إنجازه في إنستانت بوت! تُستخدم حلوى خالية من السكر لصنع صلصة توفي غنية تغطي حبات الكمثرى المسلوقة بالقرفة. قد تبدو فاخرة، لكن هذه التحلية تجهز في أقل من 20 دقيقة.","4","½ حبة كمثرى",
["¼ كوب لوز شرائح","8 حبات حلوى صلبة بنكهة الكراميل خالية من السكر (مثل Werther's) (مجروشة)","⅛ ملعقة صغيرة ملح","¾ كوب ماء","¼ كوب عصير تفاح","1 عود قرفة كامل","2 حبة كمثرى متوسطة صلبة (مقشرة ومقسومة نصفين طوليًا ومنزوعة القلب)","1 ملعقة صغيرة زبدة خفيفة بزيت الكانولا","½ ملعقة صغيرة مستخلص الفانيليا"],
["اضغط زر Sauté (التحمير) في الطباخ متعدد الوظائف. عندما يسخن الوعاء، أضف اللوز واطهِه لمدة 4 دقائق مع التحريك من وقت لآخر. ضعه جانبًا ليبرد، ثم افرمه فرمًا خشنًا.","في وعاء صغير، ضع اللوز المفروم والحلوى المجروشة والملح. ضعه جانبًا.","ضع الماء والعصير وعود القرفة في وعاء الطباخ. ضع سلة البخار في الوعاء ورتّب الكمثرى فوقها.","أحكم إغلاق الغطاء، وأغلق صمام الضغط، واضغط زر Cancel (إلغاء). اختر Manual (يدوي) واطهِ لمدة 2 دقيقة. (إذا كنت تفضل كمثرى طرية جدًا، فأضف 1 دقيقة للطهي.) استخدم التفريغ السريع للضغط.","عندما ينخفض الصمام، ارفع الغطاء بحذر. أخرج سلة البخار والكمثرى. ضع الكمثرى، والجزء المقطوع إلى الأعلى، في أربعة أطباق تحلية. أخرج عود القرفة وتخلص منه.","اضغط زر Cancel، ثم اضغط زر Sauté. اترك السائل في الوعاء يغلي. دعه يغلي لمدة 3 دقائق، أو حتى يتبخر السائل إلى ¼ كوب. أضف الزبدة ومستخلص الفانيليا وخليط اللوز والحلوى مع التحريك. اطهِه لمدة 30 ثانية، أو حتى تذوب حلوى التوفي، مع التحريك باستمرار.","اعمل بسرعة، واغرف حوالي 4 ملاعق صغيرة من صلصة التوفي في وسط كل نصف كمثرى."])}))
R.append((6177288,{
"es":L("Compota de pera con arce","Si le encanta la compota de manzana, pruebe esta compota de pera con arce. Con todos los sabores del otoño y el invierno, es un postre delicioso que toda la familia puede disfrutar.","4","1/2 taza",
["4 peras medianas (maduras, peladas, sin el corazón y picadas)","1/4 taza de agua","1 cucharadita de extracto de arce","1 cucharadita de canela molida","1 cucharada de jugo de limón"],
["En una cacerola, combine las peras picadas, 1/4 taza de agua, el extracto de arce, la canela molida y el jugo de limón.","Coloque la cacerola a fuego medio y lleve la mezcla a hervir a fuego lento.","Tape con la tapa.","Reduzca el fuego a lento y cocine, revolviendo de vez en cuando, durante unos 40 minutos o hasta que las peras estén tiernas y se puedan triturar fácilmente con un tenedor o una licuadora de mano.","Sirva tibia o fría."]),
"ar":L("صلصة الكمثرى بالقيقب","إذا كنت تحب صلصة التفاح، فجرّب صلصة الكمثرى بالقيقب هذه. فهي تجمع كل نكهات الخريف والشتاء، وهي تحلية لذيذة تستمتع بها العائلة كلها.","4","½ كوب",
["4 حبات كمثرى متوسطة (ناضجة، مقشرة ومنزوعة القلب ومقطعة)","¼ كوب ماء","1 ملعقة صغيرة مستخلص القيقب","1 ملعقة صغيرة قرفة مطحونة","1 ملعقة كبيرة عصير ليمون"],
["في قدر، اخلط الكمثرى المقطعة و¼ كوب ماء ومستخلص القيقب والقرفة المطحونة وعصير الليمون.","ضع القدر على نار متوسطة واترك الخليط حتى يغلي بهدوء.","غطِّ القدر بالغطاء.","اخفض النار إلى أقل درجة واتركه يغلي بهدوء مع التحريك من وقت لآخر لمدة 40 دقيقة تقريبًا أو حتى تلين الكمثرى ويسهل هرسها بالشوكة أو بالخلاط اليدوي.","قدّمها دافئة أو باردة."])}))
R.append((6177299,{
"es":L("Sopa toscana de frijoles","Esta sopa toscana de frijoles fue una de las primeras sopas que Robyn Webb aprendió en una clase de cocina en una granja en Italia. La simplificó usando frijoles enlatados (la receta original usa frijoles secos), lo cual funciona perfectamente. Es similar a la sopa minestrone, pero sin pasta. No olvide agregar el vinagre balsámico: realza el sabor de las verduras y hace que los garbanzos tengan un sabor aún más rico. Cubra cada plato con queso parmesano recién rallado, si lo desea.","9","1 taza",
["1 cucharada de aceite de oliva","1 cebolla (picada en cubos)","2 tallos de apio (picados en cubos)","2 zanahorias medianas (picadas en cubos)","4 dientes de ajo (picados finamente)","2 cucharaditas de romero fresco (picado finamente)","5 tazas de caldo de pollo (bajo en sodio)","1 lata (de 14.5 onzas) de tomates picados enlatados","2 latas (de 15 onzas) de garbanzos (escurridos y enjuagados)","2 cucharadas de albahaca fresca (picada finamente)","3 cucharadas de vinagre balsámico"],
["En una olla a fuego medio, caliente el aceite de oliva. Agregue la cebolla, el apio y las zanahorias y saltee durante 5 minutos.","Agregue el ajo y el romero y saltee 1 minuto.","Agregue el resto de los ingredientes, excepto la albahaca fresca y el vinagre. Lleve a ebullición.","Reduzca el fuego y cocine a fuego lento, parcialmente tapado, durante 20 minutos.","Agregue el vinagre y la albahaca y cocine durante 2 minutos. ¡Sirva de inmediato y disfrute!"]),
"ar":L("حساء الفاصوليا التوسكاني","كان حساء الفاصوليا التوسكاني هذا من أوائل أنواع الحساء التي تعلمتها روبين ويب في صف طبخ في مزرعة في إيطاليا. وقد بسّطته باستخدام الفاصوليا المعلّبة (تتطلب الوصفة الأصلية استخدام الفاصوليا المجففة)، وهذا مناسب تمامًا. يشبه هذا الحساء حساء المينسترون ولكن بدون معكرونة. احرص على إضافة خل البلسميك، فهو يُبرز نكهة الخضراوات ويجعل طعم الحمّص أغنى. غطِّ كل طبق بجبن البارميزان المبشور طازجًا إن رغبت.","9","1 كوب",
["1 ملعقة كبيرة زيت زيتون","1 حبة بصل (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","2 حبة جزر متوسطة (مقطعة مكعبات)","4 فص ثوم (مفروم ناعمًا)","2 ملعقة صغيرة إكليل الجبل الطازج (مفروم ناعمًا)","5 كوب مرق دجاج (قليل الصوديوم)","1 علبة (14.5 أونصة) طماطم مقطعة معلّبة","2 علبة (15 أونصة) حمّص (مشطوف ومصفّى)","2 ملعقة كبيرة ريحان طازج (مفروم ناعمًا)","3 ملاعق كبيرة خل بلسميك"],
["في قدر على نار متوسطة، سخّن زيت الزيتون. أضف البصل والكرفس والجزر وقلّبها لمدة 5 دقائق.","أضف الثوم وإكليل الجبل وقلّبهما لمدة 1 دقيقة.","أضف باقي المكونات ما عدا الريحان الطازج والخل. اتركها حتى تغلي.","اخفض النار واتركها على نار هادئة والقدر مغطى جزئيًا لمدة 20 دقيقة.","أضف الخل والريحان واطهِ لمدة 2 دقيقة. قدّمه فورًا واستمتع به!"])}))
save(2,R)
