from h import *
R=[]
R.append((6185754,{
"es":L("Ensalada de pepino y cebolla morada","Disfrute de lo crujiente y refrescante de nuestra ensalada de pepino y cebolla morada. Con pepinos en rodajas finas combinados con el toque vibrante de la cebolla morada, esta ensalada ligera y sabrosa es un complemento delicioso para cualquier comida.","4","1 taza",
["2 pepinos grandes (en rodajas finas)","1 cebolla morada mediana (en rodajas finas)","1/4 taza de eneldo fresco (picado)","2 cucharadas de vinagre de manzana","1 cucharada de aceite de oliva extra virgen","1 cucharadita de mostaza Dijon","1 cucharadita de miel"],
["En un tazón grande, combine los pepinos, la cebolla morada y el eneldo fresco.","En un tazón pequeño, bata el vinagre de manzana, el aceite de oliva extra virgen, la mostaza Dijon y la miel.","Vierta el aderezo sobre la ensalada.","Mezcle la ensalada con suavidad para que se cubra de manera uniforme.","Deje reposar la ensalada durante 10 minutos para que se mezclen los sabores. Antes de servir, mezcle la ensalada una vez más."]),
"ar":L("سلطة الخيار والبصل الأحمر","استمتع بقرمشة وانتعاش سلطة الخيار والبصل الأحمر. تجمع هذه السلطة الخفيفة اللذيذة بين شرائح الخيار الرقيقة ونكهة البصل الأحمر الحادة، وهي إضافة رائعة لأي وجبة.","4","1 كوب",
["2 حبة خيار كبيرة (مقطعة شرائح رقيقة)","1 حبة بصل أحمر متوسطة (مقطعة شرائح رقيقة)","¼ كوب شبت طازج (مفروم)","2 ملعقة كبيرة خل التفاح","1 ملعقة كبيرة زيت زيتون بكر ممتاز","1 ملعقة صغيرة خردل ديجون","1 ملعقة صغيرة عسل"],
["في وعاء كبير، اخلط الخيار والبصل الأحمر والشبت الطازج.","في وعاء صغير، اخفق خل التفاح وزيت الزيتون البكر الممتاز وخردل ديجون والعسل.","اسكب التتبيلة على السلطة.","قلّب السلطة برفق لتتغطى بالتساوي.","اترك السلطة لمدة 10 دقائق لتمتزج النكهات. قلّبها مرة أخرى قبل التقديم."])}))
R.append((6188015,{
"es":L("Chai casero","El chai es una parte muy querida de la vida diaria en muchos hogares de la India y del sur de Asia, y reúne té negro, especias aromáticas y leche cremosa en una taza reconfortante. Esta receta tiene el aroma y el sabor naturalmente intensos del té y las especias, lo que facilita disfrutar de un chai auténtico sin azúcar añadida.","1","8 onzas",
["1/2 taza de agua","1 rodaja fina de jengibre fresco","1 vaina de cardamomo verde (ligeramente triturada)","1 rama de canela","1 bolsita de té negro","1/2 taza de leche al 1%"],
["Lleve a hervor suave el agua, el jengibre, el cardamomo y la canela.","Agregue la bolsita de té y déjela en infusión de 3 a 5 minutos.","Incorpore la leche y caliente hasta que esté tibia.","Retire la bolsita de té y cuele las especias antes de servir."]),
"ar":L("شاي الشاي بالحليب (تشاي) المنزلي","التشاي جزء عزيز من الحياة اليومية في كثير من البيوت الهندية وبيوت جنوب آسيا، فهو يجمع الشاي الأسود والتوابل المدفئة والحليب الكريمي في كوب مريح. تتميز هذه الوصفة برائحة ونكهة الشاي والتوابل الغنية بشكل طبيعي، مما يسهّل الاستمتاع بتشاي أصيل دون سكر مضاف.","1","8 أونصات",
["½ كوب ماء","1 شريحة رقيقة من الزنجبيل الطازج","1 حبة هيل أخضر (مدقوقة قليلًا)","1 عود قرفة","1 كيس شاي أسود","½ كوب حليب 1%"],
["اترك الماء والزنجبيل والهيل والقرفة حتى تغلي بهدوء.","أضف كيس الشاي واتركه منقوعًا لمدة 3-5 دقائق.","أضف الحليب وسخّنه حتى يصبح دافئًا.","أخرج كيس الشاي وصفِّ التوابل قبل التقديم."])}))
R.append((6188633,{
"es":L("Ensalada de pollo con frutas","Esta ensalada de almuerzo combina fruta rica en fibra y proteína; también puede servirla como una cena ligera. Sirve cualquier variedad de manzana; sin embargo, la autora de libros de cocina Robyn Webb considera que la dulce Gala suaviza el sabor ligeramente fuerte de la carne de ave.","8","2/3 taza",
["2 1/2 tazas de pechuga de pollo cocida de charcutería (en cubos)","2 manzanas Gala pequeñas (sin pelar y en cubos)","1/2 taza de uvas rojas sin semillas cortadas por la mitad","1/4 taza de chabacanos (albaricoques) secos (en rebanadas)","1/4 taza de cerezas dulces oscuras","2 tallos de apio (en cubos)","1/4 taza de cebolla morada (picada finamente)","2 cucharadas de mayonesa light","2 cucharadas de yogur natural (sin grasa)","1/2 cucharadita de sal marina","1/4 cucharadita de pimienta negra (recién molida)"],
["Corte el pollo en cubos o rebanadas.","En un tazón grande, combine el pollo con las manzanas, las uvas, los chabacanos, las cerezas, el apio y la cebolla.","Incorpore suavemente la mayonesa, el yogur, la sal y la pimienta. Tape y refrigere durante 30 minutos para que se mezclen los sabores."]),
"ar":L("سلطة الدجاج بالفواكه","ستحصل في هذه السلطة على الفاكهة الغنية بالألياف والبروتين معًا في وجبة غداء، أو قدّمها كعشاء خفيف. يصلح أي نوع من التفاح، إلا أن مؤلفة كتب الطبخ روبين ويب ترى أن تفاح غالا الحلو يخفف النكهة القوية قليلًا للدواجن.","8","⅔ كوب",
["2½ كوب صدر دجاج مطبوخ من محل الأطعمة الجاهزة (مقطع مكعبات)","2 حبة تفاح غالا صغيرة (غير مقشرة ومقطعة مكعبات)","½ كوب عنب أحمر بدون بذور مقسوم نصفين","¼ كوب مشمش مجفف (مقطع شرائح)","¼ كوب كرز حلو داكن","2 عود كرفس (مقطع مكعبات)","¼ كوب بصل أحمر (مفروم ناعمًا)","2 ملعقة كبيرة مايونيز خفيف","2 ملعقة كبيرة زبادي سادة (خالٍ من الدسم)","½ ملعقة صغيرة ملح البحر","¼ ملعقة صغيرة فلفل أسود (مطحون طازجًا)"],
["قطّع الدجاج إلى مكعبات أو شرائح.","في وعاء كبير، اخلط الدجاج مع التفاح والعنب والمشمش والكرز والكرفس والبصل.","أضف المايونيز والزبادي والملح والفلفل بالتقليب الخفيف. غطِّ الوعاء وضعه في الثلاجة لمدة 30 دقيقة لتمتزج النكهات."])}))
R.append((6188990,{
"es":L("Dip de ricota con perejil y eneldo","Este dip de ricota con perejil y eneldo es perfecto para la primavera y el verano. Las hierbas frescas dan sabor al queso ricota suave y cremoso. Corte algunas verduras frescas, como zanahorias, apio o pepinos, para servir con el dip como una merienda refrescante y saludable. Si tiene tiempo extra, ¡hornee galletas saladas de romero y linaza bajas en carbohidratos para acompañarlo!","8","4 cucharadas (2 onzas)",
["15 oz de queso ricota bajo en grasa","1 limón mediano (la ralladura y el jugo)","1/2 taza de perejil de hoja plana (picado finamente)","1 cucharada de eneldo fresco (picado finamente)","1/2 taza de cebolla de cambray (cebollín) (en rodajas)","1 cucharada de aceite de oliva","1/8 cucharadita de sal","1/8 cucharadita de pimienta negra"],
["Combine la ricota y la ralladura y el jugo de limón en un tazón mediano. Revuelva para integrar.","Agregue el perejil, el eneldo, la cebolla de cambray, el aceite de oliva, la sal y la pimienta. Revuelva para integrar.","Refrigere durante una hora antes de servir."]),
"ar":L("غموس الريكوتا بالبقدونس والشبت","هذا الغموس من الريكوتا بالبقدونس والشبت مثالي في الربيع والصيف. تضفي الأعشاب الطازجة نكهتها على جبن الريكوتا الكريمي المعتدل. قطّع بعض الخضار الطازجة مثل الجزر أو الكرفس أو الخيار لتقديمها مع الغموس كوجبة خفيفة منعشة وصحية. وإذا توفر لديك وقت إضافي، فاخبز بسكويت إكليل الجبل وبذور الكتان القليل الكربوهيدرات لتقديمه معه!","8","4 ملاعق كبيرة (2 أونصة)",
["15 أونصة جبن ريكوتا قليل الدسم","1 حبة ليمون متوسطة (قشرها المبشور وعصيرها)","½ كوب بقدونس مسطح الأوراق (مفروم ناعمًا)","1 ملعقة كبيرة شبت طازج (مفروم ناعمًا)","½ كوب بصل أخضر (مقطع شرائح)","1 ملعقة كبيرة زيت زيتون","⅛ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود"],
["اخلط الريكوتا مع قشر الليمون وعصيره في وعاء متوسط. قلّب حتى يمتزج.","أضف البقدونس والشبت والبصل الأخضر وزيت الزيتون والملح والفلفل. قلّب حتى يمتزج.","ضعه في الثلاجة لمدة ساعة (1 ساعة) قبل التقديم.".replace("ساعة (1 ساعة)","1 ساعة")])}))
R.append((6189432,{
"es":L("Pollo, ejotes y papas en una sola bandeja","Esta comida familiar económica se prepara con solo 6 ingredientes y una bandeja para hornear, para limpiar lo mínimo. Es perfecta para las noches ocupadas entre semana, cuando necesita tener la cena lista en menos de 30 minutos. Puede usar cualquier verdura fresca o congelada. La mezcla para aderezo italiano es un excelente condimento de \"atajo\", pero puede usar otros condimentos que tenga a mano. Esta receta incluye un paso para \"lixiviar\" las papas, un proceso que reduce el potasio. Esto es útil para las personas que controlan la enfermedad renal o que siguen una dieta restringida en potasio. Si no necesita limitar el potasio, puede omitir este paso. Si no se lixivian, el contenido de potasio es de 765 mg por porción.","4","1/4 de la receta",
["2 papas rojas medianas (picadas en trozos del tamaño de un bocado)","2 cucharadas de aceite de oliva (más 1 cucharadita)","16 oz de tiras de pechuga de pollo (tenderloins)","10 oz de ejotes (judías verdes) cortados congelados","1 cucharada de mezcla para aderezo italiano"],
["Precaliente el horno a 400˚ F. Pique las papas en trozos del tamaño de un bocado. Consulte los consejos útiles para ver las instrucciones para reducir el potasio, si es necesario. Mezcle las papas con 1 cucharadita de aceite de oliva.","Rocíe una bandeja para hornear de 9 x 13 pulgadas con aceite en aerosol. Coloque las tiras de pollo crudo en 1/3 de la bandeja. Coloque las papas en otro 1/3 de la bandeja. Por último, coloque los ejotes congelados en el último 1/3 de la bandeja.","Rocíe 2 cucharadas de aceite de oliva sobre todo el pollo, las papas y los ejotes de la bandeja. Espolvoree la mezcla seca para aderezo italiano sobre toda la bandeja.","Hornee de 20 a 30 minutos. Compruebe si el pollo está cocido después de 20 minutos."]),
"ar":L("دجاج وفاصوليا خضراء وبطاطس في صينية واحدة","هذه الوجبة العائلية الاقتصادية تُحضَّر بـ6 مكونات فقط وصينية خبز واحدة لتقليل التنظيف. وهي مثالية لأمسيات أيام الأسبوع المزدحمة عندما تحتاج إلى وضع العشاء على المائدة في أقل من 30 دقيقة. يمكنك استخدام أي خضار طازجة أو مجمدة. خليط تتبيلة السلطة الإيطالية توابل \"مختصرة\" رائعة، لكن يمكنك استخدام توابل أخرى متوفرة لديك. تتضمن هذه الوصفة خطوة \"نقع\" البطاطس (Leaching) وهي عملية تقلل البوتاسيوم. وهذا مفيد للأشخاص الذين يتعاملون مع أمراض الكلى أو يتبعون نظامًا غذائيًا مقيّد البوتاسيوم. وإذا لم تكن بحاجة إلى تقليل البوتاسيوم، فيمكنك تخطي هذه الخطوة. وإذا لم تُنقع البطاطس، فإن محتوى البوتاسيوم هو 765 ملغ في الحصة الواحدة.","4","¼ الوصفة",
["2 حبة بطاطس حمراء متوسطة (مقطعة قطعًا بحجم اللقمة)","2 ملعقة كبيرة زيت زيتون (بالإضافة إلى 1 ملعقة صغيرة)","16 أونصة شرائح صدر دجاج رقيقة (تندرلوين)","10 أونصات فاصوليا خضراء مقطعة مجمدة","1 ملعقة كبيرة خليط تتبيلة السلطة الإيطالية"],
["سخّن الفرن مسبقًا إلى 400˚ فهرنهايت (200° مئوية). قطّع البطاطس إلى قطع بحجم اللقمة. راجع النصائح المفيدة للاطلاع على تعليمات تقليل البوتاسيوم إذا لزم الأمر. قلّب البطاطس مع 1 ملعقة صغيرة من زيت الزيتون.","رشّ صينية خبز بقياس 9 × 13 بوصة ببخاخ الطهي. ضع شرائح الدجاج النيئة على ⅓ الصينية. ضع البطاطس على ⅓ آخر من الصينية. وأخيرًا، ضع الفاصوليا الخضراء المجمدة على ⅓ الصينية الأخير.","رشّ 2 ملعقة كبيرة من زيت الزيتون على كامل الصينية من الدجاج والبطاطس والفاصوليا الخضراء. رشّ خليط التتبيلة الإيطالية الجاف على كامل الصينية.","اخبز لمدة 20 إلى 30 دقيقة. تحقق من نضج الدجاج بعد 20 دقيقة."])}))
R.append((6189913,{
"ar":L("كاري الخضار الهندي","هذا الكاري اللذيذ مليء بالخضراوات المغذية! قدّم هذا الطبق فوق الأرز البني أو في أكواب من الخس.","4","1¼ كوب",
["1 حبة بصل صغيرة (مفرومة)","4 فص ثوم (مفروم خشنًا)","1 حبة هالابينو متوسطة (منزوعة البذور ومفرومة)","2 ملعقة كبيرة ماء","1 ملعقة كبيرة زيت الكانولا","2 ملعقة كبيرة مسحوق الكاري الحلو","1 حبة بطاطا حلوة متوسطة (مقشرة ومقطعة قطعًا بحجم 1 بوصة)","2 حبة جزر متوسطة (مقشرة ومقطعة قطعًا بحجم 1 بوصة)","1 حبة فلفل رومي أحمر متوسطة (منزوعة البذور ومقطعة قطعًا بحجم 1 بوصة)","6 أونصات فاصوليا خضراء طازجة (مقصوصة الأطراف ومكسورة إلى نصفين، (حوالي 2 حفنة))","4 أعواد بصل أخضر (مقطعة شرائح رفيعة، (الجزء الأبيض والأخضر))","½ كوب مشروب جوز الهند غير المحلى","1 كوب مرق خضار قليل الصوديوم","1 ملعقة كبيرة نشا الذرة","2 ملعقة كبيرة كزبرة خضراء طازجة مفرومة","1 ملعقة صغيرة بابريكا","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["اهرس البصل والثوم والهالابينو والماء في الخلاط أو محضّرة الطعام للحصول على معجون.","ضع الزيت في مقلاة ووك أو مقلاة كبيرة على نار عالية. أضف معجون البصل ومسحوق الكاري إلى الزيت وقلّبهما لمدة 3-4 دقائق مع التحريك المستمر.","أضف البطاطا الحلوة والجزر إلى المعجون وقلّبها لمدة 4-5 دقائق مع التحريك المستمر.","أضف الفلفل الرومي الأحمر والفاصوليا الخضراء والبصل الأخضر. قلّبها لمدة 2 دقيقة.","في كوب أو وعاء منفصل، اخفق مشروب جوز الهند ومرق الخضار والنشا. اسكبه على الخضار واتركه يغلي. اخفض النار ليغلي بهدوء. دعه على نار هادئة والقدر مغطى لمدة 10 دقائق.","أضف الكزبرة الخضراء والبابريكا والملح (اختياري) والفلفل الأسود وقلّب."])}))
R.append((6190468,{
"es":L("Ensalada crujiente de pollo y manzana","Esta ensalada crujiente de pollo y manzana, salada y dulce a la vez, deleitará su paladar al combinar sabores frescos con nutrición. La ensalada crujiente de pollo y manzana es deliciosa y ligera, ideal para el almuerzo, la cena o una merienda rica en proteínas. Se ha modificado para la dieta de diálisis con el fin de fomentar una alimentación saludable y reducir el estrés relacionado con la comida.","5","3/4 taza",
["2 tazas de pollo cocido","1 taza de manzanas Gala","1/2 taza de apio","2 cucharadas de cebollitas de cambray (cebollín)","1/4 taza de pasas","1/3 taza de mayonesa light","1 cucharada de crema agria light","1 cucharada de jugo de limón","1/4 cucharadita de canela molida","1/4 cucharadita de pimienta negra"],
["Corte el pollo cocido en cubos. Pique la manzana y el apio en cubos pequeños. Pique las cebollitas de cambray.","Combine el pollo, la manzana, el apio, las cebollitas de cambray y las pasas en un tazón grande para ensalada.","Bata la mayonesa, la crema agria, el jugo de limón, la canela y la pimienta negra. Vierta sobre la mezcla de pollo y manzana y mezcle.","Refrigere para enfriar antes de servir."]),
"ar":L("سلطة الدجاج والتفاح المقرمشة","ستسعد هذه السلطة المقرمشة المالحة والحلوة من الدجاج والتفاح براعم التذوق لديك بالجمع بين النكهات الطازجة والتغذية. سلطة الدجاج والتفاح المقرمشة لذيذة وخفيفة، وتناسب الغداء أو العشاء أو كوجبة خفيفة غنية بالبروتين. وقد عُدّلت لتناسب نظام غسيل الكلى الغذائي لتشجيع الأكل الصحي وتقليل التوتر المرتبط بالطعام.","5","¾ كوب",
["2 كوب دجاج مطبوخ","1 كوب تفاح غالا","½ كوب كرفس","2 ملعقة كبيرة بصل أخضر","¼ كوب زبيب","⅓ كوب مايونيز خفيف","1 ملعقة كبيرة كريمة حامضة خفيفة","1 ملعقة كبيرة عصير ليمون","¼ ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة فلفل أسود"],
["قطّع الدجاج المطبوخ إلى مكعبات. قطّع التفاح والكرفس مكعبات صغيرة. افرم البصل الأخضر.","اخلط الدجاج والتفاح والكرفس والبصل الأخضر والزبيب في وعاء سلطة كبير.","اخفق المايونيز والكريمة الحامضة وعصير الليمون والقرفة والفلفل الأسود. اسكبها على خليط الدجاج والتفاح وقلّب.","ضعها في الثلاجة لتبرد قبل التقديم."])}))
R.append((6190469,{
"es":L("Frijoles negros cocidos","Información nutricional de los frijoles negros cocidos.","1","1/2 taza",["1/2 taza de frijoles negros cocidos"]),
"ar":L("فاصوليا سوداء مطبوخة","معلومات غذائية عن الفاصوليا السوداء المطبوخة.","1","½ كوب",["½ كوب فاصوليا سوداء مطبوخة"])}))
R.append((6192603,{
"es":L("Bebida fría de leche de almendras","La leche de almendras es una bebida muy popular en Sicilia y Túnez. Las versiones endulzadas se preparan cuando las almendras están frescas. Esta bebida se puede disfrutar a cualquier hora del día.","9","1/2 taza",
["1 2/3 taza de almendras peladas (en láminas)","3 tazas de leche descremada","3 cucharadas de néctar de agave light","1 cucharadita de ralladura de limón","10 cubos de hielo"],
["Lleve a ebullición las almendras, la leche y la ralladura de limón en una cacerola mediana a fuego medio. Cocine durante 5 minutos y luego retire del fuego.","Pase la mezcla de almendras a una licuadora. Retire la tapa central de la tapadera, coloque una toalla sobre el orificio y licúe la mezcla de almendras hasta que quede suave.","Incorpore el néctar de agave y agregue los cubos de hielo. Procese hasta que quede suave y bata hasta que esté espumosa. Enfríe en vasos transparentes durante una hora o hasta que esté fría y luego sirva."]),
"ar":L("مشروب حليب اللوز المنعش","حليب اللوز مشروب شائع جدًا في صقلية وتونس. وتُحضَّر النسخ المحلّاة عندما يكون اللوز طازجًا. يمكن الاستمتاع بهذا المشروب في أي وقت من اليوم.","9","½ كوب",
["1⅔ كوب لوز مقشر (شرائح)","3 كوب حليب خالٍ من الدسم","3 ملاعق كبيرة رحيق الأغاف الخفيف","1 ملعقة صغيرة قشر ليمون مبشور","10 مكعبات ثلج"],
["اترك اللوز والحليب وقشر الليمون حتى تغلي في قدر متوسط على نار متوسطة. اطهِها لمدة 5 دقائق، ثم ارفعها عن النار.","انقل خليط اللوز إلى الخلاط. أزل الفتحة الوسطى من الغطاء، وضع منشفة فوق الفتحة، واخلط خليط اللوز حتى يصبح ناعمًا.","أضف رحيق الأغاف ومكعبات الثلج. اخلط حتى يصبح ناعمًا، واخفق حتى يصبح رغويًا. برّده في أكواب شفافة لمدة ساعة (1 ساعة) أو حتى يبرد، ثم قدّمه.".replace("لمدة ساعة (1 ساعة)","لمدة 1 ساعة")])}))
R.append((6194651,{
"es":L("Ensalada de pollo a la parrilla con nueces pecanas caramelizadas","A veces simplemente se me antoja una ensalada sencilla de hojas verdes con el crujido de las nueces, el toque ácido de la fruta seca y un poco de pollo a la parrilla por encima. Esta es. Cúbrala con Vinagreta de tres cítricos.","8","1/8 de la receta",
["1 rocío (0.25 g) de aceite de oliva en aerosol","1/4 taza de nueces pecanas (picadas)","1 cucharadita de azúcar","1/8 cucharadita de pimienta de cayena (molida)","10 tazas de hojas verdes frescas para ensalada","3/4 taza de Vinagreta de tres cítricos (enlace a la receta en la descripción)","2 naranjas navel medianas (peladas y en gajos)","1/4 taza de arándanos rojos secos o chabacanos (albaricoques) secos","2 libras de pechugas de pollo (a la parrilla)"],
["Caliente a fuego medio-bajo un sartén antiadherente pequeño rociado con aceite en aerosol. Agregue las nueces pecanas y cocine de 3 a 4 minutos o hasta que estén ligeramente tostadas, revolviendo con frecuencia. Espolvoree con el azúcar y la pimienta roja, y cocine durante 1 minuto, revolviendo constantemente. Retire las nueces del sartén. Deje enfriar sobre papel encerado.","Combine las hojas verdes, la vinagreta de tres cítricos y los gajos de naranja en un tazón grande. Mezcle bien. Coloque 1 taza de la mezcla de hojas verdes en cada uno de los 8 platos. Cubra cada porción con 1 1/2 cucharaditas de nueces pecanas y 1 1/2 cucharaditas de arándanos rojos secos.","Cubra con la pechuga de pollo a la parrilla y sirva de inmediato."]),
"ar":L("سلطة الدجاج المشوي مع البيكان المكرمل","أحيانًا أشتهي ببساطة سلطة خضار ورقية بسيطة مع قرمشة المكسرات ولذعة الفاكهة المجففة وقليل من الدجاج المشوي فوقها. هذه هي. غطِّها بصلصة الفينيجريت بثلاثة أنواع من الحمضيات.","8","⅛ الوصفة",
["1 بخّة (0.25 غرام) بخاخ طهي بزيت الزيتون","¼ كوب بيكان (مفروم)","1 ملعقة صغيرة سكر","⅛ ملعقة صغيرة فلفل كايين (مطحون)","10 كوب خضار ورقية طازجة للسلطة","¾ كوب صلصة الفينيجريت بثلاثة أنواع من الحمضيات (رابط الوصفة في الوصف)","2 حبة برتقال سرة متوسطة (مقشرة ومقسّمة إلى فصوص)","¼ كوب توت بري مجفف أو مشمش مجفف","2 رطل صدور دجاج (مشوية)"],
["سخّن مقلاة صغيرة غير لاصقة مرشوشة ببخاخ الطهي على نار متوسطة إلى منخفضة. أضف البيكان واطهِه لمدة 3–4 دقائق أو حتى يحمّر قليلًا مع التحريك المتكرر. رشّ عليه السكر والفلفل الأحمر، واطهِه لمدة 1 دقيقة مع التحريك المستمر. أخرج البيكان من المقلاة. اتركه يبرد على ورق شمعي.","اخلط الخضار الورقية وصلصة الفينيجريت بثلاثة أنواع من الحمضيات وفصوص البرتقال في وعاء كبير. قلّب جيدًا. ضع 1 كوب من خليط الخضار في كل طبق من 8 أطباق. غطِّ كل حصة بـ1½ ملعقة صغيرة من البيكان و1½ ملعقة صغيرة من التوت البري المجفف.","غطِّها بصدر الدجاج المشوي وقدّمها فورًا."])}))
R.append((6194859,{
"ar":L("تتبيلة السلطة بالجبن الأزرق قليلة الصوديوم","تتبيلة الجبن الأزرق قليلة الصوديوم هذه كريمية ولاذعة وسهلة التحضير في المنزل. جرّبها على السلطات، أو كغموس للخضار، أو رشّها على أطباقك المفضلة لإضافة نكهة لذيذة.","14","1 ملعقة كبيرة",
["¼ كوب لبن رائب قليل الدسم (بتر ميلك)","¼ كوب زبادي يوناني سادة خالٍ من الدسم","1 فص ثوم (مهروس أو مبشور)","¼ كوب مايونيز خفيف","2 ملعقة كبيرة جبن أزرق (مفتت)","¼ ملعقة صغيرة فلفل أسود"],
["في وعاء صغير، اخفق المايونيز والزبادي اليوناني واللبن الرائب والثوم والجبن الأزرق والفلفل الأسود معًا."])}))
R.append((6195793,{
"es":L("Panqueques de plátano altos en proteína","El yogur griego añade proteína extra a estos panqueques de plátano aptos para personas con diabetes. La avena consistente y una pizca de canela aportan profundidad de sabor a un desayuno que le dará energía durante toda la mañana.","3","2 panqueques",
["3/4 taza de avena tradicional en hojuelas","1 porción de proteína en polvo (suero de leche, sabor vainilla)","1 plátano (banana) mediano (maduro, pequeño)","2 huevos grandes","1/2 taza de yogur griego natural sin grasa","1 cucharadita de polvo de hornear","1/2 cucharadita de canela molida","1/4 cucharadita de extracto de vainilla","1/8 cucharadita de sal kosher","1 rocío (0.25 g) de aceite en aerosol antiadherente"],
["En una licuadora o procesador de alimentos, combine la avena, la proteína en polvo, el plátano, los huevos, el yogur griego, el polvo de hornear, la canela, el extracto de vainilla y la sal. Licúe hasta que quede suave.","Deje reposar la masa unos minutos para que espese ligeramente.","Caliente un sartén antiadherente o una plancha a fuego medio y rocíe ligeramente con aceite en aerosol.","Vierta porciones de 1/4 taza de masa sobre el sartén para formar panqueques pequeños.","Cocine de 2 a 3 minutos por un lado o hasta que se formen burbujas en la superficie.","Voltee los panqueques y cocine de 1 a 2 minutos más, hasta que estén dorados.","Repita hasta usar toda la masa."]),
"ar":L("بانكيك الموز عالي البروتين","يضيف الزبادي اليوناني مزيدًا من البروتين إلى بانكيك الموز هذا المناسب لمرضى السكري. ويضيف الشوفان المشبع ولمسة من القرفة عمقًا في النكهة لإفطار يمنحك الطاقة طوال الصباح.","3","2 بانكيك",
["¾ كوب شوفان مجروش تقليدي","1 مسحوق بروتين (مصل اللبن، بنكهة الفانيليا)","1 حبة موز متوسطة (ناضجة، صغيرة)","2 بيضة كبيرة","½ كوب زبادي يوناني سادة خالٍ من الدسم","1 ملعقة صغيرة بيكنج باودر","½ ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة مستخلص الفانيليا","⅛ ملعقة صغيرة ملح كوشر","1 بخّة (0.25 غرام) بخاخ الطهي غير اللاصق"],
["في الخلاط أو محضّرة الطعام، اخلط الشوفان ومسحوق البروتين والموز والبيض والزبادي اليوناني والبيكنج باودر والقرفة ومستخلص الفانيليا والملح. اخلط حتى يصبح الخليط ناعمًا.","اترك الخليط لبضع دقائق ليثخن قليلًا.","سخّن مقلاة غير لاصقة أو صاجًا على نار متوسطة ورشّه رشًا خفيفًا ببخاخ الطهي.","اسكب الخليط بمقدار ¼ كوب في المقلاة لتشكيل بانكيك صغير.","اطهِ لمدة 2–3 دقائق على جانب واحد أو حتى تظهر فقاعات على السطح.","اقلب البانكيك واطهِ 1–2 دقيقة إضافية حتى يصبح ذهبيًا.","كرر العملية حتى ينتهي الخليط."])}))
save(4,R)
