from h import *
R=[]
R.append((6837569,{
"es":L("Pavo y verduras asados en una sola bandeja","¡La cena no puede ser más fácil que esto! Toda esta comida se prepara en una sola bandeja para hornear y está lista en menos de 30 minutos. Es una comida perfecta para entre semana, baja en carbohidratos y llena de verduras. Encuentre esta receta y más en nuestro libro de cocina Guilt-Free Comfort Favorites, de la Cocina de Pruebas de Mr. Food.","6","3 oz de pavo con 1 taza de verduras",
["3 cucharadas de aceite de oliva","1 cucharada de jugo de limón (de 1/2 limón mediano)","3 ramitas de romero fresco (sin tallos, picado)","1 cucharadita de ajo en polvo","1 cucharadita de pimentón","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","1 1/4 libras de lomo de pavo deshuesado (cortado por la mitad)","2 pimientos medianos (1 rojo y 1 amarillo, cortados en trozos de 2 pulgadas)","1 calabacita mediana (cortada en trozos de 1 pulgada)","1 taza de champiñones blancos (cortados por la mitad)","1/2 cebolla morada mediana (cortada en trozos de 1 pulgada)","1/2 limón mediano"],
["Precaliente el horno a 400 grados F.","En un tazón grande, mezcle el aceite, el jugo de 1/2 limón, el romero, el ajo en polvo, el pimentón, la sal y la pimienta negra; mezcle bien. Agregue el pavo y revuelva hasta que quede cubierto de manera uniforme. Colóquelo en una bandeja para hornear. Agregue los pimientos, la calabacita, los champiñones y la cebolla a la mezcla de aceite y revuelva hasta que queden cubiertos de manera uniforme. Coloque las verduras y las mitades de limón en la bandeja para hornear.","Ase de 25 a 30 minutos o hasta que el pavo ya no tenga color rosado y las verduras estén tiernas. Con unas pinzas, exprima las mitades de limón asadas sobre el pavo y las verduras y sirva de inmediato."]),
"ar":L("ديك رومي وخضار مشوية في صينية واحدة","لا يمكن أن يكون العشاء أسهل من هذا! تُحضَّر هذه الوجبة كاملة في صينية خبز واحدة وتكون جاهزة في أقل من 30 دقيقة. إنها وجبة مثالية لأيام الأسبوع، وهي قليلة الكربوهيدرات وغنية بالخضار! ستجد هذه الوصفة والمزيد في كتاب الطبخ الخاص بنا Guilt-Free Comfort Favorites من مطبخ اختبار Mr. Food.","6","3 أونصات ديك رومي مع 1 كوب خضار",
["3 ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة عصير ليمون (من ½ ليمونة متوسطة)","3 أغصان إكليل الجبل طازج (تُنزع السيقان ويُفرم)","1 ملعقة صغيرة ثوم مجفف مطحون","1 ملعقة صغيرة بابريكا","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1¼ رطل شرائح صدر ديك رومي خالية من العظم (مقطّعة إلى نصفين)","2 حبة فلفل رومي متوسطة (1 أحمر و1 أصفر، مقطّعة إلى قطع بحجم 2 بوصة)","1 حبة كوسا متوسطة (مقطّعة إلى قطع بحجم 1 بوصة)","1 كوب فطر أبيض (فطر الأزرار) (مقطّع إلى نصفين)","½ حبة بصل أحمر متوسطة (مقطّعة إلى قطع بحجم 1 بوصة)","½ ليمونة متوسطة"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية).","في وعاء كبير، اخلط الزيت وعصير ½ ليمونة والإكليل والثوم المجفف المطحون والبابريكا والملح والفلفل الأسود؛ واخلط جيدًا. أضف الديك الرومي وقلّبه حتى يتغطى بالتساوي. ضعه على صينية خبز. أضف الفلفل الرومي والكوسا والفطر والبصل إلى خليط الزيت وقلّبها حتى تتغطى بالتساوي. ضع الخضار ونصفي الليمونة على صينية الخبز.","اشوِ لمدة 25 إلى 30 دقيقة أو حتى يختفي اللون الوردي من الديك الرومي وتنضج الخضار. باستخدام ملقط، اعصر نصفي الليمونة المشويين فوق الديك الرومي والخضار وقدّمه فورًا."])}))
R.append((6837664,{
"es":L("Ratatouille en olla de cocción lenta con frijoles blancos","Esta versión del ratatouille apta para personas con diabetes incorpora frijoles blancos para aumentar la proteína. Aunque tradicionalmente se cocina en la estufa, esta versión moderna le permite usar una olla de cocción lenta, para que pueda presionar un botón y continuar con su día. Complete su plato: sírvalo con una sencilla ensalada griega de acompañamiento con vinagreta de vino tinto para una comida de origen vegetal, baja en carbohidratos y llena de verduras. Encuentre esta receta y más en The Create-Your-Plate Diabetes Cookbook, de Toby Amidor, MS, RD, CDN, FAND","6","1 1/2 tazas",
["1 cucharada de aceite de oliva","2 latas (15 onzas) de frijoles great northern o cannellini bajos en sodio (escurridos y enjuagados)","1 lata (14.5 onzas) de tomates picados asados al fuego sin sal añadida","1 taza de salsa de tomate baja en sodio","1 1/2 tazas de caldo de verduras bajo en sodio","1/2 berenjena mediana (en cubos, con piel)","2 tazas de repollo verde rallado","1 pimiento rojo entero (cortado en tiras de 1 pulgada)","3 dientes de ajo (picados)","2 cucharadas de vinagre de manzana","1 cucharadita de orégano seco","3 hojas de laurel","1/4 cucharadita más 1/8 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Unte el interior de la olla de cocción lenta con el aceite de oliva. Agregue los demás ingredientes a la olla de cocción lenta; revuelva para combinar.","Tape y cocine a temperatura baja durante 6 horas, hasta que las verduras y los frijoles se ablanden. Retire y deseche las hojas de laurel antes de servir."]),
"ar":L("راتاتوي في الطنجرة البطيئة مع الفاصولياء البيضاء","هذه النسخة من الراتاتوي المناسبة لمرضى السكري تضيف الفاصولياء البيضاء لزيادة البروتين. وبينما تُطهى عادةً على الموقد، تتيح لك هذه النسخة العصرية استخدام الطنجرة البطيئة، فتضغط زرًّا وتمضي في يومك. أكمِل طبقك: قدّمه مع سلطة يونانية جانبية بسيطة بصلصة خل النبيذ الأحمر لوجبة نباتية قليلة الكربوهيدرات وغنية بالخضار. ستجد هذه الوصفة والمزيد في كتاب The Create-Your-Plate Diabetes Cookbook من تأليف Toby Amidor, MS, RD, CDN, FAND","6","1½ كوب",
["1 ملعقة كبيرة زيت زيتون","2 علبة (15 أونصة) فاصولياء غريت نورذرن أو كانيليني قليلة الصوديوم (مصفّاة ومغسولة)","1 علبة (14.5 أونصة) طماطم مقطّعة مشوية على النار بدون ملح مضاف","1 كوب صلصة طماطم قليلة الصوديوم","1½ كوب مرق خضار قليل الصوديوم","½ حبة باذنجان متوسطة (مقطّعة مكعبات بقشرها)","2 كوب ملفوف أخضر مبشور","1 حبة فلفل رومي أحمر كاملة (مقطّعة إلى شرائح بعرض 1 بوصة)","3 فص ثوم (مفروم)","2 ملعقة كبيرة خل التفاح","1 ملعقة صغيرة أوريجانو مجفف","3 ورقة غار","¼ ملعقة صغيرة زائد ⅛ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["ادهن الجزء الداخلي من الطنجرة البطيئة بزيت الزيتون. أضف بقية المكونات إلى الطنجرة البطيئة؛ وحرّك للمزج.","غطِّها واطهُ على درجة حرارة منخفضة لمدة 6 ساعات، حتى تلين الخضار والفاصولياء. أخرج أوراق الغار وتخلّص منها قبل التقديم."])}))
R.append((6837683,{
"es":L("Guacamole brasileño","Con tantos colores y sabores bailando juntos, ¡este guacamole es una fiesta en la lengua! Úselo como salsa para mojar verduras frescas o totopos, o agréguelo a sándwiches y wraps. Está delicioso el día que lo prepara y mejora aún más al día siguiente, cuando todos los sabores se mezclan. El resultado es refrescante y muy satisfactorio.","13","1/4 taza",
["1/2 taza de aceite de oliva","2 aguacates Hass medianos (maduros)","1/4 taza de cilantro fresco (picado)","1/4 taza de perejil fresco (picado)","1 cucharada de salsa de soya baja en sodio","1/2 cucharadita de pimienta negra","1/2 cucharadita de sal","1 tomate roma mediano (sin semillas y finamente picado)","1/2 pepino inglés (pelado, sin semillas y finamente picado)","1/2 pimiento amarillo mediano (finamente picado)","1/2 pimiento rojo mediano (finamente picado)","1 tallo de cebollín (cebolla de cambray) (picado)","1 diente de ajo (finamente picado)"],
["Refrigere por al menos 3 horas para que se desarrollen los sabores, pero sáquelo del refrigerador al menos 20 minutos antes de servir. Consejo del chef: corte la otra mitad de los pimientos y del pepino en bastones para servir con el guacamole y mojar","Corte los aguacates por la mitad, quíteles el hueso y saque la pulpa de la cáscara. Pique o machaque el aguacate y agréguelo a las verduras. Agregue lentamente el aceite de oliva y mezcle todo con movimientos envolventes.","Combine el ajo, los cebollines, la cebolla morada, los pimientos, el pepino y el tomate y mezcle bien. Sazone con la salsa de soya, la sal y la pimienta, el perejil y el cilantro, y mezcle con movimientos envolventes."]),
"ar":L("غواكامولي برازيلي","مع كل هذه الألوان والنكهات الراقصة معًا، هذا الغواكامولي حفلة على لسانك! استخدمه غموسًا للخضار الطازجة أو رقائق التورتيلا، أو أضفه إلى السندويشات واللفائف. مذاقه لذيذ في يوم تحضيره ويزداد روعة في اليوم التالي عندما تمتزج النكهات كلها. والنتيجة منعشة ومُرضية جدًا.","13","¼ كوب",
["½ كوب زيت زيتون","2 حبة أفوكادو هاس متوسطة (ناضجة)","¼ كوب كزبرة خضراء طازجة (مفرومة)","¼ كوب بقدونس طازج (مفروم)","1 ملعقة كبيرة صلصة صويا قليلة الصوديوم","½ ملعقة صغيرة فلفل أسود","½ ملعقة صغيرة ملح","1 حبة طماطم روما متوسطة (منزوعة البذور ومقطّعة مكعبات صغيرة)","½ حبة خيار إنجليزي (مقشّرة ومنزوعة البذور ومقطّعة مكعبات صغيرة)","½ حبة فلفل رومي أصفر متوسطة (مقطّعة مكعبات صغيرة)","½ حبة فلفل رومي أحمر متوسطة (مقطّعة مكعبات صغيرة)","1 ساق بصل أخضر (مفرومة)","1 فص ثوم (مفروم ناعمًا جدًا)"],
["ضعه في الثلاجة لمدة 3 ساعات على الأقل لتتكوّن النكهات، ثم أخرجه من الثلاجة قبل التقديم بـ 20 دقيقة على الأقل. نصيحة الطاهي: قطّع النصف الآخر من حبات الفلفل الرومي والخيار إلى أعواد لتقديمها مع الغواكامولي للغمس","اقطع حبتي الأفوكادو إلى نصفين، وانزع النوى واغرف اللب من القشور. قطّع الأفوكادو إلى مكعبات أو اهرسه وأضفه إلى الخضار. أضف زيت الزيتون ببطء وقلّب كل شيء برفق.","اخلط الثوم والبصل الأخضر والبصل الأحمر والفلفل الرومي والخيار والطماطم وقلّبها جيدًا. تبّلها بصلصة الصويا والملح والفلفل والبقدونس والكزبرة الخضراء وقلّب برفق."])}))
R.append((6838915,{
"ar":L("لفائف الخس بالروبيان","إذا لم تستخدم كل خليط الروبيان في هذه الوصفة، يمكنك أيضًا الاستمتاع به باردًا في لفافة خس على الغداء في اليوم التالي.","7","1 لفافة",
["1 رشة، 0.25 غرام رذاذ طهي غير لاصق","1 ملعقة صغيرة زيت سمسم","1 حبة فلفل رومي أحمر متوسطة (منزوعة البذور ومقطّعة مكعبات صغيرة)","1 حبة بصل صغيرة (مقطّعة مكعبات صغيرة)","1 رطل روبيان (مقشّر ومنزوع الأمعاء)","1 ملعقة كبيرة صلصة صويا (منخفضة الصوديوم)","1 ملعقة كبيرة بديل سكر بني قليل السعرات","1 ملعقة صغيرة معجون الفلفل الحار والثوم على الطريقة التايلاندية","1 ملعقة صغيرة زنجبيل طازج (مبشور)","1 فص ثوم (مفروم)","2 ملعقة كبيرة عصير ليمون أخضر طازج","2 ملعقة صغيرة قشر ليمون أخضر مبشور","¼ كوب مرق دجاج قليل الصوديوم (خالٍ من الدسم)","1 ملعقة كبيرة زبدة فول سوداني (بدون سكر مضاف)","1 ملعقة كبيرة ثوم معمر (شيفز) طازج (مفروم)","7 ورقات خس بوسطن كبيرة","½ حبة أفوكادو متوسطة (مقطّعة مكعبات)"],
["أضف رذاذ الطهي وزيت السمسم إلى مقلاة متوسطة على نار متوسطة إلى عالية.","أضف الفلفل الرومي والبصل وقلّبهما حتى تلين الخضار ويصبح البصل شفافًا.","أضف الروبيان وقلّبه لمدة 2-3 دقائق، أو حتى ينضج الروبيان جزئيًا.","في وعاء صغير، اخفق صلصة الصويا وبديل السكر البني ومعجون الفلفل الحار والثوم والزنجبيل والثوم وقشر الليمون الأخضر وعصير الليمون الأخضر ومرق الدجاج وزبدة الفول السوداني. اسكبه فوق الروبيان واتركه على نار هادئة حتى تبدأ الصلصة بالثخانة وينضج الروبيان.","أضف الثوم المعمر المفروم وحرّك.","ضع ¼ كوب من خليط الروبيان في كوب من ورقة خس وزيّنه بالأفوكادو المقطّع. كرّر ذلك مع اللفائف الـ 6 المتبقية، مع توزيع الأفوكادو بالتساوي على اللفائف الـ 7."])}))
R.append((6840128,{
"ar":L("\"سندويش\" البطاطا الحلوة المفتوح","يمكنك استخدام هذه الطريقة مع أي حشوة سندويش. جرّب شرائح الطماطم والريحان وجبن الموزاريلا الطازج، أو جرّب لحم الخنزير المدخن (هام) مع السبانخ وجبن مونستر.","4","1 سندويش",
["1 حبة فلفل رومي أحمر متوسطة (منزوعة البذور ومقطّعة شرائح رفيعة)","2 شريحة جبن سويسري (1 أونصة لكل منها، قليل الدسم)","1 ملعقة صغيرة توابل خالية من الملح (مثل Mrs. Dash)","1 حبة كوسا صغيرة (مقطّعة شرائح رفيعة بالطول)","2 حبة بطاطا حلوة متوسطة","1 رشة، 0.25 غرام رذاذ طهي غير لاصق"],
["سخّن الفرن مسبقًا إلى 450 درجة فهرنهايت (230° مئوية). ادهن صينية خبز برذاذ الطهي وضعها جانبًا.","قطّع أحد الأطراف المستديرة من البطاطا الحلوة إلى شريحة رقيقة بالطول. ثم قطّع الطرف المستدير الآخر منها إلى شريحة رقيقة بالطول. تخلّص من هاتين الشريحتين.","قطّع البطاطا الحلوة من المنتصف بالطول وقشّرها. كرّر ذلك مع حبة البطاطا الحلوة الأخرى. ستحصل في النهاية على 4 شرائح من البطاطا الحلوة بسمك 1 بوصة مقطّعة بالطول.","ضعها على صينية الخبز المجهزة ورشّ وجوه البطاطا الحلوة برذاذ الطهي. اخبز البطاطا الحلوة لمدة 10 دقائق، ثم خفّض الحرارة إلى 350 درجة فهرنهايت (175° مئوية).","اقلب البطاطا الحلوة ثم ضع كميات متساوية من شرائح الكوسا والفلفل الرومي الأحمر الرقيقة على كل قطعة بطاطا حلوة. تبّلها بالتوابل الخالية من الملح.","قطّع كل شريحة جبن سويسري إلى نصفين وضع الجبن السويسري فوق كل قطعة بطاطا حلوة. أعد البطاطا إلى الفرن لمدة 15 دقيقة أخرى.","قدّمها فورًا."])}))
R.append((6840452,{
"es":L("Coliflor entera asada con vinagreta de limón","Una coliflor entera asada es un centro de mesa impresionante para una comida de origen vegetal. Esta estrella baja en carbohidratos vale la pena por el tiempo de cocción: sabe tan bien como se ve, y la preparación es rápida y sencilla.","8","1/2 taza",
["4 cucharadas de aceite de oliva (dividido)","1/2 cucharadita de sal","1 cabeza entera de coliflor (de aproximadamente 2 1/2 libras) (sin hojas ni tallo)","1 cucharada de jugo de limón (de 1/2 limón mediano)","1/2 cucharadita de perejil seco","1/8 cucharadita de pimienta negra"],
["Precaliente el horno a 425° F.","En un tazón pequeño, mezcle 2 cucharadas del aceite de oliva y la sal. Coloque la coliflor, con el lado cortado hacia abajo, en una fuente grande para hornear. Vierta el aceite de oliva de manera uniforme sobre la coliflor y use las manos para frotar la mezcla de aceite y sal en la coliflor.","Colóquela en la rejilla central del horno y ase durante 1 hora (si la coliflor empieza a oscurecerse demasiado, cúbrala con papel aluminio).","Mientras se asa la coliflor, bata en un tazón pequeño el jugo de limón, las 2 cucharadas restantes de aceite de oliva, el perejil y la pimienta negra.","Cuando la coliflor termine de asarse, vierta la vinagreta de manera uniforme sobre toda la cabeza.","Para servir, corte la coliflor entera por la mitad y luego corte cada mitad en 4 trozos."]),
"ar":L("القرنبيط المشوي كاملًا مع صلصة الليمون","القرنبيط المشوي كاملًا قطعة مركزية مبهرة على مائدة وجبة نباتية. هذا الطبق الرائع القليل الكربوهيدرات يستحق وقت الطهي؛ فمذاقه رائع كمظهره، وتحضيره سريع وسهل.","8","½ كوب",
["4 ملعقة كبيرة زيت زيتون (مقسّمة)","½ ملعقة صغيرة ملح","1 رأس كامل (نحو 2½ رطل) قرنبيط (مقطوعة الأوراق والساق)","1 ملعقة كبيرة عصير ليمون (من ½ ليمونة متوسطة)","½ ملعقة صغيرة بقدونس مجفف","⅛ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية).","في وعاء صغير، اخلط 2 ملعقة كبيرة من زيت الزيتون مع الملح. ضع القرنبيط وجهه المقطوع إلى الأسفل في طبق خبز كبير. اسكب زيت الزيتون بالتساوي فوق القرنبيط واستخدم يديك لتدليك القرنبيط بخليط الزيت والملح.","ضعه على رف الفرن الأوسط واشوِه لمدة 1 ساعة (وإذا بدأ القرنبيط يغمق لونه كثيرًا فغطِّه بورق الألمنيوم).","بينما يُشوى القرنبيط، اخفق في وعاء صغير عصير الليمون و2 ملعقة كبيرة المتبقية من زيت الزيتون والبقدونس والفلفل الأسود.","عندما ينتهي شيّ القرنبيط، اسكب الصلصة بالتساوي فوق الرأس كله.","للتقديم، اقطع القرنبيط كاملًا إلى نصفين، ثم اقطع كل نصف إلى 4 قطع."])}))
R.append((6841339,{
"es":L("Salmón de Alaska con naranja y berros","Este sabroso platillo de salmón del Alaska Seafood Marketing Institute está lleno de grasas saludables, junto con una serie de toques nutritivos y decorativos que logran una presentación espectacular. ¡Es un platillo rápido y fácil que además está pensado para impresionar!","8","1/2 filete + 1 taza de cobertura",
["4 filetes de salmón de Alaska congelado (6 onzas cada uno)","4 cucharadas de aceite de aguacate (dividido)","1/8 cucharadita de sal","1/8 cucharadita de pimienta negra","2 manojos (aproximadamente 3 tazas) de berros (picados toscamente)","3 cucharadas de pepino (finamente picado)","2 naranjas medianas (peladas y en gajos (sin membrana))","2 tazas de hojas verdes mixtas","1/2 aguacate mediano (sin hueso, pelado y en rebanadas)","1/4 taza de nueces","2 cucharadas de vinagre de manzana","1/8 cucharadita de pimentón ahumado (para terminar)","4 flores comestibles, como capuchinas (opcional)"],
["Enjuague bajo agua fría la capa de hielo del salmón de Alaska congelado; séquelo con toallas de papel. Caliente un sartén a fuego medio-alto y unte ambos lados del pescado con 3 cucharadas de aceite de aguacate. Cocine el salmón, sin tapar, unos 4 minutos, hasta que esté dorado.","Voltee el salmón y sazone ligeramente con 1/8 cucharadita de sal y de pimienta. Cocine de 6 a 8 minutos adicionales si está congelado, o de 3 a 4 minutos si está fresco o descongelado, solo hasta que el pescado esté opaco por completo.","Mientras tanto, en un tazón mediano combine los berros, el pepino y los gajos de naranja.","En un tazón pequeño, combine el aceite de aguacate restante, el vinagre de manzana y 1/8 cucharadita de sal y de pimienta.","Sirva las hojas verdes mixtas junto al salmón y cubra con el aguacate, las nueces y la vinagreta de vinagre de manzana. Agregue las capuchinas, si lo desea, y sirva."]),
"ar":L("سلمون ألاسكا بالبرتقال والجرجير المائي","طبق السلمون اللذيذ هذا من معهد ألاسكا لتسويق المأكولات البحرية غني بالدهون الصحية، إلى جانب عدد من اللمسات المغذية والزخرفية التي تمنحه تقديمًا مذهلًا. إنه طبق سريع وسهل ومصمَّم أيضًا لإثارة الإعجاب!","8","½ شريحة + 1 كوب من الطبقة العلوية",
["4 شرائح سلمون ألاسكا مجمّد (6 أونصات لكل منها)","4 ملعقة كبيرة زيت أفوكادو (مقسّم)","⅛ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود","2 حزمة (نحو 3 كوب) جرجير مائي (مفروم خشنًا)","3 ملعقة كبيرة خيار (مفروم ناعمًا)","2 حبة برتقال متوسطة (مقشّرة ومقسّمة إلى فصوص (بدون الأغشية))","2 كوب خضار ورقية مشكّلة","½ حبة أفوكادو متوسطة (منزوعة النواة ومقشّرة ومقطّعة شرائح)","¼ كوب جوز","2 ملعقة كبيرة خل التفاح","⅛ ملعقة صغيرة بيمنتون (بابريكا مدخنة) (للتزيين النهائي)","4 أزهار صالحة للأكل، مثل زهور أبو خنجر (اختياري)"],
["اشطف أي طبقة جليد عن سلمون ألاسكا المجمّد بالماء البارد؛ وجفّفه بمنشفة ورقية. سخّن مقلاة على نار متوسطة إلى عالية وادهن جانبي السمك بـ 3 ملاعق كبيرة من زيت الأفوكادو. اطهُ السلمون دون غطاء نحو 4 دقائق، حتى يتحمّر.","اقلب السلمون وتبّله برفق بـ ⅛ ملعقة صغيرة من الملح ومثلها من الفلفل. اطهُه 6 إلى 8 دقائق إضافية إن كان مجمّدًا، أو 3 إلى 4 دقائق إن كان طازجًا أو مذابًا، فقط حتى يصبح السمك معتمًا بالكامل.","في هذه الأثناء، اخلط في وعاء متوسط الجرجير المائي والخيار وفصوص البرتقال.","في وعاء صغير، اخلط بقية زيت الأفوكادو وخل التفاح و⅛ ملعقة صغيرة من الملح ومثلها من الفلفل.","ضع الخضار الورقية المشكّلة بجانب السلمون وزيّنها بالأفوكادو والجوز وصلصة خل التفاح. أضف أزهار أبو خنجر إن رغبت وقدّمه."])}))
R.append((6841530,{
"ar":L("سلطة الشمندر والجرجير مع جبن الفيتا","لم تطهُ الشمندر من قبل؟ هذه الوصفة السريعة والسهلة بداية رائعة. الشمندر المشوي والجرجير وجبن الفيتا يشكّلون مزيجًا لذيذًا من النكهات!","2","1 كوب (مكبوس)",
["2 حبة شمندر متوسطة (مقطوعة الأطراف ومقشّرة، تُقطّع كل منها إلى ثمانية أجزاء)","3 ملعقة صغيرة زيت زيتون (مقسّمة)","⅛ ملعقة صغيرة فلفل","½ ملعقة صغيرة خل النبيذ الأبيض","¼ ملعقة صغيرة خردل ديجون","1½ أونصة جرجير (مكبوس نحو 1½ كوب)","3 ملعقة كبيرة جبن فيتا (خالٍ من الدسم، مفتّت)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية).","ضع الشمندر في طبقة واحدة على صينية خبز ذات حواف. رشّ الشمندر بـ 1 ملعقة صغيرة من الزيت. رشّ الفلفل فوق الشمندر.","اشوِه لمدة 20-25 دقيقة، أو حتى يلين عند غرزه بالشوكة. اتركه يبرد على الصينية 10 دقائق.","في هذه الأثناء، في وعاء كبير، اخفق بقية الزيت (2 ملعقة صغيرة) والخل والخردل. أضف الجرجير وقلّب الأوراق في الصلصة (الملقط مناسب جدًا لذلك). أضف الشمندر المبرد. رشّ جبن الفيتا فوقه. قلّب للمزج.","نصيحة الطاهي: تنصح معظم الوصفات بشيّ الشمندر كاملًا ثم تقشيره بعد الطهي. ولتقليل وقت الطهي كثيرًا، قشّره نيئًا (تصلح مقشرة الخضار لذلك) وقطّعه إلى أرباع أو أثمان قبل الشيّ. قد يلطّخ الشمندر الملابس، لذا قد ترغب في ارتداء مئزر وقفازين بلاستيكيين يُستخدمان مرة واحدة قبل التعامل مع الشمندر."])}))
R.append((6843906,{
"es":L("Paella de mariscos con quinoa","La autora y chef famosa Ingrid Hoffman dice: \"Mis disculpas a España, pero me encanta esta versión de la paella más que la original; la quinoa parece absorber más el sabor que el arroz o el arroz bomba que se usa en el platillo clásico español. Me parece que la paella es un platillo tan fácil y hermoso para presentar cuando se sirve a varias personas. Un ingrediente clave es el azafrán. Uso azafrán persa (iraní), que compro por internet, porque lo prefiero a las versiones comerciales que se encuentran en el supermercado. Tiene tanto sabor que un poco rinde mucho. Lo guardo molido en mi refrigerador y lo uso en guisos, sopas, arroz, verduras, etc.\". Para obtener esta receta en español, haga clic aquí.","8","1 taza",
["1 cucharada de aceite de oliva extra virgen","1 cebolla mediana (finamente picada)","1 pimiento rojo mediano (en rebanadas finas)","1 pimiento verde mediano (en rebanadas finas)","4 dientes de ajo (picados)","1 cucharada de pasta de tomate","1 cucharadita de hebras de azafrán español","1 taza de quinoa cruda (enjuagada)","2 tazas de caldo de pollo bajo en sodio","1 lata (10 onzas) de tomates picados en lata","1/4 cucharadita de sal kosher","1 libra (aproximadamente 30) de camarones grandes silvestres, nunca congelados, pelados y desvenados","1 libra de anillos de calamar","3 cucharadas de perejil de hoja plana (picado)","1 limón mediano (cortado en 8 gajos)"],
["Caliente el aceite en un sartén antiadherente grande o en una paellera a fuego medio-alto. Agregue la cebolla, los pimientos y el ajo, y cocine, revolviendo de vez en cuando, hasta que las verduras estén tiernas, aproximadamente 8 minutos.","Agregue la pasta de tomate y el azafrán al sartén, revolviendo hasta que estén bien mezclados. Agregue la quinoa, el caldo, los tomates y la sal; lleve a ebullición. Reduzca el fuego a medio-bajo. Tape y cocine a fuego lento hasta que se absorba el líquido y la quinoa esté tierna, aproximadamente 20 minutos.","Introduzca los camarones y los calamares en la mezcla de quinoa. Tape y cocine hasta que los camarones y los calamares estén bien cocidos, aproximadamente 5 minutos. Retire del fuego; espolvoree con el perejil y decore con los gajos de limón."]),
"ar":L("باييا المأكولات البحرية بالكينوا","تقول المؤلفة والطاهية المشهورة إنغريد هوفمان: \"أعتذر من إسبانيا، لكنني أحب هذه النسخة من الباييا أكثر من الأصلية؛ فيبدو أن الكينوا تمتص النكهة أكثر من الأرز أو أرز بومبا المستخدم في الطبق الإسباني الكلاسيكي. أجد الباييا طبقًا سهلًا وجميلًا للغاية عند تقديمه لعدة أشخاص. من المكونات الأساسية الزعفران. أستخدم الزعفران الفارسي (الإيراني) الذي أشتريه عبر الإنترنت، لأنني أفضّله على النسخ التجارية الموجودة في السوبرماركت. نكهته قوية جدًا، لذا تكفي كمية صغيرة منه. أحفظه مطحونًا في ثلاجتي وأستخدمه في اليخنات والشوربات والأرز والخضار وغيرها\". للحصول على هذه الوصفة بالإسبانية، انقر هنا.","8","1 كوب",
["1 ملعقة كبيرة زيت زيتون بكر ممتاز","1 حبة بصل متوسطة (مفرومة ناعمًا)","1 حبة فلفل رومي أحمر متوسطة (مقطّعة شرائح رفيعة)","1 حبة فلفل رومي أخضر متوسطة (مقطّعة شرائح رفيعة)","4 فص ثوم (مفروم)","1 ملعقة كبيرة معجون طماطم","1 ملعقة صغيرة خيوط زعفران إسباني","1 كوب كينوا غير مطبوخة (مغسولة)","2 كوب مرق دجاج قليل الصوديوم","1 علبة (10 أونصات) طماطم مقطّعة معلّبة","¼ ملعقة صغيرة ملح كوشر","1 رطل (نحو 30 حبة) روبيان كبير بري، لم يُجمَّد قط، مقشّر ومنزوع الأمعاء","1 رطل حلقات كالاماري","3 ملعقة كبيرة بقدونس مفلطح الأوراق (مفروم)","1 ليمونة متوسطة (مقطّعة إلى 8 أسافين)"],
["سخّن الزيت في مقلاة كبيرة غير لاصقة أو مقلاة باييا على نار متوسطة إلى عالية. أضف البصل والفلفل الرومي والثوم، واطهُ مع التحريك من حين لآخر حتى تلين الخضار، نحو 8 دقائق.","أضف معجون الطماطم والزعفران إلى المقلاة وحرّك حتى يمتزجا جيدًا. أضف الكينوا والمرق والطماطم والملح؛ واتركها حتى تغلي. خفّض الحرارة إلى متوسطة منخفضة. غطِّها واتركها على نار هادئة حتى يُمتص السائل وتنضج الكينوا، نحو 20 دقيقة.","ادفن الروبيان والكالاماري في خليط الكينوا. غطِّها واطهُ حتى ينضج الروبيان والكالاماري تمامًا، نحو 5 دقائق. ارفعها عن النار؛ ورشّ البقدونس وزيّنها بأسافين الليمون."])}))
R.append((6844012,{
"es":L("Linaza molida","Información nutricional de la linaza molida","1","1 cucharada",["1 cucharada de linaza molida"],[]),
"ar":L("بذور الكتان المطحونة","المعلومات الغذائية لبذور الكتان المطحونة","1","1 ملعقة كبيرة",["1 ملعقة كبيرة بذور كتان مطحونة"],[])}))
R.append((6844655,{
"ar":L("كيش صغير بالهليون والفلفل بدون عجينة","يمكنك تجميد هذه الكيش الصغيرة بعد خبزها وتبريدها. أعد تسخينها في فرن التوستر أو الميكروويف لتحصل على فطور أو غداء رائع جاهز للحمل!","12","1 كيش صغير",
["1 رذاذ طهي غير لاصق","1 ملعقة كبيرة زيت زيتون","1 حزمة هليون (مقطوعة الأطراف ومقطّعة مكعبات)","1 حبة بصل صغيرة (مقطّعة مكعبات)","1 حبة فلفل رومي أحمر أو أصفر (منزوعة البذور ومقطّعة مكعبات)","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","8 بيضات متوسطة (2 بيضة كاملة و6 بياض بيض)","⅓ كوب حليب خالي الدسم","6 أسافين جبن Laughing Cow Light Original Cheese Wedges (مقسّمة إلى نصفين)"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية).","رشّ صينية المافن برذاذ الطهي.","أضف زيت الزيتون وكمية وفيرة من رذاذ الطهي إلى مقلاة متوسطة. قلّب الهليون والبصل والفلفل الرومي لمدة 7-9 دقائق أو حتى تنضج تمامًا. تبّلها بالملح (اختياري) والفلفل وضعها جانبًا لتبرد قليلًا.","في وعاء متوسط، اخفق البيض وبياض البيض والحليب.","وزّع الخضار المقلّبة بالتساوي على قوالب المافن الـ 12. يجب أن تكون القوالب ممتلئة من ½ إلى ¾. اسكب خليط البيض برفق فوق الخضار في كل قالب مافن، مع التوزيع بالتساوي. يجب أن تكون القوالب ممتلئة لكن دون أن تفيض.","خذ نصفًا من أسفين جبن Lite Laughing Cow Cheese Wedge واضغط عليه برفق في منتصف كل كيش. كرّر ذلك مع الـ 11 كيش المتبقية.","اخبزها لمدة 20 دقيقة. قدّمها فورًا."])}))
R.append((6845135,{
"ar":L("بيتا بالجبن والخضار","وصفة سندويش البيتا النباتية هذه سهلة التحضير لعدد كبير من الأشخاص. كما أنها سهلة التعبئة وحملها إلى العمل فلا تضطر إلى تناول الطعام خارج المنزل وقت الغداء.","8","½ رغيف بيتا",
["1 حبة طماطم كبيرة (مقطّعة إلى 4 شرائح متساوية)","2¼ شريحة جبن سويسري (قليل الدسم)","1 حبة بصل أحمر متوسطة (مقطّعة شرائح رفيعة)","2 ملعقة كبيرة مايونيز خفيف","2 كوب جرجير","¼ كوب بذور دوار الشمس","4 أرغفة بيتا متوسطة من القمح الكامل","½ كوب حمص","1 حبة خيار متوسطة"],
["اقطع جانبًا واحدًا من كل رغيف بيتا لفتح الجيب، لكن دون أن تقطعه بالكامل. ضعها جانبًا.","ادهن ½ ملعقة كبيرة من المايونيز داخل كل رغيف بيتا.","قطّع الجبن السويسري إلى 4 شرائح متساوية. ادهن 2 ملعقة كبيرة من الحمص على كل شريحة جبن ورشّ 1 ملعقة كبيرة من بذور دوار الشمس فوقها.","ضع طبقات من نحو ½ كوب من الجرجير وشرائح البصل وشرائح الطماطم وشرائح الخيار فوق الحمص.","احشُ كل رغيف بيتا بحشوة السندويش وقطّعه إلى نصفين."])}))
save("out_c22_part3.json",R)
