from h import *
R=[]
R.append((6846465,{
"ar":L("تاكو الخضار المشوية الاقتصادي","هل تحاول تناول وجبة خالية من اللحوم وغنية بالخضار مرة في الأسبوع؟ تمنحك هذه الوصفة كل نكهة التاكو لكن مع ألياف وخضار أكثر بكثير. زيّنها بشرائح الأفوكادو لمزيد من النكهة إن رغبت.","8","1 تاكو",
["1 رشة، 0.25 غرام رذاذ طهي غير لاصق","2 حبة كوسا متوسطة (مقطّعة مكعبات صغيرة)","5 حبات جزر متوسطة (مقطّعة مكعبات صغيرة)","1 حبة بصل صغيرة (مقطّعة مكعبات صغيرة)","1 حبة فلفل رومي أحمر متوسطة (مقطّعة مكعبات صغيرة)","1½ ملعقة كبيرة زيت زيتون","1 فص ثوم (مفروم)","1 حبة طماطم متوسطة (منزوعة البذور ومقطّعة مكعبات)","1 كوب فاصولياء سوداء (قليلة الصوديوم، مصفّاة ومغسولة)","1 ملعقة كبيرة + 1 ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","1 ملعقة صغيرة كمون","¼ ملعقة صغيرة فلفل أسود","8 أقراص تورتيلا ذرة كاملة (6 بوصات)","1 كوب خس (مقطّع شرائح)","½ كوب جبن كيسو فريسكو (أو شيدر مبشور قليل الدسم)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية). رشّ صينية خبز برذاذ الطهي.","ضع الكوسا والجزر والبصل والفلفل الأحمر على صينية الخبز. أضف زيت الزيتون والثوم؛ وقلّب ليتغطى. اخبز لمدة 15-18 دقيقة. أخرجه من الفرن.","بينما تُخبز الخضار، سخّن مقلاة متوسطة على نار متوسطة. رشّها برذاذ الطهي. أضف الطماطم وقلّبها لمدة 1 دقيقة. أضف الفاصولياء ومسحوق الفلفل الحار والكمون والفلفل وقلّب لمدة 2 دقيقة. أضف الخضار المطبوخة إلى المقلاة واخلط جيدًا.","ضع ½ كوب من خليط الخضار في كل تاكو وزيّنه بالخس والجبن."])}))
R.append((6849321,{
"ar":L("تفاح محشو بالقرفة مخبوز","يمكن لأطباق الفاكهة مثل التفاح المحشو بالقرفة المخبوز هذا أن تكون حلوى رائعة وصحية. رائحة هذا التفاح وهو يُخبز في الفرن ستجعل فمك يسيل.","8","½ حبة تفاح",
["4 حبة تفاح كبيرة (ماكنتوش أو غولدن ديليشس، منزوعة القلب)","½ ليمونة (معصورة)","6 ملعقة كبيرة بديل سكر بني قليل السعرات","¼ كوب شوفان","1 ملعقة صغيرة قرفة مطحونة","2 ملعقة كبيرة سمن نباتي (مارجرين) (خالٍ من الدهون المتحولة)","¼ كوب بيكان (مفروم ناعمًا)"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية).","رشّ عصير الليمون فوق التفاح.","في وعاء صغير، اخلط بقية المكونات معًا. احشُ كل تفاحة بنحو ¼ كوب من خليط الشوفان.","ضع التفاح في طبق خبز آمن للفرن واخبزه لمدة 25-30 دقيقة."])}))
R.append((6850173,{
"es":L("Magdalenas de huevo tipo suflé con verduras","Ligeras y esponjosas, estas pequeñas magdalenas para el desayuno están llenas de sabor. Son perfectas para una reunión grande o se pueden congelar y recalentar para un desayuno rápido para llevar.","6","3 magdalenas",
["6 huevos grandes (separados)","1/2 taza de requesón bajo en grasa","1/2 taza de zanahorias (en cubos)","1/2 taza de floretes pequeños de brócoli","1/2 taza de col rizada fresca (picada)","1/2 taza de pimiento rojo (pequeño, en cubos)","1/4 taza de cebolla (pequeña, en cubos)","1/2 cucharadita de ajo en polvo","1/4 cucharadita de pimienta negra","1/4 cucharadita de sal kosher"],
["Precaliente el horno a 350° F. Rocíe 2 moldes para magdalenas de 12 cavidades con aceite en aerosol.","Separe las claras de las yemas de los huevos.","En un tazón grande, bata las yemas de huevo y el requesón con una batidora de mano o de pie a velocidad medio-alta hasta que quede cremoso.","En otro tazón grande, bata las claras a punto de nieve hasta que se formen picos firmes.","Mezcle las verduras y las especias con la mezcla de yemas y combine bien.","Incorpore suavemente las claras batidas a la mezcla de yemas y verduras.","Con una cuchara medidora o una cuchara grande, divida la mezcla de huevo de manera uniforme en 18 de los moldecitos.","Coloque los moldes en el horno precalentado y hornee de 25–30 minutos, hasta que estén inflados y dorados por encima.","Retire del horno y deje enfriar durante 5 minutos. Saque las magdalenas de los moldes con cuidado."]),
"ar":L("مافن البيض بالخضار على طريقة السوفليه","هذه المافن الصغيرة للفطور خفيفة وهشّة ومليئة بالنكهة. وهي مثالية للتجمعات الكبيرة، ويمكن تجميدها وإعادة تسخينها لفطور سريع جاهز للحمل.","6","3 كعكات مافن",
["6 بيضات كبيرة (مفصولة)","½ كوب جبن قريش قليل الدسم","½ كوب جزر (مقطّع مكعبات)","½ كوب زهيرات بروكلي صغيرة","½ كوب كرنب أجعد (كيل) طازج (مفروم)","½ كوب فلفل أحمر (صغير، مقطّع مكعبات)","¼ كوب بصل (صغير، مقطّع مكعبات)","½ ملعقة صغيرة ثوم مجفف مطحون","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح كوشر"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). رشّ 2 صينية مافن من 12 قالبًا برذاذ الطهي.","افصل بياض البيض عن الصفار.","في وعاء كبير، اخفق صفار البيض والجبن القريش بخفاقة يدوية أو كهربائية قائمة على سرعة متوسطة إلى عالية حتى يصبح الخليط كريميًا.","في وعاء كبير آخر، اخفق بياض البيض حتى تتكوّن قمم جامدة.","اخلط الخضار والتوابل مع خليط صفار البيض حتى تمتزج جيدًا.","اطوِ بياض البيض برفق في خليط الصفار والخضار.","باستخدام مغرفة أو ملعقة كبيرة، وزّع خليط البيض بالتساوي على 18 قالبًا من قوالب المافن.","ضع الصواني في الفرن المسخّن مسبقًا واخبزها لمدة 25–30 دقيقة، حتى ينتفخ وجهها ويتحمّر.","أخرجها من الفرن واتركها تبرد 5 دقائق. أخرج المافن من الصواني برفق."])}))
R.append((6851302,{
"ar":L("التونة المسودّة مع صلصة الخردل الحامضة","يصلح هذا الطبق جدًا على المقلاة فوق الموقد أيضًا.","4","1 شريحة تونة",
["½ ملعقة صغيرة فلفل كايين (اختياري)","1 ملعقة صغيرة زعتر مجفف (مجفف)","1 ملعقة صغيرة أوريجانو مجفف (مجفف)","1 ملعقة كبيرة بابريكا","1 ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","1 ملعقة صغيرة فلفل أسود","½ ملعقة صغيرة ثوم مجفف مطحون","½ ملعقة صغيرة ملح (اختياري)","1 رطل شرائح تونة آهي (مقسّمة إلى 4 شرائح، 4 أونصات لكل منها)","1 رشة، 0.25 غرام رذاذ طهي غير لاصق","2 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","1 ملعقة كبيرة خردل ديجون","1 ملعقة صغيرة صلصة صويا منخفضة الصوديوم","1 ملعقة كبيرة بقدونس طازج (مفروم)"],
["جهّز شواية داخلية أو خارجية.","اخلط البابريكا ومسحوق الفلفل الحار والأوريجانو والزعتر وفلفل كايين (اختياري) والفلفل الأسود المطحون والثوم المجفف المطحون والملح (اختياري).","افرك كل شريحة تونة جيدًا من الجانبين بتوابل التسويد.","رشّ شرائح التونة برذاذ الطهي واشوِها 4-5 دقائق على كل جانب. يجب أن تبقى التونة وردية قليلًا في الوسط.","في وعاء صغير، اخفق الزبادي والخردل وصلصة الصويا. وزّع الصلصة بالتساوي على شرائح التونة الـ 4 وضعها فوقها قبل التقديم مباشرة، ثم رشّ البقدونس الطازج المفروم."])}))
R.append((6851874,{
"es":L("Ensalada de zanahoria con manzana","¡Vamos a lo crujiente! Las manzanas y las zanahorias se combinan de maravilla en esta ensalada de acompañamiento, con vinagre ácido, un toque picante de mostaza y apenas un poco de dulzor natural del jarabe de maple.","4","1 taza",
["4 zanahorias grandes (peladas y ralladas)","1 manzana mediana (sin corazón y en cubos)","3 cucharadas de aceite de oliva","2 cucharadas de vinagre de manzana","1 cucharadita de mostaza Dijon","1 cucharada de jarabe multiusos sin azúcar","1/4 cucharadita de sal kosher","1/4 cucharadita de pimienta negra","1 cucharada de perejil fresco (picado, para decorar)"],
["En un tazón grande, combine las zanahorias ralladas y la manzana en cubos.","En otro tazón más pequeño, bata el aceite de oliva, el vinagre de manzana, la mostaza Dijon, el jarabe, la sal y la pimienta.","Vierta el aderezo sobre la mezcla de zanahoria y manzana.","Mezcle la ensalada suavemente para que se cubra de manera uniforme.","Sirva fría o a temperatura ambiente."]),
"ar":L("سلطة الجزر بالتفاح","هيا نستمتع بالقرمشة! يجتمع التفاح والجزر بشكل رائع في هذه السلطة الجانبية، مع خل حامض ولمسة حارة من الخردل وقليل من الحلاوة الطبيعية من شراب القيقب.","4","1 كوب",
["4 حبات جزر كبيرة (مقشّرة ومبشورة)","1 حبة تفاح متوسطة (منزوعة القلب ومقطّعة مكعبات)","3 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة خل التفاح","1 ملعقة صغيرة خردل ديجون","1 ملعقة كبيرة شراب متعدد الاستخدامات غير محلّى","¼ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة بقدونس طازج (مفروم، للتزيين)"],
["في وعاء كبير، اخلط الجزر المبشور والتفاح المقطّع مكعبات.","في وعاء منفصل أصغر، اخفق زيت الزيتون وخل التفاح وخردل ديجون والشراب والملح والفلفل.","اسكب الصلصة فوق خليط الجزر والتفاح.","قلّب السلطة برفق لتتغطى بالتساوي.","قدّمها باردة أو بدرجة حرارة الغرفة."])}))
R.append((6852942,{
"es":L("Hamburguesas de pollo sensacionales","Barbara Seelig-Brown creó estas hamburguesas para un picnic del vecindario. Quería asegurarse de llevar algo saludable y también sabroso.","4","1 hamburguesa",
["1/2 libra de pechuga de pollo molida","1/2 libra de pollo molido (mezcla de carne blanca y oscura)","1/4 taza de tomates secados al sol (picados, sin aceite)","1/4 taza de cebolla (picada)","1/4 taza de albahaca fresca (picada)","1/4 taza de perejil italiano de hoja plana fresco (picado)","4 dientes de ajo (picados)","1/2 cucharadita de sal marina fina","1/2 cucharadita de pimienta negra (recién molida)"],
["Mezcle todos los ingredientes y forme 4 hamburguesas.","Ase de 3–4 minutos por cada lado y sirva con guacamole."]),
"ar":L("برغر الدجاج الرائع","ابتكرت باربرا سيليغ-براون هذا البرغر لنزهة في الحي. أرادت أن تتأكد من أنها ستحضر شيئًا صحيًا ولذيذًا في آن واحد.","4","1 برغر",
["½ رطل صدر دجاج مفروم","½ رطل دجاج مفروم (مزيج من اللحم الأبيض والداكن)","¼ كوب طماطم مجففة بالشمس (مفرومة، غير مغموسة في الزيت)","¼ كوب بصل (مفروم)","¼ كوب ريحان طازج (مفروم)","¼ كوب بقدونس إيطالي مفلطح طازج (مفروم)","4 فص ثوم (مفروم)","½ ملعقة صغيرة ملح بحري ناعم","½ ملعقة صغيرة فلفل أسود (مجروش طازجًا)"],
["اخلط جميع المكونات معًا وشكّل منها 4 أقراص.","اشوِها 3–4 دقائق على كل جانب وقدّمها مع الغواكامولي."])}))
R.append((6857343,{
"es":L("Verduras asadas con orégano y queso feta","Pruebe una mezcla deliciosa que combina los sabores intensos de verduras asadas a la perfección con las notas sabrosas del queso feta, para crear un platillo de inspiración mediterránea, lleno de nutrientes, que disfrutará toda la familia.","4","3/4 taza",
["3 tazas de verduras mixtas congeladas (espárragos, pimientos, calabacitas, tomates cherry, en rebanadas)","2 cucharadas de aceite de oliva","1/2 cucharadita de orégano seco","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra","2 cucharadas de queso feta"],
["Precaliente el horno a 400 grados F y cubra una bandeja para hornear con papel pergamino.","Mezcle las verduras mixtas con el aceite de oliva, el orégano seco, la sal y la pimienta.","Ase de 20-25 minutos hasta que estén tiernas y ligeramente chamuscadas.","Sirva sobre el queso feta."]),
"ar":L("خضار مشوية بالأوريجانو وجبن الفيتا","جرّب مزيجًا شهيًا يجمع بين النكهات القوية للخضار المشوية بإتقان ونفحات جبن الفيتا اللذيذة، ليشكّل طبقًا مغذيًا مستوحى من المطبخ المتوسطي تستمتع به الأسرة كلها.","4","¾ كوب",
["3 كوب خضار مشكّلة مجمّدة (هليون وفلفل رومي وكوسا وطماطم كرزية، مقطّعة شرائح)","2 ملعقة كبيرة زيت زيتون","½ ملعقة صغيرة أوريجانو مجفف","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة جبن فيتا"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية) وبطّن صينية خبز بورق الزبدة.","قلّب الخضار المشكّلة مع زيت الزيتون والأوريجانو المجفف والملح والفلفل.","اشوِها لمدة 20-25 دقيقة حتى تنضج وتتفحّم قليلًا.","قدّمها فوق جبن الفيتا."])}))
R.append((6858549,{
"ar":L("لفائف سلطة الدجاج ببيستو السبانخ","هل تحاول خفض ضغط الدم بمراقبة تناول الصوديوم؟ استخدم أعشابًا مثل الريحان ومكونات قوية النكهة مثل الليمون والثوم والفلفل للحصول على نكهة غنية. وهذه اللفافة طريقة رائعة أيضًا لإدخال مزيد من الخضار مع السبانخ.","5","1 لفافة",
["1 رشة، 0.25 غرام رذاذ طهي غير لاصق","1 رطل صدور دجاج خالية من العظم والجلد","½ ملعقة صغيرة فلفل أسود (مقسّمة)","1 ملعقة صغيرة ريحان (مجفف)","3 كوب سبانخ صغيرة (تُزال السيقان الكبيرة)","2 ملعقة كبيرة صنوبر (محمّص)","2 ملعقة كبيرة عصير ليمون طازج","¼ كوب مايونيز خفيف","1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة جبن بارميزان (مبشور طازجًا)","¼ ملعقة صغيرة ثوم مجفف مطحون","5 أقراص تورتيلا ذرة صغيرة 6 بوصات"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). رشّ صينية خبز برذاذ الطهي.","تبّل صدور الدجاج بـ ¼ ملعقة صغيرة من الفلفل الأسود والريحان المجفف. اخبزها 35 دقيقة أو حتى تنضج. ضع صدور الدجاج في الثلاجة لتبرد.","في محضّر الطعام، اخلط السبانخ والصنوبر وعصير الليمون والمايونيز. شغّل الجهاز على دفعات قصيرة بخفة. وبينما يعمل الجهاز، أضف زيت الزيتون واخلط حتى يصبح الخليط كريميًا. أضف جبن البارميزان والثوم المجفف المطحون و¼ ملعقة صغيرة من الفلفل الأسود وحرّك.","قطّع الدجاج المطبوخ إلى قطع بحجم ½ بوصة ثم فتّته. في وعاء متوسط، اخلط الدجاج مع صلصة البيستو؛ واخلط جيدًا.","ضع ½ كوب من سلطة الدجاج في كل قرص تورتيلا. اطوِ جانبي التورتيلا ولفّها مثل البوريتو. يمكنك تقديمها فورًا أو لفّها بإحكام بغلاف بلاستيكي ووضعها في الثلاجة."])}))
R.append((6859231,{
"es":L("Tostada de pera y requesón","Esta sencilla tostada combina capas de requesón cremoso con canela, rebanadas de pera dulce y nueces crujientes, para un desayuno o merienda vegetariano, bajo en grasa y muy satisfactorio. El pan integral y la fruta fresca aportan fibra, mientras que el requesón aporta proteína para ayudar a controlar los niveles de glucosa en la sangre (azúcar en la sangre). Es una opción rápida y apta para personas con diabetes que equilibra el sabor y la nutrición en cada bocado.","4","1 rebanada de pan tostado con 1/4 taza de requesón",
["4 rebanadas de pan integral (tostado)","1 taza de requesón (bajo en grasa)","2 peras enteras (maduras, en rebanadas finas)","4 cucharaditas de nueces (picadas)","1/2 cucharadita de canela molida"],
["Tueste las rebanadas de pan integral hasta que estén doradas y crujientes. Reserve para que se enfríen un poco.","En un tazón pequeño, mezcle el requesón bajo en grasa con la canela molida hasta que quede uniforme.","Unte la mezcla de requesón con canela de manera uniforme sobre cada rebanada de pan tostado. Cubra con las rebanadas de pera y espolvoree las nueces picadas."]),
"ar":L("توست الكمثرى والجبن القريش","يجمع هذا التوست البسيط طبقات من الجبن القريش الكريمي المتبّل بالقرفة مع شرائح الكمثرى الحلوة والجوز المقرمش، لوجبة فطور أو وجبة خفيفة نباتية وقليلة الدسم ومُرضية. يضيف الخبز من القمح الكامل والفاكهة الطازجة الألياف، بينما يضيف الجبن القريش البروتين للمساعدة في ضبط مستويات الغلوكوز في الدم (سكر الدم). إنه خيار سريع مناسب لمرضى السكري يوازن بين النكهة والتغذية في كل لقمة.","4","1 شريحة توست مع ¼ كوب جبن قريش",
["4 شرائح خبز قمح كامل (محمّصة)","1 كوب جبن قريش (قليل الدسم)","2 حبة كمثرى كاملة (ناضجة، مقطّعة شرائح رفيعة)","4 ملعقة صغيرة جوز (مفروم)","½ ملعقة صغيرة قرفة مطحونة"],
["حمّص شرائح خبز القمح الكامل حتى تصبح ذهبية ومقرمشة. ضعها جانبًا لتبرد قليلًا.","في وعاء صغير، حرّك الجبن القريش قليل الدسم مع القرفة المطحونة حتى يمتزجا بالتساوي.","ادهن خليط الجبن القريش بالقرفة بالتساوي على كل شريحة توست. زيّنها بشرائح الكمثرى ورشة من الجوز المفروم."])}))
R.append((6860194,{
"es":L("Tacos de pavo","El pavo molido magro es una excelente base para una deliciosa comida de tacos. Esta receta tiene un toque picante que puede ajustarse agregando más o menos jalapeño.","6","1 taco",
["2 cucharaditas de aceite de oliva","1/2 cebolla morada mediana (en cubos)","2 cucharadas de chile jalapeño finamente picado","16 onzas de pavo molido magro al 94 %","1 diente de ajo (picado)","1 cucharada de comino molido","1 cucharada de chile en polvo","1/2 cucharadita de pimentón ahumado","2 cucharadas de agua","6 tortillas de maíz pequeñas de 6 pulgadas","1 aguacate grande (en cubos)","6 cucharadas de yogur griego natural sin grasa","6 cucharadas de pico de gallo sin sal añadida"],
["En un sartén grande, caliente el aceite de oliva a fuego medio-alto.","Agregue la cebolla y el jalapeño al sartén y cocine durante 2 minutos. Agregue el pavo y cocine hasta que la carne esté dorada y las verduras bien cocidas, aproximadamente de 5 a 7 minutos. Agregue el ajo y el comino y cocine durante 30 segundos.","Baje el fuego y agregue el chile en polvo, el pimentón y el agua, y mezcle bien.","Rellene cada tortilla con ½ taza de la mezcla de pavo, más aproximadamente 2 cucharadas de aguacate en cubos, 1 cucharada de yogur y 1 cucharada de pico de gallo."]),
"ar":L("تاكو الديك الرومي","يُعدّ الديك الرومي المفروم قليل الدسم أساسًا رائعًا لوجبة تاكو لذيذة. تحتوي هذه الوصفة على لمسة حارة يمكن تعديلها بإضافة كمية أكثر أو أقل من الهالابينو.","6","1 تاكو",
["2 ملعقة صغيرة زيت زيتون","½ حبة بصل أحمر متوسطة (مقطّعة مكعبات)","2 ملعقة كبيرة فلفل هالابينو مقطّع مكعبات صغيرة جدًا","16 أونصة ديك رومي مفروم بنسبة 94% خالٍ من الدهون","1 فص ثوم (مفروم)","1 ملعقة كبيرة كمون مطحون","1 ملعقة كبيرة مسحوق الفلفل الحار (تشيلي)","½ ملعقة صغيرة بابريكا مدخنة","2 ملعقة كبيرة ماء","6 أقراص تورتيلا ذرة صغيرة 6 بوصات","1 حبة أفوكادو كبيرة (مقطّعة مكعبات)","6 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","6 ملعقة كبيرة بيكو دي غايو بدون ملح مضاف"],
["في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة إلى عالية.","أضف البصل والهالابينو إلى المقلاة واطهُهما لمدة 2 دقيقة. أضف الديك الرومي واطهُه حتى يتحمّر اللحم وتنضج الخضار، نحو 5 إلى 7 دقائق. أضف الثوم والكمون واطهُ لمدة 30 ثانية.","خفّض الحرارة وأضف مسحوق الفلفل الحار والبابريكا والماء، واخلط جيدًا.","احشُ كل قرص تورتيلا بـ ½ كوب من خليط الديك الرومي، مع نحو 2 ملعقة كبيرة من الأفوكادو المقطّع و1 ملعقة كبيرة من الزبادي و1 ملعقة كبيرة من بيكو دي غايو."])}))
R.append((6860841,{
"es":L("\"Pasta\" de verduras estilo carbonara con tiras anchas","En esta receta se usa un pelador de verduras para hacer cintas de zanahoria y calabacita, que son un excelente sustituto de la pasta, más bajo en carbohidratos.","4","1 taza",
["2 dientes de ajo (picados)","1/2 cebolla pequeña (picada finamente)","1 calabacita mediana","2 zanahorias medianas (o 1 grande, pelada)","2 cucharaditas de aceite de oliva","4 rebanadas de tocino de pavo (en cubos pequeños)","2 cucharadas de harina","1 1/2 tazas de leche descremada","3 cucharadas de queso parmesano (rallado)","1/2 cucharadita de sal (opcional)","1/4 cucharadita de pimienta negra","1 cucharada de perejil fresco (picado finamente)"],
["Llene una olla de sopa con agua y lleve el agua a ebullición.","Con un pelador de verduras, saque tiras delgadas de cada verdura (calabacita y zanahoria) para hacer \"fideos\" anchos. Debe obtener aproximadamente 5 tazas de \"fideos\" de verdura. Tenga cuidado de evitar las semillas de la calabacita.","Hierva los \"fideos\" de verdura de 2-4 minutos o hasta que apenas se ablanden. Escúrralos y extiéndalos en una sola capa sobre una bandeja para hornear para que se sequen.","En un sartén antiadherente mediano, agregue el aceite de oliva a fuego medio-bajo.","Saltee el tocino de pavo y la cebolla hasta que la cebolla empiece a ablandarse. Agregue el ajo y cocine dos minutos más. Incorpore la harina y déjela cocinar durante 2 minutos.","Incorpore la leche y el queso y lleve a ebullición, raspando el fondo del sartén para integrar toda la harina, hasta que espese.","Una vez que espese, agregue los \"fideos\" de verdura y mezcle suavemente para cubrirlos.","Sazone con sal (opcional) y pimienta negra molida, e incorpore el perejil. Sirva de inmediato."]),
"ar":L("\"باستا\" الخضار كاربونارا بشرائح عريضة","في هذه الوصفة تستخدم مقشرة خضار لتحضير شرائح من الجزر والكوسا، وهي بديل رائع وأقل كربوهيدرات من المعكرونة.","4","1 كوب",
["2 فص ثوم (مفروم)","½ حبة بصل صغيرة (مفروم ناعمًا)","1 حبة كوسا متوسطة","2 حبة جزر متوسطة (أو 1 كبيرة، مقشّرة)","2 ملعقة صغيرة زيت زيتون","4 شرائح لحم ديك رومي مقدد (مقطّعة مكعبات صغيرة)","2 ملعقة كبيرة دقيق","1½ كوب حليب خالي الدسم","3 ملعقة كبيرة جبن بارميزان (مبشور)","½ ملعقة صغيرة ملح (اختياري)","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة بقدونس طازج (مفروم ناعمًا)"],
["املأ قدر شوربة بالماء واتركه حتى يغلي.","باستخدام مقشرة الخضار، قشّر شرائح رفيعة من كل خضار (الكوسا والجزر) لتحضير \"شعيرية\" عريضة. يجب أن تحصل على نحو 5 كوب من \"شعيرية\" الخضار. احرص على تجنب بذور الكوسا.","اسلق \"شعيرية\" الخضار لمدة 2-4 دقائق أو حتى تلين فقط. صفِّها وافردها في طبقة واحدة على صينية خبز لتجف.","في مقلاة متوسطة غير لاصقة، أضف زيت الزيتون على نار متوسطة إلى منخفضة.","قلّب لحم الديك الرومي المقدد والبصل حتى يبدأ البصل بالليونة. أضف الثوم واطهُ لدقيقتين (2 دقيقة) إضافيتين. أضف الدقيق وحرّك واتركه يُطهى لمدة 2 دقيقة.","أضف الحليب والجبن واتركه حتى يغلي، مع كشط قاع المقلاة لدمج كل الدقيق حتى يثخن.","عندما يثخن، أضف \"شعيرية\" الخضار وقلّبها برفق لتتغطى.","تبّل بالملح (اختياري) والفلفل الأسود المطحون، وأضف البقدونس وحرّك. قدّمه فورًا."])}))
R.append((6862739,{
"es":L("Yogur griego sin grasa","Información nutricional del yogur griego sin grasa","1","3/4 taza",["3/4 taza de yogur griego natural sin grasa"],[]),
"ar":L("زبادي يوناني خالٍ من الدسم","المعلومات الغذائية للزبادي اليوناني الخالي من الدسم","1","¾ كوب",["¾ كوب زبادي يوناني سادة خالٍ من الدسم"],[])}))
R.append((6862793,{
"es":L("Sopa cremosa de calabaza con pepitas tostadas","El autor Steven Petusevsky: \"Esta sopa cremosa es rica y está llena de un intenso sabor tropical. Puede dejarla con trozos, como yo, o hacerla puré si le gusta suave y cremosa. A veces sustituyo 1 taza del caldo de verduras o del agua por una taza de leche de coco light para darle un poco más de riqueza\".","8","1 taza",
["2 libras de calabaza calabaza (pelada y picada)","8 tazas de caldo de verduras bajo en sodio (o use agua)","1 tomate grande (picado)","1 cebolla mediana (picada)","1 pimiento verde mediano (picado)","1 chile jalapeño mediano (sin semillas y picado finamente)","1 cucharada de jengibre fresco (picado finamente)","8 tallos de cebollín (cebolla de cambray) (picados)","3 ramitas de tomillo fresco (o 1 cucharadita de tomillo seco)","1/4 taza de cilantro (picado)","2 cucharadas de jugo de limón verde fresco","1/8 cucharadita de sal","1 cucharada de pepitas (tostadas)"],
["Coloque la calabaza, el caldo, los tomates, la cebolla, el pimiento, la raíz de jengibre, los cebollines y las ramitas de tomillo o el tomillo seco en una cacerola grande no reactiva. Lleve a ebullición, reduzca el fuego y cocine a fuego lento sin tapar durante 45 minutos, revolviendo de vez en cuando, hasta que todos los ingredientes estén tiernos.","Agregue el cilantro, el jugo de limón verde y la sal. Retire los tallos de tomillo antes de servir. Decore cada tazón de sopa con pepitas antes de servir. Rinde aproximadamente 2 cuartos de galón."]),
"ar":L("شوربة القرع الكريمية مع بذور القرع المحمّصة","يقول المؤلف ستيفن بيتوسيفسكي: \"هذه الشوربة الكريمية غنية ومليئة بنكهة استوائية جريئة. يمكنك تركها بقطعها كما أفعل، أو هرسها إن كنت تفضّلها ناعمة وكريمية. أحيانًا أستبدل 1 كوب من مرق الخضار أو الماء بكوب من حليب جوز الهند الخفيف لمزيد من الغنى\".","8","1 كوب",
["2 رطل قرع كالابازا (مقشّر ومقطّع)","8 كوب مرق خضار قليل الصوديوم (أو استخدم الماء)","1 حبة طماطم كبيرة (مقطّعة)","1 حبة بصل متوسطة (مقطّعة)","1 حبة فلفل رومي أخضر متوسطة (مقطّعة)","1 حبة فلفل هالابينو متوسطة (منزوعة البذور ومفرومة)","1 ملعقة كبيرة زنجبيل طازج (مفروم)","8 سيقان بصل أخضر (مقطّعة)","3 أغصان زعتر طازج (أو 1 ملعقة صغيرة زعتر مجفف)","¼ كوب كزبرة خضراء (مفرومة)","2 ملعقة كبيرة عصير ليمون أخضر طازج","⅛ ملعقة صغيرة ملح","1 ملعقة كبيرة بذور قرع (محمّصة)"],
["ضع القرع والمرق والطماطم والبصل والفلفل والزنجبيل والبصل الأخضر وأغصان الزعتر أو الزعتر المجفف في قدر كبير غير تفاعلي. اتركه حتى يغلي، ثم خفّض الحرارة واتركه على نار هادئة دون غطاء لمدة 45 دقيقة مع التحريك من حين لآخر، حتى تنضج جميع المكونات.","أضف الكزبرة الخضراء وعصير الليمون الأخضر والملح. أخرج سيقان الزعتر قبل التقديم. زيّن كل وعاء شوربة ببذور القرع قبل التقديم. تكفي نحو 2 كوارت."])}))
save("out_c22_part4.json",R)
