import sys; sys.path.insert(0,'/mnt/c/WSL/davita/translations/sid1')
from mk import build
R=[
("Haysa Kurma Madinah","Haysa adalah manisan tradisional Madinah dari tepung gandum utuh yang disangrai dalam ghee dan dicampur dengan kurma, kapulaga, dan wijen, disajikan hangat bersama kopi Arab. Kami memakai sekitar seperempat dari jumlah lemak yang biasa, tanpa gula tambahan karena kurma sudah memaniskannya, dan dibentuk menjadi potongan kecil.","12","1 potong (sekitar 32 g)",
["25 g ghee (sekitar 2 sendok makan)","100 g tepung gandum utuh","1 sendok teh kapulaga bubuk","250 g kurma lunak tanpa biji (seperti Khalas)","10 g biji wijen sangrai (1 sendok makan) dan ½ sendok teh biji jintan hitam"],
["Lelehkan ghee dalam panci antilengket dengan api kecil, masukkan tepung dan aduk terus selama 6–8 menit hingga tersangrai, keemasan, dan harum.","Masukkan kapulaga, lalu kurma dan lumatkan ke dalam tepung dengan sendok kayu atau penumbuk dengan api sangat kecil hingga tercampur rata (sekitar 5 menit).","Masukkan wijen dan biji jintan hitam lalu aduk 1 menit.","Biarkan agak dingin, lalu bentuk menjadi 12 bola kecil atau persegi dengan tangan basah dan sajikan hangat bersama kopi Arab."],
["Yang diubah: 25 g ghee sebagai pengganti 100 g mentega ditambah minyak, tepung gandum utuh, tanpa gula tambahan atau krim, dan potongan kecil yang ukurannya tetap.","Tips untuk ginjal: kurma tinggi kalium (sekitar 170 mg per potong) dan wijen serta tepung gandum utuh mengandung fosfor; makan satu potong, dan Anda dapat memakai tepung putih dan melewatkan wijen.","Tips untuk diabetes: satu potong mengandung sekitar 22 g karbohidrat dari kurma dan tepung; batasi satu potong dengan kopi setelah makan.","Cocok untuk: penderita diabetes, kesehatan jantung dan tekanan darah, penyakit ginjal (belum dialisis), pasien dialisis, vegetarian.","Referensi: Encyclopedia Cooking (encyclopediacooking.com), Al Bilad Daily, Cookpad"]),
("Ma'soub","Ma'soub adalah sarapan khas Hijaz yang terkenal dari Makkah, Jeddah, dan Madinah: roti gandum cincang diaduk dengan pisang dan ghee lalu diberi krim dan madu di atasnya. Pada versi ini rotinya dibuat dari tepung gandum utuh, dengan sedikit ghee dan krim ringan, serta pisang dan kurma memberi sebagian besar rasa manis dengan hanya satu sendok madu.","4","1 piring (sekitar 200 g)",
["200 g tepung gandum utuh","1 sendok teh ragi kering (3 g)","sejumput garam (1 g)","sekitar 140 ml air hangat","3 sendok teh ghee (15 g)","3 pisang matang, dikupas (300 g)","4 butir kurma tanpa biji atau rutab (40 g)","sejumput kapulaga bubuk","2 sendok makan krim ringan (qishta) (40 g)","1 sendok makan madu (20 g)"],
["Uleni tepung dengan ragi, garam, dan air menjadi adonan lembut; tutup dan biarkan mengembang selama 30 menit.","Bagi adonan menjadi 3 bulatan, giling masing-masing tipis dan masak dalam wajan antilengket kering atau di saj panas 1–2 menit per sisi hingga matang dan berbintik.","Potong roti dan haluskan dalam food processor menjadi remah halus.","Lelehkan ghee dalam panci dengan api kecil, masukkan kurma dan lumatkan hingga meleleh, lalu masukkan remah roti dan aduk 5 menit.","Masukkan pisang iris dan kapulaga dan lumatkan dengan sendok sambil diaduk selama 3–5 menit hingga campuran rata dan lembut.","Sendokkan ma'soub ke piring saji dan beri satu sendok teh krim dan sedikit madu pada masing-masing; sajikan hangat."],
["Yang diubah: roti gandum utuh buatan sendiri, ghee jauh lebih sedikit, sedikit krim ringan, dan rasa manis terutama dari pisang dan kurma dengan hanya satu sendok madu untuk seluruh hidangan.","Tips untuk ginjal: pisang dan kurma kaya kalium dan tepung gandum utuh mengandung fosfor; pakai 2 pisang sebagai pengganti 3 ditambah apel parut yang dimasak, dan makan setengah porsi.","Tips untuk diabetes: satu porsi mengandung sekitar 65 g karbohidrat; makan setengah porsi dengan telur rebus atau laban rendah lemak dan lewatkan madunya.","Cocok untuk: kesehatan jantung dan tekanan darah, vegetarian.","Referensi: Encyclopedia Cooking, Mawdoo3, Khaleeji Food"]),
("Daghabees Ghamdi","Daghabees adalah hidangan tradisional dari wilayah Ghamid dan Zahran di Al-Baha, Arab Saudi bagian selatan: pangsit adonan gandum dimasak dalam kuah daging dan dimakan dengan tangan, dengan menekan cekungan dengan ibu jari dan mengisinya dengan kuah. Versi ini memakai daging domba tanpa lemak dan tepung gandum utuh, menambahkan sayuran ke dalam kuah, dan tanpa kaldu kubus.","4","1 piring (sekitar 3 daghabees dengan daging dan kuah, 450 g)",
["560 g paha domba tanpa tulang dan tanpa lemak, lemak dibuang, potong besar","2 sendok teh minyak zaitun (10 g)","1 bawang bombai besar, potong dadu (150 g)","3 siung bawang putih, cincang (9 g)","2 tomat sedang, parut (240 g)","1 zukini sedang, potong dadu (150 g) dan 1 wortel sedang, potong dadu (100 g)","1½ sendok teh jintan, ½ sendok teh lada hitam, ½ sendok teh kunyit, sejumput kayu manis","6 butir kapulaga, 1 batang kayu manis, 1 lemon hitam kering yang ditusuk","¾ sendok teh garam (4.5 g) untuk seluruh resep, dibagi antara kuah dan adonan","1.6 l air panas","150 g tepung gandum utuh (cokelat)","100 g tepung putih","sekitar 160 ml air hangat"],
["Campur kedua tepung dengan seperempat garam, tambahkan air hangat sedikit demi sedikit dan uleni menjadi adonan padat dan halus. Tutup dan diamkan 30 menit.","Panaskan minyak dalam panci lebar, masukkan jintan, butir kapulaga, dan kayu manis, lalu daging domba, dan cokelatkan di semua sisi.","Masukkan bawang bombai dan bawang putih dan aduk 3 menit, lalu tomat, lada hitam, kunyit, dan lemon hitam.","Tuang air panas, tutup dengan menyisakan celah kecil dan didihkan perlahan 1 jam hingga daging hampir empuk, sambil membuang busa dan lemak.","Masukkan zukini, wortel, dan sisa garam.","Dengan tangan basah bagi adonan menjadi 12 bulatan dan pipihkan masing-masing di telapak tangan menjadi oval tebal.","Masukkan cakram ke dalam kuah yang mendidih perlahan satu per satu, beri jeda satu menit di antaranya agar tidak saling menempel.","Tutup dan didihkan perlahan 25–30 menit, goyangkan panci perlahan setiap 5 menit, hingga pangsit dan daging matang.","Tata daghabees dan daging di piring besar dengan kuah dan sayuran dalam mangkuk, dan celupkan pangsit ke dalam kuah untuk memakannya."],
["Yang diubah: tanpa kaldu kubus (resep umum menambahkan dua setengah), daging domba tanpa lemak dengan lemak dibuang dari kuah, lebih banyak tepung gandum utuh daripada tepung putih, dan sayuran ditambahkan ke dalam kuah.","Tips untuk ginjal: tomat, tepung cokelat, dan daging menambah kalium dan fosfor; pakai lebih banyak tepung putih jika Anda perlu membatasi fosfor, dan batasi tiga pangsit dengan sedikit kuah.","Tips untuk diabetes: satu piring mengandung sekitar 57 g karbohidrat, sebagian besar dari adonan; batasi tiga pangsit kecil dan sajikan dengan salad hijau.","Cocok untuk: penderita diabetes, kesehatan jantung dan tekanan darah.","Referensi: Encyclopedia Cooking (Mawsouat Al Tabkh), Wikipedia Arab, Majalah Al Jawhara"]),
("Marsa Jazan","Marsa adalah hidangan tradisional dari wilayah Jazan: roti tipis yang dipanggang di wajan datar atau oven mifa dicincang halus dan diuleni dengan pisang yang dilumatkan, lalu disajikan dengan ghee dan madu, sering di samping ikan. Versi ini memakai sebagian tepung gandum utuh, hanya dua sendok teh minyak dalam adonan, dan separuh ghee dan madu yang biasa.","4","1 piring kecil (170 g)",
["120 g tepung gandum utuh dan 80 g tepung putih","2 sendok teh minyak zaitun (10 ml)","1 sejumput garam (1 g)","sekitar 130 ml air","2 pisang matang sedang (240 g dikupas)","2½ sendok teh ghee (12 g)","4 sendok teh madu (28 g)"],
["Campur kedua tepung dengan garam dan minyak, tambahkan air sedikit demi sedikit dan uleni menjadi adonan lembut; diamkan 15 menit.","Bagi adonan menjadi 3 bagian, giling masing-masing tipis dan masak dalam wajan antilengket dengan api sedang di kedua sisi hingga keemasan dan sedikit garing.","Selagi panas, cincang roti sangat halus atau haluskan dalam food processor.","Lumatkan pisang dengan garpu dalam mangkuk, masukkan roti cincang dan uleni bersama hingga rata.","Tekan marsa ke dalam piring saji dan ratakan bagian atasnya, tuang ghee cair, siramkan madu dan bagi menjadi 4 porsi."],
["Yang diubah: sebagian tepung gandum utuh, sedikit minyak dalam adonan sebagai pengganti banyak lemak, sekitar separuh ghee dan madu yang biasa, dan pisang memberi sebagian besar rasa manis.","Tips untuk ginjal: pisang tinggi kalium (sekitar 90 g pisang per porsi); Anda dapat memakai satu pisang saja, atau seluruhnya tepung putih, dan batasi satu porsi.","Tips untuk diabetes: satu porsi mengandung sekitar 56 g karbohidrat; sajikan dengan sepotong ikan panggang (secara tradisional dimakan dengan ikan) dan salad hijau, dan Anda dapat mengurangi atau melewatkan madu.","Cocok untuk: penderita diabetes, kesehatan jantung dan tekanan darah, penyakit ginjal (belum dialisis), pasien dialisis, vegetarian.","Referensi: Encyclopedia Cooking, surat kabar Al-Madina, Cookpad"]),
("Haysiya Jazan","Haysiya adalah hidangan tradisional dari wilayah Jazan: roti lahoh asam hasil fermentasi disobek ke dalam mangkuk tanah liat (haysiya), direndam kuah daging berempah, dan diberi daging di atasnya; keluarga pesisir menyebutnya marshoosh. Versi ini memakai daging domba tanpa lemak, tepung sorgum dan gandum utuh untuk lahoh, sangat sedikit ghee, dan garam lebih sedikit tanpa kaldu kubus.","4","1 mangkuk (sekitar 450 g dengan kuah)",
["100 g tepung sorgum biji utuh","100 g tepung gandum utuh kasar","1 sendok teh ragi kering (3 g)","2 sendok makan bawang bombai parut (30 g) dan 1 siung bawang putih yang dimemarkan","sekitar 400 ml air hangat","560 g paha domba tanpa tulang dan tanpa lemak, lemak dibuang, potong sedang","2 sendok teh minyak zaitun (10 g)","1 bawang bombai besar, iris tipis (150 g)","3 siung bawang putih, cincang (9 g)","2 tomat kecil, cincang (200 g)","1 sendok teh jintan, ½ sendok teh lada hitam, ½ sendok teh kapulaga bubuk, sejumput kayu manis","Rempah utuh: 2 butir cengkih, 3 butir kapulaga, 1 batang kayu manis kecil","¾ sendok teh garam (4.5 g) untuk seluruh resep","1.2 l air","2 sendok teh ghee (8 g) dan peterseli cincang (10 g) untuk penyajian"],
["Campur tepung sorgum, tepung gandum, ragi, bawang parut, dan bawang putih, lalu kocok air hangat sedikit demi sedikit menjadi adonan cair yang bisa dituang seperti adonan kue.","Tutup dan diamkan di tempat hangat selama 3–4 jam hingga berbuih dan sedikit asam.","Sementara itu, panaskan minyak dalam panci dan masak bawang bombai iris hingga lunak dan keemasan, lalu masukkan bawang putih dan tomat dan aduk 3 menit.","Masukkan daging domba dan balik hingga berubah warna, lalu masukkan rempah utuh dan bubuk serta air. Didihkan, kecilkan api, tutup dan didihkan perlahan 1½ jam hingga empuk, sambil membuang busa dan lemak.","Masukkan garam pada 10 menit terakhir memasak.","Panaskan wajan antilengket dengan api sedang tanpa minyak, tuang satu sendok sayur kecil adonan cair dan ratakan menjadi bulatan. Masak hingga penuh lubang dan kering di bagian atas, tanpa dibalik (sekitar 2 menit). Ulangi hingga mendapat sekitar 8 bulatan.","Sobek 2 bulatan lahoh ke dalam setiap mangkuk, tuang kuah panas hingga terendam, lalu letakkan daging di atasnya.","Lelehkan ghee dan siramkan ½ sendok teh pada setiap mangkuk, taburi peterseli dan sajikan panas dengan salad hijau."],
["Yang diubah: paha domba yang dipangkas sebagai pengganti daging berlemak, lemak dibuang dari kuah, hanya 2 sendok teh ghee untuk seluruh panci sebagai pengganti tuangan yang banyak, sedikit garam tanpa kaldu kubus atau campuran rempah bergaram, dan lahoh dibuat dari biji-bijian utuh.","Tips untuk ginjal: tomat, daging, dan biji-bijian utuh menambah kalium dan fosfor; batasi satu mangkuk, pakai satu sendok sayur kuah dan jangan minum kuah tambahan, dan Anda dapat mengganti separuh tepung gandum utuh dengan tepung putih untuk menurunkan fosfor.","Tips untuk diabetes: satu mangkuk mengandung sekitar 45 g karbohidrat dari lahoh; sorgum dan gandum utuh menaikkan gula darah lebih lambat daripada roti putih, jadi sajikan dengan salad dalam jumlah besar.","Cocok untuk: penderita diabetes, kesehatan jantung dan tekanan darah.","Referensi: Encyclopedia Cooking (Mawsouat Al Tabkh), Sayidaty Kitchen, Yummy (Layalina)"]),
("Luqaimat Labu Kuning","Luqaimat labu kuning adalah versi Teluk dan Saudi dari luqaimat di mana puree labu kuning dan yogurt dimasukkan ke dalam adonan dengan saffron dan kapulaga; biasanya digoreng dan dicelup sirop gula. Di sini dimasak dalam cetakan aebleskiver (pancake bulat) atau air fryer dengan sedikit minyak zaitun, separuh tepungnya gandum utuh, dan sedikit sirop kurma menggantikan sirop gula.","6","6 luqaimat dengan sirop kurma (sekitar 90 g)",
["250 g labu kuning, dikupas dan dipotong dadu","170 g yogurt rendah lemak","sekitar 120 ml air hangat","120 g tepung putih","120 g tepung gandum utuh","2 sendok makan tepung maizena (30 g)","2 sendok teh ragi kering (7 g)","sejumput garam (1 g)","½ sendok teh kapulaga bubuk dan sejumput saffron","1 sendok makan minyak zaitun (15 ml)","3 sendok makan sirop kurma (60 g)","2 sendok teh biji wijen sangrai (6 g)"],
["Rebus labu kuning dalam sedikit air selama 12–15 menit hingga lunak, lalu tiriskan dengan baik dan biarkan agak dingin.","Blender labu kuning dengan yogurt dan air hingga halus.","Dalam mangkuk besar campur kedua tepung, maizena, ragi, garam, kapulaga, dan saffron, lalu masukkan campuran labu kuning dan kocok kuat dengan tangan atau sendok menjadi adonan lembut dan lengket.","Tutup dan diamkan di tempat hangat selama 1 sampai 1½ jam hingga mengembang dua kali lipat.","Panaskan cetakan aebleskiver (pancake bulat) dengan api sedang, olesi cekungannya tipis-tipis dengan minyak dan jatuhkan bola kecil adonan ke masing-masing dengan dua sendok basah; balik hingga kecokelatan merata dan matang (4–5 menit). Atau air-fry dalam keranjang yang diolesi minyak pada 190 °C selama 8–10 menit, digoyang sekali.","Tumpuk luqaimat di piring, siramkan sirop kurma, taburi wijen dan sajikan segera."],
["Yang diubah: tanpa menggoreng dengan banyak minyak (satu sendok minyak zaitun untuk seluruh adonan), separuh tepung gandum utuh, yogurt rendah lemak, dan sedikit sirop kurma sebagai pengganti sirop gula.","Tips untuk ginjal: labu kuning, sirop kurma, yogurt, dan tepung gandum utuh mengandung kalium dan fosfor; batasi 6 potong, dan Anda dapat memakai seluruhnya tepung putih dan sirop lebih sedikit.","Tips untuk diabetes: satu porsi mengandung sekitar 47 g karbohidrat; makan 3 potong tanpa sirop atau hanya 1 sendok teh, dengan kopi Arab sebagai pengganti teh manis.","Cocok untuk: kesehatan jantung dan tekanan darah, penyakit ginjal (belum dialisis), pasien dialisis, vegetarian.","Referensi: Encyclopedia Cooking, Fatafeat, Cookpad Arab Saudi"]),
]
build(60,R,'/mnt/c/WSL/davita/translations/sid1/part8.json')
