import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xid11')
from h import *
L=[]
L.append(T(1002699,"Chiles Rellenos dengan Jamur dan Krim Keju","Ingin menambahkan sedikit cita rasa pada hidangan ramah ginjal berikutnya? Cobalah chiles rellenos dengan jamur dan krim keju ini.","2","1 chile relleno",
["4 ons krim keju","1/4 cangkir jamur, diiris","1 sendok teh bawang bombai","1 sendok makan wortel","2 cabai California","1 putih telur","1 sendok teh tepung terigu serbaguna","1 cangkir minyak kanola"],
["Cincang wortel dan bawang bombai.","Dalam mangkuk, campurkan krim keju dengan jamur, wortel, dan bawang bombai untuk membuat isian. Dinginkan di lemari es sampai cabai siap.","Panaskan wajan dengan api sedang. Letakkan cabai di wajan dan panggang sambil dibalik beberapa kali hingga kulitnya melepuh. Angkat dari api. Setelah cabai cukup dingin untuk dipegang, kupas kulitnya.","Belah cabai memanjang dan isi dengan hati-hati setengah dari isian krim keju ke dalam setiap cabai.","Dalam mangkuk lain, kocok putih telur dan tepung hingga kaku. Balurkan campuran telur pada setiap cabai.","Tuangkan minyak kanola ke dalam wajan hingga sedalam satu inci. Panaskan dengan api sedang.","Letakkan cabai dengan hati-hati ke dalam minyak panas dan goreng hingga cokelat keemasan, dibalik satu kali. Sajikan hangat."],
["Cabai California, yang juga dikenal sebagai cabai Anaheim, adalah cabai panjang dengan rasa agak pedas. Jika Anda tidak menemukannya, Anda dapat menggantinya dengan cabai utuh kalengan rendah natrium.","Kandungan kalium cabai berbeda-beda; beberapa varietas mengandung lebih dari 300 mg kalium per buah. Konsultasikan dengan ahli gizi Anda sebelum mengganti dengan varietas lain dalam resep ini."],
["1/2 daging","1/2 susu","1 sayuran, kalium sedang","4 lemak"]))
L.append(T(1002711,"Sofrito","Nikmati cita rasa melting pot Amerika bersama Tahseen, ahli gizi ginjal DaVita dari Florida. Setelah tinggal di berbagai penjuru dunia dan mencicipi hidangan dari banyak budaya, Tahseen membagikan hidangan Karibia favoritnya. Ia menawarkan resep sofrito ramah ginjal, bumbu dasar yang kaya rasa dari paprika, bawang bombai, bawang putih, dan minyak yang digunakan dalam banyak hidangan.","16","2 sendok makan",
["1 paprika hijau","1/2 bawang bombai ukuran sedang","8 siung bawang putih","3/4 cangkir paprika merah panggang kalengan","1 cangkir daun ketumbar segar (cilantro)","1 lembar daun recao (tersedia di pasar bahan makanan Hispanik)","1/3 cangkir air","1/4 cangkir minyak zaitun"],
["Buang biji paprika. Potong paprika dan bawang bombai menjadi potongan besar.","Masukkan paprika hijau, bawang bombai, dan bawang putih ke dalam blender atau food processor.","Bilas paprika panggang, lalu tambahkan paprika merah panggang, cilantro, daun recao, air, dan minyak zaitun ke dalam food processor.","Haluskan hingga kental seperti saus. Tambahkan lebih banyak air untuk mendapatkan kekentalan yang diinginkan."],
["Tambahkan 2 sendok makan Sofrito pada hidangan daging dan nasi untuk menambah rasa dan bumbu.","Satu paprika hijau setara dengan 3/4 cangkir saat dicincang.","Carilah daun recao di pasar bahan makanan Hispanik. Daun salam dapat digunakan sebagai pengganti recao jika tidak tersedia.","3/4 cangkir paprika merah kalengan kira-kira 4 ons. Paprika ini dijual dalam kaleng atau toples berbagai ukuran. Bilas untuk menghilangkan sebagian natrium. Periksa label Informasi Nilai Gizi dan pilih merek dengan natrium paling sedikit.","Dapat disimpan di lemari es selama sekitar 1 minggu."],
["1/2 lemak"]))
L.append(T(1002726,"Semur Daging Sapi dan Kentang","Semur Daging Sapi dan Kentang adalah hidangan ramah ginjal yang mengenyangkan, mudah dibuat, dan enak dipanaskan kembali jika ada sisa.","2","1/2 resep",
["5 ons (150 gram) daging sapi tanpa lemak","1 sendok makan seledri","1 tangkai rosemary","1 sendok makan mentega","2 sendok makan minyak sayur","1/2 cangkir tomat","2 kentang sabanera ukuran sedang","1/8 sendok teh lada"],
["Potong dadu daging sapi, cincang halus seledri, dan lepaskan daun rosemary dari batangnya. Lelehkan mentega dengan 2 sendok makan minyak sayur dalam panci. Masukkan rosemary dan seledri lalu tumis selama beberapa menit. Masukkan daging sapi yang sudah dipotong dadu dan masak hingga kecokelatan di semua sisi.","Tambahkan tomat kupas yang dicincang halus dan 1/4 cangkir air panas, lalu didihkan perlahan dengan panci tertutup selama sekitar 1-1/4 jam.","Sementara itu, kupas dan potong dadu kentang. Letakkan dalam panci besar dan tutupi seluruhnya dengan air. Rebus kentang hingga mendidih lalu tiriskan. Ulangi proses perebusan. Tiriskan.","Sepuluh menit sebelum mengangkat semur dari api, masukkan kentang dan aduk rata semuanya. Sajikan selagi masih panas mengepul."],
["Merebus kentang dua kali mengurangi kalium."],
["2 daging","1 pati","1 sayuran, kalium tinggi","2 lemak"]))
L.append(T(1002729,"Muffin Jagung Manis Ringan","Cobalah muffin jagung manis ringan ini saat Anda menginginkan roti yang ramah ginjal.","12","1 muffin",
["1 cangkir tepung terigu serbaguna","1 cangkir tepung jagung polos, putih atau kuning","1/4 cangkir gula","2 sendok teh soda kue","1/2 cangkir pengganti telur cair","1 cangkir susu beras tanpa pengayaan","2 sendok makan mentega tawar, dilelehkan, atau 2 sendok makan minyak kanola"],
["Panaskan oven terlebih dahulu hingga 400° F.","Dalam mangkuk, campurkan tepung terigu, tepung jagung, gula, dan baking powder.","Dalam mangkuk lain, campurkan pengganti telur, susu beras, dan mentega cair.","Aduk bahan kering ke dalam bahan basah hanya sampai lembap.","Isi cetakan muffin yang diolesi lemak atau dialasi kertas hingga 2/3 penuh.","Panggang selama 15 hingga 20 menit atau sampai tusuk gigi yang ditusukkan keluar bersih.","Sajikan hangat."],
["Menggunakan pengganti telur sebagai ganti telur dan susu beras sebagai ganti susu mengurangi fosfor dari 130 mg menjadi 100 mg. Baking powder menambahkan 76 mg fosfor pada setiap muffin. Batasi porsi Anda satu muffin.","Jangan mengganti dengan tepung jagung swa-naik (self-rising), karena kandungan fosfornya lebih tinggi.","Bekukan sisa muffin dan panaskan kembali nanti sebagai tambahan cepat untuk hidangan.","Untuk membuat roti jagung dalam wajan, bukan muffin, gunakan wajan besi cor ukuran sedang dan kurangi gula menjadi 2 sendok makan."],
["1-1/2 pati"]))
L.append(T(1002733,"Semur Ayam ala Pesisir","Ini adalah resep semur ayam ala pesisir yang ramah ginjal. Hidangan ini menggunakan paha ayam, paprika merah, seledri, dan terong yang dibumbui dengan oregano dan bawang putih.","2","1 paha utuh ayam ukuran sedang (100 g)",
["2 paha utuh ayam ukuran sedang","2 siung bawang putih","1 paprika merah","1 batang daun bawang","1 bawang merah kecil","1/2 batang seledri","1 terong kecil","1 lembar daun oregano kering"],
["Tuangkan 1/2 liter air ke dalam wajan.","Buang kulit paha utuh ayam dan masukkan ke dalam wajan.","Memarkan bawang putih. Cincang halus semua bahan yang tersisa dan masukkan ke dalam ayam.","Masak dengan api kecil selama 30 menit.","Sajikan ayam dengan kuah semur yang terbentuk."],
["Gantilah paha ayam dengan dada ayam jika diinginkan."],
["2 daging","1-1/2 sayuran, kalium tinggi"]))
L.append(T(1002746,"Pinwheel Tortilla","Adakan pesta dengan Pinwheel Tortilla untuk orang yang menjalani diet dialisis. Resep ramah ginjal ini akan menerbitkan selera Anda.","4","3 potong",
["1/2 cangkir krim keju kocok","2 tortilla tepung ukuran burrito","1/2 cangkir daun bayam mentah cincang","2 sendok makan penuh bawang bombai cincang","2 sendok makan penuh paprika cincang","1/2 cangkir nanas hancur","3 ons dada kalkun matang tanpa olahan, dipotong dadu kecil","1 sendok teh ketumbar kering (cilantro)"],
["Oleskan krim keju pada setiap tortilla hingga menutupi. Taburi dengan ketumbar kering.","Masukkan bahan-bahan yang tersisa ke dalam mangkuk dan campur.","Bagi campuran bahan menjadi 2 porsi. Letakkan setengahnya pada setiap tortilla dan gulung dengan kencang.","Potong kedua ujungnya dan potong setiap gulungan menjadi 6 potong."],
["Bungkus gulungan yang belum dipotong dengan plastik pembungkus dan dinginkan di lemari es sampai siap diiris dan disajikan.","Bandingkan merek tortilla dan pilih yang natriumnya paling rendah."],
["1 daging","1 pati","1/2 sayuran, kalium rendah","1 lemak"]))
L.append(T(1002750,"Samosa ala Kolombia","Segitiga dari India yang ramah ginjal ini adalah pilihan lezat untuk hidangan Anda berikutnya.","6","1 samosa (80 gram)",
["300 gram daging has luar sapi tanpa lemak","1 bawang bombai ukuran sedang","1 bawang merah","1 sendok makan (15 mL) minyak sayur","1 tangkai timi","1 sendok teh bubuk kari","1/2 sendok teh lada","6 lembar puff pastry atau adonan filo","1 telur ukuran sedang","1 tangkai ketumbar segar (cilantro)","2 kenari","1/2 sendok teh bubuk cabai","1/8 sendok teh bubuk bawang putih","2 sendok makan (30 mL) air perasan lemon"],
["Cincang daging sapi dan bawang, lalu tumis dengan satu sendok makan minyak dan timi hingga kecokelatan.","Angkat dari api dan tambahkan bubuk kari dan lada.","Ambil selembar kulit pastry dan bentuk kerucut segitiga dengan melipat tepinya ke arah dalam, rekatkan dengan telur kocok dan sisakan satu sisi terbuka untuk diisi.","Isi dengan campuran daging sapi lalu rekatkan.","Panaskan minyak dan goreng samosa hingga cokelat keemasan.","Untuk membuat saus ketumbar, cincang halus ketumbar dan kenari. Campurkan dengan bubuk cabai, bubuk bawang putih, dan air perasan lemon dalam mangkuk kecil.","Sajikan panas dengan saus ketumbar."],
["Samosa adalah pastel berbentuk segitiga, makanan tradisional India."],
["2 daging","1/2 sayuran, kalium rendah"]))
L.append(T(1002763,"Salad Pedesaan","Ahli gizi DaVita, Jennie, memiliki pasien yang menyukai resep salad telur sederhananya, dan Anda pasti akan menyukainya juga. Cobalah dalam sandwich, di atas salad, atau di atas biskuit rendah natrium sebagai camilan protein berkualitas tinggi.","2","1/2 salad",
["2 lembar daun selada romaine","1/2 lemon","1/2 bawang bombai","3/4 wortel kecil","2 sendok makan jagung manis","2 sendok makan minyak sayur","1-1/2 sendok makan air perasan lemon","lada secukupnya"],
["Cuci daun selada. Tiriskan dan potong kecil-kecil.","Didihkan 2 cangkir air dalam panci. Setelah mendidih, angkat panci dari kompor dan tambahkan air perasan setengah lemon, lalu masukkan bawang bombai dan diamkan selama 10 menit. Setelah 10","menit, angkat bawang, biarkan dingin dan potong berbentuk bulan sabit.","Potong wortel menjadi potongan korek api (julienne).","Dalam wajan, tumis butiran jagung hingga keemasan dan empuk. Biarkan dingin.","Dalam cangkir, campurkan 2 sendok makan minyak sayur, 1-1/2 sendok makan air perasan lemon, dan lada untuk membuat vinaigrette.","Dalam mangkuk, gabungkan semua bahan, termasuk jagung dan vinaigrette, lalu aduk rata.","Sajikan segera."],
["Anda dapat menggunakan cuka sebagai pengganti lemon untuk melunakkan rasa bawang bombai dan untuk vinaigrette.","Menambahkan vinaigrette bersifat opsional."],
["1 sayuran, kalium rendah","2 lemak"]))
L.append(T(1002782,"Salad Selada dan Mangga","Mulailah setiap hidangan dengan Salad Selada dan Mangga, perpaduan selada, mangga, dan yoghurt.","4","4 sendok makan",
["20 gram (3 lembar) selada","1/2 mangga Tommy","1 cangkir yoghurt tanpa gula","1 sendok makan pemanis tanpa kalori","3 sendok makan air perasan lemon"],
["Cuci selada dan potong menjadi irisan tipis.","Kupas mangga dan potong dadu kecil.","Dalam mangkuk terpisah, campurkan yoghurt tanpa gula dengan pemanis dan air perasan lemon.","Masukkan mangga dan selada ke dalam campuran yoghurt.","Aduk rata."],
["Anda dapat mengganti mangga dengan buah rendah kalium lain pilihan Anda."],
["1 buah, kalium sedang"]))
L.append(T(1002783,"Sup Ayam dan Nasi","Sup yang mengenyangkan ini dapat menghangatkan Anda pada hari yang dingin. Kentang adalah sayuran tinggi kalium, tetapi porsi yang dianjurkan membuat hidangan ini ramah ginjal.","6","1-1/4 cangkir (300 mL)",
["2 kentang ukuran sedang","1/2 cangkir wortel","1 siung bawang putih","1 batang daun bawang","5 paha ayam (masing-masing sekitar 60 gram)","1/2 cangkir kacang polong kupas","8 cangkir air","lada secukupnya","1/2 cangkir nasi putih","1/4 cangkir ketumbar segar (cilantro)"],
["Cuci kentang hingga bersih, kupas dan potong. Letakkan dalam panci, tutupi seluruhnya dengan air dan didihkan. Tiriskan dan ulangi prosesnya.","Kupas dan potong wortel. Cincang bawang putih dan daun bawang.","Buang tulang dan kulit ayam lalu bilas hingga bersih.","Masukkan semua bahan kecuali nasi dan ketumbar ke dalam panci bersama air.","Didihkan, lalu masak dengan api kecil selama 45 menit lagi.","Tambahkan nasi dan lanjutkan memasak selama 25 menit lagi.","Angkat ayam dari panci. Potong kecil-kecil dan masukkan kembali ke dalam panci.","Tambahkan lada secukupnya.","Sajikan dengan taburan ketumbar yang dicincang halus."],
["Untuk mengurangi kalium, rendam kentang yang sudah dikupas dan dipotong dalam semangkuk air, dan ganti air rendamannya beberapa kali. Kemudian masukkan ke dalam sup tanpa air rendamannya."],
["1 daging","1 pati","1/2 sayuran, kalium rendah"]))
L.append(T(1002787,"Smoothie Stroberi Tinggi Protein","Mencari camilan penambah kebugaran atau tambahan cepat untuk hidangan? Smoothie ini juga populer di kalangan anak muda yang modis dan peduli kesehatan. Ahli gizi DaVita, Judy dari Michigan, mempersembahkan Smoothie Stroberi Tinggi Protein.","2","3/4 cangkir",
["3/4 cangkir stroberi segar","1/2 cangkir putih telur","1/2 cangkir es batu","1 sendok makan gula"],
["Masukkan stroberi ke dalam blender dan haluskan hingga lembut.","Kocok putih telur hingga mengembang kaku.","Masukkan semua bahan dan lanjutkan memblender hingga halus.","Jika menggunakan buah beku, tambahkan 1/4 cangkir air sebagai ganti 1/2 cangkir es batu."][:3],
["Jika menggunakan buah beku, tambahkan 1/4 cangkir air sebagai ganti 1/2 cangkir es batu. Tingkat kebekuan buah menentukan seberapa penuh Anda dapat mengisi blender. Hasilnya juga akan lebih \"lembut\" daripada smoothie, sehingga sangat menyegarkan di hari yang panas.","Sesuaikan jumlah gula atau pemanis rendah kalori sesuai selera Anda."],
["1 daging","1 buah, kalium rendah"]))
L.append(T(1002790,"Salad Tropis","Ceplukan, apel, dan stroberi menjadi bintang salad buah tropis ini yang diciptakan oleh ahli gizi DaVita, Josefina dari Kolombia.","8","100 g",
["1/2 pon ceplukan (golden berry)","1 sendok teh mentega","1 cangkir gula","2 cangkir selada","2 apel hijau ukuran sedang","1/2 pon stroberi","5 sendok makan mayones rendah lemak"],
["Dalam wajan dengan api sedang, campurkan mentega, gula, dan dua cangkir air. Masukkan ceplukan yang dibelah dua dan masak hingga lunak dan campuran menjadi sirup encer. Diamkan beberapa menit.","Secara terpisah, potong selada menjadi irisan sangat tipis dan potong apel tanpa dikupas menjadi irisan tipis berbentuk bulan sabit. Potong stroberi menjadi irisan sedang.","Campur selada dan buah dengan mayones.","Siramkan sirup ceplukan di atas salad."],
["Anda dapat menyajikan salad ini dengan ayam atau ikan.","Jika diinginkan, Anda dapat mengganti gula pasir dengan pengganti gula."],
["1 buah, kalium rendah","1/2 lemak","1 kalori tinggi"]))
L.append(T(1002806,"Salad Festival","Perpaduan cita rasa ini akan memberi sentuhan baru pada perayaan Anda.","8","100 g",
["1 sayuran","2 lemak","1/2 pon ceplukan (golden berry)","1 sendok teh mentega","1 cangkir gula","2 cangkir selada","2 apel hijau ukuran sedang","1/2 pon stroberi","5 sendok makan mayones rendah lemak"],
["Dalam wajan dengan api sedang, campurkan mentega, gula, dan dua cangkir air. Masukkan ceplukan yang dibelah dua dan masak hingga lunak dan campuran menjadi sirup encer. Diamkan beberapa menit.","Secara terpisah, potong selada menjadi irisan sangat tipis dan potong apel tanpa dikupas menjadi irisan tipis berbentuk bulan sabit. Potong stroberi menjadi irisan sedang.","Campur selada dan buah dengan mayones.","Siramkan sirup ceplukan di atas salad."],
["Anda dapat menyajikan salad ini dengan ayam atau ikan.","Jika diinginkan, Anda dapat mengganti gula pasir dengan pengganti gula."],
["1 buah, kalium rendah","1/2 lemak","1 kalori tinggi"]))
L.append(T(1002816,"Sorbet Labu","Camilan dingin yang ramah ginjal ini dapat membantu di hari musim panas yang terik.","8","1 cangkir (250 mL)",
["500 gram (2 cangkir) labu segar (ahuyama)","1/2 liter (2 cangkir) air","1 liter (4 cangkir) susu skim","200 gram (1 cangkir) gula"],
["Cuci labu hingga bersih, kupas dan potong kecil-kecil.","Didihkan air.","Setelah air mendidih, masukkan labu dan masak hingga agak lunak.","Angkat dari api dan biarkan dingin.","Haluskan labu, susu, dan gula hingga kental dan lembut.","Dinginkan di lemari es selama 30 menit dan sajikan dalam keadaan sangat dingin."],
["Susunya dapat berupa susu skim atau susu bebas laktosa."],
["1 sayuran, kalium sedang","1 susu"]))
L.append(T(1002819,"Salsa Verde","Tomatillo, ketumbar, dan cabai jalapeño berpadu dengan bawang bombai, bawang putih, dan air perasan jeruk nipis untuk membuat Salsa Verde rendah natrium ini.","10","1/4 cangkir",
["6 tomatillo ukuran sedang (sekitar ½ pon)","1 cabai jalapeño ukuran sedang","1/2 bawang bombai putih atau kuning ukuran kecil","1 siung bawang putih","1/4 cangkir daun ketumbar segar (cilantro), dipadatkan","1/4 sendok teh garam","1/4 sendok teh lada hitam","1 sendok teh air perasan jeruk nipis"],
["Rendam tomatillo dalam mangkuk sedang berisi air selama 5 menit. Letakkan piring kecil di atas tomatillo agar tetap terendam. Selagi tomatillo direndam, alasi loyang berpinggir dengan aluminium foil dan panaskan broiler terlebih dahulu dengan rak 4 inci di bawah sumber panas.","Buang kulit ari dan tangkai dari tomatillo yang sudah direndam. Bilas sisa lengket pada kulitnya. Keringkan tomatillo dengan ditepuk-tepuk lalu belah dua.","Buang tangkai jalapeño dan potong menjadi empat bagian. Potong bawang bombai menjadi empat bagian.","Letakkan tomatillo dan jalapeño dengan sisi potongan menghadap ke bawah di atas loyang yang sudah disiapkan. Letakkan siung bawang putih dan potongan bawang bombai di atas loyang. Panggang dengan broiler selama 5 hingga 7 menit sampai muncul bintik-bintik kecil gosong atau kecokelatan. Sesuaikan waktunya sesuai kebutuhan dan awasi dengan saksama, karena dapat cepat gosong. Angkat dari oven.","Pindahkan dengan hati-hati sayuran yang telah dipanggang beserta sarinya ke food processor atau blender. Tambahkan ketumbar, air perasan jeruk nipis, garam, dan lada hitam.","Proses dengan fungsi pulse hingga halus tanpa potongan tomatillo yang besar. Hati-hati jangan sampai menjadi bubur. Salsa akan encer, tetapi akan mengental setelah didinginkan di lemari es selama beberapa jam."],
["Buang biji dan bagian putih dalam jalapeño untuk salsa yang tidak terlalu pedas, atau tambahkan satu jalapeño lagi untuk rasa lebih pedas.","Pilih tomatillo yang keras.","Salsa Verde dapat disimpan dalam wadah kedap udara di lemari es hingga satu minggu, atau di freezer untuk digunakan nanti.","Merendam tomatillo membantu menghilangkan sisa lengket dari kulitnya.","Sajikan hangat atau dingin di atas telur, taco, atau hidangan Meksiko favorit Anda."],
["1/2 sayuran, kalium rendah"]))
save(1,L)
