import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xid11')
from h import *
L=[]
L.append(T(4002784,"Burger Kalkun Jalapeno, Jeruk Nipis, dan Mozzarella Asap",None,None,None,
["1½ pon daging kalkun giling 2 sendok makan jalapeno cincang halus* Air perasan 2 jeruk nipis dan parutan kulit** 1 jeruk nipis 1 sendok makan lada hitam yang baru digiling 1 sendok makan saus Worcestershire rendah natrium 4 sendok makan minyak zaitun extra virgin ¾ cangkir mozzarella asap parut mozzarel"],
["SATU: Panaskan panggangan luar ruangan atau wajan panggang atau dalam wajan tumis antilengket besar dengan api sedang-besar, panaskan setengah minyak kanola dengan api sedang-besar (panggangan George Foreman® juga dapat digunakan). DUA: Dalam mangkuk berukuran sedang, campurkan 5 bahan pertama ditambah 2 sendok makan minyak zaitun. TIGA: Bentuk 6 patty burger berukuran sama dan olesi tipis dengan 2 sendok makan minyak zaitun yang tersisa. EMPAT: Masak burger selama 5-7 menit per sisi, dibalik satu kali, atau sampai mencapai suhu internal 165° F pada termometer instan. LIMA: Taburkan sekitar 2 sendok makan keju di atas setiap burger dan lelehkan dalam oven pemanggang roti atau oven yang diatur pada mode broil. ENAM: Sajikan setiap burger di atas roti burger yang dipanggang. (Jika menggunakan panggangan George Foreman®, setelah matang, cabut colokan panggangan dan tambahkan keju ke burger. Biarkan panggangan terbuka dan biarkan keju meleleh sedikit.) * Saat memegang atau memotong cabai pedas, sebaiknya kenakan sarung tangan plastik atau karet dan jangan menyentuh wajah Anda. Jika Anda tidak memakai sarung tangan, cuci tangan Anda dengan saksama dengan sabun dan air sebelum menyentuh wajah atau mata Anda."],
["** Untuk mengambil parutan kulit, pegang buah dengan stabil dan gerakkan alat parut (misalnya zester, pengupas, parutan kotak) perlahan maju mundur di atas kulit buah. Hati-hati untuk hanya mengambil lapisan kulit terluar yang berwarna, dan bukan bagian putih yang pahit."],
[]))
L.append(T(4002988,"Tiramisu Lemon",None,"8","1/10 resep",
["1 kemasan (7 ons) biskuit ladyfinger",("Sirup","½ cangkir air perasan lemon, diperas segar"),("Sirup","½ cangkir air"),("Sirup","½ cangkir gula pasir"),("Krim","1 cangkir krim kocok ringan (lite whipping cream)"),("Krim","¼ cangkir gula pasir"),("Krim","1 cangkir keju mascarpone"),("Krim","2 sendok makan air perasan lemon"),("Hiasan","1 sendok makan bubuk kakao")],
["Dalam panci kecil, didihkan air perasan lemon, air, dan gula. Aduk sampai gula larut. Angkat dari api dan biarkan dingin.","Dalam mangkuk, kocok krim dengan mixer listrik sampai mengembang. Tambahkan gula, keju mascarpone, dan air perasan lemon. Campur dengan hati-hati dan sisihkan.","Celupkan setengah biskuit, satu per satu, ke dalam sirup yang sudah dingin dan tata berdampingan dalam satu lapisan di dalam wadah persegi panjang (7\"×11\"). Saat mencelupkan biskuit pastikan dilakukan dengan cepat. Anda tidak ingin biskuit menjadi lembek dan hancur.","Tutupi lapisan biskuit dengan setengah campuran krim dari langkah 2.","Celupkan setengah biskuit lainnya ke dalam sirup dan buat lapisan baru di atas campuran krim. Akhiri dengan mengoleskan sisa campuran krim di atasnya.","Taburi bagian atas dengan bubuk kakao menggunakan saringan. Tutup dengan plastik wrap dan diamkan di lemari es selama 12 jam sebelum disajikan."],
[("Keju, silakan!","Dalam jumlah sedang, produk susu dapat dimakan sebagai bagian dari diet ramah ginjal. Keju, yoghurt, dan susu secara alami mengandung kalium dan fosfor, tetapi makanan ini juga menyediakan vitamin, mineral, dan sedikit protein yang bermanfaat sehingga penting untuk bekerja sama dengan ahli gizi terdaftar untuk menentukan sumber susu mana dan berapa banyak yang tepat bagi Anda.\n\nKeju adalah bahan serbaguna dalam banyak hidangan yang berbeda. Kandungan natrium, kalium, dan fosfor bervariasi tergantung pada jenis dan jumlah keju.\n\nKeju yang dianggap lebih rendah fosfor dan kalium umumnya yang lebih lunak seperti Brie, krim keju, mascarpone, dan cheddar tajam alami. Bacalah label, tetapi sebagian besar merek dari pilihan ini mengandung 200 miligram natrium atau kurang per porsi.\n\nKeju cottage sering dianjurkan sebagai camilan ramah ginjal. Batasi porsi Anda hingga setengah cangkir dan ingatlah bahwa makanan ini dapat lebih tinggi fosfor dan natrium jika dikonsumsi dalam jumlah lebih besar.\n\nKeju olahan dan olesan keju sebaiknya dimakan sangat jarang.")],
["1 Pati","3 Lemak","1 Karbohidrat"]))
L.append(T(4006743,"Dip Cabai-Jeruk Nipis dengan Pita Panggang",None,"8","4 Keripik + 1½ sdm Dip",
[("Dip","1/2 cangkir tahu sutra padat"),("Dip","2 sendok makan mayones"),("Dip","1/2 cangkir paprika merah panggang dari toples"),("Dip","1 sendok teh bubuk cabai"),("Dip","1 sendok teh bubuk bawang bombai"),("Dip","1 1/2 sendok makan air perasan jeruk nipis"),("Dip","3 sendok makan ketumbar segar cincang*"),("Keripik Pita","4 roti pita Yunani putih polos dari tepung terigu (diameter 6 1/2 inci)"),("Keripik Pita","3 sendok makan minyak zaitun"),("Keripik Pita","1 siung bawang putih, dimemarkan")],
["Panaskan oven terlebih dahulu hingga 300°F.","Untuk menyiapkan dip, masukkan semua bahan dip yang tercantum ke dalam blender atau food processor dan blender sampai halus, sekitar 30 detik.","Pindahkan ke mangkuk kecil, tutup dan dinginkan di lemari es minimal 30 menit.","Campurkan minyak zaitun dengan bawang putih dan oleskan pada roti pita.","Potong setiap roti pita menjadi 8 irisan segitiga, lalu letakkan irisan di atas loyang dan panggang selama 20 menit atau sampai keripik renyah, tetapi tidak cokelat.","Tata dip dan keripik pita di atas piring dan sajikan."],
["* dapat diganti dengan dill segar atau peterseli","Dip ini cocok disantap dengan sayuran mentah atau sebagai olesan sandwich.","Anda dapat menyimpan irisan pita dalam kaleng hingga seminggu.",("Tahu dan protein nabati","Mengonsumsi protein yang cukup adalah bagian penting dari diet ginjal. Asupan protein yang terlalu sedikit dapat menyebabkan kehilangan otot, sementara makan terlalu banyak membuat ginjal Anda bekerja lebih keras. Bekerja sama dengan ahli gizi terdaftar dapat membantu menentukan jumlah protein yang Anda butuhkan. Memasukkan berbagai sumber protein dari hewan dan tumbuhan dapat membuat diet Anda lebih menarik.\n\nTahu adalah salah satu contoh makanan tinggi protein dan rendah lemak yang dapat digunakan sebagai pengganti daging. Tahu dibuat dari dadih kedelai dan dapat dibeli dalam berbagai tekstur dari lembut hingga ekstra padat. Menurut Database Zat Gizi USDA, porsi ½ cangkir tahu padat mengandung 22 gram protein, 18 miligram natrium, 299 miligram kalium, dan 239 miligram fosfor. Gunakan tahu sebagai pengganti ayam untuk membuat nugget buatan sendiri, dalam burrito sebagai pengganti telur, atau dipanggang sebagai bagian dari sandwich atau salad.")],
["1 Pati","1 Lemak"]))
L.append(T(4014095,"Jari Ayam Dijon",None,"8","1/8 resep: 2 Potong",
["2 dada ayam (1 pon)",("Pelapis","1 telur"),("Pelapis","2 sendok makan mustard Dijon"),("Pelapis","1/4 sendok teh bubuk bawang putih"),("Pelapis","1/4 sendok teh lada hitam bubuk"),("Pelapis","1 cangkir remah roti panko"),("Pelapis","1 sendok teh minyak zaitun"),("Dip Dill","1/4 cangkir mayones"),("Dip Dill","1 sendok makan dill segar, dicincang"),("Dip Dill","1 sendok makan mustard Dijon"),("Dip Dill","1 sendok teh air perasan lemon")],
["Panaskan oven terlebih dahulu hingga 400°F.","Iris setiap dada ayam menjadi 8 potongan memanjang.","Dalam mangkuk, kocok telur, mustard, dan rempah.","Dalam mangkuk kedua, campurkan remah roti dengan minyak zaitun.","Lumuri setiap potongan ayam dengan campuran telur dan mustard.","Celupkan potongan ayam ke dalam remah roti sebelum meletakkannya di atas loyang antilengket.","Panggang selama 15–20 menit, balik jari ayam di tengah waktu.","Campurkan bahan dip dalam mangkuk kecil dan sajikan dengan jari ayam yang hangat."],
[],["2 Daging"]))
L.append(T(4015375,"Rillettes Ikan Nila",None,"4","1/4 resep",
[("Rillettes","¼ pon fillet ikan nila"),("Rillettes","1 telur besar"),("Rillettes","1 sendok makan ketumbar, dicincang halus"),("Rillettes","1 sendok makan bawang merah, dicincang halus"),("Rillettes","1 sendok makan air perasan lemon"),("Rillettes","1 sendok teh jahe, diparut"),("Rillettes","1 sendok teh mustard kering"),("Rillettes","1/8 sendok teh lada hitam"),("Rillettes","1 sendok teh minyak zaitun"),("Keripik Pita","2 roti pita putih (diameter 6.5 inci)"),("Keripik Pita","1 sendok makan minyak zaitun")],
["Dalam panci, didihkan 1 kuart air. Masukkan fillet ikan dan telur yang dipecahkan ke dalam air. Kecilkan api dan didihkan perlahan selama 6 menit sampai ikan matang dan telur terpoci.","Angkat keduanya dari air dan biarkan dingin.","Dalam mangkuk kecil, campurkan ikan dan telur dengan garpu. Tambahkan ketumbar, bawang, air perasan lemon, jahe, dan mustard. Bumbui dengan lada, tutup, dan simpan di lemari es selama 1 jam.","Panaskan oven terlebih dahulu hingga 300°F.","Oleskan minyak pada roti pita. Potong setiap roti pita menjadi 8 irisan segitiga.","Letakkan irisan, sisi berminyak menghadap ke atas, di atas loyang dan panggang selama 7 menit.","Sajikan keripik yang sudah dingin dengan rillettes ikan."],
[("Rillettes: cara lain menikmati ikan","Rillettes ikan adalah cara unik untuk menyajikan hidangan laut sebagai pengganti resep panggang atau bakar biasa. Ikan direbus dalam air mendidih perlahan dan setelah empuk, dicampur dengan bahan-bahan lezat lainnya untuk membentuk olesan. Rillettes dapat digunakan sebagai bagian dari hidangan pembuka, ditambahkan ke sandwich, dioleskan di atas biskuit atau irisan roti, atau dicampur ke dalam isian pasta. Saat membuat rillettes, pilih bahan yang lebih rendah natrium dan kalium.\n\nLemak tambahan: Pilih mentega atau margarin tanpa garam. Hindari juga lemak yang bahan pertamanya adalah minyak terhidrogenasi parsial untuk menurunkan lemak jenuh.\n\nLebih rendah garam: Ganti garam dengan rempah-rempah. Pilih lada hitam, daun salam, butir lada hitam, peterseli, bawang putih, dan cabai sesuai rasa yang Anda inginkan.\n\nTambahan sayuran: Masukkan sayuran dengan rasa kuat untuk menambah cita rasa. Pilih sedikit kucai, daun bawang prei, bawang merah kecil (shallot), dan bawang merah untuk ditambahkan ke rillettes Anda.\n\nSaran penyajian: Pertimbangkan bagaimana rillettes akan disajikan untuk menghindari garam dan kalium yang tidak diinginkan. Irisan baguette Prancis yang dipanggang atau biskuit tanpa garam dengan selapis tipis rillettes hanyalah beberapa saran.")],
["3 Daging Tanpa Lemak","1 Pati"]))
L.append(T(4017183,"Cupcake Angel Stroberi",None,"16 cupcake","1/16 resep (1 cupcake)",
["1 cangkir putih telur","½ cangkir gula putih*","1 sendok makan parutan kulit lemon","½ sendok teh ekstrak vanila","¾ cangkir gula bubuk, diayak","¾ cangkir tepung kue dan pastry, diayak",("Hiasan","2 cangkir krim kocok"),("Hiasan","16 stroberi, dicuci, dibuang tangkainya dan diiris")],
["Panaskan oven terlebih dahulu hingga 350°F dan alasi cetakan muffin dengan cup kertas.","Dalam mangkuk pencampur yang bersih, kocok putih telur sampai berbusa. Tambahkan gula putih perlahan dan lanjutkan mengocok sampai terbentuk puncak. Campurkan parutan kulit lemon dan ekstrak vanila.","Lipat dengan hati-hati gula bubuk dan tepung kue yang sudah diayak. Jangan dicampur berlebihan.","Tuang adonan angel food cake ke dalam cetakan muffin yang sudah dialasi dan panggang sekitar 25 menit atau sampai cupcake menjadi padat dan keemasan.","Setelah cupcake dingin, letakkan di lemari es. Hias setiap cupcake dengan irisan stroberi dan krim kocok sebelum disajikan."],
["* Untuk menurunkan kandungan karbohidrat Anda dapat menggunakan pengganti gula","Cupcake dapat disimpan di freezer. Letakkan dalam kantong freezer. Hias setelah dicairkan. 2017-04-11 2:06 PM",("Stroberi","Dengan begitu banyak batasan dalam diet ginjal, makan berbagai buah berwarna cerah penting untuk memastikan Anda mengonsumsi banyak zat gizi. Warna merah cerah buah beri berasal dari antioksidan yang secara alami dikandungnya. Makan stroberi membantu ginjal Anda bekerja dengan mengurangi peradangan dalam tubuh Anda.\n\nSetengah cangkir stroberi, atau sekitar 5 buah ukuran sedang, mengandung sekitar 120 mg kalium dan natrium serta fosfor dalam jumlah yang sangat rendah. Buah ini juga penuh vitamin C, mangan, folat, dan serat. Dengan rasa yang kaya, stroberi dapat ditambahkan ke hidangan apa pun. Pilih saat sarapan untuk ditaburkan di atas sereal panas atau dingin. Manjakan lidah Anda saat makan siang dengan menambahkan stroberi ke salad buah rendah kalium atau salad ayam. Nikmati saat makan malam sebagai tambahan salad hidangan utama atau marinade daging. Pilih stroberi sebagai camilan atau campurkan sebagai bagian dari smoothie untuk makanan penutup rendah kalori.")],
["1 Pati"]))
L.append(T(4028523,"Roti Nanas Cranberry",None,"12","1/12 resep",
["2 telur besar","1 cangkir gula putih","½ cangkir minyak kanola","½ sendok teh ekstrak vanila","1 ½ cangkir tepung terigu serbaguna","1 sendok teh soda kue","¼ sendok teh jahe bubuk","¼ sendok teh kayu manis bubuk","½ cangkir nanas hancur, kalengan dalam air","1 cangkir cranberry beku"],
["Panaskan oven terlebih dahulu hingga 350°F. Semprot loyang roti dengan semprotan masak antilengket.","Dalam mangkuk pencampur, masukkan telur, gula, minyak, dan vanila. Kocok bersama hingga tercampur.","Dalam mangkuk pencampur terpisah, ayak tepung, soda kue, jahe, dan kayu manis.","Tambahkan bahan kering ke dalam campuran telur. Aduk rata.","Tambahkan nanas hancur dan cranberry beku lalu aduk hingga tercampur.","Tuang campuran nanas ke dalam loyang roti (4\"× 8\").","Panggang selama satu jam 15 menit atau sampai tusuk gigi yang ditusukkan di tengah roti keluar bersih. Angkat dari oven dan biarkan dingin.","Tutup dan simpan pada suhu ruang."],
[("Memasukkan nanas ke dalam diet ginjal Anda","Memilih makanan dengan berbagai rasa dan tekstur penting untuk menjaga diet ginjal Anda tetap menarik. Buah menawarkan pilihan rasa, serat, dan vitamin dan merupakan makanan padat gizi. Studi terbaru menunjukkan bahwa diet yang lebih tinggi buah dan sayuran mungkin baik untuk kesehatan ginjal, tetapi diperlukan lebih banyak penelitian untuk rekomendasi spesifik.\n\nNanas adalah makanan rendah kalium yang sangat baik untuk diet ginjal Anda. Satu cangkir potongan nanas segar mengandung kurang dari 200 mg kalium dan natrium serta fosfor dalam jumlah minimal.\n\nNanas dapat dimasukkan ke dalam banyak hidangan yang berbeda. Gunakan nanas sebagai topping sarapan atau sebagai bagian dari fruit cup rendah kalium. Taburi sandwich dengan nanas untuk menciptakan rasa dan tekstur yang berbeda sebagai pengganti tomat tinggi kalium. Atau tambahkan nanas ke hidangan tumisan atau masakan slow cooker agar hidangan Anda lebih menarik. Makanan penutup seperti muffin atau smoothie adalah cara hebat lainnya untuk menambahkan rasa nanas segar.")],
["2 Pati","2 Lemak"]))
L.append(T(4035847,"Terong Provençal",None,"2","1/4 terong + 1/3 cangkir nasi",
["1 terong ukuran sedang","2 sendok makan minyak zaitun","2 sendok makan minyak zaitun","¼ cangkir bawang bombai, dicincang","½ cangkir paprika merah, dipotong dadu","½ cangkir paprika kuning, dipotong dadu","¼ cangkir air","½ pon daging sapi giling ekstra rendah lemak","2 siung bawang putih, dicincang","2 sendok teh paprika bubuk","1 sendok makan cuka anggur","1 sendok teh oregano kering","¼ cangkir keju cheddar, diparut","½ cangkir beras putih, kering"],
["Panaskan oven terlebih dahulu hingga 400°F. Alasi loyang dengan kertas roti.","Potong terong menjadi dua memanjang. Oleskan 1 sendok makan minyak zaitun pada permukaan potongan setiap belahan. Letakkan belahan terong, sisi potongan menghadap ke bawah, di atas loyang dan panggang sekitar 35 menit. Setelah matang, bagian dalam terong seharusnya lunak sementara bagian luarnya tetap mampu mempertahankan bentuknya.","Dalam wajan antilengket, panaskan minyak zaitun dengan api sedang. Masukkan bawang bombai dan paprika lalu tumis selama 5 menit, sesekali diaduk. Tambahkan air dan lanjutkan memasak sampai cairan menguap. Pindahkan ke piring dan sisihkan.","Dalam wajan yang sama, masukkan daging sapi giling, bawang putih, dan paprika bubuk lalu tumis sampai daging kecokelatan. Tambahkan cuka, oregano, bawang bombai dan paprika dari langkah 3. Campurkan semuanya dan angkat wajan dari api.","Masak nasi sesuai petunjuk pada kemasan.","Angkat belahan terong dari oven. Keluarkan daging terong dengan hati-hati menggunakan sendok sambil menyisakan kulit dan selapis tipis daging di bagian dalam agar belahan terong dapat menahan isian.","Tambahkan ¼ cangkir daging terong ke dalam campuran isian dari langkah 4 dan aduk hingga tercampur. Buang sisa daging terong.","Bagi isian di antara dua belahan terong dan taburi dengan keju parut. Masukkan kembali belahan terong ke dalam oven selama beberapa menit sampai keju meleleh.","Potong belahan terong menjadi 4 porsi dan sajikan dengan nasi yang sudah dimasak."],
[("Pengganti daging hamburger","Mengonsumsi jumlah protein yang tepat pada penyakit ginjal kronis penting untuk menjaga kesehatan yang baik. Banyak orang dengan fungsi ginjal yang menurun juga memiliki masalah jantung dan harus mengikuti diet sehat jantung, yaitu rendah lemak dan kolesterol. Bekerja sama dengan ahli gizi terdaftar dapat membantu menentukan kebutuhan protein spesifik Anda dan pilihan protein terbaik bagi kesehatan Anda. Jika Anda seharusnya mengikuti diet sehat jantung, gunakan daging sapi giling ekstra rendah lemak. Anda juga dapat mempertimbangkan pengganti lainnya. Sumber protein nabati termasuk tahu giling atau burger sayuran. Jintan, bawang putih, dan lada hitam dapat menambah rasa yang sangat baik pada pilihan ini. Bacalah label produk dan pilih yang paling rendah natrium dan kalium. Ayam giling, kalkun, dan babi juga merupakan pilihan protein yang baik. Kemangi, bawang putih, sage, timi, dan savory kering hanyalah beberapa rempah untuk menambah rasa rendah natrium dan rendah kalium. Pilih daging giling segar tanpa tambahan garam dan rendah lemak sebagai pilihan yang sehat.")],
["2 Daging","1 1/2 Pati","1 Sayuran Kalium Lebih Rendah","1 Lemak"]))
L.append(T(4035983,"Tart Sarapan Sunny",None,"4","1/4 resep",
["4 cangkang puff pastry siap beli","1 sendok makan minyak zaitun","½ cangkir daun bawang prei, dicuci dan diiris","1 cangkir bayam muda","1/8 sendok teh lada hitam","4 sendok teh krim keju bawang putih & rempah*","4 telur"],
["Panaskan minyak dalam wajan kecil dengan api sedang. Tumis daun bawang prei sampai lunak, sekitar 5 menit. Tambahkan bayam muda dan lanjutkan menumis sampai layu. Bumbui dengan lada hitam.","Letakkan 4 cangkang di atas loyang. Pada dasar setiap cangkang, oleskan 1 sendok teh krim keju bawang putih & rempah. Bagi campuran bayam dan daun bawang prei ke dalam keempat cangkang, buat cekungan untuk telur. Pecahkan satu telur utuh ke dalam cekungan.","Panggang selama 15–20 menit atau sampai putih telur mengeras. Sajikan segera."],
["* Anda juga dapat menggunakan krim keju biasa dan membumbui dengan 1 sendok teh bawang putih cincang dan ¼ sendok teh dill","HARAP DIPERHATIKAN: Untuk foto ini koki menggunakan adonan puff pastry beku untuk membentuk cangkang yang lebih besar. Adonan ini biasanya lebih tinggi lemak daripada cangkang siap beli.",("Krim keju dapat menjadi pilihan keju rendah kalium","Menurunkan asupan makanan tinggi kalium adalah kunci saat menjalani diet ginjal Anda. Keju terdapat dalam banyak resep dan menambah rasa, penampilan, dan tekstur hidangan Anda. Keju menyediakan kalsium, protein, dan Vitamin D. Namun, penderita ginjal perlu mengonsumsinya secukupnya karena terlalu banyak akan menyebabkan asupan natrium, fosfor, dan kalium yang tinggi. Krim keju adalah pilihan kalium lebih rendah yang dapat digunakan bersama hidangan Anda. Satu porsi satu sendok makan mengandung sekitar 20 mg kalium. Memantau ukuran porsi memungkinkan Anda menikmati makanan ini sambil menjalani diet ginjal Anda. Cobalah krim keju sebagai isian dip hidangan pembuka, suguhan manis dalam makanan penutup dan hidangan sarapan, dressing dalam salad buah serta olesan untuk sandwich dan hidangan utama sehingga menjadikannya bahan makanan yang sangat serbaguna untuk diet ginjal Anda.")],
["1 Daging","1 Pati","4 Lemak"]))
L.append(T(4047168,"Ikan Goreng Rendah Natrium","Favorit dari Selatan","2",None,
["3 ons fillet ikan putih (pilihan Anda, seperti nila, cod, flounder, dll.), masing-masing 2","1 sendok makan mentega tawar atau minyak zaitun","Campuran Rempah: 1 sendok teh Mrs. Dash","original dan 1 sendok teh Mrs. Dash","bumbu bawang putih dan rempah"],
["Panaskan 1 sendok makan mentega tawar atau minyak kanola dalam wajan.","Masukkan fillet ikan (keringkan dulu dengan tisu dapur).","Bumbui kedua sisi ikan dengan campuran rempah.","Goreng dalam wajan selama 3 menit di setiap sisi.","Peras lemon segar di atas fillet ikan sesuai selera."],
[],[]))
save(10,L)
