from h import *
O=[]
O.append(R(6425743,
es=("Calabaza espagueti horneada dos veces","Disfrute de esta abundante receta de otoño. La calabaza espagueti es rica en nutrientes y tiene menos calorías y carbohidratos que la pasta. Es deliciosa, fácil de preparar y versátil.","8","2 cucharadas de salsa + 1/3 de taza de verduras",
["1 rociada de aceite en aerosol antiadherente, 0.25 g","2 calabazas espagueti pequeñas (de 1.5 libras cada una)","4 salchichas italianas de pollo precocidas (bajas en sodio, de 3 onzas cada una, en cubos)","3 tazas de salsa marinara de frasco (baja en sodio)","1/2 cucharadita de pimienta negra","1 cucharada de orégano fresco (picado)","1/2 taza de queso parmesano (rallado, dividido)"],
["Precaliente el horno a 375 grados F. Rocíe una bandeja para hornear con aceite en aerosol. Corte las calabazas por la mitad a lo largo y colóquelas con el lado cortado hacia abajo en la bandeja. Hornee por 45 minutos.","Quite las semillas de las calabazas y raspe la pulpa de la cáscara con un tenedor para formar hebras, manteniendo intacta la cáscara. Coloque cada cáscara de calabaza con el lado cortado hacia arriba en la bandeja.","Ponga las hebras de calabaza en un tazón grande. Agregue la salchicha, la salsa marinara, la pimienta negra y el orégano, y mezcle hasta combinar. Divida la mezcla en partes iguales entre las cáscaras de calabaza.","Cubra cada mitad de calabaza con 2 cucharadas de queso parmesano rallado. Hornee por 25 minutos, hasta que estén doradas. Corte cada cáscara de calabaza por la mitad para servir."],[],[]),
ar=("قرع السباغيتي المخبوز مرتين","استمتع بهذه الوصفة الخريفية المشبعة. قرع السباغيتي غني بالعناصر الغذائية وأقل في السعرات الحرارية والكربوهيدرات من المعكرونة. وهو لذيذ وسهل التحضير ومتعدد الاستخدامات.","8","2 ملعقة كبيرة صلصة + ⅓ كوب خضار",
["1 بخة من بخاخ طهي غير لاصق، 0.25 غرام","2 حبة قرع سباغيتي صغيرة (1.5 رطل لكل واحدة)","4 نقانق دجاج إيطالية مطهوة مسبقًا (قليلة الصوديوم، قطعة 3 أونصات، مقطّعة مكعبات)","3 كوب صلصة مارينارا من البرطمان (قليلة الصوديوم)","½ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة أوريغانو طازج (مفروم)","½ كوب جبن بارميزان (مبشور، مقسّم)"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190 درجة مئوية). ادهن صينية خبز ببخاخ الطهي. اقطع القرع إلى نصفين طوليًا وضعه على الصينية وجهه المقطوع إلى الأسفل. اخبزه لمدة 45 دقيقة.","أزل البذور من القرع واكشط اللب عن القشرة بشوكة ليتحول إلى خيوط، مع الحفاظ على القشرة سليمة. ضع كل قشرة قرع على الصينية وجهها المقطوع إلى الأعلى.","ضع خيوط القرع في وعاء كبير. أضف النقانق وصلصة المارينارا والفلفل الأسود والأوريغانو وقلّب حتى تمتزج. وزّع الخليط بالتساوي على قشور القرع.","غطِّ كل نصف قرع بملعقتين كبيرتين من جبن البارميزان المبشور. اخبزه لمدة 25 دقيقة حتى يصبح لونه ذهبيًا. اقطع كل قشرة قرع إلى نصفين للتقديم."],[],[])))
O.append(R(6425903,
ar=("خليط المكسرات بالكاري وجوز الهند","هذه وجبة خفيفة سريعة ومشبعة ممتازة عندما تحتاج إلى شيء تأخذه معك ولا يفسد. يمكنك تقسيمها إلى حصص من 2 ملعقة كبيرة في علب بحجم الوجبات الخفيفة للمساعدة في التحكم في الكمية.","24","2 ملعقة كبيرة",
["¼ ملعقة صغيرة مسحوق الكاري","1 بخاخ طهي غير لاصق","¼ كوب بذور عباد الشمس","3 ملعقة كبيرة رقائق جوز الهند المحلاة","¼ كوب رقائق الشوكولاتة","1 كوب لوز كامل محمص","1½ كوب فول سوداني غير مملح"],
["في علبة بلاستيكية متوسطة، ضع اللوز والفول السوداني ورقائق الشوكولاتة وبذور عباد الشمس وجوز الهند. رش الخليط بالتساوي ببخاخ الطهي ثم رش مسحوق الكاري. ضع الغطاء على العلبة البلاستيكية وهزّ المحتويات برفق لتمتزج جيدًا."],[],[])))
O.append(R(6425972,
es=("Ensalada de tempeh a la parrilla con barbacoa","Disfrute de los sabores intensos y ahumados de esta ensalada de tempeh sellado con barbacoa, un plato vibrante que se ajusta al plan de comidas vegano. El tempeh a la parrilla se marina en una salsa barbacoa sabrosa y se sirve sobre una cama fresca de verduras de hoja, cubierto con verduras crujientes y un aderezo ácido. Es una combinación perfecta de texturas y sabores, ideal para una comida vegana satisfactoria.","4","3 tazas de ensalada de verduras, 1/2 taza de tempeh y pimientos",
["1 paquete de tempeh (8 onzas)","1 pimiento rojo (en rodajas finas)","3 onzas de salsa barbacoa (sin azúcar añadida)","2 cucharaditas de aceite de oliva","1 cabeza de lechuga romana (picada)","1 pepino inglés (en rodajas finas en forma de media luna)","1 taza de tomates cherry (partidos por la mitad)","1/3 de taza de aderezo Catalina para ensalada sin grasa"],
["Corte el tempeh a lo ancho en tiras delgadas y colóquelo en un tazón mediano. Agregue los pimientos y la salsa barbacoa al tazón con el tempeh y mezcle con suavidad para cubrir.","Caliente una sartén grande a fuego medio-alto.","Cuando la sartén esté caliente, agregue el aceite y gire para cubrir el fondo. Agregue el tempeh y los pimientos en una sola capa y cocine, volteando una vez, hasta que el tempeh esté dorado y caliente, de 4 a 5 minutos. Retire del fuego.","Para armar las ensaladas, divida la lechuga romana, el pepino y los tomates entre platos o tazones. Cubra con el tempeh a la barbacoa y los pimientos, y rocíe con el aderezo."],[],[]),
ar=("سلطة التمبيه المشوي بالباربكيو","استمتع بالنكهات القوية والمدخنة لسلطة التمبيه المشوي بالباربكيو، وهي طبق نابض بالحياة يتماشى مع النمط الغذائي النباتي. يُتبّل التمبيه المشوي في صلصة باربكيو منعشة ويُقدَّم على طبقة من الخضار الورقية الطازجة، مغطى بخضار مقرمشة وصلصة حامضة. إنه مزيج مثالي من القوام والنكهات، ومناسب لوجبة نباتية مشبعة.","4","3 كوب سلطة خضار، ½ كوب تمبيه وفلفل",
["1 عبوة تمبيه (8 أونصات)","1 حبة فلفل رومي أحمر (مقطّعة شرائح رفيعة)","3 أونصة صلصة باربكيو (بدون سكر مضاف)","2 ملعقة صغيرة زيت زيتون","1 رأس خس روماني (مفروم)","1 حبة خيار إنجليزي (مقطّعة شرائح رفيعة على شكل أنصاف أقمار)","1 كوب طماطم كرزية (مقطوعة إلى نصفين)","⅓ كوب صلصة سلطة كاتالينا خالية من الدسم"],
["قطّع التمبيه عرضيًا إلى شرائح رفيعة وضعه في وعاء متوسط. أضف الفلفل الرومي وصلصة الباربكيو إلى وعاء التمبيه وقلّب برفق ليتغطى.","سخّن مقلاة كبيرة على نار متوسطة إلى عالية.","عندما تسخن المقلاة، أضف الزيت ودوّره ليغطي القاع. أضف التمبيه والفلفل الرومي في طبقة واحدة واطهِ مع قلبها مرة واحدة حتى يصبح التمبيه بنيًا وساخنًا، من 4 إلى 5 دقائق. ارفعها عن النار.","لتجميع السلطات، وزّع الخس الروماني والخيار والطماطم على أطباق أو أوعية. غطِّها بالتمبيه بالباربكيو والفلفل، ثم رش الصلصة فوقها."],[],[])))
O.append(R(6426164,
es=("Poppers de jalapeño envueltos en tocino de pavo","Estos bocadillos picantes, cremosos y envueltos en tocino son un éxito seguro entre los invitados.","20","1 popper",
["1 rociada de aceite en aerosol antiadherente, 0.25 g","10 chiles jalapeños medianos","3/4 de taza de queso crema light","1 salchicha (3 onzas) de pollo estilo andouille precocida (en cubos)","10 lonchas de tocino de pavo"],
["Precaliente el horno a 375 grados F. Rocíe una bandeja para hornear con aceite en aerosol y reserve.","Ponga los chiles en una sartén grande para saltear con una pulgada de agua y cocine a fuego alto. Cuando hierva, apague el fuego y tape. Deje que los chiles se cuezan al vapor durante 10 minutos.","Retire los chiles de la sartén y deje que se enfríen hasta poder tocarlos. Corte cada chile por la mitad a lo largo y quite las venas y las semillas (si le gusta picante, déjelas o quite solo algunas). NOTA: Use guantes o una bolsa de sándwich para protegerse las manos al manipular los chiles. Lávese las manos de inmediato después.","Coloque los chiles con el lado cortado hacia arriba en una bandeja para hornear.","En un tazón pequeño, mezcle el queso crema y la salchicha en cubos. Rellene cada mitad de chile con 1 cucharada de la mezcla de queso crema.","Corte cada loncha de tocino de pavo por la mitad a lo largo. Envuelva cada chile con una tira de tocino de pavo y colóquelo con la unión hacia abajo en la bandeja, o sujete el tocino con un palillo.","Hornee los poppers por 20 minutos. Deje que se enfríen a temperatura ambiente antes de servir."],[],[]),
ar=("بوبرز الهالابينو الملفوفة بلحم الديك الرومي المقدد","هذه الحلويات الحارة والكريمية الملفوفة بالبيكون ستنال إعجاب الجميع بلا شك.","20","1 بوبر",
["1 بخة من بخاخ طهي غير لاصق، 0.25 غرام","10 حبة فلفل هالابينو متوسطة","¾ كوب جبن كريمي خفيف","1 قطعة (3 أونصات) نقانق دجاج مطهوة مسبقًا على طريقة الأندوي (مقطّعة مكعبات)","10 شريحة لحم ديك رومي مقدد"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190 درجة مئوية). ادهن صينية خبز ببخاخ الطهي وضعها جانبًا.","ضع حبات الفلفل في مقلاة عميقة كبيرة فيها 1 بوصة من الماء واطهها على نار عالية. عندما يغلي الماء، أطفئ النار وغطِّ المقلاة. اترك الفلفل يتبخر لمدة 10 دقائق.","أخرج الفلفل من المقلاة واتركه حتى يبرد بما يكفي لتلمسه. اقطع كل حبة فلفل إلى نصفين طوليًا وأزل الأضلاع والبذور (إذا كنت تحب الطعم الحار، اترك هذه الأجزاء أو أزل بعضها فقط). ملاحظة: ارتدِ قفازات أو استخدم كيس ساندويتش لحماية يديك أثناء التعامل مع الفلفل. اغسل يديك فورًا بعد ذلك.","ضع حبات الفلفل على صينية الخبز وجهها المقطوع إلى الأعلى.","في وعاء صغير، اخلط الجبن الكريمي مع النقانق المقطّعة مكعبات. املأ كل نصف فلفل بملعقة كبيرة من خليط الجبن الكريمي.","اقطع كل شريحة من لحم الديك الرومي المقدد إلى نصفين طوليًا. لفّ كل حبة فلفل بشريحة من اللحم المقدد وضعها على صينية الخبز وجهة الالتحام إلى الأسفل، أو ثبّت اللحم المقدد بعود أسنان.","اخبز البوبرز لمدة 20 دقيقة. اتركها لتبرد إلى درجة حرارة الغرفة قبل التقديم."],[],[])))
O.append(R(6427973,
ar=("كرات اللحم المطهوة ببطء بالأرز البني","هذه الوصفة من كرات اللحم إضافة رائعة إلى وجبة مشبعة. قدّمها مع طبق جانبي من الخضار لتحصل على مزيج لا يُضاهى.","6","2 كرة لحم",
["½ كوب أرز بني (مطهو، بارد)","1 كوب بصل (مفروم)","1 ملعقة صغيرة بابريكا مدخنة","1 ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة مسحوق الثوم","1 رطل لحم بقري مفروم (قليل الدهن، 95% على الأقل)","1 بيضة (مخفوقة)","16 أونصة عصير خضار (قليل الصوديوم)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175 درجة مئوية).","ضع جميع المكونات ما عدا عصير الخضار في وعاء واخلطها جيدًا. شكّل الخليط على هيئة 12 كرة لحم.","ضع كرات اللحم في طبق خبز صغير وأضف عصير الخضار واخبزها لمدة 30 دقيقة.","قدّمها مع سلطة خضراء متبّلة بقليل من زيت الزيتون وعصير الليمون، إن رغبت."],[],[])))
O.append(R(6428942,
es=("Pizza de champiñones y arúgula","Las minipizzas son fáciles y divertidas de preparar con un pan delgado para sándwich y sus ingredientes favoritos.\n\nEncuentre esta receta y más en The Diabetes Superfoods Cookbook and Meal Planner.","6","1 pizza (1/2 pan delgado para sándwich)",
["4 dientes de ajo (picados, divididos)","1/4 de taza de cebolla morada (en cubos)","8 onzas de champiñones blancos (en rodajas)","2 cucharaditas de aceite de oliva","3 tazas de arúgula (sin apretar)","1/4 de taza más 1 cucharada de queso ricotta parcialmente descremado","1/8 de cucharadita de pimienta blanca","3 panes delgados para sándwich integrales (abiertos por la mitad)","3 cucharadas de queso mozzarella (reducido en grasa, rallado)"],
["En una sartén, saltee 2 dientes de ajo picados, la cebolla y los champiñones en el aceite de oliva durante unos 10 minutos, o hasta que los champiñones estén dorados.","En un procesador de alimentos, combine la arúgula, el ricotta, 2 dientes de ajo enteros y la pimienta blanca, y pulse hasta obtener una mezcla suave.","Coloque 6 mitades de pan delgado en una bandeja para hornear. Agregue 1 cucharada de la mezcla de arúgula a cada mitad de pan. Cubra con la mezcla de champiñones y el queso mozzarella rallado, repartiéndolos en partes iguales entre las seis pizzas.","Gratine (broil) durante 5 minutos en el horno a temperatura baja, hasta que el queso se derrita."],[],[]),
ar=("بيتزا الفطر والجرجير","البيتزا المصغرة سهلة وممتعة التحضير باستخدام خبز الساندويتش الرقيق والإضافات التي تفضلها.\n\nتجد هذه الوصفة والمزيد في كتاب The Diabetes Superfoods Cookbook and Meal Planner.","6","1 بيتزا (½ خبز ساندويتش رقيق)",
["4 فص ثوم (مفروم، مقسّم)","¼ كوب بصل أحمر (مقطّع مكعبات)","8 أونصة فطر أبيض (شامبينيون) (مقطّع شرائح)","2 ملعقة صغيرة زيت زيتون","3 كوب جرجير (غير مكبوس)","¼ كوب بالإضافة إلى 1 ملعقة كبيرة جبن ريكوتا قليل الدسم","⅛ ملعقة صغيرة فلفل أبيض","3 رغيف خبز ساندويتش رقيق من القمح الكامل (مفتوح إلى نصفين)","3 ملعقة كبيرة جبن موزاريلا (قليل الدسم، مبشور)"],
["في مقلاة، قلّب فصّي ثوم مفرومين مع البصل والفطر في زيت الزيتون لمدة 10 دقائق تقريبًا أو حتى يصبح الفطر ذهبيًا.","في محضّر الطعام، اخلط الجرجير والريكوتا وفصّي ثوم كاملين والفلفل الأبيض وشغّله بالنبض حتى يصبح الخليط ناعمًا.","ضع 6 أنصاف من خبز الساندويتش الرقيق على صينية خبز. أضف 1 ملعقة كبيرة من خليط الجرجير على كل نصف. غطِّها بخليط الفطر والموزاريلا المبشورة، مع توزيعها بالتساوي على البيتزا الست.","اشوِها (برويل) لمدة 5 دقائق في الفرن على حرارة منخفضة حتى يذوب الجبن."],[],[])))
O.append(R(6429648,
es=("Wraps de lechuga con tacos de tofu desmenuzado","Disfrute de estos vibrantes y sabrosos wraps de lechuga con tacos de tofu desmenuzado, una versión fresca de un clásico que se ajusta al plan de comidas vegano. El tofu desmenuzado se sazona con especias de taco y se envuelve en hojas de lechuga crujientes, cubierto con verduras frescas. Es una comida ligera, sabrosa y baja en carbohidratos, perfecta para cualquier hora del día.","4","3 wraps de lechuga, 3/4 de taza de relleno",
["1 lima","1/2 taza de cebolla amarilla (en cubos)","14 onzas de tofu extra firme (escurrido y prensado)","1 pimiento rojo (en cubos pequeños)","1 pimiento amarillo pequeño (en cubos pequeños)","1 cucharada de chile en polvo","1/2 cucharadita de comino","1/2 cucharadita de orégano seco","1/2 cucharadita de ajo en polvo","1/2 cucharadita de cebolla en polvo","1/2 cucharadita de sal kosher","1/4 de cucharadita de pimienta negra","1 cabeza de lechuga mantequilla (con las hojas separadas)","1/2 taza de salsa","1/4 de taza de cilantro fresco (picado)"],
["Ralle la cáscara de la lima y exprima el jugo en un tazón pequeño; reserve.","Caliente una sartén a fuego medio-alto. Cuando esté caliente, agregue el aceite y gire para cubrir el fondo. Agregue la cebolla y cocine, revolviendo con frecuencia, hasta que esté suave y dorada, de 2 a 3 minutos.","Desmenuce el tofu con los dedos directamente en la sartén. Agregue la mezcla de lima, el pimiento, el chile en polvo, el comino, el orégano, el ajo en polvo, la cebolla en polvo, la sal y la pimienta. Revuelva para combinar.","Cocine, revolviendo con frecuencia, hasta que el tofu se dore y las verduras se ablanden, de 8 a 10 minutos.","Separe la lechuga en hojas. Apile las hojas de dos en dos para cada wrap sobre los platos. Rellene cada wrap con tofu, salsa y cilantro."],[],[]),
ar=("لفائف الخس بتاكو التوفو المفتت","استمتع بلفائف الخس النابضة بالنكهة بتاكو التوفو المفتت، وهي لمسة جديدة على طبق كلاسيكي تتماشى مع النمط الغذائي النباتي. يُتبّل التوفو المفتت بتوابل التاكو المنعشة ويُلف في أوراق خس مقرمشة ويُغطى بخضار طازجة. إنها وجبة خفيفة وشهية وقليلة الكربوهيدرات، مثالية في أي وقت من اليوم.","4","3 لفائف خس، ¾ كوب حشوة",
["1 حبة ليمون أخضر","½ كوب بصل أصفر (مقطّع مكعبات)","14 أونصة توفو صلب جدًا (مصفى ومعصور)","1 حبة فلفل رومي أحمر (مقطّعة مكعبات صغيرة)","1 حبة فلفل رومي أصفر صغيرة (مقطّعة مكعبات صغيرة)","1 ملعقة كبيرة مسحوق الفلفل الحار","½ ملعقة صغيرة كمون","½ ملعقة صغيرة أوريغانو مجفف","½ ملعقة صغيرة مسحوق الثوم","½ ملعقة صغيرة مسحوق البصل","½ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","1 رأس خس زبدة (بعد فصل الأوراق)","½ كوب صلصة سالسا","¼ كوب كزبرة خضراء طازجة (مفرومة)"],
["اُبشر قشر الليمون الأخضر واعصره في وعاء صغير وضعه جانبًا.","سخّن مقلاة على نار متوسطة إلى عالية. عندما تسخن، أضف الزيت ودوّره ليغطي القاع. أضف البصل واطهه مع التقليب المستمر حتى يصبح طريًا وذهبيًا، من 2 إلى 3 دقائق.","فتّت التوفو بأصابعك في المقلاة. أضف خليط الليمون الأخضر والفلفل الرومي ومسحوق الفلفل الحار والكمون والأوريغانو ومسحوق الثوم ومسحوق البصل والملح والفلفل. قلّب لدمج المكونات.","اطهِ مع التقليب المستمر حتى يصبح التوفو ذهبيًا ويلين الخضار، من 8 إلى 10 دقائق.","افصل الخس إلى أوراق. كوّم الأوراق في أكوام من ورقتين لكل لفافة على الأطباق. املأ كل لفافة بالتوفو والسالسا والكزبرة الخضراء."],[],[])))
O.append(R(6431387,
es=("Semillas de cáñamo","Información nutricional de las semillas de cáñamo.","1","3 cucharadas",["3 cucharadas de semillas de cáñamo"],[],[],[]),
ar=("بذور القنب","المعلومات الغذائية لبذور القنب.","1","3 ملعقة كبيرة",["3 ملعقة كبيرة بذور القنب"],[],[],[])))
O.append(R(6432957,
es=("Rollitos de lenguado y verduras con cubierta de nuez y perejil","El lenguado es un pescado blanco de sabor suave y ligeramente dulce. Es bajo en grasa, contiene grasas omega 3 saludables para el corazón y es una buena fuente de proteína. Combinado con verduras y la cubierta sabrosa de nueces picadas, es una cena deliciosa, saludable y baja en carbohidratos.","4","2 rollitos de pescado + 1 taza de verduras",
["1 libra de filetes de pescado (unos 8 filetes delgados)","1/4 de cucharadita de pimienta negra","16 tallos de espárragos (cortados en trozos de 2 a 3 pulgadas)","2 zanahorias medianas (cortadas en palitos delgados, de unas 2 a 3 pulgadas de largo)","1/4 de taza de nueces","1/4 de taza de perejil de hoja plana (fresco)","1 cucharadita de jugo de limón","1 cucharadita de ralladura de limón","1 cucharada de pan molido panko","2 cucharaditas de aceite de oliva extra virgen (divididas)","3 dientes de ajo (divididos)","4 tazas de espinaca baby (picada)"],
["Precaliente el horno a 350 grados F. Rocíe una fuente para hornear con aceite en aerosol antiadherente.","Seque los filetes de pescado con una toalla de papel y colóquelos sobre una superficie plana.","Espolvoree cada filete con pimienta negra.","Enrolle cada filete alrededor de los palitos de zanahoria y apio, y colóquelos con la unión hacia abajo en la fuente para hornear.","Coloque las nueces, el perejil, el jugo de limón, la ralladura de limón, el pan molido, 1 cucharadita de aceite de oliva y 1 diente de ajo en un procesador de alimentos pequeño. Procese hasta que quede desmenuzado.","Extienda 1 cucharadita de la mezcla de nueces y perejil sobre cada rollito de pescado.","Colóquelos en el centro del horno y hornee de 15 a 20 minutos, hasta que el pescado se desmenuce fácilmente y las verduras estén tiernas.","Colóquelos en el centro del horno y hornee de 15 a 20 minutos, hasta que el pescado se desmenuce fácilmente y las verduras estén tiernas.","Mientras se hornea el pescado, pique los 2 dientes de ajo restantes. Agregue 1 cucharadita de aceite de oliva a una sartén grande y caliente a fuego medio. Agregue el ajo y saltee de 30 segundos a un minuto, hasta que desprenda aroma. Agregue la espinaca picada y cocine hasta que se marchite."],[],[]),
ar=("لفائف سمك الفلاوندر والخضار مع طبقة الجوز والبقدونس","سمك الفلاوندر سمك أبيض خفيف النكهة وحلو قليلًا. وهو قليل الدهون ويحتوي على دهون أوميغا 3 الصحية للقلب ومصدر جيد للبروتين. مع الخضار وطبقة الجوز المفروم المنعشة، يُعد عشاءً لذيذًا وصحيًا وقليل الكربوهيدرات.","4","2 لفة سمك + 1 كوب خضار",
["1 رطل فيليه سمك (حوالي 8 شرائح رفيعة)","¼ ملعقة صغيرة فلفل أسود","16 حزمة أعواد هليون (مقطّعة إلى قطع بطول 2 إلى 3 بوصات)","2 حبة جزر متوسطة (مقطّعة إلى أعواد رفيعة بطول 2 إلى 3 بوصات تقريبًا)","¼ كوب جوز","¼ كوب بقدونس مسطح الأوراق (طازج)","1 ملعقة صغيرة عصير ليمون","1 ملعقة صغيرة قشر ليمون مبشور","1 ملعقة كبيرة فتات خبز بانكو","2 ملعقة صغيرة زيت زيتون بكر ممتاز (مقسّمة)","3 فص ثوم (مقسّمة)","4 كوب سبانخ صغيرة (مفرومة)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175 درجة مئوية). رش طبق خبز ببخاخ الطهي غير اللاصق.","جفّف شرائح السمك بمنديل ورقي وضعها على سطح مستوٍ.","رش كل شريحة بالفلفل الأسود.","لفّ كل شريحة حول أعواد الجزر والكرفس وضعها في طبق الخبز وجهة الالتحام إلى الأسفل.","ضع الجوز والبقدونس وعصير الليمون وقشر الليمون وفتات الخبز و1 ملعقة صغيرة من زيت الزيتون وفصًا واحدًا من الثوم في محضّر طعام صغير. شغّله حتى يصبح الخليط مفتتًا.","وزّع 1 ملعقة صغيرة من خليط الجوز والبقدونس فوق كل لفة سمك.","ضعها في منتصف الفرن واخبزها من 15 إلى 20 دقيقة، حتى يتفتت السمك بسهولة وتنضج الخضار.","ضعها في منتصف الفرن واخبزها من 15 إلى 20 دقيقة، حتى يتفتت السمك بسهولة وتنضج الخضار.","بينما يُخبز السمك، افرم فصّي الثوم المتبقيين. أضف 1 ملعقة صغيرة من زيت الزيتون إلى مقلاة كبيرة وسخّنها على نار متوسطة. أضف الثوم وقلّبه من 30 ثانية إلى دقيقة حتى تفوح رائحته. أضف السبانخ المفرومة واطهها حتى تذبل."],[],[])))
O.append(R(6433160,
en=("Carrot and Cabbage Salad","Like other cruciferous vegetables (broccoli and cauliflower), cabbage is considered an important part of the diet for lowering the risk of cancer.","4","1/2 cup",
["2 cups shredded cabbage","1 medium carrot (grated)","3 tablespoons lime juice or 1/4 cup vinegar (your choice)","1/2 teaspoon sugar","1/4 teaspoon salt","1/2 teaspoon black pepper","1 tablespoon chopped cilantro","1-3 tablespoons jalapeño or serrano chile (optional)"],
["Combine all ingredients and mix well."],[],[]),
ar=("سلطة الجزر والملفوف","كما هو الحال مع الخضروات الصليبية الأخرى (البروكلي والقرنبيط)، يُعد الملفوف (الكرنب) عنصرًا غذائيًا مهمًا للمساعدة في تقليل خطر الإصابة بالسرطان.","4","½ كوب",
["2 كوب ملفوف (كرنب) مقطّع شرائح","1 حبة جزر متوسطة (مبشورة)","3 ملعقة كبيرة عصير ليمون أخضر أو ¼ كوب خل (حسب تفضيلك)","½ ملعقة صغيرة سكر","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة كزبرة خضراء مفرومة","1-3 ملعقة كبيرة فلفل هالابينو أو سيرانو (اختياري)"],
["اخلط جميع المكونات وقلّبها جيدًا."],[],[])))
O.append(R(6433313,
ar=("دجاج بالديجون مع الكوسا والطماطم","يُقدَّم طبق الدجاج هذا على أفضل وجه فوق الكينوا. الكينوا حبوب كاملة خالية من الغلوتين وغنية بالبروتين وتُطهى في حوالي 15 دقيقة. يمكنك الآن إيجادها في معظم محلات البقالة.","4","1 صدر دجاج + ¾ كوب خضار",
["1 بخة من بخاخ طهي غير لاصق، 0.25 غرام","2 حبة كوسا متوسطة (مقطّعة إلى دوائر بسمك ¼ بوصة)","10 أونصة طماطم عنبية","1 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة فلفل أسود (مطحون، مقسّم)","½ حبة ليمون متوسطة (معصورة)","2 ملعقة كبيرة خردل ديجون","4 قطع، حوالي 4 أونصات لكل منها، صدور دجاج (بدون عظم وبدون جلد)","¼ ملعقة صغيرة ملح كوشر (اختياري)","½ ملعقة صغيرة مسحوق الثوم","1 ملعقة صغيرة أوريغانو مجفف","1 ملعقة كبيرة جبن بارميزان (مبشور طازجًا)"],
["سخّن الفرن مسبقًا إلى 350 درجة (175 درجة مئوية). ادهن طبق خبز كبيرًا ببخاخ الطهي. في وعاء صغير، اخلط الكوسا والطماطم وزيت الزيتون و⅛ ملعقة صغيرة من الفلفل الأسود وقلّبها لتتغطى. ضعها جانبًا.","في وعاء صغير آخر، اخلط عصير الليمون وخردل الديجون. ضعه جانبًا.","تبّل صدور الدجاج من الجانبين بـ⅛ ملعقة صغيرة من الفلفل ومسحوق الثوم والأوريغانو. ضع صدور الدجاج في طبق الخبز وادهن وجهها العلوي بخليط الخردل. رش جبن البارميزان.","اسكب الكوسا والطماطم حول الدجاج في طبق الخبز. اخبزه لمدة 30 دقيقة أو حتى ينضج."],[],[])))
O.append(R(6434931,
es=("Col rizada salteada con tocino de pavo","La col rizada (kale) se ha vuelto un superalimento popular porque está llena de vitamina A, vitamina C, potasio y fibra. También es baja en carbohidratos, por lo que no elevará demasiado el azúcar en la sangre. Si tiene prisa, puede comprar la col rizada ya picada en bolsas en la mayoría de los supermercados.","6","1/2 taza",
["1 cucharada de aceite de oliva","6 lonchas de tocino de pavo (cortadas en trozos de 1 pulgada)","8 onzas de col rizada (kale) (picada)","1/2 taza de caldo de pollo bajo en sodio (sin grasa, reducido en sodio)","1/8 de cucharadita de pimienta negra","2 cucharaditas de vinagre de vino tinto"],
["Caliente una olla grande a fuego medio-alto. Agregue el tocino de pavo y cocine de 4 a 5 minutos, hasta que esté listo.","Agregue la col rizada y el caldo de pollo a la olla; mezcle bien. Tape y cocine por 5 minutos.","Destape la olla y agregue la pimienta negra y el vinagre de vino tinto."],[],[]),
ar=("الكيل المقلي مع لحم الديك الرومي المقدد","أصبح الكيل (اللفت الورقي) غذاءً خارقًا شائعًا لأنه غني بفيتامين أ وفيتامين ج والبوتاسيوم والألياف. كما أنه قليل الكربوهيدرات، لذا لن يرفع سكر الدم كثيرًا. وإذا كنت على عجل، يمكنك شراء الكيل مفرومًا جاهزًا في أكياس من معظم محلات البقالة.","6","½ كوب",
["1 ملعقة كبيرة زيت زيتون","6 شريحة لحم ديك رومي مقدد (مقطّعة إلى قطع بطول 1 بوصة)","8 أونصة كيل (مفروم)","½ كوب مرق دجاج قليل الصوديوم (خالٍ من الدسم، مخفض الصوديوم)","⅛ ملعقة صغيرة فلفل أسود","2 ملعقة صغيرة خل النبيذ الأحمر"],
["سخّن قدرًا كبيرًا على نار متوسطة إلى عالية. أضف لحم الديك الرومي المقدد واطهه من 4 إلى 5 دقائق حتى ينضج.","أضف الكيل ومرق الدجاج إلى القدر؛ وقلّب جيدًا. غطِّه واطهه لمدة 5 دقائق.","ارفع الغطاء عن القدر وأضف الفلفل الأسود وخل النبيذ الأحمر وقلّب."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c12_part2.json")
