from mk import *
R=[]
R.append((9000851,"Stuffing Vegan di Atas Kompor",
"Stuffing vegan di atas kompor yang MUDAH ini siap hanya dalam 30 menit. Cocok untuk Thanksgiving, Natal, atau hari biasa!",
"8 porsi","1 porsi",
["300 gram roti gandum utuh iris, dipotong dadu 1\" (sekitar 6 cangkir potongan dadu)","1 cangkir pecan atau kenari cincang","2 sendok makan mentega vegan (lewati dan gunakan kaldu untuk menumis jika ingin bebas minyak)","1 bawang bombai kuning, dipotong dadu","2 wortel, dikupas + dipotong dadu","2 batang seledri, dipotong dadu","3-4 siung bawang putih, dikupas + dicincang halus","1.5 sendok teh sage kering","1 sendok teh thyme kering","1 sendok teh rosemary kering yang dihaluskan","2-3 cangkir kaldu sayuran rendah natrium (mulai dengan 2 cangkir dan tambah jika perlu)","garam + merica secukupnya",("Hiasan Opsional","rosemary segar")],
["Panaskan oven terlebih dahulu hingga 400 derajat F dan alasi loyang dengan kertas roti.","Susun roti yang sudah dipotong dadu dan pecan cincang di atas loyang, lalu panggang selama 8 menit, atau hingga kecokelatan dengan baik. Keluarkan dari oven dan sisihkan.","Sementara itu, lelehkan mentega (jika digunakan) dalam wajan besar, lalu masukkan semua sayuran cincang dan bumbu ke dalam wajan. Tumis selama 7-8 menit, hingga sayuran lunak dan keemasan.","Masukkan roti panggang dan pecan ke dalam wajan berisi sayuran, lalu tuangkan 2 cangkir kaldu di atasnya. Aduk rata. Cicipi dan sesuaikan garam dan merica, lalu tambahkan kaldu jika Anda menyukai stuffing yang lebih lembut. Sajikan dan nikmati."],
["Saya menggunakan setengah roti Dempster’s Ancient Grains w/ Quinoa. Anda boleh menggunakan roti tawar favorit Anda, atau roti buatan sendiri. Mulailah hanya dengan 2 cangkir kaldu terlebih dahulu. Aduk rata dan tambahkan lagi jika Anda menyukai stuffing yang lebih lembut."],[]))
R.append((9005196,"Roti Gandum Utuh Ara dan Kenari - Tanpa Diuleni!",
"Roti ara dan kenari yang sangat lezat, dibuat dengan tepung gandum utuh dan tanpa perlu diuleni.",
"12 potong","1 porsi",
["520 gram tepung gandum utuh (sekitar 4 cangkir)","1 sachet ragi instan 8 gram (sekitar 2 ¼ sendok teh)","¾ sendok teh garam laut","1 sendok makan sirup maple atau pemanis lain seperti sirup kurma atau agave","2 cangkir air hangat","½ cangkir buah ara kering, dipadatkan (sekitar 6-7 buah ara, dicincang kecil-kecil)","½ cangkir potongan kenari, dipadatkan"],
["Alasi loyang roti ukuran 5 inci x 9 inci dengan kertas roti dan sisihkan.","Masukkan tepung, ragi instan, dan garam ke dalam mangkuk besar, lalu aduk rata.","Kemudian masukkan sirup maple ke dalam semangkuk air hangat dan aduk hingga larut. Setelah itu tuangkan air tersebut ke dalam mangkuk tepung dan aduk dengan spatula silikon, jangan terlalu lama, dan JANGAN ULENI.","Masukkan ara cincang dan potongan kenari dengan cara dilipat, lalu pindahkan adonan ke loyang yang sudah disiapkan. Tutup loyang dengan plastik pembungkus dan diamkan selama 20 menit. Adonan akan mengembang hingga sekitar dua kali lipat, dan roti akan mencapai bagian atas loyang. (lihat catatan)","Sementara itu, panaskan oven terlebih dahulu hingga 400°F/204°C, lalu panggang roti ara dan kenari yang sudah mengembang selama 40 menit. Keluarkan dari oven dan biarkan dingin sebelum diiris."],
["Timbang tepung Anda untuk hasil terbaik. Volume tepung akan bervariasi tergantung cara mengukurnya, misalnya dengan mengeruk dan meratakan dibandingkan menyendokkan tepung ke dalam cangkir ukur. Gunakan timbangan dapur untuk takaran tepung yang paling akurat. Pastikan menggunakan air hangat untuk dicampur dengan sirup maple, dan BUKAN air dingin. Anda membutuhkan air hangat untuk mengaktifkan ragi. JANGAN ULENI adonan. Aduk hingga tidak ada bagian tepung yang tersisa, tanpa mengaduk berlebihan. Ketika roti mencapai bagian atas loyang, roti siap dipanggang. Jangan biarkan roti mengembang melewati tepi loyang, atau Anda akan mendapatkan bagian atas yang menyembul seperti muffin. Ini biasanya memerlukan waktu 20 menit, tetapi jika belum cukup, biarkan 5 menit lagi. Roti yang baru dipanggang paling enak pada hari yang sama, tetapi Anda dapat menyimpannya pada suhu ruang selama 3-4 hari. Untuk membekukan, pastikan roti sudah benar-benar dingin hingga suhu ruang terlebih dahulu. Kemudian bungkus rapat dengan plastik pembungkus, dan letakkan dalam wadah kedap udara yang aman untuk freezer. Anda perlu menjauhkan udara dari roti di dalam freezer agar tidak terkena freezer burn."],[]))
R.append((9005368,"Burger Ayam Vegan [Bebas Gluten + Tanpa Minyak]",
"Dibumbui dengan cita rasa ala unggas dan dipanggang hingga renyah dan keemasan. Burger ayam vegan ini beraroma kaya, bergizi, dan lezat!",
"8 patty","1 g",
["1 cangkir nasi merah matang, dipadatkan perlahan","3 cangkir kentang kuning, dikupas & dipotong dadu","1 kaleng 15 ons buncis, ditiriskan & dibilas, atau 1.5 cangkir buncis matang","1 cangkir oat steel cut yang cepat matang atau oat gulung","2 sendok makan air","2 sendok makan ragi nutrisi","1 sendok teh bubuk bawang putih","1 sendok teh bubuk bawang bombai","¾ sendok teh garam laut","¼ sendok teh oregano kering","¼ sendok teh thyme kering","¼ sendok teh sage kering","¼ sendok teh rosemary kering yang dihaluskan"],
["Panaskan oven terlebih dahulu hingga 425 derajat F dan alasi loyang dengan kertas roti.","Rendam kentang yang sudah dipotong dadu dengan air bergaram dalam panci kecil dan didihkan. Masak selama 10 menit, atau hingga mudah ditusuk dengan garpu. Tiriskan dan masukkan ke dalam mangkuk pencampur besar. Kemudian haluskan perlahan dengan penumbuk kentang hingga hancur, tanpa terlalu halus. Sisakan sedikit tekstur. Sisihkan.","Masukkan nasi, buncis, oat, air, dan semua bumbu ke dalam food processor. Pulsekan hingga tercampur dan hancur, tanpa diproses berlebihan. Anda tidak menginginkan adonan menjadi puree.","Pindahkan bahan yang sudah diproses ke dalam mangkuk kentang tumbuk, lalu aduk rata dengan spatula.","Dengan tangan basah, genggam adonan menjadi bola, lalu tekan menjadi bentuk cakram. Buat patty agak tipis dan letakkan di atas loyang yang sudah disiapkan. Ulangi dengan sisa adonan. Anda akan mendapatkan 8 patty besar.","Panggang selama 20 menit, lalu balik dengan hati-hati dan panggang lagi selama 10 menit, atau hingga cokelat keemasan ringan.","Sajikan patty ayam vegan Anda dengan atau tanpa roti burger, dan dengan semua topping favorit Anda."],
["Untuk kedalaman rasa tambahan, masak kentang Anda (dan nasi jika tidak ada sisa) dalam kaldu atau dengan sedikit bubuk kaldu. Jangan terlalu menghaluskan kentang. Ingat, Anda tidak sedang membuat kentang tumbuk, dan kentang sebaiknya bergumpal agar tekstur patty terbaik. Jadi cukup tumbuk beberapa kali untuk memastikan tidak ada potongan yang terlalu besar. Jangan memproses campuran nasi dan buncis secara berlebihan. Sekali lagi, untuk tekstur patty ayam vegan terbaik, sisakan sedikit kekasaran, dan jangan dijadikan puree. Gunakan tangan basah untuk membentuk patty. Letakkan semangkuk kecil air di dekat Anda, atau bekerjalah di dekat bak cuci dan basahi sedikit tangan Anda sebelum membentuk setiap bola dan lagi sebelum memipihkan setiap patty. Ini akan membantu Anda membentuk patty tanpa adonan menempel di tangan. Ini juga membantu mencegah patty retak saat dibentuk. Buat patty ayam vegan agak tipis untuk tekstur dan kerenyahan terbaik. Menyajikan untuk anak kecil? Buat beberapa patty yang lebih kecil untuk disajikan sebagai nugget ayam vegan. Simpan sisa makanan di lemari es selama 3-4 hari atau bekukan hingga 3 bulan. Untuk membekukan, masak sesuai petunjuk dan bekukan dalam wadah kedap udara. Pisahkan setiap patty dengan kertas roti agar tidak lengket, dan panaskan kembali di dalam oven. Informasi nilai gizi untuk 1 burger ayam vegan. Roti burger dan topping tidak termasuk dalam perhitungan."],[]))
R.append((9007563,"Paprika Isi Meksiko Vegan dengan Saus Keju Kenari",
"Paprika isi Meksiko vegan yang menggugah selera dan sangat kaya rasa!",
"4 porsi","1 porsi",
["4 paprika besar warna apa saja, dibelah dua memanjang dan biji dibuang","1 cangkir quinoa, dibilas & ditiriskan","2 cangkir kaldu sayuran rendah natrium","1.5 cangkir kacang hitam, matang atau kalengan","1 cangkir jagung beku, dicairkan","½ cangkir salsa sedang yang agak kasar atau salsa favorit Anda","1.5 sendok teh paprika asap","1.5 sendok teh bubuk cabai","1 sendok teh jintan","garam + merica secukupnya",("Topping Opsional","saus keju kenari (sangat disarankan)"),("Topping Opsional","irisan alpukat, tomat dipotong dadu, jalapeño"),("Topping Opsional","pico de gallo nanas"),("Topping Opsional","guacamole"),("Topping Opsional","kisaran kari cincang".replace("kisaran kari","kemangi").replace("kemangi","ketumbar segar"))],
["Masukkan quinoa dan kaldu ke dalam panci sedang dan didihkan. Kemudian kecilkan api dan didihkan perlahan hingga air terserap, sekitar 15 menit. Aduk sesering mungkin menjelang akhir waktu memasak agar tidak lengket. Angkat dari api dan masukkan kacang hitam, jagung, salsa, dan semua bumbu ke dalam quinoa yang sudah matang. Aduk rata, lalu cicipi dan sesuaikan bumbu sesuai selera.","Sementara itu, panaskan oven terlebih dahulu hingga 425°F/218°C dan alasi loyang 9\"x13\" dengan kertas roti. Susun paprika yang sudah dibelah dengan sisi potongan menghadap ke atas di dalam loyang, lalu taburi dengan garam dan merica.","Bagi campuran ke dalam 8 belahan paprika, lalu tutup loyang dengan kertas roti, kemudian dengan aluminium foil. Panggang selama 30-35 menit, hingga paprika empuk.","Saat paprika dipanggang, siapkan topping opsional apa pun. Kemudian sajikan."],
["Untuk hasil terbaik, masak quinoa (atau nasi) dalam kaldu sayuran yang gurih dan beraroma. Anda boleh menggunakan air garam untuk memasak quinoa (sebagai pengganti kaldu), tetapi rasanya tidak akan sekaya itu. Jika Anda kurang menyukai quinoa, gunakan nasi, dan ikuti petunjuk memasak yang sama atau gunakan penanak nasi. Informasi nilai gizi untuk satu paprika (atau dua belahan paprika) dan seperempat isian yang sudah disiapkan. Tidak termasuk topping opsional."],[]))
R.append((9014896,"Bisque Tomat Vegan [dengan tomat segar!]",
"Bisque tomat vegan yang kaya dan creamy, dibuat dalam satu panci, dengan cita rasa tomat segar yang melimpah! Teksturnya halus lembut dan mengenyangkan, tetapi tidak membuat Anda merasa berat!",
"6 porsi","1 porsi",
["1 sendok makan mentega vegan (opsional, lewati untuk bebas minyak, dan tumis dengan air atau kaldu)","1 bawang bombai kuning besar, dicincang kasar","1 batang seledri, dicincang kasar","4 siung bawang putih, dikupas & dicincang kasar","½ sendok teh paprika asap","½ sendok teh garam laut","¼ cangkir tepung gandum utuh (atau tepung bebas gluten, jika diinginkan)","3 pon tomat ladang atau tomat matang di pohon, dibelah empat","3 cangkir kaldu sayuran rendah natrium","2 lembar daun salam","2 tangkai peterseli segar","454 gram tahu sedang/padat (sebaiknya non-GMO, atau ukuran serupa)","garam + merica secukupnya"],
["Lelehkan mentega, jika digunakan, dalam panci besar lalu masukkan bawang bombai, seledri, dan bawang putih yang sudah dicincang. Tumis sambil sering diaduk hingga lunak dan bawang bombai bening, sekitar 5 menit.","Masukkan paprika asap dan garam, lalu aduk rata. Kecilkan api, tambahkan sedikit air dan tepung, lalu aduk terus selama sekitar 30 detik.","Sekarang masukkan tomat cincang ke dalam panci dan masak sambil sering diaduk selama 1-2 menit. Kemudian tuangkan kaldu, daun salam, dan peterseli. Aduk rata dan didihkan dengan api sedang, masak selama sekitar 20-25 menit sambil sesekali diaduk.","Angkat dari api, lalu angkat dan buang daun salam. Masukkan tahu dan haluskan sup tomat dengan blender tangan (immersion blender). Setelah halus, cicipi dan sesuaikan garam dan merica, jika perlu.","Sajikan dengan hiasan kemangi segar dan nikmati."],
["Untuk hasil terbaik, diamkan sup yang sudah dimasak dan dihaluskan selama 10 menit sebelum disajikan. Waktu istirahat singkat ini akan membuat sup sedikit lebih kental. Jika Anda tidak memiliki blender tangan atau immersion blender, Anda dapat memindahkan sup dengan hati-hati, dalam beberapa tahap, ke blender biasa. Berhati-hatilah saat memblender cairan panas, jangan isi blender sampai penuh, dan kerjakan dalam beberapa kali sesuai kebutuhan. Buat bebas minyak dengan tidak memakai mentega dan menumis dengan air atau kaldu sebagai gantinya. Tambahkan lagi sesuai kebutuhan, agar tidak lengket. Untuk versi bebas kedelai, lewati tahu dan gunakan 1.5 cangkir krim mete yang diaduk di akhir. Perlu diingat, ini akan meningkatkan kandungan lemak. ATAU – Gunakan 1 kaleng 15 ons kacang cannellini putih yang ditiriskan dan dibilas jika menghindari kedelai dan kacang-kacangan pohon. Ukuran blok tahu bervariasi, dan kali ini saya menggunakan satu blok tahu sedang/padat 454 g, tetapi apa pun antara 350 hingga 454 g akan cocok untuk resep ini. Sisa makanan dapat disimpan di lemari es hingga 3 hari, atau Anda dapat membekukannya selama 2-3 bulan."],[]))
R.append((9021259,"Carbonara Vegan Mudah dengan Pancetta Soy Curl",
"Spageti empuk dengan pancetta soy curl beraroma asap dan saus telur yang lezat membuat carbonara vegan ini tak terlupakan!",
"6 porsi","1 porsi",
G("Untuk Pancetta Vegan",["4 ons soy curl (sekitar setengah kemasan Butler's)","⅓ cangkir kecap asin rendah natrium atau tamari untuk bebas gluten","2 sendok makan sirup maple","2 sendok teh paprika asap","½ sendok teh merica hitam"])+G("Untuk Saus Telur Vegan",["300 gram tahu lembut","¼ cangkir ragi nutrisi","3 sendok makan cuka sari apel","1 sendok teh kunyit","1 sendok teh bubuk bawang bombai","1 sendok teh garam hitam (dikenal juga sebagai Kala Namak)","⅓ cangkir susu kedelai tanpa pemanis atau susu nabati pilihan"])+G("Untuk Pasta",["410 gram (14.5 ons) spageti atau spaghettini, bebas gluten jika diinginkan"])+G("Hiasan Opsional",["keju Parmesan vegan","merica hitam, peterseli segar, kemangi segar, dan/atau serpihan cabai merah"]),
["Pecah soy curl dengan tangan menjadi potongan kecil, lalu letakkan dalam mangkuk sedang. (Tidak harus berukuran sama.)","Dalam mangkuk kecil, aduk bahan marinasi pancetta: tamari, sirup maple, paprika asap, dan merica hitam. Tuang campuran di atas potongan soy curl, aduk hingga terlapisi rata, lalu diamkan selama 5 menit. Kemudian aduk lagi agar soy curl menyerap semua marinasi.","Didihkan panci besar berisi air bergaram dan masak pasta Anda sesuai petunjuk kemasan hingga 'al dente'.","Sementara itu, panaskan wajan dalam di atas kompor, dan setelah panas, masukkan soy curl ke dalam wajan. Tumis kering selama sekitar 5 menit, sering diaduk, hingga cokelat keemasan, tanpa gosong. Lalu matikan api dan sisihkan. (Jika Anda ingin menghias piring dengan soy curl nanti, sisihkan segenggam potongan.)","Masukkan semua bahan saus ke dalam blender dan proses hingga halus. Sisihkan.","Ketika pasta sudah matang, SISIHKAN 1 cangkir air rebusan sebelum ditiriskan. Masukkan spageti yang sudah matang ke dalam wajan dan tuang saus carbonara di atasnya. Lalu masukkan satu cangkir air pasta ke dalam blender yang kosong, goyangkan dengan baik, atau blender ulang selama beberapa detik untuk mengumpulkan sisa saus dan bumbu di sisi blender. Tuang ini ke dalam wajan dan aduk rata.","Sajikan dengan merica hitam, rempah segar, dan/atau keju parmesan vegan."],
["Beri garam pada air rebusan pasta! Pastikan menambahkan garam yang cukup ke dalam panci air untuk hasil terbaik. Berikut panduan praktis jika diperlukan. Jangan memasak pasta terlalu matang. Ikuti petunjuk untuk pasta 'al dente'. Jika kemasan Anda tidak mencantumkan petunjuk 'al dente', masak pasta 1-3 menit lebih singkat. 'Al dente' berarti pasta masih terasa padat setelah dimasak, dan tidak lembek. Ini memberikan tekstur yang optimal. Sisihkan sedikit air pasta untuk 'dikocok' di dalam blender saat menyaring mi Anda. Jika lupa, gunakan sedikit kaldu, atau air segar dengan sedikit garam, agar saus carbonara tidak terlalu encer, tetapi air yang mengandung pati bekerja paling baik. Garam hitam alias Kala Namak adalah bahan penting dalam hidangan ini. Inilah yang memberi saus rasa telur. Jangan dilewatkan jika memungkinkan. Jika Anda tidak punya, atau tidak dapat menemukan garam hitam, Anda dapat menggunakan garam laut dengan hasil yang sedikit berbeda. Sajikan carbonara vegan Anda segera, karena pasta akan menyerap saus saat mendingin. Sisa makanan dapat disimpan di lemari es selama 3-4 hari. Tambahkan sedikit kaldu atau susu nabati ke wajan saat memanaskan kembali untuk mengencerkan dan mengembalikan kelembapan. Pancetta soy curl terinspirasi dari bacon bits vegan My Quiet Kitchen."],[]))
R.append((9021515,"Irisan Deli Vegan [Irisan Kalkun Seitan]",
"Irisan deli vegan yang mantap, \"berdaging\", juicy, kaya rasa, dan mudah dibuat!",
"8 porsi","1 porsi",
["130 gram gluten gandum vital (sekitar 1 cangkir penuh menggunung)","350 gram (12 ons) satu blok tahu ekstra padat, dipotong dadu","6 sendok makan ragi nutrisi","2 sendok makan kecap asin","1 sendok makan liquid smoke","3 sendok teh bumbu unggas (poultry seasoning)","2 sendok teh bubuk bawang putih","2 sendok teh bubuk bawang bombai","1 sendok teh cuka sari apel","½ sendok teh garam laut (opsional, tetapi karena daging deli tradisional asin, tambahan garam membantu meniru rasa tersebut)"],
["Masukkan semua bahan ke dalam food processor dan pulsekan hingga tercampur. Adonan akan mudah hancur, tetapi Anda dapat menekan semuanya menjadi satu dengan tangan, jadi jangan khawatir jika tidak membentuk bola yang sempurna.","Angkat campuran dari processor dan bentuk menjadi gulungan atau cakram. Kemudian bungkus rapat dengan kain kasa (cheesecloth) dan ikat kedua ujungnya seperti bungkus permen. (Lihat gambar proses di atas sebagai acuan.)","Gunakan panci pengukus untuk menaruh seitan kalkun Anda di dalamnya ATAU buat pengukus sendiri jika tidak punya. Caranya dengan menaruh mangkuk tahan panas di atas panci berisi air, tetapi pastikan mangkuk tidak menyentuh air. Jaga agar air mendidih perlahan dan tutup seitan dengan penutup.","Kukus selama 45 menit, lalu balik, dan kukus lagi selama 35-45 menit, atau hingga suhu internal mencapai 160℉/71℃. Perhatikan permukaan air agar tidak menguap habis dan tambahkan air PANAS/mendidih sesuai kebutuhan.","Untuk hasil terbaik dan irisan yang mudah, diamkan gulungan seitan kalkun Anda pada suhu ruang selama 30 menit, lalu dinginkan di lemari es semalaman atau beberapa jam hingga dingin."],
["Gunakan timbangan dapur untuk menimbang gluten gandum vital agar hasil paling akurat dan tekstur terbaik.","Perhatikan permukaan air selama pengukusan agar tidak habis. Tambahkan air mendidih panas ke dalam panci sesuai kebutuhan untuk menjaga didihan tetap perlahan.","Waktu pengukusan akan bervariasi tergantung bentuk gulungan atau cakram seitan kalkun Anda, jadi memeriksa suhu internal adalah cara termudah untuk mendapatkan hasil terbaik.","Jika Anda tidak punya kain kasa (cheesecloth), Anda dapat membungkus seitan dengan aluminium foil. Namun, agar aluminium tidak menyentuh makanan, Anda dapat menggunakan kertas roti terlebih dahulu, lalu membungkusnya dengan aluminium foil.","Sisa makanan dapat disimpan di lemari es hingga 5 hari dalam wadah tertutup. Atau bekukan deli vegan dalam irisan atau satu gulungan penuh untuk digunakan nanti."],[]))
R.append((9023396,"Veloute Jamur Vegan [Tanpa Minyak]",
"Veloute jamur vegan (atau sup jamur vegan) penuh dengan kelezatan umami. Hanya 7 bahan dan 25 menit dari awal hingga selesai!",
"3 porsi","1 porsi",
["1 pon jamur cremini atau baby bella, dicincang kasar","3 siung bawang putih, dikupas & dicincang halus","¼ sendok teh thyme kering","3 cangkir kaldu sayuran rendah natrium","1 sendok makan pasta miso putih","3 sendok makan air lemon (sekitar 1 lemon sedang)","1 cangkir susu kedelai tanpa pemanis atau susu nabati pilihan","garam + merica secukupnya"],
["Dalam panci sedang, atau wajan dalam, masukkan jamur, bawang putih, thyme, dan beberapa tetes air agar tidak lengket. Tumis hingga jamur menyusut, sekitar 4 menit.","Masukkan kaldu, pasta miso, dan air lemon lalu didihkan perlahan, masak selama sekitar 5 menit. Matikan api, tambahkan susu, lalu gunakan blender tangan untuk menghaluskan sup Anda ATAU pindahkan ke blender. Cicipi dan tambahkan garam dan merica, hanya jika perlu, dan sajikan dengan roti renyah."],
["Jangan menambahkan garam pada sup sebelum dicicipi, setelah dihaluskan. Pasta miso dan kaldu sayuran sudah memberikan cukup banyak rasa asin. Setelah diblender, cicipi sup dan tambahkan sedikit garam, hanya jika perlu. Gunakan kaldu sayuran rendah natrium, atau gunakan campuran kaldu biasa dan air jika Anda tidak memiliki yang rendah natrium. Anda selalu bisa menambahkan garam jika perlu, tetapi tidak bisa menguranginya. Jika Anda tidak punya blender tangan, pindahkan sup dengan hati-hati ke blender dan proses hingga halus. Berhati-hatilah saat memblender cairan panas, jangan mengisi blender terlalu penuh dan kerjakan dalam beberapa kali, sesuai kebutuhan! Sisa makanan dapat disimpan di lemari es hingga 4 hari atau dibekukan hingga 3 bulan."],[]))
R.append((9028983,"Cupcake Wortel Vegan Sehat",
"Cupcake wortel vegan yang lembap, manis, dan lezat, dibuat dengan bahan-bahan sehat untuk camilan fantastis TANPA rasa bersalah!",
"12 cupcake","1 porsi",
G("Untuk cupcake wortel vegan",["½ cangkir susu kedelai","¼ cangkir air lemon (sekitar 1 lemon besar)","½ cangkir saus apel tanpa pemanis","½ cangkir sirup maple","1 cangkir wortel parut, dipadatkan (sekitar 2 wortel besar)","2 sendok teh ekstrak vanila murni"])+G("Bahan kering",["240 gram tepung pastry gandum utuh (sekitar 2 cangkir)","1 sendok teh kayu manis bubuk","¼ sendok teh pala bubuk","2 sendok teh baking powder","½ sendok teh baking soda"])+G("Opsional (Pilih 1 atau Tidak Sama Sekali)",["½ cangkir kismis","½ cangkir kenari atau pecan cincang"])+G("Untuk frosting cream cheese vegan",["340 gram tahu ekstra padat, ditiriskan dan ditepuk hingga kering (gunakan yang bebas GMO jika memungkinkan)","¼ cangkir mete mentah","5-8 sendok makan sirup maple","2-3 sendok teh air lemon"]),
G("Untuk cupcake",["Masukkan susu kedelai dan air lemon ke dalam mangkuk pencampur besar dan diamkan selama 5 menit hingga mengental dan menggumpal. (Ini adalah buttermilk vegan Anda.)","Panaskan oven terlebih dahulu hingga 350°F/176°C dan siapkan cetakan muffin antilengket. (Atau olesi cetakan atau cup kertas jika perlu.)","Setelah menggumpal, masukkan sisa bahan basah ke dalam mangkuk dan aduk rata. Kemudian masukkan bahan kering ke mangkuk yang sama dan aduk hingga tercampur TANPA mengaduk berlebihan. (Jika menggunakan tambahan opsional, lipat juga ke dalam adonan.)","Bagi adonan cupcake ke dalam 12 cetakan muffin Anda dan panggang hingga tusuk gigi yang ditusukkan ke tengah cupcake keluar bersih, sekitar 18 menit. Keluarkan dari oven dan diamkan selama 10 menit sebelum dipindahkan ke rak pendingin."])+G("Untuk frosting",["Masukkan semua bahan frosting ke dalam blender dan proses hingga halus. Mulailah dengan 5 sendok makan sirup maple, lalu cicipi, dan tambahkan lagi hingga tingkat kemanisan yang diinginkan tercapai. Jangan berlebihan atau frosting akan terlalu lembek.","Setelah cupcake benar-benar dingin, hias cupcake Anda dengan frosting menggunakan kantong piping, lalu nikmati."]),
["Timbang tepung Anda untuk hasil yang paling akurat. Saya sangat menyarankan agar Anda tidak mengandalkan takaran cangkir saat memanggang. Jika Anda tidak punya timbangan dapur, Anda dapat menyendokkan tepung ke dalam cangkir ukur dan menggunakan pisau untuk meratakan kelebihannya, dengan hasil yang serupa. Jangan mengeruk langsung dari kantong!","Gunakan parutan kotak atau food processor untuk memarut wortel Anda, tetapi bagaimanapun caranya, parutan segar paling baik karena wortel parut kemasan bisa kering.","Jangan mengaduk adonan cupcake secara berlebihan. Aduk hingga tidak ada bagian tepung yang tersisa, tetapi jangan khawatir untuk menghaluskan setiap gumpalan. Pengadukan berlebihan dapat menghasilkan tekstur yang lengket atau padat.","Gunakan baking powder yang segar dan aktif. Baking powder yang sudah dibuka di lemari dapur selama 6+ bulan dapat mulai kehilangan keefektifannya.","Karena cupcake ini tidak mengandung lemak tambahan, pastikan menggunakan cetakan muffin antilengket ATAU olesi cetakan atau cup cupcake Anda agar tidak lengket.","Jika Anda tidak memiliki blender yang bertenaga, rendam mete Anda dalam air panas selama 30 menit sebelum memblender frosting. Ini akan membantu mete mengembang dan melunak, sehingga lebih mudah diblender menjadi frosting yang halus.","Tiriskan dan tepuk tahu Anda hingga kering untuk menghilangkan kelebihan cairan dan mencegah frosting menjadi terlalu encer.","Jika frosting menjadi hangat saat diblender (ini bisa terjadi pada blender yang kuat), pindahkan ke mangkuk dan taruh di freezer selama 30 menit sebelum menuang frosting ke cupcake dengan piping.","Biarkan cupcake Anda dingin di dalam cetakan muffin setidaknya 10 menit sebelum disentuh. Kemudian pindahkan ke rak pendingin hingga benar-benar dingin SEBELUM diberi frosting."],[]))
R.append((9032359,"Saus Bolognese Kembang Kol Sehat",
"Mengenyangkan, penuh sayuran, dan dibumbui dengan cita rasa Italia, bolognese kembang kol ini akan mewujudkan impian saus bolognese vegan Anda.",
"6 porsi","1 porsi",
["1 cangkir kenari atau biji labu untuk bebas kacang","½ cangkir tomat kering, dipadatkan perlahan","1 bawang bombai kuning, dibelah empat","4-5 siung bawang putih, dikupas","1 kembang kol, dipecah menjadi kuntum besar","4 cangkir saus tomat atau puree tomat pilihan","2 cangkir kaldu sayuran rendah natrium","½ cangkir lentil merah belah","1 sendok teh oregano kering","½ sendok teh garam laut atau secukupnya","½ sendok teh kemangi kering","½ sendok teh peterseli kering","2 lembar daun salam","½ pon pasta pilihan, bebas gluten jika diinginkan",("Hiasan Opsional","keju Parmesan vegan"),("Hiasan Opsional","peterseli segar")],
["Masukkan kenari dan tomat kering ke dalam mangkuk food processor dan pulsekan hingga hancur dan remah, tanpa dihaluskan. Pindahkan ke mangkuk kecil dan sisihkan.","Sekarang masukkan bawang bombai, bawang putih, dan kuntum kembang kol ke dalam food processor dan pulsekan perlahan hingga tercincang, tetapi jangan berlebihan. Biarkan potongan tetap kasar untuk saus yang mengenyangkan dan tekstur terbaik, kerjakan dalam beberapa kali sesuai kebutuhan. Pindahkan setiap bagian ke panci saus atau wajan dalam antilengket.","Tumis sayuran dengan api sedang-besar, sesekali diaduk, hingga menyusut, sekitar 5-7 menit. Anda tidak memerlukan air atau minyak, karena sayuran akan mengeluarkan air. Tetapi jika ada yang menempel, tambahkan 1-2 sendok makan air.","Kemudian masukkan semua sisa bahan saus: campuran kenari dan tomat kering, saus tomat, kaldu, lentil, dan semua bumbu. Didihkan perlahan selama 20 menit, hingga lentil matang dan saus kental. Cicipi bumbunya dan tambahkan lagi jika perlu. Buang daun salam.","Sementara itu, didihkan panci besar berisi air yang diberi cukup banyak garam, dan masak pasta Anda sesuai petunjuk kemasan hingga 'al dente'. Kemudian sajikan pasta dengan satu sendok besar saus bolognese kembang kol di atasnya."],
["Jangan memproses sayuran secara berlebihan. Anda menginginkan saus bolognese kembang kol yang kasar dan mengenyangkan, jadi pastikan masih ada tekstur.","Didihkan saus perlahan setidaknya selama 20 menit. Perebusan perlahan membuat cita rasa menyatu dengan indah. Jika Anda punya waktu lebih, masak lebih lama. Semakin lama direbus, semakin kuat cita rasanya.","Tambahkan kaldu jika saus menjadi terlalu kental. Saus harus kental dan kaya, tetapi jika terlalu kental, tambahkan setengah cangkir kaldu sayuran.","Beri garam pada air rebusan pasta Anda! Pastikan menambahkan garam yang cukup ke dalam panci air untuk hasil terbaik. Berikut panduan praktis jika diperlukan.","Jangan memasak pasta terlalu matang. Ikuti petunjuk untuk pasta 'al dente'. Al dente berarti 'masih keras saat digigit'. Jika kemasan Anda tidak mencantumkan petunjuk 'al dente', masak pasta 1-3 menit lebih singkat. Pasta 'al dente' masih terasa padat setelah dimasak, dan tidak lembek. Ini memberikan tekstur yang optimal.","Untuk bebas kacang, gunakan biji bunga matahari atau biji labu sebagai pengganti kenari dengan hasil yang serupa.","Untuk kalori lebih rendah, nikmati porsi pasta yang lebih kecil dengan porsi saus bolognese kembang kol yang lebih besar. ATAU gunakan mi zucchini, mi wortel, atau labu spageti.","Untuk saus yang lebih encer, tambahkan lebih banyak kaldu dan/atau saus tomat.","Sisa saus bolognese kembang kol dapat disimpan di lemari es hingga 5 hari dalam wadah tertutup, atau bekukan dalam wadah kedap udara hingga 3 bulan."],[]))
R.append((9038412,"Salad Coleslaw Kacang Thailand [Tanpa Minyak]",
"Coleslaw renyah dengan dressing kacang yang kaya dan creamy membuat salad kacang Thailand ini tak terlupakan.",
"8 porsi","1 porsi",
G("Untuk Salad",["1.5 cangkir buncis, matang atau kalengan (sekitar 1 kaleng 15 ons)","4 cangkir kubis merah, diiris tipis, sekitar setengah kubis kecil","4 cangkir kubis hijau, diiris tipis, sekitar setengah kubis kecil","2 cangkir wortel, dikupas & diparut, sekitar 2 wortel sedang","¼ cangkir bawang merah, diiris tipis","1 cangkir ketumbar segar cincang, batang tebal dibuang (atau peterseli)"])+G("Untuk Dressing",["½ cangkir selai kacang halus","3 sendok makan tamari atau kecap asin jika tidak menghindari gluten","3 sendok makan cuka beras","2 sendok makan air jeruk nipis (sekitar 1 jeruk nipis besar)","2 sendok teh sriracha atau secukupnya","1 sendok teh bubuk bawang putih","½ sendok teh jahe bubuk"]),
["Iris tipis sayuran Anda dan masukkan semua bahan salad ke dalam mangkuk pencampur besar. Sisihkan.","Dalam mangkuk kecil, campurkan semua bahan dressing, menggunakan garpu hingga halus.","Saat siap disajikan, tuang dressing ke atas salad dan aduk rata hingga terlapisi merata."],
["Jika Anda menyiapkannya lebih awal, simpan salad dan dressing secara terpisah hingga siap disajikan. Untuk kemudahan, Anda dapat membeli coleslaw yang sudah diiris untuk mempersingkat waktu persiapan. Tambahkan 1-2 sendok makan air ke dalam dressing kacang, jika perlu, untuk mengencerkan. Salad kacang Thailand ini paling enak saat baru diberi dressing, tetapi sisanya dapat disimpan di lemari es selama 1-2 hari."],[]))
R.append((9039315,"Burger Risotto Jamur",
"Burger risotto jamur ini memiliki gigitan yang mengenyangkan dan \"berdaging\" dengan rasa umami yang melimpah, penuh nutrisi, dan tidak mudah hancur!",
"6 burger","1 porsi",
["2 cangkir nasi basmati merah matang","1 pon jamur kancing putih","1 bawang bombai kuning","4 siung bawang putih, dikupas","1 wortel sedang, dikupas","90 gram kale","½ cangkir kacang polong beku atau kalengan","¼ cangkir ragi nutrisi","½ sendok teh oregano kering","½ sendok teh garam laut atau secukupnya","5-8 sendok makan pati tapioka atau tepung tapioka"],
["Jika Anda tidak punya nasi matang, mulailah dengan memasaknya sesuai petunjuk kemasan sambil menyiapkan bahan lainnya.","Panaskan oven terlebih dahulu hingga 425 derajat F dan alasi loyang dengan kertas roti.","Masukkan jamur ke dalam food processor dan cincang halus, sambil mengerok sisi-sisinya sesuai kebutuhan. Jika food processor Anda lebih kecil, Anda mungkin perlu mengerjakannya dalam beberapa kali.","Pindahkan jamur ke dalam wajan besar dan tumis kering dengan api sedang hingga uap air dan cairan menguap, sekitar 6-8 menit.","Sementara itu, masukkan bawang bombai, bawang putih, wortel, dan kale ke dalam food processor dan cincang halus juga. Kerok sisi-sisinya sesuai kebutuhan, dan pastikan tidak ada potongan besar yang tersisa. Pindahkan ke wajan berisi jamur yang sudah matang, bersama kacang polong, ragi nutrisi, dan bumbu, lalu tumis 2-3 menit lagi, kemudian angkat dari api. Masukkan nasi matang sebanyak 1.5 cangkir ke dalam wajan, aduk rata, cicipi campuran, dan tambahkan garam atau bumbu lain jika diinginkan.","Masukkan sisa setengah cangkir nasi merah matang ke dalam blender kecil bersama satu atau dua sendok makan air, sesuai kebutuhan agar menjadi puree. Setelah halus, pindahkan ke wajan dan aduk rata. Sekarang tambahkan pati tapioka, mulai dengan 5 sendok makan dan aduk hingga tercampur. Bentuk bola di tangan Anda untuk menguji campuran dan melihat seberapa baik adonan menyatu. Anda menginginkan campuran yang menyatu, tetapi tidak terlalu lengket. Jika sangat lengket dan sulit dibentuk menjadi bola atau patty, tambahkan satu atau dua sendok makan pati tapioka lagi, aduk rata, dan uji lagi.","Sekarang bagi campuran menjadi enam patty. Anda akan menggunakan kurang dari 3/4 cangkir campuran per burger. Mulailah dengan membentuk bola di tangan dan meremasnya perlahan untuk memastikan tidak ada celah. Kemudian pipihkan di tangan menjadi bentuk patty dan letakkan di atas loyang. Jangan menekan patty ke loyang atau patty bisa menempel saat dipanggang.","Panggang selama 20 menit, lalu keluarkan dari oven dan balik setiap patty dengan hati-hati. Masukkan kembali ke oven selama 10-15 menit lagi, hingga tepinya cokelat keemasan. Keluarkan dari oven dan diamkan pada suhu ruang selama 5 menit sebelum disajikan."],
["Untuk rasa tambahan, masak nasi merah Anda dalam kaldu sayuran.","Pastikan sayuran Anda dicincang sangat halus, tetapi tidak menjadi puree. Potongan sayuran yang besar tidak akan menyatu dengan baik.","Saat menguji campuran, remas sedikit di tangan Anda untuk melihat seberapa baik adonan menyatu. Nasi puree akan membuat adonan agak lengket, yang berfungsi sebagai pengikat. Namun, adonan tidak boleh terlalu lengket sehingga Anda tidak dapat membentuk bola atau patty tanpa adonan menempel sepenuhnya di tangan Anda. Tambahkan lebih banyak pati tapioka hingga mencapai konsistensi yang sedikit lengket. Anda mungkin membutuhkan antara lima hingga delapan sendok makan. (Ini tergantung pada banyaknya air yang Anda gunakan untuk memblender nasi.)","Saat membentuk patty, lakukan di tangan Anda dan bukan di atas loyang. Karena resep ini tidak menggunakan minyak, jika Anda terlalu menekannya ke loyang, patty akan menempel pada kertas roti. Remas campuran menjadi bola di tangan, lalu pipihkan menjadi bentuk patty dan letakkan dengan lembut di atas loyang. Jika patty masih menempel di tangan, gunakan tangan yang sedikit lembap untuk membentuknya.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari dan Anda dapat memanaskannya kembali di oven atau di wajan di atas kompor. Untuk membekukan, biarkan patty dingin lalu letakkan dalam wadah yang aman untuk freezer dengan patty disusun berlapis di antara lembaran kertas roti agar tidak lengket."],[]))
R.append((9040812,"Cara Membuat Saus Tomat Buatan Sendiri",
"Pernahkah Anda penasaran dengan rahasia Italia dalam membuat saus tomat buatan sendiri? Rahasianya, lengkap dengan petunjuk foto langkah demi langkah, kini terungkap!",
"12 kuart","1 cangkir",
["1 bushel tomat Roma atau San Marzano (sekitar 52 pon), dicuci","½ cangkir minyak zaitun (lihat catatan untuk versi bebas minyak)","2 bawang bombai kuning, dikupas & dibelah empat","1 bawang merah, dikupas & dibelah empat","12 siung bawang putih, dikupas","4-5 lembar daun salam","2 sendok makan garam laut atau secukupnya","1 cangkir daun kemangi segar, dipadatkan longgar","10 sendok teh asam sitrat atau air lemon atau cuka, lihat catatan*"],
["Dengan food processor, proses bawang bombai dan bawang putih hingga tercincang halus, tetapi tidak menjadi puree. Sisihkan.","Belah setiap tomat menjadi dua, sambil memeriksa bagian yang buruk saat memotongnya. (Anda tidak boleh menggunakan tomat yang busuk, karena dapat merusak seluruh saus.)","Didihkan panci besar berisi air dan masukkan tomat yang sudah dipotong. Tomat yang dingin kemungkinan akan membuat air berhenti mendidih. Setelah air kembali mendidih perlahan, segera tiriskan tomat. JANGAN memasak tomat terlalu lama pada langkah ini. Tiriskan setelah air mulai mendidih, dan/atau setelah Anda melihat busa oranye di permukaan air. (Lihat foto sebagai acuan.)","Gunakan penggiling makanan (food mill) untuk menghancurkan tomat Anda sehingga kulit dan bijinya terpisah dan hanya menyisakan saus tomat.","Panaskan minyak bersama bawang bombai, bawang putih, dan daun salam, lalu masak selama sekitar 5 menit, hingga bawang bombai dan bawang putih sedikit keemasan. Awasi dengan cermat agar tidak gosong. Masukkan saus dan garam ke dalam panci dan didihkan perlahan. Masak selama 1 jam, tambahkan kemangi dalam sekitar 20 menit terakhir. Sering-sering diaduk! Anda tidak ingin ada saus yang gosong di dasar panci, atau seluruh saus bisa rusak. Cicipi garamnya, dan sesuaikan jika diinginkan.","Sekarang, tergantung ukuran toples yang Anda gunakan, masukkan asam sitrat ke dasar setiap toples. *lihat catatan","Isi toples dengan hati-hati, sisakan ruang 1/4\" dari bibir toples. Kemudian tutup rapat toples kaca Anda menggunakan tutup dan cincin Bernardin.","Panaskan beberapa inci air dalam panci besar dan letakkan toples yang sudah tertutup ke dalam panci setelah air panas. Jangan masukkan toples ke dalam air dingin! Toples sangat panas, dan memasukkannya ke dalam panci berisi air dingin dapat menyebabkannya retak. Setelah semua toples diletakkan di dalam panci, isi perlahan dengan air secukupnya untuk menutupi semua toples dan didihkan selama minimal 30 menit, lalu matikan api dan biarkan selama 12 jam atau semalaman. (Jadi cukup sampai di sini untuk hari ini.) Setelah air dan toples cukup dingin untuk dipegang, angkat dari panci dan simpan di tempat yang dingin dan gelap hingga 12 bulan."],
["*Untuk asam sitrat, tambahkan ½ sendok teh ke toples ukuran kuart (32 oz) atau ¼ sendok teh ke toples ukuran pint (16 oz) sebelum diisi dengan saus tomat. Meskipun ada cara menggunakan air lemon kemasan atau cuka sebagai pengganti asam sitrat, saya merasa cara ini akan memengaruhi rasa saus Anda. Jadi pilihan kami untuk mengawetkan saus tomat adalah asam sitrat. Jika Anda lebih suka menggunakan air lemon, pastikan menggunakan yang sudah dalam kemasan botol untuk memastikan tingkat keasaman dan pH yang tepat, yang dapat bervariasi pada lemon segar, dan gunakan 1 sendok makan untuk toples pint atau 2 sendok makan untuk toples kuart. Jika Anda lebih suka cuka, gunakan yang berkadar asam 5% atau lebih tinggi, dan tambahkan ¼ cangkir untuk toples kuart atau 2 sendok makan untuk toples pint. Jika Anda menghindari minyak, Anda dapat menumis sayuran dengan air sebagai gantinya. Awasi dengan cermat agar tidak ada yang menempel di dasar panci. Anda tidak ingin ada yang gosong, atau Anda berisiko merusak seluruh saus."],[]))
R.append((9042335,"Mi Thailand Pedas Instant Pot + Petunjuk Memasak di Kompor",
"Mi kacang pedas ala Instant Pot ini benar-benar lezat. Hidangan hari kerja yang hebat dengan persiapan sederhana, dan siap dalam sekejap. Petunjuk memasak di kompor juga tersedia.",
"6 porsi","1 porsi",
["3 wortel besar, dipotong korek api (julienne, potongan tipis panjang)","1 paprika merah, dipotong korek api (julienne, potongan tipis panjang)","4 cangkir air","450 gram Bucatini atau Spageti, gandum utuh atau bebas gluten jika diinginkan","3 bawang daun, diiris tipis",("Untuk Saus Kacang","¼ cangkir selai kacang halus atau yang bertekstur juga boleh"),("Untuk Saus Kacang","2 sendok makan air jeruk nipis (sekitar 1 jeruk nipis besar atau 2 kecil)"),("Untuk Saus Kacang","3 sendok makan cuka beras"),("Untuk Saus Kacang","3 sendok makan tamari atau kecap asin jika tidak menghindari gluten"),("Untuk Saus Kacang","1 sendok teh bubuk bawang putih"),("Untuk Saus Kacang","1-2 sendok makan sriracha (gunakan 1 untuk tingkat pedas ringan)"),("Untuk Saus Kacang","½ sendok teh garam laut"),("Untuk Saus Kacang","½ sendok teh jahe bubuk")],
G("Petunjuk Instant Pot",["Dalam mangkuk kecil, campurkan semua bahan saus dan kocok hingga rata. Sisihkan.","Setel Instant Pot Anda ke mode tumis, tambahkan satu atau dua sendok makan air, wortel, dan paprika merah, lalu tumis hingga agak lunak, sekitar 5 menit. Jangan terlalu matang, karena akan semakin matang bersama mi. Kemudian masukkan saus dan air, lalu aduk sebentar.","Patahkan mi Anda menjadi dua dan letakkan di dalam panci. Pastikan mi terendam air dengan menekannya perlahan dengan spatula jika perlu. Tutup penutup, putar katup ke posisi tertutup (sealing), dan atur ke tekanan tinggi selama 4 menit. (Dibutuhkan sekitar 10 menit untuk membangun tekanan sebelum panci mulai menghitung mundur.)","Setelah selesai, lepaskan uap dengan cepat melalui katup, lalu masukkan bawang daun Anda (sisihkan sebagian untuk hiasan jika diinginkan) dan aduk sebentar. Sajikan dengan hiasan kacang cincang, bawang daun, irisan jeruk nipis, atau tambahan sriracha jika diinginkan."])+G("Petunjuk di Kompor",["Dalam mangkuk kecil, campurkan semua bahan saus dan kocok hingga rata. Sisihkan.","Gunakan wajan besar dan tambahkan satu atau dua sendok makan air, wortel, dan paprika merah, lalu tumis hingga agak lunak, sekitar 5 menit. Kemudian masukkan saus kacang, dan 1 cangkir air, lalu didihkan perlahan selama sekitar 5 menit.","Sementara itu, didihkan panci besar berisi air bergaram, dan masak pasta Anda sesuai petunjuk kemasan. Tiriskan dan kembalikan ke panci. Kemudian tuang saus di atas pasta, aduk rata dan sajikan."]),
["Jangan memasak sayuran Anda terlalu matang saat menumis. Sayuran akan terus matang saat dimasak bertekanan, jadi cukup tumis sebentar saja. Pastikan menekan mi Anda ke dalam campuran air dan saus sebelum memasak bertekanan. Mi yang mencuat di atas cairan tidak akan matang dengan baik. Gunakan selai kacang yang terbuat dari HANYA kacang, tanpa tambahan gula, minyak, atau garam. Mi Instant Pot Anda dapat disimpan di lemari es selama 2-3 hari. Mi akan menyerap saus saat mendingin. Jadi tambahkan sedikit cairan ke wajan saat memanaskan kembali. Gunakan sedikit kaldu, kecap asin atau tamari, atau sedikit air dengan taburan garam."],[]))
build(R,'/mnt/c/WSL/davita/translations/tid0/part1.json')
