from mk import *
R=[]
R.append((9044922,"Sup Kembang Kol Ubi Jalar",
"Sup kembang kol ubi jalar yang creamy ini adalah hidangan yang menghangatkan dan penuh nutrisi, sempurna untuk malam yang nyaman.",
"4 porsi","1 porsi",
["6 cangkir kuntum kembang kol (dari sekitar 1 kembang kol kecil)","1 pon ubi jalar (sekitar 3 ubi kecil yang ramping dan panjang)","1 bawang bombai kuning (dibelah empat)","4-5 siung bawang putih (biarkan kulitnya)","2 sendok makan ragi nutrisi","2 sendok teh paprika asap","1/2 sendok teh jintan","1/2 sendok teh thyme kering","1/8 sendok teh cabai cayenne","4 cangkir kaldu sayuran","1 sendok makan air lemon","garam + merica (secukupnya)"],
["Panaskan oven terlebih dahulu hingga 425℉/218℃ dengan mode panggang konveksi dan alasi loyang dengan kertas roti.","Sikat bersih ubi jalar Anda dan potong menjadi dua memanjang. Letakkan dengan sisi potongan menghadap ke bawah di atas loyang. Kemudian tambahkan kuntum kembang kol, bawang bombai yang dibelah empat, dan siung bawang putih (biarkan kulitnya) ke loyang yang sama. Siram semua sayuran dengan kaldu sayuran (atau Anda boleh menggunakan minyak) dan taburi dengan garam dan merica.","Panggang sayuran di dalam oven selama 20-25 menit, hingga kembang kol cokelat keemasan, dan ubi jalar empuk saat ditusuk garpu. Keluarkan dari oven.","Pindahkan sayuran ke blender ATAU panci jika Anda menggunakan blender tangan, tetapi sisihkan beberapa potongan kembang kol terkecil untuk menghias mangkuk Anda jika diinginkan. Masukkan semua bahan yang tersisa dan blender sup Anda, kerjakan dalam beberapa kali jika perlu.","Sajikan dengan hiasan potongan kembang kol panggang dan daun kucai."],[],[]))
R.append((9046047,"Mousse Alpukat Cokelat 3 Bahan",
"Puaskan keinginan Anda akan cokelat dengan mousse alpukat cokelat 3 bahan yang lezat ini!",
"1 porsi","1 porsi",
["1 pisang yang sangat matang (kulitnya harus berbintik cokelat)","½ alpukat matang","1 sendok makan bubuk kakao mentah tanpa pemanis",("Tambahan Opsional","1 sendok teh sirup maple"),("Tambahan Opsional","½ sendok teh ekstrak vanila murni"),("Tambahan Opsional","1 jumput garam laut"),("Tambahan Opsional","1 jumput kayu manis")],
["Masukkan semua 3 bahan ke dalam blender kecil seperti Magic Bullet, atau food processor mini. Blender hingga halus, tambahkan 1-2 sendok teh air atau susu nabati jika perlu agar mudah berputar.","Cicipi tingkat kemanisannya, dan jika diinginkan, tambahkan satu sendok teh sirup maple. (Jika pisang Anda cukup matang, Anda tidak memerlukan pemanis tambahan.)","Dinginkan selama 1 jam (atau lebih lama) untuk hidangan yang lebih dingin, atau nikmati segera."],
["Tingkat kematangan bahan Anda akan menentukan apakah Anda memerlukan cairan, dan berapa banyak, agar mudah berputar. Mulailah memblender tanpa cairan tambahan dan tambahkan sesuai kebutuhan.","Jadikan camilan cokelat beku dengan membekukannya selama 1 jam sebelum dinikmati."],[]))
R.append((9046931,"Taco Kentang Renyah dengan Kacang Hitam + Coleslaw",
"Pada taco Tuesday berikutnya, pilih taco kentang yang kaya rasa dan sangat menggugah selera ini untuk menu Anda.",
"6 porsi","1 porsi",
["2 pon kentang kuning (sekitar 4 kentang besar atau 8 kecil)","1 sendok makan minyak alpukat atau pilihan Anda (lihat catatan untuk opsi bebas minyak)","1 sendok teh paprika (manis atau asap)","½ sendok teh garam laut atau secukupnya","½ sendok teh rosemary kering","½ sendok teh thyme kering","½ sendok teh bubuk bawang putih","½ sendok teh bubuk bawang bombai","¼ sendok teh jintan","¼ sendok teh merica hitam atau cabai cayenne (opsional untuk taco kentang pedas)","6 tortilla gandum utuh atau jagung","¾ cangkir kacang hitam, matang atau kalengan",("Topping Opsional","coleslaw"),("Topping Opsional","guacamole"),("Topping Opsional","krim mete"),("Topping Opsional","tomat dipotong dadu, irisan jalapeño, zaitun"),("Topping Opsional","ketumbar segar, air jeruk nipis")],
["Panaskan oven terlebih dahulu hingga 450°F / 232°C dengan mode panggang konveksi dan alasi loyang besar dengan kertas roti. Sisihkan.","Kupas dan potong dadu kentang Anda menjadi kubus setengah inci. Anda akan mendapatkan sekitar 4 cangkir kentang dadu. Masukkan ke dalam mangkuk pencampur besar bersama minyak (jika digunakan) dan semua bumbu. Aduk rata.","Susun kentang dadu dalam satu lapisan di atas loyang yang sudah disiapkan dan panggang selama 15 menit. Kemudian balik kentang dan panggang 10-15 menit lagi, hingga renyah.CATATAN: Jika Anda tidak punya oven konveksi, Anda mungkin memerlukan beberapa menit tambahan untuk mencapai tingkat kerenyahan yang diinginkan.","Saat kentang dipanggang, siapkan topping lain yang Anda inginkan. Kemudian rakit taco kentang Anda dengan kentang dalam jumlah banyak dan topping pilihan Anda."],
["Potong kentang dengan ukuran sama rata mungkin agar matang merata. Jangan menumpuk kentang di loyang Anda. Susun dalam satu lapisan dengan banyak ruang agar menjadi renyah dengan baik. Untuk bebas minyak, lewati minyak dan gunakan kaldu yang beraroma sebagai gantinya. Di pertengahan waktu, semprotkan sedikit kaldu atau air lagi pada kentang jika terlihat kering. Awasi dengan cermat agar tidak gosong. Kentang dapat disimpan selama 3-4 hari dalam wadah tertutup di lemari es, namun akan kehilangan sebagian kerenyahannya. Panaskan kembali di oven atau oven toaster agar kembali renyah. Simpan sisa makanan secara terpisah dan rakit tepat sebelum dinikmati. Informasi nilai gizi untuk ⅙ kentang dan kacang hitam dengan satu tortilla dan tidak termasuk topping opsional."],[]))
R.append((9049980,"Salad Quinoa Kubis",
"Salad quinoa kubis ini padat nutrisi dan lezat, dengan dressing segar dan asam yang siap dalam sekejap.",
"8 porsi","1 porsi",
["1 cangkir quinoa","2 cangkir air","½ sendok teh garam laut","3 cangkir kubis ungu, diiris tipis (sekitar setengah kubis kecil)","1 wortel besar, diparut","1 paprika merah, dipotong dadu","2 cangkir jagung beku, dicairkan","1 mentimun besar, dibelah empat memanjang & diiris","3 bawang daun, diiris tipis","½ cangkir ketumbar atau peterseli cincang (dipadatkan)",("Bahan Dressing","1.5 sendok makan cuka beras"),("Bahan Dressing","¼ cangkir tamari atau kecap asin jika tidak menghindari gluten"),("Bahan Dressing","1 jeruk nipis yang baru diperas"),("Bahan Dressing","2 sendok makan wijen"),("Bahan Dressing","1 sendok makan sirup maple (opsional)"),("Bahan Dressing","½ sendok teh bubuk bawang putih"),("Bahan Dressing","¼ sendok teh cabai cayenne")],
["Dalam panci kecil, masukkan quinoa, air, dan garam lalu didihkan dengan api besar. Kemudian kecilkan api dan didihkan perlahan selama 10-12 menit, hingga air terserap. Sisihkan dan biarkan agak dingin.","Dalam mangkuk besar, campurkan semua sayuran cincang dan quinoa yang sudah dingin, lalu aduk rata.","Masukkan semua bahan dressing ke dalam toples kecil atau mangkuk dan aduk. Kemudian tuang dressing ke atas salad dan aduk hingga tercampur.","Dinginkan di lemari es selama 1 jam sebelum disajikan. Atau nikmati segera jika diinginkan."],
["Gunakan parutan kotak atau alat pengiris untuk mengiris kubis dan wortel. Jika menggunakan food processor, kerjakan dalam beberapa kali dan gunakan pulse agar tidak terproses berlebihan. Anda menginginkan kubis dan wortel parut, bukan puree. Untuk tambahan protein, tambahkan satu kaleng buncis atau kacang hitam yang sudah ditiriskan dan dibilas ke dalam campuran. Jika merencanakan sebelumnya, buat dan simpan salad dan dressing dalam wadah terpisah di lemari es. Beri dressing pada salad di hari yang sama saat Anda berencana menikmatinya, untuk tekstur terbaik. Untuk bebas gula, lewati sirup maple dalam dressing. Jika Anda boleh mengonsumsi sedikit gula, saya menyarankannya untuk menyeimbangkan keasaman. Namun, kedua cara tetap terasa enak. Untuk bebas kedelai, gunakan coconut aminos sebagai pengganti tamari. Sisa makanan dapat disimpan di lemari es selama 2 hari. Untuk penyimpanan lebih lama, simpan dressing secara terpisah dan jangan beri dressing pada seluruh salad. Salad tanpa dressing dapat disimpan di lemari es hingga 1 minggu."],[]))
R.append((9054548,"Sup Quinoa Instant Pot dengan Sayuran",
"Sup quinoa Instant Pot yang mengenyangkan, kaya rasa, dan menyehatkan, dengan petunjuk memasak di kompor juga!",
"6 porsi","1 porsi",
["1 bawang bombai kuning, dipotong dadu","2 wortel besar, dipotong dadu","2 batang seledri, dipotong dadu","2 zucchini, dibelah empat memanjang + diiris tebal","1.5 cangkir kacang polong beku","6 cangkir kaldu sayuran rendah natrium","2 cangkir saus tomat atau puree tomat pilihan","1 cangkir quinoa","5 ons bayam muda","½ sendok teh oregano kering","½ sendok teh bubuk bawang putih","½ sendok teh bubuk cabai","garam + merica secukupnya"],
G("Petunjuk Instant Pot",["Setel Instant Pot Anda ke mode tumis. Tambahkan 3-4 sendok makan air, bersama bawang bombai, wortel, dan seledri, lalu tumis hingga lunak, sekitar 5 menit. (Tambahkan air lagi jika perlu agar tidak lengket.)","Masukkan semua bahan yang tersisa, kecuali bayam, lalu aduk sebentar. Kunci penutup pada tempatnya, pastikan katup berada pada posisi tertutup (sealing). Kemudian atur ke tekanan tinggi selama 2 menit. (Dibutuhkan sekitar 15 menit untuk mencapai tekanan.) Setelah selesai, lepaskan uap dengan cepat, buka penutup dan aduk bayam hingga layu."])+G("Petunjuk di Kompor",["Dalam panci sup besar, masukkan 3-4 sendok makan air, bersama bawang bombai, wortel, dan seledri, lalu tumis dengan api sedang hingga lunak, sekitar 5 menit. (Tambahkan air lagi sesuai kebutuhan agar tidak lengket.)","Kemudian masukkan semua bahan yang tersisa, kecuali bayam, tutup panci dengan penutup, dan didihkan perlahan. Lalu didihkan sup dengan api kecil selama 12-15 menit, hingga quinoa matang dan sup mengental. Matikan api, dan aduk bayam hingga layu."]),
["Potong dadu bawang bombai, wortel, dan seledri menjadi potongan kecil, tetapi biarkan potongan zucchini lebih besar agar tidak terlalu matang dan terlalu lembek.","Jika menggunakan metode Instant Pot, pastikan katup pada penutup berada pada posisi tertutup (sealing), atau panci tidak akan mencapai tekanan. Ketika timer selesai, segera lepaskan uap dengan cepat agar tidak terlalu matang.","Jika menggunakan metode kompor, tutup panci atau panci saus Anda dengan penutup selama memasak agar cairan tidak terlalu banyak menguap dan sup tidak menjadi terlalu kental.","Saat sup mendingin, quinoa akan menyerap lebih banyak kaldu. Tambahkan sedikit kaldu ekstra, sesuai kebutuhan, jika sup menjadi lebih kental dari yang Anda inginkan.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari atau dibekukan dalam wadah kedap udara hingga 3 bulan. Pastikan sup didinginkan sebelum dibekukan dan sisakan sedikit ruang untuk pemuaian."],[]))
R.append((9057993,"Wafel Bit",
"Wafel bit vegan yang cerah ini adalah variasi unik yang lezat dari sarapan klasik.",
"10 wafel","1 porsi",
["2 cangkir susu kedelai","2 sendok teh cuka sari apel","1/3 cangkir saus apel tanpa pemanis","2 sendok makan tahini","240 gram tepung gandum utuh (sekitar 2 cangkir)","2 sendok makan bubuk bit","2 sendok teh baking powder"],
["Campurkan susu kedelai dan cuka sari apel dalam mangkuk pencampur besar dan sisihkan selama 5 menit hingga mengental dan menggumpal, membentuk buttermilk vegan Anda.","Panaskan terlebih dahulu cetakan wafel Anda dengan api sedang/besar, atau sesuai petunjuk pabrikan.","Dalam mangkuk sedang, kocok semua bahan kering: tepung, bubuk bit, baking powder.","Sekarang susu kedelai Anda seharusnya sudah menggumpal, jadi masukkan saus apel dan tahini ke dalam mangkuk lalu aduk. Kemudian masukkan bahan kering ke mangkuk yang sama dan aduk hingga tercampur tanpa mengaduk berlebihan.","Masak wafel selama 6-8 menit, atau sesuai petunjuk pabrikan. Jangan membuka penutup terlalu cepat atau wafel dapat menempel dan patah. Periksa dengan hati-hati dan jika tampak menempel, masak 1-2 menit lagi dan periksa kembali."],[],[]))
R.append((9064307,"Pizza Keju Vegan",
"Pizza keju vegan yang SEMUANYA TENTANG KEJU.",
"8 potong","1 porsi",
["adonan pizza 12 inci (1 bulatan yang dapat dipipihkan hingga sekitar 12 inci)","⅓ cangkir saus tomat","1 sendok teh oregano kering","1 sendok teh bubuk bawang putih","1 cangkir penuh menggunung mozzarella vegan","6-8 lembar kemangi segar"],
["Panaskan oven terlebih dahulu hingga 450℉/232℃ dengan mode panggang konveksi dan siapkan loyang pizza 12 inci. (Jika Anda tidak punya konveksi, gunakan suhu yang sama dengan panggang biasa.)","Pipihkan adonan Anda di atas meja dapur atau talenan yang ditaburi tepung dan pindahkan dengan hati-hati ke loyang Anda.","Oleskan saus tomat secara merata dan taburkan bumbu di atasnya. Kemudian sebarkan mozzarella dengan banyak untuk menutupi saus.","Panggang selama 10-12 menit, atau hingga tingkat kematangan yang diinginkan tercapai."],
["Taburi meja dan rolling pin Anda dengan tepung agar tidak lengket saat memipihkan adonan pizza.","Jika Anda tidak punya oven konveksi, gunakan suhu panggang yang sama, dan tambah waktu memasak sesuai kebutuhan.","Sisa makanan dapat disimpan di lemari es selama 2-3 hari dalam wadah tertutup atau dibekukan dalam wadah kedap udara hingga 3 bulan."],[]))
R.append((9064409,"Bliss Ball Lemon Mudah",
"Bliss ball lemon adalah camilan lezat dan bergizi yang sempurna untuk memuaskan keinginan Anda akan makanan manis dengan bahan-bahan sehat.",
"22 bola","1 porsi",
["1 cangkir mete mentah","½ cangkir kelapa parut tanpa pemanis ditambah lebih banyak untuk menggulung","1 cangkir kurma tanpa biji, dipadatkan","1 sendok makan parutan kulit lemon (dari sekitar 1 lemon besar)","2 sendok makan air lemon","2-4 sendok makan air"],
["Masukkan semuanya ke dalam food processor, mulai dengan 2 sendok makan air. Proses hingga hancur dan Anda mendapatkan campuran yang lengket dan tercampur rata. Tambahkan air lagi jika perlu.","Ambil adonan menggunakan sendok kue kecil dan gulung menjadi bola. Letakkan setiap bliss ball lemon di atas piring, loyang, atau selembar kertas roti. Ulangi dengan sisa adonan. Anda akan mendapatkan sekitar 22 energy ball.","Opsional: Gulung setiap bola dengan kelapa parut tambahan menggunakan piring dangkal."],
["Jangan memproses campuran secara berlebihan. Bola lemon ini paling enak dengan sedikit tekstur.","Parut kulit lemon sebelum memeras airnya! Dan gunakan air lemon segar untuk hasil terbaik.","Simpan bola dalam wadah kedap udara di lemari es hingga 5 hari, atau bekukan hingga 3 bulan."],[]))
R.append((9066125,"Saus Gravy Miso",
"Saus gravy miso yang asin, gurih, dan sangat kaya rasa, tersaji di meja Anda dalam 10 menit atau kurang.",
"8 porsi","1 porsi",
["2 sendok makan pasta miso putih","¾ sendok teh bubuk bawang putih","¾ sendok teh bubuk bawang bombai","½ sendok teh mustard kuning","¼ cangkir tepung gandum utuh putih atau tepung beras merah untuk bebas gluten","2 cangkir kaldu sayuran *gunakan kaldu yang asin/beraroma kuat"],
["Kocok semua bahan dalam panci kecil dan didihkan.","Kemudian kecilkan api ke sedang untuk menjaga didihan tetap perlahan dan kocok sesering mungkin hingga mengental. Sajikan hangat."],
["Pastikan mengocok bahan pada suhu ruang (sebelum mulai memanaskan gravy) agar tepung tidak menggumpal. Untuk gravy miso yang lebih kental, tambahkan 2 sendok makan tepung lagi. Untuk bebas gluten, gunakan tepung beras merah. Sisa makanan dapat disimpan di lemari es dalam wadah tertutup hingga 5 hari, atau dibekukan dalam wadah kedap udara hingga 3 bulan. Gravy akan mengental saat dingin, jadi encerkan dengan sedikit kaldu atau air sesuai kebutuhan dan panaskan kembali di atas kompor."],[]))
R.append((9066355,"Creme Brulee Vegan [Tanpa Gula Rafinasi!]",
"Creme brulee vegan yang creamy dan sangat halus dengan topping gula yang renyah!",
"3 porsi","1 porsi",
G("Untuk Dasar Custard",["12 ons (340 gram) tahu ekstra padat, ditiriskan, gunakan kedelai bebas GMO jika memungkinkan","¼ cangkir gula kelapa tanpa pemurnian","¼ cangkir sirup maple","2 sendok teh ekstrak vanila murni","1 sendok makan air lemon"])+G("Untuk Topping",["3-6 sendok teh gula kelapa (1 sendok teh untuk setiap ramekin)"])+G("Untuk Hiasan",["raspberry, blackberry, stroberi, mint"]),
["Masukkan semua bahan untuk dasar custard ke dalam food processor dan blender hingga benar-benar tercampur dan halus, sambil mengerok sisi-sisinya sesuai kebutuhan.","Pindahkan campuran ke ramekin Anda. (Saya menggunakan tiga ramekin 6 ons, atau Anda dapat menggunakan enam ramekin 3-4 ons untuk porsi tambahan.) Kemudian dinginkan di lemari es setidaknya satu jam (atau semalaman.)","Selanjutnya, taburkan satu sendok teh gula kelapa di atas setiap dasar. Kemudian gunakan blow torch untuk membakar gula hingga gelap dan renyah. Tunggu 2-3 menit agar topping gula dingin lalu hias sesuai selera."],
["Obor gas propana sangat mudah terbakar dan harus dijauhkan dari panas, api terbuka, dan paparan sinar matahari yang lama. Gunakan hanya di area dengan ventilasi yang baik dan ikuti petunjuk pabrikan obor.","Menggunakan gula kelapa tanpa pemurnian untuk topping berarti topping Anda akan lebih gelap daripada creme brulee tradisional yang menggunakan gula putih.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari, tetapi paling enak saat gulanya baru “dibakar”."],[]))
R.append((9067847,"Ubi Jalar Panggang Air Fryer",
"Buat ubi jalar panggang di air fryer Anda dalam sekejap! Sangat lezat dan lebih cepat daripada metode oven.",
"2 porsi","1 porsi",
["2 ubi jalar yang panjang dan ramping, disikat bersih (sekitar 6-7 inci panjang/2-3 inci lebar)","1 sendok teh minyak alpukat (opsional, pilih metode memasak yang sesuai di bawah)",("Topping Opsional","tomat dipotong dadu"),("Topping Opsional","krim mete"),("Topping Opsional","peterseli segar, ketumbar atau daun kucai")],
["Sikat bersih kentang Anda, kemudian gunakan garpu atau pisau untuk menusuknya di seluruh permukaan. Ini akan mencegah kentang meletus di beberapa bagian saat di-air fry.",("Untuk memasak dengan minyak opsional","Gunakan kuas silikon atau tangan Anda untuk mengoleskan minyak ke permukaan kentang lalu air fry pada suhu 400 derajat F selama 20-30 menit, hingga lunak dan garpu mudah menembus kentang."),("Untuk bebas minyak","Air fry kentang pada suhu 350 derajat F selama 25-35 menit, hingga lunak dan mudah ditusuk dengan garpu. Menggunakan suhu yang lebih rendah tanpa minyak mencegah kulit gosong sebelum bagian dalam sempat matang.")],[],[]))
R.append((9070331,"Steak Kembang Kol Air Fryer",
"Steak kembang kol air fryer ini lezat, sehat, dan siap di meja dalam sekejap.",
"2 porsi","1 porsi",
["1 kembang kol besar","2 sendok makan kaldu sayuran","1 sendok makan air jeruk nipis (sekitar setengah jeruk nipis)","1 sendok teh paprika asap","1 sendok teh bubuk bawang putih","½ sendok teh garam laut","¼ sendok teh merica hitam"],
["Cuci kembang kol Anda dan buang daun hijaunya, tetapi jangan potong batangnya.","Kemudian letakkan kembang kol dengan sisi batang menghadap ke bawah di atas talenan, dan potong kedua ujungnya agar rata, sisihkan potongan lepas yang patah. (Lihat foto proses di atas sebagai acuan.)","Sekarang potong irisan tebal (sekitar 1.25 inci tebal) dari bagian yang tersisa menjadi 2 atau 3 steak (tergantung ukuran kembang kol Anda).","Dalam mangkuk kecil, campurkan semua bahan marinasi dan aduk rata. Kemudian olesi satu sisi setiap steak, letakkan dengan sisi yang diolesi saus menghadap ke bawah di keranjang air fryer Anda, lalu olesi sisi lainnya.","Air fry pada suhu 375°F/190°C selama 10 menit, lalu balik steak dengan hati-hati dan lanjutkan air fry selama 5-8 menit lagi, atau hingga kembang kol empuk dan tepinya cokelat keemasan."],
["Tergantung ukuran kembang kol Anda, Anda akan mendapatkan 2 atau 3 steak. Jika Anda membuat 3 steak, tingkatkan bahan marinasi menjadi sebagai berikut: 3 sendok makan kaldu","1.5 sendok makan air jeruk nipis","1.5 sendok teh paprika asap","1.5 sendok teh bubuk bawang putih","¾ sendok teh garam laut","⅜ sendok teh merica hitam (atau ¼ + ⅛)","Gunakan pisau yang tajam, dan usahakan sebaik mungkin memotong steak kembang kol dengan ukuran sama rata agar matang merata.","Untuk menghemat waktu, Anda dapat membeli steak kembang kol yang sudah dipotong dari supermarket.","Sisa makanan dapat disimpan di lemari es selama 2-3 hari dalam wadah tertutup. Jangan dibekukan."],[]))
R.append((9074637,"Es Lolly Persik Kelapa Vegan",
"Es lolly persik vegan ini adalah camilan sehat dan lezat hanya dengan DUA bahan.",
"6 es lolly","1 es lolly",
["300 gram persik matang (sekitar 2 persik)","¾ cangkir (177 ml) santan tanpa pemanis Thai Kitchen atau susu pilihan","2 sendok makan sirup maple (opsional)","1 sendok teh ekstrak vanila murni (opsional)","¼ sendok teh kayu manis (opsional)"],
["Cuci dan iris persik Anda, lalu buang bijinya. Masukkan ke dalam blender atau food processor bersama santan dan bahan opsional apa pun yang Anda gunakan. Pulsekan hingga sebagian besar tercampur, sisakan beberapa potongan persik kecil untuk tekstur.","Bagi campuran secara merata ke enam cetakan es lolly lalu ketukkan cetakan ke meja dapur untuk mengeluarkan gelembung udara. Pasang tutup di atasnya dan bekukan selama 6 jam atau semalaman. Simpan dalam keadaan beku hingga disajikan.CATATAN: Jika menggunakan tongkat es lolly, bekukan es lolly selama 1-2 jam, cukup agar tongkat dapat berdiri tegak, lalu masukkan tongkat dan lanjutkan membekukan hingga padat.",("Untuk melepaskan dari cetakan","Isi mangkuk dengan air hangat, setinggi cetakan Anda, dan letakkan cetakan di dalamnya, tanpa meluap ke bagian atas tempat tongkat berada. Tunggu 15-20 detik sebelum mengangkatnya, lalu gunakan gerakan menggoyang ke kiri dan kanan untuk melepaskan es lolly dari cetakan."),("Untuk melepaskan dari cetakan","Anda juga dapat mengalirkan air hangat dari keran bak cuci ke es lolly selama 15-20 detik, atau hingga mudah lepas."),("Untuk melepaskan dari cetakan","Jika es lolly masih lunak, letakkan di atas piring dan kembalikan ke freezer.")],
["Saat persik sedang musimnya dan sangat manis, Anda dapat melewatkan sirup maple opsional untuk hidangan penutup tanpa tambahan gula. Untuk potongan buah yang lebih kasar dalam es lolly persik Anda, gunakan food processor dan jangan memproses berlebihan. Untuk es lolly persik yang benar-benar halus, gunakan blender hingga menjadi puree. (Jika Anda punya anak yang pilih-pilih makanan, inilah caranya.) Jika menggunakan tongkat es lolly (sebagai pengganti tutup bawaan cetakan Anda), bekukan es lolly selama 1-2 jam, cukup agar tongkat dapat berdiri tegak, lalu masukkan tongkat dan lanjutkan membekukan hingga padat. Waktu pembekuan akan bervariasi sesuai ketebalan cetakan Anda. Sebagian besar es lolly akan beku dalam 4-6 jam. Untuk lemak lebih sedikit, gunakan santan kalengan LIGHT. Untuk rendah lemak, gunakan susu nabati lain seperti susu almond, atau susu mete sebagai pengganti santan. Perhatikan, es lolly persik akan terasa kurang kaya dengan cara ini."],[]))
R.append((9077170,"Brownies Buncis Sehat Rahasia",
"Brownies buncis tanpa tepung ini lembut padat, penuh cokelat, mewah, dimaniskan secara alami, dan menyehatkan!",
"9 potong","1 porsi",
["1 cangkir kurma tanpa biji, dipadatkan","¼ cangkir air","1 kaleng 15 ons buncis, ditiriskan tetapi cairannya disisihkan","3 sendok makan aquafaba dari cairan buncis yang disisihkan di atas","½ cangkir selai kacang alami (halus atau berbutir)","⅓ cangkir bubuk kakao mentah tanpa pemanis",("Tambahan Opsional","⅓ cangkir keping cokelat vegan"),("Tambahan Opsional","½ cangkir potongan kenari")],
["Panaskan oven Anda terlebih dahulu hingga 350℉/176℃ dan alasi loyang persegi 8 inci dengan kertas roti.","Masukkan kurma dan air ke dalam food processor dan proses hingga menjadi pasta halus. Kemudian tambahkan buncis, aquafaba, selai kacang, kakao, lalu proses hingga tercampur rata.","Selanjutnya, tambahkan tambahan opsional, jika digunakan, dan pulsekan beberapa kali untuk mencampurnya tanpa memproses berlebihan.","Sendokkan adonan brownies ke dalam loyang Anda dan ratakan bagian atasnya dengan spatula silikon. Adonan akan sangat kental, jadi tekan ke bawah untuk memastikan tidak ada celah. Taburkan keping cokelat dan kenari lebih banyak di atasnya jika diinginkan dan panggang selama 25-30 menit.","Biarkan dingin di dalam loyang selama 5 menit, lalu angkat brownies menggunakan kertas roti, dan pindahkan ke talenan. Biarkan dingin SETIDAKNYA 20 menit sebelum diiris."],
["Untuk bebas kacang, gunakan wow butter atau sun butter sebagai pengganti selai kacang dan lewati kenari opsional. Silakan ganti dengan buah kering, seperti kismis atau cranberry, jika diinginkan. Untuk brownies yang lebih manis, tambahkan 1-2 sendok makan sirup maple ke campuran setelah memproses kurma, dan/atau gunakan hingga ½ cangkir keping cokelat. Gunakan kertas roti untuk mengalasi loyang Anda agar lebih mudah mengangkat brownies setelah dipanggang. Jangan memanggang terlalu lama! Pemanggangan berlebihan akan menghasilkan brownies yang lebih kering dan kurang terasa lembut padat. Brownies akan tampak belum matang saat Anda mengeluarkannya dari oven, tetapi akan mengeras saat dingin. Basahi pisau Anda di antara setiap potongan saat mengiris brownies agar tepinya lebih halus dan tidak lengket. Sisa makanan dapat disimpan dalam wadah kedap udara pada suhu ruang hingga 4 hari."],[]))
build(R,'/mnt/c/WSL/davita/translations/tid0/part2.json')
