from mk import *
R=[]
R.append((9111240,"Pancake Pisang Lentil [Tanpa Minyak]",
"Entah untuk sarapan atau makan malam, pancake protein vegan ini wajib dicoba! Rasanya manis, sederhana, dan lezat, dan Anda tidak akan menyangka pancake ini dibuat dari lentil!",
"5 (Menghasilkan 20 pancake 4\")","1 porsi",
["1 cangkir lentil merah BELAH yang direndam dalam air mendidih panas selama 30 menit*","1 cangkir oat gulung, bebas gluten jika diinginkan","1 pisang besar matang, dikupas","1 sendok teh kayu manis","1 sendok teh ekstrak vanila murni, gelap atau bening","1.5 cangkir susu mete tanpa pemanis atau susu nabati pilihan","1 sendok makan baking powder","¼ cangkir sirup maple (opsional)"],
["Didihkan beberapa cangkir air dalam ketel atau panci saus kecil. Kemudian masukkan lentil merah belah mentah Anda ke dalam mangkuk tahan panas. Tuang air panas di atasnya, hingga lebih dari menutupi lentil karena akan mengembang, dan rendam selama 30 menit.","Panaskan terlebih dahulu griddle antilengket dengan api sedang/besar. Kemudian tiriskan lentil Anda dan masukkan ke blender berkecepatan tinggi (saya menggunakan Vitamix), bersama SEMUA bahan yang tersisa. Proses dengan kecepatan tinggi hingga halus.","Tuang adonan Anda langsung dari corong blender ke griddle panas Anda, untuk membuat pancake selebar sekitar 4 inci. Jika perlu, gunakan bagian belakang sendok atau sendok sayur untuk memipihkan pancake sedikit agar tipis, supaya matang merata. Masak selama 4-5 menit, hingga tepinya tampak set, lalu balik dan masak 4-5 menit lagi hingga cokelat keemasan.","Sajikan dengan sirup maple, irisan pisang, kenari, atau buah beri segar."],
["* Untuk merendam lentil Anda, didihkan sedikit air lalu angkat dari api. Masukkan lentil dan rendam selama 30 menit, lalu tiriskan. Atau didihkan air dalam ketel dan tuang ke atas semangkuk lentil merah belah Anda dalam mangkuk tahan panas. JANGAN mengganti lentilnya. Anda HARUS menggunakan hanya lentil merah belah untuk resep pancake lentil ini. Blender adonan pancake selama sekitar 1 menit penuh untuk memastikan tidak ada bagian berpasir yang tersisa. Masak pancake lentil ini sedikit lebih lama daripada pancake klasik. Pancake ini tidak akan banyak membentuk gelembung sebagai tanda untuk membaliknya. Sebaliknya, carilah tepi yang tampak set dan keemasan sebelum membaliknya. Jika adonan menjadi terlalu kental saat didiamkan di dalam blender di antara adonan yang dimasak, pipihkan sedikit pancake Anda setelah dituang ke griddle panas. Gunakan bagian belakang sendok atau sendok sayur untuk menipiskannya, jika perlu. Ini akan memastikan pancake matang merata. Satu porsi = EMPAT pancake lentil 4 inci dalam informasi nilai gizi di bawah. Sisa makanan dapat disimpan di lemari es selama 3-4 hari atau dibekukan hingga 2 bulan. Pastikan didinginkan hingga suhu ruang sebelum dibekukan, dan panaskan kembali/cairkan di toaster."],[]))
R.append((9113470,"Blondies Vegan dengan Kacang Putih",
"Blondies vegan yang kaya dan lembut padat dengan dasar kacang putih! Lezat, manis, dan menyehatkan!",
"8 porsi","1 porsi",
["1.25 cangkir kacang cannellini putih (sekitar 1 kaleng 13.5 ons, ditiriskan + dibilas)","100 gram tepung almond blanched (sekitar 1 cangkir)","½ cangkir gula kelapa tanpa pemurnian","⅓ cangkir saus apel tanpa pemanis","¼ cangkir selai almond","¼ cangkir keping cokelat vegan (opsional, tetapi disarankan)"],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi loyang roti dengan kertas roti. Sisihkan.","Masukkan semuanya kecuali keping cokelat ke dalam food processor dan blender hingga halus dan tercampur.","Pindahkan adonan blondie ke loyang roti Anda dan ratakan bagian atasnya dengan sendok kayu atau spatula silikon. Kemudian taburi dengan keping cokelat jika Anda menggunakannya. Tekan perlahan.","Panggang blondies vegan di oven yang sudah dipanaskan selama 30 menit, atau hingga tusuk gigi yang ditusukkan ke tengah keluar bersih dan kering. Kemudian keluarkan dari oven dan biarkan dingin selama 10-15 menit dalam loyang sebelum dipindahkan ke rak kawat untuk melanjutkan pendinginan. Blondies akan lebih mudah diiris setelah dingin."],
["Gunakan kertas roti untuk mengalasi loyang Anda. Meskipun mengolesi dengan lemak juga bisa membuatnya antilengket, akan jauh lebih mudah mengangkat brownies dengan kertas tersebut. (Dan brownies akan dingin lebih cepat dengan cara ini!)","Basahi pisau Anda di antara setiap potongan saat mengiris blondies, agar tepi lebih halus, lebih indah, dan tidak lengket.","Keping cokelat opsional TERMASUK dalam informasi nilai gizi di bawah.","Sisa makanan dapat disimpan pada suhu ruang selama 2-3 hari, hingga 1 minggu di lemari es, atau dibekukan hingga 3 bulan."],[]))
R.append((9114619,"Saus Chimichurri Tanpa Minyak",
"Chimichurri tanpa minyak dengan rempah segar, air jeruk nipis segar, dan cuka anggur merah yang asam adalah topping terbaik untuk semua hidangan panggang favorit Anda.",
"8 porsi (menghasilkan sekitar 1 cangkir)","2 Sendok makan",
["1 cangkir peterseli daun pipih, dipadatkan rapat (batang tebal dibuang)","½ cangkir ketumbar segar, dipadatkan rapat (batang tebal dibuang)","3-4 siung bawang putih, dikupas","1 sendok teh oregano kering","½ sendok teh garam laut","1 sendok teh paprika (manis atau asap)","1 sendok makan air jeruk nipis (sekitar setengah jeruk nipis)","¼ cangkir cuka anggur merah"],
["Masukkan semua bahan, kecuali air jeruk nipis dan cuka, ke dalam food processor Anda. Proses hingga tercincang halus.","Kemudian pindahkan rempah ke mangkuk atau toples dan tuang air jeruk nipis dan cuka. Aduk rata dan diamkan selama 1 jam agar cita rasa menyatu. Sajikan dengan hidangan panggang favorit Anda."],
["Apakah Anda tidak suka ketumbar? Kami menyukainya, tetapi saya tahu sebagian dari Anda tidak. Tidak masalah. Gunakan saja peterseli seluruhnya, atau perbandingan ketumbar yang lebih kecil. Jika Anda tidak punya cuka anggur merah, cuka anggur putih atau cuka sari apel juga bisa. Ingin rasa pedas? Tambahkan sejumput cabai cayenne atau serpihan cabai merah. Ingin cita rasa asap? Gunakan paprika asap sebagai pengganti paprika manis dan/atau tambahkan sedikit liquid smoke. Ganti jeruk sitrus jika diinginkan. Gunakan lemon sebagai pengganti jeruk nipis, atau kombinasi keduanya, atau tambahkan sedikit jeruk segar yang diperas ke dalam campuran untuk sentuhan manis. Jangan memasukkan cairan ke food processor bersama rempah. Rempah harus dicincang halus SEBELUM menambahkan cairan agar campuran tidak menjadi puree. Jika Anda tidak ingin memindahkan bahan ke mangkuk untuk dicampur dengan cairan, masukkan cairan ke processor SETELAH bahan lain dicincang halus dan pulsekan satu atau dua kali (JANGAN LEBIH) untuk mencampur."],[]))
R.append((9115856,"Kue Kering Pisang Tepung Almond",
"Kue kering pisang dengan tepung almond ini manis alami, lembap, dan lezat!",
"16 kue kering","1 porsi",
["1/2 cangkir pisang lumat (sekitar 1 pisang besar atau 2 kecil)","1 sendok teh ekstrak vanila murni","150 gram tepung almond blanched (sekitar 1.5 cangkir)","1/2 sendok teh baking powder","1/4 sendok teh kayu manis","1/8 sendok teh garam laut"],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi loyang dengan kertas roti.","Lumatkan pisang ke dalam mangkuk pencampur sedang. Kemudian tambahkan semua bahan yang tersisa dan aduk hingga tercampur.","Sendokkan adonan kue kering ke loyang beralas Anda, menggunakan sendok makan atau sendok kue untuk mendapatkan sekitar 16-18 kue kering. Anda dapat menekannya untuk kue yang lebih pipih, atau biarkan bulat untuk kue yang lebih empuk. (Saya lebih suka yang bulat dan empuk.)","Panggang selama 12-15 menit, atau hingga tepi kue kering cokelat keemasan dan terasa padat saat disentuh. Keluarkan loyang dari oven dan biarkan dingin selama 5-10 menit sebelum dinikmati."],[],[]))
R.append((9117377,"Cara Membuat Selai Almond",
"Tidak ada yang sebanding dengan selai almond buatan sendiri, dan yang ini hanya membutuhkan 1 bahan!",
"16 porsi masing-masing 1 sendok makan","1 porsi",
["2 cangkir almond","¼ sendok teh garam laut (opsional)"],
["Panaskan oven terlebih dahulu hingga 350 derajat dan alasi loyang besar dengan kertas roti. Susun almond dalam satu lapisan dan panggang selama 8-10 menit. Almond siap ketika cokelat keemasan, tetapi TIDAK gosong. Keluarkan dari oven.","Masukkan almond dan garam (jika digunakan) ke dalam food processor. Proses dengan kecepatan tinggi hingga creamy, berhenti untuk mengerok sisi-sisinya sesering mungkin. Almond akan berubah dari utuh, menjadi tepung, menjadi gumpalan, menjadi bola besar, dan akhirnya, menjadi selai yang creamy dan lezat. Dibutuhkan beberapa menit pemrosesan, antara 3-10 menit. Beri mesin Anda jeda 30-60 detik, sesuai kebutuhan, agar tidak terlalu panas.","Pindahkan ke wadah atau toples yang bersih dan kering dan gunakan seperti selai kacang-kacangan lainnya."],
["Beri mesin Anda jeda singkat di antara pemrosesan agar tidak terlalu panas. Matikan food processor Anda selama 30-60 detik setiap kali, sesuai kebutuhan, lalu lanjutkan. Gunakan jeda itu untuk mengerok sisi-sisinya. Selai almond buatan sendiri Anda akan melalui banyak tahap, dan mungkin terasa seperti tidak akan pernah menjadi selai, tetapi pasti akan jadi. Berubah dari almond utuh, menjadi potongan hancur, menjadi tepung, menjadi gumpalan kecil, lalu gumpalan besar, lalu satu bola raksasa, dan akhirnya selai kacang yang creamy. (Lihat foto proses di atas sebagai gambaran.) Simpan dalam wadah atau toples yang bersih dan kering pada suhu ruang hingga 1 minggu, atau dinginkan di lemari es hingga 4 minggu. Anda dapat membekukannya dalam wadah kedap udara yang aman untuk freezer hingga 4 bulan."],[]))
R.append((9122275,"Casserole Enchilada Vegan",
"Casserole enchilada vegan yang penuh sayuran, mudah dibuat, dan kaya cita rasa.",
"6 porsi","1 porsi",
["1 cangkir quinoa mentah","1 kaleng 15 ons kacang hitam, ditiriskan + dibilas","4 paprika warna apa saja, dipotong dadu","3.5 cangkir ubi jalar dipotong dadu ½ inci, sekitar 1 ubi jalar besar","1 zucchini, dipotong dadu","1 cangkir jagung","2 cangkir kaldu sayuran rendah natrium",("Untuk Saus Enchilada","1-3 jalapeño, dicincang halus"),("Untuk Saus Enchilada","2 cangkir kaldu sayuran rendah natrium"),("Untuk Saus Enchilada","4 sendok makan pasta tomat"),("Untuk Saus Enchilada","1 sendok teh bubuk bawang putih"),("Untuk Saus Enchilada","1 sendok teh bubuk cabai"),("Untuk Saus Enchilada","1 sendok teh jintan"),("Untuk Saus Enchilada","½ sendok teh garam laut atau secukupnya"),("Hiasan Opsional","krim mete"),("Hiasan Opsional","saus keju kenari"),("Hiasan Opsional","guacamole"),("Hiasan Opsional","salsa"),("Hiasan Opsional","ketumbar segar")],
G("Untuk Saus Enchilada",["Masukkan jalapeño dengan satu atau dua sendok makan kaldu Anda ke dalam panci saus kecil dan tumis selama 2 menit.","Masukkan semua bahan yang tersisa, aduk rata, dan didihkan. Kemudian kecilkan api ke sedang-kecil dan didihkan perlahan selama 8 menit hingga sedikit menyusut. Sisihkan."])+G("Untuk Casserole Enchilada",["Panaskan oven Anda terlebih dahulu hingga 400℉/204℃ dan siapkan loyang yang berukuran 11x15 inci atau serupa.","Sementara itu, cincang semua sayuran Anda dan masukkan ke dalam loyang bersama quinoa mentah. Tuang 2 cangkir kaldu dan 2 cangkir saus enchilada yang baru Anda buat di atasnya. Aduk rata.","Tutup loyang dengan foil dan panggang selama 30 menit. Kemudian buka foil, aduk semuanya sebentar, dan panggang 15-20 menit lagi, hingga cairan sebagian besar terserap dan ubi empuk ditusuk garpu.","Sajikan dengan topping pilihan Anda."]),
["Potong dadu ubi jalar dengan ukuran lebih kecil (tidak lebih besar dari potongan setengah inci) agar cukup lunak saat dipanggang.","Jika menggunakan saus enchilada kemasan, tambahkan bumbu ekstra seperti jintan, bubuk cabai, dan/atau paprika untuk menambah cita rasa.","Hidangan akan tampak berair pada awalnya. Jangan khawatir! Saat quinoa matang, quinoa akan menyerap semua cairan. Jika ada cairan tersisa di akhir pemanggangan, diamkan hidangan pada suhu ruang selama 5-7 menit untuk menyerap kelebihan cairan.","Informasi nilai gizi adalah untuk satu per enam casserole termasuk saus enchilada buatan sendiri, tetapi tanpa topping opsional."],[]))
R.append((9122292,"Puding Pisang Vegan",
"Puding pisang vegan yang manis alami, creamy, dan sangat lezat!",
"2 porsi","1 porsi",
["2 pisang matang","1/2 cangkir almond blanched","6-8 kurma","1 sendok teh ekstrak vanila murni","1-3 sendok makan susu almond (atau susu nabati pilihan)","buah beri segar, irisan pisang, almond serut, parutan kelapa, keping cokelat"],
["Masukkan semuanya ke dalam blender atau food processor, mulai dengan hanya 1 sendok makan susu. Blender hingga halus, dan tambahkan lebih banyak susu jika perlu. Ini akan bervariasi tergantung seberapa kering kurma Anda, dan seberapa bertenaga alat Anda. Terus proses hingga campuran halus dan creamy, sambil mengerok sisi-sisinya, sesuai kebutuhan.","Dinginkan puding di lemari es selama 1 jam atau lebih lama. Kemudian bagi campuran ke dalam dua cangkir dan beri topping sesuai selera."],[],[]))
R.append((9124659,"Jamur Isi Vegan dengan Risotto Cranberry",
"Jamur isi vegan dengan risotto cranberry yang creamy adalah hidangan pembuka yang indah dan lezat.",
"15 jamur","1 porsi",
["15 jamur untuk diisi (jamur cremini besar atau jamur kancing putih)","½ bawang bombai kecil, dicincang halus","2 siung bawang putih, dicincang halus","½ cangkir beras arborio","3 cangkir kaldu sayuran rendah natrium","⅓ cangkir cranberry kering tanpa pemanis","garam + merica secukupnya",("Hiasan Opsional","keju parmesan vegan")],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi loyang dengan kertas roti.","Gunakan pisau kecil untuk melepaskan batang jamur dengan hati-hati, cincang halus, dan sisihkan. Kemudian gunakan sendok kecil untuk mengerok bagian insang dengan lembut dan buang.","Letakkan jamur dengan sisi berongga menghadap ke bawah di atas loyang Anda dan panggang selama 10 menit. Keluarkan dari oven dan gunakan lap piring bersih atau tisu dapur untuk menyerap kelebihan air yang dikeluarkan jamur saat dipanggang. (Keringkan juga kertas rotinya.) Kemudian balik dengan sisi berongga menghadap ke atas dan sisihkan.","Sementara itu, masukkan bawang bombai, bawang putih, dan batang jamur cincang ke dalam wajan besar dan taburi dengan garam dan merica. Tumis kering selama sekitar 5 menit (jamur akan mengeluarkan air sehingga Anda tidak memerlukan minyak) hingga lunak dan menyusut. Kemudian masukkan beras dan aduk rata, masak/sangrai selama sekitar 30 detik.","Tambahkan sekitar 1/2 cangkir kaldu ke wajan Anda, sering diaduk hingga terserap. Lanjutkan menambahkan kaldu sekitar 1/2 cangkir setiap kali, sering mengaduk risotto Anda. Tunggu hingga cairan terserap sebelum menambahkan porsi kaldu berikutnya. Ulangi hingga semua 3 cangkir kaldu terpakai. Ini akan memakan waktu sekitar 20 menit. Kemudian angkat wajan dari api, dan aduk cranberry.","Naikkan suhu oven hingga 400℉/204℃. Kemudian, isi jamur dengan banyak, taburi dengan keju Parmesan vegan, dan panggang selama 15 menit."],
["Berhati-hatilah saat melepaskan batang jamur. Jangan terburu-buru, terutama jika ini pertama kalinya Anda membuat jamur isi.","Jika ini pertama kalinya Anda membuat jamur isi, beli beberapa tambahan, untuk berjaga-jaga jika ada yang pecah. Kemudian, jika Anda akhirnya mendapatkan beberapa yang pecah, cincang halus dan tambahkan ke isian Anda. Tidak ada yang terbuang.","Keringkan kelebihan cairan setelah putaran pertama pemanggangan jamur Anda. Jangan lewati langkah ini.","JANGAN menambahkan semua kaldu sekaligus ke wajan berisi beras arborio Anda. Saat membuat risotto Italia, cara yang lambat adalah yang terbaik untuk tekstur yang sempurna creamy (tanpa menambahkan krim, mentega vegan, atau cream cheese vegan).","Sisa makanan dapat disimpan di lemari es selama 2-3 hari dalam wadah tertutup."],[]))
R.append((9125031,"Meatloaf Buncis dengan Glasir Maple Asap",
"Meatloaf buncis ini \"berdaging\" (meskipun tanpa daging) dan kaya rasa, dengan glasir maple asap yang luar biasa yang akan membuat Anda ingin menambah lagi.",
"6 (Menghasilkan sekitar 12 iris)","2 Iris",
G("Untuk Meatloaf",["2 telur rami atau telur chia","2 wortel, dikupas & dicincang halus","1 bawang bombai besar, dicincang halus","3 cangkir buncis matang atau dua kaleng 15 ons, ditiriskan & dibilas","5 sendok makan tamari atau kecap asin jika tidak menghindari gluten","1 cangkir remah roti bebas gluten","2 sendok makan ragi nutrisi","2 sendok teh bubuk bawang putih","2 sendok teh bubuk bawang bombai","2 sendok teh paprika asap","garam + merica secukupnya"])+G("Untuk Glasir Maple Asap",["1 cangkir kaldu sayuran rendah natrium","3 sendok makan pasta tomat","2 sendok makan sirup maple","2 sendok teh paprika asap","¼ sendok teh cabai cayenne (opsional)"]),
["Siapkan telur rami atau chia Anda dengan mencampur 2 sendok makan biji dengan 6 sendok makan air dalam mangkuk kecil dan sisihkan hingga mengental. Kemudian alasi loyang roti dengan kertas roti dan panaskan oven Anda terlebih dahulu hingga 400 derajat F dengan mode panggang konveksi.","Masukkan wortel dan bawang bombai cincang ke dalam wajan dan tumis kering selama 5-7 menit, hingga lunak. Tambahkan satu atau dua sendok makan air jika perlu agar tidak lengket.","Sementara itu, masukkan buncis ke dalam mangkuk pencampur besar dan tumbuk dengan garpu, tanpa terlalu halus. Anda ingin sebagian besar buncis hancur, tetapi tidak perlu memastikan setiap butirnya tertumbuk.","Kemudian tambahkan sayuran tumis bersama tamari, telur chia, remah roti, dan semua bumbu (tetapi BUKAN bahan glasir maple asap Anda) ke mangkuk yang sama dan aduk rata. Pastikan mengaduk secara menyeluruh untuk mendistribusikan telur chia dan bumbu dengan sangat baik. Kemudian cicipi dan tambahkan garam dan merica, jika perlu.","Tuang campuran ke dalam loyang roti yang sudah disiapkan dan tekan dengan kuat menggunakan tangan atau spatula silikon lalu ratakan bagian atasnya. Panggang selama 30 menit dan keluarkan dari oven.","Saat roti dipanggang, campurkan semua bahan glasir dalam panci kecil dan didihkan dengan api sedang, masak selama 10 menit, sering dikocok. Ini akan mengentalkan saus Anda sedikit.","Oleskan sekitar sepertiga glasir pada meatloaf Anda dengan kuas silikon dan kembalikan ke oven selama 15 menit. Keluarkan dari oven dan biarkan dingin selama 10 menit sebelum dipindahkan ke talenan. Gunakan kertas roti untuk mengangkat dan memindahkan meatloaf. Biarkan dingin di talenan Anda setidaknya 10 menit lagi, lalu iris dan sajikan dengan sisa glasir."],
["Jika Anda menghindari gandum, Anda dapat mengganti remah roti dengan oat gulung bebas gluten, jika perlu. Remah roti menyatukan sedikit lebih padat, tetapi oat juga bekerja dengan baik. Tumbuk buncis dalam mangkuk pencampur dengan garpu besar, daripada memasukkannya ke food processor agar bahan tidak terlalu halus. Anda tidak menginginkan bahan yang terlalu diproses di sini, atau itu dapat menghasilkan meatloaf buncis yang bertekstur lembek. Jika Anda tidak punya oven panggang konveksi, naikkan suhu oven sebanyak 25 derajat dan masak dengan waktu yang sama. Awasi dengan cermat. Sediakan waktu ekstra agar meatloaf dingin dan mengeras setidaknya 20 menit secara total. Ini akan membuat meatloaf buncis Anda jauh lebih mudah diiris dan disajikan. Bereksperimenlah dengan bumbu! Tambahkan lebih banyak atau lebih sedikit rempah yang Anda sukai, sesuai selera Anda. Jika Anda ingin menyajikan ini untuk Thanksgiving, Anda dapat mempertimbangkan menambahkan sage, thyme, dan pala ke dalam campuran dan melewatkan paprika asap. Jika Anda tidak ingin pedas, lewati cayenne. Bersenang-senanglah dan buat sesuai selera Anda! Untuk glasir yang lebih cepat, atau jika Anda tidak punya pasta tomat, ganti kaldu dan pasta tomat dengan saus tomat (ketchup), dan campur dengan sirup maple, paprika asap, dan cayenne (jika digunakan). Kemudian glasir meatloaf buncis Anda sesuai petunjuk, tetapi tidak perlu mendidihkan saus terlebih dahulu."],[]))
R.append((9125690,"Tahu Mongolia",
"Hidangan tahu Mongolia yang manis, lengket, gurih, dan pedas yang akan membuat Anda terkesima. Tahu renyah dibalut saus Mongolia yang kental dan lezat yang pasti memuaskan!",
"4 porsi","1 porsi",
G("Untuk tahu",["12 ons (340 gram) tahu ekstra padat","2 sendok makan kecap asin rendah natrium atau Tamari untuk bebas gluten","2 sendok makan tepung tapioka atau pati tapioka"])+G("Untuk saus Mongolia",["½ cangkir kecap asin rendah natrium atau Tamari untuk bebas gluten","½ cangkir air","3 sendok makan sirup maple","3-4 siung bawang putih, dicincang halus","1 sendok teh jahe segar, dicincang halus","¼ sendok teh serpihan cabai merah","2 sendok makan tepung tapioka"])+G("Untuk penyajian (opsional)",["nasi merah","bawang daun, kucai, daun bawang, wijen"]),
G("Pres tahu",["Potong tahu Anda menjadi dadu setengah inci. Kemudian letakkan beberapa tisu dapur atau lap piring bersih di atas talenan dan letakkan potongan tahu dalam satu lapisan di atasnya. Sekarang tambahkan lebih banyak tisu dapur di atas potongan dan letakkan talenan lain, piring datar, atau loyang di atasnya. Terakhir, letakkan sesuatu yang sangat berat di atasnya seperti wajan besi cor atau buku tebal. Pres seperti ini selama 15 menit sambil Anda menyiapkan bahan yang tersisa."])+G("Untuk tahu Mongolia",["Panaskan oven terlebih dahulu hingga 425°F/218°C dengan mode panggang konveksi dan alasi loyang dengan kertas roti.","Letakkan dadu tahu yang sudah dipres dalam mangkuk pencampur besar dan tambahkan 2 sendok makan kecap asin, lalu aduk rata. Kemudian tambahkan 2 sendok makan tepung tapioka dan aduk lagi.","Susun tahu dalam satu lapisan dengan jarak di antara setiap potongan di atas loyang Anda. Panggang selama 15 menit, lalu balik potongan dan panggang 10 menit lagi atau hingga tingkat kerenyahan yang diinginkan tercapai.","Saat tahu dipanggang, siapkan saus Mongolia. Masukkan semua bahan saus ke dalam wajan besar atau wok dan kocok hingga tercampur. Didihkan perlahan dengan api sedang dan sering dikocok hingga mengental, sekitar 3 menit.","Ketika tahu sudah dipanggang, pindahkan potongan tahu ke wajan berisi saus dan aduk perlahan.","Sajikan segera dengan taburan wijen dan nasi merah atau lauk pendamping pilihan Anda."]),
["Jangan lupa mengepres tahu Anda untuk tekstur terbaik. Gunakan metode pres cepat saya atau Anda dapat menggunakan alat pres tahu jika punya.","Usahakan memotong dadu sama rata mungkin agar matang merata.","Susun potongan dadu dalam satu lapisan di atas loyang Anda dengan jarak di antara setiap potongan agar tidak saling menempel dan menjadi renyah dengan baik.","Sisa makanan dapat disimpan di lemari es dalam wadah tertutup selama 3-4 hari. Saus akan mengental saat dingin, jadi masukkan tahu Mongolia ke dalam wajan dengan beberapa percikan air untuk mengencerkannya saat dipanaskan kembali."],[]))
R.append((9126167,"Hot Dog Tahu Bebas Gluten",
"Hot dog tahu beraroma asap dan kaya rasa yang sempurna untuk musim BBQ.",
"4 hot dog jumbo","1 porsi",
["340 gram (12 ons) satu blok tahu ekstra padat (pilih tahu organik yang bebas GMO jika memungkinkan)","2 sendok makan Tamari atau kecap asin","1 sendok makan liquid smoke","2 sendok teh bubuk bawang putih","2 sendok teh bubuk bawang bombai","2 sendok teh paprika asap","2 sendok teh bumbu unggas (poultry seasoning)","4-6 sendok makan tepung beras merah sesuai kebutuhan"],
["Jika bekerja lebih awal, bekukan tahu Anda dan cairkan sebelum dipres. Jika tidak, cukup pres untuk mengeluarkan sebanyak mungkin kelebihan air demi tekstur terbaik.",("Pres tahu (metode pres cepat)","Potong tahu Anda menjadi dadu. Kemudian letakkan beberapa tisu dapur atau lap piring bersih di atas talenan dan letakkan potongan dadu dalam satu lapisan di atasnya. Tambahkan lap bersih lainnya di atasnya, diikuti talenan lain, piring datar atau loyang. Terakhir, letakkan sesuatu yang sangat berat di atasnya seperti wajan besi cor atau buku tebal. Pres seperti ini selama 15 menit sambil Anda menyiapkan bahan yang tersisa."),("Siapkan hot dog tahu","Panaskan oven terlebih dahulu hingga 350℉/176℃ dan siapkan loyang kecil. (Tidak perlu dialasi.)"),("Siapkan hot dog tahu","Masukkan tahu yang sudah dipres dan semua yang lain kecuali tepung ke dalam food processor Anda. Proses hingga tercampur. Kemudian tambahkan 4 sendok makan tepung dan pulsekan hingga tercampur. Periksa konsistensi campuran Anda, Anda menginginkannya sedikit lebih lembut daripada Play-Doh. Jika sangat lembek/basah, tambahkan sisa tepung dan pulsekan lagi."),("Siapkan hot dog tahu","Tentukan apakah Anda membuat 4 hot dog jumbo atau 8 sosis yang lebih kecil. (Yang difoto adalah hot dog jumbo.) Kemudian potong 4 atau 8 lembar persegi kertas roti dan aluminium foil, sesuai jumlahnya."),("Siapkan hot dog tahu","Bagi adonan Anda menjadi 4 atau 8 bagian dan letakkan masing-masing di atas selembar kertas roti persegi dengan aluminium foil di bawahnya. Jika Anda ingin hot dog tahu dengan porsi yang sempurna, gunakan timbangan dapur, jika tidak, perkirakan saja."),("Siapkan hot dog tahu","Gunakan tangan Anda untuk membentuk adonan menjadi bentuk hot dog/gulungan, lalu bungkus rapat dengan kertas roti dan foil, putar ujung-ujungnya seperti bungkus permen. Letakkan setiap hot dog yang dibungkus di atas loyang Anda dan panggang."),("Petunjuk Pemanggangan","Untuk 4 hot dog jumbo panggang selama 40 menit, lalu balik dan lanjutkan memanggang 30-40 menit lagi hingga terasa padat saat disentuh.Untuk 8 hot dog tahu yang lebih kecil panggang selama 30 menit, lalu balik dan lanjutkan memanggang 20-30 menit lagi hingga terasa padat saat disentuh.Keluarkan dari oven, buka bungkusnya dan diamkan selama 5 menit sebelum dipanggang di grill atau disajikan. (Jika bekerja lebih awal, Anda dapat membiarkannya terbungkus dan mendinginkannya di lemari es semalaman.)"),("Petunjuk Memanggang di Grill (opsional)","Panggang hot dog tahu Anda di grill selama 2-3 menit di setiap sisi untuk mendapatkan garis panggangan yang indah jika diinginkan. Atau Anda dapat menikmati hot dog langsung dari oven.")],
["Tidak ada garam tambahan karena saya menggunakan Tamari yang menurut saya sudah cukup asin. Namun, Anda boleh menambahkan garam sesuai selera jika perlu.","Anda menginginkan konsistensi yang sedikit lebih lembut daripada Play-Doh, jadi mulailah dengan lebih sedikit tepung dan tambahkan lagi hanya jika perlu. Tepung yang dibutuhkan akan bervariasi tergantung berapa lama Anda mengepres tahu, dan apakah Anda menggunakan tahu yang dicairkan dari beku.","Jika Anda tidak suka foil menyentuh makanan Anda (seperti saya), gunakan kertas roti di antara hot dog tahu dan lapisan aluminium foil."],[]))
R.append((9130591,"Brokoli Air Fryer dengan Opsi Tanpa Minyak",
"Brokoli air fryer yang beraroma bawang putih, renyah, dan sedikit pedas ini lezat dan membuat ketagihan. Cara yang menyenangkan untuk mengubah rutinitas brokoli Anda dan siap dalam waktu kurang dari 15 menit!",
"2 porsi","1 porsi",
["4 cangkir kuntum brokoli (sekitar 1 brokoli kecil)","1 sendok makan minyak alpukat, atau pilihan Anda (ganti dengan kaldu sayuran untuk tanpa minyak)","¼ sendok teh garam laut","¼ sendok teh bubuk bawang putih","¼ sendok teh serpihan cabai (opsional, tetapi disarankan)",("Untuk Penyajian","Keju Parmesan Vegan (opsional)"),("Untuk Penyajian","irisan lemon (opsional)")],
["Potong brokoli Anda menjadi kuntum kecil dan masukkan ke dalam mangkuk. Siram dengan minyak atau kaldu sayuran dan taburi dengan bumbu. Aduk rata agar brokoli terlapisi merata.","Tambahkan 2-3 sendok makan air ke dasar air fryer Anda, di bawah keranjang. Ini akan mencegah brokoli berasap dan menjadi terlalu pahit. Kemudian masukkan brokoli ke keranjang Anda dan air fry pada suhu 380 derajat F selama 7-9 menit, hingga tingkat kecokelatan yang diinginkan tercapai. Aduk brokoli Anda, atau goyangkan keranjang Anda di sekitar pertengahan waktu.","Sajikan brokoli Anda dengan irisan lemon atau ditaburi keju Parmesan vegan, jika diinginkan."],
["Potong kuntum menjadi potongan kecil berukuran sama untuk tekstur terbaik dan matang merata. Bawang putih bubuk lebih kecil kemungkinannya gosong dibandingkan yang segar, jadi sebaiknya jangan menggunakan bawang putih segar kali ini. Jangan memasak brokoli terlalu lama, karena rasanya paling enak saat sedikit renyah, tetapi juga kecokelatan. Jadi mulailah memeriksanya sekitar menit ke-6 hingga 7. Brokoli air fryer Anda paling enak saat baru dibuat. Namun, sisa makanan dapat disimpan di lemari es selama 3-4 hari. Anda dapat memanaskannya kembali di fryer, oven toaster, atau oven biasa hingga panas merata. **Harap periksa dengan produsen merek air fryer Anda sebelum menambahkan air di bawah keranjang. Beberapa model mengizinkannya, sementara yang lain tidak. Jika Anda ragu, hindari."],[]))
R.append((9131956,"Nugget Sayuran Lentil Panggang",
"Untuk balita (atau orang dewasa) pilih-pilih makanan di rumah Anda, nugget sayuran lentil ini pasti jadi favorit! Sangat lezat, namun dibuat dengan bahan-bahan yang menyehatkan.",
"6 porsi (menghasilkan 24 nugget)","4 Nugget",
["1 cangkir lentil merah belah yang direndam dalam air mendidih panas selama 30 menit","1 zucchini sedang, diparut","1 wortel besar, diparut","2 lembar roti gandum utuh yang tidak dipanggang, bebas gluten jika diperlukan","¼ cangkir kacang polong beku","¼ cangkir jagung beku","½ sendok teh garam laut","½ sendok teh bubuk bawang putih","½ sendok teh paprika","¼ sendok teh oregano kering"],
["Panaskan oven Anda terlebih dahulu hingga 425 derajat F dan alasi loyang besar dengan kertas roti.","Masukkan irisan roti Anda ke dalam food processor dan proses hingga konsistensi remah roti tercapai. Kemudian pindahkan remah roti Anda ke dalam mangkuk besar, masukkan jagung dan kacang polong beku ke mangkuk yang sama dan sisihkan.","Tiriskan lentil Anda dan masukkan ke food processor bersama wortel parut, zucchini, dan semua bumbu. Proses hingga hancur dan tercampur baik. Kemudian pindahkan ke mangkuk berisi remah roti, dan aduk hingga tercampur.","Bentuk bola berukuran 1-1.5\" dengan tangan Anda, dan letakkan di loyang Anda. Kemudian tekan setiap bola perlahan, tanpa memecahkannya, untuk membentuk nugget Anda.","Panggang selama 30 menit, balik dengan hati-hati pada menit ke-15. Biarkan nugget Anda dingin pada suhu ruang setidaknya 5 menit agar mengeras. Kemudian sajikan dengan saus tomat (ketchup), mayones buatan sendiri, atau tahini."],
["Jangan mengganti dengan lentil biasa. Anda harus menggunakan lentil merah belah untuk resep ini. Pastikan campuran Anda diproses sangat halus sebelum menambahkan kacang polong dan jagung. Lihat foto proses atau video sebagai perbandingan. Jika ada nugget yang pecah saat ditekan di loyang Anda, bentuk ulang sebelum dipanggang untuk memastikan nugget menyatu dengan baik. Sisa makanan dapat disimpan di lemari es hingga 3 hari, dan Anda dapat memanaskannya kembali di oven atau oven toaster."],[]))
R.append((9135569,"Salad Jagung",
"Tingkatkan hidangan Anda dengan salad jagung yang menyegarkan ini! Jagung manis, kacang-kacangan, sayuran segar, dan rempah berpadu dalam dressing asam yang ringan dan penuh cita rasa.",
"4 porsi","1 porsi",
["3 cangkir biji jagung (sekitar 3-4 tongkol jagung segar, dikupas)","1 kaleng 15 ons kacang hitam (ditiriskan + dibilas)","1 cangkir mentimun (dipotong dadu)","1 cangkir tomat ceri atau anggur (dibelah dua)","1/3 cangkir bawang merah (dipotong dadu)","2 sendok makan tahini","2 sendok makan air jeruk nipis (sekitar 1 jeruk nipis besar)","2 sendok makan cuka anggur putih","1 sendok makan sirup maple","3-4 sendok makan kemangi segar (dicincang halus)","garam + merica (secukupnya)"],
["Campurkan semua bahan dressing salad dalam mangkuk kecil dan sisihkan.","Kemudian masukkan semua bahan salad ke dalam mangkuk yang lebih besar, aduk dengan dressing, dan sajikan. Jika waktu memungkinkan, dinginkan di lemari es selama 1 jam sebelum disajikan."],[],[]))
build(R,'/mnt/c/WSL/davita/translations/tid0/part4.json')
