from mk import *
R=[]
R.append((9184828,"Roti Pisang Labu Vegan",
"Nikmati camilan musim gugur yang sempurna dengan roti labu pisang vegan ini! Lembap, kaya rasa, dan mudah dibuat!",
"12 potong","1 porsi",
G("Bahan Basah",["1 cangkir pisang lumat dari sekitar 3 pisang sedang","1.5 cangkir puree labu","¼ cangkir molase fancy","¼ cangkir susu kedelai atau susu nabati lain"])+G("Bahan Kering",["270 gram tepung serbaguna gandum utuh (sekitar 2 cangkir)","2 sendok teh baking powder","1 sendok teh kayu manis","½ sendok teh jahe bubuk","¼ sendok teh pala"])+G("Opsional",["⅓ cangkir keping cokelat semi-manis atau hitam ditambah lebih banyak untuk topping"]),
["Panaskan oven Anda terlebih dahulu hingga 350℉/176℃ dan alasi loyang roti dengan kertas roti.","Lumatkan pisang dan campurkan semua bahan basah dalam mangkuk besar. Kemudian tambahkan bahan kering dan aduk hingga tercampur tanpa mengaduk berlebihan. Lipat keping cokelat jika digunakan.","Tuang adonan ke dalam loyang roti beralas Anda, ratakan bagian atasnya dan tambahkan lebih banyak keping cokelat di atasnya jika diinginkan. Tekan perlahan.","Panggang roti labu pisang selama 45-55 menit atau hingga tusuk gigi yang ditusukkan ke tengah keluar bersih. Kemudian keluarkan dari oven dan diamkan selama 15-20 menit sebelum memindahkan roti ke rak pendingin atau talenan untuk melanjutkan pendinginan."],
["Timbang tepung menggunakan timbangan dapur untuk hasil yang paling akurat. Mengeruk tepung dari kantong sering kali menyebabkan terlalu banyak tepung yang digunakan dan dapat mengubah tekstur.","Gunakan pisang yang sangat matang. Semakin banyak bintik cokelat, semakin baik, karena akan semakin manis. Karena resep ini menggunakan sangat sedikit pemanis, Anda perlu memastikan pisang Anda memberikan kemanisan yang cukup.","Ukur pisang lumat Anda. Ukuran pisang bervariasi. Jadi pastikan menggunakan cukup banyak untuk kemanisan dan kelembapan. Ukur 1 cangkir penuh pisang lumat.","Gunakan baking powder yang segar + aktif! Baking powder yang sudah dibuka di lemari dapur selama 6+ bulan dapat mulai kehilangan keefektifannya.","Gunakan kertas roti untuk mengalasi loyang roti Anda. Meskipun loyang roti antilengket bisa digunakan, saya merasa lebih mudah mengeluarkan roti dari loyang saat menggunakan kertas roti. Anda dapat dengan mudah mengangkat roti dan meletakkannya di rak kawat tanpa memecahkannya.","Setiap oven berbeda. Jadi uji kematangan roti labu pisang Anda menggunakan tusuk gigi yang ditusukkan ke tengah. Ketika keluar dalam keadaan hampir kering dan bersih, roti sudah matang.","Biarkan dingin. Sediakan waktu ekstra agar roti dingin. Minimal 20-30 menit di rak pendingin disarankan agar benar-benar set dan lebih mudah diiris.","Sisa makanan dapat disimpan pada suhu ruang selama 2-3 hari, di lemari es hingga 5 hari, atau dibekukan hingga 3 bulan."],[]))
R.append((9188036,"Selai Apel Instant Pot [Tanpa Dikupas]",
"Selai apel Instant Pot yang kental, manis, dan lezat, tanpa perlu dikupas dan tanpa tambahan gula!",
"6 cangkir","2 Sendok makan",
["5 pon apel (saya suka Fuji, sekitar 10-12 apel besar)","⅓ cangkir cuka sari apel","1 sendok makan ekstrak vanila murni","1 sendok makan kayu manis","¼ sendok teh pala","⅛ sendok teh garam laut",("Opsional","2-4 sendok makan molase fancy"),("Opsional","2-4 sendok makan sirup maple")],
["Masukkan cuka sari apel, kayu manis, pala, vanila, dan garam ke dalam Instant Pot Anda lalu kocok hingga tercampur.","Lepaskan semua stiker dari apel Anda, cuci dengan baik dan potong menjadi empat bagian. Buang bagian inti. Tidak perlu mengupas apel. Letakkan di dalam Instant Pot Anda, tutup penutup dan setel katup pada posisi tertutup (sealing).","Setel panci ke tekanan tinggi selama 5 menit. (Dibutuhkan sekitar 10-15 menit untuk membangun tekanan.) Setelah timer selesai, biarkan panci melepaskan tekanan secara alami selama 20 menit lalu lepaskan sisa uap dengan cepat dan buka penutup setelah aman.","Gunakan blender tangan (atau pindahkan dengan hati-hati, dalam beberapa kali ke blender biasa) untuk menghaluskan apel Anda. Setelah benar-benar halus, cicipi kemanisannya dan tambahkan sedikit sirup maple dan/atau molase, jika perlu, sesuai selera Anda.",("Pilih SATU Metode: Slow Cook ATAU Tumis","SLOW COOK: Setel ke slow cook pada HIGH. Pilih slow cook, sesuaikan lalu HIGH. Letakkan penutup kaca dengan ventilasi (penutup IP, atau penutup lain yang cocok) dan masak selama 2-3 jam hingga kekentalan yang diinginkan tercapai, sesekali diaduk."),("Pilih SATU Metode: Slow Cook ATAU Tumis","TUMIS: Setel ke fungsi tumis pada LOW. Pilih tumis, sesuaikan, lalu LOW. Masak selang apel Anda selama 30 menit, menggunakan penutup anti-cipratan, dan sering dikocok. Berhati-hatilah SANGAT HATI-HATI karena akan menggelegak dan dapat menyebabkan luka bakar."),("Penyimpanan","Matikan panci dan biarkan agak dingin. Kemudian pindahkan ke toples yang bersih dan kering untuk dikalengkan, dibekukan, atau dibagikan. (Lihat di atas untuk petunjuk pengalengan.)")],
["Tingkat kemanisan akan bergantung pada apel yang Anda gunakan. Gunakan apel manis untuk selai apel yang manis alami, dan agar tidak perlu menambahkan gula. Saya menyukai apel Fuji untuk ini. Jika menggunakan apel asam, atau campuran beberapa varietas, Anda mungkin ingin menambahkan sedikit pemanis setelah matang. Cicipi dan sesuaikan dengan tingkat kemanisan yang Anda inginkan SETELAH memasak agar Anda tidak menambahkan lebih dari yang diperlukan. Jika Anda memiliki blender berkualitas baik, tidak perlu mengupas apel. Apel akan halus dengan baik dan menambah serat dan cita rasa. Lihat di atas untuk gambar dan cara mengetahui kapan selai apel Anda siap/cukup kental. Resep ini menghasilkan sekitar 6 cangkir selai apel dan ukuran porsi dalam informasi nilai gizi mewakili 2 sendok makan."],[]))
R.append((9193390,"Salad Bit dan Labu Panggang",
"Jangan lewatkan salad bit dan labu panggang yang cerah dan lezat ini.",
"6 porsi","1 porsi",
G("Untuk salad",["6 cangkir labu dipotong dadu dari sekitar 2 pon labu pai","3 cangkir bit dipotong dadu dari sekitar 1 pon bit","1 kaleng 15 ons buncis, ditiriskan + dibilas, sekitar 1.5 cangkir","⅓ cangkir almond serut","¼ cangkir cranberry kering tanpa pemanis"])+G("Untuk dressing",["¼ cangkir tahini","3 sendok makan cuka sari apel","3 sendok makan sirup maple","½ sendok teh bubuk bawang putih","½ sendok teh kayu manis","½ sendok teh jahe bubuk","garam + merica secukupnya"]),
["Panaskan oven terlebih dahulu hingga 425℉/218℃ dengan mode panggang konveksi. (Jika Anda tidak punya oven konveksi, sediakan waktu ekstra untuk memanggang sayuran.) Alasi loyang besar (atau dua yang lebih kecil) dengan kertas roti dan sisihkan.","Kupas dan potong dadu bit dan labu Anda menjadi potongan setengah inci agar cepat matang. Kemudian susun dalam satu lapisan di atas loyang Anda dan taburi dengan garam dan merica. Panggang selama 25 menit. Kemudian keluarkan loyang dari oven, tambahkan buncis dan lanjutkan memanggang 15-20 menit lagi hingga sayuran empuk ditusuk garpu dan buncis renyah.","Sementara itu, campurkan bahan dressing dalam mangkuk kecil dan aduk rata.","Masukkan sayuran panggang, buncis, almond, cranberry, dan dressing salad ke dalam mangkuk besar. Aduk hingga terlapisi rata, dan sajikan hangat atau dinginkan di lemari es selama 1 jam sebelum menyajikan salad."],
["Potong bit dan labu menjadi dadu kecil agar lebih cepat matang.","Untuk menghemat waktu, Anda dapat membeli potongan labu dadu dan bit dari toko.","Cicipi dan sesuaikan dressing salad, tambahkan garam laut dan merica hitam sesuai selera Anda sebelum mencampurnya dengan salad.","Sisa makanan dapat disimpan di lemari es selama 2-3 hari dalam wadah kedap udara."],[]))
R.append((9193815,"Kentang Tumbuk Garam dan Cuka",
"Saatnya mengubah kentang panggang Anda! Sebagai keluarga, kami tergila-gila dengan kentang bagaimanapun cara memasaknya, tetapi kentang panggang mungkin favorit saya. Yang kedua terbaik adalah kentang goreng dengan banyak garam dan cuka. Jadi, saya memutuskan untuk menggabungkan keduanya dan membuat saya, dan Anda, sangat bahagia. Setelah Anda menambahkan cuka dan garam laut serpihan, kentang yang panas, ditumbuk, dan renyah menjadi benar-benar membuat ketagihan. Bagian menumbuknya, selain memuaskan untuk dilakukan, membuatnya semakin enak. Sangat sulit untuk tidak memakan semuanya langsung dari loyang, tetapi jika ada yang lolos dari genggaman Anda, kentang ini menjadi hidangan pendamping, camilan, atau hidangan pembuka yang hebat dan sangat disukai di pesta.",
"4 porsi","1 porsi",
["1½ lb (680 g) kentang bayi dengan kulit","1¼ cangkir (300 ml) cuka putih, dibagi dua","2 sendok teh (10 g) garam","3 sendok makan (45 ml) minyak zaitun","Garam laut serpihan untuk ditaburkan"],
["Panaskan oven terlebih dahulu hingga 450°F (232°C).","Masukkan kentang ke dalam panci saus. Tuang 1 cangkir (240 ml) cuka di atasnya, dan tambahkan garam. Tambahkan air dingin secukupnya hingga hanya menutupi kentang. Didihkan dan masak selama sekitar 7 menit, atau hingga Anda baru bisa menusukkan garpu ke dalamnya tetapi belum matang sepenuhnya. Segera tiriskan dan biarkan di saringan selama beberapa menit agar uapnya mengering.","Kembalikan kentang ke dalam panci saus tempat Anda merebusnya dan aduk dengan minyak zaitun; kemudian sebarkan di atas loyang besar dalam satu lapisan dengan jarak di antara setiap kentang. Panggang selama 30 menit, lalu keluarkan dari oven. Tumbuk setiap kentang dengan penumbuk kentang atau dasar mug hingga pipih dan terbelah. Siram dengan sisa ¼ cangkir (60 ml) cuka, pastikan melakukannya semerata mungkin. Kemudian kembalikan loyang ke oven dan panggang lagi selama sekitar 30 menit lagi, atau hingga benar-benar keemasan dan renyah.","Taburi dengan garam laut serpihan secara melimpah dan sajikan segera"],[],[]))
R.append((9195537,"Salad Nasi Merah dan Quinoa",
"Salad nasi merah dan quinoa yang mengenyangkan, lezat, dengan sayuran segar dan dressing creamy kaya protein.",
"6 porsi","1 porsi",
["1 cangkir nasi merah matang (sekitar ½ cangkir kering)","1 cangkir quinoa matang (sekitar ⅓ cangkir kering)","1.5 cangkir buncis (sekitar 1 kaleng 15 ons)","1 cangkir tomat ceri, dibelah dua","1 cangkir mentimun, dipotong dadu","½ cangkir bawang merah, dicincang halus","½ cangkir kemangi segar, dicincang halus",("Untuk dressing","¼ cangkir tahini"),("Untuk dressing","3 sendok makan cuka sari apel"),("Untuk dressing","1 sendok makan cuka anggur merah"),("Untuk dressing","½ sendok teh bubuk bawang putih"),("Untuk dressing","1-2 sendok makan air saring"),("Untuk dressing","garam + merica secukupnya")],
["Mulailah dengan memasak nasi dan quinoa Anda sesuai petunjuk kemasan jika Anda belum punya yang sudah matang. Saya suka memasaknya dalam kaldu untuk menambah cita rasa atau Anda dapat menggunakan air dingin dengan garam. Untuk memasak biji-bijian, gunakan perbandingan 2 banding 1 antara biji-bijian kering dan cairan. Didihkan, lalu kecilkan api dan didihkan perlahan dengan penutup hingga matang dan air terserap.","Saat biji-bijian dimasak, siapkan dan cincang semua sayuran. Kemudian, campurkan semua bahan dressing salad dalam mangkuk kecil dan aduk rata.","Setelah biji-bijian matang, gemburkan dengan garpu dan sisihkan agar agak dingin sebelum mencampurnya dengan bahan salad lainnya. Kemudian aduk semuanya dengan dressing dan dinginkan salad di lemari es selama 1 jam sebelum disajikan."],[],[]))
R.append((9200252,"Baked Beans Slow Cooker Beraroma Asap (Anda tidak akan merindukan dagingnya!)",
"Baked beans buatan sendiri yang dimasak perlahan untuk menyerap semua saus gurih beraroma asap yang lezat. Penuh cita rasa sehingga Anda tidak akan pernah merindukan dagingnya!",
"6 porsi","1 porsi",
["450 gram kacang navy kering yang direndam semalaman atau 10-12 jam *lihat catatan untuk metode rendam cepat","1 bawang bombai kuning kecil, dicincang halus","3 siung bawang putih, dicincang halus","2.5 cangkir kaldu sayuran rendah natrium","2 sendok makan pasta tomat atau saus tomat (ketchup)","⅓ cangkir sirup maple","1 sendok makan mustard kuning","1 sendok teh bubuk bawang putih","1 sendok teh bubuk bawang bombai","2 sendok teh paprika asap","½ sendok teh jintan","1 sendok teh garam laut","½ sendok teh cabai cayenne untuk rasa, bukan kepedasan"],
["Tiriskan dan bilas kacang Anda. Kemudian masukkan, bersama semua bahan yang tersisa, ke dalam crock pot Anda. Aduk sangat rata hingga semuanya tercampur.","Masak dengan pengaturan rendah selama 8 jam, atau dengan pengaturan tinggi selama 4-5 jam. **lihat catatan"],
["Rendam kacang sebelum dimasak selama 10-12 jam hingga 24 jam. Air harus setidaknya 2 inci di atas permukaan kacang untuk memberi ruang pengembangan. Tambahkan ¼ sendok teh baking soda ke air rendaman Anda untuk membantu melunakkan kacang lebih jauh lagi. Selain itu, ini juga dikatakan dapat membantu menghilangkan efek kacang yang menyebabkan perut kembung. Cincang bawang bombai dan bawang putih Anda sangat halus. Semakin kecil potongannya, semakin banyak cita rasa yang akan menyebar ke setiap butir kacang. Jangan membuka penutup slow cooker Anda setidaknya selama 2 jam. Anda ingin menjaga panas di dalamnya. Jadi pastikan Anda mengaduk semuanya dengan sangat baik sebelum mulai memasak. Menjelang akhir memasak, aduk sangat rata dan cicipi lalu sesuaikan bumbu jika perlu. Sisa makanan dapat disimpan di lemari es hingga 5 hari dan dibekukan hingga 2 bulan. *Jika Anda lupa merendam kacang, masukkan ke dalam panci berisi air dan tutup dengan penutup. Didihkan lalu matikan api dan biarkan terendam selama 1 jam. **Slow cooker sangat bervariasi. Jika kacang Anda mulai mengering sebelum lunak, tambahkan lebih banyak kaldu atau air, aduk rata dan lanjutkan memasak. Jangan berlebihan. Cukup tambahkan ¼-1/2 cangkir setiap kali sesuai kebutuhan. Kacang sudah matang saat lunak dan creamy dan saus sangat kental."],[]))
R.append((9206024,"Pisang Air Fryer",
"Pisang air fryer adalah camilan cepat dan mudah yang bisa Anda buat dalam sekejap dengan beberapa bahan yang kemungkinan besar sudah ada di rumah Anda!",
"2 porsi","1 porsi",
["2 pisang hijau kecil (atau 1 besar), harus padat","1 sendok makan air lemon (sekitar setengah lemon kecil)","½ sendok teh garam laut","¼ sendok teh merica hitam"],
["Dalam mangkuk pencampur kecil, campurkan air lemon, garam, dan merica lalu sisihkan.","Kupas dan iris pisang Anda menjadi irisan setebal sekitar 1/8 inci. Sedikit lebih tebal tidak masalah, tetapi usahakan sebaik mungkin menjaga irisan tetap seragam agar matang merata. Kemudian letakkan dalam mangkuk berisi marinasi dan aduk perlahan agar irisan terlapisi rata.","Olesi keranjang air fryer Anda dengan sedikit minyak dan letakkan pisang yang sudah dilapisi dalam satu lapisan. Kemudian air fry pada suhu 350 derajat F selama 8-10 menit hingga keemasan dan berkaramel. Awasi dengan cermat menjelang akhir memasak agar tidak gosong."],
["Iris pisang Anda seseragam mungkin agar matang merata. Jika ada irisan yang terlalu tipis, irisan tersebut bisa gosong, jadi awasi dengan cermat menjelang akhir memasak. Untuk hidangan yang ekstra istimewa, sajikan dengan es krim!"],[]))
R.append((9211594,"Muffin Cranberry Vegan [Tanpa Minyak]",
"Muffin cranberry vegan ini dimaniskan ringan dan menggunakan cranberry segar dan lemon untuk memberikan ledakan rasa asam di setiap gigitan.",
"12 muffin","1 g",
G("Bahan Basah",["1 cangkir susu kedelai","⅓ cangkir saus apel tanpa pemanis","1 sendok makan parutan kulit lemon dari sekitar 1 lemon besar","⅓ cangkir air lemon dari sekitar 1 lemon besar","2 sendok teh ekstrak vanila murni","1.25 cangkir cranberry segar"])+G("Bahan Kering",["150 gram tepung oat (sekitar 1.5 cangkir)","1 cangkir oat gulung","¼ cangkir gula kelapa tanpa pemurnian atau gula merah","½ sendok teh baking soda","2 sendok teh baking powder","¼ sendok teh garam laut"]),
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi cetakan muffin dengan cup kertas roti.","Aduk semua bahan basah (kecuali cranberry) dalam mangkuk besar dan diamkan selama 5 menit hingga susu kedelai menggumpal. (Lihat foto proses di atas sebagai acuan.)","Setelah menggumpal, masukkan semua bahan kering dan aduk hingga tercampur tanpa mengaduk berlebihan. Kemudian lipat cranberry.","Bagi campuran ke dalam 12 cetakan muffin Anda dan panggang selama 24-25 menit, atau hingga tusuk gigi yang ditusukkan ke tengah muffin keluar kering. Keluarkan dari oven dan biarkan loyang muffin selama 10 menit sebelum memindahkannya ke rak kawat."],
["Gunakan baking powder yang aktif/segar. Baking powder yang sudah dibuka selama 6+ bulan dapat mulai kehilangan keefektifannya.","Jangan mengaduk adonan Anda berlebihan. Pada sebagian besar resep muffin, sebaiknya tidak mengaduk berlebihan untuk tekstur dan keempukan yang optimal. Saat mencampur bahan basah dan kering, aduk saja hingga tidak ada bagian tepung yang tersisa, tetapi jangan khawatir untuk menghaluskan setiap gumpalan.","Biarkan muffin Anda dingin. Muffin membutuhkan setidaknya 10 menit untuk beristirahat setelah dikeluarkan dari oven. Kemudian, pindahkan ke rak pendingin untuk melanjutkan pendinginan.","Simpan sisa makanan pada suhu ruang selama 3-4 hari dalam wadah tertutup atau ditutup dengan plastik pembungkus. Pastikan Anda menutup muffin setelah dingin atau akan menjadi kering. Simpan di lemari es hingga 6 hari atau bekukan dalam wadah kedap udara hingga 3 bulan."],[]))
R.append((9214034,"Pasta Paprika Merah Panggang Vegan",
"Nikmati kelezatan creamy dari pasta paprika merah panggang vegan ini!",
"4 porsi","1 porsi",
["1/2 pon pasta penne (atau pilihan Anda)","1 kaleng 15 ons buncis (ditiriskan + dibilas (dibagi dua))","1 toples 12 ons paprika merah panggang (sekitar 2 paprika besar)","1 cangkir kaldu sayuran","3-4 siung bawang putih (dikupas)","1/4 cangkir ragi nutrisi","1/2 sendok teh oregano kering","1/2 sendok teh serpihan cabai merah (opsional)","garam + merica (secukupnya)","peterseli atau kemangi segar","serpihan cabai merah atau minyak pedas","keju parmesan vegan"],
["Didihkan panci besar berisi air yang diberi cukup banyak garam. Masak pasta Anda sesuai petunjuk kemasan hingga 'al dente'. (Artinya memasak pasta sedikit kurang matang beberapa menit.) Tiriskan pasta tetapi SISIHKAN satu cangkir air rebusan.","Sementara itu, masukkan semua bahan saus ke dalam blender yang kuat dan proses hingga halus. Kemudian cicipi garam dan merica, tambahkan lagi jika perlu. Pindahkan saus ke wajan dalam dan panaskan di atas kompor.","Pindahkan pasta yang sudah matang dan buncis ke wajan berisi saus dan aduk rata. Tambahkan air pasta yang disisihkan ke dalam saus jika konsistensi yang lebih encer/lebih bersaus diinginkan.","Sajikan pasta paprika merah panggang Anda dengan hiasan rempah segar, serpihan cabai merah, atau keju parmesan vegan jika diinginkan."],[],[]))
R.append((9214087,"Salad Cobb Vegan dengan Dressing Kacang Putih \"Beraroma Keju\"",
"Salad cobb vegan ini menampilkan jamur beraroma \"bacon\" asap, jagung manis, alpukat yang kaya, tomat juicy, bawang yang segar, dan dressing creamy yang fantastis.",
"4 porsi","1 porsi",
G("Untuk Dressing",["1.5 cangkir kacang cannellini putih (sekitar 1 kaleng 15 ons)","¼ cangkir ragi nutrisi","¼ cangkir cuka sari apel","2 sendok makan tamari rendah natrium atau kecap asin jika tidak menghindari gluten","1 sendok teh bubuk bawang bombai","1 sendok teh bubuk bawang putih","1 sendok teh dill kering","¼ cangkir air"])+G("Untuk \"Bacon\" Jamur Asap",["1 pon jamur putih atau cremini, diiris, sekitar 4-5 cangkir irisan","3 sendok makan tamari rendah natrium atau kecap asin jika tidak menghindari gluten","1 sendok makan sirup maple","2 sendok teh paprika asap"])+G("Untuk Salad",["8 cangkir selada romaine atau iceberg, dicincang","1 alpukat, dipotong dadu","1 cangkir jagung, dicairkan jika menggunakan yang beku","275 gram tomat anggur atau ceri, dibelah dua, sekitar 1.5 cangkir","¼ cangkir bawang merah, dipotong dadu"]),
G("Untuk Dressing",["Masukkan semua bahan dressing ke dalam blender Anda dan proses hingga halus. Pindahkan ke mangkuk atau toples dan sisihkan."])+G("Untuk Jamur",["Dalam wajan besar, masukkan jamur iris, tamari, sirup maple, dan paprika asap. Tumis hingga menyusut dan cairan terserap, sekitar 6-8 menit. Sisihkan."])+G("Untuk Salad",["Masukkan selada ke dalam piring saji besar dan susun jamur dan topping yang tersisa dalam barisan, atau taburkan secara merata. Sajikan dengan dressing di atasnya atau di samping."]),
["Buat bebas kedelai dengan menggunakan coconut aminos untuk menggantikan tamari/kecap asin. Atau jika Anda tidak punya itu, gunakan sedikit air dan garam, atau kaldu asin dengan hasil yang serupa. Ganti atau lewati bahan apa pun yang tidak Anda sukai. Pilihan topping lainnya meliputi: Zaitun hitam atau hijau","Kucai atau daun bawang","Mentimun","Wortel atau kubis parut","Kacang merah kidney atau buncis renyah","Acar cincang","Simpan sisa salad dan dressing secara terpisah di lemari es selama 3-4 hari."],[]))
R.append((9216639,"Cheesecake Mini Vegan Tanpa Panggang",
"Dasar oat yang dimaniskan kurma dengan isian creamy yang manis dan topping raspberry segar membuat cheesecake mini vegan tanpa panggang ini tak terlupakan!",
"8 porsi","1 porsi",
G("Untuk dasar",["¾ cangkir kurma tanpa biji, dipadatkan","3 sendok makan air panas","1 sendok teh ekstrak vanila murni","¾ cangkir oat gulung, bebas gluten jika diinginkan"])+G("Untuk isian cheesecake",["14 ons (400 gram) tahu ekstra padat, gunakan yang bebas GMO jika memungkinkan","½ cangkir sirup maple","1 sendok makan air lemon","1 sendok teh ekstrak vanila murni"])+G("Untuk topping raspberry",["1 cangkir raspberry segar ditambah lebih banyak untuk hiasan (atau buah beri pilihan)","2 sendok makan sirup maple","1 sendok makan air lemon"]),
G("Untuk dasar cheesecake",["Masukkan kurma, air panas, dan vanila ke dalam mangkuk food processor Anda dan proses hingga sebagian besar halus, sambil mengerok sisi-sisinya, sesuai kebutuhan. Kemudian tambahkan oat dan pulsekan beberapa kali untuk menghancurkannya tetapi jangan dijadikan puree.","Bagi dasar ke dalam cangkir-cangkir individual Anda dan tekan menggunakan sendok atau gelas shot."])+G("Untuk isian cheesecake",["Masukkan semua bahan isian ke dalam food processor Anda dan blender hingga halus, sambil mengerok sisi-sisinya sesuai kebutuhan. Kemudian tuang dan bagi isian di atas dasar."])+G("Untuk topping",["Masukkan semua bahan ke dalam mangkuk sedang dan tumbuk perlahan dengan penumbuk kentang atau garpu besar, tetapi sisakan beberapa potongan untuk tekstur. Kemudian beri setiap cheesecake mini dengan satu sendok besar topping buah.","Opsional: Hias dengan raspberry segar dan daun mint.","Letakkan cheesecake berlapis di lemari es Anda setidaknya selama 1 jam sebelum disajikan, tetapi cheesecake ini paling enak jika didinginkan semalaman."]),
["Jangan memproses oat secara berlebihan saat membuat dasar. Anda menginginkan tekstur yang bagus, bukan puree.","Basahi sendok atau gelas shot Anda saat menekan dasar ke dalam cangkir individual agar tidak lengket.","Jika memungkinkan, buat cheesecake mini Anda satu hari sebelumnya karena paling enak jika didinginkan semalaman.","Anda dapat menggunakan stroberi, blueberry, atau campuran buah beri untuk topping. Atau, untuk menghemat waktu, Anda dapat menggunakan selai kemasan favorit Anda untuk topping buah.","Ukuran porsi yang difoto adalah gelas 6 ons. Ukuran porsi akan bervariasi sesuai ukuran gelas yang digunakan. Sisa makanan dapat disimpan di lemari es selama 3-4 hari."],[]))
R.append((9221793,"Cara Membuat Selai Kenari",
"Selai kenari buatan sendiri halus, creamy, encer, dan sangat kaya serta lezat!",
"16 porsi (menghasilkan sekitar 1 cangkir)","1 porsi",
["2 ¼ cangkir kenari mentah",("Tambahan Opsional","¼ sendok teh garam laut"),("Tambahan Opsional","1-2 sendok makan gula kelapa atau gula merah"),("Tambahan Opsional","½ sendok teh kayu manis")],
["Panaskan oven Anda terlebih dahulu hingga 325°F/163°C. Kemudian susun kenari di atas loyang dan panggang selama 6-8 menit. Anda hanya ingin memanaskannya hingga sedikit harum, jadi berhati-hatilah agar tidak gosong, atau selai kenari Anda akan pahit.","Keluarkan dari oven dan pindahkan kenari panggang ke mangkuk food processor Anda. Kenari akan melalui beberapa tahap, dari potongan remah, lalu tepung, kemudian akan mulai menggumpal, dan akhirnya, Anda akan mendapatkan selai kenari yang creamy dan halus. Pastikan berhenti dan mengerok sisi-sisinya, sesuai kebutuhan, dan beri alat Anda jeda singkat di antara pemrosesan agar tidak terlalu panas. Seluruh proses (dengan jeda) akan memakan waktu sekitar 3-5 menit, tergantung kekuatan processor Anda."],
["Beri mesin Anda jeda singkat di antara pemrosesan agar tidak terlalu panas. Matikan food processor Anda selama 30-40 detik setiap kali, sesuai kebutuhan, lalu lanjutkan. Gunakan jeda itu untuk mengerok sisi-sisinya. Selai kenari buatan sendiri Anda akan melalui banyak tahap, dan mungkin terasa seperti tidak akan pernah menjadi selai, tetapi pasti akan jadi. Berubah dari kenari utuh, menjadi potongan hancur, menjadi tepung, menjadi gumpalan kecil, lalu gumpalan yang lebih besar, dan akhirnya selai kacang yang creamy. (Lihat foto proses di atas sebagai gambaran.) Untuk bebas gula, lewati gula kelapa opsional, atau jika Anda suka manis, tingkatkan menjadi dua sendok makan. (Coba dulu dengan satu) Anda dapat menggunakan blender berkecepatan tinggi, seperti Vitamix untuk hasil yang lebih cepat, tetapi saya merasa lebih mudah mengerok selai kacang dari mangkuk food processor."],[]))
R.append((9226480,"Dip Krim Asam dan Bawang Vegan",
"Dip bawang karamel yang creamy dalam versi VEGAN! Rasanya ENAK BANGET!",
"6 porsi","1 porsi",
["1 cangkir kaldu sayuran rendah natrium (dibagi dua)","2 bawang bombai kuning sedang (dipotong dadu)","1.5 cangkir kacang cannellini putih (matang atau kalengan (sekitar 1 kaleng 15 ons))","3 sendok makan air lemon (atau cuka sari apel)","1 sendok makan tamari (atau kecap asin jika tidak menghindari gluten)","3/4 sendok teh bubuk bawang putih","3/4 sendok teh bubuk bawang bombai","2-4 sendok makan air (sesuai kebutuhan untuk mencapai konsistensi yang diinginkan)","kucai cincang","everything bagel seasoning","keripik pita","keripik tortilla","biskuit kering (cracker)"],
["Masukkan bawang bombai yang dipotong dadu dengan 1/4 cangkir kaldu ke dalam wajan besi cor atau wajan antilengket dan tumis dengan api sedang/besar. Aduk sesekali dan lanjutkan menambahkan kaldu sekitar 1/4 cangkir setiap kali, setelah kaldu sebelumnya benar-benar menguap, agar tidak lengket. Lanjutkan hingga bawang cokelat dan berkaramel dan kaldu habis. Ini akan memakan waktu sekitar 15-20 menit. Sisihkan setelah selesai.","Sementara itu, masukkan semua bahan krim asam, mulai dengan 2 sendok makan air, ke dalam blender berkecepatan tinggi. Proses hingga benar-benar halus dan tambahkan lebih banyak air jika konsistensi yang lebih encer diinginkan. Cicipi garamnya dan tambahkan sedikit jika perlu. (Kecap asin akan menambah rasa asin, jadi cicipi sebelum menambahkan garam.)","Pindahkan krim asam vegan ke dalam mangkuk lalu aduk bawang karamel. Dinginkan di lemari es setidaknya 1 jam, tetapi sedikit lebih lama bahkan lebih baik. Dip ini paling enak saat dingin dan cita rasa sudah sempat menyatu."],[],[]))
build(R,'/mnt/c/WSL/davita/translations/tid0/part6.json')
