from mk import *
R=[]
R.append((9250282,"Mayo Vegan Tanpa Minyak",
"Mayo vegan buatan sendiri mudah dibuat, hanya butuh 5 menit atau kurang dan sama lezatnya dengan yang dibeli di toko. Tanpa telur, tanpa minyak, tanpa susu, tanpa kedelai, dan tanpa kacang!",
"16 porsi masing-masing 1 sdm (menghasilkan sekitar 1 cangkir)","1 porsi",
["1 cangkir biji labu mentah tanpa kulit atau pepitas","⅓ cangkir air segar atau sedikit lebih banyak jika Anda menginginkan mayo yang lebih encer","1 sendok makan cuka sari apel","1 sendok makan air lemon","1 sendok teh mustard kuning","½ sendok teh bubuk bawang bombai","½ sendok teh garam laut atau secukupnya","⅛ sendok teh garam hitam (opsional tetapi disarankan)"],
["Masukkan biji labu ke dalam blender Anda dan proses hingga hancur dan berkonsistensi seperti tepung.","Sekarang masukkan semua bahan yang tersisa dan proses hingga halus dan creamy.","Dinginkan di lemari es hingga siap digunakan, karena paling enak saat dingin."],
["Memproses biji terlebih dahulu secara terpisah akan membantu memastikan tidak ada potongan biji yang tersisa di mayo Anda, sehingga menghasilkan mayo yang lebih halus. Simpan dalam wadah kedap udara di lemari es hingga 1 minggu. Jika Anda tidak menghindari kacang-kacangan, dan menginginkan mayo yang berwarna putih, Anda dapat mengganti biji labu dengan mete. Jika Anda tidak punya blender berkecepatan tinggi, Anda perlu merendam mete terlebih dahulu dalam air mendidih panas setidaknya selama 15 menit. Untuk mayo pedas tambahkan sedikit saus pedas atau cayenne, atau lihat Mayo Sriracha saya"],[]))
R.append((9251879,"Sup Brokoli Almond",
"Sup brokoli almond yang creamy dalam satu panci atau wajan, lembut seperti beludru, kaya protein, dan lezat.",
"6 porsi","1 porsi",
["1 cangkir almond blanched *jika Anda tidak punya almond blanched, lihat catatan atau di atas untuk petunjuk cara membuatnya","1 bawang bombai kuning, dicincang kasar","3 siung bawang putih, dikupas & dicincang","2 batang seledri, dicincang kasar","¾ sendok teh thyme kering","1.5 pon kentang yukon gold atau kentang putih (sekitar 3.5 cangkir dipotong dadu)","7 cangkir kuntum brokoli (sekitar 1 brokoli besar)","5 cangkir kaldu sayuran rendah natrium","½ sendok teh garam laut atau secukupnya","½ sendok teh merica hitam atau secukupnya"],
["Jika Anda tidak punya almond blanched, mulailah dengan melakukan blanching pada almond mentah utuh sesuai petunjuk di dalam postingan, atau lihat ringkasannya di catatan di bawah.","Cincang kasar bawang bombai, bawang putih, dan seledri Anda dan masukkan ke dalam panci dengan 2-3 sendok makan air. Tumis selama 3-4 menit, hingga lunak, tambahkan air lagi agar tidak lengket, jika perlu. Kemudian masukkan thyme dan tumis selama 30 detik, hingga harum.","Tuang kaldu, almond, kentang cincang, kuntum brokoli, serta garam dan merica. Didihkan dengan api besar lalu kecilkan api ke sedang dan masak selama sekitar 6-8 menit, hingga kentang empuk ditusuk garpu.","Gunakan blender tangan untuk menghaluskan sup Anda, atau pindahkan dengan hati-hati ke blender biasa, kerjakan dalam beberapa kali. Berhati-hatilah saat menangani cairan panas dan jangan mengisi blender terlalu penuh. Sajikan dengan roti renyah, crouton dan/atau peterseli segar."],
["Gunakan kaldu sayuran rendah natrium ATAU lewati garam jika Anda hanya punya kaldu biasa.","Untuk menghaluskan sup Anda, gunakan blender tangan agar tidak berantakan, dan mudah memblender dalam satu langkah.","Jika Anda tidak punya blender tangan, pindahkan dengan sangat hati-hati ke blender biasa. Kerjakan dalam beberapa kali, sesuai kebutuhan, dan jangan pernah mengisi blender terlalu penuh dengan cairan panas.","Setelah dihaluskan, cicipi sup dan sesuaikan garam dan merica sesuai selera Anda. Ingat, Anda selalu bisa menambah, tetapi tidak bisa mengurangi.","Sup ini sangat enak sebagai sisa makanan dan semakin mengental saat didiamkan, jadi sangat cocok dibuat lebih awal dan dipanaskan kembali.","Sisa makanan dapat disimpan di lemari es hingga 4 hari atau Anda dapat membekukannya hingga 3 bulan.","Cara Blanching Almond Jika Anda tidak punya almond blanched, Anda hanya membutuhkan 5 menit untuk membuatnya dari almond mentah utuh. Didihkan panci kecil berisi air (cukup untuk merendam almond). Setelah mendidih, masukkan almond dan rebus selama 1 menit. Kemudian tiriskan dan bilas dengan air dingin untuk mendinginkannya, cukup agar bisa dipegang. Kemudian pencet almond dan kulitnya akan terlepas dengan mudah."],[]))
R.append((9252979,"Muffin Pisang Lentil",
"Muffin pisang lentil yang lezat dan menyehatkan yang akan disukai orang dewasa maupun anak-anak.",
"12 muffin","1 porsi",
["1 cangkir lentil hijau matang atau kalengan (sekitar ⅓ cangkir kering)","1 cangkir pisang lumat dari sekitar 3 pisang sedang","½ cangkir saus apel tanpa pemanis","2 sendok teh ekstrak vanila murni","150 gram tepung pastry gandum utuh (sekitar 1 + ⅓ cangkir)","2 sendok teh baking powder","½ sendok teh kayu manis","1 cangkir blueberry segar"],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi cetakan muffin dengan cup kertas roti.","Masukkan lentil matang, pisang lumat, saus apel, dan vanila ke dalam blender Anda dan proses hingga benar-benar halus. Kemudian tuang campuran ke dalam mangkuk pencampur sedang.","Ke dalam mangkuk yang sama, masukkan tepung, baking powder, dan kayu manis, lalu aduk hingga baru tercampur. Kemudian lipat blueberry.","Sendokkan campuran ke 12 cetakan muffin dan panggang selama 20-22 menit, atau hingga tusuk gigi yang ditusukkan ke tengah muffin keluar hampir bersih.","Keluarkan loyang dari oven dan biarkan muffin lentil Anda pada suhu ruang selama 10 menit sebelum dipindahkan ke rak kawat."],
["Gunakan pisang yang sangat matang dengan banyak bintik cokelat pada kulitnya untuk kemanisan ekstra. Anda juga dapat menggunakan pisang beku, biarkan saja mencapai suhu ruang sebelum dilumatkan.","Gunakan baking powder yang SEGAR + AKTIF. Baking powder yang sudah dibuka di lemari dapur selama 6+ bulan dapat mulai kehilangan keefektifannya.","Jangan mengaduk berlebihan. Tekstur muffin paling baik jika dilipat bersama hingga baru tercampur.","Ketukkan loyang muffin perlahan pada permukaan keras untuk menutup celah dalam adonan sebelum dipanggang.","Biarkan muffin Anda selama 10 menit setelah dipanggang. Waktu pendinginan singkat ini akan membuat muffin Anda mengeras sepenuhnya, dan mencegahnya patah saat dikeluarkan dari cetakan."],[]))
R.append((9254108,"Tahu Air Fryer",
"Tahu air fryer yang renyah, penuh cita rasa, rendah kalori dan lemak, tanpa minyak tetapi sangat lezat! Renyah di luar, lembut dan empuk di tengah.",
"4 porsi","1 porsi",
["350 gram (12 ons) satu blok tahu ekstra padat (sebaiknya bebas GMO)","2 sendok makan tamari atau kecap asin jika tidak menghindari gluten","1 sendok makan cuka beras","1 sendok makan tepung maizena","1 sendok teh bubuk bawang putih","1 sendok teh bubuk bawang bombai","1 sendok teh paprika asap atau manis","¼ sendok teh garam laut (opsional)"],
[("Pres Tahu","Potong tahu Anda menjadi dadu setengah inci. Kemudian letakkan beberapa tisu dapur atau lap piring bersih di atas talenan dan letakkan potongan tahu dalam satu lapisan di atasnya. Sekarang tambahkan lebih banyak tisu dapur di atas potongan dan letakkan talenan lain, piring datar atau loyang di atasnya. Terakhir letakkan sesuatu yang sangat berat di atasnya seperti wajan besi cor atau buku tebal. Pres seperti ini selama 15 menit sambil Anda menyiapkan bahan yang tersisa."),("Siapkan Tahu","Campurkan semua bumbu kering, termasuk tepung maizena dalam mangkuk kecil, dan sisihkan."),("Siapkan Tahu","Letakkan dadu tahu yang sudah dipres dalam piring dangkal atau wadah dan tuang tamari dan cuka beras di atasnya, aduk agar terlapisi rata. Kemudian taburkan semua bumbu di atasnya dan aduk rata. Jika Anda menggunakan wadah, Anda dapat menutupnya dan memutar wadah dengan lembut untuk menyebarkan bumbu secara merata."),("Siapkan Tahu","Susun dadu Anda di keranjang fryer dalam satu lapisan, dikerjakan dalam dua kali jika Anda punya fryer kecil. Jangan menumpuk tahu Anda terlalu penuh untuk memastikan kerenyahan maksimal. Air fry pada suhu 400 derajat F selama 10-15 menit, aduk atau goyangkan keranjang Anda di sekitar pertengahan waktu. Punya saya sempurna pada menit ke-13, tetapi mulailah memeriksa tahu sekitar menit ke-10."),("Siapkan Tahu","Sajikan dengan cocolan seperti mayo pedas atau krim mete. Atau gunakan sebagai topping nasi dan sayuran.")],
["Jangan menumpuk tahu terlalu penuh, atau tidak akan sekeras renyah itu. Jika Anda punya fryer yang lebih kecil, kerjakan dalam dua kali untuk tekstur dan hasil terbaik. Jika Anda bekerja dalam beberapa kali, ingat bahwa porsi kedua Anda akan matang lebih cepat karena fryer Anda sudah panas, jadi mulailah memeriksa tahu lebih awal. Usahakan sebaik mungkin memotong dadu Anda menjadi potongan berukuran serupa agar matang merata dan hasil terbaik. Rencanakan untuk menghabiskan tahu air fryer Anda pada hari yang sama saat dibuat karena akan mulai kehilangan kerenyahannya semakin lama didiamkan. Jika waktu memungkinkan, Anda dapat merendam tahu Anda dalam marinasi selama 30 menit, hingga 12 jam (di lemari es) sebelum di-air fry, untuk menyerap lebih banyak cita rasa."],[]))
R.append((9255743,"Sayap Buffalo Kembang Kol Vegan [Oven atau Air Fryer]",
"Sayap buffalo kembang kol ini pedas, lezat, dan kaya rasa. Renyah di luar, empuk di tengah untuk camilan hari pertandingan yang sempurna!",
"4 porsi","1 porsi",
["1 kembang kol kecil, dipotong menjadi kuntum kecil seukuran sekali gigit","½ cangkir tepung beras merah atau tepung pilihan jika tidak menghindari gluten","1 sendok teh bubuk bawang putih","1 sendok teh bubuk bawang bombai","1.5 sendok teh paprika","½ sendok teh jintan","½ sendok teh garam laut","¼ sendok teh merica hitam","¼ sendok teh cabai cayenne","¾ cangkir susu mete tanpa pemanis atau susu pilihan",("Bahan Saus Sayap Buffalo","½ cangkir air"),("Bahan Saus Sayap Buffalo","¼ cangkir cuka putih"),("Bahan Saus Sayap Buffalo","1 sendok teh paprika"),("Bahan Saus Sayap Buffalo","1 sendok teh bubuk bawang putih"),("Bahan Saus Sayap Buffalo","¼ sendok teh cabai cayenne"),("Bahan Saus Sayap Buffalo","½ sendok teh garam laut"),("Bahan Saus Sayap Buffalo","3 sendok makan pasta tomat"),("Saus Cocol Opsional (sangat disarankan)","1 resep dressing ranch bebas susu")],
["Jika membuat saus cocol ranch, mulailah dengan merendam mete Anda sebelum mulai menyiapkan kembang kol. Setelah direndam, siapkan ranch sesuai petunjuknya dan dinginkan di lemari es hingga dibutuhkan.","Alasi loyang dengan kertas roti dan panaskan oven Anda terlebih dahulu hingga 450 derajat F.","Letakkan kembang kol yang sudah dipotong dalam mangkuk besar. Kemudian dalam mangkuk terpisah, campurkan tepung dan semua bumbu lalu aduk hingga tercampur. Kemudian tambahkan susu dan aduk rata untuk membuat adonan basah Anda. Sekarang tuang adonan ke mangkuk berisi kembang kol dan aduk rata agar setiap potongan terlapisi merata.","Letakkan kembang kol yang sudah dilapisi di atas loyang yang sudah disiapkan, satu per satu, dalam satu lapisan dan panggang selama 20 menit. Balik sekali di pertengahan waktu.","Sementara itu, siapkan saus sayap buffalo Anda dengan memasukkan semua bahannya ke dalam panci saus kecil. Kocok hingga tercampur dan didihkan perlahan dengan api sedang 3-5 menit, agar cita rasa menyatu.","Keluarkan kembang kol dari oven, dan lapisi potongan dengan saus buffalo Anda. Saya menggunakan kuas silikon untuk mengoleskan saus dalam jumlah banyak pada setiap potongan kembang kol. Kemudian kembalikan ke oven selama 10-15 menit, balik sekali di pertengahan waktu.","Sajikan dengan ranch dan celupkan sepuasnya.",("Petunjuk Air Fryer","Letakkan kembang kol yang sudah dipotong dalam mangkuk besar. Kemudian dalam mangkuk terpisah, campurkan tepung dan semua bumbu lalu aduk hingga tercampur. Kemudian tambahkan susu dan aduk rata untuk membuat adonan basah Anda. Sekarang tuang adonan ke mangkuk berisi kembang kol dan aduk rata agar setiap potongan terlapisi merata."),("Petunjuk Air Fryer","Letakkan kembang kol yang sudah dilapisi ke dalam keranjang crisp Anda, di dalam alat Ninja Foodi. Kemudian atur ke 390 derajat F dan air fry selama 20 menit, goyangkan keranjang Anda setiap 5 menit atau lebih."),("Petunjuk Air Fryer","Sementara itu, siapkan saus sayap buffalo Anda dengan memasukkan semua bahannya ke dalam panci saus kecil. Kocok hingga tercampur dan didihkan perlahan dengan api sedang 3-5 menit, agar cita rasa menyatu."),("Petunjuk Air Fryer","Kemudian gunakan kuas silikon untuk melapisi kuntum Anda secara merata dengan saus buffalo. Lanjutkan air fry selama 10-15 menit lagi, goyangkan atau balik kuntum Anda di pertengahan waktu. Waktu memasak akan bervariasi tergantung model air fryer yang Anda gunakan dan ukuran kuntum."),("Petunjuk Air Fryer","Sajikan dengan ranch dan celupkan sepuasnya.")],
["Jika menggunakan dressing ranch, siapkan terlebih dahulu dan dinginkan di lemari es hingga dibutuhkan. Untuk bebas kacang, gunakan susu kedelai atau oat sebagai pengganti mete. Sisa makanan dapat disimpan di lemari es selama 2-3 hari dan dipanaskan kembali di air fryer, oven, atau oven toaster. Tips Ahli untuk hasil TERBAIK, setiap saat! Setelah melapisi sayap kembang kol Buffalo Anda dengan adonan, jangan menuangkannya ke loyang Anda. Kelebihan adonan di dasar mangkuk akan menggenang di loyang Anda, menyebabkan potongan menempel satu sama lain, dan menempel pada kertas roti. Ini akan membuatnya kurang renyah.","Saya tahu ini merepotkan, tetapi untuk hasil terbaik, letakkan sayap buffalo vegan Anda di loyang, satu potong per satu.","Pastikan sayap buffalo vegan Anda berada dalam satu lapisan, dengan jarak di antara masing-masing. Ini akan membantu membuatnya lebih renyah.","Balik kembang kol Anda di pertengahan waktu putaran pertama DAN kedua (setelah dilapisi saus Buffalo) pemanggangan. Ini membantu mendapatkan kerenyahan maksimal dari gigitan buffalo yang lezat ini."],[]))
R.append((9261320,"Pai Lemon Vegan Lebih Sehat [Tanpa Minyak]",
"Pai lemon vegan ini asam yang pas dengan sedikit manis. Creamy dan kaya, mudah disiapkan, dan sempurna untuk dibuat lebih awal.",
"8 potong","1 porsi",
["1 kulit pai gandum utuh vegan atau kulit pai pilihan","2.5 cangkir santan tanpa pemanis Thai Kitchen (kocok dengan baik sebelum dibuka atau tuang isinya ke dalam mangkuk dan kocok hingga tercampur)","⅓ cangkir gula pasir putih (Anda dapat menggunakan gula kelapa atau gula kurma jika lebih suka opsi tanpa pemurnian, tetapi perhatikan warna isian Anda akan lebih gelap.)","⅓-1/2 cangkir air lemon segar (sekitar 2-3 lemon, tergantung seberapa asam yang Anda suka (kami suka setengah cangkir))","¼ cangkir tepung maizena","½ sendok teh kunyit (untuk warna kuning, Anda tidak akan merasakan rasanya)",("Hiasan Opsional","irisan lemon, blueberry, irisan stroberi atau buah pilihan"),("Hiasan Opsional","almond serut")],
["Siapkan kulit pai pilihan Anda dan panggang tanpa isian (blind bake) sesuai petunjuk untuk kulit pilihan tersebut. Jika Anda menggunakan kulit pai tanpa minyak saya, panggang selama 15-20 menit, hingga tepinya keemasan. Sisihkan agar dingin sebelum diisi.","Kocok santan kalengan Anda dengan sangat baik sebelum dibuka. Kemudian ukur jumlah yang dibutuhkan dan letakkan dalam panci sedang, bersama gula, air lemon, tepung maizena, dan kunyit. Kocok dengan baik dan didihkan dengan api besar. Kemudian kecilkan api dan didihkan perlahan 2-3 menit hingga mengental, sering dikocok.","Tuang campuran secara merata ke atas kulit pai Anda yang sudah dingin dan dinginkan di lemari es semalaman, atau 6 jam atau lebih hingga set.","Setelah set, hias dengan irisan lemon, buah beri, dan almond serut, jika diinginkan."],
["Pastikan mengocok kaleng santan Anda dengan sangat baik sebelum dibuka. Karena Anda tidak menggunakan seluruh kaleng, Anda perlu memastikan isinya tercampur dengan baik sebelum mengukur jumlah yang akan Anda butuhkan. Pastikan merencanakan sebelumnya, karena hidangan penutup ini paling enak jika didinginkan semalaman. Jangan memotong pai Anda sampai dingin. Isian membutuhkan waktu untuk dingin dan set sebelum diiris. Informasi nilai gizi adalah untuk satu potong (atau ⅛) pai lemon, termasuk kulit pai tanpa minyak saya. Jika Anda menggunakan kulit pai lain, informasi nilai gizi akan bervariasi."],[]))
R.append((9263742,"Apel Panggang Air Fryer",
"Apel panggang air fryer yang manis, lembut, dan berkaramel! Rasanya seperti pai apel, tetapi dalam waktu yang jauh lebih singkat.",
"4 porsi","1 porsi",
["4 apel besar (saya suka campuran Granny Smith dan Honeycrisp)","3 sendok makan sirup maple","1 sendok makan mentega vegan atau margarin yang dilelehkan (opsional)","1 sendok teh kayu manis","1 sendok makan pati tapioka atau tepung maizena"],
["Dalam mangkuk sedang, campurkan sirup, mentega leleh (jika digunakan), kayu manis dan pati tapioka. Aduk rata.","Cuci apel Anda, lepaskan stiker apa pun dan iris setiap apel menjadi 8 irisan/potongan, buang biji/intinya. Masukkan irisan apel ke dalam mangkuk dan aduk rata agar terlapisi merata.","Letakkan 1/4 cangkir air di dasar air fryer Anda, di bawah keranjang. Kemudian letakkan apel yang sudah dilapisi di dalam keranjang dalam satu lapisan merata. Air fry pada suhu 380 derajat F selama 12-15 menit, hingga apel empuk ditusuk garpu. Aduk setiap 5 menit atau lebih. Sajikan hangat."],
["Jika Anda punya anak yang pilih-pilih makanan, kupas kulit apel sebelum mengiris dan melapisinya dengan marinasi untuk tekstur yang lebih halus. Usahakan memotong irisan apel Anda dengan ukuran yang sama agar matang merata. Jika ada potongan yang lebih besar, tidak akan selembut yang lain. Gunakan varietas apel favorit Anda. Saya suka mencampur apel manis dan asam, tetapi gunakan semuanya manis, atau semuanya asam, jika diinginkan. Simpan sisa makanan dalam wadah kedap udara di lemari es selama 1-2 hari. **Harap periksa dengan produsen merek air fryer Anda sebelum menambahkan air di bawah keranjang. Beberapa model mengizinkannya, sementara yang lain tidak. Jika Anda ragu, hindari."],[]))
R.append((9264119,"Saus Buffalo Vegan [Tanpa mentega atau minyak]",
"Saus Buffalo vegan buatan sendiri yang asam, kaya rasa, dan benar-benar PEDAS!",
"16 porsi (menghasilkan sekitar 2 cangkir)","1 porsi",
["1 cangkir Frank's RedHot Original Hot Sauce atau saus pedas serupa berbahan dasar cayenne","½ cangkir kaldu sayuran rendah natrium","⅓ cangkir mete mentah","¼ cangkir cuka putih","½ sendok teh bubuk bawang putih","½ sendok teh bubuk bawang bombai"],
["Masukkan semuanya ke dalam blender berkecepatan tinggi dan proses hingga halus dan creamy.","Pindahkan saus ke toples kaca yang bersih atau wadah bertutup dan simpan di lemari es hingga 10 hari."],
["Jika Anda tidak punya blender berkecepatan tinggi, rendam mete Anda dalam air dingin semalaman, atau rendam dalam air mendidih panas selama 30 menit. Kemudian tiriskan mete dan gunakan sesuai petunjuk. Merendam mete akan melunakkannya, sehingga lebih mudah diblender.","Jika Anda masih kesulitan membuat saus Anda halus, Anda dapat menyaring potongan mete yang tersisa menggunakan saringan halus atau kantong susu kacang (nut milk bag).","Buat bebas kacang dan ganti mete dengan pepitas mentah tanpa kulit atau biji bunga matahari dengan hasil yang serupa. Pastikan tidak ada tambahan garam.","Untuk natrium lebih rendah, gunakan air sebagai pengganti kaldu sayuran.","Untuk kepedasan lebih ringan, ganti ¼ hingga ½ dari saus pedas yang diperlukan dengan kaldu atau air.","Untuk rasa asam lebih ringan, gunakan hanya 2 sendok makan cuka atau ganti dengan cuka sari apel.","Untuk saus yang lebih creamy/kental, gunakan hingga ⅔ cangkir mete atau biji.","Jadikan saus pedas beraroma asap dan tambahkan 1 sendok teh paprika asap.","Simpan dalam toples atau wadah kaca yang bersih di lemari es hingga 10 hari, atau bekukan hingga 6 bulan. Gunakan cetakan es batu untuk membekukannya dalam ukuran porsi individual."],[]))
R.append((9265013,"Saus Keju Vegan Bebas Kacang [Tanpa Minyak Juga!]",
"Saus keju vegan bebas kacang yang sederhana dan lezat, sangat halus, dan siap dalam 5 menit saja, tanpa bahan istimewa!",
"6 porsi","1 porsi",
["½ cangkir biji labu tanpa kulit atau biji bunga matahari mentah","½ cangkir air segar atau mulai dengan sedikit lebih sedikit untuk saus yang lebih kental","8 ons paprika merah panggang (sekitar 2 paprika besar)","2 sendok makan ragi nutrisi","2 sendok makan cuka beras atau cuka sari apel","1 sendok makan sriracha atau saus pedas pilihan","1 sendok teh paprika asap","1 sendok teh bubuk bawang putih","1 sendok teh garam laut atau secukupnya"],
["Masukkan semua bahan ke dalam blender Anda dan proses hingga halus.","Sajikan dengan keripik tortilla, di atas nachos, dengan brokoli atau kembang kol kukus atau panggang, atau di atas kentang wedges atau poutine."],
["Gunakan pepitas atau biji bunga matahari mentah tanpa garam. Jika Anda tidak punya, atau tidak dapat menemukan yang tanpa garam, pastikan mengurangi atau melewatkan garam tambahan. Setelah diblender, cicipi dan tambahkan lebih banyak garam, hanya jika perlu. Untuk memastikan saus keju tidak mengandung minyak, gunakan paprika merah panggang yang dikemas dalam air, dan bukan yang direndam dalam minyak. (Atau panggang sendiri.) Sisa makanan dapat disimpan di lemari es dalam wadah tertutup hingga 5 hari. Atau bekukan dalam wadah kedap udara yang aman untuk freezer hingga 3 bulan."],[]))
R.append((9266414,"Burger Labu Kacang Hitam [Vegan + Bebas Gluten]",
"Burger kacang hitam labu ini sederhana dan lezat! Tanpa perlu dimasak atau dicincang sebelumnya. Cukup campurkan semua bahan, bentuk patty dan panggang!",
"5 burger","1 Patty",
["1 kaleng 15 ons kacang hitam, ditiriskan & dibilas, sekitar 1+⅓ cangkir","1 cangkir puree labu","1 sendok teh bubuk bawang putih","1 sendok teh paprika asap atau manis","½ sendok teh jintan","2 sendok makan tamari atau kecap asin jika tidak menghindari gluten","⅔ cangkir oat steel cut yang cepat matang atau oat gulung",("Topping Opsional","roti burger"),("Topping Opsional","selada"),("Topping Opsional","tomat"),("Topping Opsional","acar"),("Topping Opsional","guasacaca"),("Topping Opsional","mayo sriracha")],
["Panaskan oven Anda terlebih dahulu hingga 375 derajat F dan alasi loyang dengan kertas roti.","Masukkan semua bahan ke dalam food processor dan pulsekan hingga tercampur, berhenti untuk mengerok sisi-sisinya jika perlu. Jangan memproses berlebihan, beberapa potongan yang lebih kasar adalah yang ideal.","Bagi campuran Anda menjadi 5 patty dan panggang selama 20-25 menit. Jangan memasak terlalu lama atau akan menjadi kering. Burger sudah matang ketika mulai tampak retak di sekitar tepi seperti yang ditunjukkan pada foto 4 di atas.","Keluarkan dari oven dan biarkan dingin selama 5 menit sebelum disajikan."],
["JANGAN memproses berlebihan. Patty ini benar-benar paling enak saat bahan-bahannya masih cukup kasar. Gunakan tombol pulse pada food processor Anda untuk mencampur bahan, tanpa memblendernya.","JANGAN memasak terlalu lama. Jangan memasak burger ini terlalu lama, atau akan menjadi kering dan hancur. Waktu yang pas adalah 20-25 menit. Meski begitu, jangan juga memasak kurang matang, atau akan terlalu lembek. Untuk tekstur terbaik, masak hingga tepi tampak retak dan terasa padat saat disentuh, seperti yang ditunjukkan pada foto 4 di atas, tetapi bagian tengahnya akan lebih lembut.","Biarkan beristirahat. Ketika Anda mengeluarkan burger labu dari oven, pastikan membiarkannya selama 5 menit sebelum disajikan. Beberapa menit tambahan ini akan membantu burger menyelesaikan proses set dan mengeras.","Sesuaikan bumbunya. Silakan sesuaikan burger labu ini dengan selera Anda. Ingat, ini bukan burger pumpkin spice; labu memberikan kelembapan dan nutrisi. Jika Anda menginginkan cita rasa pumpkin spice pada burger Anda, tambahkan sedikit kayu manis, pala, jahe, dan/atau cengkih jika diinginkan. Jangan berlebihan. Atau, jika Anda lebih suka rasa pedas daripada rasa asap, ganti setengah atau seluruh paprika asap"],[]))
R.append((9271997,"Kulit Pizza Buckwheat",
"Kulit pizza buckwheat ini mudah dibuat hanya dengan 3 bahan (termasuk air) dan matang bahkan lebih cepat daripada kulit pizza gandum!",
"3 porsi","1 porsi",
["240 gram tepung buckwheat (sekitar 2 cangkir)","1 sendok teh garam laut","¾ cangkir air saring"],
["Panaskan oven Anda terlebih dahulu hingga 450 derajat F (232 derajat C) dan alasi loyang pizza bulat 9 inci dengan kertas roti. Sisihkan.","Masukkan tepung, garam, dan air ke dalam mangkuk besar dan aduk dengan tangan hingga tercampur. Kemudian tuang adonan ke permukaan bersih yang sudah ditaburi sedikit tepung.","Uleni adonan, menggunakan tangan Anda hingga menjadi bola yang agak halus. Pada tahap ini, sesuaikan air atau tepung jika perlu. Jika adonan terlalu lengket, taburkan sedikit tepung tambahan dan uleni. Jika adonan terlalu kering dan tidak menyatu, tambahkan satu sendok teh air setiap kali hingga Anda mendapatkan konsistensi seperti play-dough.","Sekarang letakkan bola adonan di atas lembaran kertas roti yang Anda sisihkan sebelumnya pada permukaan datar, seperti meja dapur. Gunakan rolling pin yang ditaburi tepung untuk meratakan adonan hingga ke tepi kertas roti. Kemudian geser kertas roti kembali ke loyang pizza Anda.","Panggang kulit pizza buckwheat selama 5-6 menit dan keluarkan dari oven. Kemudian lepaskan kertas roti (untuk kulit yang lebih renyah), beri topping pizza Anda sesuai selera, dan panggang 2-4 menit lagi. Selamat menikmati!"],
["Timbang tepung Anda untuk hasil yang paling akurat. Mengeruk tepung dari kantong sering kali menyebabkan terlalu banyak tepung yang digunakan. Sesuaikan air dan/atau tepung, sesuai kebutuhan. Adonan tidak boleh terlalu lengket, maupun terlalu kering. Anda menginginkan konsistensi seperti play-dough yang hanya sedikit lengket. Giling adonan di atas kertas roti agar mudah dipindahkan ke loyang pizza Anda, tanpa merusak kulitnya. Lepaskan kertas roti setelah pemanggangan pertama untuk kulit yang lebih renyah."],[]))
R.append((9272338,"Sup Kembang Kol Instant Pot [Vegan]",
"Sup kembang kol vegan ini bergizi, lezat, dan sangat mudah dibuat hanya dengan 4 bahan.",
"4 porsi","1 porsi",
["1 bawang bombai kuning, dicincang kasar","1 kembang kol besar, dipecah menjadi kuntum besar","4 cangkir kaldu sayuran rendah natrium","1 sendok teh bubuk bawang putih","garam + merica secukupnya",("Topping Opsional","buncis renyah"),("Topping Opsional","keju parmesan vegan"),("Topping Opsional","serpihan cabai merah, saus pedas, atau merica hitam"),("Topping Opsional","rempah segar seperti kucai, peterseli, kemangi, atau ketumbar")],
G("Petunjuk Instant Pot",["Masukkan semuanya ke dalam Instant Pot Anda, tutup penutup, dan setel katup ke posisi tertutup (sealing). Masak bertekanan tinggi selama 4 menit (dibutuhkan sekitar 10 menit untuk mencapai tekanan) dan setelah timer selesai, lepaskan katup uap dengan cepat.","Buka penutup setelah aman, dan gunakan blender tangan untuk menghaluskannya. Sajikan sup kembang kol vegan Anda dengan topping pilihan Anda."])+G("Petunjuk di Kompor",["Masukkan semua bahan ke dalam panci besar dan didihkan dengan api besar. Kecilkan ke api kecil/sedang dan didihkan perlahan selama sekitar 8 menit, hingga kembang kol empuk ditusuk garpu.","Matikan api, dan gunakan blender tangan untuk menghaluskan sup Anda hingga halus. Sajikan sup kembang kol vegan Anda dengan topping pilihan Anda."]),
["Jika Anda tidak punya blender tangan, pindahkan dengan hati-hati ke blender dan haluskan dalam beberapa kali sesuai kebutuhan.","Tambahkan lebih banyak bumbu jika diinginkan. Sup ini dirancang agar sederhana, menggunakan bahan minimal, namun tetap memberikan cita rasa yang hebat. Jika diinginkan, tambahkan sedikit jintan, ketumbar, biji seledri, ragi nutrisi, dan/atau paprika asap untuk meningkatkan cita rasa.","Tambahkan protein dengan satu kaleng kacang putih atau satu blok tahu sutra atau lembut dan haluskan ke dalam sup.","Untuk sup yang lebih kental, tambahkan 2 kentang yang dicincang kasar ke dalam sup dan haluskan bersama kembang kol setelah matang. Atau, tambahkan ½ cangkir mete mentah sebelum diblender.","Jadikan sup sederhana ini lebih mengenyangkan dan cocok sebagai hidangan utama dengan menambahkan satu sendok nasi merah matang, pasta, barley, farro, atau quinoa ke setiap mangkuk sebelum disajikan.","Sisa makanan dapat disimpan di lemari es hingga 5 hari atau dibekukan hingga 3 bulan."],[]))
R.append((9273315,"Es Lolly Stroberi Pisang",
"Camilan fantastis tanpa rasa bersalah untuk mengalahkan panas musim panas. Resep es lolly bebas gula ini mudah dibuat dan sangat lezat.",
"6 es lolly","1 porsi",
["1 cangkir stroberi iris (sekitar 4-6 stroberi)","1 pisang kecil (sekitar ¾ cangkir irisan)","1 cangkir susu almond atau susu nabati pilihan","2 sendok makan sirup maple (opsional)"],
["Masukkan semua bahan ke dalam food processor atau blender dan proses hingga konsistensi yang Anda inginkan. Saya membuat yang ini halus, tetapi Anda dapat menyisakan beberapa potongan buah jika diinginkan.","Kemudian isi keenam cetakan es lolly Anda, tetapi sisakan sedikit ruang untuk pemuaian. Lalu ketukkan cetakan ke meja dapur untuk mengeluarkan gelembung udara. Pasang tutup cetakan di atasnya dan bekukan selama 4-6 jam, atau semalaman. Simpan dalam keadaan beku hingga disajikan.CATATAN: Jika menggunakan tongkat es lolly, bekukan cetakan selama 1-2 jam, cukup agar tongkat dapat berdiri tegak, lalu masukkan tongkat dan lanjutkan membekukan hingga padat.",("Untuk melepaskan dari cetakan","Isi mangkuk dengan air hangat, setinggi cetakan Anda dan letakkan cetakan di dalamnya, tanpa meluap ke bagian atas tempat tongkat berada. Tunggu 15-20 detik sebelum mengangkatnya, lalu gunakan gerakan menggoyang ke kiri dan kanan untuk melepaskan es lolly dari cetakan."),("Untuk melepaskan dari cetakan","Anda juga dapat mengalirkan air hangat dari keran bak cuci ke es lolly selama 15-20 detik, atau hingga mudah lepas."),("Untuk melepaskan dari cetakan","Jika es lolly masih lunak, letakkan di atas piring dan kembalikan ke freezer.")],
["Gunakan pisang yang sangat matang yang berbintik cokelat untuk kemanisan alami. Saat stroberi sedang musimnya dan sangat manis, Anda dapat melewatkan sirup maple opsional untuk hidangan penutup tanpa tambahan gula. Untuk potongan buah yang lebih kasar dalam es lolly stroberi pisang Anda, gunakan food processor dan jangan memproses berlebihan. Untuk es lolly merah muda yang halus merata, gunakan blender hingga menjadi puree. Jika menggunakan tongkat es lolly (sebagai pengganti tutup bawaan cetakan Anda), bekukan cetakan selama 1-2 jam, cukup agar tongkat dapat berdiri tegak, lalu masukkan tongkat dan lanjutkan membekukan hingga padat. Waktu pembekuan akan bervariasi sesuai ketebalan cetakan Anda. Sebagian besar es lolly akan beku dalam 4-6 jam."],[]))
R.append((9274349,"Pasta Panggang Vegan",
"Pasta panggang vegan ini adalah hidangan comfort food terbaik dengan lapisan penne empuk, keju ricotta mete, dan saus bolognese yang mengenyangkan.",
"8 porsi","1 porsi",
["1 pon pasta pennoni atau penne, bebas gluten jika diinginkan",("Untuk Ricotta Vegan","1.5 cangkir mete mentah"),("Untuk Ricotta Vegan","1 sendok makan cuka sari apel"),("Untuk Ricotta Vegan","¼ cangkir ragi nutrisi"),("Untuk Ricotta Vegan","¾ sendok teh garam laut"),("Untuk Ricotta Vegan","1 sendok teh bubuk bawang putih"),("Untuk Ricotta Vegan","1 sendok teh bubuk bawang bombai"),("Untuk Ricotta Vegan","½ cangkir air"),("Untuk Saus Bolognese","5 cangkir saus tomat, gunakan jenis favorit Anda"),("Untuk Saus Bolognese","1 cangkir kenari cincang, cukup kecil agar menyerupai daging cincang"),("Untuk Saus Bolognese","½ sendok teh garam laut"),("Untuk Saus Bolognese","½ sendok teh oregano kering"),("Untuk Saus Bolognese","½ sendok teh kemangi kering"),("Untuk Saus Bolognese","½ sendok teh peterseli kering"),("Opsional","⅓ cangkir keju parmesan vegan")],
["Panaskan oven Anda terlebih dahulu hingga 425℉/218℃ dan siapkan loyang casserole berukuran 9\"x 13\" atau serupa. Kemudian, isi panci besar dengan air yang diberi cukup banyak garam dan didihkan.","Sambil menunggu air mendidih, buat ricotta bebas susu Anda. Masukkan semua bahan ricotta ke dalam food processor Anda dan proses hingga halus. Berhenti untuk mengerok sisi-sisinya sesuai kebutuhan dan sisihkan.","Sekarang air Anda seharusnya sudah mendidih, jadi masukkan pasta Anda ke dalam panci dan masak KURANG MATANG 2-3 menit dari petunjuk kemasan. Kemudian segera tiriskan.","Saat pasta dimasak, siapkan saus Anda dengan mengaduk bahan Bolognese dalam mangkuk. Sisihkan.","Ketika pasta sudah matang, mulailah merakit hidangan pasta panggang vegan Anda.",("Perakitan","Masukkan selapis tipis saus ke dasar loyang Anda agar tidak lengket. Kemudian masukkan setengah pasta matang Anda di atasnya, selapis tipis saus lagi, dan setengah keju ricotta. Ratakan keju sebaik mungkin, tetapi tidak perlu sempurna."),("Perakitan","Sekarang masukkan setengah pasta yang tersisa, selapis saus lagi, dan sisa keju ricotta. Ratakan keju, tambahkan satu lapis saus lagi, lalu taburi dengan keju Parmesan vegan, jika digunakan."),("Perakitan","Panggang tanpa ditutup selama 20 menit, lalu keluarkan loyang dari oven. Hias dengan rempah segar, dan taburi dengan serpihan cabai merah, merica hitam, atau lebih banyak keju parmesan vegan.")],
["Jangan memasak pasta Anda terlalu matang. Ingat bahwa pasta akan terus matang di oven, jadi sebaiknya masak KURANG MATANG 2-3 menit.","Jika Anda tidak punya food processor atau blender yang kuat, rendam mete Anda dalam air panas sebelum diblender. Didihkan air dalam panci atau ketel dan rendam mete selama 15-20 menit. Ini akan melunakkannya, sehingga lebih mudah diproses. Tiriskan dan buat keju sesuai petunjuk.","Untuk bebas kacang: gunakan biji bunga matahari sebagai pengganti mete untuk ricotta dengan hasil yang serupa. Lewati kenari, atau gunakan pepitas dengan hasil yang serupa. Atau buat ricotta tahu saya sebagai gantinya.","Jangan merasa kewalahan dengan banyaknya bahan dan langkah. Sebagian besar adalah bahan dan rempah yang biasa ada di dapur dan banyak langkah dilakukan secara bersamaan, jadi tidak akan memakan waktu lama. Lihat foto proses di atas, di dalam postingan, jika perlu, untuk membantu merakit.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari atau Anda dapat membekukannya hingga 3 bulan. Tidak seperti kebanyakan resep di blog, resep ini melebihi 400 kalori per porsi, jadi pertimbangkan untuk hidangan sesekali pada hari bebas diet. 😉"],[]))
build(R,'/mnt/c/WSL/davita/translations/tid0/part8.json')
