from h import *
O=[]
O.append(R(6274363,
("Peras asadas con crumble de avena","Este reconfortante postre combina peras asadas con una cobertura de avena con especias. Naturalmente dulce y lleno de sabor, este manjar apto para personas con diabetes es perfecto para disfrutar en cualquier época del año.","4","1/2 pera",
["2 peras enteras (maduras pero firmes, partidas por la mitad y sin el corazón)","1 cucharada de jarabe sin azúcar con sabor a arce (cero calorías)","1/4 de cucharadita de canela molida","1/8 de cucharadita de nuez moscada molida","1/2 taza de avena tradicional en hojuelas","2 cucharadas de harina de almendras","1 cucharada de aceite vegetal","1 cucharada de nueces pecanas (picadas)"],
["Caliente el horno a 350 grados F. Forre una bandeja para hornear con papel pergamino.","En un tazón pequeño, mezcle el jarabe de arce, la canela molida y la nuez moscada molida.","En otro tazón pequeño, combine la avena, la harina de almendras, el aceite vegetal y las nueces pecanas picadas. Mezcle hasta que la cobertura desmenuzada quede bien integrada.","Coloque las mitades de pera en la bandeja para hornear, con el lado cortado hacia arriba. Unte los lados cortados de las peras con la mezcla de jarabe de arce.","Espolvoree la mezcla de crumble de avena de manera uniforme sobre cada mitad de pera.","Ase las peras hasta que estén tiernas y el crumble esté dorado, unos 30 minutos. Sirva caliente."],[],[]),
("كمثرى محمّصة مع فتات الشوفان","حلوى مريحة تجمع بين الكمثرى المحمّصة وطبقة الشوفان المتبّلة. هذه الحلوى المناسبة لمرضى السكري حلوة بطبيعتها ومليئة بالنكهة، وهي مثالية للاستمتاع بها في أي وقت من السنة.","4","½ حبة كمثرى",
["2 حبة كمثرى كاملة (ناضجة لكن متماسكة، مقطوعة إلى نصفين ومنزوعة اللب)","1 ملعقة كبيرة شراب خالٍ من السكر بنكهة القيقب (خالٍ من السعرات الحرارية)","¼ ملعقة صغيرة قرفة مطحونة","⅛ ملعقة صغيرة جوزة الطيب المطحونة","½ كوب شوفان مجروش تقليدي","2 ملعقة كبيرة دقيق اللوز","1 ملعقة كبيرة زيت نباتي","1 ملعقة كبيرة بيكان (مفروم)"],
["سخّن الفرن إلى 350 درجة فهرنهايت (175° مئوية). بطّن صينية الخبز بورق الزبدة.","في وعاء صغير، اخلط شراب القيقب والقرفة المطحونة وجوزة الطيب المطحونة.","في وعاء صغير آخر، اخلط الشوفان ودقيق اللوز والزيت النباتي والبيكان المفروم. اخلطها جيدًا حتى يتجانس خليط الفتات.","ضع أنصاف الكمثرى على صينية الخبز بحيث يكون الجانب المقطوع إلى الأعلى. ادهن الجوانب المقطوعة من الكمثرى بخليط شراب القيقب.","رشّ خليط فتات الشوفان بالتساوي فوق كل نصف كمثرى.","حمّص الكمثرى حتى تصبح طرية ويصبح الفتات ذهبي اللون، نحو 30 دقيقة. قدّمها دافئة."],[],[])))
O.append(R(6274572,
("Hummus natural","Información nutricional del hummus","1","2 cucharadas",["2 cucharadas de hummus"],[],[],[]),
("حمّص سادة","المعلومات الغذائية للحمّص","1","2 ملعقة كبيرة",["2 ملعقة كبيرة حمّص"],[],[],[])))
O.append(R(6275460,
("Pera fresca","Información nutricional de una pera pequeña","1","1 pera pequeña",["1 pera pequeña (fresca)"],[],[],[]),
("كمثرى طازجة","المعلومات الغذائية لحبة كمثرى صغيرة","1","1 حبة كمثرى صغيرة",["1 حبة كمثرى صغيرة (طازجة)"],[],[],[])))
O.append(R(6277295,None,
("ساندويتش لفة الديك الرومي والأفوكادو","هذه اللفة السريعة واللذيذة مثالية لوجبة غداء أثناء العمل من المنزل. عند تحضير اللفائف، جرّب إضافة العديد من القوامات المختلفة كما فعلنا هنا، للحصول على أقصى قدر من النكهة والإشباع.","4","1 لفة",
["½ حبة أفوكادو متوسطة (مهروسة)","2 ملعقة كبيرة زبادي يوناني سادة خالي الدسم","4 رغيف تورتيلا كبير منخفض الكربوهيدرات","12 شريحة صدر ديك رومي بأسلوب المحال الجاهزة بدون ملح مضاف","4 ملعقة صغيرة بذور عباد الشمس","1 حبة طماطم متوسطة (مقطعة شرائح)","1 كوب خس مقطع شرائح رفيعة"],
["في وعاء صغير، اخلط الأفوكادو والزبادي اليوناني.","ادهن خليط الأفوكادو بالتساوي على 4 أرغفة تورتيلا.","ضع على كل رغيف 3 أونصات من الديك الرومي و1 ملعقة صغيرة من بذور عباد الشمس و2 شريحة من الطماطم و¼ كوب من الخس."],[],[])))
O.append(R(6281267,
("Cazuela de huevo y salchicha de pavo","Esta cazuela de huevo es más ligera, ya que usa sustituto de huevo y queso reducido en grasa.","10","1 porción",
["1/2 taza de cebollín (cebolla de verdeo) (picado)","2 tazas de leche sin grasa","1 rociada, 0.25 gramos de aceite en aerosol antiadherente","1/2 cucharadita de mostaza en polvo","1/4 de cucharadita de sal (opcional)","1/4 de cucharadita de pimienta negra","16 onzas de sustituto de huevo","4 rebanadas de pan integral (cortadas en cubos de 1/2 pulgada)","3 hamburguesitas enteras de salchicha de pavo para el desayuno, precocidas (en cubos)","1/4 de taza de queso cheddar rallado reducido en grasa"],
["Precaliente el horno a 350°F. Rocíe un molde para hornear de 9x13 con aceite en aerosol.","En un tazón mediano, bata la leche sin grasa, el cebollín, la mostaza en polvo, la sal (opcional), la pimienta y el sustituto de huevo.","Coloque los cubos de pan y la salchicha en el fondo del molde para hornear y vierta la mezcla de huevo de manera uniforme sobre el pan y la salchicha. Cubra con el queso cheddar.","Cubra el molde con papel de aluminio y hornee durante 20 minutos. Retire el papel de aluminio y hornee otros 40 minutos.","Saque del horno y deje enfriar durante 20 minutos; luego corte en 10 porciones iguales."],[],[]),
("طاجن البيض بنقانق الديك الرومي","طاجن البيض هذا أخف من المعتاد، إذ يستخدم بديل البيض والجبن قليل الدسم.","10","1 شريحة",
["½ كوب بصل أخضر (مفروم)","2 كوب حليب خالي الدسم","1 بخّة، 0.25 غرام بخاخ طهي غير لاصق","½ ملعقة صغيرة مسحوق الخردل","¼ ملعقة صغيرة ملح (اختياري)","¼ ملعقة صغيرة فلفل أسود","16 أونصة بديل البيض","4 شريحة خبز قمح كامل (مقطعة مكعبات بحجم ½ بوصة)","3 أقراص نقانق ديك رومي للفطور مطبوخة مسبقًا (مقطعة مكعبات)","¼ كوب جبن شيدر مبشور قليل الدسم"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). ارشش طبق خبز مقاس 9×13 ببخاخ الطهي.","في وعاء متوسط، اخفق الحليب الخالي الدسم والبصل الأخضر ومسحوق الخردل والملح (اختياري) والفلفل وبديل البيض.","ضع مكعبات الخبز والنقانق في قاع طبق الخبز، ثم اسكب خليط البيض بالتساوي فوق الخبز والنقانق. غطِّها بجبن الشيدر.","غطِّ الطبق بورق الألمنيوم واخبزه لمدة 20 دقيقة. أزل ورق الألمنيوم واخبزه 40 دقيقة إضافية.","أخرجه من الفرن واتركه يبرد لمدة 20 دقيقة، ثم قطّعه إلى 10 شرائح متساوية."],[],[])))
O.append(R(6281813,
("Vinagreta de frambuesa","Preparar su propio aderezo para ensaladas en casa es rápido y fácil, y le permite controlar la sal, el azúcar y otros ingredientes.","12","2 cucharadas",
["1 1/2 tazas de frambuesas frescas o congeladas (descongeladas si usa frambuesas congeladas)","1/2 taza de vinagre de vino de arroz","1/4 de taza de agua","1/4 de taza de aceite de oliva extra virgen","1 cucharada de eritritol u otro sustituto del azúcar","1/2 cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["En una licuadora o procesador de alimentos, haga un puré con todos los ingredientes hasta obtener una mezcla suave.","Vierta el aderezo a través de un colador de malla fina para eliminar las semillas.","Guarde en el refrigerador en un recipiente hermético hasta por 1 semana."],[],[]),
("صلصة الخل بالتوت الأحمر (الراسبيري)","تحضير صلصة السلطة في المنزل سريع وسهل، ويتيح لك التحكم في الملح والسكر وغيرهما من المكونات.","12","2 ملعقة كبيرة",
["1½ كوب توت أحمر (راسبيري) طازج أو مجمد (مذاب إذا كان مجمدًا)","½ كوب خل نبيذ الأرز","¼ كوب ماء","¼ كوب زيت زيتون بكر ممتاز","1 ملعقة كبيرة إريثريتول أو بديل سكر آخر","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["في الخلاط أو محضّر الطعام، اهرس جميع المكونات حتى تصبح ناعمة.","اسكب الصلصة من خلال مصفاة شبكية ناعمة لإزالة البذور.","احفظها في الثلاجة في وعاء محكم الإغلاق لمدة تصل إلى 1 أسبوع."],[],[])))
O.append(R(6282037,None,
("شوربة الطماطم السريعة بالأعشاب","تُعدّ هذه الشوربة طبقًا جانبيًا لذيذًا مع الساندويتش أو السلطة. ويمكنك أيضًا تقديمها كمقبّل. والأفضل من ذلك كله أنه يمكنك تحضيرها في أقل من 10 دقائق!","2","1 كوب",
["1 علبة (14.5 أونصة) طماطم مقطعة مكعبات (بدون ملح مضاف، غير مصفاة)","¼ كوب حمّص بالثوم (محمّص)","1 ملعقة صغيرة إكليل الجبل المجفف (مجروش)","½ ملعقة صغيرة خليط التوابل الإيطالية (مفتت)","½ ملعقة صغيرة فلفل أسود (يُفضّل مطحونًا خشنًا)","1 ملعقة كبيرة بقدونس (اختياري)"],
["في قدر صغير، قلّب جميع المكونات معًا ما عدا البقدونس. أحضرها إلى درجة الغليان الهادئ على نار متوسطة إلى منخفضة. خفّض النار واتركها على نار هادئة لمدة 5 دقائق. اسكبها بحذر في الخلاط واخلطها حتى تصبح ناعمة (أو ارفعها عن النار واستخدم خلاطًا يدويًا غاطسًا)."," أعدها إلى القدر. سخّنها على نار متوسطة إلى منخفضة لمدة 2 إلى 3 دقائق، أو حتى تبدأ بالغليان الهادئ فقط. اغرفها في أطباق. زيّنها بالبقدونس."],[],[])))
O.append(R(6282423,
("Bocaditos de huevo mediterráneos con espinacas y queso feta","Esponjosos bocaditos de huevo al horno hechos con huevos, espinacas, tomate y queso feta para un desayuno bajo en carbohidratos y rico en proteínas. Estos bocaditos salados ofrecen un sabor satisfactorio y, a la vez, son ligeros y fáciles de llevar, lo que los convierte en una opción inteligente para cualquier mañana.","6","12 bocaditos; 2 bocaditos por porción",
["1 cucharadita de aceite de oliva","1 bolsa (8 onzas) de espinacas (picadas)","7 huevos grandes","1/2 taza de leche descremada","1/8 de cucharadita de pimienta negra","1 tomate mediano (sin semillas y en cubos pequeños)","1/2 taza de queso feta desmenuzado","1/2 cucharadita de orégano seco"],
["Precaliente el horno a 350 grados F (175 grados C). Engrase ligeramente o forre un molde de silicona para 12 muffins.","Caliente el aceite de oliva en una sartén a fuego medio. Agregue las espinacas y cocínelas de 3 a 4 minutos, hasta que se marchiten y se haya evaporado la mayor parte del líquido. Debería obtener aproximadamente 1 taza (150 g) de espinacas cocidas. Deje enfriar un poco.","En un tazón grande, bata los huevos, la leche, la pimienta negra y el orégano (si lo usa) hasta obtener una mezcla suave.","Divida las espinacas de manera uniforme entre los moldes. Cubra cada uno con tomate en cubos y una pizca de queso feta. Vierta la mezcla de huevo sobre las espinacas y el tomate, llenando cada molde hasta aproximadamente ¾ de su capacidad.","Hornee de 22 a 25 minutos, o hasta que los huevos estén inflados y cuajados en el centro.","Déjelos reposar 5 minutos antes de sacarlos del molde. Sirva calientes o refrigere hasta por 4 días y recaliente con suavidad en el microondas."],[],[]),
("لقيمات البيض المتوسطية بالسبانخ والفيتا","لقيمات بيض هشّة مخبوزة تُحضَّر من البيض والسبانخ والطماطم وجبن الفيتا لتكون وجبة فطور غنية بالبروتين ومنخفضة الكربوهيدرات. تقدّم هذه اللقيمات المالحة نكهة مُرضية مع بقائها خفيفة وسهلة الحمل، مما يجعلها خيارًا ذكيًا لأي صباح.","6","12 لقيمة؛ لقيمتان لكل حصة",
["1 ملعقة صغيرة زيت زيتون","1 كيس (8 أونصات) سبانخ (مفرومة)","7 بيضات كبيرة","½ كوب حليب خالي الدسم","⅛ ملعقة صغيرة فلفل أسود","1 حبة طماطم متوسطة (منزوعة البذور ومقطعة مكعبات صغيرة)","½ كوب جبن فيتا مفتت","½ ملعقة صغيرة أوريغانو مجفف"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175 درجة مئوية). ادهن قالب مافن سيليكون من 12 تجويفًا بقليل من الزيت أو بطّنه بالورق.","سخّن زيت الزيتون في مقلاة على نار متوسطة. أضف السبانخ واطهها لمدة 3 إلى 4 دقائق حتى تذبل ويتبخر معظم السائل. يجب أن تحصل على نحو 1 كوب (150 غرامًا) من السبانخ المطبوخة. اتركها تبرد قليلًا.","في وعاء كبير، اخفق البيض والحليب والفلفل الأسود والأوريغانو (إن استخدمته) حتى يصبح الخليط ناعمًا.","وزّع السبانخ بالتساوي على تجاويف القالب. ضع فوق كل تجويف مكعبات الطماطم ورشّة من جبن الفيتا. اسكب خليط البيض فوق السبانخ والطماطم، واملأ كل تجويف حتى ¾ تقريبًا.","اخبزها لمدة 22 إلى 25 دقيقة، أو حتى ينتفخ البيض ويتماسك في الوسط.","اتركها ترتاح لمدة 5 دقائق قبل إخراجها من القالب. قدّمها دافئة أو احفظها في الثلاجة لمدة تصل إلى 4 أيام وأعد تسخينها برفق في الميكروويف."],[],[])))
O.append(R(6283047,
("Tortilla de maíz","Información nutricional de una tortilla de maíz.","0","1 tortilla",["1 tortilla de maíz (de 6 pulgadas)"],[],[],[]),
("خبز تورتيلا الذرة","المعلومات الغذائية لرغيف تورتيلا الذرة.","0","1 رغيف تورتيلا",["1 رغيف تورتيلا ذرة (6 بوصات)"],[],[],[])))
O.append(R(6283486,
("Almendras tostadas en seco","Información nutricional de las almendras tostadas en seco","1","1/4 de taza",["1/4 de taza de almendras tostadas en seco"],[],[],[]),
("لوز محمّص جاف","المعلومات الغذائية للوز المحمّص الجاف","1","¼ كوب",["¼ كوب لوز محمّص جاف"],[],[],[])))
O.append(R(6283603,None,
("لقيمات السلطعون المصغرة - وصفة سريعة","هذه الوصفة السريعة والصحية تصلح مقبّلًا رائعًا للحفلات. يمكنك استبدال التونة المعلبة بالسلطعون إن رغبت؛ فقط احذف الطرخون واستبدله بالثوم المعمّر (الشيف).","7","4 لقيمات سلطعون",
["2 علبة (6 أونصات) لحم سلطعون (مصفى (15% لحم أرجل))","⅓ كوب مايونيز خفيف","1 ملعقة صغيرة خردل ديجون","2 ساق بصل أخضر (مقطعة شرائح)","½ حبة فلفل رومي أحمر متوسطة (مقطعة مكعبات صغيرة جدًا)","1 ملعقة كبيرة عصير ليمون","¾ ملعقة صغيرة طرخون مجفف (مجفف)","2 ملعقة كبيرة مخلل حلو مفروم (ريليش)","⅛ ملعقة صغيرة فلفل كايين أو بابريكا (حسب الرغبة)","⅛ ملعقة صغيرة فلفل أسود (مطحون طازجًا)","2 حبة خيار متوسطة (مقشرة ومقطعة إلى شرائح دائرية)"],
["في وعاء متوسط، اخلط جميع المكونات ما عدا الخيار، وامزجها جيدًا.","ضع شرائح الخيار في صحن التقديم وضع فوقها ملعقة من سلطة السلطعون."],[],[])))
O.append(R(6284164,
("Paletas de limón","Disfrute estas paletas de limón en un caluroso día de verano. Frescas y cítricas, son un manjar refrescante y apto para personas con diabetes para combatir el calor.","4","1 paleta (aproximadamente 1/2 taza de líquido)",
["3/4 de taza de jugo de limón","1/2 taza de agua","2 cucharaditas de stevia"],
["En un tazón, bata el jugo de limón, el agua y la stevia.","Vierta en moldes para paletas, usando alrededor de 1/2 taza de líquido para cada una.","Congele durante 6 horas o toda la noche."],[],[]),
("مصّاصات الليمون المثلجة","استمتع بمصّاصات الليمون المثلجة هذه في يوم صيفي حار. منعشة بنكهة الحمضيات، وهي حلوى مثلجة مناسبة لمرضى السكري للتبريد.","4","1 مصّاصة مثلجة (نحو ½ كوب سائل)",
["¾ كوب عصير ليمون","½ كوب ماء","2 ملعقة صغيرة ستيفيا"],
["في وعاء، اخفق عصير الليمون والماء والستيفيا.","اسكب الخليط في قوالب المصّاصات المثلجة، مستخدمًا نحو ½ كوب من السائل لكل قالب.","جمّدها لمدة 6 ساعات أو طوال الليل."],[],[])))
O.append(R(6284632,None,
("كرنب بروكسل مخلل","طريقة سهلة للتخليل في الثلاجة تحوّل كرنب بروكسل إلى لقيمات مقرمشة لاذعة منكّهة بالشبت والثوم. يمكنك أيضًا استخدام طريقة التخليل السريعة هذه مع الخضار الأخرى المفضلة لديك.","8","¼ كوب مصفى",
["8½ كوب ماء (يُستخدم على دفعات)","2 كوب كرنب بروكسل طازج (مقطوع إلى نصفين)","1 برطمان كامل سعة 1 باينت بغطاء (أو علبة بلاستيكية مقاومة للحرارة سعة 1 باينت)","½ كوب خل أبيض مقطّر","1 ملعقة صغيرة ملح","2 ملعقة صغيرة سكر","1 ورقة غار","2 غصن شبت طازج","2 فص ثوم (مهروس)","¼ كوب بصل (مفروم ناعمًا)","1 ملعقة كبيرة توابل التخليل"],
["في قدر كبير على نار عالية، سخّن 7 أكواب من الماء وأحضرها إلى درجة الغليان. ضع 1 كوب من الماء في وعاء مملوء بالثلج.","أضف كرنب بروكسل إلى الماء المغلي واطهه لمدة دقيقتين. استخدم ملعقة مثقبة لنقل الكرنب إلى الماء المثلج ليبرد. صفِّ الكرنب بعد أن يبرد وعبّئه في البرطمان.","ضع الخل و½ كوب من الماء والملح والسكر في قدر صغير على نار عالية. أحضرها إلى درجة الغليان وحرّكها حتى يذوب الملح والسكر. دعها تغلي لمدة دقيقتين. ارفع المحلول الملحي عن النار.","أضف ورقة الغار والشبت والثوم والبصل وتوابل التخليل إلى المحلول الملحي.","املأ البرطمان بحذر بالمحلول الملحي بحيث يغطي كرنب بروكسل بالكامل.","ضع الغطاء على البرطمان وهزّ البرطمان برفق لتوزيع المكونات.","ضعه في الثلاجة لمدة ساعتين على الأقل قبل التقديم. احفظه في الثلاجة لمدة تصل إلى 3 أشهر. قبل التقديم، أخرج ورقة الغار وتخلّص منها.","نصيحة الشيف: الخضار القاسية فقط، مثل كرنب بروكسل والجزر، تحتاج إلى سلقها سلقًا خفيفًا أولًا. أما الخضار الأطرى، مثل الخيار والكوسا، فيمكن وضعها نيئة في البرطمان قبل إضافة المحلول الملحي."],[],[])))
dump(O,"../out_c8_part2.json")
