from h import *
R=[]
R.append((6913065,{
"es":L("Brochetas de pollo tikka",
"Estas brochetas de pollo tikka son una forma apta para personas con diabetes de disfrutar de comida india perfectamente condimentada, sin muchas calorías ni carbohidratos.",
"4","2 brochetas + 1/4 taza de salsa tzatziki",
["3 dientes de ajo (rallados)","1/4 taza de yogur griego natural sin grasa","2 cucharadas de jugo de limón","2 cucharaditas de ralladura de limón","2 cucharaditas de pimentón","2 cucharaditas de comino molido","2 cucharaditas de garam masala","1 cucharadita de cúrcuma","1 cucharadita de pimienta de cayena","1/2 cucharadita de sal kosher","1 libra de pechugas de pollo deshuesadas y sin piel (cortadas en cubos de 1 pulgada)","1 pimiento rojo grande (cortado en trozos de 1 pulgada)","1 cebolla roja pequeña (cortada en trozos de 1 pulgada)","8 brochetas de bambú enteras (remojadas durante 20 minutos)","1 rocío de 0.25 g de aceite antiadherente en aerosol","1 taza de salsa tzatziki (para servir)"],
["En un tazón grande, mezcle el ajo, el yogur, la ralladura y el jugo de limón, las especias y la sal kosher hasta que se integren.","Agregue el pollo al tazón y revuelva hasta que todos los cubos estén cubiertos de manera uniforme con el adobo. Tape y deje marinar durante 20 minutos (o refrigere hasta por 24 horas).","Deseche el adobo y ensarte el pollo en las brochetas, alternándolo con el pimiento y la cebolla.","Engrase ligeramente la parrilla, la plancha o el sartén para asar y colóquelos a fuego alto. Cuando estén calientes, coloque las brochetas sobre la parrilla y gírelas para que se cocinen de manera uniforme, durante 12–15 minutos, según el grosor del pollo.","Deje reposar las brochetas tapadas durante 5 minutos antes de servirlas con salsa tzatziki."]),
"ar":L("كباب دجاج تكّا",
"كباب الدجاج تكّا هذا طريقة مناسبة لمرضى السكري للاستمتاع بطعام هندي متبّل بإتقان دون الكثير من السعرات الحرارية أو الكربوهيدرات.",
"4","2 سيخ + ¼ كوب صلصة تزاتزيكي",
["3 فصوص ثوم (مبشورة)","¼ كوب زبادي يوناني سادة خالي الدسم","2 ملعقة كبيرة عصير ليمون","2 ملعقة صغيرة قشر ليمون مبشور","2 ملعقة صغيرة بابريكا","2 ملعقة صغيرة كمون مطحون","2 ملعقة صغيرة جارام ماسالا","1 ملعقة صغيرة كركم","1 ملعقة صغيرة فلفل كايين","½ ملعقة صغيرة ملح كوشر","1 رطل صدور دجاج منزوعة العظم والجلد (مقطعة إلى مكعبات بحجم 1 بوصة)","1 حبة فلفل رومي أحمر كبيرة (مقطعة إلى قطع بحجم 1 بوصة)","1 بصلة حمراء صغيرة (مقطعة إلى قطع بحجم 1 بوصة)","8 أعواد خيزران كاملة (منقوعة لمدة 20 دقيقة)","1 بخّة زيت طهي بخاخ غير لاصق (0.25 غرام)","1 كوب صلصة تزاتزيكي (للتقديم)"],
["في وعاء كبير، اخلط الثوم والزبادي وقشر الليمون وعصيره والتوابل وملح الكوشر حتى تتجانس.","أضف الدجاج إلى الوعاء وقلّب حتى تُغطّى جميع المكعبات بالتتبيلة بالتساوي. غطِّ الوعاء واتركه ينقع في التتبيلة لمدة 20 دقيقة (أو ضعه في الثلاجة لمدة تصل إلى 24 ساعة).","تخلّص من التتبيلة وثبّت الدجاج على الأسياخ بالتناوب مع الفلفل الرومي والبصل.","ادهن الشواية أو المقلاة المخصصة للشوي أو الصاج بقليل من الزيت وضعها على نار عالية. وعندما تسخن، ضع الأسياخ على الشواية وقلّبها لتنضج بالتساوي لمدة 12–15 دقيقة حسب سماكة قطع الدجاج.","اترك الكباب مغطى لمدة 5 دقائق قبل تقديمه مع صلصة تزاتزيكي."])}))
R.append((6913457,{
"ar":L("دجاج مو شو في قدر الطهي البطيء",
"إليك وصفة بسيطة للغاية في قدر الطهي البطيء، تُطهى أثناء غيابك وتكون جاهزة عند موعد العشاء!",
"4","1 كأس من الخس",
["12 أونصة ملفوف البروكلي المبشور (بروكلي سلو)","3 حبات جزر (مبشورة)","1 رطل صدور دجاج منزوعة العظم والجلد (مقطعة شرائح رقيقة)","3 ملاعق كبيرة صلصة هويسين","¼ كوب ماء","3 فصوص ثوم (مفروم)","1 ملعقة صغيرة صلصة صويا قليلة الصوديوم","1 ملعقة كبيرة نشا الذرة","4 أوراق خس بيب أو بوسطن"],
["ضع خليط الملفوف المبشور والجزر في قاع قدر الطهي البطيء، ثم ضع الدجاج فوقه.","في وعاء صغير، اخلط صلصة الهويسين والماء والثوم وصلصة الصويا ونشا الذرة. اسكب الخليط فوق الدجاج واضبط قدر الطهي البطيء على الحرارة العالية لمدة 4-6 ساعات.","قدّم 1½ كوب من الخليط في كل ورقة خس."])}))
R.append((6914294,{
"es":L("Res estofada con zanahorias y nabos en olla de cocción lenta",
"Tierna y jugosa, esta res estofada con zanahorias y nabos en olla de cocción lenta será un éxito con quien la pruebe. ¡Pruebe servirla en su próxima cena familiar del domingo!",
"8","1 taza",
["2 cucharadas de aceite de oliva","1 1/2 libras de asado de res (corte redondo inferior, magro, grasa recortada a 1/8 de pulgada, deshuesado) (sin grasa)","1 cebolla amarilla grande (picada)","3 dientes de ajo (picados)","1/2 taza de agua","3 cucharadas de pasta de tomate","5 zanahorias grandes (cortadas en trozos de 1 pulgada)","4 nabos medianos (pelados y picados)","2 1/2 cucharaditas de tomillo seco","2 hojas de laurel","1/2 cucharadita de sal kosher","1 cucharadita de pimienta negra","2 latas (de 8 onzas) de salsa de tomate (baja en sodio)","14 1/2 onzas de caldo de res bajo en sodio"],
["En un sartén grande a fuego medio-alto, caliente 1 cucharada de aceite de oliva. Dore los trozos de res por todos lados. Pase la carne dorada a la olla de cocción lenta.","En el mismo sartén, agregue la cucharada de aceite restante si es necesario. Saltee la cebolla y el ajo hasta que se ablanden.","Desglase el sartén con el agua, raspando los restos dorados del fondo. Agregue la pasta de tomate y revuelva para integrar.","Pase la mezcla de cebolla y tomate a la olla de cocción lenta.","Agregue las zanahorias, los nabos, el tomillo seco, las hojas de laurel, la sal y la pimienta a la olla de cocción lenta.","Vierta la salsa de tomate baja en sodio y el caldo de res sobre los ingredientes en la olla de cocción lenta.","Tape y cocine a temperatura baja de 6–8 horas, o hasta que la carne esté tierna.","Antes de servir, deseche las hojas de laurel y ajuste el sazón si es necesario."]),
"ar":L("لحم بقري مطهو ببطء مع الجزر واللفت",
"لحم طري وغني بالعصارة، سيحوز طبق اللحم البقري المطهو ببطء مع الجزر واللفت إعجاب كل من يتذوقه. جرّب تقديمه في عشاء العائلة القادم يوم الأحد!",
"8","1 كوب",
["2 ملعقة كبيرة زيت زيتون","1½ رطل لحم بقري للتحمير (من الفخذ السفلي، قليل الدهن، مع تقليم الدهن حتى ⅛ بوصة، منزوع العظم) (بعد إزالة الدهون)","1 بصلة صفراء كبيرة (مفرومة)","3 فصوص ثوم (مفرومة)","½ كوب ماء","3 ملاعق كبيرة معجون طماطم","5 حبات جزر كبيرة (مقطعة إلى قطع بحجم 1 بوصة)","4 حبات لفت متوسطة (مقشرة ومقطعة)","2½ ملعقة صغيرة زعتر مجفف","2 ورقة غار","½ ملعقة صغيرة ملح كوشر","1 ملعقة صغيرة فلفل أسود","2 علبة (8 أونصات) صلصة طماطم (قليلة الصوديوم)","14½ أونصة مرق لحم بقري قليل الصوديوم"],
["في مقلاة كبيرة على نار متوسطة إلى عالية، سخّن 1 ملعقة كبيرة من زيت الزيتون. حمّر قطع اللحم من جميع الجوانب، ثم انقل اللحم المحمّر إلى قدر الطهي البطيء.","في المقلاة نفسها، أضف ملعقة الزيت المتبقية إذا لزم الأمر. قلّب البصل والثوم حتى يذبلا.","أضف الماء إلى المقلاة لتذويب القطع المحمّرة العالقة في القاع مع كشطها، ثم أضف معجون الطماطم وقلّب حتى يمتزج.","انقل خليط البصل والطماطم إلى قدر الطهي البطيء.","أضف الجزر واللفت والزعتر المجفف وورق الغار والملح والفلفل إلى قدر الطهي البطيء.","اسكب صلصة الطماطم قليلة الصوديوم ومرق اللحم فوق المكونات في قدر الطهي البطيء.","غطِّ القدر واطهِ على حرارة منخفضة لمدة 6–8 ساعات أو حتى يصبح اللحم طريًا.","قبل التقديم، أخرج ورق الغار وعدّل التوابل إذا لزم الأمر."])}))
R.append((6914404,{
"ar":L("سكالوب مشوي مع صلصة فيردي الخشنة",
"هذا طبق مأكولات بحرية رائع قليل الدهون والصوديوم وغني بالبروتين. جرّب تقديمه مع سلطة جرجير بسيطة مزينة ببضع قطع من الفراولة لتوازن حدّة صلصة السالسا فيردي الحارة.",
"4","3 حبات سكالوب و½ كوب صلصة",
["½ رطل طماطيو (مقشر ومغسول ومقطع مكعبات صغيرة)","1 حبة فلفل هالابينو صغيرة (منزوعة البذور والعروق ومفرومة)","¼ كوب كزبرة خضراء طازجة (مفرومة)","1 حبة كوسا متوسطة (منزوعة البذور ومقطعة مكعبات صغيرة)","2 ملعقة كبيرة عصير ليمون أخضر","1 ملعقة صغيرة عسل أو ½ كيس محلٍّ صناعي","2 فص ثوم (مفروم)","12 حبة سكالوب كبيرة (بعد إزالة العضلة الجانبية الصغيرة (ملاحظة: يُفضَّل سكالوب البحر الطازج أو الذي لم تُضَف إليه مواد حافظة))","1 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["جهّز شواية داخلية أو خارجية.","في وعاء متوسط، اخلط الطماطيو والهالابينو والكزبرة الخضراء والكوسا وعصير الليمون الأخضر والستيفيا والثوم. امزج المكونات جيدًا وضعها جانبًا.","جفّف السكالوب بمنديل ورقي. قلّبه مع زيت الزيتون والملح والفلفل في وعاء متوسط.","ضع السكالوب على الشواية على جانبه المسطح. قلّبه من حين لآخر واشوه حتى يتفحم قليلًا وينضج تمامًا، حوالي 2 دقيقة لكل جانب. قدّم السكالوب مغطى بصلصة فيردي الخشنة."])}))
R.append((6914849,{
"es":L("Bacalao cocido lentamente con cítricos",
"El pescado blanco, como el bacalao, tiene un sabor delicado que le permite absorber los sabores de los ingredientes con los que se cocina. Al asarlo con rodajas de limón y naranja y con hinojo, este pescado adquiere un sabor cítrico y brillante.",
"4","4 onzas de pescado",
["1/4 cucharadita de pimienta negra","1/2 cucharadita de sal kosher","2 cucharadas de aceite de oliva","4 ramitas de tomillo fresco","1 libra de filetes de bacalao (4 filetes, de unas 4 onzas cada uno)","1/2 jalapeño pequeño (partido por la mitad, sin semillas y en rodajas finas)","1 limón mediano (sin pelar, en rodajas finas, sin semillas)","1 naranja mediana (sin pelar, en rodajas finas, sin semillas)","1 bulbo de hinojo entero (en rodajas finas)"],
["Precaliente el horno a 300° F. Mezcle el hinojo, las rodajas de naranja y de limón, y el jalapeño en un molde para hornear de 9 por 13 pulgadas.","Coloque los trozos de bacalao junto a la mezcla de cítricos. Esparza las ramitas de tomillo sobre el pescado. Rocíe con el aceite de oliva y espolvoree con la sal y la pimienta.","Ase el pescado de 25 a 30 minutos, o hasta que esté opaco y bien cocido. Sirva el pescado con el hinojo asado y los cítricos."]),
"ar":L("سمك القد المحمّر ببطء مع الحمضيات",
"للسمك الأبيض، مثل سمك القد، نكهة رقيقة تسمح له بامتصاص نكهات المكونات التي يُطهى معها. وتحميصه مع شرائح الليمون والبرتقال والشمر يمنحه نكهة حمضية منعشة.",
"4","4 أونصات من السمك",
["¼ ملعقة صغيرة فلفل أسود","½ ملعقة صغيرة ملح كوشر","2 ملعقة كبيرة زيت زيتون","4 أغصان زعتر طازج","1 رطل شرائح سمك القد (4 شرائح، حوالي 4 أونصات لكل منها)","½ حبة هالابينو صغيرة (مقسومة نصفين، منزوعة البذور ومقطعة شرائح رقيقة)","1 حبة ليمون متوسطة (بقشرها، مقطعة شرائح رقيقة، منزوعة البذور)","1 حبة برتقال متوسطة (بقشرها، مقطعة شرائح رقيقة، منزوعة البذور)","1 بصلة شمر كاملة (مقطعة شرائح رقيقة)"],
["سخّن الفرن مسبقًا إلى 300° فهرنهايت (150° مئوية). اخلط الشمر وشرائح البرتقال والليمون والهالابينو في صينية خبز مقاس 9 × 13 بوصة.","ضع قطع سمك القد بجانب خليط الحمضيات. وزّع أغصان الزعتر فوق السمك. رشّ زيت الزيتون وذرّ الملح والفلفل.","حمّر السمك في الفرن لمدة 25 إلى 30 دقيقة، أو حتى يصبح معتمًا وناضجًا تمامًا. قدّم السمك مع الشمر المحمّر والحمضيات."])}))
R.append((6915533,{
"ar":L("يخنة خضار اقتصادية مع زلابية القمح الكامل",
"ما الأفضل في الخريف من شوربة دافئة ولذيذة؟ هذه الوصفة الاقتصادية سهلة التحضير إلى حد كبير.",
"8","1½ كوب يخنة + 1 زلابية",
["1 ملعقة كبيرة زيت زيتون","1 بصلة شمر كاملة (مقطعة مكعبات)","1 بصلة متوسطة (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","4 كوب يقطين الجوز (مقطع مكعبات)","1 ملعقة صغيرة مريمية مطحونة","4 كوب مرق دجاج قليل الصوديوم (قليل الصوديوم)","4 كوب ماء","2 ملعقة صغيرة ملح (مقسمة للاستخدام)","¾ ملعقة صغيرة فلفل أسود (مقسمة للاستخدام)","2 ورقة غار","4 كوب كيل (مقطع، 1 حزمة بعد إزالة السيقان وتقطيعها)","1 كوب دقيق القمح الكامل","½ كوب دقيق متعدد الاستخدامات","1 ملعقة كبيرة بيكنج باودر","1 ملعقة صغيرة أعشاب بروفانس (أو مريمية مجففة)","1 بيضة كبيرة","½ كوب زبادي يوناني سادة خالي الدسم"],
["ضع الزيت في قدر شوربة كبير على نار متوسطة إلى عالية.","أضف الشمر والبصل والكرفس إلى الزيت وقلّبها حتى يصبح البصل شفافًا (حوالي 4-5 دقائق). أضف يقطين الجوز والمريمية ومرق الدجاج والماء و1 ملعقة صغيرة ملح (اختياري) و½ ملعقة صغيرة فلفل أسود وورق الغار. اتركها تغلي ثم خفّف الحرارة لتغلي على نار هادئة.","اترك اليخنة على نار هادئة لمدة 20 دقيقة، ثم أضف الكيل واتركها على نار هادئة 10 دقائق أخرى.","بينما تغلي اليخنة على نار هادئة، اخفق جميع مكونات الزلابية معًا للحصول على عجينة سائلة متماسكة. ضعها جانبًا.","بعد أن يغلي الكيل لمدة 10 دقائق، أخرج ورق الغار.","استخدم كوب قياس ¼ كوب لوضع الزلابية فوق اليخنة بحيث تحصل على 8 حبات. لا تقلّب بعد وضع الزلابية فوق اليخنة. غطِّ القدر وخفّف الحرارة إلى أدنى درجة غليان لمدة 10 دقائق حتى تنضج الزلابية تمامًا وتنتفخ."])}))
R.append((6916353,{
"ar":L("سلطة البرتقال والجوز",
"قدّم هذه السلطة الخفيفة كخيار صحي في تجمعكم الاحتفالي هذا العام. ستمنحك بعض الفاكهة والخضار الطازجة، وهما أمران غالبًا ما يغيبان عن مائدة الأعياد المعتادة!",
"8","حوالي ⅔ كوب من خليط البرتقال والجزر + 1 كوب خضروات ورقية",
["2 حبة برتقال كبيرة (مقشرة ومقسمة إلى فصوص)","8 كوب خضروات ورقية مشكلة للسلطة","1 بصلة حمراء صغيرة (مقطعة شرائح رقيقة)","2 حبة جزر كبيرة (مقشرة ومقطعة شرائح رقيقة)","2 ملعقة كبيرة عصير برتقال طازج","2 ملعقة كبيرة عصير ليمون (طازج)","1 ملعقة كبيرة عسل","2 ملعقة صغيرة خردل ديجون","¼ كوب زيت الجوز","⅛ ملعقة صغيرة فلفل أسود (حسب الرغبة)","¼ كوب قطع الجوز"],
["ضع الخضروات الورقية في طبق التقديم. ضع فوقها الجزر والبصل والبرتقال.","لتحضير الصلصة، اخفق عصير البرتقال وعصير الليمون مع العسل والخردل. أضف الزيت ببطء على شكل خيط رفيع مع الاستمرار في الخفق.","رشّ الصلصة فوق السلطة. أضف الفلفل حسب الرغبة، وزيّنها بالجوز."])}))
R.append((6917127,{
"ar":L("فريتاتا الخضار الصيفية الاقتصادية",
"هذه الفريتاتا طريقة رائعة لتناول المزيد من الخضار في يومك، ويمكن الاستمتاع بها على وجبة برنش أو عشاء. باستخدام مزيج من بياض البيض والبيض الكامل، تقلّل من بعض الدهون المشبعة والكوليسترول.",
"4","2 شريحة",
["1 ملعقة كبيرة زيت زيتون","8 أونصات فطر أبيض (فطر الأزرار) (مقطع مكعبات)","1 حبة فلفل رومي أحمر متوسطة (منزوعة البذور ومقطعة مكعبات)","1 بصلة صغيرة (مقطعة مكعبات)","3 كوب سبانخ","2 بيضة كبيرة","5 بياض بيض كبير","¼ كوب حليب خالي الدسم","½ ملعقة صغيرة ملح (اختياري)","½ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة فلفل كايين","1 ملعقة كبيرة ريحان طازج (مفروم)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية).","ضع زيت الزيتون في مقلاة غير لاصقة صالحة للفرن على نار متوسطة إلى عالية.","أضف الفطر وقلّبه حتى يتبخر كل السائل الخارج منه.","أضف الفلفل الرومي والبصل والسبانخ وقلّبها حتى تذبل الخضار ويتبخر السائل.","اخفق البيض وبياض البيض والحليب والملح (اختياري) والفلفل وفلفل الكايين والريحان في وعاء متوسط. اسكب الخليط فوق الخضار وقلّب حتى يبدأ البيض بالتماسك.","سوِّ سطح الفريتاتا بملعقة عريضة (سباتولا) وضعها في الفرن لمدة 20 دقيقة أو حتى يتماسك البيض.","اسحب الفريتاتا من المقلاة إلى طبق وقطّعها إلى 8 شرائح على شكل شرائح فطيرة."])}))
R.append((6917203,{
"es":L("Tazón de batido de granada y frambuesa",
"El tofu sedoso crea una base cremosa llena de proteínas y grasas saludables en este tazón de batido para la mañana. Cubierto con semillas de granada y muesli, un cereal saludable de granos integrales y fruta seca, este tazón de batido lo llenará y le dará energía durante toda la mañana. Es una receta vegana, vegetariana y baja en grasa.",
"2","1 taza",
["8 onzas de tofu sedoso (escurrido)","2 cucharadas de jugo de granada","1/2 taza de frambuesas (congeladas)","2 cucharaditas de jarabe sin azúcar","1 onza de semillas de granada","1/4 taza de muesli"],
["Coloque el tofu, el jugo de granada, las frambuesas y el jarabe en una licuadora o procesador de alimentos. Licúe a velocidad alta hasta que esté cremoso y de color rosado.","Divida la mezcla entre 2 tazones. Cubra cada uno con la mitad de las semillas de granada y 2 cucharadas de muesli."]),
"ar":L("وعاء سموذي الرمان والتوت الأحمر",
"يشكّل التوفو الحريري قاعدة كريمية غنية بالبروتين والدهون الصحية في وعاء السموذي الصباحي هذا. مغطّى بحبوب الرمان والموسلي، وهو حبوب كاملة صحية مع فاكهة مجففة، سيشبعك وعاء السموذي هذا ويمدّك بالطاقة طوال الصباح. هذه وصفة نباتية خالية من المنتجات الحيوانية وخفيفة الدهون.",
"2","1 كوب",
["8 أونصات توفو حريري (مصفّى)","2 ملعقة كبيرة عصير رمان","½ كوب توت العليق (مجمّد)","2 ملعقة صغيرة شراب خالٍ من السكر","1 أونصة حبوب رمان","¼ كوب موسلي"],
["ضع التوفو وعصير الرمان وتوت العليق والشراب في خلاط أو محضّرة طعام. اخلط على أعلى سرعة حتى يصبح الخليط كريميًا ويتحول لونه إلى الوردي.","قسّم الخليط بين 2 وعاء. زيّن كل وعاء بنصف كمية حبوب الرمان و2 ملعقة كبيرة من الموسلي."])}))
R.append((6917425,{
"en":L("Asian Tuna Salad",
"This Asian tuna salad is perfect for food lovers looking for a healthy main dish with an Asian twist!",
"4","1.5 cups salad with just under 4 oz (113 grams) of fish.",
["2 tbsp low-sodium or reduced-sodium soy sauce","2 1/2 tbsp low-calorie brown sugar substitute","1 tsp Asian hot sauce (Sriracha, optional)","1/2 tsp black pepper","1 spray nonstick cooking spray","1 lb fresh white tuna","1 lb asparagus (trimmed)","1 tsp sesame seeds","6 cups mixed spring lettuce (washed and dried, or spun in a salad spinner)","1 large red bell pepper (julienned)","1 medium cucumber (seeded and julienned)","1/4 cup rice wine vinegar","1 tbsp toasted sesame oil"],
["Preheat an indoor or outdoor grill.","In a small bowl, whisk together the soy sauce, brown sugar substitute, hot sauce (optional) and black pepper. Set aside.","Spray the indoor grill with cooking spray. If using an outdoor grill, make sure the grates are clean and lightly oiled.","Brush the tuna and asparagus with the soy sauce marinade. Place them on the grill. Grill the tuna for 3 minutes per side. Grill the asparagus, turning frequently, until it begins to soften (about 6-8 minutes). Remove the tuna and asparagus from the grill, sprinkle with sesame seeds and let cool. The tuna should be slightly pink in the center, but not raw.","Combine the lettuce, red bell pepper and cucumber in a salad bowl.","In a small bowl, whisk the dressing ingredients. Pour it over the salad and toss gently to coat well. Divide the salad evenly among four plates.","Once the tuna and asparagus have cooled to room temperature or slightly warmer, slice the tuna and divide it evenly among the four salads (a little under 4 oz or 115 grams of tuna per salad). Carefully place it on top of the salad.","Cut the asparagus in half and arrange it around the edge of the salad."]),
"ar":L("سلطة التونة الآسيوية",
"هذه السلطة الآسيوية بالتونة مثالية لمحبي الطعام الذين يبحثون عن طبق رئيسي صحي بلمسة آسيوية!",
"4","1.5 كوب سلطة مع أقل بقليل من 113 غرامًا من السمك.",
["2 ملعقة كبيرة صلصة صويا قليلة الصوديوم أو مخفضة الصوديوم","2½ ملعقة كبيرة بديل السكر البني قليل السعرات","1 ملعقة صغيرة صلصة حارة آسيوية (سريراتشا، اختياري)","½ ملعقة صغيرة فلفل أسود","1 بخّة زيت طهي بخاخ غير لاصق","1 رطل تونة بيضاء طازجة","1 رطل هليون (مقلّم)","1 ملعقة صغيرة بذور سمسم","6 كوب خس ربيعي مشكل (مغسول ومجفف أو منشّف بمجفف السلطة)","1 حبة فلفل رومي أحمر كبيرة (مقطعة شرائح طويلة رفيعة)","1 حبة خيار متوسطة (منزوعة البذور ومقطعة شرائح طويلة رفيعة)","¼ كوب خل نبيذ الأرز","1 ملعقة كبيرة زيت سمسم محمّص"],
["سخّن شواية داخلية أو خارجية مسبقًا.","في وعاء صغير، اخفق صلصة الصويا وبديل السكر البني والصلصة الحارة (اختياري) والفلفل الأسود. ضعها جانبًا.","رشّ الشواية الداخلية ببخاخ زيت الطهي. وإذا كنت تستخدم شواية خارجية، فتأكد من نظافة الشبك ودهنه بقليل من الزيت.","افرد تتبيلة صلصة الصويا على التونة والهليون. ضعهما على الشواية. اشوِ التونة 3 دقائق لكل جانب. اشوِ الهليون مع تقليبه بكثرة حتى يبدأ بالليونة (حوالي 6-8 دقائق). أخرج التونة والهليون من الشواية، وذرّ عليهما بذور السمسم واتركهما يبردان. يجب أن تكون التونة وردية قليلًا في الوسط وليست نيئة.","اخلط الخس والفلفل الرومي الأحمر والخيار في وعاء السلطة.","في وعاء صغير، اخفق مكونات التتبيلة. اسكبها فوق السلطة وقلّب بلطف لتتغلغل جيدًا. وزّع السلطة بالتساوي على أربعة أطباق.","بعد أن تبرد التونة والهليون إلى درجة حرارة الغرفة أو تبقى أدفأ قليلًا، قطّع التونة إلى شرائح ووزّعها بالتساوي على السلطات الأربع (أقل بقليل من 115 غرامًا من التونة لكل سلطة). ضعها برفق فوق السلطة.","قطّع الهليون إلى نصفين ورتّبه حول حافة السلطة."])}))
R.append((6918726,{
"es":L("Magdalenas de proteína y arándanos azules con 5 ingredientes",
"No se deje engañar. Estas magdalenas de proteína y arándanos azules con 5 ingredientes pueden ser más pequeñas, ¡pero son deliciosas! Esta receta puede ayudarle a incluir más proteína en su dieta al combinar arándanos azules frescos, dulces y ligeramente ácidos con los sabores cálidos de la mantequilla de almendra y el yogur griego de vainilla sin grasa. Mejor aún, esta receta tiene solo cinco ingredientes, por lo que es facilísima de preparar y de llevar a cualquier parte.",
"6","1 magdalena",
["1 plátano mediano","1 taza de quinoa (cocida)","1/4 taza de yogur griego de vainilla (sin grasa)","1/4 taza de mantequilla de almendra","1 taza de arándanos azules (frescos)","1 rocío de 0.25 g de aceite antiadherente en aerosol"],
["Precaliente el horno a 375° F. Rocíe 6 moldes para magdalenas con aceite en aerosol. En un tazón grande, mezcle el plátano, la quinoa, el yogur sin grasa y la mantequilla de almendra hasta que se integren. Incorpore con movimientos envolventes los arándanos azules.","Vierta la masa con una cuchara en los moldes preparados. Hornee de 20 a 25 minutos, o hasta que estén dorados y firmes en el centro. Deje enfriar por completo."]),
"ar":L("مافن البروتين بالتوت الأزرق بـ5 مكونات",
"لا تنخدع. قد تكون مافن البروتين بالتوت الأزرق بـ5 مكونات أصغر حجمًا، لكنها بالتأكيد لذيذة! يمكن أن تساعدك هذه الوصفة على إضافة المزيد من البروتين إلى نظامك الغذائي بدمج التوت الأزرق الطازج الحلو الحامض مع النكهات الدافئة لزبدة اللوز والزبادي اليوناني بالفانيليا الخالي من الدسم. والأفضل من ذلك أن هذه الوصفة تحتوي على خمسة مكونات فقط، ما يجعل تحضيرها سهلًا للغاية وحملها معك في أي مكان.",
"6","1 كعكة مافن",
["1 موزة متوسطة","1 كوب كينوا (مطبوخة)","¼ كوب زبادي يوناني بالفانيليا (خالٍ من الدسم)","¼ كوب زبدة اللوز","1 كوب توت أزرق (طازج)","1 بخّة زيت طهي بخاخ غير لاصق (0.25 غرام)"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية). رشّ 6 قوالب مافن ببخاخ زيت الطهي. في وعاء كبير، اخلط الموز والكينوا والزبادي الخالي من الدسم وزبدة اللوز حتى تتجانس. أضف التوت الأزرق برفق.","اسكب العجينة بالملعقة في قوالب المافن المجهزة. اخبز لمدة 20 إلى 25 دقيقة أو حتى يتحول لونها إلى الذهبي وتتماسك في الوسط. اتركها تبرد تمامًا."])}))
R.append((6920949,{
"es":L("Pollo desmenuzado con cilantro y limón verde",
"Cocinar las pechugas de pollo en una olla de cocción lenta las ablanda, por lo que es fácil desmenuzarlas. Este pollo está impregnado de un sabor picante a limón verde y es delicioso sobre hojas de lechuga o en una tortilla, acompañado de guacamole y salsa.",
"4","3/4 taza",
["1 cebolla roja pequeña (finamente picada)","1/4 taza de jugo de limón verde (recién exprimido, más 2 cucharadas)","1/4 cucharadita de sal kosher","1 libra de pechugas de pollo deshuesadas y sin piel (sin nada de grasa)","1 cucharadita de chile en polvo","1/2 cucharadita de comino molido","1 taza de caldo de pollo bajo en sodio (sin grasa)","1 limón verde pequeño (cortado en gajos para servir)","1/4 taza de cilantro (picado)"],
["En un tazón mediano, mezcle la cebolla, el jugo de limón verde y la sal. Cubra con envoltura de plástico y deje reposar a temperatura ambiente de 3 a 5 horas, mientras se cocina el pollo.","Coloque el pollo en una olla de cocción lenta mediana. Espolvoree con el chile en polvo y el comino. Vierta el caldo de pollo alrededor del pollo. Tape y cocine a temperatura baja de 3 a 5 horas, o hasta que el pollo alcance una temperatura de 165° F.","Retire el pollo de la olla de cocción lenta y, con las puntas de dos tenedores, desmenúcelo. Coloque el pollo en un tazón y mézclelo con la mezcla de cebolla y limón verde. Sirva con gajos de limón verde y el cilantro picado espolvoreado por encima.","Variación con olla de presión eléctrica: Prepare la mezcla de cebolla y limón verde como se indicó. Coloque el pollo en la olla de presión. Espolvoree con chile en polvo y comino. Vierta el caldo de pollo alrededor del pollo. Asegure la tapa. Cocine a presión alta durante 6 minutos. Deje que la presión se libere de forma natural durante 5 minutos y luego libere rápidamente la presión restante. Continúe como se indicó anteriormente."]),
"ar":L("دجاج مسحوب بالكزبرة والليمون الأخضر",
"طهي صدور الدجاج في قدر الطهي البطيء يجعلها طرية فيسهل تفتيتها وسحبها. تتشرب هذه الدجاجة نكهة الليمون الأخضر الحارة، وهي لذيذة على أوراق الخس أو في التورتيلا مع الجواكامولي والسالسا.",
"4","¾ كوب",
["1 بصلة حمراء صغيرة (مفرومة ناعمًا)","¼ كوب عصير ليمون أخضر (معصور طازجًا، بالإضافة إلى 2 ملعقة كبيرة)","¼ ملعقة صغيرة ملح كوشر","1 رطل صدور دجاج منزوعة العظم والجلد (بعد إزالة كل الدهون)","1 ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","½ ملعقة صغيرة كمون مطحون","1 كوب مرق دجاج قليل الصوديوم (خالٍ من الدسم)","1 حبة ليمون أخضر صغيرة (مقطعة إلى أرباع للتقديم)","¼ كوب كزبرة خضراء (مفرومة)"],
["في وعاء متوسط، اخلط البصل وعصير الليمون الأخضر والملح. غطِّه بغلاف بلاستيكي واتركه جانبًا في درجة حرارة الغرفة لمدة 3 إلى 5 ساعات، أثناء طهي الدجاج.","ضع الدجاج في قدر طهي بطيء متوسط. رشّ عليه مسحوق الفلفل الحار والكمون. اسكب مرق الدجاج حول الدجاج. غطِّ القدر واطهِ على حرارة منخفضة لمدة 3 إلى 5 ساعات أو حتى تصل حرارة الدجاج إلى 165° فهرنهايت (75° مئوية).","أخرج الدجاج من قدر الطهي البطيء، وباستخدام شوكتين فتّته. ضع الدجاج في وعاء وقلّبه مع خليط البصل والليمون الأخضر. قدّمه مع أرباع الليمون الأخضر والكزبرة الخضراء المفرومة مرشوشة فوقه.","طريقة بديلة بقدر الضغط الكهربائي: حضّر خليط البصل والليمون الأخضر كما سبق. ضع الدجاج في قدر الضغط. رشّ عليه مسحوق الفلفل الحار والكمون. اسكب مرق الدجاج حول الدجاج. أحكم إغلاق الغطاء. اطهِ على ضغط عالٍ لمدة 6 دقائق. اترك الضغط يتحرر طبيعيًا لمدة 5 دقائق، ثم حرّر الضغط المتبقي بسرعة. أكمل كما سبق."])}))
save("out_c24_part1.json",R)
