import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xfr5')
from lib import *
o=[]
o.append(R(2950,"Mini pains de viande glacés au chipotle",
"Ces pains de viande ont une touche épicée grâce à un glaçage à la poudre de piment chipotle. Préparés en portions individuelles, les mini pains de viande glacés au chipotle sont faciles à faire et à servir.",
"2","1 mini pain de viande",
["2 oignons verts (ciboules)","3 gousses d'ail","1/2 cuillère à café de poudre de piment chipotle","2 cuillères à soupe de ketchup sans sel ajouté","1/2 livre de bœuf haché, 10 % de matières grasses","1/2 tasse de chapelure panko","1/2 cuillère à café de poivre","1/8 cuillère à café de sel"],
["Préchauffez le four à 400° F, la grille placée en position supérieure. Parez et émincez finement les oignons verts en séparant les parties blanches des parties vertes. Hachez finement les parties blanches. Écrasez la gousse d'ail avec le plat du couteau pour que la peau s'ouvre. Pelez l'ail et hachez-le finement.","Dans un petit bol, mélangez le ketchup et 1/2 cuillère à café de poudre de piment chipotle et réservez.","Dans un bol moyen, mélangez le bœuf, les parties blanches des oignons verts, l'ail haché, le panko, le poivre, le sel et le reste de 1/2 cuillère à café de poudre de piment chipotle.","Façonnez le mélange de bœuf en deux pains. Placez-les sur une plaque de cuisson vaporisée d'aérosol antiadhésif.","Faites cuire jusqu'à ce que les pains de viande soient presque cuits, environ 15 minutes.","Badigeonnez les pains de viande du mélange de ketchup. Remettez au four de 4 à 8 minutes ou jusqu'à ce que les pains de viande soient cuits à cœur, à une température interne de 160° F.","Garnissez des parties vertes des oignons verts hachées avant de servir."],
["Les pains peuvent aussi être cuits dans des moules à pain individuels.","Si vous ne trouvez pas de ketchup sans sel ajouté à votre épicerie locale, envisagez de le commander en ligne.","Doublez la recette pour en préparer davantage à congeler en vue d'un plat rapide plus tard."],
["3 viande","1 féculent","1/2 légume, faible teneur en potassium"]))
o.append(R(2951,"Salade de thon du Sud-Ouest",
"La cuisine du Sud-Ouest de la région de l'Arizona a sa propre personnalité vibrante, issue d'influences espagnoles et mexicaines. Elaine, de l'Arizona, a mis ses talents culinaires à profit et créé la salade de thon du Sud-Ouest adaptée aux reins, avec une touche de jalapeño.",
"2","3/4 tasse",
["1/4 tasse de mayonnaise","2 piments jalapeños frais","1/2 concombre moyen","2 oignons verts","1 cuillère à soupe de coriandre fraîche","1 cuillère à soupe de jus de lime frais","5 onces de thon en conserve pauvre en sodium, conservé dans l'eau"],
["Épépinez et hachez finement les piments jalapeños. Épépinez et hachez le concombre ; hachez les oignons verts et la coriandre.","Dans un bol moyen, mélangez la mayonnaise, le piment jalapeño et le jus de lime.","Incorporez le thon égoutté. Mélangez bien.","Ajoutez le concombre et les oignons verts. Réfrigérez jusqu'au moment de servir.","Servez une portion de salade de thon du Sud-Ouest sur de la laitue, un bagel ou le pain de votre choix. Garnissez de coriandre hachée si désiré."],
[],
["2-1/2 viande","1 légume, faible teneur en potassium","2 matière grasse"]))
o.append(R(2953,"Frittata aux courgettes",
"La courgette est l'un des légumes les plus polyvalents. Vous pouvez en faire du pain ou des muffins, l'ajouter crue à une salade, la cuire à la vapeur, la faire bouillir, la cuire au micro-ondes ou la faire frire, ou vous pouvez essayer la frittata aux courgettes proposée par Jessica, diététicienne DaVita de Californie. Cette recette adaptée aux reins plaira à coup sûr !",
"9","1 morceau",
["2 courgettes moyennes","1 oignon moyen","1/4 tasse de persil","1 gousse d'ail","4 gros œufs","1 tasse de préparation pour biscuits","1/2 tasse de parmesan râpé","1/4 tasse d'huile de canola","1/2 cuillère à café de marjolaine séchée","1/4 cuillère à café de poivre noir"],
["Préchauffez le four à 350° F. Râpez les courgettes ; hachez l'oignon et le persil ; hachez finement l'ail. Battez légèrement les œufs.","Dans un grand bol, mélangez tous les ingrédients et mélangez bien.","Versez dans un moule graissé de 11 x 7 pouces ou une poêle en fonte de 9 pouces. Faites cuire de 30 à 35 minutes, jusqu'à ce que la frittata soit prise et légèrement dorée.","Coupez en 9 morceaux et servez."],
["Les restes sont encore délicieux le lendemain ! Réfrigérez et réchauffez au four ou au micro-ondes.","Délicieuse chaude ou froide !"],
["1/2 viande","1/2 féculent","1/2 légume, faible teneur en potassium","1 matière grasse"]))
o.append(R(2956,"Salade de pois chiches et de riz brun",
"Mélange de riz brun, de pois chiches, de persil, de poivron, de concombre et d'un peu de feta, cette salade de pois chiches et de riz brun est riche en saveur comme en fibres.",
"6","3/4 tasse",
["1/2 tasse de riz brun, sec","15 onces de pois chiches en conserve","1/2 tasse de persil frais","1/4 tasse de jus de citron frais","3 cuillères à soupe d'huile d'olive","1/2 cuillère à café de poivre noir","1 poivron rouge moyen","1 tomate Roma","1/2 oignon rouge moyen","1 petit concombre anglais","2 cuillères à soupe de fromage feta émietté"],
["Faites cuire le riz brun selon les instructions et réservez.","Rincez et égouttez les pois chiches. Hachez le persil.","Dans un grand bol, ajoutez le persil, le jus de citron, l'huile d'olive et le poivre noir. Fouettez ensemble pour préparer la vinaigrette.","Hachez le poivron, la tomate, l'oignon et le concombre et ajoutez-les au bol avec la vinaigrette.","Ajoutez le riz cuit et les pois chiches, mélangez pour combiner.","Garnissez de feta émiettée.","Laissez reposer de 30 minutes à 1 heure avant de servir pour que les saveurs se développent pleinement."],
["Servez froide ou à température ambiante.","Cette recette peut être préparée à l'avance et conservée au réfrigérateur jusqu'à 3 jours."],
["2 féculent","1/2 légume, teneur moyenne en potassium"]))
o.append(R(2959,"Soupe mexicaine aux boulettes de viande (albóndigas)",
"La soupe mexicaine aux boulettes de viande est une version plus pauvre en sodium et adaptée aux reins de cette célèbre soupe mexicaine.",
"6","3 boulettes + 3/4 tasse de liquide avec 1/3 tasse de légumes",
["1 oignon moyen","1 grosse carotte","1 petite courgette","1/2 tasse de coriandre fraîche","48 onces de bouillon de poulet pauvre en sodium","2 cuillères à café de cumin moulu","4 onces de piments verts en dés en conserve","4 onces de sauce tomate non salée","2 cuillères à soupe de jus de lime","1 cuillère à café de paprika","1/4 cuillère à café de sel","1/4 cuillère à café de piment de Cayenne (ajustez selon le goût)","1 gros œuf","1 cuillère à café d'ail haché","1 livre de bœuf haché","1/2 tasse de riz blanc cuit","1/2 cuillère à café de poivre noir"],
["Préchauffez le four à 400° F. Hachez finement 1/4 de l'oignon et réservez jusqu'au moment de préparer les boulettes. Coupez en dés de 3/4 de pouce le reste de l'oignon, la carotte et la courgette. Hachez la coriandre.","Versez le bouillon dans une marmite et chauffez à feu moyen. Ajoutez les légumes en dés, 1 cuillère à café de cumin, les piments verts, la sauce tomate, 1/4 tasse de coriandre, le jus de lime, le paprika, le sel et le piment de Cayenne. Couvrez la marmite et réduisez à feu doux.","Dans un bol moyen, mélangez l'œuf, 1 cuillère à café de cumin et l'ail. Ajoutez le bœuf haché, le riz cuit et l'oignon finement haché réservé. Mélangez jusqu'à ce que le tout soit combiné.","Formez des boulettes d'environ 1-1/2 pouce de diamètre pour obtenir 18 boulettes. Placez-les sur une plaque de cuisson tapissée de papier sulfurisé et faites cuire 20 minutes, jusqu'à ce qu'elles soient dorées et cuites à cœur. Laissez refroidir les boulettes 5 minutes.","Ajoutez les boulettes et le reste de 1/4 tasse de coriandre à la soupe et laissez mijoter 10 minutes avant de servir."],
["Les boulettes peuvent être cuites dans le bouillon au lieu d'être cuites au four si vous le souhaitez, mais cela troublera le bouillon. Ajoutez les boulettes crues au bouillon chaud, couvrez et faites cuire à feu moyen pendant 30 minutes."],
["2-1/2 viande","1/2 féculent","1 légume, teneur moyenne en potassium"]))
o.append(R(2960,"Poulet rôti au citron à la Crock-Pot®",
"Imaginez rentrer du travail ou d'une longue journée à l'extérieur et, en ouvrant la porte, sentir l'odeur d'un succulent poulet au citron, prêt à être servi pour le dîner. Ce n'est pas qu'un rêve si vous essayez cette recette adaptée aux reins de poulet rôti au citron à la Crock-Pot® de Deanna, diététicienne DaVita de l'Ohio.",
"8","1 blanc de poulet",
["1 cuillère à soupe d'huile d'olive","2 gousses d'ail, hachées","1 cuillère à café d'origan","2 livres de blancs de poulet avec os et avec peau","13 onces de bouillon de poulet en conserve à teneur réduite en sodium","3 cuillères à soupe de jus de citron"],
["Chauffez l'huile dans une grande poêle.","Ajoutez l'ail et l'origan.","Ajoutez les blancs de poulet et faites-les dorer de tous les côtés.","Placez le poulet dans la Crock-Pot et ajoutez le bouillon de poulet.","Faites cuire à feu doux de 6 à 8 heures.","Ajoutez le jus de citron pendant la dernière heure de cuisson."],
["Complétez ce repas avec une portion de riz, des haricots verts, du pain français, de la margarine ou du beurre et une pomme au four en dessert.","Utilisez les restes de blancs de poulet dans une salade de poulet ou un sandwich pour le déjeuner du lendemain.","Recherchez un bouillon à teneur réduite en sodium contenant 500 milligrammes de sodium ou moins par portion de 1 tasse. Les marques recommandées comprennent Health Valley® No Salt, Fat Free Chicken Broth (1-800-423-4846), Kitchen Basics® Natural Chicken Stock et Swanson® 50% Less Sodium Chicken Broth. Le bouillon pauvre en sodium est aussi un bon choix. Il contient moins de 140 milligrammes de sodium par tasse. Évitez les bouillons pauvres en sodium qui contiennent du chlorure de potassium : ils sont très riches en potassium.","Si vous suivez un régime à protéines restreintes, demandez conseil à votre diététicien sur la taille de portion adaptée à votre régime."],
["3-1/2 viande"]))
o.append(R(2961,"Raviolis et courgettes",
"Les plats de pâtes sont une excellente façon de varier votre alimentation à la place d'un repas typique à base de viande. La recette adaptée aux reins de raviolis et courgettes de Sandra, diététicienne DaVita, peut être préparée de A à Z en 20 minutes ou moins : l'astuce de ce plat est de ne pas trop cuire les raviolis, qui doivent conserver cette qualité al dente qu'apprécient les Italiens. La traduction littérale d'« al dente » est « sous la dent » : plantez-y les vôtres dans cette délicieuse recette.",
"4","1 tasse",
["9 onces de raviolis au bœuf surgelés","2 tasses de courgettes","3 oignons verts","1 poivron rouge moyen","1/2 cuillère à café d'ail en poudre","1/2 cuillère à café de feuilles de basilic séchées","1/8 cuillère à café de poivre noir","1/4 tasse de bouillon de poulet à teneur réduite en sodium"],
["Coupez les courgettes en julienne et émincez les oignons verts ; hachez grossièrement le poivron.","Faites cuire les raviolis selon les instructions de l'emballage.","Vaporisez une grande poêle antiadhésive d'aérosol de cuisson et chauffez à feu moyen-vif.","Ajoutez les courgettes, les oignons verts, le poivron, l'ail en poudre, le basilic et le poivre noir. Faites cuire de 3 à 5 minutes jusqu'à ce que les légumes soient tendres mais croquants.","Égouttez les raviolis, ajoutez le bouillon et incorporez au mélange de légumes.","Couvrez la poêle et faites cuire à feu moyen-doux encore 5 minutes, ou jusqu'à ce que le tout soit bien chaud. Remuez de temps en temps en prenant soin de ne pas briser les raviolis."],
["Si les légumes sont préparés à l'avance, c'est un repas rapide et facile que tout le monde peut préparer.","Accompagne bien une salade verte et du pain français.","Essayez d'autres types de raviolis, surgelés ou frais, au bœuf ou au poulet."],
["1-1/2 viande","1-1/2 féculent","1 légume, teneur moyenne en potassium"]))
o.append(R(2962,"Pilaf de riz meilleur que celui en sachet",
"Le fait maison est toujours meilleur que les aliments préemballés, tant pour la saveur que pour la valeur nutritive. Brooke, diététicienne DaVita de Californie, a créé ce pilaf de riz adapté aux reins et plus pauvre en sodium. Il est facile à préparer et constitue un excellent choix, surtout par comparaison avec le pilaf de riz préemballé.",
"6","3/4 tasse",
["2 onces de vermicelles, crus","2 cuillères à soupe de beurre non salé","1 tasse de riz étuvé, cru","2 tasses d'eau","1 cuillère à soupe de mélange d'assaisonnements oignon et herbes Mrs. Dash®","1 cuillère à café de granulés de bouillon à saveur de poulet"],
["Dans une poêle à feu moyen, faites fondre 1 cuillère à soupe de beurre.","Cassez les vermicelles en morceaux de 2 pouces et faites-les cuire en remuant souvent jusqu'à ce qu'ils commencent à dorer.","Ajoutez le reste du beurre et le riz. Remuez pour combiner.","Ajoutez l'eau, l'assaisonnement aux herbes Mrs. Dash et les granulés de bouillon de poulet dans la poêle. Remuez pour mélanger les ingrédients.","Couvrez et portez à ébullition. Réduisez à feu doux et laissez mijoter 20 minutes. Ne retirez pas le couvercle.","Éteignez le feu et laissez reposer, couvert, encore 5 minutes.","Égrenez à la fourchette et servez."],
["Des cheveux d'ange ou des spaghettis fins peuvent remplacer les vermicelles.","À titre de comparaison, le pilaf de riz préemballé préparé avec du beurre salé ou de la margarine contient de 400 à 650 mg de sodium par portion de 1/2 tasse.","Certains granulés ou cubes de bouillon pauvres ou à teneur réduite en sodium contiennent du chlorure de potassium au lieu de sel. Ils ne sont pas recommandés si vous suivez un régime pauvre en potassium.","Congelez les portions supplémentaires et réchauffez-les au micro-ondes pour un accompagnement de féculents très rapide plus tard."],
["2 féculent","1/2 matière grasse"]))
o.append(R(2964,"Boulettes de maïs et de fromage",
"Préparées par la mère d'un patient dialysé, les boulettes de maïs et de fromage sont une collation fromagère qui vous rassasiera tout en respectant le régime rénal.",
"8","4 boulettes",
["2 tasses de maïs jaune surgelé","1 piment vert","2 cuillères à soupe de coriandre fraîche","1/2 tasse de fromage cottage","4 tranches de pain blanc","1/2 tasse de farine blanche tout usage","1 cuillère à café de poudre de chili","1 cuillère à café de cumin en poudre","1 cuillère à café de coriandre en poudre","1/4 cuillère à café de sel","2 tasses d'huile végétale"],
["Décongelez le maïs. Hachez finement le piment vert et la coriandre.","Dans un bol à mélanger, mélangez le fromage et le maïs décongelé.","Faites tremper les tranches de pain dans l'eau et essorez-les pour que le pain devienne sec. Ajoutez-le au mélange de maïs et de fromage. Ajoutez la farine, les épices sèches et la coriandre. Mélangez délicatement.","Chauffez l'huile dans une grande casserole. À l'aide d'une cuillère à soupe, formez de petites boulettes avec le mélange de maïs et de fromage et déposez chaque boulette dans l'huile chaude. Faites cuire jusqu'à ce qu'elles soient dorées.","Retirez les boulettes de l'huile et placez-les sur un plateau recouvert d'un essuie-tout pour égoutter l'excès d'huile.","Servez chaud avec du chutney de coriandre."],
["Si vous en trouvez, remplacez le fromage cottage par du fromage paneer émietté.","Le paneer est un fromage non affiné obtenu en faisant cailler du lait avec du jus de citron ou un autre aliment acide. Les substituts comprennent le fromage cottage à grains secs, le fromage fermier, le queso blanco ou le queso fresco. La portion est limitée car ce produit laitier contient du phosphore."],
["2 féculent","1/2 légume, teneur moyenne en potassium","2 matière grasse"]))
o.append(R(2965,"Bouchées apéritives en barquettes de tomate",
"Les tomates et les haricots figurent sur la liste des aliments à « limiter » dans la plupart des régimes rénaux, mais de petites portions de ces ingrédients sains peuvent être incluses tout en gardant le potassium et le phosphore sous contrôle. En plus des nutriments supplémentaires, une portion des bouchées apéritives en barquettes de tomate de Christine, diététicienne DaVita, contient 2,5 grammes de fibres.",
"8","1 demi-tomate",
["4 tomates Roma fermes","1 cuillère à soupe d'huile d'olive extra vierge","1 cuillère à café de poivre noir","1 cuillère à café d'ail en poudre","1 cuillère à café de mélange d'herbes assaisonnées sans sel","15 onces de pois chiches en conserve","1/2 citron","1 cuillère à café de vinaigre de vin rouge","8 feuilles de menthe fraîche"],
["Coupez les tomates en deux et jetez la chair pour former des « barquettes ».","Arrosez légèrement l'intérieur des barquettes de tomate de 1/2 cuillère à soupe d'huile d'olive, 1/2 cuillère à café de poivre, 1/2 cuillère à café d'ail en poudre et 1/2 cuillère à café d'assaisonnement sans sel.","Rincez et égouttez les pois chiches. Dans un bol, ajoutez les pois chiches, le reste de l'huile d'olive, les épices, le jus de 1/2 citron et le vinaigre. Mélangez ensemble.","Déposez le mélange de pois chiches à la cuillère dans les barquettes de tomate. Garnissez d'une feuille de menthe.","Réfrigérez et servez frais."],
["Remplacez chaque moitié de tomate par 1/4 de poivron rouge moyen si vous le souhaitez. Le potassium est inférieur de 12 mg.","Les pois chiches, et d'autres légumineuses, sont riches en potassium et en phosphore. De petites quantités peuvent être incluses dans une alimentation rénale saine pour augmenter les fibres. Chaque barquette contient environ 1/6 de tasse de pois chiches.","Retirer la pulpe des tomates réduit la teneur en potassium."],
["1/2 féculent","1/2 légume, teneur moyenne en potassium","1/2 matière grasse"]))
save(o,7)
