import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes3')
from h import *
X=[]
def G(g,l): return [(g,x) for x in l]
X.append(r(9798062,"Bowl Buda de tofu con salsa de cacahuate","¡El tofu crujiente, la sabrosa salsa de cacahuate, los granos y las verduras frescas hacen de este bowl Buda de tofu algo inolvidable!","4 porciones","1 porción",
G("Para el tofu crujiente",["1 bloque de 350 gramos (12 onzas) de tofu extra firme cortado en cubos de media pulgada (use tofu sin transgénicos si es posible)","2 cucharadas de salsa de soya baja en sodio (o tamari si es sin gluten)","2 cucharadas de polvo de arrurruz o fécula de maíz","1 cucharadita de cebolla en polvo","1 cucharadita de ajo en polvo"])+
G("Para la salsa de cacahuate",["⅓ de taza de crema de cacahuate lisa (de la natural, sin aceite ni azúcar añadidos)","2 cucharadas de vinagre de arroz","2 cucharadas de jugo de limón (aprox. 1 limón)","2 cucharadas de salsa de soya (o tamari si es sin gluten)","1 a 2 dientes de ajo picados","½ cucharada de jengibre fresco rallado","1 a 2 cucharadas de agua filtrada para aligerar"])+
G("Para servir (opcional)",["arroz integral, fideos o quinoa","verduras como col morada rallada, zanahorias, tiras de pimiento morrón rojo, jitomates cherry partidos por la mitad, pepino rebanado, aguacate, cebollín"]),
["Precaliente el horno a 425° F/218° C y forre una bandeja para hornear con papel pergamino.","Coloque los cubos de tofu en un tazón mediano y agregue la salsa de soya. Mezcle suavemente para cubrir los trozos. Luego agregue el arrurruz y las especias y revuelva hasta que queden cubiertos de manera uniforme.","Acomode los cubos sazonados en una sola capa sobre la bandeja forrada con pergamino. Luego hornee durante 15 minutos, voltee los cubos y hornee de 8 a 10 minutos más, o hasta alcanzar la crujiencia deseada.","Mientras se hornea el tofu, agregue todos los ingredientes de la salsa de cacahuate a un tazón pequeño y mezcle hasta integrar, agregando de 1 a 2 cucharadas de agua para aligerar a la consistencia que prefiera.","Sirva con las verduras frescas de su elección y el grano de su elección, y rocíe cada bowl con la salsa de cacahuate, o sírvala aparte para mojar."],
["No es necesario prensar el tofu si usa extra firme para esta receta. Lo he probado de ambas formas y la diferencia fue mínima. Dicho esto, puede prensarlo primero si lo desea.","Haga su mejor esfuerzo por cortar los cubos de tofu del mismo tamaño para una cocción uniforme.","Asegúrese de acomodar los cubos en una sola capa con bastante espacio entre ellos para que queden bien crujientes.","Las sobras se conservan refrigeradas de 3 a 4 días."],[]))
X.append(r(9801698,"¡No puedo creer que sea una poutine vegana!","¡Una poutine vegana con cuajos de queso que CHIRRÍAN! Es la poutine vegana DEFINITIVA y de verdad sabe como la original. ¡Mejor imposible!","3 porciones","1 porción",
G("Para las papas fritas",["1.5 libras de papas russet (aprox. 3 papas grandes)","1 cucharadita de aceite de aguacate (para que no lleve aceite, sustitúyalo por 1 cucharada de caldo)","½ cucharadita de sal marina","½ cucharadita de romero seco","1 cucharada de fécula de maíz"])+
G("Para los cuajos de queso",["½ receta de queso mozzarella vegano"])+
G("Para la salsa gravy",["100 gramos de champiñones cremini rebanados finamente (aprox. 4 a 5 pequeños)","1 cucharadita de tamari o salsa de soya (si no evita el gluten)","1 taza de caldo de verduras bajo en sodio","1 cucharada de harina de arroz integral o harina multiusos (si no evita el gluten)"])+
G("Decoración opcional",["cebollín"]),
["Primero, prepare el queso mozzarella vegano, páselo a un recipiente o tazón y refrigere para que se enfríe.","Precaliente el horno a 425 grados F con convección y forre una bandeja grande para hornear con papel pergamino.","Pele o lave bien las papas y córtelas en bastones con un cortador de papas fritas o un cuchillo afilado.","Mezcle las papas fritas con el aceite, la sal, el romero y la fécula de maíz hasta que queden cubiertas de manera uniforme. Luego extiéndalas en una sola capa sobre la bandeja preparada. Hornee de 20 a 25 minutos, luego voltee las papas y hornee de 15 a 20 minutos más, o hasta alcanzar el nivel de crujiencia deseado.","Mientras se hornean las papas, prepare la salsa gravy. Agregue los champiñones rebanados y el tamari a una olla pequeña y cocine a fuego medio hasta que los champiñones se reduzcan, aprox. 5 minutos. Agregue el caldo y lleve a hervor, cocinando de 1 a 2 minutos.","Mientras tanto, mezcle la cucharada de harina con una cucharada de agua en un tazón pequeño aparte para hacer su mezcla espesante. (Esto espesará su salsa.) Luego vierta la mezcla en la olla y bata bien para integrar. Cocine 1 minuto más y retire del fuego. La salsa se espesará aún más al empezar a enfriarse.","Arme su poutine colocando primero las papas fritas y luego tome el queso vegano con un cortador de bolitas de melón (o una cucharita) para poner los \"cuajos de queso\" encima. (¡Al tomar los cuajos, escuche el CHIRRIDO! :)) Por último, vierta la salsa gravy encima y espolvoree con cebollín, si lo desea. ¡DISFRUTE!"],
["Asegúrese de acomodar las papas en una sola capa con bastante espacio entre ellas para obtener las papas fritas horneadas más crujientes y evitar que se peguen. Si su horno no tiene convección, las papas pueden necesitar un poco más de tiempo de cocción. Siga horneando hasta alcanzar el nivel de crujiencia deseado. Para una salsa gravy suave sin trozos de champiñón, puede licuarla una vez cocida. Si no le gustan los champiñones, puede seguir la misma técnica con cebollas rebanadas finamente, o probar esta salsa gravy de cebolla. ¡No omita la mezcla espesante! Puede sentir la tentación de agregar la harina directamente a la salsa caliente, pero esto provocará grumos. Si lo prepara con anticipación, puede preparar el queso por completo y refrigerarlo un par de días, hasta que lo necesite."],[]))
X.append(r(9807540,"Jitomates en freidora de aire","¡Jitomates en freidora de aire jugosos, sabrosos y absolutamente deliciosos!","3 porciones","1 porción",
["1 pinta de jitomates cherry","1 cucharada de vinagre balsámico","1 cucharadita de orégano seco","1 cucharadita de ajo en polvo","¼ de cucharadita de sal marina o al gusto","¼ de cucharadita de hojuelas de chile rojo (opcional, pero recomendado)"],
["Agregue todos los ingredientes a un recipiente apto para horno que quepa dentro de la canasta de su freidora de aire. Mezcle bien para cubrir los jitomates de manera uniforme y coloque el recipiente dentro de la canasta.","Cocine en la freidora de aire a 375° F/190° C de 8 a 10 minutos, o hasta que la piel de los jitomates se vea arrugada, mezclando una vez a la mitad del tiempo; luego retire el recipiente de la freidora.","Disfrútelos sobre pan tostado, como guarnición o como cobertura para hamburguesas."],
["Experimente con diferentes variedades de jitomate. También puede usar rebanadas de jitomate si son de formato grande, como el beefsteak. Cada modelo cocina a una velocidad distinta, así que vigile los jitomates con cuidado y empiece a revisarlos alrededor de los 5 minutos. Las sobras se conservan refrigeradas de 3 a 4 días."],[]))
X.append(r(9807591,"Salami vegano picante","Un salami vegano picante, con textura de carne, ahumado, lleno de sabor y realmente irresistible. Es fácil de hacer y tiene una textura masticable perfecta, ¡tal vez le cueste creer que es vegano!","6 porciones","1 porción",
G("Ingredientes secos",["1 taza de gluten de trigo vital","2 cucharaditas de pimentón ahumado","2 cucharaditas de ajo en polvo","1 cucharadita de semillas de hinojo","1 cucharadita de sal marina","1 cucharadita de cebolla en polvo","1 cucharadita de orégano seco","1 cucharadita de perejil seco","1 cucharadita de pimienta negra","½ cucharadita de hojuelas de chile"])+
G("Ingredientes húmedos",["½ taza de caldo de verduras bajo en sodio","2 cucharadas de pasta de tomate","1 cucharada de aceite de aguacate o el aceite de sabor neutro de su elección","1 cucharada de salsa de soya","2 cucharaditas de humo líquido"]),
G("Instrucciones para el horno",["Precaliente el horno a 375 grados F.","Combine todos los ingredientes secos en un tazón y mezcle bien. Luego combine los ingredientes húmedos en otro tazón y bata para integrar.","Vierta los ingredientes húmedos sobre los secos y empiece a mezclar hasta que estén casi integrados y tenga algo parecido a una masa. Luego pase a una superficie limpia o tabla para cortar y use las manos para amasar y presionar la masa durante 1 a 2 minutos. Debe sentirse suave y verse bien integrada.","Ahora corte la masa en dos piezas del mismo tamaño y ruédelas para darles forma de salami de unas 6 pulgadas de largo. No tiene que quedar perfecto; se alisará al cocinarse. Luego envuelva cada salami con papel pergamino y después con papel aluminio, asegurándose de que el aluminio sea lo bastante largo para traslaparse y luego retuerza los extremos. (Vea las fotos del proceso arriba para una referencia visual.)","Coloque los salamis envueltos en una bandeja para hornear y hornee de 45 a 55 minutos, volteándolos a la mitad del tiempo.","Saque del horno y despegue con cuidado el aluminio para ver si los salamis se ven lisos, y presione con el dedo para probar su firmeza. Deben sentirse firmes, pero ceder un poco a la presión. Se firmarán más al enfriarse.","Deje enfriar por completo, luego rebane y disfrute con pizza, en sándwiches, en una tabla de charcutería o como refrigerio."])+
G("Instrucciones para cocinar al vapor",["Siga los pasos 2 a 4 anteriores para preparar el salami. Luego agregue 1 a 2\" de agua a una olla grande donde quepa su canasta para vapor, SIN que el agua toque la canasta. Lleve a hervor y luego reduzca el fuego para mantener un hervor bajo y coloque los salamis dentro de la canasta.","Tape y cocine al vapor de 45 a 60 minutos, vigilando el agua para asegurarse de que no se evapore por completo. Empiece a revisarlos alrededor de los 45 minutos. Retire con cuidado el aluminio; el salami debe verse liso. Puede presionarlo con el dedo o con unas pinzas para probar su firmeza. Deben sentirse firmes, pero ceder un poco a la presión. Se firmarán más al enfriarse.","Deje enfriar por completo, luego rebane y disfrute con pizza, en sándwiches, en una tabla de charcutería o como refrigerio."]),
["Asegúrese de amasar y mezclar muy bien la masa para obtener un sabor uniforme y la mejor textura. No se preocupe demasiado por darle al salami una forma perfecta. Se verá irregular antes de hornearse, pero queda liso y bonito al cocinarse. Si no le gusta que el papel aluminio toque su comida, use papel pergamino entre el salami y la capa de papel aluminio. Para un salami vegano suave, simplemente omita las hojuelas de chile, pero conserve la pimienta negra para obtener el mejor sabor. Mantenga refrigerado en un recipiente sellado o bolsa con cierre hasta por 1 semana. O puede congelarlo hasta por 3 meses."],[]))
X.append(r(9808977,"Palomitas saludables en freidora de aire","Las palomitas en freidora de aire son un refrigerio saludable y delicioso que requiere solo UN ingrediente. Los granos de maíz palomero son TODO lo que necesita para un bocadillo crujiente y sabroso, sin culpa y completamente satisfactorio.","2 porciones","1 porción",
["¼ de taza de granos de maíz palomero",("Coberturas opcionales","mantequilla derretida o aceite"),("Coberturas opcionales","vinagre blanco"),("Coberturas opcionales","sal y pimienta"),("Coberturas opcionales","o sus mezclas de condimentos favoritas")],
["Precaliente la freidora a 400 grados F durante 5 minutos.","Luego coloque una hoja de papel aluminio con los lados ligeramente doblados hacia arriba en el fondo de la canasta. Vierta los granos encima, sin necesidad de extenderlos, y cierre la tapa. (Vea las fotos del proceso arriba para una referencia visual.)","Cocine en la freidora de aire durante unos 7 a 8 minutos, o hasta que el reventar de los granos disminuya. Debe empezar a reventar alrededor de los 4 a 5 minutos. Tenga en cuenta que los diferentes modelos funcionan a velocidades distintas, así que revise las palomitas con cuidado levantando la tapa lo justo para echar un vistazo.","Pase las palomitas a un tazón y agregue las coberturas que desee, o disfrútelas solas."],
["No olvide el papel aluminio. Aunque puede moverse o desplazarse por el ventilador, evitará que muchos granos se caigan por los pequeños orificios del fondo de la canasta antes de tener la oportunidad de reventar. Como con cualquier método para hacer palomitas, quedarán algunos granos sin reventar cuando termine el reventar; simplemente deséchelos. Las palomitas se conservan en una bolsa con cierre a temperatura ambiente de 3 a 4 días. Saque la mayor cantidad de aire posible al cerrarla para que las palomitas se mantengan frescas."],[]))
X.append(r(9809440,"Duraznos en freidora de aire [con instrucciones para horno]","¡Duraznos en freidora de aire dulces, suaves y acaramelados! ¡Sirva con helado de plátano para disfrutar duraznos con crema!","3 porciones","1 porción",
["1 libra de duraznos frescos maduros pero FIRMES (aprox. 3 grandes o 6 pequeños)",
("Marinada opcional","2 cucharadas de mantequilla vegana derretida"),("Marinada opcional","2 cucharadas de azúcar de coco o azúcar morena"),("Marinada opcional","1 cucharadita de canela"),
("Coberturas opcionales","helado de plátano (nice cream)"),("Coberturas opcionales","nueces de Castilla o pecanas picadas"),("Coberturas opcionales","granola o avena (sin gluten, si lo prefiere)")],
["Lave y rebane los duraznos y quíteles los huesos. Coloque los duraznos rebanados en un tazón pequeño y reserve.","Opcional: En otro tazón pequeño combine la mantequilla, el azúcar y la canela. Luego vierta la marinada sobre los duraznos rebanados y mezcle bien para cubrir las rebanadas de manera uniforme. (Puede cocinar los duraznos solos en la freidora de aire, sin la mezcla, si desea evitar grasa y azúcar añadidas.)","Acomode los duraznos rebanados en una sola capa en la canasta de la freidora y cocine en la freidora de aire a 350° F/177° C de 8 a 12 minutos. Están listos cuando están muy suaves y un tenedor atraviesa fácilmente una rebanada de durazno.","Sirva caliente con las coberturas que desee o disfrute tal cual."],
["Use duraznos frescos MADUROS para obtener el mejor sabor y dulzor natural. Corte los duraznos grandes en 6 rebanadas y los pequeños en 4 rebanadas. La madurez de los duraznos determinará el tiempo de cocción. Los duraznos más maduros y suaves se cocinarán más rápido que los menos maduros y duros. Retire las cáscaras de durazno que se desprendan durante la cocción en la freidora de aire. Para niños exigentes, pele los duraznos antes de rebanarlos y cocinarlos en la freidora de aire. La información nutricional INCLUYE la marinada opcional. No incluye coberturas opcionales como nueces y/o helado de vainilla. Omitir la marinada y cocinar los duraznos solos hará que este postre no tenga grasa y reducirá las calorías a 64 por porción."],[]))
X.append(r(9810559,"Sopa de zanahoria y lentejas","La sopa de zanahoria y lentejas es un platillo reconfortante, abundante, nutritivo y fácil de preparar.","6 porciones","1 porción",
["1.5 tazas de lentejas rojas, seleccionadas y enjuagadas","1 cebolla amarilla finamente picada","3 dientes de ajo pelados y picados","2 libras de zanahorias peladas y picadas en trozos grandes (aprox. 6 zanahorias grandes)","1.5 libras de camotes pelados y picados en trozos grandes (aprox. 2 camotes medianos)","8 tazas de caldo de verduras","2 cucharaditas de pimentón ahumado","1.5 cucharaditas de comino","sal y pimienta al gusto","2 a 3 cucharadas de jugo de limón al gusto, opcional pero recomendado",("Decoración opcional","perejil fresco, cilantro, cilantro en grano, jengibre recién rallado o un chorrito de aceite de oliva")],
["Agregue la cebolla y el ajo a una olla grande con una cucharada de agua o caldo (o aceite, si lo prefiere) y saltee a fuego medio hasta que estén transparentes, aprox. 5 minutos.","Luego agregue todos los demás ingredientes, excepto el jugo de limón. Lleve la sopa a hervor, luego reduzca el fuego y cocine a fuego lento hasta que las lentejas estén cocidas y las zanahorias y los camotes estén tiernos al pincharlos con un tenedor. Revuelva ocasionalmente.","Apague el fuego y use una licuadora de inmersión para hacer puré la sopa. Luego agregue el jugo de limón, la sal y la pimienta a su gusto, y disfrute."],
["Comience con 8 tazas de caldo, pero agregue más si prefiere una sopa más líquida.","Al reposar las sobras en el refrigerador, la sopa se espesará. Puede agregar más agua o caldo al recalentarla si desea aligerar la sopa.","Las sobras se conservan en el refrigerador de 3 a 4 días o congeladas hasta por 3 meses."],[]))
X.append(r(9811020,"Aderezo green goddess de aguacate [sin aceite]","Con mucha albahaca fresca, este aderezo green goddess para ensaladas agregará un toque de color y un sabor delicioso a sus ensaladas.","8 porciones (rinde aprox. 1 taza)","2 cucharadas",
["1 aguacate pequeño, pelado y sin hueso","½ taza de hojas de albahaca fresca, bien compactadas","¼ de taza de cebollín","¼ de taza de vinagre de manzana","2 cucharadas de jugo de limón (aprox. medio limón grande)","2 cucharadas de tahini","1 diente de ajo pelado","1 cucharada de jarabe de arce, opcional","1 a 2 cucharadas de agua, si es necesario para aligerar","sal y pimienta al gusto"],
["Agregue todos los ingredientes, excepto el agua, a una licuadora y procese hasta obtener una mezcla suave. Agregue el agua si prefiere una consistencia más líquida y vuelva a licuar.","Guarde en un recipiente hermético o frasco en el refrigerador hasta por 1 semana."],
["Para una textura más suave y cremosa con un color uniforme, use una licuadora de alta velocidad y procese hasta que quede completamente en puré. Si prefiere ver trocitos de hierbas en todo el aderezo, use un procesador de alimentos para procesar finamente todos los ingredientes primero (sin los líquidos). Luego agregue los ingredientes líquidos y pulse para combinar. Guarde su aderezo en un frasco de vidrio LIMPIO o recipiente hermético. Mantenga refrigerado hasta por 1 semana."],[]))
X.append(r(9811305,"Curry de calabaza butternut y garbanzos","Este curry de calabaza butternut y garbanzos está lleno de sabor y ¡garantiza impresionar!","6 porciones","1 porción",
["2 libras de calabaza butternut pelada y cortada en cubos de media pulgada (aprox. 6 tazas en cubos)","1 cucharada de aceite de coco (o use agua o caldo para saltear si no quiere aceite)","1 cebolla amarilla en cubos","2 zanahorias peladas y en cubos","1 a 2 chiles rojos tailandeses finamente picados, opcional para dar picante","6 dientes de ajo picados","1 cucharada de jengibre fresco rallado (aprox. un trozo de una pulgada)","4 onzas de pasta de curry rojo Thai Kitchen (aprox. 5 a 6 cucharadas)","2 cucharadas de salsa de soya (o tamari si es sin gluten)","2 cucharadas de jarabe de arce","1 taza de chícharos congelados","1 taza de caldo de verduras","13.5 onzas de leche de coco sin azúcar Thai Kitchen","1.5 tazas de garbanzos cocidos o enlatados","4 tazas de col rizada (kale), sin tallos","2 cucharadas de jugo de limón (aprox. 1 limón grande)","sal y pimienta al gusto",("Opcional","1 taza de cilantro, sin los tallos gruesos"),("Opcional","1 taza de albahaca tailandesa picada"),("Opcional","arroz integral y/o pan naan para servir")],
["Precaliente el horno a 425° F/218° C en asado con convección y forre una bandeja para hornear con papel pergamino.","Acomode los cubos de calabaza en una sola capa sobre la bandeja y espolvoree con sal y pimienta. Luego ase de 25 a 30 minutos, o hasta que estén ligeramente dorados y tiernos al pincharlos con un tenedor. Reserve.","Mientras tanto, derrita el aceite de coco (si lo usa) en una sartén grande y honda (o una olla de hierro fundido) y luego agregue la cebolla y las zanahorias y saltee hasta que se ablanden y se caramelicen ligeramente, aprox. de 8 a 10 minutos. Después, agregue los chiles, el ajo y el jengibre y revuelva constantemente hasta que desprendan aroma, aprox. 30 segundos.","Agregue a la sartén la pasta de curry rojo, la salsa de soya, el jarabe de arce, los chícharos, el caldo, la leche de coco, los garbanzos y la col rizada, y cocine a fuego lento de 8 a 10 minutos.","Luego apague el fuego y agregue el jugo de limón, el cilantro y la albahaca si los usa, e incorpore los cubos de calabaza butternut asados. Pruebe y agregue sal y pimienta, si es necesario.","Sirva este curry de calabaza butternut y garbanzos con arroz, pan naan o totopos de pita."],
["Si no tiene horno con convección, use 425° F/218° C en hornear (o asar, si lo tiene). Tardará de 5 a 10 minutos adicionales en asarse, según el tamaño de los cubos. Corte los cubos de calabaza butternut lo más uniformes posible para que se asen por igual. Las sobras se conservan en el refrigerador de 3 a 4 días; recaliéntelas en la estufa. Puede congelarlas en un recipiente hermético apto para congelador hasta por 3 meses, pero la textura de las verduras será más suave."],[]))
X.append(r(9814933,"Dip vegano de cheesecake con sabor a pan de jengibre","Un fantástico dip vegano de cheesecake lleno de reconfortantes sabores de pan de jengibre.","8 porciones","1 porción",
["1 taza de leche de coco light de lata","2 tazas de nueces de la India crudas o almendras blanqueadas","¼ de taza de azúcar de coco sin refinar","2 cucharadas de melaza media u oscura","1 cucharadita de jengibre molido","1 cucharadita de canela","⅛ de cucharadita de nuez moscada"],
["Agregue todos los ingredientes a una licuadora de alta velocidad y procese hasta obtener una mezcla suave y cremosa.","Refrigere el dip por al menos 1 hora antes de servirlo con rebanadas de manzana, piña, fresas, malvaviscos, galletas de jengibre o galletas graham."],
["Si no tiene una licuadora potente, remoje primero las nueces de la India en agua hirviendo durante 30 minutos. Esto las ablandará y facilitará licuarlas. Luego escúrralas, agréguelas a la licuadora con los demás ingredientes y procese hasta obtener una mezcla suave. El dip vegano de cheesecake se conserva refrigerado de 4 a 5 días o congelado hasta por 2 meses. CONSEJO: ¡congele el dip de 1 a 2 horas y disfrútelo como helado vegano de pan de jengibre!"],[]))
save(3,X)
