import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes3')
from h import *
X=[]
def G(g,l): return [(g,x) for x in l]
X.append(r(9816028,"Sopa de cacahuate con garbanzos en Instant Pot","La sopa de cacahuate en Instant Pot lleva verduras en trozos grandes como camote, calabacita y champiñones, junto con garbanzos en un cremoso caldo de cacahuate.","6 porciones","1 porción",
["1 pimiento morrón rojo grande en cubos gruesos","3 tazas de calabacita en cubos gruesos (aprox. 2 calabacitas medianas)","2.5 tazas de camote en cubos (aprox. 1 camote mediano)","1 paquete de 8 onzas de champiñones cremini partidos por la mitad, o en cuartos si son muy grandes","1 taza de elote congelado","1 lata de 15 onzas de garbanzos, escurridos y enjuagados (aprox. 1.5 tazas)","4 tazas de caldo de verduras bajo en sodio","½ taza de crema de cacahuate lisa","3 cucharadas de tamari o salsa de soya (si no evita el gluten)","1 cucharadita de pimentón ahumado","1 cucharadita de jengibre molido","1 cucharadita de ajo en polvo","½ cucharadita de pimienta de cayena (opcional, pero recomendado)",("Decoración opcional","cebollín"),("Decoración opcional","cacahuates picados"),("Decoración opcional","cilantro fresco"),("Decoración opcional","sriracha"),("Decoración opcional","rodajas de jalapeño"),("Decoración opcional","gajos de limón")],
G("Instrucciones para Instant Pot",["Vierta todos los ingredientes en la Instant Pot y cierre la tapa, asegurándose de que la válvula esté en la posición de sellado. Programe a alta presión durante 2 minutos (tardará unos 15 a 20 minutos en alcanzar la presión) y luego libere rápidamente el vapor cuando termine el temporizador.","Sirva decorada con las coberturas que desee."])+
G("Instrucciones para la estufa",["Agregue todos los ingredientes a una olla grande y lleve a hervor. Cuando hierva, baje el fuego y cocine a fuego lento de 12 a 15 minutos, hasta que las verduras estén tiernas al pincharlas con un tenedor.","Sirva decorada con las coberturas que desee."]),
["Corte los trozos de calabacita y champiñón más grandes, ya que se cocinan más rápido y no conviene que queden demasiado blandos. El camote puede ir un poco más pequeño, ya que requiere más tiempo de cocción. Así las verduras se cocinarán de manera uniforme. Libere rápidamente la presión y retire la tapa de inmediato (cuando sea seguro hacerlo) una vez que termine la cocción a presión, para evitar que las verduras se cuezan de más. Las sobras se conservan en un recipiente sellado en el refrigerador hasta por 4 días."],[]))
X.append(r(9822376,"Pesto de albahaca con limón sin nueces [sin aceite]","Aromático y fresco, con albahaca, ajo y limón: la receta perfecta de pesto sin aceite que necesita en su cocina.","6 porciones (rinde 1 taza)","1 porción",
["2 tazas de hojas de albahaca fresca, compactadas","3 a 4 dientes de ajo pelados","2 cucharadas de jugo de limón (aprox. medio limón grande)","½ cucharadita de sal marina o al gusto","1 a 2 cucharadas de agua, según sea necesario","2 tazas de cilantro fresco, compactado","3 a 4 dientes de ajo pelados","2 cucharadas de jugo de limón verde (aprox. 1 limón pequeño)","1 jalapeño (sin semillas para menos picante)","½ taza de semillas de girasol crudas sin sal","½ cucharadita de sal marina","2 a 4 cucharadas de agua, según sea necesario","2 tazas de perejil fresco, compactado","3 a 4 dientes de ajo pelados","2 cucharadas de jugo de limón (aprox. medio limón grande)","½ taza de jitomates secos","½ taza de aceitunas kalamata","¼ de cucharadita de sal marina","3 a 6 cucharadas de agua, según sea necesario"],
["Agregue todos los ingredientes, excepto el agua, a un procesador de alimentos o licuadora. Procese hasta obtener una mezcla suave y raspe los lados según sea necesario.","Agregue 1 cucharada de agua a la vez, según sea necesario, hasta alcanzar la consistencia deseada."],
["Puede guardar el pesto en un frasco en el refrigerador para usarlo en unos días. O manténgalo congelado hasta por 6 meses. Puede sustituir la albahaca por cualquier hierba, según desee. Solo mantenga la misma proporción. Use un procesador de alimentos para un pesto con algo de textura, o una licuadora para resultados más suaves. Siéntase libre de duplicar o triplicar la receta para hacer porciones para congelar y usar más adelante. Esto es especialmente útil al cosechar hierbas de su huerto para no desperdiciar nada."],[]))
X.append(r(9825585,"Paletas heladas de coco y limón","Mayormente ácidas con un toque de dulzura, estas paletas heladas son el refrigerio de verano perfecto. ¡Ideales para refrescarse en los días calurosos del sol de verano y hechas con solo 3 ingredientes!","7 paletas","1 porción",
["400 ml de leche de coco light","¼ de taza de jugo de limón verde recién exprimido (de aprox. 2 limones)","1 aguacate, pelado y sin hueso","2 cucharadas de jarabe de arce, opcional"],
["Agregue todos los ingredientes a una licuadora o procesador de alimentos y procese hasta obtener una mezcla suave. Luego vierta suavemente la mezcla en moldes para paletas o vasos de plástico. Congele durante 6 horas o toda la noche.","Cuando esté listo para disfrutarlas, pase la parte exterior del molde para paletas bajo agua tibia unos segundos y retire suavemente la paleta del molde."],
["Pruebe la mezcla antes de congelar. Tome una cuchara y pruebe la mezcla de paleta de limón (o de cualquier paleta que esté preparando) para comprobar el nivel de dulzor, acidez u otro sabor que desee agregar. Siempre puede agregar un poco más de jugo de limón antes de congelarlas, si lo desea. Al separar el molde de la paleta, tenga cuidado de no romperla. Pase la parte exterior del molde bajo agua tibia en el fregadero de su cocina durante unos segundos y luego trate de separarla suavemente. Use un movimiento de lado a lado, no jale. Repita hasta que pueda separar fácilmente las paletas de limón de su molde sin romperlas. Si le sobra un poco de mezcla de paleta de limón al final, congele el resto en una charola para cubos de hielo para hacer bocadillos pequeños. Llene los moldes casi hasta arriba. Las paletas solo se expandirán ligeramente, así que no deje demasiado espacio para la expansión, o el palito o la tapa no sostendrán bien la paleta. ¡Asegúrese de congelar las paletas el tiempo suficiente! Lo peor que puede hacer es sacar la paleta del molde antes de que esté completamente sólida. A mí me gusta darles un mínimo de 6 horas para asegurarme de que estén sólidas por completo. ¿No tiene moldes para paletas? ¡No hay problema! Use vasos de papel y congélelos con la abertura hacia arriba durante unos 30 a 45 minutos. Luego inserte un palito de paleta en el centro y continúe congelando hasta que estén completamente sólidas."],[]))
X.append(r(9827404,"Cena de espárragos en una sola bandeja","Esta cena de espárragos en una sola bandeja es una comida rápida, fácil y sabrosa, perfecta para las noches ocupadas entre semana.","4 porciones","1 porción",
["1 manojo de espárragos (sin los extremos y cortados en tiras de 2 pulgadas)","2 zanahorias (peladas y cortadas en tiras delgadas de 2 pulgadas)","1 cebolla amarilla (rebanada)","1.5 tazas de garbanzos (cocidos o enlatados)","1 taza de arroz integral o quinoa (o el grano de su elección)","1/4 de taza de jugo de limón (aprox. 1 limón)","1/4 de taza de caldo de verduras","1 cucharada de semillas de ajonjolí","1 cucharadita de ajo en polvo","1 cucharadita de orégano seco","sal y pimienta (al gusto)"],
["Precaliente el horno a 425° F/218° C en hornear con convección, o en asar si tiene esa función, y forre una bandeja grande para hornear con papel pergamino.","Combine todos los ingredientes de la marinada en un tazón pequeño. Luego agregue las verduras preparadas y los garbanzos a un tazón grande y mézclelos con la marinada. Acomode las verduras en una sola capa sobre la bandeja y ase aproximadamente de 20 a 25 minutos, hasta que estén doradas.","Mientras tanto, prepare el grano de su elección. Cocine el arroz, la quinoa o el grano de su elección en la estufa o en una arrocera según las instrucciones del paquete. (NOTA: Use caldo en lugar de agua para cocinar los granos y darles más sabor.)","Sirva los granos cocidos en tazones con las verduras y los garbanzos encima."],[],[]))
X.append(r(9829268,"Pastel de pastor de lentejas [sin aceite]","Este pastel de pastor de lentejas es más ligero, con ingredientes nutritivos, y aun así increíblemente apetitoso: un platillo saludable que sabe a comida reconfortante.","6 porciones","1 porción",
G("Puré de papa",["3 libras de papas Yukon Gold peladas y en cuartos","½ cucharadita de sal marina o al gusto","½ taza de leche de soya o la leche de su elección","¼ de cucharadita de ajo en polvo (opcional)"])+
G("Relleno",["3 tazas de lentejas verdes o pardinas cocidas o enlatadas (aprox. 1 taza crudas)","3 tazas de verduras mixtas congeladas","2 cucharadas de tamari o salsa de soya (si no evita el gluten)","⅓ de taza de salsa de tomate o puré de tomate","1 cucharadita de ajo en polvo","1 cucharadita de cebolla en polvo","1 cucharadita de comino","1 cucharadita de pimentón ahumado o dulce","sal y pimienta al gusto"]),
["Precaliente el horno a 425 grados F.","Coloque las papas en una olla grande con agua (apenas cubriéndolas) y lleve a hervor, cocinando hasta que estén tiernas al pincharlas con un tenedor, aprox. 10 minutos. Escurra y devuelva a la olla, agregue la leche, la sal y el ajo en polvo si lo usa, y haga puré con un machacador de papas. Agregue más leche si es necesario y reserve.","Mientras tanto, agregue las lentejas cocidas o enlatadas y todos los demás ingredientes del relleno al fondo de un molde para hornear de 9\"x13\" (o similar). Mezcle bien.","Cubra con el puré de papa y extiéndalo de manera uniforme por encima. Luego use un tenedor para hacer un patrón entrecruzado en la superficie. Cubra el molde con papel pergamino y luego con papel aluminio.","Hornee durante 20 minutos, luego retire el aluminio y el papel y hornee otros 10 minutos sin cubrir. Saque del horno y deje enfriar unos minutos antes de rebanar y servir."],
["Pese las papas para obtener mejores resultados. Como las papas varían mucho de tamaño, pesarlas será lo más exacto. Si no tiene una báscula de cocina y tiene que calcularlo a ojo, use aprox. 10 papas Yukon Gold de tamaño promedio. No machaque demasiado las papas, solo hasta que estén suaves, y luego extiéndalas sobre la mezcla de lentejas y verduras. Machacar demasiado las papas puede hacer que pasen de suaves y esponjosas a gomosas. Una vez preparada la mezcla de lentejas y verduras, pruebe y agregue más tamari, sal, pimienta u otro condimento, si es necesario. Las sobras se conservan refrigeradas de 3 a 4 días, aunque al recalentarlas las papas pueden resecarse un poco. Agregue un chorrito de leche encima de las papas antes de recalentar. O caliéntelo como un pastel de pastor deconstruido con un poco de caldo o leche y mezcle todo para rehumedecerlo. Puede congelar una bandeja completa sin cocinar y cocinarla directamente congelada, agregando 20 minutos de tiempo de cocción tapada. O descongélela primero y cocínela como de costumbre."],[]))
X.append(r(9833058,"Avena de plátano preparada de un día para otro [sin lácteos]","La avena de plátano preparada de un día para otro, sencilla, deliciosa y saciante, es la manera perfecta de comenzar su día. Mezcle todo, métalo al refrigerador y el desayuno estará listo por la mañana.","1 porción","1 porción",
["1 plátano maduro machacado","½ taza de avena en hojuelas (sin gluten, si lo prefiere)","⅔ de taza de leche de nuez de la India sin azúcar (o de almendra o la de su elección)","1 cucharada de crema de cacahuate (lisa o con trozos, opcional pero recomendada)","1 cucharadita de jarabe de arce (opcional)","½ cucharadita de canela (opcional)"],
["Machaque el plátano en un tazón con tapa, o macháquelo en un plato y pase a un frasco. Luego agregue todos los demás ingredientes y mezcle bien.","Refrigere durante la noche, o por LO MENOS 4 horas. Cubra con fruta fresca, nueces, semillas o cualquier otra cobertura que desee y disfrute."],
["Asegúrese de usar avena en hojuelas o avena de cocción rápida, NO avena instantánea. Duplique la receta para tener el desayuno listo para los siguientes dos días, o para compartir. Prepárela con anticipación; lo mejor es de un día para otro, pero un mínimo de 4 horas también funciona. Use un plátano muy maduro con muchas manchas marrones en la cáscara. Como la mayor parte del dulzor viene del plátano, asegúrese de elegir uno súper maduro, especialmente si desea omitir el jarabe de arce. Asegúrese de usar avena con certificación sin gluten, si es necesario, ya que la avena suele entrar en contacto con otros productos que contienen gluten. La información nutricional no incluye los ingredientes opcionales."],[]))
X.append(r(9834844,"Bowl Buda mexicano sin aceite","Un bowl Buda mexicano increíblemente delicioso, nutritivo y fácil de hacer.","2 bowls","1 porción",
["1 taza de arroz integral cocido","1 taza de frijoles negros cocidos o enlatados","¼ de cucharadita de ajo en polvo","¼ de cucharadita de cebolla en polvo","1 cucharadita de pimentón ahumado","1 cucharadita de comino","1 cucharadita de chile en polvo","⅛ de cucharadita de sal marina o al gusto","¼ de taza de elote","1 aguacate partido por la mitad",
("Para la ensalada","2 jitomates roma en cubos"),("Para la ensalada","¼ de taza de cebolla morada finamente picada"),("Para la ensalada","½ taza de cilantro fresco picado"),("Para la ensalada","2 cucharaditas de vinagre de vino blanco"),("Para la ensalada","2 cucharaditas de jugo de limón verde"),("Para la ensalada","sal y pimienta al gusto")],
["Agregue los frijoles negros, todos los condimentos y 1/4 de taza de agua a una sartén grande. Mezcle bien y caliente a fuego medio durante unos 5 a 6 minutos para calentar los frijoles y que absorban el condimento y casi toda el agua.","Mientras tanto, combine todos los ingredientes de la ensalada en un tazón y mezcle bien. Reserve.","Divida los componentes entre sus dos bowls y decore con más cilantro y gajos de limón si lo desea."],
["Si no quiere cilantro: Pruébelo con perejil fresco, eneldo u otra hierba que le guste.","Cambie el arroz integral por arroz salvaje, quinoa, cebada, farro u otro grano que tenga disponible.","Para menos calorías, use arroz de coliflor en lugar de arroz integral.","Si no quiere elote, simplemente omítalo o agregue más ensalada de jitomate u otra verdura.","Cambie los frijoles negros por lentejas pardas o garbanzos si lo prefiere."],[]))
X.append(r(9839357,"Cecina vegana de rizos de soya","¡Cecina de rizos de soya masticable, ahumada y adictiva!","4 porciones","1 porción",
["8 onzas de rizos de soya (1 bolsa de rizos de soya Butler's)","½ taza de caldo de verduras bajo en sodio","¼ de taza de salsa de soya baja en sodio (o tamari si es sin gluten)","2 cucharadas de jarabe de arce","2 cucharadas de salsa picante (a mí me gusta la Frank's)","1 cucharada de humo líquido","3 cucharaditas de pimentón ahumado","3 cucharaditas de cebolla en polvo","3 cucharaditas de ajo en polvo","½ cucharadita de pimienta de cayena (opcional)","sal y pimienta al gusto"],
["Agregue los rizos de soya a un tazón grande y cubra con agua. Reserve y deje remojar durante 10 minutos para rehidratarlos. Luego precaliente el horno a 300° F/149° C y forre una bandeja grande para hornear con papel pergamino.","Mientras tanto, combine todos los ingredientes de la marinada (todo excepto los rizos de soya) en otro tazón grande y revuelva hasta integrar.","Escurra los rizos de soya y tómelos un puñado a la vez, exprima el exceso de humedad sobre el fregadero y páselos al tazón con la marinada. Una vez que todos los rizos estén en el tazón con la salsa, revuelva para cubrir cada pieza de manera uniforme. Deje que los rizos absorban toda la salsa, dejándolos reposar un par de minutos si es necesario, y luego revuelva de nuevo.","Acomode los rizos de soya marinados en una sola capa sobre la bandeja y hornee durante 30 minutos. Luego voltee las piezas y continúe horneando en intervalos de 10 minutos hasta alcanzar el punto de cocción deseado. Los míos quedaron perfectos después de 60 minutos en total. (Las piezas más pequeñas pueden estar listas antes.)","Saque del horno y deje reposar unos minutos antes de disfrutar."],
["Exprima el exceso de humedad después de remojar los rizos de soya. Si no lo hace, absorberán menos de la deliciosa marinada y la cecina de rizos de soya tendrá menos sabor.","No cocine de más la cecina o quedará demasiado crujiente y seca. El punto ideal es un interior masticable con un exterior firme, así que revísela con frecuencia hacia el final del horneado.","Las piezas más pequeñas pueden estar listas antes, así que retire las piezas de la bandeja según sea necesario para que ninguna se cueza de más.","Guarde las sobras en un recipiente o frasco a temperatura ambiente hasta por 5 días."],[]))
X.append(r(9843388,"Ensalada de tofu crujiente","Una deliciosa ensalada de tofu crujiente, llena de sabor, con un aderezo cremoso y con hierbas a base de tahini.","6 porciones","1 porción",
["1 bloque de 340 gramos (12 onzas) de tofu extra firme (sin transgénicos si es posible)","2 cucharadas de tamari (o salsa de soya)","1 cucharadita de ajo en polvo","1 cucharadita de cebolla en polvo","2 cucharadas de fécula de maíz (o harina de arroz integral)","6 tazas de lechuga romana (aprox. 2 corazones de lechuga romana)","1 taza de jitomates cherry (partidos por la mitad)","1 taza de zanahoria rallada","1 pimiento amarillo (rebanado finamente)","1 cebollín (rebanado finamente)","1/4 de taza de tahini","1/4 de taza de vinagre de manzana","1 cucharada de jarabe de arce","1 cucharadita de mostaza amarilla","2 cucharadas de albahaca fresca (finamente picada)","sal y pimienta (al gusto)","1 a 2 cucharadas de agua (si es necesario para aligerar el aderezo)"],
[("Prense el tofu","Corte el tofu en cubos de media pulgada. Luego coloque unas toallas de papel o un paño de cocina limpio sobre una tabla para cortar y ponga encima los cubos de tofu en una sola capa. Ahora agregue más toallas de papel sobre los cubos y coloque encima otra tabla para cortar, un plato plano o una bandeja para hornear. Por último, ponga algo muy pesado encima, como una sartén de hierro fundido o un libro pesado. Prense así durante 15 minutos mientras prepara los demás ingredientes."),
("Hornee el tofu","Precaliente el horno a 425° F/218° C en hornear con convección y forre una bandeja para hornear con papel pergamino."),
("Hornee el tofu","Combine el tamari, el ajo en polvo, la cebolla en polvo y la fécula de maíz en un tazón mediano. Mezcle bien. Luego agregue los cubos de tofu prensados y revuelva suavemente para cubrirlos de manera uniforme."),
("Hornee el tofu","Acomode los cubos marinados en una sola capa, con espacio entre cada pieza, sobre la bandeja. Hornee durante 15 minutos, luego voltee y hornee de 5 a 10 minutos más, o hasta alcanzar la crujiencia deseada."),
("Para la ensalada y el aderezo","Mientras se hornea el tofu, agregue todos los ingredientes de la ensalada a un tazón grande, o acomódelos en capas en una charola grande para servir."),
("Para la ensalada y el aderezo","Luego combine todos los ingredientes del aderezo en un tazón pequeño y reserve."),
("Para la ensalada y el aderezo","Una vez horneado el tofu, agréguelo a la ensalada y mézclelo con el aderezo, o sirva el aderezo aparte para conservar la crujiencia del tofu hasta el momento de disfrutarlo.")],[],[]))
X.append(r(9847094,"Crema de pistache casera","¿Le encantan los pistaches? TIENE que hacer crema de pistache. Es suave, rica, llena de sabor y absolutamente ¡FANTÁSTICA!","24 porciones de 1 cucharada (rinde aprox. 1.5 tazas)","1 porción",
["3 tazas de pistaches crudos sin cáscara"],
["Precaliente el horno a 350° F/176° C y acomode los pistaches en una bandeja para hornear. Hornee de 5 a 6 minutos para calentarlos sin dorarlos y luego sáquelos del horno.","Pase los pistaches al tazón del procesador de alimentos o licuadora y comience a procesar. Pasarán de trozos a harina, luego empezarán a formar grumos y, finalmente, tendrá una crema de pistache suave y cremosa. Asegúrese de hacer pausas y raspar los lados, según sea necesario, y deje descansar su aparato entre cada proceso para que no se sobrecaliente. Todo el proceso (con pausas) puede tardar hasta 15 minutos, según su procesador."],[],[]))
X.append(r(9847862,"Hotcakes rosados de betabel [veganos y sin gluten]","¡Hermosos hotcakes rosados de betabel, divertidos, deliciosos y nutritivos! Además, ¡son veganos, sin gluten y sin aceite!","10 hotcakes","1 porción",
["1 betabel mediano asado","1.25 tazas de avena en hojuelas (sin gluten, si lo prefiere)","2 cucharadas de linaza molida","1 cucharadita de canela","2 cucharaditas de polvo para hornear","1 cucharadita de extracto puro de vainilla","1.5 tazas de leche de soya sin azúcar o la leche vegetal de su elección",("Coberturas opcionales","fruta fresca, jarabe de arce, coco rallado, chispas de chocolate, nueces")],
["Precaliente el horno a 425° F/218° C en hornear con convección. Corte la parte superior e inferior de los tallos del betabel y luego pártalo por la mitad. Colóquelo con el lado cortado hacia abajo en un paquete de papel aluminio sobre una bandeja para hornear. Doble los lados del aluminio hacia arriba para mantener los jugos dentro del paquete y evitar que se ensucie. Luego hornee el betabel hasta que esté tierno al pincharlo con un tenedor, aprox. de 30 a 45 minutos. (El tiempo de horneado variará según el tamaño del betabel y qué tan fresco esté.)","Sáquelo del horno y deje enfriar un poco. Luego precaliente el comal o plancha a fuego medio y pele las mitades de betabel. La piel se desprenderá fácilmente después de asarlo.","Agregue el betabel con todos los demás ingredientes a la licuadora y procese hasta obtener una mezcla suave. Luego vierta la masa de la licuadora sobre el comal caliente, haciendo hotcakes de unas 4 pulgadas de diámetro. Cocine de 3 a 4 minutos, hasta que tengan burbujas arriba y los bordes se vean firmes. Luego voltee y cocine de 3 a 4 minutos más hasta que estén cocidos por completo. ¡Disfrute!"],
["Deje la cáscara al asar el betabel. Quitar la cáscara es tedioso y ensucia mucho cuando el betabel está crudo, y se pela con mucha facilidad una vez asado.","Si el tiempo lo permite, ase en lugar de hervir. El resultado son hotcakes de betabel naturalmente más dulces. (¡Eso significa que necesitará menos jarabe o ninguno!)","Si cocina sus hotcakes rosados por tandas, la masa se espesará mientras reposa en la licuadora. Si es necesario, agregue otras 1 a 2 cucharadas de leche y vuelva a licuar unos segundos antes de cocinar la siguiente tanda.","Las sobras se conservan refrigeradas hasta por 3 días o congeladas en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9848739,"Bowl Buda asiático de garbanzos","¡Un bowl Buda asiático que está absolutamente LLENO de sabor!","4 porciones","1 porción",
G("Para el bowl",["4 tazas de camote en cubos de media pulgada (aprox. 2 camotes medianos)","3 tazas de garbanzos cocidos o enlatados (aprox. 2 latas de 15 onzas)","¼ de taza de caldo de verduras","1 diente de ajo picado","⅛-1/4 de cucharadita de hojuelas de chile rojo","4 a 5 manojos de bok choy baby, sin la base del tallo y con las hojas separadas"])+
G("Para la salsa de cacahuate",["⅓ de taza de crema de cacahuate lisa","2 cucharadas de vinagre de arroz","2 cucharadas de jugo de limón verde (aprox. 1 limón mediano)","2 cucharadas de salsa de soya baja en sodio (o tamari si es sin gluten)","1 diente de ajo picado","1 cucharadita de jengibre recién rallado (aprox. un trozo de 1 pulgada)","¼ de cucharadita de hojuelas de chile rojo o al gusto","¼ de taza de agua"])+
G("Opcional para servir",["arroz integral, fideos o quinoa","cebollín, cebollines, cebolletas, semillas de ajonjolí"]),
["Precaliente el horno a 425° F/218° C en asar con convección (u hornear) y forre una bandeja para hornear con papel pergamino. Acomode los cubos de camote en una sola capa, espolvoree con sal y pimienta y áselos durante 20 minutos, luego voltee y ase de 10 a 15 minutos más. Reserve.","Mientras tanto, combine todos los ingredientes de la salsa de cacahuate en un tazón mediano y reserve.","Agregue el caldo de verduras, 1 diente de ajo picado y las hojuelas de chile rojo a una sartén grande y saltee de 30 a 60 segundos. Luego agregue el bok choy y saltee por ambos lados de 1 a 2 minutos, hasta que se marchite y se cubra con el ajo y las especias. Pase a un plato y reserve.","En la misma sartén, agregue la salsa de cacahuate y los garbanzos, cocine a fuego lento de 2 a 3 minutos y luego apague el fuego.","Acomode los garbanzos con salsa, el bok choy y los camotes en bowls y sirva con arroz cocido o fideos si lo desea."],[],[]))
save(4,X)
