import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes3')
from h import *
X=[]
def G(g,l): return [(g,x) for x in l]
X.append(r(9882145,"Hot dogs veganos [salchichas de seitán]","¡Las salchichas de seitán son sabrosas, fáciles de hacer y más saludables que las compradas! ¡Perfectas para los asados!","8 salchichas de seitán","1 porción",
G("Ingredientes húmedos",["1 taza de frijoles cannellini blancos, escurridos, enjuagados y secados con toques","1 taza de caldo de verduras bajo en sodio","3 cucharadas de salsa de soya","2 cucharadas de pasta de tomate","1 cucharada de jarabe de arce","1 cucharada de vinagre de manzana"])+
G("Ingredientes secos",["270 gramos de gluten de trigo vital (aprox. 2 tazas)","3 cucharaditas de cebolla en polvo","2.5 cucharaditas de ajo en polvo","2 cucharaditas de pimentón ahumado o dulce","1 cucharadita de sal marina","½ cucharadita de condimento para aves","½ cucharadita de cilantro molido","¼ de cucharadita de cúrcuma","¼ de cucharadita de nuez moscada","¼ de cucharadita de pimienta negra"])+
G("Coberturas opcionales",["panes para hot dog","mostaza, cátsup, relish, jalapeño, chile, ensalada de col"]),
["Precaliente el horno a 350 grados F (si usa el método del horno) y corte 8 trozos de papel aluminio (y papel pergamino si prefiere que el aluminio no toque la comida) y reserve.","Agregue los frijoles blancos a un tazón y macháquelos suavemente con un tenedor grande o un machacador de papas. (No necesitan estar completamente machacados; algunos trozos más grandes están bien.) Luego agregue todos los demás ingredientes HÚMEDOS al mismo tazón y mezcle bien.","Ahora agregue TODOS los ingredientes secos y empiece a mezclar hasta que se integren casi por completo en una bola de masa. Luego pase a una tabla para cortar o a una superficie de trabajo limpia para amasar durante aprox. 1 minuto, hasta obtener una mezcla bien integrada, pero sin amasar de más.","Divida en 8 piezas y enrolle cada pieza en forma de cilindro para hacer sus hot dogs veganos. (No se preocupe si queda irregular; se alisará al cocinarse.) Luego envuelva cada salchicha de seitán con el papel pergamino (si lo usa) y el papel aluminio y retuerza los extremos para asegurarlas dentro. (Vea las fotos del proceso arriba para una referencia visual.) Elija un método de cocción a continuación.",
("Instrucciones para cocinar al vapor","Lleve a hervor una olla grande con un par de pulgadas de agua y coloque dentro su canasta para vapor. Asegúrese de que la canasta no toque el agua. Cuando hierva, reduzca el fuego para mantener un hervor bajo/fuego lento y coloque dentro las salchichas de seitán. Tape con una tapa y cocine al vapor de 45 a 55 minutos, volteándolas a la mitad del tiempo. Revise el agua de vez en cuando y agregue agua caliente SI es necesario. Retire los hot dogs de la canasta y deje enfriar 5 minutos antes de quitar el aluminio."),
("Instrucciones para hornear","Coloque las salchichas de seitán envueltas en una bandeja y hornee durante 45 minutos, volteándolas a la mitad del tiempo. Saque del horno y deje enfriar unos 5 minutos antes de quitar el aluminio."),
("Instrucciones para Instant Pot","Agregue 1.5 tazas de agua al fondo de la Instant Pot. Luego coloque la rejilla dentro de la olla. Acomode las salchichas de seitán envueltas sobre la rejilla, apilándolas según sea necesario. Luego cierre la tapa y asegúrese de que la válvula esté en la posición de sellado. Cocine al vapor durante 45 minutos y deje que la olla libere la presión de forma natural hasta que baje el pasador. Retire cuando sea seguro hacerlo."),
("Opcional: a la parrilla","Puede disfrutarlas de inmediato una vez horneadas o cocidas al vapor. O bien, puede asar las salchichas de seitán a la parrilla para obtener esas hermosas marcas. Barnice los hot dogs veganos con aceite (si lo desea) y espolvoree un poco más de sal y pimienta. Luego ase a la parrilla de 1 a 2 minutos para realzar los sabores."),
("Opcional: a la parrilla","Sirva con panes para hot dog y todas sus coberturas favoritas. ¡Disfrute!")],
["Para mayor exactitud, pese el gluten de trigo vital. Si no tiene una báscula de cocina, use 2 tazas. Asegúrese de mezclar bien la masa para obtener un sabor uniforme y la mejor textura, pero no amase de más. Amasar de 1 a 2 minutos es perfecto. No se preocupe demasiado por darles a los hot dogs una forma perfecta. Estarán irregulares antes de cocinarse, pero quedan lisos y bonitos al cocinarse. Si no le gusta que el papel aluminio toque su comida, use papel pergamino entre las salchichas de seitán y la capa de papel aluminio. Para salchichas veganas picantes, agregue 1 cucharadita de hojuelas de chile a la mezcla. Para preparar con anticipación: Prepare y cocine por completo las salchichas 1 a 2 días antes con el método de su elección (al vapor u horneadas) y luego áselas a la parrilla justo antes de servir. Las sobras se conservan refrigeradas hasta por 5 días o congeladas hasta por 3 meses. ¿Cómo sé si están cocidas? Despegue suavemente el aluminio; los hot dogs deben verse lisos. Puede presionarlos con el dedo o con unas pinzas para probar su firmeza. Deben sentirse firmes, pero ceder un poco a la presión. Se firmarán más al enfriarse."],[]))
X.append(r(9882257,"Magdalenas de plátano y garbanzos","Húmedas, nutritivas y llenas de proteína: estas magdalenas de plátano y garbanzos son una variación deliciosamente saludable de un clásico favorito.","12 magdalenas","1 porción",
["2 tazas (lata de 18 onzas) de garbanzos, escurridos y enjuagados","3 plátanos medianos (1 taza machacados)","½ taza de tahini o crema de almendra","¼ de taza de azúcar de coco sin refinar","1.5 tazas de avena en hojuelas (sin gluten, si lo prefiere)","1 cucharada de extracto puro de vainilla","2 cucharaditas de polvo para hornear",("Coberturas opcionales","rebanadas de plátano, chispas de chocolate, arándanos azules, nueces")],
["Precaliente el horno a 350° F/176° C y use un molde para magdalenas engrasado o forre el molde con capacillos para magdalenas.","Machaque el plátano para asegurarse de tener 1 taza de plátano machacado. Luego agregue todos los ingredientes, excepto las coberturas opcionales, al procesador de alimentos. Procese la mezcla hasta que esté casi suave.","Divida la masa entre los 12 moldes y cubra algunas o todas las magdalenas con coberturas si lo desea.","Hornee las magdalenas de garbanzos de 20 a 22 minutos o hasta que un palillo insertado en el centro de una magdalena salga casi limpio. Luego sáquelas del horno y déjelas enfriar de 10 a 15 minutos antes de pasarlas a una rejilla."],
["Use plátanos muy maduros. Cuanto más maduros estén los plátanos, más sabor, dulzor y humedad aportarán a sus magdalenas de plátano y garbanzos. Los plátanos con cáscara marrón funcionan mejor.","Use polvo para hornear fresco y ACTIVO. El polvo para hornear que lleva abierto en la despensa 6 meses o más puede perder su efectividad.","Mida el plátano machacado para asegurarse de usar una taza. Los plátanos varían mucho de tamaño. Dos plátanos grandes o tres medianos me funcionan.","Deje enfriar las magdalenas de 10 a 15 minutos antes de sacarlas del molde para ayudar a que se asienten y evitar que se rompan.","Las magdalenas sobrantes se conservan a temperatura ambiente de 1 a 2 días, refrigeradas hasta por 5 días o congeladas hasta por 3 meses."],[]))
X.append(r(9882910,"Salteado fácil de rizos de soya [salteado vegano]","Un sabroso salteado de rizos de soya, sencillo de preparar y listo en 30 minutos o menos.","4 porciones","1 porción",
["4 onzas de rizos de soya (aprox. media bolsa de rizos de soya Butler's)","6 a 8 tazas de verduras congeladas para salteado",
("Para la marinada","2 tazas de caldo de verduras bajo en sodio"),("Para la marinada","⅓ de taza de salsa de soya baja en sodio (o tamari si es sin gluten)"),("Para la marinada","¼ de taza de vinagre de arroz"),("Para la marinada","¼ de taza de agua fresca"),("Para la marinada","2 cucharadas de jarabe de arce"),("Para la marinada","2 cucharaditas de ajo en polvo"),("Para la marinada","1 cucharadita de jengibre en polvo"),("Para la marinada","2 cucharadas de fécula de maíz o harina de tapioca"),
("Para servir (opcional)","fideos de arroz, arroz integral, quinoa, fideos de verduras, arroz de coliflor"),("Para servir (opcional)","semillas de ajonjolí, cebollín y/o hojuelas de chile rojo para decorar")],
["Combine todos los ingredientes de la marinada, excepto la fécula de maíz, en un tazón grande. Luego agregue los rizos de soya secos al tazón, revuélvalos y déjelos remojar durante 10 minutos.","Precaliente una sartén de hierro fundido, o similar, a fuego medio-alto. Luego saque los rizos de soya marinados del tazón (NO ESCURRA: RESERVE LA SALSA) y colóquelos en la sartén para freírlos hasta que estén dorados, aprox. de 4 a 5 minutos, revolviendo con frecuencia.","Luego agregue las verduras, revolviendo ocasionalmente durante otros 4 a 5 minutos.","Mientras tanto, incorpore la fécula de maíz al tazón de marinada reservada. Luego vierta la salsa en la sartén con los rizos de soya y las verduras. Deje que hierva a fuego lento y espese de 2 a 3 minutos antes de servir."],
["Use caldo y salsa de soya bajos en sodio para la marinada para evitar que el platillo quede demasiado salado. Use mitad agua y mitad caldo si no tiene caldo bajo en sodio. (Siempre puede agregar sal después si es necesario.)","¡No cocine de más las verduras! Saben mejor tiernas pero crujientes, para obtener la mejor textura.","Guarde las sobras en el refrigerador de 3 a 4 días o congélelas en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9889051,"Hotcakes veganos saludables de arándanos azules","Los hotcakes veganos de arándanos azules son esponjosos, gruesos, sin azúcar y absolutamente deliciosos.","8 hotcakes","1 hotcake",
["1.5 tazas de leche de soya","1.5 cucharaditas de vinagre de manzana","1 taza de avena en hojuelas (sin gluten, si lo prefiere)","2 cucharadas de semillas de chía","2 cucharadas de semillas de cáñamo peladas","⅓ de taza de harina de garbanzo (también conocida como harina de chickpea)","2 cucharaditas de polvo para hornear","1 taza de arándanos azules frescos"],
["Caliente el comal o plancha antiadherente a fuego medio. Luego agregue la leche de soya y el vinagre de manzana a un tazón pequeño y reserve para que se corte.","Mientras tanto, agregue la avena, las semillas de cáñamo y las semillas de chía a una licuadora y procese hasta que tenga una consistencia parecida a la harina. (No se preocupe si quedan algunos trozos más grandes.) Pase a un tazón grande para mezclar y agregue la harina de garbanzo y el polvo para hornear y bata para integrar.","Para este momento la leche ya debería estar cortada, así que viértala en el tazón de harina y mezcle hasta integrar sin mezclar de más. Incorpore con movimientos envolventes los arándanos azules.","Sirva la masa con un cucharón sobre el comal precalentado, haciendo hotcakes de aproximadamente 4 pulgadas de diámetro. Puede presionar suavemente los hotcakes para ayudar a que se extiendan un poco, ya que la masa no será muy líquida. Sin embargo, no los extienda demasiado, ya que saben mejor un poco gruesos y esponjosos.","Cocine de 4 a 5 minutos hasta que estén dorados, voltee y cocine otros 3 a 4 minutos más, hasta que estén cocidos por completo.","Sirva con más arándanos azules frescos, frambuesas, coco rallado, chispas de chocolate, nueces o jarabe de arce."],
["Asegúrese de que su polvo para hornear esté activo. Si lleva abierto en la despensa más de 6 meses, puede empezar a perder su efectividad.","La avena y las semillas no necesitan estar perfectamente molidas. Si quedan algunos trozos en hojuelas que no se muelen, sus hotcakes saldrán perfectos de todos modos.","No es necesario mezclar demasiado la masa de los hotcakes. Si quedan algunos grumos, no pasa nada. Solo mezcle hasta que se integre y no queden grumos de harina.","Use fuego medio para una cocción uniforme. El fuego alto cocinará demasiado rápido el exterior, dejando el centro crudo. ¡Pero asegúrese de que esté precalentado para que los hotcakes no se peguen!","Las sobras se conservan refrigeradas de 3 a 4 días o congeladas en bolsas con cierre o un recipiente apto para congelador hasta por 3 meses. Recaliente en el tostador para desayunos rápidos y fáciles."],[]))
X.append(r(9890162,"Tacos de coliflor y garbanzos","¡Estos tacos de coliflor y garbanzos son vibrantes, reconfortantes, frescos y sabrosos!","4 porciones","1 porción",
["4 tazas de floretes de coliflor (aprox. 1 coliflor pequeña)","1.5 tazas de garbanzos (aprox. 1 lata de 15 onzas, escurridos y enjuagados)","4 cucharadas de salsa de soya","1 cucharada de agua filtrada","1 cucharada de chile en polvo","1 cucharadita de pimentón ahumado","1 cucharadita de ajo en polvo","1 cucharadita de cebolla en polvo","1 cucharadita de comino","sal y pimienta (al gusto)","8 tortillas para taco (tacos duros)","2 aguacates maduros","1/4 de taza de nueces de la India crudas","2 cucharadas de jugo de limón verde (aprox. 1 limón grande)","2 cucharadas de vinagre de manzana","1/2 cucharadita de sal marina","1/3 de taza de agua filtrada (más 1 a 2 cucharadas para una consistencia más líquida)"],
["Precaliente el horno a 425° F/218° C y forre una bandeja para hornear con papel pergamino.","Combine la salsa de soya, el agua y todos los condimentos en un tazón mediano. Luego agregue los floretes de coliflor y los garbanzos. Mezcle bien para cubrir las piezas de manera uniforme.","Ase durante unos 20 a 25 minutos hasta que los bordes estén dorados y un poco crujientes.","Mientras se asa, prepare su crema de aguacate y limón. Agregue todos los ingredientes a la licuadora y procese hasta obtener una mezcla suave, comenzando con 1/3 de taza de agua. Agregue más agua si desea una consistencia más líquida.","Arme sus tacos con sus tortillas o tacos favoritos y agregue una porción generosa de crema de aguacate encima."],[],[]))
X.append(r(9890977,"Galletas de mantequilla sin lácteos (shortbread)","Las galletas de mantequilla sin lácteos son un antojo divertido para que todos disfruten. ¡Son perfectamente dulces, desmenuzables, \"mantecosas\" y deliciosas!","26 galletas","1 galleta",
["1 taza de margarina vegana o mantequilla suavizada","½ taza de azúcar glass","1 cucharadita de extracto puro de vainilla (opcional)","1 ¾ tazas de harina multiusos sin blanquear",
("Glaseado (opcional)","1 taza de azúcar glass"),("Glaseado (opcional)","2 a 3 cucharadas de agua"),("Glaseado (opcional)","1 gota de colorante alimentario azul (asegúrese de usar una marca vegana si lo prefiere, u omítalo y deje el glaseado blanco)"),("Glaseado (opcional)","grageas de colores de su elección (asegúrese de usar una marca vegana si lo prefiere)")],
["En un tazón grande, bata la margarina con una batidora de mano de 1 a 2 minutos, hasta que esté esponjosa. Luego agregue el azúcar y la vainilla y siga mezclando hasta integrar.","Agregue la harina en dos partes y mezcle hasta integrar. Tendrá una mezcla que parece no mantenerse unida, pero lo hará. Use las manos para darle a la masa la forma de una bola aplanada en el fondo del tazón. Cubra con plástico adherente y refrigere de 2 a 3 horas o congele de 15 a 20 minutos.","Mientras tanto, forre una bandeja grande para hornear con papel pergamino y precaliente el horno a 350 grados F.","Coloque una hoja de papel pergamino sobre la encimera y la masa fría encima. Aplane y extienda la masa con un rodillo engrasado hasta aprox. 1/4\" de grosor. Luego use cortadores de galletas para hacer las galletas. Pase con cuidado las galletas a la bandeja. Luego vuelva a extender la masa sobrante, aplánela de nuevo y siga haciendo galletas. Repita hasta usar toda la masa.","Hornee de 15 a 18 minutos, o hasta que los bordes estén ligeramente dorados. Saque del horno y pase a una rejilla. Deje enfriar por completo antes de glasear.",
("Glaseado opcional","Combine el azúcar glass con 2 cucharadas de agua en un tazón pequeño y mezcle bien. Si el glaseado está demasiado espeso, agregue una cucharada más y mezcle de nuevo. Luego agregue una gota de colorante alimentario, si lo usa, y mezcle para integrar."),
("Glaseado opcional","Use una brocha de silicona para glasear las galletas y luego espolvoréelas con las grageas. Asegúrese de agregar las grageas inmediatamente después de glasear, mientras el glaseado esté húmedo, para que se adhieran. Reserve y deje secar.")],
["Use cortadores de galletas con menos detalles para mayor facilidad. Los cortadores con más ranuras o patrones intrincados hacen más difícil mantener las galletas unidas al pasarlas a la bandeja. Las formas sencillas como círculos, corazones o estrellas tienen menos probabilidad de romperse. Engrase el rodillo para que no se pegue a la masa. Esto hará galletas más lisas, pero no busque la perfección. El glaseado y las grageas cubrirán la parte superior de las galletas de todos modos. Si el rodillo sigue pegándose a la masa, coloque una hoja de papel pergamino encima y extienda sobre el pergamino. Tenga cuidado al pasar las galletas de mantequilla a la bandeja. La masa es suave y las galletas pueden romperse si usa demasiada fuerza. A mí me gusta usar un tenedor grande o un cuchillo para pay para raspar primero por debajo de la galleta (para \"despegarla\" del pergamino), y luego levantarla y pasarla lentamente. ¡Pero si alguna galleta se rompe, no se preocupe! Puede presionar suavemente la pieza para unirla de nuevo con los dedos engrasados. Si no tiene arreglo, simplemente agréguela a la masa sobrante para volver a extenderla en la siguiente ronda. El grosor de la masa determinará el tiempo de cocción. Si extiende la masa más delgada, las galletas se hornearán más rápido, pero si la extiende más gruesa, necesitarán un poco más de tiempo en el horno. Empiece a revisarlas alrededor de los 10 minutos para asegurarse de que no se quemen. Deje que las galletas de mantequilla se enfríen por completo antes de glasearlas. Si las galletas están demasiado calientes, el glaseado goteará y escurrirá y las grageas se derretirán. Una vez glaseadas, espolvoree las grageas de inmediato, antes de que el glaseado cuaje, o no se adherirán. La información nutricional no incluye el glaseado opcional. Las galletas se conservan refrigeradas hasta por 1 semana o congeladas en un recipiente hermético apto para congelador hasta por 2 meses. Separe las capas de galletas con papel pergamino antes de congelar."],[]))
X.append(r(9892214,"Elote en crema vegano [sin aceite]","Este elote en crema vegano tiene un sabor increíble con un esfuerzo mínimo.","8 porciones","1 porción",
["4 tazas de granos de elote congelados (no es necesario descongelar)","400 ml de leche de coco sin azúcar Thai Kitchen (regular para mejores resultados*) (aprox. 1 ¾ de taza)","½ taza de leche de soya sin azúcar o leche vegetal sin azúcar de su elección","½ cucharadita de sal marina o al gusto","1 cucharadita de ajo en polvo","1 cucharadita de cebolla en polvo","2 cucharadas de jarabe de arce (opcional, pero recomendado)","½ cucharadita de hojuelas de chile rojo (opcional, pero recomendado)"],
["Agregue todos los ingredientes a una olla o sartén y mezcle bien. Lleve a un hervor suave a fuego medio, revolviendo ocasionalmente. Continúe cocinando a fuego lento de 8 a 10 minutos hasta que se reduzca aproximadamente a la mitad.","Luego pase 1 taza de la mezcla de elote a una licuadora y procese hasta obtener una mezcla suave. Devuelva el elote hecho puré a la sartén y revuelva para integrar. Sirva caliente."],
["Para menos calorías y grasa, use leche de coco light enlatada en lugar de regular, pero tenga en cuenta que esto hará el platillo un poco menos rico.","Para endulzar, prefiero el jarabe de arce, pero puede usar otros endulzantes líquidos si lo prefiere.","Para que no lleve coco, use otra leche vegetal, como leche de nuez de la India o de soya. De nuevo, tenga en cuenta que esto hará el platillo menos rico.","Para que no lleve soya, use otra leche sin lácteos y sin azúcar de su elección.","Las sobras se conservan refrigeradas hasta por 3 días. Recaliéntelas en la estufa con un chorrito de leche o agua para aflojarlas."],[]))
X.append(r(9897433,"Ensalada vegana de \"pollo\" con yaca asada","Esta apetitosa ensalada vegana de \"pollo\" está llena de sabor intenso, un toque crujiente, dulzura y mucha delicia. Cubierta con un aderezo rico y cremoso, sin aceite.","6 porciones","1 porción",
G("Para la ensalada",["1 lata de 20 onzas de yaca verde joven en salmuera o agua, NO en almíbar, escurrida y enjuagada","1 lata de 15 onzas de garbanzos, escurridos y enjuagados (o 1.5 tazas)","½ taza de trozos de nuez de Castilla o pecanas","½ taza de apio en cubos (aprox. 1 tallo)","½ taza de uvas rojas partidas por la mitad","¼ de taza de cebollín rebanado finamente (aprox. 1 cebollín)"])+
G("Para el aderezo",["¾ de taza de nueces de la India crudas","¾ de taza + 2 cucharadas de agua","2 cucharadas de jugo de limón (aprox. medio limón grande)","1 cucharadita de eneldo seco","½ cucharadita de ajo en polvo","½ cucharadita de sal marina","¼ de cucharadita de pimienta negra"]),
["Precaliente el horno a 400° F/204° C y forre una bandeja grande para hornear con papel pergamino.","Enjuague muy bien la yaca para quitar la salmuera y separe todas las piezas para deshebrarla. Agregue la yaca deshebrada a la bandeja junto con los garbanzos y los trozos de nuez. Hornee durante 15 minutos y saque del horno.","Mientras tanto, agregue todos los ingredientes del aderezo, comenzando con 3/4 de taza de agua, a una licuadora de alta velocidad y procese hasta obtener una mezcla suave y cremosa. Agregue las dos cucharadas de agua restantes si es necesario para aligerar el aderezo y vuelva a licuar.","Coloque la yaca, los garbanzos, las nueces, el apio, las uvas y el cebollín en un tazón para servir y vierta el aderezo encima. Mezcle bien y refrigere durante 1 hora antes de servir."],
["Use únicamente yaca verde joven enlatada en salmuera o agua. No use yaca fresca ni yaca enlatada en almíbar.","Si no tiene una licuadora de alta velocidad, remoje las nueces de la India en agua fría durante la noche, o en agua hirviendo de 15 a 30 minutos, y luego escúrralas. El tiempo de remojo hará que las nueces se hinchen y ablanden, lo que facilita licuarlas.","Esta ensalada sabe muy bien recién hecha, pero sabe mejor si se enfría durante 1 hora o más.","Para que no lleve nueces: Omita las nueces de Castilla o sustitúyalas por pepitas en la ensalada. Para el aderezo, use semillas de girasol crudas en lugar de nueces de la India con resultados similares.","Para un aderezo estilo mayonesa, use mayonesa vegana comprada o mi mayonesa casera de pepitas sin aceite.","Las sobras se conservan refrigeradas en un recipiente sellado de 2 a 3 días."],[]))
X.append(r(9898504,"Sopa de verduras y cebada","¡La sopa casera de verduras y cebada con frijoles es abundante, deliciosa y fácil de hacer!","8 porciones","1 porción",
["1 taza de frijoles navy o alubias blancas (remojados toda la noche o con el método de remojo rápido; vea las notas abajo)","1 cebolla morada","4 zanahorias grandes","2 tazas de chícharos congelados","1 taza de elote congelado","1 taza de cebada perlada integral","10 tazas de caldo de verduras bajo en sodio","1.5 cucharaditas de ajo en polvo","½ cucharadita de orégano seco","2 puñados de espinaca baby","sal y pimienta al gusto"],
["Pele y corte en cuartos la cebolla y pele las zanahorias. Agréguelas a un procesador de alimentos y procese hasta que estén finamente picadas. Si no tiene un procesador de alimentos, puede picarlas finamente a mano. Luego páselas a una olla grande.","Agregue todos los demás ingredientes, excepto la espinaca, a la misma olla y lleve a hervor a fuego alto. Luego baje el fuego a medio-bajo y cocine a fuego lento con la tapa puesta, pero ligeramente ladeada, de 30 a 40 minutos hasta que la cebada y los frijoles estén tiernos.","Apague el fuego e incorpore la espinaca. La espinaca se marchitará rápidamente y luego sirva."],
["Para remojar los frijoles durante la noche, cúbralos con agua fría dos pulgadas por encima de los frijoles para dejar espacio a que crezcan. Escurra cuando esté listo para usarlos. Si no remojó los frijoles durante la noche, hierva agua en una olla o hervidor y cubra los frijoles con el agua hirviendo durante 30 minutos. Luego escurra y use según las indicaciones. Para que la sopa sea sin gluten, puede usar arroz integral en lugar de cebada. Las sobras se conservan refrigeradas de 3 a 4 días o congeladas en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9908880,"Salsa vegana de calabaza para pasta","La deliciosa salsa vegana de calabaza para pasta es perfecta para una comida entre semana súper rápida y fácil, con ingredientes sencillos que dan mucho sabor.","6 porciones","1 porción",
["1.5 tazas de caldo de verduras bajo en sodio","2 tazas de puré de calabaza","½ cucharadita de salvia seca","½ cucharadita de ajo en polvo","1 cucharadita de chile en polvo","½ cucharadita de sal marina","¼ de cucharadita de pimienta de cayena","¼ de cucharadita de jengibre molido","2 cucharadas de polvo de arrurruz o harina multiusos","½ taza de leche de soya o la leche de su elección","450 gramos de pasta de su elección (a mí me gusta el fettuccine)"],
["Combine el caldo de verduras, el puré de calabaza, todos los condimentos y el polvo de arrurruz en una cacerola mediana. Cocine a fuego medio-bajo de 5 a 6 minutos, revolviendo con frecuencia. Luego apague el fuego e incorpore la leche. Reserve y mantenga tapado.","Mientras tanto, lleve a hervor una olla grande con agua generosamente salada y cocine la pasta según las instrucciones del paquete. Escurra y devuelva a la olla. Luego vierta la salsa sobre la pasta y mezcle de inmediato para que la pasta no se pegue. Puede reservar un poco de salsa para decorar cada plato o mezclarla toda.","Sirva decorada con hojuelas de chile y queso parmesano vegano si lo desea."],
["Sale el agua. Agregue suficiente sal al agua hirviendo para obtener la mejor textura y sabor. Aquí tiene una guía práctica para ayudarle a salar el agua perfectamente cada vez. La salsa queda excelente con pasta de trigo, zoodles, arroz integral, pasta de garbanzo o de lentejas. Cocine la pasta de trigo \"al dente\" para obtener la mejor textura. (Al dente significa que la pasta sigue firme una vez cocida, lo que ofrece una textura óptima en cada bocado.) Para que sea sin gluten, use su pasta sin gluten favorita y cocínela según las instrucciones del paquete para una pasta \"al dente\". Guarde por separado la pasta y la salsa sobrantes o la pasta absorberá toda la salsa extra. Si cocina para niños exigentes, omita la pimienta de cayena. Si no puede consumir soya (pero sí nueces), use leche de nuez de la India o de almendra sin azúcar. O pruebe la leche de coco enlatada para una salsa más rica. Use light para menos grasa."],[]))
X.append(r(9909062,"Wraps fáciles de falafel horneado - sin gluten","Los wraps de falafel horneado, en versión más ligera, son tan deliciosos como la versión tradicional frita, pero con menos calorías y grasa.","4 porciones (rinde aprox. 20 a 22 falafel)","1 porción",
["1 taza de garbanzos secos/crudos, remojados durante la noche. (NO use enlatados)","1 taza de cilantro o perejil picado en trozos grandes y poco compactado","1 cebolla amarilla picada en trozos grandes","4 cucharadas de jugo de limón (aprox. 1 limón grande)","2 cucharadas de aceite de oliva","1 cucharadita de albahaca seca","2 cucharaditas de ajo en polvo","1.5 cucharaditas de comino","½ cucharadita de polvo para hornear","¾ de cucharadita de sal marina","¼ de cucharadita de pimienta negra",
("Ingredientes opcionales","pan pita integral (sin gluten si es necesario)"),("Ingredientes opcionales","jitomate"),("Ingredientes opcionales","pepino"),("Ingredientes opcionales","cebolla morada"),("Ingredientes opcionales","cilantro, perejil o eneldo frescos"),("Ingredientes opcionales","tahini")],
["Forre una bandeja para hornear con pergamino y precaliente el horno a 400 grados F.","Escurra bien los garbanzos y agréguelos al procesador de alimentos junto con todos los demás ingredientes. Procese hasta que esté desmenuzado pero no hecho puré. No procese de más.","Forme con la mezcla bolitas pequeñas (de 1 a 1.5\"), exprimiendo con las manos el exceso de humedad, luego aplánelas ligeramente y deles forma de hamburguesita/nugget. Colóquelas en la bandeja preparada.","Hornee durante 15 minutos y luego voltee los falafel y hornee otros 5 minutos hasta que estén ligeramente dorados. No cocine de más los falafel o quedarán demasiado secos.","Sirva en pitas con sus coberturas y salsas favoritas o úselos para cubrir ensaladas."],
["Asegúrese de escurrir bien los garbanzos y secarlos con toques, junto con el perejil o cilantro, con un paño de cocina limpio antes de pasarlos al procesador de alimentos. Exprima el exceso de humedad sobre el fregadero al formar las bolitas de falafel, antes de aplanarlas en forma de disco. No procese de más los ingredientes en el procesador de alimentos. Quiere una mezcla ligeramente con trozos para obtener la mejor textura posible. (Consulte la imagen de arriba.) No sustituya por garbanzos enlatados, ya que quedarán muy blandos y alterarán la textura de los falafel. El tamaño de la porción es para una cuarta parte de la receta o aprox. 5 falafel de los 20 que rinde. No se incluyen en el cálculo la pita, el wrap ni las coberturas adicionales. Las sobras se conservan refrigeradas hasta por 4 días. Guarde en un recipiente sellado y recaliente en el horno a 350 grados durante unos 10 minutos."],[]))
X.append(r(9910859,"Sopa saludable de brócoli y papa","La sopa de brócoli y papa es un poco cremosa, un poco con trozos y muy deliciosa. Esta sabrosa receta de sopa es reconfortante, nutritiva y 100% saludable.","8 porciones","1 porción",
["1 cebolla morada grande finamente picada","4 zanahorias grandes en rodajas finas","2 libras de papas Yukon Gold peladas y en cubos","1 lata de 19 onzas de frijoles blancos (alubias), escurridos y enjuagados","1 brócoli grande cortado en floretes del tamaño de un bocado (aprox. 8 tazas de floretes pequeños)","6 tazas de caldo de verduras bajo en sodio","½ taza de levadura nutricional","1 cucharadita de ajo en polvo","½ cucharadita de tomillo seco","sal marina al gusto","1 taza de leche de nuez de la India sin azúcar, leche de soya o leche de coco"],
["Agregue la cebolla y las zanahorias a una olla grande con una o dos cucharadas de agua. Saltee hasta que se ablanden un poco, aprox. 2 minutos.","Agregue las papas, los frijoles, el caldo, la levadura nutricional, el tomillo y el ajo en polvo a la olla y lleve a hervor a fuego alto. Reduzca el fuego y cocine a fuego lento hasta que las papas se atraviesen fácilmente con un tenedor, aprox. 8 minutos. Luego agregue el brócoli y cocine a fuego lento 5 minutos más.","Apague el fuego y, con una cuchara ranurada, retire y reserve aprox. 4 tazas de las verduras. Luego haga puré el resto de la sopa en la olla con una licuadora de inmersión. O puede pasarla por tandas a una licuadora de vaso, con precaución al licuar líquidos calientes. Devuelva a la olla las 4 tazas de verduras reservadas, incorpore la leche vegetal y pruebe la sal. En este punto yo agregué 1/2 cucharadita, pero sale a su gusto. Luego sirva y disfrute.",
("Instrucciones para Instant Pot","Programe la Instant Pot en la función de saltear, luego agregue la cebolla y las zanahorias con una o dos cucharadas de agua. Saltee hasta que se ablanden un poco, aprox. 2 minutos."),
("Instrucciones para Instant Pot","Agregue todos los demás ingredientes EXCEPTO la leche y cierre la tapa, asegurándose de que la válvula esté en la posición de sellado. Cocine a alta presión durante 7 minutos y luego libere rápidamente la válvula de vapor. Retire la tapa cuando sea seguro hacerlo."),
("Instrucciones para Instant Pot","Use una cuchara ranurada para retirar 4 tazas de las verduras y reserve. Luego haga puré el resto de la sopa con una licuadora de inmersión. O puede pasarla por tandas a una licuadora de vaso, con precaución al licuar líquidos calientes."),
("Instrucciones para Instant Pot","Devuelva las verduras reservadas a la olla, incorpore la leche y pruebe la sal. En este punto yo agregué 1/2 cucharadita, pero sale a su gusto. Luego sirva y disfrute.")],
["Me gusta esta sopa bastante con trozos, pero si la sirve a niños exigentes, puede hacer puré toda la sopa en lugar de reservar algunas verduras en trozos. Puede usar las verduras reservadas para incorporarlas de nuevo a la olla, o para decorar cada plato de sopa. Si evita las nueces, use leche de soya o de coco en lugar de leche de nuez de la India. También puede usar leche de coco enlatada si desea un acabado aún más rico y cremoso, sin embargo, esto agregará más grasa. Mantuve el condimento sencillo aquí para agradar a algunos niños exigentes, pero si desea realzar el sabor, puede agregar un poco de comino, pimentón o incluso un poco de cayena para dar algo de picante."],[]))
save(6,X)
