import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes0')
from h import *
X=[]
X.append(r(9070331,"Filetes de coliflor en freidora de aire","Los filetes de coliflor en freidora de aire son deliciosos, saludables y estarán en la mesa en un santiamén.","2 porciones","1 porción",
["1 coliflor grande","2 cucharadas de caldo de verduras","1 cucharada de jugo de limón verde (aprox. medio limón)","1 cucharadita de pimentón ahumado","1 cucharadita de ajo en polvo","½ cucharadita de sal marina","¼ de cucharadita de pimienta negra"],
["Lave la coliflor y quítele las hojas verdes, pero no corte el tallo.","Luego coloque la coliflor con el tallo hacia abajo sobre una tabla para cortar y recorte ambos extremos para que queden planos, reservando los trozos sueltos que se desprendan. (Vea las fotos del proceso arriba como referencia).","Ahora corte la pieza restante en rebanadas gruesas (aprox. 1.25 pulgadas de grosor) para obtener 2 o 3 filetes (según el tamaño de la coliflor).","En un tazón pequeño, combine todos los ingredientes del adobo y mezcle bien. Luego unte un lado de cada filete, colocándolos con el lado del adobo hacia abajo en la canasta de la freidora de aire, y después unte el otro lado.","Cocine en la freidora de aire a 375°F/190°C durante 10 minutos, luego voltee los filetes con cuidado y continúe cocinando otros 5-8 minutos, o hasta que la coliflor esté tierna y los bordes estén dorados."],
["Según el tamaño de la coliflor, obtendrá 2 o 3 filetes. Si va a hacer 3 filetes, aumente los ingredientes del adobo a lo siguiente: 3 cucharadas de caldo","1.5 cucharadas de jugo de limón verde","1.5 cucharaditas de pimentón ahumado","1.5 cucharaditas de ajo en polvo","¾ de cucharadita de sal marina","⅜ de cucharadita de pimienta negra (o ¼ + ⅛)","Use un cuchillo afilado e intente cortar los filetes de coliflor del mismo tamaño para que se cocinen de manera uniforme.","Para ahorrar tiempo, puede comprar en el supermercado filetes de coliflor que ya vienen cortados.","Las sobras se conservan en el refrigerador durante 2-3 días en un recipiente cerrado. No las congele."],[]))
X.append(r(9074637,"Paletas veganas de durazno y coco","Estas paletas veganas de durazno son un postre nutritivo y delicioso que solo necesita DOS ingredientes.","6 paletas","1 paleta",
["300 gramos de duraznos maduros, aprox. 2 duraznos","¾ de taza (177 ml) de leche de coco sin azúcar Thai Kitchen o la leche que prefiera","2 cucharadas de jarabe de arce (opcional)","1 cucharadita de extracto puro de vainilla (opcional)","¼ de cucharadita de canela (opcional)"],
["Lave y rebane los duraznos y quíteles los huesos. Póngalos en una licuadora o procesador de alimentos junto con la leche de coco y los ingredientes opcionales que use. Pulse hasta que estén casi integrados, dejando algunos trocitos pequeños de durazno para dar textura.","Distribuya la mezcla de manera uniforme entre seis moldes para paletas y luego golpee el molde contra la encimera para liberar las burbujas de aire. Coloque las tapas encima y congele durante 6 horas o toda la noche. Mantenga congeladas hasta el momento de servir. NOTA: Si usa palitos para paletas, congele las paletas de 1 a 2 horas, lo justo para que los palitos se mantengan rectos, y luego agregue los palitos y continúe congelando hasta que estén sólidas.",("Para sacarlas del molde","Llene un tazón con agua tibia, tan alto como su molde, y coloque el molde dentro, sin que se desborde por la parte superior donde están los palitos. Espere de 15 a 20 segundos antes de sacarlas y luego use un movimiento de lado a lado para sacar las paletas del molde."),("Para sacarlas del molde","También puede pasar las paletas bajo agua tibia del grifo de la cocina durante 15-20 segundos, o hasta que salgan con facilidad."),("Para sacarlas del molde","Si las paletas todavía están blandas, colóquelas en un plato y regréselas al congelador.")],
["Cuando los duraznos están en temporada y muy dulces, puede omitir el jarabe de arce opcional para un postre sin azúcar añadida. Para trozos de fruta más grandes en las paletas de durazno, use un procesador de alimentos y no procese en exceso. Para paletas de durazno perfectamente suaves, use una licuadora hasta obtener un puré. (Si tiene comensales exigentes, esta es la mejor opción). Si usa palitos para paletas (en lugar de las tapas que vienen con su molde), congele las paletas de 1 a 2 horas, lo justo para que los palitos se mantengan rectos, y luego agregue los palitos y continúe congelando hasta que estén sólidas. El tiempo de congelación variará según el grosor del molde. La mayoría de las paletas se congelan en 4-6 horas. Para menos grasa, use leche de coco LIGHT enlatada. Para una versión baja en grasa, use otra leche vegetal, como leche de almendras o leche de anacardos (nueces de la India), en lugar de leche de coco. Tenga en cuenta que las paletas de durazno quedarán menos ricas de esta manera."],[]))
X.append(r(9077170,"Brownies de garbanzo secretamente saludables","Los brownies de garbanzo sin harina son suaves y densos, chocolatosos, decadentes, endulzados de forma natural y nutritivos.","9 cuadros","1 porción",
["1 taza de dátiles sin hueso, compactados","¼ de taza de agua","1 lata de 15 onzas de garbanzos, escurridos pero reservando el líquido","3 cucharadas de aquafaba del líquido de los garbanzos reservado arriba","½ taza de crema de cacahuate natural, lisa o con trocitos","⅓ de taza de cacao en polvo crudo sin azúcar",("Ingredientes opcionales para incorporar","⅓ de taza de chispas de chocolate veganas"),("Ingredientes opcionales para incorporar","½ taza de trozos de nueces de Castilla")],
["Precaliente el horno a 350℉/176℃ y cubra un molde cuadrado para hornear de 8 pulgadas con papel pergamino.","Ponga los dátiles y el agua en el procesador de alimentos y procese hasta obtener una pasta suave. Luego agregue los garbanzos, la aquafaba, la crema de cacahuate y el cacao, y procese hasta que estén bien integrados.","A continuación, agregue los ingredientes opcionales, si los usa, y pulse unas cuantas veces para mezclarlos sin procesar en exceso.","Vierta la masa de los brownies en el molde y alise la superficie con una espátula de silicón. La masa será muy espesa, así que presiónela para asegurarse de que no queden huecos. Espolvoree más chispas de chocolate y nueces encima, si lo desea, y hornee durante 25-30 minutos.","Deje enfriar en el molde durante 5 minutos y luego levante los brownies con ayuda del papel pergamino y pase a una tabla para cortar. Deje enfriar durante AL MENOS 20 minutos antes de cortar."],
["Para una versión sin frutos secos, use crema de semillas (wow butter o sun butter) en lugar de la crema de cacahuate y omita las nueces opcionales. Si lo desea, puede sustituirlas por fruta seca, como pasas o arándanos rojos. Para brownies más dulces, agregue 1-2 cucharadas de jarabe de arce a la mezcla después de procesar los dátiles, y/o use hasta ½ taza de chispas de chocolate. Cubra el molde con papel pergamino para que sea más fácil sacar los brownies una vez horneados. ¡No los hornee en exceso! Hornear de más dará brownies más secos y con menos textura suave y densa. Se verán a medio hornear al sacarlos del horno, pero se asentarán al enfriarse. Moje el cuchillo entre cada corte al rebanar los brownies para obtener bordes más lisos y evitar que se peguen. Las sobras se conservan en un recipiente hermético a temperatura ambiente hasta por 4 días."],[]))
X.append(r(9079053,"Mac and Thai","Hay mucho que amar en esta fiesta de fusión culinaria con pasta gemelli bañada en una salsa cremosa hecha con anacardos (nueces de la India), leche de coco y pasta de curry rojo tailandés.","6 porciones","1 porción",
[("Salsa","2 cucharaditas de aceite vegetal neutro"),("Salsa","1 cebolla amarilla pequeña, picada finamente"),("Salsa","3 cucharadas (30 g) de pasta de curry rojo tailandés"),("Salsa","½ cucharadita de sal marina"),("Salsa","¼ de cucharadita de pimienta negra molida"),("Salsa","2 tazas (480 ml) de agua, divididas"),("Salsa","¾ de taza (105 g) de anacardos (nueces de la India) crudos sin sal, remojados en agua hirviendo durante 30 minutos y escurridos"),("Salsa","1 lata de 13 onzas, o 368 g, de leche de coco sin azúcar"),("Pasta","16 onzas (454 g) de gemelli u otra pasta pequeña"),("Guarnición","Cacahuates tostados picados para decorar"),("Guarnición","Albahaca tailandesa fresca o cilantro fresco picado, para decorar"),("Guarnición","Hojuelas de chile rojo para decorar (opcional)"),("Guarnición","Gajos de limón verde para servir")],
["Para preparar la salsa: En una sartén a fuego medio, caliente el aceite vegetal.","Agregue la cebolla y cocine hasta que esté tierna, unos 5 minutos.","Incorpore la pasta de curry, la sal y la pimienta. Cocine, revolviendo constantemente, durante 1 minuto.","Agregue 1 taza (240 ml) de agua y retire la sartén del fuego.","En una licuadora de alta potencia, combine los anacardos (nueces de la India) y la 1 taza (240 ml) restante de agua. Licue hasta que quede completamente suave. Agregue la mezcla de curry y licue de nuevo hasta que quede suave. Reserve.","Para preparar la pasta: Hierva una olla grande con agua con sal a fuego alto. Agregue la pasta y cocine según las indicaciones del paquete hasta que esté al dente. Escurra bien y regrésela a la olla.","Para terminar: Incorpore la salsa de curry y la leche de coco. Coloque la olla a fuego bajo y cocine, revolviendo de vez en cuando, durante unos minutos para que se caliente y la salsa espese. Pruebe y ajuste los condimentos según sea necesario. Pase a una fuente grande y sirva caliente, espolvoreado con cacahuates, albahaca y hojuelas de chile rojo (si las usa), con gajos de limón verde a un lado para exprimir."],
["Vegan Mac & Cheese de Robin Robertson © 2019 Quarto Publishing Group USA Inc. Esta es una reseña de receta y no es mi receta; tenga en cuenta que los ingredientes y las instrucciones de la receta son de Robin Robertson. Para preparar esta receta con menos de 400 calorías, disfrute una porción más pequeña."],[]))
X.append(r(9079622,"Sopa de brócoli y camote","Esta sopa de brócoli y camote es reconfortante, aterciopelada y deliciosa.","4 porciones","1 porción",
["2 libras de camotes, aprox. 3 camotes medianos largos y delgados","4 tazas de floretes de brócoli, aprox. 1 brócoli mediano","1 cebolla amarilla pelada + cortada por la mitad","3-4 dientes de ajo, sin pelar","4 tazas de caldo de verduras bajo en sodio","½ taza de levadura nutricional","1 cucharadita de perejil seco","½ cucharadita de semillas de apio (no sal de apio, a menos que no le importe el sodio adicional)","¼ de cucharadita de hojuelas de chile rojo (opcional, pero recomendado)","sal + pimienta al gusto"],
["Precaliente el horno a 400 grados F (200 C) y cubra una bandeja grande para hornear con papel pergamino.","Restriegue bien los camotes y córtelos por la mitad a lo largo. Acomódelos con el lado cortado hacia abajo en la bandeja. Agregue a la misma bandeja la cebolla, con el lado cortado hacia abajo, los floretes de brócoli y el ajo sin pelar. (Use dos bandejas si no cabe todo en una).","Rocíe las verduras con aceite de aguacate O con caldo de verduras para una versión sin aceite. Use los dedos o una brocha de silicón para frotar el líquido sobre la cáscara de los camotes. Luego espolvoree todo con sal y pimienta.","Hornee durante 25-30 minutos, hasta que los camotes se atraviesen fácilmente con un tenedor y las demás verduras estén bien asadas y doradas. Retire del horno.","Opcional: Reserve algunos de los trozos más pequeños de brócoli para decorar.","Ponga las verduras asadas (excepto los trozos que reservó para decorar) y todos los demás ingredientes en una olla y use una batidora de inmersión para hacer un puré hasta que quede suave. O pase a una licuadora de vaso y licue por tandas. Tenga precaución al licuar líquidos calientes y no llene demasiado la licuadora. Pruebe y ajuste la sal y la pimienta, si es necesario.","Sirva la sopa de brócoli y camote con los trozos de brócoli asado que reservó, crotones y crema de anacardos (nueces de la India), si lo desea."],
["Use camotes delgados y largos. Los camotes anchos tardarán mucho más en cocinarse. Haga lo posible por cortar los camotes en mitades iguales para que se cocinen de manera uniforme. Si prefiere una sopa más ligera, agregue una taza más de caldo. Pase las verduras asadas a una olla y use una batidora de inmersión para hacerlas puré y poder licuar todo en una sola tanda. Las sobras se conservan de 3 a 4 días en el refrigerador o puede congelarlas en un recipiente hermético apto para congelador hasta por 3 meses."],[]))
X.append(r(9080453,"Muffins saludables de trigo sarraceno","Los muffins de trigo sarraceno, húmedos, deliciosos y muy satisfactorios, son un desayuno nutritivo o un postre saludable.","12 muffins","1 porción",
[("Ingredientes húmedos","1.5 tazas de plátano maduro machacado, de aprox. 3 plátanos grandes o 4 medianos"),("Ingredientes húmedos","¼ de taza de crema de almendra"),("Ingredientes húmedos","⅓ de taza de jarabe de arce"),("Ingredientes secos","200 gramos de harina de trigo sarraceno, aprox. 1.5 tazas"),("Ingredientes secos","1 cucharadita de canela"),("Ingredientes secos","2 cucharaditas de polvo para hornear"),("Ingredientes secos","½ cucharadita de sal marina")],
["Precaliente el horno a 350℉/176℃ y cubra un molde para muffins con capacillos de papel pergamino.","Machaque los plátanos hasta obtener un puré muy fino, colóquelos en un tazón grande y agregue al mismo tazón la crema de almendra y el jarabe de arce. Mezcle bien.","Luego agregue todos los ingredientes secos y revuelva hasta que se integren.","Divida la mezcla entre los 12 moldes para muffins y hornee durante 20 minutos, o hasta que un palillo insertado en el centro de un muffin salga limpio. Retire los muffins de trigo sarraceno del horno y déjelos reposar de 5 a 10 minutos antes de pasarlos a una rejilla."],
["Use plátanos muy maduros con muchas manchas cafés en la cáscara para obtener más dulzor. También puede usar plátanos congelados; solo deje que lleguen a temperatura ambiente antes de machacarlos.","¡Pese la harina con una báscula de cocina para obtener los resultados más exactos! Tomar la harina directamente de la bolsa con la taza la compacta y podría significar que se esté usando demasiada harina, lo que podría dar como resultado un muffin más denso.","Use polvo para hornear FRESCO + ACTIVO. El polvo para hornear que lleva abierto en la despensa 6 meses o más puede empezar a perder su efectividad.","Deje reposar los muffins de 5 a 10 minutos después de hornearlos. Este breve tiempo de enfriamiento permitirá que los muffins se asienten por completo y evitará que se rompan al sacarlos del molde.","Guarde los muffins de trigo sarraceno a temperatura ambiente durante 2-3 días, en el refrigerador hasta por 4 días, o congélelos en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9080740,"Ensalada de papa con hierbas","¡Una deliciosa ensalada de papa con hierbas, de sabor fresco y sin mayonesa!","6 porciones","1 porción",
["2 libras de papas pequeñas rojas o amarillas (lavadas y cortadas en trozos de 1/2 pulgada de grosor)","1 cucharada de sal marina","1/3 de taza de eneldo fresco (picado finamente)","1/4 de taza de cebollín (picado finamente)","3 cucharadas de aquafaba (o aceite de oliva si no evita el aceite)","2 cucharadas de jugo de limón fresco","1 cucharada de vinagre de manzana","2 cucharaditas de mostaza Dijon","1 cucharadita de ajo en polvo","1/2 cucharadita de orégano seco","sal + pimienta (al gusto)"],
["En una olla grande, ponga las papas en rebanadas y la sal, y llene con agua cubriendo las papas por aproximadamente una pulgada. Hierva a fuego alto, luego reduzca el fuego a medio-bajo y cocine hasta que las papas estén tiernas al pincharlas con un tenedor, aprox. 10 minutos. Escurra las papas, pero RESERVE 1/4 de taza del agua con almidón.","Mientras tanto, combine todos los ingredientes del aderezo de la ensalada más el agua de cocción reservada en un tazón pequeño y mezcle bien. Luego agregue sal y pimienta al gusto.","Coloque las papas escurridas en un tazón grande y agregue el aderezo de hierbas. Mezcle bien y deje reposar las papas unos minutos antes de mezclar de nuevo con suavidad. (Las papas absorberán la salsa mientras reposan).","Puede servir la ensalada de papa tibia o fría. Refrigérela durante unas horas, o toda la noche, si planea servirla fría."],[],[]))
X.append(r(9084623,"Salsa BBQ vegana sin cocción","¡Una sencilla salsa BBQ vegana que puede preparar en minutos! No requiere cocción y solo necesita 8 ingredientes que ya tiene en la despensa.","12 porciones (rinde aprox. 1.5 tazas)","1 porción",
["1 taza de cátsup sin azúcar añadida","¼ de taza de jarabe de arce","2 cucharadas de vinagre de manzana","2 cucharadas de tamari bajo en sodio o salsa de soya si no evita el gluten","1 cucharadita de sriracha","1 cucharadita de mostaza amarilla","1 cucharadita de cebolla en polvo","1 cucharadita de pimentón ahumado"],
["Ponga todos los ingredientes en un tazón pequeño y bata bien para integrarlos por completo.","Pase la salsa BBQ a un frasco o recipiente LIMPIO."],
["Si no tiene o no encuentra cátsup sin azúcar añadida, reduzca el jarabe de arce. ¡Ajuste a su gusto! Si prefiere una salsa BBQ más picante, duplique la salsa picante. Si no desea picante, omítala. Para un sabor más ahumado, agregue una cucharadita de humo líquido o duplique el pimentón ahumado. Guarde la salsa en el refrigerador hasta por 3 semanas en un frasco o recipiente cerrado. O congélela en un recipiente hermético hasta por 3 meses. Esta receta de salsa BBQ vegana rinde aprox. 1.5 tazas en total, para 12 porciones de 2 cucharadas cada una. La información nutricional representa 1 porción de aprox. 2 cucharadas."],[]))
save(4,X)
