from h import *
O=[]
O.append(R(6487300,
("Ejotes con cebolla morada","Los ejotes frescos cocinados solo unos minutos tienen un delicado toque crujiente y un sabor vivo. Con tomillo fresco y cebolla morada salteada, este acompañamiento se convertirá en uno de sus favoritos.","8","1 taza",
["1/2 cucharadita de sal marina","2 libras de ejotes frescos (sin las puntas)","5 cucharaditas de mantequilla untable ligera","2 cucharadas de aceite de oliva","2 cebollas moradas medianas (partidas por la mitad, peladas y cortadas en rodajas de 1/2 pulgada de grosor)","1 cucharada de tomillo fresco (picado muy fino)","1/2 taza de almendras en rodajas","1 cucharada de ralladura de limón (de 1 limón mediano)"],
["Lleve a ebullición una olla de 6 cuartos de galón llena de agua hasta 2/3 de su capacidad. Agregue la sal. Agregue los ejotes y apague el fuego. Deje reposar los ejotes en el agua de 3 a 4 minutos. Escúrralos. Sumerja los ejotes en un recipiente con agua con hielo. Escúrralos de nuevo y resérvelos.","En una sartén grande, caliente la mantequilla y el aceite a fuego medio. Agregue las cebollas y cocínelas, revolviendo de vez en cuando, de 20 a 25 minutos, hasta que estén muy suaves. Baje el fuego si las cebollas empiezan a dorarse demasiado rápido.","Agregue el tomillo y los ejotes a las cebollas y caliente todo, volteando las verduras con cuidado con unas pinzas. Para servir, coloque la mezcla de cebolla y ejotes en una fuente y cubra con las almendras y la ralladura de limón."]),
("فاصوليا خضراء بالبصل الأحمر","الفاصوليا الخضراء الطازجة التي تُطهى لبضع دقائق فقط تحتفظ بقرمشة خفيفة ونكهة نضرة. مع الزعتر الطازج والبصل الأحمر المقلي قليلًا، سيصبح هذا الطبق الجانبي من أطباقكم المفضلة.","8","1 كوب",
["½ ملعقة صغيرة ملح بحري","2 رطل فاصوليا خضراء طازجة (مقطوعة الأطراف)","5 ملاعق صغيرة دهن زبدة خفيف","2 ملعقة كبيرة زيت زيتون","2 حبة بصل أحمر متوسطة (مقسومة إلى نصفين ومقشرة ومقطعة شرائح بسماكة ½ بوصة)","1 ملعقة كبيرة زعتر طازج (مفروم ناعمًا جدًا)","½ كوب لوز شرائح","1 ملعقة كبيرة قشر ليمون مبشور (من 1 ليمونة متوسطة)"],
["اغلِ قدرًا سعته 6 أرباع الجالون مملوءًا بالماء إلى ⅔ سعته. أضف الملح. أضف الفاصوليا الخضراء وأطفئ النار. اترك الفاصوليا في الماء من 3 إلى 4 دقائق. صفِّها من الماء. اغمس الفاصوليا في وعاء من الماء المثلج. صفِّها مرة أخرى وضعها جانبًا.","في مقلاة كبيرة، سخّن الزبدة والزيت على نار متوسطة. أضف البصل واطهه مع التقليب من حين لآخر لمدة 20 إلى 25 دقيقة حتى يصبح طريًا جدًا. اخفض النار إذا بدأ البصل يتحمّر بسرعة كبيرة.","أضف الزعتر والفاصوليا الخضراء إلى البصل وسخّنها جيدًا، مع قلب الخضار برفق باستخدام ملقط. للتقديم، ضع خليط البصل والفاصوليا الخضراء في طبق تقديم وغطِّه باللوز وقشر الليمون المبشور."])))

O.append(R(6488181,
("Ceviche de camarones","Esta versión del ceviche combina camarones sabrosos, piña dulce y chiles picantes en un adobo cítrico de limón. Sírvalo sobre arroz con guisantes cocidos o como salsa sobre pescado cocido. También puede servirlo con galletas saladas como botana o aperitivo.","6","1/2 taza",
["1 cucharada de aceite de oliva","1 cucharadita de ajo en polvo","2 cucharadas de vinagre blanco","3 cucharadas de jugo de limón","2 cucharadas de cilantro fresco","1 taza de piña picada","1 chile picante pequeño (picado en trozos grandes)","1 chile güero amarillo (picado en trozos grandes)","1 tomate mediano (picado en trozos grandes)","2 cebollitas de cambray (picadas en trozos grandes)","12 camarones (congelados, cocidos y pelados)"],
["Coloque la mezcla en un tazón para servir y agregue los camarones picados y el aceite de oliva. Refrigere durante 30 minutos o más antes de servir.","En un procesador de alimentos, agregue las cebollitas de cambray, el tomate, los chiles, la piña y el cilantro; pulse el botón de encendido y apagado para picar hasta obtener una consistencia muy gruesa. Se busca una textura con trozos. Agregue a la mezcla el jugo de limón, el vinagre y el ajo en polvo."]),
("سيفيتشي الجمبري","تضم هذه النسخة من السيفيتشي جمبريًا لذيذًا وأناناسًا حلوًا وفلفلًا حارًا في تتبيلة منعشة من الليمون الأخضر. قدّمه فوق الأرز المطهو والبازلاء، أو كصلصة فوق السمك المطهو. أو قدّمه مع البسكويت المملح كوجبة خفيفة أو مقبلات.","6","½ كوب",
["1 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة مسحوق الثوم","2 ملعقة كبيرة خل أبيض","3 ملاعق كبيرة عصير ليمون أخضر","2 ملعقة كبيرة كزبرة خضراء طازجة","1 كوب أناناس مقطع","1 حبة فلفل حار صغيرة (مقطعة تقطيعًا خشنًا)","1 حبة فلفل موز أصفر (مقطعة تقطيعًا خشنًا)","1 حبة طماطم متوسطة (مقطعة تقطيعًا خشنًا)","2 حبة بصل أخضر (مقطعة تقطيعًا خشنًا)","12 حبة جمبري (مجمد، مطهو ومقشر)"],
["ضع الخليط في وعاء تقديم وأضف الجمبري المقطع وزيت الزيتون. برّده في الثلاجة 30 دقيقة أو أكثر قبل التقديم.","في محضّرة الطعام، ضع البصل الأخضر والطماطم والفلفل والأناناس والكزبرة الخضراء؛ ثم اضغط زر التشغيل والإيقاف بالتناوب لتقطيعها تقطيعًا خشنًا جدًا. المطلوب قوام يحتوي على قطع. أضف عصير الليمون الأخضر والخل ومسحوق الثوم إلى الخليط."])))

O.append(R(6488782,
("Ensalada de col rizada y manzana","Puede variar las verduras de esta ensalada usando espinaca picada, repollo verde y zanahoria rallada.\n\nComplete su plato: Acompañe esta guarnición de verduras con el Chili de res fácil. Ambos son excelentes como sobras, por lo que es una gran opción para preparar comidas con anticipación.","4","1 1/4 tazas",
["1/2 taza de yogur griego natural sin grasa","1 diente de ajo (picado)","1 cucharadita de mostaza Dijon","1 cucharada de aceite de oliva","3 cucharadas de jugo de limón","3 cucharadas de agua","1/4 de cucharadita de sal","1/8 de cucharadita de pimienta negra","2 tazas de col rizada (kale) picada","3 tazas de col morada rallada","1 manzana Fuji (rallada con cáscara)"],
["En un tazón grande, bata el yogur, el ajo, la mostaza, el aceite de oliva, el jugo de limón, el agua, la sal y la pimienta negra.","Agregue al tazón la col rizada, el repollo y la manzana, y mezcle para cubrir todo de manera uniforme. Tape y refrigere durante 30 minutos antes de servir para que se integren los sabores."]),
("سلطة اللفت الأجعد (الكيل) والتفاح","يمكنكم تغيير الخضار في هذه السلطة باستخدام السبانخ المفرومة أو الملفوف الأخضر أو الجزر المبشور.\n\nأكملوا طبقكم: قدّموا هذا الطبق الجانبي من الخضار مع تشيلي اللحم البقري السهل. كلاهما ممتاز كبقايا طعام، لذا فهو خيار رائع لتحضير الوجبات مسبقًا.","4","1¼ كوب",
["½ كوب زبادي يوناني سادة خالٍ من الدسم","1 فص ثوم (مفروم)","1 ملعقة صغيرة خردل ديجون","1 ملعقة كبيرة زيت زيتون","3 ملاعق كبيرة عصير ليمون","3 ملاعق كبيرة ماء","¼ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود","2 كوب كيل (لفت أجعد) مفروم","3 كوب ملفوف أحمر مبشور","1 تفاحة فوجي (مبشورة بقشرها)"],
["في وعاء كبير، اخفق الزبادي والثوم والخردل وزيت الزيتون وعصير الليمون والماء والملح والفلفل الأسود معًا.","أضف الكيل والملفوف والتفاح إلى الوعاء وقلّب لتغطيتها بالتساوي. غطِّ الوعاء وضعه في الثلاجة 30 دقيقة قبل التقديم لتتمازج النكهات."])))

O.append(R(6489390,
("Salsa casi suave","¿Le gusta la salsa suave o con trocitos? Si le gusta suave, licúela hasta que quede tersa. Si le gusta con trocitos, omita por completo el licuado.","12","2 cucharadas",
["2 tomates roma (tipo pera) medianos (picados en cubitos)","1/4 de pimiento verde mediano (picado en cubitos)","1/4 de cebolla morada mediana (picada en cubitos)","1/2 chile jalapeño entero (sin semillas ni venas, picado en cubitos)","3 cucharadas de cilantro fresco (picado)","1 cucharada de jugo de limón","1 cucharada de aceite de oliva","1/4 de cucharadita de sal","1/8 de cucharadita de pimienta negra"],
["Agregue los tomates, el pimiento, la cebolla, el jalapeño y el cilantro a un tazón mediano. Agregue el jugo de limón, el aceite de oliva, la sal y la pimienta negra. Mezcle para cubrir todo de manera uniforme.","Con una licuadora de inmersión, licúe hasta que la salsa quede casi suave, dejando algunos trocitos."]),
("صلصة شبه ناعمة","هل تفضّلون الصلصة الناعمة أم التي فيها قطع؟ إذا كنتم تحبون الصلصة ناعمة، فاخلطوها حتى تصبح ناعمة تمامًا. وإذا كنتم تحبونها بقطع، فتجاوزوا الخلط تمامًا.","12","2 ملعقة كبيرة",
["2 حبة طماطم روما (كمثرية الشكل) متوسطة (مقطعة مكعبات)","¼ حبة فلفل رومي أخضر متوسطة (مقطعة مكعبات)","¼ حبة بصل أحمر متوسطة (مقطعة مكعبات)","½ حبة هالابينو كاملة (منزوعة البذور والعروق ومقطعة مكعبات)","3 ملاعق كبيرة كزبرة خضراء طازجة (مفرومة)","1 ملعقة كبيرة عصير ليمون أخضر","1 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود"],
["ضع الطماطم والفلفل الرومي والبصل والهالابينو والكزبرة الخضراء في وعاء متوسط. أضف عصير الليمون الأخضر وزيت الزيتون والملح والفلفل الأسود. قلّب لتغطية المكونات بالتساوي.","باستخدام خلاط يدوي، اخلط حتى تصبح الصلصة شبه ناعمة مع ترك بعض القطع فيها."])))

O.append(R(6489812,
("Bacalao al horno con chimichurri de perejil y cilantro","Una vibrante salsa chimichurri hecha con perejil, cilantro, vinagre y limón cubre el suave bacalao. Este plato de proteína, apto para personas con diabetes, se prepara rápidamente y es fácil de hacer al horno. Pruebe preparar quinoa con cilantro y limón como un delicioso almidón para acompañarlo.","4","1 filete de bacalao + 2 cucharadas de salsa",
["4 filetes de bacalao (de 4 onzas cada uno)","4 dientes de ajo","1/2 cebolla morada mediana (picada)","1 taza de perejil liso fresco (bien compacta)","1 taza de hojas de cilantro fresco (bien compacta)","1/4 de cucharadita de hojuelas de chile rojo triturado","1/8 de cucharadita de pimienta negra","2 cucharadas de vinagre de vino tinto","1 cucharadita de ralladura de limón","2 cucharadas de jugo fresco de limón","4 cucharadas de aceite de oliva (divididas)"],
["Precaliente el horno a 400 °F.","Coloque los filetes de bacalao en una bandeja para hornear forrada con papel pergamino. Rocíe ligeramente con 1 cucharada de aceite. Coloque la bandeja en el horno y cocine hasta que la temperatura interna del pescado sea de 145 °F, de 8 a 10 minutos.","Coloque el ajo, la cebolla, el perejil, el cilantro, el chile rojo triturado y la pimienta negra en un procesador de alimentos. Procese hasta que todo esté finamente picado.","Agregue el vinagre, la ralladura y el jugo de limón, y 3 cucharadas de aceite de oliva. Procese hasta obtener una mezcla suave y reserve.","Para servir, divida el pescado entre los platos y cubra con la salsa chimichurri."]),
("سمك القد المخبوز بصلصة التشيميتشوري بالبقدونس والكزبرة","تغطي صلصة التشيميتشوري المنعشة المصنوعة من البقدونس والكزبرة الخضراء والخل والليمون الأخضر سمك القد ذا النكهة الهادئة. هذا الطبق من البروتين المناسب لمرضى السكري يُحضَّر بسرعة وسهل التحضير بخبزه في الفرن. جرّبوا تحضير الكينوا بالكزبرة والليمون الأخضر كطبق جانبي لذيذ من النشويات لتقديمه معه.","4","1 قطعة سمك قد + 2 ملعقة كبيرة صلصة",
["4 شرائح سمك قد (4 أونصات لكل شريحة)","4 فصوص ثوم","½ حبة بصل أحمر متوسطة (مفرومة)","1 كوب بقدونس مسطح الأوراق طازج (مكبوس)","1 كوب أوراق كزبرة خضراء طازجة (مكبوسة)","¼ ملعقة صغيرة رقائق فلفل أحمر مجروش","⅛ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة خل النبيذ الأحمر","1 ملعقة صغيرة قشر ليمون أخضر مبشور","2 ملعقة كبيرة عصير ليمون أخضر طازج","4 ملاعق كبيرة زيت زيتون (مقسمة)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية).","ضع شرائح سمك القد على صينية خبز مبطنة بورق الزبدة. رُشَّ عليها قليلًا 1 ملعقة كبيرة من الزيت. ضع الصينية في الفرن واطهِ حتى تبلغ درجة الحرارة الداخلية للسمك 145° فهرنهايت (65° مئوية)، لمدة 8 إلى 10 دقائق.","ضع الثوم والبصل والبقدونس والكزبرة الخضراء والفلفل الأحمر المجروش والفلفل الأسود في محضّرة الطعام. اخلط حتى تصبح المكونات مفرومة ناعمًا.","أضف الخل وقشر الليمون الأخضر المبشور وعصيره و3 ملاعق كبيرة من زيت الزيتون. اخلط حتى تصبح الصلصة ناعمة وضعها جانبًا.","للتقديم، وزّع السمك على الأطباق وغطِّه بصلصة التشيميتشوري."])))

O.append(R(6491318,
("Anacardos (nueces de la India) de 1/2 onza","Información nutricional de los anacardos (nueces de la India)","1","Anacardos de 1/2 onza",["1/2 onza de anacardos (nueces de la India)"],[]),
("الكاجو ½ أونصة","المعلومات الغذائية للكاجو","1","كاجو ½ أونصة",["½ أونصة كاجو"],[])))
O.append(R(6494336,None,
("جزر صغير مشوي","يُبرز الشواء النكهة الطبيعية للجزر وحلاوته. استخدمنا هنا البقدونس، لكن يمكنكم استخدام أعشاب طازجة أخرى مثل الطرخون أو الشبت أو النعناع أو الزعتر أو إكليل الجبل، أو مزيجًا منها.","8","⅓ كوب",
["1 بخّاخ زيت طهي غير لاصق","1 رطل جزر صغير","1½ ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة عسل أو 2 عبوة من المُحلّي الصناعي","1 ملعقة كبيرة بقدونس طازج مفروم أو 1 ملعقة صغيرة بقدونس مجفف"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية). رُشَّ صينية الخبز بزيت الطهي.","في وعاء صغير، اخلط الجزر مع زيت الزيتون. اسكب الخليط على صينية الخبز.","اخبز لمدة 15 إلى 20 دقيقة حتى يصبح الجزر طريًا.","ضع الجزر في وعاء واخلطه مع العسل أو المُحلّي الصناعي. رُشَّ الجزر بالبقدونس أو بالأعشاب الأخرى."])))
O.append(R(6494648,
("Pistachos ligeramente salados","Información nutricional de 50 pistachos ligeramente salados","1","50 pistachos",["50 pistachos enteros ligeramente salados"],[]),
("فستق حلبي مملح قليلًا","المعلومات الغذائية لـ 50 حبة فستق حلبي مملح قليلًا","1","50 حبة فستق حلبي",["50 حبة فستق حلبي كاملة مملحة قليلًا"],[])))
O.append(R(6494663,
("Coulis de pimiento rojo asado","Un coulis es simplemente un puré o salsa espesa. Este es un toque final hermoso y delicioso para sus platillos. (En la imagen, con Cebollas con romero y balsámico y Pesto.)","8","1/4 de taza",
["4 pimientos rojos medianos"],
["Coloque los pimientos enteros directamente sobre una parrilla o una hornilla de gas, o bajo el asador del horno. Áselos hasta que estén completamente ennegrecidos por fuera. Colóquelos en un tazón y cúbralos bien con envoltura plástica durante al menos 15 minutos. Una vez que se hayan enfriado, podrá pelar la piel ennegrecida.","Coloque el pimiento asado en el procesador de alimentos y haga un puré fino."]),
("كولي الفلفل الأحمر المشوي","الكولي هو ببساطة هريس أو صلصة سميكة. وتُعدّ هذه اللمسة الأخيرة جميلة وشهية لأطباقكم. (في الصورة مع بصل إكليل الجبل والبلسميك والبيستو.)","8","¼ كوب",
["4 حبات فلفل رومي أحمر متوسطة"],
["ضع حبات الفلفل كاملة مباشرة على الشواية أو على موقد الغاز أو تحت شواية الفرن. اشوِها حتى تسودّ تمامًا من الخارج. ضعها في وعاء وغطِّه بإحكام بغلاف بلاستيكي لمدة 15 دقيقة على الأقل. بعد أن تبرد، يمكنك إزالة القشرة المسودّة.","ضع الفلفل المشوي في محضّرة الطعام وهرسه حتى يصبح ناعمًا."])))

O.append(R(6495824,
("Brochetas de vieiras","Esta es una forma totalmente distinta de preparar vieiras. La mayoría de las recetas indican sellarlas en la sartén, pero ¿por qué no probar algo nuevo? Cubro las vieiras con pan molido panko crujiente sazonado con un poco de queso parmesano y ajo, y las ensarto en brochetas. Bajo el asador del horno, el exterior queda crujiente y el interior de la vieira se mantiene sedoso.","4","3 onzas",
["8 brochetas de madera enteras","1/2 taza de pan molido panko","2 cucharadas de queso parmesano (rallado)","3 dientes de ajo (picados muy finos, casi hasta formar una pasta)","1 cucharadita de condimento italiano","12 onzas de vieiras grandes de mar (frescas o congeladas, descongeladas y secadas con toques de papel)","1 rocío, 0.25 g de aceite de oliva en aerosol para cocinar"],
["Ponga las brochetas de madera en una cacerola con agua caliente. Déjelas reposar de 1 a 2 horas.","Cubra una bandeja para asar con papel de aluminio. Rocíe el papel con aceite en aerosol para cocinar. Precaliente el asador del horno a temperatura alta con la rejilla a unas 5 pulgadas de la fuente de calor.","En un plato, mezcle el pan molido, el queso parmesano, el ajo y el condimento italiano. Pase cada vieira por la mezcla de pan molido.","Saque las brochetas de madera del agua caliente. Con dos brochetas por cada brocheta de vieiras, ensarte las vieiras de modo que queden planas a lo largo de las brochetas.","Coloque las brochetas en la bandeja para asar preparada. Rocíe cada brocheta con aceite de oliva en aerosol. Ase las vieiras unos 4 minutos por lado, hasta que estén bien cocidas."]),
("أسياخ الإسكلوب","إليكم طريقة مختلفة تمامًا لتحضير الإسكلوب. تطلب معظم الوصفات تحميره في المقلاة، ولكن لماذا لا نجرّب شيئًا جديدًا؟ أغطّي الإسكلوب بفتات خبز البانكو المقرمش المتبّل بقليل من جبن البارميزان والثوم، وأنظمه في أسياخ. تحت شواية الفرن، يصبح الخارج مقرمشًا ويبقى داخل الإسكلوب ناعمًا كالحرير.","4","3 أونصات",
["8 أعواد خشبية كاملة للأسياخ","½ كوب فتات خبز بانكو","2 ملعقة كبيرة جبن بارميزان (مبشور)","3 فصوص ثوم (مفرومة ناعمًا جدًا، تكاد تصبح عجينة)","1 ملعقة صغيرة توابل إيطالية","12 أونصة إسكلوب بحري كبير (طازج أو مجمد، مذاب ومجفف بالمناديل)","1 رشة، 0.25 غرام بخّاخ زيت زيتون للطهي"],
["ضع الأعواد الخشبية في قدر فيه ماء ساخن. اتركها جانبًا لمدة 1 إلى 2 ساعة.","غطِّ صينية الشواء بورق الألمنيوم. رُشَّ الورق ببخّاخ زيت الطهي. سخّن شواية الفرن مسبقًا على درجة حرارة عالية مع وضع الرف على بُعد 5 بوصات تقريبًا من مصدر الحرارة.","اخلط فتات الخبز وجبن البارميزان والثوم والتوابل الإيطالية في صحن. قلّب كل قطعة إسكلوب في خليط فتات الخبز.","أخرج الأعواد الخشبية من الماء الساخن. باستخدام عودين لكل سيخ، اِنظم قطع الإسكلوب على الأعواد بحيث تكون مسطحة على امتداد السيخ.","ضع الأسياخ على صينية الشواء المجهزة. رُشَّ كل سيخ ببخّاخ زيت الزيتون للطهي. اشوِ الإسكلوب نحو 4 دقائق من كل جانب حتى ينضج تمامًا."])))

O.append(R(6496705,None,
("كعك فاصوليا رعاة البقر المقلي","أحضروا هذه المقبلات لمشاركتها في حفل الشواء الصيفي القادم. قدّموا الكعكات مع خيارات للغمس مثل الصلصة والزبادي اليوناني السادة الخالي من الدسم (بديل أكثر صحة للقشدة الحامضة).","20","3 كعكات",
["1¾ كوب دقيق متعدد الاستخدامات","2 ملعقة صغيرة بيكنج بودر","½ ملعقة صغيرة كمون","2 ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","4 بياض بيض (مخفوق قليلًا)","1 كوب صلصة سالسا","2 علبة فاصوليا سوداء (16 أونصة، مشطوفة بالماء ومصفاة)","1 ملعقة كبيرة زيت نباتي (مع كمية إضافية عند الحاجة)"],
["في وعاء كبير، اخلط الدقيق والبيكنج بودر والكمون والملح والفلفل. أضف بياض البيض والصلصة؛ وقلّب جيدًا، ثم أضف الفاصوليا السوداء وحرّك.","في مقلاة كبيرة على نار متوسطة إلى عالية، سخّن 1 ملعقة كبيرة من الزيت. اسكب 1 ملعقة صغيرة من العجين لكل كعكة في المقلاة، واطهِ عدة كعكات في الوقت نفسه دون تكديسها. اطهِ 1 دقيقة، ثم اقلب الكعكات واضغط عليها برفق بالملعقة العريضة (السباتولا)؛ ثم اطهِ من 1 إلى 2 دقيقة إضافية أو حتى تتحمّر من الجانبين. كرّر العملية مع العجين المتبقي، مع إضافة المزيد من الزيت عند الحاجة."])))
O.append(R(6497012,
("Brócoli al vapor","Información nutricional del brócoli al vapor","1","1 taza",["1 taza de brócoli (congelado)"],
["Coloque los floretes de brócoli congelado en un tazón apto para microondas.","Agregue de 2 a 4 cucharadas de agua.","Tape el tazón con un plato o una tapa aptos para microondas.","Cocine en el microondas a temperatura alta de 2 a 4 minutos, hasta que esté suave.","Retire con cuidado, ya que el vapor estará caliente."]),
("بروكلي مطهو على البخار","المعلومات الغذائية للبروكلي المطهو على البخار","1","1 كوب",["1 كوب بروكلي (مجمد)"],
["ضع زهرات البروكلي المجمدة في وعاء صالح للاستخدام في الميكروويف.","أضف من 2 إلى 4 ملاعق كبيرة من الماء.","غطِّ الوعاء بصحن أو غطاء صالح للاستخدام في الميكروويف.","سخّنه في الميكروويف على درجة حرارة عالية من 2 إلى 4 دقائق حتى يصبح طريًا.","أخرجه بحذر، لأن البخار سيكون ساخنًا."])))

O.append(R(6497459,
("Marinara italiana clásica con pasta integral","Puede preparar su propia salsa marinara por una fracción del precio de las salsas embotelladas del comercio. Esta salsa lleva mucho ajo, pero siéntase en libertad de suavizar este sabor intenso si lo desea. Reduzca la cantidad de ajo o corte el ajo en rebanadas en lugar de picarlo. Cuanto más pique el ajo, más fuerte será el sabor del platillo final. Los trozos más grandes de ajo, aunque siguen aportando sabor, liberan un gusto más sutil. Esta salsa se congela muy bien. Viértala en una bolsa gruesa para congelador con cierre hermético y guárdela hasta por 6 meses.","10","1/2 taza",
["2 cucharadas de aceite de oliva","5 dientes de ajo (picados)","1 lata (de 28 onzas) de tomates enlatados (de buena calidad, de preferencia en su propio jugo, escurridos; reserve el líquido)","5 hojas de albahaca fresca (en tiras, o puede dejarlas enteras)","10 onzas de pasta integral (penne, conchas, fusilli)","1/4 de cucharadita de sal kosher","1/4 de cucharadita de pimienta negra (recién molida)","1/4 de cucharadita de hojuelas de chile rojo molido (opcional)","2 cucharadas de queso parmesano o romano (recién rallado)"],
["Caliente el aceite de oliva y el ajo en una sartén grande con tapa a fuego bajo (no use una olla honda, ya que desea que el agua se evapore rápidamente y la salsa se espese). Cocine el ajo unos 6 a 7 minutos, sin dejar que se dore, revolviendo de vez en cuando.","Mientras tanto, ponga los tomates escurridos en un tazón hondo. Aplaste los tomates con las manos hasta que queden en trozos gruesos. Agregue los tomates y la albahaca a la sartén y cocine a fuego lento de 20 a 25 minutos, hasta que se espese. Si la salsa queda demasiado espesa, agregue un poco del líquido reservado de la lata de tomates.","Mientras tanto, lleve a ebullición fuerte una olla de 3 a 5 cuartos de galón con agua ligeramente salada (llene la olla hasta 2/3 de su capacidad). Agregue la pasta y revuelva durante el primer minuto. Siga cocinando la pasta aproximadamente de 7 a 8 minutos, hasta que esté al dente. Escúrrala, sin enjuagarla.","Agregue la sal, la pimienta y el chile rojo triturado, si lo usa, a la salsa de tomate. Agregue la pasta a la salsa, tape y deje reposar la pasta en la salsa de 1 a 2 minutos. Pase la pasta a un tazón caliente y espolvoree con el queso. (La salsa también se puede congelar. Congélela en un recipiente de un cuarto de galón y guárdela de 3 a 4 meses.)"]),
("مارينارا إيطالية كلاسيكية مع معكرونة القمح الكامل","يمكنكم تحضير صلصة المارينارا بأنفسكم بجزء صغير من ثمن الصلصات المعبأة الجاهزة. تعتمد هذه الصلصة كثيرًا على الثوم، لكن يمكنكم تخفيف هذه النكهة القوية إن رغبتم. قلّلوا كمية الثوم أو قطّعوه شرائح بدلًا من فرمه. كلما فرمتم الثوم أكثر، أصبحت نكهة الطبق النهائي أقوى. أما قطع الثوم الأكبر، فمع احتفاظها بالنكهة، تُطلق مذاقًا أخف. تتحمل هذه الصلصة التجميد جيدًا. اسكبوها في كيس تجميد سميك بسحّاب وخزّنوها حتى 6 أشهر.","10","½ كوب",
["2 ملعقة كبيرة زيت زيتون","5 فصوص ثوم (مفرومة)","1 علبة (28 أونصة) طماطم معلبة (جيدة النوعية، ويفضّل أن تكون في عصيرها، مصفاة مع الاحتفاظ بالسائل)","5 أوراق ريحان طازج (مقطعة شرائح، أو يمكنكم تركها كاملة)","10 أونصات معكرونة القمح الكامل (بيني أو أصداف أو فوسيلي)","¼ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود (مطحون طازجًا)","¼ ملعقة صغيرة رقائق فلفل أحمر مطحون (اختياري)","2 ملعقة كبيرة جبن بارميزان أو رومانو (مبشور طازجًا)"],
["سخّن زيت الزيتون والثوم في مقلاة كبيرة بغطاء على نار هادئة (لا تستخدم قدرًا عميقًا، فالمطلوب أن يتبخر الماء بسرعة وتصبح الصلصة سميكة). اطهِ الثوم نحو 6 إلى 7 دقائق دون أن يتحمّر، مع التحريك من حين لآخر.","في هذه الأثناء، ضع الطماطم المصفاة في وعاء عميق. اهرس الطماطم بيديك حتى تصبح خشنة القوام. أضف الطماطم والريحان إلى المقلاة واتركها على نار هادئة 20 إلى 25 دقيقة حتى تثخن. أضف قليلًا من السائل المحتفظ به من علبة الطماطم إذا كانت الصلصة سميكة جدًا.","في هذه الأثناء، اغلِ قدرًا سعته 3 إلى 5 أرباع الجالون من الماء المملح قليلًا (املأ القدر إلى ⅔ سعته) حتى يغلي غليانًا شديدًا. أضف المعكرونة وحرّكها خلال الدقيقة الأولى. تابع طهي المعكرونة نحو 7 إلى 8 دقائق حتى تصبح «آل دنتي». صفِّها ولا تشطفها.","أضف الملح والفلفل والفلفل الأحمر المجروش، إن استخدمته، إلى صلصة الطماطم. أضف المعكرونة إلى الصلصة، وغطِّها واتركها في الصلصة من 1 إلى 2 دقيقة. ضع المعكرونة في وعاء مسخّن ورُشَّ عليها الجبن. (يمكن أيضًا تجميد الصلصة. جمّدها في وعاء سعة ربع جالون وخزّنها من 3 إلى 4 أشهر.)"])))
dump(O,"../out_c14_part1.json")
