from h import *
O=[]
O.append(R(6514260,
("Frambuesas, 1 taza","Información nutricional de las frambuesas","1","1 taza",["1 taza de frambuesas"],[]),
("توت العليق (الراسبيري)، 1 كوب","المعلومات الغذائية لتوت العليق","1","1 كوب",["1 كوب توت عليق"],[])))
O.append(R(6514294,
("Berenjena con ajo y jengibre","Este platillo de verduras de inspiración asiática lleva berenjena, champiñones y brotes de frijol en una salsa hoisin con ajo y jengibre. La receta indica berenjena china o japonesa, que es larga y delgada. Si no encuentra berenjena china, puede usar berenjena común cortada en cubos de 1 pulgada. Puede servirse como guarnición o como plato principal vegetariano. Agregue tofu u otra fuente de proteína de origen vegetal para tener una comida vegetariana completa.\n\nPowered by Homemade, brought to you by Davita.","4","3/4 de taza",
["2 cucharadas de aceite de ajonjolí","2 berenjenas japonesas enteras (cortadas en trozos de 1 pulgada)","2 cucharaditas de jengibre fresco picado","2 dientes de ajo (picados)","1/2 taza de champiñones picados","1 taza de brotes frescos de frijol mungo","1/4 de taza de albahaca fresca (picada)","1/4 de cucharadita de hojuelas de chile rojo triturado","1 cucharada de salsa hoisin"],
["Caliente el aceite de ajonjolí en una sartén grande. Agregue la berenjena, el jengibre, el ajo, los champiñones y los brotes de frijol. Saltee a fuego medio-alto hasta que la berenjena empiece a ablandarse, de 4 a 6 minutos.","Agregue a la berenjena la albahaca, las hojuelas de chile y la salsa hoisin. Siga cocinando de 1 a 2 minutos. Retire del fuego y sirva."]),
("باذنجان بالثوم والزنجبيل","يضم هذا الطبق من الخضار المستوحى من المطبخ الآسيوي الباذنجان والفطر وبراعم الفاصوليا في صلصة الهويسين بالثوم والزنجبيل. تستخدم الوصفة الباذنجان الصيني أو الياباني، وهو طويل ونحيف. إذا لم تجدوا الباذنجان الصيني، فيمكنكم استخدام الباذنجان العادي مقطعًا إلى مكعبات بحجم 1 بوصة. يمكن تقديمه كطبق جانبي أو كطبق رئيسي نباتي. أضيفوا التوفو أو مصدرًا آخر للبروتين النباتي للحصول على وجبة نباتية متكاملة.\n\nPowered by Homemade, brought to you by Davita.","4","¾ كوب",
["2 ملعقة كبيرة زيت السمسم","2 حبة باذنجان ياباني كاملة (مقطعة إلى قطع بحجم 1 بوصة)","2 ملعقة صغيرة زنجبيل طازج مفروم","2 فص ثوم (مفروم)","½ كوب فطر مفروم","1 كوب براعم فاصوليا الماش الطازجة","¼ كوب ريحان طازج (مفروم)","¼ ملعقة صغيرة رقائق فلفل أحمر مجروش","1 ملعقة كبيرة صلصة هويسين"],
["سخّن زيت السمسم في مقلاة كبيرة. أضف الباذنجان والزنجبيل والثوم والفطر وبراعم الفاصوليا. قلّبها على نار متوسطة إلى عالية حتى يبدأ الباذنجان بالليونة، من 4 إلى 6 دقائق.","أضف الريحان ورقائق الفلفل الحار وصلصة الهويسين إلى الباذنجان. واصل الطهي من 1 إلى 2 دقيقة. ارفعه عن النار وقدّمه."])))
O.append(R(6515306,
("Filetes de coliflor con chimichurri","Los filetes de coliflor con chimichurri son un platillo vegetariano sabroso y saciante que transforma la coliflor en filetes contundentes y los acompaña con una salsa chimichurri vibrante y vivaz.","8","1 filete de coliflor + 2 cucharadas de chimichurri",
["2 coliflores grandes","1 cucharada de aceite de oliva","3/4 de cucharadita de sal kosher (dividida)","1/2 cucharadita de pimienta negra (dividida)","1/2 taza de perejil fresco (picado muy fino)","2 cucharadas de cilantro fresco (picado muy fino)","2 dientes de ajo (picados)","1/2 cucharadita de orégano seco","1/4 de cucharadita de hojuelas de chile rojo molido (ajuste al gusto)","2 cucharadas de vinagre de vino tinto","1/4 de taza de aceite de oliva extra virgen"],
["Precaliente el horno a 425 °F.","Retire las hojas exteriores de las coliflores. Recorte el extremo del tallo para crear una base plana.","Corte cada coliflor en rebanadas de 1 pulgada de grosor para formar los filetes de coliflor.","Coloque los filetes de coliflor en una bandeja para hornear. Úntelos por ambos lados con 1 cucharada de aceite de oliva y sazone con sal kosher y pimienta negra.","Ase los filetes de coliflor hasta que estén dorados y suaves, unos 20 minutos.","Mientras se asa la coliflor, prepare la salsa chimichurri. En un tazón, mezcle el perejil y el cilantro finamente picados, el ajo picado, el orégano seco, las hojuelas de chile rojo, el vinagre de vino tinto, el aceite de oliva extra virgen, la sal kosher y la pimienta negra. Bata hasta integrar bien.","Cuando los filetes de coliflor estén listos, páselos a platos para servir.","Vierta con una cuchara abundante salsa chimichurri sobre cada filete de coliflor."]),
("شرائح القرنبيط بصلصة التشيميتشوري","شرائح القرنبيط بصلصة التشيميتشوري طبق نباتي غني بالنكهة ومشبع، يحوّل القرنبيط إلى شرائح مشبعة تشبه شرائح اللحم ويقدّمها مع صلصة تشيميتشوري نابضة بالحياة ومنعشة.","8","1 شريحة قرنبيط + 2 ملعقة كبيرة تشيميتشوري",
["2 رأس قرنبيط (كبيرة)","1 ملعقة كبيرة زيت زيتون","¾ ملعقة صغيرة ملح كوشر (مقسمة)","½ ملعقة صغيرة فلفل أسود (مقسمة)","½ كوب بقدونس طازج (مفروم ناعمًا)","2 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة ناعمًا)","2 فص ثوم (مفروم)","½ ملعقة صغيرة أوريجانو مجفف","¼ ملعقة صغيرة رقائق فلفل أحمر مطحون (عدّلوها حسب الذوق)","2 ملعقة كبيرة خل النبيذ الأحمر","¼ كوب زيت زيتون بكر ممتاز"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية).","انزع الأوراق الخارجية عن رأسي القرنبيط. قصّ طرف الساق لتحصل على قاعدة مسطحة.","قطّع كل رأس قرنبيط إلى شرائح بسماكة 1 بوصة للحصول على شرائح القرنبيط.","ضع شرائح القرنبيط على صينية خبز. ادهن الجانبين بـ 1 ملعقة كبيرة من زيت الزيتون وتبّلها بملح الكوشر والفلفل الأسود.","اشوِ شرائح القرنبيط حتى تصبح ذهبية اللون وطرية، نحو 20 دقيقة.","أثناء شواء القرنبيط، حضّر صلصة التشيميتشوري. في وعاء، اخلط البقدونس والكزبرة الخضراء المفرومين ناعمًا والثوم المفروم والأوريجانو المجفف ورقائق الفلفل الأحمر وخل النبيذ الأحمر وزيت الزيتون البكر الممتاز وملح الكوشر والفلفل الأسود. اخفقها حتى تمتزج جيدًا.","عندما تنضج شرائح القرنبيط، انقلها إلى أطباق التقديم.","اسكب صلصة التشيميتشوري بسخاء فوق كل شريحة قرنبيط."])))
O.append(R(6516194,None,
("سلطة الشمندر المشوي والتفاح وجبن كيسو فريسكو","سلطة لذيذة تتيح لكم إدخال بعض منتجات الخريف مثل الشمندر.","4","1 كوب",
["1 ملعقة صغيرة زيت الكانولا","3 حبات شمندر صغيرة (نحو 12 أونصة إجمالًا)","1 ملعقة كبيرة عصير ليمون أخضر طازج","2 ملعقة صغيرة زيت الأفوكادو","¼ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود (مجروش)","2 كوب تفاح جولدن ديليشس (مقشر ومقطع مكعبات (مكعبات بحجم ½ بوصة))","1 ملعقة كبيرة كزبرة خضراء (مفرومة ناعمًا)","1 ملعقة كبيرة جبن كيسو فريسكو (مفتت)","¼ كوب بصل أصفر (شرائح)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية).","افرك الشمندر بزيت الكانولا مع التأكد من تغطية السطح بالكامل. اثقب الشمندر في عدة مواضع ليتخلله الحرارة ويُسرَّع الطهي. ضع الشمندر في طبق خبز صغير وغطِّه بإحكام بورق الألمنيوم. اشوِ الشمندر 1 ساعة و10 دقائق حتى تتمكن من غرز الشوكة في لبّه بسهولة. أخرجه من الفرن وضع الشمندر مباشرة في وعاء فيه ماء مثلج. سيبرد الشمندر بسرعة وتتوقف عملية الطهي وتصبح إزالة القشر أسهل بكثير. عندما يبرد الشمندر، انزع القشر بمنديل ورقي. قطّع الشمندر إلى مكعبات بحجم ½ بوصة وضعه جانبًا.","ضع زيت الأفوكادو وعصير الليمون الأخضر والملح والفلفل الأسود في وعاء واخفقها بقوة لمدة 30 ثانية لتحضير الصلصة. ضعها جانبًا.","في وعاء منفصل، ضع التفاح و2 كوب من مكعبات الشمندر والكزبرة الخضراء وجبن كيسو فريسكو والبصل وقلّب برفق. أضف الصلصة وقلّب مرة أخرى. الآن أصبحت جاهزة للتقديم. بالهناء والعافية!"])))
O.append(R(6517612,
("Ensalada italiana de frijoles y hojas verdes","Los frijoles con verduras de hoja son una comida o guarnición italiana clásica. En esta versión apta para personas con diabetes, el jamón curado se sustituye por tocino de pavo y salchicha de pollo. Se mezclan con hojas verdes tiernas y frijoles cannellini para hacer una ensalada. Es una versión contundente y fresca de un clásico mediterráneo.","4","1 taza de hojas verdes para ensalada + 1 onza de salchicha de pollo",
["2 rebanadas de tocino de pavo (cortadas en trozos de ½ pulgada)","2 salchichas de pollo enteras con condimento italiano (cortadas en rodajas de ½ pulgada)","4 tazas de mezcla de hojas verdes nutritivas (power greens)","1/2 taza de frijoles cannellini bajos en sodio (enjuagados y escurridos)","1/4 de taza de cebolla morada (en rodajas)","2 cucharadas de aceite de oliva extra virgen","1 cucharada de vinagre balsámico blanco","2 dientes de ajo (picados)","1/4 de cucharadita de pimienta negra","1/8 de cucharadita de sal kosher","2 cucharadas de queso parmesano (en láminas)"],
["En una sartén grande, cocine el tocino de pavo hasta que esté crujiente y la salchicha hasta que esté dorada.","Coloque las hojas verdes, los frijoles cannellini y las cebollas en un tazón grande.","En un tazón pequeño, bata el aceite de oliva, el vinagre, el ajo y la pimienta negra. Rocíe sobre la ensalada y mezcle para cubrir las hojas verdes. Espolvoree con el queso parmesano."]),
("سلطة الفاصوليا والخضار الورقية الإيطالية","الفاصوليا مع الخضار الورقية وجبة أو طبق جانبي إيطالي كلاسيكي. في هذه النسخة المناسبة لمرضى السكري، استُبدل اللحم المقدد المعالج بلحم الديك الرومي المقدد ونقانق الدجاج. تُخلط مع الخضار الورقية الصغيرة وفاصوليا كانيليني وتُحضَّر على شكل سلطة. إنها لمسة مشبعة ومنعشة على أحد أطباق البحر المتوسط الكلاسيكية.","4","1 كوب خضار ورقية للسلطة + 1 أونصة نقانق دجاج",
["2 شريحة لحم ديك رومي مقدد (مقطعة إلى قطع بحجم ½ بوصة)","2 قطعة نقانق دجاج كاملة بتوابل إيطالية (مقطعة إلى دوائر بسماكة ½ بوصة)","4 كوب خضار ورقية مشكلة غنية بالعناصر الغذائية (باور جرينز)","½ كوب فاصوليا كانيليني قليلة الصوديوم (مشطوفة ومصفاة)","¼ كوب بصل أحمر (شرائح)","2 ملعقة كبيرة زيت زيتون بكر ممتاز","1 ملعقة كبيرة خل بلسميك أبيض","2 فص ثوم (مفروم)","¼ ملعقة صغيرة فلفل أسود","⅛ ملعقة صغيرة ملح كوشر","2 ملعقة كبيرة جبن بارميزان (مقشّر شرائح رقيقة)"],
["في مقلاة كبيرة، اطهِ لحم الديك الرومي المقدد حتى يصبح مقرمشًا والنقانق حتى تتحمّر.","ضع الخضار الورقية وفاصوليا كانيليني والبصل في وعاء كبير.","في وعاء صغير، اخفق زيت الزيتون والخل والثوم والفلفل الأسود معًا. رُشَّه فوق السلطة وقلّب لتغطية الخضار الورقية. رُشَّ جبن البارميزان."])))
O.append(R(6518949,
("Salsa de tomate y calabacín","Esta salsa de tomate y calabacín es una opción versátil y nutritiva que celebra los sabores de los productos frescos de temporada. Disfrute de su textura crujiente y su sabor vibrante como un delicioso complemento de sus comidas o como botana por sí sola.","4","1/2 taza",
["2 tomates roma (tipo pera) grandes (en cubitos)","1 calabacín pequeño (en cubitos muy pequeños)","1/4 de taza de cebolla morada (picada muy fina)","1/4 de taza de cilantro fresco (picado)","1 chile jalapeño pequeño (sin semillas y picado muy fino)","2 dientes de ajo (picados)","2 cucharadas de jugo fresco de limón","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["En un tazón, mezcle los tomates en cubitos, el calabacín en cubitos, la cebolla morada picada finamente, el cilantro picado y el chile jalapeño picado muy fino. Agregue el ajo picado a la mezcla. Rocíe el jugo fresco de limón sobre los ingredientes. Sazone la salsa con sal y pimienta.","Mezcle suavemente todos los ingredientes hasta que estén bien integrados y cubiertos con el jugo de limón y los condimentos.","Deje reposar la salsa unos 10 a 15 minutos para que se mezclen los sabores. Ajuste el sazonado a su gusto."]),
("صلصة الطماطم والكوسا","صلصة الطماطم والكوسا هذه خيار متعدد الاستخدامات ومغذٍّ يحتفي بنكهات المنتجات الطازجة الموسمية. استمتعوا بقوامها المقرمش ومذاقها النابض بالحياة كإضافة لذيذة إلى وجباتكم أو كوجبة خفيفة بمفردها.","4","½ كوب",
["2 حبة طماطم روما (كمثرية الشكل) كبيرة (مقطعة مكعبات)","1 حبة كوسا صغيرة (مقطعة مكعبات صغيرة جدًا)","¼ كوب بصل أحمر (مفروم ناعمًا)","¼ كوب كزبرة خضراء طازجة (مفرومة)","1 حبة هالابينو صغيرة (منزوعة البذور ومفرومة ناعمًا)","2 فص ثوم (مفروم)","2 ملعقة كبيرة عصير ليمون أخضر طازج","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["في وعاء خلط، اخلط الطماطم المقطعة مكعبات والكوسا المقطعة مكعبات والبصل الأحمر المفروم ناعمًا والكزبرة الخضراء المفرومة والهالابينو المفروم. أضف الثوم المفروم إلى الخليط. رُشَّ عصير الليمون الأخضر الطازج فوق المكونات. تبّل الصلصة بالملح والفلفل.","قلّب جميع المكونات برفق حتى تمتزج جيدًا وتتغطى بعصير الليمون الأخضر والتوابل.","اترك الصلصة نحو 10 إلى 15 دقيقة لتتمازج النكهات. عدّل التتبيل حسب ذوقك."])))
O.append(R(6519498,
("Paletas heladas de yogur con miel, vainilla y frambuesa","Estas paletas heladas de yogur con miel, vainilla y frambuesa son una forma cremosa de refrescarse. Aptas para personas con diabetes, son un postre aprobado por los niños, perfecto para el verano.","4","1 paleta",
["1 taza de yogur griego natural sin grasa","1 taza de frambuesas congeladas","1 cucharada de miel","1 cucharadita de extracto de vainilla"],
["En una licuadora, haga un puré con el yogur y las frambuesas.","Una vez licuado, agregue la miel y la vainilla a la mezcla. Licúe bien.","Vierta la mezcla en moldes para paletas. Congele durante 8 horas o toda la noche."]),
("مثلجات الزبادي بالعسل والفانيليا وتوت العليق","مثلجات الزبادي بالعسل والفانيليا وتوت العليق هذه طريقة كريمية للانتعاش. وهي مناسبة لمرضى السكري، وحلوى يحبها الأطفال ومثالية في الصيف.","4","1 مثلجة",
["1 كوب زبادي يوناني سادة خالٍ من الدسم","1 كوب توت عليق مجمد","1 ملعقة كبيرة عسل","1 ملعقة صغيرة خلاصة الفانيليا"],
["في الخلاط، اهرس الزبادي وتوت العليق.","بعد الخلط، اسكب العسل والفانيليا في الخليط. اخلط جيدًا.","اسكب الخليط في قوالب المثلجات. جمّده لمدة 8 ساعات أو طوال الليل."])))
O.append(R(6520204,
("Hummus de pesto y limón","Disfrute este hummus como dip para botanear con verduras sin almidón, pan pita integral o galletas integrales.","5","1/4 de taza",
["1 lata (de 14.5 onzas) de garbanzos (escurridos y enjuagados)","2 cucharadas de salsa pesto de frasco","2 cucharadas de jugo de limón (de 1 limón mediano)","1/2 cucharadita de pimienta negra recién molida"],
["Agregue todos los ingredientes a un procesador de alimentos o licuadora y mezcle hasta obtener una consistencia suave."]),
("حمّص بالبيستو والليمون","استمتعوا بهذا الحمّص كغموس لتناول وجبة خفيفة مع الخضار غير النشوية أو خبز بيتا القمح الكامل أو البسكويت المملح من الحبوب الكاملة.","5","¼ كوب",
["1 علبة (14.5 أونصة) حمّص (مصفى ومشطوف)","2 ملعقة كبيرة صلصة بيستو معلبة","2 ملعقة كبيرة عصير ليمون (من 1 ليمونة متوسطة)","½ ملعقة صغيرة فلفل أسود مطحون طازجًا"],
["ضع جميع المكونات في محضّرة طعام أو خلاط واخلطها حتى تصبح ناعمة."])))
O.append(R(6520840,
("Ensalada de espinaca, aguacate y frutos rojos de verano","Esta ensalada de superalimentos está repleta de antioxidantes y sabores vivos, propios del verano. Acompáñela con un platillo de pollo a la parrilla, como estas Fajitas de pollo a la parrilla con limón, o con pescado, como este Salmón a la parrilla con salsa de mango y tomate. ¿Busca una forma más fácil de preparar el aderezo de ensalada? Agregue todos los ingredientes del aderezo a un frasco con tapa. Enrosque bien la tapa y agite hasta que todo esté integrado. Si prepara esta ensalada con anticipación, espere para agregar el aderezo justo antes de servir.","8","1 taza",
["10 onzas de espinaca baby fresca","1 taza de fresas en cubitos o rebanadas","1/2 taza de arándanos azules","1 aguacate mediano (en cubitos)","1/3 de taza de cebolla morada en cubitos finos o en rebanadas","2 cucharadas de aceite de oliva","2 cucharadas de vinagre balsámico blanco o vinagre de champán","1 cucharadita de miel","1 cucharada de jugo de limón (exprimido)","1 diente de ajo (picado)","1/4 de cucharadita de pimienta negra"],
["Coloque la espinaca, las fresas, los arándanos azules, el aguacate y la cebolla en una ensaladera grande.","En un tazón pequeño, bata el aceite de oliva, el vinagre, la miel, el jugo de limón, el ajo y la pimienta negra.","Vierta el aderezo sobre la ensalada y mezcle para cubrir de manera uniforme."]),
("سلطة السبانخ والأفوكادو وتوت الصيف","هذه السلطة من الأطعمة الخارقة غنية بمضادات الأكسدة والنكهات الصيفية النضرة. قدّموها مع طبق دجاج مشوي، مثل فاهيتا الدجاج المشوي بالليمون الأخضر هذه، أو مع السمك، مثل سلمون مشوي بصلصة المانجو والطماطم هذا. هل تبحثون عن طريقة أسهل لتحضير صلصة السلطة؟ ضعوا جميع مكونات الصلصة في برطمان بغطاء. أحكموا إغلاق الغطاء ورجّوه جيدًا حتى تمتزج المكونات. وإذا كنتم تحضّرون هذه السلطة مسبقًا، فانتظروا حتى قبيل التقديم مباشرة لإضافة الصلصة.","8","1 كوب",
["10 أونصات سبانخ صغيرة الأوراق طازجة","1 كوب فراولة مقطعة مكعبات أو شرائح","½ كوب توت أزرق","1 حبة أفوكادو متوسطة (مقطعة مكعبات)","⅓ كوب بصل أحمر مقطع مكعبات صغيرة جدًا أو شرائح","2 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة خل بلسميك أبيض أو خل الشمبانيا","1 ملعقة صغيرة عسل","1 ملعقة كبيرة ليمون أخضر (معصور)","1 فص ثوم (مفروم)","¼ ملعقة صغيرة فلفل أسود"],
["ضع السبانخ والفراولة والتوت الأزرق والأفوكادو والبصل في وعاء سلطة كبير.","في وعاء صغير، اخفق زيت الزيتون والخل والعسل وعصير الليمون الأخضر والثوم والفلفل الأسود معًا.","اسكب الصلصة فوق السلطة وقلّب لتغطيتها بالتساوي."])))
O.append(R(6520930,
("Champiñones rellenos de pavo y espinaca","Suba de nivel su juego de aperitivos con nuestros champiñones rellenos de pavo y espinaca, una sinfonía sabrosa que convierte los champiñones cremini comunes en maravillas de un solo bocado. Estas pequeñas potencias presentan champiñones cremini que acunan una animada mezcla de espinaca fresca, pavo molido magro y un toque de parmesano, para una versión apta para personas con diabetes de un clásico.","8","2 champiñones rellenos",
["2 rocíos, 0.5 g de aceite en aerosol antiadherente","1/2 libra de pavo molido magro","1/4 de taza de cebolla (picada en cubitos muy pequeños)","2 dientes de ajo (picados)","1 taza de espinaca baby (picada)","16 champiñones cremini (baby bella) grandes (limpios y sin tallos)","1/4 de taza de queso parmesano (rallado)","1/2 cucharadita de orégano seco","1/2 cucharadita de romero seco","1/2 cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["Precaliente el horno a 375 °F y prepare una bandeja para hornear forrándola con papel pergamino o engrasándola ligeramente con aceite en aerosol.","En una sartén a fuego medio, cocine el pavo molido magro, desmenuzándolo en trozos pequeños, hasta que esté dorado y bien cocido. Escurra el exceso de grasa.","En la misma sartén, agregue la cebolla picada en cubitos finos y el ajo picado, y saltee de 2 a 3 minutos hasta que desprendan aroma y se ablanden ligeramente.","Agregue la espinaca fresca picada a la sartén y cocine otros 2 a 3 minutos, hasta que se marchite y se evapore el exceso de humedad.","Incorpore el queso parmesano rallado, el orégano seco y el romero seco. Sazone la mezcla con sal y pimienta. Mezcle bien y deje enfriar un poco.","Tome los champiñones limpios y úntelos o rocíelos ligeramente con aceite en aerosol o aceite de oliva. Colóquelos en la bandeja preparada con las laminillas hacia arriba.","Rellene cada sombrero de champiñón con la mezcla de pavo y espinaca, presionando ligeramente para compactarla.","Hornee los champiñones rellenos en el horno precalentado durante unos 15 a 20 minutos, o hasta que los champiñones estén suaves y el relleno esté caliente y ligeramente dorado.","Saque los champiñones rellenos del horno y déjelos enfriar unos minutos antes de servir."]),
("فطر محشو بالديك الرومي والسبانخ","ارتقوا بمقبلاتكم مع فطر الديك الرومي والسبانخ المحشو، وهو سيمفونية لذيذة تحوّل فطر الكريميني العادي إلى قطع رائعة بحجم اللقمة. تضم هذه القطع الصغيرة القوية فطر كريميني يحتضن مزيجًا نابضًا من السبانخ الطازجة ولحم الديك الرومي المفروم الخالي من الدهون ولمسة من البارميزان، لتقدّم نسخة مناسبة لمرضى السكري من طبق كلاسيكي.","8","2 حبة فطر محشوة",
["2 بخّة، 0.5 غرام بخّاخ طهي غير لاصق","½ رطل لحم ديك رومي مفروم قليل الدسم","¼ كوب بصل (مقطع مكعبات صغيرة جدًا)","2 فص ثوم (مفروم)","1 كوب سبانخ صغيرة الأوراق (مفرومة)","16 حبة فطر كريميني (بيبي بيلا) كبيرة (منظفة ومنزوعة السيقان)","¼ كوب جبن بارميزان (مبشور)","½ ملعقة صغيرة أوريجانو مجفف","½ ملعقة صغيرة إكليل الجبل المجفف","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية) وجهّز صينية خبز ببطانة من ورق الزبدة أو بدهنها قليلًا ببخّاخ الطهي.","في مقلاة على نار متوسطة، اطهِ لحم الديك الرومي المفروم قليل الدسم مع تفتيته إلى قطع صغيرة حتى يتحمّر وينضج تمامًا. تخلّص من الدهن الزائد.","في المقلاة نفسها، أضف البصل المقطع مكعبات صغيرة والثوم المفروم وقلّبهما لمدة 2 إلى 3 دقائق حتى تفوح رائحتهما ويلينا قليلًا.","أضف السبانخ الطازجة المفرومة إلى المقلاة واطهِها 2 إلى 3 دقائق إضافية حتى تذبل ويتبخر أي سائل زائد.","أضف جبن البارميزان المبشور والأوريجانو المجفف وإكليل الجبل المجفف وحرّك. تبّل الخليط بالملح والفلفل. اخلط جيدًا واتركه يبرد قليلًا.","خذ الفطر المنظف وادهنه أو رُشَّه قليلًا ببخّاخ الطهي أو بزيت الزيتون. رتّبه على الصينية المجهزة بحيث يكون جانب الشفرات إلى الأعلى.","احشُ كل قبعة فطر بخليط الديك الرومي والسبانخ، مع الضغط عليه قليلًا لتعبئته جيدًا.","اخبز الفطر المحشو في الفرن المسخّن مسبقًا نحو 15 إلى 20 دقيقة أو حتى يصبح الفطر طريًا ويسخن الحشو جيدًا ويتحمّر قليلًا.","أخرج الفطر المحشو من الفرن واتركه يبرد بضع دقائق قبل التقديم."])))
O.append(R(6521634,None,
("إجاص مشوي بالقرفة","الفاكهة ختام رائع للوجبة. وبتجربة شواء الفاكهة وتحميصها، يمكنكم إبراز أقصى نكهة فيها. يمكن تحضير هذه الوصفة بسهولة بالتفاح أيضًا.","4","½ حبة إجاص",
["1 ملعقة كبيرة سمن نباتي (مارجرين) Smart Balance","½ ملعقة صغيرة قرفة مطحونة","2 ملعقة كبيرة بديل سكر بني قليل السعرات","2 حبة إجاص أنجو متوسطة ((نحو 6.5 أونصات للحبة) مقشرة ومنزوعة القلب ومقسومة إلى نصفين)","1 ملعقة كبيرة جوز (مفروم)","¼ كوب ماء"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية).","في وعاء صغير (باستخدام أصابعك) اخلط السمن النباتي والقرفة والسكر البني. أضف الجوز وامزجه.","رتّب حبات الإجاص بحيث يكون الجانب المقطوع إلى الأعلى في طبق خبز زجاجي مربع قياس 8 بوصات. اسكب ¼ كوب من الماء في قاع الطبق.","وزّع خليط السكر البني بالتساوي على أنصاف الإجاص وضعه في وسط كل نصف.","اخبز حتى يصبح الإجاص طريًا ويبدأ بالتحمّر، نحو 45 دقيقة."])))
O.append(R(6523355,None,
("فاصوليا مخبوزة نباتية","يمكنكم تحضير هذه الفاصوليا المخبوزة بفاصوليا بينتو إذا كنتم تفضلونها على الفاصوليا البيضاء الصغيرة (نيفي).","6","⅓ كوب",
["1 رشة، 0.25 غرام بخّاخ طهي غير لاصق","1 حبة بصل كبيرة (مقطعة مكعبات)","2 علبة (14.5 أونصة) فاصوليا بيضاء صغيرة (نيفي) أو فاصوليا غريت نورذرن (مشطوفة ومصفاة)","1 كوب مرق خضار قليل الصوديوم","¼ كوب كاتشب بدون ملح مضاف","¼ كوب بديل سكر بني قليل السعرات","1 ملعقة كبيرة صلصة صويا قليلة الصوديوم","1 ملعقة كبيرة خردل ديجون","1 ملعقة صغيرة مسحوق الثوم"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). رُشَّ صينية خبز قياس 8 بوصات ببخّاخ الطهي. ضعها جانبًا.","اخلط جميع المكونات في وعاء كبير. اسكبها في صينية الخبز المجهزة. غطِّها واخبزها لمدة 45 دقيقة. اكشف الغطاء واخبز 30 إلى 40 دقيقة إضافية أو حتى يثخن الخليط."])))
dump(O,"../out_c14_part4.json")
