from h import *

add(6036850, ar=T("سلطة الدجاج بالفراولة","تمنح الفراولة وصلصة بذور الخشخاش هذه السلطة المكوّنة من 5 مكوّنات مذاقًا حلوًا منعشًا مع بقائها قليلة الكربوهيدرات.","4","2 كوب سلطة، 1½ ملعقة كبيرة صلصة",
["5½ أونصة سبانخ صغيرة عضوية","4 ملعقة كبيرة لوز نيئ (مقطع شرائح)","2 كوب فراولة (مقطعة شرائح)","2 كوب صدر دجاج مطبوخ (مقطع مكعبات)","6 ملعقة كبيرة صلصة بذور الخشخاش خالية من الدسم"],
["في وعاء سلطة، اخلط جميع مكوّنات السلطة معًا.","صبّ الصلصة فوق السلطة وقلّبها حتى تتغطى."]))

add(6041604,
es=T("Sándwich de verduras y hummus","Esta deliciosa y crujiente ensalada es una excelente opción saludable para un almuerzo sin cocinar. No solo es apta para personas con diabetes, ¡también es vegana!","2","1 sándwich",
["4 rebanadas de pan integral (en rebanadas finas)","1/3 taza de hummus","1 taza de hojas verdes para ensalada","1/2 pepino mediano (en rodajas finas)","1/2 pimiento mediano (en rodajas finas)","1 tomate roma (pera) mediano (en rodajas finas)","2 cucharadas de aceitunas Kalamata (sin hueso y en rodajas)","1 cucharada de aceite de oliva","1/8 cucharadita de pimienta negra"],
["Coloque las rebanadas de pan integral o de trigo integral sobre la superficie de trabajo.","Unte una capa generosa de hummus en cada rebanada.","Divida las hojas verdes mixtas en partes iguales y colóquelas sobre dos rebanadas de pan.","Cubra las hojas verdes con las rodajas de pepino, las rodajas de pimiento, las rodajas de tomate, las rodajas de cebolla morada y las aceitunas Kalamata.","Rocíe aceite de oliva extra virgen sobre las capas de verduras. Sazone con pimienta negra.","Coloque las rebanadas de pan restantes, con el lado del hummus hacia abajo, sobre las verduras para formar los sándwiches. Presione suavemente para sujetar las capas."]),
ar=T("ساندويتش الخضار والحمص","هذه السلطة المقرمشة اللذيذة خيار صحي رائع لوجبة غداء لا تحتاج إلى طهي. إنها مناسبة لمرضى السكري، كما أنها نباتية بالكامل!","2","1 ساندويتش",
["4 شريحة خبز حبوب كاملة (رقيقة)","⅓ كوب حمص","1 كوب أوراق سلطة خضراء","½ حبة خيار متوسطة (مقطعة شرائح رقيقة)","½ حبة فلفل رومي متوسطة (مقطعة شرائح رقيقة)","1 حبة طماطم رومي (برقوقية) متوسطة (مقطعة شرائح رقيقة)","2 ملعقة كبيرة زيتون كالاماتا (منزوع النوى ومقطع شرائح)","1 ملعقة كبيرة زيت زيتون","⅛ ملعقة صغيرة فلفل أسود"],
["رتّب شرائح خبز الحبوب الكاملة أو القمح الكامل.","افرد طبقة سخية من الحمص على كل شريحة.","قسّم أوراق السلطة الخضراء المشكلة بالتساوي وضعها على شريحتين من الخبز.","ضع فوق الأوراق الخضراء شرائح الخيار وشرائح الفلفل الرومي وشرائح الطماطم وشرائح البصل الأحمر وزيتون كالاماتا.","رشّ زيت الزيتون البكر الممتاز فوق طبقات الخضار. تبّل بالفلفل الأسود.","ضع شرائح الخبز المتبقية، بحيث يكون جانب الحمص لأسفل، فوق الخضار لتكوين الساندويتشات. اضغط برفق لتثبيت الطبقات."]))

add(6042443, ar=T("بطاطس حمراء ريفية مع فاصولياء خضراء","هذا الطبق من الخضار المشكلة مثال على كيفية زيادة تناول الخضار مع التحكم في كمية الكربوهيدرات. قدّمه إلى جانب طبق رئيسي بروتيني مع خضار إضافية مثل أفخاذ الدجاج المطهوة ببطء مع الفطر أو شرائح لحم الخنزير المدخنة مع الطماطم.","6","حوالي ¾ كوب",
["1 بخّة، 0.25 غرام رذاذ طهي غير لاصق","1 رطل فاصولياء خضراء طازجة","6 حبات بطاطس حمراء متوسطة (مقطعة إلى ثمانية أجزاء)","2 ملعقة كبيرة زيت زيتون (تُستخدم على مرحلتين)","½ ملعقة صغيرة ملح الثوم (يُستخدم على مرحلتين)","¼ ملعقة صغيرة فلفل أسود (يُستخدم على مرحلتين)","¼ ملعقة صغيرة بقدونس مجفف"],
["سخّن الفرن مسبقًا على 400 درجة فهرنهايت (205 درجة مئوية). رشّ صينية خَبز برذاذ الطهي.","في وعاء متوسط، اخلط البطاطس مع 1 ملعقة كبيرة زيت زيتون و¼ ملعقة صغيرة ملح الثوم و⅛ ملعقة صغيرة فلفل و¼ ملعقة صغيرة بقدونس.","ضع البطاطس على نصف الصينية واخبزها لمدة 15 دقيقة.","في وعاء متوسط، اخلط الفاصولياء الخضراء مع 1 ملعقة كبيرة زيت زيتون و¼ ملعقة صغيرة ملح الثوم و⅛ ملعقة صغيرة فلفل.","بعد أن تُخبز البطاطس لمدة 15 دقيقة، أضف الفاصولياء الخضراء إلى النصف الآخر من الصينية. اخبز البطاطس والفاصولياء الخضراء لمدة 20 دقيقة إضافية."]))

add(6045990, ar=T("خليط وجبة خفيفة بعناقيد بذور القرع","هل مللت من خليط المكسرات التقليدي؟ كن مبدعًا في المطبخ وجرّب خليط الوجبة الخفيفة الموسمي هذا بدلًا منه!","8","⅓ كوب",
["½ كوب بذور قرع مملحة (بقشرها)","¼ كوب فول سوداني غير مملح","2 كوب حبوب إفطار عنقودية عالية الألياف (حوالي 4 أونصات)","¼ كوب زبيب ذهبي، أو توت بري مجفف","2 ملعقة كبيرة رقائق شوكولاتة صغيرة"],
["ضع مقلاة كبيرة غير لاصقة على نار متوسطة إلى عالية حتى تسخن. اطهِ بذور القرع والفول السوداني لمدة 2 إلى 3 دقائق أو حتى يبدأ لونها بالاحمرار الخفيف، مع التحريك المتكرر. ضعها جانبًا على منديل ورقي في طبقة رقيقة لتبرد بسرعة، نحو 5 دقائق.","اخلط خليط بذور القرع مع بقية المكوّنات."]))

add(6047124,
es=T("Frittata de champiñones","Los champiñones de sabor terroso son la base de esta frittata apta para personas con diabetes. Las frittatas son platos a base de huevo, a medio camino entre una tortilla y un quiche sin masa.","4","1/4 de la frittata",
["2 tazas de sustituto de huevo","1/4 cucharadita de sal","1/2 cucharadita de pimienta negra","1 cucharadita de tomillo seco","1 cucharada de aceite de oliva","1/2 taza de cebolla (en cubos)","1 taza de champiñones (de su preferencia) (en rodajas)","3 cucharadas de queso parmesano (rallado)"],
["Precaliente el horno a 375 grados F.","En un tazón, bata el sustituto de huevo con la sal, la pimienta y el tomillo seco.","Caliente el aceite de oliva en una sartén que pueda ir al horno a fuego medio.","Agregue la cebolla en cubos y cocine hasta que se ablande.","Agregue los champiñones en rodajas a la sartén y cocine hasta que suelten su humedad, unos 6 minutos.","Vierta los huevos batidos sobre la mezcla de champiñones.","Deje que los bordes de la frittata cuajen, levantándolos con una espátula para que el huevo sin cocer fluya por debajo.","Cuando los bordes estén cuajados, espolvoree el queso parmesano rallado de manera uniforme por encima.","Pase la sartén al horno precalentado y hornee durante unos 10–12 minutos o hasta que la frittata esté cocida por dentro y la parte superior esté dorada.","Retire del horno y déjela enfriar unos minutos antes de cortarla."]),
ar=T("فريتاتا الفطر","الفطر ذو النكهة الترابية هو أساس هذه الفريتاتا المناسبة لمرضى السكري. الفريتاتا أطباق تعتمد على البيض، وهي مزيج بين العجّة والكيش بدون عجينة.","4","¼ الفريتاتا",
["2 كوب بديل البيض","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة زعتر مجفف","1 ملعقة كبيرة زيت زيتون","½ كوب بصل (مقطع مكعبات)","1 كوب فطر (من اختيارك) (مقطع شرائح)","3 ملعقة كبيرة جبن بارميزان (مبشور)"],
["سخّن الفرن مسبقًا على 375 درجة فهرنهايت (190 درجة مئوية).","في وعاء، اخفق بديل البيض مع الملح والفلفل والزعتر المجفف.","سخّن زيت الزيتون في مقلاة تصلح للفرن على نار متوسطة.","أضف البصل المقطع مكعبات واطهِه حتى يلين.","أضف الفطر المقطع شرائح إلى المقلاة واطهِه حتى يفقد رطوبته، نحو 6 دقائق.","صبّ البيض المخفوق فوق خليط الفطر.","اترك حواف الفريتاتا تتماسك، مع رفعها بملعقة التقليب (السباتولا) ليتدفق البيض غير المطبوخ تحتها.","عندما تتماسك الحواف، انثر جبن البارميزان المبشور بالتساوي على الوجه.","انقل المقلاة إلى الفرن المسخّن مسبقًا واخبزها لمدة 10–12 دقيقة تقريبًا أو حتى تنضج الفريتاتا ويصبح وجهها ذهبي اللون.","أخرجها من الفرن واتركها تبرد بضع دقائق قبل تقطيعها."]))

add(6047974,
es=T("Sopa cremosa de cangrejo de la costa este de Maryland","Maryland es famoso por sus cangrejos y los muchos platos especiales que se preparan con ellos. La sopa cremosa de cangrejo es un clásico de la costa este, generalmente un plato rico e indulgente lleno de crema y mantequilla. Esta versión más ligera usa media crema (half and half) y caldo espesado con maicena para lograr la misma textura cremosa con mucha menos grasa y calorías. Lo ideal es usar carne de cangrejo en trozos frescos, pero se pueden usar otras variedades o cangrejo de imitación.","7","1 taza",
["1 cucharada de mantequilla sin sal","1 cebolla mediana (en cubos)","1/2 libra de carne de cangrejo en trozos","4 tazas de caldo de mariscos o de pollo bajo en sodio","1 taza de media crema (half-and-half) (sin grasa)","2 cucharadas de maicena","1/4 cucharadita de condimento Old Bay","1/8 cucharadita de eneldo seco","1/8 cucharadita de pimienta negra"],
["Derrita la mantequilla en una olla grande a fuego moderado. Agregue la cebolla y cocine unos minutos, hasta que se ablande y quede transparente.","Agregue la carne de cangrejo. Cocine de 2 a 3 minutos, revolviendo constantemente.","Agregue el caldo de pollo y deje que la mezcla hierva. Reduzca el fuego a bajo.","En un tazón pequeño, mezcle la media crema (half & half) y la maicena. Bata hasta que quede suave. Agréguela a la sopa y aumente un poco el fuego, revolviendo constantemente hasta que la mezcla espese y hierva.","Agregue el eneldo, el condimento Old Bay y la pimienta a la sopa. Cocine de 5 a 10 minutos más. Sirva caliente."]),
ar=T("حساء كريمة السرطان من الساحل الشرقي لماريلاند","تشتهر ماريلاند بسرطان البحر والعديد من الأطباق الخاصة المصنوعة منه. حساء كريمة السرطان من كلاسيكيات الساحل الشرقي، وهو عادةً طبق غني وفاخر مليء بالكريمة والزبدة. تستخدم هذه النسخة الأخف نصف كريمة ونصف حليب (half and half) ومرقًا مُكثّفًا بنشا الذرة للحصول على القوام الكريمي نفسه بدهون وسعرات حرارية أقل بكثير. يُفضَّل لحم السرطان الطازج على شكل قطع كبيرة، ولكن يمكن استخدام أنواع أخرى أو سرطان بحر مقلّد.","7","1 كوب",
["1 ملعقة كبيرة زبدة غير مملحة","1 حبة بصل متوسطة (مقطعة مكعبات)","½ رطل لحم سرطان بحر على شكل قطع كبيرة","4 كوب مرق مأكولات بحرية أو دجاج قليل الصوديوم","1 كوب نصف كريمة ونصف حليب (half-and-half) (خالٍ من الدسم)","2 ملعقة كبيرة نشا الذرة","¼ ملعقة صغيرة توابل أولد باي","⅛ ملعقة صغيرة شبت مجفف","⅛ ملعقة صغيرة فلفل أسود"],
["ذوّب الزبدة في قدر كبير على نار متوسطة. أضف البصل واطهِه بضع دقائق حتى يلين ويصبح شفافًا.","أضف لحم السرطان. اطهِه من 2 إلى 3 دقائق مع التحريك المستمر.","أضف مرق الدجاج واترك الخليط حتى يغلي. خفّض الحرارة إلى منخفضة.","اخلط نصف الكريمة ونصف الحليب (half & half) مع نشا الذرة في وعاء صغير. اخفقهما حتى يصبحا ناعمين. أضفهما إلى الحساء وارفع الحرارة قليلًا، مع التحريك المستمر حتى يتكاثف الخليط ويغلي.","أضف الشبت وتوابل أولد باي والفلفل إلى الحساء. اطهِه لمدة 5-10 دقائق إضافية. قدّمه دافئًا."]))

add(6048241,
es=T("Pechuga de pollo cocida, 2 onzas","Información nutricional de 2 onzas de pechuga de pollo cocida.","1","2 onzas",["2 onzas de pechuga de pollo (sin piel, cocida)"],[]),
ar=T("صدر دجاج مطبوخ، 2 أونصة","المعلومات الغذائية لـ 2 أونصة من صدر الدجاج المطبوخ.","1","2 أونصة",["2 أونصة صدر دجاج (بدون جلد، مطبوخ)"],[]))

add(6050339,
es=T("Frijoles blancos ahumados con espinaca","¡Un toque del suroeste para los frijoles con verduras! Sírvalo con lomo de cerdo asado o falda de res a la parrilla. Puede sustituir la espinaca por acelga o col rizada (kale).","6","1 taza",
["2 cucharaditas de aceite de oliva","1 cebolla mediana (en cubos)","3 dientes de ajo (picados)","1 1/2 cucharaditas de pimentón ahumado","1 lata (15 onzas) de tomates asados al fuego (sin sal agregada)","1 lata (15 onzas) de frijoles cannellini (sin sal agregada, escurridos y enjuagados)","10 onzas de espinaca (sin tallos)","1 cucharada de vinagre balsámico","1/4 cucharadita de pimienta negra"],
["Caliente el aceite en una cacerola grande a fuego medio. Agregue la cebolla y saltee de 5 a 6 minutos. Agregue el ajo y el pimentón ahumado y saltee durante 1 minuto.","Agregue los tomates y cocine de 5 a 6 minutos. Agregue los frijoles y cocine durante 5 minutos. Agregue la espinaca y cocine hasta que se marchite. Incorpore el vinagre balsámico y la pimienta, y sirva."]),
ar=T("فاصولياء بيضاء مدخنة مع السبانخ","لمسة من الجنوب الغربي الأمريكي على الفاصولياء والخضروات الورقية! قدّمها مع فيليه لحم خنزير مشوي أو شريحة لحم بقر مشوية على الشواية. يمكنك استبدال السبانخ بالسلق السويسري أو الكرنب الأجعد (كيل).","6","1 كوب",
["2 ملعقة صغيرة زيت زيتون","1 حبة بصل متوسطة (مقطعة مكعبات)","3 فص ثوم (مفروم)","1½ ملعقة صغيرة بابريكا مدخنة","1 علبة (15 أونصة) طماطم مشوية على النار (بدون ملح مضاف)","1 علبة (15 أونصة) فاصولياء كانيليني (بدون ملح مضاف، مصفّاة ومغسولة)","10 أونصات سبانخ (منزوعة السيقان)","1 ملعقة كبيرة خل بلسمي","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الزيت في قدر كبير على نار متوسطة. أضف البصل وقلّبه لمدة 5 إلى 6 دقائق. أضف الثوم والبابريكا المدخنة وقلّبهما لمدة دقيقة واحدة.","أضف الطماطم واطهِها لمدة 5 إلى 6 دقائق. أضف الفاصولياء واطهِها لمدة 5 دقائق. أضف السبانخ واطهِها حتى تذبل. أضف الخل البلسمي والفلفل وحرّك، ثم قدّم."]))

add(6050475, ar=T("قرنبيط كريمي بالجبن","قرنبيط لم تتذوقه من قبل بهذه الطريقة! تصلح هذه الوصفة طبقًا جانبيًا رائعًا ليوم عيد الشكر. إنها أفضل لك من البطاطس بالجبن أو طاجن الفاصولياء الخضراء التقليدي، وبالنكهة الغنية نفسها!","10","½ كوب",
["10 كوب زهيرات قرنبيط (مفرومة فرمًا خشنًا، حوالي رأسين)","2 ملعقة صغيرة زيت زيتون بكر ممتاز","2 حبة بصل كبيرة (مفرومة)","3 فص ثوم (مفروم)","½ كوب دقيق متعدد الاستخدامات","3½ كوب حليب 1% دسم","½ ملعقة صغيرة ملح كوشر","¾ كوب جبن بارميزان (مبشور طازجًا)","3 ملعقة كبيرة بقدونس (مفروم ناعمًا جدًا)","½ ملعقة صغيرة فلفل أسود"],
["ضع 4 أرباع (كوارت) من الماء في قدر سعة 6 أرباع. أوصل الماء إلى الغليان. أضف القرنبيط واطهِه لمدة 10 إلى 12 دقيقة تقريبًا أو حتى يلين. صفِّه وضعه جانبًا.","في مقلاة كبيرة، ذوّب الزبدة على نار متوسطة إلى عالية. أضف البصل والثوم وقلّبهما لمدة 6 إلى 7 دقائق حتى يلينا، مع الحرص على ألا يتحول البصل والثوم إلى اللون البني. اخلط الدقيق مع الحليب واخفقهما حتى يصبحا ناعمين جدًا. أضفهما إلى البصل والثوم، واتركهما حتى يغليا بهدوء، واطهِهما لمدة دقيقتين. تبّل بالملح والفلفل. أضف الجبن مع الخفق، ثم اطوِ القرنبيط برفق. زيّن بالبقدونس."]))

add(6050561, ar=T("تفاح بالقرفة والزنجبيل على عود","طريقة مبتكرة لتقديم الحلوى. تضيف المكسرات المجروشة قرمشة ومظهرًا جذابًا. يمكنك أيضًا تقطيع التفاح إلى أرباع ووضع بضعة أنواع مختلفة على كل عود.","6","½ تفاحة",
["3 حبات تفاح ((غراني سميث أو فوجي أو روم أو غالا)، مقشرة ومنصّفة ومنزوعة القلب)","1 عصير ليمونة واحدة","1 ملعقة كبيرة جذر زنجبيل طازج (مفروم)","½ ملعقة صغيرة قرفة مطحونة","1 ملعقة كبيرة عسل","¼ كوب جوز أو بيكان (مجروش)","6 أسياخ خشبية أو معدنية"],
["ضع أنصاف التفاح وعصير الليمون والزنجبيل والقرفة والعسل في كيس قابل لإعادة الإغلاق وأغلقه بإحكام. قلّب الكيس لتغطية التفاح بالخليط واترك التفاح يتتبّل لمدة 30 دقيقة.","سخّن الشواية مسبقًا على حرارة متوسطة إلى عالية. أخرج التفاح من الكيس وضعه على الشواية. اشوِه لمدة 5–6 دقائق، مع قلبه مرة واحدة حتى يصبح ذهبي اللون من الخارج ودافئًا فقط من الداخل.","أخرج التفاح من الشواية، واتركه يبرد بضع دقائق، ثم قلّبه في الجوز المجروش. اضغط برفق.","اغرس سيخًا في كل نصف تفاحة وقدّم."]))

add(6050583, ar=T("خرشوف بالثوم وزيت الزيتون (Carciofi All’Aglio E Olio)","ملاحظة من إيمي ريولو: بالإضافة إلى قوامه الكريمي ونكهته الزبدية، يحتوي الخرشوف على مضادات أكسدة مفيدة للصحة. إذا لم تتعامل مع الخرشوف الطازج من قبل، فلا تتردد. خطوات تحضيره بسيطة، وبعد طهيه مرة واحدة ستصبح محترفًا. عندما يكون الخرشوف الصغير في موسمه، جرّب استخدامه، فهو ينضج في نصف المدة فقط. وعندما لا يكون الخرشوف الطازج في موسمه، استبدله بقلوب الخرشوف المعلبة قليلة الصوديوم أو المجمدة.","4","1 حبة خرشوف (أو 2 حبة خرشوف صغيرة)",
["12 حبة خرشوف صغير طازج","4 ملعقة كبيرة عصير ليمون (من ليمونتين متوسطتين، يُستخدم على مرحلتين)","3 ملعقة كبيرة زيت زيتون بكر ممتاز","4 فص ثوم (مفروم)","¼ ملعقة صغيرة ملح بحري","⅛ ملعقة صغيرة فلفل أسود (مطحون طازجًا)","⅛ ملعقة صغيرة رقائق الفلفل الحار الأحمر المجروش","1 ملعقة صغيرة بقدونس طازج (مفروم ناعمًا)"],
["انقع الخرشوف في الماء لتنظيفه؛ ثم صفِّه وكرّر ذلك حتى يصبح الماء صافيًا. انزع الأوراق الخارجية من النصف السفلي للخرشوف. اقطع الربع العلوي من الخرشوف (في هذه المرحلة يجب أن يبدو الخرشوف كالزهرة، وتكون كل الأوراق القاسية الداكنة قد أُزيلت، ولا يبقى سوى الأوراق الأفتح لونًا والأطرى). إذا بقيت أوراق خضراء داكنة قاسية، فقشّرها أيضًا. أضف عصير ليمونة واحدة إلى وعاء مملوء بالماء البارد، وضع الخرشوف المنظَّف فيه لمنع تغيّر لونه.","أوصل قدرًا كبيرًا من الماء إلى الغليان، وأضف الخرشوف المنظَّف. أعده إلى الغليان على نار عالية. خفّض الحرارة إلى متوسطة منخفضة واتركه يغلي بهدوء لمدة 25–30 دقيقة، أو حتى يلين. صفِّ الخرشوف جيدًا، وجفّفه بمنديل ورقي، وضعه جانبًا.","في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة. أضف الثوم وقلّبه حتى تفوح رائحته، نحو دقيقة واحدة. أضف الخرشوف، وقلّبه ليتغطى بالزيت، وتبّله بالملح والفلفل ورقائق الفلفل الحار الأحمر المجروش. انثر البقدونس وقدّمه دافئًا."]))

add(6051058,
es=T("Pastel de verduras","Relleno de verduras deliciosas y nutritivas, este pastel apto para personas con diabetes es una alternativa saludable que toda la familia puede disfrutar.","4","1/4 del pastel",
["1 cucharada de aceite de oliva","1 cebolla mediana (finamente picada)","2 zanahorias grandes (en cubos)","2 tallos de apio (en cubos)","6 onzas de tempeh (desmenuzado)","1 papa pequeña (pelada y en cubos)","1/4 taza de harina para todo uso","3 tazas de caldo de verduras bajo en sodio","1 cucharadita de tomillo seco","1/2 cucharadita de pimienta negra","1 taza de guisantes (chícharos) congelados","2 bollitos (biscuits) de masa refrigerada de suero de leche bajos en grasa (de 2 pulgadas, cortados en cuartos)"],
["Precaliente el horno a 375 grados F.","En una olla grande, caliente el aceite a fuego medio. Agregue la cebolla picada, las zanahorias en cubos y el apio en cubos. Saltee hasta que las verduras se ablanden, unos 5 minutos.","Incorpore el tempeh y la papa. Cocine de 3 a 4 minutos más.","Espolvoree la harina sobre la mezcla de verduras y revuelva para cubrir de manera uniforme. Cocine de 1 a 2 minutos para eliminar el sabor crudo de la harina.","Vierta poco a poco el caldo de verduras, revolviendo constantemente para evitar grumos. Agregue el tomillo seco, la pimienta y los guisantes congelados. Deje que la mezcla hierva a fuego lento y cocine hasta que la salsa espese, unos 5 minutos.","Retire la olla del fuego y deje que el relleno se enfríe un poco.","Con una cuchara, vierta el relleno de verduras en un molde cuadrado para hornear.","Cubra el relleno con los bollitos (biscuits).","Hornee en el horno precalentado de 10 a 15 minutos, hasta que los bollitos estén dorados. Corte en 4 porciones y sirva."]),
ar=T("فطيرة الخضار","هذه الفطيرة المناسبة لمرضى السكري مليئة بالخضار اللذيذة والمغذية، وهي بديل صحي يمكن لجميع أفراد العائلة الاستمتاع به.","4","¼ الفطيرة",
["1 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مفرومة ناعمًا)","2 حبة جزر كبيرة (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","6 أونصات تمبيه (مفتت)","1 حبة بطاطس صغيرة (مقشرة ومقطعة مكعبات)","¼ كوب دقيق متعدد الاستخدامات","3 كوب مرق خضار قليل الصوديوم","1 ملعقة صغيرة زعتر مجفف","½ ملعقة صغيرة فلفل أسود","1 كوب بازلاء مجمدة","2 قطعة بسكويت (بيسكويت) من عجينة اللبن الرائب المبردة قليلة الدسم (2 بوصة، مقطعة أرباعًا)"],
["سخّن الفرن مسبقًا على 375 درجة فهرنهايت (190 درجة مئوية).","في قدر كبير، سخّن الزيت على نار متوسطة. أضف البصل المفروم والجزر المقطع مكعبات والكرفس المقطع مكعبات. قلّبها حتى تلين الخضار، نحو 5 دقائق.","أضف التمبيه والبطاطس وحرّك. اطهِها لمدة 3–4 دقائق إضافية.","انثر الدقيق فوق خليط الخضار وحرّك لتغطيتها بالتساوي. اطهِها لمدة 1–2 دقيقة للتخلص من طعم الدقيق النيئ.","صبّ مرق الخضار تدريجيًا، مع التحريك المستمر لتجنب التكتل. أضف الزعتر المجفف والفلفل والبازلاء المجمدة. اترك الخليط حتى يغلي بهدوء واطهِه حتى تتكاثف الصلصة، نحو 5 دقائق.","ارفع القدر عن النار واترك الحشوة تبرد قليلًا.","اسكب حشوة الخضار بالملعقة في طبق خَبز مربع.","ضع قطع البسكويت فوق الحشوة.","اخبزها في الفرن المسخّن مسبقًا لمدة 10–15 دقيقة حتى يصبح البسكويت ذهبي اللون. قطّعها إلى 4 قطع وقدّم."]))
save(2)
