from h import *

add(6051334, ar=T("كوسا مشوية مع جبن الفيتا","الشواء طريقة سريعة وصحية لتناول المزيد من الخضار. هذه الوصفة لذيذة ببساطة وطبق جانبي سهل يمكن إضافته إلى أي وجبة. إذا بقي لديك شيء من هذه الوصفة، فستكون الكوسا المشوية رائعة في عجّة الإفطار في اليوم التالي.","6","نصف حبة كوسا",
["3 حبات كوسا متوسطة (مشقوقة نصفين بالطول (مقطوعة الأطراف))","1 ملعقة كبيرة زيت زيتون","¼ كوب جبن فيتا مفتت قليل الدسم"],
["سخّن الشواية مسبقًا على حرارة متوسطة إلى عالية.","رشّ زيت الزيتون بالتساوي على أنصاف الكوسا. اشوِ الكوسا 4-5 دقائق لكل جانب، حتى تلين.","أخرج الكوسا من الشواية وانثر جبن الفيتا على كل قطعة."]))

add(6052216,
es=T("Espagueti scampi de camarones con fideos de calabacín y tomates frescos",None,"4","1 taza",
["8 onzas de espagueti delgado","2 calabacines medianos","3 cucharadas de aceite de oliva extra virgen","1/2 cebolla amarilla grande (picada muy fina)","3 dientes de ajo (picados)","1/2 cucharadita de hojuelas de chile rojo triturado","1 libra de camarones grandes (pelados y desvenados)","2 cucharadas de perejil italiano (picado)","1 limón mediano","1/8 cucharadita de sal kosher","1 cucharadita de pimienta negra","1 pinta de tomates cherry (cortados por la mitad)","1 cucharada de queso parmesano (rallado)"],
["Hierva el espagueti según las instrucciones del paquete. Escurra y reserve en un tazón grande.","Use un espiralizador o un pelador juliana para hacer fideos de calabacín y reserve.","Caliente el aceite de oliva en una sartén grande a fuego medio. Agregue la cebolla, el ajo y las hojuelas de chile rojo. Cuando la cebolla esté translúcida, agregue los camarones y cocine hasta que estén rosados.","Retire del fuego, incorpore el perejil y mezcle para combinar. Exprima el jugo del limón sobre los camarones y sazone con sal y pimienta. Vierta los camarones y el líquido sobre el espagueti.","Agregue los fideos de calabacín y los tomates y mezcle hasta que el calabacín se marchite ligeramente.","Decore con queso parmesano."]),
ar=T("سباغيتي الجمبري سكامبي مع معكرونة الكوسا والطماطم الطازجة",None,"4","1 كوب",
["8 أونصات سباغيتي رفيعة","2 حبة كوسا متوسطة","3 ملعقة كبيرة زيت زيتون بكر ممتاز","½ حبة بصل أصفر كبيرة (مفروم ناعمًا)","3 فص ثوم (مفروم)","½ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","1 رطل جمبري كبير (مقشر ومنزوع الأحشاء)","2 ملعقة كبيرة بقدونس إيطالي (مفروم)","1 حبة ليمون متوسطة","⅛ ملعقة صغيرة ملح كوشر","1 ملعقة صغيرة فلفل أسود","1 باينت طماطم كرزية (مقطعة إلى نصفين)","1 ملعقة كبيرة جبن بارميزان (مبشور)"],
["اسلق السباغيتي حسب تعليمات العبوة. صفِّها وضعها جانبًا في وعاء كبير.","استخدم آلة تقطيع حلزونية أو مقشرة جوليان لتحضير معكرونة الكوسا، وضعها جانبًا.","سخّن زيت الزيتون في مقلاة كبيرة على نار متوسطة. أضف البصل والثوم ورقائق الفلفل الأحمر. عندما يصبح البصل شفافًا، أضف الجمبري واطهِه حتى يصبح ورديًا.","ارفعه عن النار، وأضف البقدونس، وقلّب للمزج. اعصر الليمون فوق الجمبري وتبّل بالملح والفلفل. صبّ الجمبري مع سائله فوق السباغيتي.","أضف معكرونة الكوسا والطماطم وقلّب حتى تذبل الكوسا قليلًا.","زيّن بجبن البارميزان."]))

add(6052473,
es=T("Muffin energético de avena en taza","¿Tiene ganas de un postre calentito y reconfortante, bajo en carbohidratos, que puede preparar en 5 minutos? Pruebe este muffin energético de avena en taza como una sabrosa opción para el desayuno o el postre.","1","1 taza de café",
["3 cucharadas de yogur griego natural sin grasa","1 huevo entero","1/2 cucharadita de extracto de vainilla","2 cucharadas de harina de avena (licúe avena regular si no tiene harina de avena a mano)","1/2 cucharadita de polvo de hornear","1/4 canela","2 cucharadas de arándanos azules"],
["En un tazón pequeño o una taza, bata el yogur griego, el huevo y el extracto de vainilla.","Agregue la harina de avena y el polvo de hornear. Mezcle hasta que quede suave.","Incorpore la canela y los arándanos azules.","Cocine en el microondas a temperatura alta durante 1 minuto y 30 segundos a 2 minutos, o hasta que el muffin esté inflado y firme. El tiempo de cocción puede variar según su microondas."]),
ar=T("مافن الشوفان المنشّط في كوب","هل تشتهي حلوى دافئة ومريحة قليلة الكربوهيدرات يمكنك تحضيرها في 5 دقائق؟ جرّب مافن الشوفان المنشّط في كوب هذا كخيار لذيذ للإفطار أو للحلوى.","1","1 كوب قهوة",
["3 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","1 بيضة كاملة","½ ملعقة صغيرة مستخلص الفانيليا","2 ملعقة كبيرة دقيق الشوفان (اطحن الشوفان العادي إذا لم يتوفر لديك دقيق الشوفان)","½ ملعقة صغيرة بيكنج باودر","¼ قرفة","2 ملعقة كبيرة توت أزرق"],
["في وعاء صغير أو كوب، اخفق الزبادي اليوناني والبيض ومستخلص الفانيليا.","أضف دقيق الشوفان والبيكنج باودر. اخلط حتى يصبح الخليط ناعمًا.","أضف القرفة والتوت الأزرق وحرّك.","سخّنه في الميكروويف على الدرجة العالية لمدة دقيقة و30 ثانية إلى دقيقتين، أو حتى ينتفخ المافن ويتماسك. قد يختلف وقت الطهي حسب جهاز الميكروويف لديك."]))

add(6052689,
es=T("Coles de Bruselas y calabaza butternut asadas","Asar las verduras resalta su dulzor a medida que desarrollan una capa caramelizada. Pruebe asar cualquiera de sus verduras favoritas y experimente con diferentes hierbas para variar. Para ahorrar tiempo al cocinar con calabaza butternut, compre calabaza ya empacada y corte en trozos más pequeños los pedazos grandes.","7","1/2 taza",
["12 onzas de coles de Bruselas (frescas)","20 onzas de calabaza butternut (aproximadamente 3 1/2 tazas)","1 cucharada de aceite de oliva","2 cucharaditas de tomillo seco"],
["Precaliente el horno a 450°F.","Corte las coles de Bruselas por la mitad. Corte los trozos más grandes de calabaza en cubos de 1 pulgada.","Coloque las coles de Bruselas y la calabaza en un tazón grande y rocíe con el aceite de oliva. Agregue el tomillo y mezcle para cubrir.","Extienda las coles de Bruselas y la calabaza en una sola capa en un molde para hornear y hornee durante 25 minutos, hasta que las verduras estén tiernas y comiencen a dorarse."]),
ar=T("كرنب بروكسل وقرع جوزي مشويان","يُبرز التحميص حلاوة الخضار إذ تكتسب طبقة مكرملة. جرّب تحميص أي من خضارك المفضلة وجرّب أعشابًا مختلفة للتنويع. لتوفير الوقت عند الطهي بالقرع الجوزي، اشترِ القرع المعبأ مسبقًا وقطّع القطع الكبيرة إلى قطع أصغر.","7","½ كوب",
["12 أونصة كرنب بروكسل (طازج)","20 أونصة قرع جوزي (حوالي 3½ كوب)","1 ملعقة كبيرة زيت زيتون","2 ملعقة صغيرة زعتر مجفف"],
["سخّن الفرن مسبقًا على 450° فهرنهايت (230° مئوية).","قطّع كرنب بروكسل إلى نصفين. قطّع القطع الأكبر من القرع إلى مكعبات بحجم 1 بوصة.","ضع كرنب بروكسل والقرع في وعاء كبير ورشّ عليهما زيت الزيتون. أضف الزعتر وقلّب لتغطيتهما.","افرد كرنب بروكسل والقرع في طبقة واحدة في صينية خَبز واخبزهما لمدة 25 دقيقة، حتى تلين الخضار وتبدأ بالاحمرار."]))

add(6054285,
es=T("Chips de plátano horneados con especias chai","Estos chips de plátano horneados con especias chai son un bocadillo sabroso y saludable con un delicioso toque de especias chai. El dulzor natural de los plátanos combinado con las cálidas especias chai crea un bocadillo satisfactorio y aromático.","4","20 chips",
["4 plátanos pequeños (maduros pero firmes)","1 cucharada de jugo de limón","1 cucharadita de canela molida","1/2 cucharadita de cardamomo molido","1/2 cucharadita de jengibre molido","1/4 cucharadita de clavo molido","1/4 cucharadita de nuez moscada molida"],
["Precaliente el horno a 200 grados F. Forre una bandeja para hornear con papel pergamino.","Pele los plátanos y córtelos en rodajas finas, de aproximadamente 1/8 a ¼ de pulgada de grosor. Coloque las rodajas de plátano en un tazón y mézclelas con el jugo de limón para evitar que se oscurezcan y para darles un toque de acidez.","En un tazón pequeño, mezcle la canela molida, el cardamomo molido, el jengibre molido, el clavo molido y la nuez moscada molida para crear una mezcla de especias chai.","Espolvoree la mezcla de especias chai sobre las rodajas de plátano, asegurándose de que queden bien cubiertas con las especias aromáticas. Acomode las rodajas de plátano en la bandeja preparada en una sola capa, cuidando que no se traslapen.","Hornee en el horno precalentado durante aproximadamente 2 horas, o hasta que los chips de plátano estén crujientes y dorados. Voltee los chips a la mitad del tiempo de horneado para asegurar que queden crujientes de manera uniforme.","Vigile los chips de plátano hacia el final del tiempo de horneado para evitar que se quemen. El tiempo exacto de horneado puede variar según su horno y el grosor de las rodajas. Seguirán poniéndose crujientes a medida que se enfríen.","Guarde los chips de plátano en un recipiente hermético a temperatura ambiente después de dejarlos enfriar por completo."]),
ar=T("رقائق الموز المخبوزة بتوابل الشاي بالحليب (تشاي)","تُعدّ رقائق الموز المخبوزة بتوابل التشاي هذه وجبة خفيفة لذيذة وصحية بلمسة رائعة من توابل التشاي. تخلق الحلاوة الطبيعية للموز مع توابل التشاي الدافئة وجبة خفيفة مُشبعة وعطرة.","4","20 رقاقة",
["4 حبات موز صغيرة (ناضجة لكن متماسكة)","1 ملعقة كبيرة عصير ليمون","1 ملعقة صغيرة قرفة مطحونة","½ ملعقة صغيرة هيل مطحون","½ ملعقة صغيرة زنجبيل مطحون","¼ ملعقة صغيرة قرنفل مطحون","¼ ملعقة صغيرة جوزة الطيب المطحونة"],
["سخّن الفرن مسبقًا على 200 درجة فهرنهايت (95 درجة مئوية). بطّن صينية خَبز بورق الزبدة.","قشّر الموز وقطّعه إلى شرائح دائرية رقيقة، بسماكة ⅛ إلى ¼ بوصة تقريبًا. ضع شرائح الموز في وعاء وقلّبها مع عصير الليمون لمنع تغيّر لونها وإضفاء لمسة من الحموضة.","في وعاء صغير، اخلط القرفة المطحونة والهيل المطحون والزنجبيل المطحون والقرنفل المطحون وجوزة الطيب المطحونة لتحضير خليط توابل التشاي.","انثر خليط توابل التشاي فوق شرائح الموز، مع التأكد من تغطيتها جيدًا بالتوابل العطرية. رتّب شرائح الموز في الصينية المجهزة في طبقة واحدة، مع التأكد من عدم تداخلها.","اخبزها في الفرن المسخّن مسبقًا لمدة ساعتين تقريبًا، أو حتى تصبح رقائق الموز مقرمشة وذهبية اللون. اقلب الرقائق في منتصف مدة الخَبز لضمان قرمشة متساوية.","راقب رقائق الموز قرب نهاية مدة الخَبز لتجنب احتراقها. قد يختلف وقت الخَبز بالضبط حسب الفرن وسماكة الشرائح. وستستمر في التقرمش أثناء تبريدها.","احفظ رقائق الموز في وعاء محكم الإغلاق في درجة حرارة الغرفة بعد تركها تبرد تمامًا."]))

add(6054450,
es=T("Trucha al horno o a la parrilla","Esta sencilla receta de pescado se sazona con pimienta de limón sin sal y pimentón para un plato principal de proteína bajo en sodio y saludable para el corazón. Si le gusta picante, también puede agregar una pizca de pimienta de cayena. Esta receta usa trucha, pero puede usar el mismo condimento y la misma técnica, a la parrilla o al horno, con su filete de pescado favorito.","8","1 filete (aproximadamente 3 onzas)",
["2 libras de filetes de trucha arcoíris","1 cucharada de aceite de oliva","1/2 cucharadita de sal","1 cucharadita de pimienta de limón sin sal","1/2 cucharadita de pimentón"],
["Seque los filetes de pescado con una toalla de papel. Frote ligeramente ambos lados con aceite de oliva (o use aceite en aerosol). Mezcle la sal, la pimienta de limón y el pimentón en un tazón pequeño. Espolvoree el condimento de manera uniforme sobre el lado del filete del pescado.","A la parrilla: Precaliente la parrilla a fuego alto. Coloque la trucha directamente sobre la parrilla, con el lado del filete hacia abajo. Cocine durante 4 minutos. Voltee los filetes y cocine hasta que el pescado se desmenuce fácilmente con un tenedor, unos 3 a 5 minutos.","Al horno: Precaliente el horno a 350° F. Coloque la trucha con la piel hacia abajo en una bandeja grande para hornear. Hornee sin tapar de 10 a 15 minutos, o hasta que la trucha se desmenuce fácilmente con un tenedor."]),
ar=T("سمك السلمون المرقط المخبوز أو المشوي","يُتبَّل طبق السمك البسيط هذا بالليمون والفلفل الخالي من الملح والبابريكا ليكون طبقًا رئيسيًا بروتينيًا قليل الصوديوم وصحيًا للقلب. إذا كنت تحب الطعم الحار، يمكنك أيضًا إضافة رشة من فلفل الكايين. تستخدم هذه الوصفة سمك السلمون المرقط، ولكن يمكنك استخدام التتبيلة والتقنية نفسها، شويًا أو خبزًا، مع شرائح السمك المفضلة لديك.","8","1 شريحة (حوالي 3 أونصات)",
["2 رطل شرائح سمك السلمون المرقط (قوس قزح)","1 ملعقة كبيرة زيت زيتون","½ ملعقة صغيرة ملح","1 ملعقة صغيرة فلفل بالليمون خالٍ من الملح","½ ملعقة صغيرة بابريكا"],
["جفّف شرائح السمك بمنديل ورقي. افرك الجانبين برفق بزيت الزيتون (أو استخدم رذاذ الطهي). اخلط الملح والفلفل بالليمون والبابريكا في وعاء صغير. انثر التتبيلة بالتساوي على جانب اللحم من السمك.","للشواء: سخّن الشواية مسبقًا على حرارة عالية. ضع السمك مباشرة على الشواية، بحيث يكون جانب اللحم لأسفل. اشوِه لمدة 4 دقائق. اقلب الشرائح واطهِها حتى يتفتت السمك بسهولة بالشوكة، نحو 3 إلى 5 دقائق.","للخَبز: سخّن الفرن مسبقًا على 350° فهرنهايت (175° مئوية). ضع السمك بحيث يكون الجلد لأسفل في صينية كبيرة. اخبزه دون تغطية لمدة 10-15 دقيقة، أو حتى يتفتت السمك بسهولة بالشوكة."]))

add(6055159,
es=T("Jambalaya de camarones","Este jambalaya fácil está lleno de sabor cajún. Los camarones se cocinan muy rápido, lo que los convierte en una proteína ideal para una comida rápida entre semana.","8","2/3 taza",
["2 cucharadas de aceite de oliva","1 1/2 libras de camarones (pelados y desvenados)","1 cebolla mediana (picada)","1 pimiento verde mediano (picado)","1 cucharadita de condimento cajún","16 onzas de salsa de tomate","1 1/2 tazas de arroz integral (seco)"],
["Caliente el aceite en una sartén grande a fuego medio-alto y saltee los camarones, la cebolla y el pimiento durante unos 5 minutos, hasta que los camarones estén rosados.","Incorpore los demás ingredientes y cocine durante unos 5 minutos, hasta que estén calientes.","Mientras tanto, cocine el arroz según las instrucciones del paquete. Colóquelo en un tazón grande y cúbralo con la mezcla de camarones y verduras."]),
ar=T("جامبالايا الجمبري","هذه الجامبالايا السهلة مليئة بنكهة الكاجون. ينضج الجمبري بسرعة كبيرة، مما يجعله بروتينًا مثاليًا لوجبة سريعة في أيام الأسبوع.","8","⅔ كوب",
["2 ملعقة كبيرة زيت زيتون","1½ رطل جمبري (مقشر ومنزوع الأحشاء)","1 حبة بصل متوسطة (مفرومة)","1 حبة فلفل رومي أخضر متوسطة (مفرومة)","1 ملعقة صغيرة توابل كاجون","16 أونصة صلصة طماطم","1½ كوب أرز بني (جاف)"],
["سخّن الزيت في مقلاة كبيرة على نار متوسطة إلى عالية وقلّب الجمبري والبصل والفلفل الرومي لمدة 5 دقائق تقريبًا، حتى يصبح الجمبري ورديًا.","أضف بقية المكوّنات وحرّك، واطهِها لمدة 5 دقائق تقريبًا، حتى تسخن جيدًا.","في هذه الأثناء، اطهِ الأرز حسب تعليمات العبوة. ضعه في وعاء كبير وضع فوقه خليط الجمبري والخضار."]))

add(6055302,
es=T("Coliflor asada sencilla",None,"9","2/3 taza",
["1/4 cucharadita de pimienta negra","1/4 cucharadita de sal","1 1/2 cucharadas de aceite de oliva","1 cucharada (o 1 cucharadita de romero seco) de romero fresco (picado)","6 tazas de floretes de coliflor"],
["Precaliente el horno a 450° F.","En un tazón grande, mezcle la coliflor con el romero, el aceite de oliva, la sal y la pimienta. Extienda la coliflor sazonada en una bandeja grande para hornear (use dos bandejas si queda apretada en una).","Ase durante 15 minutos; retire del horno y revuelva.","Continúe asando durante 10 minutos o hasta que la coliflor esté tierna y ligeramente dorada."]),
ar=T("قرنبيط مشوي بسيط",None,"9","⅔ كوب",
["¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح","1½ ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة (أو 1 ملعقة صغيرة إكليل الجبل المجفف) إكليل الجبل الطازج (مفروم)","6 كوب زهيرات قرنبيط"],
["سخّن الفرن مسبقًا على 450° فهرنهايت (230° مئوية).","في وعاء كبير، قلّب القرنبيط مع إكليل الجبل وزيت الزيتون والملح والفلفل. افرد القرنبيط المتبّل على صينية خَبز كبيرة (استخدم صينيتين إذا كان مزدحمًا في صينية واحدة).","اشوِه لمدة 15 دقيقة؛ أخرجه من الفرن وحرّكه.","تابع الشيّ لمدة 10 دقائق أو حتى يلين القرنبيط ويكتسب لونًا بنيًا خفيفًا."]))

add(6055640,
es=T("Espárragos y tomates asados","Esta deliciosa receta se centra en la sencillez de los espárragos y los tomates asados, donde el crujiente tierno de los espárragos se encuentra con el estallido de dulzor de los tomates asados, creando una mezcla apta para personas con diabetes y rica en vitaminas.","3","1.5 tazas",
["1 libra de espárragos (recortados)","1 taza de tomates cherry (cortados por la mitad)","2 cucharadas de aceite de oliva","1 cucharada de vinagre balsámico","1/4 cucharadita de sal","1/2 cucharadita de pimienta negra","1/2 cucharada de albahaca fresca (picada, para decorar)"],
["Precaliente el horno a 400 grados F y cubra una bandeja para hornear con papel pergamino.","Mezcle los espárragos y los tomates cherry con el aceite de oliva, el vinagre balsámico, la sal y la pimienta.","Extienda de manera uniforme sobre la bandeja y ase de 15 a 20 minutos, hasta que los espárragos estén tiernos y los tomates ligeramente caramelizados.","Sirva en una fuente y decore con albahaca fresca."]),
ar=T("هليون وطماطم مشويان","تدور هذه الوصفة اللذيذة حول بساطة الهليون والطماطم المشوية، حيث تلتقي قرمشة الهليون الطرية بانفجار الحلاوة من الطماطم المشوية، لتُكوّن مزيجًا غنيًا بالفيتامينات ومناسبًا لمرضى السكري.","3","1.5 كوب",
["1 رطل هليون (مقطوع الأطراف)","1 كوب طماطم كرزية (مقطعة إلى نصفين)","2 ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة خل بلسمي","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","½ ملعقة كبيرة ريحان طازج (مفروم، للتزيين)"],
["سخّن الفرن مسبقًا على 400 درجة فهرنهايت (205 درجة مئوية) وغطِّ صينية خَبز بورق الزبدة.","قلّب الهليون والطماطم الكرزية مع زيت الزيتون والخل البلسمي والملح والفلفل.","افرده بالتساوي على الصينية واشوِه لمدة 15–20 دقيقة حتى يلين الهليون وتتكرمل الطماطم قليلًا.","ضعه في طبق التقديم وزيّنه بالريحان الطازج."]))

add(6055782,
es=T("Pollo con za’atar y farro con uvas, cebolla y coles de Bruselas asadas","Para acompañar el pollo cubierto de za’atar con hierbas, lo servirá sobre una abundante base de farro y verduras y uvas asadas, todo unido con una salsa sabrosa de sartén de vinagre balsámico, ajo y un toque de chile rojo triturado.","2","1/2 receta",
["4 onzas de coles de Bruselas frescas","1 cebolla morada mediana","4 onzas de uvas rojas sin semillas","2 dientes de ajo","1/2 taza de farro semiperlado","1 1/2 cucharaditas de aceite de oliva ((dividido))","2 pechugas de pollo enteras sin hueso ni piel","1 cucharada de condimento za'atar","2 cucharadas de vinagre balsámico","1/4 taza de agua","1/4 cucharadita de hojuelas de chile rojo triturado","1/8 cucharadita de sal (opcional)","1/8 cucharadita de pimienta negra"],
["Prepare los ingredientes: Coloque una rejilla en el centro del horno y precaliéntelo a 450°F. Llene una olla mediana con agua hasta 3/4 de su capacidad; tape y caliente a fuego alto hasta que hierva. Lave y seque los productos frescos. Corte y deseche los extremos del tallo de las coles de Bruselas; pártalas por la mitad a lo largo. Parta la cebolla por la mitad y pélela; córtela en gajos de 1 pulgada de ancho, separando las capas. Parta las uvas por la mitad. Pele y pique grueso 2 dientes de ajo.","Cocine el farro: Agregue el farro a la olla de agua hirviendo y cocine, sin tapar, de 18 a 20 minutos, o hasta que esté tierno. Apague el fuego. Escurra bien y regrese a la olla. Tape para mantener caliente.","Ase las verduras y las uvas: Mientras tanto, coloque las coles de Bruselas, la cebolla y las uvas preparadas en una bandeja para hornear. Rocíe con 1/2 cucharadita de aceite de oliva y sazone con sal (opcional) y pimienta; mezcle para cubrir. Acomode en una capa uniforme. Ase de 15 a 17 minutos, o hasta que estén doradas y tiernas al pincharlas con un tenedor. Retire del horno.","Cocine el pollo: Mientras tanto, seque el pollo con toallas de papel; sazone ambos lados con sal (opcional), pimienta y suficiente za’atar para cubrir (puede que le sobre). En una sartén mediana (antiadherente, si tiene una), caliente 1/2 cucharadita de aceite de oliva a fuego medio-alto hasta que esté caliente. Agregue el pollo sazonado. Cocine de 6 a 7 minutos por lado, o hasta que esté dorado y bien cocido (un termómetro de lectura instantánea debe marcar 165°F). Dejando en la sartén los trocitos dorados (o fondo de cocción), pase el pollo a una tabla de cortar.","Prepare la salsa de sartén: En la sartén con el fondo de cocción reservado, caliente 1/2 cucharadita de aceite de oliva a fuego medio-alto hasta que esté caliente. Agregue el ajo picado. Cocine, revolviendo con frecuencia, de 30 segundos a 1 minuto, o hasta que se ablande ligeramente. Agregue el vinagre (con cuidado, ya que el líquido puede salpicar), 1/4 taza de agua y la cantidad de hojuelas de chile rojo que desee, según qué tan picante quiera el platillo. Sazone con sal (opcional) y pimienta. Cocine, revolviendo ocasionalmente, de 1 a 2 minutos, o hasta que la salsa espese ligeramente. Apague el fuego.","Termine y sirva su platillo: A la olla con el farro cocido, agregue las verduras y las uvas asadas y la salsa de sartén. Mezcle para combinar. Corte el pollo cocido en rebanadas transversales. Sirva el pollo rebanado sobre el farro terminado. ¡Buen provecho!"]),
ar=T("دجاج بالزعتر مع الفارو والعنب والبصل وكرنب بروكسل المشوي","لمرافقة الدجاج المغطى بالزعتر العطري، ستقدّمه فوق طبقة وفيرة من الفارو والخضار والعنب المشوي، يجمع بينها صلصة مقلاة لذيذة من الخل البلسمي والثوم ولمسة من الفلفل الأحمر المجروش.","2","½ الوصفة",
["4 أونصات كرنب بروكسل طازج","1 حبة بصل أحمر متوسطة","4 أونصات عنب أحمر بدون بذور","2 فص ثوم","½ كوب فارو نصف مقشور","1½ ملعقة صغيرة زيت زيتون ((مقسّمة))","2 صدر دجاج كامل بدون عظم وبدون جلد","1 ملعقة كبيرة توابل الزعتر","2 ملعقة كبيرة خل بلسمي","¼ كوب ماء","¼ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","⅛ ملعقة صغيرة ملح (اختياري)","⅛ ملعقة صغيرة فلفل أسود"],
["حضّر المكوّنات: ضع رفّ الفرن في المنتصف، ثم سخّن الفرن مسبقًا على 450° فهرنهايت (230° مئوية). املأ قدرًا متوسطًا بالماء حتى ¾ ارتفاعه؛ غطِّه وسخّنه على نار عالية حتى الغليان. اغسل المنتجات الطازجة وجفّفها. اقطع أطراف السيقان من كرنب بروكسل وتخلّص منها؛ وقسّمه إلى نصفين بالطول. قسّم البصل إلى نصفين وقشّره؛ واقطعه إلى أرباع بعرض 1 بوصة، مع فصل الطبقات. قسّم حبات العنب إلى نصفين. قشّر فصّي الثوم وافرمهما فرمًا خشنًا.","اطهِ الفارو: أضف الفارو إلى قدر الماء المغلي واطهِه دون تغطية لمدة 18 إلى 20 دقيقة، أو حتى يلين. أطفئ النار. صفِّه جيدًا وأعده إلى القدر. غطِّه ليبقى دافئًا.","اشوِ الخضار والعنب: في هذه الأثناء، ضع كرنب بروكسل والبصل والعنب المجهزة على صينية خَبز. رشّ عليها ½ ملعقة صغيرة من زيت الزيتون وتبّلها بالملح (اختياري) والفلفل؛ وقلّبها لتتغطى. وزّعها في طبقة متساوية. اشوِها لمدة 15 إلى 17 دقيقة، أو حتى تحمرّ وتلين عند وخزها بالشوكة. أخرجها من الفرن.","اطهِ الدجاج: في هذه الأثناء، جفّف الدجاج بمناديل ورقية؛ وتبّل الجانبين بالملح (اختياري) والفلفل وكمية كافية من الزعتر لتغطيته (قد يتبقى لديك منه). في مقلاة متوسطة (غير لاصقة إن توفرت)، سخّن ½ ملعقة صغيرة من زيت الزيتون على نار متوسطة إلى عالية حتى يسخن. أضف الدجاج المتبّل. اطهِه من 6 إلى 7 دقائق لكل جانب، أو حتى يحمرّ وينضج تمامًا (يجب أن يُظهر ميزان حرارة سريع القراءة 165° فهرنهايت (75° مئوية)). اترك أي قطع بنية (أو رواسب الطهي) في المقلاة، وانقل الدجاج إلى لوح التقطيع.","حضّر صلصة المقلاة: في المقلاة التي تحتوي على رواسب الطهي المحتفظ بها، سخّن ½ ملعقة صغيرة من زيت الزيتون على نار متوسطة إلى عالية حتى يسخن. أضف الثوم المفروم. اطهِه مع التحريك المتكرر من 30 ثانية إلى دقيقة واحدة، أو حتى يلين قليلًا. أضف الخل (بحذر، فقد يتناثر السائل) و¼ كوب ماء وما تشاء من رقائق الفلفل الأحمر حسب درجة حدة الطبق التي تريدها. تبّل بالملح (اختياري) والفلفل. اطهِه مع التحريك من حين لآخر لمدة 1 إلى 2 دقيقة، أو حتى تتكاثف الصلصة قليلًا. أطفئ النار.","أنهِ الطبق وقدّمه: أضف الخضار والعنب المشويين وصلصة المقلاة إلى قدر الفارو المطهو. حرّك للمزج. قطّع الدجاج المطبوخ شرائح بالعرض. قدّم شرائح الدجاج فوق الفارو الجاهز. بالهناء والعافية!"]))

add(6056440,
es=T("Ensalada con tortitas de salmón, limón y eneldo","Este almuerzo vivificante, ligero y bajo en carbohidratos está lleno de omega-3, saludables para el corazón. Prepare las tortitas de salmón y el aderezo con anticipación para un almuerzo rápido. Es una receta perfecta para quienes les gusta preparar las comidas con antelación.","4","2 tazas de ensalada + 2 tortitas de salmón",
["3 latas de 5 onzas de salmón rosado silvestre (escurrido)","1/4 taza de pan molido panko integral","2 cucharadas de queso feta","1/4 taza de sustituto de huevo","2 cucharadas de yogur griego natural sin grasa","3 cucharadas de jugo de limón","1 1/2 cucharaditas de ralladura de limón","2 cucharaditas de eneldo fresco (o 1/2 cucharadita de seco)","2 cucharadas de aceite de oliva","1/8 cucharadita de jarabe multiusos sin azúcar","8 tazas de hojas verdes para ensalada","1/4 pepino entero sin semillas (en rodajas finas)","1/2 taza de tomates cherry (cortados por la mitad)"],
["Precaliente el horno o la freidora de aire a 400 grados F. Forre una bandeja para hornear con papel pergamino si cocina en el horno.","En un tazón grande, combine el salmón, el pan molido y el queso.","En un tazón pequeño, bata el sustituto de huevo, el yogur, el jugo de limón, la ralladura de limón y el eneldo. Incorpore suavemente a la mezcla de salmón y mezcle bien, con cuidado de no desmenuzar demasiado los trozos de salmón.","Forme 8 tortitas, de aproximadamente 1/4 taza cada una, y colóquelas en la bandeja para hornear o en la canasta de la freidora de aire.","Hornee en el horno aproximadamente 15 minutos, o en la freidora de aire 8 minutos, o hasta que estén ligeramente doradas y crujientes.","Mientras se cocinan las tortitas de salmón, bata los ingredientes del aderezo en un tazón pequeño. Bata 2 cucharadas de aceite de oliva; 2 cucharadas de jugo de limón; ½ cucharadita de ralladura de limón; ½ cucharadita de eneldo fresco picado; y 1/8 cucharadita de jarabe multiusos sin azúcar.","Divida la ensalada en 4 platos y cubra con las hojas verdes, el pepino y el tomate.","Coloque 2 tortitas de salmón sobre cada ensalada y rocíe con el aderezo. Decore con más eneldo picado si lo desea."]),
ar=T("سلطة أقراص السلمون بالليمون والشبت","هذه الوجبة المنعشة الخفيفة قليلة الكربوهيدرات للغداء مليئة بأوميغا 3 المفيدة للقلب. حضّر أقراص السلمون والصلصة مسبقًا لتناول غداء سريع. إنها وصفة مثالية لمن يحبون تحضير الوجبات مسبقًا.","4","2 كوب سلطة + قرصان من السلمون",
["3 علب، 5 أونصات لكل منها، سلمون وردي بري (مصفّى)","¼ كوب فتات خبز بانكو من القمح الكامل","2 ملعقة كبيرة جبن فيتا","¼ كوب بديل البيض","2 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","3 ملعقة كبيرة عصير ليمون","1½ ملعقة صغيرة قشر ليمون مبشور","2 ملعقة صغيرة شبت طازج (أو ½ ملعقة صغيرة مجفف)","2 ملعقة كبيرة زيت زيتون","⅛ ملعقة صغيرة شراب متعدد الاستخدامات خالٍ من السكر","8 كوب أوراق سلطة خضراء","¼ حبة خيار كاملة بدون بذور (مقطعة شرائح رقيقة)","½ كوب طماطم كرزية (مقطعة إلى نصفين)"],
["سخّن الفرن أو القلاية الهوائية مسبقًا على 400 درجة فهرنهايت (205 درجة مئوية). بطّن صينية خَبز بورق الزبدة إذا كنت ستطهو في الفرن.","في وعاء كبير، اخلط السلمون وفتات الخبز والجبن.","في وعاء صغير، اخفق بديل البيض والزبادي وعصير الليمون وقشر الليمون والشبت. أضفه برفق إلى خليط السلمون واخلطه جيدًا، مع الحرص على ألا تُفتَّت قطع السلمون كثيرًا.","شكّل الخليط إلى 8 أقراص، بحجم ¼ كوب تقريبًا لكل قرص، وضعها على صينية الخَبز أو في سلة القلاية الهوائية.","اخبزها في الفرن لمدة 15 دقيقة تقريبًا، أو في القلاية الهوائية لمدة 8 دقائق، أو حتى يصبح لونها بنيًا خفيفًا وتصبح مقرمشة.","بينما تُطهى أقراص السلمون، اخفق مكوّنات الصلصة في وعاء صغير. اخفق 2 ملعقة كبيرة زيت زيتون؛ و2 ملعقة كبيرة عصير ليمون؛ و½ ملعقة صغيرة قشر ليمون مبشور؛ و½ ملعقة صغيرة شبت طازج مفروم؛ و⅛ ملعقة صغيرة شراب متعدد الاستخدامات خالٍ من السكر.","وزّع السلطة على 4 أطباق وضع فوقها أوراق السلطة الخضراء والخيار والطماطم.","ضع قرصين من السلمون فوق كل سلطة ورشّ الصلصة. زيّن بمزيد من الشبت المفروم إن رغبت."]))

add(6056779, ar=T("فطيرة الدجاج بالحبوب الكاملة","فطيرة الدجاج غنية عادةً بالدهون والكربوهيدرات. هذه النسخة الأخف مليئة بالبروتين قليل الدهن والخضار والحبوب الكاملة.","8","1¼ كوب",
["1 بخّة، 0.25 غرام رذاذ طهي غير لاصق","2 كوب دقيق القمح الكامل","4 ملعقة صغيرة بيكنج باودر","4 ملعقة كبيرة سمن نباتي (مارجرين) بارد (خالٍ من الدهون المتحولة)","1 ملعقة كبيرة بقدونس (مجفف)","2½ كوب حليب خالٍ من الدسم (مقسّم)","1 ملعقة صغيرة زيت زيتون","2 حبة جزر متوسطة (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","1 حبة بصل كبيرة (مقطعة مكعبات)","8 أونصات فطر أبيض (فطر الأزرار) (مقطع شرائح)","12 أونصة دجاج مطبوخ (مفروم)","2 ملعقة كبيرة دقيق","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا على 375 درجة فهرنهايت (190 درجة مئوية). افرك طبق خَبز مقاس 9×13 بوصة برذاذ الطهي وضعه جانبًا.","في وعاء كبير، اغربل دقيق القمح الكامل مع البيكنج باودر. قطّع السمن النباتي (المارجرين) فيه، ثم أضف البقدونس و1 كوب من الحليب، وحرّك برفق للمزج. ضعه في الثلاجة إلى حين الحاجة.","أضف زيت الزيتون وكمية وفيرة من رذاذ الطهي إلى مقلاة سوتيه كبيرة غير لاصقة على نار متوسطة إلى عالية. أضف الجزر والكرفس والبصل والفطر. قلّبها لمدة 10 دقائق أو حتى تلين الخضار دون أن تتهرأ.","أضف الدجاج المطبوخ وحرّك.","في وعاء صغير، اخفق الدقيق مع 1½ كوب حليب والملح والفلفل الأسود المطحون. أضفه إلى خليط الخضار واتركه حتى يغلي. خفّض الحرارة ليغلي بهدوء لمدة دقيقتين. ارفعه عن النار.","صبّ خليط الدجاج والخضار في طبق الخَبز. ضع كتلًا من خليط عجينة القمح الكامل فوق خليط الدجاج والخضار (ستكون الطبقة العلوية لزجة جدًا). استخدم ملعقة لفردها برفق.","اخبزها لمدة 20 دقيقة وقدّمها."]))

add(6057267,
es=T("Bolitas energéticas de limón y semillas de amapola","Dé más energía a su postre con estas deliciosas y nutritivas bolitas energéticas de limón y semillas de amapola. Elaboradas con ingredientes sustanciosos, son un excelente postre.","20","1 bolita energética",
["1 1/2 tazas de avena de cocción rápida","1/2 taza de almendras sin piel (picadas en trozos grandes)","1/4 taza de jarabe sin azúcar tipo arce","2 cucharadas de mantequilla de semillas de girasol","1 cucharada de ralladura de limón","2 cucharadas de jugo de limón","1 cucharadita de extracto de vainilla","1/4 cucharadita de sal marina","2 cucharaditas de semillas de amapola"],
["Pulse la avena en el tazón de un procesador de alimentos hasta que esté finamente molida.","Agregue las almendras y continúe pulsando hasta obtener una mezcla finamente molida.","Vierta el jarabe junto con la mantequilla de semillas de girasol, la ralladura y el jugo de limón, la vainilla y la sal, y licúe hasta que se convierta en una masa.","Pase la masa a un tazón para mezclar e incorpore las semillas de amapola.","Con una cuchara medidora de porciones de 2 cucharadas, forme 20 bolitas. Ruede cada una entre las manos para formar una bola lisa.","Guarde en un recipiente hermético en el refrigerador hasta por 12 días o en el congelador por 1 mes."]),
ar=T("كرات الطاقة بالليمون وبذور الخشخاش","عزّز حلواك بكرات الطاقة اللذيذة والمغذية بالليمون وبذور الخشخاش. تُحضَّر من مكوّنات مشبعة، وهي حلوى ممتازة.","20","1 كرة طاقة",
["1½ كوب شوفان سريع الطهي","½ كوب لوز مقشر (مفروم فرمًا خشنًا)","¼ كوب شراب بنكهة القيقب خالٍ من السكر","2 ملعقة كبيرة زبدة بذور دوار الشمس","1 ملعقة كبيرة قشر ليمون مبشور","2 ملعقة كبيرة عصير ليمون","1 ملعقة صغيرة مستخلص الفانيليا","¼ ملعقة صغيرة ملح بحري","2 ملعقة صغيرة بذور الخشخاش"],
["اخفق الشوفان بنبضات متقطعة في وعاء محضّرة الطعام حتى يصبح مطحونًا ناعمًا.","أضف اللوز واستمر في النبضات حتى يصبح الخليط مطحونًا ناعمًا.","صبّ الشراب مع زبدة بذور دوار الشمس وقشر الليمون وعصيره والفانيليا والملح، وامزج حتى يتحول إلى عجينة.","انقل العجينة إلى وعاء خلط وأضف بذور الخشخاش وحرّك.","باستخدام مغرفة تقسيم بسعة 2 ملعقة كبيرة، اغرف 20 كرة. لفّ كل واحدة بين يديك لتشكيل كرة ملساء.","احفظها في وعاء محكم الإغلاق في الثلاجة لمدة تصل إلى 12 يومًا أو في المجمّد لمدة شهر واحد."]))
save(3)
