from h import *
O=[]
O.append(R(6558830,ar=(
"وعاء نودلز «رامن» من قرع السباغيتي",
"نسخة أكثر صحة من أوعية نودلز الرامن الرائجة، تمنحك مرقًا لذيذًا يمكنك تخصيصه حسب ذوقك. لا دجاج أو فلفل رومي؟ بدّل المكوّنات ببروتينات وخضار أخرى، مثل الروبيان وبراعم الفاصولياء والجزر المبشور.",
"4","1 وعاء",
["2 ملعقة صغيرة زيت سمسم محمّص","2½ ملعقة صغيرة صلصة صويا قليلة الصوديوم","4 أكواب مرق دجاج قليل الصوديوم (خالٍ من الدسم)","2½ رطل قرع سباغيتي (متوسط الحجم)","2 كوب دجاج مطبوخ (مفتّت)","1 ملعقة صغيرة صلصة حارة على الطريقة الآسيوية (مثل سامبال أولك)","½ ملعقة صغيرة صلصة السمك","½ كوب بصل أخضر (مقطّع شرائح رفيعة، الجزء الأبيض والأخضر)","½ كوب فلفل رومي أحمر (مقطّع شرائح رفيعة بطول 1 بوصة)","1 حبة ليمون أخضر (مقطّعة أرباعًا للتقديم)"],
["سخّن الفرن مسبقًا على 400° فهرنهايت (200° مئوية). املأ طبق خبز زجاجيًا أو معدنيًا مقاس 9x13 بوصة بماء بارتفاع 2 بوصة. اقطع طرفي قرع السباغيتي ثم اقسمه نصفين بالطول. ضع القرع في الطبق وجانب القطع إلى الأسفل واخبزه لمدة 40 دقيقة. أخرجه من الفرن وأخرج القرع من الطبق فورًا. أخرج البذور وتخلّص منها. استخدم شوكة لكشط القرع من القشرة وضعه جانبًا. ينتج عن ذلك 4 أكواب من القرع المطبوخ.","بينما يُطهى القرع، سخّن المرق في قدر متوسط الحجم على نار متوسطة حتى يبدأ بالغليان الهادئ. أضف صلصة الصويا وزيت السمسم وصلصة السمك والصلصة الحارة. اتركه على نار هادئة لمدة دقيقتين. أضف الدجاج وسخّنه جيدًا لمدة دقيقتين.","ضع كوبًا واحدًا من القرع في وعاء حساء. اسكب كوبًا واحدًا من المرق فوق القرع وأضف ½ كوب من الدجاج. زيّن بملعقتين كبيرتين من البصل الأخضر وملعقتين كبيرتين من شرائح الفلفل الرومي.","كرّر الخطوات للأوعية الثلاثة المتبقية. أضف ربع حبة ليمون أخضر إلى كل وعاء عند التقديم."],[],[])))
O.append(R(6560352,
("Puré cremoso de chirivías y zanahorias","Una deliciosa mezcla de chirivías con sabor a tierra y zanahorias dulces da vida a este plato de acompañamiento sabroso y apto para personas con diabetes.","4","1/2 taza",
["4 chirivías medianas (peladas y picadas)","2 zanahorias medianas (peladas y picadas)","2 cucharadas de mantequilla sin sal","1/4 de taza de caldo de verduras bajo en sodio","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra","1 cucharada de perejil fresco (picado, para decorar)"],
["En una olla grande, hierva agua. Agregue las chirivías y las zanahorias picadas al agua hirviendo.","Cocine de 15 a 20 minutos, o hasta que las chirivías y las zanahorias estén tiernas al pincharlas con un tenedor.","Escurra las chirivías y las zanahorias y devuélvalas a la olla.","Agregue la mantequilla sin sal a la olla y machaque las chirivías y las zanahorias con un machacador de papas o un tenedor.","Agregue poco a poco el caldo de verduras sin dejar de machacar, hasta lograr la consistencia cremosa deseada.","Sazone con la sal y la pimienta. Mezcle bien."],[],[]),
("هريس البقدونس الجذري (الباستيناك) مع الجزر بقوام كريمي","مزيج شهي من الباستيناك الترابي النكهة والجزر الحلو يجتمع في طبق جانبي لذيذ مناسب لمرضى السكري.","4","½ كوب",
["4 جذور باستيناك متوسطة (مقشّرة ومقطّعة)","2 جزرة متوسطة (مقشّرة ومقطّعة)","2 ملعقة كبيرة زبدة غير مملحة","¼ كوب مرق خضار قليل الصوديوم","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة بقدونس طازج (مفروم، للتزيين)"],
["في قدر كبيرة، اغلِ الماء. أضف الباستيناك والجزر المقطّعين إلى الماء المغلي.","اطبخهما لمدة 15–20 دقيقة أو حتى يلين الباستيناك والجزر عند غرزهما بالشوكة.","صفِّ الباستيناك والجزر وأعدهما إلى القدر.","أضف الزبدة غير المملحة إلى القدر وهرس الباستيناك والجزر باستخدام مهراس البطاطس أو شوكة.","أضف مرق الخضار تدريجيًا مع متابعة الهرس حتى تحصل على القوام الكريمي المطلوب.","تبّل بالملح والفلفل. امزج جيدًا."],[],[])))
O.append(R(6560917,
("Mejor puré de papas","Este mejor puré de papas es un acompañamiento cremoso y reconfortante, preparado con ingredientes sencillos y más ligero. Conserva la textura suave y el sabor delicioso que le encantan, pero con pequeños cambios para agregar más verduras sin almidón a su comida. Es fácil de preparar y es una excelente opción para las comidas diarias o las ocasiones especiales.","10","1/2 taza",
["1/2 cucharadita de pimienta negra","1 cucharadita de sal","2 cucharaditas de mantequilla (sin sal)","1 cucharada de aceite de oliva","2 cucharadas de queso parmesano (rallado)","1/3 de taza de suero de leche bajo en grasa","1 cabeza de coliflor (separada en floretes pequeños; deseche el centro y el tallo)","5 dientes de ajo (pelados y enteros)","7 onzas de papas russet o para hornear (peladas y cortadas en cubos de 2 pulgadas)"],
["En una olla grande, coloque la papa, el ajo y la coliflor. Agregue suficiente agua para cubrirlos por completo. Hierva, reduzca el fuego a medio y cocine hasta que la papa y la coliflor estén tiernas, unos 15 minutos.","Escurra y vuelva a colocar las verduras y el ajo en la olla. Cubra la olla con un paño de cocina y ponga la tapa sobre el paño. Deje reposar durante 5 minutos. Retire la tapa y el paño. Este proceso ayuda a secar las verduras para que se machaquen mejor.","Agregue el suero de leche, el queso, el aceite de oliva, la mantequilla, la sal y la pimienta. Machaque solo hasta que los ingredientes estén ligeramente mezclados. Si lo desea, decore con cebollín fresco picado."],[],[]),
("بطاطس مهروسة بوصفة أفضل","بطاطس مهروسة كريمية ومريحة كطبق جانبي، تُحضَّر بمكوّنات بسيطة وبلمسة أخف. تحافظ على القوام الناعم والنكهة الغنية التي تحبها، مع إجراء تغييرات صغيرة لإضافة المزيد من الخضار غير النشوية إلى وجبتك. سهلة التحضير، وهي إضافة رائعة إلى الوجبات اليومية أو المناسبات الخاصة.","10","½ كوب",
["½ ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة ملح","2 ملعقة صغيرة زبدة (غير مملحة)","1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة جبن بارميزان (مبشور)","⅓ كوب لبن رائب (بتيرميلك) قليل الدسم","1 رأس قرنبيط (مفصول إلى زهيرات صغيرة، مع التخلص من اللب والساق)","5 فصوص ثوم (مقشّرة وتُترك كاملة)","7 أونصات بطاطس روسيت أو بطاطس للخَبز (مقشّرة ومقطّعة إلى مكعبات بطول 2 بوصة)"],
["ضع البطاطس والثوم والقرنبيط في قدر كبيرة. أضف ماءً يكفي لتغطيتها بالكامل. اتركها حتى تغلي، ثم خفّض الحرارة إلى متوسطة واطبخها حتى تلين البطاطس والقرنبيط، نحو 15 دقيقة.","صفِّ الخضار وأعدها مع الثوم إلى القدر. غطِّ القدر بمنشفة مطبخ ثم ضع الغطاء فوق المنشفة. اتركها لمدة 5 دقائق. أزل الغطاء والمنشفة. تساعد هذه الطريقة على تجفيف الخضار فتُهرس بشكل أفضل.","أضف اللبن الرائب والجبن وزيت الزيتون والزبدة والملح والفلفل. اهرس المكوّنات حتى تمتزج برفق فقط. زيّن بالثوم المعمّر (الكرّاث) الطازج المقطّع إن رغبت."],[],[])))
O.append(R(6561298,ar=(
"بطاطس بالفرن بالكريمة (سكالوب)",
"أطباق البطاطس شائعة في موائد الأعياد. قدّم هذا الطبق الجانبي الكريمي من البطاطس على عشاء العيد. لن يخطر ببال أحد أنه نسخة «صحية» من البطاطس بالفرن بالكريمة!",
"8","½ كوب",
["1 بخّة (0.25 غ) بخاخ طهي غير لاصق","¼ ملعقة صغيرة ملح (اختياري)","6 حبات بطاطس روسيت أو بطاطس للخَبز متوسطة","1 حبة بصل أصفر متوسطة (مقطّعة شرائح رفيعة)","¼ ملعقة صغيرة فلفل أسود","1 كوب خليط نصف كريمة ونصف حليب خالٍ من الدسم","½ كوب جبن شيدر (قليل الدسم، مبشور حاد النكهة، مقسّم)"],
["سخّن الفرن مسبقًا على 400 درجة فهرنهايت (200 درجة مئوية). قشّر البطاطس وقطّعها إلى شرائح دائرية رفيعة.","ادهن مقلاة كبيرة غير لاصقة ببخاخ الطهي وقلّب البصل على نار متوسطة إلى عالية حتى يصبح شفافًا.","ادهن طبق فطيرة أو قالب كيك دائريًا مقاس 8 بوصات ببخاخ الطهي.","ضع طبقة سميكة (نحو النصف) من البطاطس والبصل في قاع الطبق.","أضف الملح والفلفل إلى خليط نصف الكريمة ونصف الحليب. اسكب ½ كوب من خليط نصف الكريمة ونصف الحليب فوق البطاطس. رشّ ¼ كوب من الجبن على الوجه.","أضف باقي البطاطس واسكب ½ كوب من خليط نصف الكريمة ونصف الحليب فوقها ثم غطِّها بباقي الجبن.","اخبزها لمدة 40 دقيقة أو حتى تلين البطاطس."],[],[])))
O.append(R(6561472,ar=(
"سلطة الفاصولياء السوداء والذرة",
"هذه السلطة مثالية لنزهة الربيع أو لوجبة غداء سريعة، وهي غنية جدًا بالألياف.",
"12","½ كوب",
["2 علبة (14.5 أونصة) فاصولياء سوداء (مشطوفة ومصفّاة)","2 كوب ذرة مجمّدة (مذابة)","1 حبة فلفل رومي أحمر (مقطّعة مكعبات صغيرة جدًا)","½ كوب بصل أحمر مقطّع مكعبات صغيرة جدًا","½ كوب كزبرة خضراء طازجة مفرومة","2 حبة ليمون أخضر صغيرة (عصير)","3 ملاعق كبيرة زيت زيتون","½ ملعقة صغيرة كمون","¼ ملعقة صغيرة مسحوق الثوم","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة فلفل كايين (اختياري)"],
["في وعاء متوسط الحجم، اخلط الفاصولياء والذرة والفلفل الأحمر والبصل الأحمر والكزبرة الخضراء.","في وعاء صغير، اخفق باقي المكوّنات معًا وصبّها فوق سلطة الفاصولياء. قلّب لتتغلّف المكوّنات جيدًا."],[],[])))
O.append(R(6561654,
("Ensalada mediterránea de pepino","Esta cremosa ensalada mediterránea de pepino es un acompañamiento crujiente y bajo en carbohidratos, ideal para una noche de verano.","6","½ taza",
["2 pepinos medianos (en rodajas)","1/4 de cebolla morada mediana (en rodajas)","2 cucharadas de eneldo fresco","2 cucharadas de pistaches (finamente picados)","2 cucharadas de yogur griego natural sin grasa","1 cucharada de aceite de oliva","1 cucharada de vinagre de vino tinto","1/2 cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["En un tazón, mezcle los pepinos, la cebolla morada, el eneldo y los pistaches.","En otro tazón pequeño, bata el yogur griego, el aceite de oliva, el vinagre de vino tinto, la sal y la pimienta.","Vierta el aderezo sobre la mezcla de pepino y revuelva para cubrir."],[],[]),
("سلطة الخيار المتوسطية","سلطة الخيار المتوسطية الكريمية هذه طبق جانبي مقرمش وقليل الكربوهيدرات، مثالي لأمسيات الصيف.","6","½ كوب",
["2 حبة خيار متوسطة (مقطّعة شرائح دائرية)","¼ حبة بصل أحمر متوسطة (مقطّعة شرائح)","2 ملعقة كبيرة شبت طازج","2 ملعقة كبيرة فستق (مفروم ناعمًا)","2 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","1 ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة خل النبيذ الأحمر","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["في وعاء، اخلط الخيار والبصل الأحمر والشبت والفستق.","في وعاء صغير منفصل، اخفق الزبادي اليوناني وزيت الزيتون وخل النبيذ الأحمر والملح والفلفل.","اسكب التتبيلة فوق خليط الخيار وقلّب حتى يتغلّف جيدًا."],[],[])))
O.append(R(6562027,
("Salmón sellado a la sartén con hongos glaseados con soya y arroz integral con verduras","Este plato equilibrado de salmón combina filetes sellados a la sartén y crujientes con hongos sabrosos glaseados con soya y un pilaf de arroz integral lleno de verduras. La mezcla de grasas saludables para el corazón, granos integrales ricos en fibra y verduras llenas de antioxidantes lo hace a la vez satisfactorio y nutritivo. Con un sazonado inteligente y sin azúcar añadida, es una opción amigable con la glucosa en la sangre (azúcar en la sangre) para personas con diabetes que buscan una comida sabrosa y completa. Es una receta DASH (Enfoques Alimentarios para Detener la Hipertensión) y baja en grasa.","4","3 onzas de salmón, 1 taza de pilaf",
["3 cucharaditas de aceite de oliva extra virgen (divididas)","2 zanahorias grandes (peladas y cortadas en cubos pequeños)","2 calabacitas pequeñas (en cubos)","1 cebolla amarilla mediana (en cubos pequeños)","1/2 cucharadita de pimienta negra molida","2 tazas de arroz integral (cocido)","2 tazas de agua","2 tazas de espinacas (picadas)","4 filetes de salmón (de 3 onzas cada uno)","1/4 de cucharadita de ajo en polvo","8 onzas de hongos portobello pequeños (en rodajas)","2 dientes de ajo (picados)","2 cucharaditas de salsa de soya baja en sodio"],
["Precaliente una sartén a fuego medio. Cuando esté caliente, agregue 1 cucharadita de aceite y gire la sartén para cubrir el fondo. Agregue las verduras y 1/4 de cucharadita de pimienta negra; cocine, revolviendo de vez en cuando, hasta que empiecen a ablandarse, de 3 a 4 minutos.","Agregue el arroz y las espinacas a la sartén y cocine, revolviendo de vez en cuando, hasta que el arroz esté caliente y las espinacas se hayan marchitado, de 2 a 3 minutos. Tape y reserve.","Precaliente otra sartén mediana a fuego medio-alto.","Mientras se calienta la sartén, seque los filetes con toallas de papel y colóquelos con la piel hacia abajo en un plato; sazone el lado de arriba con 1/4 de cucharadita de ajo en polvo y 1/4 de cucharadita de pimienta negra.","Cuando la sartén esté caliente, agregue 1 cucharadita de aceite y gire para cubrir el fondo. Agregue el salmón con la piel hacia abajo y cocine, volteándolo una sola vez, hasta que la piel esté crujiente y la carne opaca, de 3 a 4 minutos por lado. Pase a un plato limpio y cubra sin apretar con papel de aluminio. (Reserve la sartén para el siguiente paso).","Limpie la sartén con toallas de papel y vuelva a ponerla a fuego medio-alto; agregue la 1 cucharadita de aceite restante y gire para cubrir el fondo. Agregue los hongos y los 2 dientes de ajo; cocine, revolviendo de vez en cuando, hasta que se ablanden, de 4 a 5 minutos.","Agregue la salsa de soya a la sartén y siga cocinando hasta que el líquido se haya evaporado, de 1 a 2 minutos más; retire del fuego.","Para servir, divida el arroz, el salmón y los hongos entre los platos."],[],[]),
("سلمون مُحمَّر في المقلاة مع فطر مُلمَّع بالصويا وأرز بني بالخضار","طبق سلمون متوازن يجمع بين شرائح السلمون المقرمشة المحمّرة في المقلاة والفطر اللذيذ المُلمَّع بالصويا وأرز بني (بيلاف) غني بالخضار. يجعل مزيج الدهون الصحية للقلب والحبوب الكاملة الغنية بالألياف والخضار الغنية بمضادات الأكسدة هذه الوجبة مشبعة ومغذية. وبفضل التتبيل المدروس ودون سكر مضاف، فهو خيار مناسب لمستوى الغلوكوز في الدم (سكر الدم) لمرضى السكري الباحثين عن وجبة لذيذة ومتكاملة. وهذه وصفة مناسبة لحمية DASH (النهج الغذائي لوقف ارتفاع ضغط الدم) وقليلة الدسم.","4","3 أونصات سلمون، 1 كوب بيلاف",
["3 ملاعق صغيرة زيت زيتون بكر ممتاز (مقسّمة)","2 جزرة كبيرة (مقشّرة ومقطّعة مكعبات صغيرة)","2 كوسا صغيرة (مقطّعة مكعبات)","1 حبة بصل أصفر متوسطة (مقطّعة مكعبات صغيرة)","½ ملعقة صغيرة فلفل أسود مطحون","2 كوب أرز بني (مطبوخ)","2 كوب ماء","2 كوب سبانخ (مفرومة)","4 شرائح سلمون (3 أونصات لكل منها)","¼ ملعقة صغيرة مسحوق الثوم","8 أونصات فطر بيبي بيلا (مقطّع شرائح)","2 فص ثوم (مفروم)","2 ملعقة صغيرة صلصة صويا قليلة الصوديوم"],
["سخّن مقلاة مسبقًا على نار متوسطة. عندما تسخن، أضف 1 ملعقة صغيرة من الزيت وحرّكها لتغطية القاع. أضف الخضار و¼ ملعقة صغيرة من الفلفل الأسود؛ اطبخها مع التقليب من حين لآخر حتى تبدأ بالليونة، 3–4 دقائق.","أضف الأرز والسبانخ إلى المقلاة واطبخ مع التقليب من حين لآخر حتى يسخن الأرز جيدًا وتذبل السبانخ، 2–3 دقائق. غطِّ المقلاة وضعها جانبًا.","سخّن مقلاة متوسطة أخرى مسبقًا على نار متوسطة إلى عالية.","بينما تسخن المقلاة، جفّف شرائح السلمون بمناديل ورقية وضعها على طبق وجلدها إلى الأسفل؛ تبّل الوجه العلوي بـ¼ ملعقة صغيرة من مسحوق الثوم و¼ ملعقة صغيرة من الفلفل الأسود.","عندما تسخن المقلاة، أضف 1 ملعقة صغيرة من الزيت وحرّكها لتغطية القاع. أضف السلمون وجلده إلى الأسفل واطبخه مع قلبه مرة واحدة حتى يصبح الجلد مقرمشًا ويصبح اللحم معتمًا، 3–4 دقائق لكل جانب. انقله إلى طبق نظيف وغطِّه بورق الألمنيوم بشكل فضفاض. (احتفظ بالمقلاة للخطوة التالية).","امسح المقلاة بمناديل ورقية وأعدها إلى نار متوسطة إلى عالية؛ أضف 1 ملعقة صغيرة المتبقية من الزيت وحرّكها لتغطية القاع. أضف الفطر وفصَّي الثوم؛ اطبخ مع التقليب من حين لآخر حتى يلين، 4–5 دقائق.","أضف صلصة الصويا إلى المقلاة وواصل الطهي حتى يتبخر السائل، 1–2 دقيقة أخرى؛ ارفعها عن النار.","عند التقديم، وزّع الأرز والسلمون والفطر على الأطباق."],[],[])))
O.append(R(6562343,
("Hongos salteados con tomillo","Disfrute de una comida más amigable con la diabetes con estos deliciosos hongos salteados con tomillo. Llenos de sabor y sazonados a la perfección, son un complemento sabroso para cualquier comida. Pruebe un plato que satisface y apoya sus metas de control de la diabetes.","4","aprox. ¾ de taza",
["1 libra de hongos (como cremini o champiñones blancos) (en cuartos)","2 cucharadas de aceite de oliva","2 dientes de ajo (picados)","1 cucharada de hojas de tomillo fresco","1/8 de cucharadita de sal kosher (opcional)","1/8 de cucharadita de pimienta negra (opcional)","1 cucharada de jugo de limón (opcional, para darle un toque ácido)"],
["Caliente el aceite de oliva en una sartén grande a fuego medio-alto.","Agregue los hongos en rodajas a la sartén y cocine durante unos 6 a 8 minutos, revolviendo de vez en cuando, hasta que suelten su humedad y se doren.","Agregue el ajo picado y las hojas de tomillo fresco a la sartén. Saltee durante 1 a 2 minutos más, hasta que el ajo desprenda su aroma.","Sazone los hongos con sal (opcional) y pimienta negra, ajustando la cantidad al gusto. Si lo desea, rocíe los hongos con jugo de limón para darles un sabor ácido.","Siga cocinando los hongos durante un minuto más, revolviendo para distribuir los sabores de manera uniforme.","Retire del fuego y pase los hongos salteados con tomillo a una fuente para servir."],[],[]),
("فطر مُسوَّى بالزعتر","ارتقِ بوجباتك المناسبة لمرضى السكري مع هذا الفطر المُسوَّى بالزعتر. غنيٌّ بالنكهة ومتبَّل بإتقان، وهو إضافة لذيذة إلى أي وجبة. جرّب طبقًا يُشبعك ويدعم أهدافك في السيطرة على السكري.","4","نحو ¾ كوب",
["1 رطل فطر (مثل الكريميني أو الفطر الأبيض) (مقطّع أرباعًا)","2 ملعقة كبيرة زيت زيتون","2 فص ثوم (مفروم)","1 ملعقة كبيرة أوراق زعتر (ثايم) طازجة","⅛ ملعقة صغيرة ملح كوشر (اختياري)","⅛ ملعقة صغيرة فلفل أسود (اختياري)","1 ملعقة كبيرة عصير ليمون (اختياري، لإضفاء نكهة منعشة)"],
["سخّن زيت الزيتون في مقلاة كبيرة على نار متوسطة إلى عالية.","أضف الفطر المقطّع شرائح إلى المقلاة واطبخه نحو 6–8 دقائق مع التقليب من حين لآخر، حتى يفقد رطوبته ويصبح بنيًّا ذهبيًا.","أضف الثوم المفروم وأوراق الزعتر الطازجة إلى المقلاة. قلّب لمدة 1–2 دقيقة أخرى حتى تفوح رائحة الثوم.","تبّل الفطر بالملح (اختياري) والفلفل الأسود، مع ضبط الكمية حسب الذوق. إن رغبت، رشّ الفطر بعصير الليمون لنكهة منعشة.","واصل طهي الفطر دقيقة إضافية مع التقليب لتتوزع النكهات بالتساوي.","ارفعه عن النار وانقل الفطر المُسوَّى بالزعتر إلى طبق التقديم."],[],[])))
O.append(R(6563395,
("Hachís de verduras para el desayuno","Este hachís de verduras es una forma sustanciosa de comenzar el día y funciona muy bien para un brunch. Puede personalizarlo cambiando por cualquiera de sus verduras sin almidón favoritas.","4","1 taza",
["2 cucharadas de aceite de canola","1/2 taza de cebolla amarilla (en cubos)","1 pimiento mediano (en cubos)","2 calabacitas medianas (en cubos)","1 papa mediana (en cubos)","1/2 cucharadita de sal (dividida)","1/2 cucharadita de pimienta negra","1 taza de tomates cherry (en mitades)","2 dientes de ajo (picados)","1 cucharadita de pimentón ahumado","1/2 cucharadita de comino","4 huevos grandes"],
["Caliente el aceite en una sartén grande a fuego medio.","Agregue la cebolla y la papa en cubos y cocine hasta que la cebolla se ablande.","Incorpore el pimiento y las calabacitas en cubos y sazone con la pimienta negra y ¼ de cucharadita de sal. Cocine de 5 a 7 minutos, hasta que las verduras estén tiernas.","Agregue los tomates cherry, el ajo picado, el pimentón ahumado, el comino, ¼ de cucharadita de sal y pimienta. Cocine de 3 a 5 minutos más, hasta que los tomates se ablanden.","Haga cuatro huecos en la mezcla de verduras.","Casque un huevo en cada hueco. Sazone con ¼ de cucharadita de sal y pimienta negra.","Tape la sartén y cocine de 5 a 7 minutos, o hasta que los huevos estén cocidos a su gusto."],[],[]),
("هاش الخضار للفطور","هذا الهاش بالخضار طريقة مشبعة لبدء يومك، ويناسب وجبة البرانش أيضًا! يمكنك تخصيصه باستبدال أي من الخضار غير النشوية المفضلة لديك.","4","1 كوب",
["2 ملعقة كبيرة زيت كانولا","½ كوب بصل أصفر (مقطّع مكعبات)","1 حبة فلفل رومي متوسطة (مقطّعة مكعبات)","2 حبة كوسا متوسطة (مقطّعة مكعبات)","1 حبة بطاطس متوسطة (مقطّعة مكعبات)","½ ملعقة صغيرة ملح (مقسّمة)","½ ملعقة صغيرة فلفل أسود","1 كوب طماطم كرزية (مقطّعة نصفين)","2 فص ثوم (مفروم)","1 ملعقة صغيرة بابريكا مدخّنة","½ ملعقة صغيرة كمون","4 بيضات كبيرة"],
["سخّن الزيت في مقلاة كبيرة على نار متوسطة.","أضف البصل والبطاطس المقطّعين مكعبات واطبخهما حتى يلين البصل.","أضف الفلفل الرومي والكوسا المقطّعين مكعبات وتبّل بالفلفل الأسود و¼ ملعقة صغيرة من الملح. اطبخ 5–7 دقائق حتى تنضج الخضار.","أضف الطماطم الكرزية والثوم المفروم والبابريكا المدخّنة والكمون و¼ ملعقة صغيرة من الملح والفلفل. اطبخ 3–5 دقائق إضافية حتى تلين الطماطم.","اصنع أربع حفر في خليط الخضار.","اكسر بيضة واحدة في كل حفرة. تبّل بـ¼ ملعقة صغيرة من الملح والفلفل الأسود.","غطِّ المقلاة واطبخ 5–7 دقائق أو حتى تنضج البيضات حسب رغبتك."],[],[])))
O.append(R(6563572,
("Wrap de pollo con pesto","Estos wraps sabrosos son una buena forma de aprovechar el pollo al horno que le sobró y de incluir también verduras frescas. ¡Se preparan fácilmente en cinco minutos o menos!","2","1 wrap",
["4 onzas de pechuga de pollo cocida y deshebrada (aproximadamente 1/2 taza)","1 cucharada de pesto preparado","2 tortillas para wrap integrales bajas en carbohidratos","4 hojas de lechuga mantequilla o romana","4 cucharaditas de queso feta sin grasa","2 cucharadas de tiras de pimiento rojo asado","1 tomate pequeño (en rodajas finas)"],
["En un tazón pequeño, mezcle el pollo deshebrado con el pesto y reserve.","Coloque las tortillas sobre una superficie plana. Ponga las hojas de lechuga sobre la tortilla, dejando sin cubrir aproximadamente 1 pulgada del borde de la tortilla.","Divida el pollo entre las tortillas y extiéndalo sobre la lechuga.","Espolvoree el queso feta sobre el pollo y agregue las tiras de pimiento rojo y las rodajas de tomate.","Doble hacia adentro 1 pulgada aproximadamente dos lados opuestos de la tortilla. Tome uno de los otros lados y enróllelo hacia el lado contrario, formando un rollo apretado. Procure que el relleno no se salga. Corte el wrap enrollado por la mitad.","Sirva con una ensalada pequeña si lo desea."],[],[]),
("لفّة الدجاج بالبيستو","هذه اللفائف اللذيذة طريقة جيدة للاستفادة من بقايا الدجاج المخبوز وإضافة بعض الخضار الطازجة أيضًا. تحضيرها سهل في خمس دقائق أو أقل!","2","1 لفّة",
["4 أونصات صدر دجاج مطبوخ ومفتّت (نحو ½ كوب)","1 ملعقة كبيرة بيستو جاهز","2 رغيف تورتيلا للّفائف من الحبوب الكاملة قليل الكربوهيدرات","4 ورقات خس بيب أو خس روماني","4 ملاعق صغيرة جبن فيتا خالٍ من الدسم","2 ملعقة كبيرة شرائح فلفل أحمر مشوي","1 حبة طماطم صغيرة (مقطّعة شرائح رفيعة)"],
["في وعاء صغير، اخلط الدجاج المفتّت مع البيستو وضعه جانبًا.","ضع أرغفة التورتيلا على سطح مستوٍ. ضع أوراق الخس على التورتيلا مع ترك نحو 1 بوصة من حافتها دون تغطية.","وزّع الدجاج على أرغفة التورتيلا وافرده فوق الخس.","رشّ جبن الفيتا فوق الدجاج وأضف شرائح الفلفل الأحمر وشرائح الطماطم.","اطوِ جانبين متقابلين من التورتيلا إلى الداخل بمقدار 1 بوصة تقريبًا. خذ أحد الجانبين الآخرين ولفّه نحو الجانب المقابل لتحصل على لفّة محكمة. احرص على ألا تخرج الحشوة. اقطع اللفّة نصفين.","قدّمها مع سلطة جانبية إن رغبت."],[],[])))
O.append(R(6564680,ar=(
"سلطة الجرجير والكمثرى والجوز وجبن بيكورينو",
"بسيطة جدًا لكنها جميلة، وهي سلطة كلاسيكية في جنوب إيطاليا.",
"6","1/6 من الوصفة",
["6 أونصات جرجير","1 حبة كمثرى متوسطة","¼ كوب أنصاف الجوز","½ أونصة جبن بيكورينو رومانو (بارد، مبشور طازجًا على شكل رقائق)","2 ملعقة كبيرة خل بلسمي","2 ملعقة كبيرة زيت زيتون بكر ممتاز","½ ملعقة صغيرة فلفل أسود"],
["ضع الجرجير في وعاء سلطة كبير. قطّع الكمثرى إلى شرائح رفيعة قدر الإمكان وضعها فوق الجرجير. رشّ أنصاف الجوز فوقها. باستخدام مقشرة الخضار، قشّر ½ أونصة من جبن البيكورينو على شكل رقائق فوق وعاء السلطة.","رشّ الخل البلسمي فوق السلطة. ثم رشّ زيت الزيتون البكر الممتاز. أضف الفلفل. قلّب جيدًا. قدّمها."],[],[])))
O.append(R(6565884,
("Calabacitas amarillas y verdes asadas","Esta receta de calabacitas amarillas y verdes asadas es un acompañamiento amigable con la diabetes, en el que los colores vivos complementan los sabores intensos y caramelizados que se logran al asarlas.","4","½ taza",
["1 calabacita amarilla mediana (en medias lunas)","1 calabacita verde mediana","2 cucharadas de aceite de oliva","1 cucharadita de orégano seco","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["Precaliente el horno a 400 grados F.","En un tazón grande, mezcle las calabacitas con el aceite de oliva, el orégano seco, la sal y la pimienta.","Colóquelas en una bandeja para hornear y áselas de 15 a 20 minutos, hasta que estén tiernas."],[],[]),
("كوسا صفراء وخضراء مشوية بالفرن","وصفة الكوسا الصفراء والخضراء المشوية هذه طبق جانبي مناسب لمرضى السكري، حيث تتناغم الألوان الزاهية مع النكهات الغنية المكرمَلة التي يمنحها الشواء.","4","½ كوب",
["1 حبة كوسا صفراء متوسطة (مقطّعة على شكل أنصاف أقمار)","1 حبة كوسا خضراء متوسطة","2 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة أوريجانو مجفف","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا على 400 درجة فهرنهايت (200 درجة مئوية).","في وعاء كبير، قلّب الكوسا مع زيت الزيتون والأوريجانو المجفف والملح والفلفل.","ضعها على صينية الخَبز واشوها 15–20 دقيقة حتى تنضج."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c16_part1.json")
