from h import *
O=[]
O.append(R(6572091,ar=(
"زهيرات بروكلي مشوية على الطريقة الكوبية",
"تبحث عن طبق جانبي قليل الكربوهيدرات يتناسب مع أي بروتين رئيسي، ويمكن أن يكون أساسيًا في طريقة الطبق الصحي، ويضيف لمسة حارة إلى طعام خارق غني بالعناصر الغذائية؟ هذا طبق البروكلي المشوي البسيط من الشيف رونالدو لينارس يفي بالغرض. يضيف الكمون والليمون الأخضر نكهة حارة وحمضية تمنح الطبق مذاقًا كاريبيًا، ويضفي زيت الأفوكادو دهونًا صحية مفيدة للقلب. قدّمه مع لحم الخنزير المتبّل بالموخو من الشيف رونالدو وسلطة أرز القرنبيط لتحصل على وجبة مشبعة وقليلة الكربوهيدرات تليق بإجازة في جزيرة.",
"4","1 كوب",
["3 فص ثوم (مقشّر ومقطّع شرائح رفيعة)","¼ ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة عصير ليمون أخضر","⅛ ملعقة صغيرة فلفل أسود","½ كوب بصل إسباني (مقطّع شرائح رفيعة)","2 ملعقة صغيرة زيت أفوكادو","16 أونصة زهيرات بروكلي","1 ورقة زبدة (ورق خَبز)"],
["سخّن الفرن مسبقًا على 350° فهرنهايت (175° مئوية).","في وعاء، اخلط الثوم والكمون وعصير الليمون الأخضر والفلفل والبصل. قلّب المكوّنات جيدًا لتتوزع التوابل بالتساوي. أضف زيت الأفوكادو وزهيرات البروكلي إلى الوعاء وقلّب مرة أخرى.","ضع جميع المكوّنات على صينية خَبز مبطّنة بورق الزبدة واشوها لمدة 25 دقيقة.","أخرجها من الفرن، وتناول شوكة لتستمتع بهذا الطبق اللذيذ."],[],[])))
O.append(R(6575594,
("Berenjena horneada al estilo mediterráneo","La berenjena, rica en nutrientes, recibe un toque de inspiración mediterránea en esta receta sencilla de acompañamiento. Los tomates frescos, el queso feta desmenuzado y las hierbas llevan este plato amigable con la diabetes a otro nivel de sabor.","4","3/4 de taza",
["1 berenjena mediana (en rodajas)","2 cucharadas de aceite de oliva","2 dientes de ajo (picados)","1 cucharadita de orégano seco","1 cucharadita de tomillo seco","1/2 cucharadita de pimentón ahumado","1/8 de cucharadita de sal","1/4 de cucharadita de pimienta negra","1 taza de tomates cherry (en mitades)","1/4 de taza de queso feta (reducido en grasa, desmenuzado)","2 cucharadas de hojas de perejil fresco (para decorar)"],
["Precaliente el horno a 400 grados F.","Coloque las rodajas de berenjena en una bandeja para hornear.","En un tazón pequeño, bata el aceite de oliva, el ajo picado, el orégano seco, el tomillo seco, el pimentón ahumado, la sal y la pimienta negra.","Unte ambos lados de cada rodaja de berenjena con la mezcla de aceite de oliva.","Hornee en el horno precalentado durante 15 minutos, luego voltee las rodajas de berenjena y hornee 15 minutos más, o hasta que estén tiernas y doradas.","Saque la berenjena del horno.","Espolvoree los tomates cherry en mitades y el queso feta desmenuzado sobre la berenjena horneada.","Vuelva a colocar la bandeja en el horno y hornee 5 minutos más, o hasta que el queso feta se ablande y los tomates estén ligeramente asados."],[],[]),
("باذنجان مخبوز على الطريقة المتوسطية","يحصل الباذنجان الغني بالعناصر الغذائية على لمسة متوسطية في وصفة الطبق الجانبي السهلة هذه. تنقل الطماطم الطازجة وجبن الفيتا المفتّت والأعشاب هذا الطبق المناسب لمرضى السكري إلى مستوى أعلى من اللذة.","4","¾ كوب",
["1 حبة باذنجان متوسطة (مقطّعة شرائح دائرية)","2 ملعقة كبيرة زيت زيتون","2 فص ثوم (مفروم)","1 ملعقة صغيرة أوريجانو مجفف","1 ملعقة صغيرة زعتر (ثايم) مجفف","½ ملعقة صغيرة بابريكا مدخّنة","⅛ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 كوب طماطم كرزية (مقطّعة نصفين)","¼ كوب جبن فيتا (مخفّض الدسم، مفتّت)","2 ملعقة كبيرة أوراق بقدونس طازجة (للتزيين)"],
["سخّن الفرن مسبقًا على 400 درجة فهرنهايت (200 درجة مئوية).","ضع شرائح الباذنجان على صينية خَبز.","في وعاء صغير، اخفق زيت الزيتون والثوم المفروم والأوريجانو المجفف والزعتر المجفف والبابريكا المدخّنة والملح والفلفل الأسود.","ادهن وجهي كل شريحة باذنجان بخليط زيت الزيتون.","اخبزها في الفرن المسخّن مسبقًا 15 دقيقة، ثم اقلب شرائح الباذنجان واخبزها 15 دقيقة إضافية أو حتى تنضج وتصبح بنية ذهبية.","أخرج الباذنجان من الفرن.","انثر الطماطم الكرزية المقطّعة نصفين وجبن الفيتا المفتّت فوق الباذنجان المخبوز.","أعد الصينية إلى الفرن واخبزها 5 دقائق إضافية، أو حتى يلين الفيتا وتُشوى الطماطم قليلًا."],[],[])))
O.append(R(6576870,
("Ceviche de atún","El ceviche es un plato latino que tradicionalmente se prepara con pescado crudo marinado y «cocido» en jugos cítricos. Esta versión económica usa atún enlatado, pero ofrece el mismo sabor fresco y cítrico. El ceviche combina muy bien con galletas saladas, pero puede usar su galleta favorita o comerlo solo como parte de un almuerzo ligero.","3","1/4 de taza (aproximadamente 1 ⅓ onzas) + 6 galletas saladas",
["5 onzas de atún bajo en sodio en agua (escurrido)","1 cucharada de cilantro fresco (picado)","1/4 de taza de cebolla morada (picada)","1/4 de cucharadita de pimienta negra","1/4 de cucharadita de condimento de hierbas sin sal","3 cucharadas de jugo de limón","18 galletas saladas bajas en sodio"],
["Mezcle el atún, la cebolla, el cilantro, la pimienta negra y el condimento en un tazón pequeño. Agregue el jugo de limón y mezcle todo muy bien. Tape y refrigere por lo menos 2 horas para que se marine antes de servir."],[],[]),
("سيفيتشي التونة","السيفيتشي طبق لاتيني يُحضَّر تقليديًا من السمك النيئ المتبّل والمنضَج بعصائر الحمضيات. تستخدم هذه النسخة الاقتصادية التونة المعلّبة لكنها تمنح النكهة المنعشة الحامضة نفسها. يتناسب السيفيتشي جيدًا مع البسكويت المملح (سالتين)، لكن يمكنك استخدام أي بسكويت مفضل لديك أو تناوله وحده كجزء من غداء خفيف.","3","¼ كوب (نحو 1⅓ أونصة) + 6 قطع بسكويت",
["5 أونصات تونة قليلة الصوديوم معلّبة في الماء (مصفّاة)","1 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة)","¼ كوب بصل أحمر (مفروم)","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة خليط أعشاب خالٍ من الملح","3 ملاعق كبيرة عصير ليمون","18 قطعة بسكويت مملح قليل الصوديوم"],
["اخلط التونة والبصل والكزبرة الخضراء والفلفل الأسود وخليط التوابل في وعاء صغير. أضف عصير الليمون وامزج كل شيء جيدًا. غطِّه وضعه في الثلاجة لمدة ساعتين على الأقل ليتتبّل قبل التقديم."],[],[])))
O.append(R(6579046,ar=(
"يخنة العدس",
"يمكنك تجربة أنواع مختلفة من العدس في هذه اليخنة، جرّب العدس الأحمر أو الأصفر أو البني.",
"6","1 كوب",
["1 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مقطّعة مكعبات)","2 عود كرفس (مقطّع مكعبات)","3 حبات جزر صغيرة (أو 2 متوسطة، مقشّرة ومقطّعة مكعبات)","1 حبة فلفل هالابينو متوسطة (منزوعة البذور ومفرومة ناعمًا)","2 فص ثوم (مفروم)","1 كوب عدس","4 أكواب مرق خضار قليل الصوديوم","1 كوب ماء","1 ورقة غار","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","4 أكواب سبانخ صغيرة"],
["ضع الزيت في قدر شوربة على نار متوسطة إلى عالية. أضف البصل والكرفس والجزر والهالابينو وقلّبها حتى يصبح البصل شفافًا، نحو 5 دقائق.","أضف الثوم وقلّب دقيقة إضافية واحدة.","أضف العدس وصبّ مرق الخضار والماء.","أضف ورقة الغار والملح (اختياري) والفلفل الأسود المطحون. اتركها حتى تغلي. ثم خفّض الحرارة لتغلي بهدوء. اتركها على نار هادئة مع التغطية لمدة 40 دقيقة.","أزل ورقة الغار وأضف السبانخ وقلّب حتى تذبل."],[],[])))
O.append(R(6579178,ar=(
"كعكات الخضار الجذرية",
"تصلح هذه الكعكات طبقًا جانبيًا رائعًا أو وجبة خفيفة، وتتناسب تمامًا مع يخنة اللحم البقري والبطاطا الحلوة لدينا.",
"10","1 كعكة",
["1 حبة بطاطا حلوة كبيرة (نحو 10 أونصات) (مقشّرة ومبشورة)","1 حبة لفت سويدي (روتاباغا) متوسطة (نحو 10 أونصات) (مقشّرة ومبشورة)","2 حبة باستيناك (جذر البقدونس) صغيرة (نحو 6 أونصات إجمالًا) (مقشّرة ومبشورة)","1 بيضة كبيرة","3 بياضات بيض كبيرة","¼ كوب بقدونس طازج (مفروم)","2 فص ثوم (مفروم)","½ كوب دقيق القمح الكامل","½ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","1 بخّة (0.25 غ) بخاخ طهي غير لاصق"],
["سخّن الفرن مسبقًا على 375 درجة فهرنهايت (190 درجة مئوية). بطّن صينية خَبز كبيرة بورق الزبدة أو بحصيرة سيليكون.","اخلط جميع المكوّنات جيدًا في وعاء خلط كبير.","املأ كوب قياس ½ كوب بخليط الخضار الجذرية وأفرغه على صينية الخَبز. اضغط عليه برفق ليتشكل على هيئة كعكة. كرّر هذه العملية للكعكات التسع المتبقية (حسب حجم صينيتك، قد تحتاج إلى تحضيرها على دفعات أو استخدام صينيتين).","رشّ وجوه الكعكات ببخاخ الطهي واخبزها 35 دقيقة.","اترك الكعكات تبرد قليلًا قبل إخراجها من الصينية."],[],[])))
O.append(R(6579304,
("Ensalada de coles de Bruselas con aguacate, alcachofas y aderezo cremoso de miel y mostaza",None,"8","1/2 taza",
["2 dientes de ajo","2 cucharadas de mayonesa (de aceite de oliva)","4 cucharaditas de vinagre blanco","2 cucharaditas de miel","2 cucharaditas de mostaza Dijon","1 cucharadita de albahaca seca","1/8 de cucharadita de sal","1/8 de cucharadita de pimienta negra","1/2 libra de coles de Bruselas frescas","6 onzas de corazones de alcachofa (1 frasco, en salmuera; en cuartos, escurridos y enjuagados)","1/2 aguacate grande","1 cabeza de lechuga romana","1 cucharada de semillas de linaza enteras (tostadas)"],
["En un tazón grande, bata el ajo, la mayonesa, el vinagre, la miel, la mostaza Dijon, la albahaca, la sal y la pimienta.","Recorte las coles de Bruselas y córtelas en tiras finas; agréguelas al tazón con el aderezo.","Pique grueso las alcachofas y agréguelas al tazón.","Corte el aguacate en cubos medianos y agréguelo al tazón.","Pique o parta la lechuga en trozos del tamaño de un bocado y agréguela al tazón; mezcle para integrar la ensalada.","Sirva con un poco de linaza tostada espolvoreada por encima."],[],[]),
("سلطة براعم بروكسل مع الأفوكادو والخرشوف وتتبيلة العسل والخردل الكريمية",None,"8","½ كوب",
["2 فص ثوم","2 ملعقة كبيرة مايونيز (بزيت الزيتون)","4 ملاعق صغيرة خل أبيض","2 ملعقة صغيرة عسل","2 ملعقة صغيرة خردل ديجون","1 ملعقة صغيرة ريحان مجفف","⅛ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود","½ رطل براعم بروكسل طازجة","6 أونصات قلوب خرشوف (برطمان واحد، في محلول ملحي؛ مقطّعة أرباعًا ومصفّاة ومشطوفة)","½ حبة أفوكادو كبيرة","1 رأس خس روماني","1 ملعقة كبيرة بذور كتان كاملة (محمّصة)"],
["في وعاء كبير، اخفق الثوم والمايونيز والخل والعسل وخردل الديجون والريحان والملح والفلفل.","قصّ أطراف براعم بروكسل وقطّعها إلى شرائح رفيعة؛ وأضفها إلى الوعاء مع التتبيلة.","قطّع الخرشوف تقطيعًا خشنًا وأضفه إلى الوعاء.","قطّع الأفوكادو مكعبات متوسطة وأضفه إلى الوعاء.","قطّع الخس أو مزّقه إلى قطع بحجم لقمة وأضفه إلى الوعاء؛ قلّب لتمتزج السلطة.","قدّمها مع رشّة من بذور الكتان المحمّصة."],[],[])))
O.append(R(6580283,ar=(
"«آيس كريم» الموز بالشوكولاتة",
"من الصعب تصديق ذلك، لكن الموز المجمّد يشكّل قاعدة رائعة لهذا «الآيس كريم» الطري من أربعة مكوّنات والقليل الدهون المشبعة. اشترِ أوعية صغيرة أو أكوابًا صغيرة لتسهيل التحكم في الحصص عند تقديم الحلويات مثل هذه.",
"5","½ كوب",
["2 حبة موز متوسطة","⅓ كوب حليب خالي الدسم","2 ملعقة كبيرة مسحوق الكاكاو","1 كوب كريمة مخفوقة (خالية من الدسم)"],
["قشّر الموز وقطّعه إلى أقراص بسماكة ¼ بوصة. ضعه في وعاء وجمّده لمدة ساعتين على الأقل.","عندما يتجمّد الموز، ضع الموز والحليب ومسحوق الكاكاو في الخلاط. اخلطها حتى تصبح ناعمة.","أضف الكريمة المخفوقة بالطي الرفيق.","ضع الخليط في وعاء صالح للمجمّد وجمّده 30 دقيقة على الأقل.","اغرفه بمغرفة سعة ½ كوب عند التقديم."],[],[])))
O.append(R(6580857,
("Ensalada de garbanzos con aderezo cremoso de tahini","Esta ensalada de garbanzos, crujiente y refrescante, se mezcla con un cremoso aderezo casero de tahini para lograr una comida sencilla a base de plantas, llena de sabor y fibra. Los garbanzos aportan proteína que satisface y carbohidratos de digestión lenta que pueden ayudar a mantener estable la glucosa en la sangre (azúcar en la sangre). Es una opción nutritiva y sin cocción, especialmente adecuada para quienes buscan un almuerzo fresco y saciante.","4","3 tazas de ensalada + 2 cucharadas de aderezo",
["1/4 de taza de tahini","2 cucharadas de jugo de limón (fresco)","1 diente de ajo (machacado)","2 cucharadas de agua","1/4 de cucharadita de sal","8 tazas de lechuga romana (picada)","1 taza de tomates cherry (en mitades)","1 taza de pepino (en cubos)","1 taza de garbanzos enlatados (sin sal añadida, escurridos y enjuagados)","1/4 de taza de cebolla morada (en rodajas finas)","2 cucharadas de perejil fresco (picado)"],
["En un tazón mediano, mezcle el tahini, el jugo de limón fresco, el ajo machacado y la sal. Agregue poco a poco el agua fría, batiendo constantemente, hasta que el aderezo tenga una consistencia suave que se pueda verter.","En otro tazón grande, mezcle la lechuga romana picada, los tomates cherry, el pepino en cubos y los garbanzos. Agregue la cebolla morada en rodajas y el perejil picado. Rocíe el aderezo de tahini sobre la ensalada."],[],[]),
("سلطة الحمص مع تتبيلة الطحينة الكريمية","تُخلط سلطة الحمص المقرمشة والمنعشة هذه مع تتبيلة طحينة كريمية محضّرة في المنزل لتحصل على وجبة نباتية بسيطة غنية بالنكهة والألياف. يوفّر الحمص بروتينًا مُشبعًا وكربوهيدرات بطيئة الهضم قد تساعد على استقرار مستوى الغلوكوز في الدم (سكر الدم). وهي خيار مغذٍّ دون طهي، ومناسب خصوصًا لمن يبحثون عن غداء منعش ومشبع.","4","3 أكواب سلطة + ملعقتان كبيرتان من التتبيلة",
["¼ كوب طحينة","2 ملعقة كبيرة عصير ليمون (طازج)","1 فص ثوم (مهروس)","2 ملعقة كبيرة ماء","¼ ملعقة صغيرة ملح","8 أكواب خس روماني (مفروم)","1 كوب طماطم كرزية (مقطّعة نصفين)","1 كوب خيار (مقطّع مكعبات)","1 كوب حمص معلّب (بدون ملح مضاف، مصفّى ومشطوف)","¼ كوب بصل أحمر (مقطّع شرائح رفيعة)","2 ملعقة كبيرة بقدونس طازج (مفروم)"],
["في وعاء متوسط، اخلط الطحينة وعصير الليمون الطازج والثوم المهروس والملح. أضف الماء البارد تدريجيًا مع الخفق المستمر حتى تصل التتبيلة إلى قوام ناعم يمكن سكبه.","في وعاء كبير منفصل، اخلط الخس الروماني المفروم والطماطم الكرزية والخيار المقطّع مكعبات والحمص. أضف شرائح البصل الأحمر والبقدونس المفروم. رشّ تتبيلة الطحينة فوق السلطة."],[],[])))
O.append(R(6581480,ar=(
"سمك القد المشوي مع الطماطم والكوسا والزيتون",
"سمك القد سمك أبيض طري يتشرّب نكهات ما يُطهى معه. تجتمع حلاوة الطماطم والكوسا مع ملوحة الزيتون لتجعل من هذه الوجبة البحرية المستوحاة من المطبخ المتوسطي طبقًا مفضلًا بلا شك.",
"4","1 فيليه قد + ½ كوب خضار",
["1 كوب طماطم روما (برقوقية) (مقطّعة مكعبات)","2 حبة كوسا كبيرة (مقطّعة مكعبات)","1 حبة بصل أصفر متوسطة (مقطّعة شرائح)","⅛ ملعقة صغيرة ملح كوشر","⅛ ملعقة صغيرة فلفل أسود (مطحون طازجًا)","2 ملعقة كبيرة زيت زيتون بكر ممتاز","2 فص ثوم (مفروم)","¼ كوب زيتون كالاماتا (منزوع النوى ومقطّع مكعبات)","¼ كوب ريحان (مفروم)","4 شرائح فيليه سمك قد (4–6 أونصات لكل منها)","2 ملعقة كبيرة عصير ليمون أخضر طازج"],
["سخّن الفرن مسبقًا على 425° فهرنهايت (220° مئوية).","ضع الطماطم والكوسا والبصل في طبق خَبز كبير وتبّلها بالملح والفلفل. رشّ زيت الزيتون واشوها نحو 20 دقيقة أو حتى تنضج الخضار.","أخرجها من الفرن وأضف الثوم والزيتون والريحان وقلّب. ضع شرائح سمك القد فوق الخضار ورشّ عليها الملح والفلفل. رشّ عصير الليمون الأخضر. أعدها إلى الفرن. اخبزها نحو 15 دقيقة حتى ينضج السمك تمامًا."],[],[])))
O.append(R(6585792,
("Zanahorias salteadas perfectas","Puede que suene atrevido, pero creemos que esta es la manera perfecta de saltear zanahorias. Caramelizar ligeramente las zanahorias agrega una riqueza y una dulzura deliciosas a esta receta sencilla, que seguramente será un éxito con toda la familia.","4","1/2 taza",
["3 cucharadas de aceite de oliva","1 libra de zanahorias (peladas y cortadas en bastones de 2 a 3 pulgadas)","1/2 cucharadita de sal","1/2 cucharadita de tomillo seco","1/4 de cucharadita de pimienta negra"],
["En una sartén grande, caliente el aceite de oliva a fuego medio.","Agregue las zanahorias a la sartén y extiéndalas en una sola capa.","Saltee las zanahorias de 8 a 10 minutos, revolviendo de vez en cuando, hasta que estén tiernas pero crujientes y ligeramente caramelizadas.","Sazone las zanahorias con la sal, el tomillo y la pimienta negra."],[],[]),
("جزر مُقلَّب مثالي","قد يبدو هذا جريئًا، لكننا نعتقد أنها الطريقة المثالية لتقليب الجزر! تكرمل الجزر قليلًا يضيف غنى وحلاوة لذيذين إلى هذه الوصفة البسيطة، وستنال بالتأكيد إعجاب العائلة كلها.","4","½ كوب",
["3 ملاعق كبيرة زيت زيتون","1 رطل جزر (مقشّر ومقطّع إلى أعواد بطول 2–3 بوصات)","½ ملعقة صغيرة ملح","½ ملعقة صغيرة زعتر (ثايم) مجفف","¼ ملعقة صغيرة فلفل أسود"],
["في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة.","أضف الجزر إلى المقلاة وافرده في طبقة واحدة.","قلّب الجزر 8–10 دقائق مع التحريك من حين لآخر، حتى يصبح طريًا مع بقاء قرمشة خفيفة ويتكرمل قليلًا.","تبّل الجزر بالملح والزعتر والفلفل الأسود."],[],[])))
O.append(R(6586304,
("Berza, papa y frijoles blancos estofados","El clásico plato campesino italiano de frijoles y verduras de hoja verde, preparado con berza fresca y frijoles cannellini, con un toque picante de hojuelas de pimiento rojo. Un delicioso acompañamiento o almuerzo ligero.","4","1 1/2 tazas de papas y berza por porción",
["1 libra de berza (col rizada tipo collard)","1 cucharada de vinagre blanco (vinagre blanco, de vino blanco o de manzana)","1 cucharada de aceite de oliva extra virgen","1/4 de taza de agua","1 cebolla amarilla pequeña (cortada en trozos grandes)","1 papa mediana (cortada en trozos grandes)","3 tomates medianos (en cubos)","1 cucharadita de orégano seco","1 lata (de 15 onzas) de frijoles blancos reducidos en sodio (cannellini o Great Northern) (escurridos y enjuagados)","1/2 cucharadita de hojuelas de pimiento rojo machacadas (opcional)"],
["Para preparar la berza: pase cada hoja bajo el chorro de agua fría para limpiarla. Corte la nervadura del centro de cada hoja y pique las hojas en trozos pequeños. Deseche las nervaduras. Coloque las hojas picadas en un tazón grande y cúbralas con agua; agregue un chorrito de vinagre. Deje reposar 15 minutos.","Caliente una olla grande y pesada (como una olla holandesa) a fuego medio y agregue el aceite.","Agregue las cebollas a la olla y cocine, revolviendo de vez en cuando, hasta que empiecen a ablandarse, de 4 a 5 minutos.","Agregue la berza escurrida y cocine, revolviendo de vez en cuando, hasta que se marchite, de 3 a 4 minutos.","Agregue las papas, el orégano, los tomates y el agua. Cocine a fuego bajo, ligeramente tapado, de 20 a 30 minutos, hasta que las papas estén tiernas al pincharlas con un tenedor.","Incorpore los frijoles blancos. Decore con hojuelas de pimiento rojo machacadas, si lo desea."],[],[]),
("كرنب أخضر (كولارد) مطهو مع البطاطس والفاصولياء البيضاء","الطبق الإيطالي الريفي الكلاسيكي من الفاصولياء والخضار الورقية، يُحضَّر بالكرنب الأخضر الطازج (كولارد) وفاصولياء كانيليني مع لمسة حارة من رقائق الفلفل الأحمر. طبق جانبي لذيذ أو غداء خفيف.","4","1½ كوب من البطاطس والخضار الورقية لكل حصة",
["1 رطل كرنب أخضر (كولارد)","1 ملعقة كبيرة خل أبيض (خل أبيض أو خل نبيذ أبيض أو خل تفاح)","1 ملعقة كبيرة زيت زيتون بكر ممتاز","¼ كوب ماء","1 حبة بصل أصفر صغيرة (مقطّعة إلى قطع كبيرة)","1 حبة بطاطس متوسطة (مقطّعة إلى قطع كبيرة)","3 حبات طماطم متوسطة (مقطّعة مكعبات)","1 ملعقة صغيرة أوريجانو مجفف","1 علبة (15 أونصة) فاصولياء بيضاء مخفّضة الصوديوم (كانيليني أو غريت نورذرن) (مصفّاة ومشطوفة)","½ ملعقة صغيرة رقائق فلفل أحمر مجروشة (اختياري)"],
["لتحضير الكرنب: مرّر كل ورقة تحت الماء البارد الجاري لتنظيفها. اقطع العرق من وسط كل ورقة وقطّع الأوراق إلى قطع صغيرة. تخلّص من الأعراق. ضع الأوراق المقطّعة في وعاء كبير وغطِّها بالماء؛ وأضف رشّة من الخل. اتركها 15 دقيقة.","سخّن قدرًا كبيرة ثقيلة (مثل القدر الهولندية) على نار متوسطة وأضف الزيت.","أضف البصل إلى القدر واطبخه مع التقليب من حين لآخر حتى يبدأ بالليونة، 4–5 دقائق.","أضف الكرنب المصفّى واطبخه مع التقليب من حين لآخر حتى يذبل، 3–4 دقائق.","أضف البطاطس والأوريجانو والطماطم والماء. اطبخ على نار هادئة والقدر مغطّى جزئيًا لمدة 20–30 دقيقة، حتى تلين البطاطس عند غرزها بالشوكة.","أضف الفاصولياء البيضاء وقلّب. زيّن برقائق الفلفل الأحمر المجروشة إن رغبت."],[],[])))
O.append(R(6586871,ar=(
"صلصة غمس حلوة وحارة",
"هذه صلصة الغمس مثالية للسبرينغ رول وأجنحة الدجاج والتوفو المقرمش وكعكات السلطعون، وتحضيرها في غاية السهولة!",
"8","1 ملعقة كبيرة",
["1 ملعقة صغيرة صلصة ثوم وفلفل حار على الطريقة التايلاندية (أو صلصة حارة أخرى)","½ كوب مربى مشمش بدون سكر مضاف (مخفّض السكر)","1 ملعقة صغيرة صلصة صويا (مخفّضة الصوديوم)"],
["للتحضير، اخلط ½ كوب من مربى المشمش المخفّض السكر مع 1 ملعقة صغيرة من صلصة الثوم والفلفل الحار على الطريقة التايلاندية (أو صلصة حارة أخرى) و1 ملعقة صغيرة من صلصة الصويا المخفّضة الصوديوم في وعاء و","سخّنها في الميكروويف لمدة 30 ثانية."],[],[])))
O.append(R(6586894,
("Omelet de claras de huevo con espinacas y queso feta","Este omelet ligero y sabroso está relleno de verduras salteadas y queso feta ácido, y se sirve con pan tostado de granos integrales germinados para una comida equilibrada y rica en fibra. Usar principalmente claras de huevo mantiene baja la grasa saturada y aun así aporta proteína que satisface. Es una gran opción de desayuno para personas con diabetes que desean mantener estable la glucosa en la sangre (azúcar en la sangre) sin sacrificar el sabor. Es una receta DASH (Enfoques Alimentarios para Detener la Hipertensión), vegetariana, baja en grasa y baja en carbohidratos.","4","1 omelet y 1 rebanada de pan tostado",
["4 huevos grandes","3/4 de taza de claras de huevo","1/4 de cucharadita de pimienta negra molida","1/8 de cucharadita de ajo en polvo","1/8 de cucharadita de pimentón ahumado","1 cucharadita de aceite de oliva","1/4 de taza de cebolla morada (finamente picada)","1 pimiento rojo entero (finamente picado)","1 taza de espinacas baby frescas (picadas)","1 capa de aceite en aerosol antiadherente","4 cucharaditas de queso feta sin grasa (desmenuzado)","4 rebanadas de pan de granos germinados, Ezekiel 4:9 sin harina, bajo en sodio"],
["Coloque los huevos y las claras en un tazón mediano. Bata junto con la pimienta negra, el ajo en polvo y el pimentón ahumado.","Caliente el aceite de oliva en una sartén antiadherente a fuego medio. Agregue la cebolla morada y el pimiento. Saltee de 2 a 3 minutos hasta que se ablanden. Incorpore las espinacas y cocine de 1 a 2 minutos más, hasta que se marchiten. Retire las verduras de la sartén y reserve.","Limpie la sartén y rocíela con aceite en aerosol. Vuelva a ponerla a fuego medio-bajo. Vierta 1/4 de la mezcla de huevo en la sartén, inclinándola para distribuirla de manera uniforme. Cocine de 2 a 3 minutos hasta que los bordes estén firmes. Espolvoree 1/4 de las verduras cocidas y 1 cucharadita de queso feta en un lado del omelet.","Doble suavemente el omelet por la mitad y cocine de 1 a 2 minutos más, hasta que cuaje por completo. Pase a un plato y repita con los omelets restantes. Tueste ligeramente las rebanadas de pan."],[],[]),
("أومليت بياض البيض بالسبانخ والفيتا","هذا الأومليت الخفيف واللذيذ محشو بالخضار المقلّبة وجبن الفيتا المنعش، ويُقدَّم مع خبز محمّص من الحبوب الكاملة المستنبتة لوجبة متوازنة غنية بالألياف. استخدام بياض البيض في الغالب يُبقي الدهون المشبعة منخفضة مع الحصول على بروتين مُشبع. وهو خيار فطور رائع لمرضى السكري الذين يريدون الحفاظ على استقرار مستوى الغلوكوز في الدم (سكر الدم) دون التضحية بالنكهة. وهذه وصفة مناسبة لحمية DASH (النهج الغذائي لوقف ارتفاع ضغط الدم)، ونباتية، وقليلة الدسم، وقليلة الكربوهيدرات.","4","أومليت واحد وشريحة خبز محمّص",
["4 بيضات كبيرة","¾ كوب بياض البيض","¼ ملعقة صغيرة فلفل أسود مطحون","⅛ ملعقة صغيرة مسحوق الثوم","⅛ ملعقة صغيرة بابريكا مدخّنة","1 ملعقة صغيرة زيت زيتون","¼ كوب بصل أحمر (مقطّع مكعبات صغيرة جدًا)","1 حبة فلفل رومي أحمر (مقطّعة مكعبات صغيرة جدًا)","1 كوب سبانخ صغيرة طازجة (مفرومة)","1 طبقة بخاخ طهي غير لاصق","4 ملاعق صغيرة جبن فيتا خالٍ من الدسم (مفتّت)","4 شرائح خبز من الحبوب الكاملة المستنبتة، إزيكيل 4:9 بدون دقيق، قليل الصوديوم"],
["ضع البيض وبياض البيض في وعاء متوسط. اخفقها مع الفلفل الأسود ومسحوق الثوم والبابريكا المدخّنة.","سخّن زيت الزيتون في مقلاة غير لاصقة على نار متوسطة. أضف البصل الأحمر والفلفل الرومي. قلّبهما 2–3 دقائق حتى يلينا. أضف السبانخ واطبخ 1–2 دقيقة إضافية حتى تذبل. أخرج الخضار من المقلاة وضعها جانبًا.","امسح المقلاة ورشّها ببخاخ الطهي. أعدها إلى نار متوسطة إلى منخفضة. اسكب ¼ خليط البيض في المقلاة مع إمالتها ليتوزع بالتساوي. اطبخ 2–3 دقائق حتى تتماسك الحواف. رشّ ¼ الخضار المطبوخة وملعقة صغيرة واحدة من جبن الفيتا على أحد جانبي الأومليت.","اطوِ الأومليت برفق إلى نصفين واطبخه 1–2 دقيقة إضافية حتى يتماسك تمامًا. انقله إلى طبق وكرّر العملية مع بقية الأومليت. حمّص شرائح الخبز تحميصًا خفيفًا."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c16_part3.json")
