from mk import *
R=[]
R.append((9523761,"Selai Chia Blueberry Sehat - Rendah Gula + Tanpa Pektin!",
"Selai chia blueberry yang lezat dengan pemanis alami, dengan sentuhan rasa lemon yang asam segar.",
"16 porsi","1 porsi",
["4 cangkir blueberry segar atau blueberry beku yang sudah dicairkan","1 sendok makan parutan kulit lemon dari sekitar 1 buah lemon besar","⅓ cangkir air lemon dari sekitar 1 buah lemon besar (lemon yang sama)","2 sendok makan sirup maple opsional","⅓ cangkir biji chia"],
["Masukkan blueberry, air lemon, parutan kulit lemon, dan sirup maple (jika digunakan) ke dalam panci saus berukuran sedang. Didihkan perlahan dengan api sedang selama sekitar 5 menit. Anda akan melihat blueberry mulai pecah.","Kemudian tumbuk perlahan dengan penumbuk kentang atau garpu besar hingga sekitar setengah dari blueberry hancur, sisakan beberapa potongan utuh.","Besarkan api dan didihkan selama 5 menit untuk mengurangi sebagian cairan. Lalu matikan api dan aduk biji chia ke dalamnya.","Pindahkan selai chia blueberry ke dalam toples yang bersih dan kering, lalu simpan di lemari es atau bekukan."],
["Anda memerlukan 1 buah lemon besar untuk kulit sekaligus air lemonnya. Pastikan Anda memarut kulit lemon sebelum memeras airnya. Jangan terlalu menumbuk selai hingga menjadi bubur. Beberapa potongan blueberry akan memberi tekstur yang enak. Jika selai tampak encer setelah dididihkan, jangan khawatir. Biji chia akan menyerap sebagian besar kelebihan cairan saat selai mendingin. Untuk tekstur yang lebih halus (jika Anda tidak suka tekstur chia), haluskan biji chia sebelum dimasukkan ke dalam selai. Coba juga dengan buah beri lain seperti raspberry dan/atau blackberry. Atau coba versi stroberi kami di sini. Simpan selai dalam toples kaca yang bersih di lemari es hingga 2 minggu atau bekukan hingga 6 bulan. Saya suka menyimpannya dalam 2 toples terpisah, satu untuk lemari es dan satu untuk freezer."],
[]))
R.append((9529012,"Kacang Polong Air Fryer (Dua Rasa)",
"Kacang polong air fryer adalah hidangan pendamping yang luar biasa dan penuh rasa, yang bisa Anda buat dalam 10 menit!",
"2 porsi","1 porsi",
[("Rasa BBQ","1 cangkir kacang polong beku yang sudah dicairkan"),("Rasa BBQ","1 sendok teh bubuk bawang putih"),("Rasa BBQ","1 sendok teh paprika asap"),("Rasa BBQ","garam + merica secukupnya"),("Rasa Italia","1 cangkir kacang polong beku yang sudah dicairkan"),("Rasa Italia","1 sendok teh bubuk bawang putih"),("Rasa Italia","1 sendok teh bumbu Italia"),("Rasa Italia","garam + merica secukupnya")],
["Masukkan kacang polong yang sudah dicairkan ke dalam mangkuk kecil dan tambahkan bumbu pilihan Anda. Aduk rata, lalu susun kacang polong dalam satu lapisan di keranjang air fryer.","Masak kacang polong dengan air fryer pada suhu 350℉/176℃ selama 8-12 menit, atau hingga tingkat kematangan yang diinginkan. Aduk atau goyangkan keranjang setiap 2-3 menit."],
["Susun kacang polong dalam satu lapisan agar matang merata.","Goyangkan keranjang atau aduk kacang polong setiap 2-3 menit agar tidak lengket dan/atau gosong."],
[]))
R.append((9529996,"Kue Mentega Pecan Vegan [Tanpa Minyak]",
"Kue mentega pecan vegan yang LUAR BIASA! Kuenya lembap, lembut seperti mentega, asin-manis, dan SANGAT enak!",
"12 kue","1 porsi",
["1 cangkir selai kacang pecan","⅓ cangkir gula kelapa tidak dimurnikan atau gula merah","½ sendok teh baking powder","1 sendok teh vanili opsional tetapi disarankan","1 sendok teh kayu manis opsional tetapi disarankan","¼ sendok teh garam laut opsional tetapi disarankan","1-2 sendok makan susu mete tanpa pemanis atau susu pilihan Anda"],
["Panaskan oven terlebih dahulu hingga 350 derajat F dan alasi loyang besar dengan kertas roti.","Dalam mangkuk berukuran sedang, masukkan semua bahan, mulai dengan hanya 1 sendok makan susu, lalu aduk rata. Adonan harus kental dan lengket. Jika terasa terlalu kering untuk menyatu, tambahkan sendok makan susu yang kedua.","Gunakan sendok es krim kue ukuran KECIL, atau sendok makan, untuk menyendok adonan kue ke loyang, sisakan banyak ruang di antara setiap kue. Anda akan mendapatkan 12-14 kue. Gunakan garpu untuk menekan setiap kue dengan lembut agar lebih mudah melebar. Kue akan terus melebar di dalam oven.","Panggang selama 10-11 menit lalu keluarkan dari oven. Kue akan terasa lembut dan seperti belum matang, ini normal, jadi jangan langsung dimakan begitu keluar dari oven. Diamkan setidaknya 10 menit sebelum disentuh. Lalu pindahkan ke rak pendingin untuk terus mendingin dan mengeras sepenuhnya."],
["Pastikan hanya menggunakan 1 sendok makan susu pada awal mengaduk adonan. Tergantung kekentalan selai kacang Anda, Anda mungkin memerlukan sendok makan kedua atau tidak. Mungkin menggoda, tetapi jangan sentuh kue Anda setelah dikeluarkan dari oven. Diamkan selama 10 menit sebelum disentuh, karena kue akan sangat lembut dan terasa belum matang sebelum dingin. Untuk gula yang lebih sedikit, Anda dapat menguranginya menjadi ¼ cangkir dengan hasil yang serupa. Simpan kue Anda pada suhu ruang dalam wadah selama 2-3 hari, atau simpan di lemari es hingga 1 minggu. Anda dapat membekukannya dalam wadah kedap udara hingga 3 bulan."],
[]))
R.append((9532392,"Sup Miso Tomat Panggang",
"Sup miso tomat yang luar biasa, dibuat hanya dengan enam bahan tetapi penuh rasa.",
"4 porsi","1 porsi",
["2 pon tomat matang di pohon dibelah empat","1 bawang bombai kuning dibelah empat","6 siung bawang putih tidak dikupas","2 cangkir kaldu sayuran rendah natrium","¼ cangkir pasta miso putih","½ cangkir kacang cannellini putih matang atau kalengan","garam + merica secukupnya",("Untuk Hiasan","basil atau peterseli segar"),("Untuk Hiasan","kerupuk, crouton, atau roti renyah")],
["Panaskan oven terlebih dahulu hingga 425℉/218℃ dengan mode convection roast dan alasi loyang besar dengan kertas roti.","Susun tomat yang sudah dibelah empat, bawang bombai, dan siung bawang putih (jangan kupas bawang putihnya) di atas loyang, lalu panggang selama 25 menit, atau hingga sayuran berwarna cokelat keemasan. Keluarkan dari oven.","Setelah dipanggang, kupas bawang putih (kulitnya akan mudah terlepas sekarang), lalu masukkan sayuran panggang, kaldu, pasta miso, dan kacang ke dalam blender dan proses hingga benar-benar halus. Cicipi untuk garam dan merica, lalu sajikan."],
["Gunakan kaldu sayuran rendah natrium karena pasta miso juga memberi rasa asin. Setelah diblender, cicipi dan tambahkan garam dan merica jika perlu.","Jika Anda tidak punya oven convection, gunakan suhu yang sama, tetapi perlu diingat Anda mungkin membutuhkan tambahan sekitar 5 menit untuk memanggang sayuran.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari, atau bekukan dalam wadah kedap udara hingga 3 bulan."],
[]))
R.append((9537373,"Kentang Wedges Air Fryer",
"Siap untuk kentang wedges air fryer yang paling renyah? Penuh rasa, dengan usaha yang sedikit, dan matang dalam 15 menit!",
"2 porsi","1 porsi",
["1 pon kentang russet sekitar 2 buah besar","1 sendok makan minyak alpukat opsional","½ sendok teh bubuk bawang putih","½ sendok teh rosemary kering yang dihaluskan","½ sendok teh peterseli kering","½ sendok teh garam laut"],
["Kupas atau sikat kentang hingga bersih, lalu potong menjadi wedges. (Lihat di atas untuk foto prosesnya, jika perlu.)","Masukkan potongan kentang wedges ke dalam mangkuk dan rendam dengan air dingin setidaknya selama 20 menit. Lalu tiriskan dan keringkan dengan lap dapur yang bersih. Lap mangkuk hingga kering, lalu masukkan kembali wedges ke dalamnya.","Tambahkan minyak (jika digunakan) dan semua bumbu, lalu aduk hingga terlapisi merata. Kemudian pindahkan kentang wedges yang sudah dibumbui ke keranjang air fryer dalam satu lapisan, sisakan sedikit ruang di antaranya. (Masak secara bertahap, jika perlu.)","Masak dengan air fryer pada suhu 400 derajat F selama 15 menit, aduk sekali di pertengahan waktu. Sajikan dengan saus tomat, mayones pedas, atau saus celup favorit Anda."],
["Meskipun opsional, saya menyarankan merendam wedges kentang mentah agar hasilnya paling renyah. Terutama jangan lewati langkah ini jika Anda memilih untuk tidak menggunakan minyak. Resep ini telah diuji dengan minyak maupun tanpa minyak. Hasilnya serupa, tetapi opsi dengan minyak menghasilkan tekstur yang sedikit lebih renyah, seperti yang diperkirakan. Ubah bumbunya setiap kali dengan salah satu campuran rempah saya yang tercantum di atas. Kentang wedges paling enak saat baru dibuat, tetapi sisanya dapat disimpan di lemari es hingga 3 hari."],
[]))
R.append((9539328,"Tahu Lengket ala Asia",
"Tahu yang manis, pedas, dan lengket ini renyah di luar dan empuk di dalam. Hidangan bergaya Asia ini penuh dengan rasa dan dijamin mengesankan.",
"4 porsi","1 porsi",
[("Untuk tahu","12 ons (340 gram) tahu ekstra padat"),("Untuk tahu","2 sendok makan tamari rendah natrium atau kecap asin rendah natrium jika tidak menghindari gluten"),("Untuk tahu","2 sendok makan tepung beras cokelat"),("Untuk tahu","1 sendok teh bubuk bawang bombai"),("Untuk tahu","1 sendok teh bubuk bawang putih"),("Untuk saus tahu lengket","⅓ cangkir tamari rendah natrium atau kecap asin"),("Untuk saus tahu lengket","⅓ cangkir gula kelapa tidak dimurnikan atau gula merah"),("Untuk saus tahu lengket","⅓ cangkir air"),("Untuk saus tahu lengket","¼ cangkir cuka beras"),("Untuk saus tahu lengket","2 siung bawang putih dicincang halus"),("Untuk saus tahu lengket","1 sendok makan sriracha atau saus pedas pilihan Anda"),("Untuk saus tahu lengket","½ sendok teh jahe bubuk"),("Untuk saus tahu lengket","2 sendok makan tepung beras cokelat"),("Untuk penyajian (opsional)","Mi bihun atau nasi merah"),("Untuk penyajian (opsional)","daun bawang atau kucai"),("Untuk penyajian (opsional)","biji wijen")],
[("Tekan tahu","Potong tahu menjadi dadu setengah inci. Lalu susun beberapa lembar tisu dapur atau lap dapur bersih di atas talenan dan letakkan potongan tahu dalam satu lapisan di atasnya. Sekarang tambahkan tisu dapur lagi di atas potongan tahu dan letakkan talenan lain, piring datar, atau loyang di atasnya. Terakhir, letakkan benda yang sangat berat di atasnya seperti wajan besi cor atau buku tebal. Tekan seperti ini selama 15 menit sambil Anda menyiapkan bahan-bahan lainnya."),("Untuk tahu","Panaskan oven terlebih dahulu hingga 425°F/218°C dengan mode convection bake dan alasi loyang dengan kertas roti."),("Untuk tahu","Setelah tahu dipres, masukkan potongan tahu ke dalam mangkuk pencampur berukuran sedang bersama 2 sendok makan tamari, lalu aduk perlahan. Kemudian tambahkan 2 sendok makan tepung, serta bubuk bawang bombai dan bawang putih. Aduk perlahan hingga potongan tahu terlapisi merata."),("Untuk tahu","Susun potongan tahu yang sudah dilapisi dalam satu lapisan di atas loyang, sisakan banyak ruang di antara setiap potongan. Panggang selama 25-30 menit, balik sekali di pertengahan waktu. CATATAN: Jika Anda tidak punya oven convection, mungkin diperlukan waktu sedikit lebih lama untuk mencapai tingkat kerenyahan yang diinginkan."),("Untuk saus tahu lengket","Selagi tahu dipanggang, campurkan semua bahan saus tahu lengket dalam panci berukuran sedang. Kocok hingga tercampur dan didihkan perlahan selama 5 menit, hingga sedikit mengental. Lalu matikan api."),("Untuk saus tahu lengket","Masukkan tahu panggang ke dalam panci berisi saus, lalu aduk perlahan hingga setiap potongan terlapisi."),("Untuk saus tahu lengket","Sajikan tahu lengket Anda dengan nasi atau mi, lalu taburi dengan daun bawang atau kucai dan biji wijen.")],
["Susun potongan tahu dalam satu lapisan dengan ruang di antara setiap potongan. Potongan tidak boleh saling menyentuh di atas loyang agar mencapai tingkat kerenyahan maksimal. Jika Anda tidak punya oven convection, mungkin diperlukan beberapa menit tambahan agar tahu Anda renyah. Panggang hingga tingkat kerenyahan yang diinginkan tercapai. Untuk tekstur terbaik, nikmati tahu lengket ala Asia Anda segera. Semakin lama direndam dalam saus, bagian luarnya yang renyah akan mulai berkurang. Hidangan tahu lengket ini paling enak saat baru dibuat. Namun, sisanya dapat disimpan di lemari es dalam wadah tertutup selama 3-4 hari. Untuk memanaskan kembali, tambahkan sedikit air ke dalam wajan berisi tahu agar sausnya mencair."],
[]))
R.append((9539871,"Wafel Protein Pisang",
"Wafel protein pisang bebas gluten ini penuh rasa, dimaniskan secara alami, dan mengandung 8 gram protein hanya dalam satu wafel kecil.",
"8 wafel","1 porsi",
["1 cangkir pisang tumbuk sekitar 3 pisang besar","⅓ cangkir + 1 sendok makan susu kedelai atau susu nabati pilihan Anda","100 gram tepung almond tanpa kulit ari sekitar 1 cangkir","100 gram bubuk selai kacang sekitar 1 cangkir","2 sendok teh baking powder","1 sendok teh kayu manis"],
["Panaskan cetakan wafel Anda dengan api sedang dan olesi minyak jika perlu.","Tumbuk pisang hingga benar-benar halus dan campurkan dengan susu dalam mangkuk pencampur berukuran sedang. Lalu tambahkan bahan-bahan kering dan aduk hingga tercampur rata.","Sendokkan adonan wafel ke cetakan wafel yang sudah dipanaskan dan masak sesuai petunjuk pabrikan untuk merek cetakan wafel Anda. Punya saya membutuhkan 3-4 menit per adonan. Untuk memeriksa wafel, angkat tutupnya perlahan dan hati-hati untuk memastikan wafel tidak menempel. Jika wafel menempel, berarti belum matang, jadi lanjutkan memasak sekitar satu menit lagi sebelum memeriksanya kembali.","Sajikan wafel protein pisang Anda dengan topping favorit Anda."],
["Timbang tepung dan bubuk Anda untuk hasil terbaik. Jika menyendok langsung dari kantong, jumlahnya bisa terlalu banyak dan Anda memerlukan lebih banyak cairan agar adonan memiliki kekentalan yang tepat.","Jika Anda tidak punya timbangan dapur, sendokkan tepung ke dalam cangkir takar Anda dan gunakan pisau untuk meratakan kelebihannya.","Gunakan pisang yang sangat matang dengan bintik-bintik cokelat untuk rasa terbaik.","Pastikan cetakan wafel Anda PANAS sebelum menuang adonan wafel agar tidak lengket.","Jangan membuka tutup terlalu cepat atau wafel Anda akan pecah, dan angkat tutupnya perlahan dan hati-hati untuk memeriksa apakah menempel.","Adonan wafel berikutnya matang sedikit lebih cepat daripada adonan pertama, jadi perhatikan dengan saksama.","Simpan sisa wafel di lemari es selama 3-4 hari atau bekukan hingga 3 bulan."],
[]))
R.append((9541318,"Stroberi Air Fryer",
"Stroberi air fryer adalah camilan manis yang benar-benar sehat, tanpa tambahan gula.",
"2 porsi","1 porsi",
["300 gram stroberi segar"],
["Cuci stroberi Anda dan keringkan dengan menepuk-nepuknya untuk menghilangkan kelebihan kelembapan. Lalu gunakan alat pemotong tangkai stroberi atau pisau tajam untuk membuang tangkainya.","Iris stroberi serata mungkin, sekitar 1/8 inci tebalnya. Lalu susun di keranjang air fryer Anda dalam satu lapisan, tanpa tumpang tindih.","Masak dengan air fryer atau gunakan fungsi dehidrasi (tergantung model Anda) pada suhu 190℉/88℃ selama 60-90 menit. (Waktu akan bervariasi tergantung ketebalan irisan dan model air fryer yang Anda miliki.)","Mulailah memeriksa stroberi Anda pada menit ke-45, lalu balik. Kemudian lanjutkan memeriksanya setiap 15 menit hingga benar-benar kering saat disentuh.",("Petunjuk Oven","Panaskan oven terlebih dahulu hingga 200℉/93℃ dan alasi loyang dengan kertas roti."),("Petunjuk Oven","Cuci stroberi Anda dan keringkan dengan menepuk-nepuknya untuk menghilangkan kelebihan kelembapan. Lalu gunakan alat pemotong tangkai stroberi atau pisau tajam untuk membuang tangkainya."),("Petunjuk Oven","Iris stroberi serata mungkin, sekitar 1/8 inci tebalnya. Lalu susun di atas loyang Anda dalam satu lapisan, tanpa tumpang tindih."),("Petunjuk Oven","Panggang selama 90 menit, lalu lepaskan irisan dari kertas roti dan balik. Lanjutkan memanggang selama 30-60 menit lagi hingga benar-benar kering. (Ketebalan irisan akan menentukan berapa lama waktu yang dibutuhkan hingga kering sepenuhnya.)")],
["Irisan tebal akan membutuhkan waktu lebih lama untuk kering dibandingkan irisan tipis. Usahakan memotong stroberi dengan ketebalan seragam agar waktu memasaknya merata.","Angkat potongan yang lebih tipis setelah matang dan lanjutkan memasak potongan yang lebih tebal hingga setiap irisan terdehidrasi.","Saya sudah membuatnya dengan dan tanpa mengalasi keranjang air fryer dengan kertas roti. Kedua pilihan berhasil dengan baik, tetapi"],
[]))
build(R,'part1.json')
