from mk import *
R=[]
R.append((9560531,"Buncis Air Fryer Tanpa Minyak [Lima Rasa!]",
"Buncis air fryer yang renyah! Camilan sehat yang paling renyah, mudah dibuat, dan benar-benar bikin ketagihan! Dengan lima pilihan rasa.",
"3 porsi","1 porsi",
[("Untuk Buncis","1 kaleng 15 ons buncis tanpa tambahan garam ditiriskan, tetapi simpan cairannya dan JANGAN dibilas"),("Untuk Buncis","1 sendok makan aquafaba (cairan dari kaleng yang Anda simpan)"),("Pedas Asap","1 sendok teh paprika asap"),("Pedas Asap","¼ sendok teh bubuk bawang putih"),("Pedas Asap","¼ sendok teh garam laut"),("Pedas Asap","¼ sendok teh cabai cayenne opsional"),("Cabai Jeruk Nipis","1 sendok makan air jeruk nipis"),("Cabai Jeruk Nipis","1 sendok teh bubuk cabai"),("Cabai Jeruk Nipis","½ sendok teh paprika"),("Cabai Jeruk Nipis","¼ sendok teh garam laut"),("Manis Kayu Manis (Churros)","1 sendok makan gula kelapa atau gula pasir pilihan Anda"),("Manis Kayu Manis (Churros)","½ sendok teh kayu manis"),("Italia","1 sendok teh bubuk bawang putih"),("Italia","½ sendok teh peterseli kering"),("Italia","¼ sendok teh oregano kering"),("Italia","½ sendok teh garam laut"),("Ranch","½ sendok teh peterseli kering"),("Ranch","½ sendok teh dill kering"),("Ranch","¼ sendok teh bubuk bawang bombai"),("Ranch","¼ sendok teh bubuk bawang putih"),("Ranch","¼ sendok teh garam laut"),("Ranch","⅛ sendok teh merica hitam")],
["Tiriskan buncis Anda di atas mangkuk, agar Anda dapat menyimpan satu sendok makan aquafaba, dan JANGAN dibilas.","Letakkan buncis yang sudah ditiriskan (tetapi tidak dibilas) di keranjang air fryer dalam satu lapisan. Masak dengan air fryer pada suhu 400 derajat F selama 10 menit, aduk di pertengahan waktu.","Sementara itu, campurkan satu sendok makan aquafaba (dan air jeruk nipis untuk pilihan cabai jeruk nipis) dengan SETENGAH dari bumbu untuk rasa pilihan Anda. Lalu buka air fryer (setelah dimasak 10 menit) dan tuang campuran tersebut secara merata ke atas buncis, lalu aduk rata hingga terlapisi. Lanjutkan memasak dengan air fryer selama 5-7 menit lagi, hingga tingkat kerenyahan yang diinginkan tercapai. Pastikan mengaduknya setiap beberapa menit agar tidak gosong.","Segera pindahkan buncis air fryer Anda ke mangkuk dan taburi dengan sisa bumbu selagi masih panas. Aduk rata dan nikmati."],
["Jangan bilas buncis. Membilasnya membuat kulitnya terlepas dan kemudian gosong jika Anda tidak membuangnya semua, yang merepotkan dan sama sekali tidak perlu. Gunakan buncis tanpa tambahan garam karena kita tidak membilasnya, untuk mengendalikan kadar natrium. Tidak perlu mengeringkan buncis. Air fryer Anda akan mengeringkannya, sehingga resep ini jadi lebih mudah dari sebelumnya! Aduk buncis Anda setiap beberapa menit setelah dibumbui, agar tidak gosong. Simpan sisa makanan dalam kantong kertas pada suhu ruang. Jangan simpan di lemari es atau dalam wadah tertutup, atau buncis akan lembap dan kehilangan kerenyahannya. Informasi nutrisi untuk sepertiga porsi adonan, tetapi tidak termasuk bumbu. Diedit pada Juni 2021 untuk menambahkan dua rasa tambahan, Italia + ranch."],
[]))
R.append((9563775,"Resep Nutella Sehat [Vegan+Tanpa Minyak]",
"Nutella sehat yang cokelat, kaya rasa, dan lezat, tetapi dimaniskan secara alami sebagai alternatif bergizi dari produk toko.",
"16 porsi (menghasilkan sekitar 2 cangkir)","2 Sendok makan",
["1.5 cangkir hazelnut mentah tanpa garam","1 cangkir kurma tanpa biji dipadatkan","½ cangkir + 2 sendok makan susu mete tanpa pemanis atau susu almond dibagi","3 sendok makan bubuk kakao mentah tanpa pemanis","1 sendok teh ekstrak vanili murni","¼ sendok teh garam laut"],
["Panaskan oven terlebih dahulu hingga 350 derajat F dan alasi loyang dengan kertas roti. Masukkan hazelnut mentah dalam satu lapisan dan panggang selama 15 menit.","Keluarkan dari oven dan letakkan lap dapur yang bersih dan kering di atas hazelnut, lalu gosokkan tangan Anda pada kacang untuk menghilangkan kulitnya. Gerakan menggosok bolak-balik akan melepaskan sebagian besar kulit. Lakukan sekitar 30 detik, lalu angkat lap dan lanjutkan dengan tangan kosong saat sudah cukup dingin. Jangan khawatir jika ada beberapa kulit membandel yang tidak lepas, selama sebagian besar sudah terlepas.","Masukkan hazelnut yang sudah dikupas ke dalam blender berkecepatan tinggi, seperti Vitamix, atau ke food processor, lalu proses hingga menjadi selai kacang yang halus. Berhenti dan kerok sisi mangkuk sesuai kebutuhan.","Sekarang angkat selai kacang dan sisihkan dalam mangkuk. Pada food processor yang sama, masukkan kurma dan mulai proses. Lalu tuang 1/4 cangkir susu nabati saat mesin berjalan dan proses hingga halus. Kerok sisi mangkuk sesuai kebutuhan.","Kembalikan selai hazelnut ke dalam processor, bersama sisa susu nabati, bubuk kakao, vanili, dan garam. Pulse beberapa kali hingga tercampur. Anda dapat menambahkan 2-3 sendok makan susu lagi jika menginginkan kekentalan yang lebih encer.","Simpan Nutella sehat Anda dalam toples kaca yang bersih pada suhu ruang hingga 1 minggu."],
["Setelah memanggang hazelnut, bekerjalah dengan cepat untuk mengupas kulitnya karena paling mudah lepas saat masih hangat. Sebagian besar kulit akan lepas dengan mudah, tetapi jangan khawatir jika ada beberapa yang membandel.","Hazelnut akan memerlukan waktu untuk berubah dari kacang utuh menjadi selai kacang. Anda akan melihat kacang melewati tahap potongan yang lebih kasar, menjadi tepung, menjadi gumpalan, dan akhirnya selai kacang yang halus. Bersabarlah. 🙂","Jika Anda menggunakan food processor, pastikan memberinya jeda singkat agar tidak terlalu panas. Waktu pemrosesan bagi saya sekitar 1 menit, tetapi setiap alat berbeda.","Menambahkan susu saat food processor berjalan akan menghasilkan tekstur yang lebih halus. Tetapi, jika menggunakan blender, masukkan keduanya sekaligus lalu proses. Jika blender atau processor Anda tidak bertenaga, rendam kurma Anda terlebih dahulu selama 15-30 menit lalu tiriskan agar pasta kurma lebih halus.","Meskipun food processor dan blender sama-sama berfungsi dengan baik, blender berkecepatan tinggi seperti Vitamix akan menghasilkan tekstur yang lebih halus. Tetapi sebagai gantinya, lebih mudah memindahkan Nutella dari mangkuk food processor.","Saya menyukai tingkat kemanisan Nutella ini apa adanya. Namun, jika Anda menginginkan Nutella yang lebih manis, Anda dapat menambahkan pemanis cair secukupnya, seperti sirup maple, sirup kurma, atau agave di akhir lalu pulse beberapa kali hingga tercampur.","Resep ini menghasilkan sekitar 2 cangkir Nutella sehat. Simpan dalam toples kaca yang bersih pada suhu ruang hingga 1 minggu. Simpan di lemari es hingga 3 minggu. Ukuran sajinya adalah dua sendok makan."],
[]))
R.append((9564162,"Pasta e Piselli",
"Hidangan makan malam hari kerja yang cepat dan mudah, sangat lezat dan penuh rasa, dengan HANYA 7 bahan.",
"4 porsi","1 porsi",
["3 ¼ cangkir kaldu sayuran dibagi","1 bawang bombai kuning besar dicincang halus","2-3 siung bawang putih dikupas + dicincang halus","½ sendok teh serpihan cabai merah","3 cangkir kacang polong beku","½ pon pasta ditali atau pasta pendek lainnya","⅓ cangkir keju parmesan vegan"],
["Panaskan wajan tumis yang dalam dengan api sedang di atas kompor. Lalu masukkan 1/4 cangkir kaldu, bawang bombai cincang, bawang putih, dan serpihan cabai merah. Tumis hingga lunak, sekitar 5 menit, sambil sering diaduk.","Lalu masukkan sisa 3 cangkir kaldu, kacang polong, pasta, dan keju vegan ke dalam wajan yang sama. Tutup dengan penutup, pertahankan api kecil agar mendidih perlahan, dan sering diaduk, hingga pasta matang al dente. Buka tutup pada beberapa menit terakhir memasak agar sebagian besar cairan terserap. (Kecuali Anda lebih suka yang berkuah, dalam hal ini biarkan tutup terpasang selama seluruh proses memasak.)","Sajikan dihiasi dengan basil segar, merica hitam, dan/atau lebih banyak keju parmesan vegan jika diinginkan."],
["Masak pasta Anda al dente. Jangan sampai terlalu matang! Al dente berarti pasta masih terasa kenyal setelah dimasak, sehingga memberikan tekstur optimal di setiap gigitan. Agar tidak terlalu matang, mulailah mencicipi beberapa menit sebelum waktu yang tertera di kemasan. Pasta harus empuk, tetapi masih kenyal.","Cicipi pasta setelah matang dan tambahkan garam dan merica hitam, jika perlu. Ini akan bervariasi tergantung keasinan kaldu yang Anda gunakan.","Sisa makanan dapat disimpan di lemari es selama 3-4 hari. Panaskan kembali di atas kompor dengan sedikit air atau kaldu agar mencair, sesuai kebutuhan."],
[]))
R.append((9566547,"Bola Bliss Karamel Asin",
"Bola bliss karamel asin yang lezat adalah camilan seukuran sekali gigit yang menyenangkan, mengenyangkan, dan sehat.",
"18 bola","1 porsi",
["1 cangkir kurma medjool dipadatkan","1 cangkir kacang macadamia mentah atau sangrai kering","1 sendok teh ekstrak vanili murni","¼ sendok teh garam laut kurangi jika menggunakan kacang macadamia asin","kelapa kering parut opsional, untuk menggulung"],
["Masukkan semua 4 bahan ke dalam food processor Anda dan proses hingga tercampur dan konsistensinya merata, tanpa memproses terlalu lama. (Sedikit tekstur itu enak.)","Sendokkan adonan dan gulung menjadi bola seukuran sekali gigit, letakkan masing-masing di atas piring datar atau loyang. Anda akan mendapatkan sekitar 18 bola tergantung ukurannya.","Opsional: Gulingkan sebagian atau semua bola dalam kelapa kering parut."],
["Jika kurma Anda sangat kering, rendam dalam air panas selama 10-15 menit, lalu tiriskan sebelum dimasukkan ke dalam food processor. Ini akan membantu melunakkannya dan mempermudah proses penghalusan.","Gunakan kacang macadamia mentah ATAU sangrai kering, dengan atau tanpa garam. Namun, jika kacangnya asin, kurangi separuh garam yang ditambahkan.","Jangan memproses campuran terlalu lama. Camilan ini paling enak dengan sedikit tekstur; proses hingga tercampur tanpa berlebihan.","Camilan energi ini dapat disimpan pada suhu ruang selama 2-3 hari, di lemari es hingga 1 minggu, atau di freezer hingga 3 bulan."],
[]))
R.append((9570781,"Perahu Zukini Vegan ala Meksiko [Resep Rendah Kalori]",
"Perahu zukini vegan ala Meksiko yang sehat ini penuh rasa, namun rendah kalori.",
"4 porsi","2 perahu zukini",
["4 zukini besar","1 bawang merah dipotong dadu","1 paprika merah dipotong dadu","¼ cangkir salsa sedang berpotongan besar atau tingkat kepedasan sesuai selera","½ sendok teh garam laut","½ sendok teh bubuk bawang putih","½ sendok teh bubuk bawang bombai","½ sendok teh jintan","½ sendok teh bubuk cabai","¼ sendok teh cabai cayenne atau lebih, opsional","1 cangkir nasi merah matang","1 cangkir kacang hitam matang atau kalengan","½ cangkir jagung",("Topping Opsional","guacamole"),("Topping Opsional","saus keju kenari"),("Topping Opsional","saus keju bebas kacang"),("Topping Opsional","tomat dipotong dadu"),("Topping Opsional","jalapeno iris"),("Topping Opsional","ketumbar segar")],
["Jika Anda tidak punya nasi merah matang, mulailah dengan memasak nasi Anda sesuai petunjuk kemasan. Nasi akan mengembang sekitar tiga kali lipat, jadi gunakan 1/3 cangkir nasi merah mentah untuk mendapatkan sekitar 1 cangkir yang dibutuhkan dalam resep ini.","Dalam wajan besar, masukkan 2-3 sendok makan air atau kaldu bersama bawang bombai dan paprika cincang, lalu tumis hingga lunak dan menyusut, sekitar 5 menit. Matikan api dan masukkan nasi matang, kacang, jagung, salsa, dan semua bumbu, lalu aduk rata. Cicipi dan tambahkan lebih banyak bumbu jika diinginkan, lalu sisihkan.","Alasi loyang 9\"x13\" (atau ukuran serupa) dengan kertas roti dan panaskan oven Anda terlebih dahulu hingga 425 derajat F (218 derajat C).","Belah zukini Anda menjadi dua secara memanjang serata mungkin. Lalu kerok daging buahnya dengan hati-hati menggunakan sendok teh logam. Letakkan perahu zukini yang sudah dikosongkan dengan sisi berongga menghadap ke atas di loyang Anda.","Bagi isian ke 8 perahu zukini Anda. Lalu tutup loyang dengan kertas roti dan kemudian foil, dan panggang selama 25-30 menit, hingga zukini mudah ditusuk dengan garpu.","Sajikan dengan guacamole dan topping lain yang diinginkan."],
["Berhati-hatilah, dan kerok dengan lembut, agar zukini Anda tidak patah. Pegang setengah zukini dengan kuat di satu tangan, dan kerok dari atas ke bawah dengan sendok teh logam. Anda dapat mengganti nasi merah dengan quinoa matang atau barley matang jika diinginkan. Sisa makanan dapat disimpan di lemari es selama 3-4 hari. Panaskan kembali di oven atau oven toaster. Informasi nutrisi untuk 2 perahu zukini berisi (2 belahan zukini) tidak termasuk topping opsional."],
[]))
R.append((9571235,"Orak-arik Tahu Sutra",
"Orak-arik tahu sutra yang gurih, mirip telur, dan sangat lezat! Siap dalam 15 menit atau kurang.",
"2 porsi","1 porsi",
["12 ons (300 gram) tahu sutra atau tahu lembut","2 sendok makan ragi nutrisi","½ sendok teh bubuk bawang putih","¼ sendok teh paprika","⅛ sendok teh kunyit opsional, untuk warna","¼ sendok teh garam laut","⅛ sendok teh garam hitam juga dikenal sebagai Kala Namak"],
["Gunakan wajan besi cor yang sudah berpengalaman (well-seasoned) atau wajan antilengket. Olesi minyak terlebih dahulu, jika perlu. Panaskan wajan Anda di atas kompor dengan api sedang dan setelah panas, letakkan balok tahu di dalamnya.","Gunakan garpu atau spatula untuk memecahnya menjadi potongan yang sangat besar dan biarkan matang tanpa diganggu selama 4-5 menit hingga keemasan. Lalu balik dan masak sisi lainnya selama 2-3 menit lagi, hingga sebagian besar air dari tahu menguap. (Berhati-hatilah saat membalik tahu lembut atau tahu sutra karena dapat hancur saat diaduk. Itulah sebabnya kita memulai dengan potongan besar terlebih dahulu.)","Tambahkan semua bumbu, kecuali garam hitam, lalu aduk hingga terlapisi merata. Pada tahap ini, Anda dapat memecah potongan tahu sedikit lagi, jika perlu.","Matikan api, taburi dengan garam hitam dan sajikan."],
["Untuk versi tanpa minyak, gunakan wajan antilengket yang lebih baru atau wajan besi cor yang sudah well-seasoned. Jika wajan besi Anda belum well-seasoned, orak-arik tahu mungkin menempel. Mulailah dengan potongan besar (sekitar 1.5-2 inci) tahu sutra Anda. Tahu akan menyusut cukup banyak saat airnya keluar selama dimasak. Jangan terlalu sering membalik tahu atau tahu bisa hancur lebih dari yang Anda inginkan dan menjadi sedikit lembek. Di akhir memasak, Anda dapat memecah tahu lebih banyak JIKA DIPERLUKAN."],
[]))
R.append((9572606,"Casserole Quinoa Vegan Berkeju dengan Lentil",
"Casserole quinoa vegan berkeju yang sangat lezat dan penuh dengan sayuran dan rasa!",
"6 porsi","1 porsi",
["1 cangkir lentil merah belah","½ cangkir quinoa","4 cangkir kaldu sayuran rendah natrium","1 ¼ cangkir daun bawang prei dicincang halus","1 cangkir zukini dipotong dadu","1 kemasan 8 ons (227g) jamur kancing dicincang","1 sendok teh bubuk bawang putih","½ sendok teh thyme kering","½ sendok teh garam laut atau secukupnya",("Untuk Saus Keju","1 cangkir ubi jalar dipotong dadu"),("Untuk Saus Keju","⅔ cangkir oat gulung bebas gluten jika diinginkan"),("Untuk Saus Keju","¼ cangkir ragi nutrisi"),("Untuk Saus Keju","3 sendok makan pati tapioka atau tepung tapioka"),("Untuk Saus Keju","1 cangkir air"),("Untuk Saus Keju","1 sendok teh cuka apel"),("Untuk Saus Keju","2 sendok teh bubuk bawang bombai"),("Untuk Saus Keju","1 sendok teh paprika asap"),("Untuk Saus Keju","1 sendok teh garam laut"),("Untuk Saus Keju","Hiasan Opsional: thyme")],
["Panaskan oven Anda terlebih dahulu hingga 450°F/232°C.","Dalam panci saus berukuran sedang, masukkan lentil, quinoa, dan kaldu sayuran lalu didihkan. Kecilkan api, dan biarkan mendidih perlahan tanpa ditutup selama 20 menit sambil sesekali diaduk, hingga sebagian besar cairan terserap. (Menjelang akhir memasak, aduk lebih sering.) Sisihkan.","Sementara itu, masukkan ubi jalar yang sudah dipotong dadu ke dalam panci kecil, tutup dengan air, didihkan, dan masak hingga empuk saat ditusuk garpu, sekitar 8 menit. Tiriskan dan sisihkan.","Dalam wajan besar, masukkan daun bawang prei, zukini, jamur, bubuk bawang putih, thyme, dan garam, lalu tumis dengan api sedang-besar hingga lunak, sekitar 5 menit. Aduk sering agar tidak lengket. Anda seharusnya tidak memerlukan air atau minyak karena jamur akan mengeluarkan cairan saat dimasak.","Masukkan quinoa dan lentil matang, ditambah sayuran tumis, ke dalam loyang 9\"x13\" (atau ukuran serupa) dan aduk rata.","Untuk membuat saus keju, masukkan ubi jalar matang Anda, dan semua bahan saus keju lainnya ke dalam blender dan proses hingga halus. Tuang saus secara merata ke atas campuran lentil, quinoa, dan sayuran, lalu taburi dengan lebih banyak thyme, jika Anda mau.","Tutup loyang dengan kertas roti lalu aluminium foil dan panggang selama 15 menit. Lalu lepas foil/kertas dan panggang 5 menit lagi agar bagian atasnya sedikit kecokelatan. Sajikan panas."],
["Masak quinoa dan lentil dalam kaldu yang lezat (bukan air) untuk menambah kedalaman rasa. Siapkan dan susun casserole terlebih dahulu jika memungkinkan. Dengan begitu Anda dapat menyajikan makan malam dalam 20 menit pada malam hari kerja yang sibuk. Casserole quinoa vegan ini paling enak saat baru dipanggang dan saus kejunya panas dan meleleh. Saat mendingin hingga suhu ruang, lapisan keju akan mulai mengeras. Untuk mengembalikannya ke keadaan meleleh, cukup masukkan kembali ke oven dan panaskan ulang. Sisa makanan dapat disimpan hingga 4 hari di lemari es. Cukup panaskan kembali dan nikmati."],
[]))
R.append((9572814,"Cara Membuat Selai Kacang Pecan",
"Ikuti panduan mudah ini untuk mempelajari cara membuat selai kacang pecan hanya dengan SATU bahan.",
"20 porsi masing-masing 1 sendok makan","1 porsi",
["3 cangkir belahan pecan",("Tambahan Opsional","1 sendok makan gula kelapa tidak dimurnikan atau gula merah"),("Tambahan Opsional","½-1 sendok teh kayu manis"),("Tambahan Opsional","¼ sendok teh garam laut")],
["Panaskan oven terlebih dahulu hingga 350 derajat dan alasi loyang besar dengan kertas roti. Susun pecan dalam satu lapisan dan panggang selama 5 menit. Lalu keluarkan dari oven.","Pindahkan pecan yang sudah dipanggang ke food processor Anda dan mulai proses. Berhenti untuk mengerok sisi mangkuk, sesuai kebutuhan, dan beri mesin Anda jeda 30-60 detik agar tidak terlalu panas. Pecan akan berubah dari utuh, menjadi remah, menjadi tepung, menjadi gumpalan, dan akhirnya selai pecan yang creamy. Tergantung alat Anda, ini akan memakan waktu 2-6 menit.","Setelah halus, tambahkan salah satu atau semua tambahan opsional (jika digunakan) dan pulse hingga tercampur.","Simpan dalam toples kaca atau wadah yang bersih dan kering, lalu gunakan sesuai keinginan."],
["Beri mesin Anda jeda singkat di antara proses agar tidak terlalu panas. Matikan food processor Anda selama 30-60 detik sekali waktu, sesuai kebutuhan, lalu lanjutkan. Manfaatkan jeda itu untuk mengerok sisi mangkuk. Untuk versi tanpa gula, lewati gula kelapa opsional, atau jika Anda suka manis, Anda dapat menambahnya menjadi dua sendok makan. (Coba dengan satu terlebih dahulu) Selai kacang buatan sendiri Anda akan melewati banyak tahap. Dari pecan utuh, menjadi potongan kecil, menjadi tepung, menjadi gumpalan kecil, lalu gumpalan lebih besar, dan akhirnya selai kacang yang creamy. (Lihat foto proses di atas untuk gambaran visual.) Anda dapat menggunakan blender berkecepatan tinggi, seperti Vitamix, untuk hasil yang lebih cepat, tetapi saya merasa lebih mudah mengeluarkan selai dari food processor. Simpan pada suhu ruang hingga 1 minggu, atau simpan di lemari es hingga 4 minggu. Anda juga dapat membekukannya dalam wadah kedap udara yang aman untuk freezer hingga 3 bulan."],
[]))
build(R,'part3.json')
