from mk import *
R=[]
R.append((9635144,"Keripik Tortilla Vegan",
"Keripik tortilla vegan buatan sendiri siap dalam waktu singkat dan tidak memerlukan minyak. Camilan renyah yang sempurna saat Anda ingin keripik, tanpa rasa bersalah.",
"4 porsi","1 porsi",
["8 tortilla jagung enam inci","2 sendok makan air jeruk nipis sekitar 1 jeruk nipis besar","½ sendok teh garam laut","¼ sendok teh bubuk bawang putih opsional"],
["Panaskan oven Anda terlebih dahulu hingga 400 derajat F (205 derajat C) dan alasi dua loyang besar dengan kertas roti.","Tumpuk tortilla jagung secara rata di atas talenan. Lalu gunakan pemotong pizza untuk mengirisnya menjadi empat bagian. (Jika menggunakan tortilla yang lebih besar, iris menjadi enam potong.)","Susun keripik tortilla yang sudah dipotong dalam satu lapisan merata di atas loyang Anda. Lalu olesi masing-masing dengan air jeruk nipis dan taburi secara merata dengan garam dan bubuk bawang putih, jika digunakan.","Panggang selama 8-10 menit, periksa sesering mungkin menjelang akhir pemanggangan. Anda ingin keripik berwarna cokelat keemasan dan renyah, tetapi tidak terlalu matang."],
["Saya menggunakan tortilla jagung enam inci dan mengiris masing-masing menjadi empat bagian untuk membuat keripik ukuran pas ala restoran. Jika Anda menggunakan tortilla yang lebih besar, Anda dapat mengirisnya menjadi enam potong. Periksa keripik tortilla Anda sesering mungkin menjelang akhir pemanggangan. Keripik akan berubah dari matang sempurna menjadi terlalu matang dengan cepat, jadi gunakan timer oven Anda untuk mengatur pengingat."],
[]))
R.append((9635628,"Donat Vegan Panggang dengan Glasir",
"Donat vegan berglasir yang manis, lembap, dan sangat lezat yang dipanggang (bukan digoreng!) untuk hidangan terbaik.",
"12 donat","1 porsi",
[("Bahan Kering","240 gram tepung pastry gandum utuh sekitar 2 cangkir"),("Bahan Kering","2 sendok teh baking powder"),("Bahan Kering","1 sendok teh kayu manis"),("Bahan Basah","½ cangkir saus apel tanpa pemanis"),("Bahan Basah","½ cangkir sirup maple"),("Bahan Basah","½ cangkir susu kedelai atau susu non-susu lainnya"),("Bahan Basah","2 sendok teh ekstrak vanili murni"),("Untuk Glasir","¾ cangkir gula bubuk"),("Untuk Glasir","2 sendok teh air lemon"),("Untuk Glasir","1-2 sendok makan susu kedelai atau susu bebas susu hewani lainnya")],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan siapkan cetakan donat yang cukup untuk membuat 12 donat. (Saya menggunakan 2 cetakan masing-masing berisi 6 donat.)","Kocok tepung, baking powder, dan kayu manis dalam mangkuk pencampur berukuran sedang. Lalu tambahkan bahan basah dan aduk hingga tercampur.","Bagi adonan donat ke 12 cetakan donat dan panggang selama 12-15 menit. Donat sudah matang saat terasa padat saat disentuh, tetapi sedikit melenting saat ditekan perlahan. Keluarkan dari oven dan biarkan dingin sebelum diberi glasir.","Selagi donat mendingin, siapkan glasir. Campurkan gula, air lemon, dan susu (mulai dengan 1 sendok makan) dalam mangkuk kecil. Tambahkan sedikit susu lagi jika perlu.","Setelah dingin, celupkan bagian atas setiap donat ke dalam glasir, dan letakkan dengan sisi glasir menghadap ke atas di rak kawat agar glasir mengeras. Selamat menikmati!"],
["Timbang tepung Anda menggunakan timbangan dapur untuk hasil yang paling akurat. Menyendok tepung dari kantong dapat menyebabkan terlalu banyak tepung yang digunakan dan dapat mengubah tekstur.","Gunakan baking powder yang segar dan aktif. Setelah dibuka, baking powder mulai kehilangan keefektifannya, jadi sebaiknya gunakan baking powder Anda dalam waktu 6 bulan.","Biarkan donat Anda dingin selama 10-15 menit sebelum mencoba mengeluarkannya dari cetakan. Jika donat terlalu panas, Anda berisiko merusaknya.","Setelah dipindahkan ke rak kawat, biarkan terus dingin hingga suhu ruang sebelum diberi glasir.","Informasi nutrisi di atas mencakup 1 donat, dengan glasir."],
[]))
R.append((9644787,"Roti Cranberry Jeruk Vegan dengan Glasir Jeruk Manis",
"Roti cranberry jeruk vegan yang sehat, lembap, dimaniskan secara alami, dan dibuat dengan bahan-bahan bergizi",
"12 iris (1 - loyang roti 5\"x9\")","1 porsi",
[("Bahan Kering","2 cangkir tepung oat bebas gluten jika diinginkan"),("Bahan Kering","2.5 sendok teh baking powder"),("Bahan Kering","½ sendok teh soda kue"),("Bahan Kering","1 sendok teh kayu manis"),("Bahan Basah","1 cangkir kurma tanpa biji"),("Bahan Basah","1.5 cangkir air"),("Bahan Basah","½ cangkir (ditambah 2 sendok makan untuk glasir, disisihkan) air jeruk yang baru diperas dari sekitar 1 jeruk besar"),("Bahan Basah","1 sendok makan parutan kulit jeruk"),("Bahan Basah","⅓ cangkir saus apel tanpa pemanis"),("Bahan Basah","1 cangkir cranberry segar atau blueberry segar jika cranberry segar tidak tersedia di tempat Anda tinggal")],
["Panaskan oven terlebih dahulu hingga 350 derajat F dan alasi loyang roti 9\" x 5\" (atau ukuran serupa) dengan kertas roti.","Dalam mangkuk pencampur besar, campurkan semua bahan kering Anda dan kocok bersama. Sisihkan.","Masukkan kurma tanpa biji dan air ke dalam blender dan proses hingga benar-benar halus. Ini akan menghasilkan sekitar 2 cangkir sirup kurma. Ukur 1.5 cangkir yang akan digunakan dalam roti Anda dan sisa 1/2 cangkir akan digunakan nanti untuk membuat glasir. Jangan gunakan lebih dari 1.5 cangkir dalam roti.","Sekarang masukkan bahan basah Anda (kecuali cranberry), ke dalam mangkuk bahan kering: 1.5 cangkir sirup kurma yang Anda buat, 1/2 cangkir air jeruk, parutan kulit jeruk, dan saus apel. Aduk hingga tercampur lalu lipat cranberry.","Tuang adonan ke dalam loyang roti yang sudah disiapkan dan ketuk perlahan loyang roti 2-3 kali pada permukaan keras untuk memastikan tidak ada celah pada roti. Jangan menekan dengan spatula.","Panggang di oven yang sudah dipanaskan selama 45-55 menit, hingga tusuk gigi yang ditusukkan di tengah keluar kering. Tergantung oven dan ukuran loyang roti Anda, waktu memasak akan bervariasi. Setelah matang, keluarkan dari oven dan biarkan dingin selama 10 menit sebelum mengeluarkan roti dari loyang. Pindahkan ke rak pendingin hingga benar-benar dingin sebelum diberi glasir.","Untuk membuat glasir Anda: Tambahkan 2 sendok makan air jeruk yang baru diperas ke dalam sisa 1/2 cangkir sirup kurma Anda dan aduk rata. Lalu siramkan glasir di atas roti Anda yang sudah dingin. Iris dan nikmati!"],
["Jika Anda tidak punya blender yang bertenaga, rendam kurma Anda dalam air hangat selama sekitar 15 menit terlebih dahulu. Lalu tiriskan dan buat sirup kurma sesuai petunjuk. Ini akan membantu melunakkan kurma, sehingga lebih mudah diblender. Gunakan baking powder yang segar dan aktif. Baking powder yang sudah terbuka di lemari dapur selama 6+ bulan dapat mulai kehilangan keefektifannya. Pastikan roti cranberry jeruk Anda benar-benar dingin sebelum diberi glasir. Jika Anda tidak memiliki cranberry segar di tempat Anda tinggal, blueberry segar juga sangat cocok dalam roti manis ini. Roti dapat disimpan tertutup, pada suhu ruang selama 2-3 hari, atau dibekukan dalam wadah kedap udara selama 3-4 minggu."],
[]))
R.append((9652525,"Mac and Cheese Alpukat Vegan",
"Hidangan kaya dan creamy yang disukai anak-anak maupun orang dewasa! Mac alpukat ini mudah dibuat, diam-diam sehat, dan sangat lezat!",
"6 porsi","1 porsi",
["¼ cangkir mete mentah","1 alpukat besar matang dikupas & biji dibuang","1.5 cangkir susu mete tanpa pemanis atau susu nabati pilihan Anda","3 sendok makan air lemon sekitar 1 lemon kecil atau setengah lemon besar","¼ cangkir ragi nutrisi","1.5 sendok teh garam laut","1 sendok teh bubuk bawang putih","1 sendok teh paprika asap","1 sendok makan mentega vegan atau minyak alpukat opsional","450 gram pasta makaroni bebas gluten jika diinginkan",("Hiasan Opsional","keju Parmesan vegan sangat disarankan"),("Hiasan Opsional","irisan alpukat"),("Hiasan Opsional","peterseli, kucai atau dill segar")],
["Didihkan panci besar berisi air bergaram, dan masak pasta sesuai petunjuk kemasan hingga al dente. Tiriskan dan kembalikan ke dalam panci.","Sementara itu, masukkan semua bahan Anda (kecuali pasta) ke dalam blender berkecepatan tinggi dan proses hingga halus. Tuang saus di atas pasta Anda dan aduk rata.","Sajikan dengan hiasan pilihan Anda dan nikmati."],
["Jika Anda tidak punya blender berkecepatan tinggi, pastikan merendam mete Anda terlebih dahulu. Rendam dalam air mendidih selama 30 menit, lalu tiriskan dan gunakan sesuai petunjuk. Beri garam pada air perebus pasta Anda untuk hasil terbaik. Jangan memasak pasta Anda terlalu lama. Masak sesuai petunjuk kemasan untuk al dente. Pasta paling enak dengan sedikit gigitan, dan tidak terlalu lunak. Sisa makanan dapat disimpan di lemari es selama 2-3 hari. Untuk memanaskan kembali, tambahkan sedikit susu nabati, air atau kaldu ke dalam wajan bersama pasta, untuk melembapkan kembali dan memanaskannya hingga matang."],
[]))
R.append((9655561,"Pai Blueberry Vegan [Lebih Sehat dari Kebanyakan!]",
"Pai blueberry vegan ini segar dan manis dengan sedikit rasa asam. Versi yang lebih sehat dari pai tradisional Anda, dengan lebih sedikit gula, tanpa minyak atau mentega, dan dengan kulit gandum utuh!",
"8 iris","1 porsi",
["2 kulit pai vegan tanpa minyak atau kulit pai pilihan Anda","5.5 cangkir blueberry","⅓ cangkir gula kelapa tidak dimurnikan atau gula pasir pilihan Anda","¼ cangkir pati jagung atau tepung tapioka","2 sendok makan air lemon sekitar 1 lemon sedang","1 sendok teh kayu manis opsional, tetapi disarankan","1-2 sendok makan susu mete tanpa pemanis atau susu nabati pilihan Anda","1-2 sendok makan gula putih opsional untuk ditaburkan"],
["Siapkan kulit pai pilihan Anda dan panggang kosong (blind bake) sesuai petunjuknya. Jika Anda menggunakan kulit pai tanpa minyak saya, panggang 1 kulit selama 15 menit, hingga tepinya keemasan. Lalu keluarkan dari oven dan sisihkan. Untuk kulit pai kedua, giling dan sisihkan untuk diletakkan di atas pai Anda, setelah diisi.","Panaskan oven terlebih dahulu hingga 350 derajat F.","Dalam mangkuk pencampur, campurkan blueberry, gula, pati jagung, air lemon, dan kayu manis. Aduk rata. Lalu tuang campuran ke dalam kulit pai yang sudah disiapkan.","Sekarang gunakan kulit pai kedua untuk menutupi isian. Anda dapat meletakkan seluruh kulit di atasnya dan melipat tepinya, membuat lubang ventilasi di tengah kulit Anda. Sebagai alternatif, Anda dapat membuat pola anyaman keranjang atau potongan berbentuk bintang (atau bentuk apa pun) untuk menutupi pai. Pilihan Anda.","Olesi sedikit susu nabati pilihan Anda pada kulit atas Anda dan Anda dapat menaburinya dengan gula secara opsional.","Panggang pai Anda selama 45-55 menit, hingga cairan dari blueberry menggelegak dan kulitnya keemasan. Jika pai Anda matang terlalu cepat, tutup bagian atas dengan pelindung pai atau gunakan aluminium foil agar tidak terlalu gelap.","Keluarkan dari oven dan biarkan dingin sepenuhnya sebelum diiris dan disajikan. Pai harus dingin agar mengeras sepenuhnya."],
["Jika kulit pai Anda matang terlalu cepat, tutup dengan pelindung pai atau aluminium foil agar kulit tidak terlalu matang. Pastikan membuat lubang ventilasi jika menggunakan kulit pai utuh untuk bagian atas! Jika membuat pola anyaman keranjang atau menggunakan potongan bintang, ventilasi tidak diperlukan. Biarkan pai blueberry Anda dingin sepenuhnya sebelum diiris! Waktu pendinginan sangat penting agar pai Anda mengeras dengan baik. Meskipun Anda BISA memotongnya saat hangat, pai akan encer hingga dingin. Sisa pai dapat disimpan di lemari es selama 3-4 hari, atau ditutup rapat kedap udara dan dibekukan hingga 2 bulan. Informasi nutrisi mencakup 2 kulit pai tanpa minyak penuh. Jika menggunakan kulit lain, melewatkan kulit atas, atau menggunakan potongan bintang, informasi nutrisi akan bervariasi."],
[]))
R.append((9659242,"Pai Pecan Vegan yang Lebih Sehat [Tanpa Sirup Jagung]",
"Pai pecan vegan yang lebih sehat, sangat lezat, kaya, manis, berasa karamel, penuh pecan, dan hidangan penutup liburan yang sempurna.",
"8 iris","1 porsi",
[("Untuk Kulit Pai (Atau kulit pai vegan","90 gram (sekitar ¾ cangkir) tepung almond"),("Untuk Kulit Pai (Atau kulit pai vegan","80 gram (sekitar ¾ cangkir) tepung gandum utuh putih juga dikenal sebagai gandum utuh lembut atau tepung pastry gandum utuh"),("Untuk Kulit Pai (Atau kulit pai vegan","1 alpukat matang sedang"),("Untuk Kulit Pai (Atau kulit pai vegan","¼ sendok teh garam laut"),("Untuk Kulit Pai (Atau kulit pai vegan","4 sendok makan susu almond atau susu non-susu pilihan Anda"),("Untuk Kulit Pai (Atau kulit pai vegan","1-2 sendok makan air HANYA jika diperlukan!"),("Untuk Kulit Pai (Atau kulit pai vegan","2 sendok makan gula kelapa atau gula pasir pilihan Anda opsional"),("Untuk Kulit Pai (Atau kulit pai vegan","1 sendok teh kayu manis opsional"),("Untuk Isian","1 ¼ cangkir belahan pecan"),("Untuk Isian","⅔ cangkir sirup maple"),("Untuk Isian","3 sendok makan molase fancy"),("Untuk Isian","¼ cangkir biji rami (flaxseed) bubuk"),("Untuk Isian","⅓ cangkir susu mete tanpa pemanis atau susu pilihan Anda"),("Untuk Isian","3 sendok makan pati tapioka"),("Untuk Isian","2 sendok makan selai mete atau selai almond"),("Untuk Isian","½ sendok teh garam laut"),("Tambahan Opsional Untuk Isian","2.5 sendok teh butiran kopi instan"),("Tambahan Opsional Untuk Isian","1 sendok teh ekstrak vanili murni"),("Tambahan Opsional Untuk Isian","1 sendok teh kayu manis")],
["Siapkan kulit pai pilihan Anda dan sisihkan. Saya menggunakan kulit pai tanpa minyak saya (lihat postingan untuk petunjuk terperinci dan foto langkah demi langkah cara membuat kulitnya) dengan pilihan tepung almond, yang sangat saya sarankan. Jika menggunakan kulit ini, tidak perlu memanggang kulit terlebih dahulu (blind bake).","Panaskan oven terlebih dahulu hingga 325 derajat F.","Masukkan semua bahan isian, kecuali pecan, ke dalam mangkuk pencampur dan kocok hingga tercampur rata. Lalu tambahkan belahan pecan dan aduk sebentar agar pecan terlapisi.","Tuang campuran ke dalam kulit pai yang sudah disiapkan dan panggang selama 15 menit. Lalu letakkan pelindung pai di atas pai Anda atau tutup longgar dengan aluminium foil dan panggang 25 menit lagi. (Total waktu panggang 40 menit.) Ini akan mencegah kulit Anda matang terlalu cepat dan terlalu gelap.","Keluarkan dari oven dan dinginkan di rak pendingin minimal dua jam sebelum diiris."],
["Biarkan pai pecan Anda dingin pada suhu ruang minimal dua jam setelah dipanggang. Waktu pendinginan ini penting agar pai Anda mengeras, dan mempermudah pemotongan. Pastikan pai sudah benar-benar dingin hingga suhu ruang sebelum disimpan di lemari es atau dibekukan. Anda dapat membuat pai Anda terlebih dahulu, tetapi paling enak pada hari ke-1 hingga ke-2. Sisa pai dapat disimpan di lemari es selama 3-5 hari, atau dibekukan hingga 2 bulan."],
[]))
R.append((9660382,"Muffin Frittata Vegan [Muffin Gurih Vegan]",
"Muffin frittata vegan ini alias muffin gurih vegan adalah alternatif terbaik untuk egg cup tradisional yang akan memuaskan lidah Anda dan mengawali hari Anda.",
"12 muffin","1 porsi",
["¼ cangkir bawang bombai kuning dicincang halus","½ cangkir paprika merah dipotong dadu sekitar 1 paprika kecil","1 cangkir jamur cremini atau baby bella dipotong dadu sekitar 4-5 jamur","¾ cangkir brokoli dicincang halus, sekitar 3-5 kuntum","300 gram tepung buncis atau garbanzo sekitar 2 cangkir","4 sendok makan ragi nutrisi","1 sendok teh bubuk bawang putih","½ sendok teh kunyit untuk warna","1 sendok teh garam laut atau ganti setengahnya dengan garam hitam alias kala namak","¼ sendok teh merica hitam opsional, tetapi disarankan","1 sendok teh baking powder","2.5 cangkir air"],
["Panaskan oven terlebih dahulu hingga 400℉/204℃ dan siapkan cetakan muffin antilengket atau olesi minyak jika perlu.","Masukkan semua sayuran yang sudah dicincang ke dalam wajan dan taburi dengan sedikit garam dan merica, jika diinginkan. Tumis kering, sering diaduk, hingga menyusut dan lunak, sekitar 5 menit. Sisihkan.","Sementara itu, dalam mangkuk besar, masukkan tepung buncis, ragi nutrisi, bumbu, dan baking powder, lalu kocok hingga tercampur. Lalu tuang air dan aduk rata.","Bagi sayuran tumis ke 12 cetakan muffin Anda, sekitar 1 sendok makan penuh per muffin. Lalu tuang adonan buncis di atasnya agar terbagi merata ke 12 muffin Anda. Gunakan sendok untuk mengaduk setiap muffin dengan lembut, agar sayuran dan adonan tersebar merata. (JANGAN LEWATKAN PENGADUKAN.)","Panggang selama 30 menit atau hingga tusuk gigi yang ditusukkan di tengah keluar bersih. Keluarkan dari oven dan biarkan dingin setidaknya 10 menit. Lalu keluarkan dengan hati-hati dari cetakan."],
["Aduk muffin SEBELUM dipanggang. Ini akan memastikan sayuran tersebar merata. Selain itu, pastikan sebagian adonan sampai ke dasar cetakan agar muffin berbentuk rata dan tidak lengket.","Sebagai alternatif, Anda dapat menuang satu sendok makan adonan buncis ke dasar setiap cetakan muffin, diikuti sayuran, lalu tuang sisa adonan di atasnya.","Biarkan muffin beristirahat pada suhu ruang setidaknya 10 menit sebelum mengeluarkannya dari cetakan. Masa pendinginan ini membantu muffin mengeras sehingga tidak pecah saat dikeluarkan.","Jika Anda menghindari minyak dan tidak ingin mengolesi cetakan muffin Anda, biarkan muffin dingin sedikit lebih lama sebelum mencoba mengeluarkannya. Lalu gunakan pisau mentega untuk menyusuri dengan lembut di sekeliling setiap muffin jika agak menempel, dan sendok keluar.","Sisa makanan dapat disimpan dalam wadah tertutup di lemari es Anda hingga 5 hari. Atau bekukan hingga 3 bulan. Pastikan mendinginkan muffin telur vegan sepenuhnya sebelum disimpan di lemari es atau dibekukan. Anda dapat memanaskan kembali egg cup di microwave atau oven toaster, atau menikmatinya dingin."],
[]))
R.append((9660403,"Ham Vegan [Ham Seitan]",
"Ham vegan yang bertekstur seperti daging, empuk, sangat penuh rasa dengan glasir maple asap!!",
"8 porsi","1 porsi",
[("Untuk Ham","1 cangkir buncis kalengan atau matang (ditiriskan)"),("Untuk Ham","1 cangkir kaldu sayuran gunakan kaldu yang asin/penuh rasa seperti versi buatan sendiri saya"),("Untuk Ham","3-4 siung bawang putih"),("Untuk Ham","3 sendok makan pasta tomat"),("Untuk Ham","2 sendok makan minyak alpukat atau minyak masak pilihan Anda (ganti dengan lebih banyak kaldu agar bebas minyak)"),("Untuk Ham","2 sendok teh liquid smoke"),("Untuk Ham","1.5 sendok makan paprika asap"),("Untuk Ham","1 sendok teh garam laut"),("Untuk Ham","¼ sendok teh kayu manis"),("Untuk Ham","¼ sendok teh cengkeh bubuk"),("Untuk Ham","210 gram vital wheat gluten sekitar 1.75 cangkir"),("Untuk Glasir Maple","½ cangkir kaldu sayuran gunakan kaldu yang asin/penuh rasa seperti versi buatan sendiri saya"),("Untuk Glasir Maple","3 sendok makan sirup maple"),("Untuk Glasir Maple","2 sendok teh paprika asap"),("Untuk Glasir Maple","1 sendok teh mustard kuning")],
["Masukkan semua bahan ham KECUALI vital wheat gluten ke dalam food processor dan proses hingga sebagian besar tercampur. Lalu tambahkan SETENGAH vital wheat gluten dan lanjutkan memproses hingga tercampur rata. Sekarang tambahkan setengah sisanya dan proses hingga sebagian besar tercampur.","Pindahkan campuran ke permukaan yang bersih dan uleni dengan tangan selama 1-2 menit, sambil memutar dan membuat simpul pada campuran Anda. Lalu bentuk menjadi oval, serata yang Anda bisa, tetapi tidak harus sempurna. (Lihat foto proses di atas untuk gambaran visual.)","Bungkus roast Anda dengan rapat menggunakan kain keju (atau kertas roti dan aluminium foil) dan amankan ujung-ujungnya.","Masukkan 1.5 cangkir air ke dasar Instant Pot Anda dan letakkan trivet-nya di dalam. Lalu letakkan ham yang sudah dibungkus di atas trivet. Tutup penutup dan pastikan katup dalam posisi menyegel. Atur pada fungsi kukus selama 40 menit dan biarkan tekanan terlepas secara alami hingga pin turun. Dibutuhkan sekitar 10 menit agar pin turun.","Selagi ham dikukus di Instant Pot Anda, panaskan oven Anda terlebih dahulu hingga 375 derajat F. Lalu masukkan SEMUA bahan glasir ke dalam mangkuk pencampur kecil dan kocok hingga tercampur. Sisihkan.","Pindahkan roast ke talenan dan gunakan pisau tajam untuk menggores ham Anda. Mulailah dari satu ujung dan buat sayatan sedalam sekitar 1/4-1/3 inci dengan jarak sekitar 1 inci. Lalu putar ham dan ulangi secara diagonal dari satu sisi ke sisi lainnya. (Lihat foto proses di atas untuk gambaran visual.)","Letakkan ham yang sudah digores dalam wadah yang aman untuk oven dan tuang glasir maple Anda di atasnya, gunakan kuas silikon untuk memastikan permukaan ham Anda tertutup sepenuhnya oleh glasir.","Panggang tanpa ditutup selama 15-20 menit, olesi setiap beberapa menit. Lalu Anda dapat secara opsional memanggang ham dengan mode broil selama 2-3 menit agar bagian atasnya sedikit kecokelatan, tetapi Anda dapat melewatkan langkah ini jika diinginkan.","Keluarkan dari oven dan diamkan selama 5-10 menit. Lalu gunakan pisau bergerigi atau pisau listrik untuk mengiris. Sajikan dan nikmati."],
["Jangan merasa terintimidasi! Ini JAUH lebih mudah dibuat daripada kelihatannya. 🙂 Pastikan menggunakan kaldu berkualitas baik dan sangat penuh rasa untuk hasil terbaik. Saya menggunakan dan menyukai kaldu buatan sendiri ini, tetapi yang dibeli di toko juga bisa. Kain keju lebih mudah daripada kertas roti dan aluminium foil untuk membungkus ham vegan Anda. Selain itu, aman untuk makanan jika Anda lebih suka menghindari foil. Beri ham Anda sedikit waktu untuk beristirahat sebelum diiris. Saat mulai dingin, ham akan semakin mengeras dan mempermudah pengirisan serta memungkinkan irisan yang lebih tipis. Sisa makanan dapat disimpan di lemari es dalam wadah tertutup hingga 5 hari. Anda dapat membekukan sisa makanan, utuh atau diiris dalam kantong ziptop atau wadah yang aman untuk freezer hingga 3 bulan."],
[]))
build(R,'part8.json')
