from mk import *
R=[]
R.append((9661912,"Salad Kale Jeruk dengan Vinaigrette Sitrus",
"Salad kale jeruk alias salad kale musim dingin ini segar dan beraroma sitrus, dengan sentuhan manis dan asam di setiap gigitan. Kaya rasa, tetapi hanya memerlukan beberapa bahan. Siap dalam 20 menit!",
"4 porsi","1 porsi",
[("Untuk Salad","6 cangkir kale dipadatkan sekitar 1 ikat besar, batang tebal dibuang dan kale disobek menjadi potongan besar seukuran sekali gigit"),("Untuk Salad","2-3 sendok makan air lemon sekitar setengah lemon besar"),("Untuk Salad","1 kaleng 15 ons buncis ditiriskan & dibilas"),("Untuk Salad","¼ cangkir hemp hearts atau biji labu mentah atau biji bunga matahari"),("Untuk Salad","1 jeruk dikupas & dipisahkan per segmen"),("Untuk Vinaigrette Sitrus","⅓ cangkir air jeruk yang baru diperas sekitar 1 jeruk sedang"),("Untuk Vinaigrette Sitrus","2 sendok makan cuka apel"),("Untuk Vinaigrette Sitrus","1 sendok teh mustard kuning"),("Untuk Vinaigrette Sitrus","1 sendok teh jahe bubuk"),("Untuk Vinaigrette Sitrus","¼ sendok teh garam laut")],
["Sobek kale Anda menjadi potongan besar seukuran sekali gigit dan buang batang yang tebal. Bilas hingga bersih lalu masukkan ke dalam mangkuk pencampur besar. Tuang air lemon di atasnya dan pijat kale dengan tangan Anda selama 2-3 menit. Ini akan melayukan dan melunakkan kale dengan lembut.","Masukkan buncis dan hemp hearts ke dalam mangkuk yang sama dan sisihkan.","Campurkan bahan-bahan dressing dalam mangkuk kecil dan kocok hingga tercampur sempurna. Lalu tuang dressing ke salad Anda dan aduk rata agar tersebar merata.","Hias dengan segmen jeruk dan nikmati."],
["Pastikan memijat kale. Jangan lewati langkah ini. Hanya membutuhkan waktu 2-3 menit dan hasilnya sepadan dengan usahanya. Gunakan air jeruk yang baru diperas untuk rasa terbaik. Jika Anda tidak punya cuka apel, ganti dengan cuka anggur putih atau balsamic putih dengan hasil yang serupa. Sisa makanan dapat disimpan di lemari es selama 1-2 hari."],
[]))
R.append((9665970,"Labu Acorn Air Fryer",
"Labu acorn air fryer ini hanya memerlukan 4 bahan, tetapi penuh rasa dan tidak akan mengecewakan.",
"3 porsi","1 porsi",
["2 pon labu acorn (1 labu kecil) dikupas + dipotong dadu setengah inci","2 sendok makan kaldu sayuran rendah natrium","½ sendok teh garam laut","½ sendok teh paprika asap","½ sendok teh bubuk bawang putih"],
["Kupas dan potong labu acorn Anda menjadi dadu setengah inci dan masukkan ke dalam mangkuk pencampur.","Masukkan bahan-bahan yang tersisa ke dalam mangkuk dan aduk rata agar bumbu tersebar merata.","Atur air fryer Anda pada suhu 400°F/200°C dan masak labu acorn dengan air fryer selama 18-24 menit, sesekali aduk atau goyangkan. Waktu memasak akan bervariasi di antara model air fryer yang berbeda."],
["Berhati-hatilah saat memotong dan mengupas labu karena kulitnya sangat keras. Setiap air fryer akan bervariasi dalam waktu memasak, jadi pastikan labu empuk saat ditusuk garpu dengan tepi yang renyah sebelum disajikan. Sisa makanan dapat disimpan dalam wadah tertutup di lemari es selama 3-4 hari."],
[]))
R.append((9666805,"Pure Polenta Vegan",
"Pure polenta yang creamy, penuh rasa dan lezat, dengan lebih sedikit kalori daripada kentang tumbuk.",
"4 porsi","1 porsi",
["2 sendok makan mentega vegan (atau minyak masak (untuk bebas minyak lewati dan tumis menggunakan kaldu))","2-3 siung bawang putih (dicincang halus)","4 cangkir kaldu sayuran","1 cangkir tepung jagung (corn meal)","1 cangkir susu oat tanpa pemanis (atau susu non-susu pilihan Anda)","1/4 cangkir keju parmesan vegan (opsional, tetapi disarankan)","mentega vegan atau minyak zaitun","kucai, daun bawang, atau dill yang baru dicincang","saus kental bawang bombai (onion gravy)","saus kental miso (miso gravy)"],
["Lelehkan mentega (jika digunakan) dan tumis bawang putih selama 30-60 detik hingga harum.","Masukkan kaldu dan didihkan. Lalu kecilkan api dan tuang tepung jagung perlahan. Masak dengan api kecil, sering diaduk selama 15-20 menit hingga sangat kental dan empuk.","Matikan api, tambahkan susu dan keju parmesan vegan, lalu aduk rata. Sajikan segera."],
[],[]))
R.append((9668816,"Kari Thailand Instant Pot",
"Kari Thailand buatan sendiri yang mudah, satu panci, dengan lapisan banyak rasa yang luar biasa! Bergizi dan sehat tetapi rasanya seperti makanan penghibur!",
"5 porsi","1 porsi",
["1 sendok makan minyak kelapa lewati agar bebas minyak dan tumis dalam air atau kaldu","1 bawang bombai kuning besar dicincang halus","6 siung bawang putih dikupas dan dicincang halus","1 sendok makan jahe segar diparut atau dicincang (sekitar 1\" akar jahe)","2 paprika merah diiris (atau warna pilihan Anda)","2 wortel besar diiris memanjang","1 kepala brokoli dipotong menjadi kuntum","1 cangkir kaldu sayuran rendah natrium","1 kaleng 400ml santan tanpa pemanis Thai Kitchen *Anda dapat menggunakan yang lite untuk lemak lebih rendah, tetapi rasa kelapanya juga akan berkurang","5 sendok makan pasta kari merah Thai Kitchen","2 sendok makan tamari atau kecap asin jika tidak menghindari gluten","1 sendok makan sirup maple","½ sendok teh merica hitam","2 sendok makan air jeruk nipis sekitar 1 jeruk nipis besar",("Opsional","Sajikan dengan nasi merah atau putih, mi, atau roti naan."),("Opsional","Hias dengan irisan jeruk nipis, basil Thailand, ketumbar segar dan/atau sriracha, jika diinginkan.")],
["Siapkan dan cincang semua sayuran Anda sebelum mulai. Lalu atur Instant Pot Anda ke mode tumis dan masukkan minyak kelapa (jika digunakan) dan bawang bombai cincang lalu tumis selama 3-5 menit, sering diaduk. Lalu masukkan jahe dan bawang putih yang sudah dicincang/diparut ke dalam panci, aduk rata dan tumis sekitar 30 detik lagi.","Matikan panci dan masukkan semua bahan yang tersisa KECUALI air jeruk nipis. Aduk rata, tutup penutup dan atur katup ke posisi menyegel. Atur panci Anda ke manual atau pressure cook (tergantung model Anda) selama 3 menit pada tekanan tinggi. Dibutuhkan sekitar 10 menit untuk mencapai tekanan lalu mulai menghitung mundur.","Setelah selesai, lepaskan uap dengan cepat melalui katup dan buka penutup setelah aman. Peras air jeruk nipis ke dalam panci Anda dan aduk rata. Sajikan dengan nasi, mi, atau roti naan dan hias dengan sriracha dan rempah segar, jika diinginkan."],
["Beri kari Thailand Anda tambahan protein dengan menambahkan satu kaleng buncis atau lentil, jika diinginkan. Untuk rasa pedas ekstra, tambahkan setengah sendok teh cabai cayenne atau serpihan cabai. Saya merasa hidangan ini hanya sedikit pedas apa adanya. Gunakan jahe dan bawang putih SEGAR untuk hasil rasa terbaik. Jika Anda menjalani diet rendah lemak, Anda dapat melewatkan minyak kelapa dan menumis dalam kaldu sayuran atau air sebagai gantinya. Anda juga dapat mengganti santan dengan versi lite, namun perlu diingat, rasa kelapanya akan sedikit berkurang. Untuk bebas kedelai, lewati Tamari atau kecap asin dan tambahkan sedikit garam ekstra sebagai gantinya. Atau, ganti dengan coconut aminos. Tidak punya brokoli? Ganti dengan kacang polong manis, buncis hijau, kembang kol atau kale. Simpan sisa nasi dan kari Thailand dalam wadah terpisah di lemari es Anda hingga 3 hari. Panaskan kembali dan nikmati."],
[]))
R.append((9671588,"Salad Pasta Pesto Lentil",
"Salad pasta lentil dengan pesto lentil! Penuh rasa, mudah disiapkan, dan terasa luar biasa baik hangat maupun dingin.",
"4 porsi","1 porsi",
[("Untuk pesto lentil","1 cangkir daun basil segar dipadatkan"),("Untuk pesto lentil","½ cangkir lentil hijau matang atau kalengan"),("Untuk pesto lentil","2 siung bawang putih dikupas"),("Untuk pesto lentil","2 sendok makan air lemon sekitar setengah lemon"),("Untuk pesto lentil","2-3 sendok makan kaldu sayuran"),("Untuk pesto lentil","garam + merica secukupnya"),("Untuk salad pasta lentil","½ pon pasta rotini atau pasta pendek lainnya"),("Untuk salad pasta lentil","1 pint tomat ceri dibelah dua"),("Untuk salad pasta lentil","½ cangkir lentil hijau matang atau kalengan"),("Untuk salad pasta lentil","½ cangkir almond iris tipis disangrai")],
["Didihkan panci besar berisi air yang diberi banyak garam dan masak pasta Anda sesuai petunjuk kemasan hingga 'al dente'. Tiriskan, (TETAPI simpan 1/2 cangkir air rebusan pasta) masukkan ke dalam mangkuk besar, dan sisihkan.","Sementara itu, masukkan semua bahan pesto lentil kecuali kaldu ke dalam food processor Anda dan proses hingga tercincang halus, kerok sisi mangkuk sesuai kebutuhan. Lalu tambahkan 2-3 sendok makan kaldu untuk mengencerkan pesto sesuai selera Anda. Cicipi garam dan merica dan tambahkan jika perlu.","Sekarang masukkan pesto, 1/2 cangkir lentil lainnya, tomat ceri, dan almond iris (sisihkan sebagian untuk hiasan) ke dalam mangkuk berisi pasta matang. Aduk rata dan tambahkan sedikit air rebusan pasta yang disimpan jika perlu. Sajikan hangat atau dingin."],
["Beri garam pada air rebusan pasta Anda. Pastikan menambahkan garam yang cukup ke dalam panci air Anda untuk tekstur dan rasa terbaik. Berikut panduan praktis untuk membantu Anda menggarami air dengan sempurna setiap kali.","Masak pasta Anda 'al dente'. Pasta al dente biasanya \"kurang matang\" 1-3 menit. Beginilah cara orang Italia menikmati pasta mereka. 😉 Kami suka sedikit gigitan, dan tidak lembek.","Sisa salad pasta lentil dapat disimpan di lemari es selama 3-4 hari. Saya tidak menyarankan pembekuan."],
[]))
R.append((9675054,"Salad Elote Vegan [Tanpa Minyak + SANGAT Mudah!]",
"Mengubah hidangan klasik Meksiko menjadi salad elote vegan yang kaya, penuh rasa, creamy, dan sangat lezat. Pasti memuaskan banyak orang.",
"4 porsi","1 porsi",
["2 cangkir jagung beku dicairkan","1 cangkir mentimun dipotong dadu","1 alpukat sedang dipotong dadu","¼ cangkir bawang merah dipotong dadu","⅓ cangkir daun ketumbar","½ sendok teh serpihan cabai atau lebih",("Untuk Dressing","½ cangkir mete mentah"),("Untuk Dressing","2 sendok makan air lemon sekitar setengah lemon sedang"),("Untuk Dressing","¼ cangkir air segar"),("Untuk Dressing","1 sendok makan cuka apel"),("Untuk Dressing","¼ sendok teh garam laut atau secukupnya"),("Hiasan Opsional","ketumbar tambahan"),("Hiasan Opsional","keju Parmesan vegan"),("Hiasan Opsional","serpihan cabai ekstra")],
["Masukkan semua bahan dressing ke dalam blender Anda dan proses hingga halus dan creamy. Mulailah dengan kecepatan rendah lalu tingkatkan perlahan agar serpihan mete tidak terciprat. Kerok sisi blender, sesuai kebutuhan. Sisihkan.","Campurkan semua bahan salad dalam mangkuk pencampur dan tuang dressing di atasnya lalu aduk rata.","Dinginkan selama 1 jam atau sajikan segera."],
["Jika Anda tidak punya blender yang bertenaga, rendam mete Anda terlebih dahulu. Anda dapat merendam semalaman dalam air dingin, atau merendam dalam air mendidih selama 30 menit. Waktu perendaman akan mengembangkan dan melunakkan mete, sehingga lebih mudah diblender. Meskipun Anda dapat menikmatinya langsung, elote vegan ini paling enak saat didinginkan selama 1 jam, jadi rencanakan sebelumnya jika memungkinkan. Untuk rasa yang kurang pedas, kurangi separuh serpihan cabai, atau ganti dengan bubuk cabai. Jika Anda tidak punya lemon, Anda dapat menggantinya dengan air jeruk nipis atau menggunakan lebih banyak cuka. Sisa makanan dapat disimpan di lemari es selama 3-4 hari."],
[]))
R.append((9682858,"Dip Ranch Vegan [Tanpa Minyak + Pilihan Bebas Kacang]",
"Pelajari cara membuat dip ranch vegan yang mudah ini dengan bahan-bahan dapur dan blender. Anda hanya memerlukan 5 menit untuk dip ranch mete yang creamy dan lezat ini yang ingin Anda gunakan untuk mencelup segalanya!",
"8 porsi","1 porsi",
["1 cangkir mete mentah","½ cangkir air ditambah 1-2 sendok makan jika Anda lebih suka yang lebih encer","1 sendok makan air jeruk nipis","1 sendok teh peterseli kering","1 sendok teh dill kering","½ sendok teh bubuk bawang putih","½ sendok teh garam laut","¼ sendok teh merica hitam"],
["Masukkan semua bahan ke dalam blender berkecepatan tinggi dan proses hingga halus.","Pindahkan ke mangkuk atau wadah dan dinginkan di lemari es selama 1 jam sebelum disajikan."],
["Jika Anda tidak punya blender yang bertenaga, rendam mete Anda dalam air mendidih selama 20-30 menit. Lalu tiriskan sebelum diblender. Untuk dressing ranch, tambahkan 1-3 sendok makan air lagi untuk mengencerkannya sesuai selera Anda. ATAU tambahkan 1-3 sendok makan cuka apel. Setelah diblender, cicipi dan tambahkan lebih banyak garam atau bumbu lainnya, jika diinginkan. Simpan di lemari es dalam wadah tertutup hingga 7 hari, atau bekukan dalam wadah kedap udara hingga 6 bulan. Informasi nutrisi untuk sekitar 2 sendok makan atau ⅛ dari dip."],
[]))
R.append((9685307,"Kue Oatmeal Selai Kacang Vegan",
"Kue oatmeal selai kacang vegan yang kenyal dan tak tertahankan! Manis, tetapi sehat, untuk kue sarapan yang sempurna.",
"10 kue","1 porsi",
["½ cangkir selai kacang halus","⅓ cangkir sirup maple","¼ cangkir susu bebas susu hewani","1.5 cangkir oat gulung","100 gram (sekitar 1 cangkir) tepung almond tanpa kulit ari","½ sendok teh soda kue","⅓ cangkir keping cokelat hitam opsional"],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi loyang dengan kertas roti.","Campurkan selai kacang, sirup maple, dan susu dalam mangkuk berukuran sedang dan aduk rata. Lalu tambahkan oat, tepung almond, dan soda kue dan aduk hingga tercampur. Jika menggunakan keping cokelat, lipat sekarang.","Untuk kue besar (seperti pada foto) gunakan sendok es krim kue dua sendok makan. Sendokkan campuran menjadi 10 bola dan letakkan di atas loyang Anda dengan banyak ruang di antara masing-masing. Tekan setiap bola dengan lembut menggunakan bagian belakang sendok agar lebih mudah melebar. (Kue akan terus melebar di oven.)","Lalu panggang kue selama 11-12 menit dan keluarkan loyang dari oven. Kue mungkin tampak belum matang, tetapi akan mengeras saat dingin. Biarkan beristirahat selama 10 menit, lalu nikmati hangat, atau pindahkan ke rak kawat agar terus dingin."],
["Saya membuat kue yang sangat besar untuk kue sarapan. Namun, Anda dapat dengan mudah mendapatkan 20 kue jika menggunakan sendok es krim kue yang lebih kecil (1 sendok makan). Ini akan membagi dua informasi nutrisi per kue.","Timbang tepung almond untuk hasil yang paling akurat, daripada mengandalkan takaran cangkir.","Sisakan banyak ruang di antara setiap kue karena kue ini akan melebar cukup banyak.","Kue akan tampak belum matang, tetapi akan mengeras pada suhu ruang, jadi jangan memanggangnya terlalu lama."],
[]))
build(R,'part9.json')
