import json
def fv(n): return ["Portions de fruits et légumes", f"Portions de fruits et légumes par portion : {n}"]
def P(t): return [None,t]
R=[]
def add(id,title,desc,por,serv,ing,steps,hints,fvn=None):
    h=[P(x) if isinstance(x,str) else x for x in hints]
    if fvn is not None: h.append(fv(fvn))
    R.append({"id":id,"translations":{"fr":{"title":title,"description":desc,"portions":por,"serving_size":serv,
      "ingredients":[P(x) for x in ing],"steps":[P(x) for x in steps],"hints":h,"food_choices":[]}}})

add(7958623,"Chowder de dinde et maïs","Délicieux, copieux et prêt en seulement 30 minutes, ce chowder est idéal pour utiliser des restes.","4","423 g",
["2 c. à café d'huile de tournesol","400 g de pommes de terre, pelées et coupées en cubes de 1 cm","1 petit oignon, finement haché","1 branche de céleri, hachée","1 grosse carotte, coupée en petits dés","1 poivron rouge, épépiné et coupé en dés","1 c. à soupe de farine complète","300 ml de lait écrémé","300 ml de bouillon de légumes pauvre en sel","300 g de dinde cuite sans peau, coupée en dés","1 boîte de 198 g de maïs sans sel ajouté, égoutté","1 c. à soupe de persil plat haché"],
["Faites chauffer l'huile dans une grande casserole, ajoutez les pommes de terre, l'oignon, le céleri et la carotte, et faites sauter pendant 5 minutes en remuant de temps en temps. Saupoudrez de farine et laissez cuire 2 minutes en remuant constamment.","Retirez du feu et incorporez le lait et le bouillon. Remettez sur le feu et portez lentement à ébullition en remuant constamment. Ajoutez la dinde, le maïs et le poivron rouge, puis laissez mijoter 5 à 6 minutes, jusqu'à ce que les pommes de terre soient bien cuites. Parsemez de persil et servez."],
["Si vous cuisinez pour une seule personne, ce plat peut être divisé en portions et congelé."],1)

add(7959955,"Chili aux haricots à l'autocuiseur","Ce plat consistant, riche en protéines, est préparé en un rien de temps. J'utilise la fonction « maintien au chaud » pour qu'il soit prêt à manger quand je rentre du travail.","4","500 g",
["huile en spray de votre choix (facultatif)","2 oignons moyens, hachés","1 c. à café d'ail écrasé","1/2 c. à café de gingembre moulu","300 g de champignons variés","1 à 2 poivrons (verts, rouges ou jaunes), hachés","300 g de hachis Quorn","1 c. à soupe de vinaigre balsamique","80 g de carottes, coupées en cubes","1 boîte de 400 g de tomates concassées","1 boîte de 400 g de pois chiches au naturel, égouttés","1 boîte de 400 g de haricots rouges au naturel, égouttés","2 c. à café de concentré de tomate","700 ml de bouillon de légumes très pauvre en sel","1 pincée de flocons de piment"],
["Utilisez la fonction de dorage de votre autocuiseur pour faire ramollir les oignons et l'ail, puis saupoudrez de gingembre.","Ajoutez les champignons, les poivrons, le hachis de soja et le vinaigre balsamique. Lorsque le tout est doré, ajoutez les carottes et laissez cuire 20 minutes.","Ajoutez les tomates, les haricots, les pois chiches, le concentré de tomate et suffisamment de bouillon pour atteindre le milieu de la cuve.","Ajoutez les flocons de piment et réglez votre autocuiseur sur 30 minutes. Servez avec du riz."],
["Cette recette a été créée par Shivali, vedette de la couverture de Balance, au cours de son parcours vers la rémission."],5)

add(7962332,"Shakshuka","Un plat nord-africain d'œufs pochés dans une sauce épicée à la tomate, au poivron et à l'oignon. Idéal pour un brunch du week-end.","1","645 g",
["1 petit oignon, finement émincé, environ 60 g, non pelé","1 poivron rouge et 1 poivron orange, coupés en deux, épépinés et hachés, environ 120 g de poids brut","1 gousse d'ail, écrasée","1 c. à café de pâte de tomates séchées ou de concentré de tomate","1 c. à café de paprika fumé","1/2 c. à café de cumin moulu","1/2 c. à café de coriandre moulue","1 boîte de 400 g de tomates concassées","1 œuf","Persil et menthe frais hachés"],
["Mettez l'oignon, les poivrons et l'ail dans un bol en verre avec 1 c. à soupe d'eau. Couvrez de film alimentaire et faites cuire au micro-ondes à 800 W pendant 2 minutes. Remuez et poursuivez la cuisson 2 minutes de plus.","Incorporez la pâte et les épices au mélange d'oignon et faites cuire au micro-ondes encore 1 minute. Versez dans une poêle moyenne.","Ajoutez les tomates et laissez mijoter doucement 15 minutes, ou jusqu'à épaississement, en remuant de temps en temps.","Creusez un puits au centre et cassez-y l'œuf. Couvrez la poêle avec un couvercle et laissez cuire jusqu'à ce que l'œuf soit cuit à votre goût.","Parsemez de flocons de piment rouge (facultatif), d'un peu de persil et de menthe hachés, et servez."],
["Vous pouvez utiliser des poivrons de n'importe quelle couleur pour ce plat.","Essayez d'ajouter des champignons ou des cœurs d'artichaut.","Instructions de congélation : la sauce peut être congelée."],5)

add(7963728,"Cabillaud gratiné aux fines herbes et au fromage","Une façon simple de rendre le cabillaud encore plus délicieux.","2","228 g",
["15 g de matière grasse végétale à tartiner","15 g de farine ordinaire","100 ml de lait","25 g de cheddar fort ou d'un autre fromage à pâte dure, râpé","1 c. à café de moutarde anglaise","2 c. à soupe de fines herbes mélangées, hachées","poivre noir fraîchement moulu","2 gros morceaux de filet de cabillaud (ou de tout autre poisson blanc épais) d'environ 150 g chacun"],
["Préchauffez le four à 200 °C/thermostat 6. Faites fondre la matière grasse dans une petite casserole, incorporez la farine au fouet et laissez cuire 1 minute.","Ajoutez progressivement le lait en fouettant constamment, et laissez mijoter 1 minute jusqu'à obtenir une sauce épaisse.","Incorporez le fromage, la moutarde et les herbes, et assaisonnez avec le poivre noir.","Placez les morceaux de cabillaud sur une plaque de cuisson et nappez-les de sauce.","Enfournez et laissez cuire environ 15 minutes, jusqu'à ce que le poisson soit cuit.","Servez avec les légumes de votre choix."],
["Essayez d'autres combinaisons d'herbes, comme le persil et l'aneth ou la coriandre et la ciboulette.","Cette garniture convient aux filets de maquereau, à l'églefin, au silure ou au tilapia.","Vous pouvez laisser refroidir la sauce, puis l'étaler sur le poisson et réfrigérer jusqu'au moment voulu.","Sortez du réfrigérateur 10 minutes avant la cuisson, puis cuisez comme indiqué."],0)

add(7965730,"Tarte aux fraises","Il s'agit d'une recette exclusive tirée de « The Diabetes Weight Loss Diet » d'Antony Worrall Thompson et Azmina Govindji.","6","105 g",
["4 feuilles de pâte filo","2 c. à café de beurre non salé, fondu","1 c. à soupe de sucre glace","6 c. à soupe de fromage frais 0 % de matières grasses","1 c. à soupe de lemon curd","350 g de petites fraises mûres, équeutées et tranchées"],
["Préchauffez le four à 200 ºC/thermostat 6. Posez une feuille de pâte filo sur une plaque de cuisson antiadhésive. Badigeonnez d'un peu de beurre fondu et saupoudrez d'un peu de sucre glace.","Répétez l'opération trois fois, en réservant environ 1 c. à café de sucre glace.","Faites cuire 10 minutes, jusqu'à ce que la pâte soit dorée. Laissez refroidir. Mélangez le fromage frais avec le lemon curd et étalez sur la pâte.","Garnissez de fraises et saupoudrez du sucre glace réservé. Servez immédiatement."],
["Cette recette est aussi délicieuse avec des framboises.","Si vous n'avez pas de lemon curd, utilisez plutôt 1 c. à soupe de confiture."])

add(7967885,"Tartine ouverte aux crevettes et à l'aneth","Un sandwich délicieusement rafraîchissant, parfait pour les pique-niques","1","230 g",
["1 sandwich thin complet, coupé en deux","80 g de fromage blanc nature allégé en matières grasses (cottage cheese)","1 brin d'aneth frais","1 trait de sauce Tabasco (facultatif)","30 g de concombre, finement tranché","50 g de crevettes royales cuites et décortiquées"],
["Faites légèrement griller les deux moitiés de sandwich thin. Mélangez le fromage blanc avec un peu d'aneth ciselé, quelques gouttes de Tabasco, si vous en utilisez, et un peu de poivre noir.","Répartissez le mélange sur les sandwich thins, puis ajoutez les tranches de concombre, les crevettes, un peu d'aneth supplémentaire et un trait de Tabasco, puis servez."],[])

add(7967911,"Désordre de framboises au sablé","Une version plus saine de l'Eton mess classique.","2","170 g",
["150 g de framboises","1 c. à café d'édulcorant sans sucre","2 sablés en bâtonnets (39 g au total)","150 g de yaourt grec à 0 %"],
["Dans un bol, écrasez délicatement la moitié des framboises à la fourchette et mélangez avec l'édulcorant.","Dans un autre bol, émiettez les sablés.","Réservez quelques framboises entières et un peu de sablé émietté pour la décoration.","Incorporez délicatement au yaourt les framboises entières et écrasées restantes, ainsi que le sablé.","Répartissez dans des verres ou des bols, saupoudrez de sablé émietté et décorez d'une framboise."],
["Cette recette fonctionne aussi très bien avec des fraises ou des mûres. Ou essayez avec des pêches ou des nectarines coupées en morceaux.","Essayez d'utiliser d'autres biscuits, comme des biscuits sablés complets (digestives) ou des biscuits au gingembre.","Pour une version végétalienne, remplacez le yaourt par une alternative sans produits laitiers à base de soja ou de noix de coco.","Instructions de congélation : sortez du congélateur quelques minutes avant de servir."])

add(7972804,"Panna cotta et compote de fruits","Ce dessert italien classique est aussi bon qu'il en a l'air.","4","315 g",
["600 ml de lait d'amande enrichi non sucré","2 c. à café d'agar-agar en poudre","200 ml de babeurre","1 gousse de vanille, fendue","3 c. à soupe d'édulcorant en grains","1 citron, zeste finement râpé et jus","1 barquette de fraises (environ 14), équeutées et coupées en quatre","1 petite barquette de framboises (environ 4 poignées)","1 petite barquette de myrtilles (environ 4 poignées)","25 g de pistaches, grillées et grossièrement hachées"],
["Faites chauffer le lait d'amande jusqu'à ce qu'il arrive tout juste à ébullition. Saupoudrez d'agar-agar et laissez mijoter 2 minutes en remuant constamment.","Retirez la gousse de vanille et grattez les graines avec un couteau bien aiguisé. Incorporez au fouet les graines de vanille, 2 c. à soupe d'édulcorant et le babeurre jusqu'à obtenir un mélange lisse.","Répartissez à parts égales dans 4 verres. Vous pouvez aussi utiliser 4 ramequins de 175 ml, légèrement vaporisés d'un spray allégé en calories, si vous souhaitez démouler ces desserts. Laissez prendre au réfrigérateur pendant 2 heures, jusqu'à ce que ce soit ferme, ou jusqu'au moment de servir.","Mettez le zeste et le jus de citron, 2 c. à soupe d'eau, les fraises, les framboises et les myrtilles dans une petite casserole avec le reste de l'édulcorant et faites chauffer doucement 2 à 3 minutes pour les réchauffer. Laissez refroidir.","Une fois les panna cotta prises, versez à la cuillère la compote de fruits dans les verres et parsemez de pistaches. Si vous utilisez des ramequins, plongez le fond de chaque ramequin dans de l'eau chaude pendant 20 à 30 secondes et retournez sur une assiette pour démouler les desserts. Servez avec la compote et les noix."],
["Si vous utilisez du lait d'amande enrichi, ce dessert est riche en calcium, ce qui est important pour maintenir des dents et des os en bonne santé.","Les baies sont une bonne source de vitamine C."],1)

add(7972818,"Pommes farcies au four","Des pommes farcies de noix hachées, de raisins secs et de cannelle, puis cuites au four, pour un dessert simple mais délicieux.","6","126 g",
["20 g de noix","30 g d'abricots secs","25 g de raisins secs de Smyrne (sultanines)","1 c. à café de cannelle moulue","20 g de graines de courge","zeste finement râpé et jus de 1 orange","6 pommes à croquer, non pelées et évidées","1 c. à soupe d'eau"],
["Préchauffez le four à 180 °C/thermostat 4.","Mélangez les noix, les abricots et les raisins secs, puis déposez sur une planche. Hachez finement l'ensemble pour obtenir une pâte, puis incorporez les graines de courge, la cannelle et le zeste d'orange.","Remplissez le centre de chaque pomme avec ce mélange, en le tassant fermement dans le fruit.","Placez les pommes dans un plat allant au four avec l'eau, puis arrosez-les du jus d'orange.","Couvrez de papier aluminium et faites cuire 20 minutes. Retirez le papier aluminium et poursuivez la cuisson 10 à 15 minutes.","Servez avec une cuillerée de yaourt nature non sucré ou d'une alternative sans produits laitiers."],
["Essayez différentes combinaisons de fruits et de noix pour la garniture.","Essayez avec des canneberges et des épices mélangées pour une saveur de Noël."],1)

add(7973577,"Riz au lait à la mangue, à la lime et à la noix de coco","Ce riz au lait a une touche fruitée et plein de saveur.","5","198 g",
["1 spray d'huile à 1 calorie","100 g de riz à dessert sec (riz rond pour pudding)","2 c. à soupe d'édulcorant","650 ml de lait d'amande enrichi non sucré","1 c. à café d'extrait de vanille","zeste finement râpé et jus de 1 lime","3 gousses de cardamome, légèrement écrasées","2 mangues mûres de taille moyenne, pelées et finement tranchées","20 g de noix de coco desséchée grillée non sucrée"],
["Préchauffez le four à 150 °C/thermostat 2. Vaporisez légèrement un plat à pudding moyen allant au four avec un spray de cuisson allégé en calories.","Placez le riz dans une passoire et rincez-le sous l'eau froide courante. Égouttez et versez dans le plat allant au four. Incorporez l'édulcorant, le lait d'amande, l'extrait de vanille, le jus de lime et la cardamome. Faites cuire 50 minutes.","Remuez bien et poursuivez la cuisson 1 heure de plus. Disposez les tranches de mangue sur le dessus, saupoudrez de noix de coco desséchée et remettez au four 10 minutes. Parsemez de zeste de lime et servez immédiatement."],
["Si vous utilisez du lait d'amande enrichi, ce dessert est une bonne source de calcium, ce qui est important pour maintenir des os en bonne santé."],1)

add(7974942,"Salade de pâtes méditerranéenne","Elle fait un excellent repas à emporter. Avec toutes ses saveurs méditerranéennes, c'est une belle alternative aux sandwichs.","3","293 g",
["225 g de pâtes sèches de forme courte","10 tomates cerises, coupées en quatre","10 olives noires, tranchées","un quart de concombre, haché","un demi-oignon rouge, finement émincé","40 g de feta, émiettée","15 g de pignons de pin, grillés","1 c. à soupe d'huile d'olive","1 c. à soupe de vinaigre balsamique","une poignée de feuilles de basilic"],
["Faites cuire les pâtes selon les instructions du paquet. Égouttez et rincez à l'eau froide.","Mélangez les pâtes avec les autres ingrédients et servez."],
["Pour faire griller les pignons de pin, mettez-les dans une poêle sèche à feu moyen, remuez régulièrement pendant quelques minutes jusqu'à ce qu'ils commencent à dorer, puis retirez-les immédiatement de la poêle pour arrêter la cuisson.","Pour une version sans gluten, remplacez les pâtes par une boîte de pois chiches."],1)

add(7975803,"Curry de pommes de terre et de lentilles","Les pommes de terre sont un merveilleux ingrédient pour les currys : elles absorbent toutes les saveurs épicées et apportent de la consistance.","4","461 g",
["1 c. à café d'huile de tournesol","1 oignon, haché","1 c. à café de graines de moutarde","2 cm de gingembre frais, pelé et râpé","1 c. à café de piment en poudre","1 c. à café de coriandre moulue","1 pincée de curcuma","6 c. à soupe de coriandre fraîche, feuilles et tiges finement hachées","200 g de tomates concassées","2 c. à soupe de concentré de tomate","125 g de lentilles jaunes, lavées et égouttées","600 ml de bouillon de légumes","900 g de pommes de terre farineuses, pelées et coupées en cubes","feuilles de coriandre fraîche, pour servir"],
["Faites chauffer l'huile de tournesol dans une casserole moyenne. Ajoutez l'oignon et faites-le revenir 2 à 3 minutes. Ajoutez les graines de moutarde, le gingembre, le piment en poudre, la coriandre, le curcuma et la coriandre fraîche, et poursuivez la cuisson 1 minute.","Ajoutez dans la casserole les tomates, le concentré de tomate et les lentilles, puis versez le bouillon. Portez à ébullition, réduisez le feu, couvrez et laissez mijoter 25 minutes, ou jusqu'à ce que les lentilles soient presque tendres.","Incorporez les pommes de terre et poursuivez la cuisson 10 à 15 minutes, jusqu'à ce qu'elles soient tendres. Incorporez les feuilles de coriandre et servez avec un raita au yaourt."],
["Vous pouvez utiliser des patates douces à la place des pommes de terre ordinaires : elles comptent parmi vos 5 fruits et légumes par jour.","Pour une rapide relish d'oignon rouge à servir avec le curry, émincez finement 1 oignon rouge et 1 tomate finement hachée, mélangez avec le jus de 1 citron et une petite pincée de sel. Laissez infuser 10 minutes avant de servir.","Instructions de congélation : se congèle une fois cuit. Décongelez au réfrigérateur ou au micro-ondes et réchauffez jusqu'à ce que le plat soit bien chaud à cœur."],1)

add(7982558,"Pâtes à l'aubergine, aux courgettes, à la ricotta et aux pignons de pin","Essayez ce plat savoureux et nutritif pour égayer vos plats de pâtes habituels.","2","431 g",
["1 petite aubergine (environ 250 g), hachée","6 mini-courgettes (environ 400 g), coupées en deux dans la longueur","1 gousse d'ail, tranchée","1 piment, finement haché (facultatif)","1 c. à café d'huile d'olive","1 c. à soupe de vinaigre balsamique","150 g de pâtes sèches de forme courte","1 c. à soupe de pignons de pin, grillés","2 c. à soupe de ricotta","une poignée de basilic frais, déchiré"],
["Préchauffez le four à 200 °C/thermostat 6.","Placez l'aubergine, les courgettes, l'ail et le piment (si vous en utilisez) dans un plat allant au four, arrosez d'huile et de vinaigre et faites cuire 30 à 40 minutes, jusqu'à ce que les légumes soient tendres et commencent à noircir légèrement.","Pendant ce temps, faites cuire les pâtes selon les instructions du paquet. Égouttez.","Mélangez les pâtes avec les pignons de pin et la ricotta, puis parsemez de basilic et servez."],
["Si vous ne trouvez pas de ricotta, vous pouvez utiliser du fromage frais allégé en matières grasses ou du fromage de chèvre."],4)

add(7982930,"Tortilla aux épinards, à l'oignon rouge et aux pommes de terre","Elle est parfaite chaude ou froide, pour le déjeuner, un pique-nique ou un barbecue.","4","258 g",
["400 g de pommes de terre nouvelles","250 g d'épinards en feuilles surgelés (130 g une fois décongelés et l'excès d'eau pressé)","1 c. à soupe d'huile d'olive","1 gros oignon rouge, finement émincé","5 œufs","1 pincée de poivre, pour assaisonner"],
["Faites cuire les pommes de terre dans leur peau à l'eau bouillante pendant 15 à 20 minutes (selon leur taille), jusqu'à ce qu'elles soient presque cuites mais encore fermes. Égouttez-les et passez-les sous l'eau froide du robinet pour les manipuler plus facilement, puis coupez chaque pomme de terre en tranches de 1⁄2 cm d'épaisseur.","Pendant ce temps, faites décongeler les épinards, pressez-les pour en extraire l'excès d'eau et hachez-les grossièrement.","Versez l'huile dans une grande poêle antiadhésive et placez sur feu moyen. Ajoutez l'oignon et faites cuire 2 à 3 minutes, jusqu'à ce qu'il soit tendre.","Battez les œufs avec le poivre, incorporez les épinards, puis ajoutez les pommes de terre.","Versez le mélange d'œufs dans la poêle. Utilisez une spatule pour tasser la tortilla et repousser les bords afin d'obtenir une forme régulière.","Lorsque la tortilla est presque prise (environ 5 minutes), retournez-la sur une assiette, puis faites-la glisser de nouveau dans la poêle pour cuire l'autre face pendant 5 minutes. Réduisez le feu et retournez la tortilla encore deux fois, en la faisant cuire 2 à 3 minutes de chaque côté pour vous assurer que le centre est cuit.","Faites glisser la tortilla sur une assiette et laissez refroidir 10 à 15 minutes. Il est préférable de la servir tiède, car elle est bien meilleure ainsi. Pour un repas à emporter, laissez-la refroidir complètement avant de la couper et de l'emballer."],
["Pour cette recette de tortilla (également appelée omelette espagnole), vous pouvez utiliser d'autres légumes à la place des épinards, comme des petits pois et du poivron rouge. Ou essayez d'ajouter des herbes ou de l'ail."],1)

add(7984576,"Mojito sans alcool","Boisson cubaine traditionnelle, ce délicieux rafraîchissement ajoute de l'éclat à toutes les fêtes.","4","207 g",
["16 grandes feuilles de menthe fraîche, plus 4 brins pour servir","2 limes fraîches, lavées et coupées en petits morceaux","4 c. à café d'édulcorant artificiel en grains (ajoutez-en plus si vous le souhaitez)","750 ml d'eau gazeuse","12 glaçons","1 lime fraîche, en rondelles ou en quartiers, pour servir"],
["Répartissez les feuilles de menthe et les morceaux de lime entre quatre verres individuels, en pressant chaque morceau au moment de l'ajouter.","Ajoutez l'édulcorant et écrasez le tout avec le manche d'une cuillère en bois pour faire ressortir le jus et les arômes.","Ajoutez les glaçons dans chaque verre, complétez avec de l'eau gazeuse, remuez et servez avec un brin de menthe, quelques morceaux de lime et une paille."],
["Vous pouvez utiliser des oranges, ou essayer des citrons à la place.","Le mojito sans alcool est aussi idéal servi dans une grande carafe."],0)

add(7987020,"Pizza espagnole à l'oignon et aux anchois","Elle est idéale coupée en petits morceaux et servie lors d'un apéritif, en entrée ou en repas léger.","8","101 g",
["200 g de farine de blé à forte teneur en gluten (farine de force)","un quart de c. à café de sel","1 sachet de 7 g de levure instantanée","2 c. à soupe d'huile d'olive","75 ml de lait demi-écrémé","2 gros oignons, finement émincés","1 boîte de 25 g d'anchois, égouttés et grossièrement hachés","1 c. à soupe de pignons de pin","1 c. à soupe de raisins secs de Smyrne (sultanines)","une demi-c. à café de flocons de piment","2 c. à café de ciboulette fraîche, hachée, pour décorer"],
["Préchauffez le four à 200 °C/thermostat 6. Dans un grand bol, tamisez ensemble la farine et le sel. Incorporez la levure. Mélangez la moitié de l'huile, le lait et 50 ml d'eau tiède, versez sur la farine et mélangez pour former une pâte.","Déposez la pâte sur un plan de travail légèrement fariné et pétrissez-la 5 minutes, jusqu'à ce qu'elle soit lisse.","Placez-la dans un bol légèrement huilé, couvrez d'un torchon humide et laissez reposer dans un endroit chaud pendant 1 heure, jusqu'à ce qu'elle ait doublé de volume. Pétrissez-la de nouveau, puis façonnez-la en un carré d'environ 40 cm x 40 cm.","Pendant ce temps, faites chauffer le reste de l'huile dans une poêle, ajoutez les oignons et faites-les revenir doucement 8 à 10 minutes, jusqu'à ce qu'ils soient ramollis et commencent à dorer.","Répartissez-les sur la base de pizza avec les autres ingrédients, sauf la ciboulette, puis faites cuire 20 à 25 minutes, jusqu'à ce que la base soit dorée et croustillante. Parsemez de ciboulette et servez."],
["Pour une version végétarienne, utilisez 75 g de tomates séchées émincées à la place des anchois.","Préparez la pizza avec des oignons rouges pour plus de couleur."],0)

add(7988967,"Poulet tikka masala","Une version plus saine et moins grasse du curry préféré des Britanniques, avec tout le goût.","4","195 g",
["1 c. à café d'huile de colza","1 gros oignon, haché","1 poivron rouge, finement haché","2 blancs de poulet sans peau (300 g), coupés en cubes","2 c. à soupe de pâte tikka","2 à 3 gousses d'ail, écrasées","1 boîte de 400 g de tomates concassées","2 c. à soupe de coriandre fraîche hachée, plus 2 c. à café pour servir","2 c. à soupe de yaourt grec à 0 % de matières grasses"],
["Versez l'huile dans une casserole et ajoutez les oignons et les poivrons. Faites cuire 5 minutes jusqu'à ce qu'ils soient tendres, puis ajoutez les blancs de poulet et laissez cuire 3 minutes.","Ajoutez la pâte tikka et remuez 1 à 2 minutes, jusqu'à ce que le poulet soit uniformément enrobé.","Ajoutez l'ail et les tomates, mélangez de nouveau et portez à léger frémissement, puis couvrez et laissez mijoter doucement 6 à 8 minutes.","Ajoutez la coriandre, remuez bien, puis retirez du feu.","Incorporez le yaourt, saupoudrez du reste de coriandre et servez immédiatement."],
["Fonctionne très bien avec de la dinde ou du saumon coupé en cubes.","Servez avec beaucoup de salade. Pour une option plus riche en glucides, enveloppez dans un roti ou servez avec du naan."],2)

add(7989211,"Tzatziki","Cette savoureuse trempette est délicieuse servie avec du pain pita réchauffé, des lamelles de poivron et des bâtonnets de céleri.","4","119 g",
["un demi-concombre, pelé et râpé","250 g de yaourt grec à 0 % de matières grasses","2 gousses d'ail, écrasées","1 c. à soupe d'huile d'olive","1 c. à soupe de menthe fraîche hachée","poivre noir fraîchement moulu"],
["Placez le concombre dans un torchon propre et pressez jusqu'à ce que la plus grande partie du liquide soit éliminée.","Mélangez avec les autres ingrédients et servez."],
["Le tzatziki est une excellente sauce pour accompagner du poisson grillé, de la viande ou des plats principaux végétariens."],0)

add(7990195,"Soupe de carottes à la coriandre","Cette soupe copieuse et nourrissante vous réconfortera à coup sûr et vous réchauffera. Cette recette a été sélectionnée en partenariat avec Slimming World.","4","563 g",
["1 gros oignon, haché","80 g de courge butternut pelée, hachée","750 g de carottes, hachées","1 litre de bouillon de légumes chaud à teneur réduite en sel","1 c. à café de coriandre moulue","60 g de haricots cannellini en boîte, égouttés et rincés","½ petit bouquet de coriandre fraîche, finement hachée","3 c. à soupe de quark nature"],
["Mettez l'oignon dans une grande casserole antiadhésive avec la courge, les carottes, le bouillon et la coriandre moulue. Portez à ébullition à feu vif, baissez le feu et laissez mijoter 20 minutes, ou jusqu'à ce que les légumes soient très tendres.","Ajoutez les haricots à la soupe et laissez mijoter 2 minutes. Retirez du feu, laissez refroidir légèrement, puis versez dans un robot ou un mixeur et mixez jusqu'à obtenir une texture lisse.","Incorporez la coriandre et le quark, assaisonnez de poivre si vous le souhaitez, et servez."],
[],3)

add(7995017,"Soupe de citrouille effrayante et pain « pierre tombale »","Soupe de citrouille avec toile d'araignée au yaourt et toasts décorés.","4","430 g",
["2 c. à café d'huile de colza","1 gros oignon, haché","1 petite courge butternut (500 g de poids préparé), pelée et coupée en cubes","1 cube de bouillon de légumes à très faible teneur en sel dans 800 ml d'eau bouillante","75 g de lentilles corail","1 boîte de 400 g de tomates","1 c. à soupe de concentré de tomate","1 bonne pincée de poivre","4 tranches de pain complet"],
["Mettez l'oignon dans la casserole avec 1 cuillère à café d'huile. Faites cuire doucement jusqu'à ce que l'oignon commence à dorer.","Ajoutez maintenant la courge, le bouillon, les lentilles, les tomates et le concentré de tomate, et laissez mijoter 15 à 20 minutes.","Ajoutez une bonne pincée de poivre, puis mixez avec un mixeur plongeant ou dans un robot jusqu'à obtenir une texture lisse.","Pendant ce temps, découpez le pain en forme de pierre tombale, placez le pochoir en position et vaporisez sur le pain grillé.","Versez la soupe dans des bols. Mettez le yaourt dans une poche à douille avec une très petite douille et tracez une fine spirale sur la soupe. Prenez une brochette ou une baguette chinoise et tracez-la à travers la spirale du centre vers l'extérieur pour créer une toile d'araignée. Ajoutez le toast et servez."],
["Vous pouvez utiliser une alternative non laitière à base d'avoine ou de soja à la place du yaourt pour une version sans lactose.","La suggestion de présentation ci-dessus comprend du pain complet, mais pas le yaourt. Pour une option plus pauvre en glucides, servez sans pain."],4)

add(7997094,"Poulet jerk","Un plat jamaïcain classique, populaire dans toute la Caraïbe. Le jerk désigne l'assaisonnement épicé dans lequel le poulet est mariné. Peut être cuit au four ou au barbecue.","4","219 g",
["4 oignons nouveaux, hachés","2 piments Scotch Bonnet, finement hachés","1 c. à café de poivre noir fraîchement moulu","une demi-c. à café de cannelle","une demi-c. à café de noix de muscade moulue","1 c. à café de piment de la Jamaïque moulu","2 c. à café de cassonade brune","2 gousses d'ail, écrasées","3 cm de racine de gingembre frais, râpée","1 c. à soupe de feuilles de thym frais ou 1 c. à café de thym séché","1 c. à soupe de sauce soja à teneur réduite en sel *","zeste râpé et jus de 1 lime","jus de 1 orange","1 c. à soupe de vinaigre de vin","4 pilons de poulet et 4 hauts de cuisse de poulet (1 kilo), excès de peau retiré"],
["Pour préparer l'assaisonnement jerk, mettez tous les ingrédients sauf le poulet dans un blender et mixez jusqu'à obtenir une pâte. Vous pouvez aussi utiliser un mixeur plongeant ou un pilon et un mortier.","Piquez le poulet avec un couteau pointu et placez-le dans un sac alimentaire avec l'assaisonnement jerk. Laissez mariner au moins six heures, ou toute une nuit si possible.","Préchauffez le four à 190 °C/thermostat 5. Étalez le poulet mariné sur une plaque de cuisson et faites cuire 25 minutes, jusqu'à ce qu'il soit croustillant et doré et commence à noircir sur les bords.","Sinon, pour une cuisson au barbecue, couvrez de papier aluminium et faites cuire au four 20 minutes. Passez ensuite au barbecue pendant encore 10 minutes."],
["*La recette contient de la sauce soja qui peut contenir du gluten. Si vous suivez un régime sans gluten, vérifiez l'étiquette pour trouver une version sans gluten.","Essayez de servir avec du riz aux pois et beaucoup de salade.","Vous pouvez utiliser cette marinade sur du porc, des filets de poisson, de grosses crevettes ou des cubes de tofu.","Vous pouvez mettre le poulet et l'assaisonnement jerk dans un sac alimentaire, bien mélanger et congeler pour une utilisation ultérieure.","Instructions de congélation : se congèle une fois cuit. Décongelez au réfrigérateur et réchauffez jusqu'à ce que le plat soit bien chaud à cœur."],0)

json.dump(R,open('/mnt/c/WSL/davita/translations/out_yfr5.json','w'),ensure_ascii=False,indent=1)
print(len(R))
