import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xid9')
from h import *
P=[]
P.append(R(3576,"Saus Enchilada","Ahli gizi DaVita, Kara dan Maria dari Arizona, menyusun menu regional berisi makanan favorit dari wilayah Barat Daya Amerika. Resep Saus Enchilada yang ramah bagi pasien cuci darah ini menggunakan bahan-bahan yang melimpah di Barat Daya Amerika.","6 (resep menghasilkan 1-1/2 cangkir saus)","1/4 cangkir",
["2 sendok makan minyak kanola","14 ons tomat potong dadu kalengan rendah natrium","1/8 sendok teh bubuk bawang putih","1 sendok teh bubuk cabai","1/4 sendok teh garam","1 sendok makan tepung maizena"],
["Tiriskan tomat.","Panaskan minyak di wajan. Masukkan tomat potong dadu, bubuk bawang putih, 1 sendok teh bubuk cabai, dan garam, lalu aduk.","Dalam cangkir kecil, campurkan tepung maizena dengan 1/2 cangkir air. Aduk hingga halus.","Tambahkan campuran tepung maizena ke dalam tomat panas sambil diaduk hingga tercampur rata.","Kecilkan api dan masak dengan api kecil hingga mengental.","Cicipi dan tambahkan bubuk cabai jika diinginkan."],
["Siapkan saus 2 sampai 3 hari sebelumnya dan simpan di lemari es. Gunakan untuk membuat hidangan enchilada dengan cepat di kemudian hari dalam minggu itu.","Saat menyantap hidangan yang dibuat dengan saus ini, hitung sebagai pengganti 1 porsi sayuran agar kalium tetap seimbang jika Anda menjalani diet rendah kalium.","Saus enchilada kalengan biasa mengandung 150 sampai 400 mg natrium per 1/4 cangkir."],
["1 sayuran, kalium sedang","1 lemak"]))
P.append(R(3577,"Sandwich Sarapan Telur dan Sosis","Bagi penderita penyakit ginjal yang menjalani diet, Anda tidak perlu membeli sarapan di drive-thru dan tetap bisa menikmati semua cita rasanya dengan membuat sarapan sendiri di rumah. Resep Sandwich Sarapan Telur dan Sosis dari ahli gizi ginjal DaVita, Sara dari California, ini memungkinkan Anda menikmati sarapan yang mengenyangkan dan lezat dengan kandungan natrium, kalium, dan fosfor yang lebih rendah daripada yang Anda dapatkan di restoran.","1","1 sandwich",
["semprotan masak antilengket","1/4 cangkir pengganti telur cair rendah kolesterol","1 muffin Inggris","1 patty sosis kalkun","1 sendok makan keju cheddar tajam alami parut"],
["Dalam wajan kecil yang sudah disemprot semprotan masak antilengket, tuangkan pengganti telur dan masak dengan api sedang-kecil. Ketika telur tampak hampir matang, balik dengan spatula dan masak 30 detik lagi.","Panggang muffin Inggris.","Letakkan patty sosis kalkun di piring, tutup dengan tisu dapur, dan panaskan dalam microwave selama 1 menit atau sesuai waktu yang dianjurkan pada kemasan.","Susun telur matang di atas muffin Inggris (lipat agar muat di muffin). Tambahkan patty sosis di atasnya, lalu keju cheddar tajam, dan tutup dengan separuh muffin yang tersisa."],
["Sebagai perbandingan, sandwich sosis dan telur dari restoran cepat saji mengandung 800 sampai 1.135 mg natrium, 280 mg fosfor, 30 gram lemak, dan 255 mg kolesterol.","Mengganti telur dengan produk telur rendah kolesterol membantu mengurangi fosfor, kolesterol, dan lemak.","Ukuran muffin Inggris: 2 ons; ukuran patty sosis kalkun: 1 ons. Pilih sosis dengan kandungan natrium paling rendah."],
["2 daging","2 pati"]))
P.append(R(3579,"Kalkun Slow Cooker dengan Wortel & Saus Cranberry","Hidangan kalkun yang lezat tidak harus hanya disajikan saat Thanksgiving. Dada Kalkun Slow Cooker dengan Wortel dan Saus Cranberry dibuat khusus untuk DaVita.com oleh ahli gizi ginjal DaVita, Sara dari California, untuk menghadirkan resep lezat yang ramah ginjal dan mudah dibuat.","6","2-1/2 ons kalkun, 1/3 cangkir sayuran, 1/4 cangkir saus cranberry",
["1/4 cangkir bawang bombai","1/3 cangkir seledri","2 cangkir wortel","18 ons dada kalkun tanpa tulang dan tanpa kulit","1 sendok teh bumbu unggas","1/2 sendok teh butiran kaldu ayam","1 cangkir saus cranberry"],
["Potong dadu bawang bombai. Iris seledri dan wortel.","Letakkan dada kalkun dalam slow cooker dan taburi dengan bumbu unggas dan butiran kaldu.","Sendokkan saus cranberry di atasnya; tambahkan sayuran.","Tutup slow cooker dengan penutupnya, atur ke suhu tinggi, dan masak selama 4 jam.","Angkat dada kalkun dan iris. Sajikan bersama sayuran dan saus cranberry."],
["Dada kalkun utuh dapat digunakan sebagai pengganti kalkun tanpa tulang.","Semprot panci slow cooker dengan semprotan masak antilengket atau gunakan pelapis slow cooker agar lebih mudah dibersihkan.","Bawang bombai dan wortel beku dapat digunakan sebagai pengganti sayuran segar.","Sedikit sekali kaldu biasa sudah menambah cita rasa. Pengaturan porsi membantu menjaga kandungan natrium tetap dalam batas diet rendah natrium.","Sajikan dengan mi, roti gulung, margarin, dan salad buah."],
["2 daging","1 sayuran, kalium sedang","1 kalori tinggi"]))
P.append(R(3582,"Adonan Pancake atau Wafel Siap Simpan untuk Banyak Orang","Ahli gizi DaVita, Mary, membagikan versi ramah ginjal dari adonan sarapan ini, Adonan Pancake atau Wafel Siap Simpan untuk Banyak Orang. Serunya resep ini adalah Anda bisa menyenangkan semua orang, mulai dari pencinta pancake hingga penggemar wafel.","20","satu pancake 4\" atau setengah wafel 4\" x 4\"",
["4-1/2 cangkir tepung terigu serbaguna","1/4 cangkir gula","1/2 sendok teh garam","1 bungkus ragi kering aktif","4 cangkir susu rendah lemak 1%","1/2 cangkir mentega","6 butir telur besar, dikocok"],
["Sendokkan tepung perlahan ke dalam cangkir takar dan ratakan.","Dalam mangkuk besar, campurkan tepung, gula, garam, dan ragi.","Dalam panci sedang, panaskan susu dan mentega hingga hangat 120-140°F.","Tambahkan cairan hangat dan telur ke campuran tepung, lalu kocok dengan mixer pada kecepatan sedang hingga halus.","Tutup dan simpan di lemari es minimal 1 jam atau hingga 4 hari, dengan menambahkan 2 sendok makan gula setelah hari kedua.","Untuk pancake, olesi sedikit wajan datar atau wajan biasa dengan minyak, panaskan, lalu tuangkan 1/4 cangkir adonan untuk setiap pancake. Balik pancake saat tepinya tampak kering dan gelembung mulai pecah di permukaan.","Untuk wafel, panggang 1/2 cangkir adonan dalam cetakan wafel panas hingga uap berhenti keluar."],
["Ragi dalam resep ini menggantikan baking powder, bahan yang tinggi fosfor dan tinggi natrium."],
["1/2 daging","1-1/2 pati","1 lemak"]))
P.append(R(3584,"Orak-arik Telur Meriah","Paprika warna-warni membuat resep Orak-arik Telur Meriah yang ramah ginjal ini istimewa untuk pagi hari apa pun.","8","1/2 cangkir",
["3-1/2 cangkir pengganti telur cair rendah kolesterol","1/2 cangkir bawang bombai","1/2 cangkir paprika merah","1/2 cangkir paprika hijau","1 sendok teh lada hitam","2 sendok makan margarin bebas lemak trans"],
["Cincang halus bawang bombai dan paprika.","Campurkan produk telur, bawang bombai, paprika, dan lada hitam dalam mangkuk.","Lelehkan margarin di wajan. Masukkan campuran telur dan masak hingga telur matang. Aduk sesekali agar tidak lengket.","Sajikan hangat atau simpan di penghangat hingga siap disajikan."],
["Pengganti telur rendah kolesterol tersedia dalam bentuk dingin atau beku. Pilihan terbaik bagi pasien ginjal adalah merek dengan natrium terendah tanpa tambahan produk kedelai atau susu atau zat aditif fosfat."],
["1-1/2 daging","1/2 sayuran, kalium rendah"]))
P.append(R(3586,"Ayam Panggang Lemon-Rosemary","Ayam Panggang Lemon-Rosemary mungkin bernama mewah, dan rasanya memang mewah, tetapi waktu persiapan dan memasaknya singkat dan mudah untuk resep ramah ginjal ini.","4","1 potong ayam, sekitar 3 ons",
["1 pon paha ayam, dengan tulang, dengan kulit","1/4 cangkir minyak kanola","1 cangkir air lemon","1/2 sendok teh lada hitam","1 sendok teh bubuk bawang putih","1 sendok makan rosemary kering"],
["Bilas ayam di bawah air dingin, keringkan dengan tisu dapur, lalu letakkan potongan ayam dengan sisi kulit menghadap ke bawah dalam loyang 2 quart, mangkuk Pyrex®, atau peralatan masak tahan oven lainnya.","Tuangkan minyak dan air lemon ke dalam wadah 16 ons (dengan penutup rapat) lalu kocok hingga tercampur.","Campurkan lada hitam, bubuk bawang putih, dan serpihan rosemary, sisihkan dua sendok teh untuk digunakan nanti. Masukkan sisa bumbu ke campuran lemon/minyak, lalu kocok hingga tercampur rata.","Taburkan satu sendok teh bumbu yang disisihkan di atas ayam, tutup, dan marinasi semalaman atau minimal 8 jam.","Panaskan oven terlebih dahulu hingga 350° F. Buka penutup ayam dan panggang dalam oven selama 25 menit. (Biarkan ayam tetap dalam marinade.)","Keluarkan dari oven dan balik ayam sehingga sisi kulit menghadap ke atas. Taburi dengan satu sendok teh sisa campuran bumbu.","Panggang 25 sampai 30 menit lagi atau hingga potongan ayam tidak lagi merah muda di bagian dalam.","Tuangkan sebagian cairan yang tersisa di atas ayam saat disajikan."],
["Gunakan dada ayam atau kombinasi dada dan paha ayam jika diinginkan.","Bumbui dengan bubuk bawang putih dan rosemary sesuai selera Anda. Takarannya hanya saran.","Gunakan 1 sendok teh rosemary segar sebagai pengganti rosemary kering jika tersedia.","Semakin lama dimarinasi, semakin sedap rasanya. Marinasi minimal 8 jam, tetapi untuk rasa yang maksimal, semalaman.","Jika Anda menjalani diet pembatasan protein, kurangi porsi sesuai rencana makan Anda."],
["3 daging","1/2 buah, kalium rendah","2 lemak"]))
P.append(R(3587,"Labu Spageti Parmigiano","Bayangkan hidangan mirip pasta tetapi tanpa karbohidrat, itulah Labu Spageti Parmigiano dari ahli gizi ginjal DaVita, Melissa. Mudah dibuat dan dapat disajikan sendiri atau sebagai pengganti pasta dengan saus pasta ramah ginjal favorit Anda di atasnya.","8","3/4 cangkir",
["1 labu spageti sedang, sekitar 5 pon","4 sendok makan minyak zaitun","2 siung bawang putih","1 bawang merah sedang","1/4 sendok teh lada hitam","1/8 sendok teh serpihan cabai merah","3/4 cangkir keju Parmigiano-Reggiano parut"],
["Panaskan oven terlebih dahulu hingga 375º F.","Tusuk labu spageti dengan garpu. Panaskan dalam microwave selama 5 menit hingga lunak. Potong labu spageti menjadi dua dan buang biji serta selaputnya.","Olesi labu dengan minyak zaitun. Letakkan labu dengan sisi potongan menghadap ke bawah di atas loyang yang diolesi sedikit minyak lalu panggang selama 50 menit. Keluarkan labu dari oven dan sisihkan hingga cukup dingin untuk dipegang.","Cincang halus bawang putih dan bawang merah. Parut halus keju Parmigiano-Reggiano.","Panaskan 2 sendok makan minyak zaitun di wajan dengan api sedang. Masukkan bawang putih dan bawang merah; masak sambil diaduk hingga harum, 2-3 menit. Matikan api.","Gunakan sendok besar untuk mengeruk daging labu yang berserat ke dalam wajan. Tambahkan keju Parmesan, lada hitam, dan serpihan cabai merah; aduk hingga tercampur.","Pindahkan ke piring saji dan sajikan hangat."],
["Labu spageti adalah satu-satunya labu musim dingin dengan kalium lebih rendah, dan merupakan pengganti pasta rendah karbohidrat yang lezat. Beratnya berkisar antara 4 sampai 8 pon.","Labu 4 pon menghasilkan 5 cangkir","Labu 5 pon menghasilkan 6-1/4 cangkir","Labu 6 pon menghasilkan 7-1/2 cangkir","Labu 7 pon menghasilkan 8-3/4 cangkir","Labu 8 pon menghasilkan 10 cangkir","Panaskan labu musim dingin selama 4-5 menit dalam microwave agar lebih mudah dipotong sebelum dipanggang. Dinginkan selama 10 sampai 15 menit sebelum dipotong.","Untuk versi dengan fosfor dan natrium lebih rendah, kurangi keju menjadi 1/2 cangkir. Alih-alih dicampurkan ke labu saat persiapan, taburkan 1 sendok makan di atas setiap porsi. Natrium berkurang menjadi 142 mg dan fosfor menjadi 79 mg.","Saran penyajian: Beri topping Saus Tomat Paprika Merah Panggang atau saus ramah ginjal favorit Anda."],
["1 sayuran, kalium sedang","1-1/2 lemak"]))
P.append(R(3592,"Gulung Kubis dengan Kalkun","Ahli gizi ginjal DaVita, Wendy dari Ohio, membagikan resep ramah ginjalnya untuk Gulung Kubis dengan Kalkun. Cobalah hidangan berbungkus kubis ini dan sajikan sesuatu yang baru untuk keluarga Anda.","6","2 gulung kubis",
["12 lembar daun kubis","1 pon kalkun giling","1/2 cangkir beras mentah","1/4 cangkir bawang bombai, dicincang halus","2 butir telur","1/2 sendok teh lada hitam (dibagi)","1/4 sendok teh basil kering","2 sendok teh peterseli kering","1-1/4 cangkir air (dibagi)","3 ons pasta tomat","2 sendok makan air lemon","1 sendok makan gula"],
["Lepaskan dengan hati-hati 12 lembar daun kubis dari satu kubis utuh dan cuci.","Didihkan air dalam panci besar. Masukkan daun kubis dan rebus selama 2 menit hingga lunak. Tiriskan dan sisihkan daunnya.","Dalam mangkuk besar, campurkan kalkun giling, beras, bawang bombai, telur, 1/4 sendok teh lada, basil, peterseli, dan 1/4 cangkir air.","Letakkan 1/4 cangkir adonan kalkun di atas daun kubis dan lipat sisi-sisi daun menutupi adonan kalkun.","Susun gulungan berdekatan dengan sisi lipatan menghadap ke bawah dalam loyang.","Campurkan pasta tomat, air lemon, 1 cangkir air, 1/4 sendok teh lada, dan gula untuk membuat saus. Siramkan saus di atas gulung kubis. Tutup dan panggang pada suhu 375° F selama 1-1/2 jam. Buka penutup dan panggang 30 menit lagi."],
["Gulung kubis dapat dimasak dalam slow cooker dengan pengaturan rendah selama 6 sampai 8 jam sebagai ganti dipanggang dalam oven.","Jika Anda menjalani diet rendah kalium, perlu diketahui bahwa 2 gulung kubis setara dengan 2 porsi sayuran. Mengonsumsi porsi tambahan buah atau sayuran dapat menyebabkan kadar kalium tinggi."],
["2 daging","2 sayuran, kalium sedang","1 kalori tinggi"]))
P.append(R(3593,"Roti Panggang Alpukat dengan Telur","Buatlah roti panggang alpukat dan telur ini untuk sarapan atau brunch Anda. Resep DaVita lezat, ramah ginjal, dan disumbangkan oleh ahli gizi DaVita.","2","1 roti panggang",
["2 lembar roti gandum utuh","1 sendok makan peterseli","1/2 alpukat Hass sedang","1 sendok makan air jeruk nipis","1/8 sendok teh garam","2 butir telur besar","2 sendok makan keju feta hancur","1/8 sendok teh lada hitam bubuk"],
["Panggang irisan roti. Cincang peterseli dan sisihkan.","Keluarkan setengah alpukat dari kulitnya dan lumatkan dengan garpu. Campurkan dengan air jeruk nipis dan garam. Oleskan campuran ke setiap potong roti panggang.","Semprot wajan dengan semprotan masak dan panaskan dengan api sedang. Pecahkan telur ke dalam wajan dan masak hingga tingkat kematangan yang diinginkan.","Geser telur dari wajan ke atas alpukat pada setiap roti panggang. Taburkan di atas setiap telur 1 sendok makan keju feta, peterseli cincang, dan lada hitam bubuk."],
["Alpukat tinggi kalium. Dengan membatasi jumlahnya hingga 1/4 alpukat sedang (sekitar 1/4 cangkir), Anda masih bisa memasukkannya ke dalam diet ginjal ketika kadar kalium terkendali dengan baik. Tanyakan kepada ahli gizi Anda untuk panduan yang sesuai dengan kondisi Anda."],
["1 daging","1 pati","1 lemak"]))
P.append(R(3594,"Ayam Lemon-Bawang Putih dengan Quinoa dan Orzo","Ahli gizi ginjal DaVita, Dara dari Idaho, selalu memiliki hasrat terhadap kebugaran dan makanan. Dara memahami bahwa membuat makanan sehat saja tidak cukup, makanan itu juga harus lezat. Resepnya, Ayam Lemon-Bawang Putih dengan Quinoa dan Orzo, menyediakan protein tanpa lemak yang baik dan cita rasa lemon dan bawang putih yang luar biasa.","4","1/4 resep",
["2 ons pasta orzo, mentah","2 ons quinoa, mentah","2 siung bawang putih","1/2 cangkir bawang bombai","1 cangkir paprika merah","1/2 cangkir jamur segar","12 ons dada ayam tanpa tulang dan tanpa kulit","2 buah lemon","1-1/2 sendok makan campuran bumbu herba tanpa garam","2-1/2 sendok makan minyak zaitun"],
["Masak orzo dan quinoa sesuai petunjuk pada kemasan lalu sisihkan.","Cincang halus bawang putih; potong dadu bawang bombai dan paprika; iris jamur.","Potong ayam menjadi potongan 1″. Masukkan ayam ke dalam kantong plastik berzipper bersama air dari 1 lemon dan 1 sendok makan campuran bumbu herba tanpa garam. Aduk rata dan simpan di lemari es.","Panaskan 1/2 sendok makan minyak zaitun dalam wajan antilengket sedang dengan api sedang. Masukkan bawang putih dan bawang bombai. Tumis hingga bawang bombai bening (sekitar 3 sampai 5 menit). Tambahkan paprika dan jamur. Masak sambil sesekali diaduk hingga paprika baru empuk (sekitar 5 sampai 7 menit). Angkat dari api dan sisihkan.","Panaskan 1 sendok makan minyak zaitun dalam wajan antilengket besar dengan api sedang. Masukkan ayam dan masak hingga tidak lagi merah muda di bagian dalam (sekitar 7 menit).","Kocok bersama sisa 1 sendok makan minyak zaitun, air dari 1 lemon, dan 1/2 sendok makan campuran bumbu herba tanpa garam, lalu tambahkan ke ayam.","Masukkan orzo, quinoa, dan sayuran tumis yang sudah matang, lalu masak 3 sampai 5 menit lagi hingga ayam benar-benar matang dan semua bahan panas merata.","Bagi rata menjadi 4 porsi."],
["Dua ons pasta orzo kering dan dua ons quinoa kering masing-masing menghasilkan 1 cangkir setelah dimasak."],
["3 daging","1-1/2 pati","1 sayuran, kalium sedang"]))
P.append(R(3596,"Roti Zucchini","Ahli gizi ginjal DaVita, Eileen dari California, memiliki resep yang sempurna: Roti Zucchini. Selain ramah ginjal dan lezat, satu loyang ekstra dapat dibekukan dengan baik sehingga Anda bisa menikmatinya dua kali lipat.","24","satu irisan 3/4″",
["3 cangkir tepung terigu putih serbaguna","3/4 cangkir gula atau pemanis butiran Splenda®","1-1/2 sendok teh bumbu pumpkin pie","1-1/2 sendok teh soda kue","1 sendok teh garam","4 butir telur","2 cangkir zucchini parut","3/4 cangkir madu","1/3 cangkir minyak","1/3 cangkir saus apel tanpa gula","2 sendok makan air lemon","1 sendok teh ekstrak vanila"],
["Panaskan oven terlebih dahulu hingga 325° F.","Olesi dua loyang roti 8-1/2″ x 4-1/2″ dengan minyak.","Dalam mangkuk besar, campurkan tepung, gula, bumbu pumpkin pie, soda kue, dan garam.","Dalam mangkuk sedang, kocok telur sebentar. Masukkan zucchini, madu, minyak, saus apel, air lemon, dan vanila, lalu aduk.","Aduk campuran cair ke dalam campuran tepung hanya sampai tepung basah merata. Ratakan dalam loyang.","Panggang 1 jam atau hingga tusuk gigi keluar bersih.","Dinginkan dalam loyang di atas rak kawat selama 10 menit, lalu keluarkan dari loyang.","Potong setiap roti menjadi 12 irisan."],
["Tingkatkan kandungan protein menjadi 4 gram dengan menambahkan 7 sendok makan bubuk protein favorit Anda ke bahan kering.","Jika Splenda® digunakan sebagai pengganti gula, karbohidrat berkurang menjadi 22 gram dan 1-1/2 pilihan karbohidrat.","Roti zucchini dapat dibekukan dengan baik. Bungkus dengan plastik pembungkus, lalu masukkan ke dalam kantong pembeku.","Jika diinginkan, gunakan 2/3 cangkir saus apel dan hilangkan minyak, atau gunakan 2/3 cangkir minyak dan hilangkan saus apel."],
["1 pati","1/2 kalori tinggi","1/2 lemak"]))
P.append(R(3597,"Campuran Pelapis Daging Dasar","Buatlah remah roti buatan sendiri dengan resep Campuran Pelapis Daging Dasar yang ramah ginjal ini untuk memastikan Anda memiliki cara rendah natrium untuk menambah cita rasa dan kerenyahan pada daging sapi, ayam, dan ikan. Lapisi daging lalu goreng atau panggang. Cobalah menambahkan rempah yang berbeda ke Campuran Pelapis Daging Dasar sesuai jenis daging yang Anda gunakan untuk meningkatkan cita rasa.","12","1-1/2 sendok makan untuk 1 potong daging",
["1 cangkir remah roti kering tanpa bumbu","1/4 sendok teh lada hitam","1/2 sendok teh bubuk bawang putih","1/2 sendok teh basil","1/2 sendok teh daun seledri kering","1/2 sendok teh paprika"],
["Haluskan bahan-bahan dalam food processor atau blender. Simpan hingga siap digunakan.","Saat siap digunakan, celupkan daging segar ke dalam margarin atau minyak, lalu lapisi dengan campuran pelapis, satu potong demi satu.","Panggang daging dalam oven atau goreng dalam wajan."],
["Buat remah roti kering buatan sendiri dengan memanggang roti dalam oven hingga kering dan renyah. Haluskan dalam food processor atau blender untuk membuat remah.","Campuran ini awet disimpan di freezer. Buat lebih banyak untuk digunakan nanti.","Cobalah variasi berikut untuk cita rasa tambahan:","Daging sapi atau daging anak sapi: tambahkan 1/2 sendok teh marjoram atau oregano","Ayam: tambahkan 1/2 sendok teh thyme dan ½ sendok teh sage"],
["1/2 pati"]))
P.append(R(3599,"Pai Kalkun","Meski ada anggota keluarga yang menjalani diet ginjal, mereka tetap dapat menikmati semua kelezatan panggang dari Pai Kalkun yang menggugah selera ini, berkat ahli gizi ginjal DaVita, Mary Beth dari Louisiana.","8","1/8 pai",
["1 cangkir kentang","1 cangkir bawang bombai","1/2 cangkir seledri","2 cangkir kalkun matang","1 cangkir mentega ditambah 1 sendok makan mentega","2-3/4 cangkir tepung terigu serbaguna","1/4 sendok teh lada hitam","1/4 sendok teh sage bubuk","1/4 sendok teh thyme","3/4 cangkir kaldu ayam natrium rendah","3/4 cangkir susu rendah lemak 1%","10 ons kacang polong dan wortel beku","6 sendok makan air es"],
["Kupas dan potong dadu kentang. Cincang bawang bombai dan seledri. Potong kalkun matang menjadi kubus.","Rebus kentang dua kali untuk mengurangi kalium (lihat petunjuk di tips bermanfaat di bawah).","Panaskan oven terlebih dahulu hingga 425° F.","Lelehkan 1 sendok makan mentega dalam panci besar dan tumis bawang bombai hingga empuk.","Tambahkan seledri dan masak semenit lagi.","Campurkan 2 sendok makan tepung, lada, sage, dan thyme, lalu masak dengan api kecil selama 1 menit.","Angkat dari api. Masukkan kaldu ayam dan susu, aduk hingga tercampur. Didihkan dan masak dengan api kecil selama 1 menit sambil terus diaduk.","Masukkan kalkun, kentang yang sudah direbus dua kali, serta kacang polong dan wortel. Sisihkan hingga dingin.","Dalam mangkuk terpisah, potong 1 cangkir mentega ke dalam sisa tepung menggunakan pastry blender. Campuran harus membentuk butiran seukuran kacang polong.","Mulailah menambahkan air es, satu sendok makan setiap kali, aduk rata setiap kali, hingga adonan membentuk bola.","Bagi adonan menjadi dua dan giling satu bagian dengan rolling pin dan tambahan tepung hingga adonan lentur dan tidak lagi lengket. Pastikan adonan lebih besar daripada diameter loyang pai 9 inci.","Letakkan adonan dalam loyang pai, ratakan dengan jari agar memenuhi loyang, lalu tuangkan campuran kalkun di atasnya.","Giling bagian adonan kedua hingga ukuran serupa dan letakkan di atas isian pai kalkun. Rekatkan tepi pai.","Dengan pisau tajam, buat empat sampai lima sayatan sepanjang satu inci di atas kulit pai sebagai lubang uap.","Letakkan pai di atas loyang datar dan panggang selama 35-40 menit atau hingga kecokelatan."],
["Untuk mengurangi kalium pada kentang, gunakan metode Rebus Dua Kali. Kupas dan potong dadu kentang menjadi potongan 1”. Rebus dalam panci besar berisi air selama 10 menit. Buang airnya dan tambahkan air baru ke dalam panci. Didihkan dan masak hingga kentang empuk.","Gunakan kulit pai siap pakai dari lemari es jika diinginkan. Pilih merek dengan natrium terendah.","Untuk versi lebih rendah lemak dan kalori, buat setengah adonan dan gunakan untuk menutupi isian pai sebagai ganti versi dengan adonan ganda."],
["1-1/2 daging","2 pati","1 sayuran, kalium sedang","3 lemak"]))
P.append(R(3600,"Salad Tabbouleh","Salad Tabbouleh adalah hidangan populer Timur Tengah yang memadukan bulgur, daun bawang, peterseli segar, mint, minyak zaitun, dan air lemon. Kombinasi ramah ginjal ini awet disimpan di lemari es, jadi buatlah satu porsi besar untuk disajikan sepanjang minggu.","8","3/4 cangkir",
["1/2 cangkir bulgur kering","1 tomat sedang","1 mentimun sedang","1 ikat daun bawang","2 ikat peterseli","1/2 ikat mint","1/2 cangkir minyak zaitun","3 buah lemon","1/2 sendok teh garam","1/2 sendok teh lada hitam"],
["Cuci bulgur. Tiriskan dan letakkan dalam mangkuk besar. Tuangkan 1/2 cangkir air mendidih di atas bulgur, tutup mangkuk, dan diamkan selama 30 menit. Buang kelebihan cairan (jika ada).","Potong dadu tomat; cincang mentimun yang sudah dikupas, daun bawang, peterseli, dan mint.","Tambahkan sayuran ke bulgur dan aduk rata.","Peras 3 lemon. Tambahkan minyak zaitun, air lemon, garam, dan lada ke campuran bulgur.","Diamkan salad pada suhu ruang selama sekitar satu jam agar menyerap air lemon dan minyak zaitun sebelum disajikan. Simpan sisanya di lemari es dan sajikan selama minggu itu."],
["Santap Salad Tabbouleh dengan daun selada, daun anggur muda, atau dengan garpu.","Bulgur adalah biji gandum yang dipecahkan (juga dikenal sebagai gandum pecah). Tersedia dalam gilingan dari halus hingga sangat kasar. Gunakan bulgur gilingan halus atau sedang untuk resep ini.","Satu ikat peterseli, daun bawang, atau mint menghasilkan sekitar 1 cangkir cincang."],
["1/2 pati","1-1/2 sayuran, kalium rendah","2-1/2 lemak"]))
P.append(R(3601,"Air Infus Stroberi Lemon Rosemary","Minuman ini tidak hanya cantik, tetapi juga menyegarkan. Memberi sentuhan cita rasa pada air putih biasa.","5","1 cangkir (8 ons)",
["1/2 cangkir stroberi","1 lemon","1 tangkai rosemary","5 cangkir air dingin (40 ons)","1 sachet stevia"],
["Buang tangkai dan iris stroberi. Iris lemon berbentuk bulat dan lepaskan daun dari tangkai rosemary.","Masukkan semua bahan ke dalam teko. Diamkan di lemari es selama 2 jam. Angkat irisan lemon dan diamkan 2 jam lagi.","Saring stroberi dan rosemary dengan saringan halus lalu simpan di lemari es selama sekitar 3 hari."],
["Anda boleh menambahkan stroberi dan lemon ekstra pada setiap sajian sebagai hiasan jika diinginkan.","Anda boleh tidak menggunakan sachet stevia jika diinginkan.","Jika perlu, sesuaikan ukuran porsi berdasarkan batasan atau target cairan pribadi Anda."],
["tidak ada"]))
save(1,P)
