import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xid9')
from h import *
P=[]
P.append(R(3605,"Pierogi dengan Isian Kubis Manis dan Jamur","Berikut resep modern ramah ginjal untuk Anda coba di rumah — Pierogi dengan Isian Kubis Manis dan Jamur — berkat ahli gizi ginjal DaVita, Christine dari Illinois.","3","4 pangsit",
["2 cangkir kubis","1/2 cangkir bawang bombai","1/2 cangkir jamur","1 cangkir tepung terigu serbaguna","1 butir telur besar","1 sendok makan margarin bebas lemak trans","2 sendok makan air panas","1 sendok makan minyak goreng","1/4 sendok teh lada segar giling"],
["Iris halus kubis, cincang halus bawang bombai, dan iris jamur.","Letakkan tepung dalam mangkuk dan buat lubang di tengahnya. Tambahkan telur, margarin cair, dan air panas.","Aduk dengan pisau adonan hingga terbentuk adonan. Pindahkan ke talenan dan uleni adonan hingga halus. Bulatkan, tutup, dan sisihkan selama satu jam.","Masukkan kubis ke dalam panci sedang, tutup dengan air, dan didihkan. Kecilkan api dan masak dengan api kecil selama 15 sampai 20 menit hingga empuk. Tiriskan kubis dan peras kelebihan cairannya.","Tumis bawang bombai dan jamur cincang dalam satu sendok makan minyak hingga sedikit karamel.","Campurkan kubis dengan bawang bombai dan jamur. Sisihkan hingga dingin.","Setelah dingin, cincang halus campuran sayuran. Tambahkan lada secukupnya dan aduk.","Giling adonan menjadi lingkaran berdiameter 10” sampai 11”. Potong 12 lingkaran dari adonan dengan cetakan kue bulat.","Letakkan satu sendok teh penuh isian di tengah setiap lingkaran adonan. Lipat, regangkan, dan tekan sisi-sisinya hingga menyatu untuk membentuk pangsit berbentuk bulan sabit.","Masukkan pangsit, dua atau tiga sekaligus, ke dalam panci berisi air mendidih. Pierogi akan mengapung ke permukaan saat matang. Angkat dengan sendok berlubang.","Setelah direbus, goreng sebentar pangsit dalam minyak untuk sajian yang renyah, jika diinginkan."],
["Sesuaikan jumlah air panas agar adonan memiliki kekentalan yang tepat. Adonan harus halus dan lentur tetapi tidak lengket.","Untuk menghemat waktu, Anda dapat menggunakan kubis coleslaw yang sudah diiris.","Isian dapat disiapkan sebelumnya dan disimpan di lemari es semalaman, jika perlu.","Resep ini menghasilkan 3 porsi, tetapi dapat dengan mudah digandakan dan pierogi mentah ekstra dibekukan untuk nanti.","Hias dengan siraman margarin cair dan sesendok krim asam."],
["2 pati","2 sayuran, kalium rendah","2 lemak"]))
P.append(R(3609,"Ayam Panggang, Asparagus, dan Jagung","Ayam Panggang, Asparagus, dan Jagung adalah resep terinspirasi koki dari Chef Frank Bonanno. Chef Bonanno dan DaVita bekerja sama menciptakan resep ramah ginjal untuk seri video DaVita Eats: Chef Tips.","2","3-1/2 ons ayam, 1/2 tongkol jagung, 5 batang asparagus",
["8 ons dada ayam tanpa tulang dan tanpa kulit (1 besar atau 2 sedang)","2 sendok makan minyak zaitun","1/2 sendok teh lada hitam kasar","1/2 sendok teh campuran herba-rempah (jinten, paprika, bubuk cabai)","1/4 sendok teh serpihan cabai merah","10 batang asparagus","1 tongkol jagung segar (jagung Colorado jika tersedia)","1/2 lemon","1 sendok makan kucai segar"],
["Bumbui dada ayam dengan satu sendok makan minyak zaitun, lada hitam kasar, campuran herba-rempah, dan serpihan cabai merah. Letakkan ayam di bagian terpanas panggangan dengan sisi berbumbu menghadap ke bawah. Panggang selama 12 menit.","Sementara ayam dimasak, potong asparagus dan letakkan di panggangan. Bumbui dengan lada hitam dan siram dengan 2 sendok teh minyak zaitun. Panggang asparagus selama 5 sampai 7 menit.","Potong tongkol jagung menjadi dua dan siram dengan 1 sendok teh minyak zaitun. Panggang jagung selama 3 sampai 4 menit, hingga sedikit gosong. Setelah jagung diangkat dari panggangan, peras sedikit air lemon dan taburi kucai cincang.","Peras lemon di atas ayam dan asparagus sesuai selera."],
["Air lemon segar dan sedikit minyak zaitun adalah pengganti garam yang sangat baik.","Setelah asparagus mulai gosong, Anda dapat menggesernya ke bagian panggangan yang tidak terkena api langsung.","Masak satu tongkol jagung ekstra untuk makan siang atau makan malam besok.","Sesuaikan porsi ayam dengan rencana makan Anda.","Resep ini ditampilkan dalam seri video DaVita Eats: Chef Tips."],
["3-1/2 daging","1/2 pati","2 sayuran, kalium sedang"]))
P.append(R(3611,"Salad Pasta","Penuh dengan sayuran kaya nutrisi, hidangan ini mendapatkan cita rasanya dari bawang putih dan bawang bombai, serta Mrs. Dash®, yang sepenuhnya bebas garam dan MSG. Salad Pasta ramah ginjal ini juga menggunakan keju parmesan, yang rasanya begitu kuat dan unik sehingga sedikit saja sudah cukup.","12","1 cangkir",
["1 sendok makan bawang bombai","1 cangkir wortel","1 cangkir kuntum brokoli","1 cangkir mentimun","1 cangkir paprika merah","1/2 cangkir cuka putih suling","1/2 cangkir minyak zaitun","1/4 sendok teh bubuk bawang putih","1/4 sendok teh lada hitam","1/2 sendok teh oregano kering","1/2 sendok teh biji seledri","1 kotak 16 ons pasta rotini","1/4 cangkir keju Parmesan parut","1 sendok teh campuran bumbu herba Mrs. Dash®","1/8 sendok teh paprika"],
["Cincang sangat halus bawang bombai, parut wortel, potong kuntum brokoli menjadi potongan kecil, potong dadu mentimun, dan cincang paprika.","Campurkan cuka, minyak, bubuk bawang putih, lada, oregano, biji seledri, dan bawang bombai untuk membuat dressing. Sisihkan.","Masak pasta hingga al dente; jangan terlalu matang.","Tiriskan dan bilas pasta. Aduk dengan dressing secukupnya hingga terlapisi.","Tambahkan keju parmesan ke pasta dan simpan di lemari es minimal 12 jam.","Dua jam sebelum disajikan, tambahkan sisa sayuran, Mrs. Dash®, dan paprika, lalu aduk. Tambahkan lebih banyak dressing jika perlu atau diinginkan.","Simpan di lemari es hingga siap disajikan."],
["Penting untuk menyimpan Salad Pasta di lemari es minimal 12 jam (tetapi tidak lebih dari 24 jam) sebelum disajikan agar bumbu sempat meresap ke dalam pasta.","Jumlah dressing dan paprika yang digunakan dalam resep ini tergantung selera pribadi. Analisis gizi mencakup seluruh dressing."],
["1-1/2 pati","1/2 sayuran, kalium rendah","2 lemak"]))
P.append(R(3612,"Sayap Ayam Pedas Segar","Beberapa kesempatan seolah memanggil sayap ayam, mulai dari acara olahraga hingga menonton TV bersama keluarga, sehingga ahli gizi ginjal DaVita, Lisa dari Massachusetts, bertekad membuat resep ramah ginjal yang akan membuat semua yang mencicipinya mengacungkan jempol untuk Sayap Ayam Pedas Segarnya.","18","2 sayap",
["4 batang daun bawang","2 sendok makan kecap asin rendah natrium","1/4 cangkir madu","1/4 cangkir gula merah","2 sendok makan gula pasir","2 sendok teh bumbu allspice","2 sendok teh thyme kering","2 sendok teh saus pedas","1 sendok teh jahe","1 sendok teh bawang putih cincang","1/4 cangkir cuka sari apel","1/4 cangkir air jeruk nipis","1/4 cangkir jus cranberry","7 pon sayap ayam"],
["Cincang daun bawang.","Campurkan semua bahan kecuali sayap ayam. Sisihkan 3/4 cangkir marinade.","Letakkan sayap ayam dalam wadah atau kantong plastik besar yang dapat ditutup kembali. Tuangkan marinade sisanya di atas sayap.","Tutup dan marinasi di lemari es selama 4 sampai 6 jam.","Panaskan oven terlebih dahulu hingga 350° F.","Letakkan sayap ayam di atas loyang datar dan panggang selama 20 menit.","Sementara itu, dalam panci kecil, didihkan 3/4 cangkir marinade yang disisihkan. Kurangi sepertiganya hingga sedikit mengental menjadi glasir (sekitar 10 menit).","Setelah 20 menit, keluarkan ayam dari oven dan olesi sayap dengan glasir.","Naikkan suhu oven menjadi 400° F dan panggang sayap ayam sekitar 20 menit lagi, hingga matang."],
["Tujuh pon sayap ayam utuh menghasilkan sekitar 36 sayap.","Drumette sayap ayam atau potongan ayam tanpa tulang dapat digunakan sebagai pengganti sayap ayam utuh. Sesuaikan waktu memasak agar tidak terlalu matang."],
["3 daging","1/2 kalori tinggi"]))
P.append(R(3615,"Dip Keju Krim Jeli Mint","Jeli mint hijau adalah rahasia untuk membuat hidangan pembuka ramah ginjal yang sederhana dengan 3 bahan.","10","1-1/2 sendok makan dip dengan 3 keping biskuit",
["8 ons keju krim","1/2 cangkir jeli mint","30 keping biskuit rendah natrium"],
["Buka kemasan keju krim dan letakkan seluruh batangan di atas piring saji.","Oleskan jeli di atas keju krim.","Sajikan dengan biskuit rendah natrium atau roti pipih."],
["Siapkan pada malam sebelumnya atau tepat sebelum disajikan. Sangat mudah dan murah!","Anda dapat menggunakan jeli rasa apa pun, tetapi yang hijau cocok untuk Hari St. Patrick. Cobalah jeli paprika jalapeño untuk sensasi pedas ekstra."],
["1 pati","2 lemak"]))
P.append(R(3618,"Es Nanas-Jeruk Nipis","Es Nanas-Jeruk Nipis adalah sajian beku yang menyegarkan dan cocok untuk diet diabetes, cuci darah, dan PGK non-dialisis. Rendah kalori, natrium, kalium, dan fosfor, serta bebas lemak dan kolesterol. Untuk nutrisi tambahan, Anda dapat mencampurkan bubuk protein ke dalam air jeruk nipis sebelum ditambahkan ke nanas yang telah dihaluskan.","4","1/2 cangkir",
["20 ons nanas potong kalengan","1-1/2 sendok makan konsentrat limeade beku","1-1/2 sendok makan air jeruk nipis segar"],
["Buka kaleng nanas dan tiriskan.","Letakkan potongan nanas di atas loyang datar dalam satu lapisan dan bekukan.","Ketika potongan sudah beku, masukkan ke dalam food processor atau blender.","Tambahkan limeade dan air jeruk nipis. Proses hingga tercampur rata dan bertekstur lembut berongga.","Sajikan segera atau bekukan dalam porsi 1/2 cangkir."],
["Bubuk protein dapat ditambahkan untuk camilan/pencuci mulut yang lebih bergizi. Campurkan ke dalam air jeruk nipis sebelum ditambahkan ke nanas yang telah dihaluskan.","Anda dapat mengganti nanas kalengan dengan 16 ons potongan nanas beku dan melewati langkah 1 dan 2."],
["1 buah, kalium rendah"]))
P.append(R(3623,"Kue Poor Man’s","Cocok untuk rencana makan PGK dan cuci darah, kue ini hanya membutuhkan setengah cangkir kakao untuk memberikan warna pekat dan rasa cokelat. Kathy mengatakan bahwa Michelle memberinya resep ini karena ingin membantu pasien menjaga kadar fosfor tetap terkendali sambil menikmati cokelat mereka.","24","potongan persegi 2” x 2”",
["3 cangkir tepung terigu putih serbaguna","2 cangkir gula","1/2 cangkir kakao","1/2 sendok teh garam","2 sendok teh soda kue","2 sendok makan cuka","3/4 cangkir minyak nabati","2 sendok teh vanila","2 cangkir air dingin"],
["Panaskan oven terlebih dahulu hingga 350°F.","Campurkan 5 bahan pertama dalam loyang 9” x 13” yang tidak diolesi minyak.","Buat 3 lubang pada bahan kering.","Tuangkan 2 sendok makan cuka ke dalam satu lubang.","Tuangkan 3/4 cangkir minyak ke dalam lubang kedua.","Tuangkan 2 sendok teh vanila ke dalam lubang ketiga.","Tambahkan 2 cangkir air dingin dan aduk.","Panggang selama 30 sampai 45 menit hingga tusuk gigi yang ditusukkan ke tengah keluar bersih."],
["Cocok juga untuk cupcake! Tuangkan 1/3 cangkir adonan ke dalam setiap cetakan cupcake ukuran biasa untuk membuat 24 cupcake.","Kakao yang diproses dengan alkali, juga dikenal sebagai cokelat Dutch, memiliki kalium yang jauh lebih tinggi daripada bubuk kakao alami."],
["1 pati","1 kalori tinggi","1 lemak"]))
P.append(R(3630,"Pastie Sirloin Giling","Ahli gizi ginjal DaVita, Shelli dari Michigan, membagikan resep ramah ginjalnya untuk Pastie Sirloin Giling. Pastie yang lezat diperkenalkan di AS oleh para penambang Cornish yang berimigrasi ke Semenanjung Atas Michigan pada tahun 1800-an. Pastie Sirloin Giling Shelli, juga dikenal sebagai Upper Peninsula Pastie, adalah kulit pai yang diisi bahan-bahan mengenyangkan berupa sirloin, sayuran, dan bumbu.","8","1 pastie",
["1/4 cangkir wortel","1/4 cangkir bawang bombai","1 pon sirloin giling","1/4 cangkir jagung beku","1/4 cangkir kacang polong hijau beku","1 sendok makan saus Worcestershire rendah natrium","1 sendok teh lada hitam","1 sendok teh thyme kering","1 kemasan 15 ons (2 lembar) kulit pai gulung dingin mentah","1 putih telur","8 sendok teh saus tomat"],
["Panaskan oven terlebih dahulu hingga 375° F. Biarkan kulit pai pada suhu ruang sesuai petunjuk kemasan.","Potong dadu wortel dan cincang bawang bombai.","Tumis sirloin giling dalam wajan besar dengan api sedang hingga kecokelatan. Tiriskan dan sisihkan.","Letakkan wortel dalam wadah microwave. Tambahkan 1 sendok makan air; tutup dan masak dengan daya tinggi selama 2 menit. Tambahkan jagung dan kacang polong beku; panaskan dalam microwave selama 2 menit. Tiriskan.","Untuk membuat isian, campurkan daging, sayuran, bawang bombai, saus Worcestershire, lada hitam, dan thyme dalam mangkuk.","Di atas permukaan yang ditaburi sedikit tepung, bentangkan kulit pai. Potong setiap kulit pai menjadi empat bagian.","Sendokkan 1/4 cangkir isian ke separuh setiap potongan kulit pai. Basahi sedikit tepi kulit pai dengan sedikit susu atau putih telur.","Lipat separuh kulit pai lainnya menutupi isian. Rekatkan tepi dengan menekannya menggunakan garpu. Buat sayatan di bagian atas pastie. Olesi bagian atas dengan putih telur. Letakkan di atas loyang datar besar yang tidak diolesi minyak.","Panggang selama 15 sampai 20 menit atau hingga kulit berwarna cokelat keemasan. Dinginkan sebentar di atas rak kawat.","Sajikan setiap pastie dengan 1 sendok teh saus tomat."],
["Bungkus dan bekukan pastie ekstra untuk hidangan cepat saji nanti. Panaskan kembali dalam oven atau microwave.","Untuk variasi, gunakan kalkun giling atau ayam sebagai pengganti daging sapi."],
["1-1/2 daging","1-1/2 pati","1/2 sayuran, kalium rendah","2-1/2 lemak"]))
P.append(R(3631,"Saus Tzatziki","Saus tradisional Yunani, Saus Tzatziki adalah tambahan yang menyegarkan untuk burger atau sandwich apa pun.","8","2-1/2 sendok makan",
["1/2 mentimun kecil","1 cangkir yogurt Yunani tawar tanpa lemak","1/2 sendok teh dill kering","1/4 sendok teh bubuk bawang putih","1/4 sendok teh lada hitam","1 sendok makan air lemon"],
["Kupas mentimun lalu parut menggunakan lubang besar parutan kotak.","Buang sebagian cairan dari mentimun parut dengan meremasnya perlahan di atas wastafel.","Dalam mangkuk kecil, campurkan mentimun dengan yogurt Yunani, bubuk bawang putih, dill, lada, dan air lemon untuk membuat saus tzatziki.","Tutup dan simpan di lemari es hingga siap disajikan."],
["Sajikan Saus Tzatziki dengan Gyros Bakso Kalkun dan Burger Buncis."],
["1/2 susu"]))
P.append(R(3636,"Susu Beras Tinggi Protein","Tambahkan protein pada minuman beras favorit Anda untuk membantu memenuhi kebutuhan protein yang lebih tinggi pada diet cuci darah.","2","1/2 cangkir",
["1 cangkir susu beras dingin tanpa pengayaan","2 sendok takar whey protein vanila"],
["Campurkan susu beras dan bubuk protein dalam blender dan blender hingga tercampur rata.","Bagi menjadi 2 porsi. Nikmati satu sekarang dan satu nanti."],
["Simpan porsi ekstra di lemari es hingga siap diminum.","EAS 100% Whey Protein Powder® digunakan dalam analisis resep ini. Tanyakan kepada ahli gizi Anda tentang pilihan bubuk protein lainnya.","Aduk dalam gelas atau kocok dalam shaker sebagai pengganti blender jika diinginkan."],
["2 daging","1 pengganti susu"]))
P.append(R(3637,"Kotlet (Perkedel Daging dan Kentang)","Untuk sajian ramah ginjal, ikuti kami ke Timur Tengah dan cicipi Kotlet, atau perkedel daging dan kentang ala Persia. Resep gurih ini diadaptasi bagi penderita penyakit ginjal yang menjalani diet ginjal oleh Zohreh, ahli gizi DaVita dari California.","5","1 perkedel",
["1 kentang kecil","1 bawang bombai putih sedang","1/4 cangkir bawang merah","3/4 cangkir selada","1 pon daging sapi giling tanpa lemak","1 butir telur besar","1/2 sendok teh kunyit","1/2 sendok teh bubuk bawang putih","1/2 sendok teh lada hitam","1 sendok teh campuran bumbu herba Mrs. Dash® Original","1/4 cangkir minyak nabati","5 lembar roti pita, ukuran 6”","1/4 cangkir daun basil segar"],
["Kupas dan parut kentang, lalu rendam dalam air hangat selama 2 jam untuk mengurangi kalium. Bilas, tiriskan, dan peras kelebihan air menggunakan lap dapur bersih.","Parut bawang bombai putih; potong dadu bawang merah dan iris halus selada.","Campurkan daging sapi giling, bawang bombai putih, kentang parut, telur, kunyit, bubuk bawang putih, lada hitam, dan bumbu Mrs. Dash hingga tercampur rata.","Panaskan minyak dalam wajan berukuran sedang.","Bentuk 5 perkedel (bulat, seukuran telapak tangan Anda) dan goreng dengan api sedang hingga kecokelatan di kedua sisi.","Sajikan setiap perkedel dalam roti pita dengan selada, bawang merah, dan basil segar."],
["Roti Prancis, lavash, roti burger, atau tortilla juga pilihan roti yang baik.","Gunakan lebih sedikit minyak dan wajan antilengket untuk menurunkan kalori dan lemak.","Anda dapat dengan mudah berkreasi dengan Kotlet dengan menambah atau mengganti berbagai bahan. Sajikan dingin atau panas untuk makan siang, makan malam, atau sebagai hidangan pembuka.","Kentang hash brown parut dapat digunakan sebagai pengganti kentang segar. Tidak perlu merendam kentang jika Anda tidak membatasi kalium."],
["2-1/2 daging","2 pati","1 sayuran, kalium sedang"]))
P.append(R(3638,"Eggnog Rempah","Untuk hari raya, cobalah sesuatu yang sedikit berbeda seperti resep Eggnog Rempah yang ramah ginjal.","6","1/2 cangkir",
["2 cangkir krimer half & half","3/4 cangkir produk telur rendah kolesterol","1/4 cangkir gula","2 sendok teh ekstrak rum","1/2 sendok teh bumbu pumpkin pie","1/4 sendok teh pala","6 sendok makan krim kocok"],
["Campurkan krimer half & half, produk telur, gula, ekstrak rum, dan bumbu pumpkin pie dalam blender yang sudah didinginkan dan blender selama 1 sampai 2 menit.","Tuang ke dalam 6 gelas kecil. Beri topping satu sendok makan krim kocok dan taburan pala di atas setiap sajian."],
["Ekstrak rum dapat diganti dengan 2 sendok makan rum, jika diinginkan. Selalu konsultasikan dengan dokter Anda sebelum memasukkan alkohol ke dalam diet Anda.","Ganti gula dengan pemanis rendah kalori untuk menurunkan karbohidrat menjadi 4 gram dan kalori menjadi 125 per porsi.","Periksa bahan half & half dan hindari merek dengan zat aditif fosfat."],
["1 susu","1 lemak"]))
P.append(R(3640,"Ayam dan Selada Air dengan Pasta Gratin","Ayam dan Selada Air dengan Pasta Gratin adalah hidangan satu piring yang lezat dan ramah ginjal, menyediakan sumber protein bersama pasta dan sayuran.","4","1-3/4 cangkir",
["2 cangkir pasta spiral atau cangkang","1 bawang bombai kecil","2 siung bawang putih","1 sendok makan minyak zaitun","1 cangkir ayam matang suwir","1 cangkir selada air segar","1-2/3 cangkir saus béchamel (saus putih)","1/4 sendok teh lada","1/2 cangkir keju Parmesan"],
["Masak pasta sesuai petunjuk kemasan, tanpa garam.","Sementara itu, cincang bawang bombai, bawang putih, dan selada air. Panaskan minyak dalam wajan dan tumis bawang bombai dan bawang putih. Tambahkan ayam suwir dan selada air. Aduk rata dan masak hingga selada air layu.","Setelah pasta matang, tiriskan dan campurkan dengan campuran ayam dan setengah saus béchamel. Aduk rata.","Letakkan campuran ke dalam loyang yang sudah disemprot semprotan masak. Tutup dengan sisa saus béchamel. Taburi dengan keju Parmesan dan panggang 30 sampai 40 menit hingga cokelat keemasan."],
["Saus béchamel adalah saus putih dasar."],
["1 daging","2 pati","1 sayuran, kalium rendah","2 lemak"]))
P.append(R(3647,"Roti Awan","Telur dan bubuk whey protein menjadikan Roti Awan sumber protein yang baik bagi pasien cuci darah yang membutuhkan tambahan protein.","12","1 iris",
["6 butir telur besar","1/2 sendok teh cream of tartar","3/4 cangkir krim asam","1/2 sendok teh baking powder","1/8 sendok teh garam","1/2 cangkir bubuk whey protein"],
["Panaskan oven terlebih dahulu hingga 300˚ F. Pisahkan telur, sisihkan kuning telur untuk nanti.","Dengan stand mixer atau mixer tangan, kocok putih telur dan cream of tartar hingga terbentuk puncak kaku. Sisihkan.","Campurkan kuning telur dalam mangkuk dengan bahan-bahan lainnya dan aduk rata.","Menggunakan sedikit putih telur, lipat perlahan ke dalam campuran kuning telur sedikit demi sedikit hingga tercampur rata. Lanjutkan menambahkan sisa putih telur.","Tuang campuran ke dalam loyang roti yang sudah diolesi minyak.","Panggang di tengah oven selama 50 sampai 60 menit, hingga tusuk gigi yang ditusukkan ke tengah keluar bersih.","Biarkan roti awan dingin. Keluarkan dari loyang dan iris. Simpan di lemari es."],
["Pilih merek bubuk protein dengan kandungan fosfor dan kalium terendah. Ahli gizi ginjal Anda dapat memberi tips tentang merek yang tersedia di daerah Anda.","Resep ini menggunakan bubuk protein vanila. Gunakan rasa lain atau bubuk protein tanpa rasa sesuai keinginan.","Untuk rasa gurih, tambahkan bubuk bawang putih, bubuk bawang bombai, atau keduanya."],
["1 daging"]))
P.append(R(3648,"Salad Pasta Pita","Salad Pasta Pita adalah resep yang bagus untuk diet cuci darah.","5","1/2 cangkir",
["2 cangkir pasta pita matang","1/4 cangkir seledri","2 sendok makan paprika merah","2 sendok makan wortel","2 sendok makan bawang merah","1/8 sendok teh lada hitam","1/2 cangkir mayones","1/2 sendok teh gula","1 sendok makan air lemon"],
["Cincang seledri dan paprika. Parut wortel. Cincang halus bawang merah.","Campurkan pasta, seledri, paprika merah, wortel, dan bawang merah dalam mangkuk.","Dalam mangkuk kecil terpisah, aduk lada, mayones, gula, dan air lemon hingga halus.","Tuang dressing ke atas pasta dan sayuran lalu aduk hingga terlapisi rata.","Dinginkan dan sajikan."],
["Tambahkan basil, tarragon, atau rosemary segar jika diinginkan."],
["1 pati","1/2 sayuran, kalium rendah","4 lemak"]))
save(2,P)
