import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/xid9')
from h import *
P=[]
P.append(R(3781,"Sawi Collard Gaya Selatan","Hidangan tradisional Selatan, sawi collard berdaun lebar ini kaya manfaat gizi. Ahli gizi ginjal DaVita, Lisa dari Alabama, menawarkan versi pedas dari sawi collard, resep ramah ginjal Sawi Collard Gaya Selatan, yang akan membuat bahkan orang Utara meminta tambah!","8","1/2 cangkir",
["1 sayap kalkun (8 ons)","1/2 cangkir bawang bombai","1 siung bawang putih","1 pon sawi collard","1 sendok makan minyak zaitun","1 sendok makan mentega tanpa garam","1 sendok teh serpihan cabai merah","1/2 sendok teh garam"],
["Dalam panci besar, didihkan 2 quart air. Masukkan sayap kalkun. Kecilkan api dan masak sekitar 1 jam. Sisihkan.","Cincang bawang bombai, bawang putih, dan sawi collard.","Dalam panci besar lainnya, panaskan minyak dan mentega dengan api sedang. Masukkan bawang bombai dan tumis selama 2 menit atau hingga empuk.","Tambahkan bawang putih dan serpihan cabai merah, lalu masak 1 menit.","Tambahkan sawi collard dan masak 1 menit.","Tambahkan kaldu kalkun secukupnya hingga menutupi sayuran (sekitar 4 cangkir). Tambahkan garam dan didihkan perlahan.","Masak hingga sayuran empuk, sekitar 40 sampai 50 menit.","Pisahkan daging dari tulang sayap kalkun dan tambahkan dagingnya ke sayuran yang sudah matang sebelum disajikan."],
["Kebanyakan sayuran hijau dianggap buruk karena tinggi kalium, padahal porsi yang dikonsumsilah yang menentukan. Banyak orang makan lebih dari 1/2 cangkir. Tetaplah dalam porsi yang disarankan agar kalium tetap rendah.","Untuk memasukkan daging kalkun sebagai hidangan utama, masak beberapa sayap atau paha kalkun. Buang kulit dari kalkun yang sudah matang dan tambahkan dagingnya ke sawi collard jika diinginkan."],
["1 daging","1 sayuran, kalium sedang","1 lemak"]))
P.append(R(3784,"Kubis Isi Kalkun","Menjalani diet ginjal tidak mudah. Tetapi membatasi fosfor, kalium, dan natrium tidak berarti Anda harus membatasi cita rasa. Ahli gizi ginjal DaVita, Sara dari California, tahu cara membuat hidangan lezat yang ramah ginjal dan Anda juga bisa dengan resepnya untuk Kubis Isi Kalkun.","6","1 cangkir atau 1/6 kubis",
["1 kepala kubis hijau sedang","12 ons kalkun giling, 7% lemak","3 ons sosis kalkun","1/4 cangkir bawang bombai, dicincang halus","1/4 cangkir paprika hijau, dicincang halus","1 sendok makan saus Worcestershire","1/2 sendok teh bumbu herba ekstra pedas Mrs. Dash®"],
["Panaskan oven terlebih dahulu hingga 350° F.","Buang bagian inti kubis dan keruk 3 cangkir kubis dari bagian dalam untuk membuat rongga isian.","Campurkan kalkun, sosis, bawang bombai, paprika, saus Worcestershire, dan bumbu herba dalam mangkuk. Aduk rata lalu isikan ke dalam kubis.","Tusukkan 4 sampai 5 tusuk gigi di sekeliling bagian luar kubis untuk menahannya. Letakkan dengan sisi isian menghadap ke atas dalam panci dalam yang tahan oven.","Tuang 1/2 cangkir air ke dasar panci, tutup dengan penutup dan panggang 45 menit atau hingga suhu kalkun giling mencapai 175° F.","Angkat dari oven dan diamkan 10 menit sebelum dipotong menjadi 6 porsi yang sama."],
["Buat coleslaw dari sisa kubis yang dikeruk untuk membuat rongga isian kalkun.","Pilih sosis kalkun pedas untuk cita rasa lebih kuat.","Sosis lebih tinggi natrium dan fosfor daripada banyak daging lain. Bila digunakan dalam jumlah kecil, sosis dapat dimasukkan dalam resep yang memenuhi target diet ginjal.","Bagi sisa sosis menjadi porsi 1-1/2 ons dan bekukan untuk digunakan nanti."],
["2 daging","1 sayuran, kalium sedang"]))
P.append(R(3788,"Kue Lemon Dingin","Manis, asam, dan menyegarkan, Kue Lemon Dingin adalah pencuci mulut yang bagus atau penyemangat ketika Anda mendambakan sajian ramah ginjal.","20","potongan persegi 2” x 2”",
["1 kotak campuran kue kuning (18,5 ons)","1/2 cangkir saus apel tanpa gula","3 butir telur besar","1 cangkir air","2 cangkir gula bubuk","1/4 cangkir air lemon"],
["Panaskan oven terlebih dahulu hingga 350° F.","Olesi dengan minyak dan taburi tepung loyang 13” x 9” x 2”.","Dalam mangkuk adonan besar, campurkan campuran kue, saus apel, telur, dan air selama 30 detik dengan kecepatan rendah. Naikkan mixer ke kecepatan sedang dan aduk selama 2 menit.","Tuang adonan kue ke dalam loyang yang sudah disiapkan dan panggang 40 menit, atau hingga tusuk gigi yang ditusukkan ke tengah kue keluar bersih.","Dinginkan kue sepenuhnya. Jangan dikeluarkan dari loyang.","Sementara kue mendingin, campurkan gula bubuk dan air lemon dalam mangkuk kecil hingga tercampur.","Tusuk lubang di atas kue yang sudah dingin dengan jarak 1/2” satu sama lain.","Sendokkan glasir di atas kue, biarkan meresap ke dalam lubang. Lama-kelamaan glasir akan melapisi bagian atas kue dengan lapisan buram.","Dinginkan hingga benar-benar dingin dan sajikan."],
["Semakin dingin kuenya, semakin enak rasanya. Ini resep yang bagus untuk musim semi dan musim panas."],
["1 pati","1 kalori tinggi"]))
P.append(R(3790,"Wafel Gaya Lama","Lisa, ahli gizi ginjal DaVita dan mantan koki dari New York, membagikan resep ramah ginjal yang lezat. Mulailah hari Anda dengan sarapan hangat berupa Wafel Gaya Lama Lisa yang menggugah selera.","8","setengah wafel 7”",
["1-3/4 cangkir susu 2%","8 sendok makan mentega tanpa garam, dipotong menjadi 8 bagian","2 cangkir tepung terigu serbaguna","1 sendok makan gula pasir","1 sendok teh garam","1-1/2 sendok teh ragi roti","2 butir telur besar","1 sendok teh ekstrak almond murni"],
["Panaskan susu dan mentega dalam panci kecil dengan api sedang-kecil hingga mentega meleleh, 3 sampai 5 menit. Dinginkan campuran susu/mentega hingga hangat saat disentuh.","Sementara itu, kocok tepung, gula, garam, dan ragi dalam mangkuk besar hingga tercampur.","Kocok campuran susu/mentega hangat ke dalam campuran tepung secara bertahap; terus kocok hingga adonan halus.","Dalam mangkuk kecil, kocok telur dan vanila hingga tercampur, lalu tambahkan campuran telur ke adonan dan kocok hingga menyatu.","Kerok sisi mangkuk dengan spatula karet, tutup dengan plastik pembungkus dan simpan di lemari es minimal 12 jam dan hingga 24 jam.","Saat siap membuat wafel, panaskan oven hingga 200° F untuk menjaga wafel tetap hangat setelah dimasak. Panaskan cetakan wafel.","Keluarkan adonan dari lemari es saat cetakan wafel siap (adonan akan berbusa dan mengembang dua kali lipat). Kocok adonan untuk menyatukan kembali (adonan akan mengempis).","Gunakan 1/2 cangkir adonan untuk cetakan wafel 7” atau 1 cangkir adonan untuk cetakan wafel 9”.","Sajikan segera atau buat renyah dan simpan hangat dalam oven."],
["Buat adonan sehari sebelum digunakan.","Resep ini belum diuji dengan krimer non-susu atau pengganti susu lainnya.","Untuk variasi rasa, gunakan ekstrak vanila murni atau ekstrak jeruk sebagai pengganti ekstrak almond.","Beri topping buah beri segar atau sedikit gula bubuk jika diinginkan.","Kebanyakan campuran wafel atau wafel beku mengandung lebih dari 400 mg natrium dan lebih dari 180 mg fosfor untuk satu porsi yang sebanding dengan resep ini. Mengganti baking powder dengan ragi roti membuat perbedaan."],
["1-1/2 pati","1/2 susu","2 lemak"]))
P.append(R(3793,"Salad Farro dan Apel","Farro adalah gandum utuh yang tinggi serat dan protein. Cobalah Salad Farro dan Apel ini sebagai hidangan utama berbahan nabati.","4","1 cangkir selada + 1/4 bahan resep",
["1/2 cangkir farro kering","2 apel sedang","1 cangkir buncis (kacang arab)","2 sendok makan air jeruk","2 sendok teh mustard Dijon","2 sendok makan cuka","2 sendok makan madu","2 sendok makan minyak zaitun","1/2 cangkir keju kambing","4 cangkir selada butterhead"],
["Masak farro sesuai petunjuk kemasan, sekitar 15 sampai 20 menit. Gemburkan dan sisihkan hingga dingin.","Buang bagian tengah apel dan iris. Tiriskan dan bilas buncis.","Untuk membuat dressing vinaigrette, kocok bersama air jeruk, mustard, cuka, madu, dan minyak zaitun.","Untuk menyusun salad, letakkan selada dalam 4 mangkuk. Bagi rata irisan apel, buncis, dan farro di atas selada. Beri topping setiap salad dengan 2 sendok makan keju kambing dan 2 sendok makan vinaigrette."],
["Jika farro tidak tersedia, beras merah dapat digunakan sebagai pengganti. Ini menurunkan protein menjadi 9 g dan kandungan serat menjadi 5 g."],
["1 daging","1 pati","1 buah, kalium rendah","1/2 kalori tinggi","2 lemak"]))
P.append(R(3797,"Chili Con Carne","Semangkuk Chili Con Carne yang hangat adalah hidangan sempurna di hari yang dingin. Resep ramah ginjal yang lezat ini akan memuaskan selera makan Anda sepanjang tahun.","8","1 cangkir",
["1/2 cangkir bawang bombai","1 batang seledri","1/2 cangkir paprika hijau","1-1/2 pon daging sapi giling tanpa lemak","16 ons tomat rebus rendah natrium","1 sendok makan minyak kanola","2 sendok makan bubuk cabai","1-1/2 cangkir air"],
["Cincang bawang bombai, seledri, dan paprika.","Panaskan wajan besar dengan api sedang. Masukkan minyak, bawang bombai, seledri, dan paprika hingga empuk, tetapi tidak cokelat.","Tambahkan daging sapi giling, hancurkan menjadi potongan kecil dan masak hingga kecokelatan.","Haluskan tomat dengan blender dan tambahkan ke daging sapi. Tambahkan bubuk cabai dan air. Aduk rata; kecilkan api.","Masak dengan api kecil selama beberapa jam."],
["Sajikan dengan biskuit rendah natrium."],
["3 daging","1 sayuran, kalium sedang"]))
P.append(R(3799,"Lasagna Vanila","Kita biasanya tidak memikirkan lasagna ketika memikirkan pencuci mulut, tetapi ahli gizi ginjal DaVita, Krissy dari Illinois, membagikan versi berbeda dari pencuci mulut yang memuaskan selera manis semua orang, termasuk mereka yang menjalani diet ginjal. Lasagna Vanila memadukan biskuit graham yang renyah dengan puding vanila yang kaya untuk perpaduan tekstur dan rasa yang memuaskan sehingga pencuci mulut ini menonjol.","15","satu potong 3\" x 2-1/2\"",
["4 kemasan puding vanila Snack Pack®","1 kotak biskuit graham madu","13 ons topping pencuci mulut susu bebas lemak Reddi-Wip®","1 cangkir keping cokelat mini"],
["Tuang puding vanila dari kemasan ke dalam mangkuk adonan.","Lipat perlahan 3 cangkir Reddi Wip® ke dalam mangkuk puding.","Lapisi dasar loyang 9” x 13” dengan biskuit graham.","Ratakan setengah campuran puding di atas biskuit graham.","Letakkan lapisan biskuit graham lagi di atas campuran puding.","Ratakan setengah campuran puding lainnya di atas biskuit graham.","Letakkan lapisan terakhir biskuit graham di atas campuran puding.","Simpan di lemari es semalaman.","Setelah dikeluarkan dari lemari es dan sebelum disajikan, semprotkan sisa topping krim kocok di atas pencuci mulut lalu taburkan 1 cangkir keping cokelat mini di atasnya."],
["Resep ini paling enak jika disiapkan malam sebelum disajikan.","Kurangi porsi menjadi setengah dari ukuran yang disarankan jika Anda menderita diabetes dan hitung sebagai 1-1/2 pilihan karbohidrat."],
["1 pati","1 produk susu","1 kalori tinggi","1 lemak"]))
P.append(R(3800,"Ayam Asam Manis","Apakah Anda menyukai masakan Tionghoa, renyahnya sayuran, dan saus yang asam segar? Resep ayam asam manis yang ramah ginjal ini memiliki semuanya dan sangat mudah dibuat.","4","satu potong ayam ditambah 1/2 cangkir nasi",
["2 paha utuh ayam","2 dada ayam, dengan tulang","1/4 sendok teh garam","1/4 sendok teh bubuk bawang putih","6 ons konsentrat limun beku","3 sendok makan gula merah muda, dipadatkan","1/4 cangkir saus tomat","1 sendok makan cuka","1 cangkir paprika hijau, diiris","1/4 cangkir bawang bombai, dipotong dadu","2 sendok makan tepung maizena","2 sendok makan air dingin","2 cangkir nasi putih matang"],
["Letakkan potongan ayam dalam Crock-Pot® dan taburi dengan garam dan bubuk bawang putih.","Dalam mangkuk kecil, campurkan konsentrat limun, gula merah, saus tomat, dan cuka. Tuang di atas ayam. Tutup dan masak pada pengaturan api rendah selama 4-1/2 jam.","Tambahkan irisan paprika dan bawang bombai potong dadu. Tutup dan lanjutkan memasak dengan api rendah 1-1/2 sampai 2-1/2 jam lagi. Pindahkan ayam dan sayuran ke piring saji; tutup dan simpan hangat. Tuang cairan dari Crock-Pot ke dalam panci. Campurkan tepung maizena dengan air dingin; aduk ke dalam cairan. Masak sambil diaduk dengan api sedang hingga kental dan berbuih.","Sajikan saus di atas ayam, bersama nasi putih."],
["Cobalah resep ini dengan drumstick dan paha ayam jika Anda menjalani diet protein yang lebih rendah dan membutuhkan porsi ayam yang lebih kecil.","Ini adalah hidangan tinggi karbohidrat dan tidak dianjurkan bagi penderita diabetes yang membutuhkan hidangan dengan karbohidrat lebih rendah."],
["4 daging","1/2 sayuran, kalium rendah","2 pati","2 kalori tinggi"]))
P.append(R(3806,"Pancake Oven Mengembang","Pancake Oven Mengembang mudah disiapkan dengan hanya 5 bahan. Bebas gluten dan beragam topping membuatnya cocok untuk semua diet ginjal.","4","1/4 pancake",
["2 sendok makan mentega tanpa garam","2 butir telur besar","1/2 cangkir tepung beras","1/2 cangkir susu beras tanpa pengayaan","1/8 sendok teh garam"],
["Panaskan oven terlebih dahulu hingga 400º F.","Letakkan mentega dalam wajan 10 inci tahan oven atau piring pai kaca. Masukkan ke oven selama 3 sampai 5 menit atau hingga mentega meleleh.","Dalam mangkuk adonan sedang, gunakan whisk kawat atau pengocok putar untuk mengocok telur hingga tercampur. Tambahkan tepung beras, susu beras, dan garam. Kocok hingga halus.","Keluarkan wajan atau piring pai dari oven. Segera tuang adonan ke dalam wadah panas. Panggang selama 25 sampai 30 menit hingga pancake mengembang dan cokelat merata.","Pindahkan ke piring saji dan potong menjadi 4 porsi. Tambahkan topping pilihan. Sajikan hangat."],
["Pastikan pancake cokelat merata pada langkah #4. Jika tidak, bagian dalam pancake tidak akan matang.","Topping buah yang disarankan meliputi blueberry, stroberi iris, raspberry, persik iris, atau saus apel. Untuk topping tambahan, taburi dengan gula bubuk atau beri krim kocok atau sirup.","Pancake ini bebas gluten."],
["1/2 daging","1 pati","1 lemak"]))
P.append(R(3808,"Dressing Quinoa","Cobalah quinoa untuk meningkatkan serat dan asupan biji-bijian yang tidak diproses. Meskipun kandungan kalium dan fosfornya lebih tinggi dibandingkan biji-bijian olahan, quinoa dapat dimasukkan ke dalam diet ramah ginjal.","6","1/2 cangkir",
["1 cangkir bawang bombai","2 cangkir seledri","1 cangkir kaldu sayuran rendah natrium","1 cangkir air","3/4 cangkir quinoa, mentah","1/4 cangkir mentega tanpa garam","2 sendok makan peterseli kering","1 sendok makan sage kering","1/2 sendok teh bubuk bawang putih","1/2 sendok teh lada hitam bubuk","1/2 cangkir cranberry kering"],
["Panaskan oven terlebih dahulu hingga 350º F.","Cincang bawang bombai dan potong dadu seledri. Sisihkan.","Masukkan kaldu dan air ke dalam panci sedang dan didihkan dengan api besar. Masukkan quinoa dan didihkan kembali. Kecilkan api, tutup, dan masak dengan api kecil selama 12 menit, atau hingga quinoa menyerap semua cairan.","Sementara itu, lelehkan mentega dalam wajan besar dengan api sedang. Masukkan bawang bombai dan seledri, aduk sesekali, hingga bening, sekitar 10 menit.","Angkat campuran bawang bombai dari api. Masukkan quinoa ke campuran bawang bombai. Tambahkan peterseli, sage, bawang putih, dan lada. Aduk hingga rata.","Tambahkan cranberry ke dressing dan aduk.","Pindahkan dressing ke loyang persegi 8″ dan panggang selama 30 menit."],
["Quinoa lebih tinggi kalium dan fosfor dibandingkan biji-bijian utuh lainnya, tetapi merupakan sumber protein dan serat yang baik. Secara umum, hanya setengah dari fosfor dalam biji-bijian utuh yang diserap selama pencernaan. Dengan membatasi porsi, Anda masih dapat menikmati quinoa dalam diet ginjal Anda. Konsultasikan dengan ahli gizi Anda.","Setiap batang seledri menghasilkan sekitar 1 cangkir setelah dipangkas dan dipotong dadu.","Resep ini juga cocok digunakan sebagai isian."],
["1 pati","1 sayuran, kalium sedang","1/2 buah, kalium rendah","1 lemak"]))
save(7,P)
