import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/c4')
from h import *
I=[]
I.append((6131476,{
"es":T("Sloppy Joes de lentejas","Estos Sloppy Joes de lentejas son una alternativa vegetal, abundante y satisfactoria, a la versión clásica. Con mucha proteína y sabor, son una comida deliciosa y nutritiva que les encanta a los niños. Agregue una ensalada mixta como acompañamiento para completar su Plato para la Diabetes.","6","1 pan de hamburguesa y aproximadamente ½ taza de la mezcla de lentejas",
["1 cebolla blanca mediana (cortada en 12 rodajas finas)","6 hojas de lechuga","6 panes de hamburguesa integrales enteros","1/4 cucharadita de sal","1/2 cucharadita de pimentón ahumado","1/2 cucharadita de chile en polvo","1 cucharada de salsa Worcestershire","1 cucharada de azúcar morena","1/4 taza de salsa de tomate","1 taza de lentejas (verdes, enjuagadas)","2 tazas de caldo de verduras bajo en sodio","2 dientes de ajo (picados)","1 cebolla amarilla pequeña (picada en cubos)","1 cucharada de aceite de oliva extra virgen"],
["Ponga una cacerola a fuego medio. Agregue el aceite, la cebolla y el ajo. Cocine, revolviendo de vez en cuando, hasta que la cebolla empiece a ablandarse, de 3 a 4 minutos.","Agregue el caldo y las lentejas. Lleve a ebullición, luego reduzca el fuego para que hierva a fuego lento y tape durante unos 20 minutos, hasta que las lentejas estén tiernas.","Incorpore la salsa de tomate, el azúcar morena, la salsa Worcestershire y las especias.","Para servir, reparta las lentejas entre los panes. Cubra con la lechuga y los aros de cebolla.","Sirva con una ensalada mixta como acompañamiento."]),
"ar":T("ساوري جو بالعدس","ساوري جو بالعدس بديل نباتي مشبع ولذيذ للنسخة التقليدية. غني بالبروتين والنكهة، وهو وجبة لذيذة ومغذية يحبها الأطفال! أضف سلطة مشكلة كطبق جانبي لإكمال طبق السكري الخاص بك.","6","1 رغيف همبرغر وحوالي ½ كوب من خليط العدس",
["1 بصلة بيضاء متوسطة (مقطعة إلى 12 شريحة رقيقة)","6 أوراق خس","6 أرغفة همبرغر كاملة من القمح الكامل","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة مسحوق الفلفل الحار","1 ملعقة كبيرة صلصة ورسترشير","1 ملعقة كبيرة سكر بني","¼ كوب صلصة طماطم","1 كوب عدس (أخضر، مغسول)","2 كوب مرق خضار قليل الصوديوم","2 فص ثوم (مفروم)","1 بصلة صفراء صغيرة (مقطعة مكعبات)","1 ملعقة كبيرة زيت زيتون بكر ممتاز"],
["ضع قدرًا صغيرًا على نار متوسطة. أضف الزيت والبصل والثوم. اطهِ مع التحريك من حين لآخر حتى يبدأ البصل بالليونة، من 3 إلى 4 دقائق.","أضف المرق والعدس. اتركه حتى يغلي، ثم خفّف النار ليغلي على نار هادئة وغطِّه نحو 20 دقيقة حتى ينضج العدس.","أضف صلصة الطماطم والسكر البني وصلصة ورسترشير والتوابل وحرّك.","عند التقديم، وزّع العدس على الأرغفة. زيّنه بالخس وحلقات البصل.","قدّمه مع سلطة مشكلة كطبق جانبي."])}))
I.append((6131494,{
"ar":T("فيليه السمك بالليمون والبقدونس","إليك عشاءً سريعًا لأيام الأسبوع تستمتع به مع عائلتك. يمكن أن يكون السمك طبقًا رئيسيًا رائعًا عندما يضيق الوقت لأنه ينضج بسرعة، كما أنه مصدر ممتاز للبروتين قليل الدهون.","4","4½ أونصة سمك مطبوخ + 1 ملعقة كبيرة من خليط البقدونس",
["4 شرائح فيليه سمك أبيض قليل الدهون (6 أونصات لكل منها، مثل البلطي أو الهامور الأحمر أو سمك موسى، مغسولة ومجففة)","⅛ ملعقة صغيرة بابريكا (حسب الذوق)","2 ملعقة كبيرة زيت زيتون بكر ممتاز","½ ملعقة صغيرة قشر ليمون مبروش","1 ملعقة كبيرة بقدونس (مفروم ناعمًا)","⅛ ملعقة صغيرة شبت مجفف","1 ليمونة متوسطة (مقطوعة إلى نصفين)"],
["سخّن الفرن مسبقًا على 400° فهرنهايت (200° مئوية).","بطّن صينية الخبز بورق الألمنيوم، ودهنه ببخاخ الطهي، ورتّب شرائح السمك عليه، ورشّها بالتساوي بالبابريكا. تبّلها بخفة بالملح والفلفل الأسود إن رغبت. اخبزها 10 دقائق أو حتى يصبح وسط السمك معتمًا.","أثناء نضج السمك، اخلط المكونات المتبقية، عدا نصفي الليمون، في وعاء خلط صغير وضعه جانبًا.","باستخدام ملعقة تقليب مثقبة، أخرج السمك وضعه في أربعة أطباق عشاء، واعصر عصير الليمون بالتساوي فوقه. زيّنه بخليط البقدونس."])}))
I.append((6131682,{
"ar":T("صلصة المانجو والطماطم","هذه الصلصة المنزلية المصنوعة من منتجات طازجة أكثر قيمة غذائية وأقل صوديومًا من الصلصة المعلبة التي تجدها في المتجر. قدّمها مع التاكو أو الكيساديا أو الدجاج المشوي!","5","½ كوب",
["1 فلفل هالابينو صغير (مفروم)","1 كوب طماطم (مفرومة)","1 كوب مانجو (مفرومة)","¼ كوب بصل أبيض (مفروم)","½ كوب كزبرة خضراء (مفرومة)","1 ملعقة صغيرة زيت زيتون","1 ملعقة صغيرة عصير الليمون الأخضر"],
["حدّد كمية الهالابينو التي تريد استخدامها. إذا كنت تفضل إزالة البذور فافعل ذلك بحذر. تجنّب لمس عينيك وأنفك.","اخلط جميع المكونات.","قدّمها مع خبز التورتيلا الذرة الدافئ أو اللحوم المشوية."]),
}))
I.append((6132615,{
"es":T("Tostada de aguacate y tomate","Esta tostada fresca y satisfactoria combina aguacate cremoso y tomate jugoso sobre pan integral crujiente. Es rápida de preparar, llena de sabor y perfecta como refrigerio.","1","1 rebanada",
["1 rebanada de pan integral tostado","1/2 aguacate entero","1/2 tomate entero (en rodajas)"],
["Tueste una rebanada de pan integral hasta que quede tan crujiente como a usted le guste.","Triture ligeramente con un tenedor 1/2 aguacate y úntela sobre la tostada.","Coloque encima las rodajas de 1/2 tomate.","Sirva de inmediato."]),
"ar":T("توست الأفوكادو والطماطم","يجمع هذا التوست المنعش والمشبع بين الأفوكادو الكريمي والطماطم العصيرية على خبز الحبوب الكاملة المقرمش. سهل التحضير وغني بالنكهة ومثالي كوجبة خفيفة.","1","1 شريحة",
["1 شريحة توست من الحبوب الكاملة","½ حبة أفوكادو","½ حبة طماطم (مقطعة شرائح)"],
["حمّص شريحة واحدة من خبز الحبوب الكاملة حتى تصبح مقرمشة كما تحب.","اهرس ½ حبة أفوكادو برفق بالشوكة وافردها على التوست.","ضع شرائح ½ حبة طماطم فوقها.","قدّمه فورًا."])}))
I.append((6135376,{
"ar":T("دجاج كورنيش المشوي بإكليل الجبل","دجاج كورنيش نوع من الدجاج الصغير الحجم ويمكن أن يكون وجبة مميزة للأعياد. إذا لم تجد دجاج كورنيش في متجر البقالة، يمكنك تحضير الوصفة نفسها بصدور الدجاج بالعظم.","4","½ دجاجة كورنيش",
["1 بخة من بخاخ الطهي غير اللاصق، 0.25 غرام","1 ملعقة كبيرة إكليل جبل طازج (مفروم)","¼ ملعقة صغيرة فلفل أسود","½ ملعقة صغيرة ملح (اختياري)","2 فص ثوم (مفروم أو مبروش)","1 ملعقة كبيرة خردل ديجون","2 ملعقة كبيرة عصير ليمون (معصور طازجًا من 1 ليمونة متوسطة)","1 ملعقة صغيرة قشر ليمون مبروش (من 1 ليمونة متوسطة)","1 ملعقة كبيرة زيت زيتون","2 دجاجة كورنيش كاملة (حوالي 1¼ رطل لكل منها)","4 أغصان إكليل جبل طازج"],
["سخّن الفرن مسبقًا على 350° فهرنهايت (175° مئوية). ادهن طبق خبز زجاجيًا أو معدنيًا كبيرًا ببخاخ الطهي.","في وعاء صغير، اخفق زيت الزيتون وقشر الليمون وعصير الليمون وخردل ديجون والثوم والملح (اختياري) والفلفل الأسود وإكليل الجبل المفروم معًا.","اقطع كل دجاجة كورنيش إلى نصفين بالطول وانزع الجلد. جففها بمنشفة ورقية. ضع 4 أغصان إكليل الجبل في قاع طبق الخبز.","رتّب الدجاج وجهه الصدري إلى الأعلى في طبق الخبز (نصف دجاجة فوق كل غصن إكليل جبل). افرد التتبيلة بسخاء على كل دجاجة (باستخدام كامل كمية التتبيلة).","اخبزها 30–35 دقيقة أو حتى تصل درجة الحرارة الداخلية إلى 165° فهرنهايت (75° مئوية)."])}))
I.append((6135574,{
"ar":T("بيتزا المكسرات للفطور","جرّب هذا الفطور البسيط جدًا. سيحبه الصغار والكبار، ويكون جاهزًا خلال دقائق! وإذا كان ذلك أنسب لميزانيتك، يمكنك استبدال زبدة اللوز بزبدة الفول السوداني.","2","½ مافن إنجليزي",
["1 مافن إنجليزي من القمح الكامل","2 ملعقة كبيرة زبدة اللوز","½ كوب فراولة (مقطعة شرائح)","1½ ملعقة صغيرة رقائق جوز الهند غير المحلاة (مبشورة)"],
["اقسم المافن الإنجليزي إلى نصفين وحمّصه.","افرد زبدة اللوز على كل نصف.","ضع شرائح الفراولة فوقه.","رش جوز الهند."])}))
I.append((6137042,{
"es":T("Ejotes con arándanos rojos y avellanas","Alegre un acompañamiento de ejotes con arándanos rojos secos de sabor ácido, ralladura fresca de limón y avellanas crujientes. Esta guarnición sencilla parece de alta cocina, pero es muy fácil de preparar. También es un complemento ligero y agradable para su mesa de Acción de Gracias.","16","1/2 taza",
["2 libras de ejotes frescos (sin las puntas)","1 cucharada de aceite de oliva","3 cucharadas de arándanos rojos secos","1/4 taza de avellanas (picadas en trozos grandes)","1/4 cucharadita de pimienta negra","1/4 cucharadita de sal","2 cucharaditas de ralladura de limón"],
["Llene 2/3 de una olla grande con agua y lleve a ebullición. Agregue los ejotes, apague el fuego y deje los ejotes en el agua durante 3 minutos. Escurra los ejotes y póngalos en un tazón o fuente para servir.","En un tazón pequeño, mezcle el aceite, las nueces, los arándanos rojos, la sal y la pimienta. Cubra los ejotes con la mezcla de arándanos y nueces. Decore con la ralladura de limón."]),
"ar":T("فاصولياء خضراء بالتوت البري والبندق","أضف حيوية إلى طبق الفاصولياء الخضراء الجانبي مع التوت البري الحامض وقشر الليمون الطازج المبشور والبندق المقرمش! هذا الطبق الجانبي البسيط يبدو فاخرًا لكنه سهل التحضير جدًا. كما أنه إضافة خفيفة ولطيفة إلى مائدة عيد الشكر.","16","½ كوب",
["2 رطل فاصولياء خضراء طازجة (منزوعة الأطراف)","1 ملعقة كبيرة زيت زيتون","3 ملاعق كبيرة توت بري مجفف","¼ كوب بندق (مفروم فرمًا خشنًا)","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح","2 ملعقة صغيرة قشر ليمون مبروش"],
["املأ قدرًا كبيرًا بالماء حتى ⅔ وأوصله إلى الغليان. أضف الفاصولياء الخضراء وأطفئ النار واتركها في الماء 3 دقائق. صفِّ الفاصولياء وانقلها إلى وعاء تقديم أو طبق كبير.","في وعاء صغير، اخلط الزيت والمكسرات والتوت البري والملح والفلفل. غطِّ الفاصولياء الخضراء بخليط التوت البري والمكسرات. زيّنها بقشر الليمون المبروش."])}))
I.append((6137953,{
"es":T("Sazonador cajún sin sal","El sazonador cajún comprado en tienda puede contener más de 1000 mg de sal por cucharadita. Esta mezcla sin sal ofrece los mismos sabores cajún, pero usted controla cuánta sal lleva el plato final. Puede usar este sazonador en pollo, pescado u otros mariscos, espolvoreado sobre verduras al vapor o asadas, o como condimento para palomitas de maíz. ¡Las posibilidades son infinitas!","20","1 cucharadita",
["2 cucharadas de pimentón","1 cucharada de ajo en polvo","1 cucharada de cebolla en polvo","2 cucharaditas de pimienta negra","2 cucharaditas de pimienta de cayena","2 cucharaditas de tomillo seco","2 cucharaditas de orégano seco"],
["Mezcle todos los ingredientes. Guarde en un recipiente hermético."]),
"ar":T("توابل كاجون خالية من الملح","قد تحتوي توابل الكاجون الجاهزة من المتجر على أكثر من 1000 ملغ من الملح في الملعقة الصغيرة الواحدة! يمنحك هذا الخليط الخالي من الملح نكهات الكاجون نفسها، لكنك تتحكم في كمية الملح في الطبق النهائي. يمكنك استخدام هذه التوابل على الدجاج أو السمك أو المأكولات البحرية الأخرى، أو رشّها على الخضار المطهوة على البخار أو المشوية، أو كتتبيلة للفشار. الاحتمالات لا حصر لها!","20","1 ملعقة صغيرة",
["2 ملعقة كبيرة بابريكا","1 ملعقة كبيرة مسحوق الثوم","1 ملعقة كبيرة مسحوق البصل","2 ملعقة صغيرة فلفل أسود","2 ملعقة صغيرة فلفل حار كايين","2 ملعقة صغيرة زعتر مجفف","2 ملعقة صغيرة أوريجانو مجفف"],
["اخلط جميع المكونات معًا. احفظها في وعاء محكم الإغلاق."])}))
I.append((6139190,{
"es":T("Sándwich abierto de ensalada de garbanzos","Disfrute de los sabores frescos y satisfactorios de este sándwich abierto de ensalada de garbanzos, una deliciosa opción del Patrón de Comidas Vegano. Una mezcla de garbanzos, verduras crujientes y un aderezo con un toque cítrico se apila sobre una rebanada de pan tostado, para una comida colorida y nutritiva, ligera y a la vez saciante. Perfecto para un almuerzo rápido o una cena ligera.","4","1 rebanada de pan, ⅔ taza de relleno de garbanzos",
["30 onzas de garbanzos enlatados (sin sal añadida)","1 cucharada de eneldo fresco (picado)","1/3 taza de mayonesa vegana baja en grasa","2 cucharaditas de mostaza Dijon","2 cucharaditas de vinagre de sidra de manzana","1/4 cucharadita de cebolla en polvo","1/4 cucharadita de pimentón","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra","4 rebanadas de pan integral","1/2 paquete (5 onzas) de mezcla de lechugas tiernas","1 tomate entero (en rodajas)","1 cucharada de perejil de hoja plana (picado)","2 zanahorias grandes (peladas y cortadas en bastones de 2 pulgadas)","2 tallos de apio (sin las puntas y cortados en bastones de 2 pulgadas)"],
["Escurra y enjuague los garbanzos. Páselos a un tazón mediano.","Agregue al tazón el eneldo fresco, la mayonesa, la mostaza Dijon, el vinagre y las especias.","Con un tenedor o un machacador de papas, triture los garbanzos hasta obtener una pasta semisuave.","Tueste las rebanadas de pan. Reparta entre los platos y cubra con la mezcla de lechugas, las rodajas de tomate y la pasta de garbanzos. Sirva con bastones de verduras como acompañamiento."]),
"ar":T("ساندويتش مفتوح بسلطة الحمص","استمتع بالنكهات المنعشة والمشبعة لهذا الساندويتش المفتوح بسلطة الحمص، وهو خيار لذيذ من النمط الغذائي النباتي. يُكدَّس خليط من الحمص والخضار المقرمشة وصلصة منعشة فوق شريحة خبز محمص، لتحصل على وجبة ملونة ومغذية خفيفة ومشبعة في آن واحد. مثالي لغداء سريع أو عشاء خفيف.","4","1 شريحة خبز، ⅔ كوب من حشوة الحمص",
["30 أونصة حمص معلب (بدون ملح مضاف)","1 ملعقة كبيرة شبت طازج (مفروم)","⅓ كوب مايونيز نباتي قليل الدسم","2 ملعقة صغيرة خردل ديجون","2 ملعقة صغيرة خل التفاح","¼ ملعقة صغيرة مسحوق البصل","¼ ملعقة صغيرة بابريكا","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","4 شرائح خبز من الحبوب الكاملة","½ عبوة (5 أونصات) خضار سلطة مشكلة","1 حبة طماطم (مقطعة شرائح)","1 ملعقة كبيرة بقدونس مسطح الأوراق (مفروم)","2 جزرة كبيرة (مقشرة ومقطعة أعوادًا بطول 2 بوصة)","2 ساق كرفس (منزوعة الأطراف ومقطعة أعوادًا بطول 2 بوصة)"],
["صفِّ الحمص واغسله. انقله إلى وعاء متوسط.","أضف الشبت الطازج والمايونيز وخردل ديجون والخل والتوابل إلى الوعاء.","استخدم شوكة أو مهراس بطاطس لهرس الحمص حتى تحصل على معجون شبه ناعم.","حمّص شرائح الخبز. وزّعها على الأطباق وضع فوقها خضار السلطة وشرائح الطماطم ومعجون الحمص. قدّمها مع أعواد الخضار كطبق جانبي."])}))
I.append((6139340,{
"es":T("“Albóndigas” de berenjena con fideos de calabacín","Esta es una receta vegetariana con “albóndigas” de berenjena que ofrecen un toque vegetal a un clásico y se sirven sobre fideos de calabacín ligeros y tiernos, para una comida reconfortante y baja en carbohidratos. La harina de almendra y el parmesano dan estructura y sabor a las albóndigas, mientras que la fibra de las verduras ayuda a retrasar la digestión. Con su combinación de proteína, fibra y grasas saludables, es una excelente opción para mantener estables los niveles de glucosa en la sangre (azúcar en la sangre).","4","Aproximadamente 3–4 albóndigas + 1 taza de fideos de calabacín",
["1 berenjena mediana (pelada y cortada en cubos)","2 cucharaditas de aceite de oliva extra virgen","1/2 cebolla morada pequeña (picada finamente)","2 dientes de ajo (picados)","1/3 taza de harina de almendra","1/4 de taza de queso parmesano (rallado)","1/4 taza de perejil fresco (picado)","1 cucharadita de orégano seco","1/4 cucharadita de hojuelas de chile rojo triturado","1/4 cucharadita de pimienta negra","1 huevo entero (ligeramente batido)","4 calabacines medianos (en espiral)","1/8 cucharadita de sal (una pizca)","1 taza de salsa marinara (sin azúcar añadida)","1/4 taza de albahaca fresca (picada)"],
["Precaliente el horno a 375 grados F.","Cocine los cubos de berenjena al vapor o en el microondas hasta que estén blandos (unos 8–10 minutos). Deje enfriar un poco, luego pase a un paño de cocina limpio o a una gasa y exprima el exceso de humedad.","En un sartén, caliente 1 cucharadita de aceite de oliva a fuego medio. Agregue la cebolla y el ajo y cocine de 3 a 4 minutos, hasta que se ablanden.","En un tazón, triture la berenjena cocida con un tenedor o un machacador de papas. Agregue la cebolla y el ajo salteados, la harina de almendra, el parmesano, el perejil, el orégano, el chile rojo triturado, la pimienta negra y el huevo. Mezcle hasta integrar bien.","Cubra una bandeja para hornear con papel pergamino. Forme con la mezcla de 12 a 16 bolitas pequeñas y colóquelas en la bandeja. Hornee de 25 a 30 minutos, volteándolas a la mitad del tiempo, hasta que estén firmes y doradas.","Caliente 1 cucharadita de aceite de oliva en un sartén antiadherente grande a fuego medio-alto. Agregue los fideos de calabacín y una pizca de sal. Saltee de 2 a 3 minutos hasta que estén apenas tiernos. Escurra el exceso de humedad si es necesario.","Caliente la salsa marinara en una cacerola pequeña o en el microondas hasta que esté bien caliente.","Reparta los fideos de calabacín en 4 platos. Cubra con las albóndigas de berenjena y vierta con una cuchara la salsa marinara caliente por encima. Decore con la albahaca."]),
"ar":T("«كرات اللحم» بالباذنجان مع معكرونة الكوسا","هذه وصفة نباتية تقدم «كرات لحم» من الباذنجان كلمسة نباتية على طبق كلاسيكي، وتُقدَّم فوق معكرونة الكوسا الخفيفة الطرية لوجبة مريحة قليلة الكربوهيدرات. يمنح دقيق اللوز والبارميزان الكرات تماسكها ونكهتها، بينما تساعد ألياف الخضار على إبطاء الهضم. وبفضل مزيجها من البروتين والألياف والدهون الصحية، فهي خيار رائع للحفاظ على ثبات مستويات الجلوكوز في الدم (سكر الدم).","4","حوالي 3–4 كرات لحم + 1 كوب من معكرونة الكوسا",
["1 باذنجانة متوسطة (مقشرة ومقطعة مكعبات)","2 ملعقة صغيرة زيت زيتون بكر ممتاز","½ بصلة حمراء صغيرة (مفرومة ناعمًا)","2 فص ثوم (مفروم)","⅓ كوب دقيق اللوز","¼ كوب جبن بارميزان (مبشور)","¼ كوب بقدونس طازج (مفروم)","1 ملعقة صغيرة أوريجانو مجفف","¼ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","¼ ملعقة صغيرة فلفل أسود","1 بيضة (مخفوقة قليلًا)","4 حبات كوسا متوسطة (مبرومة على شكل شرائط)","⅛ ملعقة صغيرة ملح (رشة)","1 كوب صلصة مارينارا (بدون سكر مضاف)","¼ كوب ريحان طازج (مفروم)"],
["سخّن الفرن مسبقًا على 375° فهرنهايت (190° مئوية).","اطهُ مكعبات الباذنجان على البخار أو في الميكروويف حتى تلين (حوالي 8–10 دقائق). اتركها لتبرد قليلًا، ثم انقلها إلى منشفة مطبخ نظيفة أو قطعة شاش واعصرها للتخلص من الرطوبة الزائدة.","في مقلاة، سخّن 1 ملعقة صغيرة من زيت الزيتون على نار متوسطة. أضف البصل والثوم واطهِ 3–4 دقائق حتى يلينا.","في وعاء خلط، اهرس الباذنجان المطبوخ بشوكة أو مهراس بطاطس. أضف البصل والثوم المقليين ودقيق اللوز والبارميزان والبقدونس والأوريجانو ورقائق الفلفل الأحمر المجروش والفلفل الأسود والبيضة. اخلط حتى تتجانس المكونات جيدًا.","بطّن صينية الخبز بورق الزبدة. شكّل الخليط على هيئة 12–16 كرة صغيرة وضعها على الصينية. اخبزها 25–30 دقيقة مع قلبها في منتصف المدة، حتى تتماسك وتصبح ذهبية.","سخّن 1 ملعقة صغيرة زيت زيتون في مقلاة كبيرة غير لاصقة على نار متوسطة إلى عالية. أضف معكرونة الكوسا ورشة ملح. قلّبها 2–3 دقائق حتى تصبح طرية بالكاد. صفِّ الرطوبة الزائدة عند الحاجة.","سخّن صلصة المارينارا في قدر صغير أو في الميكروويف حتى تسخن جيدًا.","وزّع معكرونة الكوسا على 4 أطباق. ضع فوقها كرات الباذنجان واسكب صلصة المارينارا الدافئة فوقها. زيّنها بالريحان."])}))
I.append((6139937,{
"es":T("Camotes rellenos de chili de pavo","¡El chili fresco y los camotes al horno son una gran combinación! Esta receta se adapta fácilmente a su gusto. Agregue una pizca de cayena o pimienta para subir el picante uno o dos niveles. Pruebe cubrir su camote con cebollín o con una cucharada de yogur griego natural sin grasa (en lugar de crema agria). ¡Las opciones son infinitas para preparar esta receta a su manera!","4","1 camote y 1 taza de chili por porción",
["4 camotes pequeños","2 cucharadas de aceite de oliva (dividido)","2 dientes de ajo (picados)","1/4 taza de zanahorias (ralladas)","2 tallos de apio (en cubos pequeños)","1 cebolla amarilla pequeña (en cubos pequeños)","1 pimiento rojo pequeño (en cubos)","1 cucharadita de chile en polvo","1/2 cucharadita de cebolla en polvo","1/2 cucharadita de orégano seco","1/2 taza de lentejas","8 onzas de salsa de tomate baja en sodio o sin sal añadida (1 lata)","3 tazas de caldo de pollo bajo en sodio","1/2 libra de pavo molido","1/3 taza de queso cheddar rallado reducido en grasa"],
["Precaliente el horno a 400 grados F. Pinche la cáscara de los camotes y colóquelos en una bandeja para hornear. Hornee durante 60 minutos o hasta que estén blandos por completo.","Caliente una olla grande a fuego medio. Agregue el ajo, las zanahorias, el apio, la cebolla, el pimiento, las especias y 1 cucharada de aceite de oliva. Cocine, revolviendo de vez en cuando, hasta que se ablanden, de 4 a 5 minutos.","Agregue las lentejas, la salsa de tomate y el caldo. Lleve a ebullición, luego reduzca el fuego a bajo y cocine a fuego lento durante 30 minutos, hasta que las lentejas estén blandas.","Cuando el chili esté casi listo, caliente un sartén a fuego medio. Agregue el aceite de oliva restante y el pavo. Cocine, desmenuzándolo con una cuchara, hasta que esté desmenuzado y dorado. Agréguelo a la sopa durante los últimos 10 minutos.","Con cuidado, abra cada camote y triture el interior. Vierta 1 taza de chili sobre cada camote y cubra con 2 cucharadas de queso."]),
"ar":T("بطاطا حلوة محشوة بتشيلي الديك الرومي","التشيلي الطازج والبطاطا الحلوة المخبوزة مزيج رائع! يمكن تعديل هذه الوصفة بسهولة لتناسب ذوقك. أضف رشة من الفلفل الحار كايين أو الفلفل لرفع درجة الحرارة درجة أو درجتين. جرّب تزيين البطاطا الحلوة بالبصل الأخضر أو بملعقة من الزبادي اليوناني الطبيعي خالي الدسم (بدلًا من القشدة الحامضة). الخيارات لا حصر لها لتحضير هذه الوصفة على طريقتك!","4","1 حبة بطاطا حلوة و1 كوب من التشيلي لكل حصة",
["4 حبات بطاطا حلوة صغيرة","2 ملعقة كبيرة زيت زيتون (مقسّمة)","2 فص ثوم (مفروم)","¼ كوب جزر (مبشور)","2 ساق كرفس (مقطعة مكعبات صغيرة)","1 بصلة صفراء صغيرة (مقطعة مكعبات صغيرة)","1 حبة فلفل رومي أحمر صغيرة (مقطعة مكعبات)","1 ملعقة صغيرة مسحوق الفلفل الحار","½ ملعقة صغيرة مسحوق البصل","½ ملعقة صغيرة أوريجانو مجفف","½ كوب عدس","8 أونصات صلصة طماطم قليلة الصوديوم أو بدون ملح مضاف (1 علبة)","3 كوب مرق دجاج قليل الصوديوم","½ رطل ديك رومي مفروم","⅓ كوب جبن شيدر مبشور قليل الدسم"],
["سخّن الفرن مسبقًا على 400° فهرنهايت (200° مئوية). اثقب قشر حبات البطاطا الحلوة وضعها على صينية الخبز. اخبزها 60 دقيقة أو حتى تلين تمامًا من الداخل.","سخّن قدرًا كبيرًا على نار متوسطة. أضف الثوم والجزر والكرفس والبصل والفلفل الرومي والتوابل و1 ملعقة كبيرة من زيت الزيتون. اطهِ مع التحريك من حين لآخر حتى تلين، من 4 إلى 5 دقائق.","أضف العدس وصلصة الطماطم والمرق. اتركه حتى يغلي، ثم اخفض النار إلى هادئة واتركه على نار هادئة 30 دقيقة حتى يلين العدس.","عندما يوشك التشيلي على النضج، سخّن مقلاة على نار متوسطة. أضف باقي زيت الزيتون والديك الرومي. اطهِه مع تفتيته بالملعقة حتى يصبح مفتتًا ومحمرًا. أضفه إلى الحساء في آخر 10 دقائق.","اشقّ كل حبة بطاطا حلوة بحذر واهرس ما بداخلها. اسكب 1 كوب من التشيلي فوق كل حبة، ثم ضع فوقها 2 ملعقة كبيرة من الجبن."])}))
I.append((6140067,{
"es":T("Sopa de lentejas con dátiles de California y espinacas","Esta sopa abundante está inspirada en los reconfortantes sabores marroquíes y aporta calidez y nutrición en cada cucharada. Las lentejas ahumadas y las espinacas frescas forman una base satisfactoria, mientras que los dátiles de California, naturalmente dulces, añaden un sabor sutil y equilibrado. Esta sopa vegetariana baja en grasa es una excelente fuente de fibra. Para una textura más cremosa, puede licuar una parte de la sopa antes de servir.","6","1 taza",
["1 cucharada de aceite de oliva","3/4 taza de cebolla amarilla (picada en cubos)","1/2 taza de zanahorias (picadas en cubos)","1/2 taza de apio (picado en cubos)","3 dientes de ajo (picados)","2 cucharaditas de comino molido","2 cucharaditas de cilantro molido","1 cucharadita de pimentón ahumado","3/4 taza de lentejas secas (enjuagadas)","1 lata (14.5 onzas) de tomates picados sin sal añadida","4 tazas de caldo de verduras sin sal","2 tazas de agua","1 cucharadita de sal","1/2 cucharadita de pimienta negra","2 tazas de espinacas tiernas frescas","2 dátiles de California (sin hueso, picados finamente)","1 cucharada de jugo de limón"],
["En una olla grande, caliente el aceite de oliva a fuego medio. Agregue la cebolla, las zanahorias y el apio. Saltee de 3 a 4 minutos hasta que empiecen a ablandarse.","Agregue el ajo, el comino, el cilantro y el pimentón. Cocine 30 segundos más, hasta que desprendan su aroma.","Incorpore las lentejas, los tomates, el caldo de verduras y el agua. Lleve a ebullición, luego reduzca el fuego y cocine a fuego lento de 25 a 30 minutos, con la tapa ligeramente abierta, hasta que las lentejas estén tiernas. Incorpore la sal y la pimienta.","Incorpore las espinacas y los dátiles. Cocine de 2 a 3 minutos hasta que las espinacas se marchiten.","Agregue el jugo de limón fresco. Sirva la sopa caliente."]),
"ar":T("شوربة العدس بتمر كاليفورنيا والسبانخ","هذه الشوربة الدسمة مستوحاة من النكهات المغربية المريحة، وتمنح الدفء والتغذية مع كل ملعقة. يشكّل العدس المدخن والسبانخ الطازجة قاعدة مشبعة، بينما يضيف تمر كاليفورنيا الحلو بطبيعته نكهة خفيفة ومتوازنة. هذه الشوربة النباتية قليلة الدهون مصدر ممتاز للألياف. للحصول على قوام أكثر كريمية، يمكنك خلط جزء من الشوربة قبل التقديم.","6","1 كوب",
["1 ملعقة كبيرة زيت زيتون","¾ كوب بصل أصفر (مقطع مكعبات)","½ كوب جزر (مقطع مكعبات)","½ كوب كرفس (مقطع مكعبات)","3 فص ثوم (مفروم)","2 ملعقة صغيرة كمون مطحون","2 ملعقة صغيرة كزبرة مطحونة","1 ملعقة صغيرة بابريكا مدخنة","¾ كوب عدس جاف (مغسول)","1 علبة (14.5 أونصة) طماطم مقطعة بدون ملح مضاف","4 كوب مرق خضار غير مملح","2 كوب ماء","1 ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","2 كوب سبانخ طازجة صغيرة الأوراق","2 حبة تمر كاليفورنيا (منزوعة النوى ومفرومة ناعمًا)","1 ملعقة كبيرة عصير ليمون"],
["في قدر كبير، سخّن زيت الزيتون على نار متوسطة. أضف البصل والجزر والكرفس. قلّبها 3–4 دقائق حتى تبدأ بالليونة.","أضف الثوم والكمون والكزبرة والبابريكا. اطهِها 30 ثانية أخرى حتى تفوح رائحتها.","أضف العدس والطماطم ومرق الخضار والماء وحرّك. اتركها حتى تغلي، ثم خفّف النار واتركها على نار هادئة 25–30 دقيقة مع ترك الغطاء مفتوحًا قليلًا حتى ينضج العدس. أضف الملح والفلفل وحرّك.","أضف السبانخ والتمر وحرّك. اطهِها 2–3 دقائق حتى تذبل السبانخ.","أضف عصير الليمون الطازج وحرّك. قدّم الشوربة دافئة."])}))
save(1,I)
