import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/c4')
from h import *
I=[]
I.append((6144571,{
"es":T("Muffins de sidra de manzana","Estos muffins de sidra de manzana ofrecen un toque apto para la diabetes a un clásico del otoño que sabe delicioso en cualquier época del año.","12","1 muffin",
["1 pulverización (0.25 g) de aceite en aerosol antiadherente","1 1/2 tazas de sidra de manzana","2 tazas de harina de trigo integral","1 1/2 cucharaditas de polvo de hornear","1/2 cucharadita de bicarbonato de sodio","1 1/2 cucharaditas de canela molida (dividida)","1/2 cucharadita de nuez moscada molida","3/4 cucharadita de sal kosher","1/2 taza de puré de manzana sin azúcar","1 1/2 cucharadas de sustituto de azúcar bajo en calorías","2 huevos grandes","1/4 taza de aceite de aguacate","1 cucharadita de extracto de vainilla","2 cucharadas de azúcar"],
["Precaliente el horno a 350 grados F. Rocíe ligeramente 2 moldes para muffins de tamaño estándar con aceite en aerosol antiadherente.","Hierva la sidra de manzana en una cacerola a fuego medio hasta que se reduzca a la mitad, hasta que queden unos 3/4 de taza. Deje a un lado para que se enfríe.","En un tazón mediano, bata la harina de trigo integral, el polvo de hornear, el bicarbonato de sodio, 1 cucharadita de la canela molida, la nuez moscada molida y la sal.","En otro tazón, mezcle el puré de manzana sin azúcar, el sustituto de azúcar, los huevos, la sidra de manzana, el aceite de aguacate y el extracto de vainilla.","Incorpore poco a poco los ingredientes secos a los ingredientes húmedos, solo hasta que se mezclen. No mezcle de más. Con una cuchara, vierta la masa en cada cavidad, llenándola aproximadamente dos tercios.","Hornee en el horno precalentado de 15 a 18 minutos, o hasta que un palillo salga limpio.","En un tazón pequeño, mezcle el azúcar granulada y ½ cucharadita de canela molida para preparar el azúcar con canela.","Mientras los muffins se enfrían en el molde, espolvoree ligeramente el azúcar con canela sobre la parte superior.","Deje enfriar en el molde los muffins espolvoreados antes de pasarlos a una rejilla para que se enfríen por completo."]),
"ar":T("مافن عصير التفاح","يقدّم مافن عصير التفاح هذا لمسة مناسبة لمرضى السكري على أحد كلاسيكيات الخريف، وطعمه لذيذ في أي وقت من السنة.","12","1 مافن",
["1 بخة من بخاخ الطهي غير اللاصق، 0.25 غرام","1½ كوب عصير التفاح (سيدر)","2 كوب دقيق القمح الكامل","1½ ملعقة صغيرة بيكنج باودر","½ ملعقة صغيرة بيكربونات الصوديوم","1½ ملعقة صغيرة قرفة مطحونة (مقسّمة)","½ ملعقة صغيرة جوزة الطيب المطحونة","¾ ملعقة صغيرة ملح كوشر","½ كوب صلصة تفاح غير محلاة","1½ ملعقة كبيرة بديل سكر قليل السعرات","2 بيضة كبيرة","¼ كوب زيت أفوكادو","1 ملعقة صغيرة خلاصة الفانيليا","2 ملعقة كبيرة سكر"],
["سخّن الفرن مسبقًا على 350° فهرنهايت (175° مئوية). ادهن 2 صينية مافن بحجم قياسي برفق ببخاخ الطهي غير اللاصق.","اغلِ عصير التفاح (السيدر) في قدر صغير على نار متوسطة حتى ينقص إلى النصف، ليتبقى حوالي ¾ كوب. اتركه جانبًا ليبرد.","في وعاء متوسط، اخفق دقيق القمح الكامل والبيكنج باودر وبيكربونات الصوديوم و1 ملعقة صغيرة من القرفة المطحونة وجوزة الطيب المطحونة والملح.","في وعاء منفصل، اخلط صلصة التفاح غير المحلاة وبديل السكر والبيض وعصير التفاح وزيت الأفوكادو وخلاصة الفانيليا.","أضف المكونات الجافة تدريجيًا إلى المكونات الرطبة مع التحريك حتى تمتزج فقط. لا تبالغ في الخلط. اسكب العجين بالملعقة في كل قالب واملأه حوالي الثلثين.","اخبزه في الفرن المسخّن مسبقًا 15 إلى 18 دقيقة، أو حتى تخرج عود أسنان نظيفًا.","في وعاء صغير، اخلط السكر الناعم و½ ملعقة صغيرة قرفة مطحونة لتحضير سكر القرفة.","وبينما يبرد المافن في الصينية، رش سكر القرفة برفق على الوجه.","اترك المافن المرشوش ليبرد في الصينية قبل نقله إلى رف شبكي ليبرد تمامًا."])}))
I.append((6144849,{
"ar":T("مصاصات الزبادي المجمد بالفاكهة","يمكنك تحضير هذه الوصفة بأي فاكهة وبأي نكهة زبادي. جرّب قطع المانجو مع زبادي الأناناس، أو أنصاف الكيوي مع زبادي الفراولة. ويمكنك أيضًا تجربة إضافات أخرى مثل جوز الهند أو الرشاشات الملونة بدلًا من البيكان.","6","2 مصاصة",
["¼ كوب بيكان (مفروم)","12 عود مصاصات كيك","½ كوب زبادي يوناني بالتوت الأزرق (خالٍ من الدسم)","12 حبة فراولة (منزوعة العنق)","1 ورق شمعي"],
["بطّن صينية خبز صغيرة بورق شمعي. اتركها جانبًا.","أدخل أعواد مصاصات الكيك في الجزء العلوي من الفراولة. لا تخرق الطرف الآخر للفراولة.","اغمس كل فراولة في الزبادي، وهزّها ليتغطى كل منها بطبقة رقيقة. استعن بملعقة لتغطية الفراولة عند الحاجة.","رش 1 ملعقة صغيرة من البيكان فوق كل فراولة مغطاة.","ضع مصاصات الفراولة على صينية الخبز وجمّدها 1–2 ساعة أو حتى يتجمد الزبادي. وبعد أن تتجمد المصاصات، ارفعها عن الورق الشمعي وقدّمها أو ضعها في كيس تجميد بسحاب."])}))
I.append((6145161,{
"es":T("Bastoncitos de zanahoria frescos","Información nutricional de los bastoncitos de zanahoria","1","1 taza",
["1 taza de zanahorias (cortadas en bastoncitos)"],[]),
"ar":T("أعواد الجزر الطازجة","المعلومات الغذائية لأعواد الجزر","1","1 كوب",
["1 كوب جزر (مقطع على شكل أعواد)"],[])}))
I.append((6145357,{
"es":T("Muslos de pollo a la parrilla con jalapeño y durazno, con ensalada cremosa de aguacate y alcachofa","Lleve un sabor de verano a su mesa con estos platos sabrosos que se ajustan al Patrón de Comidas Muy Bajo en Carbohidratos. Este plato es una combinación perfecta de sabores dulces, picantes y cremosos, y es una comida deliciosa para cualquier ocasión.","4","6 onzas de pollo, 1/2 taza de durazno y chiles, 2 tazas de ensalada",
["1 1/2 libras de muslos de pollo deshuesados y sin piel","1/2 cucharadita de pimienta negra","2 cucharaditas de aceite de oliva","2 duraznos pequeños (partidos por la mitad, sin hueso y en rebanadas)","2 chiles jalapeños (sin semillas y picados finamente)","1 limón entero (rallado y exprimido)","1 cucharada de jarabe tipo arce sin azúcar","1 diente de ajo (picado)","2 cucharadas de yogur griego natural sin grasa","1 cucharada de vinagre de sidra de manzana","1 cucharadita de mostaza Dijon","1 cucharadita de albahaca seca","4 onzas de corazones de alcachofa marinados (escurridos y en rebanadas)","1/2 aguacate (partido por la mitad, sin hueso y en rebanadas)","5 onzas de mezcla de lechugas tiernas"],
["Precaliente el horno a 400 grados F.","Seque los muslos de pollo con toallas de papel. Sazone ambos lados con la pimienta.","Caliente un sartén grande que pueda ir al horno a fuego medio-alto. Agregue el aceite de oliva y gire para cubrir el fondo. Coloque el pollo en el sartén y dórelo de un lado hasta que esté dorado, unos 5–6 minutos. Voltee el pollo y retire el sartén del fuego.","Acomode las rebanadas de durazno y los jalapeños picados alrededor del pollo en el sartén.","Rocíe con el jugo de limón, la ralladura y el jarabe sin azúcar. Pase el sartén al horno y hornee de 15 a 18 minutos, o hasta que el pollo esté completamente cocido (temperatura interna de 165 grados F).","Mientras tanto, en un tazón mediano, bata el ajo picado, la mayonesa, el vinagre de sidra de manzana, la mostaza Dijon y la albahaca seca.","Agregue al tazón con el aderezo los corazones de alcachofa en rebanadas y el aguacate. Mezcle suavemente para cubrir. Agregue la mezcla de lechugas tiernas y mezcle de nuevo para combinar.","Reparta la ensalada entre los platos. Cubra con el pollo asado y los duraznos caramelizados."]),
"ar":T("أفخاذ الدجاج المشوية بالهالابينو والخوخ مع سلطة الأفوكادو والخرشوف الكريمية","احصل على نكهة الصيف على مائدتك مع هذه الأطباق اللذيذة التي تناسب النمط الغذائي شديد انخفاض الكربوهيدرات. هذا الطبق مزيج مثالي من النكهات الحلوة والحارة والكريمية، وهو وجبة شهية لكل مناسبة.","4","6 أونصات دجاج، ½ كوب خوخ وفلفل، 2 كوب سلطة",
["1½ رطل أفخاذ دجاج بدون عظم وبدون جلد","½ ملعقة صغيرة فلفل أسود","2 ملعقة صغيرة زيت زيتون","2 حبة خوخ صغيرة (مقطوعة إلى نصفين ومنزوعة النوى ومقطعة شرائح)","2 حبة فلفل هالابينو (منزوعة البذور ومقطعة مكعبات صغيرة جدًا)","1 ليمونة (يُبشر قشرها ويُعصر)","1 ملعقة كبيرة شراب بنكهة القيقب خالٍ من السكر","1 فص ثوم (مفروم)","2 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","1 ملعقة كبيرة خل التفاح","1 ملعقة صغيرة خردل ديجون","1 ملعقة صغيرة ريحان مجفف","4 أونصات قلوب خرشوف متبلة (مصفاة ومقطعة شرائح)","½ حبة أفوكادو (مقطوعة إلى نصفين ومنزوعة النواة ومقطعة شرائح)","5 أونصات خضار سلطة مشكلة"],
["سخّن الفرن مسبقًا على 400° فهرنهايت (200° مئوية).","جفف أفخاذ الدجاج بمناديل ورقية. تبّل الجانبين بالفلفل.","سخّن مقلاة كبيرة تصلح للفرن على نار متوسطة إلى عالية. أضف زيت الزيتون وحرّكه ليغطي القاع. ضع الدجاج في المقلاة وحمّر جانبًا واحدًا حتى يصبح بنيًا ذهبيًا، حوالي 5–6 دقائق. اقلب الدجاج، ثم ارفع المقلاة عن النار.","رتّب شرائح الخوخ والهالابينو المقطع حول الدجاج في المقلاة.","رش عليها عصير الليمون والقشر المبشور والشراب الخالي من السكر. انقل المقلاة إلى الفرن واخبزها 15–18 دقيقة، أو حتى ينضج الدجاج تمامًا (درجة الحرارة الداخلية 165° فهرنهايت (75° مئوية)).","في هذه الأثناء، في وعاء متوسط، اخفق الثوم المفروم والمايونيز وخل التفاح وخردل ديجون والريحان المجفف.","أضف شرائح قلوب الخرشوف والأفوكادو إلى الوعاء مع الصلصة. حرّكها برفق لتتغطى. أضف خضار السلطة المشكلة وحرّك مرة أخرى لتمتزج.","وزّع السلطة على الأطباق. ضع فوقها الدجاج المحمص والخوخ المكرمل."])}))
I.append((6145617,{
"es":T("Quinoa con pimiento rojo","Disfrute esta ensalada de granos y frijoles, perfecta con platos principales sencillos de proteína en la cena y aún mejor en el almuerzo del día siguiente.","5","2/3 taza",
["1/2 taza de quinoa tricolor","1 taza de agua","1/4 taza de cebolla (picada)","2 dientes de ajo (picados)","1 pimiento rojo entero (picado)","2 cucharaditas de aceite de oliva","2 tazas de col rizada (picada)","1/3 taza de frijoles cannellini (escurridos y enjuagados)","1/3 taza de nueces","1 cucharada de jugo de limón","1 cucharada de vinagre balsámico"],
["Cocine la quinoa en agua según las instrucciones del paquete, sin agregar sal.","Mientras se cocina la quinoa, saltee la cebolla, el ajo y el pimiento rojo en aceite de oliva a fuego medio-alto durante unos 10 minutos. Agregue la col rizada y los frijoles y continúe salteando hasta que la col rizada se marchite, unos 5 minutos más.","Incorpore a la quinoa la mezcla de pimiento, las nueces, el vino (o jugo de limón) y el vinagre balsámico. Sirva tibia o fría."]),
"ar":T("كينوا بالفلفل الأحمر","استمتع بهذه السلطة من الحبوب والفاصولياء، وهي مثالية مع أطباق البروتين البسيطة على العشاء وأفضل منها على الغداء في اليوم التالي.","5","⅔ كوب",
["½ كوب كينوا ثلاثية الألوان","1 كوب ماء","¼ كوب بصل (مفروم)","2 فص ثوم (مفروم)","1 حبة فلفل رومي أحمر (مفرومة)","2 ملعقة صغيرة زيت زيتون","2 كوب كرنب أجعد (كيل) (مفروم)","⅓ كوب فاصولياء كانيليني (مصفاة ومغسولة)","⅓ كوب جوز","1 ملعقة كبيرة عصير ليمون","1 ملعقة كبيرة خل بلسمي"],
["اطهُ الكينوا في الماء حسب تعليمات العبوة، مع عدم إضافة أي ملح.","أثناء طهي الكينوا، قلّب البصل والثوم والفلفل الأحمر في زيت الزيتون على نار متوسطة إلى عالية نحو 10 دقائق. أضف الكرنب الأجعد (الكيل) والفاصولياء وواصل التقليب حتى يذبل الكرنب، حوالي 5 دقائق أخرى.","أضف خليط الفلفل والجوز والنبيذ (أو عصير الليمون) والخل البلسمي إلى الكينوا وحرّك. قدّمها دافئة أو باردة."])}))
I.append((6146081,{
"ar":T("محار الإسكالوب البحري المحمر مع الجزر المبروم والبصل المكرمل","الإسكالوب بروتين قليل الدهن جدًا، ومع ذلك فهو رطب وبنكهة تشبه الزبدة، وهو مثالي للمناسبات الخاصة. السر في تحميره بسرعة على حرارة عالية.","4","⅓ كوب معكرونة + 1 كوب من خليط الجزر والإسكالوب",
["1 رطل إسكالوب بحري","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة زيت زيتون (مقسّمة)","1 بصلة كبيرة (مقطعة شرائح رقيقة)","2 فص ثوم (مفروم)","2 جزرة كبيرة (مبرومة على شكل شرائط (أو مقشرة بقشارة الخضار أو مقطعة أعوادًا رفيعة بالمشرحة))","1 ملعقة كبيرة خل النبيذ الأبيض","1 ملعقة كبيرة ثوم معمر (شيف) طازج (مفروم ناعمًا)","1⅓ كوب معكرونة من الحبوب الكاملة أو متعددة الحبوب (مطبوخة)"],
["انزع الزائدة الجانبية من كل إسكالوبة إن لزم. «الزائدة» عضلة جانبية قد تكون ما زالت ملتصقة بالإسكالوب أو لا. تبدو وتُحَسّ كلسان صغير وهي أقسى من الإسكالوب نفسه. وإذا كانت الزائدة ما زالت ملتصقة، اسحبها برفق لإزالتها.","جفف الإسكالوب بمنديل ورقي. تبّل الجانبين بالفلفل.","ضع 1½ ملعقة صغيرة من زيت الزيتون في مقلاة غير لاصقة على نار عالية.","حمّر الإسكالوب من الجانبين حتى ينضج بالكاد، حوالي دقيقتين لكل جانب. أخرجه من المقلاة واتركه جانبًا.","أضف بقية زيت الزيتون إلى المقلاة وخفّف النار إلى متوسطة. أضف البصل وقلّبه حتى يتكرمل، حوالي خمس دقائق.","أضف الثوم والجزر وقلّبهما ثلاث دقائق. أضف الخل واطهِ حتى يتبخر كل السائل.","أضف الإسكالوب وأي عصارة تجمعت إلى الخضار وقلّبها ثلاث دقائق لإنهاء نضج الإسكالوب تمامًا.","أضف الثوم المعمر (الشيف) وحرّك. قدّم 1 كوب من خليط الإسكالوب فوق ⅓ كوب من المعكرونة المصنوعة من القمح الكامل."])}))
I.append((6146598,{
"es":T("Sopa italiana de tomate y albahaca","Esta sopa sencilla es el complemento perfecto para un sándwich de queso a la parrilla o una ensalada fresca. ¡Pero eso no es todo lo que puede hacer con ella! Sírvala sobre pasta como una salsa marinara casera sin azúcar añadida (agregue un poco de ajo y chile rojo triturado para darle más sabor) o sírvala fría como un refrescante acompañamiento de verano.","4","1 taza",
["2 cucharaditas de aceite de oliva","1 cebolla morada pequeña (en cubos)","1 lata (de 28 onzas) de puré de tomate sin sal añadida","1 taza de caldo de verduras bajo en sodio","1/4 cucharadita de sal","1/3 taza de hojas de albahaca fresca (en rebanadas finas)","2 cucharaditas de vinagre balsámico"],
["Caliente el aceite en una cacerola grande a fuego medio. Agregue la cebolla y cocine, revolviendo de vez en cuando, hasta que esté completamente blanda, unos 8 minutos.","Agregue el puré de tomate, el caldo y la sal, y lleve a ebullición a fuego alto. Reduzca el fuego a medio-bajo y cocine a fuego lento, sin tapar, hasta que se mezclen los sabores, unos 5 minutos. (Consejo: para una sopa más ligera, agregue un poco más de caldo.) Incorpore la albahaca y el vinagre.","Sirva con un cucharón en tazones. Sirva caliente o fría."]),
"ar":T("شوربة الطماطم والريحان الإيطالية","هذه الشوربة البسيطة رفيق مثالي لساندويتش الجبن المشوي أو السلطة الطازجة. لكن هذا ليس كل ما يمكنك فعله بها! قدّمها فوق المعكرونة كصلصة مارينارا منزلية بدون سكر مضاف (أضف قليلًا من الثوم والفلفل الأحمر المجروش لمزيد من الحرارة) أو قدّمها باردة كطبق جانبي منعش في الصيف.","4","1 كوب",
["2 ملعقة صغيرة زيت زيتون","1 بصلة حمراء صغيرة (مقطعة مكعبات)","1 علبة (28 أونصة) هريس طماطم بدون ملح مضاف","1 كوب مرق خضار قليل الصوديوم","¼ ملعقة صغيرة ملح","⅓ كوب أوراق ريحان طازجة (مقطعة شرائح رقيقة)","2 ملعقة صغيرة خل بلسمي"],
["سخّن الزيت في قدر كبير على نار متوسطة. أضف البصل واطهِه مع التحريك من حين لآخر حتى يلين تمامًا، حوالي 8 دقائق.","أضف هريس الطماطم والمرق والملح، واتركها حتى تغلي على نار عالية. اخفض النار إلى متوسطة منخفضة واتركها على نار هادئة دون غطاء حتى تمتزج النكهات، حوالي 5 دقائق. (تلميح: للحصول على شوربة أخف قوامًا، أضف مزيدًا من المرق.) أضف الريحان والخل وحرّك.","اغرفها في أطباق. قدّمها ساخنة أو باردة."])}))
I.append((6146820,{
"es":T("Pasta vegetariana con col rizada","Esta pasta vegetariana en un solo sartén lleva trozos de proteína vegetal a base de soya que ofrecen la misma textura y sabor que la carne molida de res. También puede preparar este plato vegano usando un yogur no lácteo. Todo se cocina junto en un solo sartén, por lo que limpiar es muy fácil, ¡perfecto para una comida entre semana!","6","1 ⅓ tazas",
["1 cucharada de aceite de oliva","1 taza de cebolla en cubos","12 onzas de trozos de “carne” molida de res sin carne (de la sección de congelados)","1/3 taza de agua","2 cucharaditas de condimento italiano","1 cucharadita de hojuelas de chile rojo","4 tazas de caldo de verduras bajo en sodio (dividido)","8 onzas de pasta integral de moño (seca)","2 tazas de col rizada (picada)","6 cucharadas de yogur griego natural sin grasa"],
["Caliente el aceite de oliva en un sartén grande a fuego medio. Saltee la cebolla hasta que esté tierna.","Incorpore los trozos de proteína vegetal, el agua y el condimento italiano. Tape y cocine hasta que los trozos estén bien cocidos, unos 4 minutos.","Vierta 2 1/2 tazas de caldo de verduras en la mezcla y lleve a ebullición. Agregue la pasta y cocine, revolviendo de vez en cuando, a fuego medio-alto hasta que se absorba el caldo, unos 10 a 12 minutos.","Agregue el caldo restante, la col rizada y las hojuelas de chile y cocine a fuego medio hasta que la pasta esté lista, unos 14 minutos.","Retire el sartén del fuego e incorpore el yogur griego. Sirva caliente."]),
"ar":T("معكرونة نباتية بالكرنب الأجعد (كيل)","تستخدم هذه المعكرونة النباتية المحضّرة في مقلاة واحدة فتاتًا نباتيًا مصنوعًا من الصويا يمنح القوام والنكهة نفسيهما للحم البقر المفروم. ويمكنك أيضًا جعل هذا الطبق نباتيًا بالكامل باستخدام زبادي غير لبني. كل شيء يُطهى معًا في مقلاة واحدة مما يجعل التنظيف سهلًا، وهو مثالي لوجبة في أيام الأسبوع!","6","1⅓ كوب",
["1 ملعقة كبيرة زيت زيتون","1 كوب بصل مقطع مكعبات","12 أونصة فتات «لحم بقر» مفروم نباتي (من قسم المجمدات)","⅓ كوب ماء","2 ملعقة صغيرة توابل إيطالية","1 ملعقة صغيرة رقائق الفلفل الأحمر الحار","4 كوب مرق خضار قليل الصوديوم (يُستخدم على مرحلتين)","8 أونصات معكرونة فراشة من القمح الكامل (جافة)","2 كوب كرنب أجعد (كيل) (مفروم)","6 ملاعق كبيرة زبادي يوناني سادة خالٍ من الدسم"],
["سخّن زيت الزيتون في مقلاة كبيرة على نار متوسطة. قلّب البصل حتى يلين.","أضف الفتات النباتي والماء والتوابل الإيطالية وحرّك. غطِّ المقلاة واطهِ حتى ينضج الفتات تمامًا، حوالي 4 دقائق.","اسكب 2½ كوب من مرق الخضار على الخليط واتركه حتى يغلي. أضف المعكرونة واطهِها مع التحريك من حين لآخر على نار متوسطة إلى عالية حتى يُمتص المرق، حوالي 10 إلى 12 دقيقة.","أضف بقية المرق والكرنب الأجعد (الكيل) ورقائق الفلفل الحار واطهِها على نار متوسطة حتى تنضج المعكرونة، حوالي 14 دقيقة.","ارفع المقلاة عن النار وأضف الزبادي اليوناني وحرّك. قدّمها ساخنة."])}))
I.append((6147388,{
"ar":T("سمك البلطي المقرمش بالبيكان","طبق البلطي الخفيف الطري هذا فيه قرمشة لطيفة، وهو طبق رئيسي رائع لعيد الحب أو أي يوم آخر من الشهر!","2","3 أونصات",
["2 ملعقة كبيرة دقيق الذرة الأصفر","2 ملعقة كبيرة بانكو أو فتات خبز جاف عادي","1 ملعقة صغيرة نشا الذرة","½ ملعقة صغيرة فلفل بالليمون (خالٍ من الملح)","2 سمكة بلطي (حوالي 4 أونصات لكل منها، مغسولة ومجففة)","2 ملعقة صغيرة عصير ليمون طازج","2 ملعقة كبيرة بيكان (مفروم فرمًا خشنًا، محمص جافًا)","1 ملعقة كبيرة بقدونس إيطالي (مسطح الأوراق) طازج (مقصوص)"],
["سخّن الشواية العلوية مسبقًا. رش طبق خبز بحجم 11×7×2 بوصة برفق ببخاخ الطهي.","في طبق مسطح، اخلط دقيق الذرة والبانكو والنشا والفلفل بالليمون. أضف السمك وقلّبه ليتغطى، ثم انفض الزائد. انقله إلى طبق الخبز. رش جانبي السمك برفق ببخاخ الطهي.","اشوِه تحت الشواية العلوية 3–4 دقائق لكل جانب، أو حتى يتفتت السمك بسهولة عند اختباره بالشوكة. انقله إلى الأطباق. رش عليه عصير الليمون. رش البيكان والبقدونس.","​"][:3]),
}))
I.append((6149233,{
"ar":T("سلطة الشمندر المحمص والدجاج بجبن الماعز","لتوفير الوقت، يمكنك استخدام لحم صدر دجاج مشوي (روتيسري) من متجر البقالة لتحضير هذه الوصفة.","4","1 سلطة",
["1 بخة من بخاخ الطهي غير اللاصق، 0.25 غرام","4 حبات شمندر صغيرة","12 أونصة صدور دجاج بدون عظم وبدون جلد","¼ ملعقة صغيرة فلفل أسود","¼ كوب خل بلسمي","1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة مرق خضار قليل الصوديوم","1 ملعقة كبيرة عسل أو 2 ظرف مُحلٍّ صناعي","2 ملعقة صغيرة خردل ديجون","1 فص ثوم (مفروم أو مبشور)","8 كوب خليط سلطة ميسكلان","2 ملعقة كبيرة جبن ماعز مفتت","⅓ كوب لوز شرائح (محمص)"],
["سخّن الفرن مسبقًا على 375° فهرنهايت (190° مئوية). ادهن صينية خبز ببخاخ الطهي. اتركها جانبًا.","لُفّ الشمندر بورق الألمنيوم وضعه على صينية الخبز. ضع صدور الدجاج على الصينية بجانب الشمندر. ادهن الدجاج ببخاخ الطهي وتبّله بالملح (اختياري) والفلفل الأسود. حمّص الدجاج والشمندر 25–30 دقيقة أو حتى تصل درجة الحرارة الداخلية للدجاج إلى 165° فهرنهايت (75° مئوية). أخرج صدور الدجاج من الفرن واتركها جانبًا. وعندما تبرد قليلًا، قطّع الدجاج إلى شرائح رقيقة.","واصل تحميص الشمندر حتى يلين، 15–20 دقيقة أخرى. أخرج الشمندر من الفرن واتركه جانبًا.","عندما يبرد الشمندر، قشّره وقطّع كل حبة إلى قطع بحجم ½ بوصة.","في وعاء متوسط، اخفق الخل البلسمي وزيت الزيتون ومرق الخضار والعسل وخردل ديجون والثوم.","ضع الجرجير وقطع الشمندر في وعاء كبير. اسكب الصلصة فوق السلطة وقلّبها لتتغطى.","وزّع السلطة على 4 أطباق. ضع فوق كل سلطة ¼ شرائح صدر الدجاج و1 ملعقة كبيرة جبن ماعز و1 ملعقة كبيرة لوز شرائح."])}))
I.append((6149915,{
"ar":T("القرنبيط المحمص","لست من محبي الخضار؟ جرّب تحميص خضارك. تحميص الخضار من أسهل الطرق وأشهاها لتحضيرها.","6","½ كوب",
["1 بخة من بخاخ الطهي غير اللاصق، 0.25 غرام","1 رأس قرنبيط (مقطع إلى زهيرات صغيرة)","2 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح"],
["سخّن الفرن مسبقًا على 425° فهرنهايت (220° مئوية). رش صينية خبز ببخاخ الطهي.","في وعاء صغير، اخلط القرنبيط وزيت الزيتون والفلفل الأسود والملح. اسكب الخليط على صينية الخبز.","اخبزه 15–20 دقيقة حتى تصبح أطراف القرنبيط بنية قليلًا وطرية."])}))
I.append((6149928,{
"ar":T("دجاج محشو بالسبانخ والفطر","هذا الطبق مصدر جيد للبروتين ويوفر أيضًا بعض الخضار. ورغم سرعة تحضيره، فإن مظهره أنيق، وسيُبهر ضيوفك بتقديمه وطعمه بلا شك!","4","1 صدر دجاج",
["1 بخة من بخاخ الطهي غير اللاصق، 0.25 غرام","1 ملعقة كبيرة زيت زيتون","½ كوب سبانخ مجمدة (مفرومة، مذابة ومصفاة)","1 كوب فطر أبيض (فطر الأزرار) (مفروم ناعمًا)","1 فص ثوم (مفروم)","4 صدور دجاج بدون عظم وبدون جلد (4 أونصات لكل منها)","4 أقراص جبن خفيف بالثوم والأعشاب","¼ ملعقة صغيرة فلفل أسود","½ ملعقة صغيرة بابريكا","4 أعواد أسنان"],
["سخّن الفرن مسبقًا على 350° فهرنهايت (175° مئوية). رش طبق الخبز ببخاخ الطهي.","ضع الزيت في مقلاة متوسطة على نار متوسطة إلى عالية. أضف السبانخ وقلّبها 3 دقائق. أضف الفطر واطهِه 4–5 دقائق أخرى. أضف الثوم وقلّبه 30 ثانية.","ضع صدر دجاج واحدًا على لوح التقطيع وغطِّه بغلاف بلاستيكي. اطرق الدجاج بمطرقة اللحم أو بشوبك حتى يصبح سمكه حوالي ¼ بوصة. كرر العملية مع صدور الدجاج الـ3 الأخرى.","افرد 1 قرص جبن Laughing Cow على أحد جانبي صدر دجاج واحد. ضع ¼ كوب من خليط السبانخ والفطر فوق الجبن. لُفّ صدر الدجاج وثبّت الحافة بعود أسنان. كرر هذه العملية مع صدور الدجاج الـ3 المتبقية.","رش صدور الدجاج بالفلفل والبابريكا. ضع صدور الدجاج الملفوفة في طبق الخبز واخبزها 30–40 دقيقة أو حتى تنضج.","عند التقديم، انزع أعواد الأسنان وقطّع كل صدر إلى 5 شرائح دائرية."])}))
I.append((6150171,{
"ar":T("روبيان مشوي بالحمضيات مع خضار الربيع","طبق خفيف وسهل، وهذا الروبيان المشوي غني بالنكهات. يمكن تناوله وحده أو مع طبق جانبي غير نشوي مثل أرز القرنبيط.","4","4 روبيانات + 1 كوب سلطة",
["2 بخة، 0.5 غرام من بخاخ الطهي غير اللاصق (تُستخدم على مرحلتين)","2 حبة كلمنتين صغيرة (معصورة)","1 ليمونة خضراء صغيرة (معصورة)","⅛ ملعقة صغيرة صلصة حارة","1 فص ثوم (مفروم)","¼ ملعقة صغيرة فلفل","16 روبيانة كبيرة (نيئة)","4 كوب خضار سلطة مشكلة ربيعية","2 حبة كلمنتين صغيرة (مقشرة ومفصصة)","2 ملعقة كبيرة زيت زيتون (للصلصة)","2 حبة كلمنتين صغيرة (معصورة، للصلصة)"],
["في وعاء متوسط، اخفق عصير البرتقال والليمون الأخضر والصلصة الحارة والثوم والفلفل. أضف الروبيان إلى الوعاء وضعه في الثلاجة ليتتبّل 20 دقيقة.","جهّز شواية داخلية أو خارجية على حرارة متوسطة. رش رف الشواية ببخاخ الطهي.","ضع الروبيان على أسياخ واشوِه 2–3 دقائق لكل جانب أو حتى ينضج.","قدّم الروبيان فوق سلطة الخضار المشكلة مع شرائح الكلمنتين.","اخفق مكونات الصلصة معًا واسكبها فوق الروبيان والسلطة."])}))
save(3,I)
