from lib import *
I=[]
I.append(R(6223265,"Haricots verts rôtis et sauce crémeuse aux champignons",
"Comme dans un gratin de haricots verts, ces haricots verts rôtis et tendres s'accompagnent à merveille d'une sauce crémeuse aux champignons maison dans cet accompagnement adapté aux personnes diabétiques.",
"6","1 tasse",
["1 lb de haricots verts frais (frais, extrémités coupées)","3 c. à soupe d'huile d'olive (divisées)","1/4 c. à café de sel","1/2 c. à café de poivre noir","1 tasse de champignons cremini (bruns) (tranchés)","2 c. à soupe de farine tout usage","1 tasse de bouillon de légumes","1/2 tasse de lait à 1 %","2 gousses d'ail (hachées)"],
["Préchauffez le four à 425 degrés F.","Mélangez les haricots verts parés avec 1 c. à soupe d'huile d'olive, le sel et le poivre noir.","Étalez les haricots verts en une seule couche sur une plaque de cuisson.","Faites rôtir au four préchauffé pendant 20 minutes, ou jusqu'à ce que les haricots verts soient tendres mais croquants et légèrement caramélisés, en les remuant à mi-cuisson.","Pendant que les haricots verts rôtissent, préparez la sauce aux champignons.","Pour la sauce crémeuse aux champignons : dans une poêle, chauffez 2 c. à soupe d'huile d'olive à feu moyen.","Ajoutez les champignons cremini tranchés dans la poêle et faites-les sauter jusqu'à ce qu'ils rendent leur eau et deviennent dorés.","Saupoudrez les champignons de farine et remuez sans arrêt pendant 1 à 2 minutes pour former un roux.","Incorporez progressivement le bouillon de légumes et le lait dans la poêle en fouettant, de façon à éviter les grumeaux.","Ajoutez l'ail haché, le sel et le poivre noir. Remuez sans arrêt jusqu'à ce que la sauce épaississe.","Réduisez le feu et laissez mijoter la sauce 2 à 3 minutes de plus.","Retirez la sauce du feu.","Pour finir, une fois les haricots verts rôtis, transférez-les dans un plat de service et nappez-les de sauce crémeuse aux champignons."]))
I.append(R(6223318,"Chou-fleur rôti au parmesan",
"Rehaussez votre chou-fleur rôti avec du parmesan onctueux. Cette recette d'inspiration italienne est une excellente option pauvre en glucides à ajouter à votre dîner.",
"6","1/2 tasse",
["1 tête de chou-fleur (grosse, coupée en bouquets)","2 c. à soupe d'huile d'olive","1/2 tasse de parmesan (râpé)","1 c. à café d'ail en poudre","1 c. à café de thym séché","1/4 c. à café de sel","1/2 c. à café de poivre noir"],
["Préchauffez le four à 425 degrés F.","Dans un grand bol, mélangez les bouquets de chou-fleur avec l'huile d'olive, le parmesan râpé, l'ail en poudre, le thym séché, le sel et le poivre noir jusqu'à ce qu'ils soient bien enrobés.","Étalez le chou-fleur en une seule couche sur une plaque de cuisson.","Faites rôtir au four préchauffé pendant 25 minutes, ou jusqu'à ce que le chou-fleur soit doré et croustillant, en le remuant à mi-cuisson.","Sortez le chou-fleur du four.","Transférez le chou-fleur dans un plat de service.","Servez le chou-fleur comme accompagnement savoureux et adapté aux personnes diabétiques."]))
I.append(R(6224028,"Salade de crevettes à la roquette et au citron",
"Cette salade pétillante et pauvre en glucides, préparée avec des ingrédients frais et délicieux, fait un délicieux déjeuner de printemps ou d'été.",
"2","2 tasses de salade + 3 oz de crevettes et environ 1 cuillère à soupe de vinaigrette",
["1 c. à soupe de jus de citron","1 c. à soupe d'huile d'olive extra vierge","1 c. à café de vinaigre de vin blanc","1/4 c. à café de poivre noir","1/4 c. à café de sirop multi-usage sans sucre","6 oz, soit environ 12 grosses crevettes (cuites)","4 tasses de roquette","1 c. à soupe de parmesan (en copeaux)","2 c. à café de pignons de pin (grillés)"],
["Cette salade pétillante et pauvre en glucides, préparée avec des ingrédients frais et délicieux, fait un délicieux déjeuner de printemps ou d'été.","Vous pouvez aussi mettre tous les ingrédients dans un petit bocal, le fermer hermétiquement et secouer.","Montez la salade. Répartissez la roquette entre 2 assiettes. Garnissez chacune de 3 oz de crevettes. Parsemez les salades de 1/2 du parmesan et de 1/2 des pignons de pin.","Arrosez les salades de vinaigrette."]))
I.append(R(6224700,"Bruschetta aux lentilles",
"Pour réduire les glucides de cette recette, servez la bruschetta dans des feuilles d'endive plutôt que sur de la baguette. La recette sera aussi sans gluten.",
"14","2 morceaux",
["1/2 tasse de lentilles brunes (sèches)","2 tasses d'eau chaude","2 tomates moyennes (épépinées et coupées en dés)","1 poivron rouge moyen (épépiné et coupé en dés)","1/2 tasse d'oignon rouge (coupé en dés)","1/2 concombre anglais moyen ((sans pépins ou de serre), coupé en dés)","1 gousse d'ail (hachée)","1 c. à soupe de coriandre fraîche (hachée)","2 c. à soupe de vinaigre de vin rouge","1 c. à soupe d'huile d'olive","1/4 c. à café de flocons de piment rouge broyés","1/4 tasse de feta (allégée en matières grasses, émiettée)","1/2 c. à café de poivre noir","1 baguette multicéréales entière (coupée en 28 tranches d'environ 1/4 pouce d'épaisseur)","1 vaporisation, 0.25 g de spray de cuisson antiadhésif"],
["Préchauffez le four à 350 degrés F.","Dans une casserole moyenne, mélangez les lentilles et l'eau chaude. Portez à ébullition à feu vif, puis réduisez le feu et laissez mijoter, sans couvercle, pendant 20 minutes.","Pendant la cuisson des lentilles, mélangez les tomates, le poivron rouge, l'oignon rouge, le concombre, l'ail, la coriandre, le vinaigre de vin rouge, l'huile d'olive, les flocons de piment rouge broyés, la feta et le poivre noir moulu. Remuez pour bien mélanger et mettez de côté.","Disposez les tranches de baguette sur une grande plaque de cuisson. Vaporisez légèrement le dessus des tranches de pain de spray de cuisson. Faites cuire sur la grille supérieure du four pendant 10 minutes. Laissez refroidir. (Voir la note à l'étape 6.)","Quand les lentilles sont cuites, égouttez-les et rincez-les à l'eau froide. Secouez la passoire pour éliminer toute l'eau des lentilles, puis ajoutez-les au mélange de bruschetta et remuez pour bien mélanger.","Pour servir, mettez le mélange de bruschetta dans un bol de service et disposez les tranches de baguette grillées autour du bol pour une bruschetta en libre-service, ou garnissez chaque tranche de baguette grillée de 2 c. à soupe bombées de mélange de bruschetta. Remarque : si vous prévoyez de servir la bruschetta sur la baguette, vous pouvez griller le pain un peu plus longtemps pour éviter qu'il ne ramollisse."]))
I.append(R(6225448,"Aubergine rôtie à l'italienne",
"Une aubergine tendre, rôtie à la perfection avec des herbes italiennes aromatiques, est un délicieux moyen, adapté aux personnes diabétiques, d'ajouter des légumes non féculents à votre repas.",
"2","1 tasse",
["1 grosse aubergine (coupée en dés de 1 pouce)","2 c. à soupe d'huile d'olive","1 c. à café d'assaisonnement italien","1/8 c. à café de sel","1/4 c. à café de poivre noir"],
["Préchauffez votre four à 375 degrés F et recouvrez une plaque de cuisson de papier sulfurisé.","Arrosez l'aubergine d'huile d'olive et saupoudrez d'assaisonnement italien, de sel et de poivre.","Faites rôtir pendant 20 à 25 minutes, jusqu'à ce que l'aubergine soit légèrement dorée et fondante à l'intérieur."]))
I.append(R(6225659,"Poulet braisé à la marocaine",
"Ajoutez une saveur exotique à votre poulet avec ce poulet braisé à la marocaine. Parfaitement épicé, il est meilleur servi avec des légumes non féculents ou essayez-le avec du riz de chou-fleur !",
"6","3 onces de poulet",
["4 c. à soupe d'huile d'avocat (divisées)","1 lb de cuisses de poulet (sans peau)","1/2 c. à café de gros sel casher","1 c. à café de poivre noir","1 petit oignon jaune (coupé en dés)","2 gousses d'ail (hachées)","1 c. à soupe de coriandre moulue","1 c. à soupe de cumin moulu","1 1/2 c. à café de paprika fumé","1/2 c. à café de curcuma","1/2 c. à café de poivre de Cayenne","2 tasses de bouillon de poulet à faible teneur en sodium","2 boîtes de tomates en dés en conserve (sans sel ajouté)","8 oz de champignons de Paris blancs (tranchés)","2 poivrons rouges moyens (tranchés)","1 citron entier (zeste râpé)"],
["Chauffez 2 cuillères à soupe d'huile dans une cocotte en fonte ou une grande marmite à feu moyen-vif.","Épongez le poulet et assaisonnez les deux faces de sel casher et de poivre. Déposez-le dans la marmite (en plusieurs fois si nécessaire) et faites-le dorer des deux côtés, en le transférant dans une assiette ou un bol à mesure qu'il est saisi.","Ajoutez l'oignon dans la poêle et faites-le cuire jusqu'à ce qu'il soit légèrement ramolli et translucide, environ 5 minutes. Ajoutez l'ail, la coriandre, le cumin, le paprika, le curcuma et le poivre de Cayenne et remuez pour mélanger. Faites cuire 1 minute, ou jusqu'à ce que les épices soient aromatiques et légèrement grillées.","Remettez le poulet dans la marmite et remuez pour l'enrober du mélange d'épices.","Versez les tomates en dés et assez de bouillon de poulet pour couvrir les morceaux de poulet aux deux tiers.","Portez le liquide à frémissement, couvrez et laissez mijoter à feu moyen-doux pendant 15 à 20 minutes.","Ajoutez les champignons, les poivrons rouges tranchés et le zeste de citron. Couvrez et poursuivez la cuisson 10 à 15 minutes de plus, jusqu'à ce que la sauce ait légèrement réduit."]))
I.append(R(6226156,"Demi-tomate","Informations nutritionnelles pour 1/2 tomate","1","1/2 tomate",["1/2 tomate entière"],[]))
I.append(R(6226195,"Chilla pakistanais au besan (crêpes salées aux pois chiches)",
"Envie de plus de saveur au petit-déjeuner ? Essayez ce petit-déjeuner traditionnel pakistanais, riche en épices savoureuses. Ces crêpes sont une excellente source de fibres et apportent une portion de protéines maigres, ce qui peut aider à maintenir stable la glycémie (taux de sucre dans le sang).",
"4","1 crêpe",
["1 tasse de farine de pois chiches (besan)","1/2 c. à café de curcuma","1/4 c. à café de piment rouge en poudre","1/4 c. à café de cumin moulu","1 tasse d'eau","1/2 tasse d'oignon (coupé en dés)","1/2 tasse de carottes (râpées)","1/4 tasse de coriandre (hachée)","1/2 c. à café de sel","1 c. à café d'huile d'olive (divisée)","1/4 tasse de yaourt grec nature sans gras"],
["Mélangez dans un bol la farine de pois chiches, le curcuma, le piment en poudre, le cumin et le sel. Incorporez progressivement l'eau en fouettant jusqu'à ce que la pâte soit lisse.","Incorporez délicatement l'oignon, la carotte et la coriandre.","Chauffez une poêle antiadhésive avec 1/4 c. à café d'huile à feu moyen. Versez 1/4 tasse de pâte et étalez-la en une crêpe mince. Faites cuire 2 à 3 minutes de chaque côté. Répétez avec le reste de la pâte.","Servez chaud, accompagné de yaourt grec faible en gras."]))
I.append(R(6226273,"Nachos de patate douce à la friteuse à air",
"La friteuse à air permet de préparer facilement des chips de patate douce maison croustillantes et pauvres en matières grasses. Garnir ces nachos riches en légumes de légumes hachés surgelés rend ce plat rapide et facile à préparer ; il peut servir d'entrée pour une assemblée ou de plat principal végétarien.",
"4","1 tasse",
["1 patate douce moyenne (coupée en chips de 1/8 pouce d'épaisseur)","2 vaporisations, 0.5 gramme de spray de cuisson antiadhésif","1 1/2 tasse de mélange surgelé de poivrons et d'oignons (partiellement décongelé et égoutté)","1 piment jalapeño entier (fendu en deux dans la longueur et épépiné)","1/4 tasse de cheddar ou de fromage de style mexicain râpé allégé en matières grasses","1/4 tasse de salsa","2/3 tasse de radis (finement tranchés)","4 tomates cerises entières (coupées en quatre)","1/2 tasse de laitue romaine (émincée)","2 c. à soupe de crème aigre légère","1 c. à soupe de coriandre fraîche (ciselée)"],
["Disposez uniformément les tranches de patate douce dans le panier de la friteuse à air. Vaporisez de spray de cuisson antiadhésif pendant 1 seconde. Répartissez uniformément les légumes surgelés sur les pommes de terre. Placez le jalapeño sur les légumes, côté peau vers le haut. Vaporisez de spray de cuisson antiadhésif pendant 1 seconde.","Réglez la température à 375° F et faites cuire à l'air chaud pendant 20 minutes, ou jusqu'à ce que les pommes de terre soient cuites. Elles doivent être tendres mais croustillantes, et non molles. Retirez le piment jalapeño et mettez-le dans un bol ; couvrez-le sans serrer d'un torchon et laissez reposer 5 minutes.","Parsemez uniformément le fromage sur les légumes. Faites cuire à l'air chaud pendant 2 minutes, ou jusqu'à ce que le fromage soit fondu.","À l'aide de la pointe d'un couteau bien aiguisé, retirez la peau dorée ou carbonisée du piment jalapeño. Hachez finement le piment.","À l'aide d'une spatule, soulevez les pommes de terre et les légumes hors du panier de la friteuse à air et disposez-les en une couche uniforme sur un plat de service. Parsemez les légumes de jalapeño haché. Garnissez de salsa, de radis, de tomates et de laitue. Ajoutez une cuillérée de crème aigre et un peu de coriandre. Servez immédiatement."]))
I.append(R(6226659,"Chou cavalier sauté, rapide et facile",
"Découvrez la préparation rapide et sans effort du chou cavalier sauté, où de beaux légumes verts sont délicatement cuits à la perfection, pour un accompagnement rapide et facile à la fois nutritif et savoureux.",
"4","1/2 tasse",
["2 c. à soupe d'huile d'olive","2 gousses d'ail (hachées)","1/2 c. à café de flocons de piment rouge moulus (facultatif)","1 botte de chou cavalier (tiges retirées et feuilles hachées)","1/4 c. à café de sel","1/4 c. à café de poivre noir","1 c. à soupe de vinaigre de cidre de pomme"],
["Chauffez l'huile d'olive dans une grande poêle à feu moyen.","Ajoutez l'ail et les flocons de piment rouge, si vous en utilisez, dans la poêle. Faites sauter 1 à 2 minutes, jusqu'à ce que l'ail soit parfumé.","Ajoutez le chou cavalier dans la poêle. Mélangez pour l'enrober d'ail et d'huile.","Faites sauter le chou cavalier pendant 5 à 7 minutes, ou jusqu'à ce qu'il soit flétri et tendre.","Assaisonnez de sel et de poivre noir.","Arrosez le chou cavalier de vinaigre de cidre de pomme. Mélangez.","Poursuivez la cuisson 2 à 3 minutes de plus pour permettre aux saveurs de se mêler."]))
I.append(R(6226902,"Huile d'herbes de tous les jours",
"Cette huile d'olive infusée aux herbes est une excellente base pour une vinaigrette ou un assaisonnement simple pour le poisson, le poulet ou les légumes. Pour cette recette, j'utilise un mélange de persil, d'origan, de romarin et de thym, mais n'hésitez pas à essayer les herbes que vous avez sous la main ou qui poussent dans votre jardin d'herbes aromatiques.\n\nTrouvez cette recette et bien d'autres dans notre livre de cuisine Whole Cooking and Nutrition !",
"32","1 c. à soupe",
["2 tasses d'huile d'olive extra vierge","6 brins (1.5 c. à soupe) de thym frais (tiges retirées et jetées)","2 brins (1 c. à soupe) de romarin frais (tiges retirées et jetées)","4 brins (2 c. à soupe) d'origan frais (tiges retirées et jetées)","1 tasse de persil frais"],
["Portez à ébullition une casserole moyenne d'eau. Remplissez un bol moyen d'eau glacée et placez-le à proximité.","Ajoutez les feuilles de persil, d'origan, de romarin et de thym dans l'eau bouillante. Blanchissez les herbes 10 à 15 secondes, puis retirez-les aussitôt à l'aide d'une écumoire et plongez-les dans l'eau glacée. Après quelques secondes, retirez les herbes de l'eau glacée à l'aide d'une écumoire et épongez-les avec du papier absorbant.","Dans un mélangeur ou un robot culinaire, réduisez en purée les herbes blanchies avec l'huile d'olive.","Versez l'huile d'herbes dans une bouteille ou un bocal en verre foncé muni d'un couvercle hermétique, fermez le contenant et placez-le dans un endroit frais et sombre (comme votre garde-manger) pour laisser infuser au moins 5 jours. Une fois l'huile bien infusée, conservez-la au réfrigérateur jusqu'à 1 à 2 semaines. Vous pouvez aussi congeler l'huile d'herbes dans des bacs à glaçons pour un usage ultérieur. (Notez que chaque glaçon contient 2 cuillères à soupe d'huile.)"]))
I.append(R(6227796,"Coupe de yaourt aux myrtilles et aux graines de tournesol",
"Cette coupe de yaourt simple et rafraîchissante superpose du yaourt grec sans gras onctueux, des myrtilles juteux et une pincée de graines de tournesol croquantes. C'est une collation individuelle rapide et riche en nutriments qui offre une douceur naturelle, de la texture et un équilibre satisfaisant en quelques minutes.",
"1","1 tasse",
["2/3 tasse de yaourt grec nature sans gras","1/2 tasse de myrtilles","1 c. à soupe de graines de tournesol"],
["Versez à la cuillère 2/3 tasse de yaourt grec sans gras dans un bol ou une coupe.","Ajoutez 1/2 tasse de myrtilles sur le dessus.","Parsemez de 1 cuillère à soupe de graines de tournesol.","Dégustez immédiatement, ou laissez refroidir quelques minutes si vous le préférez bien froid."]))
save(1,I)
