from lib import *
I=[]
I.append(R(6228270,"Frites de navet au four",
"Vous aimez les frites fraîches ? Essayez cette alternative plus pauvre en glucides : des frites de navet au four ! Cuits au four, les navets deviennent parfaitement croustillants, pour un accompagnement adapté aux personnes diabétiques.",
"6","1/2 tasse",
["4 navets moyens (pelés et coupés en bâtonnets ou en quartiers)","2 c. à soupe d'huile d'olive","1 c. à café d'ail en poudre","1 c. à café d'oignon en poudre","1/2 c. à café de paprika fumé","1/2 c. à café de sel","1/4 c. à café de poivre noir"],
["Préchauffez le four à 425 degrés F. Tapissez une plaque de cuisson de papier sulfurisé.","Dans un grand bol, mélangez les bâtonnets ou quartiers de navet avec l'huile d'olive jusqu'à ce qu'ils soient bien enrobés.","Étalez les navets en une seule couche sur une plaque de cuisson.","Saupoudrez les navets d'ail en poudre, d'oignon en poudre, de paprika fumé, de sel et de poivre noir. Mélangez pour bien les enrober.","Faites cuire au four préchauffé pendant 20 à 25 minutes, ou jusqu'à ce que les frites de navet soient dorées et croustillantes, en les retournant à mi-cuisson.","Sortez du four et laissez refroidir quelques minutes avant de servir."]))
I.append(R(6228432,"Crème glacée au chocolat sans produits laitiers",
"Les bananes, l'avocat et le lait de coco sont les ingrédients secrets de cette recette. Pour en faire une mousse, mettez-la simplement au réfrigérateur au lieu du congélateur et servez-la avec une cuillérée de crème fouettée légère et des baies fraîches sur le dessus.",
"8","1/4 tasse",
["2 bananes moyennes (mûres)","2 avocats moyens (mûrs)","1/3 tasse de lait de coco léger","1/3 tasse de poudre de cacao","1/4 tasse de substitut de sucre faible en calories"],
["Mettez tous les ingrédients dans un robot culinaire ou un mélangeur et mixez jusqu'à obtention d'une texture parfaitement lisse, en raclant de temps en temps les parois du robot.","Si vous avez une sorbetière, mixez le mélange dans la sorbetière pendant 10 minutes, puis transférez-le dans un contenant et mettez-le au congélateur. Si vous n'avez pas de sorbetière, transférez simplement le mélange dans un contenant et congelez-le.","Pour servir, sortez la crème glacée du congélateur environ 20 minutes avant de servir pour qu'elle ramollisse légèrement et soit plus facile à servir à la cuillère."]))
I.append(R(6229237,"Bol de yaourt grec aux myrtilles et au lin",
"Informations nutritionnelles pour un bol de yaourt grec aux myrtilles et au lin","1","1 3/4 tasse",
["2/3 tasse de yaourt grec nature","1 tasse de myrtilles","1 c. à soupe de graines de lin moulues"],
["Versez le yaourt grec à la cuillère dans un bol de service de taille moyenne.","Garnissez le yaourt de myrtilles.","Parsemez uniformément de graines de lin.","Mélangez tous les ingrédients jusqu'à ce qu'ils soient bien incorporés et servez immédiatement."]))
I.append(R(6229594,"Congee de riz brun aux herbes sautées",
"Le congee est une bouillie de riz traditionnelle. On le mange habituellement au petit-déjeuner, mais on peut aussi le déguster à tout moment de la journée. C'est un excellent moyen de faire durer une petite quantité de riz, et il peut être accompagné de viande, de poisson, de légumes ou d'œufs.",
"6","1 tasse",
["2 pintes d'eau filtrée","1 tasse de riz à sushi brun","1 c. à soupe d'huile de pépins de raisin","2 oz de gingembre frais (pelé et coupé en fine julienne)","2 oignons verts (ciboules) entiers (parés et coupés en julienne en morceaux de 1 pouce de long)","2 piments thaï rouges entiers (tiges et graines retirées, coupés en fines rondelles)","1/2 botte, environ 1 tasse de coriandre (tiges retirées et grossièrement hachée)"],
["Remplissez une grande marmite d'eau. Ajoutez le riz, couvrez et portez à ébullition à feu vif. Réduisez à feu moyen et poursuivez la cuisson jusqu'à ce que les grains de riz se défassent et que la soupe épaississe, environ 1 heure.","Pendant ce temps, dans une petite poêle à feu vif, versez l'huile et faites sauter le gingembre, les oignons verts et les piments jusqu'à ce qu'ils soient parfumés et légèrement dorés, 30 à 45 secondes. Ajoutez la coriandre et continuez à faire sauter jusqu'à ce qu'elle soit tout juste flétrie, environ 30 secondes de plus. Transférez dans un bol.","Versez un peu de congee à la louche dans 6 bols individuels et garnissez chacun d'environ 1 c. à soupe d'herbes sautées. Mélangez les herbes à la bouillie pour répartir les saveurs. Servez."]))
I.append(R(6229691,"Poulet balsamique aux champignons",
"Ce plat de poulet simple est économique et constitue un excellent point de départ pour une assiette saine. Servez-le avec un accompagnement de légumes simple, comme les haricots verts faciles à la moyen-orientale.",
"4","1 poitrine de poulet avec 1/4 tasse bombée de champignons",
["1 lb de poitrine de poulet désossée et sans peau (divisée en 4 portions de 4 oz)","1 c. à soupe d'huile d'olive","1/4 tasse de farine tout usage","1 c. à soupe de margarine (sans gras trans)","10 oz de champignons de Paris blancs (tranchés)","1/4 c. à café de poivre noir","1/3 tasse de vinaigre balsamique","1/2 tasse de bouillon de poulet à faible teneur en sodium"],
["Placez la poitrine de poulet dans un sac en plastique et aplatissez-la en fine tranche avec un maillet.","Chauffez l'huile d'olive à feu moyen-vif dans une poêle.","Passez le poulet dans la farine pour l'enrober des deux côtés. Mettez le poulet dans la poêle et faites-le sauter 5 minutes de chaque côté. Retirez le poulet de la poêle et mettez-le de côté.","Faites fondre la margarine dans la poêle. Ajoutez les champignons et le poivre et faites cuire 5 minutes. Ajoutez le vinaigre balsamique dans la poêle et portez à ébullition pour réduire le liquide.","Ajoutez le bouillon de poulet dans la poêle et laissez mijoter 2 minutes de plus. Remettez la poitrine de poulet dans la poêle et laissez mijoter 5 minutes."]))
I.append(R(6230599,"Tilapia au four et légumes rôtis",
"Le tilapia est un poisson blanc doux et léger qui cuit rapidement et se trouve facilement dans la plupart des épiceries. Avec des tomates, des légumes et des herbes, le poisson s'imprègne de toutes ces saveurs méditerranéennes pendant la cuisson.",
"4","3 oz de poisson + 1 ½ tasse de légumes",
["4 petits filets de tilapia frais","1/2 c. à café de poivre noir","1 c. à soupe d'huile d'olive","1/2 tasse d'oignon doux (coupé en dés)","2 tasses d'aubergine (coupée en dés)","1 tasse de courgette (coupée en dés)","1 tasse de poivron rouge (coupé en dés)","1 boîte (15 oz) de tomates rôties au feu (sans sel ajouté)","1 c. à café d'origan séché","1/4 c. à café de gros sel casher","1/2 c. à café d'ail en poudre","1 tasse de poivron orange (coupé en dés)"],
["Préchauffez le four à 400 degrés F.","Si nécessaire, coupez le poisson en 4 morceaux et assaisonnez-le de poivre des deux côtés. Mettez de côté.","Dans une grande sauteuse allant au four, chauffez l'huile d'olive à feu moyen. Ajoutez l'oignon et faites-le sauter 3 minutes, jusqu'à ce qu'il commence tout juste à ramollir. Si vous n'avez pas de grande sauteuse allant au four, transférez le poisson et les légumes sur une plaque de cuisson ou dans un plat à gratin pour les cuire au four.","Ajoutez l'aubergine à l'oignon et faites sauter 3 minutes, jusqu'à ce qu'elle commence tout juste à ramollir.","Ajoutez la courgette, les poivrons, les tomates, l'origan, le sel et l'ail en poudre, et mélangez bien.","Nichez les filets de poisson dans le mélange de tomates et de légumes.","Couvrez la poêle et mettez-la au four. Faites cuire 15 minutes, jusqu'à ce que les légumes et le poisson soient bien cuits."]))
I.append(R(6231400,"Bon gaspacho 2, 2, 2",
"Le gaspacho est une soupe préparée principalement avec des légumes non féculents. Il se sert froid et peut être une excellente collation estivale. De plus, c'est une façon facile d'ajouter plus de légumes à votre journée !",
"6","1/2 tasse",
["2 lb de tomates mûres","2 courgettes moyennes","2 gros concombres (non pelés (anglais ou de serre))","1 petit oignon rouge","4 gousses d'ail (pelées)","1 gros poivron rouge","1 c. à soupe de vinaigre balsamique","1 tasse de jus de légumes","1 pincée de sel","1 pincée de poivre noir"],
["Dans un robot culinaire, hachez finement les légumes et l'ail, en plusieurs fois. Mettez-les dans un grand bol en verre.","Ajoutez le vinaigre balsamique, le jus de légumes, le sel et le poivre. Réfrigérez pendant au moins 1 heure."]))
I.append(R(6232942,"Tacos de poisson grillé et salsa fraise-mangue",
"Cette recette de tacos au poisson devient encore plus vive lorsque vous la garnissez d'une salsa juteuse à la fraise et à la mangue. Les baies sucrées et la mangue tropicale forment l'association parfaite pour ce plat estival et festif.",
"4","2 tacos et 1/4 tasse de salsa",
["1 c. à soupe d'huile d'olive extra vierge","2 c. à soupe pour la marinade + 2 c. à soupe pour la salsa de jus de lime frais (utilisation divisée)","1 c. à café pour la marinade + 1/4 c. à café pour la salsa de zeste de lime (fraîchement râpé, utilisation divisée)","1/4 c. à café de piment chipotle en poudre","1/2 c. à café de cumin moulu","1/4 c. à café de sel de mer fin","1/4 c. à café de poivre noir fraîchement moulu","1 lb de filets de morue (ou d'un poisson blanc à chair feuilletée similaire)","8 petites tortillas de maïs","1/2 tasse de fraises (pour la salsa, hachées)","1/2 tasse de mangue (pour la salsa, hachée)","1 petite échalote (pour la salsa, hachée finement)","1/4 tasse de coriandre fraîche (pour la salsa, hachée)"],
["Dans un bol moyen, fouettez ensemble l'huile, le jus de lime, le zeste de lime, le piment en poudre, le cumin, le sel et le poivre. Ajoutez la morue et laissez mariner au réfrigérateur 15 à 20 minutes.","Pendant que le poisson marine, mélangez tous les ingrédients de la salsa dans un bol moyen.","Préchauffez un gril extérieur ou une poêle-gril à feu moyen-vif.","Retirez la morue de la marinade et faites-la griller 3 à 4 minutes d'un côté. Retournez-la ensuite et faites-la griller 1 à 2 minutes de l'autre côté, ou jusqu'à ce que le poisson s'effeuille facilement à la fourchette.","Transférez la morue dans une assiette et laissez-la reposer 5 minutes, puis effeuillez-la à la fourchette en morceaux de la taille d'une bouchée.","En procédant par lots si nécessaire, faites griller les tortillas 20 secondes chacune. Répartissez le poisson uniformément entre les tortillas, garnissez de salsa (environ 2 cuillères à soupe par taco) et servez."]))
I.append(R(6233274,"Poisson grillé au beurre et au citron sur asperges grillées",
"Cette recette de poisson rapide et facile est peut-être le plat d'été idéal pour la semaine. Avec seulement quelques ingrédients, vous pouvez servir un beau repas bon pour le cœur et adapté aux personnes diabétiques en environ 15 minutes.",
"4","3 onces de poisson cuit + 6 à 8 asperges + 1 c. à soupe de garniture",
["1 lb d'asperges (extrémités coupées)","2 vaporisations, 0.50 g de spray de cuisson antiadhésif","4 filets de morue entiers (4 onces chacun, rincés et épongés)","1 c. à soupe de zeste de citron (de 1 citron moyen)","1/4 tasse de beurre léger à l'huile de canola","2 c. à soupe de jus de citron (de 1 citron moyen)"],
["Chauffez un gril ou une poêle-gril à feu moyen-vif. Enrobez les asperges de spray de cuisson et faites-les cuire 6 à 8 minutes, ou jusqu'à ce qu'elles soient tout juste tendres mais croquantes, en les retournant de temps en temps. Réservez-les sur un plat de service à rebord et couvrez pour garder au chaud.","Enrobez les deux faces du poisson de spray de cuisson, saupoudrez de 1/4 c. à café de poivre noir, si désiré, et faites cuire 3 minutes de chaque côté, ou jusqu'à ce que le centre soit opaque.","Pendant ce temps, mélangez le beurre léger, le zeste de citron et 1/4 c. à café de sel, si désiré, dans un petit bol.","Étalez à la cuillère le mélange au beurre sur les asperges, en les recouvrant toutes. Garnissez avec le poisson et pressez du jus de citron sur le poisson."]))
I.append(R(6233807,"Crêpes farcies au fromage cottage et aux baies",
"Une envie de sucré-salé au petit-déjeuner ? Préparez ces crêpes farcies au fromage cottage et aux baies ! Elles sont riches en protéines, ce qui vous aidera à rester rassasié toute la matinée.",
"4","2 crêpes farcies",
["1/2 tasse de farine d'amande","1/2 tasse de blancs d'œufs","1/2 tasse de lait d'amande non sucré","2 c. à soupe d'huile d'olive","2 c. à café d'extrait de vanille","1/16 c. à café de sel","1 tasse de fromage cottage (sans gras)","1 tasse de baies mélangées"],
["Préparez les crêpes. Dans un mélangeur, combinez la farine d'amande, la farine de noix de coco, les œufs, le lait d'amande, l'huile d'olive, l'extrait de vanille et une pincée de sel. Mixez jusqu'à obtenir une texture lisse.","Laissez reposer la pâte à crêpes au réfrigérateur pendant au moins 30 minutes.","Chauffez une poêle antiadhésive à feu moyen et vaporisez-la légèrement de spray de cuisson.","Versez une petite quantité de pâte dans la poêle en l'inclinant pour napper le fond d'une couche fine et uniforme.","Faites cuire chaque crêpe environ 1 à 2 minutes de chaque côté, ou jusqu'à ce qu'elle soit légèrement dorée. Répétez avec le reste de la pâte.","Déposez le fromage cottage à la cuillère sur une moitié de chaque crêpe.","Ajoutez une couche de baies mélangées sur le fromage cottage.","Repliez les côtés et roulez pour refermer chaque crêpe sur la garniture."]))
I.append(R(6234115,"Craquelins de blé faibles en sodium","Informations nutritionnelles pour des craquelins de blé faibles en sodium","1","1 once",["1 oz de craquelins de blé faibles en sodium"],[]))
I.append(R(6235196,"Saumon mariné grillé - recette gourmande",
"C'est une excellente recette d'été pour le gril. Accompagnez le saumon d'un pilaf de riz et d'asperges grillées ou de courge d'été.",
"4","1 filet",
["2 c. à soupe de sauce soja à teneur réduite en sodium","1 c. à soupe d'huile d'olive","1 petit piment fort entier (Serrano ou autre, l'équivalent de 1 c. à soupe de piment haché)","1 c. à soupe de gingembre frais (râpé)","1 c. à soupe de citronnelle (hachée finement ; si vous n'en trouvez pas, remplacez par 1 c. à soupe de jus de lime)","1 c. à soupe de substitut de cassonade faible en calories","4 filets entiers de saumon rouge (sockeye) (4 onces chacun, sans peau)"],
["Préparez un gril d'intérieur ou d'extérieur.","Fouettez ensemble tous les ingrédients, sauf le saumon, dans un bol de taille moyenne.","Versez la marinade sur le saumon, en veillant à enrober les deux faces. Laissez mariner au réfrigérateur 30 minutes.","Retirez le saumon de la marinade. Faites griller les filets 4 à 6 minutes de chaque côté et jetez le reste de la marinade."]))
I.append(R(6237124,"Toast du petit-déjeuner à l'avocat et à la tomate",
"Pour un petit-déjeuner rapide et facile, essayez ce toast à l'avocat et à la tomate. L'avocat onctueux se marie avec la tomate juteuse et les œufs pour un début de journée riche en protéines. Vous pouvez ajouter une touche de saveur supplémentaire avec un trait de sauce piquante ou de sriracha sur votre toast.",
"4","1 toast",
["1 avocat moyen (mûr)","1/4 c. à café de gros sel casher (divisé)","1 vaporisation, 0.25 g de spray de cuisson antiadhésif","4 tranches de pain complet","1 tasse de substitut d'œuf","1 grosse tomate romaine (allongée) (tranchée)","1/8 c. à café de poivre noir"],
["Commencez par préparer la purée d'avocat. Coupez l'avocat mûr en deux, retirez le noyau et mettez la chair dans un bol. Écrasez-la à la fourchette et assaisonnez de 1/8 c. à café de sel. Vous pouvez aussi ajouter un trait de sauce piquante si vous le désirez.","Chauffez une poêle antiadhésive à feu moyen et vaporisez-la de spray de cuisson.","Pendant que la poêle chauffe, faites griller les tranches de pain complet jusqu'à ce qu'elles soient dorées.","Dans la poêle chaude, cassez les œufs et faites-les cuire selon vos préférences (p. ex., au plat, brouillés ou pochés). Assaisonnez de 1/8 c. à café de sel et de poivre au goût. Si vous préférez les œufs à jaune coulant, faites-les cuire environ 2 à 3 minutes au plat, ou un peu plus longtemps pour des œufs retournés mi-cuits.","Montez le toast. Étalez l'avocat écrasé sur chaque tranche de pain grillé et ajoutez une couche de tranches de tomate. Déposez les œufs cuits sur les tranches de tomate. Saupoudrez de poivre noir si désiré."]))
I.append(R(6238095,"Gaspacho aux verts puissants",
"Toute feuille verte foncée conviendrait très bien dans cette soupe. Soyez créatif et savourez cet accompagnement riche en nutriments et plus pauvre en glucides.",
"5","1 tasse",
["1 tasse de basilic (feuilles légèrement tassées)","1 tasse de babeurre faible en gras","2 gousses d'ail","1/3 tasse de vinaigre balsamique","1/4 tasse d'amandes effilées (blanchies)","1/4 tasse d'oignon (haché)","1 poivron vert moyen (épépiné et haché)","5 oz de mesclun","1 gros concombre (pelé, épépiné et haché)","1 tasse de bouillon de légumes sans sel","1/2 c. à café de poivre noir"],
["Mettez tous les ingrédients dans un mélangeur et mixez jusqu'à obtenir une texture lisse."]))
save(2,I)
