from lib import *
I=[]
I.append(R(6255845,"Pain de viande classique",
"Auteure Robyn Webb : « Demandez à n'importe qui ses souvenirs culinaires d'enfance et le pain de viande est généralement mentionné. Nous possédions une collection de moules à pain quand j'étais enfant, mais ma mère les utilisait davantage pour cuire du pain que pour former des pains de viande. C'est elle qui m'a appris à façonner un pain de viande de forme oblongue sur une plaque de cuisson, ce qui permet à l'air de circuler tout autour du pain pour obtenir ces bords croustillants. »",
"6","3 onces (environ 1 ½ pouce d'épaisseur)",
["2 c. à café d'huile d'olive","1 petit oignon (haché finement)","1/3 tasse de poivron vert ou rouge (haché très finement)","4 oz de champignons de Paris blancs (hachés)","2 gousses d'ail (hachées)","1 c. à café d'assaisonnement italien","1/4 c. à café de sel de mer","1/4 c. à café de poivre noir (fraîchement moulu)","1 lb de bœuf haché (maigre à 95 %)","1 gros œuf (battu)","1 tasse de chapelure panko de blé entier","1 tasse de lait (sans gras)","2 c. à café de sauce Worcestershire","1/2 c. à café de fumée liquide (facultatif)","1/3 tasse de ketchup (sans sucre)","1 1/2 c. à soupe de moutarde de Dijon","1 c. à café de cassonade"],
["Préchauffez le four à 375°F. Tapissez une plaque de cuisson de papier sulfurisé. Mettez de côté.","Chauffez l'huile dans une poêle moyenne à feu moyen. Faites sauter l'oignon 3 minutes. Ajoutez le poivron vert et les champignons et faites sauter 3 minutes. Ajoutez l'ail, l'assaisonnement italien, le sel et le poivre et faites sauter 1 minute.","Mettez le mélange d'oignon dans un bol et laissez refroidir 2 minutes. Ajoutez le bœuf, l'œuf, la chapelure, le lait, la sauce Worcestershire et la fumée liquide, si vous en utilisez. Mélangez délicatement, sans trop travailler la viande.","Déposez le mélange sur la plaque de cuisson préparée et façonnez-le en un pain oblong. Mélangez le ketchup, la moutarde et la cassonade et versez sur le pain de viande.","Faites cuire le pain de viande 40 à 45 minutes, jusqu'à ce qu'il soit bien cuit. Sortez-le du four et laissez-le reposer 5 à 7 minutes avant de le trancher."]))
I.append(R(6257680,"Rôti de gîte à la noix aux oignons à l'ail",
"La croûte de café et de piment en poudre ajoutera une saveur fumée et savoureuse à ce rôti de bœuf. Veillez à utiliser un thermomètre pour vérifier la température interne et sortez le rôti du four dès qu'il atteint 120°F. Laissez-le reposer au moins 10 minutes pour obtenir un rôti juteux. Un rôti de 2 lb suffit pour 8 personnes, ou pour 4 avec des restes.",
"8","3 onces de bœuf cuit + 2 c. à soupe de mélange d'oignons",
["1 c. à soupe de café instantané en granules","1 c. à soupe de piment en poudre","1 c. à café de sel","1/2 c. à café de poivre noir","1 rôti de gîte à la noix entier (d'environ 2 livres, paré)","8 oz d'oignons (coupés en quartiers de 1/4 pouce d'épaisseur)","1 tête d'ail entière (environ 12 à 16 gousses, simplement pelées)","1 c. à soupe d'huile de canola","1/2 tasse d'eau"],
["Préchauffez le four à 475°F. Mélangez les granules de café, le piment en poudre, le sel et le poivre et pressez le mélange sur toutes les faces du bœuf. Placez le rôti au centre d'un plat de cuisson de 13 × 9 pouces, disposez les oignons et l'ail autour et arrosez d'huile. Faites cuire 20 minutes, en retournant le bœuf et en remuant le mélange d'oignons après 10 minutes.","Réduisez la température du four à 300°F (ne sortez pas le rôti du four). Faites cuire 30 minutes, ou jusqu'à ce qu'un thermomètre indique 120°F. Éteignez le four. Placez le rôti sur une planche à découper et laissez reposer 10 minutes avant de le trancher finement en travers des fibres. Incorporez l'eau au mélange d'oignons dans le plat en raclant le fond et les côtés du plat, et mettez-le au four pendant que le bœuf repose. Servez avec le bœuf."]))
I.append(R(6259247,"Pouding de quinoa en dessert",
"Ce dessert a le même réconfort et la même saveur qu'un riz au lait, mais il est préparé avec du quinoa, une céréale complète riche en protéines et un superaliment pour les personnes diabétiques. Veillez à rincer le quinoa avant de le cuire : cela aide à éviter tout goût amer.",
"9","1/3 tasse",
["1 tasse de quinoa","1 1/2 tasse de lait écrémé","1 1/2 tasse de demi-crème sans gras (half-and-half)","1/4 tasse de mélange de cassonade faible en calories","1 c. à café d'extrait de vanille","1/2 c. à café de cannelle moulue","1/4 c. à café de muscade moulue","1/2 tasse de graines de courge (grillées)"],
["Rincez le quinoa à l'eau froide pendant 2 minutes.","Dans une casserole moyenne, fouettez ensemble le lait, la demi-crème sans gras, le mélange de cassonade, la vanille, la cannelle et la muscade à feu moyen. Portez à frémissement.","Quand le mélange de lait frémit, incorporez le quinoa et réduisez à feu doux pour un léger frémissement. Couvrez partiellement la casserole et faites cuire 40 minutes, en remuant toutes les 10 minutes.","Quand le quinoa est cuit, incorporez les graines de courge grillées et servez."]))
I.append(R(6259731,"Mini-burgers de poulet barbecue à la mijoteuse",
"Mettez le poulet à cuire dans une mijoteuse et assemblez ces amusants mini-sandwichs à l'arrivée de vos invités.",
"8","1 mini-burger",
["1 lb de poitrines de poulet (désossées, sans peau)","1/2 c. à café d'ail en poudre","1/4 c. à café de poivre noir","1 petit oignon (tranché)","1 tasse d'eau","1/3 tasse de sauce barbecue","8 mini-pains de blé entier (coupés en deux)"],
["Mettez les poitrines de poulet dans une mijoteuse. Saupoudrez d'ail en poudre et de poivre. Placez l'oignon tranché sur le poulet. Versez 1 tasse d'eau. Couvrez et faites cuire à feu doux pendant 6 heures, ou jusqu'à ce que ce soit cuit.","Videz l'eau de cuisson de la mijoteuse. Effilochez le poulet avec deux fourchettes. Ajoutez la sauce barbecue et remuez pour enrober le poulet. Laissez chauffer encore 15 minutes.","Assemblez les sandwichs en utilisant 1/3 tasse de poulet barbecue pour chaque pain."]))
I.append(R(6260150,"Yaourt grec à l'ananas et à la noix de coco",
"Transformez votre petit-déjeuner en délice tropical avec notre parfait de yaourt grec à l'ananas frais et à la noix de coco, une option délicieuse et adaptée aux personnes diabétiques pour bien commencer la journée. Ce parfait associe la douceur savoureuse de l'ananas frais à la richesse crémeuse du yaourt grec parfumé à la noix de coco. Pour plus de saveur et de croquant, faites griller les amandes effilées au four au préalable.",
"2","1 parfait",
["1 1/2 tasse de yaourt grec nature sans gras","2 c. à café de substitut de sucre faible en calories (sans sucre ajouté)","1 c. à café d'extrait de noix de coco","1 tasse d'ananas (coupé en dés)","3 c. à soupe d'amandes grillées (effilées)"],
["Dans un petit bol, mélangez le yaourt grec, le substitut de sucre et l'extrait de noix de coco. Ajustez la douceur à votre goût.","Dans des verres ou des bols de service, commencez par ajouter une couche de mélange de yaourt.","Ajoutez une couche d'ananas sur le yaourt.","Parsemez les amandes sur l'ananas.","Répétez les couches jusqu'à ce que votre verre soit rempli. Servez froid."]))
I.append(R(6262343,"Hachis de rutabaga et de carottes",
"Les légumes-racines sont de saison pendant les mois froids et font aussi d'excellents accompagnements pour les fêtes à venir.",
"12","1/2 tasse",
["1 lb de rutabaga (pelé, coupé en quartiers et finement tranché)","1/2 lb de pommes de terre Russet ou à cuire au four (pelées et finement tranchées)","1 1/2 carotte moyenne (pelée et finement tranchée)","5 gousses d'ail (pelées)","1 feuille de laurier","1/8 c. à café de gros sel casher","1/8 c. à café de poivre noir","2 tasses de bouillon de poulet à faible teneur en sodium (faible en gras)","2 tasses d'eau","1 c. à soupe d'huile d'olive"],
["Dans une grande casserole, mélangez le rutabaga, les pommes de terre, les carottes, l'ail, la feuille de laurier, le sel et le poivre au goût, le bouillon et l'eau. Portez à ébullition à feu moyen, réduisez à feu doux, couvrez et faites cuire 30 minutes, jusqu'à ce que les légumes soient tendres. Égouttez les légumes en réservant 1/2 tasse de liquide. Retirez et jetez la feuille de laurier.","À l'aide d'un presse-purée, écrasez les légumes avec le liquide de cuisson réservé et l'huile d'olive. Rectifiez l'assaisonnement si nécessaire et servez."]))
I.append(R(6262722,"Pistaches, 16 pièces",None,"1","16 pièces",["16 pistaches entières (non salées)"],[]))
I.append(R(6262970,"Taco à l'œuf au plat et à l'avocat",
"Ce petit-déjeuner rapide et facile pour deux met en vedette un œuf au plat, une tomate fraîche et de l'avocat, roulés dans une tortilla chaude.",
"2","1 taco",
["2 c. à café d'huile d'olive (divisées)","2 gros œufs","2 tortillas moyennes de farine de blé entier (8 pouces)","1 avocat moyen (pelé, dénoyauté et écrasé)","1 tomate moyenne (tranchée)","1 c. à soupe de pignons de pin ou de pepitas","2 c. à soupe de coriandre fraîche (hachée)","1/2 piment jalapeño moyen (épépiné et finement tranché (facultatif))","1/8 c. à café de sel","1/8 c. à café de poivre noir"],
["Badigeonnez une petite poêle antiadhésive de 1 c. à café d'huile et chauffez à feu moyen. Ajoutez les œufs un à la fois et faites-les cuire au plat pendant environ 2 minutes. À l'aide d'une spatule, transférez-les dans une assiette.","Pendant la cuisson des œufs, réchauffez les tortillas dans une autre poêle (inutile d'ajouter de l'huile).","Pour chaque portion, étalez sur une tortilla la moitié de l'avocat écrasé, des tomates, des pignons de pin, de la coriandre et des jalapeños, si vous en utilisez. Garnissez d'un œuf, arrosez du reste d'huile d'olive extra vierge et assaisonnez de sel et de poivre. Repliez et servez."]))
I.append(R(6262997,"Brocolini rôti au citron et au parmesan",
"Découvrez l'équilibre parfait des saveurs de notre brocolini rôti au citron acidulé et au parmesan dans cet accompagnement adapté aux personnes diabétiques.",
"4","1 tasse",
["1 botte de brocolini (extrémités coupées)","2 c. à soupe d'huile d'olive","2 citrons moyens","1/4 tasse de parmesan (râpé)","2 gousses d'ail (hachées)","1/8 c. à café de sel","1/4 c. à café de poivre noir","1/2 c. à café de flocons de piment rouge moulus (facultatif)"],
["Préchauffez le four à 425 degrés F. Tapissez une plaque de cuisson de papier sulfurisé.","Prélevez le zeste et pressez le jus d'un citron.","Dans un grand bol, mélangez le brocolini avec l'huile d'olive, le zeste de citron, le jus de citron, le parmesan râpé, l'ail haché, le sel, le poivre noir et les flocons de piment rouge si vous en utilisez. Veillez à ce que le brocolini soit uniformément enrobé.","Étalez le brocolini en une seule couche sur une plaque de cuisson.","Faites rôtir au four préchauffé pendant 15 minutes, ou jusqu'à ce que le brocolini soit tendre mais croquant et que les bords soient légèrement grillés.","Servez avec du parmesan râpé supplémentaire sur le dessus. Coupez le citron restant en quartiers pour les servir à côté, si désiré."]))
I.append(R(6265858,"Haricots verts de l'Action de grâce aux canneberges et aux noisettes",
"Égayez un accompagnement de haricots verts avec des canneberges acidulées, du zeste de citron frais et des noisettes croquantes ! Cet accompagnement simple a l'air gastronomique, mais il est très facile à préparer. Il constitue aussi un bel ajout léger à votre table de l'Action de grâce, à la place du traditionnel gratin de haricots verts, plus lourd. Si vous ne trouvez pas de noisettes, des amandes effilées, des noix ou des noix de pécan feront tout aussi bien l'affaire. Cette recette fait partie de notre trousse de fêtes adaptée aux personnes diabétiques et a été modifiée pour donner 10 portions. La recette originale donne 16 portions et se trouve ici.",
"10","1/2 tasse",
["1 1/4 lb de haricots verts frais (parés)","2 c. à café d'huile d'olive","2 1/2 c. à soupe de noisettes (hachées)","2 c. à soupe de canneberges séchées","1/8 c. à café de sel","1/8 c. à café de poivre noir","1 c. à soupe de zeste de citron (de 1 citron moyen)"],
["Dans un petit bol, mélangez l'huile, les noix, les canneberges, le sel et le poivre. Garnissez les haricots verts du mélange de canneberges et de noix. Garnissez de zeste de citron.","Remplissez une grande marmite d'eau aux 2/3 et portez à ébullition. Ajoutez les haricots verts, éteignez le feu et laissez les haricots verts reposer dans l'eau 3 minutes. Égouttez les haricots et mettez-les dans un saladier ou sur un plat de service."]))
I.append(R(6266360,"Œufs mimosa à la sriracha",
"Les œufs mimosa à la sriracha sont une version audacieuse et épicée d'un classique favori. Ils font une entrée fantastique pour les amateurs de piquant et ajoutent une touche de feu à votre fête ou à votre réunion. Savourez ces œufs mimosa relevés comme collation délicieuse et adaptée aux personnes diabétiques.",
"8","2 moitiés",
["8 gros œufs","1/4 tasse de mayonnaise légère","1 c. à soupe de sriracha","1 c. à café de moutarde de Dijon","1/2 c. à café de sel","1/4 c. à café de poivre noir","1 tige d'oignon vert (ciboule) (finement tranchée, pour la garniture)","1 c. à café de graines de sésame (grillées, pour la garniture)"],
["Disposez les œufs en une seule couche dans une casserole et couvrez d'eau. Portez l'eau à ébullition, puis réduisez à feu doux, couvrez et laissez mijoter 10 à 12 minutes.","Transférez les œufs durs dans un bain d'eau glacée pour les refroidir.","Une fois les œufs refroidis, écalez-les et coupez-les en deux dans la longueur. Retirez les jaunes et mettez-les dans un bol.","Dans le bol contenant les jaunes d'œufs, ajoutez la mayonnaise, la sauce sriracha, la moutarde de Dijon, le vinaigre de riz, le sel et le poivre. Écrasez et mélangez les ingrédients jusqu'à obtenir une texture lisse. Versez à la cuillère ou à la poche la garniture à la sriracha dans les blancs d'œufs évidés.","Mettez au réfrigérateur au moins 30 minutes avant de servir. Garnissez d'oignons verts tranchés et de graines de sésame."]))
I.append(R(6266956,"Melon à la vinaigrette à l'estragon",
"Le melon à la vinaigrette à l'estragon est une salade rafraîchissante et élégante qui associe la douceur du melon mûr aux notes herbacées et légèrement poivrées de l'estragon dans une vinaigrette légère. C'est un excellent accompagnement pauvre en glucides pour l'été.",
"4","1 tasse",
["2 c. à soupe de jus de citron","1 c. à soupe de sirop sans sucre","2 c. à soupe d'estragon frais (haché)","2 c. à soupe d'huile d'olive","1 cantaloup moyen (tranché et sans écorce)","1/4 c. à café de sel"],
["Dans un petit bol, fouettez le jus de citron, le sirop, l'estragon haché et l'huile.","Disposez le cantaloup sur un plat, arrosez généreusement de vinaigrette et terminez en saupoudrant de sel."]))
I.append(R(6267513,"Sauce aux myrtilles",
"Cette sauce regorge de saveur et transforme le yaourt nature le plus simple en un dessert acidulé. Utilisez-la pour garnir les crêpes à l'avoine et aux noix de pécan à la place du sirop pour un petit-déjeuner riche en nutriments.\n\nTrouvez cette recette et bien d'autres dans The Diabetes Superfoods Cookbook and Meal Planner.",
"6","2 c. à soupe",
["2 tasses de myrtilles fraîches","1 c. à café d'huile de canola","1 c. à soupe de jus de lime frais (de 1 lime moyenne)","1/2 c. à café d'extrait de vanille"],
["Dans une poêle antiadhésive, faites sauter les myrtilles dans l'huile de canola à feu doux pendant environ 10 minutes, jusqu'à ce que vous puissiez facilement écraser les baies.","Ajoutez le jus de lime et faites cuire encore 5 minutes. Retirez du feu et incorporez l'extrait de vanille."]))
I.append(R(6268899,"Smoothie aux fruits et aux amandes",
"Commencez votre matinée avec ce smoothie rafraîchissant. Le lait d'amande contient moins de glucides que le lait ordinaire et convient très bien aux personnes intolérantes au lait ou au lactose.",
"2","1 tasse",
["1/2 tasse de fraises surgelées (non sucrées)","1/2 tasse de pêches surgelées (non sucrées)","1/2 tasse de yaourt grec nature sans gras","1 tasse de lait d'amande non sucré"],
["Mettez tous les ingrédients dans un mélangeur et mixez jusqu'à obtenir une consistance lisse et épaisse."]))
save(5,I)
