from h import *
I=[]
I.append(mk(8,"Soupe asiatique aux nouilles",None,"6","1/6 de la recette",
["4 tasses de bouillon de poulet sans sel ajouté*","2 cuillères à soupe de gingembre frais, pelé et haché finement","2 tasses de tofu extra-ferme, coupé en cubes de 1/2 pouce","2 cuillères à café de sauce soja faible en sodium","1 cuillère à café de pâte d'ail et de piment","1 cuillère à soupe de vinaigre de riz","1 tasse d'oignons verts (environ 4 entiers)","3/4 tasse de céleri, tranché finement","1/4 tasse de poivron rouge, tranché finement","1 1/2 tasse de chou vert, tranché finement","2 cuillères à soupe d'huile d'olive extra vierge","1 cuillère à café d'huile de sésame","6 oz de vermicelles de riz (non cuits)","1/2 tasse de coriandre fraîche, hachée","1 cuillère à soupe de jus de lime","Poivre fraîchement moulu, au goût"],
["Faites chauffer le bouillon.","Dans un petit bol, mélangez le gingembre, le tofu, la sauce soja, la pâte de piment et le vinaigre pour faire mariner le tofu.","Tranchez les oignons verts. Séparez les tranches blanches des tranches vertes et mettez-les de côté.","Mélangez le céleri, les tranches vertes des oignons verts, le poivron rouge et le chou dans un bol.","Faites chauffer une grande casserole ou une poêle profonde de type wok pendant deux minutes à feu moyen-vif. Ajoutez l'huile d'olive et l'huile de sésame, puis faites revenir les tranches blanches des oignons verts jusqu'à ce qu'elles soient dorées et un peu croustillantes, sans être brûlées.","Baissez le feu à moyen, ajoutez le tofu et sa marinade, en remuant pour bien l'enrober, et faites cuire pendant 2 minutes.","Ajoutez tous les légumes de l'étape 4 et poursuivez la cuisson encore 2 à 3 minutes.","Versez le bouillon chaud sur les légumes, augmentez le feu et portez rapidement à ébullition, ajoutez les nouilles de riz et faites cuire pendant deux minutes.","Éteignez le feu, incorporez la coriandre et le jus de lime, et assaisonnez de poivre noir fraîchement moulu, au goût."],
["* Choisissez le bouillon ayant la plus faible teneur en sodium, mais sachez que les produits faibles en sodium contiennent souvent plus de potassium. Cherchez le chlorure de potassium dans la liste des ingrédients sur l'étiquette.","Les restes de soupe peuvent être réchauffés dans les 2 jours."],
["1 viande","2 féculent","1 légume","1 matière grasse"]))

I.append(mk(9,"Pennes crémeuses au saumon",None,"4","¼ de la recette",
["2 tasses de pennes sèches","1 tasse de petits pois surgelés","1 tasse de fromage ricotta","2 cuillères à soupe de jus de citron","½ tasse d'eau (de cuisson des pâtes)","1 cuillère à soupe de zeste de citron","¼ cuillère à café de poivre noir moulu","5 oz de saumon rouge en conserve, sans arêtes ni peau (ou reste de saumon cuit)","½ tasse de feuilles de basilic, tranchées finement"],
["Dans une grande casserole, portez l'eau à ébullition et faites cuire les pâtes selon les instructions sur l'emballage.","Peu avant que les pâtes soient prêtes, ajoutez les petits pois à l'eau bouillante et faites-les blanchir pendant 1 minute. Réservez ½ tasse de l'eau avant d'égoutter. Égouttez et mettez de côté.","Dans une autre casserole, à feu moyen, mélangez le fromage ricotta, le jus de citron et l'eau de cuisson des pâtes. Ajoutez ensuite le zeste de citron, le poivre moulu et le saumon à la sauce.","Ajoutez les pâtes et les petits pois à la sauce et mélangez pour combiner.","Éteignez le feu, parsemez les pâtes de feuilles de basilic frais et servez immédiatement."],
[],["2 viande","1 lait","3 féculent"]))

I.append(mk(10,"Poulet au curry doux et épicé",None,"6","1/6 de la recette : 2 pilons",
["1/4 tasse d'huile d'olive","1/2 cuillère à café de poivre noir","12 pilons de poulet","1 tasse de poivron rouge ou jaune, coupé en dés","3/4 tasse d'oignon, coupé en cubes","2 gousses d'ail, hachées","2 cuillères à soupe de gingembre frais, râpé","2 cuillères à soupe de pâte de curry Madras","1 boîte (14 oz) de pêches avec leur jus, coupées en dés","3/4 tasse de yogourt à la pêche ou nature","1/4 tasse de lait de coco","2 cuillères à soupe de jus de lime (1 lime)","Coriandre fraîche hachée pour la garniture (facultatif)"],
["Faites chauffer l'huile à feu moyen dans une poêle épaisse.","Poivrez les pilons de poulet et faites-les dorer de tous les côtés.","Pendant ce temps, préparez les poivrons, l'oignon, l'ail et le gingembre.","Retirez le poulet en laissant l'huile dans la poêle.","Réduisez le feu à moyen-doux, ajoutez la pâte de curry, l'ail et le gingembre directement dans la poêle. Ajoutez les poivrons et l'oignon et enrobez bien.","Remettez le poulet dans la poêle, ajoutez les pêches avec leur jus et augmentez le feu pour amener le tout à frémir.","Couvrez et faites cuire au four pendant 40 minutes à 350 °F.","Retirez du four et placez sur la cuisinière à feu doux. Ajoutez le yogourt, le lait de coco et le jus de lime. Remuez doucement jusqu'à ce que le tout soit chaud. Ne faites pas bouillir.","Garnissez de coriandre hachée et servez sur du riz blanc."],
[],["3 protéine","1 fruit"]))

I.append(mk(11,"Casserole de poulet crémeuse à la poêle",None,"6","1/6 de la recette",
["2 tasses de pâtes rotini sèches","2 cuillères à soupe d'huile d'olive","1 ½ tasse d'oignon, coupé en dés","3 tasses de légumes mélangés surgelés","1 3/4 tasse de poitrine de poulet cuite, coupée en cubes","2 cuillères à café d'assaisonnement italien","2 cuillères à café de poudre d'ail","Poivre noir moulu, au goût","1 tasse de crème moitié-moitié*","½ tasse de bouillon de poulet sans sel ajouté","2 cuillères à soupe de poudre d'oignon","3 cuillères à soupe de parmesan râpé"],
["Faites cuire les pâtes selon les instructions sur l'emballage.","Dans une grande poêle antiadhésive, faites chauffer l'huile à feu moyen et faites cuire l'oignon pendant 7 minutes. Ajoutez les légumes surgelés et faites cuire pendant 5 minutes en remuant de temps en temps.","Ajoutez le poulet en cubes, l'assaisonnement italien, la poudre d'ail et le poivre noir. Faites cuire encore 5 minutes en remuant de temps en temps.","Pendant ce temps, dans une petite casserole, mélangez tous les ingrédients de la sauce et portez à ébullition. Mettez de côté.","Ajoutez les pâtes cuites dans la poêle avec le poulet et les légumes. Versez la sauce et remuez pour combiner. Réchauffez à feu moyen et servez."],
["* Choisissez une crème sans additifs phosphatés","Manger des fruits et des légumes chaque jour est la pierre angulaire d'une alimentation saine. Ils peuvent abaisser la tension artérielle, fournir des fibres pour la santé digestive et réduire votre risque de maladie chronique. Un obstacle à leur consommation quotidienne est la disponibilité. Frais, ils sont abondants pendant une saison, mais peuvent être rares à d'autres moments de l'année. Les options fraîches peuvent aussi être assez coûteuses. Une solution possible est d'acheter des fruits et des légumes surgelés.\n\nOn entend souvent dire que « le frais est meilleur », mais les fruits et les légumes surgelés sont généralement congelés au sommet de leur saveur et de leur fraîcheur et peuvent tout de même vous fournir tous les nutriments dont vous avez besoin. Autre avantage : moins de gaspillage alimentaire. Il peut être difficile d'utiliser tous les produits frais que vous achetez avant qu'ils se gâtent. Avec les produits surgelés, vous prenez seulement ce dont vous avez besoin au congélateur et gardez le reste pour un autre jour, ce qui évite le gaspillage.\n\nLes fruits surgelés sont faciles à utiliser : il suffit de les décongeler et de les manger. Les légumes surgelés peuvent être plus délicats, car ils peuvent devenir mous une fois décongelés. Pour l'éviter, faites cuire rapidement les légumes surgelés à feu vif, par exemple dans un sauté, ou ajoutez-les aux casseroles. Le maïs, les haricots verts, les carottes et les petits pois conviennent bien à ces plats. Si vous choisissez du brocoli ou du chou-fleur, enrobez-les encore surgelés d'huile d'olive et d'herbes, puis faites-les rôtir à 450 degrés."],
["2 viande","2 féculent","1 légume féculent plus pauvre en potassium"],
{"Sauce":"Sauce","Fruits and vegetables on a budget":"Des fruits et des légumes à petit prix"}))

I.append(mk(12,"Gâteau au fromage aux bleuets",None,None,None,
["1 1/2 tasse de miettes de gaufrettes à la vanille","2 c. à soupe de sucre","3 c. à soupe de margarine ou de beurre, fondu","2 paquets (8 oz) de fromage à la crème, ramolli","1 tasse de sucre","2 c. à café de zeste de citron râpé","1/2 c. à café de vanille","3 œufs","1 boîte (21 oz) de garniture aux bleuets"],
["Mélangez les miettes de gaufrettes, 2 c. à soupe (30 ml) de sucre et la margarine.","Pressez dans le fond d'un moule à charnière de 9 pouces (20 cm) ou d'un moule à tarte de 9 pouces (20 cm).","Faites cuire 10 minutes à 350° (175° C). Laissez refroidir.","Battez le fromage à la crème dans un grand bol. Ajoutez graduellement 1 tasse (235 ml) de sucre en battant jusqu'à ce que le mélange soit léger et mousseux.","Ajoutez le zeste de citron et la vanille. Incorporez les œufs un à la fois en battant. Versez sur le mélange de miettes.","Faites cuire à 300° (150° C) pendant 1 heure ou jusqu'à ce que le centre soit ferme. Réfrigérez au moins 3 heures.","Garnissez de garniture à tarte. Donne 16 parts."],
[],[]))

I.append(mk(13,"Farfalle au thon",None,"4","1/4 de la recette",
["2 tasses de pâtes farfalle sèches","2 cuillères à soupe d'huile d'olive","2 gousses d'ail, hachées finement","1/4 cuillère à café de flocons de piment rouge","1/4 cuillère à café de poivre noir moulu","1/2 tasse de cœurs d'artichauts (conservés dans l'eau), égouttés et coupés en dés*","2 boîtes (6 oz) de thon (conservé dans l'eau, sans sel), égoutté","1 tasse de roquette","1/2 tasse de persil, lavé et haché","2 cuillères à soupe de jus de citron","1 cuillère à soupe de parmesan, râpé"],
["Dans une grande casserole, portez l'eau à ébullition et faites cuire les pâtes selon les instructions sur l'emballage.","Faites chauffer l'huile dans une grande poêle à feu moyen. Faites revenir l'ail avec les flocons de piment et le poivre noir (2 minutes). Faites attention de ne pas brûler l'ail.","Ajoutez les artichauts, le thon, la roquette, le persil et le jus de citron dans la poêle et faites cuire jusqu'à ce que la roquette soit flétrie.","Ajoutez les pâtes à la sauce et mélangez.","Saupoudrez les pâtes de parmesan et servez."],
["* L'artichaut est un légume riche en potassium et doit être consommé avec modération."],
["3 viande","2 féculent","1 légume"]))

I.append(mk(14,"Sorbet à la mandarine",None,"4","1/4 de la recette",
["2 tasses de mandarines en conserve, égouttées","¼ tasse de blancs d'œufs pasteurisés","1 cuillère à soupe de jus de citron"],
["Recouvrez une plaque de cuisson de papier parchemin. Répartissez les quartiers de mandarine sur la plaque et placez-les au congélateur pendant au moins 2 heures.","À l'aide d'un mélangeur, mélangez les quartiers congelés, les blancs d'œufs et le jus de citron, en actionnant par impulsions jusqu'à obtenir une consistance givrée.","Servez immédiatement ou répartissez dans des coupes individuelles et congelez pour plus tard."],
["Une alimentation équilibrée et pauvre en potassium peut vous fournir les différents nutriments dont votre corps a besoin. Les fruits sont une source naturelle de fibres, d'acide folique et de vitamines C et A. Visez 3 portions par jour de ce groupe d'aliments. Si les fruits frais sont une excellente option, les fruits en conserve peuvent aussi être un choix pauvre en potassium. Choisissez des fruits en conserve comme les abricots dans leur jus, la salade de fruits, les pêches, les poires, la compote de pommes et les mandarines. Une portion d'environ ½ tasse de ces fruits est considérée comme une seule portion.\n\nLorsque vous parcourez les rayons de l'épicerie, tenez compte de ce qui suit pour choisir des fruits en conserve. D'abord, lisez les étiquettes et évitez les produits contenant des additifs à base de potassium. Ensuite, visez le choix de fruits le plus naturel, avec peu d'ingrédients ajoutés. Les fruits en conserve dans leur jus sont un choix plus sain que ceux conservés dans un sirop épais, afin de limiter les sucres ajoutés et les calories superflues. Enfin, choisissez des boîtes sans bosses profondes pour garantir la sécurité alimentaire et une bonne conservation."],
["½ fruit riche en potassium"],
{"Canned fruit choices for the kidney diet":"Choix de fruits en conserve pour l'alimentation pour les reins"}))

I.append(mk(15,"Crème à la vanille et à la cannelle",None,"4","1/4 de la recette",
["2 jaunes d'œufs","2 tasses de lait écrémé","1/3 tasse de sucre","¼ tasse de fécule de maïs","1 cuillère à café d'extrait de vanille","1/8 cuillère à café de cannelle","1 cuillère à soupe de beurre non salé","4 biscuits au gingembre"],
["Dans une casserole, mélangez les jaunes d'œufs, le lait, le sucre, la fécule de maïs, l'extrait de vanille et la cannelle.","Portez à ébullition à feu moyen en remuant constamment jusqu'à épaississement.","Retirez du feu et ajoutez le beurre. Remuez pour combiner.","Répartissez la crème dans quatre bols ou verres à dessert et couvrez le dessus du dessert de pellicule plastique pour éviter que la couche supérieure ne s'épaississe. Réfrigérez pendant au moins deux heures.","Servez avec les biscuits au gingembre."],
["Pour les personnes atteintes d'insuffisance rénale chronique, il est important de suivre une alimentation à la fois adaptée aux reins et bonne pour le cœur. La clé d'une alimentation bonne pour le cœur est de manger moins de matières grasses, en particulier de graisses saturées. Les graisses saturées peuvent être naturelles, comme le beurre, le gras de la viande et l'huile de noix de coco, ou fabriquées artificiellement, on parle alors de gras trans, couramment présents dans la margarine en bâton et le shortening.\n\nLes graisses saturées sont faciles à repérer, car elles sont solides à température ambiante. De nombreuses recettes de pâtisserie contiennent des graisses saturées. La margarine contient moins de graisses saturées que le beurre ou le shortening et constitue donc un meilleur choix pour la pâtisserie. Il est aussi possible de remplacer le beurre ou le shortening par de l'huile dans de nombreuses recettes. Une bonne règle générale consiste à diminuer d'un quart la quantité d'huile par rapport à la quantité de beurre ou de shortening de la recette. Par exemple, si une recette demande 1 tasse de beurre ou de shortening, remplacez-la par trois quarts de tasse d'huile. Faites des essais avec vos recettes pour voir si cette substitution vous convient. Pour commencer, remplacez la moitié du beurre ou du shortening par de l'huile. Si cela fonctionne bien, essayez ensuite de remplacer la totalité.\n\nLes aliments emballés peuvent contenir des quantités élevées de graisses saturées et de gras trans. Limitez autant que possible les graisses saturées et évitez les gras trans chaque fois que possible. Les graisses liquides à température ambiante, comme l'huile d'olive et l'huile de canola, sont des graisses insaturées. Ce sont les meilleures à utiliser. Une lecture attentive des étiquettes de valeur nutritive vous aidera à atteindre cet objectif."],
["1 lait","1 glucide","1 matière grasse"],
{"Kidney-friendly and heart-healthy":"Bon pour les reins et bon pour le cœur"}))
save('p02',I)
