from h import *
I=[]
I.append(mk(24,"Salade de fruits d'hiver",None,"4","¼ de la recette",
["1 tasse d'eau","2 cuillères à soupe de sucre cristallisé (ou moins, si les fruits sont déjà sucrés)","1 cuillère à soupe de feuilles de menthe fraîche, hachées","1/8 cuillère à café de cannelle moulue","1 tasse d'ananas, coupé en cubes (frais ou en conserve)","1 tasse de raisins rouges, coupés en deux","3 clémentines,* séparées en quartiers","1 cuillère à soupe de feuilles de menthe, hachées"],
["Dans une petite casserole, mélangez l'eau, le sucre, la menthe et la cannelle et portez à ébullition. Réduisez à feu moyen et laissez mijoter jusqu'à ce que le liquide ait réduit d'environ la moitié.","Retirez le sirop du feu et laissez refroidir.","Disposez les fruits sur un plat de service et versez le sirop dessus. Garnissez de feuilles de menthe."],
["* Vous pouvez aussi utiliser des mandarines en conserve si vous n'avez pas de clémentines fraîches.","Lorsque vous planifiez vos repas, pensez à ajouter une salade de fruits au menu. Les fruits sont une bonne source de vitamines et de fibres, ainsi que d'autres nutriments qui combattent les maladies, ce qui en fait un élément important d'une alimentation saine. Les fruits contiennent aussi du potassium, ce qui peut être une préoccupation pour de nombreuses personnes atteintes d'insuffisance rénale chronique.\n\nPour réduire la teneur en potassium de votre salade de fruits, choisissez des fruits plus pauvres en potassium comme les pommes, les bleuets, les framboises, les quartiers de clémentine ou de mandarine, les raisins, les poires, l'ananas, les prunes et les canneberges séchées. Même si vous choisissez des fruits plus pauvres en potassium, la taille de la portion reste très importante. Demandez à votre diététiste quelle quantité de fruits vous devriez inclure chaque jour dans votre alimentation.\n\nLorsque vous préparez une salade de fruits, utilisez des fruits de différentes couleurs pour la rendre plus attrayante. Utilisez des fruits de saison lorsque c'est possible afin d'avoir des options fraîches, mais lorsqu'ils ne sont pas disponibles, les fruits en conserve dans leur propre jus sont aussi un bon choix.\n\nComme pour les salades de légumes, vous pouvez ajouter une vinaigrette à votre salade de fruits pour plus de saveur. Créez votre propre vinaigrette pour salade de fruits avec du miel et du jus de fruits comme le citron, la lime et l'ananas. D'autres ingrédients qui ajoutent de la saveur et de l'attrait visuel comprennent les graines de pavot, l'extrait de vanille et la cannelle. Faites des essais jusqu'à trouver la combinaison qui vous convient."],
["2 fruit pauvre en potassium"],
{"Syrup":"Sirop","Salad":"Salade","Kidney-friendly fruit salad":"Une salade de fruits adaptée aux reins"}))

I.append(mk(25,"Biscuits croustillants à l'orange et au sésame",None,"30 biscuits","1 biscuit",
["2 tasses de farine tout usage","1/2 cuillère à café de bicarbonate de soude","1/2 tasse de margarine sans sel","2/3 tasse de sucre blanc","3 cuillères à soupe de miel","1 œuf","1/2 cuillère à café d'extrait de vanille","1 1/2 cuillère à café de zeste d'orange (ou de citron)","2 cuillères à soupe de bleuets séchés, hachés finement","2 cuillères à soupe de fécule de maïs","1 cuillère à soupe de graines de sésame","1 cuillère à soupe de graines de sésame","1 cuillère à café de sucre","2 gouttes de colorant alimentaire au choix"],
["Fouettez ensemble la farine et le bicarbonate de soude. Mettez de côté.","Préparez les ingrédients humides dans un grand bol. Battez ensemble la margarine, le sucre et le miel jusqu'à ce que le mélange devienne léger et mousseux. Ajoutez l'œuf, l'extrait de vanille, le zeste, les bleuets, la fécule de maïs et les graines de sésame, et battez bien.","Ajoutez le mélange de farine aux ingrédients humides et mélangez les deux à la cuillère jusqu'à obtenir une pâte lisse.","Roulez la pâte dans du papier ciré et formez un boudin d'environ 1 1/2 pouce de diamètre.","Congelez pendant 1 heure ou plus.","Préchauffez le four conventionnel à 350 °F","Coupez des tranches de 1/2 pouce d'épaisseur et garnissez chaque tranche d'une pincée de graines de sésame sucrées.","Placez les tranches sur une plaque tapissée de papier parchemin. Faites cuire de 10 à 12 minutes.","Retirez les biscuits de la plaque et laissez refroidir sur des grilles."],
["Ces biscuits sont pauvres en potassium et en phosphore, et les personnes non diabétiques peuvent en manger deux !","Vous voudrez peut-être doubler la recette, car la pâte à biscuits se conserve bien au congélateur.","Si vous voulez simplifier la recette, vous pouvez omettre les bleuets et la garniture."],
["1 féculent"],
{"Garnish (mix in small bowl)":"Garniture (mélanger dans un petit bol)","To Bake":"Cuisson"}))

I.append(mk(26,"Poulet au curry doux et épicé",None,"12","1/12 de la recette",
["1/4 tasse d'huile d'olive","1/2 cuillère à café de poivre noir","12 pilons de poulet","1 tasse de poivron rouge ou jaune, coupé en dés","3/4 tasse d'oignon, coupé en cubes","2 gousses d'ail, hachées","2 cuillères à soupe de gingembre frais, râpé","2 cuillères à soupe de pâte de curry Madras","1 boîte (14 oz) de pêches avec leur jus, coupées en dés","3/4 tasse de yogourt à la pêche ou nature","1/4 tasse de lait de coco","2 cuillères à soupe de jus de lime (1 lime)","Coriandre fraîche hachée pour la garniture (facultatif)"],
["Faites chauffer l'huile à feu moyen dans une poêle épaisse.","Poivrez les pilons de poulet et faites-les dorer de tous les côtés.","Pendant ce temps, préparez les poivrons, l'oignon, l'ail et le gingembre.","Retirez le poulet en laissant l'huile dans la poêle.","Réduisez le feu à moyen-doux, ajoutez la pâte de curry, l'ail et le gingembre directement dans la poêle. Ajoutez les poivrons et l'oignon et enrobez bien.","Remettez le poulet dans la poêle, ajoutez les pêches avec leur jus et augmentez le feu pour amener le tout à frémir.","Couvrez et faites cuire au four pendant 40 minutes à 350 °F (four conventionnel).","Retirez du four et placez sur la cuisinière à feu doux. Ajoutez le yogourt, le lait de coco et le jus de lime. Remuez doucement jusqu'à ce que le tout soit chaud. Ne faites pas bouillir.","Garnissez de coriandre hachée et servez sur du riz blanc."],
["Cette recette peut facilement être réduite de moitié.","Peut être préparée à l'avance jusqu'à l'étape 7, puis réfrigérée ou congelée en portions. Pour terminer : faites cuire à feu doux jusqu'à ce que le tout soit chaud, puis ajoutez le yogourt, le lait de coco et le jus de lime. Faites cuire le riz pendant que vous réchauffez le poulet."],
["3 viande","1 légume","1 matière grasse"]))

I.append(mk(27,"Salade de haricots verts",None,"4","1/4 de la recette",
["2 tasses de haricots verts, parés et coupés en morceaux de 1 pouce","1 tasse de chou rouge, tranché finement","1/4 tasse d'échalote, coupée en fins anneaux","1/2 tasse de jeune roquette","1 cuillère à soupe de ciboulette, hachée finement","1 cuillère à café de moutarde de Dijon","1 cuillère à café de miel","1 cuillère à soupe de vinaigre de cidre","2 cuillères à soupe d'huile d'olive","1/8 cuillère à café de poivre noir moulu"],
["Dans une casserole, portez l'eau à ébullition et faites cuire les haricots verts (environ 5 minutes). Rincez immédiatement les haricots à l'eau froide pour arrêter la cuisson. Les haricots doivent rester croquants.","Dans un saladier, mélangez les haricots, le chou, les anneaux d'échalote et la roquette.","Dans un petit bol, fouettez ensemble les ingrédients de la vinaigrette.","Versez la vinaigrette sur le mélange de haricots verts et mélangez pour combiner."],
["Servez en accompagnement d'une viande ou d'un poisson.","Agrémentez-la d'une protéine, comme des tranches de steak ou un œuf dur, pour en faire un repas.","Une alimentation adaptée aux reins est pauvre en sodium. Lorsqu'on retire le sodium de l'alimentation, on peut perdre une saveur essentielle, ce qui rend les repas moins attrayants. Pour préparer des plats savoureux et susciter l'enthousiasme pour la cuisine, pensez à préparer une vinaigrette et à l'ajouter à diverses recettes. Elle est relativement facile à faire et peut ajouter beaucoup de saveur à de nombreux aliments. En plus d'en assaisonner votre salade préférée, arrosez-en des légumes chauds ou froids ou utilisez-la comme marinade.\n\nPour préparer une vinaigrette, suivez quelques étapes simples.\n\n• Ajoutez 1 part de vinaigre ou d'un autre acide pour 3 parts d'huile. Par exemple, mélangez ¼ tasse de vinaigre de vin rouge avec ¾ tasse d'huile d'olive. Évitez les huiles au goût très prononcé, comme certaines huiles de noix. Pour le vinaigre, tout est permis : cidre, vin rouge, vin blanc, riz et balsamique sont tous d'excellents choix. Parmi les autres acides à considérer, il y a le jus de citron ou de lime fraîchement pressé. Évitez le vinaigre blanc distillé nature, dont le goût est trop fort.\n\n• Ajoutez plus de saveur avec du poivre fraîchement moulu, un peu de moutarde, des herbes fraîches, de l'ail haché ou des échalotes hachées.\n\n• Si vous aimez un peu de douceur, ajoutez une touche de miel. Fouettez les ingrédients ensemble et conservez dans un bocal au réfrigérateur jusqu'à 5 jours. Agitez avant chaque utilisation."],
["1 légume"],
{"Slaw":"Salade","Vinaigrette":"Vinaigrette","Vinaigrette-style salad dressings":"Les vinaigrettes"}))

I.append(mk(28,"Tofu frit au miel et à la moutarde",None,"4","¼ de la recette",
["2 cuillères à soupe d'huile d'olive","2 cuillères à soupe de miel","2 cuillères à café de moutarde de Dijon","2 cuillères à café de curcuma","2 cuillères à café de cumin","1 bloc de tofu ferme (16 oz), non assaisonné","1 cuillère à café d'huile d'olive","2 tasses de brocoli, coupé en bouquets","1 tasse de poivrons rouges, coupés en fines lanières","2 cuillères à soupe d'eau","2 cuillères à soupe de vinaigre blanc","5 oz de nouilles de riz"],
["Égouttez le tofu, pressez-le avec un essuie-tout pour éliminer le liquide et coupez-le en cubes.","Dans un bol de taille moyenne ou un sac en plastique refermable, mélangez les ingrédients de la marinade : huile d'olive, miel, moutarde, curcuma et cumin. Ajoutez le tofu et réfrigérez pendant au moins 6 heures ou toute une nuit.","Dans une poêle antiadhésive, faites chauffer 1 cuillère à café d'huile d'olive à feu moyen. Sortez le tofu de la marinade. Mettez la marinade de côté. Faites frire le tofu pendant 2 minutes de chaque côté.","Transférez le tofu doré sur une assiette, badigeonnez-le du reste de la marinade et gardez-le au chaud.","Sans éteindre le feu, ajoutez le brocoli, les poivrons, l'eau et le vinaigre dans la poêle. Faites sauter les légumes pendant trois minutes ou jusqu'à ce que le liquide ait presque disparu et que les légumes soient cuits mais encore croquants. Transférez sur une assiette et gardez au chaud.","Préparez les nouilles selon les instructions sur l'emballage.","Mélangez les nouilles et les légumes et servez le tofu à côté ou dessus. Bon appétit !"],
["Remarque : les marinades sont la clé pour rendre le tofu savoureux. Plus vous faites mariner longtemps, plus il absorbe de saveur. Vous pouvez le faire mariner plus de 6 heures sans problème, mais aussi seulement 15 minutes si vous êtes pressé. Contrairement aux autres marinades pour la viande, le poisson ou la volaille, qui doivent être jetées après utilisation, il n'y a aucun danger à utiliser le reste de la marinade comme sauce lorsqu'il s'agit de tofu.","Pour les personnes atteintes d'insuffisance rénale chronique (IRC), il est important de suivre une alimentation à la fois adaptée aux reins et bonne pour le cœur. Manger plus de protéines végétales peut aider à protéger les reins tout en favorisant la santé du cœur. Une alimentation plus pauvre en protéines est généralement recommandée aux premiers stades de l'IRC afin de réduire la charge de travail des reins. Ajouter des protéines végétales, comme le tofu, à votre alimentation est un bon moyen de réduire votre apport en protéines. Ces aliments peuvent offrir une quantité satisfaisante de nourriture avec une teneur en protéines beaucoup plus faible que les protéines d'origine animale. Le tofu est fabriqué à partir de fèves de soja. Au marché, vous trouverez plusieurs variétés classées selon leur fermeté : soyeux, ferme, extra-ferme et super-ferme. Le tofu soyeux est le plus mou, avec une consistance semblable à celle d'une crème pâtissière. Il peut servir à faire des sauces et remplacer les œufs. Le tofu ferme est pressé en bloc et a la même consistance que la feta. Il peut être coupé en cubes et ajouté à un sauté, à un bol de riz, à une soupe, à une salade, ou enfilé sur des brochettes avec des légumes. Le tofu a la capacité d'absorber la saveur de tout ce avec quoi il est préparé; il est donc très facile de l'utiliser comme substitut de la viande dans vos recettes actuelles. Une portion de quatre onces de tofu ferme (environ ¼ de bloc) ne contient que 166 milligrammes de potassium et peut donc constituer une bonne source de protéines dans le cadre d'une alimentation plus pauvre en potassium. Demandez à votre diététiste-nutritionniste agréé quelle quantité de protéines végétales vous convient."],
["1 protéine","2 ½ féculent","2 légume pauvre en potassium","1 matière grasse"],
{"Tofu — a great source of plant-based protein":"Le tofu, une excellente source de protéines végétales"}))

I.append(mk(29,"Gruau aux bleuets cuit au four",None,"8","1/8 de la recette",
["1 tasse de lait (2 % de matières grasses)","1/2 tasse de compote de pommes non sucrée","1/4 tasse de beurre d'amande","1/4 tasse de miel","1/4 tasse d'huile de canola","1 cuillère à soupe d'extrait de vanille","1/8 cuillère à café de bicarbonate de soude","1/4 cuillère à café de crème de tartre","2 tasses de flocons d'avoine à cuisson rapide","1/2 tasse d'amandes en tranches","1/2 tasse de bleuets frais ou surgelés","1 tasse de bleuets frais ou surgelés","2 cuillères à soupe d'amandes en tranches","2 cuillères à soupe de cassonade","4 tasses de fromage cottage (2 % de matières grasses)"],
["Préchauffez le four à 350 °F. Graissez un plat de cuisson de 8 × 8 pouces.","Dans un grand bol, fouettez ensemble le lait, la compote de pommes, le beurre d'amande, le miel, l'huile et l'extrait de vanille jusqu'à consistance lisse. Incorporez au fouet le bicarbonate de soude et la crème de tartre.","À l'aide d'une spatule, incorporez les flocons d'avoine, les amandes en tranches et 1/2 tasse de bleuets jusqu'à ce que le tout soit bien mélangé.","Versez le mélange dans le plat de cuisson préparé et lissez le dessus.","Répartissez uniformément la garniture sur le dessus.","Faites cuire de 50 à 60 minutes, jusqu'à ce que ce soit pris, doré et que la garniture soit croustillante. Retirez du four et laissez refroidir environ 1 heure. Coupez en 8 carrés et servez avec du fromage cottage (facultatif)."],
["Astuce : savourez chaud ou froid, au petit-déjeuner ou en collation.","* Pour les greffés : réduisez la quantité totale de matières grasses en utilisant du lait à 1 % ou des produits laitiers sans gras.","Bien commencer la journée avec un petit-déjeuner sain est important lorsque vous êtes atteint d'insuffisance rénale chronique (IRC). Prendre un repas le matin vous apporte les nutriments nécessaires pour rester énergique au travail, à l'école ou dans vos autres activités quotidiennes. Certains choix comme les produits de boulangerie, les viandes de petit-déjeuner, les boissons fouettées à base de lait et les repas emballés peuvent être coûteux et riches en sodium, en potassium ou en phosphore. Il est essentiel de choisir des solutions de rechange pratiques et saines qui soutiennent les objectifs nutritionnels de l'IRC. Planifier à l'avance peut vous aider à préparer des petits-déjeuners plus économiques.\n\nChoisir un aliment protéiné est une première étape utile lors de la planification du petit-déjeuner. Les œufs sont une option riche en nutriments et peuvent être utilisés dans des quiches, des omelettes avec des légumes pauvres en potassium, ou cuits dans du pain doré ou du gruau. Les burritos maison à congeler, préparés à l'avance, offrent une autre option rapide qui se réchauffe facilement un matin occupé. Le fromage cottage faible en sodium peut aussi être une option, car une portion de ½ tasse fournit environ 13 grammes de protéines. Le fromage cottage peut être associé à des pêches ou à des poires pauvres en potassium, servir à accompagner le gruau cuit au four, ou être inclus dans des recettes de crêpes ou de muffins. Les céréales chaudes, comme le gruau d'avoine ou la crème de blé, sont d'autres choix de petit-déjeuner rapides et faciles. De plus grandes quantités peuvent être cuites puis congelées en portions individuelles pour plus de commodité. Pour ajouter des protéines, garnissez les céréales chaudes d'une once de noix ou de 1 cuillère à soupe de beurre d'arachide, d'amande ou de noix de cajou."],
["1 viande","2 produit laitier","1 féculent","½ fruit pauvre en potassium","1 matière grasse"],
{"Topping":"Garniture","Optional":"Facultatif","Plan ahead breakfast":"Planifier le petit-déjeuner à l'avance"}))

I.append(mk(30,"Craquelés au miel et au gingembre",None,"2 1/2 douzaines de biscuits","1 biscuit",
["3/4 tasse de shortening","1 tasse de sucre cristallisé","1 œuf","1/4 tasse de miel","2 tasses de farine tout usage","2 cuillères à café de bicarbonate de soude","2 1/2 cuillères à café de gingembre moulu","1 1/4 cuillère à café de cannelle","1 cuillère à café de clous de girofle moulus","Sucre cristallisé pour l'enrobage"],
["Préchauffez le four conventionnel à 325 °F.","Mélangez en crème les ingrédients humides dans un bol.","Préparez les ingrédients secs en tamisant la farine avec le bicarbonate et les épices dans un deuxième bol.","Incorporez les ingrédients secs aux ingrédients humides et mélangez bien, mais rapidement.","Déposez des cuillérées à soupe bombées dans le sucre cristallisé, roulez en boules et placez sur une plaque à biscuits graissée ou sur du papier parchemin, à 2 pouces d'intervalle.","Faites cuire de 8 à 10 minutes au centre du four, retirez et laissez refroidir sur la plaque avant de transférer sur une grille."],
["Ces biscuits sont très pauvres en phosphore et en potassium : les personnes non diabétiques peuvent en manger deux."],
["1 féculent","1 matière grasse"]))

I.append(mk(31,"Hamburger nouveau genre",None,"4","¼ de la recette",
["8 oz de tofu ferme (1/2 bloc), égoutté","8 oz de bœuf haché maigre (90 % / 10 %)","1 cuillère à soupe d'huile d'olive","1 cuillère à café d'ail, haché finement","2 cuillères à soupe d'oignon, haché","1/2 cuillère à café de poivre de Cayenne","1/2 cuillère à café de poivre noir","2 œufs","1 cuillère à café d'huile d'olive","1 tasse d'oignon, coupé en lanières","1 tasse de poivron rouge, coupé en lanières","1 cuillère à soupe de vinaigre balsamique","1 cuillère à café de miel","4 pains à hamburger (2 oz chacun)","4 feuilles de laitue"],
["Dans un bol, émiettez le tofu à la fourchette. Ajoutez le bœuf haché, 1 cuillère à soupe d'huile d'olive, l'ail, les oignons, le poivre de Cayenne, le poivre noir et les œufs. Mélangez tous les ingrédients à la fourchette et laissez reposer 15 minutes.","Allumez le gril et faites-le chauffer à feu moyen-vif.","Dans une poêle antiadhésive, faites chauffer 1 cuillère à café d'huile d'olive à feu moyen. Ajoutez les oignons et les poivrons rouges et faites-les frire pendant 2 minutes.","Ajoutez le vinaigre au mélange d'oignons et de poivrons, baissez le feu à moyen-doux et faites cuire encore 10 minutes, en remuant de temps en temps, jusqu'à ce que les légumes soient tendres.","Ajoutez le miel aux légumes pendant la dernière minute de cuisson. Éteignez le feu et mettez de côté.","Formez quatre galettes avec le mélange de viande et de tofu et placez les hamburgers sur le gril. Réduisez le feu à moyen et faites cuire les galettes 5 minutes d'un côté. Retournez-les et faites cuire encore 5 à 7 minutes. Pour vous assurer de la cuisson, utilisez un thermomètre à viande. La température interne doit atteindre 160 °F et la viande ne doit plus être rosée.","Pendant les 2 à 3 dernières minutes de cuisson, placez les pains à hamburger sur le gril pour les faire griller.","Une fois les pains grillés et les hamburgers cuits, assemblez les hamburgers en plaçant une galette sur un pain, puis garnissez du mélange de légumes et de laitue."],
["À NOTER : cette recette est plus riche en potassium et la taille de la portion est importante. Vérifiez avec votre diététiste-nutritionniste agréé comment cette recette peut être intégrée à votre alimentation. Pour l'IRC et la greffe : préparez six hamburgers de la taille de mini-burgers avec des petits pains de la même taille.","Que vous soyez aux premiers stades de l'insuffisance rénale chronique ou que vous ayez besoin de dialyse, les protéines végétales peuvent être une option saine. Consommer davantage de protéines végétales par rapport aux protéines animales produit moins d'acide dans votre corps, ce qui peut ralentir la progression de la maladie rénale et, si vous avez besoin de dialyse, aidera à protéger vos os et vos muscles.\n\nIl peut être difficile de changer radicalement ses habitudes alimentaires du jour au lendemain, surtout si la viande a toujours fait partie de votre alimentation. Une façon d'atteindre l'objectif de manger plus de protéines végétales est de faire évoluer votre alimentation au fil du temps, en mangeant moins de protéines animales et en intégrant davantage de protéines végétales. Cela peut se faire en ajustant vos menus quotidiens ou une recette à la fois. Cette recette est un exemple classique d'ajout d'une protéine végétale comme le tofu au bœuf pour obtenir un hamburger plus sain. Le hamburger obtenu est plus pauvre en matières grasses, en graisses saturées et en cholestérol, et mieux adapté aux reins, car il est plus pauvre en protéines, en potassium et en phosphore."],
["3 protéine","2 féculent","1 légume pauvre en potassium"],
{"How to transition to using more plant-based protein":"Comment passer à une plus grande consommation de protéines végétales"}))
save('p04',I)
