from h import *
I=[]
I.append(mk(32,"Bol poke au vermicelle",None,"4","¼ de la recette",
["14 oz de tofu extra-ferme","1 cuillère à soupe d'huile de canola","¼ tasse d'huile de canola","3 cuillères à soupe de jus de lime","1 cuillère à café de zeste de lime","½ gousse d'ail, hachée finement","2 cuillères à soupe de miel","2 cuillères à café de gingembre frais, râpé (ou ¼ cuillère à café de gingembre moulu)","1 cuillère à café de sauce soja faible en sodium","1 cuillère à café de sauce hoisin","1 cuillère à café d'huile de sésame","½ cuillère à café de sambal oelek*","5 oz (environ 150 g) de vermicelles de riz","1 tasse de carotte râpée","1 tasse de concombre anglais, coupé en dés"],
["Pressez ou épongez le tofu pour éliminer l'excès d'humidité, puis coupez-le en cubes de ½ pouce.","Dans un petit bol, fouettez ensemble tous les ingrédients de la sauce jusqu'à ce qu'ils soient bien combinés.","Dans une poêle antiadhésive, faites chauffer l'huile de canola à feu moyen-vif. Ajoutez le tofu et faites cuire en remuant de temps en temps, jusqu'à ce qu'il soit croustillant, environ 8 minutes.","Dans une casserole, portez l'eau à ébullition et faites cuire les vermicelles de riz selon les instructions sur l'emballage. Égouttez dans une passoire, puis remettez les vermicelles dans la casserole et ajoutez quelques gouttes d'huile si les nouilles collent.","Répartissez les vermicelles de riz dans quatre bols. Garnissez chaque bol de carotte, de concombre, de radis, d'oignons verts, de menthe ou de coriandre, d'arachides et de tofu croustillant.","Versez la sauce à la cuillère ou en filet sur chaque bol et assaisonnez de poivre noir au goût."],
["Inclure de bonnes graisses dans une alimentation pour l'insuffisance rénale chronique (IRC) est encouragé. Les matières grasses fournissent de l'énergie, mais trop de certains types peuvent être nocifs pour votre cœur et vos reins. Les graisses saturées et les gras trans sont considérés comme de « mauvaises » graisses, car ils augmentent le risque de maladie cardiaque et d'inflammation. En comparaison, les graisses insaturées, telles que les graisses monoinsaturées et polyinsaturées, sont des choix plus sains qui aident à réduire le cholestérol sanguin et l'inflammation. Les huiles de cuisson sont fréquemment utilisées comme ingrédient ou comme enrobage dans les recettes et améliorent la texture, la saveur et l'humidité. Le coût peut varier selon le type d'huile; conserver les huiles dans des contenants hermétiques, dans un endroit sombre et frais, peut donc aider à économiser en évitant qu'elles ne se gâtent. La modération est essentielle dans l'utilisation de l'huile, car chaque type offre un profil nutritionnel différent. HUILE DE CANOLA : ce type d'huile polyinsaturée offre les avantages des acides gras oméga-3 et oméga-6 et est pauvre en graisses saturées. Avec un goût plus neutre, l'huile de canola peut être utilisée dans une variété de recettes. HUILE D'OLIVE : considérée comme une huile bonne pour le cœur, elle est une bonne source d'antioxydants et de graisses monoinsaturées. L'huile d'olive a un goût plus prononcé et peut rehausser le goût des vinaigrettes, des glaçages ou des marinades. HUILE DE SÉSAME : pauvre en graisses saturées et riche en acides gras oméga-3 et oméga-6, l'huile de sésame est une autre bonne option. Souvent de saveur douce, cette huile convient bien pour faire sauter les aliments ou dans une recette. HUILE DE NOIX DE COCO ET HUILE DE PALME : contenant une grande quantité de graisses saturées, utilisez l'huile de noix de coco et l'huile de palme avec modération. Trop en consommer peut contribuer au risque de cholestérol élevé et de maladie cardiaque."],
["1 viande","3 féculent","1 ½ légume riche en potassium","4 matière grasse"],
{"Tofu":"Tofu","Sauce":"Sauce","Salad":"Salade","Use of Oils with Cooking":"Utilisation des huiles en cuisine"}))

I.append(mk(33,"Poulet sucré à l'érable et rutabaga",None,"5","1/5 de la recette",
["2 tasses de rutabaga, coupé en quartiers","3/4 tasse de poivron rouge, coupé en dés","1 lb de poitrine de poulet désossée, coupée en cubes de 1 pouce","1 cuillère à soupe de farine","Poivre noir au goût","2 cuillères à café d'huile végétale","3 gousses d'ail, hachées","1 cuillère à café de thym","1 cuillère à café de romarin frais haché (ou d'origan séché)","1 cuillère à soupe de persil haché","1 cuillère à café de graines de moutarde","2 cuillères à soupe de vinaigre de cidre","2 cuillères à soupe de sirop d'érable","1/4 tasse d'eau","Poivre noir au goût"],
["Préchauffez le four à 350 °F.","Portez l'eau à ébullition, ajoutez le rutabaga et faites bouillir pendant 5 minutes. Égouttez et jetez l'eau. Placez le rutabaga dans un plat allant au four de 2 pintes et ajoutez les poivrons.","Enrobez les cubes de poulet de farine et poivrez-les.","Dans une poêle antiadhésive, faites chauffer l'huile à feu moyen-vif et faites dorer délicatement le poulet. (5 minutes)","Mélangez l'ail avec les herbes, les graines, le vinaigre, le sirop et l'eau. Versez sur le poulet cuit et portez à frémissement. Transférez dans le plat allant au four avec le rutabaga.","Placez au four et faites cuire pendant 25 minutes."],
[],["3 viande","2 légume"]))

I.append(mk(34,"Salade de couscous aux pois chiches",None,"6","1/6 de la recette",
["1/2 boîte (7,5 oz) de pois chiches, sans sel ajouté, égouttés et rincés","1 cuillère à soupe d'huile d'olive","1 tasse d'oignon, haché","1 tasse de courgette, coupée en dés","1 tasse de poivrons rouges, coupés en dés","1 cuillère à café de curcuma moulu","1 cuillère à café de paprika moulu","1 tasse de bouillon de poulet non salé","1 tasse de couscous non cuit","1 tasse de poulet cuit, coupé en dés","2 cuillères à soupe de jus d'orange fraîchement pressé","2 cuillères à soupe d'oignons verts, tranchés"],
["Remplissez un grand bol d'eau et faites tremper les pois chiches pendant 12 heures ou toute une nuit pour réduire le phosphore et le potassium. Égouttez, rincez et mettez de côté.","Dans une grande poêle, faites chauffer l'huile à feu moyen. Faites revenir les oignons pendant 2 minutes. Ajoutez la courgette et les poivrons rouges et faites revenir encore 2 minutes. Assaisonnez de curcuma et de paprika et remuez pour combiner.","Ajoutez le bouillon dans la poêle et portez à ébullition. Ajoutez le couscous, le poulet et les pois chiches, et remuez pour combiner. Retirez la poêle du feu, couvrez et laissez reposer 5 minutes.","Savourez le couscous chaud ou transférez-le dans un contenant fermé et réfrigérez.","Avant de servir, ajoutez le jus d'orange et les oignons verts tranchés."],
["Il est important d'inclure une variété de sources de protéines lorsque vous suivez une alimentation adaptée aux reins. Selon le stade de l'insuffisance rénale chronique, la quantité de protéines recommandée par jour varie. Intégrer des sources de protéines végétales peut aider à atteindre les objectifs quotidiens en protéines.\n\nLes protéines d'origine animale, par exemple la viande, contiennent du phosphore naturel. Lorsque vous mangez des protéines d'origine animale, environ 30 à 80 % du phosphore de ces aliments est absorbé par l'organisme. En comparaison, les aliments d'origine végétale ont un taux d'absorption beaucoup plus faible, de seulement 20 à 40 %. À mesure que l'insuffisance rénale chronique progresse, il est important de limiter le phosphore total, car les reins sont moins capables de filtrer ce nutriment, ce qui peut entraîner des accumulations nocives dans l'organisme.\n\nLes sources de protéines végétales comprennent les légumineuses, le soja, les substituts de viande, les grains entiers, les noix et les beurres de noix. Lisez les étiquettes des produits emballés pour éviter les aliments riches en sodium, en potassium ou contenant des additifs phosphorés indésirables. Choisir la bonne portion est nécessaire pour atteindre vos objectifs nutritionnels particuliers. Essayer différentes recettes peut vous permettre de trouver des repas végétaux à savourer. Ajouter des légumineuses aux soupes ou aux salades, choisir du soja pour les sautés, opter pour des substituts de viande dans les hamburgers, incorporer des grains entiers aux casseroles et utiliser des noix, des beurres de noix ou des graines pour relever les céréales chaudes ou les produits de boulangerie ne sont que quelques idées à essayer."],
["1 viande","2 féculent","½ légume pauvre en potassium"],
{"Including vegetable protein and lowering phosphorus absorption":"Inclure des protéines végétales et réduire l'absorption du phosphore"}))

I.append(mk(35,"Boisson fouettée protéinée aux bleuets et aux poires",None,"1","1 boisson fouettée",
["½ tasse de boisson de riz enrichie, non sucrée, à la vanille","1 ½ cuillère à soupe de poudre de protéine de lactosérum non aromatisée","¼ tasse de bleuets","¼ tasse de poire en conserve","1 cuillère à soupe de flocons d'avoine","1 cuillère à soupe de miel (facultatif)"],
["Mettez tous les ingrédients dans un mélangeur et mélangez jusqu'à consistance lisse.","Servez immédiatement."],
["* Comptez les glucides des boissons fouettées dans vos objectifs de glucides totaux pour le repas ou la collation","Trouver le temps de planifier et de préparer les repas est une grande préoccupation pour la plupart des personnes atteintes d'une maladie rénale. Souvent, il est beaucoup plus simple de prendre quelque chose rapidement plutôt que de passer du temps à cuisiner et de s'asseoir pour un repas plus équilibré. Ajouter de la poudre de protéine aux repas ou aux collations est une méthode simple pour limiter le potassium et vous aider à atteindre vos objectifs quotidiens en protéines lorsque vous manquez de temps.\n\nLa quantité de protéines varie selon les poudres et peut aller de 10 à 50 grammes par portion. Travailler avec un diététiste-nutritionniste agréé peut vous aider à déterminer le choix idéal et la quantité de protéines dont vous avez besoin. La protéine de lactosérum peut être utilisée dans le cadre de votre alimentation pour les reins et existe aromatisée ou non aromatisée.\n\nPréparez une collation rapide en mélangeant une mesure de poudre de protéine avec des fruits frais, du lait de riz et de la glace pour obtenir une délicieuse boisson fouettée, ou incorporez de la poudre de protéine à une recette de muffins pour augmenter votre apport en protéines. Vous pouvez aussi ajouter une mesure de poudre de protéine à votre boisson préférée ou à un aliment mou pour ajouter des protéines sans effort."],
["1 viande","3 féculent"],
{"Protein powder in smoothies or snacks":"La poudre de protéine dans les boissons fouettées ou les collations"}))

I.append(mk(36,"Soupe asiatique aux nouilles",None,"6","1/6 de la recette",
["4 tasses de bouillon de poulet non salé","2 cuillères à soupe de gingembre frais, pelé et râpé","2 tasses de tofu extra-ferme, coupé en cubes de ½ pouce","2 cuillères à café de sauce soja faible en sodium","1 cuillère à café de pâte d'ail et de piment","1 cuillère à soupe de vinaigre de riz","1 tasse d'oignons verts, tranchés","¾ tasse de céleri, tranché","¼ tasse de poivron rouge, tranché","1 ½ tasse de chou vert, tranché finement","2 cuillères à soupe d'huile d'olive extra vierge","1 cuillère à café d'huile de sésame","6 oz de vermicelles de riz, non cuits","½ tasse de coriandre fraîche, hachée","1 cuillère à soupe de jus de lime","poivre moulu au goût"],
["poivre moulu au goût","Faites chauffer le bouillon.","Dans un petit bol, mélangez le gingembre, le tofu, la sauce soja, la pâte de piment et le vinaigre pour faire mariner le tofu. Ajoutez le tofu et mettez de côté.","Tranchez les oignons verts, séparez les tranches vertes des blanches et mettez-les de côté.","Mélangez le céleri, les tranches vertes des oignons verts, le poivron rouge et le chou dans un bol.","Faites chauffer une grande casserole ou une poêle profonde de type wok pendant 2 minutes à feu moyen-vif. Ajoutez l'huile d'olive et l'huile de sésame et faites revenir les parties blanches des oignons verts jusqu'à ce qu'elles soient dorées et un peu croustillantes, sans être brûlées.","Baissez le feu à moyen, ajoutez le tofu et sa marinade, en remuant pour bien l'enrober, et faites cuire pendant 2 minutes.","Ajoutez tous les légumes de l'étape 4 et poursuivez la cuisson encore 2 à 3 minutes.","Versez le bouillon chaud sur les légumes, augmentez le feu et portez rapidement à ébullition. Ajoutez les nouilles de riz et faites cuire pendant 2 minutes.","Éteignez le feu, incorporez la coriandre et le jus de lime et assaisonnez de poivre noir."],
["Les restes de soupe peuvent être réchauffés dans les deux jours s'ils sont conservés au réfrigérateur.","Pour les personnes atteintes d'insuffisance rénale chronique, il est important de consommer la bonne quantité de protéines. Les protéines peuvent provenir de sources animales comme la viande maigre, le porc, le poulet, la dinde, le poisson, les fruits de mer, les œufs et les produits laitiers, ou de sources végétales comme les haricots, les légumineuses et le tofu.\n\nIl est important de noter que la teneur en potassium des sources de protéines peut beaucoup varier. C'est le cas même pour des aliments riches en protéines qui semblent similaires. Par exemple, parmi les produits laitiers, le fromage est plus pauvre en potassium, alors que le lait et le yogourt peuvent en contenir beaucoup (notez toutefois que le fromage peut contenir beaucoup plus de sodium). Cela peut aussi s'appliquer aux différents types de tofu. Les variétés de tofu soyeux contiennent nettement plus de potassium que le tofu ferme ou extra-ferme ordinaire. Tenez compte de ces faits s'il est important pour vous de suivre une alimentation plus pauvre en potassium.\n\nLes sources de protéines végétales peuvent être bonnes pour le cœur et aider à contrôler la glycémie des personnes diabétiques. Essayez de remplacer la viande par du tofu dans certaines de vos recettes. Un moyen facile de commencer est de l'ajouter à un sauté ou à une salade. Vous pouvez aussi l'enfiler sur des brochettes avec des légumes. En général, la teneur en potassium des protéines végétales est plus élevée que celle de la viande, de la volaille ou du poisson. Demandez à votre diététiste-nutritionniste agréé quelle quantité et quels types de protéines vous conviennent."],
["1 viande","2 féculent","1 légume","1 matière grasse"],
{"Tofu and the kidney diet":"Le tofu et l'alimentation pour les reins"}))

I.append(mk(37,"Sandwich grillé à la poire et au cheddar",None,"2","½ de la recette",
["2 oz de cheddar blanc fort","2 muffins anglais de blé entier","½ poire, tranchée finement*","1/8 cuillère à café de cannelle","2 cuillères à café de miel","1 cuillère à soupe d'huile d'olive"],
["Tranchez le fromage finement ou râpez-le. Placez le fromage et les tranches de poire sur deux moitiés de muffin. Assaisonnez de cannelle et arrosez de miel. Recouvrez avec les moitiés de muffin restantes.","Faites chauffer l'huile à feu moyen dans une poêle antiadhésive. Faites griller les sandwichs deux minutes de chaque côté ou jusqu'à ce que les muffins soient dorés et que le fromage soit fondu. À l'aide d'une spatule, exercez une légère pression sur les sandwichs pendant la cuisson."],
["* Si vous avez un trancheur à fromage, utilisez-le pour le fromage et la poire. Vous pouvez aussi utiliser une pomme au lieu d'une poire.","ASTUCE : ajouter quelques feuilles de roquette, comme sur notre photo, apportera de la couleur et un léger goût poivré.","Les plats réconfortants peuvent faire partie d'un mode de vie sain moyennant quelques ajustements de recettes pour répondre aux besoins d'une alimentation adaptée aux reins. Un bol de soupe chaude avec un sandwich en est un exemple. Il est important de tenir compte des ingrédients de ces aliments pour respecter les objectifs de votre alimentation. Les plats préparés avec des soupes condensées ou des sauces épaisses doivent être consommés avec prudence. Beaucoup peuvent être riches non seulement en sodium, mais aussi en potassium. Comprendre quels aliments peuvent être plus riches en potassium peut aider à planifier vos repas et à inclure certains de vos préférés.\n\nDans de nombreux sandwichs, le fromage fondu est utilisé pour donner de la saveur et comme garniture. Choisir le bon type de fromage est important, non seulement pour obtenir le goût désiré, mais aussi pour s'assurer que votre choix n'est pas trop riche en sodium, en potassium ou en phosphore. La taille de la portion peut aussi faire une différence et doit être prise en compte lors de la préparation de votre plat. Parmi les fromages pauvres en phosphore qui peuvent produire l'effet fondant désiré, on trouve le cheddar fort, la mozzarella et la fontina. En général, la plupart d'entre eux sont aussi pauvres en potassium par portion. Il faut être prudent avec un choix faible en sodium. Assurez-vous de lire les étiquettes pour vérifier que du chlorure de potassium ne remplace pas le chlorure de sodium dans ces fromages."],
["1 produit laitier","2 féculent","½ fruit pauvre en potassium","2 matière grasse"],
{"Cheeses for melting can fit into a kidney diet":"Les fromages à fondre peuvent s'intégrer à une alimentation pour les reins"}))

I.append(mk(38,"Salade de chou asiatique",None,"8","1/8 de la recette",
["3 tasses du chou de votre choix, râpé finement","1 carotte, pelée et râpée","1 tasse de germes de haricots","1/2 tasse de raisins, coupés en deux","1 pomme verte, râpée","Jus de 1/2 gros citron, ou de 1 petit","1/3 tasse de vinaigre de vin blanc","1 cuillère à soupe de concentré de jus d'orange","2/3 tasse d'huile de canola","1/2 cuillère à café de graines de céleri","1/4 cuillère à café de poivre noir","1 cuillère à soupe de miel","1/4 tasse de ciboulette fraîche, hachée finement"],
["Préparez les légumes et les fruits.","Transférez-les dans un bol en verre, en râpant la pomme en dernier et en arrosant tous les ingrédients de jus de citron avant de mélanger (pour éviter qu'ils ne brunissent).","Dans un petit bol, mélangez tous les ingrédients de la vinaigrette.","Versez la vinaigrette sur la salade et mélangez.","Réfrigérez jusqu'au moment de servir."],
["Préparez à l'avance et conservez au réfrigérateur.","Cette recette peut facilement être réduite de moitié.","Les légumes font partie d'une alimentation saine pour tous. Malheureusement, pour les personnes atteintes d'insuffisance rénale chronique, de nombreux légumes peuvent contenir trop de potassium pour être consommés quotidiennement. Le chou est toutefois plus pauvre en potassium et peut être consommé tous les jours si on le souhaite. Une portion de 1 tasse de chou cru râpé ne contient que 120 milligrammes de potassium. Le chou est aussi riche en fibres, en vitamines, en minéraux et en antioxydants. Tout cela peut favoriser le fonctionnement de l'intestin, la santé du cœur et protéger contre le cancer.\n\nIl existe de nombreuses variétés de chou, mais les plus courantes sont les variétés verte, rouge et pourpre. Lorsque vous achetez un chou, choisissez des pommes fermes et denses, aux feuilles brillantes, ni fendues ni meurtries.\n\nLe chou est aussi une aubaine sur le plan nutritionnel, car c'est généralement un légume frais abordable qui peut être savouré dans de nombreux types de recettes. Le chou peut être râpé et ajouté à des salades de laitue, ou utilisé pour faire une salade hachée ou une salade de chou. Garnissez un sandwich ou des tacos de salade de chou pour plus de croquant et de saveur. Faites-le cuire à la vapeur ou sauter et servez-le en accompagnement. Ajoutez-le à votre prochain sauté ou à vos soupes et ragoûts."],
["1 légume pauvre en potassium","1/2 fruit pauvre en potassium","3 matière grasse"],
{"Salad":"Salade","Dressing":"Vinaigrette","Cabbage":"Le chou"}))

I.append(mk(39,"Tarte à la crème pâtissière",None,"8","1/8 de la recette",
["1 fond de tarte profond non cuit, du commerce","4 gros œufs","½ tasse de sucre cristallisé","1½ tasse de lait chaud (2 % de matières grasses)","2 cuillères à café d'extrait de vanille","½ cuillère à café de muscade (ou de cannelle)","1 cuillère à soupe de sirop d'érable","1 tasse de fraises tranchées"],
["Préchauffez le four à 450 °F et placez la grille au centre.","Dans un bol, fouettez ensemble les œufs, le sucre, le lait et l'extrait de vanille.","Versez dans le fond de tarte et saupoudrez de muscade (ou de cannelle). Faites cuire 10 minutes à 450 °F.","Réduisez la température du four à 350 °F et faites cuire encore 25 minutes ou jusqu'à ce que la crème soit prise.","Laissez refroidir ou servez tiède. Arrosez de sirop d'érable et garnissez de fraises tranchées."],
["La pâte à tarte offre une base polyvalente qui peut servir à préparer de nombreuses recettes. Peu coûteuse à préparer ou à acheter, elle peut être utilisée pour une quiche aux œufs et aux légumes pauvres en potassium, un pâté au poulet ou au bœuf, des empanadas faibles en sodium ou une tarte aux fruits. Si vous aimez cuisiner, vous pouvez préparer des pâtes à tarte maison avec des ingrédients simples et peu coûteux que vous avez probablement déjà sous la main. La plupart des recettes comprennent de la farine, de l'eau, du sel et du beurre ou du shortening. Les quantités précises d'ingrédients, comme le sel, peuvent être ajustées pour obtenir le goût désiré et la quantité de sodium voulue par portion. Bien que la pâte maison soit meilleure consommée peu après sa préparation, elle ne contient pas d'additifs à base de phosphate ou de potassium comme les pâtes à tarte du commerce. Les pâtes à tarte du commerce sont une solution de rechange pratique lorsque vous manquez de temps ou pour un repas économique préparé dans un seul plat. Achetées réfrigérées ou congelées, elles ont aussi une durée de conservation plus longue. La préparation est minimale, avec des instructions de cuisson faciles à suivre. Comparées à une pâte faite maison, les pâtes à tarte préparées peuvent contenir plus d'ingrédients, dont certains sont plus riches en sodium, en potassium ou en phosphore. Lire la liste des ingrédients et éviter les pâtes contenant des additifs « phos » ou « potassium » peut vous aider à choisir la meilleure option."],
["½ protéine","1 féculent","1 fruit pauvre en potassium","1 matière grasse"],
{"Garnish":"Garniture","Pie crust — use for a variety of recipes":"La pâte à tarte, utile pour de nombreuses recettes"}))
save('p05',I)
