from h import *
R=[]
R.append({"id":6866329,"translations":{"ar":T("صلصة الكمثرى المحمصة","بدلًا من صلصة التفاح الجاهزة، جرّب صلصة الكمثرى البسيطة محلية الصنع! للكمثرى نكهة ألطف وأحلى من التفاح. وتحميص الكمثرى قبل هرسها في الخلاط يكرمل سكرياتها الطبيعية فتصبح النكهة أحلى.","6","½ كوب",
["3 حبات كمثرى كبيرة (حوالي 1½ رطل، منزوعة القلب ومقطعة إلى قطع بحجم 1 بوصة)","2 ملعقة صغيرة زبدة (مذابة)","1 ملعقة كبيرة عسل أو 2 ظرف من المُحلّي الصناعي","1 ملعقة كبيرة عصير ليمون","⅓ كوب جوز (مفروم ومحمص)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية).","في وعاء كبير، قلّب الكمثرى مع الزبدة المذابة. ضع الكمثرى في طبق خبز وحمّصها دون تغطية لمدة 20 إلى 25 دقيقة أو حتى تلين الكمثرى، مع التحريك مرة أو مرتين. اترك الكمثرى المطبوخة جانبًا لتبرد.","أعد الكمثرى إلى الوعاء الكبير، وأضف العسل وعصير الليمون. باستخدام خلاط يدوي أو خلاط عادي، اخلط مزيج الكمثرى حتى يصبح ناعمًا تقريبًا. أضف الجوز وحرّك."])}})
R.append({"id":6866643,"translations":{
"es":T("Tortilla de tomate y albahaca","Comience el día con una sabrosa tortilla de tomate y albahaca. Usar claras de huevo ayuda a reducir la grasa saturada, mientras que el tomate y la albahaca frescos aportan un toque de color y sabor.","1","1 tortilla",
["1 cucharadita de aceite de canola","1 huevo grande","2 claras de huevo grandes","1/2 tomate roma (pera) grande (en cubitos)","1 cucharada de albahaca (en trozos pequeños)","1/8 cucharadita de sal","1/8 cucharadita de pimienta negra"],
["Bata los huevos en un tazón y sazone con sal y pimienta.","Caliente el aceite en una sartén antiadherente pequeña a fuego medio.","Vierta los huevos batidos en la sartén.","Espolvoree el tomate en cubitos y la albahaca picada sobre la mitad de la tortilla.","Cuando los huevos estén cuajados, doble la tortilla por la mitad y cocine hasta que el tomate se ablande, unos 30 segundos."]),
"ar":T("أومليت الطماطم والريحان","ابدأ يومك بأومليت لذيذ بالطماطم والريحان. استخدام بياض البيض يساعد على تقليل الدهون المشبعة، بينما تضفي الطماطم والريحان الطازجان لمسة من اللون والنكهة.","1","1 أومليت",
["1 ملعقة صغيرة زيت الكانولا","1 بيضة كبيرة","2 بياض بيض كبير","½ حبة طماطم روما كبيرة (مقطعة إلى مكعبات)","1 ملعقة كبيرة ريحان (ممزق)","⅛ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود"],
["اخفق البيض في وعاء وتبّله بالملح والفلفل.","سخّن الزيت في مقلاة صغيرة غير لاصقة على نار متوسطة.","اسكب البيض المخفوق في المقلاة.","انثر مكعبات الطماطم والريحان المقطع على نصف الأومليت.","عندما يتماسك البيض، اطوِ الأومليت إلى النصف واطهه حتى تلين الطماطم، حوالي 30 ثانية."])}})
R.append({"id":6867665,"translations":{
"es":T("Sancocho costero","El sancocho es un tipo de guiso latinoamericano que se prepara con carne y tubérculos. Esta receta usa pescado, bueno para el corazón, en lugar de carne de res, para obtener un plato sabroso y bajo en grasa saturada.","8","1 taza",
["1/2 taza de repollo finamente picado","1/2 taza de guisantes (arvejas) frescos o congelados","1/2 cucharadita de jugo de limón verde","1/2 libra de filete de lenguado (cortado en trozos del tamaño de un bocado)","1/2 libra de pescado blanco de carne firme (como halibut, róbalo o bacalao) (cortado en trozos del tamaño de un bocado)","1/2 plátano maduro entero (cortado en trozos de 1 pulgada)","2 zanahorias medianas (en cubos)","2 papas enteras (peladas y cortadas en trozos)","1 cucharada de leche descremada","1 libra de yuca (pelada y cortada en 4 pedazos)","4 tazas de agua","2 tazas de jugo de almejas","1 cucharada más 1/2 taza de cilantro fresco picado (porción dividida)","1/4 taza de pimiento rojo dulce o picante finamente picado","1 diente de ajo (picado)","1 cebolla mediana (pelada y finamente picada, porción dividida)","1 cucharada de aceite de oliva"],
["Combine la otra mitad de la cebolla y 1/2 taza de cilantro en un tazón pequeño. Adorne cada porción de sopa con 1 cucharada de la mezcla.","Agregue las papas, las zanahorias, el plátano, el pescado y el jugo de limón, y cocine a fuego lento durante 15 minutos. Agregue los guisantes y el repollo y cocine a fuego lento durante 5 minutos.","Agregue la yuca y la leche, tape y cocine a fuego lento durante 20 minutos.","Caliente el aceite en una olla grande y sofría 1/2 de la cebolla, el ajo, el pimiento y 1 cucharada de cilantro durante 3–4 minutos. Agregue el jugo de almejas y el agua y deje que hierva."]),
"ar":T("سانكوتشو ساحلي","السانكوتشو نوع من اليخنات الشائعة في أمريكا اللاتينية، يُحضَّر من اللحم والخضار الجذرية. تستخدم هذه الوصفة السمك المفيد للقلب بدلًا من لحم البقر للحصول على طبق لذيذ منخفض الدهون المشبعة.","8","1 كوب",
["½ كوب ملفوف مفروم ناعمًا","½ كوب بازلاء طازجة أو مجمدة","½ ملعقة صغيرة عصير ليمون أخضر","½ رطل شرائح سمك موسى (مقطعة إلى قطع بحجم اللقمة)","½ رطل سمك أبيض متماسك اللحم (مثل الهلبوت أو القاروص أو القد) (مقطع إلى قطع بحجم اللقمة)","½ حبة موز بلانتين ناضجة (مقطعة إلى قطع بحجم 1 بوصة)","2 حبة جزر متوسطة (مقطعة إلى مكعبات)","2 حبة بطاطس (مقشرة ومقطعة إلى قطع)","1 ملعقة كبيرة حليب خالي الدسم","1 رطل يوكا (كسافا) (مقشرة ومقطعة إلى 4 قطع)","4 أكواب ماء","2 كوب عصير محار","1 ملعقة كبيرة بالإضافة إلى ½ كوب كزبرة خضراء طازجة مفرومة (تُقسم)","¼ كوب فلفل أحمر حلو أو حار مفروم ناعمًا","1 فص ثوم (مفروم)","1 حبة بصل متوسطة (مقشرة ومفرومة ناعمًا، تُقسم)","1 ملعقة كبيرة زيت زيتون"],
["اخلط النصف الآخر من البصل مع ½ كوب كزبرة خضراء في وعاء صغير. زيّن كل طبق شوربة بملعقة كبيرة (1) من هذا الخليط.","أضف البطاطس والجزر والموز والسمك وعصير الليمون واتركها على نار هادئة لمدة 15 دقيقة. أضف البازلاء والملفوف واتركها على نار هادئة لمدة 5 دقائق.","أضف اليوكا والحليب، وغطِّ القدر، واتركها على نار هادئة لمدة 20 دقيقة.","سخّن الزيت في قدر كبير واقلِ ½ كمية البصل والثوم والفلفل و1 ملعقة كبيرة من الكزبرة الخضراء لمدة 3–4 دقائق. أضف عصير المحار والماء واتركه حتى يغلي."])}})
R.append({"id":6868420,"translations":{
"es":T("Barras de naranja y manzana","Estas barras, con su fina capa de sabrosa mantequilla de manzana, son un delicioso refrigerio o postre. La base se prepara con avena, buena para el corazón, para aumentar la fibra.","24","1 barra",
["1 rociada de aceite en aerosol antiadherente","1 taza de avena tradicional","1 taza de harina de trigo integral","1/4 taza de azúcar","1/2 cucharadita de cardamomo molido","1/4 cucharadita de nuez moscada molida","1/4 cucharadita de bicarbonato de sodio","2 claras de huevo grandes","3 cucharadas de aceite de canola","2 cucharadas de jugo de naranja","1 1/2 tazas de mantequilla de manzana","2 cucharaditas de ralladura de naranja"],
["Precaliente el horno a 350° F. Rocíe ligeramente un molde para hornear cuadrado de 8 pulgadas con aceite en aerosol.","En un tazón mediano, mezcle la avena, la harina, el azúcar, el cardamomo, la nuez moscada y el bicarbonato de sodio.","En un tazón pequeño, bata ligeramente las claras de huevo con un tenedor. Agregue el aceite y 2 cucharadas de jugo de naranja fresco.","Agregue la mezcla de claras a la mezcla de avena y revuelva hasta que se mantenga unida. Presione tres cuartas partes de la mezcla en el molde.","En un tazón mediano, mezcle la mantequilla de fruta con 2 cucharaditas de la ralladura de naranja. Con una espátula de goma, extienda la mezcla de mantequilla de fruta sobre la mezcla de avena. Espolvoree con el resto de la mezcla de avena.","Hornee de 30 a 35 minutos, o hasta que la parte superior esté dorada. Pase el molde a una rejilla y deje enfriar por completo; luego corte en 24 barras iguales."]),
"ar":T("ألواح البرتقال والتفاح","هذه الألواح، بطبقتها الرقيقة من زبدة التفاح اللذيذة، وجبة خفيفة أو حلوى رائعة. تُحضَّر القاعدة من الشوفان المفيد للقلب لزيادة الألياف.","24","1 لوح",
["1 بخة من بخاخ الطهي غير اللاصق","1 كوب شوفان تقليدي","1 كوب دقيق القمح الكامل","¼ كوب سكر","½ ملعقة صغيرة هيل مطحون","¼ ملعقة صغيرة جوزة الطيب المطحونة","¼ ملعقة صغيرة بيكربونات الصودا","2 بياض بيض كبير","3 ملعقة كبيرة زيت الكانولا","2 ملعقة كبيرة عصير برتقال","1½ كوب زبدة التفاح","2 ملعقة صغيرة قشر برتقال مبشور"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). رش طبق خبز مربعًا بقياس 8 بوصات رشًا خفيفًا ببخاخ الطهي.","في وعاء متوسط، اخلط الشوفان والدقيق والسكر والهيل وجوزة الطيب وبيكربونات الصودا.","في وعاء صغير، اخفق بياض البيض خفيفًا باستخدام شوكة. أضف الزيت و2 ملعقة كبيرة من عصير البرتقال الطازج وحرّك.","أضف مزيج بياض البيض إلى مزيج الشوفان وحرّك حتى يتماسك المزيج. اضغط ثلاثة أرباع المزيج في طبق الخبز.","في وعاء متوسط، اخفق زبدة الفاكهة مع 2 ملعقة صغيرة من قشر البرتقال. باستخدام ملعقة مطاطية، افرد مزيج زبدة الفاكهة فوق مزيج الشوفان. انثر فوقه باقي مزيج الشوفان.","اخبزه لمدة 30–35 دقيقة، أو حتى يصبح وجهه ذهبي اللون. انقل الطبق إلى رف التبريد واتركه يبرد تمامًا، ثم قطّعه إلى 24 لوحًا متساويًا."])}})
R.append({"id":6869591,"translations":{
"es":T("Wrap de requesón y verduras","Pruebe una nueva forma de comer requesón con estos deliciosos y fáciles wraps de requesón y verduras. Si desea agregar un toque de sabor, rocíe un poco de glaseado balsámico antes de enrollar los wraps.","4","1 wrap",
["4 tortillas pequeñas de harina de trigo integral","1 taza de requesón (sin sal agregada, bajo en grasa)","1 taza de tomates cherry (cortados por la mitad)","1/2 pepino mediano (en rodajas finas)","1/4 taza de cebolla morada (en rodajas finas)","1/4 taza de pimientos (en tiras finas)","1/4 taza de hierbas frescas (como eneldo, albahaca, perejil, picadas)","1/16 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Extienda las tortillas sobre una superficie limpia.","Unte el requesón de manera uniforme sobre cada tortilla.","Distribuya los tomates cherry, las rodajas de pepino, la cebolla morada y los pimientos sobre el requesón.","Espolvoree las hierbas frescas por encima.","Sazone con la sal y la pimienta.","Doble los lados de las tortillas y luego enróllelas firmemente para formar los wraps."]),
"ar":T("لفائف الجبن القريش والخضار","جرّب طريقة جديدة لتناول الجبن القريش مع لفائف الجبن القريش والخضار اللذيذة وسهلة التحضير. وإذا أردت إضافة لمسة من النكهة، جرّب رش قليل من صلصة البلسميك المركزة قبل لف اللفائف.","4","1 لفة",
["4 أرغفة تورتيلا صغيرة من دقيق القمح الكامل","1 كوب جبن قريش (بدون ملح مضاف، قليل الدسم)","1 كوب طماطم كرزية (مقطعة إلى نصفين)","½ حبة خيار متوسطة (مقطعة إلى شرائح رقيقة)","¼ كوب بصل أحمر (مقطع إلى شرائح رقيقة)","¼ كوب فلفل رومي (مقطع إلى شرائح رقيقة)","¼ كوب أعشاب طازجة (مثل الشبت والريحان والبقدونس، مفرومة)","1/16 ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["افرد أرغفة التورتيلا على سطح نظيف.","وزّع الجبن القريش بالتساوي على كل رغيف تورتيلا.","وزّع الطماطم الكرزية وشرائح الخيار والبصل الأحمر والفلفل الرومي فوق الجبن القريش.","انثر الأعشاب الطازجة فوقها.","تبّلها بالملح والفلفل.","اطوِ جوانب التورتيلا ثم لفّها بإحكام لتكوين اللفائف."])}})
R.append({"id":6870016,"translations":{
"es":T("Cazuela de maíz","Disfrute de nuestra cazuela de maíz apta para personas con diabetes, una mezcla rica y cremosa de maíz dulce que da como resultado un plato caliente y contundente, perfecto para reuniones familiares o noches acogedoras en casa.","12","1/4 taza",
["2 latas (15 oz) de maíz en lata (en granos enteros, escurrido)","1 lata (15 oz) de maíz (estilo crema)","1 taza de harina de maíz","1 tomate grande (en cubitos)","1 taza de yogur griego natural sin grasa","1/2 taza de mantequilla sin sal (derretida)","2 cucharadas de miel","2 cucharaditas de polvo de hornear","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","4 tallos de cebollino fresco (picado, para decorar)"],
["Precaliente el horno a 350 grados F. Engrase un molde para hornear de 9x13 pulgadas con aceite en aerosol.","En un tazón grande, combine el maíz en granos enteros, el maíz estilo crema, la harina de maíz, el tomate en cubitos, el yogur griego, la mantequilla derretida, la miel, el polvo de hornear, la sal y la pimienta. Mezcle hasta que todo esté bien integrado.","Vierta la mezcla de maíz en el molde preparado y extiéndala de manera uniforme.","Hornee durante 45 minutos o hasta que la parte superior esté dorada y un palillo insertado en el centro salga limpio.","Retire la cazuela del horno.","Decore con cebollino fresco picado, si lo desea.","Deje enfriar la cazuela unos minutos antes de servir."]),
"ar":T("طاجن الذرة","استمتع بطاجن الذرة المناسب لمرضى السكري، وهو مزيج غني وكريمي من الذرة الحلوة يمنحك طبقًا دافئًا ومشبعًا، مثاليًا للتجمعات العائلية أو الأمسيات الهادئة في المنزل.","12","¼ كوب",
["2 علبة (15 أونصة) ذرة معلبة (حبوب كاملة، مصفاة)","1 علبة (15 أونصة) ذرة (كريمية)","1 كوب دقيق الذرة","1 حبة طماطم كبيرة (مقطعة إلى مكعبات)","1 كوب زبادي يوناني سادة خالي الدسم","½ كوب زبدة غير مملحة (مذابة)","2 ملعقة كبيرة عسل","2 ملعقة صغيرة بيكنج باودر","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","4 سيقان ثوم معمر (كراث الثوم) طازج (مفروم، للتزيين)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). ادهن طبق خبز بقياس 9×13 بوصة ببخاخ الطهي.","في وعاء كبير، اخلط الذرة كاملة الحبوب والذرة الكريمية ودقيق الذرة والطماطم المقطعة والزبادي اليوناني والزبدة المذابة والعسل والبيكنج باودر والملح والفلفل. قلّب حتى يتجانس المزيج جيدًا.","اسكب مزيج الذرة في طبق الخبز المجهّز وافرده بالتساوي.","اخبزه لمدة 45 دقيقة أو حتى يصبح وجهه ذهبي اللون وتخرج عود أسنان مغروسة في الوسط نظيفة.","أخرج الطاجن من الفرن.","زيّنه بالثوم المعمر الطازج المفروم، إن رغبت.","اترك الطاجن يبرد بضع دقائق قبل التقديم."])}})
R.append({"id":6870063,"translations":{
"es":T("Brócoli congelado cocido","Brócoli congelado preparado sin ingredientes adicionales.","4","1/2 taza",
["2 tazas de floretes de brócoli congelado"],["Cocine el brócoli al vapor, en el microondas o al horno según las instrucciones del envase."]),
"ar":T("بروكلي مجمد مطبوخ","بروكلي مجمد محضّر دون أي مكونات إضافية.","4","½ كوب",
["2 كوب زهيرات بروكلي مجمدة"],["اطهُ البروكلي على البخار أو في الميكروويف أو في الفرن وفق إرشادات العبوة."])}})
R.append({"id":6871291,"translations":{
"en":T("Pizza with Greek Salad","You can serve this with homemade tzatziki sauce. Grate 1 small cucumber and 1 garlic clove into 1/2 cup plain fat-free Greek yogurt and mix to prepare it.","4",None,
["1 cup spinach (chopped)","1 tbsp Kalamata olives (pitted, chopped)","1/2 cup red onion (thinly sliced)","4 tsp balsamic vinegar","1 tbsp olive oil","2 whole wheat pitas (not pocket type)","1 nonstick cooking spray","1/2 cup artichoke hearts (drained and rinsed, chopped)","1 cup cooked chicken breast (cut into cubes)","1/3 cup feta cheese (reduced fat)","1 tsp dried oregano"],
["Preheat the oven to 375 degrees F. Coat a baking sheet with cooking spray. Set aside.","Brush each pita with some of the olive oil, using the whole tablespoon.","Drizzle each pita with 2 tsp balsamic vinegar.","Top each pita with 1/4 cup red onion, 1/2 tbsp olives, 1/2 cup spinach, 1/4 cup artichokes, 1/2 cup chicken, and half of the feta cheese.","Sprinkle the top of each pita with dried oregano. Place on the prepared baking sheet.","Bake for 15 minutes. Cut into quarters and serve."]),
"ar":T("بيتزا مع سلطة يونانية","يمكنك تقديمها مع صلصة التزاتزيكي محلية الصنع. اِبشر 1 حبة خيار صغيرة و1 فص ثوم في ½ كوب زبادي يوناني سادة خالي الدسم واخلطها لتحضير الصلصة.","4",None,
["1 كوب سبانخ (مفرومة)","1 ملعقة كبيرة زيتون كالاماتا (منزوع النوى ومفروم)","½ كوب بصل أحمر (مقطع إلى شرائح رقيقة)","4 ملعقة صغيرة خل بلسميك","1 ملعقة كبيرة زيت زيتون","2 خبز بيتا من القمح الكامل (غير مجوّف)","1 بخة من بخاخ الطهي غير اللاصق","½ كوب قلوب خرشوف (مصفاة ومشطوفة، مفرومة)","1 كوب صدر دجاج مطبوخ (مقطع إلى مكعبات)","⅓ كوب جبن فيتا (قليل الدسم)","1 ملعقة صغيرة أوريغانو مجفف"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية). رش صينية خبز ببخاخ الطهي. اتركها جانبًا.","أدهن كل رغيف بيتا بجزء من زيت الزيتون، مستخدمًا الملعقة الكبيرة كاملة.","رشّ على كل رغيف بيتا 2 ملعقة صغيرة من خل البلسميك.","غطِّ كل رغيف بيتا بـ ¼ كوب بصل أحمر، و½ ملعقة كبيرة زيتون، و½ كوب سبانخ، و¼ كوب خرشوف، و½ كوب دجاج، ونصف كمية جبن الفيتا.","انثر الأوريغانو المجفف على وجه كل رغيف بيتا. ضعه على صينية الخبز المجهزة.","اخبزه لمدة 15 دقيقة. قطّعه إلى أرباع وقدّمه."])}})
R.append({"id":6872161,"translations":{"ar":T("خبز مسطح متوسطي بالإسبلت","يصلح هذا الخبز المسطح مقبلاتٍ رائعة أيضًا. جرّب تقطيعه إلى قطع أصغر ليكون طعامًا مميزًا للحفلات.","8","1 شريحة",
["1 بخة، 0.25 جم من بخاخ الطهي غير اللاصق","¾ كوب ماء دافئ","1 ظرف خميرة جافة نشطة","½ ملعقة صغيرة عسل","1 بيضة كبيرة","½ ملعقة صغيرة ملح كوشر","¼ كوب دقيق الإسبلت (مع كمية إضافية للرش)","½ كوب دقيق القمح الكامل","1 حبة فلفل رومي أصفر متوسطة (مقطعة إلى شرائح رقيقة)","1 كوب طماطم عنبية (مقطعة إلى نصفين)","3 كوب جرجير","3 أونصة جبن فيتا (قليل الدسم)","1½ ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة خل بلسميك","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (200° مئوية). رش صينية خبز كبيرة ببخاخ الطهي. اتركها جانبًا.","أضف الخميرة والعسل إلى الماء الدافئ واتركها 5 دقائق. يجب أن تصبح الخميرة رغوية. اخفق البيضة والملح، ثم أضف الدقيقين وحرّك لتكوين كرة عجين. ستكون العجينة لزجة. اتركها جانبًا مغطاة.","قلّب الفلفل الرومي الأصفر والطماطم العنبية والجرجير وجبن الفيتا مع زيت الزيتون وخل البلسميك والفلفل الأسود.","رشّ يديك بمزيد من دقيق الإسبلت وافرد العجينة على صينية الخبز لتشكيل مستطيل بقياس حوالي 9 بوصات × 13 بوصة أو أكبر. يجب أن تكون العجينة رقيقة نسبيًا.","اسكب مزيج الخضار بالتساوي فوق العجينة، مع ترك حوالي ½ بوصة حول الحافة.","اخبزه لمدة 20 دقيقة، ثم قطّعه إلى 8 قطع."])}})
R.append({"id":6876203,"translations":{"ar":T("بارفيه بودينغ القرع مع بسكويت الزنجبيل","هذه الحلوى التي لا تحتاج إلى طهي بديل رائع لفطيرة القرع، وسعراتها 100 سعر حراري فقط! للحصول على حلوى قرع سريعة وصحية ولذيذة، لا تبحث أبعد من ذلك؛ بارفيه البودينغ هذا رائع ويكون جاهزًا في دقائق.","7","1 بارفيه",
["1 عبوة (1 أونصة) من مزيج بودينغ الجبن الفوري (خالٍ من الدسم والسكر)","1 2/3 كوب حليب خالي الدسم","1 كوب قرع معلب نقي","½ ملعقة صغيرة قرفة مطحونة","⅛ ملعقة صغيرة جوزة الطيب المطحونة","1 كوب زبادي يوناني بالفانيليا (خالٍ من الدسم، يُقسم)","7 قطع بسكويت زنجبيل كاملة (مفتتة)"],
["في وعاء خلط متوسط، اخفق مزيج البودينغ والحليب لمدة 2 دقيقة. اتركه 5 دقائق.","أضف القرع والقرفة وجوزة الطيب وقلّب برفق. أضف ½ كوب من الزبادي وقلّب برفق، ثم ضعه في الثلاجة لمدة 10 دقائق.","ضع ½ كوب من مزيج البودينغ في كل كأس بارفيه. غطِّ كل كأس بملعقة كبيرة (1) مكوّمة من الزبادي المتبقي وقطعة بسكويت زنجبيل (1) مفتتة. كرر الخطوات مع الكؤوس الستة المتبقية."])}})
R.append({"id":6876375,"translations":{
"es":T("Puré de camote al estilo mojito","¡La menta y el jugo de limón verde le dan a este puré de camote un toque de mojito! Para una comida completa y balanceada, acompáñelo con una proteína sencilla y llene el resto del plato con una verdura sin almidón.","4","Aproximadamente 1/2 taza",
["2 camotes (batatas) grandes (sin pelar, de aproximadamente 1 1/2 libras)","1 cucharada de aceite de oliva","2 cucharadas de menta fresca (picada)","2 cucharadas de jugo de limón verde","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Ponga los camotes enteros en una olla grande y agregue suficiente agua fría para cubrirlos. Lleve a ebullición a fuego alto. Reduzca el fuego a medio-bajo y cocine a fuego lento hasta que estén tiernos, de 30 a 35 minutos. Escurra los camotes y enjuague con agua fría hasta que pueda manipularlos fácilmente.","Mientras tanto, caliente el aceite en una olla pequeña a fuego alto hasta que esté tibio, aproximadamente 1 minuto. (O caliente el aceite en un recipiente apto para microondas a temperatura alta hasta que esté tibio, aproximadamente 30 segundos). Agregue las hojas de menta y macháquelas con el mango de una cuchara de madera o con un mazo. Reserve.","Pele los camotes y devuélvalos a la olla. Agregue la mezcla de menta, el jugo de limón verde, la sal y la pimienta. Triture los camotes con un machacador de papas hasta obtener un puré suave y cremoso. Pase el puré a un tazón para servir, decore con ramitas de menta y sirva caliente."]),
"ar":T("هريس البطاطا الحلوة بنكهة الموهيتو","النعناع وعصير الليمون الأخضر يمنحان هريس البطاطا الحلوة هذا لمسة من الموهيتو! للحصول على وجبة متكاملة ومتوازنة، قدّمه مع مصدر بروتين بسيط واملأ بقية الطبق بخضار غير نشوية.","4","حوالي ½ كوب",
["2 حبة بطاطا حلوة كبيرة (غير مقشرة، حوالي 1½ رطل)","1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة نعناع طازج (مفروم)","2 ملعقة كبيرة عصير ليمون أخضر","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["ضع حبات البطاطا الحلوة كاملة في قدر كبير وأضف ماءً باردًا يكفي لتغطيتها. دعها تغلي على نار عالية. خفّف النار إلى متوسطة-منخفضة واتركها على نار هادئة حتى تنضج، من 30 إلى 35 دقيقة. صفِّ البطاطا واشطفها بالماء البارد حتى يسهل التعامل معها.","في الأثناء، سخّن الزيت في قدر صغير على نار عالية حتى يصبح دافئًا، حوالي دقيقة واحدة. (أو سخّن الزيت في وعاء صالح للميكروويف على أعلى درجة حتى يصبح دافئًا، حوالي 30 ثانية.) أضف أوراق النعناع واهرسها بمقبض ملعقة خشبية أو بمدقة. اتركها جانبًا.","قشّر البطاطا الحلوة وأعدها إلى القدر. أضف خليط النعناع وعصير الليمون الأخضر والملح والفلفل. اهرس البطاطا بمهراس البطاطس حتى تصبح ناعمة وكريمية. انقل البطاطا إلى وعاء التقديم، وزيّنها بأغصان النعناع، وقدّمها ساخنة."])}})
R.append({"id":6877039,"translations":{
"es":T("Pechuga de pavo asada con hierbas al estilo provenzal","Este plato se ha convertido en la joya de la corona de la cena americana de Acción de Gracias de Amy Riolo. La combinación de hierbas, ajo, especias y jugo de limón da como resultado un pavo sabroso y jugoso que es sencillo de preparar. El pavo debe asarse de 20 a 25 minutos por libra.","10","3 onzas",
["1/4 taza de aceite de oliva extra virgen (dividido)","3 1/2 libras de pechuga de pavo con hueso","1/2 cucharadita de sal","1/8 cucharadita de pimienta negra (recién molida, al gusto)","1 cucharada de hierbas provenzales","1 cucharadita de condimento para aves","1 cabeza de ajo (con la parte superior cortada)","2 limones medianos (cortados por la mitad)","1 ramita de romero fresco","1 ramita de tomillo fresco","1 ramita de salvia fresca"],
["Precaliente el horno a 425° F. Use 1 cucharada de aceite de oliva para engrasar el fondo de una fuente grande para asar.","Seque la pechuga de pavo con una toalla de papel y sazone con sal y pimienta. Coloque la pechuga de pavo con la piel hacia arriba en la fuente. Unte el pavo con el aceite de oliva restante. Espolvoree las hierbas provenzales y el condimento para aves sobre el pavo y frote con las manos sobre la piel. Coloque en la fuente la cabeza de ajo entera, 1 mitad de limón, el romero, el tomillo y la salvia. Exprima el jugo de la otra mitad de limón sobre el pavo.","Ponga el pavo en el horno, agregue una taza de agua al fondo de la fuente y áselo durante 1 hora, sin tapar. Báñelo con sus jugos después de la primera hora de cocción. Si el pavo se ve muy dorado, cúbralo con papel de aluminio. Continúe horneando de 30 a 45 minutos más, o hasta que la temperatura interna de la parte más gruesa de la pechuga marque 180° F en un termómetro para carne. Retire del horno y colóquelo en una tabla de trinchar. Déjelo reposar 10 minutos antes de trincharlo. Retire la piel al trinchar.","Cuele el líquido del fondo de la fuente y páselo a otra olla. Exprima el jugo de las 2 mitades de limón restantes, agréguelo a la olla y revuelva. Lleve a ebullición a fuego alto y cocine durante 10 minutos o hasta que la salsa se reduzca. Pruebe y ajuste el condimento si es necesario. Sirva la salsa en una salsera junto al pavo."]),
"ar":T("صدر ديك رومي محمّص بالأعشاب على الطريقة البروفنسالية","أصبح هذا الطبق جوهرة مائدة عيد الشكر الأمريكي لدى إيمي ريولو. يمنحك مزيج الأعشاب والثوم والتوابل وعصير الليمون ديكًا روميًا لذيذًا وطريًا وسهل التحضير. يجب تحميص الديك الرومي من 20 إلى 25 دقيقة لكل رطل.","10","3 أونصات",
["¼ كوب زيت زيتون بكر ممتاز (يُقسم)","3½ رطل صدر ديك رومي بالعظم","½ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود (مطحون طازجًا، حسب الرغبة)","1 ملعقة كبيرة أعشاب بروفانس","1 ملعقة صغيرة بهارات الدواجن","1 رأس ثوم (مقطوع من الأعلى)","2 حبة ليمون متوسطة (مقطعة إلى نصفين)","1 غصن روزماري طازج","1 غصن زعتر طازج","1 غصن مريمية طازج"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية). استخدم 1 ملعقة كبيرة من زيت الزيتون لدهن قاع صينية تحميص كبيرة.","جفّف صدر الديك الرومي بمنديل ورقي وتبّله بالملح والفلفل. ضع الصدر في الصينية والجلد إلى الأعلى. افرك الديك الرومي بباقي زيت الزيتون بفرشاة. انثر أعشاب بروفانس وبهارات الدواجن على الديك الرومي ودلّكها على الجلد بيديك. ضع رأس الثوم كاملًا ونصف ليمونة (1) والروزماري والزعتر والمريمية في الصينية. اعصر عصير نصف الليمونة الباقي فوق الديك الرومي.","ضع الديك الرومي في الفرن، وأضف كوبًا من الماء إلى قاع الصينية، وحمّصه لمدة ساعة (1) دون تغطية. اسقِ الديك الرومي بعصارته بعد الساعة الأولى من الطهي. إذا بدا الديك الرومي بنيًا جدًا، غطّه بورق الألمنيوم. واصل الخبز لمدة 30-45 دقيقة أخرى أو حتى تصل درجة الحرارة الداخلية لأسمك جزء من صدر الديك الرومي إلى 180° فهرنهايت (80° مئوية) على مقياس حرارة اللحم. أخرجه من الفرن وضعه على لوح التقطيع. اتركه يرتاح 10 دقائق قبل التقطيع. انزع الجلد أثناء التقطيع.","صفِّ السائل من قاع الصينية في قدر آخر. اعصر نصفي الليمون المتبقيين (2) وأضف العصير إلى القدر وحرّك. دعه يغلي على نار عالية واتركه 10 دقائق أو حتى تتكثف الصلصة. تذوّق وعدّل التتبيل إذا لزم الأمر. قدّم الصلصة في إبريق صلصة بجانب الديك الرومي."])}})
save(1,R)
