from h import *
R=[]
R.append({"id":6877159,"translations":{"ar":T("سلطة المعكرونة بالخضار والدجاج","سر إدراج المعكرونة في خطة وجباتك دون الإفراط في الكربوهيدرات هو الحفاظ على صغر حجم الحصة وتقديمها مع الكثير من الخضار وقدر من البروتين. هذا عشاء سريع يمكن للعائلة كلها الاستمتاع به في أي وقت من السنة. جرّبها مع معكرونة مصنوعة من البقوليات مثل معكرونة العدس أو الحمص لزيادة البروتين والألياف.","4","1 كوب",
["1 كوب معكرونة مرفوعة من القمح الكامل غير مطبوخة","½ كوب فلفل رومي أحمر مقطع إلى مكعبات","½ كوب خيار مقطع إلى مكعبات","½ كوب زهيرات بروكلي صغيرة (طازجة أو مجمدة)","1 حبة جزر كبيرة (مقطعة إلى مكعبات)","1 كوب صدر دجاج مطبوخ مقطع إلى مكعبات","¼ كوب مايونيز خفيف","1 ملعقة كبيرة خل النبيذ الأحمر","⅛ ملعقة صغيرة أوريغانو مجفف","⅛ ملعقة صغيرة فلفل أسود مطحون طازجًا"],
["اسلق المعكرونة وفق إرشادات العبوة. صفّها.","في وعاء كبير، اخلط المعكرونة والفلفل الرومي الأحمر والخيار والبروكلي والجزر والدجاج.","في وعاء صغير، اخفق مكونات التتبيلة معًا. اسكب التتبيلة فوق المعكرونة والخضار والدجاج وقلّب جيدًا. قدّمها."])}})
R.append({"id":6878911,"translations":{"ar":T("لقيمات الشوفان بزبدة الفول السوداني والموز","هذه اللقيمات المشبعة الغنية بالألياف خيار رائع كوجبة خفيفة أو فطور سريع. يمكنك أيضًا تجميد لقيمتين في كيس بلاستيكي بحجم الوجبات الخفيفة لتحصل على فطور جاهز تأخذه معك!","24","2 لقيمة",
["1 بيضة كبيرة","1 حبة موز متوسطة (مهروسة)","½ كوب زبدة الفول السوداني (مسخّنة في الميكروويف لمدة 30 ثانية)","1 ملعقة صغيرة مستخلص الفانيليا","2 ملعقة كبيرة بديل سكر بني قليل السعرات","2 كوب شوفان مجروش تقليدي (خالٍ من الغلوتين إذا لزم)","1 ملعقة صغيرة بيكربونات الصودا","½ ملعقة صغيرة ملح","¼ كوب بذور الكتان المطحونة"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). بطّن صينية خبز بورق زبدة.","في وعاء متوسط، اخفق زبدة الفول السوداني والموز والبيضة والفانيليا وبديل السكر البني.","في وعاء صغير، اخلط الشوفان وبيكربونات الصودا والملح. أضف بذور الكتان المطحونة.","أضف مزيج الشوفان إلى مزيج زبدة الفول السوداني وقلّب جيدًا.","اغرف الخليط على شكل كرات بحجم ملعقة كبيرة (1) وضعها على الصينية. اخبزها لمدة 10-12 دقيقة. اتركها تبرد على رف سلكي."])}})
R.append({"id":6881554,"translations":{
"es":T("Albóndigas de pavo con fideos de calabacín","Esta versión de inspiración italiana presenta deliciosas albóndigas de pavo y fideos de calabacín bajos en carbohidratos, para una comida saludable que toda la familia disfrutará.","4","1/4 de la receta",
["1 libra de pavo molido magro (93 % magro)","1/2 taza de pan rallado","1/4 taza de queso parmesano (rallado)","1 huevo grande","2 dientes de ajo (picados)","1 cucharadita de orégano seco","1/2 cucharadita de pimienta negra (dividida)","2 tazas de salsa marinara (sin sal agregada)","4 calabacines medianos (cortados en espiral en forma de fideos)","1/4 taza de aceitunas Kalamata (sin hueso)","1 1/2 cucharadas de aceite de oliva","1 cucharada de perejil fresco (picado)"],
["Precaliente el horno a 400 grados F. Forre dos bandejas para hornear con papel pergamino.","En un tazón grande, combine el pavo molido, el pan rallado, el queso parmesano, el huevo, el ajo picado, el orégano seco y ¼ de cucharadita de pimienta negra. Mezcle hasta que todo esté bien integrado.","Con las manos húmedas, forme albóndigas de aproximadamente 1 pulgada de diámetro con la mezcla y colóquelas en una bandeja. Hornee durante 20 minutos, o hasta que la temperatura interna alcance los 165 grados F.","Mientras se hornean las albóndigas, mezcle los fideos de calabacín con el aceite de oliva y ¼ de cucharadita de pimienta negra, y extiéndalos en la segunda bandeja.","Hornee hasta que estén tiernos, aproximadamente de 10 a 15 minutos.","Caliente la salsa marinara en la estufa y mezcle las albóndigas calientes con la salsa.","Sirva las albóndigas sobre los fideos de calabacín y decore con las aceitunas y el perejil fresco."]),
"ar":T("كرات الديك الرومي مع معكرونة الكوسا","تقدم هذه النسخة المستوحاة من المطبخ الإيطالي كرات ديك رومي لذيذة ومعكرونة كوسا قليلة الكربوهيدرات، لوجبة صحية تستمتع بها العائلة كلها.","4","¼ الوصفة",
["1 رطل ديك رومي مفروم قليل الدهن (93% خالٍ من الدهن)","½ كوب فتات الخبز","¼ كوب جبن البارميزان (مبشور)","1 بيضة كبيرة","2 فص ثوم (مفروم)","1 ملعقة صغيرة أوريغانو مجفف","½ ملعقة صغيرة فلفل أسود (تُقسم)","2 كوب صلصة المارينارا (بدون ملح مضاف)","4 حبات كوسا متوسطة (مقطعة حلزونيًا على شكل شرائح معكرونة)","¼ كوب زيتون كالاماتا (منزوع النوى)","1½ ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة بقدونس طازج (مفروم)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (200° مئوية). بطّن صينيتي خبز بورق زبدة.","في وعاء خلط، اخلط الديك الرومي المفروم وفتات الخبز وجبن البارميزان والبيضة والثوم المفروم والأوريغانو المجفف و¼ ملعقة صغيرة من الفلفل الأسود. قلّب حتى يتجانس المزيج جيدًا.","بيدين مبللتين، شكّل المزيج على هيئة كرات لحم بقطر حوالي 1 بوصة وضعها على الصينية. اخبزها لمدة 20 دقيقة، أو حتى تصل درجة الحرارة الداخلية إلى 165 درجة فهرنهايت (75° مئوية).","أثناء خبز الكرات، قلّب معكرونة الكوسا مع زيت الزيتون و¼ ملعقة صغيرة من الفلفل الأسود وافردها على الصينية الثانية.","اخبزها حتى تلين، حوالي 10-15 دقيقة.","سخّن صلصة المارينارا على الموقد وقلّب الكرات الساخنة في الصلصة.","قدّم الكرات فوق معكرونة الكوسا وزيّنها بالزيتون والبقدونس الطازج."])}})
R.append({"id":6882153,"translations":{
"es":T("Huevos rellenos al curry","Los huevos rellenos al curry son un delicioso aperitivo que aporta un toque de especias y calidez a su mesa. La combinación de curry en polvo, mostaza Dijon y vinagre de manzana crea un relleno sabroso y aromático que seguramente será un éxito en fiestas y reuniones. ¡Disfrute de estos huevos rellenos con un condimento único!","8","2 mitades",
["8 huevos grandes","1/4 taza de mayonesa light","1 cucharadita de curry en polvo","1 cucharadita de mostaza Dijon","1 cucharadita de vinagre de sidra de manzana","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","1/8 cucharadita de pimentón ahumado (para decorar)","1 cucharadita de eneldo fresco (para decorar)"],
["Coloque los huevos en una sola capa en una olla y cúbralos con agua. Deje que el agua hierva, luego reduzca el fuego a bajo, tape y cocine a fuego lento de 10 a 12 minutos.","Pase los huevos cocidos a un baño de agua con hielo para que se enfríen.","Una vez fríos, pele los huevos y córtelos por la mitad a lo largo. Retire las yemas y colóquelas en un tazón.","En el tazón con las yemas, agregue la mayonesa, el curry en polvo, la mostaza Dijon, el vinagre de sidra de manzana, la sal y la pimienta. Triture y mezcle los ingredientes hasta obtener una consistencia suave. Con una cuchara o una manga pastelera, rellene las claras con la mezcla de curry.","Refrigere por lo menos 30 minutos antes de servir. Espolvoree ligeramente con pimentón y, si lo desea, decore con eneldo fresco."]),
"ar":T("بيض محشو بالكاري","البيض المحشو بالكاري مقبلات رائعة تضفي لمسة من التوابل والدفء على مائدتك. يصنع مزيج مسحوق الكاري ومستردة ديجون وخل التفاح حشوة لذيذة وعطرة ستنال بالتأكيد إعجاب الجميع في الحفلات والتجمعات. استمتع بهذا البيض المحشو بتتبيلته الفريدة!","8","2 نصف",
["8 بيضات كبيرة","¼ كوب مايونيز خفيف","1 ملعقة صغيرة مسحوق الكاري","1 ملعقة صغيرة خردل ديجون","1 ملعقة صغيرة خل التفاح","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","⅛ ملعقة صغيرة بابريكا مدخنة (للتزيين)","1 ملعقة صغيرة شبت طازج (للتزيين)"],
["ضع البيض في طبقة واحدة في قدر وغطِّه بالماء. دع الماء يغلي، ثم خفّف النار إلى أقل درجة، وغطِّ القدر، واتركه على نار هادئة لمدة 10–12 دقيقة.","انقل البيض المسلوق إلى حمام ماء مثلج ليبرد.","بعد أن يبرد البيض، قشّره وقطّعه إلى نصفين طوليًا. أخرج الصفار وضعه في وعاء.","أضف إلى وعاء الصفار المايونيز ومسحوق الكاري وخردل ديجون وخل التفاح والملح والفلفل. اهرس المكونات واخلطها معًا حتى تصبح ناعمة. باستخدام ملعقة أو كيس تزيين، املأ بياض البيض المفرغ بحشوة الكاري.","ضعه في الثلاجة لمدة 30 دقيقة على الأقل قبل التقديم. رش عليه البابريكا رشًا خفيفًا وزيّنه بالشبت الطازج إن رغبت."])}})
R.append({"id":6884440,"translations":{
"es":T("Bocadillos cremosos de apio crujiente","Estos refrescantes bocadillos combinan apio crujiente con queso crema sin grasa de textura suave y un toque de semillas de calabaza y de girasol, para una satisfactoria mezcla de crujiente y cremoso. Se preparan en minutos y son un refrigerio ligero y energizante de una sola porción.","1","4 palitos de apio rellenos",
["4 tallos de apio","4 cucharadas de queso crema sin grasa","2 cucharadas de semillas de calabaza (sin sal)","2 cucharadas de semillas de girasol (sin sal)"],
["Lave y recorte 4 tallos de apio.","Unte 4 cucharadas de queso crema sin grasa de manera uniforme en el canal de los tallos de apio.","Espolvoree 1/2 cucharada de semillas de calabaza y 1/2 cucharada de semillas de girasol sobre el queso crema de cada tallo de apio.","Sirva de inmediato para disfrutar el mejor crujido."]),
"ar":T("لقيمات الكرفس المقرمشة بالجبن الكريمي","تجمع لقيمات الوجبات الخفيفة المنعشة هذه بين الكرفس المقرمش والجبن الكريمي الناعم الخالي من الدسم مع رشة من بذور القرع وبذور عباد الشمس، لتحصل على مزيج مشبع من القرمشة والكريمية. تُحضَّر في دقائق وهي وجبة خفيفة منعشة ومنشّطة بحصة فردية.","1","4 أعواد كرفس محشوة",
["4 أعواد كرفس","4 ملعقة كبيرة جبن كريمي خالٍ من الدسم","2 ملعقة كبيرة بذور القرع (غير مملحة)","2 ملعقة كبيرة بذور عباد الشمس (غير مملحة)"],
["اغسل 4 أعواد كرفس وقصّ أطرافها.","افرد 4 ملاعق كبيرة من الجبن الكريمي الخالي من الدسم بالتساوي في تجويف أعواد الكرفس.","انثر ½ ملعقة كبيرة من بذور القرع و½ ملعقة كبيرة من بذور عباد الشمس فوق الجبن الكريمي على كل عود كرفس.","قدّمها فورًا للحصول على أفضل قرمشة."])}})
R.append({"id":6885965,"translations":{"ar":T("يخنة الباذنجان والحمص","يستمد هذا الطبق النباتي الرئيسي اللذيذ نكهته المميزة من مزيج الثوم والبصل والتوابل، وهي تساعدك على الحصول على أقصى نكهة دون إضافة الكثير من الملح.","4","1½ كوب",
["4 ملعقة صغيرة زيت زيتون بكر ممتاز (يُقسم)","2 حبة بصل أصفر متوسطة (1 مقطعة إلى مكعبات و1 مقطعة إلى شرائح)","3 فص ثوم (مفروم)","1 رطل باذنجان (مقطع إلى مكعبات)","2 كوب حمص (بدون ملح مضاف)","1 ملعقة صغيرة كمون","1 ملعقة صغيرة قرفة مطحونة","1 ملعقة صغيرة كزبرة مطحونة","28 أونصة طماطم معلبة (بدون ملح مضاف، مقطعة إلى مكعبات أو مفرومة)","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","¼ كوب كزبرة خضراء (مفرومة طازجة)"],
["سخّن 2 ملعقة صغيرة من زيت الزيتون في قدر كبير على نار متوسطة.","أضف البصل المقطع إلى مكعبات والثوم، واطهه حتى يلين البصل.","أضف الباذنجان والحمص والكمون والقرفة والكزبرة المطحونة والطماطم والملح والفلفل وحرّك. ارفع النار إلى عالية ودعه يغلي.","خفّف النار إلى منخفضة وغطِّ القدر. اطهِ اليخنة لمدة 45 دقيقة إلى ساعة (1) أو حتى يصبح الباذنجان طريًا جدًا.","في الأثناء، سخّن 2 ملعقة صغيرة المتبقية من زيت الزيتون وأضف شرائح البصل. قلّبها حتى يصبح لونها ذهبيًا، ثم ارفعها عن النار.","عند نضج اليخنة، ضعها في أطباق التقديم وزيّنها بالبصل المقلي والكزبرة الخضراء."])}})
R.append({"id":6886065,"translations":{
"es":T("Wraps de shawarma de pollo con hojas de berza","Estos wraps de shawarma de pollo con hojas de berza están llenos de especias intensas y verduras frescas, envueltos en resistentes hojas de berza bajas en carbohidratos en lugar del pan plano tradicional. La salsa de yogur y tahini aporta una cremosidad deliciosa sin exceso de grasa. Con alto contenido de proteínas y fibra y sin granos refinados, son un wrap sabroso y apto para personas con diabetes.","4","2 wraps",
["1 libra de muslos de pollo deshuesados y sin piel","2 cucharadas de aceite de oliva","3 dientes de ajo (picados, porción dividida)","1 cucharadita de comino molido","1 cucharadita de pimentón ahumado","1/2 cucharadita de cilantro molido","1/2 cucharadita de cúrcuma","1/4 cucharadita de canela molida","1/4 cucharadita de pimienta de cayena (opcional)","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","3 cucharadas de jugo de limón (de 1 1/2 limones medianos, porción dividida)","8 hojas de berza (hojas grandes, sin los tallos)","1/2 taza de yogur griego natural sin grasa","1 cucharada de tahini","1 taza de pepino (cortado en bastoncitos finos)","1 taza de tomates cherry (cortados por la mitad)","1/4 de cebolla morada pequeña"],
["En un tazón grande, combine el aceite de oliva, el ajo, el comino, el pimentón, el cilantro, la cúrcuma, la canela, la cayena (si la usa), la sal, la pimienta y 1 cucharada de jugo de limón. Agregue los muslos de pollo y cúbralos de manera uniforme. Deje marinar por lo menos 30 minutos, o hasta toda la noche en el refrigerador.","Caliente a fuego medio una plancha acanalada o una sartén. Cocine los muslos de pollo de 5 a 7 minutos por lado, o hasta que estén bien cocidos. Déjelos reposar 5 minutos y luego córtelos en rebanadas finas.","Lleve a ebullición una olla grande con agua. Una a una, escalde cada hoja de berza de 30 a 45 segundos, hasta que esté de color verde brillante y flexible. Páselas a un baño de agua con hielo y luego séquelas con toques.","En un tazón pequeño, ponga el yogur, el tahini, 1 cucharada de jugo de limón y 2 dientes de ajo picados. Bata hasta obtener una mezcla suave.","Ahora está listo para armar los wraps. Extienda una hoja de berza. Unte con una cucharada de la salsa de yogur y tahini (1/2 taza de yogur griego natural sin grasa; 1 cucharada de tahini; 1 cucharada de jugo de limón; y 1 diente de ajo pequeño, picado). Cubra con el pollo en rebanadas, el pepino, los tomates cherry y la cebolla morada. Doble los lados y enrolle como un burrito.","Si lo desea, corte cada wrap por la mitad y sirva de inmediato. Las sobras se pueden envolver bien y guardar en el refrigerador hasta por 2 días."]),
"ar":T("لفائف شاورما الدجاج بأوراق الكرنب الأخضر","تزخر لفائف شاورما الدجاج هذه بالتوابل القوية والخضار الطازجة، وهي ملفوفة في أوراق كرنب أخضر متينة وقليلة الكربوهيدرات بدلًا من الخبز المسطح التقليدي. وتضيف صلصة الزبادي والطحينة غنى كريميًا دون دهون زائدة. وبما أنها غنية بالبروتين والألياف وخالية من الحبوب المكررة، فهي لفائف لذيذة ومناسبة لمرضى السكري.","4","2 لفة",
["1 رطل أفخاذ دجاج منزوعة العظم والجلد","2 ملعقة كبيرة زيت زيتون","3 فص ثوم (مفروم، يُقسم)","1 ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة كزبرة مطحونة","½ ملعقة صغيرة كركم","¼ ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة فلفل كايين (اختياري)","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","3 ملعقة كبيرة عصير ليمون (من 1½ حبة ليمون متوسطة، يُقسم)","8 أوراق كرنب أخضر (أوراق كبيرة، مقطوعة السيقان)","½ كوب زبادي يوناني سادة خالي الدسم","1 ملعقة كبيرة طحينة","1 كوب خيار (مقطع إلى أعواد رفيعة)","1 كوب طماطم كرزية (مقطعة إلى نصفين)","¼ حبة بصل أحمر صغيرة"],
["في وعاء كبير، اخلط زيت الزيتون والثوم والكمون والبابريكا والكزبرة والكركم والقرفة وفلفل الكايين (إن استخدمته) والملح والفلفل و1 ملعقة كبيرة من عصير الليمون. أضف أفخاذ الدجاج وغلّفها بالتساوي. اتركها تتتبل لمدة 30 دقيقة على الأقل، أو حتى الليلة كاملة في الثلاجة.","سخّن مقلاة مضلعة أو مقلاة عادية على نار متوسطة. اطهِ أفخاذ الدجاج من 5 إلى 7 دقائق لكل جانب، أو حتى تنضج تمامًا. اتركها ترتاح 5 دقائق، ثم قطّعها إلى شرائح رقيقة.","اغلِ قدرًا كبيرًا من الماء. اسلق كل ورقة كرنب على حدة لمدة 30 إلى 45 ثانية حتى تصبح خضراء زاهية ومرنة. انقلها إلى حمام ماء مثلج، ثم جففها بالتربيت.","في وعاء صغير، ضع الزبادي والطحينة و1 ملعقة كبيرة من عصير الليمون و2 فص ثوم مفروم. اخفق حتى يصبح الخليط ناعمًا.","الآن أنت جاهز لتجهيز اللفائف. افرد ورقة كرنب على سطح مستوٍ. ضع عليها ملعقة من صلصة الزبادي والطحينة (½ كوب زبادي يوناني سادة خالي الدسم؛ 1 ملعقة كبيرة طحينة؛ 1 ملعقة كبيرة عصير ليمون؛ و1 فص ثوم صغير مفروم). غطِّها بشرائح الدجاج والخيار والطماطم الكرزية والبصل الأحمر. اطوِ الجانبين ولفّها مثل البوريتو.","قطّع كل لفة إلى نصفين إن رغبت وقدّمها فورًا. يمكن لف المتبقي بإحكام وحفظه في الثلاجة لمدة تصل إلى يومين."])}})
R.append({"id":6886220,"translations":{"ar":T("سلطة الأطعمة الخارقة","هذه السلطة ليست مغذية جدًا فحسب، بل مليئة بالنكهة أيضًا. عزّز النكهة أكثر بإضافة 4 ملاعق صغيرة من التوت البري المجفف، أو ¼ كوب من بذور الرمان، أو حبة برتقال مقطعة إلى مكعبات. أو اختر الجرجير الصغير ليكون الورق الأخضر. قدّمها مع الدجاج المشوي أو لحم الخنزير المشوي لوجبة كاملة.","6","1½ كوب",
["½ كوب كينوا","6 أونصات إدامامي طازج مقشر (1 كوب)","2 ملعقة كبيرة زيت زيتون بكر ممتاز","1 ملعقة كبيرة عصير ليمون (طازج)","1 ملعقة كبيرة عصير برتقال (يفضل الطازج)","¼ حبة أفوكادو","2 ملعقة كبيرة كزبرة خضراء أو بقدونس طازج (مفروم خشنًا)","½ ملعقة صغيرة ملح كوشر","1 فص ثوم (مقشر ومقطوع إلى نصفين)","1 رأس خس (حوالي 6 أونصات، مفروم أو ممزق عند الحاجة)","½ حبة فلفل رومي برتقالي متوسطة (منزوعة البذور ومقطعة إلى مكعبات)","2 ملعقة كبيرة بذور عباد الشمس غير مملحة، أو استخدم البيكان أو الفستق"],
["اشطف الكينوا واطهها في 1 كوب ماء لمدة 10 دقائق تقريبًا أو حتى يُمتص الماء بالكامل. فكّكها بالشوكة وارفعها عن النار.","في الأثناء، اسلق الإدامامي لمدة 5 دقائق في حوالي 4 أكواب من الماء المغلي.","في محضرة طعام صغيرة أو خلاط، اهرس الزيت وعصيري الليمون والبرتقال والأفوكادو والكزبرة الخضراء والملح والثوم حتى يصبح الخليط ناعمًا.","في وعاء سلطة كبير، اخلط الخس والفلفل الرومي والكينوا والإدامامي وبذور عباد الشمس. اسكب التتبيلة فوق الجميع وقلّب برفق. قدّمها فورًا.","للتحضير المسبق أو تفويض المهام: اطهُ الكينوا والإدامامي، واعصر البرتقال، وافرم الكزبرة الخضراء، وقشّر الثوم، وحضّر التتبيلة، وقطّع الفلفل الرومي إلى مكعبات."])}})
R.append({"id":6886675,"translations":{
"es":T("Filetes de repollo asados","El repollo es una verdura versátil y económica. En esta receta, una cabeza entera de repollo se corta en gruesos \"filetes\" y se asa para obtener un acompañamiento sustancioso o un plato principal vegetariano. También quedarían excelentes cocinados a la parrilla. Puede preparar una salsa sencilla de yogur griego y eneldo para acompañar los filetes.","6","1 filete de repollo",
["1 cabeza de repollo verde","2 cucharadas de aceite de oliva","1/2 cucharadita de pimienta negra","1 cucharada de mezcla de condimentos multiusos sin sal, como Ms. Dash","1 cucharada de eneldo fresco (picado)"],
["Precaliente el horno a 350° F. Corte la cabeza de repollo en seis rodajas de 1 pulgada de grosor.","Coloque las rodajas de repollo en una bandeja para hornear y rocíe con el aceite de oliva. Espolvoree la mezcla de condimentos y el eneldo sobre el repollo. Cubra con papel de aluminio.","Hornee durante 45 minutos. Retire el papel de aluminio y deje que los filetes de repollo se doren en el horno 15 minutos más."]),
"ar":T("شرائح الملفوف المحمّصة (ستيك الملفوف)","الملفوف خضار متعدد الاستخدامات واقتصادي. في هذه الوصفة، يُقطَّع رأس ملفوف كامل إلى شرائح سميكة تشبه \"الستيك\" ثم تُحمَّص لتكون طبقًا جانبيًا مشبعًا أو طبقًا رئيسيًا نباتيًا. وستكون رائعة أيضًا إذا طُهيت على الشواية. يمكنك تحضير صلصة بسيطة من الزبادي اليوناني والشبت لتقديمها فوق الشرائح.","6","1 شريحة ملفوف",
["1 رأس ملفوف أخضر","2 ملعقة كبيرة زيت زيتون","½ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة خلطة توابل متعددة الاستخدامات خالية من الملح، مثل Ms. Dash","1 ملعقة كبيرة شبت طازج (مفروم)"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). قطّع رأس الملفوف إلى ست شرائح بسُمك 1 بوصة.","رتّب شرائح الملفوف على صينية خبز ورشّ عليها زيت الزيتون. انثر خلطة التوابل والشبت فوق الملفوف. غطِّها بورق الألمنيوم.","اخبزها لمدة 45 دقيقة. انزع ورق الألمنيوم واترك شرائح الملفوف تحمرّ في الفرن 15 دقيقة أخرى."])}})
R.append({"id":6886722,"translations":{"ar":T("صدور الدجاج المحشوة بالبيستو مع صلصة البروسكيتا","هذه الوصفة المحشوة قليلة الكربوهيدرات هي محور الوجبة المثالي لطريقة طبق مرضى السكري. وعند تقديمها مع حصة صغيرة من معكرونة الحبوب الكاملة أو الكينوا وسلطة جانبية، يصبح هذا الطبق الجذاب مصممًا لإبهار الضيوف. نصيحة الشيف: تطلب منك هذه الوصفة فتح صدر الدجاج على شكل فراشة. إذا لم تكن معتادًا على هذه التقنية فلا تقلق! إنها طريقة بسيطة تسهّل حشو الدجاج أو طهي الصدر بسرعة دون أن يجف.","6","4 أونصات دجاج",
["1 بخة، 0.25 جم من بخاخ الطهي غير اللاصق","3 حبات طماطم روما (برقوق) متوسطة (منزوعة البذور ومقطعة إلى مكعبات)","½ حبة بصل أحمر صغيرة (مقطعة إلى مكعبات صغيرة)","1 ملعقة كبيرة أوريغانو طازج (مفروم)","1 ملعقة كبيرة خل النبيذ الأحمر","1 ملعقة كبيرة زيت زيتون","2¼ رطل صدور دجاج منزوعة العظم والجلد","½ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","¼ كوب ريحان طازج (مفروم)","¼ كوب جبن البارميزان (مبشور طازجًا)"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية). ادهن طبق خبز ببخاخ الطهي. اتركه جانبًا.","في وعاء صغير، قلّب الطماطم والبصل الأحمر والأوريغانو وخل النبيذ الأحمر وزيت الزيتون.","افتح كل صدر دجاج على شكل فراشة، ثم افتحه مثل الكتاب. تبّل جانبي كل صدور الدجاج بالملح والفلفل.","قلّب الريحان وجبن البارميزان في وعاء صغير ثم وزّع الخليط بالتساوي على كل صدر دجاج مفتوح. اطوِ صدر الدجاج إلى النصف مجددًا وضعه في طبق الخبز.","اسكب خليط الطماطم فوق صدور الدجاج واخبزها لمدة 35-45 دقيقة (حسب حجم صدور الدجاج) أو حتى تصل درجة الحرارة الداخلية إلى 165 درجة فهرنهايت (75° مئوية)."])}})
R.append({"id":6887150,"translations":{
"es":T("Lubina a la provenzal","La lubina es un pescado blanco firme pero delicado que se encuentra en el Mediterráneo. Se suele cocinar en una salsa de tomate y verduras. Sírvala con papas asadas y una ensalada de acompañamiento.","8","4 oz de pescado + 2 cucharadas de salsa",
["2 libras de lubina","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra","1 cucharada de aceite de oliva","1 cebolla mediana (picada)","1 pimiento rojo mediano (en rodajas finas)","2 dientes de ajo (en rodajas finas)","1 lata (15 onzas) de tomates en cubitos","1 cucharada de pasta de tomate","1/4 cucharadita de hojuelas de pimiento rojo triturado","1/4 taza de aceitunas negras","2 cucharaditas de alcaparras","1/2 taza de albahaca fresca (en tiras)"],
["Espolvoree los filetes con sal y pimienta. En una sartén antiadherente grande, caliente el aceite de oliva a fuego medio-alto. Agregue los filetes y dore cada lado durante unos 4 minutos, o hasta que estén bien cocidos. Retire el pescado de la sartén y colóquelo en un plato. Cubra sin apretar para mantenerlo caliente.","Agregue la cebolla y el pimiento rojo a la sartén y sofría durante 5 minutos, hasta que se ablanden. Agregue el ajo y sofría durante 1 minuto. Agregue los tomates sin escurrir, la pasta de tomate y las hojuelas de pimiento rojo y deje que hierva. Baje el fuego y cocine a fuego lento de 5 a 8 minutos, hasta que la salsa espese. Agregue las aceitunas y las alcaparras y cocine durante 1 minuto.","Sirva la lubina con la salsa y termine con un poco de albahaca por encima."]),
"ar":T("سمك القاروص على الطريقة البروفنسالية","القاروص سمك أبيض متماسك لكنه رقيق، يوجد في البحر الأبيض المتوسط. ويُطهى عادةً في صلصة الطماطم والخضار. قدّمه مع البطاطس المحمّصة وسلطة جانبية.","8","4 أونصات سمك + 2 ملعقة كبيرة صلصة",
["2 رطل سمك قاروص","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مفرومة)","1 حبة فلفل رومي أحمر متوسطة (مقطعة إلى شرائح رقيقة)","2 فص ثوم (مقطعة إلى شرائح رقيقة)","1 علبة (15 أونصة) طماطم مقطعة إلى مكعبات","1 ملعقة كبيرة معجون الطماطم","¼ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","¼ كوب زيتون أسود","2 ملعقة صغيرة كبر","½ كوب ريحان طازج (مقطع إلى شرائح)"],
["رشّ الفيليه بالملح والفلفل. في مقلاة كبيرة غير لاصقة، سخّن زيت الزيتون على نار متوسطة إلى عالية. أضف الفيليه واشوِ كل جانب لمدة 4 دقائق تقريبًا، أو حتى ينضج تمامًا. أخرج السمك من المقلاة وضعه على طبق. غطِّه بشكل فضفاض ليبقى دافئًا.","أضف البصل والفلفل الأحمر إلى المقلاة وقلّبهما لمدة 5 دقائق حتى يلينا. أضف الثوم وقلّبه لمدة دقيقة واحدة (1). أضف الطماطم بسائلها ومعجون الطماطم ورقائق الفلفل الأحمر واتركها حتى تغلي. خفّف النار واتركها على نار هادئة من 5 إلى 8 دقائق، حتى تتكثف الصلصة. أضف الزيتون والكبر واطهه لمدة دقيقة واحدة (1).","قدّم السمك مع الصلصة، وانثر الريحان فوقه في النهاية."])}})
R.append({"id":6887659,"translations":{
"es":T("Dip de pimientos asados y frijoles blancos","Este dip de pimientos asados y frijoles blancos es un aperitivo sabroso y cremoso que combina el sabor ahumado de los pimientos asados con la suavidad de los frijoles blancos. Es un excelente complemento para su mesa de aperitivos o un sabroso dip para acompañar diversos bocadillos.","6","1/3 taza",
["1 lata (15 oz) de frijoles cannellini (escurridos y enjuagados)","1 frasco (8 oz) de pimientos rojos asados (picados, reservando el líquido)","2 cucharadas de aceite de oliva","2 dientes de ajo (picados)","1 cucharada de jugo de limón","1 cucharadita de comino molido","1/2 cucharadita de pimentón ahumado","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra","1 cucharada de agua (según sea necesario)"],
["En un procesador de alimentos, combine los frijoles blancos, los pimientos rojos asados y picados, el aceite de oliva, el ajo picado, el jugo de limón fresco, el comino molido, el pimentón ahumado, la sal y la pimienta.","Pulse la mezcla hasta que empiece a deshacerse. Con el procesador en marcha, agregue poco a poco el jugo de los pimientos rojos asados hasta obtener una consistencia suave y cremosa. Es posible que deba detenerse y raspar los lados del procesador un par de veces."]),
"ar":T("غموس الفلفل المشوي والفاصوليا البيضاء","غموس الفلفل المشوي والفاصوليا البيضاء مقبلات لذيذة وكريمية تجمع بين نكهة الفلفل المشوي المدخنة ونعومة الفاصوليا البيضاء. وهو إضافة رائعة لمائدة المقبلات أو غموس لذيذ لمختلف الوجبات الخفيفة.","6","⅓ كوب",
["1 علبة (15 أونصة) فاصوليا كانيليني (مصفاة ومشطوفة)","1 برطمان (8 أونصات) فلفل أحمر مشوي (مفروم، مع الاحتفاظ بسائله)","2 ملعقة كبيرة زيت زيتون","2 فص ثوم (مفروم)","1 ملعقة كبيرة عصير ليمون","1 ملعقة صغيرة كمون مطحون","½ ملعقة صغيرة بابريكا مدخنة","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة ماء (حسب الحاجة)"],
["في محضرة الطعام، اخلط الفاصوليا البيضاء والفلفل الأحمر المشوي المفروم وزيت الزيتون والثوم المفروم وعصير الليمون الطازج والكمون المطحون والبابريكا المدخنة والملح والفلفل.","اخلط بنبضات متقطعة حتى يبدأ المزيج في التفتت. وأثناء تشغيل المحضرة، أضف عصير الفلفل الأحمر المشوي تدريجيًا حتى تحصل على قوام ناعم وكريمي. قد تحتاج إلى إيقاف المحضرة وكشط الجوانب مرتين."])}})
save(2,R)
