from h import *
R=[]
R.append({"id":6897570,"translations":{
"es":T("Cacahuates (maní)","Información nutricional de los cacahuates (maní)","1","1 onza",["1 onza de cacahuates (maní)"],[]),
"ar":T("الفول السوداني","المعلومات الغذائية للفول السوداني","1","1 أونصة",["1 أونصة فول سوداني"],[])}})
R.append({"id":6900701,"translations":{"ar":T("شوربة الدجاج والمعكرونة والسبانخ","دفّئ غداءك أو عشاءك بهذه الشوربة اللذيذة. تحتوي على الحبوب الكاملة والبروتين قليل الدهن وبعض الخضار أيضًا.","4","1¼ كوب شوربة + 2 ملعقة صغيرة جبن",
["14 أونصة، 1 علبة مرق دجاج قليل الصوديوم","14.5 أونصة، 1 علبة طماطم معلبة مقطعة إلى مكعبات","2 أونصة معكرونة حبوب كاملة أو متعددة الحبوب (مثل الروتيني)","2 كوب صدر دجاج مطبوخ مقطع إلى مكعبات","1 كوب سبانخ صغيرة مكبوسة","¼ كوب ريحان طازج مفروم","1 ملعقة كبيرة زيت زيتون بكر ممتاز","¼ ملعقة صغيرة ملح","2 ملعقة كبيرة جبن بارميزان مبشور"],
["في قدر متوسط، اخلط المرق والطماطم مع سائلها واتركها حتى تغلي على نار عالية. أضف المعكرونة وحرّك، ودعها تغلي مجددًا، ثم خفّف النار وغطِّ القدر واتركها على نار هادئة 6 دقائق أو حتى تنضج المعكرونة بالكاد.","ارفع القدر عن النار وأضف باقي المكونات، باستثناء الجبن، وحرّك. اتركها مغطاة 5 دقائق لتتشرب النكهات وتسخن جيدًا. قدّمها مزيّنة بالجبن."])}})
R.append({"id":6901477,"translations":{
"es":T("Barras de dátiles de California y nueces","Estas barras son perfectas para un desayuno o refrigerio para llevar. Repletas de ingredientes ricos en nutrientes como los dátiles de California, la avena y las semillas de chía, seguramente gustarán a todos. Y lo mejor es que las barras se pueden envolver individualmente, apilar en un recipiente hermético y guardar en el congelador hasta por seis meses. Solo saque cada barra y deje que se descongele a temperatura ambiente antes de comerla.","16","1 barra",
["1 taza de dátiles de California (sin hueso y picados)","1 1/4 tazas de avena en hojuelas de cocción rápida","3 cucharadas de harina de trigo integral (O harina de trigo sarraceno si prefiere sin gluten)","2 cucharadas de germen de trigo","2 cucharadas de semillas de linaza molidas","1 cucharada de semillas de chía","1/2 taza de nueces pecanas (picadas)","1 cucharadita de sal kosher","1/2 cucharadita de canela molida","1/4 taza de crema de maní (cremosa)","1/4 taza de aceite neutro (como aceite vegetal o de aguacate)","1/4 taza de jarabe de arce","1 cucharadita de ralladura de naranja","1/4 cucharadita de extracto de vainilla"],
["Precaliente el horno a 350° F y forre un molde cuadrado de 8x8 pulgadas con papel pergamino.","En un tazón, agregue los dátiles, la avena, la harina, el germen de trigo, la linaza, la chía, las nueces pecanas, la sal y la canela y mezcle bien. Asegúrese de separar los dátiles y distribuirlos por toda la mezcla.","En una olla pequeña a fuego bajo, agregue la crema de maní, el aceite y el jarabe de arce. Bata hasta que estén bien integrados y retire del fuego. Incorpore batiendo la ralladura y la vainilla.","Vierta los ingredientes húmedos sobre los secos y revuelva hasta que todo esté cubierto de manera uniforme. Siga separando los dátiles y mezclándolos por toda la preparación.","Extienda la mezcla de manera uniforme en el molde, asegurándose de presionarla firmemente contra los lados y las esquinas.","Hornee durante 30 minutos, hasta que los bordes estén dorados.","Coloque el molde sobre una rejilla y deje enfriar por completo antes de sacar la mezcla y cortarla. Para acelerar el enfriamiento, puede colocar el molde en el refrigerador.","Saque las barras del molde con ayuda del papel pergamino. Colóquelas sobre una tabla de cortar y córtelas en 16 barras."]),
"ar":T("ألواح التمر الكاليفورني والمكسرات","هذه الألواح مثالية للإفطار أو الوجبة الخفيفة السريعة. وهي مليئة بالمكونات الغنية بالعناصر الغذائية مثل التمر الكاليفورني والشوفان وبذور الشيا، وستنال بالتأكيد إعجاب الجميع. والأفضل من ذلك أنه يمكن تغليف الألواح بشكل فردي وتكديسها في وعاء محكم الإغلاق ووضعها في الفريزر لمدة تصل إلى ستة أشهر. ما عليك سوى إخراج كل لوح وتركه يذوب في درجة حرارة الغرفة قبل تناوله.","16","1 لوح",
["1 كوب تمر كاليفورني (منزوع النوى ومفروم)","1¼ كوب شوفان مجروش سريع الطهي","3 ملعقة كبيرة دقيق القمح الكامل (أو دقيق الحنطة السوداء إذا فضّلت خلوه من الغلوتين)","2 ملعقة كبيرة جنين القمح","2 ملعقة كبيرة بذور الكتان المطحونة","1 ملعقة كبيرة بذور الشيا","½ كوب جوز البيكان (مفروم)","1 ملعقة صغيرة ملح كوشر","½ ملعقة صغيرة قرفة مطحونة","¼ كوب زبدة فول سوداني (كريمية)","¼ كوب زيت محايد (مثل الزيت النباتي أو زيت الأفوكادو)","¼ كوب شراب القيقب","1 ملعقة صغيرة قشر برتقال (مبشور)","¼ ملعقة صغيرة مستخلص الفانيليا"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية) وبطّن قالبًا مربعًا بقياس 8×8 بوصة بورق زبدة.","في وعاء، ضع التمر والشوفان والدقيق وجنين القمح والكتان والشيا والبيكان والملح والقرفة واخلطها جيدًا. احرص على تفتيت التمر وتوزيعه في كل المزيج.","في قدر صغير على نار هادئة، ضع زبدة الفول السوداني والزيت وشراب القيقب. اخفقها حتى تتجانس جيدًا ثم ارفعها عن النار. أضف القشر المبشور والفانيليا واخفق.","اسكب المكونات السائلة فوق المكونات الجافة وحرّك حتى تتغطى كل المكونات بالتساوي. واصل تفتيت التمر وتوزيعه في كل المزيج.","افرد المزيج في القالب بالتساوي، مع الحرص على ضغطه بقوة على الجوانب والزوايا.","اخبزه لمدة 30 دقيقة حتى تصبح الحواف ذهبية اللون.","ضع القالب على رف التبريد واتركه يبرد تمامًا قبل إخراج المزيج وتقطيعه. ولتسريع التبريد، يمكن وضع القالب في الثلاجة.","أخرج الألواح من القالب باستخدام ورق الزبدة. ضعها على لوح التقطيع وقطّعها إلى 16 لوحًا."])}})
R.append({"id":6904987,"translations":{
"es":T("Tortilla masala con verduras variadas","Esta receta es del libro Indian Cuisine Diabetes Cookbook, de May Abraham Fridel.","2","1/2 tortilla",
["2 cucharaditas de aceite de girasol","1 cebolla morada mediana (finamente picada)","1 chile verde fresco entero (finamente picado)","1 diente de ajo (finamente picado)","1/4 cucharadita de cúrcuma (molida)","1 cucharadita de comino molido","1 tomate mediano (finamente picado)","2 huevos grandes (batidos)","1/4 cucharadita de sal","1 cucharada de cilantro fresco (picado)"],
["Caliente el aceite en una sartén de hierro fundido a fuego medio-alto. Agregue la cebolla morada, el chile, el ajo y la cúrcuma y saltee hasta que se ablanden.","Reduzca el fuego a medio y agregue el comino y el tomate. Saltee durante 2 minutos, revolviendo de vez en cuando.","Agregue los huevos batidos, moviendo la sartén en círculos para ayudar a que los huevos cuajen en el fondo. Cocine durante unos 2-3 minutos.","Cuando los huevos estén bien cocidos, doble la tortilla y espolvoree con la sal y el cilantro fresco. Sirva caliente."]),
"ar":T("أومليت ماسالا بالخضار المشكلة","هذه الوصفة من كتاب Indian Cuisine Diabetes Cookbook، تأليف ماي أبراهام فريدل.","2","½ أومليت",
["2 ملعقة صغيرة زيت عباد الشمس","1 حبة بصل أحمر متوسطة (مفرومة ناعمًا)","1 حبة فلفل أخضر حار طازجة كاملة (مفرومة ناعمًا)","1 فص ثوم (مفروم ناعمًا)","¼ ملعقة صغيرة كركم (مطحون)","1 ملعقة صغيرة كمون مطحون","1 حبة طماطم متوسطة (مفرومة ناعمًا)","2 بيضة كبيرة (مخفوقة)","¼ ملعقة صغيرة ملح","1 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة)"],
["سخّن الزيت في مقلاة من الحديد الزهر على نار متوسطة إلى عالية. أضف البصل الأحمر والفلفل الحار والثوم والكركم وقلّبها حتى تلين.","خفّف النار إلى متوسطة وأضف الكمون والطماطم. قلّبها لمدة دقيقتين (2) مع التحريك من وقت لآخر.","أضف البيض المخفوق مع تحريك المقلاة بحركة دائرية لمساعدة البيض على التماسك من الأسفل. اطهِه لمدة 2-3 دقائق تقريبًا.","عندما ينضج البيض تمامًا، اطوِ الأومليت ورشّ عليه الملح والكزبرة الخضراء الطازجة. قدّمه ساخنًا."])}})
R.append({"id":6905037,"translations":{
"es":T("Tiras de pollo al horno con salsa BBQ","Hornear las tiras de pollo es una opción saludable que sigue estando llena de sabor. Esta versión BBQ agrega un toque fresco y picante que toda la familia disfrutará.","4","3 tiras de pollo",
["1 taza de salsa de tomate (sin sal agregada)","2 cucharadas de vinagre de sidra de manzana","1 cucharada de mostaza Dijon","1 cucharada de miel","1 cucharadita de pimentón ahumado","1/2 cucharadita de ajo en polvo","1/2 cucharadita de cebolla en polvo","1/2 cucharadita de sal kosher","1/4 cucharadita de pimienta negra","1 1/2 libras de tiras de pechuga de pollo (sin empanizar)"],
["Precaliente el horno a 400 grados F. Forre una bandeja para hornear con papel pergamino.","En un tazón, bata la salsa de tomate, el vinagre de sidra de manzana, la mostaza Dijon, la miel, el pimentón ahumado, el ajo en polvo, la cebolla en polvo, la sal kosher y la pimienta negra.","Reserve la mitad de la salsa BBQ para usarla después.","Coloque las tiras de pollo en una bolsa de plástico con cierre hermético o en un recipiente poco profundo.","Vierta la otra mitad de la mezcla de salsa BBQ sobre las tiras de pollo. Cierre la bolsa o cubra el recipiente y deje marinar el pollo en el refrigerador durante al menos 30 minutos.","Coloque las tiras de pollo en la bandeja para hornear preparada.","Hornee en el horno precalentado durante unos 20 minutos o hasta que el pollo esté bien cocido, volteándolo a la mitad del tiempo.","Sirva con el resto de la salsa BBQ."]),
"ar":T("أصابع الدجاج المخبوزة بصلصة الباربكيو","خبز أصابع الدجاج خيار صحي لا يزال مليئًا بالنكهة. تضيف نسخة الباربكيو هذه نكهة حامضة منعشة ستعجب العائلة كلها.","4","3 أصابع دجاج",
["1 كوب صلصة الطماطم (بدون ملح مضاف)","2 ملعقة كبيرة خل التفاح","1 ملعقة كبيرة خردل ديجون","1 ملعقة كبيرة عسل","1 ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة مسحوق الثوم","½ ملعقة صغيرة مسحوق البصل","½ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","1½ رطل شرائح صدر دجاج (غير مغطاة بالبقسماط)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (200° مئوية). بطّن صينية خبز بورق زبدة.","في وعاء، اخفق صلصة الطماطم وخل التفاح وخردل ديجون والعسل والبابريكا المدخنة ومسحوق الثوم ومسحوق البصل وملح الكوشر والفلفل الأسود.","احتفظ بنصف صلصة الباربكيو جانبًا لاستخدامها لاحقًا.","ضع أصابع الدجاج في كيس بلاستيكي قابل للإغلاق أو في طبق غير عميق.","اسكب النصف الآخر من خليط صلصة الباربكيو فوق أصابع الدجاج. أغلق الكيس أو غطِّ الطبق واترك الدجاج يتتبل في الثلاجة لمدة 30 دقيقة على الأقل.","رتّب أصابع الدجاج على صينية الخبز المجهزة.","اخبزها في الفرن المسخن مسبقًا لمدة 20 دقيقة تقريبًا أو حتى ينضج الدجاج تمامًا، مع قلبها في منتصف المدة.","قدّمها مع باقي صلصة الباربكيو."])}})
R.append({"id":6905433,"translations":{
"es":T("Pollo con salsa de chile dulce, camotes y brócoli","Esta comida apta para personas con diabetes es una cena fácil entre semana que toda la familia puede disfrutar. Al combinar proteína magra con verduras con almidón y sin almidón, es una excelente opción para quienes desean comer saludablemente y controlar su diabetes.","4","1 filete de pollo, 1/2 taza de camotes y 1/4 taza de brócoli",
["2 camotes (batatas) medianos (pelados y cortados en cubos medianos)","2 cucharadas + 1 cucharadita de aceite de oliva (dividido)","1/4 cucharadita de sal","2 pechugas de pollo, aprox. 8 oz, deshuesadas y sin piel (cortadas en 4 filetes delgados)","1 cabeza de brócoli (dividida en floretes, aprox. 1 libra)","2 cucharadas de salsa de chile dulce"],
["Precaliente el horno a 425 grados F. Forre una bandeja grande para hornear con papel pergamino.","Mezcle los camotes con 1 cucharada de aceite de oliva y la sal. Colóquelos en la bandeja en una sola capa. Métalos al horno y hornee durante 10 minutos.","Mientras tanto, precaliente una sartén grande a fuego medio-alto.","Cuando la sartén esté caliente, agregue 1 cucharada de aceite y el pollo. Dore hasta que esté dorado por ambos lados (pero sin que se cocine por completo). Retire del fuego.","Cuando los camotes lleven 10 minutos en el horno, saque la bandeja y agregue el pollo y el brócoli. Rocíe el brócoli con la 1 cucharadita restante de aceite de oliva.","Coloque la bandeja en el horno y continúe la cocción hasta que el pollo esté bien cocido y las verduras estén tiernas.","Retire del horno y divida entre los platos. Rocíe con la salsa de chile dulce y sirva."]),
"ar":T("دجاج بصلصة الفلفل الحلو مع البطاطا الحلوة والبروكلي","هذه الوجبة المناسبة لمرضى السكري عشاء سهل في أيام الأسبوع تستمتع به العائلة كلها. وبما أنها تجمع بين البروتين قليل الدهن والخضار النشوية وغير النشوية، فهي خيار رائع لمن يرغب في تناول طعام صحي والتحكم في مرض السكري.","4","1 شريحة دجاج، ½ كوب بطاطا حلوة و¼ كوب بروكلي",
["2 حبة بطاطا حلوة متوسطة (مقشرة ومقطعة إلى مكعبات متوسطة)","2 ملعقة كبيرة + 1 ملعقة صغيرة زيت زيتون (تُقسم)","¼ ملعقة صغيرة ملح","2 صدر، حوالي 8 أونصات من صدور الدجاج منزوعة العظم والجلد (مقطعة إلى 4 شرائح رقيقة)","1 رأس بروكلي (مقسم إلى زهيرات (حوالي 1 رطل))","2 ملعقة كبيرة صلصة الفلفل الحلو (سويت تشيلي)"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية). بطّن صينية خبز كبيرة بورق زبدة.","قلّب البطاطا الحلوة مع 1 ملعقة كبيرة من زيت الزيتون والملح. ضعها في الصينية في طبقة واحدة. أدخلها الفرن واخبزها لمدة 10 دقائق.","في الأثناء، سخّن مقلاة كبيرة على نار متوسطة إلى عالية.","عندما تسخن المقلاة، أضف 1 ملعقة كبيرة من الزيت والدجاج. حمّره حتى يصبح ذهبي اللون من الجانبين (دون أن ينضج تمامًا). ارفعه عن النار.","بعد أن تخبز البطاطا الحلوة 10 دقائق، أخرج الصينية وأضف الدجاج والبروكلي. رشّ البروكلي بالملعقة الصغيرة (1) المتبقية من زيت الزيتون.","ضع الصينية في الفرن وواصل الطهي حتى ينضج الدجاج تمامًا وتلين الخضار.","أخرجها من الفرن ووزّعها على الأطباق. رشّ عليها صلصة الفلفل الحلو وقدّمها."])}})
R.append({"id":6906210,"translations":{"ar":T("لفائف الباذنجان بنكهة اللازانيا","تجعل هذه اللفائف عشاءً أنيقًا ــ وسهلًا ومغذيًا ــ في أيام الأسبوع. تنضج شرائح الباذنجان أسرع من شرائح اللازانيا وتضيف خضارًا غير نشوية غالبًا ما تفتقر إليها أطباق الصواني والمعكرونة.","6","2 لفة",
["3 بخات، 0.75 جم من بخاخ الطهي بزيت الزيتون البكر الممتاز غير اللاصق (تُقسم)","2 حبة باذنجان متوسطة (مقشرة ومقطعة إلى 12 شريحة بسمك ½ بوصة)","2 كوب جبن قريش 1% دسم، بدون ملح مضاف","½ كوب جبن موزاريلا قليلة الدسم (مبشورة)","2 بياض بيض كبير","½ ملعقة صغيرة مسحوق البصل","¼ ملعقة صغيرة مسحوق الثوم","1 ملعقة صغيرة ريحان مجفف","½ ملعقة صغيرة أوريغانو مجفف","1 ملعقة صغيرة بقدونس مجفف","1 برطمان، 24.5 أونصة صلصة مارينارا قليلة الصوديوم","2 ملعقة كبيرة جبن بارميزان (مبشور)"],
["سخّن الفرن مسبقًا إلى 450° فهرنهايت (230° مئوية). رشّ طبق خبز بقياس 9×13 بوصة رشًا خفيفًا ببخاخ الطهي.","قطّع كل حبة باذنجان إلى 6 شرائح بسمك ½ بوصة. ضعها على رف فوق صينية خبز ورشّها رشًا خفيفًا ببخاخ الطهي. حمّص الباذنجان في الفرن لمدة 15 دقيقة حتى يلين.","في الأثناء، اخلط الجبن القريش وجبن الموزاريلا وبياض البيض والتوابل في وعاء متوسط.","أخرج الباذنجان من الفرن واتركه يبرد قليلًا. اخفض حرارة الفرن إلى 375° فهرنهايت (190° مئوية).","اسكب 1 كوب من صلصة المارينارا في طبق الخبز وافرده ليغطي القاع.","ضع 2 ملعقة كبيرة من مزيج الجبن القريش على أحد طرفي شريحة باذنجان. لفّها برفق لتكوين لفة. ضعها في طبق الخبز وجانب الالتحام إلى الأسفل. كرر ذلك مع شرائح الباذنجان الـ 11 المتبقية.","اسكب باقي صلصة المارينارا فوق اللفائف وانثر فوقها جبن البارميزان. اخبزها دون تغطية لمدة 30 دقيقة."])}})
R.append({"id":6908410,"translations":{
"es":T("Hummus de guisantes","El hummus de guisantes es una variante vibrante y refrescante del hummus tradicional, que incorpora el dulzor y el color verde brillante de los guisantes (arvejas). Es una gran opción para reuniones de primavera y verano o para cualquier momento en que desee una variación única y sabrosa del hummus tradicional.","4","1/2 taza",
["1 1/2 tazas de guisantes (arvejas) congelados (descongelados)","1/2 taza de garbanzos en lata (sin sal agregada, escurridos y enjuagados)","1/4 taza de menta fresca","2 cucharadas de tahini","1 cucharada de jugo de limón","1 diente de ajo (picado)","2 cucharadas de aceite de oliva","1/2 cucharadita de comino molido","1/4 cucharadita de sal kosher","1/4 cucharadita de pimienta negra","2 cucharadas de agua (según sea necesario)"],
["En un procesador de alimentos, combine los guisantes descongelados, los garbanzos, la menta fresca, el tahini, el jugo de limón fresco, el ajo picado, el aceite de oliva, el comino molido, la sal y la pimienta. Pulse la mezcla hasta que los ingredientes empiecen a deshacerse.","Con el procesador en marcha, agregue el agua poco a poco hasta obtener una consistencia suave y cremosa. Es posible que deba detenerse y raspar los lados del procesador un par de veces. Pruebe y ajuste el condimento si es necesario."]),
"ar":T("حمص البازلاء الخضراء","حمص البازلاء الخضراء نسخة نابضة بالحياة ومنعشة من الحمص التقليدي، تضيف حلاوة البازلاء ولونها الأخضر الزاهي. وهو خيار رائع لتجمعات الربيع والصيف أو في أي وقت ترغب فيه بنسخة فريدة ولذيذة من الحمص التقليدي.","4","½ كوب",
["1½ كوب بازلاء مجمدة (مذابة)","½ كوب حمص معلب (بدون ملح مضاف، مصفى ومشطوف)","¼ كوب نعناع طازج","2 ملعقة كبيرة طحينة","1 ملعقة كبيرة عصير ليمون","1 فص ثوم (مفروم)","2 ملعقة كبيرة زيت زيتون","½ ملعقة صغيرة كمون مطحون","¼ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة ماء (حسب الحاجة)"],
["في محضرة الطعام، اخلط البازلاء المذابة والحمص والنعناع الطازج والطحينة وعصير الليمون الطازج والثوم المفروم وزيت الزيتون والكمون المطحون والملح والفلفل. اخلط بنبضات متقطعة حتى تبدأ المكونات بالتفتت.","أثناء تشغيل المحضرة، أضف الماء تدريجيًا حتى تحصل على قوام ناعم وكريمي. قد تحتاج إلى إيقاف المحضرة وكشط الجوانب مرتين. تذوّق وعدّل التتبيل إذا لزم الأمر."])}})
R.append({"id":6909702,"translations":{"ar":T("القرنبيط والبصل والبطاطا الحلوة المحمّصة","يُبرز تحميص الخضار حلاوتها الطبيعية. وبإضافة جوزة الطيب الدافئة ورشة ملح، يصبح هذا طبقًا جانبيًا مثاليًا للحم الخنزير المشوي أو الدجاج المحمّص.","4","¾ كوب",
["3 كوب زهيرات قرنبيط (مقطعة إلى قطع بحجم 1 بوصة)","6 أونصات بطاطا حلوة (مقشرة ومقطعة إلى مكعبات بحجم ¾ بوصة)","1 حبة بصل متوسطة (مقطعة إلى 8 أرباع)","1 ملعقة كبيرة زيت الكانولا","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة جوزة الطيب المطحونة"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية).","ضع القرنبيط والبطاطا والبصل على صينية خبز كبيرة مبطنة بورق الألمنيوم. رشّ عليها الزيت وقلّبها برفق حتى تتغطى جيدًا. رتّب الخضار في طبقة واحدة واخبزها 10 دقائق. قلّبها واخبزها 10–11 دقيقة أو حتى تنضج البطاطا. أخرجها من الفرن.","انثر الملح وجوزة الطيب بالتساوي. لفّ الخضار بورق الألمنيوم وأحكم إغلاق الحواف. اتركها 10 دقائق لتتشرب النكهات وتفرز عصارتها الطبيعية قليلًا."])}})
R.append({"id":6910724,"translations":{
"es":T("Ensalada de sandía y quinoa","Esta ensalada de sandía y quinoa está llena de verduras nutritivas y quinoa saciante que lo mantendrá satisfecho durante horas. Prepárela en verano, cuando la sandía está en su mejor momento, para disfrutar una explosión de sabor.","4","2 tazas de ensalada (1/2 taza de quinoa por porción)",
["1 taza de caldo de verduras bajo en sodio","1/2 taza de quinoa (enjuagada)","5 oz de arúgula tierna","2 tazas de sandía (en cubos medianos)","1 aguacate (en cubos medianos)","1/4 taza de semillas de calabaza con sal","1/2 oz de menta fresca (hojas desgarradas)","4 oz de queso feta sin grasa","1 lima mediana (con ralladura y jugo)","1 1/2 cucharadas de aceite de oliva","1 cucharadita de miel"],
["Lleve el caldo a ebullición en una olla pequeña. Agregue la quinoa, tape y reduzca el fuego a bajo. Cocine durante 15 minutos, o hasta que se absorba el caldo. Extienda la quinoa en una capa delgada sobre una bandeja grande para hornear para que se enfríe.","Cuando la quinoa se haya enfriado a temperatura ambiente, coloque la arúgula en una fuente grande. Cubra con la quinoa, la sandía, el aguacate, las semillas de calabaza, la menta y el queso feta.","Combine la ralladura y el jugo de la lima, el aceite y la miel en un tazón pequeño. Bata para integrar y rocíe el aderezo sobre la ensalada. Agregue sal y pimienta si lo desea."]),
"ar":T("سلطة البطيخ والكينوا","هذه السلطة بالبطيخ والكينوا مليئة بالخضار المغذية والكينوا المشبعة التي ستبقيك ممتلئًا لساعات. جرّبها في الصيف عندما يكون البطيخ في ذروة موسمه لتحصل على انفجار من النكهة.","4","2 كوب سلطة (½ كوب كينوا لكل حصة)",
["1 كوب مرق خضار قليل الصوديوم","½ كوب كينوا (مشطوفة)","5 أونصات جرجير صغير","2 كوب بطيخ (مقطع إلى مكعبات متوسطة)","1 حبة أفوكادو (مقطعة إلى مكعبات متوسطة)","¼ كوب بذور قرع مملحة","½ أونصة نعناع طازج (أوراق ممزقة)","4 أونصات جبن فيتا خالٍ من الدسم","1 حبة ليمون أخضر متوسطة (مبشورة القشر ومعصورة)","1½ ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة عسل"],
["اغلِ المرق في قدر صغير. أضف الكينوا وغطِّ القدر، وخفّف النار إلى منخفضة. اطهِها لمدة 15 دقيقة، أو حتى يُمتص المرق. افرد الكينوا في طبقة رقيقة على صينية خبز كبيرة لتبرد.","بعد أن تبرد الكينوا إلى درجة حرارة الغرفة، رتّب الجرجير على طبق تقديم كبير. ضع فوقه الكينوا والبطيخ والأفوكادو وبذور القرع والنعناع وجبن الفيتا.","اخلط قشر الليمون الأخضر المبشور وعصيره والزيت والعسل في وعاء صغير. اخفقها جيدًا ورشّ التتبيلة فوق السلطة. أضف الملح والفلفل إن رغبت."])}})
R.append({"id":6910935,"translations":{
"es":T("Bowl de sushi bajo en carbohidratos","Este bowl de sushi bajo en carbohidratos es una versión fresca de la comida para llevar, que reemplaza el arroz tradicional por coliflor sazonada para mantener bajos los carbohidratos sin perder sabor. Los camarones aportan proteína magra, mientras que el aguacate y las verduras ofrecen una textura satisfactoria y grasas saludables. Es una opción apta para personas con diabetes que ayuda a mantener los niveles de glucosa en la sangre (azúcar en la sangre) sin sacrificar nada de sabor.","4","3 oz de arroz de coliflor + 2 oz de camarones + 1 taza de verduras + 1 cucharada de mayonesa",
["12 oz de arroz de coliflor congelado","1 cucharada de vinagre de arroz","1/2 cucharadita de aceite de sésamo","1/8 cucharadita de sal","1/4 taza de mayonesa light","1 cucharada de sriracha","1 cucharadita de jugo de limón verde","8 oz de camarones (cocidos, en cubitos)","1 aguacate mediano (en cubitos)","1 pepino mediano (cortado en juliana)","1/4 taza de rábano (en rodajas finas)","2 tallos de cebollín (cebolla verde) (picados)","1 cucharada de semillas de sésamo"],
["Cocine el arroz de coliflor congelado según las instrucciones del envase. Pase a un tazón y mezcle con el vinagre, el aceite de sésamo y la sal. Deje enfriar a temperatura ambiente.","En un tazón pequeño, bata la mayonesa, la sriracha y el jugo de limón verde. Reserve.","Para armar, divida el arroz de coliflor entre 4 tazones. Cubra cada tazón con los camarones en cubitos, el aguacate, el pepino, los rábanos y el cebollín.","Rocíe la mayonesa picante sobre cada tazón y espolvoree con las semillas de sésamo."]),
"ar":T("وعاء السوشي قليل الكربوهيدرات","وعاء السوشي قليل الكربوهيدرات هذا نسخة منعشة من الوجبات الجاهزة، يستبدل الأرز التقليدي بالقرنبيط المتبّل لإبقاء الكربوهيدرات منخفضة دون فقدان النكهة. يضيف الروبيان بروتينًا قليل الدهن، بينما يمنح الأفوكادو والخضار قوامًا مشبعًا ودهونًا صحية. وهو خيار مناسب لمرضى السكري يدعم مستويات الجلوكوز (سكر الدم) دون التضحية بأي نكهة.","4","3 أونصات أرز القرنبيط + 2 أونصة روبيان + 1 كوب خضار + 1 ملعقة كبيرة مايونيز",
["12 أونصة أرز قرنبيط مجمد","1 ملعقة كبيرة خل الأرز","½ ملعقة صغيرة زيت السمسم","⅛ ملعقة صغيرة ملح","¼ كوب مايونيز خفيف","1 ملعقة كبيرة صلصة سريراتشا","1 ملعقة صغيرة عصير ليمون أخضر","8 أونصات روبيان (مطبوخ، مقطع إلى مكعبات)","1 حبة أفوكادو متوسطة (مقطعة إلى مكعبات)","1 حبة خيار متوسطة (مقطعة إلى أعواد رفيعة)","¼ كوب فجل (مقطع إلى شرائح رقيقة)","2 ساق بصل أخضر (مفروم)","1 ملعقة كبيرة بذور السمسم"],
["اطهِ أرز القرنبيط المجمد وفق إرشادات العبوة. انقله إلى وعاء واخلطه مع الخل وزيت السمسم والملح. اتركه يبرد إلى درجة حرارة الغرفة.","في وعاء صغير، اخفق المايونيز والسريراتشا وعصير الليمون الأخضر. اتركه جانبًا.","للتجميع، وزّع أرز القرنبيط على 4 أوعية. ضع فوق كل وعاء الروبيان المقطع والأفوكادو والخيار والفجل والبصل الأخضر.","رشّ المايونيز الحار فوق كل وعاء وزيّنه ببذور السمسم."])}})
R.append({"id":6912355,"translations":{
"es":T("Bowl griego de requesón","Este sencillo bowl griego de requesón combina requesón cremoso y rico en proteínas con una ensalada crujiente y cítrica de tomates, pepino y aceitunas. Es una comida refrescante, sin cocción, que aporta mucha fibra y grasas saludables. Con su bajo contenido de carbohidratos y sus nutrientes equilibrados, es especialmente adecuado para quienes controlan la diabetes. Es una receta baja en carbohidratos, baja en grasa y vegetariana.","4","1/2 taza de requesón, 1 taza de verduras",
["1 taza de tomates cherry (cortados por la mitad)","1 pepino inglés pequeño (en cubitos)","8 aceitunas Kalamata enteras (en rodajas)","1 cucharada de jugo de limón (fresco)","1 cucharada de vinagre de vino tinto","1 cucharadita de aceite de oliva","1/2 cucharadita de orégano seco","1/4 cucharadita de pimienta negra","2 tazas de requesón (bajo en grasa)","2 cucharadas de perejil fresco (picado)"],
["En un tazón mediano, mezcle los tomates cherry, el pepino, las aceitunas, el jugo de limón, el vinagre de vino tinto, el aceite de oliva, el orégano y la pimienta negra.","Divida el requesón de manera uniforme entre 4 tazones. Vierta con una cuchara la mezcla de ensalada griega sobre cada porción. Cubra con el perejil fresco."]),
"ar":T("وعاء الجبن القريش اليوناني","يمزج وعاء الجبن القريش اليوناني البسيط هذا بين الجبن القريش الكريمي الغني بالبروتين وسلطة مقرمشة منعشة من الطماطم والخيار والزيتون. إنها وجبة منعشة لا تحتاج إلى طهي وتوفر الكثير من الألياف والدهون الصحية. ومع انخفاض محتواها من الكربوهيدرات وتوازن عناصرها الغذائية، فهي مناسبة بشكل خاص لمن يتحكمون في مرض السكري. وهي وصفة قليلة الكربوهيدرات وقليلة الدهون ونباتية.","4","½ كوب جبن قريش، 1 كوب خضار",
["1 كوب طماطم كرزية (مقطعة إلى نصفين)","1 حبة خيار إنجليزي صغيرة (مقطعة إلى مكعبات)","8 حبات زيتون كالاماتا كاملة (مقطعة إلى شرائح)","1 ملعقة كبيرة عصير ليمون (طازج)","1 ملعقة كبيرة خل النبيذ الأحمر","1 ملعقة صغيرة زيت زيتون","½ ملعقة صغيرة أوريغانو مجفف","¼ ملعقة صغيرة فلفل أسود","2 كوب جبن قريش (قليل الدسم)","2 ملعقة كبيرة بقدونس طازج (مفروم)"],
["في وعاء متوسط، قلّب الطماطم الكرزية والخيار والزيتون وعصير الليمون وخل النبيذ الأحمر وزيت الزيتون والأوريغانو والفلفل الأسود.","وزّع الجبن القريش بالتساوي على 4 أوعية. ضع خليط السلطة اليونانية بالملعقة فوق كل حصة. زيّنه بالبقدونس الطازج."])}})
R.append({"id":6912677,"translations":{"ar":T("كرات لحم مناسبة للأطفال","هذه وصفة كرات لحم مناسبة لمرضى السكري ستحبها عائلتك. إنها طريقة رائعة لإدخال بعض الخضار الإضافية إلى طعامك وطعام أطفالك دون أن يشعروا.","11","2 كرة لحم",
["½ كوب كاتشب","3 ملعقة كبيرة خل بلسميك","1 رطل ديك رومي مفروم (93% خالٍ من الدسم)","½ حبة كوسا متوسطة (مبشورة)","1 حبة جزر متوسطة (مبشورة)","½ حبة بصل متوسطة (مبشورة)","1 فص ثوم (مفروم)","2 ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح (اختياري)","1 بيضة كبيرة (مخفوقة قليلًا)","½ كوب شوفان مجروش تقليدي","3 ملعقة كبيرة جبن بارميزان (مبشور طازجًا)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية).","في وعاء صغير، اخفق الكاتشب والخل لتحضير الصلصة.","في وعاء متوسط، اخلط باقي المكونات الخاصة بكرات اللحم. شكّلها على هيئة كرات بحجم 1 بوصة.","ضع كرات اللحم على صينية خبز وغطِّها بالتساوي بالصلصة (1½ ملعقة صغيرة لكل كرة).","اخبزها لمدة 45 دقيقة أو حتى تنضج."])}})
save(4,R)
