from lib import *
o=[]
o.append(R(0,"Fufu et soupe pimentée au poulet","Une soupe traditionnelle d’Afrique de l’Ouest, relevée et rassasiante. Servie avec du fufu de plantain.","4","435g",
["2 c. à café d’huile de colza","1 gros oignon, haché","2 blancs de poulet sans os ni peau (environ 300g), coupés en petits morceaux","2 carottes moyennes, coupées en petits morceaux","1 courgette, coupée en morceaux","2 c. à café de poudre de curry","1 bonne pincée de noix de muscade","1 c. à café rase de paprika","1 c. à soupe de concentré de tomate","2 piments rouges, coupés en rondelles","1 boîte de 400g de tomates concassées","1 cube de bouillon de poulet à teneur réduite en sel, dilué dans 500ml d’eau","400ml d’eau","200g de farine de fufu de plantain"],
["Faites chauffer l’huile dans une casserole et ajoutez l’oignon. Faites cuire 4 minutes en remuant régulièrement. Ajoutez le poulet et la carotte et poursuivez la cuisson 4 minutes, en remuant régulièrement.","Ajoutez la courgette, la poudre de curry, la noix de muscade, le paprika et le concentré de tomate, puis mélangez bien.","Ajoutez les piments, les tomates et le bouillon, portez à ébullition, baissez le feu, couvrez et laissez mijoter doucement 12 minutes.","Pendant ce temps, versez 400ml d’eau dans une casserole et portez à ébullition, baissez le feu et incorporez la farine de fufu. Remuez sans cesse pendant 3 à 4 minutes, jusqu’à ce que toute la farine soit absorbée et qu’il n’y ait plus de grumeaux. Retirez du feu, battez énergiquement avec une cuillère en bois et continuez à mélanger pendant 2 minutes, jusqu’à obtenir une pâte lisse.","Mouillez-vous les mains et divisez le fufu en quatre boules. Répartissez la soupe dans quatre bols et déposez délicatement une portion de fufu sur chaque soupe pimentée pour servir."],
["Vous pouvez préparer la soupe pimentée avec de l’agneau ou du bœuf à la place du poulet.","Pour une version végétalienne/végétarienne, remplacez le poulet par une aubergine moyenne hachée et 200g de champignons."]))
o.append(R(1,"Saumon sauce au brocoli et aux poireaux","Un plat principal léger, à servir de préférence avec beaucoup de légumes cuits à la vapeur.","4","336g",
["1 cube de bouillon de poisson pauvre en sel, dilué dans 200ml d’eau bouillante","320g de brocoli, en bouquets","150g de poireaux, hachés","175ml de lait demi-écrémé","1 c. à soupe de fécule de maïs, délayée dans 25ml de lait demi-écrémé","1 c. à café de moutarde de Dijon","1 bonne pincée de poivre blanc","15g de parmesan","400g de saumon, en cubes","1 c. à soupe de fromage frais allégé en matière grasse","10g de persil frais, haché"],
["Versez le bouillon de poisson dans une grande casserole.","Ajoutez le brocoli et les poireaux. Laissez mijoter doucement 7 à 8 minutes, puis incorporez le lait demi-écrémé et portez à frémissement.","Pendant ce temps, ajoutez le mélange de fécule de maïs dans la casserole en remuant jusqu’à ce que la sauce commence à épaissir.","Incorporez ensuite la moutarde de Dijon, le poivre blanc et le parmesan. Ajoutez le saumon, couvrez et faites cuire 3 à 4 minutes, ou jusqu’à ce que le poisson soit tout juste cuit.","Incorporez délicatement le fromage frais et le persil haché. Terminez en saupoudrant de persil haché et servez."],
["Cette recette convient bien à la plupart des poissons."]))
o.append(R(2,"Guacamole","Avocat, tomates et oignon rouge avec du yaourt grec crémeux à 0 % de matières grasses, servis avec des chips de tortilla croustillantes cuites au four.","4","145g",
["1 gros avocat (100g de chair)","2 grosses tomates, hachées (240g)","1 oignon rouge, râpé","1 bonne pincée de poivre","2 c. à soupe de yaourt grec à 0 % de matières grasses","le jus d’une demi-lime","1 c. à soupe de coriandre hachée","1/2 à 1 piment rouge (facultatif)"],
["Préchauffez le four à 180°C / thermostat 4.","Dénoyautez, pelez et écrasez un avocat mûr dans un bol.","Ajoutez les tomates, les oignons, une pincée de poivre, le yaourt, le jus de lime et la coriandre, puis mélangez bien. Placez dans un bol et saupoudrez de piment, si vous en utilisez.","Pendant ce temps, placez les tortillas sur une plaque de cuisson et faites cuire au four 10 à 12 minutes, en les retournant deux ou trois fois. Pendant la cuisson, coupez les légumes à tremper.","Disposez les légumes et les chips de tortilla sur un plat de service avec le guacamole, et servez."],
["Si vous aimez le guacamole épicé, ajoutez des flocons de piment et/ou 1 c. à café de piment en poudre avec le poivre.","Vous pouvez utiliser les légumes de votre choix pour tremper. Choisissez des couleurs et des textures variées pour que ce soit plus appétissant.","Cette recette peut facilement être préparée sans gluten : il suffit d’utiliser des tortillas sans gluten."]))
o.append(R(3,"Ragoût de tomates, ail et haricots de Lima","Ce délicieux ragoût est riche en fibres et en protéines.","4","401g",
["1 gros oignon rouge, finement émincé","2 boîtes de 400g de tomates concassées","3 poivrons de couleurs variées, épépinés et émincés","400g de haricots de Lima en conserve dans de l’eau non salée, égouttés et rincés","150g de chou kale, lavé","1 cal de spray d’huile","2 gousses d’ail, écrasées","1 c. à café de paprika fumé","2 c. à soupe de concentré de tomate"],
["Vaporisez une grande casserole de spray de cuisson faible en calories et placez-la sur feu moyen-vif. Ajoutez l’oignon et 4 c. à soupe d’eau, et faites cuire 3 à 4 minutes jusqu’à ce que l’eau se soit évaporée et que l’oignon soit ramolli.","Ajoutez l’ail et le paprika fumé et faites cuire 1 à 2 minutes.","Ajoutez les tomates concassées, le concentré de tomate et les poivrons. Portez à ébullition, couvrez et laissez mijoter à feu doux 15 minutes.","Ajoutez les haricots de Lima et le chou kale. Mélangez bien, enfoncez le chou kale sous la sauce et faites cuire à découvert 6 à 8 minutes, jusqu’à ce qu’il soit flétri."],[]))
o.append(R(4,"Pizza sur pain naan","Une autre façon de réaliser une pizza sur une base plus moelleuse, avec des ingrédients bien frais.","4","216g",
["1 c. à café d’huile de colza","1 oignon rouge","1 poivron rouge, émincé","1 poivron jaune, émincé","1 c. à café d’origan","2 tomates séchées, finement hachées","4 petits pains naan nature individuels (65g chacun)","30g de fromage frais léger à l’ail et aux fines herbes","30g de fromage blanc à 0 % de matières grasses","10 feuilles de basilic frais, déchirées","8 tomates cerises, coupées en quatre","poivre noir"],
["Préchauffez le four à 190°C / thermostat 5.","Versez l’huile sur une plaque de cuisson. Ajoutez les oignons et les poivrons et faites cuire au four 15 à 20 minutes, jusqu’à ce qu’ils commencent à dorer.","Sortez les oignons et les poivrons du four. Incorporez l’origan et les tomates séchées. Réservez et laissez refroidir.","Pendant ce temps, faites cuire les pains naan selon les instructions de l’emballage (3 à 4 minutes) et réservez.","Une fois les pains naan et les légumes refroidis (environ 30 minutes), étalez le fromage frais sur chaque naan et parsemez de petites touches de fromage blanc.","Parsemez de la moitié des feuilles de basilic, puis ajoutez les poivrons et les oignons rôtis.","Garnissez avec les tomates et le reste des feuilles de basilic, puis ajoutez un bon tour de moulin à poivre noir avant de servir."],[]))
o.append(R(5,"Galettes de patate douce (latkes) et compote de pommes","Ces latkes délicatement sucrés sont simples à préparer et complètent un buffet.","12","76g",
["1 grosse patate douce (environ 350g), pelée","1 petit oignon, finement haché","1 œuf, battu","1 bonne pincée de poivre","50g de farine de blé","2 pommes, pelées, évidées et hachées","3 c. à soupe d’eau","2 c. à café d’huile de colza, pour la cuisson"],
["Râpez la patate douce. Placez-la dans un bol avec l’oignon, l’œuf et le poivre, et mélangez bien.","Ajoutez la farine, mélangez soigneusement et laissez reposer 5 minutes.","Pendant ce temps, mettez les pommes hachées et l’eau dans une casserole avec un couvercle, et faites cuire à feu moyen à doux en remuant de temps en temps et en écrasant avec le dos d’une cuillère. Laissez cuire 12 à 15 minutes jusqu’à ce que les pommes soient tendres, puis réservez.","Faites chauffer une poêle antiadhésive à feu moyen, ajoutez une cuillère à café d’huile et étalez-la pour enduire le fond de la poêle. Quand la poêle est chaude, ajoutez une cuillerée de préparation à la patate douce et aplatissez-la en forme de galette. Faites cuire 3 minutes, puis retournez délicatement avec une spatule et faites cuire l’autre côté 2 à 3 minutes.","Servez avec la compote de pommes."],
["Pour un accompagnement moins sucré, ces latkes seront aussi délicieux servis avec du yaourt grec à 0 % de matières grasses."]))
o.append(R(6,"Pain irlandais (soda bread)","Ce pain est rapide et facile à préparer, car il n’est pas nécessaire d’attendre que la pâte lève. La farine complète le rend plus nourrissant et lui donne du caractère.","8","97g",
["250g de farine complète","200g de farine de blé","1/2 c. à café de bicarbonate de soude","1/2 c. à café de crème de tartre","25g de beurre","300ml de babeurre"],
["Tamisez ensemble les farines, le bicarbonate de soude et la crème de tartre dans un bol, puis incorporez le beurre du bout des doigts jusqu’à ce que le mélange ressemble à de la chapelure fine. Incorporez rapidement le babeurre et mélangez jusqu’à obtenir une pâte.","Déposez la pâte sur un plan de travail légèrement fariné et pétrissez jusqu’à ce qu’elle soit lisse. Façonnez-la en boule, placez-la sur une plaque de cuisson légèrement farinée, entaillez le dessus en croix et saupoudrez d’un peu de farine.","Préchauffez le four à 180°C / thermostat 5 et faites cuire 25 à 30 minutes, jusqu’à ce que le pain sonne creux quand on le tapote."],
["Lorsque vous tamisez de la farine complète, remettez dans la farine le son resté dans le tamis après le tamisage.","Vous pouvez ajouter 75g de fruits secs variés et 1 c. à café de mélange d’épices pour obtenir un délicieux pain aux fruits.","Ce pain irlandais est idéal pour être coupé en tranches et congelé : mettez les tranches directement dans le grille-pain.","Instructions de congélation : Peut être congelé une fois cuit. Coupez-le en tranches, puis enveloppez-les dans du papier d’aluminium pour les congeler. Vous pourrez ensuite utiliser les tranches selon vos besoins."]))
o.append(R(7,"Rondelles de courge farcies aux champignons","Épatez vos invités avec ce plat littéralement farci de saveurs ! Cette recette a été sélectionnée en partenariat avec Slimming World.","4","521g",
["1 grosse courge butternut (ou 2 petites), pelée ou non","Spray de cuisson faible en calories","1 gros oignon, finement haché","800g de champignons variés (nous avons utilisé des champignons de Paris bruns, des pleurotes et des chanterelles), finement hachés","4 feuilles de sauge fraîche, finement hachées, plus 12 feuilles entières","1 cube de bouillon de légumes pauvre en sel, convenant aux végétaliens","25g de flocons d’avoine"],
["Coupez la courge en 12 rondelles épaisses (d’environ 1 à 2 cm d’épaisseur chacune) en retirant et en jetant les graines et la pulpe. À l’aide d’un emporte-pièce ou d’un petit couteau, découpez un cercle au centre des rondelles pleines pour obtenir de grands anneaux. Râpez les cercles découpés au centre et réservez.","Vaporisez une grande poêle antiadhésive de quelques pressions de spray de cuisson faible en calories et placez-la sur feu doux. Ajoutez l’oignon et faites cuire 5 minutes, puis ajoutez les champignons, la sauge hachée et la courge râpée et faites cuire 5 minutes.","Préchauffez votre four à 200°C / chaleur tournante 180°C / thermostat 6.","Émiettez le cube de bouillon dans la poêle, mélangez bien pour qu’il se dissolve complètement et faites cuire 10 minutes. Incorporez les flocons d’avoine et versez le tout dans un grand bol.","Disposez tous les anneaux de courge sur une grande plaque de cuisson antiadhésive (il vous faudra peut-être 2 plaques) et remplissez-les avec la préparation aux champignons en lissant le dessus aussi soigneusement que possible. Vaporisez de quelques pressions de spray de cuisson faible en calories et faites rôtir 30 à 35 minutes, jusqu’à ce qu’ils soient cuits et légèrement dorés.","Lorsque les anneaux de courge sont presque cuits, faites frire les feuilles de sauge entières dans un peu de spray de cuisson faible en calories pendant quelques minutes.","Répartissez les anneaux de courge farcis dans les assiettes, parsemez de feuilles de sauge et servez avec vos légumes préférés. Nous recommandons des haricots verts longs et des poivrons cuits à la vapeur."]))
o.append(R(8,"Légumes rouges rôtis au gingembre et à l’ail","Ce plat sain et épicé fait un accompagnement idéal, ou peut être servi avec du riz ou des pommes de terre au four pour un repas copieux. Merci à la célèbre cheffe Sophie Grigson pour cette recette.","8","296g",
["2 c. à soupe d’huile d’olive extra vierge","12 tomates allongées, coupées en deux (de la tige à la pointe)","4 poivrons rouges, épépinés, coupés en huit","3 oignons rouges, coupés en quatre","1 morceau de 5cm de gingembre frais, pelé et haché","12 gousses d’ail (non épluchées)","4 grosses branches de thym","poivre noir fraîchement moulu"],
["Préchauffez le four à 200ºC / thermostat 6.","Versez la moitié de l’huile dans un grand plat à four peu profond et tassez-y les tomates, les poivrons et les oignons en une seule couche serrée.","Saupoudrez de gingembre et glissez les gousses d’ail et les branches de thym entre les légumes.","Arrosez avec le reste de l’huile et assaisonnez de poivre.","Mélangez pour que tout soit uniformément enrobé, puis enfournez à découvert.","Faites rôtir environ 40 à 45 minutes, en remuant de temps en temps, jusqu’à ce que les légumes soient tendres et légèrement dorés par endroits. Servez chaud ou tiède."],
["Une fois cuit, vous pouvez facilement faire sortir l’ail de sa peau en le pressant entre le pouce et l’index.","Transformez ce plat en sauce pour pâtes en hachant grossièrement le plat terminé et en le mélangeant à des pâtes cuites.","Instructions de congélation : Congelez dans un sac. Décongelez au micro-ondes et utilisez comme sauce pour pâtes."]))
o.append(R(9,"Kugel aux carottes","Le kugel est un plat traditionnel juif. Il est généralement préparé avec des nouilles et sucré, mais il existe aussi des versions salées, avec des pommes de terre ou des carottes. Il constitue un excellent déjeuner ou dîner léger servi avec une salade, et peut se manger chaud ou froid.","4","196g",
["2 œufs","1 gousse d’ail, écrasée","1 c. à café de moutarde de Dijon","50g de fromage frais allégé en matière grasse","50g de cheddar affiné allégé en matière grasse, finement râpé","1 bonne pincée de poivre blanc","500g de carottes","50g d’oignon, râpé","2 c. à café d’huile de tournesol"],
["Mettez les œufs, l’ail, la moutarde, le fromage frais, le cheddar et le poivre dans un grand bol et mélangez bien en battant à la fourchette.","Râpez la carotte et l’oignon, ajoutez-les au mélange d’œufs et de fromage et battez ensemble pour que la carotte soit entièrement enrobée de préparation.","Huilez un plat à tarte ou un moule allant au four de 15 à 18 cm de diamètre. Une fois huilé, ajoutez la préparation et appuyez légèrement pour bien la répartir.","Faites cuire dans un four préchauffé à 180°C / thermostat 4 pendant 20 à 25 minutes, jusqu’à ce que le dessus commence à dorer.","Laissez refroidir un peu avant de servir, ou laissez refroidir complètement et conservez au réfrigérateur pour le lendemain."],
["Vous pouvez aussi parfumer ce plat avec 2 à 3 c. à café d’herbes fraîches hachées, comme le basilic, l’origan, l’estragon, le thym ou la coriandre.","Essayez ce plat avec des patates douces à la place des carottes. Idéal pour un déjeuner d’été ou un pique-nique."]))
o.append(R(10,"Kedgeree au chou-fleur","Faites plaisir à vos papilles ce week-end avec ce savoureux petit-déjeuner chaud.","4","389g",
["1 chou-fleur, paré","1 c. à café d’huile de colza ou de tournesol","1 oignon, pelé et finement émincé","2 gousses d’ail, pelées et finement hachées","1 piment rouge, épépiné et finement haché","1 c. à café de gingembre finement haché","1 c. à soupe de poudre de curry","400g d’églefin fumé sans peau","150ml de bouillon de légumes, préparé avec 1 cube de bouillon à teneur réduite en sel","200g de petits pois surgelés","4 œufs","1 petite poignée de persil plat, haché","Quartiers de citron, pour servir"],
["Coupez le chou-fleur en bouquets, placez-les dans un robot de cuisine et mixez jusqu’à obtenir de petits grains.","Placez le poisson et le bouillon de légumes dans une grande poêle et portez à ébullition, couvrez et faites cuire à feu très doux 6 à 8 minutes, jusqu’à ce que le poisson soit cuit.","Pendant ce temps, faites chauffer l’huile dans une grande poêle antiadhésive. Ajoutez l’oignon et faites revenir 6 à 7 minutes jusqu’à ce qu’il soit ramolli et doré. Incorporez l’ail, le gingembre, le piment et la poudre de curry et faites revenir 1 minute en remuant sans cesse. Retirez le poisson du bouillon à l’aide d’une spatule à poisson. Émiettez-le, gardez-le au chaud et réservez. Ajoutez le bouillon réservé et les petits pois au mélange d’oignon et faites cuire 2 minutes.","Incorporez le chou-fleur au mélange d’oignon, couvrez et faites cuire à feu doux 8 à 10 minutes, en remuant de temps en temps, jusqu’à ce que le chou-fleur ait absorbé tout le bouillon et soit tendre.","Pendant ce temps, placez les œufs dans une petite casserole et couvrez d’eau froide. Portez à ébullition et laissez frémir 8 à 10 minutes, jusqu’à ce qu’ils soient durs. Retirez du feu, passez sous l’eau froide jusqu’à ce qu’ils soient refroidis, puis écalez-les et coupez-les en deux.","Incorporez le poisson émietté et le persil au chou-fleur et assaisonnez de poivre selon votre goût. Disposez les œufs sur le kedgeree. Servez avec des quartiers de citron à presser dessus."]))
o.append(R(11,"Soupe de moules et de légumes de printemps","Savourez cette soupe nutritive, rapide à préparer en une seule casserole.","4","376g",
["200g de pommes de terre nouvelles","1kg de moules fraîches","200g de brocoli violet","1 c. à soupe d’huile de tournesol","100g de poireau, finement émincé","3 gousses d’ail, écrasées","1 botte d’oignons nouveaux, parés et grossièrement hachés","100g de fèves surgelées, décongelées","400ml de lait demi-écrémé","1 bonne pincée de poivre noir","1 grosse poignée de persil, fraîchement haché"],
["Faites bouillir les pommes de terre nouvelles et coupez-les en morceaux de la taille d’une bouchée. Pendant ce temps, préparez les moules (voir les conseils du chef ci-dessous).","Émincez finement les tiges du brocoli violet en laissant les têtes intactes. Préparez le reste des ingrédients.","Versez l’huile dans une grande casserole sur feu moyen-doux, ajoutez le brocoli violet et les poireaux émincés. Faites cuire 5 à 6 minutes.","Ajoutez l’ail et l’oignon nouveau, remuez 2 minutes et montez le feu à puissance maximale.","Ajoutez maintenant les moules, mélangez et couvrez la casserole, puis faites cuire 3 à 4 minutes en secouant la casserole plusieurs fois.","Ajoutez les fèves, le lait, les pommes de terre nouvelles, le poivre et le persil. Portez à ébullition (2 à 3 minutes) en remuant régulièrement, puis baissez le feu et laissez frémir 1 minute.","Répartissez dans 4 bols et servez."],
["Lavez-les sous l’eau froide courante en jetant celles dont la coquille est cassée.","Repérez les moules ouvertes et tapotez-les ; si elles ne se referment pas, jetez-les.","Retirez les « barbes » (la petite touffe de fibres brunes).","Grattez les éventuels balanes avec un petit couteau et frottez avec une brosse de cuisine.","Rincez encore une fois les moules dans une passoire. Réservez."]))
o.append(R(12,"Pilaf de poulet, courge et coriandre","Ce plat à base de riz regorge de saveurs et de textures.","4","400g",
["2 c. à café d’huile de tournesol","250 g de riz complet, rincé à plusieurs eaux, puis égoutté","2 c. à café de poudre de curry doux","1 c. à café de cumin moulu","1 c. à café de coriandre moulue","1/2 c. à café de curcuma moulu","750 ml d’eau","1 courgette jaune ou verte, finement émincée","2 gros blancs de poulet sans peau (400g), débarrassés de l’excès de gras","2 c. à soupe d’amandes effilées","le jus de 1/2 citron","1 poignée de feuilles de coriandre","Poivre noir fraîchement moulu","1 courge (environ 250-350g)"],
["Préchauffez le four à 180°C (160°C chaleur tournante) / thermostat 4.","Faites chauffer l’huile de tournesol dans une cocotte ou un plat allant au four, placé sur feu moyen, jusqu’à ce qu’elle soit chaude.","Ajoutez le riz et faites-le revenir dans l’huile 2 minutes en remuant fréquemment. Saupoudrez des épices et faites cuire encore 2 minutes, jusqu’à ce qu’elles dégagent leur parfum.","Couvrez d’eau en remuant bien. Portez à ébullition avant de disposer la courge et le poulet sur le riz.","Couvrez le plat sans serrer de papier d’aluminium et placez-le au four pendant environ 30 minutes, jusqu’à ce que le riz ait absorbé l’eau et que le poulet soit bien cuit.","Sortez du four et retirez le papier d’aluminium. Parsemez d’amandes et remettez le plat au four 7 à 10 minutes, jusqu’à ce que les amandes soient dorées.","Sortez du four. Transférez le poulet sur une assiette et laissez-le refroidir 5 minutes avant de l’effilocher avec deux fourchettes.","Incorporez un peu de jus de citron au pilaf et égrenez le riz à la fourchette pour séparer les grains.","Garnissez avec le poulet effiloché et décorez de quelques feuilles de coriandre avant de servir."],
["Les courges jaunes sont disponibles chez les bons primeurs et dans les supermarchés. Choisissez une courge d’environ 250 à 350g.","Pour ajouter de la couleur et de la variété, remplacez la moitié des amandes effilées par des noix de cajou et des pistaches non salées."]))
o.append(R(13,"Ciabatta au fromage de chèvre et légumes rôtis","Ciabatta garnie de légumes rôtis et de fromage de chèvre – un déjeuner végétarien à emporter.","4","376g",
["3 poivrons – rouge, jaune et vert, grossièrement hachés (150g chacun)","1 gros oignon rouge, coupé en quartiers (200g)","1 courgette, coupée en rondelles (250g)","2 c. à soupe d’huile d’olive extra vierge","2 à 3 c. à café de vinaigre balsamique","1 c. à café d’origan séché","poivre noir","2 demi-ciabattas précuites (300g)","100g de fromage de chèvre","2 tomates, en rondelles (160g)","une poignée de basilic frais"],
["Préchauffez le four à 200°C / thermostat 5. Placez les poivrons, l’oignon et la courgette sur une plaque de cuisson légèrement huilée et faites-les rôtir au four 20 minutes, en les retournant plusieurs fois, jusqu’à ce que les bords commencent à dorer.","Laissez refroidir les légumes 5 minutes. Ajoutez l’huile d’olive et le vinaigre balsamique, saupoudrez d’origan, assaisonnez de poivre noir et mélangez délicatement. Divisez les légumes en 2 portions égales.","Coupez chaque pain en longueur pour obtenir 3 tranches horizontales. Placez la moitié d’une portion de légumes sur la tranche du bas, puis garnissez de fromage de chèvre.","Ajoutez la tranche de pain du milieu, puis la deuxième couche de légumes, 1 tomate en rondelles et un peu de basilic, et terminez avec la dernière tranche de pain. Répétez avec le deuxième pain.","Enveloppez chaque pain bien serré dans du papier sulfurisé en tordant les extrémités, puis enveloppez-le bien serré dans du film alimentaire. Placez les pains au réfrigérateur, recouverts d’une assiette ou d’une plaque de four, et posez dessus des poids, par exemple des boîtes de haricots. Laissez au moins 2 heures, ou toute la nuit, pour que tous les jus imprègnent le pain."],
["Pour une version sans produits laitiers ou végétalienne, ajoutez du tahini et des tomates séchées à la place du fromage de chèvre.","Vous pouvez facilement multiplier la recette et utiliser un grand pain qui nourrira 8 personnes. Vous pouvez aussi réduire les quantités pour une seule portion dans un petit pain."]))
o.append(R(14,"Curry de légumes à la mode du Kerala","Aubergine, gombo et courge butternut avec des pois cassés dans une sauce crémeuse au yaourt et à la tomate.","4","583g",
["75g de pois cassés (secs)","500ml d’eau bouillante","2 c. à café d’huile de colza","2 oignons, hachés (220g)","2 gousses d’ail, écrasées","1/2 courge butternut, pelée, épépinée et coupée en cubes (400g)","1 c. à soupe de pâte de curry","1 boîte de 400g de tomates concassées","200ml d’eau bouillante","1 aubergine, coupée en dés (250g)","1 paquet de gombos, queues retirées (175g)","1 sachet (200g) d’épinards frais","25g de coriandre fraîche, hachée","2 c. à soupe de yaourt à 0 % de matières grasses","80g de graines de grenade","80g de concombre, coupé en dés","2 oignons nouveaux, hachés","1 petit piment rouge, haché"],
["Rincez les pois cassés et placez-les dans une casserole avec de l’eau bouillante pour les couvrir entièrement. Laissez mijoter 40 minutes, puis égouttez.","Pendant ce temps, versez l’huile dans une casserole avec l’oignon et faites cuire 3 à 4 minutes.","Ajoutez l’ail, la courge butternut et la pâte de curry, puis faites cuire 2 minutes en remuant régulièrement.","Ajoutez les tomates et l’eau, mélangez bien, puis portez à ébullition. Baissez le feu, couvrez, puis laissez mijoter 10 minutes.","Ajoutez l’aubergine, couvrez et faites cuire 5 minutes.","Ajoutez ensuite le gombo, mélangez bien, couvrez et faites cuire encore 5 minutes, puis ajoutez les épinards et mélangez de nouveau. Couvrez et faites cuire 2 à 3 minutes de plus.","Vérifiez que les pois cassés sont tendres, puis égouttez-les et ajoutez-les dans la casserole avec la coriandre et le yaourt. Mélangez bien et servez parsemé de grenade, de concombre, d’oignon nouveau et de piment."],
["Essayez d’utiliser d’autres légumes comme des carottes, des courgettes, des champignons, des poivrons et n’importe quel type de courge.","Pour une version végétalienne, utilisez un yaourt non laitier ou une alternative à la crème à base d’avoine à la place du yaourt.","Instructions de congélation : Peut être congelé une fois cuit, sans les garnitures. Décongelez au réfrigérateur et réchauffez jusqu’à ce que ce soit bien chaud à cœur."]))
save(1,o)
