from lib import *
o=[]
o.append(R(30,"Aubergines farcies au tofu, aux champignons et aux haricots borlotti","Des aubergines cuites au four avec des tomates aux herbes, des haricots et des légumes, garnies de tofu pour en faire un plat principal rassasiant.","4","351g",
["2 aubergines, coupées en deux dans la longueur (500g)","1 c. à café d’huile de colza","1 oignon, finement haché (120g)","320g de champignons, émincés","2 gousses d’ail, écrasées","1 boîte de 400g de tomates concassées","1 c. à café bombée d’origan séché","1 boîte de 400g de haricots borlotti, égouttés (240g)","1 sachet de 80g d’épinards frais","1 paquet de 360g de tofu, coupé en petits dés","1/2 boule de mozzarella allégée en matière grasse (62g), finement tranchée","1 tomate fraîche (80g), coupée en petits morceaux","2 oignons nouveaux (50g), hachés","8 feuilles de basilic frais, déchirées"],
["Préchauffez le four à 180°C / thermostat 4.","Retirez la chair des aubergines à la cuillère, hachez-la et réservez. Placez les aubergines côté peau vers le bas sur une plaque de cuisson et faites cuire 15 minutes.","Pendant ce temps, versez l’huile dans une casserole, puis ajoutez l’oignon et faites cuire 3 à 4 minutes. Ajoutez les champignons et la chair d’aubergine hachée, puis faites cuire encore 5 minutes.","Ajoutez l’ail, les tomates en conserve et l’origan, mélangez bien, couvrez et laissez mijoter 5 minutes. Ajoutez ensuite les haricots borlotti et les épinards et faites cuire 2 minutes.","Sortez les aubergines du four et remplissez-les avec le mélange de haricots et de légumes, puis placez-les dans un plat allant au four.","Parsemez de tofu, remettez au four et faites cuire 20 minutes. Garnissez de mozzarella tranchée et faites cuire encore 20 minutes.","Sortez du four et parsemez de tomate hachée, d’oignon nouveau et de basilic pour servir."],
["Une fois les aubergines farcies, vous pouvez les placer au réfrigérateur et les faire cuire au moment voulu.","Utilisez une alternative au fromage non laitière pour une version végétalienne."]))
o.append(R(31,"Yeux d’ogre","Ces mini boulettes de viande font peur à voir mais sont délicieuses !","20","54g",
["1 tranche de pain complet","2 c. à soupe de lait écrémé","1 œuf, battu","500g de viande hachée de blanc de dinde","2 gousses d’ail, écrasées","1 oignon moyen, râpé","1 poivron rouge, très finement haché","1 c. à café d’origan","spray d’huile","1 bonne pincée de poivre","2 à 3 fines tranches de poivron rouge","5 à 6 olives noires dénoyautées","100g de mozzarella allégée, coupée en 20 petits disques","20 piques à cocktail"],
["Placez le pain dans un petit bol et versez dessus le lait et l’œuf. Laissez tremper 5 minutes, puis écrasez à la fourchette.","Pendant ce temps, mélangez la viande hachée, l’ail, l’oignon, le poivron rouge, l’origan et le poivre et mélangez bien. Incorporez le mélange d’œuf et de pain.","Mouillez-vous les mains, formez 20 portions et roulez-les en petites boulettes (il vaut mieux utiliser les mains pour cela).","Placez sur une plaque de cuisson légèrement huilée et mettez sous un gril chaud 10 à 12 minutes, en retournant de temps en temps, jusqu’à ce qu’elles soient dorées de toutes parts et bien cuites. Laissez refroidir un peu.","Glissez une tranche de poivron rouge dans chaque olive, puis coupez délicatement et placez un disque de mozzarella dessus.","Placez la tranche de mozzarella sous l’olive et fixez avec une pique à cocktail."],
["Vous pouvez utiliser de la viande hachée de porc, de bœuf ou d’agneau pour les boulettes. Ou vous pouvez utiliser du poisson haché, comme du cabillaud."]))
o.append(R(32,"Tartine d’avocat, banane et noix de cajou","Une garniture de tartine très facile, nutritive et simple à préparer avec les enfants.","4","110g",
["75g de noix de cajou","4 tranches de pain complet","1 gros avocat","1 grosse banane"],
["Mettez les noix dans un sac refermable et écrasez-les avec un rouleau à pâtisserie.","Faites griller le pain.","Retirez le noyau et la peau de l’avocat, puis pelez la banane. Placez les deux dans un bol.","À l’aide du dos d’une fourchette, écrasez ensemble la banane et l’avocat en purée, puis incorporez les noix, en en réservant quelques-unes pour saupoudrer le dessus.","Étalez le mélange sur les toasts et saupoudrez de quelques noix. Ou coupez le pain grillé en mouillettes et trempez-les."],
["Vous pouvez utiliser du pain sans gluten ou tremper à la place des bâtonnets de carotte, de céleri ou de poivron.","Essayez d’utiliser d’autres noix comme des amandes ou des noix de Grenoble, ou un mélange de graines de tournesol et de courge."]))
o.append(R(33,"Soupe de panais et de pommes","Une soupe d’hiver réconfortante qui peut être servie comme repas léger ou comme délicieuse entrée de fête.","2","376g",
["1 c. à café d’huile","1 petit oignon, haché","1/2 c. à café de graines de cumin","300g de panais, pelés et hachés","1 petite pomme à cuire, pelée et hachée","600ml de bouillon de légumes","poivre noir fraîchement moulu","1 petit panais","2 c. à café d’huile"],
["Faites chauffer l’huile dans une casserole, ajoutez l’oignon et les graines de cumin et faites revenir 2 à 3 minutes.","Ajoutez les panais et la pomme et continuez à faire revenir 3 minutes.","Ajoutez le bouillon, portez à ébullition et laissez mijoter 20 à 25 minutes, jusqu’à ce que les panais soient tendres.","Transférez dans un blender ou un robot de cuisine et mixez jusqu’à obtenir une texture lisse. Rectifiez l’assaisonnement.","Pour préparer les chips de panais, pelez le panais puis coupez-le en chips très fines à l’aide d’un éplucheur. Faites chauffer l’huile dans une petite poêle et faites frire les lanières de panais jusqu’à ce qu’elles soient croustillantes et dorées, puis égouttez-les sur du papier absorbant.","Garnissez la soupe de chips de panais et servez."],
["Relevez la soupe avec 1 c. à café de pâte de curry.","Instructions de congélation : Congelez par portions, puis décongelez au réfrigérateur, ou au micro-ondes en remuant régulièrement."]))
o.append(R(34,"Filet d’agneau et pilaf de lentilles épicé","Agneau maigre grillé avec un pistou aux herbes, des lentilles, des haricots et des légumes.","4","324g",
["250g de filet de collier d’agneau","1 c. à café d’origan séché","un bon tour de moulin à poivre noir","25g de basilic frais, grossièrement haché","50g de persil frais, grossièrement haché","2 gousses d’ail, écrasées","le jus et le zeste râpé de 1/2 citron","1 c. à soupe d’huile d’olive extra vierge","1 c. à soupe d’eau","2 c. à café d’huile de colza","1 poivron rouge, coupé en dés","1 poivron jaune, coupé en dés","1 courgette, coupée en dés","1 botte d’oignons nouveaux, hachés","1 boîte de 400g de lentilles vertes, égouttées et rincées","1 boîte de 400g de haricots flageolets ou cannellini, égouttés et rincés","1 c. à café de moutarde de Dijon","1 cube de bouillon de légumes pauvre en sel dans 150ml d’eau bouillante"],
["Préchauffez le four à 190°C / thermostat 5. Placez l’agneau dans une poêle antiadhésive et faites cuire 4 à 5 minutes, en le retournant régulièrement pour le saisir de tous les côtés.","Préparez le pistou en mixant tous les ingrédients ensemble pour obtenir une pâte, puis réservez.","Versez l’huile de colza dans une casserole avec les poivrons rouge et jaune et la courgette. Faites cuire 5 à 6 minutes en remuant régulièrement.","Ajoutez les oignons nouveaux, les lentilles, les haricots et la moutarde, puis mélangez bien. Ajoutez le bouillon, couvrez la casserole, baissez le feu et laissez mijoter doucement 10 minutes, en remuant de temps en temps.","Pendant ce temps, saupoudrez l’agneau d’origan et de poivre noir, placez-le sur une plaque de cuisson et faites cuire 5 à 7 minutes pour une cuisson rosée ou 10 à 12 minutes pour bien cuit. Sortez du four et laissez reposer 5 minutes avant de trancher finement.","Dressez les lentilles dans les assiettes, disposez l’agneau tranché dessus, puis arrosez de pistou."],
["Vous pouvez utiliser du filet mignon de porc ou du blanc de poulet à la place de l’agneau, mais il faudra 10 minutes de cuisson supplémentaires au four. Vérifiez que la viande est cuite à cœur et qu’aucune chair rose n’est visible avant de servir.","Instructions de congélation : Peut être congelé une fois cuit. Pour de meilleurs résultats, congelez séparément le pilaf, le pistou et l’agneau. Décongelez au réfrigérateur ou au micro-ondes et réchauffez le pilaf et l’agneau jusqu’à ce qu’ils soient bien chauds à cœur."]))
o.append(R(35,"Champignons farcis aux haricots de Lima, persil et thym","Des champignons cuits au four avec de l’ail, du persil et des haricots écrasés pour moderniser un grand classique.","18","43g",
["1 paquet de 500g de champignons (12 à 18, selon la taille)","1 c. à café d’huile de colza","4 gousses d’ail, écrasées","6 oignons nouveaux, finement hachés","1 boîte de 400g de haricots de Lima, égouttés et écrasés (235g)","15g de persil, finement haché","1 c. à café de moutarde à l’ancienne","1 c. à café de thym séché","1 bonne pincée de poivre","30g de cheddar, finement râpé"],
["Préchauffez le four à 180°C / thermostat 4. Tournez et retirez les pieds des champignons, hachez-les et réservez. Placez les champignons à l’endroit sur une petite plaque de cuisson et faites cuire 10 à 15 minutes.","Pendant ce temps, versez l’huile dans une casserole, ajoutez les pieds de champignons, l’ail et les oignons nouveaux et faites cuire 3 minutes.","Transférez le mélange dans un bol avec les haricots, le persil, la moutarde, le thym et le poivre et mélangez bien.","Garnissez les chapeaux de champignons à la cuillère, en appuyant dans les champignons et en façonnant avec les mains pour former un petit monticule. Saupoudrez de fromage et faites cuire 15 minutes, jusqu’à ce qu’ils soient légèrement ramollis et que le dessus soit doré. Servez tiède (en laissant refroidir un peu avant de servir) ou à température ambiante."],
["Vous pouvez ajouter d’autres herbes au mélange. N’importe quels haricots conviennent ; essayez les cannellini ou une boîte de haricots variés.","Vous pouvez farcir les champignons jusqu’à 1 jour à l’avance, puis les conserver au réfrigérateur jusqu’au moment de les faire cuire."]))
o.append(R(36,"Poulet façon pizza","Un délicieux dîner d’inspiration italienne, qui associe un blanc de poulet succulent au goût d’une pizza au fromage. Cette recette a été sélectionnée en partenariat avec Slimming World.","1","398g",
["1/2 petit oignon rouge, finement haché","1/2 poivron rouge, épépiné et haché","1 petite gousse d’ail, écrasée","Spray de cuisson faible en calories","2 tomates grappe, hachées","1 c. à soupe de tomates concassées en conserve","1 c. à café de concentré de tomate","1 c. à café d’origan séché","1 blanc de poulet sans peau ni os","40g de cheddar allégé en matière grasse, râpé","1 tomate cerise, coupée en deux","1 c. à café de basilic frais finement haché"],
["Mettez l’oignon, le poivron et l’ail dans une petite casserole antiadhésive. Vaporisez de quelques pressions de spray de cuisson faible en calories et faites cuire quelques minutes jusqu’à ce qu’ils ramollissent. Incorporez les tomates fraîches, les tomates en conserve, le concentré de tomate et l’origan et laissez mijoter 5 minutes. Réservez.","Préchauffez votre four à 220°C / chaleur tournante 200°C / thermostat 7.","Coupez le blanc de poulet en deux horizontalement, en prenant soin de ne pas le couper complètement. Ouvrez-le pour former un papillon.","Vaporisez une poêle antiadhésive de quelques pressions de spray de cuisson faible en calories et placez-la sur feu moyen. Ajoutez le poulet et faites cuire jusqu’à ce qu’il soit doré des deux côtés. Placez le poulet sur une plaque de cuisson antiadhésive et faites cuire 15 à 20 minutes ou jusqu’à ce qu’il soit bien cuit et qu’aucune chair rose ne soit visible (le jus doit être clair quand vous piquez une brochette dans la partie la plus épaisse du poulet).","Sortez le poulet du four et étalez dessus le mélange de tomates. Saupoudrez de fromage et placez la tomate cerise au-dessus. Faites cuire encore 5 minutes, jusqu’à ce que le fromage fonde.","Parsemez de basilic et servez chaud avec des quartiers de pommes de terre maison cuits au four avec la peau, et une grande salade verte croquante."],[]))
o.append(R(37,"Galettes aux poivrons et sauce tomate relevée","Les poivrons et les oignons donnent des galettes tout simplement délicieuses, encore meilleures avec ce condiment frais et piquant.","30","44g",
["2 c. à café d’huile de colza","1 poivron jaune, finement émincé en lanières de 2 à 3 cm","1 poivron rouge, finement émincé en lanières de 2 à 3 cm","1 oignon, finement haché","2 œufs, battus","200ml d’eau","2 c. à soupe de yaourt allégé en matière grasse","50g de cheddar râpé","150g de farine complète","1 bonne pincée de poivre","10g de persil frais","le jus et le zeste de 1 lime","4 grosses tomates grappe, finement hachées","1 à 2 petits piments rouges, finement hachés"],
["Versez 1 c. à café d’huile dans une casserole sur feu moyen, ajoutez les poivrons et l’oignon et faites cuire 10 minutes en remuant régulièrement.","Pendant ce temps, mélangez l’œuf, l’eau, le yaourt et le fromage. Incorporez la farine pour obtenir une pâte à crêpes.","Incorporez les poivrons et l’oignon à la pâte.","Versez le reste de l’huile dans une grande poêle antiadhésive. Déposez dans la poêle de petites cuillerées à dessert du mélange et faites frire 1 à 2 minutes, en retournant une fois à la spatule pour cuire l’autre côté encore 1 minute.","Pendant ce temps, préparez la sauce en mixant ensemble le persil, le jus de lime, le zeste et la tomate fraîche, puis incorporez le piment."],
["Lors de la cuisson des galettes, veillez à répartir uniformément les poivrons et l’oignon dans la pâte. Vous pouvez les préparer jusqu’à 1 jour à l’avance et les réchauffer au four quelques minutes pour servir."]))
o.append(R(38,"Salade niçoise au thon","Une recette française classique, qui fait un excellent déjeuner sain par une journée ensoleillée.","4","275g",
["450g de pommes de terre nouvelles, coupées en deux, ou en quatre pour les plus grosses","200g de haricots verts fins, équeutés","1 petite laitue pommée, feuilles séparées","2 boîtes de 160g de thon à l’eau de source, égoutté et émietté","8 olives Kalamata, dénoyautées et coupées en deux","1 c. à café de moutarde de Dijon","5 c. à café de vinaigre de cidre","1 c. à soupe d’huile d’olive extra vierge","1/2 c. à café de moutarde anglaise en poudre","1/2 petite gousse d’ail, écrasée","1/4 c. à café d’herbes de Provence"],
["Mettez les pommes de terre dans une grande casserole, couvrez d’eau froide et portez à ébullition. Baissez le feu à moyen et faites cuire 5 minutes. Ajoutez les haricots et faites cuire 4 minutes, jusqu’à ce que les pommes de terre soient tendres et que les haricots soient cuits mais encore fermes. Égouttez et transférez dans un grand saladier.","Pendant ce temps, mettez tous les ingrédients de la vinaigrette dans un bocal propre. Fermez avec un couvercle hermétique et secouez jusqu’à ce que le mélange soit homogène. Versez la moitié de la vinaigrette sur les pommes de terre et les haricots et mélangez. Ajoutez la laitue dans le saladier et mélangez de nouveau pour l’enrober.","Disposez la salade assaisonnée sur un plat de service ou dans un grand saladier, puis garnissez de thon, de câpres et d’olives. Arrosez avec le reste de la vinaigrette et servez."],
["Si vous n’avez pas de thon, vous pouvez le remplacer par n’importe quel poisson en conserve.","Vous pouvez remplacer les herbes de Provence par n’importe quelles herbes séchées.","Vous pouvez aussi utiliser des patates douces à la place des pommes de terre nouvelles."]))
o.append(R(39,"Smoothie pêche et framboise","Un smoothie aux fruits est l’accompagnement idéal d’un petit-déjeuner ou d’un déjeuner. Les enfants l’adorent aussi.","2","288g",
["1 boîte de 213g de pêches au jus, égouttées","150g de framboises fraîches ou surgelées","1 pot de 150g de yaourt nature","150ml de lait demi-écrémé"],
["Mixez ensemble tous les ingrédients et servez."],
["Pour une version sans produits laitiers, utilisez du lait de soja et une alternative au yaourt à base de soja.","Par temps vraiment chaud, ajoutez 8 à 10 glaçons avant de mixer pour obtenir un « granité » fruité."]))
o.append(R(40,"Beignets d’épinards, de maïs et de pois chiches","Un plat parfait pour le dîner. Se marie très bien avec du pain pita et beaucoup de salade.","4","164g",
["2 c. à café d’huile de colza","1 petit oignon, râpé","1 poivron rouge, finement haché","1 œuf, battu","150g d’épinards surgelés, décongelés, essorés et grossièrement hachés","1 c. à café de cumin","1 piment rouge, finement haché","80g de maïs surgelé, décongelé","1 boîte de 400g de pois chiches, égouttés et soigneusement écrasés","25g de farine de pois chiches","10g de coriandre fraîche, hachée","salade, pour servir"],
["Versez 1 c. à café d’huile dans une casserole, puis ajoutez l’oignon. Faites cuire 2 à 3 minutes, puis ajoutez le poivron rouge et faites revenir encore 4 à 5 minutes.","Pendant ce temps, mettez l’œuf, les épinards, le cumin, le piment et le maïs dans un bol et mélangez bien.","Incorporez l’oignon et le poivron rouge, puis ajoutez les pois chiches, la farine de pois chiches et la coriandre, et mélangez soigneusement. Avec les mains mouillées, façonnez la préparation en 8 galettes.","Versez le reste de l’huile dans une grande poêle antiadhésive sur feu moyen. Placez les beignets dans la poêle et aplatissez-les légèrement avec une spatule jusqu’à environ 1/2 à 1 cm d’épaisseur, pour assurer une cuisson uniforme.","Faites cuire les beignets 3 à 4 minutes, jusqu’à ce qu’ils soient légèrement dorés, puis retournez-les délicatement et faites cuire l’autre côté encore 3 à 4 minutes. Vous pouvez laisser cuire chaque côté 1 à 2 minutes de plus pour obtenir une belle croûte. Servez avec de la salade."],
["Les informations nutritionnelles ci-dessus n’incluent pas la salade ni le pain pita proposés comme suggestion de présentation.","Si vous n’avez pas de poêle assez grande, vous pouvez cuire les beignets en deux fois. Placez-les sur une assiette chaude et réservez jusqu’à ce qu’ils soient tous prêts.","Vous pouvez servir les beignets tièdes ou froids.","Si vous n’avez pas de farine de pois chiches, vous pouvez utiliser de la farine de blé ordinaire ou complète à la place.","Instructions de congélation : Congelez en portions emballées individuellement avec du papier sulfurisé entre chaque beignet. Décongelez complètement et réchauffez jusqu’à ce que ce soit bien chaud à cœur."]))
o.append(R(41,"Petites tartelettes au crabe","Ces savoureuses bouchées sont idéales en amuse-gueule pour l’apéritif.","36","12g",
["36 petits fonds de pâte (mini croustades)","1 œuf, battu","4 c. à soupe de crème fraîche demi-écrémée","1 c. à soupe de ciboulette fraîche, ciselée","1 pincée de paprika","1 c. à soupe de parmesan finement râpé","225g de chair de crabe blanche fraîche","poivre noir fraîchement moulu"],
["Préchauffez le four à 200ºC / thermostat 6.","Placez les fonds de pâte sur une plaque de cuisson. Battez ensemble tous les autres ingrédients et utilisez-les pour garnir les fonds de pâte.","Faites cuire environ 15 minutes, jusqu’à ce que la garniture soit juste prise et commence à dorer. Laissez refroidir un peu et servez."],
["Elles sont à consommer (ou à congeler) de préférence le jour même pour éviter que la pâte ne ramollisse.","Pour une option végétarienne, remplacez le crabe par le même poids d’oignons ou de champignons sautés finement tranchés.","Si vous ne trouvez pas de fonds de pâte de la taille d’une bouchée, garnissez de mini moules à tartelettes avec de la pâte brisée ou de la pâte filo (200g) étalée très finement."]))
o.append(R(42,"Esquimaux crémeux myrtille et avocat","Ces délicieux « esquimaux crémeux » sont préparés avec un smoothie épais que vous congelez. Vous pouvez les varier en ajoutant vos fruits ou baies préférés.","10","78g",
["2 petits avocats (200g), noyaux retirés et chair prélevée à la cuillère","200g de myrtilles surgelées","10 dattes molles, dénoyautées","250ml de lait écrémé (ou du lait de votre choix)","2 c. à soupe de jus de lime"],
["Mettez tous les ingrédients dans un blender et mixez jusqu’à obtenir une texture parfaitement lisse.","Répartissez le smoothie dans 10 moules à glaces. Couvrez avec le couvercle, insérez les bâtonnets et placez au congélateur pendant 8 heures, ou jusqu’à ce que ce soit congelé.","Dégustez immédiatement ou conservez au congélateur pour plus tard."],
["Si vous voulez ajouter encore plus de bienfaits nutritionnels à ces gourmandises, ajoutez deux bouquets de chou-fleur surgelé cuit à la vapeur au mélange avant de mixer."]))
o.append(R(43,"Légumes rôtis fumés et yaourt au sésame","Utilisez les légumes restants pour préparer ce plat d’inspiration moyen-orientale – il comblera à coup sûr vos papilles.","3","324g",
["1 carotte, coupée en morceaux","200g de topinambours, coupés en morceaux","1 patate douce, coupée en morceaux","2 oignons rouges, coupés en quatre","2 poivrons – rouge et vert, coupés en quatre","1 c. à soupe d’huile d’olive","2 c. à café bombées de paprika fumé doux (dulce)","2 c. à café de tahini","4 c. à soupe de yaourt grec à 0 % de matières grasses"],
["Mettez la carotte, les topinambours, la patate douce, les oignons et les poivrons dans un grand bol avec l’huile et mélangez bien.","Ajoutez le paprika et mélangez de nouveau, pour que tous les légumes soient enrobés.","Étalez sur une plaque de cuisson légèrement huilée et faites cuire dans un four préchauffé à 180°C / thermostat 4 pendant 35 à 45 minutes, en retournant de temps en temps.","Pendant ce temps, mélangez le tahini avec le yaourt et réservez jusqu’à ce que les légumes soient prêts."],
["Utilisez une alternative végétale au yaourt pour rendre ce plat végétalien.","Servez avec des pois chiches et du pain pita complet ou du riz pour en faire un repas complet."]))
o.append(R(44,"Tajine de légumes et de pois chiches","Ce plat savoureux et pauvre en matières grasses est plein de saveurs d’Afrique du Nord.","4","339g",
["1 c. à soupe d’huile","2 gousses d’ail, écrasées","1/4 c. à café de cumin moulu","1/4 c. à café de gingembre moulu","1/2 c. à café de piment en poudre","450g de légumes variés coupés en morceaux de la taille d’une bouchée – une grosse courgette, deux carottes moyennes et une aubergine moyenne","100ml de bouillon de légumes pauvre en sel","1 boîte de 400g de pois chiches, égouttés et rincés","100g (environ 12) d’abricots secs","1 boîte de 400g de tomates concassées","1 c. à café de pâte de harissa","2 c. à soupe de coriandre fraîche, hachée, pour décorer","poivre noir fraîchement moulu"],
["Faites chauffer l’huile dans une poêle antiadhésive. Ajoutez l’ail, le cumin, le gingembre et le piment en poudre, faites revenir 2 minutes jusqu’à ce que les épices soient parfumées.","Ajoutez les légumes dans la poêle et continuez à faire revenir 2 à 3 minutes.","Versez le bouillon et ajoutez les pois chiches, les abricots et les tomates, portez à ébullition et laissez mijoter 10 à 12 minutes, jusqu’à ce que les légumes soient tout juste tendres.","Incorporez la pâte de harissa et assaisonnez généreusement de poivre noir.","Servez les légumes sur de la semoule de couscous fraîchement préparée, parsemez de coriandre et servez."],
["Servez avec du couscous, du riz ou du pain plat et beaucoup de salade.","Si vous n’avez pas de pâte de harissa, vous pouvez utiliser un peu plus de piment et/ou d’ail, plus 1/2 c. à café de menthe séchée et un bon filet de citron.","À la place des abricots, vous pouvez utiliser des raisins secs ou des raisins de Smyrne.","Instructions de congélation : Peut être congelé une fois cuit. Décongelez au réfrigérateur ou au micro-ondes et réchauffez soigneusement jusqu’à ce que ce soit bien chaud à cœur."]))
save(3,o)
