from lib import *
o=[]
o.append(R(45,"Biryani d’agneau","Un excellent plat asiatique, idéal pour recevoir et pour les grandes occasions.","6","394g",
["1 c. à soupe d’huile","4 oignons, émincés","750g de gigot d’agneau désossé, coupé en cubes","4 gousses d’ail, écrasées","1,5 c. à café de gingembre frais, pelé et râpé","1 bâton de cannelle","3 gousses de cardamome","8 clous de girofle","8 grains de poivre noir","1 c. à soupe de piment en poudre","1 c. à soupe de coriandre moulue","1 pot de 150g de yaourt nature allégé en matière grasse","1/2 c. à café de safran, trempé dans 3 c. à soupe d’eau bouillante","450g de riz basmati, cuit selon les instructions de l’emballage"],
["Faites chauffer l’huile dans une grande casserole, ajoutez l’oignon et faites revenir 3 à 4 minutes jusqu’à ce qu’il soit légèrement doré. Retirez 1/4 de l’oignon et réservez.","Ajoutez l’agneau, l’ail, le gingembre, le bâton de cannelle, la cardamome, les clous de girofle et les grains de poivre dans la casserole et faites revenir 8 à 10 minutes, jusqu’à ce que l’agneau soit légèrement doré de tous les côtés.","Délayez le piment en poudre et la coriandre moulue dans 2 c. à soupe d’eau bouillante, puis versez dans la casserole. Couvrez la casserole et faites cuire la viande à feu doux. Faites cuire 40 à 45 minutes jusqu’à ce que la viande soit tendre.","Préchauffez le four à 150ºC / thermostat 2. Ajoutez le yaourt dans la casserole et mélangez. Pendant ce temps, placez l’oignon réservé dans une poêle et continuez à le faire revenir 5 à 6 minutes jusqu’à ce qu’il soit brun foncé.","Placez 1/3 du riz au fond d’une cocotte épaisse, arrosez d’un peu du mélange de safran. Étalez dessus la moitié du mélange de viande et recouvrez d’un autre 1/3 du riz, puis parsemez d’un peu de mélange de safran. Répétez l’opération en terminant par une couche de riz et en arrosant de safran. Tassez légèrement. Placez l’oignon dessus.","Couvrez la cocotte avec un couvercle bien ajusté et faites cuire 10 minutes. Sortez du four, parsemez de coriandre fraîche et servez."],
["Vous pouvez utiliser du poulet ou du porc pour ce plat.","Pour une version végétarienne, ajoutez une sélection de légumes hachés comme des poivrons, des aubergines et des champignons à la place de l’agneau. Ils n’auront besoin que de 5 minutes de cuisson avant d’être ajoutés au riz.","Instructions de congélation : Peut être congelé une fois cuit. Refroidissez rapidement. Décongelez au réfrigérateur et réchauffez soigneusement jusqu’à ce que ce soit bien chaud à cœur. Consommez immédiatement et jetez les restes."]))
o.append(R(46,"Smoothie pomme et muesli","Une alternative amusante et rassasiante aux céréales du petit-déjeuner, pleine de bienfaits.","1","345g",
["1 pomme, pelée, évidée et hachée (100g)","20g de muesli sans sucre ajouté","125g de yaourt grec nature","100ml de lait demi-écrémé"],
["Placez simplement tous les ingrédients dans un robot de cuisine ou un blender et mixez jusqu’à obtenir une texture lisse.","Servez immédiatement."],
["Laissez tremper votre muesli toute la nuit, puis ajoutez le yaourt et la pomme avant de mixer.","Ce smoothie est aussi très savoureux avec de la poire à la place de la pomme."]))
o.append(R(47,"Polenta aux légumes rôtis","Un plat réconfortant parfait pour toute la famille.","4","405g",
["2 c. à soupe d’huile d’olive","2 oignons rouges, pelés et coupés en quartiers","1 poivron rouge, 1 jaune et 1 vert, épépinés et coupés chacun en 8 quartiers","2 courgettes, coupées en quatre dans la longueur, puis en tronçons de 4cm","800ml d’eau bouillante","200g de polenta","400g de tomates cerises en conserve","2 à 3 gousses d’ail, écrasées","1 c. à café bombée d’origan séché","1 pincée de flocons de piment","1 poignée de feuilles de basilic frais, pour servir"],
["Préchauffez le four à 200°C / thermostat 6. Mettez 1,5 c. à soupe d’huile d’olive dans un bol avec les oignons, les poivrons et les courgettes. Mélangez bien, étalez sur une plaque de cuisson et faites rôtir 25 à 30 minutes.","Pendant ce temps, versez l’eau bouillante dans une grande casserole et incorporez progressivement la polenta en remuant avec une cuillère en bois pendant environ 5 minutes. Transférez ensuite dans un moule à cake de 900g légèrement huilé (environ 22cm x 11cm) et lissez le dessus avec le dos d’une cuillère. Laissez reposer 5 minutes.","Mettez les tomates en conserve, l’ail, l’origan et les flocons de piment dans une casserole, mélangez et laissez mijoter doucement 5 minutes.","Démoulez la polenta sur une planche à découper et coupez-la en tranches de 1,5 cm d’épaisseur, puis faites-les cuire sur une poêle-gril chaude ou sous le gril pendant environ 3 à 4 minutes de chaque côté, jusqu’à ce qu’elles soient légèrement dorées.","Pour servir, nappez une tranche de polenta d’une cuillerée de sauce tomate aux herbes, parsemez de quelques légumes rôtis et terminez avec quelques feuilles de basilic frais. Ajoutez une petite poignée de fromage râpé, si vous le souhaitez."],
["Utilisez les légumes de votre choix pour créer une variante de ce plat. Les aubergines et les champignons conviennent bien.","Instructions de congélation : Congelez la polenta et les légumes séparément. Décongelez ensuite au réfrigérateur ou au micro-ondes et réchauffez jusqu’à ce que ce soit bien chaud à cœur."]))
o.append(R(48,"Écorce de yaourt glacé","Savourez une gourmandise de saison, parsemée de fruits rouges d’été. Cette recette a été sélectionnée en partenariat avec Slimming World.","4","100g",
["250g de yaourt nature sans matières grasses et non sucré","150g de fraises, framboises et myrtilles fraîches, fraises équeutées et coupées en tranches"],
["Tapissez une grande plaque de cuisson de papier sulfurisé. Déposez le yaourt par cuillerées sur le papier sulfurisé, puis utilisez une spatule ou une cuillère pour l’étaler uniformément, jusqu’à environ 1 cm d’épaisseur.","Parsemez uniformément de fruits rouges, puis congelez au moins 3 heures, ou jusqu’à ce que l’écorce soit complètement solide.","Quand l’écorce est prête à être dégustée, laissez-la reposer 5 minutes à température ambiante pour qu’elle ramollisse légèrement, puis cassez-la en morceaux pour servir."],[]))
o.append(R(49,"Ketchup de tomate","Un délicieux ketchup maison et sain. Absolument parfait avec presque tout.","4","55g",
["1/2 petit oignon, pelé et très finement haché","1 gousse d’ail, pelée et finement hachée","200g de tomates concassées en conserve","2 c. à café de concentré de tomate","2 c. à soupe de vinaigre de cidre","1/2 c. à café d’édulcorant"],
["Placez tous les ingrédients dans une petite casserole.","Laissez mijoter 5 à 6 minutes, jusqu’à ce que le mélange ait légèrement réduit.","Mixez en purée et laissez refroidir."],[]))
o.append(R(50,"Blinis au saumon poché","Un excellent plat de fête que vous pouvez préparer en moins d’une demi-heure.","16","34g",
["2 pavés de saumon (125g chacun)","100g de cresson","1 c. à soupe de yaourt allégé en matière grasse","le jus et le zeste de 1 citron","1 paquet de 16 blinis (environ 160g)","1 c. à soupe de fromage frais à 50 % de matières grasses en moins","cresson ou feuilles de salade, plus brins d’aneth frais et quartiers de citron, pour la décoration"],
["Mettez les pavés de saumon dans une petite casserole, couvrez d’eau bouillante et laissez mijoter doucement 5 minutes avec un couvercle. Éteignez le feu, laissez reposer 3 minutes, ou jusqu’à ce que le saumon soit bien cuit à cœur, puis égouttez et laissez refroidir.","Une fois le saumon refroidi, retirez la peau et la graisse brune du poisson.","Pour la sauce, hachez grossièrement le cresson et mixez-le avec le yaourt, le zeste de citron et la moitié du jus de citron.","Réchauffez les blinis dans une poêle sèche 1 à 2 minutes de chaque côté.","Étalez un peu de fromage frais sur chaque blini et émiettez le saumon dessus. Arrosez du reste de jus de citron et garnissez de petites noix de sauce au cresson."],
["Pour gagner du temps, vous pouvez cuire le saumon la veille et le réfrigérer pendant la nuit, prêt pour le montage de vos blinis le lendemain.","Variez un peu en servant aussi une série de blinis garnis de crevettes ou de hareng et d’un peu de fromage frais allégé en matière grasse.","Décorez d’un peu de zeste de citron avant de servir."]))
o.append(R(51,"Panais et carottes rôtis au miel","Un accompagnement savoureux pour tout repas de viande rôtie.","4","200g",
["3 panais (450g)","4 grosses carottes (500g)","2 c. à café de miel","1 c. à café d’huile de colza","2 c. à café de tamari à teneur réduite en sel (sauce soja japonaise)","4 brins de thym frais, feuilles effeuillées","1 c. à café d’origan séché","1/2 c. à café d’estragon séché","1 c. à café de persil séché","50g de pistaches, grossièrement hachées","Le jus de 1 citron"],
["Coupez chaque panais et chaque carotte en deux dans la longueur, puis en quatre. Faites cuire dans de l’eau bouillante 5 minutes. Égouttez, rincez à l’eau froide et laissez refroidir.","Mélangez dans un bol le miel, l’huile, le tamari et les herbes. Ajoutez les panais et les carottes. Laissez mariner au réfrigérateur au moins 30 minutes.","Préchauffez le four à 200°C / chaleur tournante 180°C / thermostat 6. Tapissez une plaque de cuisson de papier sulfurisé.","Versez les panais et les carottes, avec leur marinade, sur la plaque préparée et faites rôtir 20 à 25 minutes, jusqu’à ce qu’ils soient dorés. Transférez les légumes rôtis sur un plat. Parsemez de pistaches et arrosez de jus de citron."],
["Le navet ou les patates douces feraient un parfait substitut aux panais ou aux carottes dans cette recette.","Extrait de Detox Kitchen Vegetables de Lily Simpson. Photographies © Issy Croker"]))
o.append(R(52,"Shrikhand de Rekha","Il s’agit d’un dessert traditionnel gujarati à base de yaourt sucré. Essayez une petite quantité de différentes noix et graines grillées pour encore plus de saveur. Vous pouvez aussi garnir avec une variété de fruits.","6","93g",
["500g de yaourt ferme nature à 0 % de matières grasses","2 c. à café d’édulcorant sans sucre","5 pistaches","5 amandes","5 cardamomes, moulues","10 filaments de safran","1 c. à soupe de lait écrémé"],
["Placez des feuilles de papier journal sur un plateau. Placez dessus un torchon propre.","Versez le yaourt sur le torchon et laissez égoutter toute l’eau du yaourt pendant 3 à 4 minutes. Une fois égoutté, mettez le yaourt dans le grand bol, ajoutez l’édulcorant et fouettez soigneusement 2 à 3 minutes. Il doit être épais et crémeux.","Faites bouillir 1/2 de la quantité de filaments de safran et 1/2 de la quantité de cardamomes moulues dans une petite casserole avec le lait. Laissez refroidir complètement. Une fois froid, ajoutez au mélange de yaourt.","Fouettez de nouveau énergiquement. Émincez très finement les pistaches et les amandes. Ajoutez 1/2 de la quantité au mélange de yaourt. Transférez dans le plat de service. Décorez en saupoudrant du reste des filaments de safran, des noix finement émincées et des cardamomes. Réfrigérez de 2 à 24 heures pour de meilleurs résultats."],[]))
o.append(R(53,"Tartelettes florentines aux œufs","Parfaites pour un déjeuner dominical avec une salade verte croquante.","12","65g",
["100g d’épinards cuits et égouttés (ou 100g d’épinards surgelés, décongelés et essorés)","60g de fromage frais léger (nature ou à l’ail et aux fines herbes, si vous préférez)","1 bonne pincée de noix de muscade","1 œuf de poule","1 bonne pincée de poivre fraîchement moulu","1 c. à soupe bombée (15g) de parmesan finement râpé","4 feuilles de pâte filo","2 c. à soupe d’huile de tournesol","12 œufs de caille"],
["Préchauffez le four à 180°C / thermostat 4. Mélangez dans un bol les épinards, le fromage frais, la noix de muscade, l’œuf de poule, le poivre et le parmesan, puis réservez.","Versez l’huile dans un ramequin ou une tasse, déroulez une feuille de pâte filo sur un plan de travail et, à l’aide d’un pinceau de cuisine, badigeonnez-la légèrement d’huile. Placez une autre feuille par-dessus la première et badigeonnez-la aussi d’un peu d’huile.","Coupez les feuilles en 6 rectangles et placez-les dans des moules à muffins peu profonds, en froissant légèrement les bords et en pressant dans les moules. Répétez avec 2 autres feuilles de filo, de façon à obtenir 12 fonds de pâte. Placez au four et faites cuire 2 minutes, puis sortez.","Répartissez le mélange d’épinards dans les 12 fonds et faites un creux au milieu de chacun, en repoussant les épinards sur les côtés.","Cassez chaque œuf de caille dans une tasse ou un ramequin et vérifiez qu’il n’y a pas de coquille, puis versez dans le creux des épinards.","Faites cuire 8 à 10 minutes jusqu’à ce que l’œuf prenne, puis sortez du four et servez. (L’œuf continuera à cuire une minute ou deux après la sortie du four, veillez donc à ne pas trop le cuire si vous souhaitez un jaune coulant."],
["Si vous n’avez pas de moules à muffins, vous pouvez préparer une grande tarte en façonnant 3 feuilles de filo huilées sur une plaque de cuisson, en froissant les bords pour créer une croûte de 1cm, puis en ajoutant la garniture au centre.","Elles conviennent très bien en entrée, pour un déjeuner léger, pour un brunch ou comme canapés consistants.","Les groupes « à risque » tels que les nourrissons, les enfants, les femmes enceintes, les personnes âgées et les personnes malades doivent éviter les œufs crus ou peu cuits, y compris les œufs de caille, à moins d’être certains qu’ils proviennent d’une source garantie sûre."]))
o.append(R(54,"Poulet du Sichuan","Des morceaux de poulet tendre enrobés d’une sauce parfumée au poivre du Sichuan aux agrumes et au gingembre, avec des oignons nouveaux et des graines de sésame.","3","123g",
["1 c. à café de poivre du Sichuan","le jus de 1/2 citron","2 c. à café d’huile de colza","350g de blanc de poulet, coupé en lanières","1 petit piment rouge, coupé en rondelles","4cm de gingembre frais, finement haché","2 gousses d’ail, émincées","3 oignons nouveaux, coupés en morceaux","1 c. à café bombée de poudre de cinq-épices chinoises","20g de graines de sésame","1 c. à soupe de concentré de tomate"],
["Mettez le poivre dans une tasse avec le jus de citron et réservez.","Faites chauffer l’huile dans un wok ou une poêle et ajoutez le poulet, en remuant constamment pendant 3 à 4 minutes pour le dorer légèrement à l’extérieur.","Ajoutez le piment, le gingembre et l’ail et mélangez bien 2 minutes.","Ajoutez l’oignon nouveau, la poudre de cinq-épices, les graines de sésame et le concentré de tomate. Mélangez bien et faites cuire encore 2 minutes. Ajoutez 1 à 2 c. à soupe d’eau, retirez du feu et mélangez pour que le poulet soit bien enrobé.","Placez dans un plat de service et saupoudrez du mélange de poivre et de jus de citron."],
["Convient très bien avec des lanières de dinde, de bœuf ou de porc, ou avec des crevettes ou des morceaux de saumon.","Pour une version végétalienne, utilisez du tofu à la place du poulet.","Instructions de congélation : Peut être congelé une fois cuit. Décongelez au réfrigérateur ou au micro-ondes et réchauffez soigneusement jusqu’à ce que ce soit bien chaud à cœur."]))
o.append(R(55,"Poulet rôti","Une façon simple de rôtir un poulet, parfaite à partager.","8","181g",
["1 poulet entier de 2kg","1 citron, coupé en deux","1 bonne poignée d’herbes fraîches (le romarin et le thym sont idéaux)","poivre noir fraîchement moulu","300ml d’eau bouillante"],
["Préchauffez le four à 180°C / thermostat 4.","Placez le poulet sur une grille posée sur un plat à rôtir. Pressez le citron sur le poulet et placez les moitiés de citron pressées dans la cavité du poulet.","Placez une partie des herbes sur le poulet et le reste des herbes dans la cavité. Assaisonnez de poivre noir.","Versez l’eau dans le plat à rôtir, puis placez au four et faites cuire 45 minutes par kilo, plus 20 minutes (1 heure 50 pour un poulet de 2kg), en ajoutant de l’eau si nécessaire.","Sortez du four, couvrez de papier d’aluminium et laissez reposer 15 minutes.","Retirez la peau, découpez et servez avec beaucoup de légumes et de pommes de terre."],
["Pour vérifier si le poulet est cuit, piquez la peau entre la cuisse et le blanc – le jus doit être clair.","Si vous utilisez le jus de cuisson pour préparer une sauce, versez-le dans une carafe et laissez reposer quelques minutes. La graisse remontera à la surface et pourra être retirée à la cuillère avant de préparer la sauce.","Instructions de congélation : Peut être congelé une fois cuit. Pour plus de commodité, vous pouvez congeler ce plat en portions, puis le décongeler au réfrigérateur ou au micro-ondes et le réchauffer soigneusement jusqu’à ce qu’il soit bien chaud à cœur."]))
o.append(R(56,"Pop-corn salé","Relevez votre pop-corn pour une délicieuse collation que les enfants adorent préparer et que tout le monde adore manger ! Beaucoup moins salé que le pop-corn du commerce.","6","22g",
["60g de maïs à éclater (divisé en deux portions de 30g)","1 c. à café d’huile de colza, 1 à 2 gousses d’ail, écrasées","1 c. à café d’origan frais haché (ou 1/2 c. à café d’origan séché)","un bon tour de moulin à poivre","10g de parmesan, très finement râpé","1 c. à café d’huile de colza","1/2 piment rouge, très finement haché","le jus et le zeste finement râpé de 1 citron","1 c. à café de thym frais haché (ou 1/2 c. à café de thym séché)"],
["Faites chauffer une grande casserole profonde avec un couvercle, versez-y le maïs à éclater et couvrez. Secouez régulièrement la casserole et après 2 à 3 minutes vous entendrez le maïs commencer à éclater – ne soyez pas tenté d’ouvrir le couvercle. Continuez à secouer jusqu’à ce que les éclatements cessent.","Mettez le pop-corn dans un grand bol et jetez les grains qui n’ont pas éclaté. Répétez jusqu’à ce que tout votre maïs soit prêt, puis divisez en deux.","Pendant ce temps, préparez vos assaisonnements. Pour le pop-corn au fromage et à l’ail, mettez l’huile dans une casserole avec l’ail, l’origan et le poivre. Faites cuire doucement 1 minute sans faire dorer l’ail. Ajoutez la moitié du pop-corn et le parmesan finement râpé. Mélangez bien et servez.","Pour le pop-corn au piment et au citron, mettez 1 c. à café d’huile de colza dans une casserole avec le piment rouge. Faites cuire doucement 1 minute.","Ajoutez le jus et le zeste de citron et chauffez encore 1 minute, jusqu’à ce que le jus de citron ait réduit de moitié. Ajoutez l’autre moitié du pop-corn, mélangez bien et servez."],
["Ne mettez pas trop de maïs à la fois – faites cuire par fournées, car il gonfle beaucoup.","Il n’y a pas de limite aux saveurs que vous pouvez préparer – essayez différentes épices comme le cumin ou le paprika fumé. Veillez simplement à ne pas rendre le mélange trop humide, sinon le pop-corn sera ramolli."]))
o.append(R(57,"Café glacé infusé à froid","Les amateurs de café glacé insistent pour que le café soit infusé à froid, ce qui donne un café moins amer et plus aromatique. Vous pouvez le servir avec ou sans lait, sucré ou non.","8","145g",
["3 à 4 c. à soupe bombées de café fraîchement moulu","750ml d’eau froide","1 à 4 pastilles d’édulcorant (selon votre goût)","glaçons","400ml de lait écrémé (facultatif)","1 pincée de cacao en poudre (facultatif)"],
["Mettez le café et l’eau dans une cafetière à piston de 8 tasses, mélangez bien, couvrez (sans appuyer sur le piston) et placez au réfrigérateur au moins 12 heures ou toute la nuit.","Mélangez bien puis laissez reposer quelques minutes. Appuyez sur le piston, puis laissez reposer encore quelques minutes avant de verser le café dans une grande carafe.","Dissolvez les pastilles d’édulcorant, selon vos préférences, dans le café, puis incorporez le lait si vous en utilisez et ajoutez quelques glaçons.","Versez dans des verres remplis de glaçons et servez saupoudré d’un peu de cacao en poudre."],
["Un café moulu plus grossièrement convient mieux à l’infusion à froid.","Si vous n’avez pas de cafetière à piston, vous pouvez simplement filtrer le café à travers une mousseline ou un filtre à café en papier.","Vous pouvez simplement préparer un café ordinaire et le refroidir si vous manquez de temps."]))
o.append(R(58,"Pâtes gratinées aux légumes et au fromage","Ce plat simple mais savoureux peut facilement être adapté en utilisant des alternatives allégées en matière grasse, comme le lait écrémé.","2","342g",
["100g de pâtes à cuisson rapide","80g de petits pois surgelés ou en conserve","80g de maïs doux surgelé ou en conserve","15g de matière grasse tartinable à base d’huile végétale","15g de farine de blé","300ml de lait demi-écrémé","20g de cheddar, râpé","poivre noir fraîchement moulu"],
["Faites cuire les pâtes selon les instructions de l’emballage, en ajoutant les petits pois et le maïs.","Deux minutes avant la fin de la cuisson, égouttez. Pendant ce temps, mettez la matière grasse, la farine et le lait dans une casserole et faites cuire à feu moyen en fouettant continuellement, jusqu’à ce que la sauce ait épaissi.","Incorporez le cheddar. Rectifiez l’assaisonnement, ajoutez aux pâtes et aux légumes, mélangez et servez.","Ou, si vous préférez, passez sous le gril quelques minutes pour faire dorer le dessus."],
["Essayez d’ajouter des champignons sautés ou du poivron rouge pour augmenter la quantité de légumes.","Vous pouvez essayer d’utiliser du fromage de chèvre à la place du cheddar."]))
o.append(R(59,"Crumble de fruits pochés","Variez le crumble classique avec cette version sucrée et épicée.","4","450g",
["200ml de jus de pomme","1 bâton de cannelle","1 étoile de badiane","2 pommes, pelées, évidées et coupées en gros quartiers","3 poires, pelées, évidées et coupées en gros quartiers","4 prunes, dénoyautées et coupées en quatre","4 figues, coupées en quatre","150g de mûres","30g de flocons d’avoine","60g de farine de blé","20g de sucre roux (facultatif)","1 c. à café de cannelle moulue","50g de matière grasse tartinable allégée","4 c. à soupe de yaourt grec nature à 0 % de matières grasses"],
["Mettez le jus de pomme, le bâton de cannelle et l’étoile de badiane dans une casserole et chauffez doucement. Ajoutez les pommes, les poires, les prunes et les figues. Laissez mijoter environ 20 minutes jusqu’à ce que les fruits soient tendres, en ajoutant les mûres pendant les 5 dernières minutes. Retirez les fruits à l’aide d’une écumoire et réservez. Continuez à cuire le liquide jusqu’à ce qu’il réduise en un sirop collant. Retirez la cannelle et la badiane, puis versez le sirop sur les fruits.","Préchauffez le four à 200°C, chaleur tournante 180°C, thermostat 6. Mélangez dans un bol les flocons d’avoine, la farine, le sucre et la cannelle moulue. Incorporez la matière grasse du bout des doigts, jusqu’à ce que le mélange ressemble à de la chapelure grossière.","Mettez les fruits dans un plat de 20cm x 22cm. Parsemez de crumble et faites cuire 20 à 25 minutes, jusqu’à ce qu’il soit doré. Servez avec 1 c. à soupe de yaourt grec par portion."],[]))
save(4,o)
