from lib import *
o=[]
o.append(R(88,"Curry jamaïcain aux fruits de mer","Ce plat mijoté lentement réunit quelques-uns des ingrédients préférés des Jamaïcains pour un plat sucré, épicé et sensationnel ! Cette recette a été choisie en partenariat avec Slimming World.","4","447g",
["1 gros oignon, finement haché","2 gousses d’ail, écrasées","1 morceau de 5 cm de gingembre frais, pelé et râpé","1 piment vert moyennement fort, épépiné et finement haché","1 c. à soupe de poudre de curry (selon votre goût pour le piquant)","1/2 c. à café de chacun : cannelle moulue, flocons de piment séché et curcuma moulu","1/4 c. à café de clous de girofle moulus ou de piment de la Jamaïque","2 c. à café de graines de nigelle","1 c. à café rase d’édulcorant en granulés (facultatif)","200g de tomates concassées","200ml de lait de coco allégé en matières grasses","175g de gombos, chacun coupé en 3 ou 4 morceaux en biseau","100g de jeunes pousses d’épinards, plus quelques feuilles pour servir","200g de tomates cerises, coupées en deux","200g de crevettes crues décortiquées","400g de filets de poisson blanc à chair ferme, sans peau ni arêtes, coupés en gros morceaux","1 c. à soupe de jus de citron vert"],
["Mettez l’oignon, l’ail, le gingembre, le piment, la poudre de curry et les épices, l’édulcorant, les tomates concassées, le lait de coco et un peu de poivre dans le bol de votre mijoteuse. Mélangez bien, couvrez et faites cuire à puissance élevée pendant 1 heure.","Ajoutez les gombos, couvrez à nouveau et faites cuire encore 2 heures.","Incorporez les épinards, les tomates cerises et les crevettes. Assaisonnez légèrement les morceaux de poisson de poivre et déposez-les sur le curry. Couvrez de nouveau et faites cuire encore 1 heure, jusqu’à ce que les crevettes et le poisson changent de couleur et soient cuits à cœur.","Incorporez le jus de citron vert et parsemez de feuilles d’épinards supplémentaires pour servir."],
["Si vous n’avez pas de mijoteuse, mettez tous les ingrédients jusqu’au lait de coco dans une grande casserole antiadhésive ou une cocotte, couvrez et laissez mijoter à feu doux pendant 30 minutes. Ajoutez les gombos, couvrez et laissez mijoter 30 minutes de plus. Incorporez les épinards, les tomates cerises et les crevettes, puis déposez le poisson dessus. Couvrez et laissez mijoter 5 minutes, jusqu’à ce que les crevettes et le poisson soient cuits à cœur.","Faites attention aux mélanges d’épices ou d’assaisonnements contenant du sucre, du sel, de la farine ou de l’huile ajoutés. Choisissez des mélanges d’épices composés uniquement d’herbes et d’épices."]))
o.append(R(89,"Kebabs döner","Oubliez la livraison, préparez votre propre version plus saine.","4","349g",
["1 c. à café bombée d’origan","1 c. à café de cannelle moulue","1/2 c. à café de cumin moulu","1/2 c. à café de flocons de piment","1 bonne pincée de poivre blanc","2 gousses d’ail, écrasées","le zeste râpé et le jus d’un demi-citron","1 œuf, légèrement battu","1/2 tranche de pain complet, émiettée","250g d’agneau haché à 10 % de matières grasses","4 pains pitas complets (70g chacun)","4 grandes portions de salade (concombre, 100g de laitue iceberg, 300g de tomates et 150g d’oignon rouge)","le jus d’un demi-citron, pour servir"],
["Dans un bol, mettez l’origan, la cannelle, le cumin, le piment, le poivre, l’ail, le zeste et le jus de citron, avec l’œuf et le pain émietté. Mélangez bien à la fourchette en émiettant davantage le pain.","Incorporez l’agneau et laissez reposer 10 minutes. Mélangez de nouveau et façonnez en un pain d’environ 6 cm de diamètre et 13,5 cm de long.","Déposez sur une plaque de cuisson et faites cuire dans un four préchauffé à 190°C / thermostat 5 pendant 25 à 30 minutes.","Laissez refroidir 5 minutes, puis coupez en fines tranches et garnissez-en des pains pitas bien remplis de salade. Arrosez de jus de citron et servez."],
["Vous pouvez utiliser la salade de votre choix. Pour ajouter un excellent croquant, utilisez du chou cru râpé, de la laitue, de l’oignon rouge et du concombre, mélangés avec du jus de citron.","Pour les sauces (sur la photo) : Sauce au tahini : mettez 2 c. à café de tahini dans un bol et incorporez progressivement 3 c. à soupe de yaourt allégé et une pincée de poivre blanc. Condiment à la tomate : mélangez une grosse tomate finement hachée avec 1 c. à soupe de ketchup et un trait de sauce pimentée."]))
o.append(R(90,"Escalope de poulet, sauce à l’ail et au persil","Rehaussez le poulet nature avec cette sauce facile et délicieuse, prête en quelques minutes.","2","153g",
["1 gros blanc de poulet sans peau ni os (environ 220g)","2 c. à café d’huile de colza","4 gousses d’ail, écrasées","1 oignon nouveau, finement haché","25g de persil frais, finement haché","1 bonne pincée de poivre","le jus d’un demi-citron","1 c. à soupe de yaourt grec à 0 % de matières grasses"],
["Placez le blanc de poulet entre deux morceaux de film alimentaire et aplatissez-le avec un maillet ou un rouleau à pâtisserie pour obtenir une escalope plate d’environ 4 à 5 mm d’épaisseur. Divisez-la ensuite en 2 portions égales.","Badigeonnez les morceaux de poulet avec 1 c. à café d’huile. Déposez-les sur une poêle ou un gril bien chaud et faites cuire 2 à 3 minutes de chaque côté.","Pendant ce temps, dans une petite casserole, faites chauffer le reste de l’huile (1 c. à café), ajoutez l’ail et l’oignon nouveau et faites cuire 2 minutes, jusqu’à ce que l’oignon soit tendre. Ajoutez ensuite le persil et remuez 1 minute.","Ajoutez le poivre, le jus de citron et 1 c. à soupe d’eau. Incorporez le yaourt.","Déposez le poulet dans une assiette et servez avec la sauce."],
["Cette recette convient aussi très bien aux escalopes de dinde, de bœuf ou de porc. Vous pouvez aussi essayer la sauce avec du poisson grillé.","L’aplatissement attendrit la viande et rend le filet beaucoup plus rapide à cuire, ce qui est idéal pour les barbecues."]))
o.append(R(91,"Poulet au citron et aux herbes avec pois chiches","Ce plat rafraîchissant regorge d’herbes et s’accompagne très bien de légumes grillés.","2","326g",
["2 blancs de poulet sans peau ni os, d’environ 125g chacun","le zeste râpé et le jus de 1 citron","1 gousse d’ail, écrasée","1 c. à café d’huile d’olive","1 c. à café de graines de moutarde noire","1 c. à café de graines de cumin","4 oignons nouveaux, hachés","400g de pois chiches, égouttés et rincés","3 c. à soupe d’herbes fraîches mélangées, hachées","1 pincée de curcuma","2 c. à soupe de crème fraîche allégée","poivre noir fraîchement moulu"],
["Placez le poulet dans un plat non métallique, ajoutez le zeste et le jus de citron ainsi que l’ail, mélangez et laissez reposer 30 minutes.","Faites chauffer l’huile dans une poêle antiadhésive, ajoutez les graines de moutarde et de cumin et faites-les revenir 1 minute, jusqu’à ce qu’elles dégagent leur parfum.","Ajoutez le poulet dans la poêle et faites-le revenir 2 minutes de chaque côté. Ajoutez ensuite la marinade dans la poêle avec 200ml d’eau bouillante, couvrez et laissez mijoter 7 à 8 minutes, en retournant de temps en temps, jusqu’à ce que le poulet soit cuit à cœur.","Ajoutez les autres ingrédients, faites cuire encore 2 minutes, assaisonnez généreusement et servez."],
["Si vous devez épaissir légèrement la sauce, écrasez quelques pois chiches à la fourchette et incorporez-les.","Servez avec des légumes de différentes couleurs pour varier les plaisirs et apporter des nutriments supplémentaires.","Instructions de congélation : Peut être congelé une fois cuit. Décongelez ensuite au réfrigérateur ou au micro-ondes et réchauffez jusqu’à ce que le plat soit bien chaud à cœur."]))
o.append(R(92,"Brochettes de tofu mariné","Une alternative végétarienne aux brochettes de viande, à base de tofu mariné et de thym frais.","6","156g",
["1 c. à soupe d’huile d’olive","1 c. à soupe de vinaigre balsamique","1 gousse d’ail, écrasée","1 c. à café de thym frais","1 paquet de 200g de tofu (ferme), égoutté et coupé en 12 cubes","1 poivron rouge (150g), coupé en morceaux","1 poivron jaune (150g), coupé en morceaux","2 courgettes (250g), coupées en morceaux","1 oignon rouge (150g), coupé en 8 quartiers"],
["Dans un bol non métallique, mélangez l’huile, le vinaigre, l’ail et le thym.","Ajoutez le tofu dans le bol, enrobez-le de marinade et laissez reposer au moins 10 minutes. Faites tremper les brochettes en bois dans l’eau pour éviter qu’elles ne brûlent.","Enfilez en alternance le tofu mariné et les autres ingrédients sur les brochettes et faites cuire sous un gril à feu moyen pendant environ 10 minutes, jusqu’à ce qu’ils commencent à noircir légèrement, en les retournant de temps en temps."],
["Pour une touche chinoise, essayez d’ajouter 1 c. à café bombée de cinq-épices chinois à la marinade."]))
o.append(R(93,"Harira","Populaire pendant le ramadan, cette soupe marocaine traditionnelle et copieuse est nourrissante, réconfortante et hydratante.","6","537g",
["1 c. à soupe d’huile d’olive","200g d’oignon, haché","500g d’agneau maigre, coupé en cubes de 1 cm","3 poivrons – rouge, jaune et vert, hachés","2 carottes, coupées en dés","1 aubergine, coupée en cubes de 2 cm","3 gousses d’ail, hachées","1 c. à café bombée de paprika","1 c. à café bombée de cumin","1 c. à café bien pleine de curcuma","1 c. à café bombée de cannelle","1 boîte de 400g de tomates concassées","1 cube de bouillon de légumes (sans gluten)","1,5 litre d’eau bouillante","1 boîte de 400g de pois chiches, égouttés","1 boîte de 400g de lentilles vertes, égouttées","1 pot de 170g de yaourt grec à 0 % de matières grasses","1 bouquet de 30g de coriandre fraîche, hachée","quartiers de citron"],
["Faites chauffer l’huile dans une grande casserole, ajoutez l’oignon et faites cuire 5 minutes, jusqu’à ce qu’il commence à dorer.","Ajoutez l’agneau et faites cuire encore 7 minutes, en remuant régulièrement.","Ajoutez maintenant les poivrons, les carottes et l’aubergine, mélangez bien et faites cuire 5 minutes.","Ajoutez ensuite l’ail, le paprika, le cumin, le curcuma et la cannelle. Mélangez bien, puis ajoutez les tomates, émiettez le cube de bouillon et incorporez l’eau.","Portez à ébullition, remuez et couvrez. Baissez le feu et laissez mijoter doucement 1 heure, puis ajoutez les pois chiches et les lentilles, avec leur liquide. Mélangez bien et faites cuire encore 30 minutes.","Pendant ce temps, mélangez le yaourt et la coriandre.","Servez la soupe à la louche dans des bols et garnissez d’une cuillerée de yaourt à la coriandre et d’un filet de citron."],
["Pour une version végétarienne, remplacez l’agneau par un paquet de tofu mariné ou fumé et une boîte de haricots variés.","La harira est aussi délicieuse avec du poulet ou du bœuf.","Se conserve 2 à 3 jours au réfrigérateur – elle est encore meilleure le lendemain de sa préparation.","Instructions de congélation : Peut être congelée une fois cuite. Décongelez au réfrigérateur ou au micro-ondes et réchauffez jusqu’à ce que la soupe soit bien chaude à cœur."]))
o.append(R(94,"Fruits tropicaux tièdes aux épices, yaourt à la noix de coco","Ce délicieux dessert fruité se prépare rapidement et compte pour l’une de vos cinq portions de fruits et légumes par jour.","6","166g",
["1 citron vert","4 c. à soupe de jus d’ananas sans sucre ajouté provenant de la boîte – les fruits serviront plus tard","1/2 bâton de cannelle","1 morceau de gingembre frais de 2 pouces (5 cm), émincé","1 mangue mûre d’environ 200g, pelée, dénoyautée et coupée en dés","1 banane, pelée et coupée en rondelles","2 kiwis, pelés et coupés en morceaux","230g de morceaux d’ananas en conserve au jus","4 c. à café de graines de grenade","250g de yaourt de soja nature allégé en matières grasses à la noix de coco"],
["Râpez finement le zeste du citron vert et réservez-le. Pressez le jus du citron vert dans une grande casserole et ajoutez le jus d’ananas, 200ml d’eau, le bâton de cannelle et le gingembre. Portez à ébullition, retirez du feu, couvrez et laissez reposer 10 minutes.","Répartissez les fruits préparés, sauf les graines de grenade, dans des bols individuels. Filtrez le mélange au jus d’ananas et versez-le à parts égales sur les fruits.","Servez avec le yaourt parsemé de graines de grenade et de zeste de citron vert."]))
o.append(R(95,"Soupe de haricots pimentée, salsa à l’avocat","Une soupe riche de tomates et de haricots à la mexicaine, qui fait un dîner d’hiver copieux.","6","311g",
["1 c. à soupe d’huile de tournesol","1 gros oignon, haché","2 gousses d’ail, écrasées","2 piments rouges, finement hachés","1 c. à café de cumin moulu","1/2 c. à café de cannelle moulue","2 boîtes de 400g de haricots rouges, égouttés et rincés","1 boîte de 400g de tomates concassées","1,2 L de bouillon de légumes","1 avocat de 150g, pelé et finement haché","2 tomates, finement hachées","4 c. à soupe de coriandre fraîche, hachée","1/2 petit oignon rouge, finement haché","1/2 petit piment rouge, émincé (facultatif)","poivre noir fraîchement moulu"],
["Faites chauffer l’huile de tournesol dans une grande casserole, ajoutez l’oignon, l’ail et les piments et faites revenir 2 à 3 minutes, jusqu’à ce que l’oignon commence à ramollir. Ajoutez les épices et poursuivez la cuisson encore 1 minute.","Ajoutez les autres ingrédients de la soupe dans la casserole, portez à ébullition, couvrez et laissez mijoter 20 minutes.","Versez la soupe dans un robot ménager ou utilisez un mixeur plongeant et mixez jusqu’à obtenir une texture lisse (il peut être plus facile de procéder en plusieurs fois), remettez dans la casserole et réchauffez. Pendant ce temps, mélangez tous les ingrédients de la salsa.","Servez la soupe garnie d’une cuillerée de salsa."],
["Pour une soupe plus légère, utilisez des haricots blancs (cannellini) plutôt que des haricots rouges.","Si vous ne voulez pas d’une salsa trop piquante, omettez simplement le piment."]))
o.append(R(96,"Chou rouge aux épices","Un excellent accompagnement pour tous les rôtis.","8","128g",
["1kg de chou rouge, évidé et finement émincé","2 pommes à croquer, tranchées","1 bâton de cannelle","8 clous de girofle","1 c. à soupe de cassonade claire","2 c. à soupe de vinaigre de vin blanc","1 noix de beurre"],
["Mettez tous les ingrédients dans une grande casserole munie d’un couvercle bien ajusté.","Couvrez et faites cuire à feu doux pendant 45 minutes, en remuant de temps en temps, jusqu’à ce que le chou soit tendre. Servez."],
["Ajouter du vinaigre au chou rouge pendant la cuisson l’aide à conserver sa couleur.","Vous pouvez ajouter des raisins secs et/ou des noix au chou lorsqu’il est presque prêt.","Vous pouvez aussi utiliser du chou rouge cru pour préparer une salade de chou très colorée."]))
o.append(R(97,"Burritos","Préparez votre propre version plus saine de ce classique mexicain.","8","300g",
["un trait d’huile de tournesol","1 gros oignon, finement haché","500g de viande hachée de dinde","1 poivron rouge, finement haché","1 poivron vert, finement haché","1 c. à café bombée de cumin moulu","1 c. à café bombée d’origan séché","1 c. à café rase de piment en poudre","1 boîte de 400g de tomates concassées","1 boîte de 400g de haricots variés, égouttés","8 tortillas de blé complet (65g chacune)","200g de feuilles de salade variées","50g de cheddar allégé en matières grasses, râpé"],
["Mettez l’huile dans une poêle, ajoutez l’oignon et faites cuire 5 minutes, en remuant régulièrement, jusqu’à ce qu’il soit doré.","Ajoutez la viande hachée et faites cuire encore 5 minutes, en remuant régulièrement et en défaisant les grumeaux.","Ajoutez maintenant les poivrons rouge et vert, le cumin, l’origan, le piment en poudre et les tomates. Mélangez bien, portez à ébullition, puis baissez complètement le feu et laissez mijoter doucement 7 à 8 minutes.","Ajoutez les haricots, mélangez bien et ramenez à frémissement.","Pendant ce temps, faites chauffer les tortillas dans une poêle sèche, en veillant à ce que chaque face reste 30 secondes au contact de la poêle chaude.","Étalez les tortillas, déposez une poignée de salade sur chacune, puis une cuillerée du mélange à la dinde. Ajoutez un peu de fromage, puis repliez en un paquet bien serré et net, enveloppez dans du papier d’aluminium et servez."],
["Vous pouvez ajouter davantage de piment en poudre si vous aimez vos burritos relevés.","Remplacez la dinde hachée par du poulet ou de l’agneau."]))
o.append(R(98,"Verrines de gelée et de banane","Cette gourmandise fruitée est étonnamment facile à préparer.","4","190g",
["1 sachet de 23g de gelée à l’orange sans sucre","1 orange","3 petites bananes, d’environ 65g chacune, sans peau, pelées et coupées en rondelles","2 biscuits à la cuillère, chacun coupé en 8 morceaux","50g de noix de pécan, émincées","100g de fromage frais sans matières grasses","100g de crème anglaise allégée en matières grasses"],
["Versez les cristaux de gelée dans un pichet gradué, ajoutez 300ml d’eau bouillante et remuez jusqu’à dissolution. Ajoutez 300ml d’eau froide et réservez. Râpez finement le zeste de l’orange et réservez-le. Retirez l’écorce de l’orange et prélevez les segments.","Répartissez à parts égales les segments d’orange, les rondelles de banane et les biscuits à la cuillère entre quatre verres. Versez la gelée à l’orange par-dessus et placez au réfrigérateur 1 heure, jusqu’à ce qu’elle soit prise.","Mélangez la plupart des noix (en en réservant quelques-unes pour la décoration) avec le yaourt grec et le zeste d’orange, et étalez à la cuillère sur la moitié de la surface des gelées. Étalez la crème anglaise allégée sur l’autre moitié et marbrez légèrement avec une cuillère. Parsemez des noix réservées pour décorer."]))
o.append(R(99,"Enchiladas de courgettes","Une variante originale d’un classique mexicain, ce plat fournit trois de vos cinq portions de fruits et légumes par jour. Envoyé par Natalie Loveman","4","462g",
["4 courgettes moyennes","1 c. à café d’huile","75g d’oignons nouveaux, hachés","3 gousses d’ail, écrasées","75g de poivron vert, haché","1 pincée de sel et de poivre","1 c. à café de cumin","1/2 c. à café d’origan séché","1/2 c. à café de piment en poudre","1 c. à soupe de concentré de tomate","2 blancs de poulet cuits et effilochés (environ 250g)","1 bocal de 395g de sauce pour enchiladas","75g de cheddar allégé en matières grasses, râpé"],
["Préchauffez le four à 180°C / thermostat 4. Coupez les courgettes en deux dans le sens de la longueur et, à l’aide d’une petite cuillère ou d’une cuillère à melon, retirez la chair en laissant à l’intérieur de chaque courgette une « bordure » de 7 cm. Hachez la chair retirée en petits morceaux et réservez.","Faites chauffer l’huile dans une grande poêle et ajoutez les oignons nouveaux, l’ail et le poivron. Faites cuire à feu moyen-doux 2 à 3 minutes, jusqu’à ce que les oignons soient translucides, puis ajoutez la chair de courgette hachée, assaisonnez et faites cuire environ 4 minutes.","Ajoutez le cumin, l’origan, le piment en poudre, 3 c. à soupe d’eau et le concentré de tomate. Faites cuire encore quelques minutes. Ajoutez le poulet effiloché, mélangez et faites cuire 3 minutes de plus.","Versez un quart du bocal de sauce pour enchiladas au fond d’un grand plat allant au four (ou de 2 petits), puis déposez les moitiés de courgettes, face coupée vers le haut. À l’aide d’une cuillère, garnissez chaque courgette évidée avec le mélange au poulet, en tassant fermement.","Nappez les courgettes du reste de la sauce pour enchiladas et parsemez uniformément de fromage. Couvrez de papier d’aluminium et faites cuire au four 35 minutes, jusqu’à ce que le fromage ait fondu et que les courgettes soient cuites à cœur."],
["Pour une version végétarienne, remplacez le poulet par des champignons hachés et sautés.","Si vous n’avez pas de bocal de sauce, utilisez simplement une boîte de tomates et mixez-les avec 1 c. à café bombée chacun de cumin, d’origan et de piment en poudre (doux ou fort)."]))
save(7,o)
