from h import *
O=[]
O.append(R(6531377,
es=("Salmón al horno inspirado en la barbacoa coreana","La salsa inspirada en la barbacoa coreana de este salmón tiene el equilibrio ideal entre dulce, salado, ácido y picante. El dulzor proviene de forma natural de la fruta, no de azúcares añadidos. También puede usar esta salsa con pollo: hornee muslos de pollo deshuesados y sin piel, sin la salsa, durante 15 minutos; luego úntelos con la salsa y hornee otros 15 minutos, o hasta que estén bien cocidos.","4","1 filete",
["4 filetes (de 6 onzas) de salmón sockeye, corte central, con piel","2 cucharadas de salsa de tomate (kétchup) sin azúcar añadida","1 cucharada de mermelada de albaricoque endulzada con fruta","1 cucharada de tamari o salsa de soya reducida en sodio","2 cucharaditas de vinagre de arroz","1/4 de cucharadita de salsa picante","1 cucharadita de semillas de ajonjolí"],
["Precaliente el horno a 400° F. Cubra una bandeja grande para hornear con borde con papel pergamino.","Coloque el salmón, con la piel hacia abajo, sobre la bandeja para hornear.","En un tazón pequeño, mezcle la salsa de tomate, la mermelada, el tamari, el vinagre y la salsa picante. Con el dorso de la cuchara, extienda ligeramente la mezcla sobre la parte superior de cada filete. Espolvoree con las semillas de ajonjolí.","Hornee hasta que el salmón se desmenuce fácilmente y esté bien cocido (con una temperatura interna de al menos 145° F), unos 16 minutos. Sirva."],[],[]),
ar=("سلمون مخبوز مستوحى من الشواء الكوري","تتميز الصلصة المستوحاة من الشواء الكوري على هذا السلمون بتوازن مثالي بين الحلو والمالح والحامض والحار. تأتي الحلاوة بشكل طبيعي من الفاكهة وليس من السكر المضاف. يمكنك أيضًا استخدام هذه الصلصة مع الدجاج: اخبز أفخاذ الدجاج منزوعة العظم والجلد بدون الصلصة لمدة 15 دقيقة، ثم افرد عليها الصلصة بالفرشاة واخبزها 15 دقيقة أخرى، أو حتى تنضج تمامًا.","4","1 شريحة",
["4 شرائح (6 أونصة لكل شريحة) من سلمون سوكاي من وسط السمكة مع الجلد","2 ملعقة كبيرة كاتشب بدون سكر مضاف","1 ملعقة كبيرة مربى المشمش المحلى بالفاكهة","1 ملعقة كبيرة تاماري أو صلصة صويا مخفضة الصوديوم","2 ملعقة صغيرة خل الأرز","¼ ملعقة صغيرة صلصة حارة","1 ملعقة صغيرة بذور السمسم"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية). بطّن صينية خبز كبيرة ذات حواف بورق الزبدة.","ضع السلمون، مع جعل الجلد إلى الأسفل، على صينية الخبز.","في وعاء صغير، قلّب الكاتشب والمربى والتاماري والخل والصلصة الحارة. افرد الخليط بخفة على وجه كل شريحة باستخدام ظهر الملعقة. رشّ بذور السمسم.","اخبز حتى يصبح السلمون سهل التفتت ومطهوًا تمامًا (مع درجة حرارة داخلية لا تقل عن 145° فهرنهايت (65° مئوية))، حوالي 16 دقيقة. قدّمه."],[],[])))
O.append(R(6536371,
es=("Camarones salteados con espinacas, tomates uva y papas rojas asadas","Este plato de camarones, rápido y delicioso, sigue el patrón de alimentación bajo en carbohidratos y bajo en grasa, lo que significa que es una buena opción para las personas que cuidan su presión arterial. Camarones jugosos salteados con espinacas frescas, tomates uva dulces y papas rojas asadas y crujientes, que crean una mezcla armoniosa de sabores y texturas. Es un plato sustancioso y lleno de sabor, perfecto para una cena entre semana.","4","1 taza de camarones y verduras, 1/2 taza de papas",
["16 oz de papas rojas pequeñas","1 cucharada de aceite de oliva","1/2 cucharadita de condimento italiano","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra","1 pinta de tomates uva (cortados a la mitad)","2 dientes de ajo (picados)","1 1/2 libras de camarones grandes (pelados y desvenados)","1/4 de cucharadita de hojuelas de pimiento rojo triturado","5 oz de espinacas baby","1 1/2 oz de queso parmesano (rallado fino)","1/2 taza de hojas de albahaca fresca (cortadas en tiras finas)"],
["Precaliente el horno a 425 grados F. Corte las papas rojas pequeñas por la mitad o en cuartos, según su tamaño. En una bandeja para hornear, mézclelas con 2 cucharaditas de aceite de oliva, el condimento italiano, la sal y la pimienta.","Ase en el horno de 20 a 25 minutos, volteándolas a la mitad del tiempo, hasta que estén doradas y tiernas.","Caliente una sartén a fuego medio. Agregue el resto del aceite de oliva y los tomates uva a la sartén. Cocine, revolviendo de vez en cuando, de 3 a 4 minutos, o hasta que los tomates se ablanden y suelten parte de su jugo.","Agregue el ajo, los camarones y el pimiento rojo triturado a la sartén. Saltee los camarones de 1 a 2 minutos por lado, o hasta que estén opacos y bien cocidos.","Agregue las espinacas a la sartén por puñados, revolviendo después de cada adición para que se marchiten.","Reduzca el fuego a bajo y espolvoree la mitad del queso parmesano rallado sobre el contenido de la sartén. Revuelva para combinar y deje que el queso se derrita un poco.","Divida los camarones, las verduras salteadas y las espinacas entre los platos. Decore con el queso parmesano reservado y las tiras de albahaca. Sirva acompañado de las papas rojas asadas."],[],[]),
ar=("روبيان مسوّط مع السبانخ وطماطم العنب والبطاطس الحمراء المحمصة","يتبع طبق الروبيان السريع واللذيذ هذا نمط الأكل منخفض الكربوهيدرات ومنخفض الدهون، أي أنه خيار جيد للأشخاص المهتمين بضغط الدم. يُسوَّط الروبيان الطري مع السبانخ الطازجة وطماطم العنب الحلوة والبطاطس الحمراء المحمصة المقرمشة، لتحصل على مزيج متناغم من النكهات والقوامات. إنه طبق مشبع وغني بالنكهة ومثالي لوجبة عشاء في أيام الأسبوع.","4","1 كوب روبيان وخضار، ½ كوب بطاطس",
["16 أونصة بطاطس حمراء صغيرة","1 ملعقة كبيرة زيت زيتون","½ ملعقة صغيرة توابل إيطالية","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 باينت طماطم عنب (مقطعة إلى نصفين)","2 فص ثوم (مفروم)","1½ رطل روبيان كبير (مقشر ومنزوع الأمعاء)","¼ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","5 أونصة سبانخ صغيرة","1½ أونصة جبن بارميزان (مبشور ناعمًا)","½ كوب أوراق ريحان طازجة (مقطعة إلى شرائح رفيعة)"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220 درجة مئوية). قطّع حبات البطاطس الحمراء الصغيرة إلى نصفين أو أرباع بحسب حجمها. قلّبها على صينية خبز مع 2 ملعقة صغيرة من زيت الزيتون والتوابل الإيطالية والملح والفلفل.","حمّصها في الفرن لمدة 20-25 دقيقة، مع قلبها في منتصف المدة، حتى تصبح ذهبية وطرية.","سخّن مقلاة على حرارة متوسطة. أضف باقي زيت الزيتون وطماطم العنب إلى المقلاة. اطهِ مع التحريك من حين لآخر لمدة 3-4 دقائق، أو حتى تلين الطماطم ويخرج بعض عصيرها.","أضف الثوم والروبيان والفلفل الأحمر المجروش إلى المقلاة. سوّط الروبيان لمدة 1-2 دقيقة من كل جانب، أو حتى يصبح معتمًا ومطهوًا تمامًا.","أضف السبانخ إلى المقلاة حفنة بعد حفنة، مع التقليب بعد كل إضافة حتى تذبل.","اخفض الحرارة إلى منخفضة ورشّ نصف جبن البارميزان المبشور فوق محتويات المقلاة. قلّب لتمتزج المكونات واترك الجبن يذوب قليلًا.","وزّع الروبيان والخضار المسوّطة والسبانخ بين الأطباق. زيّنها بجبن البارميزان المتبقي وشرائح الريحان. قدّمها مع البطاطس الحمراء المحمصة."],[],[])))
O.append(R(6536789,
es=("Latkes de brócoli y cebolla","Los latkes bajos en carbohidratos usan brócoli en lugar de las papas tradicionales. También son más bajos en potasio, por lo que son una excelente alternativa para quienes siguen una dieta baja en potasio para cuidar la salud de los riñones.","4","1 latke",
["3 tazas de floretes de brócoli picados, frescos o congelados","1/2 taza de cebolla en cubos","2 huevos enteros","2 cucharadas de harina de trigo para todo uso","2 cucharadas de aceite de oliva"],
["Hierva el brócoli en cubos en una pequeña cantidad de agua durante 5 minutos y luego escúrralo bien.","Rompa los huevos en un tazón mediano y bátalos. Agregue la harina y mezcle bien. Agregue el brócoli y la cebolla y revuelva hasta que todo quede bien mezclado con la mezcla de harina y huevo.","Caliente el aceite de oliva en una sartén a fuego medio-alto. Deje caer la mezcla por cucharadas en el aceite caliente, formando 4 porciones iguales. Aplánelas con una espátula y cocine hasta que estén doradas por ambos lados (unos 3 a 4 minutos por lado).","Retire los latkes de la sartén y escúrralos sobre una toalla de papel para absorber el exceso de aceite. Sirva calientes."],[],[]),
ar=("لاتكس البروكلي والبصل","تستخدم فطائر اللاتكس منخفضة الكربوهيدرات البروكلي بدلًا من البطاطس التقليدية. كما أنها أقل في البوتاسيوم، مما يجعلها بديلًا رائعًا لمن يتبعون نظامًا غذائيًا منخفض البوتاسيوم للحفاظ على صحة الكلى.","4","1 فطيرة لاتكس",
["3 كوب زهيرات بروكلي مفرومة طازجة أو مجمدة","½ كوب بصل مقطع إلى مكعبات","2 بيضة كاملة","2 ملعقة كبيرة دقيق متعدد الاستخدامات","2 ملعقة كبيرة زيت زيتون"],
["اسلق البروكلي المقطع إلى مكعبات في كمية قليلة من الماء لمدة 5 دقائق، ثم صفِّه جيدًا.","اكسر البيض في وعاء متوسط واخفقه. أضف الدقيق واخلط جيدًا. أضف البروكلي والبصل وقلّب حتى يمتزج كل شيء جيدًا مع خليط الدقيق والبيض.","سخّن زيت الزيتون في مقلاة على حرارة متوسطة عالية. اسكب الخليط بالملاعق في الزيت الساخن لتحصل على 4 حصص متساوية. سوِّها بالملعقة المسطحة (السباتولا) واطهِ حتى تصبح ذهبية اللون من الجانبين (حوالي 3-4 دقائق لكل جانب).","ارفع فطائر اللاتكس من المقلاة وصفِّها على منديل ورقي لامتصاص الزيت الزائد. قدّمها ساخنة."],[],[])))
O.append(R(6536966,
es=("Besan chilla","Elaborado con harina de garbanzo y verduras de colores, el besan chilla es un panqueque salado popular que se disfruta en muchos hogares de la India. Su sabor ligeramente a nuez, sus bordes crujientes y su centro tierno lo convierten en un delicioso refrigerio o comida ligera, mientras que la harina de garbanzo aporta proteína y fibra.","1","1 panqueque",
["1/4 de taza de harina de garbanzo (besan)","1/4 de taza de agua","2 cucharadas de cebolla amarilla (picada fina)","2 cucharadas de espinacas (picadas finas)","2 cucharadas de pimiento morrón (picado fino)","2 cucharadas de calabacín (rallado)","1/4 de cucharadita de comino molido","1/4 de cucharadita de cilantro molido","1/16 de cucharadita de cúrcuma","1/16 de cucharadita de chile en polvo","1/16 de cucharadita de sal","1 rociada de aceite en aerosol antiadherente de 0.25 g","1 cucharada de yogur griego natural sin grasa"],
["En un tazón, bata el besan, el agua y las especias hasta obtener una mezcla suave.","Agregue las verduras y revuelva. Tape y reserve de 5 a 10 minutos. Mezcle bien de nuevo.","Caliente una sartén antiadherente a fuego medio y cúbrala ligeramente con el aceite en aerosol.","Vierta la masa en la sartén, extiéndala suavemente de manera uniforme y redondee la forma para obtener un panqueque delgado de 6 pulgadas.","Cocine de 2 a 3 minutos por lado, hasta que esté ligeramente dorado y bien cocido.","Sirva caliente con 1 cucharada de yogur griego natural a un lado para mojar."],[],[]),
ar=("بيسان تشيلا","البيسان تشيلا فطيرة مالحة شائعة تُحضَّر من دقيق الحمص والخضار الملونة ويستمتع بها كثير من البيوت الهندية. نكهتها الخفيفة التي تشبه المكسرات وأطرافها المقرمشة ووسطها الطري تجعلها وجبة خفيفة أو وجبة خفيفة الحجم لذيذة، بينما يوفر دقيق الحمص البروتين والألياف.","1","1 فطيرة",
["¼ كوب دقيق الحمص (بيسان)","¼ كوب ماء","2 ملعقة كبيرة بصل أصفر (مفروم ناعمًا)","2 ملعقة كبيرة سبانخ (مفرومة ناعمًا)","2 ملعقة كبيرة فلفل رومي (مفروم ناعمًا)","2 ملعقة كبيرة كوسا (مبشورة)","¼ ملعقة صغيرة كمون مطحون","¼ ملعقة صغيرة كزبرة مطحونة","1/16 ملعقة صغيرة كركم","1/16 ملعقة صغيرة مسحوق الفلفل الحار","1/16 ملعقة صغيرة ملح","1 بخّة (0.25 غرام) بخاخ طهي غير لاصق","1 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم"],
["في وعاء، اخفق البيسان والماء والتوابل حتى يصبح الخليط ناعمًا.","أضف الخضار وقلّب. غطِّ الوعاء واتركه جانبًا لمدة 5-10 دقائق. اخلط جيدًا مرة أخرى.","سخّن مقلاة غير لاصقة على حرارة متوسطة وادهنها برفق ببخاخ الطهي.","اسكب الخليط في المقلاة، وافرده برفق بالتساوي، وقم بتدوير الشكل لتحصل على فطيرة رقيقة قطرها 6 بوصات.","اطهِ لمدة 2-3 دقائق من كل جانب، حتى يصبح لونها بنيًا فاتحًا وتنضج تمامًا.","قدّمها دافئة مع 1 ملعقة كبيرة من الزبادي اليوناني السادة بجانبها للتغميس."],[],[])))
O.append(R(6536985,
es=("Levadura nutricional","Información nutricional de 4 cucharadas de levadura nutricional.","1","4 cucharadas",["4 cucharadas de levadura nutricional"],[],[],[]),
ar=("الخميرة الغذائية","المعلومات الغذائية لـ 4 ملعقة كبيرة من الخميرة الغذائية.","1","4 ملعقة كبيرة",["4 ملعقة كبيرة خميرة غذائية"],[],[],[])))
O.append(R(6537876,
es=("Puré cremoso de coliflor","El puré cremoso de coliflor es una alternativa baja en carbohidratos para cuando se le antoja un puré de papas. Esta receta apta para personas con diabetes tiene todo lo que podría esperar de un plato clásico reconfortante.","4","3/4 de taza",
["1 coliflor grande (cortada en floretes)","1 cucharada de mantequilla sin sal","2 dientes de ajo (picados)","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra","1/4 de taza de yogur griego natural sin grasa"],
["Cocine los floretes de coliflor al vapor o hiérvalos hasta que estén tiernos al pincharlos con un tenedor, unos 10 a 12 minutos.","Coloque la coliflor cocida en un tazón grande.","En una sartén pequeña, derrita la mantequilla a fuego medio. Agregue el ajo picado y saltee de 1 a 2 minutos hasta que desprenda aroma.","Agregue la mantequilla con ajo, la sal y la pimienta a la coliflor.","Agregue el yogur griego a la coliflor.","Use una licuadora de mano para licuar la coliflor hasta que quede suave y cremosa."],[],[]),
ar=("هريس القرنبيط الكريمي","هريس القرنبيط الكريمي بديل منخفض الكربوهيدرات عندما تشتهي هريس البطاطس. هذه الوصفة المناسبة لمرضى السكري تقدم كل ما تتمناه من طبق كلاسيكي مريح.","4","¾ كوب",
["1 رأس قرنبيط (كبير، مقطع إلى زهيرات)","1 ملعقة كبيرة زبدة غير مملحة","2 فص ثوم (مفروم)","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","¼ كوب زبادي يوناني سادة خالٍ من الدسم"],
["اطهِ زهيرات القرنبيط على البخار أو اسلقها حتى تصبح طرية عند غرزها بالشوكة، حوالي 10-12 دقيقة.","ضع القرنبيط المطبوخ في وعاء كبير.","في مقلاة صغيرة، ذوّب الزبدة على حرارة متوسطة. أضف الثوم المفروم وسوّطه لمدة 1-2 دقيقة حتى تفوح رائحته.","أضف زبدة الثوم والملح والفلفل إلى القرنبيط.","أضف الزبادي اليوناني إلى القرنبيط.","استخدم خلاطًا يدويًا لهرس القرنبيط حتى يصبح ناعمًا وكريميًا."],[],[])))
O.append(R(6538174,
ar=("سلطة الدجاج والتفاح الكريمية","هذه السلطة منخفضة الكربوهيدرات وغنية بالأغذية المفيدة. سهلة التحضير ومليئة بالتغذية الجيدة، فهي توفر البروتين من الدجاج والألياف من التفاح والدهون الصحية من الجوز، وهي وصفة سريعة مناسبة لمرضى السكري ومثالية للغداء وللتحضير المسبق. مليئة بالنكهة والقرمشة، لن تصدق مدى سهولتها!","8","½ كوب",
["2 كوب صدر دجاج مطبوخ (مقطع)","2 ساق كرفس (مقطعة إلى مكعبات)","2 حبة بصل أخضر (مفرومة)","1 حبة تفاح جوناجولد متوسطة (مقطعة إلى مكعبات صغيرة)","3 ملعقة كبيرة جوز (مفروم)","¼ كوب مايونيز خفيف","¼ كوب زبادي (سادة، خالٍ من الدسم)","½ حبة ليمون (معصورة)","⅛ ملعقة صغيرة فلفل أسود"],
["في وعاء متوسط، اخلط الدجاج والكرفس والبصل الأخضر والتفاح والجوز.","في وعاء صغير، اخفق المايونيز والزبادي وعصير الليمون والفلفل. اسكبه فوق خليط الدجاج وقلّب برفق ليتغطى.","قدّم السلطة فوق أوراق الخس أو الخبز أو البسكويت المالح حسب اختيارك."],[],[])))
O.append(R(6538918,
es=("Ensalada de camote con cilantro y lima","Esta ensalada al estilo tex-mex es sustanciosa y llena, y seguramente despertará sus papilas gustativas. Es apta para personas con diabetes y quedaría excelente como guarnición en su próxima cena de martes de tacos.","6","1 taza",
["2 camotes grandes (pelados y cortados en cubos del tamaño de un bocado)","2 cucharadas de aceite de oliva","1 cucharadita de semillas de comino","1/2 cucharadita de pimentón ahumado","1/4 de cucharadita de sal kosher","1/4 de cucharadita de pimienta negra","1/4 de taza de cilantro fresco (picado)","1 lima mediana (su ralladura y su jugo)","1/4 de taza de cebolla morada (picada fina)","1 aguacate mediano (en cubos)","1 lata (de 15 oz) de frijoles negros (reducidos en sodio, escurridos y enjuagados)"],
["Precaliente el horno a 400 grados F.","En un tazón grande, mezcle los camotes en cubos con el aceite de oliva, el comino, el pimentón ahumado, la sal y la pimienta negra hasta que queden cubiertos de manera uniforme.","Extienda los camotes sazonados en una sola capa sobre una bandeja para hornear.","Ase en el horno precalentado durante 30 minutos o hasta que los camotes estén tiernos y ligeramente caramelizados, revolviendo a la mitad del tiempo.","Mientras se asan los camotes, prepare el aderezo. Ralle la cáscara de la lima y exprima su jugo. En un tazón pequeño, mezcle el cilantro fresco picado, la ralladura de lima y el jugo de lima.","Cuando los camotes estén listos, pásalos a un tazón para servir.","Vierta el aderezo de cilantro y lima sobre los camotes asados.","Agregue al tazón la cebolla morada picada fina, el aguacate y los frijoles negros.","Mezcle la ensalada con suavidad para que quede cubierta de manera uniforme."],[],[]),
ar=("سلطة البطاطا الحلوة بالكزبرة والليمون الأخضر","هذه السلطة على الطريقة التكسمكسية مشبعة ودسمة ومن المؤكد أنها ستنشّط حاسة التذوق لديك. وهي مناسبة لمرضى السكري وتصلح طبقًا جانبيًا رائعًا لعشاء ثلاثاء التاكو القادم!","6","1 كوب",
["2 حبة بطاطا حلوة كبيرة (مقشرة ومقطعة إلى مكعبات بحجم اللقمة)","2 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة بذور الكمون","½ ملعقة صغيرة بابريكا مدخنة","¼ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","¼ كوب كزبرة خضراء طازجة (مفرومة)","1 حبة ليمون أخضر متوسطة (مبشور قشرها ومعصورة)","¼ كوب بصل أحمر (مفروم ناعمًا)","1 حبة أفوكادو متوسطة (مقطعة إلى مكعبات)","1 علبة (15 أونصة) فاصولياء سوداء (مخفضة الصوديوم، مصفاة ومشطوفة)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (200 درجة مئوية).","في وعاء كبير، قلّب مكعبات البطاطا الحلوة مع زيت الزيتون والكمون والبابريكا المدخنة والملح والفلفل الأسود حتى تتغطى بالتساوي.","افرد البطاطا الحلوة المتبّلة في طبقة واحدة على صينية خبز.","حمّصها في الفرن المسخّن مسبقًا لمدة 30 دقيقة أو حتى تصبح البطاطا الحلوة طرية ومكرملة قليلًا، مع التقليب في منتصف المدة.","أثناء تحميص البطاطا الحلوة، حضّر الصلصة. ابشر قشر الليمون الأخضر واعصره. في وعاء صغير، اخلط الكزبرة الخضراء الطازجة المفرومة وقشر الليمون الأخضر وعصيره.","عندما تنضج البطاطا الحلوة، انقلها إلى وعاء التقديم.","اسكب صلصة الكزبرة والليمون الأخضر فوق البطاطا الحلوة المحمصة.","أضف البصل الأحمر المفروم ناعمًا والأفوكادو والفاصولياء السوداء إلى الوعاء.","قلّب السلطة برفق لتتغطى بالتساوي."],[],[])))
O.append(R(6538924,
ar=("تبولة القرنبيط","التبولة سلطة متوسطية تقليدية تُحضَّر من أعشاب غنية بالنكهة وليمون طازج وكسكس. تستخدم هذه النسخة المناسبة لمرضى السكري أرز القرنبيط كبديل أقل في الكربوهيدرات وخالٍ من الحبوب.","6","1 كوب",
["1 كوب أوراق بقدونس مكبوسة","¼ كوب أوراق نعناع مكبوسة","1 رأس قرنبيط صغير (أو 16 أونصة أرز قرنبيط مجمد) (منزوع الأوراق والساق)","2 حبة طماطم روما متوسطة (منزوعة البذور ومقطعة إلى مكعبات)","2 ملعقة كبيرة زيت زيتون","3 ملعقة كبيرة عصير ليمون (معصور طازجًا)","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["افرم أوراق البقدونس والنعناع فرمًا ناعمًا (أو اطحنها في محضّرة الطعام) وضعها في وعاء كبير.","ابشر القرنبيط باستخدام مبشرة ذات أوجه وقلّبه مع البقدونس والنعناع.","أضف الطماطم المقطعة إلى مكعبات وقلّبها مع السلطة.","رشّ السلطة بزيت الزيتون وعصير الليمون، وأضف الملح (اختياري) والفلفل الأسود. قلّب لتتغطى المكونات.","غطِّ التبولة واتركها لتتتبّل لمدة 30 دقيقة قبل التقديم."],[],[])))
O.append(R(6539733,
es=("Ejotes fáciles al estilo del Medio Oriente","Este plato está inspirado en un plato libanés llamado loubieh. Son simplemente ejotes y tomates uva cocinados con la cantidad justa de aceite de oliva extra virgen y sazonados con canela y sal marina. Se prepara rápido y puede hacerse fácilmente mientras se cocina el resto de su comida. Acompáñelo con un plato de proteína sencillo, como este Salmón glaseado con balsámico, para una cena rápida y fácil entre semana.\n\nEncuentre esta receta y más en The Clean & Simple Diabetes Cookbook de Jackie Newgent, RDN, CDN","2","1 1/2 tazas",
["2 cucharaditas de aceite de oliva extra virgen","8 oz de ejotes frescos (con los extremos del tallo recortados)","1 taza de tomates uva","1/4 de cucharadita de canela molida","1/8 de cucharadita de sal"],
["Caliente el aceite en una sartén antiadherente grande a fuego medio. Agregue los ejotes y los tomates, tape y cocine hasta que los ejotes estén tiernos pero crujientes y los tomates estén completamente blandos, unos 10 minutos. Mezcle con unas pinzas un par de veces durante la cocción.","Espolvoree las verduras con la canela y la sal. Mezcle para combinar y luego sirva."],[],[]),
ar=("فاصولياء خضراء سهلة على الطريقة الشرق أوسطية","هذا الطبق مستوحى من طبق لبناني يسمى اللوبية. إنه ببساطة فاصولياء خضراء وطماطم عنب مطهوة بكمية مناسبة تمامًا من زيت الزيتون البكر الممتاز ومتبّلة بالقرفة وملح البحر. يُحضَّر بسرعة ويمكن إعداده بسهولة أثناء طهي بقية وجبتك. قدّمه مع طبق بروتين بسيط، مثل سلمون مطلي بالبلسمية، لعشاء سريع وسهل في أيام الأسبوع.\n\nستجد هذه الوصفة وغيرها في كتاب The Clean & Simple Diabetes Cookbook من تأليف Jackie Newgent, RDN, CDN","2","1½ كوب",
["2 ملعقة صغيرة زيت زيتون بكر ممتاز","8 أونصة فاصولياء خضراء طازجة (مقطوعة أطراف السيقان)","1 كوب طماطم عنب","¼ ملعقة صغيرة قرفة مطحونة","⅛ ملعقة صغيرة ملح"],
["سخّن الزيت في مقلاة كبيرة غير لاصقة على حرارة متوسطة. أضف الفاصولياء الخضراء والطماطم، وغطِّ المقلاة واطهِ حتى تصبح الفاصولياء طرية لكن مقرمشة وتلين الطماطم تمامًا، حوالي 10 دقائق. قلّبها بالملقط مرتين خلال الطهي.","رشّ القرفة والملح على الخضار. قلّب لتمتزج المكونات، ثم قدّمها."],[],[])))
O.append(R(6540545,
es=("Parathas integrales de espinaca","El paratha es un tipo de pan plano originario del norte de la India, donde sigue siendo popular. Forma parte de un desayuno indio tradicional, pero también se puede servir con el almuerzo o la cena.","8","1 paratha",
["2/3 de taza de agua","2 tazas más 1 cucharada de harina integral para repostería (dividida)","1 cucharadita de comino molido","1/2 cucharadita de amchoor (polvo de mango)","1/2 cucharadita de sal marina fina (dividida)","1 taza de espinacas baby (bien compactadas y picadas)","1 chile verde entero (sin semillas, picado muy fino)","1 cucharada de jengibre fresco (rallado)","1 cucharadita de semillas de ajwain","3 cucharaditas de aceite de girasol (divididas)"],
["En una sartén de base gruesa, caliente 1 cucharadita de aceite a fuego medio-alto. Agregue las semillas de ajwain, el jengibre y el chile. Cocine durante aproximadamente 1 minuto, revolviendo con frecuencia.","Agregue las espinacas y 1/4 de cucharadita de sal. Cocine durante 3 minutos, o hasta que se absorba la humedad que sueltan las espinacas y la base quede seca. Agregue el polvo de amchoor y el comino, revolviendo bien. Retire del fuego. Reserve para que se enfríe.","Para preparar la masa de los parathas: mezcle 2 tazas de harina y el 1/4 de cucharadita de sal restante en un plato hondo. Agregue la mezcla de espinacas a la mezcla de harina. Agregue el agua, poco a poco, para formar una masa suave (con una consistencia similar a la de una masa de pizza). Amase hasta que quede suave. Páselo a un tazón de vidrio. Cubra con una toalla húmeda. Reserve de 30 minutos a una hora a temperatura ambiente.","Pasado el tiempo de reposo, amase la masa una vez más. Forme 8 bolas. Espolvoree ligeramente su superficie de trabajo con la 1 cucharada de harina restante. Con un rodillo, aplane cada bola de masa hasta que mida 6 pulgadas de diámetro.","Precaliente una plancha de hierro fundido o una sartén plana a fuego medio-alto. Coloque una pieza de masa en la sartén. Cocine durante aproximadamente 1 minuto, o hasta que empiece a hacer burbujas.","Voltee el paratha. Unte con 1/4 de cucharadita del aceite restante. Continúe cocinando de 3 a 4 minutos por lado, volteándolo según sea necesario, hasta que los bordes estén dorados por ambos lados. Con una espátula plana, presione el centro del paratha mientras se cocina para que se cocine de manera uniforme.","Retire de la sartén. Repita el proceso de cocción con las piezas de masa restantes y el aceite restante. Sirva caliente."],[],[]),
ar=("باراثا السبانخ بالقمح الكامل","الباراثا نوع من الخبز المسطح نشأ في شمال الهند، حيث لا يزال شائعًا. وهو جزء من وجبة الفطور الهندية التقليدية، لكن يمكن تقديمه أيضًا مع الغداء أو العشاء.","8","1 باراثا",
["⅔ كوب ماء","2 كوب زائد 1 ملعقة كبيرة دقيق القمح الكامل للمعجنات (مقسّم)","1 ملعقة صغيرة كمون مطحون","½ ملعقة صغيرة مسحوق أمتشور (المانجو)","½ ملعقة صغيرة ملح بحري ناعم (يُستخدم على مرتين)","1 كوب سبانخ صغيرة (مكبوسة جيدًا ومفرومة)","1 حبة فلفل أخضر حار كاملة (مُزالة البذور ومفرومة ناعمًا جدًا)","1 ملعقة كبيرة زنجبيل طازج (مبشور)","1 ملعقة صغيرة بذور أجوان","3 ملعقة صغيرة زيت عباد الشمس (يُستخدم على مرات)"],
["في مقلاة ذات قاع سميك، سخّن 1 ملعقة صغيرة من الزيت على حرارة متوسطة عالية. أضف بذور الأجوان والزنجبيل والفلفل الحار. اطهِ لمدة دقيقة واحدة تقريبًا مع التحريك باستمرار.","أضف السبانخ و¼ ملعقة صغيرة من الملح. اطهِ لمدة 3 دقائق، أو حتى تمتص الرطوبة التي تخرج من السبانخ ويصبح القاع جافًا. أضف مسحوق الأمتشور والكمون مع التقليب جيدًا. ارفع المقلاة عن النار. اتركها جانبًا لتبرد.","لتحضير عجينة الباراثا: اخلط 2 كوب من الدقيق و¼ ملعقة صغيرة المتبقية من الملح في طبق واسع. أضف خليط السبانخ إلى خليط الدقيق. أضف الماء قليلًا قليلًا لتكوين عجينة ناعمة (بقوام يشبه عجينة البيتزا). اعجن العجينة حتى تصبح ناعمة. انقلها إلى وعاء زجاجي. غطِّها بمنشفة رطبة. اتركها جانبًا لمدة 30 دقيقة إلى ساعة في درجة حرارة الغرفة.","بعد مدة الراحة، اعجن العجينة مرة أخرى. شكّلها إلى 8 كرات. رشّ سطح العمل برفق بـ 1 ملعقة كبيرة المتبقية من الدقيق. باستخدام الشوبك، افرد كل كرة عجين حتى يصبح قطرها 6 بوصات.","سخّن صاجًا من الحديد الزهر أو مقلاة مسطحة على حرارة متوسطة عالية. ضع قطعة عجين واحدة في المقلاة. اطهِ لمدة دقيقة واحدة تقريبًا، أو حتى تبدأ بتكوين فقاعات.","اقلب الباراثا. افرد عليها ¼ ملعقة صغيرة من الزيت المتبقي بالفرشاة. تابع الطهي لمدة 3-4 دقائق من كل جانب، مع القلب عند الحاجة، حتى تصبح الحواف بنية من الجانبين. باستخدام ملعقة مسطحة، اضغط على وسط الباراثا أثناء طهيها لكي تنضج بالتساوي.","ارفعها من المقلاة. كرر عملية الطهي مع قطع العجين المتبقية والزيت المتبقي. قدّمها ساخنة."],[],[])))
O.append(R(6541626,
ar=("أسياخ الكابريزي","هذه المقبلات السهلة مثالية للصيف وتستخدم مكونات طازجة من الحديقة. هذه الأسياخ مليئة بالنكهة وقليلة الكربوهيدرات. كما أنها تبدو جميلة على طبق التقديم وستبهر الضيوف بالتأكيد!","18","1 سيخ",
["18 سيخًا صغيرًا من الخيزران","18 ورقة ريحان طازجة (مطوية إلى نصفين)","18 حبة طماطم عنب متوسطة","18 كرة موزاريلا طازجة كاملة (¼ أونصة لكل كرة)","1 ملعقة كبيرة زيت زيتون","1½ ملعقة كبيرة خل بلسمي"],
["ضع حبة طماطم عنب واحدة وورقة ريحان واحدة وكرة موزاريلا واحدة على كل سيخ خيزران. كرر هذه العملية للحصول على 18 سيخًا. ضع الأسياخ على طبق التقديم.","في وعاء صغير، اخفق زيت الزيتون والخل البلسمي. قبل التقديم مباشرة، رش الصلصة فوق الأسياخ لتتغطى بالتساوي."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c15_part2.json")
