from h import *
O=[]
O.append(R(6551436,
ar=("رغيف لحم بالأعشاب والثوم اقتصادي","رغيف اللحم المالح الاقتصادي هذا لا يقل جودة عن رغيف اللحم الكلاسيكي. نسختنا المناسبة لمرضى السكري محضّرة من لحم الديك الرومي المفروم الخالي من الدهون ومتبّلة بالأعشاب الطازجة والثوم. لوجبة كاملة، قدّمه مع بطاطا حلوة محمصة (يمكن تحميصها في الفرن بجانب رغيف اللحم) وطبق جانبي من الخضار غير النشوية أو سلطة خضراء بسيطة.\n\nPowered by Homemade","6","1 شريحة",
["1 بخّة (0.25 غرام) بخاخ طهي غير لاصق","1 شريحة خبز قمح كامل","¼ كوب بديل البيض","20 أونصة لحم ديك رومي مفروم خالٍ من الدهون","2 فص ثوم (مفروم)","1 ملعقة كبيرة أوريغانو طازج","1 ملعقة كبيرة ريحان طازج (مفروم)","½ كوب كاتشب (مقسّم)","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة خل بلسمي"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190 درجة مئوية). ادهن قالب رغيف ببخاخ الطهي. ضعه جانبًا.","في وعاء متوسط، فتّت شريحة خبز القمح الكامل إلى قطع بحجم حبة البازلاء. أضف البيض واخلط جيدًا.","أضف الديك الرومي والثوم والأوريغانو والريحان و¼ كوب من الكاتشب والملح (اختياري) والفلفل الأسود المطحون. اخلط جيدًا.","اضغط خليط الديك الرومي في قالب الرغيف بإحكام. ضعه في الفرن ليُخبز لمدة 20 دقيقة.","بينما يُخبز رغيف اللحم، اخفق ¼ كوب المتبقي من الكاتشب والخل البلسمي والصلصة الحارة (اختياري).","بعد أن يُخبز رغيف اللحم لمدة 20 دقيقة، اسكب طلاء الكاتشب والخل البلسمي فوق الرغيف. أعده إلى الفرن ليُخبز 15 دقيقة إضافية أو حتى تبلغ درجة الحرارة الداخلية للرغيف 165 درجة فهرنهايت (75 درجة مئوية).","اترك رغيف اللحم ليرتاح لمدة 10 دقائق، ثم قطّعه إلى 6 حصص متساوية."],[],[])))
O.append(R(6551703,
es=("Cómo preparar una ensalada de cosecha",None,"4","1/2 taza",
["1/4 de taza de vinagre de sidra de manzana","1/4 de cucharadita de sal","1 cucharadita de mostaza Dijon","2 cucharadas de aceite de oliva","1 1/2 cucharadas de menta fresca (hojas, picadas finas, y un poco más para decorar)","12 oz de mezcla de verduras de hoja verde (1 bolsa, mezcla de hojas tiernas)","2 rábanos enteros (en rodajas finas)","1/2 taza de guisantes dulces (cortados en trozos de 1/2 pulgada)","1/8 de cucharadita de pimienta negra (recién molida, al gusto)","4 cucharadas de pepitas (tostadas)","2 cucharadas de semillas de granada"],
["Para preparar la vinagreta de sidra de manzana: vierta el vinagre de sidra de manzana en un tazón o en un frasco pequeño con tapa. Agregue 1/4 de cucharadita de sal y agite o bata para combinar.","Agregue la mostaza Dijon y el aceite de oliva, y agite con fuerza o bata bien para combinar.","Agregue la menta recién picada justo antes de aderezar la ensalada (de lo contrario se pondrá oscura).","Para preparar la ensalada: en un tazón grande, mezcle las verduras de hoja verde, los rábanos, los guisantes dulces, la mitad de las pepitas y la mitad de las semillas de granada.","Agregue unas cucharadas del aderezo y mezcle. Las hojas verdes deben quedar apenas cubiertas con el aderezo.","Pruebe y sazone con pimienta negra recién molida según sea necesario. Decore con las pepitas y las semillas de granada restantes antes de servir."],[],[]),
ar=("طريقة تحضير سلطة الحصاد",None,"4","½ كوب",
["¼ كوب خل التفاح","¼ ملعقة صغيرة ملح","1 ملعقة صغيرة خردل ديجون","2 ملعقة كبيرة زيت زيتون","1½ ملعقة كبيرة نعناع طازج (أوراق، مفرومة ناعمًا، مع كمية إضافية للتزيين)","12 أونصة خضروات ورقية مشكلة (كيس واحد، أوراق صغيرة مشكلة)","2 حبة فجل كاملة (مقطعة إلى شرائح رفيعة)","½ كوب بازلاء سكر (مقطعة إلى قطع بحجم ½ بوصة)","⅛ ملعقة صغيرة فلفل أسود (مطحون طازجًا، حسب الذوق)","4 ملعقة كبيرة بيبيتاس (بذور يقطين محمصة)","2 ملعقة كبيرة بذور رمان"],
["لتحضير صلصة خل التفاح: اسكب خل التفاح في وعاء أو في برطمان صغير بغطاء. أضف ¼ ملعقة صغيرة من الملح ورجَّ أو اخفق حتى يمتزج.","أضف خردل ديجون وزيت الزيتون ورجَّ بقوة أو اخفق جيدًا حتى يمتزج.","أضف النعناع الطازج المفروم قبل تتبيل السلطة مباشرة (وإلا سيتحول لونه إلى البني).","لتحضير السلطة: في وعاء كبير، قلّب الخضروات الورقية والفجل وبازلاء السكر ونصف كمية البيبيتاس ونصف كمية بذور الرمان.","أضف بضع ملاعق كبيرة من الصلصة وقلّب. يجب أن تتغطى الأوراق الخضراء بالصلصة بالكاد.","تذوّق وتبّل بالفلفل الأسود المطحون طازجًا حسب الحاجة. زيّن بالبيبيتاس وبذور الرمان المتبقية قبل التقديم."],[],[])))
O.append(R(6551725,
es=("Pudín de calabaza y vainilla","¡Las cálidas especias de otoño hacen de este pudín cremoso un postre festivo para las fiestas!","8","1/2 taza",
["1/4 de taza de sustituto de azúcar bajo en calorías","2 cucharadas de maicena","1 3/4 tazas de leche al 1 %","2 huevos grandes","8 oz de calabaza en lata","1 cucharadita de canela molida","1/4 de cucharadita de clavo molido","1/4 de cucharadita de jengibre molido","1/8 de cucharadita de nuez moscada molida","1 vaina de vainilla entera","1/4 de taza de nueces pecanas","8 cucharadas de cobertura batida (light)"],
["En una cacerola de 3 cuartos de galón, bata el edulcorante y la maicena.","En un tazón pequeño, bata la leche y las yemas de huevo. A fuego medio, incorpore lentamente la mezcla de huevo a la mezcla de edulcorante batiendo. Lleve a ebullición, sin dejar de batir la mezcla hasta que espese, unos 3 a 5 minutos.","Agregue la calabaza, la canela, el clavo, el jengibre y la nuez moscada. Mezcle bien y cocine a fuego bajo durante 3 minutos. Agregue las semillas de la vaina de vainilla y cocine 1 minuto más.","Retire la cacerola de la estufa. Pase el pudín a un tazón y cúbralo con envoltura plástica. Refrigere durante 1 hora antes de servir. Para servir, reparta el pudín con una cuchara en platos individuales, cubra cada plato con 1/2 cucharada de nueces pecanas y espolvoree con canela. Si lo desea, agregue una cucharada de cobertura batida."],[],[]),
ar=("بودينغ القرع والفانيليا","تجعل توابل الخريف الدافئة هذا البودينغ الكريمي حلوى احتفالية للأعياد!","8","½ كوب",
["¼ كوب بديل سكر قليل السعرات","2 ملعقة كبيرة نشا الذرة","1¾ كوب حليب 1%","2 بيضة كبيرة","8 أونصة قرع معلب","1 ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة قرنفل مطحون","¼ ملعقة صغيرة زنجبيل مطحون","⅛ ملعقة صغيرة جوزة الطيب المطحونة","1 عود فانيليا كامل","¼ كوب جوز البقان","8 ملعقة كبيرة كريمة مخفوقة (خفيفة)"],
["في قدر سعة 3 كوارت، اخفق المحلّي ونشا الذرة.","في وعاء صغير، اخفق الحليب وصفار البيض. على حرارة متوسطة، أضف خليط البيض ببطء إلى خليط المحلّي مع الخفق. اتركه حتى يغلي مع مواصلة خفق الخليط حتى يثخن، حوالي 3 إلى 5 دقائق.","أضف القرع والقرفة والقرنفل والزنجبيل وجوزة الطيب. اخلط جيدًا واطهِ على نار هادئة لمدة 3 دقائق. أضف بذور عود الفانيليا واطهِ دقيقة إضافية.","ارفع القدر عن الموقد. ضع البودينغ في وعاء وغطِّه بغلاف بلاستيكي. ضعه في الثلاجة لمدة ساعة واحدة قبل التقديم. عند التقديم، اغرف البودينغ في أطباق فردية، وضع فوق كل طبق ½ ملعقة كبيرة من جوز البقان، ورشّ القرفة. إذا رغبت، أضف فوقها كمية من الكريمة المخفوقة."],[],[])))
O.append(R(6552861,
es=("Coles de Bruselas asadas con miel y mostaza","Asar las verduras hace que salgan a la superficie sus azúcares naturales, lo que las vuelve menos amargas y deliciosas. La salsa de miel y mostaza aporta a estas coles de Bruselas un toque dulce y ácido.","9","1 taza",
["2 libras de coles de Bruselas (con la base recortada)","2 cucharadas de aceite de oliva","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra","2 cucharadas de mostaza Dijon de grano grueso","1 cucharada de miel"],
["Precaliente el horno a 425° F. Cubra una bandeja plana para hornear con papel pergamino.","En un tazón grande, mezcle las coles recortadas con el aceite de oliva, la sal y la pimienta. Coloque las coles en una sola capa sobre la bandeja cubierta con papel pergamino.","Ase las coles de Bruselas durante unos 45 minutos o hasta que estén crujientes, moviendo la bandeja aproximadamente cada 15 minutos.","En un tazón pequeño, mezcle la mostaza y la miel. Cuando las coles estén listas, páselas a un tazón para servir. Agregue la mezcla de miel y mostaza y mezcle bien. Sirva de inmediato."],[],[]),
ar=("كرنب بروكسل محمص بالعسل والخردل","يُبرز التحميص السكريات الطبيعية في الخضار إلى السطح مما يجعلها أقل مرارة ولذيذة. تضيف صلصة العسل والخردل لمسة حلوة وحامضة إلى كرنب بروكسل هذا.","9","1 كوب",
["2 رطل كرنب بروكسل (مقطوعة القواعد)","2 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة خردل ديجون خشن","1 ملعقة كبيرة عسل"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية). بطّن صينية خبز مسطحة بورق الزبدة.","في وعاء كبير، قلّب الكرنب المقطوع مع زيت الزيتون والملح والفلفل. ضع الكرنب في طبقة واحدة على الصينية المبطنة بورق الزبدة.","حمّص كرنب بروكسل لمدة 45 دقيقة تقريبًا أو حتى يصبح مقرمشًا، مع هز الصينية كل 15 دقيقة تقريبًا.","اخلط الخردل والعسل في وعاء صغير. عندما ينضج الكرنب، ضعه في وعاء التقديم. أضف خليط العسل والخردل وقلّب جيدًا. قدّمه فورًا."],[],[])))
O.append(R(6553465,
es=("Avena con manzana y canela","Las manzanas frescas hacen de esta avena el desayuno perfecto de otoño. Un toque de especias añade profundidad de sabor a esta avena con manzana y canela, apta para personas con diabetes, que le encantará a toda la familia.","4","1/2 taza de avena + 1/4 de manzana",
["1 taza de avena en hojuelas tradicional (en seco)","2 tazas de agua","1 taza de leche descremada","1 manzana mediana (pelada, sin corazón y en cubos)","1 cucharadita de canela molida","1/4 de cucharadita de nuez moscada molida","1/4 de cucharadita de sal"],
["En una cacerola, lleve el agua a ebullición.","Agregue la avena y reduzca el fuego a medio-bajo. Cocine, revolviendo de vez en cuando, durante unos 5 minutos o hasta que la avena comience a espesar.","Agregue la leche, la manzana en cubos, la canela, la nuez moscada y la sal. Continúe cocinando, revolviendo con frecuencia, hasta que la avena esté cremosa y las manzanas estén tiernas (unos 5 minutos más).","Retire del fuego y deje reposar un minuto para que espese.","Divida la avena en dos tazones. Sirva tibia."],[],[]),
ar=("شوفان بالتفاح والقرفة","يجعل التفاح الطازج هذا الشوفان وجبة فطور مثالية للخريف. رشة من التوابل تضيف عمقًا في النكهة إلى شوفان التفاح والقرفة هذا المناسب لمرضى السكري، والذي ستحبه العائلة كلها.","4","½ كوب شوفان + ¼ تفاحة",
["1 كوب شوفان مجروش تقليدي (جاف)","2 كوب ماء","1 كوب حليب خالٍ من الدسم","1 حبة تفاح متوسطة (مقشرة ومنزوعة القلب ومقطعة إلى مكعبات)","1 ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة جوزة الطيب المطحونة","¼ ملعقة صغيرة ملح"],
["في قدر، اترك الماء حتى يغلي.","أضف الشوفان وقلّب، ثم اخفض الحرارة إلى متوسطة منخفضة. اطهِ مع التحريك من حين لآخر لمدة 5 دقائق تقريبًا أو حتى يبدأ الشوفان بالثخونة.","أضف الحليب والتفاح المقطع إلى مكعبات والقرفة وجوزة الطيب والملح. تابع الطهي مع التحريك المتكرر حتى يصبح الشوفان كريميًا والتفاح طريًا (حوالي 5 دقائق أخرى).","ارفعه عن النار واتركه دقيقة ليثخن.","قسّم الشوفان إلى وعاءين. قدّمه دافئًا."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c15_part4.json")
