from mk import *
R=[]
G="Untuk garnish"
R.append((9873294,"Crostini Vegan dengan \"Ricotta\" + Jamur","Crostini vegan yang renyah, beraroma keju, segar, dan sangat lezat untuk hidangan pembuka yang sempurna, untuk waktu makan apa pun.","6 Porsi","1 porsi",
["1 baguette atau roti pilihan","454 gram (16 ounce) jamur cremini, diiris tipis","garam + merica secukupnya",("Untuk ricotta vegan","350 gram (12 ounce) blok tahu ekstra padat, ditiriskan (pilih yang bebas GMO jika memungkinkan)"),("Untuk ricotta vegan","¼ cangkir nutritional yeast"),("Untuk ricotta vegan","3 sendok makan cuka sari apel"),("Untuk ricotta vegan","1 sendok teh garam laut"),("Untuk ricotta vegan","½ sendok teh bawang putih bubuk"),(G,"glasir balsamik"),(G,"basil segar yang baru dicincang")],
["Panaskan oven terlebih dahulu hingga 375℉/190℃ mode bake. Lalu iris baguette Anda setebal seperempat inci, dan susun dalam satu lapisan di atas loyang besar (atau dua jika perlu). Panggang roti selama 5-8 menit, atau hingga keemasan dan renyah.","Sementara itu, tumis jamur tanpa minyak dengan sedikit garam + merica (jamur akan mengeluarkan banyak air dan tidak boleh menempel di wajan) hingga menyusut, sekitar 3-4 menit. Sisihkan.","Selanjutnya, masukkan semua bahan ricotta ke dalam food processor dan proses hingga sebagian besar halus dan tercampur. Teksturnya harus kental, tetapi dapat dioleskan.","Rakit crostini vegan Anda dengan mengoleskan ricotta pada setiap irisan roti panggang, lalu beri topping beberapa irisan jamur, dan terakhir siramkan glasir balsamik dan taburi dengan basil cincang."],
["Siapkan sebelumnya dengan membuat campuran keju ricotta dan simpan di lemari es hingga siap digunakan.","Rencanakan untuk menikmati crostini ini segera, karena paling enak saat baru dibuat.","Resep crostini vegan ini menghasilkan sekitar 4 porsi sebagai makanan utama, atau 6-8 porsi sebagai hidangan pembuka. Informasi nutrisi di atas mewakili 6 porsi sekitar 2-3 irisan crostini beserta topping-nya. (Ini akan bervariasi tergantung ukuran roti dan ketebalan irisan Anda.)"],[]))
R.append((9874640,"Susu Mete Buatan Sendiri yang Mudah","Susu mete buatan sendiri yang sangat mudah adalah alternatif sempurna untuk pilihan susu bebas produk susu. Gunakan dengan rasio satu banding satu sebagai pengganti susu sapi.","5 Cangkir","0.5 Cangkir",
["1 cangkir mete mentah yang direndam dalam air mendidih selama 30 menit","4 cangkir air saring",("Pemanis Opsional","1-2 sendok makan sirup maple"),("Pemanis Opsional","1-2 kurma tanpa biji")],
["Tiriskan mete dan masukkan ke dalam blender bersama air dan pemanis pilihan Anda, jika digunakan, lalu haluskan hingga lembut.","Menggunakan Bigger & Better Nut Milk Bag Anda, (atau yang setara), saring susu ke dalam teko untuk menghilangkan potongan dan ampas yang tersisa sehingga Anda mendapatkan susu mete yang halus dan lembut sempurna."],
["Simpan di lemari es dalam wadah tertutup atau teko bertutup. Konsumsi dalam 5 hari."],[]))
R.append((9876454,"Bruschetta ai funghi [Bruschetta Jamur]","Gurih, beraroma tanah, dan penuh rasa — resep bruschetta ai funghi ini sempurna.","6 Porsi","2 irisan",
["1 baguette, diiris setebal ¼ inci","227 gram jamur putih atau cremini, diiris","1 siung bawang putih, dicincang halus","1 sendok makan kecap asin","1 tomat roma, dipotong dadu","1 sendok makan cuka balsamik","1 sendok makan air lemon","2 sendok makan basil segar, dicincang","garam + merica secukupnya"],
["Panaskan oven terlebih dahulu hingga 375℉/190℃ dan siapkan loyang besar.","Sambil menunggu oven panas, tumis jamur, bawang putih, dan kecap asin hingga menyusut. Sisihkan.","Iris roti dan susun dalam satu lapisan, dan panggang selama 5-8 menit, hingga berwarna keemasan.","Saat roti dipanggang, campurkan jamur tumis dengan semua bahan yang tersisa (kecuali roti) dalam mangkuk adonan. Cicipi garam dan merica, dan sesuaikan jika perlu.","Setelah roti panggang dan keemasan, sendokkan campuran ke atas irisan roti dan sajikan."],
["Rencanakan untuk menikmati bruschetta ai funghi Anda segera, karena paling enak saat baru dibuat.","Informasi nutrisi didasarkan pada pengirisan baguette Anda menjadi 12 irisan, dan ukuran porsi mewakili sekitar 2 irisan bruschetta jamur."],[]))
S1="Untuk Salad";S2="Untuk Dressing"
R.append((9877958,"Salad Cranberry Brokoli dengan Dressing Biji Poppy [Bebas Minyak]","Cerah, menyenangkan, dan lezat! Salad cranberry brokoli ini renyah, kaya, perpaduan manis dan asam, dan sangat menggoda. Sempurna untuk hari raya, pesta kolam renang, atau pot luck.","6 Porsi","1 porsi",
[(S1,"6 cangkir kuntum brokoli, dipotong menjadi potongan kecil seukuran suapan"),(S1,"1 kaleng 15 oz buncis (chickpea), ditiriskan & dibilas"),(S1,"½ cangkir pecan atau kenari"),(S1,"½ cangkir cranberry kering tanpa pemanis"),(S1,"¼ cangkir bawang merah, dicincang halus"),(S1,"1 apel hijau, dipotong dadu"),(S1,"1 sendok makan air lemon"),(S2,"¾ cangkir mete mentah*"),(S2,"¾ cangkir air"),(S2,"3 sendok makan air lemon atau cuka sari apel"),(S2,"2 sendok makan sirup maple"),(S2,"¼ sendok teh garam laut"),(S2,"1 sendok teh biji poppy")],
["Potong dadu apel Anda dan letakkan dalam mangkuk besar. Lalu peras air lemon segar di atasnya agar tidak menjadi cokelat dan aduk rata. Tambahkan semua bahan salad yang tersisa ke dalam mangkuk yang sama dan aduk bersama.","Masukkan semua bahan dressing KECUALI biji poppy ke dalam blender dan proses hingga halus. Lalu tambahkan biji poppy dan blender selama 1-2 detik, cukup untuk mencampurnya ke dalam dressing Anda. Tuang dressing di atas salad, aduk rata dan dinginkan di lemari es selama 1 jam atau lebih lama, sebelum disajikan."],
["* Jika Anda tidak punya blender bertenaga, seperti Vitamix atau Blendtec, rendam mete Anda dalam air mendidih setidaknya 30 menit, lalu tiriskan sebelum diblender. Ini akan membantu melunakkan mete Anda cukup agar dapat diblender halus. Anda akan melihat bahwa resep ini menggunakan air lemon dua kali. Penggunaan pertama untuk mencegah apel menjadi cokelat, sekaligus untuk rasa. Penggunaan kedua untuk dressing salad biji poppy. Keduanya diperlukan. Gunakan apel yang asam, seperti granny smith untuk rasa asam terbaik. Jangan memblender biji poppy dengan dressing Anda. Pastikan menambahkannya hanya SETELAH dressing Anda selesai diproses. Untuk rasa terbaik, dinginkan selama 1 jam (atau lebih) sebelum disajikan. Namun, jika waktu tidak memungkinkan, Anda dapat langsung menikmatinya."],[]))
W="Bahan Basah";D="Bahan Kering";X="Petunjuk Pengukusan";Y="Petunjuk Pemanggangan";Z="Petunjuk Instant Pot";O="Panggang Opsional"
R.append((9882145,"Hot Dog Vegan [Seitan Dog]","Seitan dog ini penuh rasa, mudah dibuat dan lebih sehat daripada yang dibeli di toko! Sempurna untuk acara barbekyu!","8 Seitan Dog","1 porsi",
[(W,"1 cangkir kacang cannellini putih, ditiriskan, dibilas + ditepuk kering"),(W,"1 cangkir kaldu sayuran rendah natrium"),(W,"3 sendok makan kecap asin"),(W,"2 sendok makan pasta tomat"),(W,"1 sendok makan sirup maple"),(W,"1 sendok makan cuka sari apel"),(D,"270 gram vital wheat gluten, sekitar 2 cangkir"),(D,"3 sendok teh bawang bombai bubuk"),(D,"2.5 sendok teh bawang putih bubuk"),(D,"2 sendok teh paprika asap atau manis"),(D,"1 sendok teh garam laut"),(D,"½ sendok teh bumbu unggas (poultry seasoning)"),(D,"½ sendok teh ketumbar bubuk"),(D,"¼ sendok teh kunyit"),(D,"¼ sendok teh pala"),(D,"¼ sendok teh lada hitam"),("Topping Opsional","roti hot dog"),("Topping Opsional","mustard, saus tomat, relish, jalapeno, cabai, coleslaw")],
["Panaskan oven terlebih dahulu hingga 350 derajat F (jika menggunakan metode oven) dan sobek 8 lembar aluminium foil (dan kertas roti jika Anda lebih suka foil tidak menyentuh makanan Anda) dan sisihkan.","Masukkan kacang putih ke dalam mangkuk adonan dan tumbuk perlahan dengan garpu besar atau penumbuk kentang. (Tidak perlu ditumbuk sepenuhnya, beberapa potongan yang lebih kasar tidak masalah.) Lalu tambahkan semua bahan BASAH yang tersisa ke dalam mangkuk yang sama dan aduk rata.","Sekarang tambahkan SEMUA bahan kering dan mulai aduk hingga sebagian besar menyatu menjadi bola adonan. Lalu pindahkan ke talenan atau permukaan kerja bersih untuk diuleni sekitar 1 menit, hingga Anda mendapatkan campuran yang tercampur baik, tetapi jangan terlalu lama menguleni.","Bagi menjadi 8 bagian dan gulung setiap bagian menjadi bentuk silinder untuk membuat hot dog vegan Anda. (Jangan khawatir jika bergelombang, akan menjadi halus saat dimasak.) Lalu bungkus setiap seitan dog Anda dengan kertas roti (jika digunakan) dan aluminium foil dan pilin ujungnya untuk mengunci bagian dalam. (Lihat foto proses di atas sebagai gambaran visual.) Pilih metode memasak di bawah ini.",(X,"Didihkan panci besar berisi air beberapa inci dan letakkan keranjang pengukus di dalamnya. Pastikan keranjang tidak menyentuh air. Setelah mendidih, kecilkan api untuk menjaga didihan kecil/mendidih perlahan dan letakkan seitan dog Anda di dalamnya. Tutup dengan penutup dan kukus selama 45-55 menit, balik di tengah waktu. Periksa air Anda sesekali dan tambahkan air panas JIKA perlu. Angkat hot dog dari keranjang dan biarkan dingin selama 5 menit sebelum melepas foil."),(Y,"Letakkan seitan dog yang sudah dibungkus di atas loyang dan panggang selama 45 menit, balik di tengah waktu. Keluarkan dari oven dan biarkan dingin sekitar 5 menit, sebelum melepas foil."),(Z,"Tambahkan 1.5 cangkir air ke dasar Instant Pot Anda. Lalu letakkan trivet di dalam panci. Susun seitan dog yang sudah dibungkus di atas trivet, tumpuk sesuai kebutuhan. Lalu tutup dan pastikan katup berada pada posisi menutup. Kukus selama 45 menit dan biarkan panci Anda melepaskan tekanan secara alami hingga pin turun. Angkat setelah aman."),(O,"Anda dapat langsung menikmatinya setelah dipanggang atau dikukus. ATAU, Anda dapat memanggang seitan dog di panggangan untuk mendapatkan garis panggangan yang indah. Olesi hot dog vegan Anda dengan minyak (jika Anda mau) dan taburi sedikit garam dan merica tambahan. Lalu panggang selama 1-2 menit untuk meningkatkan rasa."),(O,"Sajikan dengan roti hot dog dan semua topping favorit Anda. Selamat menikmati!")],
["Untuk akurasi terbaik, timbang vital wheat gluten Anda. Jika Anda tidak punya timbangan dapur, gunakan 2 cangkir. Pastikan mengaduk adonan Anda dengan baik untuk rasa yang merata dan tekstur terbaik, tetapi jangan terlalu lama menguleni. Menguleni selama 1-2 menit sudah sempurna. Jangan terlalu repot membentuk hot dog yang sempurna. Bentuknya akan bergelombang sebelum dimasak, tetapi menjadi halus saat dimasak. Jika Anda tidak suka foil menyentuh makanan, gunakan kertas roti di antara seitan dog dan lapisan aluminium foil. Untuk sosis vegan pedas, tambahkan 1 sendok teh serpihan cabai ke dalam campuran. Untuk persiapan lebih awal: Siapkan sepenuhnya + masak hot dog Anda 1-2 hari sebelumnya menggunakan metode pilihan (kukus atau panggang) lalu panggang di panggangan sesaat sebelum disajikan. Sisa makanan dapat disimpan di lemari es hingga 5 hari atau dibekukan hingga 3 bulan. Bagaimana saya tahu sudah matang? Kupas foil dengan perlahan, hot dog harus tampak halus. Anda dapat menusuknya dengan jari atau penjepit untuk menguji kepadatannya. Hot dog harus terasa padat tetapi masih sedikit memberi saat ditekan. Hot dog akan semakin padat saat dingin."],[]))
R.append((9882257,"Muffin Pisang Buncis","Lembap, bergizi, dan kaya protein—muffin pisang buncis ini adalah variasi sehat yang lezat dari favorit klasik.","12 Muffin","1 porsi",
["2 cangkir (kaleng 18 ounce) buncis (chickpea), ditiriskan + dibilas","3 pisang sedang, 1 cangkir ditumbuk","½ cangkir tahini atau selai almond","¼ cangkir gula kelapa tidak murni","1.5 cangkir oat gulung, bebas gluten jika diinginkan","1 sendok makan ekstrak vanila murni","2 sendok teh baking powder",("Topping opsional","irisan pisang, choco chip, blueberry, kacang")],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan gunakan cetakan muffin yang diolesi lemak atau alasi cetakan muffin dengan cup muffin.","Tumbuk pisang Anda untuk memastikan Anda memiliki 1 cangkir pisang tumbuk. Lalu masukkan semua bahan kecuali topping opsional ke dalam food processor Anda. Proses campuran hingga sebagian besar halus.","Bagi adonan ke dalam 12 cetakan muffin Anda dan beri topping pada sebagian atau semua muffin jika Anda mau.","Panggang muffin buncis selama 20-22 menit atau hingga tusuk gigi yang ditusukkan ke tengah muffin keluar hampir bersih. Lalu keluarkan dari oven dan biarkan dingin selama 10-15 menit sebelum dipindahkan ke rak pendingin."],
["Gunakan pisang yang terlalu matang. Semakin matang pisang Anda, semakin banyak rasa, kemanisan, dan kelembapan yang akan ditambahkan pada muffin pisang buncis Anda. Pisang dengan kulit cokelat paling baik.","Gunakan baking powder yang segar dan AKTIF. Baking powder yang sudah dibuka di lemari dapur selama 6+ bulan mungkin kehilangan keefektifannya.","Ukur pisang tumbuk Anda untuk memastikan Anda menggunakan satu cangkir. Ukuran pisang sangat bervariasi. Dua pisang besar atau tiga pisang sedang cocok untuk saya.","Biarkan muffin Anda dingin selama 10-15 menit sebelum mengeluarkannya dari cetakan muffin agar mengeras dan tidak pecah.","Sisa muffin dapat disimpan pada suhu ruang selama 1-2 hari, di lemari es hingga 5 hari atau dibekukan hingga 3 bulan."],[]))
M="Untuk marinasi";SV="Untuk penyajian (opsional)"
R.append((9882910,"Tumis Soy Curl yang Mudah [Tumis Vegan]","Tumis soy curl yang penuh rasa, mudah dibuat, dan siap dalam 30 menit atau kurang.","4 Porsi","1 porsi",
["4 ounce soy curls, sekitar setengah kantong soy curls Butler's","6-8 cangkir sayuran tumis beku",(M,"2 cangkir kaldu sayuran rendah natrium"),(M,"⅓ cangkir kecap asin rendah natrium atau Tamari untuk bebas gluten"),(M,"¼ cangkir cuka beras"),(M,"¼ cangkir air segar"),(M,"2 sendok makan sirup maple"),(M,"2 sendok teh bawang putih bubuk"),(M,"1 sendok teh jahe bubuk"),(M,"2 sendok makan tepung maizena atau tepung tapioka"),(SV,"bihun beras, nasi merah, quinoa, mi sayuran, nasi kembang kol"),(SV,"biji wijen, daun bawang, dan/atau serpihan cabai merah untuk topping")],
["Campurkan semua bahan marinasi kecuali tepung maizena dalam mangkuk besar. Lalu masukkan soy curls kering ke dalam mangkuk, aduk dan biarkan terendam selama 10 menit.","Panaskan wajan besi cor, atau yang serupa dengan api sedang-besar. Lalu angkat soy curls yang sudah dimarinasi dari mangkuk (JANGAN DITIRISKAN - SISIHKAN SAUSNYA) dan letakkan di wajan untuk digoreng hingga kecokelatan, sekitar 4-5 menit, sambil sering diaduk.","Selanjutnya tambahkan sayuran, aduk sesekali selama 4-5 menit lagi.","Sementara itu, aduk tepung maizena ke dalam mangkuk marinasi yang disisihkan. Lalu tuang saus ke dalam wajan berisi soy curls dan sayuran. Biarkan mendidih perlahan dan mengental selama 2-3 menit sebelum disajikan."],
["Gunakan kaldu dan kecap asin rendah natrium untuk marinasi agar hidangan tidak terlalu asin. Gunakan setengah air dan setengah kaldu jika Anda tidak punya kaldu rendah natrium. (Anda selalu dapat menambahkan garam nanti jika perlu.)","Jangan memasak sayuran terlalu lama! Sayuran paling enak saat empuk dan renyah untuk tekstur terbaik.","Simpan sisa makanan di lemari es selama 3-4 hari atau bekukan dalam wadah kedap udara hingga 3 bulan."],[]))
R.append((9889051,"Pancake Blueberry Vegan yang Sehat","Pancake blueberry vegan ini empuk, tebal, bebas gula, dan sangat lezat.","8 pancake","1 pancake",
["1.5 cangkir susu kedelai","1.5 sendok teh cuka sari apel","1 cangkir oat gulung, bebas gluten jika diinginkan","2 sendok makan biji chia","2 sendok makan hemp hearts","⅓ cangkir tepung buncis (chickpea), juga dikenal sebagai tepung garbanzo","2 sendok teh baking powder","1 cangkir blueberry segar"],
["Panaskan wajan datar antilengket Anda dengan api sedang. Lalu masukkan susu kedelai dan cuka sari apel ke dalam mangkuk kecil dan sisihkan agar menggumpal.","Sementara itu, masukkan oat, hemp hearts, dan biji chia ke dalam blender dan proses hingga menyerupai tepung. (Jangan khawatir jika ada beberapa potongan yang lebih kasar.) Pindahkan ke mangkuk adonan besar dan tambahkan tepung buncis dan baking powder lalu kocok hingga tercampur.","Sekarang susu Anda seharusnya sudah menggumpal, jadi tuang ke dalam mangkuk tepung dan aduk hingga tercampur tanpa terlalu lama mengaduk. Lipat masuk blueberry dengan perlahan.","Tuang adonan Anda dengan sendok sayur ke wajan datar yang sudah dipanaskan, buat pancake berdiameter kira-kira 4 inci. Anda dapat menekan pancake perlahan agar sedikit melebar karena adonan tidak akan terlalu cair. Namun, jangan diratakan terlalu banyak karena pancake ini paling enak jika sedikit tebal dan empuk.","Masak selama 4-5 menit hingga keemasan lalu balik dan masak 3-4 menit lagi, hingga matang.","Sajikan dengan lebih banyak blueberry segar, raspberry, parutan kelapa, choco chip, kacang, atau sirup maple."],
["Pastikan baking powder Anda aktif. Jika sudah dibuka dan disimpan di lemari dapur lebih dari 6 bulan, keefektifannya mungkin mulai berkurang.","Oat dan biji-bijian tidak perlu diblender dengan sempurna. Jika ada beberapa bagian bersisik yang tidak mau halus, pancake Anda tetap akan sempurna.","Tidak perlu terlalu lama mengaduk adonan pancake. Jika ada beberapa gumpalan, tidak masalah. Cukup aduk hingga tercampur dan tidak ada sisa tepung.","Gunakan api sedang agar matang merata. Api besar akan memasak bagian luar terlalu cepat, sehingga bagian tengah kurang matang. Tetapi pastikan sudah dipanaskan terlebih dahulu agar pancake Anda tidak lengket!","Sisa makanan dapat disimpan di lemari es selama 3-4 hari atau dibekukan dalam kantong zip-top atau wadah yang aman untuk freezer hingga 3 bulan. Panaskan kembali di pemanggang roti untuk sarapan yang cepat dan mudah."],[]))
build(R,'part6.json')
