from h import *
I=[]
I.append((6040267,{
"en":L("Spinach and Feta Omelet","Fresh green spinach, crisp onions and a touch of creamy feta cheese make this an omelet you will want to prepare again and again.","1",None,
["1/2 cup egg substitute","1 pinch kosher salt","1/4 tsp black pepper","1/4 cup red onion (diced)","1 cup spinach (chopped)","2 tbsp low-fat feta cheese","1/4 cup tomatoes (diced)"],
["In a bowl, season the egg substitute with salt and pepper and mix everything together.","Heat the olive oil in a nonstick skillet over medium heat.","Add the diced red onions and sauté until softened.","Add the chopped spinach to the skillet and cook until wilted.","Pour the eggs over the spinach and onions.","As the eggs begin to set, sprinkle diced tomatoes and crumbled feta cheese over half of the omelet.","Once the eggs are completely cooked, carefully fold the omelet in half with a spatula.","Slide the omelet onto a plate, garnish with fresh herbs if desired, and serve."]),
"ar":L("أومليت السبانخ وجبن الفيتا","سبانخ خضراء طازجة وبصل مقرمش ولمسة من جبن الفيتا الكريمي تجعل من هذا الأومليت طبقًا ستحب تحضيره مرارًا وتكرارًا.","1",None,
["½ كوب بديل البيض","1 رشة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","¼ كوب بصل أحمر (مقطع مكعبات)","1 كوب سبانخ (مفرومة)","2 ملعقة كبيرة جبن فيتا قليل الدسم","¼ كوب طماطم (مقطعة مكعبات)"],
["في وعاء، تبّل بديل البيض بالملح والفلفل وامزج المكونات جيدًا.","سخّن زيت الزيتون في مقلاة غير لاصقة على نار متوسطة.","أضف البصل الأحمر المقطع مكعبات وقلّبه حتى يطرى.","أضف السبانخ المفرومة إلى المقلاة واطهها حتى تذبل.","اسكب البيض فوق السبانخ والبصل.","عندما يبدأ البيض بالتماسك، انثر الطماطم المقطعة مكعبات وجبن الفيتا المفتت على نصف الأومليت.","بعد أن ينضج البيض تمامًا، اطوِ الأومليت إلى نصفين بحرص باستخدام ملعقة تقليب مسطحة.","انقل الأومليت إلى طبق، وزيّنه بالأعشاب الطازجة إن رغبت، وقدّمه."])}))
I.append((6079494,{
"en":L("Romaine Lettuce","One cup of chopped romaine lettuce","1",None,["1 package romaine lettuce"],[]),
"ar":L("خس روماني","كوب واحد من الخس الروماني المفروم","1",None,["1 عبوة خس روماني"],[])}))
I.append((6163468,{
"en":L("Greek Pita Veggie Pizzas","A tasty blend of Mediterranean style and pizza come together in this Greek pita veggie pizza. Packed with nutrient-rich vegetables like red peppers, olives, shallots and artichokes, this quick and easy recipe is ready in under 15 minutes. Try serving it with Mediterranean zucchini for a hearty meal.","4",None,
["4 small whole wheat pitas (4 whole wheat pita rounds, 4 inches each)","1 cup low-sodium jarred pizza sauce (1 cup low-sodium pizza sauce)","1/4 cup low-fat shredded Italian cheese (¼ cup reduced-fat shredded Italian cheese)","1/4 cup Kalamata olives (¼ cup sliced Kalamata olives)","1/4 cup roasted red peppers (¼ cup roasted red peppers, thinly sliced)","1/4 cup marinated artichoke hearts (¼ cup marinated artichoke hearts, chopped)","1 shallot (1 shallot, thinly sliced)","2 oz low-fat feta cheese (2 oz reduced-fat feta cheese, crumbled)","1/2 cup fresh basil (½ cup fresh basil leaves, cut into thin strips)"],
["Preheat the oven to 400 degrees F.","Top the pita bread with sauce, olives, peppers, artichokes, shallot and Italian cheese.","Bake in the oven until the cheese melts and the pita is crisp, 7-8 minutes.","Remove from the oven and top with feta cheese and fresh basil."]),
"ar":L("بيتزا البيتا اليونانية بالخضار","مزيج لذيذ من الطابع المتوسطي والبيتزا يجتمع في بيتزا البيتا اليونانية بالخضار. هذه الوصفة السريعة والسهلة غنية بالخضار الغنية بالعناصر الغذائية مثل الفلفل الأحمر والزيتون والكراث الأخضر (الشالوت) والخرشوف، وتُحضَّر في أقل من 15 دقيقة. جرّب تقديمها مع الكوسا على الطريقة المتوسطية لوجبة مشبعة.","4",None,
["4 أرغفة بيتا صغيرة من القمح الكامل (4 أقراص بيتا من القمح الكامل، قطر كل منها 4 بوصات)","1 كوب صلصة بيتزا قليلة الصوديوم معبأة في برطمان (1 كوب صلصة بيتزا قليلة الصوديوم)","¼ كوب جبن إيطالي مبشور قليل الدسم (¼ كوب جبن إيطالي مبشور مخفض الدسم)","¼ كوب زيتون كالاماتا (¼ كوب زيتون كالاماتا مقطع شرائح)","¼ كوب فلفل أحمر مشوي (¼ كوب فلفل أحمر مشوي، مقطع شرائح رفيعة)","¼ كوب قلوب خرشوف متبلة (¼ كوب قلوب خرشوف متبلة، مفرومة)","1 شالوت (1 حبة شالوت، مقطعة شرائح رفيعة)","2 أونصة جبن فيتا قليل الدسم (2 أونصة جبن فيتا مخفض الدسم، مفتت)","½ كوب ريحان طازج (½ كوب أوراق ريحان طازجة، مقطعة شرائح رفيعة)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (205° مئوية).","غطِّ خبز البيتا بالصلصة والزيتون والفلفل والخرشوف والشالوت والجبن الإيطالي.","اخبزه في الفرن حتى يذوب الجبن ويصبح خبز البيتا مقرمشًا، من 7 إلى 8 دقائق.","أخرجه من الفرن وغطِّه بجبن الفيتا والريحان الطازج."])}))
I.append((6165411,{
"en":L("Roasted Beet and Apple Soup","Earthy and slightly sweet, I love making this scarlet-hued soup in mid to late fall, when apples and beets are at their peak. It is the perfect starter for an autumn-themed meal, and its contrasting sweet and tart flavors complement all kinds of seasonal dishes, from pork and chicken to roasted cauliflower and Brussels sprouts.","6",None,
["1/2 lbs red beets (trimmed and washed (about 3 medium beets))","2 tbsp extra-virgin olive oil","1 leek (sliced (white and pale green parts))","2 cloves garlic (minced)","2 Granny Smith or other tart apples (peeled, cored and diced)","1/8 tsp feta cheese","1/4 cup orange juice (freshly squeezed)","1 tsp orange zest (freshly grated)","4 cups low-sodium vegetable broth (low sodium)","2 tbsp lemon juice (freshly squeezed)","1/4 tsp fine sea salt","1/4 tsp freshly ground black pepper"],
["Preheat the oven to 350°F.","Wrap each beet in a piece of aluminum foil and roast until tender when pierced with a fork, about 1 hour. Remove the beets from the oven, unwrap them and let them cool for 5 minutes. Then peel the beets and cut them into 1/2-inch cubes.","Heat the oil in a medium heavy-bottomed saucepan over medium-high heat. Add the leek and garlic and cook for 5 to 8 minutes or until tender. Add the apples, the chopped beets and the ginger. Cook for 1 to 2 minutes, stirring constantly, then add the orange juice, the orange zest and the broth.","Bring the liquid to a boil, then reduce the heat to low, cover the saucepan and simmer until the vegetables are very tender, about 25 minutes.","Remove the pan from the heat, add the lemon juice and let the soup cool slightly. Carefully transfer the soup to a blender or food processor, in batches if necessary, and puree until smooth. Season with salt and pepper and serve immediately."]),
"ar":L("حساء الشمندر المشوي والتفاح","ترابي الطعم وحلو قليلًا، أحب تحضير هذا الحساء القرمزي اللون في منتصف الخريف أو أواخره، عندما يكون التفاح والشمندر في ذروة نضجهما. إنه مقبّل مثالي لوجبة بطابع خريفي، وتتكامل نكهاته المتباينة بين الحلاوة والحموضة مع جميع الأطباق الموسمية، من لحم الخنزير والدجاج إلى القرنبيط المشوي وكرنب بروكسل.","6",None,
["½ رطل شمندر أحمر (مقطوع الأطراف ومغسول (حوالي 3 حبات شمندر متوسطة))","2 ملعقة كبيرة زيت زيتون بكر ممتاز","1 كراث (مقطع شرائح (الجزء الأبيض والأخضر الفاتح))","2 فص ثوم (مفروم)","2 تفاحة غراني سميث أو تفاح حامض آخر (مقشرة ومنزوعة القلب ومقطعة مكعبات)","⅛ ملعقة صغيرة جبن فيتا","¼ كوب عصير برتقال (طازج)","1 ملعقة صغيرة قشر برتقال (مبشور طازجًا)","4 كوب مرق خضار قليل الصوديوم (قليل الصوديوم)","2 ملعقة كبيرة عصير ليمون (طازج)","¼ ملعقة صغيرة ملح بحري ناعم","¼ ملعقة صغيرة فلفل أسود مطحون طازجًا"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية).","لُفّ كل حبة شمندر بقطعة من ورق الألمنيوم واشوها حتى تلين عند وخزها بالشوكة، حوالي ساعة واحدة. أخرج الشمندر من الفرن وافتح الورق واتركه يبرد 5 دقائق. ثم قشّر الشمندر وقطّعه إلى مكعبات بحجم ½ بوصة.","سخّن الزيت في قدر متوسط سميك القاع على نار متوسطة إلى عالية. أضف الكراث والثوم واطهُ من 5 إلى 8 دقائق أو حتى يلين. أضف التفاح والشمندر المقطع والزنجبيل. اطهُ من دقيقة إلى دقيقتين مع التقليب المستمر، ثم أضف عصير البرتقال وقشر البرتقال والمرق.","اترك السائل حتى يغلي، ثم اخفض النار إلى هادئة وغطِّ القدر واتركه على نار خفيفة حتى تصبح الخضار طرية جدًا، حوالي 25 دقيقة.","ارفع القدر عن النار وأضف عصير الليمون واترك الحساء ليبرد قليلًا. انقل الحساء بحرص إلى الخلاط أو محضّر الطعام، على دفعات إذا لزم الأمر، وهرسه حتى يصبح ناعمًا. تبّله بالملح والفلفل وقدّمه فورًا."])}))
I.append((6192124,{
"en":L("Moroccan Roasted Turkey Breast with Root Vegetables","Moroccan spices like cinnamon, cardamom, cumin and coriander are ideal seasonings for roasted vegetables and meats. During roasting, they bring out the sweetness and deep flavors of whatever they are coating, and their rich, warm flavors transport the taste buds to exotic places. Make this dish in winter, when oranges are in season and cabin fever has started to set in.","12",None,
["1 turkey breast (bone-in, skin-on)","3 tbsp extra-virgin olive oil (divided)","1 tsp fine sea salt (divided)","1 tsp freshly ground black pepper (divided)","2 Moroccan spice blend","5 cloves garlic (placed)","1 onion (halved, peeled, then cut into quarters)","3 stalks celery (trimmed and cut into thirds)","2 cups carrots (peeled, chopped and cut into 2-inch pieces)","2 cups rutabaga (peeled, chopped and cut into 2-inch pieces)","1 cup turnips (peeled, chopped and cut into 2-inch pieces)","1 cup sweet potato (peeled, chopped and cut into 2-inch pieces)","1 tbsp fresh oregano (chopped)","1 tbsp orange zest (freshly grated)","1 orange (halved, then quartered)","1 tsp cumin","1/2 tsp smoked paprika (mild or hot)"],
["Preheat the oven to 425°F.","Loosen the skin of the turkey breast by gently pushing your fingers between the skin and the meat. Season under the skin with 1 tablespoon of olive oil, 1/2 teaspoon of salt and 1/2 teaspoon of pepper. Rub the spice blend under and over the loosened skin, then place the turkey breast in a roasting pan.","In a small bowl, mix the remaining oil, the remaining salt and pepper, the garlic, onion, celery, carrots, rutabaga, turnip, sweet potato, oregano, orange zest, orange, cumin and smoked paprika. Arrange the vegetable mixture in a single layer around the turkey breast.","Transfer the pan to the oven and roast the turkey and vegetables, uncovered, for 15 minutes. Loosely cover the pan with aluminum foil. Reduce the oven temperature to 325°F and roast for 30 to 45 minutes more, or until an instant-read thermometer inserted into the meatiest part of the turkey breast registers 165°F.","Remove the pan from the oven, transfer the turkey to a cutting board and loosely cover it with aluminum foil. Let the turkey rest for 20 minutes, then discard the skin and slice the meat.","Remove and discard the oranges from the roasted vegetables, stir the vegetables well and serve them with the sliced turkey."]),
"ar":L("صدر ديك رومي مشوي على الطريقة المغربية مع الخضار الجذرية","التوابل المغربية مثل القرفة والهيل والكمون والكزبرة هي بهارات مثالية للخضار واللحوم المشوية. فأثناء الشوي، تُبرز حلاوة ما تغطيه ونكهاته العميقة، وتنقل نكهاتها الغنية والدافئة حاسة التذوق إلى أماكن غريبة. حضّر هذا الطبق في الشتاء، عندما يكون موسم البرتقال وعندما يبدأ الملل من البقاء في المنزل.","12",None,
["1 صدر ديك رومي (بالعظم، بالجلد)","3 ملعقة كبيرة زيت زيتون بكر ممتاز (مقسّم)","1 ملعقة صغيرة ملح بحري ناعم (مقسّم)","1 ملعقة صغيرة فلفل أسود مطحون طازجًا (مقسّم)","2 خليط توابل مغربية","5 فص ثوم (موضوع)","1 بصلة (مقطوعة إلى نصفين ومقشرة ثم مقطعة أرباعًا)","3 عروق كرفس (مقطوعة الأطراف ومقطعة أثلاثًا)","2 كوب جزر (مقشر ومفروم ومقطع إلى قطع بحجم 2 بوصة)","2 كوب لفت سويدي (مقشر ومفروم ومقطع إلى قطع بحجم 2 بوصة)","1 كوب لفت (مقشر ومفروم ومقطع إلى قطع بحجم 2 بوصة)","1 كوب بطاطا حلوة (مقشرة ومفرومة ومقطعة إلى قطع بحجم 2 بوصة)","1 ملعقة كبيرة أوريغانو طازج (مفروم)","1 ملعقة كبيرة قشر برتقال (مبشور طازجًا)","1 برتقالة (مقطوعة إلى نصفين ثم أرباع)","1 ملعقة صغيرة كمون","½ ملعقة صغيرة بابريكا مدخنة (حلوة أو حارة)"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية).","أرخِ جلد صدر الديك الرومي بدفع أصابعك برفق بين الجلد واللحم. تبّل تحت الجلد بملعقة كبيرة واحدة من زيت الزيتون و½ ملعقة صغيرة من الملح و½ ملعقة صغيرة من الفلفل. افرك خليط التوابل تحت الجلد المرتخي وفوقه، ثم ضع صدر الديك الرومي في صينية شوي.","في وعاء صغير، اخلط الزيت المتبقي والملح والفلفل المتبقيين والثوم والبصل والكرفس والجزر واللفت السويدي واللفت والبطاطا الحلوة والأوريغانو وقشر البرتقال والبرتقال والكمون والبابريكا المدخنة. وزّع خليط الخضار في طبقة واحدة حول صدر الديك الرومي.","انقل الصينية إلى الفرن واشوِ الديك الرومي والخضار دون غطاء لمدة 15 دقيقة. غطِّ الصينية بورق الألمنيوم بشكل غير محكم. اخفض حرارة الفرن إلى 325° فهرنهايت (160° مئوية) واشوِ من 30 إلى 45 دقيقة إضافية، أو حتى يسجل ميزان حرارة فوري القراءة مغروس في أسمك جزء من صدر الديك الرومي 165° فهرنهايت (75° مئوية).","أخرج الصينية من الفرن، وانقل الديك الرومي إلى لوح التقطيع وغطِّه بورق الألمنيوم بشكل غير محكم. اترك الديك الرومي يرتاح 20 دقيقة، ثم تخلّص من الجلد وقطّع اللحم شرائح.","أخرج البرتقال من الخضار المشوية وتخلّص منه، وقلّب الخضار جيدًا وقدّمها مع شرائح الديك الرومي."])}))
I.append((6270294,{
"en":L("Peanut Butter Chocolate Chip Bars","I boosted this version of a \"blondie\" with the goodness of peanut butter. These bars are a great example of a dessert that is sweet enough, yet ridiculously satisfying!","16",None,
["1 nonstick cooking spray","1 large egg","1 egg white","1/3 cup avocado oil","1/3 cup pure maple syrup (preferably grade B)","1/4 cup banana (mashed)","1/4 cup unsweetened almond milk","1 tsp pure vanilla extract","1/2 cup peanut butter with no added sugar","3/4 cup almond flour","3/4 cup chickpea flour or spelt flour","2 tbsp flaxseeds","1 tsp baking powder (aluminum-free)","1/2 tsp baking soda","1/3 cup dark chocolate chips sweetened with stevia (no added sugars)"],
["Preheat the oven to 350°F. Coat a 9 x 9-inch baking dish with nonstick cooking spray.","In the bowl of an electric mixer, or with a hand mixer, beat the egg, egg white, oil, maple syrup, banana, almond milk, vanilla and peanut butter until smooth. Set the wet ingredients aside.","In a separate large bowl, mix the almond flour, chickpea flour, flaxseeds, baking powder and baking soda.","Add the dry ingredients to the wet ingredients and stir with a wooden spoon or a spatula until well combined. Fold in the chocolate chips. Pour the batter into the prepared baking dish and spread it evenly.","Transfer the pan to the oven and bake for 30 minutes, or until a toothpick inserted in the center comes out clean.","Remove the pan from the oven, let it cool slightly and then cut into 16 bars."]),
"ar":L("ألواح زبدة الفول السوداني ورقائق الشوكولاتة","عززتُ هذه النسخة من حلوى \"البلوندي\" بفوائد زبدة الفول السوداني. هذه الألواح مثال رائع على حلوى حلوة بما يكفي، لكنها مُشبعة بشكل لا يُصدَّق!","16",None,
["1 بخاخ طهي غير لاصق","1 بيضة كبيرة","1 بياض بيضة","⅓ كوب زيت أفوكادو","⅓ كوب شراب القيقب الخالص (يفضل الدرجة B)","¼ كوب موز (مهروس)","¼ كوب حليب لوز غير محلى","1 ملعقة صغيرة مستخلص الفانيليا الخالص","½ كوب زبدة فول سوداني بدون سكر مضاف","¾ كوب دقيق اللوز","¾ كوب دقيق الحمص أو دقيق الإسبلت","2 ملعقة كبيرة بذور الكتان","1 ملعقة صغيرة بيكنج باودر (خالٍ من الألمنيوم)","½ ملعقة صغيرة بيكربونات الصودا","⅓ كوب رقائق شوكولاتة داكنة محلاة بالستيفيا (بدون سكريات مضافة)"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). ادهن طبق خبز مقاس 9 × 9 بوصات ببخاخ الطهي غير اللاصق.","في وعاء الخلاط الكهربائي، أو باستخدام خلاط يدوي، اخفق البيضة وبياض البيضة والزيت وشراب القيقب والموز وحليب اللوز والفانيليا وزبدة الفول السوداني حتى تصبح ناعمة. ضع المكونات السائلة جانبًا.","في وعاء كبير منفصل، اخلط دقيق اللوز ودقيق الحمص وبذور الكتان والبيكنج باودر وبيكربونات الصودا.","أضف المكونات الجافة إلى المكونات السائلة وقلّب بملعقة خشبية أو ملعقة تقليب مسطحة حتى تمتزج جيدًا. اطوِ رقائق الشوكولاتة في الخليط. اسكب العجينة في طبق الخبز المجهّز وافرشها بالتساوي.","انقل الصينية إلى الفرن واخبز لمدة 30 دقيقة، أو حتى تخرج عود الأسنان المغروس في المنتصف نظيفًا.","أخرج الصينية من الفرن واتركها تبرد قليلًا ثم قطّعها إلى 16 لوحًا."])}))
I.append((6270743,{
"en":L("Oven-Fried Chicken","This \"fried\" chicken is not only healthier than traditional fried chicken, but also easier and less fussy to make than the traditional version.","8",None,
["2 cups whole wheat Italian-style bread crumbs","1 clove garlic","1 tbsp Italian seasoning","1/2 cup all-purpose flour","2 large eggs (beaten with 1 tablespoon of water)","4 large egg whites","8 chicken thighs (boneless, skinless, about 2 pounds)"],
["Preheat the oven to 375°F convection or 400°F in a conventional oven. Place the bread crumbs, garlic and stress-free Italian seasoning mix in the food processor. Process until well combined.","Place the flour in a pie dish. Place the eggs and egg whites in a separate pie dish. Place the bread crumb mixture in a third pie dish.","Line a large baking sheet with parchment paper.","Dip the chicken in flour and coat it on all sides, then in egg and then in bread crumbs. Coat evenly. Place it on a baking sheet lined with parchment paper. If you have time, refrigerate the chicken for a while before cooking it.","Bake the chicken for 45 minutes until crispy and well browned. Serve with picnic-style condiments or salads. It can be made ahead and frozen to reheat in a very hot oven. Thaw before reheating."]),
"ar":L("دجاج مقلي بالفرن","هذا الدجاج \"المقلي\" ليس أكثر صحة من الدجاج المقلي التقليدي فحسب، بل هو أيضًا أسهل وأقل تعقيدًا في التحضير من النسخة التقليدية.","8",None,
["2 كوب فتات خبز إيطالي الطراز من القمح الكامل","1 فص ثوم","1 ملعقة كبيرة بهارات إيطالية","½ كوب دقيق متعدد الاستخدامات","2 بيضة كبيرة (مخفوقة مع 1 ملعقة كبيرة ماء)","4 بياض بيض كبير","8 أفخاذ دجاج (منزوعة العظم والجلد، حوالي 2 رطل)"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية) بوضع الحمل الحراري أو 400° فهرنهايت (205° مئوية) في الفرن التقليدي. ضع فتات الخبز والثوم وخليط البهارات الإيطالية للطهي السهل في محضّر الطعام. شغّله حتى تمتزج المكونات جيدًا.","ضع الدقيق في طبق فطيرة. ضع البيض وبياض البيض في طبق فطيرة منفصل. ضع خليط فتات الخبز في طبق فطيرة ثالث.","بطّن صينية خبز كبيرة بورق الزبدة.","اغمس الدجاج في الدقيق وغطِّه من جميع الجهات، ثم في البيض ثم في فتات الخبز. غطِّه بالتساوي. ضعه في صينية خبز مبطنة بورق الزبدة. إن توفر لديك الوقت، ضع الدجاج في الثلاجة لبعض الوقت قبل طهيه.","اخبز الدجاج لمدة 45 دقيقة حتى يصبح مقرمشًا ومحمرًّا جيدًا. قدّمه مع توابل النزهات أو السلطات. يمكن تحضيره مسبقًا وتجميده ثم إعادة تسخينه في فرن حار جدًا. اتركه ليذوب قبل إعادة التسخين."])}))
I.append((6398040,{
"en":L("Balsamic Salmon over Barley Pilaf",None,"4",None,
["1 lbs salmon (skinless, cut into 4 pieces (4 oz each))","1/8 tsp black pepper","1/4 tsp salt","1/2 cup fresh basil (coarsely chopped)","1/4 cup balsamic vinegar","1 pints cherry tomatoes (halved)","3 cups low-sodium chicken broth","1 cup pearl barley","4 carrots (thinly sliced)","2 stalks celery (thinly sliced)","1 clove garlic (finely chopped)","1 onion (very finely chopped)","1 tbsp canola oil"],
["Place the canola oil in a large pot. Heat and add the onion, garlic and celery. Cook over medium heat, covered, until the onion becomes translucent. Add the carrots and barley and cook uncovered until the barley begins to look toasted. Add broth. Cover and cook 30 minutes.","Cut the tomatoes in half and place them in a large bowl with balsamic vinegar, basil, salt, pepper and salmon. Let it rest while the barley cooks for the first 30 minutes. After 30 minutes, remove the salmon from the tomato mixture. Add the tomato mixture to the barley and place the salmon on top of the barley. Cover and cook 10 more minutes to steam the salmon.","Place some barley pilaf in a pasta bowl and top with a piece of salmon to serve."]),
"ar":L("سلمون بالخل البلسمي على بيلاف الشعير",None,"4",None,
["1 رطل سلمون (منزوع الجلد، مقطع إلى 4 قطع (4 أونصات لكل قطعة))","⅛ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح","½ كوب ريحان طازج (مفروم فرمًا خشنًا)","¼ كوب خل بلسمي","1 باينت طماطم كرزية (مقطعة إلى نصفين)","3 كوب مرق دجاج قليل الصوديوم","1 كوب شعير مقشور (لؤلؤي)","4 جزرات (مقطعة شرائح رفيعة)","2 عروق كرفس (مقطعة شرائح رفيعة)","1 فص ثوم (مفروم ناعمًا)","1 بصلة (مفرومة فرمًا ناعمًا جدًا)","1 ملعقة كبيرة زيت كانولا"],
["ضع زيت الكانولا في قدر كبير. سخّنه وأضف البصل والثوم والكرفس. اطهُ على نار متوسطة والقدر مغطى حتى يصبح البصل شفافًا. أضف الجزر والشعير واطهُ دون غطاء حتى يبدأ الشعير بالظهور محمّصًا. أضف المرق. غطِّ القدر واطهُ 30 دقيقة.","قطّع الطماطم إلى نصفين وضعها في وعاء كبير مع الخل البلسمي والريحان والملح والفلفل والسلمون. اتركه جانبًا بينما يُطهى الشعير خلال أول 30 دقيقة. بعد 30 دقيقة، أخرج السلمون من خليط الطماطم. أضف خليط الطماطم إلى الشعير وضع السلمون فوق الشعير. غطِّ القدر واطهُ 10 دقائق إضافية ليُطهى السلمون على البخار.","ضع بعضًا من بيلاف الشعير في صحن مخصص للمعكرونة وزيّنه بقطعة سلمون وقدّمه."])}))
I.append((6445111,{
"en":L("Sweet and Sour Cucumbers","This recipe is presented by DaVita, a proud partner of the American Diabetes Association® and Diabetes Food Hub®","12",None,
["1/4 tsp black pepper","3 med cucumber(s)","1 med white onion","1/4 cup sugar","1/2 cup white wine vinegar"],
["The marinade liquid should be drained well and discarded from the cucumbers before serving. Serve in small salad bowls as a salad or snack.","Cover the container with plastic wrap and leave it in the refrigerator for the last 2 hours.","Pour over the cucumbers and onion. Add pepper and, if desired, ¼ teaspoon of salt.","Combine the sugar and vinegar. Stir until the sugar dissolves completely.","Cut the cucumbers and onions into slices about 1/8 inch thick. Place in a large bowl."]),
"ar":L("خيار حلو وحامض","هذه الوصفة مقدمة من DaVita، الشريك الفخور لـ American Diabetes Association® وDiabetes Food Hub®","12",None,
["¼ ملعقة صغيرة فلفل أسود","3 حبات متوسطة خيار","1 حبة متوسطة بصل أبيض","¼ كوب سكر","½ كوب خل النبيذ الأبيض"],
["يجب تصفية سائل التتبيل جيدًا والتخلص منه من الخيار قبل التقديم. قدّمه في أوعية سلطة صغيرة كسلطة أو وجبة خفيفة.","غطِّ الوعاء بغلاف بلاستيكي واتركه في الثلاجة خلال آخر ساعتين.","اسكبه فوق الخيار والبصل. أضف الفلفل، وإن رغبت أضف ¼ ملعقة صغيرة من الملح.","اخلط السكر والخل. قلّب حتى يذوب السكر تمامًا.","قطّع الخيار والبصل إلى شرائح بسماكة حوالي ⅛ بوصة. ضعها في وعاء كبير."])}))
I.append((6536401,{
"en":L("Sesame Maple Glazed Tofu with Veggie Quinoa and Furikake","For this vibrant dish, you will brown tofu and glaze it in the skillet with a sweet and savory mixture of sesame oil, maple syrup and more, then serve it over a hearty bed of quinoa mixed with sautéed cabbage, carrots and mushrooms.\n\nBlue Apron believes mealtime should be the best part of the day. That is why we partnered with the American Diabetes Association to serve delicious, ready-to-cook meals packed with fresh produce, lean proteins and plenty of tasty options. All delivered to your door.","2",None,
["1/2 cup red quinoa","14 oz firm tofu","6 oz (about 3 whole carrots) carrots","4 oz cremini (baby bella) mushrooms","1/2 lbs red cabbage","1 (1-inch) piece fresh ginger","2 clove garlic","2 green onion (scallion)","2 tbsp coconut aminos or low-sodium soy sauce","1 1/2 tbsp maple syrup","1 tbsp sesame oil (divided use)","1 tbsp water","1 tbsp sherry vinegar","2 tsp olive oil","1 tsp furikake (optional)"],
["Cook the quinoa: Fill a medium pot 3/4 full with salted water; cover and heat to a boil over high heat. Once it boils, add the quinoa and cook, uncovered, for 18 to 20 minutes or until tender. Turn off the heat. Drain well and return to the pot.","Press the tofu: Meanwhile, drain the tofu and then place it on a plate lined with paper towels. Place several layers of paper towels on top and then place a heavy-bottomed pot (or skillet) on top of the paper towels. Set aside to release excess liquid for at least 10 minutes.","Prep the ingredients and make the glaze: Meanwhile, wash and dry the fresh produce. Peel the carrots; thinly slice them on an angle. Cut the mushrooms into small pieces. Cut out and discard the core of the cabbage; thinly slice the leaves. Peel and finely chop the ginger. Peel and coarsely chop 2 cloves of garlic. Thinly slice the scallions, separating the white bottoms from the hollow green tops. In a bowl, combine the sliced cabbage, chopped ginger, chopped garlic and sliced white parts of the scallions. In a separate bowl, whisk together the coconut aminos, maple syrup, half of the sesame oil and 1 tablespoon of water.","Cook the veggies and finish the quinoa: In a medium skillet (nonstick, if you have one), heat the remaining sesame oil over medium-high heat until hot. Add the sliced carrots and mushroom pieces in an even layer. Cook, without stirring, for 2 to 3 minutes or until lightly browned. Add the prepared cabbage mixture; season with salt (optional) and pepper. Cook, stirring occasionally, for 2 to 3 minutes, or until softened. Add the vinegar. Cook, stirring frequently, for 30 seconds to 1 minute, or until the liquid has evaporated. Transfer to the pot of cooked quinoa; stir to combine. Cover to keep warm. Rinse and wipe out the skillet.","Cook the tofu and serve your dish: Transfer the pressed tofu to a cutting board; cut it lengthwise into 4 equal-size pieces. Season with salt (optional) and pepper on both sides. In the same skillet, heat 2 teaspoons of olive oil over medium-high heat until hot. Add the seasoned tofu pieces in an even layer and cook for 5 to 6 minutes, or until browned. Flip and cook for 2 to 3 minutes, or until lightly browned. Add half of the glaze (carefully, as the liquid may splatter) and cook, frequently spooning the glaze over the tofu, for 1 to 2 minutes, or until the tofu is coated. Transfer to a cutting board. Cut crosswise into 1-inch pieces. Serve the finished quinoa topped with the cooked tofu and the remaining glaze. Garnish with the sliced green tips of the scallions and the furikake. Enjoy!"]),
"ar":L("توفو مطلي بالسمسم وشراب القيقب مع كينوا الخضار والفوريكاكي","في هذا الطبق النابض بالحيوية، ستحمّر التوفو وتطليه في المقلاة بخليط حلو ومالح من زيت السمسم وشراب القيقب وغيرها، ثم تقدّمه فوق طبقة وفيرة من الكينوا الممزوجة بالملفوف والجزر والفطر المقلي.\n\nتؤمن Blue Apron بأن وقت الطعام يجب أن يكون أفضل جزء من اليوم. ولهذا تعاونّا مع الجمعية الأمريكية للسكري لتقديم وجبات لذيذة جاهزة للطهي مليئة بالمنتجات الطازجة والبروتينات الخالية من الدهون والكثير من الخيارات الشهية. وكل ذلك يصل إلى باب منزلك.","2",None,
["½ كوب كينوا حمراء","14 أونصة توفو صلب","6 أونصات (حوالي 3 جزرات كاملة) جزر","4 أونصات فطر كريميني (بيبي بيلا)","½ رطل ملفوف أحمر","1 قطعة (بطول 1 بوصة) زنجبيل طازج","2 فص ثوم","2 بصل أخضر (كراث أخضر)","2 ملعقة كبيرة أمينو جوز الهند أو صلصة صويا قليلة الصوديوم","1½ ملعقة كبيرة شراب القيقب","1 ملعقة كبيرة زيت سمسم (مقسّمة الاستخدام)","1 ملعقة كبيرة ماء","1 ملعقة كبيرة خل الشيري","2 ملعقة صغيرة زيت زيتون","1 ملعقة صغيرة فوريكاكي (اختياري)"],
["اطهُ الكينوا: املأ قدرًا متوسطًا بالماء المملح حتى ¾ سعته؛ غطِّه وسخّنه حتى الغليان على نار عالية. عند الغليان، أضف الكينوا واطهُها دون غطاء من 18 إلى 20 دقيقة أو حتى تلين. أطفئ النار. صفِّها جيدًا وأعدها إلى القدر.","اضغط التوفو: في هذه الأثناء، صفِّ التوفو ثم ضعه على طبق مبطن بمناديل ورقية. ضع عدة طبقات من المناديل الورقية فوقه ثم ضع قدرًا (أو مقلاة) سميك القاع فوق المناديل الورقية. اتركه جانبًا ليفرز السائل الزائد لمدة 10 دقائق على الأقل.","جهّز المكونات وحضّر الطلاء: في هذه الأثناء، اغسل المنتجات الطازجة وجففها. قشّر الجزر؛ وقطّعه شرائح رفيعة بشكل مائل. قطّع الفطر إلى قطع صغيرة. اقطع قلب الملفوف وتخلّص منه؛ وقطّع الأوراق شرائح رفيعة. قشّر الزنجبيل وافرمه ناعمًا. قشّر 2 فص ثوم واقطعهما فرمًا خشنًا. قطّع الكراث الأخضر شرائح رفيعة، مع فصل الجزء الأبيض السفلي عن الجزء الأخضر الأجوف العلوي. في وعاء، اخلط الملفوف المقطع والزنجبيل المفروم والثوم المفروم والأجزاء البيضاء المقطعة من الكراث الأخضر. في وعاء منفصل، اخفق أمينو جوز الهند وشراب القيقب ونصف كمية زيت السمسم و1 ملعقة كبيرة ماء.","اطهُ الخضار وأنهِ الكينوا: في مقلاة متوسطة (غير لاصقة إن توفرت لديك)، سخّن زيت السمسم المتبقي على نار متوسطة إلى عالية حتى يسخن. أضف شرائح الجزر وقطع الفطر في طبقة متساوية. اطهُ دون تقليب من 2 إلى 3 دقائق أو حتى يحمرّ قليلًا. أضف خليط الملفوف المجهّز؛ وتبّله بالملح (اختياري) والفلفل. اطهُ مع التقليب من حين لآخر من 2 إلى 3 دقائق، أو حتى يطرى. أضف الخل. اطهُ مع التقليب المتكرر من 30 ثانية إلى دقيقة واحدة، أو حتى يتبخر السائل. انقله إلى قدر الكينوا المطهوة؛ وقلّب لدمجه. غطِّه للحفاظ على سخونته. اشطف المقلاة وامسحها.","اطهُ التوفو وقدّم طبقك: انقل التوفو المضغوط إلى لوح تقطيع؛ وقطّعه طوليًا إلى 4 قطع متساوية الحجم. تبّله بالملح (اختياري) والفلفل من الجانبين. في المقلاة نفسها، سخّن 2 ملعقة صغيرة من زيت الزيتون على نار متوسطة إلى عالية حتى يسخن. أضف قطع التوفو المتبلة في طبقة متساوية واطهُها من 5 إلى 6 دقائق، أو حتى تحمرّ. اقلبها واطهُها من 2 إلى 3 دقائق، أو حتى تحمرّ قليلًا. أضف نصف الطلاء (بحذر لأن السائل قد يتناثر) واطهُ مع سكب الطلاء على التوفو بشكل متكرر من دقيقة إلى دقيقتين، أو حتى يُغطّى التوفو. انقله إلى لوح تقطيع. قطّعه عرضيًا إلى قطع بحجم 1 بوصة. قدّم الكينوا الجاهزة مغطاة بالتوفو المطهو وبقية الطلاء. زيّنه بالأطراف الخضراء المقطعة من الكراث الأخضر والفوريكاكي. بالهناء والشفاء!"])}))
I.append((6548749,{
"en":L("Grilled Fruit with Vanilla Yogurt Cream","Grilling caramelizes the natural sugars in fruit, giving it a richer, sweeter flavor that tastes more like dessert than a healthy snack. We are using a combination of peaches, plums and apricots, but any 6 summer stone fruits will do. For even more flavor, we top the fruit with low-fat yogurt and a light drizzle of honey. For extra crunch, try topping with chopped nuts; pistachios work particularly well. This recipe appeared in:","6",None,
["2 ripe peaches (halved, pitted)","2 ripe plums (halved, pitted)","2 ripe apricots (halved, pitted)","1 cup low-fat vanilla yogurt","2 tbsp flaxseeds","2 tbsp ground almond","2 1/2 tbsp honey","to taste ground cinnamon"],
["Place the peaches, plums and apricots on the grill, cut side down. Grill over low or indirect heat until soft, about 2 to 4 minutes per side.","Place the fruit on a serving platter and top evenly with yogurt, ground flaxseed and ground almonds.","Drizzle honey over each serving and garnish with a pinch of cinnamon. If desired, sprinkle chopped pistachios over each one. Serve immediately."]),
"ar":L("فواكه مشوية مع كريمة الزبادي بالفانيليا","يؤدي الشوي إلى كرملة السكريات الطبيعية في الفاكهة، فيمنحها نكهة أغنى وأحلى يشبه طعمها الحلوى أكثر من كونها وجبة خفيفة صحية. نستخدم مزيجًا من الخوخ والبرقوق والمشمش، لكن أي 6 فواكه ذات نواة صيفية تفي بالغرض. ولمزيد من النكهة، نغطي الفاكهة بالزبادي قليل الدسم ورشة خفيفة من العسل. ولمزيد من القرمشة، جرّب تغطيتها بالمكسرات المفرومة؛ ويناسبها الفستق بشكل خاص. ظهرت هذه الوصفة في:","6",None,
["2 حبة خوخ ناضجة (مقطوعة إلى نصفين ومنزوعة النواة)","2 حبة برقوق ناضجة (مقطوعة إلى نصفين ومنزوعة النواة)","2 حبة مشمش ناضجة (مقطوعة إلى نصفين ومنزوعة النواة)","1 كوب زبادي بالفانيليا قليل الدسم","2 ملعقة كبيرة بذور الكتان","2 ملعقة كبيرة لوز مطحون","2½ ملعقة كبيرة عسل","قرفة مطحونة حسب الذوق"],
["ضع الخوخ والبرقوق والمشمش على الشواية، مع توجيه الجانب المقطوع إلى الأسفل. اشوِها على نار هادئة أو غير مباشرة حتى تلين، حوالي 2 إلى 4 دقائق لكل جانب.","ضع الفاكهة في طبق تقديم وغطِّها بالتساوي بالزبادي وبذور الكتان المطحونة واللوز المطحون.","رشّ العسل فوق كل حصة وزيّنها برشة قرفة. وإن رغبت، انثر الفستق المفروم فوق كل حصة. قدّمها فورًا."])}))
I.append((6621196,{
"en":L("Peach Pesto Pizza","This simple recipe combines three of our favorite P's: pesto, peach and pizza. If you love sweet and savory and are looking for a creative gluten-free pizza recipe with a cauliflower crust to mix up at home, look no further. This recipe is brought to you by CAULIPOWER®, a proud supporter of the American Diabetes Association® and the Diabetes Food Hub®.","4",None,
["2 tbsp balsamic glaze","1/3 cup parmesan cheese (grated, reduced fat)","1/3 cup almonds (sliced)","1/2 cup red onion","1 cup arugula (fresh)","1/2 avocado (sliced)","1 fennel bulb (shaved)","1 whole peaches (sliced)","3 tbsp pesto sauce","1 whole cauliflower pizza crust"],
["Preheat the oven to 425°F (218°C).","Remove your CAULIPOWER® pizza crust from the box and plastic wrapping, and place it on a clean surface.","Spread the pesto sauce evenly over the CAULIPOWER® pizza crust.","Top with peach, fennel, red onion and parmesan and bake for 13 to 16 minutes.","Remove it from the oven and add arugula and sliced almonds, and drizzle balsamic glaze over the pizza."]),
"ar":L("بيتزا الخوخ بالبيستو","تجمع هذه الوصفة البسيطة ثلاثة من أطعمتنا المفضلة التي تبدأ بحرف P: البيستو (pesto) والخوخ (peach) والبيتزا (pizza). إن كنت تحب المزج بين الحلو والمالح وتبحث عن وصفة بيتزا مبتكرة خالية من الغلوتين بقاعدة من القرنبيط لتحضيرها في المنزل، فلا تبحث أكثر. هذه الوصفة مقدمة لك من CAULIPOWER®، الداعم الفخور لـ American Diabetes Association® وDiabetes Food Hub®.","4",None,
["2 ملعقة كبيرة طلاء بلسمي","⅓ كوب جبن بارميزان (مبشور، مخفض الدسم)","⅓ كوب لوز (مقطع شرائح)","½ كوب بصل أحمر","1 كوب جرجير (طازج)","½ حبة أفوكادو (مقطعة شرائح)","1 بصلة شمر (مقشّرة رقيقة)","1 حبة كاملة خوخ (مقطعة شرائح)","3 ملعقة كبيرة صلصة بيستو","1 قاعدة بيتزا قرنبيط كاملة"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (218° مئوية).","أخرج قاعدة بيتزا CAULIPOWER® من العلبة والغلاف البلاستيكي، وضعها على سطح نظيف.","افرد صلصة البيستو بالتساوي على قاعدة بيتزا CAULIPOWER®.","غطِّها بالخوخ والشمر والبصل الأحمر والبارميزان واخبزها من 13 إلى 16 دقيقة.","أخرجها من الفرن وأضف الجرجير وشرائح اللوز، ورشّ الطلاء البلسمي فوق البيتزا."])}))
I.append((6764984,{
"en":L("Greek Roasted Eggplant with Feta Cheese",None,"4",None,
["1 tbsp feta cheese (finely crumbled)","1 tbsp fresh mint (chopped)","3 tbsp fresh parsley","2 eggplant (each cut lengthwise into quarters, stems removed)","1/4 tsp ground cinnamon","1 clove garlic (minced)","1 tbsp olive oil","1 lemon (zested and juiced, divided use)","3 tbsp marinara sauce"],
["Preheat the oven to 400° F. In a small bowl, mix the marinara sauce, lemon juice, oil, garlic and cinnamon. Place the eggplant wedges, skin side down, on a baking sheet lined with unbleached parchment paper. Generously brush the flesh of the eggplant wedges with the marinara mixture.","Roast the eggplant wedges until well cooked and soft, about 30 minutes.","Transfer the wedges to a plate. Sprinkle with parsley, mint, feta cheese and lemon zest and serve."]),
"ar":L("باذنجان يوناني مشوي بجبن الفيتا",None,"4",None,
["1 ملعقة كبيرة جبن فيتا (مفتت ناعمًا)","1 ملعقة كبيرة نعناع طازج (مفروم)","3 ملعقة كبيرة بقدونس طازج","2 باذنجان (كل واحدة مقطوعة طوليًا إلى أرباع على شكل أسياخ، منزوعة الأعناق)","¼ ملعقة صغيرة قرفة مطحونة","1 فص ثوم (مفروم)","1 ملعقة كبيرة زيت زيتون","1 ليمونة (مبشورة القشر ومعصورة، مقسّمة الاستخدام)","3 ملعقة كبيرة صلصة مارينارا"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (205° مئوية). في وعاء صغير، اخلط صلصة المارينارا وعصير الليمون والزيت والثوم والقرفة. ضع شرائح الباذنجان، مع توجيه الجلد إلى الأسفل، في صينية خبز مبطنة بورق زبدة غير مبيّض. ادهن لب شرائح الباذنجان بسخاء بخليط المارينارا.","اشوِ شرائح الباذنجان حتى تنضج جيدًا وتلين، حوالي 30 دقيقة.","انقل الشرائح إلى طبق. انثر عليها البقدونس والنعناع وجبن الفيتا وقشر الليمون المبشور وقدّمها."])}))
save(1,I)
