from h import *
I=[]
I.append((6847213,{
"en":L("Creamy Chicken Basil Pasta","In the mood for a comforting plate of pasta? Try making this diabetes-friendly creamy chicken basil pasta. The homemade sauce made with fresh herbs adds a burst of flavor that will make this recipe a family favorite.","4",None,
["1/4 cup fresh basil (¼ cup fresh basil leaves, cut into thin strips)","1/4 cup parmesan cheese (¼ cup freshly grated parmesan cheese)","2 cups whole wheat penne pasta (2 cups cooked whole wheat pasta)","1 lbs boneless, skinless chicken breasts (1 pound boneless, skinless chicken breasts, cut in half lengthwise into thin cutlets)","1/2 tsp no-salt-added Italian seasoning (½ teaspoon low-sodium or no-salt-added Italian seasoning)","1/2 cup low-fat Italian cheese (½ cup Italian cheese)","3 cups fat-free milk (3 cups skim milk)","2 tbsp flour (2 tablespoons flour)","1/2 tsp onion powder (½ teaspoon onion powder)","1 tsp garlic (1 teaspoon minced garlic)","3 tbsp olive oil (3 tablespoons olive oil, divided)","2 tbsp half-and-half (2 tablespoons half-and-half)","1/2 cup fresh parsley (½ cup packed flat-leaf Italian parsley)","1 cup fresh basil (1 cup packed basil leaves)","5 oz baby spinach (5 oz baby spinach)"],
["Bring a large pot of water to a boil. Add the baby spinach to the pot and blanch for 1 minute. Use a slotted spoon to remove the spinach and place it in a bowl of ice water. Add the packed parsley and basil to the pot and blanch for 15 seconds. Remove and add to the bowl of ice water. Drain the water and squeeze as much liquid as possible from the greens.","Add the spinach, parsley and basil to a food processor. Add the half-and-half to the food processor and puree. Set aside.","Heat a saucepan over medium heat. Add 2 tablespoons of olive oil, garlic and onion powder. Add the flour and whisk for 1 minute. Add the milk and whisk until smooth.","Add the cheese, Italian seasoning, salt (optional) and pepper. Stir until the sauce thickens.","Add the vegetable puree and stir to combine.","Meanwhile, heat a large skillet over medium heat. Add the remaining olive oil. Cook the chicken for 3-4 minutes on each side, until browned and cooked through.","To serve, divide the chicken and pasta among plates. Top with sauce, parmesan cheese and fresh basil strips."]),
"ar":L("معكرونة كريمية بالدجاج والريحان","هل تشتهي طبق معكرونة مريحًا؟ جرّب تحضير هذه المعكرونة الكريمية بالدجاج والريحان المناسبة لمرضى السكري. تضيف الصلصة محلية الصنع المصنوعة من الأعشاب الطازجة دفعة من النكهة تجعل هذه الوصفة من المفضلات لدى العائلة.","4",None,
["¼ كوب ريحان طازج (¼ كوب أوراق ريحان طازجة، مقطعة شرائح رفيعة)","¼ كوب جبن بارميزان (¼ كوب جبن بارميزان مبشور طازجًا)","2 كوب معكرونة بيني من القمح الكامل (2 كوب معكرونة قمح كامل مطبوخة)","1 رطل صدور دجاج منزوعة العظم والجلد (1 رطل صدور دجاج منزوعة العظم والجلد، مقطوعة إلى نصفين طوليًا على شكل شرائح رفيعة)","½ ملعقة صغيرة بهارات إيطالية بدون ملح مضاف (½ ملعقة صغيرة بهارات إيطالية قليلة الصوديوم أو بدون ملح مضاف)","½ كوب جبن إيطالي قليل الدسم (½ كوب جبن إيطالي)","3 كوب حليب خالٍ من الدسم (3 أكواب حليب منزوع الدسم)","2 ملعقة كبيرة دقيق (2 ملعقة كبيرة دقيق)","½ ملعقة صغيرة مسحوق البصل (½ ملعقة صغيرة مسحوق بصل)","1 ملعقة صغيرة ثوم (1 ملعقة صغيرة ثوم مفروم)","3 ملعقة كبيرة زيت زيتون (3 ملاعق كبيرة زيت زيتون، مقسّمة)","2 ملعقة كبيرة نصف حليب ونصف قشدة (2 ملعقة كبيرة نصف حليب ونصف قشدة)","½ كوب بقدونس طازج (½ كوب بقدونس إيطالي مسطح الأوراق مكبوس)","1 كوب ريحان طازج (1 كوب أوراق ريحان مكبوسة)","5 أونصات سبانخ صغيرة الأوراق (5 أونصات سبانخ صغيرة الأوراق)"],
["اغلِ قدرًا كبيرًا من الماء. أضف السبانخ الصغيرة إلى القدر واسلقها سلقًا سريعًا لمدة دقيقة واحدة. استخدم ملعقة مثقبة لإخراج السبانخ وضعها في وعاء من الماء المثلج. أضف البقدونس والريحان المكبوسين إلى القدر واسلقهما سلقًا سريعًا لمدة 15 ثانية. أخرجهما وأضفهما إلى وعاء الماء المثلج. صفِّ الماء واعصر أكبر قدر ممكن من السائل من الخضار الورقية.","ضع السبانخ والبقدونس والريحان في محضّر الطعام. أضف نصف الحليب ونصف القشدة إلى محضّر الطعام وهرسها حتى تصبح هريسًا. ضعه جانبًا.","سخّن قدرًا على نار متوسطة. أضف 2 ملعقة كبيرة من زيت الزيتون والثوم ومسحوق البصل. أضف الدقيق واخفق لمدة دقيقة واحدة. أضف الحليب واخفق حتى يصبح الخليط متجانسًا.","أضف الجبن والبهارات الإيطالية والملح (اختياري) والفلفل. قلّب حتى تثخن الصلصة.","أضف هريس الخضار وقلّب لدمجه.","في هذه الأثناء، سخّن مقلاة كبيرة على نار متوسطة. أضف زيت الزيتون المتبقي. اطهُ الدجاج من 3 إلى 4 دقائق على كل جانب، حتى يحمرّ وينضج جيدًا.","للتقديم، وزّع الدجاج والمعكرونة على الأطباق. غطِّها بالصلصة وجبن البارميزان وشرائح الريحان الطازج."])}))
I.append((6949633,{
"en":L("Gluten-Free Almond Flour Pancakes","Enjoy your morning with these gluten-free almond flour pancakes that provide enough protein to keep you energized. If your diabetes management meal plan allows it, top them with fresh banana slices or low-carb berries.","2",None,
["1 cup almond flour","2 tbsp coconut flour","1 tsp baking powder","1 pinch kosher salt","2 large eggs","1/2 cup unsweetened almond milk","1 tbsp olive oil (plus 1 tsp)","1 tbsp maple syrup","1 tsp vanilla extract"],
["In a bowl, mix the almond flour, coconut flour, baking powder and salt.","In a separate container, beat the eggs and add the almond milk, 1 tablespoon of olive oil, the maple syrup and the vanilla extract. Mix well.","Pour the wet ingredients into the dry ingredients and stir until combined. Let the batter rest for a couple of minutes to thicken.","Heat a skillet or griddle over medium heat and grease with 1 teaspoon of olive oil or cooking spray.","Pour ¼ cup of batter into the skillet for each pancake. Spread the batter slightly with the back of a spoon.","Cook until bubbles form on the surface, then flip and cook until the other side is golden.","Repeat with the remaining batter."]),
"ar":L("بان كيك دقيق اللوز الخالي من الغلوتين","استمتع بصباحك مع بان كيك دقيق اللوز الخالي من الغلوتين الذي يوفر ما يكفي من البروتين ليبقيك نشيطًا. إن كانت خطة وجباتك لإدارة السكري تسمح بذلك، فأضف إليه شرائح موز طازجة أو توتًا قليل الكربوهيدرات.","2",None,
["1 كوب دقيق اللوز","2 ملعقة كبيرة دقيق جوز الهند","1 ملعقة صغيرة بيكنج باودر","1 رشة ملح كوشر","2 بيضة كبيرة","½ كوب حليب لوز غير محلى","1 ملعقة كبيرة زيت زيتون (بالإضافة إلى 1 ملعقة صغيرة)","1 ملعقة كبيرة شراب القيقب","1 ملعقة صغيرة مستخلص الفانيليا"],
["في وعاء، اخلط دقيق اللوز ودقيق جوز الهند والبيكنج باودر والملح.","في وعاء منفصل، اخفق البيض وأضف حليب اللوز و1 ملعقة كبيرة من زيت الزيتون وشراب القيقب ومستخلص الفانيليا. اخلط جيدًا.","اسكب المكونات السائلة على المكونات الجافة وقلّب حتى تمتزج. اترك العجينة ترتاح بضع دقائق لتثخن.","سخّن مقلاة أو صاجًا على نار متوسطة وادهنه بـ 1 ملعقة صغيرة من زيت الزيتون أو بخاخ الطهي.","اسكب ¼ كوب من العجينة في المقلاة لكل قطعة بان كيك. افرد العجينة قليلًا بظهر ملعقة.","اطهُها حتى تتكون فقاعات على السطح، ثم اقلبها واطهُها حتى يصبح الجانب الآخر ذهبي اللون.","كرّر العملية مع العجينة المتبقية."])}))
I.append((6998435,{
"en":L("Chicken and Butter Lettuce Wrap","LETTUCE present your new healthier favorite chicken wrap! Made with CAULIPOWER BAKED (never fried) chicken tenders, this tasty recipe is gluten-free, dairy-free and packed with protein, making your weekday lunch a little more CAULIPOWERful! This recipe is presented by CAULIPOWER®, a proud supporter of the American Diabetes Association® and Diabetes Food Hub®.","1",None,
["2 CAULIPOWER® Original Chicken Tenders (servings, 85 g)","1 large lettuce (leaf)","1/4 cup green onion (scallion) (chopped)","1/4 cup carrots (shredded)","1/8 cup avocado (sliced)","1/4 cup red cabbage (shredded)","1 tbsp pico de gallo"],
["Preheat the oven to 425 degrees F.","Place the CAULIPOWER chicken tenders on a baking sheet that has been sprayed with nonstick cooking spray.","Heat for 17 to 19 minutes for a conventional oven, 15 to 17 minutes for a convection oven, or until the tenders reach an internal temperature of 165 degrees F.","Remove the tenders from the oven and place the hot tenders on the lettuce.","Top with carrots, green onions, avocado, red cabbage and pico de gallo."]),
"ar":L("لفائف الدجاج وخس الزبدة","تقدم لك LETTUCE لفائف الدجاج الجديدة الأكثر صحة والمفضلة لديك! مصنوعة من شرائح دجاج CAULIPOWER المخبوزة بالفرن (وليست مقلية أبدًا)، وهذه الوصفة الشهية خالية من الغلوتين ومن منتجات الألبان وغنية بالبروتين، مما يجعل غداءك في أيام الأسبوع أكثر قوة بقليل! هذه الوصفة مقدمة من CAULIPOWER®، الداعم الفخور لـ American Diabetes Association® وDiabetes Food Hub®.","1",None,
["2 شريحة دجاج CAULIPOWER® الأصلية (حصص، 85 غ)","1 ورقة خس كبيرة","¼ كوب بصل أخضر (كراث أخضر) (مقطع)","¼ كوب جزر (مبشور)","⅛ كوب أفوكادو (مقطع شرائح)","¼ كوب ملفوف أحمر (مبشور)","1 ملعقة كبيرة بيكو دي غايو"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية).","ضع شرائح دجاج CAULIPOWER على صينية خبز رُشَّت ببخاخ الطهي غير اللاصق.","سخّنها من 17 إلى 19 دقيقة في الفرن التقليدي، ومن 15 إلى 17 دقيقة في فرن الحمل الحراري، أو حتى تبلغ الشرائح درجة حرارة داخلية قدرها 165 درجة فهرنهايت (75° مئوية).","أخرج الشرائح من الفرن وضع الشرائح الساخنة على ورقة الخس.","غطِّها بالجزر والبصل الأخضر والأفوكادو والملفوف الأحمر وبيكو دي غايو."])}))
I.append((7002183,{
"es":L("Tostadas poppadom crujientes con pato picante","Tienen un aspecto impresionante, pero en realidad son muy sencillas de preparar. Los mini poppadoms son ideales para una fiesta con bebidas.","40","17g",
["2 pechugas de pato, sin piel ni grasa (peso 400g)","2 cucharaditas de cinco especias chinas","1 cucharada de aceite de colza","40 mini poppadoms","1 trozo de pepino de 6cm, sin semillas y finamente picado","2 cucharadas de cilantro fresco, picado grueso","4 cebolletas, finamente cortadas en tiras","4 cucharadas de chutney de mango"],
["Coloque las pechugas de pato en un recipiente no metálico y frótelas por todas partes con el polvo de cinco especias chinas. Déjelas marinar durante al menos 10 minutos. Corte el pato en trozos pequeños.","Caliente el aceite en una sartén antiadherente. Agregue el pato y fríalo de 2 a 3 minutos, hasta que esté crujiente y dorado.","Mezcle el pepino, el cilantro y las cebolletas, y coloque un poco sobre cada poppadom.","Añada una cucharada pequeña de chutney de mango y cubra cada poppadom con un trozo de pato."],
[ "Podría usar pechuga de pollo o filete magro en lugar de pato.","Para una versión vegana, reemplace el pato con cubos pequeños de tofu.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 0"]]),
"ar":L("رقائق البوبادوم المغطاة ببط حار","تبدو مبهرة لكنها في الواقع سهلة التحضير جدًا. رقائق البوبادوم الصغيرة مثالية لحفلات المشروبات.","40","17 غ",
["2 صدر بط، منزوع الجلد والدهن (الوزن 400 غ)","2 ملعقة صغيرة بهارات صينية خماسية","1 ملعقة كبيرة زيت اللفت","40 رقاقة بوبادوم صغيرة","قطعة خيار بطول 6 سم، منزوعة البذور ومفرومة ناعمًا","2 ملعقة كبيرة كزبرة خضراء طازجة، مفرومة فرمًا خشنًا","4 حبات بصل أخضر، مقطعة شرائح رفيعة جدًا","4 ملاعق كبيرة تشاتني المانجو"],
["ضع صدور البط في وعاء غير معدني وافركها من كل الجهات ببهارات الخمس بهارات الصينية. اتركها لتتتبل 10 دقائق على الأقل. قطّع البط إلى قطع صغيرة.","سخّن الزيت في مقلاة غير لاصقة. أضف البط وقلّبه من 2 إلى 3 دقائق حتى يصبح مقرمشًا وذهبي اللون.","اخلط الخيار والكزبرة الخضراء والبصل الأخضر وضع قليلًا منه على كل رقاقة بوبادوم.","ضع قليلًا من تشاتني المانجو بالملعقة وغطِّ كل رقاقة بوبادوم بقطعة من البط."],
["يمكنك استخدام صدر الدجاج أو شريحة لحم بقري خالية من الدهن بدلًا من البط.","لنسخة نباتية، استبدل البط بمكعبات صغيرة من التوفو.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 0"]])}))
I.append((7002703,{
"es":L("Ensalada de salmón crujiente","Las papas, los tomates y el salmón se combinan para preparar esta ensalada abundante.","2","338g",
["250g de papas nuevas","8 tomates cherry, cortados por la mitad","90g de hojas de ensalada variadas","2 filetes de salmón sin piel (aprox. 100g cada uno)","1 cucharada de pimienta negra molida gruesa","ralladura y jugo de 1 naranja","1 cucharada de mostaza de grano entero"],
["Hierva las papas de 10 a 15 minutos hasta que estén tiernas, luego enfríelas con agua fría, déjelas enfriar un poco y córtelas en rodajas.","Mezcle las rodajas de papa y los tomates, y repártalos en 2 platos. Coloque las hojas de ensalada encima y reserve.","Cubra un lado de cada filete de salmón con pimienta.","Caliente una sartén antiadherente o una plancha hasta que esté muy caliente. Coloque el salmón con el lado de la pimienta hacia abajo y cocínelo de 3 a 4 minutos; luego voltee y cocine de 3 a 4 minutos más, hasta que esté completamente cocido.","Coloque el salmón sobre las hojas de ensalada, mezcle la ralladura y el jugo de naranja con la mostaza, rocíe sobre la ensalada y sirva."],
["Esta ensalada queda muy bien con otros pescados, como filetes de caballa, atún fresco o langostinos. También podría usar pechuga de pollo cortada en rodajas finas.","Como alternativa vegana, pruebe tiras de tofu en lugar de salmón. Simplemente fríalas en una sartén antiadherente hasta que estén crujientes y luego mézclelas con un poco de aceite de sésamo, salsa de soja y cinco especias chinas.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 1"]]),
"ar":L("سلطة السلمون المقرمش","تجتمع البطاطس والطماطم والسلمون لتشكّل هذه السلطة المشبعة.","2","338 غ",
["250 غ بطاطس صغيرة جديدة","8 حبات طماطم كرزية، مقطوعة إلى نصفين","90 غ أوراق سلطة مشكلة","2 قطعة فيليه سلمون منزوع الجلد (حوالي 100 غ لكل قطعة)","1 ملعقة كبيرة فلفل أسود مطحون خشنًا","قشر مبشور وعصير 1 برتقالة","1 ملعقة كبيرة خردل بالحبوب الكاملة"],
["اسلق البطاطس من 10 إلى 15 دقيقة حتى تلين ثم انقعها في ماء بارد، واتركها تبرد قليلًا وقطّعها شرائح.","اخلط شرائح البطاطس والطماطم ووزّعها على طبقين للتقديم. كوّم أوراق السلطة فوقها وضعها جانبًا.","غطِّ أحد جانبي كل قطعة سلمون بالفلفل.","سخّن مقلاة غير لاصقة أو صاجًا حتى يسخن جيدًا. ضع السلمون وجانب الفلفل إلى الأسفل واطهُه من 3 إلى 4 دقائق، ثم اقلبه واطهُه من 3 إلى 4 دقائق إضافية حتى ينضج تمامًا.","ضع السلمون فوق أوراق السلطة، واخلط قشر البرتقال وعصيره مع الخردل، ثم رشّه فوق السلطة وقدّمها."],
["تناسب هذه السلطة أنواع الأسماك الأخرى جيدًا، مثل فيليه الماكريل أو التونة الطازجة أو الجمبري الكبير. ويمكنك أيضًا استخدام صدر دجاج مقطع شرائح رفيعة.","كبديل نباتي، جرّب شرائح التوفو بدلًا من السلمون. فقط قلّها في مقلاة غير لاصقة حتى تصبح مقرمشة ثم قلّبها مع قليل من زيت السمسم وصلصة الصويا والبهارات الصينية الخماسية.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 1"]])}))
I.append((7006166,{
"es":L("Pizza de papa","Una alternativa vegetariana a la cobertura habitual de queso y tomate para la pizza.","4","171g",
[["Para la base","100g de harina integral común"],["Para la base","150g de harina común"],["Para la base","1 pizca de sal"],["Para la base","1 sobre de 7g de levadura de acción rápida"],["Para la base","1 cucharada de leche semidescremada"],["Para la base","1 cucharada de aceite de oliva"],["Para la cobertura","250g de papas cerosas, en rodajas finas"],["Para la cobertura","1 cucharada de aceite de oliva"],["Para la cobertura","1 cebolla, en rodajas"],["Para la cobertura","hojas de 1 ramita de romero"],["Para la cobertura","1 cucharada de tomillo fresco"],["Para la cobertura","4 cucharadas de crème fraîche semidescremada"],["Para la cobertura","pimienta negra recién molida"]],
["Precaliente el horno a 220°C/gas 7.","Coloque las harinas y la levadura en un bol grande. Mezcle la leche, el aceite y 125ml de agua tibia, vierta sobre la harina y una hasta formar una masa suave.","Vuélquela sobre una superficie ligeramente enharinada y amase de 5 a 6 minutos hasta que quede lisa. Colóquela en un bol ligeramente aceitado, cúbrala con un paño húmedo y déjela reposar en un lugar tibio durante 30 minutos.","Mientras tanto, cueza las papas a fuego lento en agua ligeramente salada durante 5 minutos. Escúrralas.","Caliente el aceite en una sartén antiadherente y fría la cebolla de 3 a 4 minutos hasta que se ablande.","Corte la masa en dos y dé a cada pieza forma de un círculo de 23cm, de aproximadamente ½-1cm de grosor, y colóquelas en una bandeja para hornear resistente.","Prepare la cobertura: añada el romero, el tomillo, la crème fraîche y la pimienta a las papas y repártalas entre las bases. Déjelas reposar 5 minutos y luego hornee de 15 a 20 minutos hasta que estén crujientes y doradas."],
["Esparza sobre la pizza cocida un puñado de hojas frescas de rúcula y un chorrito de vinagre balsámico, o unos tomates cherry picados y un par de cebolletas picadas.","Pruebe a untar 1 cucharadita de pasta de curry sobre la base de la pizza antes de cocinarla.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 0"]]),
"ar":L("بيتزا البطاطس","بديل نباتي لحشوة البيتزا المعتادة من الجبن والطماطم.","4","171 غ",
[["للقاعدة","100 غ دقيق قمح كامل عادي"],["للقاعدة","150 غ دقيق عادي"],["للقاعدة","رشة ملح"],["للقاعدة","1 كيس 7 غ خميرة سريعة التحضير"],["للقاعدة","1 ملعقة كبيرة حليب نصف خالي الدسم"],["للقاعدة","1 ملعقة كبيرة زيت زيتون"],["للحشوة","250 غ بطاطس شمعية، مقطعة شرائح رفيعة"],["للحشوة","1 ملعقة كبيرة زيت زيتون"],["للحشوة","1 بصلة، مقطعة شرائح"],["للحشوة","أوراق من 1 غصن إكليل الجبل"],["للحشوة","1 ملعقة كبيرة زعتر طازج"],["للحشوة","4 ملاعق كبيرة كريمة كريم فريش نصف دسمة"],["للحشوة","فلفل أسود مطحون طازجًا"]],
["سخّن الفرن مسبقًا إلى 220° مئوية/علامة الغاز 7.","ضع الدقيق والخميرة في وعاء كبير. اخلط الحليب والزيت و125 مل من الماء الدافئ، واسكبه على الدقيق وضمّه معًا لتكوين عجينة طرية.","اقلبها على سطح مرشوش قليلًا بالدقيق واعجنها من 5 إلى 6 دقائق حتى تصبح ناعمة. ضعها في وعاء مدهون بالزيت قليلًا، وغطِّها بقطعة قماش مبللة واتركها جانبًا في مكان دافئ لمدة 30 دقيقة.","في هذه الأثناء، اسلق البطاطس على نار هادئة في ماء مملح قليلًا لمدة 5 دقائق. صفِّها.","سخّن الزيت في مقلاة غير لاصقة وقلّب البصل من 3 إلى 4 دقائق حتى يطرى.","اقطع العجينة إلى قطعتين وشكّل كل قطعة على هيئة دائرة قطرها 23 سم وسماكتها حوالي ½–1 سم، وضعها على صينية خبز ثقيلة.","حضّر الحشوة بإضافة إكليل الجبل والزعتر والكريم فريش والفلفل إلى البطاطس ووزّعها على القاعدتين. اتركها جانبًا 5 دقائق، ثم اخبزها من 15 إلى 20 دقيقة حتى تصبح مقرمشة وذهبية."],
["انثر على البيتزا المطهوة حفنة من أوراق الجرجير الطازجة ورشة من الخل البلسمي، أو بضع حبات طماطم كرزية مفرومة وحبتين من البصل الأخضر المفروم.","جرّب دهن 1 ملعقة صغيرة من معجون الكاري على قاعدة البيتزا قبل الخبز.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 0"]])}))
I.append((7006687,{
"es":L("Ensalada vietnamita de res","Una ensalada sustanciosa pero ligera, con carne de res tierna y brotes de soja.","6","255g",
["350g de carne de res magra, cortada en tiras","½ cucharadita de hojuelas de chile","2 dientes de ajo, machacados","4cm de jengibre fresco, finamente picado","1 pimiento rojo, en rodajas","150g de mini mazorcas de maíz, cortadas a lo largo por la mitad","300g de brotes de soja","6 cebolletas, cortadas en trozos de 1cm",["Para el aderezo","1 trozo de pepino de 10cm, finamente picado"],["Para el aderezo","25g de cilantro, picado grueso"],["Para el aderezo","Jugo de 1 lima"],["Para el aderezo","2 cucharaditas de salsa de soja reducida en sal"],["Para el aderezo","300g de fideos de arroz frescos precocidos"]],
["Agregue el aceite a una sartén. Añada la carne y cocínela de 4 a 5 minutos a fuego alto, revolviendo con frecuencia. Incorpore las hojuelas de chile, el ajo y el jengibre.","A continuación, añada el pimiento rojo y revuelva de 2 a 3 minutos; después agregue las mini mazorcas de maíz. Revuelva durante 1 minuto.","Añada los brotes de soja y las cebolletas, mezcle bien durante 1 minuto y retire del fuego. Deje enfriar.","Para el aderezo, ponga el pepino, el cilantro, el jugo de lima y la salsa de soja en un bol pequeño.","Añada el aderezo a los fideos y mezcle bien. Luego agregue la mezcla de carne ya fría, mezcle todo y sirva."],
[["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 1"]]),
"ar":L("سلطة اللحم البقري الفيتنامية","سلطة مشبعة لكنها خفيفة مع لحم بقري طري وبراعم الفاصولياء.","6","255 غ",
["350 غ لحم بقري قليل الدسم، مقطع شرائح","½ ملعقة صغيرة رقائق الفلفل الحار","2 فص ثوم، مهروس","4 سم زنجبيل طازج، مفروم ناعمًا","1 حبة فلفل أحمر، مقطعة شرائح","150 غ ذرة صغيرة، مقطوعة طوليًا إلى نصفين","300 غ براعم الفاصولياء","6 حبات بصل أخضر، مقطعة إلى قطع بطول 1 سم",["للتتبيلة","قطعة خيار بطول 10 سم، مفرومة ناعمًا"],["للتتبيلة","25 غ كزبرة خضراء، مفرومة فرمًا خشنًا"],["للتتبيلة","عصير 1 حبة ليمون أخضر"],["للتتبيلة","2 ملعقة صغيرة صلصة صويا قليلة الملح"],["للتتبيلة","300 غ نودلز أرز طازجة مطبوخة مسبقًا"]],
["أضف الزيت إلى مقلاة. أضف اللحم البقري واطهُه من 4 إلى 5 دقائق على نار عالية مع التقليب بانتظام. أضف رقائق الفلفل الحار والثوم والزنجبيل وقلّب.","بعد ذلك، أضف الفلفل الأحمر مع التقليب من 2 إلى 3 دقائق، ثم أضف الذرة الصغيرة. قلّب لمدة دقيقة واحدة.","أضف براعم الفاصولياء والبصل الأخضر، وامزج جيدًا لمدة دقيقة واحدة وارفع عن النار. اتركه ليبرد.","للتتبيلة، ضع الخيار والكزبرة الخضراء وعصير الليمون الأخضر وصلصة الصويا في وعاء صغير.","أضف التتبيلة إلى النودلز واخلط جيدًا. ثم أضف خليط اللحم البقري المبرد واخلطه وقدّم السلطة."],
[["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 1"]])}))
I.append((7007009,{
"es":L("Pollo balti","Un plato balti aromático, sabroso y reconfortante.","2","467g",
["1 cucharadita de aceite de colza","1 cebolla, picada","2 pechugas de pollo sin piel, en cubos","1 pimiento verde, picado","2 zanahorias, picadas","1 rama de apio","4 dientes de ajo, machacados","2–3 cucharaditas colmadas de curry en polvo","1 cucharadita colmada de garam masala","1 chile verde, cortado en aros","1 lata de 400g de tomates picados","1 cucharada de puré de tomate","25g de cilantro fresco, picado"],
["Ponga el aceite en una sartén, agregue la cebolla y cocínela de 3 a 4 minutos hasta que se ablande. Añada el pollo y cocine de 2 a 3 minutos.","Añada el pimiento, la zanahoria y el apio, y cocine de 3 a 4 minutos, revolviendo con frecuencia.","Agregue el ajo, el curry en polvo y el garam masala, y revuelva bien para que todo quede cubierto con las especias.","Añada el chile, los tomates y el puré de tomate, y lleve a un hervor suave.","Tape y cocine a fuego lento de 12 a 14 minutos hasta que la zanahoria esté tierna. Incorpore el cilantro y sirva."],
["Hemos usado curry en polvo; a diferencia de la pasta de curry, no lleva sal ni grasa añadidas.","Podría usar cerdo magro o cubos de cordero para este plato. Para una versión vegetariana/vegana, reemplace el pollo con una lata de garbanzos o de frijoles mixtos.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 3"]]),
"ar":L("دجاج بالتي","طبق بالتي عطري ولذيذ ومُدفئ.","2","467 غ",
["1 ملعقة صغيرة زيت اللفت","1 بصلة، مفرومة","2 صدر دجاج منزوع الجلد، مقطع مكعبات","1 حبة فلفل أخضر، مفرومة","2 جزرة، مفرومة","1 عود كرفس","4 فص ثوم، مهروس","2–3 ملعقة صغيرة مكدسة مسحوق الكاري","1 ملعقة صغيرة مكدسة جارام ماسالا","1 حبة فلفل حار أخضر، مقطعة حلقات","1 علبة 400 غ طماطم مفرومة","1 ملعقة كبيرة معجون طماطم","25 غ كزبرة خضراء طازجة، مفرومة"],
["ضع الزيت في مقلاة، ثم أضف البصل واطهُه من 3 إلى 4 دقائق حتى يطرى. أضف الدجاج واطهُه من 2 إلى 3 دقائق.","أضف الفلفل والجزر والكرفس، واطهُ من 3 إلى 4 دقائق مع التقليب بانتظام.","أضف الثوم ومسحوق الكاري وجارام ماسالا، وقلّب جيدًا ليتغطى كل شيء بالتوابل.","أضف الفلفل الحار والطماطم ومعجون الطماطم، واتركه حتى يغلي برفق.","غطِّه واتركه على نار هادئة من 12 إلى 14 دقيقة حتى يلين الجزر. أضف الكزبرة الخضراء وقلّب وقدّم."],
["استخدمنا مسحوق الكاري، فهو على عكس معجون الكاري لا يحتوي على ملح أو دهون مضافة.","يمكنك استخدام لحم خنزير قليل الدسم أو مكعبات لحم ضأن لهذا الطبق. ولنسخة نباتية/خالية من اللحوم، استبدل الدجاج بعلبة حمص أو فاصولياء مشكلة.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 3"]])}))
I.append((7007691,{
"es":L("Frittata de espárragos","Un almuerzo súper sabroso que requiere solo cuatro ingredientes.","2","237g",
["1 manojo de 250g de espárragos frescos (185g una vez recortados)","½ manojo (60g) de cebolleta, picada","3 huevos medianos, batidos","½ bolsa mediana (p. ej., 150g) de hojas de espinaca frescas","1 aceite en spray de 1 caloría (aproximadamente 7 pulverizaciones de aceite)","Pimienta negra al gusto"],
["Quiebre los extremos de los espárragos por donde se rompan de forma natural y luego córtelos en trozos más bien grandes.","Pique finamente la cebolleta.","Bata los huevos y sazone con pimienta negra al gusto.","Rocíe una sartén pequeña con el aceite en spray de 1 caloría y colóquela a fuego medio.","Fría la cebolleta y los espárragos durante unos minutos, hasta que empiecen a ablandarse.","Añada las espinacas y cocine unos minutos más, hasta que se marchiten.","Vierta los huevos batidos en la sartén, distribuya los espárragos de manera uniforme en la mezcla y cocine unos 5 minutos, hasta que los bordes empiecen a dorarse.","Retire la sartén de la hornilla y colóquela bajo un grill caliente hasta que la frittata empiece a dorarse."],
[["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 2"]]),
"ar":L("فريتاتا الهليون","غداء لذيذ للغاية لا يتطلب سوى أربعة مكونات.","2","237 غ",
["1 حزمة 250 غ هليون طازج (185 غ بعد التقليم)","½ حزمة (60 غ) بصل أخضر، مفروم","3 بيضات متوسطة، مخفوقة","½ كيس متوسط (مثلًا 150 غ) أوراق سبانخ طازجة","1 بخاخ زيت 1 سعرة (حوالي 7 بخات من الزيت)","فلفل أسود حسب الذوق"],
["اكسر أطراف الهليون من الموضع الذي تنكسر عنده بشكل طبيعي ثم قطّعه إلى قطع كبيرة نوعًا ما.","افرم البصل الأخضر ناعمًا.","اخفق البيض معًا ثم تبّله بالفلفل الأسود حسب الذوق.","رشّ مقلاة صغيرة ببخاخ الزيت 1 سعرة وضعها على نار متوسطة.","قلّب البصل الأخضر والهليون لبضع دقائق، حتى يبدآن بالطراوة.","أضف السبانخ واطهُ بضع دقائق إضافية حتى تذبل السبانخ.","اسكب البيض المخفوق في المقلاة، ووزّع الهليون بالتساوي في الخليط، واطهُ لحوالي 5 دقائق، حتى تبدأ الحواف بالاحمرار.","ارفع المقلاة عن الموقد وضعها تحت شواية ساخنة حتى تبدأ الفريتاتا بالاحمرار."],
[["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 2"]])}))
I.append((7007930,{
"es":L("Pastel de zanahoria","Esta versión más saludable es fácil de preparar. Lo cortamos en 18 porciones, pero podría dividirlo fácilmente en 24 cuadrados pequeños para una fiesta.","18","76g",
[ "300g de harina integral","1 cucharadita de polvo para hornear","2 cucharaditas de mezcla de especias","3 huevos, batidos","1 plátano, machacado","3 cucharadas de edulcorante granulado","50ml de aceite de colza + 2 cucharaditas para engrasar el molde","50g de pasas sultanas","400g de zanahorias",["Para la cobertura","250g de quark sin grasa (queso crema)"],["Para la cobertura","1 cucharada de edulcorante granulado"],["Para la cobertura","ralladura de 1 naranja"],["Para la cobertura","20g de trozos de nuez"]],
["Caliente el horno a 180°C/gas 4 y engrase ligeramente un molde para pastel de 20cm x 25cm con el aceite de colza.","En un bol, mezcle la harina, el polvo para hornear y las especias.","En otro bol, ponga el huevo y el plátano y bata bien. Incorpore el edulcorante y el aceite.","Incorpore poco a poco los ingredientes secos a la mezcla de plátano, huevo y aceite con movimientos envolventes; luego añada las pasas sultanas y las zanahorias.","Vierta la mezcla en el molde y hornee de 25 a 30 minutos; luego retire del horno y deje enfriar sobre una rejilla.","Cuando el pastel esté frío, cúbralo con el quark endulzado y decore con la ralladura de naranja y los trozos de nuez."],
["Asegúrese de que el pastel esté completamente frío antes de cubrirlo; de lo contrario, el queso crema se derretirá.","Pruebe a cortarlo en cuadrados pequeños antes de cubrirlo, luego coloque con manga pastelera una porción de queso crema endulzado sobre cada cuadrado y espolvoree con ralladura de naranja y un trozo de nuez.","Podría usar canela en lugar de la mezcla de especias o probar con otros frutos secos, como avellanas o almendras."]),
"ar":L("كعكة الجزر","هذه النسخة الأكثر صحة سهلة التحضير. قطّعناها إلى 18 قطعة، ولكن يمكنك بسهولة تقسيمها إلى 24 مربعًا صغيرًا لحفلة.","18","76 غ",
["300 غ دقيق قمح كامل","1 ملعقة صغيرة بيكنج باودر","2 ملعقة صغيرة خليط توابل","3 بيضات، مخفوقة","1 موزة، مهروسة","3 ملاعق كبيرة محلي محبب","50 مل زيت اللفت + 2 ملعقة صغيرة لدهن القالب","50 غ زبيب سلطانة","400 غ جزر",["للتغطية","250 غ كوارك خالٍ من الدسم (جبن كريمي)"],["للتغطية","1 ملعقة كبيرة محلي محبب"],["للتغطية","قشر مبشور من 1 برتقالة"],["للتغطية","20 غ قطع جوز"]],
["سخّن الفرن إلى 180° مئوية/علامة الغاز 4 وادهن قالب كعك مقاس 20 سم × 25 سم قليلًا بزيت اللفت.","في وعاء، اخلط الدقيق والبيكنج باودر والتوابل معًا.","في وعاء آخر أضف البيض والموز واخفق جيدًا. أضف المحلي والزيت وامزج.","اطوِ المكونات الجافة تدريجيًا في خليط الموز والبيض والزيت، ثم اطوِ فيه الزبيب والجزر.","اسكب الخليط في قالب الكعك واخبزه من 25 إلى 30 دقيقة ثم أخرجه من الفرن واتركه يبرد على رف سلكي.","عندما تبرد الكعكة، غطِّها بالكوارك المحلى وزيّنها بقشر البرتقال وقطع الجوز."],
["تأكد من أن الكعكة قد برُدت تمامًا قبل تغطيتها وإلا ذاب الجبن الكريمي.","جرّب تقطيعها إلى مربعات صغيرة قبل تغطيتها، ثم اضغط كتلة من الجبن الكريمي المحلى على كل مربع وانثر عليه قشر البرتقال وقطعة جوز.","يمكنك استخدام القرفة بدلًا من خليط التوابل أو تجربة مكسرات مختلفة مثل البندق أو اللوز."])}))
I.append((7011229,{
"es":L("Guiso de calabaza butternut y frijoles borlotti","Un plato invernal lleno de color que se puede cocinar en una sola sartén.","6","454g",
["1 cucharadita de aceite de colza","2 cebollas moradas, picadas","1 calabaza butternut mediana, sin semillas, pelada y en cubos","1 pimiento verde, picado","1 cubito de caldo de verduras disuelto en 500ml de agua","2 latas de 400g de tomates","50g de lentejas rojas secas","1 cucharadita colmada de orégano seco","1 buena pizca de hojuelas de chile","4 dientes de ajo, machacados","2 latas de 400g de frijoles borlotti, escurridos","una buena molida de pimienta negra","1 cucharada de perejil picado, para decorar"],
["Caliente el aceite en una sartén y agregue las cebollas, la calabaza y el pimiento verde. Revuelva con frecuencia durante 5 minutos, hasta que empiecen a dorarse.","Añada el caldo, los tomates, las lentejas rojas, el orégano, el chile y el ajo. Lleve a ebullición, reduzca el fuego, tape y cocine a fuego lento durante 10 minutos.","Añada los frijoles y caliente 10 minutos más; compruebe que la calabaza esté bien cocida (hasta que esté tierna). Sirva con una buena molida de pimienta negra y un poco de perejil espolvoreado."],
["Es ideal con calabaza de Castilla en lugar de calabaza butternut.","Cualquier tipo de frijol queda bien; podría usar dos variedades distintas o latas de frijoles mixtos.","Pruebe a rellenar mitades de pimientos con esta mezcla, espolvoree con un poco de queso y hornee a 180°/gas 4 durante 15 minutos, hasta que el pimiento esté blando y el queso dorado.","Instrucciones para congelar: Se puede congelar una vez cocido. Luego descongele en el refrigerador y recaliente en el microondas o en la estufa hasta que esté bien caliente por completo.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 5"]]),
"ar":L("يخنة القرع الجوزي وفاصولياء البورلوتي","طبق شتوي ملوّن يمكنك طهيه في مقلاة واحدة.","6","454 غ",
["1 ملعقة صغيرة زيت اللفت","2 بصلة حمراء، مفرومة","1 حبة قرع جوزي متوسطة، منزوعة البذور ومقشرة ومقطعة مكعبات","1 حبة فلفل أخضر، مفرومة","1 مكعب مرق خضار مذاب في 500 مل ماء","2 علبة 400 غ طماطم","50 غ عدس أحمر مجفف","1 ملعقة صغيرة مكدسة أوريغانو مجفف","رشة جيدة من رقائق الفلفل الحار","4 فص ثوم، مهروس","2 علبة 400 غ فاصولياء بورلوتي، مصفاة","طحنة جيدة من الفلفل الأسود","1 ملعقة كبيرة بقدونس مفروم، للتزيين"],
["سخّن الزيت في مقلاة وأضف البصل والقرع والفلفل الأخضر. قلّب بانتظام لمدة 5 دقائق حتى يبدأ بالاحمرار.","أضف المرق والطماطم والعدس الأحمر والأوريغانو والفلفل الحار والثوم. اتركه حتى يغلي، ثم اخفض النار وغطِّه واتركه على نار هادئة لمدة 10 دقائق.","أضف الفاصولياء وسخّنها 10 دقائق إضافية، وتأكد من أن القرع قد نضج تمامًا (حتى يلين). قدّمه مع طحنة جيدة من الفلفل الأسود ورشة من البقدونس."],
["مثالي مع اليقطين بدلًا من القرع الجوزي.","يناسب أي نوع من الفاصولياء، ويمكنك استخدام نوعين مختلفين أو علب فاصولياء مشكلة.","جرّب حشوه في أنصاف الفلفل، وغطِّه برشة من الجبن واخبزه في الفرن على 180°/علامة الغاز 4 لمدة 15 دقيقة حتى يلين الفلفل ويحمرّ الجبن.","تعليمات التجميد: مناسب للتجميد بعد الطهي. ثم ذوّبه في الثلاجة وأعد تسخينه في الميكروويف أو على الموقد حتى يسخن تمامًا من الداخل.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 5"]])}))
I.append((7013544,{
"es":L("Pastel de manzana y canela","Un postre sabroso hecho con harina integral.","8","159g",
["100g de harina integral","1 cucharada colmada de edulcorante artificial granulado","1 cucharadita rasa de canela molida","6g de polvo para hornear","3 huevos","3 cucharadas rasas de leche descremada","75g de grasa vegetal para untar, derretida","1kg de manzanas"],
["Precaliente el horno a 200°C/gas 6.","Tamice la harina en un bol, añada el edulcorante artificial, el polvo para hornear y la canela, y mezcle.","Haga un hueco en el centro de los ingredientes secos y agregue los huevos y la leche. Bata e incorpore la mantequilla derretida.","Pele las manzanas, quíteles el corazón y las semillas. Córtelas en rodajas grandes. Añada las rodajas de manzana a la mezcla e incorpórelas con suavidad.","Engrase un molde para pastel (de unos 23cm de diámetro) con un poco de aceite vegetal. Vierta la mezcla en el molde y hornee durante 35 minutos.","Desmolde sobre una rejilla. Deje enfriar y sirva."],
["Comience preparando la masa para poder dejarla reposar mientras pela las manzanas.","También puede reemplazar las manzanas por peras, y la canela por jengibre molido o mezcla de especias."]),
"ar":L("كعكة التفاح والقرفة","حلوى شهية مصنوعة من دقيق القمح الكامل.","8","159 غ",
["100 غ دقيق قمح كامل","1 ملعقة كبيرة مكدسة محلي صناعي محبب","1 ملعقة صغيرة مستوية قرفة مطحونة","6 غ بيكنج باودر","3 بيضات","3 ملاعق كبيرة مستوية حليب منزوع الدسم","75 غ دهن نباتي، مذاب","1 كغ تفاح"],
["سخّن الفرن مسبقًا إلى 200° مئوية/علامة الغاز 6.","اغربل الدقيق في وعاء، وأضف المحلي الصناعي والبيكنج باودر والقرفة إلى الدقيق وامزج.","اصنع حفرة في وسط المكونات الجافة وأضف البيض والحليب. اخفق وأضف الزبدة المذابة.","قشّر التفاح وانزع قلبه وبذوره. قطّعه إلى شرائح كبيرة. أضف شرائح التفاح إلى الخليط وقلّب برفق.","ادهن قالب كعك (قطره حوالي 23 سم) بقليل من الزيت النباتي. اسكب الخليط في القالب واخبزه في الفرن لمدة 35 دقيقة.","اقلبه على رف تبريد. اتركه ليبرد وقدّمه."],
["ابدأ بتحضير العجينة، لتتركها جانبًا بينما تقشّر التفاح.","يمكنك أيضًا استبدال التفاح بالكمثرى، والقرفة بالزنجبيل المطحون أو خليط التوابل."])}))
I.append((7014156,{
"es":L("Curry de coliflor asada, paneer y garbanzos","Un delicioso y sabroso curry de verduras con paneer y garbanzos. Cubierto con coliflor asada, picante y crujiente.","4","504g",
["2 cucharaditas de aceite","500g de coliflor, en ramilletes pequeños","2 cucharaditas de cúrcuma","2 cebollas, picadas","1 camote grande, en cubos (300g)","1 pimiento rojo, picado","3 dientes de ajo, machacados","1 cucharadita de comino molido","1 cucharada de pasta de curry de intensidad media","1 cubito de caldo de verduras bajo en sal, disuelto en 400ml de agua","100g de paneer","240g de garbanzos, escurridos","80g de guisantes congelados, descongelados","2 cucharadas de yogur con 0% de grasa"],
["Precaliente el horno a 180°C/gas 4 y engrase ligeramente una bandeja para hornear con 1 cucharadita de aceite.","Enjuague la coliflor con agua fría, sacuda el exceso y colóquela en un bol. Espolvoree con la cúrcuma y mezcle bien. Colóquela en la bandeja y áselo durante 20 minutos, hasta que los bordes empiecen a chamuscarse; luego reserve.","Mientras tanto, ponga 1 cucharadita de aceite en una sartén y añada la cebolla. Cocine de 3 a 4 minutos hasta que se ablande, sin que se dore.","Añada el camote, el pimiento rojo, el ajo, el comino y la pasta de curry, y cocine de 2 a 3 minutos más, revolviendo con frecuencia.","Vierta el caldo, mezcle bien, tape y cocine a fuego lento de 8 a 10 minutos, hasta que el camote esté casi tierno.","Añada el paneer, los garbanzos y los guisantes, y continúe hirviendo sin tapa de 5 a 6 minutos. Incorpore el yogur y sirva cubierto con la coliflor asada."],
["Experimente con frijoles mixtos o frijoles cannellini en lugar de garbanzos.","Pruebe a añadir otras verduras, como 150g de espinacas frescas o champiñones.","Puede usar un yogur natural de su elección, pero esto cambiará la información nutricional.","Instrucciones para congelar: Se puede congelar una vez cocido. Descongele en el refrigerador o en el microondas y luego recaliente hasta que esté bien caliente por completo.",["Porciones de fruta/verdura","Porciones de fruta/verdura por ración: 4"]]),
"ar":L("كاري القرنبيط المشوي والبانير والحمص","كاري خضار لذيذ وشهي مع جبن البانير والحمص. يعلوه قرنبيط مشوي حار ومقرمش.","4","504 غ",
["2 ملعقة صغيرة زيت","500 غ قرنبيط، على شكل زهيرات صغيرة","2 ملعقة صغيرة كركم","2 بصلة، مفرومة","1 حبة بطاطا حلوة كبيرة، مقطعة مكعبات (300 غ)","1 حبة فلفل أحمر، مفرومة","3 فص ثوم، مهروس","1 ملعقة صغيرة كمون مطحون","1 ملعقة كبيرة معجون كاري متوسط الحدة","1 مكعب مرق خضار قليل الملح، مذاب في 400 مل ماء","100 غ جبن بانير","240 غ حمص، مصفى","80 غ بازلاء مجمدة، مذابة","2 ملعقة كبيرة زبادي خالٍ من الدسم 0%"],
["سخّن الفرن مسبقًا إلى 180° مئوية/علامة الغاز 4 وادهن صينية خبز قليلًا بـ 1 ملعقة صغيرة من الزيت.","اشطف القرنبيط بالماء البارد، وانفض عنه الماء الزائد، ثم ضعه في وعاء. رشّ عليه الكركم وامزج جيدًا. ضعه على صينية الخبز واشوِه لمدة 20 دقيقة، حتى تبدأ الحواف بالاحتراق قليلًا، ثم ضعه جانبًا.","في هذه الأثناء، أضف 1 ملعقة صغيرة من الزيت إلى مقلاة وأضف البصل. اطهُه من 3 إلى 4 دقائق حتى يطرى دون أن يحمرّ.","أضف البطاطا الحلوة والفلفل الأحمر والثوم والكمون ومعجون الكاري، ثم اطهُ من 2 إلى 3 دقائق إضافية مع التقليب بانتظام.","اسكب المرق وامزج جيدًا وغطِّه ثم اتركه على نار هادئة من 8 إلى 10 دقائق حتى تكاد البطاطا تلين.","أضف البانير والحمص والبازلاء، ثم واصل الغليان دون غطاء من 5 إلى 6 دقائق. أضف الزبادي وقلّب وقدّمه مغطى بالقرنبيط المشوي."],
["جرّب الفاصولياء المشكلة أو فاصولياء كانيليني بدلًا من الحمص.","جرّب إضافة خضار مختلفة مثل 150 غ من السبانخ الطازجة أو الفطر.","يمكنك استخدام زبادي سادة من اختيارك، لكن ذلك سيغيّر المعلومات الغذائية.","تعليمات التجميد: مناسب للتجميد بعد الطهي. ذوّبه في الثلاجة أو الميكروويف، ثم أعد تسخينه حتى يسخن تمامًا من الداخل.",["حصص الفاكهة/الخضار","حصص الفاكهة/الخضار لكل حصة: 4"]])}))
save(2,I)
