from h import *
I=[]
FV_ES="Porciones de fruta/verdura"; FV_AR="حصص الفاكهة/الخضار"
def fv(n): return [[FV_ES,f"Porciones de fruta/verdura por ración: {n}"]],[[FV_AR,f"حصص الفاكهة/الخضار لكل حصة: {n}"]]
I.append((7041630,{
"es":L("Sopa de calabaza butternut asada y lentejas rojas","Una sopa caliente y abundante, fácil de preparar, baja en grasa, alta en fibra y muy saciante.","4","414g",
["1 calabaza butternut (aprox. 700g–1kg)","2 cucharaditas de aceite de girasol","1 cebolla grande, picada grueso","1 zanahoria, picada gruesa","1 litro de caldo de verduras con sal reducida (hecho con cubito)","120g de lentejas rojas partidas","pimienta blanca, al gusto","4 cucharadas de crème fraîche semidescremada","Cebollín fresco, picado"],
["Precaliente el horno a 200°C/gas 7. Corte la calabaza butternut en cuartos a lo largo, retire las semillas, úntela con un poco del aceite y hornee durante 25 minutos.","Mientras tanto, ponga la cebolla y la zanahoria en la olla con 1 cucharadita del aceite y cocine suavemente unos minutos, hasta que la cebolla empiece a dorarse.","Ahora vierta el caldo en la olla y añada las lentejas, revuelva y cocine a fuego lento durante unos 15 minutos.","Retire la calabaza butternut del horno, saque la pulpa con una cuchara y añádala a la sopa.","Cocine a fuego lento 5 minutos más, añada una buena pizca de pimienta y luego licúe con una batidora de mano o en un procesador de alimentos hasta que quede suave.","Sirva con un remolino de crème fraîche semidescremada y un poco de cebollín picado."],
["Esta receta es alta en vitamina A, que ayuda a que su sistema inmunitario funcione de la mejor manera.","Los cubitos de caldo contienen sal, así que no agregue sal adicional durante la cocción. Al cocinar la sopa a fuego lento, se reduce el contenido de agua y se concentra el contenido de sal; por eso pruébela una vez cocida y agregue sal solo si es necesario.","Instrucciones para congelar: Congele en porciones y luego descongele en el refrigerador, o descongele en el microondas y recaliente bien hasta que esté bien caliente.",*fv(3)[0]]),
"ar":L("حساء القرع الجوزي المشوي والعدس الأحمر","حساء دافئ ومشبع وسهل التحضير، قليل الدسم وغني بالألياف ومشبع بشكل مُرضٍ.","4","414 غ",
["1 حبة قرع جوزي (حوالي 700 غ–1 كغ)","2 ملعقة صغيرة زيت عباد الشمس","1 بصلة كبيرة، مفرومة فرمًا خشنًا","1 جزرة، مفرومة فرمًا خشنًا","1 لتر مرق خضار بملح مخفض (من مكعبات المرق)","120 غ عدس أحمر مجروش","فلفل أبيض، حسب الذوق","4 ملاعق كبيرة كريم فريش نصف دسم","ثوم معمر (شيف) طازج، مفروم"],
["سخّن الفرن مسبقًا إلى 200° مئوية/علامة الغاز 7. قطّع القرع الجوزي إلى أرباع بالطول، وأخرج البذور، وادهنه بقليل من الزيت واخبزه في الفرن لمدة 25 دقيقة.","في هذه الأثناء، أضف البصل والجزر إلى القدر مع 1 ملعقة صغيرة من الزيت، واطهُ بهدوء لبضع دقائق، حتى يبدأ البصل بالاحمرار.","الآن، اسكب المرق في القدر وأضف العدس، وقلّب معًا واتركه على نار هادئة لحوالي 15 دقيقة.","أخرج القرع الجوزي من الفرن، وأخرج اللب بالملعقة وأضفه إلى الحساء.","اتركه على نار هادئة 5 دقائق إضافية، وأضف رشة جيدة من الفلفل، ثم اخلطه بخلاط يدوي أو في محضّر الطعام حتى يصبح ناعمًا.","قدّمه مع دوّامة من كريم فريش نصف الدسم وقليل من الثوم المعمر المفروم."],
["هذه الوصفة غنية بفيتامين أ، الذي يساعد جهازك المناعي على العمل بأفضل شكل.","تحتوي مكعبات المرق على الملح، لذا لا تضف أي ملح إضافي أثناء الطهي. وعند إبقاء الحساء على نار هادئة، ينقص محتوى الماء ويتركز محتوى الملح، لذا تذوّقه بعد الطهي وأضف الملح عند الحاجة فقط.","تعليمات التجميد: جمّده في حصص ثم ذوّبه في الثلاجة، أو ذوّبه في الميكروويف وأعد تسخينه جيدًا حتى يسخن تمامًا.",*fv(3)[1]])}))
I.append((7044698,{
"es":L("Sopa de lentejas rojas","Una sopa sabrosa, reconfortante y nutritiva.","2","304g",
["100g de lentejas rojas, enjuagadas","1 cebolla pequeña, picada","1 zanahoria, picada","1 diente de ajo, machacado","600ml de caldo de verduras bajo en sal","2 cucharadas de crème fraîche ligera","1 cucharada de perejil fresco, picado","pimienta negra recién molida","pan, para servir"],
["Ponga las lentejas, la cebolla, la zanahoria, el ajo y el caldo en una olla, lleve a ebullición y cocine a fuego lento de 20 a 25 minutos, hasta que las lentejas estén tiernas.","Pase a una licuadora con la crème fraîche y el perejil y licúe hasta que quede suave. Sazone y sirva con un trozo de pan."],
["Para una versión vegana, simplemente omita la crème fraîche o añada 4 cucharadas de leche de soja en su lugar.","Dele un toque picante con 1 cucharadita de pasta o polvo de curry o una pizca de hojuelas de chile.","Instrucciones para congelar: Congele en porciones y luego descongele en el refrigerador, o descongele en el microondas, teniendo cuidado de revolver con frecuencia.",*fv(2)[0]]),
"ar":L("حساء العدس الأحمر","حساء لذيذ مُدفئ ومغذٍّ في آن واحد.","2","304 غ",
["100 غ عدس أحمر، مشطوف","1 بصلة صغيرة، مفرومة","1 جزرة، مفرومة","1 فص ثوم، مهروس","600 مل مرق خضار قليل الملح","2 ملعقة كبيرة كريم فريش خفيف","1 ملعقة كبيرة بقدونس طازج، مفروم","فلفل أسود مطحون طازجًا","خبز، للتقديم"],
["ضع العدس والبصل والجزر والثوم والمرق في قدر، واتركه حتى يغلي ثم اتركه على نار هادئة من 20 إلى 25 دقيقة، حتى يلين العدس.","انقله إلى الخلاط مع كريم فريش والبقدونس واخلطه حتى يصبح ناعمًا. تبّله وقدّمه مع قطعة خبز."],
["لنسخة نباتية، احذف كريم فريش ببساطة أو أضف بدلًا منه 4 ملاعق كبيرة من حليب الصويا.","أضف إليه نكهة حارة بـ 1 ملعقة صغيرة من معجون أو مسحوق الكاري أو رشة من رقائق الفلفل الحار.","تعليمات التجميد: جمّده في حصص ثم ذوّبه في الثلاجة، أو ذوّبه في الميكروويف مع الحرص على التقليب بانتظام.",*fv(2)[1]])}))
I.append((7046638,{
"es":L("Taza para microondas: avena con manzana y canela","Esta avena con frutas es reconfortante, saciante y rápida de preparar, ideal para empezar el día de manera saludable.","1","263g",
["35g de avena en hojuelas","1 cucharadita de edulcorante artificial (opcional)","1 cucharadita de canela, más una pizca para decorar","1 manzana pequeña, picada en trozos pequeños","25ml de leche semidescremada"],
["Ponga la avena, el edulcorante opcional, la canela y la manzana en una taza y mezcle.","Añada 100ml de agua y cocine a máxima potencia (800W) durante dos minutos.","Agregue la leche, mezcle y espolvoree un poco de canela por encima."],
["Podría usar pera o plátano en lugar de manzana, o añadir un poco de fruta seca, como ciruelas pasas o pasas.","Pruebe a añadir unas cuantas nueces picadas, o semillas de girasol o de calabaza.",*fv(1)[0]]),
"ar":L("كوب الميكروويف: عصيدة الشوفان بالتفاح والقرفة","عصيدة الفاكهة هذه دافئة ومشبعة وسريعة التحضير – مثالية لبداية صحية.","1","263 غ",
["35 غ شوفان للعصيدة","1 ملعقة صغيرة محلي صناعي (اختياري)","1 ملعقة صغيرة قرفة، بالإضافة إلى رشة للتزيين","1 تفاحة صغيرة، مقطعة قطعًا صغيرة","25 مل حليب نصف خالي الدسم"],
["ضع الشوفان والمحلي الاختياري والقرفة والتفاح في كوب كبير وامزجها.","أضف 100 مل من الماء واطهُه على القوة الكاملة (800 واط) لمدة دقيقتين.","أضف الحليب وامزج ورشّ قليلًا من القرفة فوقه."],
["يمكنك استخدام الكمثرى أو الموز بدلًا من التفاح أو إضافة قليل من الفاكهة المجففة، مثل البرقوق المجفف أو الزبيب.","جرّب إضافة بضع حبات من المكسرات المفرومة، أو بذور عباد الشمس أو اليقطين.",*fv(1)[1]])}))
I.append((7046889,{
"es":L("Chili con carne","Este chili reconfortante es un clásico contundente que siempre gusta. Lleno de verduras y proteínas, es una comida rápida y fácil a la que siempre se puede recurrir.","8","328g",
["1 cucharadita de aceite de girasol","2 cebollas, finamente picadas","500g de carne molida de res magra (5% de grasa)","250g de champiñones, en rodajas","1 pimiento rojo, finamente picado","1 pimiento amarillo, finamente picado","1 calabacín, en cubitos","4 dientes de ajo, machacados","1–2 cucharaditas de chile en polvo (picante o suave, según su preferencia)","2 cucharaditas de orégano","2 cucharaditas de comino","1 lata de 800g de tomates picados","1 lata de 390g de lentejas (236g una vez escurridas y enjuagadas)","1 lata de 400g de frijoles rojos","25g de chocolate amargo (70% de sólidos de cacao)"],
["Ponga el aceite en una olla grande, añada las cebollas y cocine de 3 a 4 minutos, hasta que apenas empiecen a dorarse.","Añada la carne molida y cocine de 5 a 7 minutos (o hasta que esté bien cocida), deshaciendo los grumos con una cuchara de madera.","Añada los champiñones, los pimientos, el calabacín y el ajo. Cocine de 7 a 8 minutos más, revolviendo con frecuencia, hasta que se ablanden.","Incorpore el chile, el orégano, el comino y los tomates, luego tape con una tapa y cocine suavemente a fuego lento durante 10 minutos, revolviendo de vez en cuando.","Añada las lentejas y los frijoles, y mezcle bien. Tape y cocine a fuego lento 5 minutos más.","Incorpore el chocolate hasta que se derrita. Sirva con ensalada."],
["El chocolate amargo intensifica los sabores, es más saludable y funciona mejor que otros tipos de chocolate.","Instrucciones para congelar: Se puede congelar una vez cocido. Descongele por completo en el refrigerador y recaliente hasta que esté bien caliente por completo, revolviendo con frecuencia.",*fv(3)[0]]),
"ar":L("تشيلي كون كارني","هذا التشيلي المُدفئ هو طبق كلاسيكي مشبع يلقى استحسانًا دائمًا. مليء بالخضار والبروتين، وهو وجبة سريعة وسهلة يمكن الاعتماد عليها.","8","328 غ",
["1 ملعقة صغيرة زيت عباد الشمس","2 بصلة، مفرومة ناعمًا","500 غ لحم بقري مفروم قليل الدسم (5% دهون)","250 غ فطر، مقطع شرائح","1 حبة فلفل أحمر، مفرومة ناعمًا","1 حبة فلفل أصفر، مفرومة ناعمًا","1 كوسا، مقطعة مكعبات","4 فص ثوم، مهروس","1–2 ملعقة صغيرة مسحوق الفلفل الحار (حار أو معتدل حسب رغبتك)","2 ملعقة صغيرة أوريغانو","2 ملعقة صغيرة كمون","1 علبة 800 غ طماطم مفرومة","1 علبة 390 غ عدس (236 غ بعد التصفية والشطف)","1 علبة 400 غ فاصولياء حمراء","25 غ شوكولاتة داكنة عادية (70% كاكاو صلب)"],
["أضف الزيت إلى قدر كبير، ثم أضف البصل واطهُه من 3 إلى 4 دقائق حتى يبدأ بالاحمرار بالكاد.","أضف اللحم البقري المفروم واطهُه من 5 إلى 7 دقائق (أو حتى ينضج تمامًا)، مع تفتيت أي كتل بملعقة خشبية.","أضف الفطر والفلفل والكوسا والثوم. اطهُ من 7 إلى 8 دقائق إضافية مع التقليب بانتظام حتى تطرى.","أضف الفلفل الحار والأوريغانو والكمون والطماطم وقلّب، ثم غطِّه بغطاء واتركه على نار هادئة برفق لمدة 10 دقائق مع التقليب من حين لآخر.","أضف العدس والفاصولياء وامزج جيدًا. غطِّه واتركه على نار هادئة 5 دقائق إضافية.","أضف الشوكولاتة وقلّب حتى تذوب. قدّمه مع السلطة."],
["تُعزز الشوكولاتة الداكنة النكهات، وهي أكثر صحة وتعطي نتيجة أفضل من الأنواع الأخرى من الشوكولاتة.","تعليمات التجميد: مناسب للتجميد بعد الطهي. ذوّبه تمامًا في الثلاجة وأعد تسخينه حتى يسخن تمامًا من الداخل مع التقليب بانتظام.",*fv(3)[1]])}))
I.append((7046954,{
"es":L("Salsa de manzana y arándanos rojos","Una salsa rápida y fácil para acompañar su cena de Navidad.","6","53g",
["2 manzanas","2 cucharadas colmadas de salsa de arándanos rojos","1 cucharada de arándanos rojos secos"],
["Quite el corazón a las manzanas y píquelas de forma gruesa; luego póngalas en una olla con un chorrito de agua. Añada la salsa de arándanos rojos y los arándanos rojos secos.","Caliente suavemente, revolviendo con frecuencia de 5 a 6 minutos, hasta que las manzanas se hayan ablandado."],
["Guarde en el refrigerador.","Instrucciones para congelar: Se puede congelar una vez cocida. Congele en porciones y luego descongele y sirva fría o tibia.",*fv(0)[0]]),
"ar":L("صلصة التفاح والتوت البري","صلصة سريعة وسهلة لمرافقة عشاء الكريسماس.","6","53 غ",
["2 تفاحة","2 ملعقة كبيرة مكدسة صلصة التوت البري","1 ملعقة كبيرة توت بري مجفف"],
["انزع قلب التفاح وقطّعه فرمًا خشنًا، ثم ضعه في قدر مع رشة ماء. أضف صلصة التوت البري والتوت البري المجفف.","سخّنها برفق مع التقليب بانتظام من 5 إلى 6 دقائق حتى يطرى التفاح."],
["احفظها في الثلاجة.","تعليمات التجميد: مناسبة للتجميد بعد الطهي. جمّدها في حصص ثم ذوّبها وقدّمها باردة أو دافئة.",*fv(0)[1]])}))
I.append((7048524,{
"es":L("Fruta a la barbacoa","Un giro interesante a la comida a la barbacoa, usando fruta en lugar de ingredientes salados.","6","195g",
["3 peras, peladas, sin corazón y cortadas en cuartos","2 manzanas, peladas, sin corazón y cortadas en cuartos","1 buena pizca de mezcla de especias","5 rebanadas de melón honeydew, cortadas en cubos (pulpa comestible 500g)"],
["Simplemente mezcle todos los ingredientes, repártalos en 6 cuadrados grandes de papel de aluminio y ciérrelos formando paquetes.","Cocine sobre las brasas de la barbacoa durante unos 10 a 12 minutos y sirva."],
["¿Por qué no probar una versión tropical? Use mangos y piña.","Queda muy bien con diferentes especias, como canela o jengibre molido.",*fv(2)[0]]),
"ar":L("فواكه مشوية على الفحم","لمسة مثيرة للاهتمام على أطعمة الشواء، باستخدام الفاكهة بدلًا من المكونات المالحة.","6","195 غ",
["3 حبات كمثرى، مقشرة ومنزوعة القلب ومقطعة أرباعًا","2 تفاحة، مقشرة ومنزوعة القلب ومقطعة أرباعًا","رشة جيدة من خليط التوابل","5 شرائح شمام عسلي، مقطعة مكعبات (اللب الصالح للأكل 500 غ)"],
["اخلط جميع المكونات ببساطة، ووزّعها على 6 مربعات كبيرة من ورق الألمنيوم وأغلقها على شكل طرود.","اطهُها فوق فحم الشواء لحوالي 10–12 دقيقة وقدّمها."],
["لماذا لا تجرّب نسخة استوائية؟ استخدم المانجو والأناناس.","تناسبها توابل مختلفة، مثل القرفة أو الزنجبيل المطحون.",*fv(2)[1]])}))
I.append((7050301,{
"es":L("Huevos al horno con espinacas, champiñones y papas fritas al horno","Este sabroso plato de huevos al horno es una opción vegetariana perfecta para el almuerzo o la cena. Las papas fritas caseras de acompañamiento son estupendas para mojar en las yemas. Esta receta fue seleccionada en colaboración con Slimming World.","4","578g",
["750g de papas harinosas, como Maris Piper o King Edward, cortadas en bastones","Aceite en spray bajo en calorías","1 cebolla, en cubitos finos","500g de champiñones castaña, en rodajas finas","1 pizca grande de nuez moscada molida","2 dientes de ajo, machacados","600g de espinacas congeladas, descongeladas y bien escurridas","75g de yogur griego natural sin grasa y sin azúcar","4 huevos grandes"],
["Precaliente el horno a 200°C/ventilador 180°C/gas 6. Extienda las papas en una bandeja para hornear grande antiadherente en una sola capa. Rocíe con un par de pulverizaciones de aceite en spray bajo en calorías y sazone con pimienta. Hornee durante 40 minutos, o hasta que estén doradas, volteándolas a la mitad.","Mientras tanto, rocíe una sartén grande antiadherente con un par de pulverizaciones de aceite en spray bajo en calorías y colóquela a fuego medio-alto. Cuando esté caliente, añada la cebolla y los champiñones, y saltee de 5 a 6 minutos, hasta que se ablanden y tomen un poco de color. Incorpore la nuez moscada y el ajo. Cocine 2 minutos hasta que desprendan aroma, luego añada las espinacas y revuelva todo hasta que esté bien caliente por completo. Retire del fuego e incorpore el yogur; luego sazone con pimienta.","Reparta la mezcla en 4 platos individuales para tarta o viértala en 1 plato grande para tarta. Haga 4 huecos en la mezcla y rompa un huevo en cada uno. Cubra con un toque de pimienta negra y hornee en la rejilla inferior a las papas durante los últimos 15 minutos de cocción de las papas, o hasta que las claras estén cuajadas. Reparta las papas en 4 platos y sirva con los huevos al horno."],
["Puede usar un yogur natural de su elección. Sin embargo, esto cambiará la información nutricional y la textura del plato.","Los grupos de riesgo, como los bebés, los niños, las mujeres embarazadas, los ancianos y las personas enfermas, deben evitar los huevos poco cocidos o crudos, a menos que puedan garantizar que se hayan producido bajo el programa de garantía de calidad Lion Code.",*fv(3)[0]]),
"ar":L("بيض مخبوز بالسبانخ والفطر والبطاطس المقلية بالفرن","طبق البيض المخبوز اللذيذ هذا خيار نباتي مثالي للغداء أو العشاء. أصابع البطاطس المنزلية الجانبية رائعة لغمسها في صفار البيض. تم اختيار هذه الوصفة بالتعاون مع Slimming World.","4","578 غ",
["750 غ بطاطس دقيقية القوام، مثل ماريس بايبر أو كينغ إدوارد، مقطعة أصابع","بخاخ طهي قليل السعرات","1 بصلة، مقطعة مكعبات صغيرة","500 غ فطر كستنائي، مقطع شرائح رفيعة","رشة كبيرة من جوزة الطيب المطحونة","2 فص ثوم، مهروس","600 غ سبانخ مجمدة، مذابة ومعصورة جيدًا","75 غ زبادي يوناني طبيعي خالٍ من الدسم وغير محلى","4 بيضات كبيرة"],
["سخّن الفرن مسبقًا إلى 200° مئوية/بالمروحة 180° مئوية/علامة الغاز 6. افرد أصابع البطاطس على صينية خبز كبيرة غير لاصقة في طبقة واحدة. رشّها بضغطتين من بخاخ الطهي قليل السعرات وتبّلها بالفلفل. اخبزها لمدة 40 دقيقة، أو حتى تصبح ذهبية، مع قلبها في المنتصف.","في هذه الأثناء، رشّ مقلاة كبيرة غير لاصقة بضغطتين من بخاخ الطهي قليل السعرات وضعها على نار متوسطة إلى عالية. عندما تسخن، أضف البصل والفطر وقلّبهما من 5 إلى 6 دقائق حتى يطريا ويكتسبا بعض اللون. أضف جوزة الطيب والثوم. اطهُ دقيقتين حتى تفوح الرائحة، ثم أضف السبانخ وقلّب كل شيء معًا حتى يسخن تمامًا من الداخل. ارفعه عن النار وأضف الزبادي وقلّب، ثم تبّله بالفلفل.","إما أن توزع الخليط على 4 أطباق فطائر فردية، أو تسكبه في طبق فطيرة كبير واحد. اصنع 4 حفر في الخليط واكسر بيضة في كل حفرة. غطِّها بطحنة من الفلفل الأسود واخبزها على الرف الأسفل من البطاطس خلال آخر 15 دقيقة من وقت طهي البطاطس، أو حتى يتماسك بياض البيض. وزّع البطاطس على 4 أطباق وقدّمها مع البيض المخبوز."],
["يمكنك استخدام زبادي سادة من اختيارك. ومع ذلك، سيغيّر ذلك المعلومات الغذائية وقوام الطبق.","ينبغي للفئات المعرضة للخطر مثل الرضع والأطفال والحوامل وكبار السن والمرضى تجنب البيض الطري/الخفيف الطهي والنيئ، ما لم يكن بإمكانهم ضمان أنه أُنتج وفق نظام ضمان الجودة Lion Code.",*fv(3)[1]])}))
I.append((7052242,{
"es":L("Barras integrales de frutas","Ideales para las loncheras o como refrigerio saludable.","25","39g",
["175g de pasas","50g de azúcar","100g de grasa vegetal para untar","1 cucharadita colmada de mezcla de especias","350g de harina integral común","50g de nueces picadas","50g de dátiles picados"],
["Precaliente el horno a 180ºC/gas 4 y engrase ligeramente una bandeja para hornear de 19cm x 28cm.","Ponga las pasas, el azúcar, la grasa vegetal y la mezcla de especias en una olla mediana con 200ml de agua.","Lleve a ebullición, luego retire del fuego y deje enfriar.","En un recipiente aparte, mezcle los demás ingredientes y luego incorpórelos a la mezcla de pasas. Vierta con una cuchara en el molde preparado, alise hasta obtener 1½ cm de grosor y hornee de 25 a 30 minutos.","Inmediatamente después de sacarlo del horno, marque 25 barras.","Deje enfriar y sirva."],
["Pruebe a añadir diferentes especias, como canela o jengibre molido.","También puede usar frutas secas, como fruta seca variada, uvas sultanas, ciruelas pasas o albaricoques.","Instrucciones para congelar: Se puede congelar una vez cocidas. Congele en porciones y luego descongele y sirva frías o tibias.",*fv(0)[0]]),
"ar":L("ألواح الفاكهة بالقمح الكامل","مثالية لعلب الغداء أو كوجبة خفيفة صحية.","25","39 غ",
["175 غ زبيب","50 غ سكر","100 غ دهن نباتي","1 ملعقة صغيرة مكدسة خليط توابل","350 غ دقيق حبوب كاملة عادي","50 غ جوز مفروم","50 غ تمر مفروم"],
["سخّن الفرن مسبقًا إلى 180° مئوية/علامة الغاز 4 وادهن صينية خبز مقاس 19 سم × 28 سم قليلًا.","ضع الزبيب والسكر والدهن النباتي وخليط التوابل في قدر متوسط مع 200 مل من الماء.","اتركه حتى يغلي، ثم ارفعه عن النار واتركه ليبرد.","في طبق منفصل، اخلط المكونات المتبقية ثم أضفها إلى خليط الزبيب وقلّب. اسكبه بالملعقة في القالب المجهّز، وسوّه بسماكة 1½ سم ثم اخبزه من 25 إلى 30 دقيقة.","فور إخراجه من الفرن، علّم عليه لتقطيعه إلى 25 لوحًا.","اتركه ليبرد وقدّمه."],
["جرّب إضافة توابل مختلفة مثل القرفة أو الزنجبيل المطحون.","يمكنك أيضًا استخدام فواكه مجففة مثل الفواكه المجففة المشكلة أو الزبيب السلطاني أو البرقوق المجفف أو المشمش المجفف.","تعليمات التجميد: مناسبة للتجميد بعد الطهي. جمّدها في حصص ثم ذوّبها وقدّمها باردة أو دافئة.",*fv(0)[1]])}))
I.append((7053704,{
"es":L("Pizza turca de coliflor con Quorn y tzatziki","La coliflor es una alternativa saludable y más baja en carbohidratos a la base de pizza tradicional.","4","478g",
["Para la base: 900 g/32 oz de coliflor, cortada en ramilletes","1 cebolla pequeña, finamente picada","1 huevo mediano, batido","40g/3 oz de queso crema con 3% de grasa, p. ej., queso crema Philadelphia lightest, o 40g/3 oz de yogur natural bajo en grasa","2 cucharadas de harina integral","1/4 cucharadita de pimienta negra recién molida","1 cucharadita de aceite de oliva","Para las coberturas: 1 cucharadita de aceite de oliva","300 g/12 oz de carne molida sin carne Quorn","2 cucharaditas de pimentón ahumado","1 cucharadita de comino molido","1 cucharadita de cilantro molido","1/2 cucharadita de orégano seco","1 pepino grande, la mitad rallado y la otra mitad en cubitos finos","175 g/5 oz de tomates cherry, cortados en cuartos","2 cucharadas de perejil de hoja plana, picado","200 g/7 oz de yogur natural bajo en grasa"],
["Para la base: Precaliente el horno a 200°C (180° con ventilador)/400F/gas 6. Engrase y forre con papel encerado una bandeja redonda grande para hornear.","Ponga los ramilletes de coliflor en un procesador de alimentos y pulse hasta que tengan una textura similar al arroz. Lleve a ebullición una olla grande con agua y cocine la coliflor, tapada, de 4 a 5 minutos, hasta que esté tierna.","Escurra bien y reúna la coliflor en un cuadrado grande de muselina o gasa. También puede usar un paño de cocina limpio. Envuelva la coliflor con la muselina formando una bola y retuerza bien para exprimir la mayor cantidad posible de agua.","Pase la coliflor seca a un bol y añada el huevo, el queso crema, la harina y la pimienta negra recién molida. Mezcle bien hasta que se forme una masa rústica.","Pase la masa de coliflor a la bandeja forrada y extiéndala con el rodillo formando un círculo grande. Unte la superficie con aceite de oliva.","Hornee de 25 a 35 minutos, hasta que esté seca al tacto y dorada por todos lados.","Para las coberturas: Mientras tanto, caliente el aceite de oliva en una sartén honda a fuego medio hasta que esté caliente.","Añada la cebolla y cocínela hasta que se ablande, unos 5 minutos. Incorpore el Quorn y cocine a fuego un poco más alto hasta que se dore por todos lados, deshaciéndolo con una cuchara de madera.","Incorpore las especias y el orégano, y cocine 2 minutos más. Retire del fuego y tape para mantener caliente.","Retire la base de coliflor del horno cuando esté lista. Cubra con el Quorn, el pepino en cubitos, los tomates cherry y el perejil picado.","Mezcle el pepino rallado con el yogur en un bol pequeño. Ponga cucharadas sobre la pizza y sirva el resto aparte."],
["Reemplace la carne molida Quorn de esta receta con rodajas de pimiento asado o berenjena para aumentar su consumo de verduras.",*fv(4)[0]]),
"ar":L("بيتزا القرنبيط التركية مع كورن والتزاتزيكي","يُعدّ القرنبيط بديلًا صحيًّا وأقل في الكربوهيدرات لقاعدة البيتزا التقليدية.","4","478 غ",
["للقاعدة: 900 غ/32 أونصة قرنبيط، مقسّم إلى زهيرات","1 بصلة صغيرة، مفرومة ناعمًا","1 بيضة متوسطة، مخفوقة","40 غ/3 أونصات جبن كريمي بنسبة دهون 3%، مثل جبن فيلادلفيا لايتست الكريمي، أو 40 غ/3 أونصات زبادي طبيعي قليل الدسم","2 ملعقة كبيرة دقيق قمح كامل","¼ ملعقة صغيرة فلفل أسود مطحون طازجًا","1 ملعقة صغيرة زيت زيتون","للتغطية: 1 ملعقة صغيرة زيت زيتون","300 غ/12 أونصة كورن (Quorn)، لحم مفروم نباتي","2 ملعقة صغيرة بابريكا مدخنة","1 ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة كزبرة مطحونة","½ ملعقة صغيرة أوريغانو مجفف","1 خيارة كبيرة، نصفها مبشور ونصفها مقطع مكعبات صغيرة","175 غ/5 أونصات طماطم كرزية، مقطعة أرباعًا","2 ملعقة كبيرة بقدونس مسطح الأوراق، مفروم","200 غ/7 أونصات زبادي طبيعي قليل الدسم"],
["للقاعدة: سخّن الفرن مسبقًا إلى 200° مئوية (180° بالمروحة)/400 فهرنهايت/علامة الغاز 6. ادهن صينية خبز دائرية كبيرة وبطّنها بورق الزبدة.","ضع زهيرات القرنبيط في محضّر الطعام وشغّله على نبضات حتى يصبح قوامه شبيهًا بالأرز. اغلِ قدرًا كبيرًا من الماء واسلق القرنبيط مغطى من 4 إلى 5 دقائق حتى يلين.","صفِّه جيدًا واجمع القرنبيط في قطعة مربعة كبيرة من الشاش القطني (موسلين). يمكنك أيضًا استخدام منشفة مطبخ نظيفة. لُفّ الشاش حول القرنبيط على شكل كرة والتفّه جيدًا لعصر أكبر قدر ممكن من الماء الزائد.","ضع القرنبيط الجاف في وعاء وأضف البيض والجبن الكريمي والدقيق والفلفل الأسود المطحون طازجًا. امزج جيدًا حتى تتكون عجينة خشنة.","انقل عجينة القرنبيط إلى الصينية المبطنة وافردها على شكل دائرة كبيرة. ادهن السطح بزيت الزيتون.","اخبزها من 25 إلى 35 دقيقة حتى يجف سطحها عند اللمس وتصبح ذهبية اللون من كل الجهات.","للتغطية: في هذه الأثناء، سخّن زيت الزيتون في مقلاة عميقة على نار متوسطة حتى يسخن.","أضف البصل واطهُه حتى يطرى، حوالي 5 دقائق. أضف الكورن واطهُه على نار أعلى قليلًا حتى يحمرّ من كل الجهات، مع تفتيته بملعقة خشبية.","أضف التوابل والأوريغانو وقلّب، واطهُ دقيقتين إضافيتين. ارفعه عن النار وغطِّه للحفاظ على سخونته.","أخرج قاعدة القرنبيط من الفرن عندما تكون جاهزة. غطِّها بالكورن والخيار المقطع مكعبات والطماطم الكرزية والبقدونس المفروم.","قلّب الخيار المبشور في الزبادي في وعاء خلط صغير. ضع كتلًا بالملعقة فوق البيتزا وقدّم الباقي على الجانب."],
["استبدل لحم الكورن المفروم في هذه الوصفة بشرائح الفلفل المشوي أو الباذنجان لزيادة تناولك للخضار.",*fv(4)[1]])}))
I.append((7054837,{
"es":L("Ensalada de garbanzos y atún","Los trozos abundantes de atún con garbanzos hacen que este plato sea ideal para un almuerzo para llevar.","2","458g",
["ralladura de medio limón","1 pizca de pimienta negra","20ml de aceite de oliva extra virgen","1 cebolla morada pequeña, finamente picada","180g de tomates cherry maduros, cortados en cuartos","8cm de pepino, picado","1 lata de 400g de garbanzos en agua, escurridos (peso escurrido 240g)","1 lata de 200g de atún en agua, escurrido (peso escurrido 150g)","150g de hojas de ensalada/lechuga","2 gajos de limón"],
["Ponga la ralladura de limón en un bol grande con la pimienta y el aceite de oliva.","A continuación, añada la cebolla morada, los tomates y el pepino, mezcle bien y deje reposar un par de minutos para que se integren los sabores.","Añada los garbanzos y el atún, e incorpore con suavidad para que todo quede cubierto con el aderezo.","Por último, mezcle las hojas de ensalada y reparta en dos loncheras, con un gajo de limón para exprimir encima antes de comer."],
["Los ingredientes ácidos, como el jugo de limón, harán que su ensalada se ablande, así que lleve un gajo de limón en su almuerzo para usarlo justo antes de comer.","El salmón o los camarones son una buena alternativa al atún. Para una versión vegana, pruebe con trozos de tofu marinado.",*fv(4)[0]]),
"ar":L("سلطة الحمص والتونة","قطع التونة المشبعة مع الحمص تجعل هذا الطبق مثاليًا لغداء يُؤخذ معك.","2","458 غ",
["قشر مبشور من نصف ليمونة","رشة فلفل أسود","20 مل زيت زيتون بكر ممتاز","1 بصلة حمراء صغيرة، مفرومة ناعمًا","180 غ طماطم كرزية ناضجة، مقطعة أرباعًا","8 سم خيار، مفروم","1 علبة 400 غ حمص في الماء، مصفى (الوزن بعد التصفية 240 غ)","1 علبة 200 غ تونة في الماء، مصفاة (الوزن بعد التصفية 150 غ)","150 غ أوراق سلطة/خس","2 شريحة ليمون"],
["ضع قشر الليمون في وعاء كبير مع الفلفل وزيت الزيتون.","بعد ذلك، أضف البصل الأحمر والطماطم والخيار، وامزج جيدًا واتركها لبضع دقائق لتتشرب النكهات.","أضف الحمص والتونة، وقلّب برفق ليتغطى كل شيء بالتتبيلة.","أخيرًا، أضف أوراق السلطة وقلّب ووزّعها على علبتي غداء، مع شريحة ليمون لعصرها فوقها قبل الأكل."],
["المكونات الحمضية، مثل عصير الليمون، ستجعل سلطتك تذبل، لذا خذ معك شريحة ليمون في غدائك لاستخدامها قبل الأكل مباشرة.","السلمون أو الجمبري بديل جيد للتونة. ولنسخة نباتية، جرّب قطع التوفو المتبلة.",*fv(4)[1]])}))
I.append((7055081,{
"es":L("Ragú de champiñones","Un ragú de champiñones rico que combina de maravilla con verduras en espiral.","2","358g",
["1 cucharadita de aceite de colza","1 puerro, en rodajas finas","250g de champiñones variados","2 dientes de ajo, en rodajas muy finas","1 pizca de hojuelas de chile","1 cucharadita colmada de orégano seco","2 cucharaditas de semillas de calabaza, tostadas","2 cucharaditas de semillas de girasol, tostadas","1 calabacín, en espiral","1 zanahoria grande, en espiral","2 cucharadas de yogur con 0% de grasa","una buena molida de pimienta negra","5g de virutas de queso parmesano","ramitas de albahaca fresca, para decorar"],
["Ponga el aceite en una sartén y cocine suavemente el puerro de 3 a 4 minutos, revolviendo con frecuencia.","Añada los champiñones, el ajo, el chile y el orégano. Continúe cocinando suavemente durante 5 minutos, revolviendo con frecuencia. Mientras tanto, tueste las semillas y reserve.","Sumerja las verduras en espiral (caseras o ya preparadas) en agua hirviendo durante 2 minutos.","Justo antes de servir, incorpore el yogur a los champiñones.","Reparta las verduras en espiral en 2 tazones. Cubra cada uno con la salsa de champiñones y espolvoree con las semillas tostadas, pimienta negra, unas virutas de parmesano y una ramita de albahaca."],
["Otras verduras en espiral quedan muy bien con este plato, como la calabaza butternut o la remolacha.","Para una opción más alta en carbohidratos, sirva con pasta integral en lugar de verduras en espiral.","Para una alternativa vegetariana al parmesano, sustitúyalo por un queso duro de tipo vegetariano.","Puede usar un yogur natural sin azúcar de su elección, pero esto cambiará la información nutricional y la textura del plato.",*fv(4)[0]]),
"ar":L("راغو الفطر","راغو فطر غني يتناسب بشكل رائع مع الخضار المقطعة على شكل حلزوني.","2","358 غ",
["1 ملعقة صغيرة زيت اللفت","1 كراث، مقطع شرائح رفيعة","250 غ فطر مشكل","2 فص ثوم، مقطع شرائح رفيعة جدًا","رشة رقائق الفلفل الحار","1 ملعقة صغيرة مكدسة أوريغانو مجفف","2 ملعقة صغيرة بذور يقطين، محمصة","2 ملعقة صغيرة بذور عباد الشمس، محمصة","1 كوسا، مقطعة على شكل حلزوني","1 جزرة كبيرة، مقطعة على شكل حلزوني","2 ملعقة كبيرة زبادي خالٍ من الدسم 0%","طحنة جيدة من الفلفل الأسود","5 غ رقائق جبن بارميزان","أغصان ريحان طازج، للتزيين"],
["ضع الزيت في مقلاة واطهُ الكراث بهدوء من 3 إلى 4 دقائق مع التقليب بانتظام.","أضف الفطر والثوم والفلفل الحار والأوريغانو. واصل الطهي بهدوء لمدة 5 دقائق مع التقليب بانتظام. في هذه الأثناء، حمّص البذور وضعها جانبًا.","اغمس الخضار الحلزونية (محضّرة في المنزل أو جاهزة) في ماء مغلي لمدة دقيقتين.","قبل التقديم مباشرة، أضف الزبادي إلى الفطر وقلّب.","وزّع الخضار الحلزونية على وعاءين. غطِّ كل واحد بصلصة الفطر، وانثر عليه البذور المحمصة والفلفل الأسود وبضع رقائق من البارميزان وغصن ريحان."],
["تناسب هذا الطبق خضار حلزونية أخرى، مثل القرع الجوزي أو الشمندر.","لخيار أعلى في الكربوهيدرات، قدّمه مع معكرونة الحبوب الكاملة بدلًا من الخضار الحلزونية.","لبديل نباتي للبارميزان، استبدله بجبن صلب من النوع النباتي.","يمكنك استخدام زبادي سادة غير محلى من اختيارك، لكن ذلك سيغيّر المعلومات الغذائية وقوام الطبق.",*fv(4)[1]])}))
save(4,I)
