from h import *
O=[]
O.append(R(6357497,
("Tortilla francesa de salmón ahumado y yogur griego","Esta elegante tortilla combina salmón ahumado sedoso con yogur griego cremoso y eneldo fresco para comenzar el día con un desayuno rico en proteínas y muy satisfactorio. Es una opción inteligente de desayuno para quienes cuidan su nivel de glucosa en la sangre (azúcar en la sangre), gracias a su bajo contenido de carbohidratos y su proteína equilibrada.","4","1 tortilla",
["4 huevos grandes","1/2 taza de claras de huevo","1/4 de taza de leche al 1%","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra","1 cucharada de aceite de oliva","2 onzas de salmón ahumado en frío (bajo en sodio, picado)","1/4 de taza de yogur griego natural sin grasa","1 cucharada de eneldo fresco (picado, más un poco para decorar)","1/2 cebolla morada pequeña (en rodajas finas)"],
["En un tazón, bata los huevos, las claras, la leche, la sal y la pimienta hasta obtener una mezcla homogénea.","Caliente el aceite de oliva en una sartén antiadherente a fuego medio-bajo. Vierta ¼ de la mezcla de huevo en la sartén y gire la sartén para cubrir el fondo. Cocine hasta que los bordes comiencen a cuajar, unos 2 minutos.","Agregue ¼ del salmón ahumado, una cucharada de yogur griego, eneldo fresco y cebolla morada a un lado de la tortilla.","Con cuidado, doble la tortilla sobre el relleno y cocine durante 30 segundos para que se caliente por completo.","Pásela a un plato y repita con los demás ingredientes."],[],[]),
("أومليت السلمون المدخّن والزبادي اليوناني","يجمع هذا الأومليت الأنيق بين السلمون المدخّن الناعم والزبادي اليوناني الكريمي والشبت الطازج ليمنحك بداية يوم غنية بالبروتين ومشبعة. وهو خيار فطور ذكي لمن يراقبون مستوى الغلوكوز في الدم (سكر الدم)، بفضل انخفاض الكربوهيدرات فيه وتوازن البروتين.","4","1 أومليت",
["4 بيضات كبيرة","½ كوب بياض بيض","¼ كوب حليب 1%","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة زيت زيتون","2 أونصة سلمون مدخّن على البارد (قليل الصوديوم، مفروم)","¼ كوب زبادي يوناني سادة خالٍ من الدسم","1 ملعقة كبيرة شبت طازج (مفروم، مع كمية إضافية للتزيين)","½ حبة بصل أحمر صغيرة (مقطّعة شرائح رفيعة)"],
["في وعاء، اخفق البيض وبياض البيض والحليب والملح والفلفل حتى يصبح الخليط ناعمًا.","سخّن زيت الزيتون في مقلاة غير لاصقة على نار متوسطة إلى منخفضة. اسكب ¼ خليط البيض في المقلاة مع تحريك المقلاة ليغطي القاع. اطهه حتى تبدأ الأطراف في التماسك، حوالي دقيقتين.","ضع ¼ كمية السلمون المدخّن وملعقة من الزبادي اليوناني والشبت الطازج والبصل الأحمر على أحد جانبي الأومليت.","اطوِ الأومليت برفق فوق الحشوة واتركه على النار 30 ثانية ليسخن من الداخل.","انقله إلى طبق وكرّر العملية مع بقية المكونات."],[],[])))
O.append(R(6358049,None,
("برغر الديك الرومي الآسيوي الاقتصادي","هل تبحث عن طريقة لإضفاء نكهة مميزة على البرغر؟ هذه الوصفة مناسبة لك! يمكنك العثور على الصلصات المستخدمة فيها مثل صلصة المحار وصلصة الفلفل والثوم التايلاندية والسريراتشا في قسم الأطعمة العالمية في معظم محلات البقالة.","6","1 برغر",
["1 ملعقة كبيرة صلصة المحار (إذا لم تجدها، استبدلها بـ 1 ملعقة كبيرة صلصة صويا مخفضة الصوديوم)","20 أونصة لحم ديك رومي مفروم قليل الدهن (خالٍ من الدهون بنسبة 93%)","2 عود بصل أخضر (مفروم ناعمًا، الجزء الأبيض والأخضر)","1 فص ثوم (مفروم)","1 ملعقة صغيرة معجون الفلفل والثوم على الطريقة التايلاندية","1 ملعقة صغيرة زيت سمسم","1 ملعقة كبيرة زنجبيل طازج (مبشور)","1 ملعقة كبيرة عصير ليمون أخضر","½ ملعقة صغيرة ملح (اختياري)","½ ملعقة صغيرة فلفل أسود","⅓ كوب زبادي سادة (خالٍ من الدسم)","1 ملعقة صغيرة صلصة سريراتشا","12 ورقة خس بيب أو بوسطن","18 شريحة خيار"],
["جهّز شواية داخلية أو خارجية.","في وعاء كبير، اخلط لحم الديك الرومي المفروم والبصل الأخضر والثوم وصلصة المحار ومعجون الفلفل والثوم وزيت السمسم والزنجبيل المبشور وعصير الليمون الأخضر والملح (اختياري) والفلفل. شكّل الخليط 6 أقراص وضعها في الثلاجة حتى موعد الشيّ، لمدة 15 دقيقة على الأقل.","اشوِ البرغر لمدة 5-7 دقائق على كل جانب أو حتى تصل درجة الحرارة الداخلية للبرغر إلى 165 درجة فهرنهايت (75° مئوية).","لتجميع البرغر، اخلط الزبادي والسريراتشا في وعاء صغير. ضع كل قرص برغر بين ورقتي خس مع أقل قليلًا من 1 ملعقة كبيرة من خليط الزبادي و3 شرائح خيار."],[],[])))
O.append(R(6359083,
("Avena con jengibre","Comience su día con una satisfactoria avena con jengibre, un delicioso desayuno apto para personas con diabetes y muy saciante. La avena cremosa, infusionada suavemente con el calor del jengibre, aporta un toque reconfortante y ligeramente picante a su rutina matutina. Está llena de semillas de chía para aumentar la fibra y los ácidos grasos omega-3 saludables para el corazón. Cúbrala con una mezcla vibrante de frutos rojos frescos que aportan un estallido de dulzura natural y antioxidantes. Espolvoree nueces picadas para darle un toque crujiente y una dosis adicional de beneficios para el corazón.","4","1/2 taza de avena + ¼ de taza de frutos rojos",
["1 taza de avena en hojuelas tradicional","2 tazas de leche descremada","2 cucharaditas de sustituto de azúcar morena","1 cucharada de jengibre fresco (rallado)","1 cucharada de semillas de chía","1/4 de cucharadita de canela molida","1/4 de cucharadita de extracto de vainilla","1/2 taza de frambuesas","1/2 taza de arándanos azules","2 cucharadas de nueces (picadas)"],
["En una cacerola mediana, caliente la leche a fuego lento hasta que hierva suavemente.","Agregue la avena, el sustituto de azúcar morena, el jengibre rallado, las semillas de chía, la canela y la vainilla.","Cocine la mezcla a fuego medio, revolviendo de vez en cuando, hasta que la avena esté cremosa y el líquido se haya absorbido (unos 5-7 minutos).","Sirva la avena en tazones y cúbrala con los frutos rojos frescos y las nueces."],[],[]),
("شوفان بالزنجبيل","ابدأ يومك بطبق شوفان بالزنجبيل مشبع، وهو فطور شهي مناسب لمرضى السكري. يمنح الشوفان الكريمي المنقوع برفق بدفء الزنجبيل لمسة مريحة وحارة قليلًا لروتين صباحك. وهو غني ببذور الشيا التي تزيد الألياف وأحماض أوميغا 3 الدهنية المفيدة للقلب. زيّنه بمزيج زاهٍ من التوت الطازج الذي يمنحك حلاوة طبيعية ومضادات أكسدة. ورشّ عليه الجوز المفروم للحصول على قرمشة مشبعة وجرعة إضافية من الفوائد الصحية للقلب.","4","½ كوب شوفان + ¼ كوب توت",
["1 كوب شوفان مسطّح تقليدي","2 كوب حليب خالٍ من الدسم","2 ملعقة صغيرة بديل السكر البني","1 ملعقة كبيرة زنجبيل طازج (مبشور)","1 ملعقة كبيرة بذور الشيا","¼ ملعقة صغيرة قرفة مطحونة","¼ ملعقة صغيرة خلاصة الفانيليا","½ كوب توت العليق","½ كوب توت أزرق","2 ملعقة كبيرة جوز (مفروم)"],
["في قدر متوسطة، سخّن الحليب حتى يغلي غليانًا هادئًا.","أضف الشوفان وبديل السكر البني والزنجبيل المبشور وبذور الشيا والقرفة والفانيليا وقلّب.","اطهِ الخليط على نار متوسطة مع التحريك من حين لآخر حتى يصبح الشوفان كريميًا ويُمتصّ السائل (حوالي 5–7 دقائق).","قدّم الشوفان في أوعية مزيّنًا بالتوت الطازج والجوز."],[],[])))
O.append(R(6359828,
("Tostada de bistec a la parrilla con pimienta","Estas tostadas se cubren con filete magro asado en lonjas finas, aguacate cremoso, tomates cherry y una salsa verde fresca para una comida entre semana fresca y sabrosa. Ase el bistec y las tortillas en una plancha acanalada o en una parrilla al aire libre, y agregue unas rodajas de chile jalapeño para darle más picante.","4","2 tostadas",
["12 onzas de bistec magro (asado de ojo de round, punta de solomillo, round superior o round inferior)","1/4 de cucharadita de sal (kosher)","1/2 cucharadita de pimienta negra","2 rociadas, 0.5 g de aceite en aerosol antiadherente","8 tortillas de maíz pequeñas (de 6 pulgadas)","1/2 taza de salsa verde (salsa de tomatillo)","1 aguacate grande (en rodajas)","1 taza de tomates cherry (en cuartos)","1/4 de taza de cilantro fresco (picado)"],
["Saque el bistec del refrigerador 30 minutos antes de asarlo. Frote el bistec con la sal y la pimienta.","Precaliente una plancha acanalada, una sartén o una parrilla al aire libre a fuego medio-alto.","Cuando la plancha esté caliente, úntela con aceite. Agregue el bistec y cocínelo de 6 a 8 minutos por lado, hasta que alcance el término deseado. Retírelo del fuego, colóquelo en un plato y déjelo reposar 5 minutos antes de cortarlo en tiras finas.","Limpie la plancha con una toalla de papel y rocíela ligeramente con aceite en aerosol. Vuelva a ponerla a fuego medio.","Coloque dos tortillas en la plancha y áselas de 2 a 3 minutos, solo hasta que se tuesten. Voltéelas y tuéstelas de 2 a 3 minutos más. Retírelas y ase las tortillas restantes.","Cubra las tortillas con la salsa verde, el bistec en tiras, las rodajas de aguacate, los tomates en cubos y el cilantro."],[],[]),
("توستادا شريحة اللحم المشوية بالفلفل","تُغطّى هذه التوستادا بشرائح رفيعة من اللحم الخالي من الدهن المشوي والأفوكادو الكريمي وطماطم الكرز وصلصة سالسا فيردي المنعشة لوجبة طازجة ولذيذة في أيام الأسبوع. اشوِ اللحم والتورتيلا على مقلاة شواء أو شواية خارجية، وأضف بضع شرائح من فلفل الهالابينو لمزيد من الحرارة.","4","2 توستادا",
["12 أونصة شريحة لحم قليلة الدهن (لحم عجل مشوي من الفخذ، أو طرف السيرلوين، أو الفخذ العلوي، أو الفخذ السفلي)","¼ ملعقة صغيرة ملح (خشن)","½ ملعقة صغيرة فلفل أسود","2 بخّة، 0.5 جم بخاخ طهي غير لاصق","8 تورتيلا ذرة صغيرة (6 بوصات)","½ كوب سالسا فيردي (صلصة الطماطم الخضراء توماتيو)","1 حبة أفوكادو كبيرة (مقطّعة شرائح)","1 كوب طماطم كرز (مقطّعة أرباعًا)","¼ كوب كزبرة خضراء طازجة (مفرومة)"],
["أخرج اللحم من الثلاجة قبل الشيّ بـ 30 دقيقة. افرك اللحم بالملح والفلفل.","سخّن مقلاة شواء داخلية أو مقلاة عادية أو شواية خارجية على نار متوسطة إلى عالية.","عندما تسخن مقلاة الشواء، ادهنها بالزيت. أضف اللحم واطهه من 6 إلى 8 دقائق لكل جانب حتى يصل إلى درجة النضج المطلوبة. ارفعه عن النار وضعه جانبًا على طبق؛ واتركه يرتاح 5 دقائق قبل تقطيعه إلى شرائح رفيعة.","امسح مقلاة الشواء بمنديل ورقي ورشّها قليلًا ببخاخ الطهي. أعدها إلى نار متوسطة.","ضع تورتيلتين على مقلاة الشواء واشوِهما من 2 إلى 3 دقائق، حتى تحمّصا فقط. اقلبهما وحمّصهما من 2 إلى 3 دقائق أخرى. أخرجهما واشوِ باقي التورتيلا.","ضع فوق التورتيلا سالسا فيردي وشرائح اللحم وشرائح الأفوكادو والطماطم المقطّعة مكعبات والكزبرة الخضراء."],[],[])))
O.append(R(6360044,None,
("غموس الفاصولياء الكاريبي","حضّر هذا الغموس واحفظه في الثلاجة لتتناوله كوجبة خفيفة مع بعض الخضار الطازجة طوال الأسبوع.","8","3½ ملعقة كبيرة غموس + 4 أعواد كرفس + 4 أعواد جزر",
["1 علبة (15.5 أونصة) فاصولياء سوداء عضوية (مصفاة ومشطوفة)","½ حبة أفوكادو هاس متوسطة (مقشّرة ومقطّعة شرائح)","3 ملاعق كبيرة عصير ليمون","2 ملعقة كبيرة كزبرة خضراء (مفرومة تقريبًا)","¼ ملعقة صغيرة فلفل أحمر كايين مطحون","¼ ملعقة صغيرة كمون مطحون","¼ ملعقة صغيرة ملح خشن","3 عود بصل أخضر (مقطّع شرائح رفيعة)","4 أعواد كرفس (مقسومة إلى نصفين)","4 جزرات متوسطة (مقسومة إلى نصفين ومقطّعة أعوادًا أصغر)"],
["اهرس جميع المكونات ما عدا البصل الأخضر في الخلاط حتى تصبح ناعمة. زيّنها بالبصل الأخضر.","قدّمها مع أعواد الكرفس والجزر."],[],[])))
O.append(R(6360759,
("Ensalada de salmón y granos de trigo con pesto","Los granos de trigo son el grano de la planta de trigo sin la cáscara exterior. Tienen un sabor a nuez y una textura masticable, y están llenos de fibra, proteína y hierro. Puede preparar una tanda con anticipación y guardarla en el refrigerador hasta por una semana. Si no encuentra granos de trigo, puede sustituirlos en esta receta por farro, espelta o arroz integral.","2","2 1/4 tazas de mezcla de ensalada y verduras + 3 oz de salmón",
["1/2 taza de granos de trigo (o farro)","2 filetes de salmón de 3 onzas cada uno","5 1/2 cucharaditas de pesto preparado","2 tazas de arúgula","2 tazas de espinaca baby (picada)","1/2 taza de ejotes cocidos","1/2 taza de tomates cherry (cortados por la mitad)","1 cucharada de piñones (tostados)","1/4 de taza de microvegetales"],
["Precaliente el horno a 350 grados F. Forre una bandeja para hornear con papel de aluminio y rocíe ligeramente con aceite en aerosol.","Cocine los granos de trigo según las instrucciones del paquete.","Unte cada filete de salmón con media cucharadita de pesto. Colóquelos en la bandeja preparada y métalos al horno. Cocine hasta que el salmón alcance 145 grados F, unos 15 a 20 minutos según el grosor del filete.","Cuando los granos de trigo estén cocidos, escúrralos y mézclelos con 4 1/2 cucharaditas de pesto.","Divida la espinaca y la arúgula entre 2 platos grandes o tazones. Agregue los granos de trigo y mezcle para cubrir las hojas con el pesto.","Coloque 1 filete de salmón sobre cada plato de hojas verdes. Agregue la mitad de los ejotes y de los tomates y espolvoree cada tazón con piñones y microvegetales."],[],[]),
("سلطة السلمون وحبوب القمح بالبيستو","حبوب القمح (ويت بيري) هي نواة نبات القمح بعد إزالة القشرة الخارجية. لها نكهة تشبه المكسرات وقوام مطاطي، وهي غنية بالألياف والبروتين والحديد. يمكنك تحضير كمية منها مسبقًا وحفظها في الثلاجة حتى أسبوع. وإذا لم تجد حبوب القمح، يمكن استبدالها في هذه الوصفة بالفارو أو القمح المقشور (سبلت) أو الأرز البني.","2","2¼ كوب من خليط السلطة والخضار + 3 أونصات سلمون",
["½ كوب حبوب القمح (أو الفارو)","2 شريحة سلمون، 3 أونصات لكل شريحة","5½ ملعقة صغيرة بيستو جاهز","2 كوب جرجير","2 كوب سبانخ صغيرة (مفرومة)","½ كوب فاصولياء خضراء مطبوخة","½ كوب طماطم كرز (مقسومة إلى نصفين)","1 ملعقة كبيرة صنوبر (محمّص)","¼ كوب خضروات صغيرة (ميكروجرينز)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). بطّن صينية خبز بورق الألمنيوم ورشّها قليلًا ببخاخ الطهي.","اطهِ حبوب القمح بحسب إرشادات العبوة.","ادهن كل شريحة سلمون بنصف ملعقة صغيرة من البيستو. ضعها على الصينية المجهزة وأدخلها الفرن. اطهها حتى تصل حرارة السلمون إلى 145 درجة فهرنهايت (65° مئوية)، حوالي 15–20 دقيقة بحسب سماكة الشريحة.","عندما تنضج حبوب القمح، صفّها وقلّبها مع 4½ ملعقة صغيرة من البيستو.","وزّع السبانخ والجرجير على طبقين أو وعاءين كبيرين. أضف حبوب القمح وقلّب لتغطي البيستو الأوراق الخضراء.","ضع شريحة سلمون واحدة فوق كل طبق من الخضار الورقية. أضف نصف كمية الفاصولياء الخضراء والطماطم ورشّ كل وعاء بالصنوبر والخضروات الصغيرة."],[],[])))
O.append(R(6360930,
("Tofu con parmesano y fideos de calabaza butternut","Pruebe nuestro tofu con parmesano y fideos de calabaza butternut, un platillo apto para personas con diabetes que combina el crujiente sabroso del tofu cubierto con parmesano con lo saludable de los fideos de calabaza butternut. Prepárelo con Ejotes asados con vinagreta de champán para una comida hermosa y colorida. Este platillo se puede hacer fácilmente vegano sustituyendo el queso y la mayonesa por alternativas sin lácteos y sin huevo.","4","7 oz de tofu y ~2 tazas de fideos",
["28 onzas de tofu extrafirme (escurrido y prensado por al menos 30 minutos)","2 cucharaditas de aceite de oliva (divididas)","1 calabaza butternut mediana","1/2 cucharadita de condimento italiano (dividida)","1 onza de queso parmesano reducido en grasa (rallado)","1/4 de taza de mayonesa light","1/4 de cucharadita de cebolla en polvo","1/4 de cucharadita de ajo en polvo","1 taza de albahaca fresca (hojas en juliana)"],
["Precaliente el horno a 350 grados F. Forre una bandeja para hornear con papel de aluminio.","Corte cada bloque de tofu por la mitad a lo largo. Colóquelos en la bandeja y rocíelos con 1 cucharadita de aceite. Hornee 15 minutos, voltee y hornee otros 15 minutos.","Mientras tanto, pele la cáscara dura de la calabaza. Use un pelador de juliana para cortar fideos de la calabaza.","Precaliente una sartén grande a fuego medio. Agregue 1 cucharadita de aceite, la calabaza y ¼ de cucharadita de condimento italiano. Cocine, revolviendo de vez en cuando, hasta que los fideos de calabaza estén tiernos, de 7 a 8 minutos. Retire del fuego, tape y reserve.","Combine el parmesano, la mayonesa, 1/4 de cucharadita de condimento italiano, la cebolla en polvo y el ajo en polvo en un tazón pequeño.","Después de que el tofu se haya horneado durante 30 minutos, sáquelo del horno. Ponga el horno en modo de asar (broil) a temperatura alta y mueva una rejilla del horno al estante superior, debajo del asador.","Extienda la mezcla de queso sobre la parte superior del tofu. Regréselo al horno y áselo hasta que la cubierta burbujee y empiece a dorarse, de 1 a 2 minutos.","Sirva sobre una cama de fideos de calabaza con un puñado de albahaca fresca."],[],[]),
("توفو بالبارميزان مع نودلز القرع الجوزي","جرّب التوفو بالبارميزان مع نودلز القرع الجوزي، وهو طبق مناسب لمرضى السكري يجمع بين قرمشة التوفو المغطى بالبارميزان الشهية وفوائد نودلز القرع الجوزي. حضّره مع الفاصولياء الخضراء المحمّصة بصلصة الشمبانيا لوجبة جميلة الألوان. ويمكن جعل هذا الطبق نباتيًا بسهولة باستبدال الجبن والمايونيز ببدائل خالية من الألبان والبيض.","4","7 أونصات توفو وحوالي 2 كوب نودلز",
["28 أونصة توفو صلب جدًا (مصفى ومضغوط لمدة 30 دقيقة على الأقل)","2 ملعقة صغيرة زيت زيتون (مقسّمة)","1 حبة قرع جوزي متوسطة","½ ملعقة صغيرة توابل إيطالية (مقسّمة)","1 أونصة جبن بارميزان قليل الدسم (مبشور)","¼ كوب مايونيز خفيف","¼ ملعقة صغيرة مسحوق البصل","¼ ملعقة صغيرة مسحوق الثوم","1 كوب ريحان طازج (أوراق مقطّعة شرائح طويلة رفيعة)"],
["سخّن الفرن مسبقًا إلى 350 درجة فهرنهايت (175° مئوية). بطّن صينية خبز بورق الألمنيوم.","اقطع كل قطعة توفو إلى نصفين على طول الضلع الطويل. ضعها على الصينية ورشّ عليها 1 ملعقة صغيرة من الزيت. اخبزها 15 دقيقة، ثم اقلبها واخبزها 15 دقيقة أخرى.","في الأثناء، قشّر القشرة القاسية عن القرع. استخدم مقشرة جوليان لقطع نودلز من القرع.","سخّن مقلاة كبيرة على نار متوسطة. أضف 1 ملعقة صغيرة من الزيت والقرع و¼ ملعقة صغيرة من التوابل الإيطالية. اطهه مع التحريك من حين لآخر حتى تلين نودلز القرع، من 7 إلى 8 دقائق. ارفعه عن النار وغطِّه وضعه جانبًا.","اخلط البارميزان والمايونيز و¼ ملعقة صغيرة من التوابل الإيطالية ومسحوق البصل ومسحوق الثوم في وعاء صغير.","بعد أن يُخبز التوفو لمدة 30 دقيقة، أخرجه من الفرن. اضبط الفرن على الشواء (برويل) على درجة عالية وانقل رف الفرن إلى الرف العلوي تحت عنصر الشواء.","وزّع خليط الجبن على وجه التوفو. أعده إلى الفرن واشوِه حتى تتبقّع الطبقة العلوية بالفقاعات وتبدأ في الاحمرار، من 1 إلى 2 دقيقة.","قدّمه على فراش من نودلز القرع مع حفنة من الريحان الطازج."],[],[])))
O.append(R(6362411,None,
("تشيلي الديك الرومي والخضار","يُعدّ هذا التشيلي وجبة رائعة في قدر واحدة. توفر الفاصولياء كربوهيدرات صحية، ويوفر الديك الرومي بروتينًا قليل الدهن، ويضيف الجزر والكوسا والبصل والطماطم الخضار. سريع وسهل وصحي ومثالي في أيام الشتاء الباردة!","8","1 كوب",
["1 حبة بصل صغيرة (مقطّعة مكعبات)","2 جزرة متوسطة (مقطّعة مكعبات)","1 حبة كوسا متوسطة (مقطّعة مكعبات)","1 فص ثوم (مفروم)","1 بخّة، 0.25 جم بخاخ طهي غير لاصق","16 أونصة لحم ديك رومي مفروم قليل الدهن","1 علبة (14.5 أونصة) طماطم معلّبة مقطّعة مكعبات","1 علبة (28 أونصة) طماطم معلّبة مهروسة","1 علبة (15.8 أونصة) فاصولياء بيضاء صغيرة أو فاصولياء جريت نورثرن معلّبة (مشطوفة ومصفاة)","1 علبة (15 أونصة) فاصولياء حمراء (مشطوفة ومصفاة)","½ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة مسحوق التشيلي","1 ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة مسحوق الثوم"],
["رشّ قدر شوربة كبيرة ببخاخ الطهي. أضف البصل والجزر والكوسا وقلّبها على نار متوسطة إلى عالية لمدة 3-4 دقائق أو حتى يصبح البصل شفافًا. أضف الثوم وقلّب 30 ثانية أخرى.","أضف لحم الديك الرومي المفروم واطهه حتى يحمرّ. أضف باقي المكونات؛ وامزج جيدًا وأحضر التشيلي إلى الغليان. خفّف النار واتركه على نار هادئة لمدة 15-20 دقيقة."],[],[])))
O.append(R(6363916,
("Naranjas glaseadas con especias","Las naranjas glaseadas con miel y especias son un postre sencillo y delicioso, apto para personas con diabetes, que combina la dulzura natural de las naranjas con un glaseado cálido y aromático de miel y especias. Cubra con hojas de menta fresca picada para darle un toque extra de color y sabor.","4","1/2 naranja",
["2 naranjas grandes (peladas y cortadas en rodajas)","1 cucharada de miel","1/2 cucharadita de canela molida","1/8 de cucharadita de nuez moscada molida","1/8 de cucharadita de jengibre molido","1/8 de cucharadita de sal","1 ramita de menta fresca (para decorar, opcional)"],
["Pele las naranjas y córtelas en rodajas. Quite las semillas.","En una cacerola pequeña a fuego bajo, combine la miel, 1 cucharada de agua, la canela molida, la nuez moscada molida, el jengibre molido y una pizca de sal marina. Revuelva hasta que la mezcla esté bien integrada y caliente.","Acomode las rodajas de naranja en una fuente para servir o en platos individuales.","Rocíe el glaseado de miel con especias sobre las rodajas de naranja, asegurándose de que cada rodaja quede bien cubierta de sabor.","Sirva las naranjas de inmediato."],[],[]),
("برتقال مُغلَّف بالتوابل","البرتقال المُغلَّف بعسل التوابل حلوى بسيطة وشهية مناسبة لمرضى السكري، تجمع بين الحلاوة الطبيعية للبرتقال وطبقة دافئة عطرية من العسل والتوابل. زيّنه بأوراق النعناع الطازج المفروم لمسة إضافية من اللون والنكهة.","4","½ حبة برتقال",
["2 حبة برتقال كبيرة (مقشّرة ومقطّعة حلقات)","1 ملعقة كبيرة عسل","½ ملعقة صغيرة قرفة مطحونة","⅛ ملعقة صغيرة جوزة الطيب المطحونة","⅛ ملعقة صغيرة زنجبيل مطحون","⅛ ملعقة صغيرة ملح","1 غصن نعناع طازج (للتزيين، اختياري)"],
["قشّر البرتقال وقطّعه حلقات. أزل أي بذور.","في قدر صغيرة على نار هادئة، اخلط العسل و1 ملعقة كبيرة من الماء والقرفة المطحونة وجوزة الطيب المطحونة والزنجبيل المطحون ورشة من ملح البحر. قلّب حتى يتجانس الخليط ويسخن.","رتّب شرائح البرتقال على طبق تقديم أو في أطباق فردية.","اسكب مزيج العسل والتوابل على شرائح البرتقال، مع التأكد من تغطية كل شريحة بالنكهة.","قدّم البرتقال فورًا."],[],[])))
O.append(R(6364308,None,
("خضار ورقية مطبوخة لذيذة","استخدم الخردل أو اللفت أو السلق أو الكيل أو الكولارد لهذه الوصفة!","12","½ كوب",
["2 رطل خضار ورقية طرية (طازجة)","2 ملعقة صغيرة زيت ذرة","½ كوب بصل (مفروم)","1¼ كوب ماء","1 مكعب مرق دجاج كامل (قليل الصوديوم)","¼ ملعقة صغيرة ملح","1 ملعقة صغيرة سكر","⅛ ملعقة صغيرة صلصة تاباسكو"],
["انزع السيقان وأي أوراق مصفرّة من الخضار، ثم اشطفها جيدًا وصفّها.","سخّن الزيت في قدر كبيرة على نار متوسطة. أضف البصل وقلّبه حتى يلين.","أضف الخضار والماء ومكعب المرق إلى القدر. غطِّها وأحضرها إلى الغليان. خفّف النار إلى منخفضة واتركها على نار هادئة لمدة 30 دقيقة أو حتى تلين الخضار، مع التحريك من حين لآخر.","أضف الملح والسكر وصلصة التاباسكو. قلّب جيدًا واتركها على نار هادئة 5 دقائق إضافية. يمكن تقديمها مع خل التفاح لإبراز أفضل نكهة للخضار."],[],[])))
O.append(R(6364389,None,
("سلطة السبانخ بالدجاج والأفوكادو","تحتاج السلطة الجيدة إلى خضار وبروتين ونكهة وقوامات مختلفة. يوفر الدجاج في هذه الوصفة البروتين. وعند دمجه مع الأفوكادو وبذور عباد الشمس تحصل على النكهة والقوام والقرمشة المثالية. هذه السلطة السريعة والسهلة مثالية لغداء خفيف ومشبع. وهي رائعة أيضًا لتحضير الوجبات مسبقًا، فقط ضع كل حصة في وعاء منفصل، وانتظر لإضافة الصلصة حتى قبل التقديم مباشرة.","4","2 كوب",
["12 أونصة سبانخ صغيرة (بيبي)","1 حبة أفوكادو صغيرة (منزوعة النواة ومقطّعة شرائح رفيعة)","2 حبة طماطم روما (برقوقية) متوسطة (مقطّعة مكعبات)","1 كوب صدر دجاج مطبوخ (مقطّع مكعبات)","4 ملاعق كبيرة بذور عباد الشمس","6 ملاعق كبيرة صلصة رانش خفيفة"],
["في وعاء سلطة كبير، اخلط السبانخ والأفوكادو والطماطم والدجاج وبذور عباد الشمس. أضف الصلصة وقلّب لتتغطى بالتساوي. أو، إذا كنت تحضّرها مسبقًا، وزّع السلطة على أربعة أوعية. أضف 1½ ملعقة كبيرة من الصلصة قبل الأكل مباشرة."],[],[])))
O.append(R(6366362,
("Bowls japoneses de arroz con pollo y espinacas","Los bowls de cereales, proteína y verduras están de moda ahora, y en cuanto pruebe este entenderá por qué. Es un bowl nutritivo que combina el confort de la sopa de pollo con el color y el sabor de las verduras frescas. También puede personalizarlo según sus preferencias o lo que tenga a mano. Si no tiene arroz integral, puede sustituirlo por quinoa cocida, farro o cuscús integral. También puede cubrir su bowl con pepinos picados, zanahorias ralladas o pimientos picados. Y, si le gusta la comida picante, aumente las hojuelas de pimiento rojo.","4","1 ½ tazas de pollo y verduras + 1/2 taza de arroz integral",
["1 libra de pechugas de pollo (mitades sin hueso ni piel, sin ninguna grasa visible)","1 tallo de apio (cortado en cuartos)","1/2 cebolla mediana (cortada en gajos de 1/2 pulgada)","2 dientes de ajo (picados)","1 cucharadita de salsa de soya baja en sodio","1 cucharadita de vinagre de arroz","1/8 de cucharadita de hojuelas de chile rojo triturado","3 tazas de agua","2 tazas de caldo de pollo sin sal agregada (sin grasa)","2/3 de taza de arroz integral","4 tazas de espinaca (hojas frescas ligeramente apretadas, sin tallos y picadas en trozos grandes)","4 rábanos medianos (en rodajas finas)","2 tallos de cebolla de cambray (en rodajas finas)","2 cucharaditas de semillas de ajonjolí (tostadas)"],
["Coloque el pollo en una olla de cocción lenta mediana. Agregue los trozos de apio, los gajos de cebolla, el ajo, la salsa de soya, el vinagre y las hojuelas de chile. Agregue el agua y el caldo de pollo. Tape y cocine a temperatura baja de 3 a 5 horas, o hasta que el pollo esté completamente cocido y alcance una temperatura de 165 F.","Aproximadamente una hora antes de servir, prepare el arroz según las instrucciones del paquete, omitiendo la sal y la margarina.","Con una espumadera, saque el pollo de la olla de cocción lenta y colóquelo en una tabla de cortar. Cuele el caldo a través de un colador de malla fina en un tazón hondo. Vierta el caldo caliente de nuevo en la olla de cocción lenta. Ponga la olla en temperatura alta.","Corte el pollo en trozos del tamaño de un bocado y vuelva a mezclarlo con el caldo caliente en la olla de cocción lenta. Agregue la espinaca. Tape y cocine a temperatura alta durante 15 minutos.","Sirva 1/2 taza de arroz integral cocido en cada tazón. Vierta con un cucharón 1 1/2 tazas de la mezcla de pollo, espinaca y caldo sobre el arroz. Cubra con los rábanos y las cebollas de cambray en rodajas. Espolvoree con las semillas de ajonjolí.","Variación en olla a presión: Coloque el pollo, el apio, la cebolla, el ajo, la salsa de soya, el vinagre y las hojuelas de chile en la olla a presión. Agregue el agua y el caldo de pollo. Asegure la tapa. Cocine a alta presión durante 6 minutos. Libere la presión rápidamente. Retire el pollo y colóquelo en una tabla de cortar. Cuele el caldo y devuélvalo a la olla a presión. Corte el pollo en trozos del tamaño de un bocado y mézclelo con el caldo. Ponga la olla a presión en la función de saltear. Agregue la espinaca y cocine, revolviendo con frecuencia, de 3 a 5 minutos o hasta que la espinaca esté cocida. Continúe como indica la receta, sirviendo el pollo y la espinaca con un cucharón sobre el arroz integral cocido y cubra con los rábanos, las cebollas de cambray y las semillas de ajonjolí."],[],[]),
("أوعية الأرز الياباني بالدجاج والسبانخ","أصبحت أوعية الحبوب والبروتين والخضار شائعة الآن، وبمجرد أن تتذوق هذه الوصفة ستفهم السبب. إنها وجبة مغذية تجمع بين راحة شوربة الدجاج وألوان ونكهة الخضار الطازجة. يمكنك أيضًا تخصيص الوعاء بما يناسب ذوقك أو ما يتوفر لديك. وإذا نفد الأرز البني لديك يمكنك استبداله بالكينوا المطبوخة أو الفارو أو الكسكس من الحبوب الكاملة. ويمكنك أيضًا تزيين الوعاء بالخيار المفروم أو الجزر المبشور أو الفلفل الرومي المفروم. وإذا كنت تحب الطعام الحار، فزد كمية رقائق الفلفل الأحمر.","4","1½ كوب من الدجاج والخضار + ½ كوب أرز بني",
["1 رطل صدور دجاج (أنصاف بدون عظم وبدون جلد، مع التخلص من كل الدهون الظاهرة)","1 عود كرفس (مقطّع أرباعًا)","½ حبة بصل متوسطة (مقطّعة إلى أسافين بسمك ½ بوصة)","2 فص ثوم (مفروم)","1 ملعقة صغيرة صلصة صويا قليلة الصوديوم","1 ملعقة صغيرة خل الأرز","⅛ ملعقة صغيرة رقائق الفلفل الأحمر المجروش","3 أكواب ماء","2 كوب مرق دجاج بدون ملح مضاف (خالٍ من الدهون)","⅔ كوب أرز بني","4 أكواب سبانخ (أوراق طازجة غير مكبوسة، منزوعة السيقان ومفرومة فرمًا خشنًا)","4 حبات فجل متوسطة (مقطّعة شرائح رفيعة)","2 عود بصل أخضر (مقطّع شرائح رفيعة)","2 ملعقة صغيرة بذور السمسم (محمّصة)"],
["ضع الدجاج في قدر طهي بطيء متوسطة. أضف قطع الكرفس وأسافين البصل والثوم وصلصة الصويا والخل ورقائق الفلفل الحار. أضف الماء ومرق الدجاج. غطِّها واطهِ على حرارة منخفضة من 3 إلى 5 ساعات، أو حتى ينضج الدجاج تمامًا وتصل حرارته إلى 165° فهرنهايت (75° مئوية).","قبل التقديم بساعة تقريبًا، حضّر الأرز بحسب إرشادات العبوة مع الاستغناء عن الملح والسمن النباتي (المارجرين).","باستخدام ملعقة مخرّمة، ارفع الدجاج من قدر الطهي البطيء وضعه على لوح التقطيع. صفِّ المرق بمصفاة ناعمة في وعاء عميق. اسكب المرق الساخن مرة أخرى في قدر الطهي البطيء. اضبط القدر على الحرارة العالية.","قطّع الدجاج إلى قطع بحجم اللقمة وأعده إلى المرق الساخن في القدر. أضف السبانخ وقلّب. غطِّ القدر واطهِ على حرارة عالية لمدة 15 دقيقة.","ضع ½ كوب من الأرز البني المطبوخ في كل وعاء تقديم. اسكب بالمغرفة 1½ كوب من خليط الدجاج والسبانخ والمرق فوق الأرز. زيّنه بشرائح الفجل والبصل الأخضر. رشّ بذور السمسم.","طريقة بديلة بقدر الضغط: ضع الدجاج والكرفس والبصل والثوم وصلصة الصويا والخل ورقائق الفلفل الحار في قدر الضغط. أضف الماء ومرق الدجاج. أحكم إغلاق الغطاء. اطهِ على ضغط عالٍ لمدة 6 دقائق. أطلق الضغط بسرعة. أخرج الدجاج وضعه على لوح التقطيع. صفِّ المرق وأعده إلى قدر الضغط. قطّع الدجاج إلى قطع بحجم اللقمة وقلّبه في المرق. اضبط قدر الضغط على وضع التحمير. أضف السبانخ واطهِ مع التحريك المتكرر لمدة 3 إلى 5 دقائق أو حتى تنضج السبانخ. أكمل كما في الوصفة، بسكب الدجاج والسبانخ فوق الأرز البني المطبوخ وتزيينه بالفجل والبصل الأخضر وبذور السمسم."],[],[])))
dump(O,"../out_c10_part2.json")
