from h import *
R=[]
R.append((6109950,{
"es":T("Bowl de fajitas de pollo y verduras","Este delicioso bowl de fajitas de pollo y verduras es una forma baja en carbohidratos de disfrutar platillos de inspiración mexicana. Agregue un poco de cilantro fresco y rodajas de limón si desea darle un toque extra a esta sabrosa receta para el almuerzo.","4","aproximadamente 1/2 taza de la mezcla de pollo + 1 taza de arroz de coliflor + 1/4 de taza de tomates cherry + 1/4 de aguacate",
["1 cucharadita de comino molido","1/2 cucharadita de chile en polvo","1/4 de cucharadita de pimentón ahumado","1/2 cucharadita de orégano seco","1/2 cucharadita de perejil seco","1/4 de cucharadita de pimienta de cayena","1/2 cucharadita de ajo en polvo","1/2 cucharadita de cebolla en polvo","1 libra de pechugas de pollo sin hueso y sin piel (cortadas en tiras)","2 pimientos medianos (en rebanadas finas)","1 cebolla morada mediana (en rebanadas finas)","1 cucharada de aceite de oliva","4 tazas de «arroz» de coliflor (cocido)","1 taza de tomates cherry (partidos por la mitad)","1 aguacate mediano (en rebanadas)"],
["Mezcle las especias en un tazón pequeño y reserve.","En un tazón grande, combine las tiras de pollo, los pimientos en rebanadas, la cebolla morada en rebanadas y la mezcla de especias.","Caliente un sartén a fuego medio-alto. Agregue el aceite de oliva y gire el sartén para cubrir el fondo. Cocine el pollo sazonado y las verduras hasta que el pollo esté bien cocido y las verduras estén tiernas pero crujientes, unos 5 a 7 minutos.","Divida el arroz de coliflor entre cuatro bowls. Cubra con la mezcla de pollo y verduras cocidos.","Agregue tomates cherry y rebanadas de aguacate a cada bowl."]),
"ar":T("وعاء الفاهيتا بالدجاج والخضار","وعاء الفاهيتا اللذيذ هذا بالدجاج والخضار طريقة قليلة الكربوهيدرات للاستمتاع بأطباق مستوحاة من المطبخ المكسيكي. أضف بعض الكزبرة الخضراء الطازجة وشرائح الليمون الأخضر إذا أردت إضافة لمسة مميزة إلى وصفة الغداء الغنية بالنكهة هذه.","4","نحو ½ كوب من خليط الدجاج + 1 كوب أرز القرنبيط + ¼ كوب طماطم كرزية + ¼ حبة أفوكادو",
["1 ملعقة صغيرة كمون مطحون","½ ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","¼ ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة أوريجانو مجفف","½ ملعقة صغيرة بقدونس مجفف","¼ ملعقة صغيرة فلفل كايين","½ ملعقة صغيرة مسحوق الثوم","½ ملعقة صغيرة مسحوق البصل","1 رطل صدور دجاج بدون عظم وبدون جلد (مقطعة شرائح طويلة)","2 حبة فلفل رومي متوسطة (مقطعة شرائح رفيعة)","1 حبة بصل أحمر متوسطة (مقطعة شرائح رفيعة)","1 ملعقة كبيرة زيت زيتون","4 كوب «أرز» القرنبيط (مطبوخ)","1 كوب طماطم كرزية (مقطعة نصفين)","1 حبة أفوكادو متوسطة (مقطعة شرائح)"],
["اخلط البهارات في وعاء صغير وضعها جانبًا.","في وعاء كبير، اخلط شرائح الدجاج وشرائح الفلفل الرومي وشرائح البصل الأحمر وخليط البهارات.","سخّن مقلاة على نار متوسطة إلى عالية. أضف زيت الزيتون وحرّك المقلاة ليغطي قاعها. اطهِ الدجاج المتبّل والخضار حتى ينضج الدجاج تمامًا وتصبح الخضار طرية ومقرمشة قليلًا، نحو 5 إلى 7 دقائق.","وزّع أرز القرنبيط على أربعة أوعية. ضع فوقه خليط الدجاج والخضار المطبوخ.","أضف الطماطم الكرزية وشرائح الأفوكادو إلى كل وعاء."])}))
R.append((6110430,{
"ar":T("كاسترد الهليون المالح","تتطلب هذه الوصفة هليونًا ربيعيًا وطماطم مجففة بالشمس وريحانًا طازجًا. يمكنك شراء الأعشاب الطازجة من معظم محلات البقالة. تبقى الأعشاب الطازجة صالحة في الثلاجة لعدة أيام إلى أسبوع، أما الريحان الطازج فيمكن حفظه على سطح المطبخ.","6","1 قالب صغير (أو قالب مافن)",
["1 بخة، 0.25 غرام من بخاخ الطهي غير اللاصق","1 ملعقة صغيرة زيت زيتون","1 حزمة هليون (مفروم، نحو 2 كوب)","2 ملعقة كبيرة طماطم مجففة بالشمس (مفرومة، غير معبأة في الزيت)","1 ملعقة كبيرة ريحان طازج (مفروم)","2 كوب بديل البيض","¼ كوب حليب خالي الدسم","1 ملعقة كبيرة دقيق","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). استخدم إما 6 قوالب صغيرة سعة كل منها 4 أونصات أو صينية مافن. ادهن القوالب أو الصينية ببخاخ الطهي وضعها جانبًا.","ضع زيت الزيتون في مقلاة غير لاصقة متوسطة. سخّنها على نار متوسطة وقلّب الهليون والطماطم المجففة بالشمس لمدة 8 إلى 10 دقائق أو حتى يبدأ الهليون في اللين. وإذا كان الهليون سميكًا، أضف بضع ملاعق كبيرة من الماء إلى المقلاة وغطِّها لمدة 5 دقائق ليتبخر، ثم تابع التقليب حتى يُمتص كل السائل. ضعه جانبًا ليبرد.","في وعاء متوسط، اخفق الريحان وبديل البيض والحليب والدقيق والملح والفلفل حتى يصبح الخليط ناعمًا بلا كتل.","وزّع خليط الهليون بالتساوي على القوالب الصغيرة أو صينية المافن. يجب أن تمتلئ الأكواب.","اسكب خليط البيض برفق فوق الهليون حتى حافة القالب فقط، ولا تملأه أكثر من اللازم.","اخبزه لمدة 30 دقيقة أو حتى ينتفخ الكاسترد ويبدأ لونه في التحول إلى البني.","أخرجه من الفرن واتركه يبرد قليلًا. اقلب الكاسترد من القوالب الصغيرة أو صينية المافن وقدّمه."])}))
R.append((6111989,{
"es":T("Frambuesas, 1/2 taza","Información nutricional de las frambuesas","0","1/2 taza",["1/2 taza de frambuesas"],[]),
"ar":T("توت العليق، ½ كوب","المعلومات الغذائية لتوت العليق","0","½ كوب",["½ كوب توت العليق"],[])}))
R.append((6112057,{
"ar":T("سلطة التونة والأفوكادو","استمتع بهذه السلطة الغنية بأحماض أوميغا 3 الدهنية! فهي مليئة بالتونة المفيدة للقلب والأفوكادو الغني بالألياف، وهي قليلة الكربوهيدرات ومناسبة لمرضى السكري، وتجهز في دقائق فقط وبسعر يناسب أي ميزانية. قطّع بعض الأفوكادو، وأضف التونة المعلبة، وامزجها مع بيكو دي غالو جاهز من المتجر. تجهز في أقل من 5 دقائق، وهي خيار مثالي للغداء أو طبق سريع بلمسة من الجنوب الغربي الأمريكي. ويُفضَّل استخدام بيكو دي غالو الطازج الذي يمكنك شراؤه من قسم الخضار والفاكهة أو من ركن المأكولات الجاهزة في معظم محلات البقالة. أو إذا كان لديك حبة طماطم وبصلة وفلفلة زائدة، فقطّعها وحضّر بيكو دي غالو بنفسك! ويمكنك أيضًا أن تبدع وتضيف فلفلًا أو قليلًا من الكزبرة الخضراء. اجعل هذا الطبق الغني بالعناصر المغذية والمناسب لمرضى السكري طبقك الخاص!","5","½ كوب",
["2 كيس (6.4 أونصة لكل كيس) تونة في أكياس محكمة الإغلاق معبأة في الماء","½ كوب بيكو دي غالو","1 حبة أفوكادو متوسطة (مقطوعة نصفين)"],
["أزل نواة الأفوكادو. استخدم ملعقة لإخراج لب الأفوكادو وضعه في وعاء متوسط. اهرس الأفوكادو بالشوكة أو بمهراس البطاطس. أضف بيكو دي غالو وامزج جيدًا.","أضف التونة إلى الوعاء وامزج جيدًا. قدّم سلطة التونة مع ما تختاره من البسكويت المالح من القمح الكامل أو خبز البيتا من القمح الكامل أو لفائف الخس."])}))
R.append((6112072,{
"es":T("Pasta e fagioli (pasta y frijoles a la italiana)","La pasta e fagioli es un platillo clásico italiano cuyo nombre significa «pasta y frijoles». Esta versión apta para personas con diabetes incorpora verduras ricas en nutrientes para lograr una comida saludable y saciante.","6","1 ½ tazas",
["2 cucharadas de aceite de oliva","1 cebolla mediana (en cubos)","2 zanahorias medianas (en cubos)","2 tallos de apio (en cubos)","3 dientes de ajo (picados)","4 tazas de caldo de verduras bajo en sodio","1 lata (15 onzas) de tomates en cubos en conserva (sin sal añadida)","1 lata (15 onzas) de frijoles cannellini (sin sal añadida, escurridos y enjuagados)","1 cucharadita de orégano seco","1 cucharadita de albahaca seca","1/2 cucharadita de tomillo seco","1/4 de cucharadita de sal kosher","1/2 cucharadita de pimienta negra","1 taza de pasta (conchas pequeñas)","2 tazas de espinacas baby (picadas)","1/4 de taza de queso parmesano (rallado, para servir)"],
["En una olla grande, caliente el aceite de oliva a fuego medio. Agregue la cebolla, las zanahorias y el apio en cubos. Saltee hasta que las verduras se ablanden, unos 5 minutos.","Agregue el ajo picado a la olla y saltee de 1 a 2 minutos más, hasta que desprenda aroma.","Vierta el caldo de verduras, los tomates en cubos, los frijoles cannellini, el orégano seco, la albahaca seca, el tomillo seco, la sal kosher y la pimienta. Deje que la mezcla suelte el hervor, luego reduzca el fuego y cocine a fuego lento durante 15 minutos.","Mientras tanto, cocine la pasta de conchas según las instrucciones del paquete. Escúrrala y reserve.","Agregue las espinacas picadas a la olla y cocine hasta que se marchiten.","Incorpore la pasta cocida. Cocine a fuego lento 5 minutos más para que se integren los sabores. Cubra con queso parmesano recién rallado, si lo desea."]),
"ar":T("باستا فاجيولي (المعكرونة والفاصولياء الإيطالية)","باستا إي فاجيولي، أو باستا فاجيولي، طبق إيطالي كلاسيكي معناه «المعكرونة والفاصولياء». تضيف هذه النسخة المناسبة لمرضى السكري بعض الخضار الغنية بالعناصر المغذية للحصول على وجبة صحية ومشبعة.","6","1½ كوب",
["2 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مقطعة مكعبات)","2 حبة جزر متوسطة (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","3 فص ثوم (مفروم)","4 كوب مرق خضار قليل الصوديوم","1 علبة (15 أونصة) طماطم معلبة مقطعة مكعبات (بدون ملح مضاف)","1 علبة (15 أونصة) فاصولياء كانيليني (بدون ملح مضاف، مصفاة ومغسولة)","1 ملعقة صغيرة أوريجانو مجفف","1 ملعقة صغيرة ريحان مجفف","½ ملعقة صغيرة زعتر مجفف","¼ ملعقة صغيرة ملح كوشر","½ ملعقة صغيرة فلفل أسود","1 كوب معكرونة (أصداف صغيرة)","2 كوب سبانخ صغيرة (مفرومة)","¼ كوب جبن بارميزان (مبشور، للتقديم)"],
["في قدر كبير، سخّن زيت الزيتون على نار متوسطة. أضف البصل والجزر والكرفس المقطع مكعبات. قلّبها حتى تلين الخضار، نحو 5 دقائق.","أضف الثوم المفروم إلى القدر وقلّبه لمدة 1 إلى 2 دقيقة إضافية حتى تفوح رائحته.","اسكب مرق الخضار والطماطم المقطعة والفاصولياء الكانيليني والأوريجانو المجفف والريحان المجفف والزعتر المجفف وملح الكوشر والفلفل. دع الخليط يصل إلى درجة الغليان، ثم خفف النار واتركه على نار هادئة لمدة 15 دقيقة.","في هذه الأثناء، اسلق معكرونة الأصداف حسب إرشادات العبوة. صفّها وضعها جانبًا.","أضف السبانخ المفرومة إلى القدر واطهِها حتى تذبل.","أضف المعكرونة المطبوخة وقلّب. اتركها على نار هادئة 5 دقائق إضافية لتتمازج النكهات. زيّنها بجبن البارميزان الطازج المبشور إن رغبت."])}))
R.append((6112084,{
"es":T("Bok choy fácil con ajo","¿Busca un acompañamiento bajo en carbohidratos para una cena rápida entre semana? ¡Pruebe nuestra receta de bok choy fácil con ajo! Este platillo sabroso y apto para personas con diabetes lleva bok choy baby tierno, salteado con ingredientes buenos para el corazón y un toque de salsa de soya baja en sodio. Es un complemento delicioso y cuidadoso con la glucosa en la sangre (azúcar en la sangre) para su menú. Pruebe combinar esta guarnición de verdura sin almidón con salmón glaseado con miel y soya para una cena fácil y sabrosa entre semana.","4","1 taza",
["1 cucharada de aceite de oliva","5 dientes de ajo (picados)","2 chalotes enteros (picados)","8 bok choy baby enteros (con las raíces recortadas)","1/4 de cucharadita de salsa de soya baja en sodio","2 cucharadas de caldo de verduras bajo en sodio","1 cucharadita de aceite de ajonjolí","1 cucharadita de hojuelas de chile rojo triturado"],
["Caliente el aceite de oliva en un sartén grande a fuego medio-alto. Agregue el ajo y los chalotes y cocine, revolviendo de vez en cuando, hasta que desprendan aroma, de 1 a 2 minutos.","En un tazón pequeño, mezcle la salsa de soya, el caldo de verduras y el aceite de ajonjolí.","Agregue el bok choy y la salsa al sartén. Revuelva para cubrir. Tape y cocine de 2 a 3 minutos, destape y revuelva, luego tape y continúe cocinando hasta que el bok choy esté tierno, de 3 a 5 minutos más.","Espolvoree con el chile rojo triturado."]),
"ar":T("باك تشوي بالثوم سهل التحضير","هل تبحث عن طبق جانبي قليل الكربوهيدرات لعشاء سريع في أيام الأسبوع؟ جرّب وصفة الباك تشوي بالثوم سهلة التحضير! يتميز هذا الطبق اللذيذ والمناسب لمرضى السكري بالباك تشوي الصغير الطري المقلي مع مكونات مفيدة للقلب ولمسة من صلصة الصويا قليلة الصوديوم، ما يجعله إضافة لذيذة ومراعية لسكر الدم إلى قائمة وجباتك. جرّب تقديم هذا الطبق الجانبي من الخضار غير النشوية مع السلمون المطلي بالعسل وصلصة الصويا للحصول على وجبة عشاء لذيذة وسهلة في أيام الأسبوع.","4","1 كوب",
["1 ملعقة كبيرة زيت زيتون","5 فص ثوم (مفروم)","2 حبة كراث أخضر (شالوت) كاملة (مفرومة)","8 حبات باك تشوي صغيرة كاملة (مقطوعة الجذور)","¼ ملعقة صغيرة صلصة صويا قليلة الصوديوم","2 ملعقة كبيرة مرق خضار قليل الصوديوم","1 ملعقة صغيرة زيت السمسم","1 ملعقة صغيرة رقائق الفلفل الأحمر المجروش"],
["سخّن زيت الزيتون في مقلاة كبيرة على نار متوسطة إلى عالية. أضف الثوم والشالوت واطهِهما مع التقليب من حين لآخر حتى تفوح رائحتهما، من 1 إلى 2 دقيقة.","في وعاء صغير، اخلط صلصة الصويا ومرق الخضار وزيت السمسم.","أضف الباك تشوي والصلصة إلى المقلاة. قلّب ليتغلف بالصلصة. غطِّ المقلاة واطهِ من 2 إلى 3 دقائق، ثم اكشف الغطاء وقلّب، ثم غطِّ مجددًا وواصل الطهي حتى يصبح الباك تشوي طريًا، من 3 إلى 5 دقائق إضافية.","رش فوقه الفلفل الأحمر المجروش."])}))
R.append((6112105,{
"ar":T("كاري السبانخ والبطاطا الحلوة (ساغ آلو)","تستبدل هذه الوصفة الخاصة بطبق السبانخ الهندي المتبّل البطاطس العادية بالبطاطا الحلوة، لتقدم نسخة جديدة لذيذة وصحية من الكاري.","6","¾ كوب",
["2 حبة بطاطا حلوة متوسطة (نحو 12 أونصة، مقشرة ومقطعة إلى قطع بحجم 1 بوصة)","1 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مقشرة ومقطعة شرائح رفيعة)","2 فص ثوم (مبشور أو مفروم)","½ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة كمون (مطحون)","1 ملعقة صغيرة كركم","1 ملعقة صغيرة زنجبيل مطحون","1 ملعقة كبيرة مسحوق الفلفل الحار (تشيلي)","1 كوب ماء أو مرق خضار","5 أونصة سبانخ صغيرة"],
["ضع البطاطا الحلوة و½ كوب ماء في وعاء صالح للميكروويف أو جهاز تبخير بغطاء. سخّنها في الميكروويف لمدة 7-8 دقائق أو حتى تصبح البطاطا الحلوة طرية بحيث تخترقها الشوكة بسهولة. لا تفرط في طهيها.","بينما تُبخَّر البطاطا الحلوة، ضع زيت الزيتون في مقلاة كبيرة على نار متوسطة. أضف البصل وقلّبه لمدة 3-4 دقائق أو حتى يصبح البصل شفافًا. أضف الثوم وقلّب لمدة دقيقتين إضافيتين.","أضف الملح والفلفل والكمون والكركم والزنجبيل ومسحوق الفلفل الحار والماء أو المرق. اتركه حتى يغلي على نار هادئة.","أضف السبانخ واطهِها حتى تذبل، نحو 5 دقائق.","أضف البطاطا الحلوة وقلّب حتى تسخن."])}))
R.append((6112598,{
"es":T("Huevos horneados dulces y ahumados","En lugar de huevos fritos y pan tostado, pruebe este desayuno fácil. Es la manera perfecta de animar su desayuno o brunch del fin de semana.","4","1 mitad de tomate + 1 huevo",
["2 tomates grandes enteros, maduros, tipo beefsteak o heirloom","1 cucharadita de pimienta negra","1 cucharadita de comino","4 huevos medianos","2 cucharaditas de queso parmesano (rallado, reducido en grasa)"],
["Precaliente el horno a 350°F.","Lave los tomates y córtelos por la mitad. Retire la pulpa y las semillas, dejando un borde de tomate de aproximadamente 1/2 pulgada.","Colóquelos con el lado cortado hacia arriba en un molde de vidrio para hornear engrasado.","Espolvoree cada mitad de tomate con pimienta y comino. Rompa un huevo dentro de cada «cascarón» de tomate. Espolvoree cada huevo con 1/2 cucharadita del queso.","Hornee hasta que los huevos estén cuajados, aproximadamente 25 minutos."]),
"ar":T("بيض مخبوز بنكهة حلوة ومدخنة","بدلًا من البيض المقلي والخبز المحمص، جرّب هذا الفطور السهل. إنه الطريقة المثالية لإضفاء البهجة على فطور نهاية الأسبوع أو وجبة البرانش.","4","نصف حبة طماطم + 1 بيضة",
["2 حبة طماطم كبيرة ناضجة كاملة من نوع بيف ستيك أو الطماطم التراثية","1 ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة كمون","4 بيضات متوسطة","2 ملعقة صغيرة جبن بارميزان (مبشور، قليل الدسم)"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية).","اغسل الطماطم وقطّعها نصفين. أخرج اللب والبذور واترك حافة من الطماطم بسمك نحو ½ بوصة.","ضعها بحيث يكون الجانب المقطوع لأعلى في طبق خَبز زجاجي مدهون بالزيت.","رش كل نصف طماطم بالفلفل والكمون. اكسر بيضة في كل «قشرة» طماطم. رش كل بيضة بـ ½ ملعقة صغيرة من الجبن.","اخبزها حتى يتماسك البيض، نحو 25 دقيقة."])}))
R.append((6112652,{
"es":T("Cazuela de huevo estilo mexicano en sartén","Este desayuno colorido parece una tostada, pero la base está hecha con sustituto de huevo en lugar de tortillas. Es una manera saciante de empezar el día e incluir una porción de verduras.","4","1/4 de la receta, aproximadamente 1 ½ tazas",
["1 cucharadita de aceite de canola","1 1/2 tazas de sustituto de huevo","1 lata de chiles verdes en conserva (4.5 onzas, picados, escurridos)","1/3 de taza de queso cheddar (rallado, reducido en grasa, añejo)","1 lata (2.25 onzas) de aceitunas negras (en rodajas, escurridas)","1/2 taza de tomate (en cubos)","1 aguacate mediano (maduro, pelado, sin hueso y picado)","1/4 de taza de cilantro fresco (picado)"],
["Caliente el aceite en un sartén antiadherente mediano a fuego medio. Agregue el huevo, cocine 1 minuto y revuelva suavemente hasta que cuaje apenas (Nota: el huevo todavía estará muy húmedo). Retire del fuego.","Cubra con el resto de los ingredientes en el orden indicado. Tape y cocine a fuego medio-bajo de 2 a 3 minutos o hasta que el queso se derrita."]),
"ar":T("طاجن البيض المكسيكي في المقلاة","يبدو هذا الفطور الملون كالتوستادا، لكن قاعدته مصنوعة من بديل البيض بدلًا من التورتيلا. إنها طريقة مشبعة لبدء يومك وتناول حصة من الخضار.","4","¼ الوصفة، نحو 1½ كوب",
["1 ملعقة صغيرة زيت الكانولا","1½ كوب بديل البيض","1 علبة فلفل أخضر حار معلب (4.5 أونصات، مفروم، مصفى)","⅓ كوب جبن شيدر (مبشور، قليل الدسم، حاد)","1 علبة (2.25 أونصة) زيتون أسود (مقطع شرائح، مصفى)","½ كوب طماطم (مقطعة مكعبات)","1 حبة أفوكادو متوسطة (ناضجة، مقشرة ومنزوعة النواة ومفرومة)","¼ كوب كزبرة خضراء طازجة (مفرومة)"],
["سخّن الزيت في مقلاة متوسطة غير لاصقة على نار متوسطة. أضف البيض واطهه دقيقة واحدة وقلّب برفق حتى يتماسك بالكاد (ملاحظة: سيظل البيض رطبًا جدًا). ارفعه عن النار.","ضع فوقه بقية المكونات بالترتيب المذكور. غطِّ المقلاة واطهِ على نار متوسطة إلى منخفضة من 2 إلى 3 دقائق أو حتى يذوب الجبن."])}))
R.append((6112688,{
"ar":T("برغر السلمون الاقتصادي","هذه البرغر طريقة جيدة لتنويع قائمة طعامك! فهي مليئة بالسلمون المفيد للقلب مع بعض الخضار. وللحفاظ على كمية الكربوهيدرات منخفضة، تُقدَّم فوق خس بيب بدلًا من خبز البرغر. قدّم هذه البرغر مع سلطة خضراء مرشوشة بصلصة السمسم والزنجبيل للحصول على وجبة خفيفة ومنعشة.","6","1 برغر سلمون",
["1 بخة، 0.25 غرام من بخاخ الطهي غير اللاصق","½ حبة بصل صغيرة (مفرومة)","1 فص ثوم (مفروم)","1 حبة فلفل رومي أحمر متوسطة (منزوعة البذور ومفرومة)","1 ملعقة كبيرة معجون الكاري الأحمر التايلاندي","1 رطل سلمون (بدون جلد، مقطع إلى قطع)","1 بيضة كبيرة","¼ كوب كزبرة خضراء طازجة","6 ورقات خس","2 عود بصل أخضر (مقطع شرائح رفيعة)"],
["سخّن الفرن مسبقًا إلى 475° فهرنهايت (245° مئوية). ادهن صينية خَبز ببخاخ الطهي وضعها جانبًا.","ضع البصل والثوم والفلفل الرومي ومعجون الكاري التايلاندي في محضّر طعام كبير واخلطها حتى تصبح ناعمة.","أضف السلمون وامزجه حتى يصبح ناعمًا. أضف البيضة والكزبرة وامزجها حتى تتجانس.","ضع الخليط بمقدار ½ كوب لكل حصة على صينية الخَبز واضغط عليه برفق لتشكيل قرص. كرر العملية للحصول على 6 أقراص.","رش وجه كل قرص ببخاخ الطهي واخبزها لمدة 15 دقيقة.","قدّم كل برغر سلمون في ورقة خس، وضع فوق كل واحد ملعقة كبيرة واحدة من البصل الأخضر المقطع شرائح."])}))
R.append((6113306,{
"es":T("Aderezo ranch ligero","Información nutricional del aderezo ranch ligero","1","2 cucharadas",["2 cucharadas de aderezo ranch ligero"],[]),
"ar":T("صلصة الرانش الخفيفة","المعلومات الغذائية لصلصة الرانش الخفيفة","1","2 ملعقة كبيرة",["2 ملعقة كبيرة صلصة رانش خفيفة"],[])}))
R.append((6114026,{
"es":T("Ensalada de pollo asado con manzana y aderezo de granada","Fresca y afrutada, esta abundante ensalada de pollo muy baja en carbohidratos es un almuerzo otoñal fácil. Hágala aún más fácil asando el pollo con anticipación y refrigerándolo hasta el momento de armar la ensalada.","4","2 1/2 tazas de ensalada + 4 onzas de pollo + 1 cucharada de aderezo",
["4 pechugas de pollo de 4 onzas cada una (asadas)","8 tazas de espinacas baby","1/4 de taza de nueces tostadas (picadas)","1/4 de taza de cebolla morada (en rebanadas)","1/4 de taza de semillas de granada","1/4 de taza de queso feta sin grasa","1/2 manzana Granny Smith mediana (en rebanadas)","2 cucharadas de jugo de granada","2 cucharadas de aceite de canola","1 cucharadita de mostaza Dijon","1 cucharadita de vinagre de vino blanco","1 cucharadita de jarabe multiusos sin azúcar","1/8 de cucharadita de sal kosher","1/4 de cucharadita de pimienta negra"],
["Prepare el aderezo poniendo el jugo de granada, el aceite, la mostaza, el vinagre, el jarabe, la sal y la pimienta en un tazón pequeño o en un frasco de vidrio. Bata los ingredientes en el tazón o agítelos en el frasco para combinarlos. Reserve.","Arme la ensalada colocando 2 tazas de espinacas en cada plato o tazón. Cubra con las pechugas de pollo en rebanadas.","Espolvoree cada ensalada con 1 cucharada de nueces, cebolla, semillas de granada y queso feta. Agregue 1/4 de la manzana en rebanadas a cada ensalada.","Rocíe cada una con 1 cucharada de aderezo y mezcle."]),
"ar":T("سلطة الدجاج المشوي مع التفاح وصلصة الرمان","طازجة وبنكهة الفاكهة، هذه السلطة الدسمة من الدجاج شديدة الانخفاض في الكربوهيدرات غداء خريفي سهل. يمكنك تسهيل تحضيرها أكثر بشواء الدجاج مسبقًا وحفظه في الثلاجة حتى تكون مستعدًا للتجميع!","4","2½ كوب سلطة + 4 أونصات دجاج + 1 ملعقة كبيرة صلصة",
["4 صدور دجاج، 4 أونصات لكل صدر (مشوية)","8 كوب سبانخ صغيرة","¼ كوب جوز محمص (مفروم)","¼ كوب بصل أحمر (مقطع شرائح)","¼ كوب حبوب رمان","¼ كوب جبن فيتا خالي الدسم","½ حبة تفاح غراني سميث متوسطة (مقطعة شرائح)","2 ملعقة كبيرة عصير رمان","2 ملعقة كبيرة زيت الكانولا","1 ملعقة صغيرة خردل ديجون","1 ملعقة صغيرة خل النبيذ الأبيض","1 ملعقة صغيرة شراب متعدد الاستخدامات خالٍ من السكر","⅛ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود"],
["حضّر الصلصة بوضع عصير الرمان والزيت والخردل والخل والشراب والملح والفلفل في وعاء صغير أو برطمان زجاجي. اخفق المكونات في الوعاء أو رجّها في البرطمان حتى تمتزج. ضعها جانبًا.","جمّع السلطة بوضع 2 كوب من السبانخ في كل طبق أو وعاء. ضع فوقها شرائح صدر الدجاج.","رش على كل سلطة 1 ملعقة كبيرة من الجوز والبصل وحبوب الرمان وجبن الفيتا. أضف ¼ حبة التفاح المقطعة شرائح إلى كل سلطة.","رش على كل واحدة 1 ملعقة كبيرة من الصلصة وقلّب."])}))
save("part2",R)
