from h import *
R=[]
R.append((6123574,{
"es":T("Rebanadas de manzana con mantequilla de cacahuate, arándanos rojos y nueces","¡Lo sencillo y lo delicioso pueden ir de la mano! Siempre puede adaptar esta receta a su gusto sustituyendo la manzana por una pera, la mantequilla de cacahuate por su mantequilla de nuez favorita, y los arándanos rojos por pasas o cerezas secas. Lo más importante es respetar las porciones indicadas a continuación.","6","2 rebanadas",
["2 manzanas medianas (sin corazón y cortadas en 6 rebanadas cada una)","4 cucharadas de mantequilla de cacahuate cremosa","3 cucharadas de arándanos rojos secos","3 cucharadas de nueces (picadas)","2 cucharadas de hojuelas de coco sin azúcar"],
["Coloque las 12 rebanadas de manzana sobre una superficie plana. Unte cada rebanada con 1 cucharadita de mantequilla de cacahuate.","En un tazón pequeño, mezcle los arándanos rojos, las nueces y las hojuelas de coco.","Espolvoree de manera uniforme cada rebanada de manzana con aproximadamente 1 cucharada de la mezcla de arándanos."]),
"ar":T("شرائح التفاح بزبدة الفول السوداني والتوت البري والجوز","البساطة واللذة يمكن أن يجتمعا معًا! يمكنك دائمًا تعديل هذه الوصفة حسب ذوقك باستبدال التفاح بالكمثرى، وزبدة الفول السوداني بزبدة المكسرات المفضلة لديك، والتوت البري بالزبيب أو الكرز المجفف. الأهم هو الالتزام بالكميات المذكورة أدناه.","6","شريحتان",
["2 حبة تفاح متوسطة (منزوعة القلب ومقطعة إلى 6 شرائح لكل حبة)","4 ملعقة كبيرة زبدة فول سوداني كريمية","3 ملعقة كبيرة توت بري مجفف","3 ملعقة كبيرة جوز (مفروم)","2 ملعقة كبيرة رقائق جوز الهند غير المحلاة"],
["ضع شرائح التفاح الـ 12 على سطح مستوٍ. ادهن كل شريحة بـ 1 ملعقة صغيرة من زبدة الفول السوداني.","في وعاء صغير، اخلط التوت البري والجوز ورقائق جوز الهند.","رش كل شريحة تفاح بالتساوي بنحو 1 ملعقة كبيرة من خليط التوت البري."])}))
R.append((6123989,{
"es":T("Panqueques de avena y nueces pecanas","La avena finamente molida puede ser una alternativa fácil e integral a la harina de trigo en muchas recetas, como estos panqueques. ¡Agregue ¾ de taza de arándanos azules frescos para una cobertura con más fibra!","6","1 panqueque",
["1 taza de avena de cocción rápida","1 1/2 cucharaditas de polvo de hornear","2 huevos grandes","1/3 de taza de leche descremada","1/2 plátano mediano (machacado, aproximadamente 1/3 de taza)","1/2 cucharadita de extracto de vainilla","2 cucharadas de nueces pecanas picadas","1 cucharada de aceite de canola"],
["Con un procesador de alimentos, procese la avena hasta lograr una consistencia parecida a la harina. Mezcle la avena y el polvo de hornear en un tazón pequeño y reserve.","En otro tazón, mezcle los huevos, la leche, el plátano machacado y la vainilla. Agregue a los ingredientes secos y mezcle hasta que apenas se integren. Luego incorpore las nueces pecanas con movimientos envolventes.","Caliente el aceite en un sartén antiadherente a fuego medio. Vierta 1/4 de taza de masa sobre el sartén caliente para formar cada panqueque. Cocine hasta que estén ligeramente dorados por ambos lados."]),
"ar":T("بان كيك الشوفان والبيكان","يمكن للشوفان المفروم ناعمًا أن يكون بديلًا سهلًا من الحبوب الكاملة لدقيق القمح في وصفات كثيرة مثل هذا البان كيك. أضف ¾ كوب من العنب البري الطازج للحصول على إضافة أعلى في الألياف!","6","1 فطيرة بان كيك",
["1 كوب شوفان سريع التحضير","1½ ملعقة صغيرة بيكنج باودر","2 بيضة كبيرة","⅓ كوب حليب خالي الدسم","½ حبة موز متوسطة (مهروسة، نحو ⅓ كوب)","½ ملعقة صغيرة خلاصة الفانيلا","2 ملعقة كبيرة بيكان مفروم","1 ملعقة كبيرة زيت الكانولا"],
["باستخدام محضّر الطعام، اطحن الشوفان حتى يصبح قوامه كالدقيق. اخلط الشوفان والبيكنج باودر في وعاء صغير وضعه جانبًا.","في وعاء منفصل، اخلط البيض والحليب والموز المهروس والفانيلا. أضفه إلى المكونات الجافة وامزج حتى يمتزج بالكاد. ثم أضف البيكان بحركة طي رفيقة.","سخّن الزيت في مقلاة غير لاصقة على نار متوسطة. اسكب ¼ كوب من الخليط على المقلاة الساخنة لتحضير كل فطيرة. اطهِها حتى تتحمر قليلًا من الجهتين."])}))
R.append((6126102,{
"ar":T("شوربة البروكلي بالجبن","هذه نسخة أقل في السعرات الحرارية من شوربة البروكلي بالشيدر التقليدية، وما زالت غنية بالنكهة، وهي طريقة رائعة لتناول المزيد من الخضار.","8","¾ كوب",
["1 ملعقة صغيرة زيت الكانولا أو زيت الذرة","1 حبة بصل صغيرة (مفرومة ناعمًا)","2 فص ثوم (مفروم)","1 رطل زهرات بروكلي (مفرومة (نحو 4 كوب))","2 كوب مرق دجاج أو خضار (خالٍ من الدسم، قليل الصوديوم)","½ ملعقة صغيرة مسحوق الخردل","¼ ملعقة صغيرة فلفل أسود","⅛ ملعقة صغيرة صلصة الفلفل الأحمر الحار (اختياري)","⅛ ملعقة صغيرة ملح كوشر","2 كوب حليب (خالٍ من الدسم)","⅓ كوب دقيق متعدد الاستخدامات","½ كوب نصف كريمة ونصف حليب خالٍ من الدسم (half-and-half)","2 أونصة جبن شيدر (قليل الدسم، شرائح أو مبشور)","2 ملعقة كبيرة جبن بارميزان (مبشور)"],
["في قدر كبير، سخّن الزيت على نار متوسطة مع تحريك القدر ليغطي القاع. اطهِ البصل والثوم لمدة 3-4 دقائق، أو حتى يكاد البصل يلين، مع التقليب المستمر.","أضف البروكلي والمرق والخردل والفلفل وصلصة الفلفل الحار والملح وقلّب. ارفع الحرارة إلى متوسطة عالية واتركه حتى يغلي على نار هادئة. خفف الحرارة واتركه على نار هادئة لمدة 5 دقائق، أو حتى يلين البروكلي، مع التقليب من حين لآخر.","في وعاء متوسط، اخفق الحليب والدقيق معًا. أضفه إلى الشوربة وقلّب. اتركها على نار هادئة لمدة 2-3 دقائق، أو حتى يثخن الخليط، مع التقليب من حين لآخر.","أضف نصف الكريمة ونصف الحليب (half-and-half) وجبن الشيدر والبارميزان وقلّب. اطهِها على نار متوسطة إلى منخفضة لمدة 1-2 دقيقة، أو حتى يذوب الجبن، مع التقليب من حين لآخر."])}))
R.append((6127449,{
"es":T("Puré de calabaza butternut","Excelente como acompañamiento de otoño o invierno, este puré de calabaza butternut apto para personas con diabetes es una alternativa deliciosa y baja en carbohidratos al puré de papas.","4","1 taza",
["1 calabaza butternut pequeña (pelada y en cubos)","2 dientes de ajo (picados)","1 cucharada de aceite de oliva","1/4 de cucharadita de sal","1/2 cucharadita de pimienta negra"],
["Cocine al vapor o hierva los cubos de calabaza butternut hasta que estén tiernos al pincharlos con un tenedor. Si los cocinó al vapor, retire la calabaza cocida de la canasta y colóquela en un tazón grande. Si los hirvió, escurra la calabaza butternut y luego páselos a un tazón grande.","Agregue el ajo picado, el aceite de oliva, la sal y la pimienta, y triture hasta obtener un puré suave."]),
"ar":T("هريس القرع العسلي (باتر نات)","هذا الهريس من القرع العسلي المناسب لمرضى السكري طبق جانبي رائع للخريف أو الشتاء، وهو بديل لذيذ وقليل الكربوهيدرات لهريس البطاطس.","4","1 كوب",
["1 حبة قرع عسلي (باتر نات) صغيرة (مقشرة ومقطعة مكعبات)","2 فص ثوم (مفروم)","1 ملعقة كبيرة زيت زيتون","¼ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود"],
["بخّر مكعبات القرع العسلي أو اسلقها حتى تصبح طرية بحيث تخترقها الشوكة. إذا بخّرتها، أخرج القرع المطبوخ من سلة التبخير وضعه في وعاء كبير. وإذا سلقتها، صفِّ القرع ثم ضعه في وعاء كبير.","أضف الثوم المفروم وزيت الزيتون والملح والفلفل واهرس حتى يصبح ناعمًا."])}))
R.append((6127541,{
"ar":T("شوربة الخضار في القدر البطيء","تُعد هذه الشوربة طبق خضار جانبيًا رائعًا. قدّمها مع الدجاج المشوي أو السمك. يمكن تجميدها جيدًا، لذا يمكنك حفظ جزء منها لوقت لاحق إن أردت.","6","2 كوب",
["2 علبة طماطم مقطعة بدون ملح مضاف (14 أونصة مع العصير)","1 حبة بصل كبيرة كاملة (مقطعة مكعبات)","4 فص ثوم (مفروم)","2 حبة جزر كبيرة (مقطعة مكعبات)","2 عود كرفس (مقطع مكعبات)","1 حبة جزر أبيض (باستنك) متوسطة (مقطعة مكعبات)","1 حبة فلفل رومي أحمر كبيرة (منزوعة البذور ومقطعة مكعبات)","6 كوب مرق خضار قليل الصوديوم (قليل الصوديوم)","3 كوب ملفوف (مفروم)","1 ملعقة صغيرة بهارات بدون ملح (خالية من الملح)","½ ملعقة صغيرة ملح (اختياري)","¼ ملعقة صغيرة فلفل أسود","1 حبة بطاطا حلوة كبيرة ((نحو 10 أونصات)، مقشرة ومقطعة مكعبات)"],
["اخلط جميع المكونات معًا في القدر البطيء.","اضبط القدر البطيء على الدرجة العالية لمدة 4-6 ساعات.","قلّب جيدًا قبل التقديم واهرس الجزر الأبيض والبطاطا الحلوة قليلًا لتثخين الشوربة قليلًا."])}))
R.append((6128101,{
"ar":T("سلطة الملفوف","الملفوف مكون أساسي في المطبخ الأيرلندي. قدّم هذه السلطة مع طبق «بانغرز آند ماش» للحصول على وجبة أيرلندية متكاملة في يوم القديس باتريك!","6","½ كوب",
["1 كيس (10 أونصات) خليط كولسلو جاهز","1 ملعقة كبيرة خردل ديجون","1 ملعقة صغيرة محلٍّ قليل السعرات أو خالٍ منها (أو ½ ملعقة صغيرة)","½ ملعقة صغيرة بذور الخشخاش","2 ملعقة كبيرة خل الأرز","⅓ كوب مايونيز خفيف"],
["في وعاء كبير، اخفق المايونيز الخفيف وخل الأرز وخردل ديجون والمحلّي قليل السعرات أو الخالي منها وبذور الخشخاش.","أضف الملفوف إلى الصلصة بحركة طي رفيقة وضعه في الثلاجة لمدة ساعة قبل التقديم ليتشرب الملفوف التتبيلة. (ويمكنك تقديمه فورًا أيضًا، لكنه أفضل إذا تُرك ليتشرب التتبيلة)"])}))
R.append((6128345,{
"es":T("Frittata de espárragos y bok choy","Perfecta para el desayuno, el brunch o incluso la cena, nuestra frittata de espárragos y bok choy es un platillo sabroso y pensado para personas con diabetes, que deleitará su paladar con un efecto mínimo en la glucosa en la sangre (azúcar en la sangre). Esta frittata combina la frescura de los espárragos y el suave crujido del bok choy con huevos ricos en proteínas, y crea una comida equilibrada y nutritiva para quienes viven con diabetes. Rica en nutrientes esenciales, esta frittata es un delicioso complemento para su menú apto para personas con diabetes y ofrece una experiencia culinaria satisfactoria.","6","1 rebanada",
["2 cucharadas de aceite de oliva","1 manojo de espárragos (picados en trozos del tamaño de un bocado)","1 cabeza de bok choy baby (picado)","1/2 cucharadita de sal","1/4 de cucharadita de pimienta negra","2 tazas de sustituto de huevo","2/3 de taza de mozzarella reducida en grasa (rallada)"],
["Precaliente a fuego medio un sartén grande apto para horno.","Agregue el aceite, los espárragos, el bok choy, la sal y la pimienta al sartén. Cocine, revolviendo de vez en cuando, hasta que las verduras se ablanden, de 2 a 3 minutos.","Rompa los huevos en un tazón grande y bata para combinarlos.","Precaliente el horno en la función de asador (broil).","Reduzca el fuego a bajo y vierta la mezcla de huevo en el sartén. Levante suavemente con una espátula los huevos cocidos de la orilla hasta que los lados estén firmes pero la parte superior aún esté líquida, de 3 a 4 minutos.","Espolvoree el queso sobre la frittata. Coloque el sartén en el horno y áselo con el asador hasta que la parte superior esté cuajada y el queso derretido, de 1 a 2 minutos. Corte en seis porciones iguales."]),
"ar":T("فريتاتا الهليون والباك تشوي","فريتاتا الهليون والباك تشوي لدينا مثالية للفطور أو البرانش أو حتى العشاء، وهي طبق غني بالنكهة ومراعٍ لمرضى السكري، صُمم ليسعد ذوقك بأقل تأثير على سكر الدم. تجمع هذه الفريتاتا بين انتعاش الهليون والقرمشة الخفيفة للباك تشوي مع البيض الغني بالبروتين، لتقدم وجبة متوازنة ومغذية لمرضى السكري. وهي مليئة بالعناصر الغذائية الأساسية، وإضافة لذيذة إلى قائمة طعامك المناسبة لمرضى السكري، وتمنحك تجربة طهي مُرضية.","6","1 شريحة",
["2 ملعقة كبيرة زيت زيتون","1 حزمة هليون (مقطعة إلى قطع بحجم اللقمة)","1 رأس باك تشوي صغير (مفروم)","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","2 كوب بديل البيض","⅔ كوب جبن موزاريلا قليل الدسم (مبشور)"],
["سخّن مقلاة كبيرة صالحة للفرن على نار متوسطة.","أضف الزيت والهليون والباك تشوي والملح والفلفل إلى المقلاة. اطهِها مع التقليب من حين لآخر حتى تلين الخضار، من 2 إلى 3 دقائق.","اكسر البيض في وعاء كبير واخفقه حتى يمتزج.","سخّن الفرن مسبقًا على وضع الشواية العلوية.","خفف الحرارة إلى منخفضة واسكب خليط البيض في المقلاة. ارفع البيض المطبوخ عند الحافة برفق بملعقة تقليب مسطحة حتى تتماسك الجوانب ويبقى الوجه سائلًا، من 3 إلى 4 دقائق.","رش الجبن فوق الفريتاتا. ضع المقلاة في الفرن واشوها بالشواية العلوية حتى يتماسك الوجه ويذوب الجبن، من 1 إلى 2 دقيقة. قطّعها إلى ست قطع متساوية."])}))
R.append((6128588,{
"ar":T("سلطة أرز القرنبيط","هذا الطبق القليل الكربوهيدرات يتناسب جيدًا مع كل شيء تقريبًا ويستغرق وقتًا قصيرًا في التحضير أيضًا.","4","1 كوب",
["12 أونصة «أرز» قرنبيط","1 كوب خيار (مقطع مكعبات)","1 كوب طماطم عنبية (مقطوعة نصفين)","2 عود بصل أخضر (مقطع شرائح)","3 ملعقة كبيرة زيتون كالاماتا (مقطع شرائح)","¼ كوب خل النبيذ الأحمر","2 ملعقة كبيرة زيت زيتون","½ ملعقة كبيرة خردل ديجون"],
["يمكن شراء «أرز» القرنبيط مجمدًا من بعض المتاجر، أو يمكنك تحضيره بنفسك باتباع هذه الإرشادات: ضع زهرات القرنبيط في محضّر الطعام وافرمها حتى يصبح قوامها كالأرز (احرص على ألا تفرط في الفرم).","في وعاء كبير، اخلط أرز القرنبيط والخيار والطماطم والبصل الأخضر والزيتون.","في وعاء صغير، اخفق الخل والزيت والخردل. اسكب الصلصة فوق السلطة وقلّب حتى تمتزج.","اسكب الصلصة فوق السلطة وقدّمها مع جبن الفيتا قليل الدسم إن رغبت."])}))
R.append((6129053,{
"ar":T("فلفل محشي اقتصادي","حضّر هذا الطبق بالكامل في الليلة السابقة واحفظه في الثلاجة حتى موعد التقديم. ما عليك سوى تسخينه في الفرن أو الميكروويف لتحصل على عشاء للعائلة كلها في وقت قصير. وهو لذيذ أيضًا عند تناوله باردًا!","6","1 حبة فلفل محشية",
["1 كوب عدس أحمر أو بني","2 كوب ماء","1 ملعقة كبيرة زنجبيل طازج (مبشور)","2 فص ثوم (مفروم)","1 ملعقة صغيرة كركم","1 رطل دجاج مفروم قليل الدهن","1 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة)","½ ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة فلفل كايين","6 حبات فلفل رومي صغيرة ((بأي لون أو بألوان متنوعة))","½ كوب مرق دجاج قليل الصوديوم"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية).","ضع العدس والماء والزنجبيل والثوم والكركم في قدر متوسط. دعه يغلي ثم خفف الحرارة واتركه على نار هادئة مع تغطيته جزئيًا لمدة 20 دقيقة. ضعه جانبًا ليبرد.","بينما يُطهى العدس، اخلط الدجاج المفروم والكزبرة والملح والفلفل الأسود المطحون وفلفل كايين في وعاء متوسط وضعه جانبًا.","اقطع أغطية حبات الفلفل وأزل قلب البذور (احتفظ بالأغطية). نظّف الأضلاع الداخلية وأي بذور من داخل الفلفل ورتّب الحبات في طبق خَبز بحيث يكون الجزء المفتوح لأعلى. ضع الأغطية جانبًا. (ملاحظة: إذا لم تثبت حبات الفلفل واقفة، اقطع قليلًا من قاعدتها لتستوي وتقف مستقيمة. حاول ألا تصنع ثقبًا في القاعدة حتى لا تسقط الحشوة).","بعد أن يبرد العدس، أضفه إلى خليط الدجاج وامزج جيدًا حتى يتجانس.","املأ كل حبة فلفل بخليط الدجاج والعدس دون أن تكبس الخليط بإحكام. املأها برفق حتى الحافة.","أعد كل غطاء إلى حبة الفلفل المحشوة بخليط الدجاج والعدس، ثم اسكب مرق الدجاج في قاع الطبق.","اخبزه لمدة ساعة واحدة أو حتى تصل درجة الحرارة الداخلية لخليط الدجاج إلى 165 درجة (75° مئوية)."])}))
R.append((6129077,{
"es":T("Pimiento relleno de camarones con grits","Pruebe esta variante de los clásicos camarones con grits. Esta receta más baja en carbohidratos es una excelente opción para personas con diabetes y concentra muchísimo sabor en una cena fácil entre semana.","8","1 mitad de pimiento relleno",
["1 taza de grits molidos a la piedra (sémola de maíz)","1 taza de queso cheddar (reducido en grasa, rallado, dividido)","1/4 de cucharadita de sal kosher (dividida)","1/4 de cucharadita de pimienta negra (dividida)","4 pimientos medianos (partidos por la mitad, sin semillas)","1 cucharada de aceite de oliva","1 cebolla mediana (finamente picada)","2 dientes de ajo","1 taza de tomates cherry (partidos por la mitad)","1 libra de camarones (pelados y desvenados)","1 cucharadita de condimento Old Bay","1/2 taza de caldo de pollo bajo en sodio","1 cucharada de perejil fresco (picado, para decorar)"],
["Cocine los grits según las instrucciones del paquete hasta que queden cremosos y suaves.","Incorpore ½ taza de queso cheddar, 1/8 de cucharadita de sal y 1/8 de cucharadita de pimienta negra.","Precaliente el horno a 375 grados F.","Coloque las mitades de pimiento en un molde para hornear, con el lado cortado hacia arriba. Tape y hornee durante 40 minutos.","En un sartén grande, caliente el aceite de oliva a fuego medio. Agregue la cebolla picada y el ajo, y saltee hasta que se ablanden.","Incorpore los tomates cherry, el condimento Old Bay, la sal kosher restante y la pimienta. Cocine 2 minutos más.","Apague el fuego y agregue los camarones al sartén. Revuelva para combinar.","Con una cuchara, rellene cada mitad de pimiento con los grits cocidos, presionando con el dorso de la cuchara. Cubra los grits con la mezcla de camarones y tomate.","Espolvoree el queso cheddar rallado restante sobre cada pimiento relleno.","Cubra con papel aluminio y hornee hasta que el queso se derrita, los pimientos se ablanden y el relleno esté bien cocido, unos 20 minutos.","Gratine con el asador del horno de 2 a 3 minutos hasta que el queso burbujee.","Retire del horno y deje enfriar unos minutos. Decore con perejil fresco picado, si lo desea."]),
"ar":T("فلفل محشي بالروبيان والجريتس","جرّب هذه النسخة المبتكرة من طبق الروبيان والجريتس الكلاسيكي. هذه الوصفة الأقل كربوهيدرات خيار رائع لمرضى السكري، وتجمع كمية كبيرة من النكهة في عشاء سهل لأيام الأسبوع.","8","نصف حبة فلفل محشية",
["1 كوب جريتس مطحون على الحجر (دقيق ذرة خشن)","1 كوب جبن شيدر (قليل الدسم، مبشور، مقسّم)","¼ ملعقة صغيرة ملح كوشر (مقسّمة)","¼ ملعقة صغيرة فلفل أسود (مقسّمة)","4 حبات فلفل رومي متوسطة (مقطوعة نصفين ومنزوعة البذور)","1 ملعقة كبيرة زيت زيتون","1 حبة بصل متوسطة (مفرومة ناعمًا)","2 فص ثوم","1 كوب طماطم كرزية (مقطوعة نصفين)","1 رطل روبيان (مقشر ومنزوع الخيط)","1 ملعقة صغيرة بهارات أولد باي","½ كوب مرق دجاج قليل الصوديوم","1 ملعقة كبيرة بقدونس طازج (مفروم، للتزيين)"],
["اطهِ الجريتس حسب إرشادات العبوة حتى يصبح كريميًا وناعمًا.","أضف ½ كوب من جبن الشيدر و⅛ ملعقة صغيرة من الملح و⅛ ملعقة صغيرة من الفلفل الأسود بحركة طي رفيقة.","سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية).","ضع أنصاف الفلفل الرومي في طبق خَبز بحيث يكون الجانب المقطوع لأعلى. غطِّه واخبزه لمدة 40 دقيقة.","في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة. أضف البصل المفروم والثوم وقلّبهما حتى يلينا.","أضف الطماطم الكرزية وبهارات أولد باي وما تبقى من ملح الكوشر والفلفل. اطهِها دقيقتين إضافيتين.","أطفئ النار وأضف الروبيان إلى المقلاة. قلّب حتى يمتزج.","اغرف الجريتس المطبوخ في كل نصف فلفل واضغط عليه بظهر الملعقة. ضع فوق الجريتس خليط الروبيان والطماطم.","رش بقية جبن الشيدر المبشور فوق كل فلفل محشي.","غطِّه بورق الألمنيوم واخبزه حتى يذوب الجبن ويلين الفلفل وتنضج الحشوة، نحو 20 دقيقة.","اشوه بالشواية العلوية لمدة 2-3 دقائق حتى يتفقع الجبن.","أخرجه من الفرن واتركه يبرد بضع دقائق. زيّنه بالبقدونس الطازج المفروم إن رغبت."])}))
R.append((6129816,{
"es":T("Omelet de espinacas y queso feta","Las espinacas frescas y verdes, la cebolla crujiente y un toque de cremoso queso feta hacen de este omelet uno que querrá preparar una y otra vez.","1","1 omelet",
["1/2 taza de sustituto de huevo","1/4 de cucharadita de pimienta negra","1 cucharadita de aceite de oliva","1/4 de taza de cebolla morada (en cubos)","1 taza de espinacas (picadas)","1 cucharada de queso feta reducido en grasa","1/4 de taza de tomates roma (en cubos)","1/8 de cucharadita de sal"],
["En un tazón, sazone el sustituto de huevo con sal y pimienta y mezcle.","Caliente el aceite de oliva en un sartén antiadherente a fuego medio.","Agregue la cebolla morada en cubos y saltee hasta que se ablande.","Agregue las espinacas picadas al sartén y cocine hasta que se marchiten.","Vierta el huevo batido sobre las espinacas y la cebolla.","Cuando el huevo empiece a cuajar, espolvoree los tomates en cubos y el queso feta desmenuzado sobre la mitad del omelet.","Cuando el huevo esté completamente cuajado, doble con cuidado el omelet por la mitad con una espátula.","Deslice el omelet a un plato, decore con hierbas frescas si lo desea y sirva."]),
"ar":T("أومليت السبانخ والفيتا","السبانخ الخضراء الطازجة والبصل المقرمش ولمسة من جبن الفيتا الكريمي تجعل هذا الأومليت وصفة تحب أن تحضّرها مرارًا وتكرارًا.","1","1 أومليت",
["½ كوب بديل البيض","¼ ملعقة صغيرة فلفل أسود","1 ملعقة صغيرة زيت زيتون","¼ كوب بصل أحمر (مقطع مكعبات)","1 كوب سبانخ (مفرومة)","1 ملعقة كبيرة جبن فيتا قليل الدسم","¼ كوب طماطم روما (مقطعة مكعبات)","⅛ ملعقة صغيرة ملح"],
["في وعاء، تبّل بديل البيض بالملح والفلفل وامزجه.","سخّن زيت الزيتون في مقلاة غير لاصقة على نار متوسطة.","أضف البصل الأحمر المقطع مكعبات وقلّبه حتى يلين.","أضف السبانخ المفرومة إلى المقلاة واطهِها حتى تذبل.","اسكب البيض المخفوق فوق السبانخ والبصل.","عندما يبدأ البيض في التماسك، رش الطماطم المقطعة مكعبات وجبن الفيتا المفتت فوق نصف الأومليت.","بعد أن يتماسك البيض تمامًا، اطوِ الأومليت بعناية إلى نصفين باستخدام ملعقة تقليب مسطحة.","اسحب الأومليت إلى طبق، وزيّنه بالأعشاب الطازجة إن رغبت، ثم قدّمه."])}))
R.append((6130738,{
"es":T("Estofado de garbanzos al curry con verduras asadas","Prepárese para saborear un reconfortante tazón lleno de verduras con este estofado vegano de garbanzos apto para personas con diabetes. Lleno de sabor y verduras asadas, es como un abrazo para su paladar y su salud.","4","2 tazas",
["1 taza de camotes (pelados y en cubos, para las verduras asadas)","1 pimiento rojo entero (en cubos, para las verduras asadas)","1 taza de floretes de coliflor (para las verduras asadas)","2 cucharaditas de aceite de oliva (divididas)","1/2 cucharadita de sal (dividida)","1/2 cucharadita de pimienta negra (dividida)","1 cebolla pequeña (en cubos)","2 dientes de ajo (picados)","2 cucharaditas de curry en polvo","1/2 cucharadita de cúrcuma molida","14 onzas de tomates en cubos en conserva (sin sal añadida)","6 onzas de leche de coco light sin azúcar","1 taza de caldo de verduras bajo en sodio","7 onzas de garbanzos en conserva (enjuagados y escurridos)","1 manojo de cilantro fresco (picado, para decorar)"],
["Precaliente el horno a 400 grados F. Forre una bandeja para hornear con papel pergamino.","En un tazón grande, mezcle el camote, el pimiento rojo y los floretes de coliflor con 1/8 de cucharadita de sal, 1/4 de cucharadita de pimienta y 1 cucharadita de aceite de oliva.","Extienda las verduras en una sola capa sobre la bandeja preparada. Áselas en el horno precalentado de 20 a 25 minutos, hasta que estén tiernas y ligeramente caramelizadas.","En una olla grande u olla holandesa, caliente el aceite de oliva restante a fuego medio. Agregue la cebolla en cubos y el ajo picado, y saltee hasta que desprendan aroma y se vuelvan translúcidos.","Agregue a la olla el curry en polvo, la cúrcuma, 1/4 de cucharadita de sal y 1/4 de cucharadita de pimienta. Revuelva bien para cubrir la cebolla y el ajo con las especias.","Vierta los tomates en cubos (con su jugo), la leche de coco y el caldo de verduras. Revuelva para combinar. Agregue los garbanzos enjuagados a la olla y mezcle todo. Deje que la mezcla suelte el hervor.","Reduzca el fuego a bajo y deje que el estofado hierva a fuego lento sin tapar unos 15 a 20 minutos, para que se integren los sabores. Revuelva de vez en cuando.","Retire las verduras asadas del horno y agréguelas a la olla. Revuelva con cuidado para incorporarlas al estofado. Sirva el estofado de garbanzos al curry en tazones, decorado con cilantro fresco."]),
"ar":T("يخنة الحمص بالكاري مع الخضار المشوية","استعد لتتذوق وعاءً دافئًا مليئًا بالخضار مع يخنة الحمص النباتية هذه المناسبة لمرضى السكري. إنها غنية بالنكهة والخضار المشوية، وكأنها عناق لحاسة التذوق ولصحتك.","4","2 كوب",
["1 كوب بطاطا حلوة (مقشرة ومقطعة مكعبات، للخضار المشوية)","1 حبة فلفل رومي أحمر كاملة (مقطعة مكعبات، للخضار المشوية)","1 كوب زهرات قرنبيط (للخضار المشوية)","2 ملعقة صغيرة زيت زيتون (مقسّمة)","½ ملعقة صغيرة ملح (مقسّمة)","½ ملعقة صغيرة فلفل أسود (مقسّمة)","1 حبة بصل صغيرة (مقطعة مكعبات)","2 فص ثوم (مفروم)","2 ملعقة صغيرة مسحوق الكاري","½ ملعقة صغيرة كركم مطحون","14 أونصة طماطم معلبة مقطعة مكعبات (بدون ملح مضاف)","6 أونصات حليب جوز الهند الخفيف غير المحلى","1 كوب مرق خضار قليل الصوديوم","7 أونصات حمص معلب (مغسول ومصفى)","1 حزمة كزبرة خضراء طازجة (مفرومة، للتزيين)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية). بطّن صينية خَبز بورق الزبدة.","في وعاء كبير، قلّب البطاطا الحلوة والفلفل الرومي الأحمر وزهرات القرنبيط مع ⅛ ملعقة صغيرة من الملح و¼ ملعقة صغيرة من الفلفل و1 ملعقة صغيرة من زيت الزيتون.","افرد الخضار في طبقة واحدة على الصينية المجهّزة. اشوها في الفرن المسخّن مسبقًا لمدة 20 إلى 25 دقيقة حتى تصبح طرية ومكرملة قليلًا.","في قدر كبير أو قدر ثقيل، سخّن ما تبقى من زيت الزيتون على نار متوسطة. أضف البصل المقطع مكعبات والثوم المفروم وقلّبهما حتى تفوح رائحتهما ويصبحا شفافين.","أضف مسحوق الكاري والكركم و¼ ملعقة صغيرة من الملح و¼ ملعقة صغيرة من الفلفل إلى القدر. قلّب جيدًا ليتغطى البصل والثوم بالبهارات.","اسكب الطماطم المقطعة (مع عصيرها) وحليب جوز الهند ومرق الخضار. قلّب حتى يمتزج. أضف الحمص المغسول إلى القدر وقلّب كل شيء معًا. دع الخليط يغلي.","خفف الحرارة إلى منخفضة واترك اليخنة على نار هادئة دون غطاء لمدة 15 إلى 20 دقيقة تقريبًا لتتمازج النكهات. قلّب من حين لآخر.","أخرج الخضار المشوية من الفرن وأضفها إلى القدر. قلّب برفق لدمجها في اليخنة. قدّم يخنة الحمص بالكاري في أوعية مزيّنة بالكزبرة الخضراء الطازجة."])}))
R.append((6131183,{
"ar":T("الإدامامي والمعكرونة مع الفيتا","قدّم طبق المعكرونة الفريد هذا مع بعض الخضار الورقية المتبّلة بخفة. وهو أيضًا غداء رائع يمكنك أخذه معك إلى المكتب.","6","1 كوب",
["4 أونصات معكرونة بيني أو روتيني من الحبوب الكاملة (غير مطبوخة)","8 أونصات إدامامي مقشر طازج أو مجمد","1½ كوب طماطم عنبية (مقطعة أرباعًا)","16 حبة زيتون كالاماتا كاملة (منزوعة النوى ومفرومة فرمًا خشنًا)","2 ملعقة كبيرة ريحان طازج مفروم، أو 2 ملعقة صغيرة ريحان مجفف","½ ملعقة صغيرة أوراق إكليل الجبل (مفتتة (اختياري))","1 فص ثوم (مفروم)","⅛ ملعقة صغيرة رقائق الفلفل الأحمر المجروش (اختياري)","1 حبة ليمون متوسطة (معصورة)","2 أونصة جبن فيتا (قليل الدسم، مفتت)"],
["اطهِ المعكرونة حسب إرشادات العبوة دون إضافة أي ملح أو دهون، وأضف الإدامامي خلال آخر دقيقتين من وقت الطهي.","في وعاء صغير، اخلط الطماطم والزيتون والريحان وإكليل الجبل (اختياري) والثوم ورقائق الفلفل. قلّب لتمتزج وضعها جانبًا.","صفِّ المعكرونة والإدامامي في مصفاة، وضعهما في طبق تقديم أو وعاء معكرونة، واعصر الليمون فوق الجميع، وضع الفيتا فوقها، وكوّم خليط الطماطم في الوسط."])}))
save("part4",R)
