from lib import build
R = []
# 7426196
R.append((7426196,
("Sopa de chirivía y manzana", "Una sopa caliente y reconfortante para el invierno, que puede servirse como comida ligera o como deliciosa entrada festiva.", "2", "376 g",
 ["1 cucharadita de aceite", "1 cebolla pequeña, picada", "media cucharadita de semillas de comino", "300 g de chirivías, peladas y picadas", "1 manzana pequeña para cocinar, pelada y picada", "600 ml de caldo de verduras", "pimienta negra recién molida", "1 chirivía pequeña", "2 cucharaditas de aceite"],
 ["Caliente el aceite en una cacerola, agregue la cebolla y las semillas de comino y fría durante 2 a 3 minutos.", "Agregue las chirivías y la manzana y continúe friendo durante 3 minutos.", "Agregue el caldo, déjelo hervir y cocine a fuego lento durante 20 a 25 minutos, hasta que las chirivías estén tiernas.", "Pase la mezcla a una licuadora o procesador de alimentos y procese hasta obtener una consistencia suave. Sazone al gusto.", "Para hacer las chips de chirivía, pele la chirivía y córtela en rodajas muy finas con un pelador. Caliente el aceite en una sartén pequeña y fría las tiras de chirivía hasta que estén crujientes y doradas; luego escúrralas sobre papel de cocina.", "Cubra la sopa con las chips de chirivía y sirva."],
 ["Dé más sabor a la sopa con 1 cucharadita de pasta de curry.", "Instrucciones para congelar: Congele en porciones y luego descongele en el refrigerador, o descongele en el microondas revolviendo con frecuencia.", "Porciones de fruta/verdura por ración: 4"], []),
("حساء الجزر الأبيض والتفاح", "حساء دافئ لأيام الشتاء، يمكن تقديمه كوجبة خفيفة أو كمقبلات شهية في المناسبات.", "2", "376 غرام",
 ["1 ملعقة صغيرة زيت", "1 بصلة صغيرة مقطعة", "½ ملعقة صغيرة بذور كمون", "300 غرام جزر أبيض، مقشر ومقطع", "1 تفاحة صغيرة للطبخ، مقشرة ومقطعة", "600 مل مرق خضار", "فلفل أسود مطحون طازجًا", "1 جزرة بيضاء صغيرة", "2 ملعقة صغيرة زيت"],
 ["سخّن الزيت في قدر، وأضف البصل وبذور الكمون وقلّب على النار لمدة 2-3 دقائق.", "أضف الجزر الأبيض والتفاح واستمر في التقليب على النار لمدة 3 دقائق.", "أضف المرق واتركه حتى يغلي، ثم اتركه على نار هادئة لمدة 20-25 دقيقة حتى يصبح الجزر الأبيض طريًا.", "انقل الخليط إلى الخلاط أو محضّر الطعام واخلطه حتى يصبح ناعمًا. تبّل حسب الرغبة.", "لتحضير شرائح الجزر الأبيض المقرمشة، قشّر الجزرة البيضاء ثم قطّعها إلى شرائح رقيقة جدًا باستخدام مقشرة. سخّن الزيت في مقلاة صغيرة وقلِ شرائح الجزر الأبيض حتى تصبح مقرمشة وذهبية، ثم صفّها على ورق المطبخ.", "زيّن الحساء بشرائح الجزر الأبيض المقرمشة وقدّمه."],
 ["أضف نكهة أقوى إلى الحساء بإضافة 1 ملعقة صغيرة من معجون الكاري.", "تعليمات التجميد: جمّده في حصص ثم ذوّبه في الثلاجة، أو ذوّبه في الميكروويف مع التحريك بانتظام.", "حصص الفاكهة/الخضار لكل حصة: 4"], [])))
# 7427026
R.append((7427026,
("Filete de cordero con pilaf de lentejas especiado", "Cordero magro a la parrilla con pistou de hierbas, lentejas, frijoles y verduras.", "4", "324 g",
 ["250 g de filete de cuello de cordero", "1 cucharadita de orégano seco", "una buena cantidad de pimienta negra molida", "25 g de albahaca fresca, picada en trozos grandes", "50 g de perejil fresco, picado en trozos grandes", "2 dientes de ajo, machacados", "jugo y ralladura de medio limón", "1 cucharada de aceite de oliva extra virgen", "1 cucharada de agua", "2 cucharaditas de aceite de colza", "1 pimiento rojo, en cubos", "1 pimiento amarillo, en cubos", "1 calabacín, en cubos", "1 manojo de cebollines, picados", "1 lata de 400 g de lentejas verdes, escurridas y enjuagadas", "1 lata de 400 g de frijoles flageolet o cannellini, escurridos y enjuagados", "1 cucharadita de mostaza Dijon", "1 cubito de caldo de verduras bajo en sal disuelto en 150 ml de agua hirviendo"],
 ["Precaliente el horno a 190 °C (marca de gas 5). Ponga el cordero en una sartén antiadherente y cocínelo de 4 a 5 minutos, dándole vuelta con frecuencia para sellar el exterior.", "Prepare el pistou mezclando todos los ingredientes hasta formar una pasta, y resérvelo.", "Ponga el aceite de colza en una cacerola con los pimientos rojo y amarillo y el calabacín. Cocine de 5 a 6 minutos, revolviendo con frecuencia.", "Agregue los cebollines, las lentejas, los frijoles y la mostaza, y mezcle bien. Agregue el caldo, tape la cacerola, baje el fuego y cocine a fuego lento durante 10 minutos, revolviendo de vez en cuando.", "Mientras tanto, espolvoree el cordero con el orégano y la pimienta negra, colóquelo en una bandeja para hornear y hornee de 5 a 7 minutos si lo desea rosado, o de 10 a 12 minutos si lo desea bien cocido. Retírelo del horno y déjelo reposar durante 5 minutos antes de cortarlo en rebanadas finas.", "Sirva las lentejas en el plato, acomode encima las rebanadas de cordero y rocíe con el pistou."],
 ["Puede usar lomo de cerdo o pechuga de pollo en lugar del cordero, pero necesitará 10 minutos más en el horno. Verifique que la carne esté cocida por completo y que no se vea carne rosada antes de servir.", "Instrucciones para congelar: Se puede congelar una vez cocido. Para obtener mejores resultados, congele por separado el pilaf, el pistou y el cordero. Descongele en el refrigerador o en el microondas y recaliente el pilaf y el cordero hasta que estén muy calientes por completo.", "Porciones de fruta/verdura por ración: 3"], []),
("فيليه لحم الضأن مع بيلاف العدس المتبّل", "لحم ضأن قليل الدهن مشوي مع صلصة البيستو بالأعشاب والعدس والفاصوليا والخضار.", "4", "324 غرام",
 ["250 غرام فيليه رقبة ضأن", "1 ملعقة صغيرة أوريجانو مجفف", "رشة وفيرة من الفلفل الأسود المطحون", "25 غرام ريحان طازج، مفروم فرمًا خشنًا", "50 غرام بقدونس طازج، مفروم فرمًا خشنًا", "2 فص ثوم، مهروس", "عصير وبشر قشر نصف ليمونة", "1 ملعقة كبيرة زيت زيتون بكر ممتاز", "1 ملعقة كبيرة ماء", "2 ملعقة صغيرة زيت اللفت", "1 فلفل رومي أحمر، مقطع مكعبات", "1 فلفل رومي أصفر، مقطع مكعبات", "1 كوسا، مقطعة مكعبات", "1 حزمة بصل أخضر، مقطع", "1 علبة عدس أخضر 400 غرام، مصفاة ومشطوفة", "1 علبة فاصوليا فلاجوليه أو كانيليني 400 غرام، مصفاة ومشطوفة", "1 ملعقة صغيرة خردل ديجون", "1 مكعب مرق خضار قليل الملح مذاب في 150 مل ماء مغلي"],
 ["سخّن الفرن مسبقًا إلى 190° مئوية (علامة الغاز 5). ضع لحم الضأن في مقلاة غير لاصقة واطهه لمدة 4-5 دقائق، مع تقليبه باستمرار لإغلاق مسام سطحه.", "حضّر البيستو بخلط جميع المكونات معًا حتى تصبح عجينة، ثم ضعها جانبًا.", "ضع زيت اللفت في قدر مع الفلفل الرومي الأحمر والأصفر والكوسا. اطه لمدة 5-6 دقائق مع التحريك باستمرار.", "أضف البصل الأخضر والعدس والفاصوليا والخردل، ثم اخلط جيدًا. أضف المرق، وضع غطاء على القدر، وخفّض النار، واتركه على نار هادئة لمدة 10 دقائق مع التحريك من حين لآخر.", "في هذه الأثناء، رشّ لحم الضأن بالأوريجانو والفلفل الأسود، وضعه على صينية خبز واخبزه لمدة 5-7 دقائق إذا أردته وردي اللون، أو 10-12 دقيقة إذا أردته مطهوًا جيدًا. أخرجه من الفرن واتركه يرتاح لمدة 5 دقائق قبل تقطيعه إلى شرائح رقيقة.", "قدّم العدس في الأطباق، ورتّب شرائح لحم الضأن فوقه، ثم رشّ البيستو عليه."],
 ["يمكنك استخدام فيليه لحم الخنزير أو صدر الدجاج بدلًا من لحم الضأن، لكنه سيحتاج إلى 10 دقائق إضافية في الفرن. تأكد من أن اللحم قد نضج تمامًا وأنه لا يوجد لحم وردي ظاهر قبل التقديم.", "تعليمات التجميد: يمكن تجميده بعد الطهي. للحصول على أفضل النتائج، جمّد البيلاف والبيستو ولحم الضأن كلًا على حدة. ذوّبه في الثلاجة أو الميكروويف وأعد تسخين البيلاف ولحم الضأن حتى يصبحا ساخنين جدًا في كل جزء منهما.", "حصص الفاكهة/الخضار لكل حصة: 3"], [])))
# 7430012
R.append((7430012,
("Champiñones rellenos de frijoles de lima, perejil y tomillo", "Champiñones horneados con ajo, perejil y puré de frijoles, una versión renovada de un clásico favorito.", "18", "43 g",
 ["1 paquete de 500 g de champiñones (12–18, según el tamaño)", "1 cucharadita de aceite de colza", "4 dientes de ajo, machacados", "6 cebollines, finamente picados", "1 lata de 400 g de frijoles de lima, escurridos y hechos puré (235 g)", "15 g de perejil, finamente picado", "1 cucharadita de mostaza en grano entero", "1 cucharadita de tomillo seco", "una buena pizca de pimienta", "30 g de queso cheddar, finamente rallado"],
 ["Precaliente el horno a 180 °C (marca de gas 4). Gire y quite los tallos de los champiñones; píquelos y resérvelos. Coloque los champiñones boca arriba en una bandeja pequeña para hornear y hornee de 10 a 15 minutos.", "Mientras tanto, ponga el aceite en una sartén, agregue los tallos de los champiñones, el ajo y los cebollines y cocine durante 3 minutos.", "Pase la mezcla a un tazón con los frijoles, el perejil, la mostaza, el tomillo y la pimienta, y mezcle bien.", "Con una cuchara, rellene los sombreros de los champiñones, presionando la mezcla y dándole forma con las manos para crear un montículo. Espolvoree con el queso y hornee durante 15 minutos, hasta que estén ligeramente suaves y la parte superior esté dorada. Sirva tibios (deje enfriar un poco antes de servir) o a temperatura ambiente."],
 ["Puede agregar otras hierbas a la mezcla. Cualquier tipo de frijol funciona; pruebe con cannellini o con una lata de frijoles variados.", "Puede rellenar los champiñones hasta con 1 día de anticipación y mantenerlos en el refrigerador hasta el momento de hornear.", "Porciones de fruta/verdura por ración: 0"], []),
("فطر محشو بالفاصوليا البيضاء والبقدونس والزعتر", "فطر مخبوز مع الثوم والبقدونس وهريس الفاصوليا، وصفة جديدة لطبق مفضّل قديم.", "18", "43 غرام",
 ["1 عبوة فطر 500 غرام (12-18 حبة حسب الحجم)", "1 ملعقة صغيرة زيت اللفت", "4 فص ثوم، مهروس", "6 حبات بصل أخضر، مفرومة ناعمًا", "1 علبة فاصوليا بيضاء كبيرة 400 غرام، مصفاة ومهروسة (235 غرام)", "15 غرام بقدونس، مفروم ناعمًا", "1 ملعقة صغيرة خردل بالحبوب الكاملة", "1 ملعقة صغيرة زعتر مجفف", "رشة وفيرة من الفلفل", "30 غرام جبن شيدر، مبشور ناعمًا"],
 ["سخّن الفرن إلى 180° مئوية (علامة الغاز 4). أدِر سيقان الفطر وانزعها، ثم قطّعها واحتفظ بها جانبًا. ضع الفطر بوضع قائم على صينية خبز صغيرة واخبزه لمدة 10-15 دقيقة.", "في هذه الأثناء، ضع الزيت في مقلاة، وأضف سيقان الفطر والثوم والبصل الأخضر واطهها لمدة 3 دقائق.", "انقل الخليط إلى وعاء مع الفاصوليا والبقدونس والخردل والزعتر والفلفل، واخلط جيدًا.", "احشُ رؤوس الفطر بالملعقة، مع الضغط على الحشوة داخل الفطر وتشكيلها بيديك لتكوين كومة صغيرة. رشّ الجبن واخبزها لمدة 15 دقيقة حتى تلين قليلًا وتصبح وجوهها ذهبية. قدّمها دافئة (اتركها تبرد قليلًا قبل التقديم) أو على درجة حرارة الغرفة."],
 ["يمكنك إضافة أعشاب أخرى إلى الخليط. يناسب أي نوع من الفاصوليا، جرّب الكانيليني أو علبة فاصوليا مشكّلة.", "يمكنك حشو الفطر قبل 1 يوم كحد أقصى، ثم حفظه في الثلاجة حتى موعد الخبز.", "حصص الفاكهة/الخضار لكل حصة: 0"], [])))
# 7432104
R.append((7432104,
("Pollo estilo pizza", "Una deliciosa cena de inspiración italiana que combina pechuga de pollo jugosa con el sabor de una pizza con queso. Esta receta fue seleccionada en colaboración con Slimming World.", "1", "398 g",
 ["½ cebolla morada pequeña, finamente picada", "½ pimiento rojo, sin semillas y picado", "1 diente de ajo pequeño, machacado", "Aceite en aerosol bajo en calorías", "2 tomates de rama, picados", "1 cucharada de tomate picado en lata", "1 cucharadita de puré de tomate", "1 cucharadita de orégano seco", "1 pechuga de pollo sin piel y sin hueso", "40 g de queso cheddar reducido en grasa, rallado", "1 tomate cherry, cortado por la mitad", "1 cucharadita de albahaca fresca finamente picada"],
 ["Ponga la cebolla, el pimiento y el ajo en una cacerola pequeña antiadherente. Rocíe con un par de disparos de aceite en aerosol bajo en calorías y cocine unos minutos hasta que se ablanden. Agregue los tomates frescos, el tomate en lata, el puré de tomate y el orégano, y cocine a fuego lento durante 5 minutos. Reserve.", "Precaliente el horno a 220 °C (200 °C con ventilador, marca de gas 7).", "Corte la pechuga de pollo por la mitad a lo largo, con cuidado de no cortarla por completo. Ábrala como si fuera una mariposa.", "Rocíe una sartén antiadherente con un par de disparos de aceite en aerosol bajo en calorías y colóquela a fuego medio. Agregue el pollo y cocine hasta que se dore por ambos lados. Pase el pollo a una bandeja antiadherente para hornear y hornee de 15 a 20 minutos, o hasta que esté bien cocido y no se vea carne rosada (los jugos deben salir claros al insertar una brocheta en la parte más gruesa del pollo).", "Saque el pollo del horno y extienda encima la mezcla de tomate. Espolvoree el queso y ponga encima el tomate cherry. Cocine 5 minutos más, hasta que el queso se derrita.", "Espolvoree con la albahaca y sirva caliente con papas en gajos caseras horneadas con cáscara y una ensalada verde grande y crujiente."],
 [], []),
("دجاج بنكهة البيتزا", "عشاء شهي بوحي إيطالي يجمع بين صدر الدجاج الطري ونكهة البيتزا بالجبن. تم اختيار هذه الوصفة بالتعاون مع Slimming World.", "1", "398 غرام",
 ["½ بصلة حمراء صغيرة، مفرومة ناعمًا", "½ فلفل رومي أحمر، منزوع البذور ومقطع", "1 فص ثوم صغير، مهروس", "بخاخ طهي قليل السعرات", "2 حبة طماطم عنقودية، مقطعة", "1 ملعقة كبيرة طماطم معلبة مقطعة", "1 ملعقة صغيرة معجون طماطم", "1 ملعقة صغيرة أوريجانو مجفف", "1 صدر دجاج بدون جلد وبدون عظم", "40 غرام جبن شيدر قليل الدسم، مبشور", "1 حبة طماطم كرزية، مقطوعة إلى نصفين", "1 ملعقة صغيرة ريحان طازج مفروم ناعمًا"],
 ["ضع البصل والفلفل والثوم في قدر صغير غير لاصق. رشّ عليها بخاخ الطهي قليل السعرات بضغطتين تقريبًا واطهها لبضع دقائق حتى تلين. أضف الطماطم الطازجة والطماطم المعلبة ومعجون الطماطم والأوريجانو واتركها على نار هادئة لمدة 5 دقائق. ضعها جانبًا.", "سخّن الفرن مسبقًا إلى 220° مئوية (200° مئوية للفرن بمروحة، علامة الغاز 7).", "اشطر صدر الدجاج إلى نصفين بالعرض، مع الحرص على ألا تقطعه بالكامل. افتحه ليأخذ شكل الفراشة.", "رشّ مقلاة غير لاصقة ببخاخ الطهي قليل السعرات بضغطتين تقريبًا وضعها على نار متوسطة. أضف الدجاج واطهه حتى يحمرّ من الجهتين. انقل الدجاج إلى صينية خبز غير لاصقة واخبزه لمدة 15-20 دقيقة أو حتى ينضج تمامًا ولا يظهر لحم وردي (يجب أن يخرج العصير صافيًا عند غرس سيخ في أسمك جزء من الدجاج).", "أخرج الدجاج من الفرن وافرد خليط الطماطم فوقه. رشّ الجبن وضع حبة الطماطم الكرزية في الأعلى. اطهه لمدة 5 دقائق أخرى حتى يذوب الجبن.", "رشّ الريحان وقدّمه ساخنًا مع أصابع البطاطس المنزلية المخبوزة في الفرن بقشرها، وطبق كبير من السلطة الخضراء المقرمشة."],
 [], [])))
# 7432936
R.append((7432936,
("Panqueques de pimiento dulce con relish de tomate picante", "Los pimientos dulces y la cebolla hacen unos panqueques sencillamente deliciosos, que saben aún mejor con este relish fresco y picante.", "30", "44 g",
 ["2 cucharaditas de aceite de colza", "1 pimiento amarillo, en tiras finas de 2 a 3 cm de largo", "1 pimiento rojo, en tiras finas de 2 a 3 cm de largo", "1 cebolla, finamente picada", "2 huevos, batidos", "200 ml de agua", "2 cucharadas de yogur bajo en grasa", "50 g de queso cheddar rallado", "150 g de harina integral", "una buena pizca de pimienta", "10 g de perejil fresco", "jugo y ralladura de 1 limón verde", "4 tomates de rama grandes, finamente picados", "1 a 2 chiles rojos pequeños, finamente picados"],
 ["Ponga 1 cucharadita de aceite en una sartén a fuego medio, agregue los pimientos y la cebolla y cocine durante 10 minutos, revolviendo con frecuencia.", "Mientras tanto, mezcle los huevos, el agua, el yogur y el queso. Incorpore la harina para hacer una masa líquida.", "Incorpore los pimientos y la cebolla a la masa.", "Ponga el aceite restante en una sartén grande antiadherente. Agregue cucharadas colmadas de postre de la mezcla a la sartén y fría de 1 a 2 minutos, volteándolas una vez con una espátula para cocinar el otro lado 1 minuto más.", "Mientras tanto, prepare la salsa licuando el perejil, el jugo y la ralladura del limón verde y los tomates frescos; luego incorpore el chile."],
 ["Al cocinar los panqueques, asegúrese de distribuir los pimientos y la cebolla de manera uniforme en la mezcla. Puede prepararlos hasta con 1 día de anticipación y calentarlos en el horno unos minutos antes de servir.", "Porciones de fruta/verdura por ración: 0"], []),
("فطائر الفلفل الحلو مع صلصة الطماطم الحامضة", "الفلفل الحلو والبصل يصنعان فطائر لذيذة ببساطة، وطعمها أفضل مع هذه الصلصة الطازجة الحادة.", "30", "44 غرام",
 ["2 ملعقة صغيرة زيت اللفت", "1 فلفل رومي أصفر، مقطع شرائح رفيعة بطول 2-3 سم", "1 فلفل رومي أحمر، مقطع شرائح رفيعة بطول 2-3 سم", "1 بصلة، مفرومة ناعمًا", "2 بيضة، مخفوقة", "200 مل ماء", "2 ملعقة كبيرة زبادي قليل الدسم", "50 غرام جبن شيدر مبشور", "150 غرام دقيق قمح كامل", "رشة وفيرة من الفلفل", "10 غرام بقدونس طازج", "عصير وبشر قشر 1 ليمونة خضراء", "4 حبات طماطم عنقودية كبيرة، مفرومة ناعمًا", "1-2 فلفل حار أحمر صغير، مفروم ناعمًا"],
 ["ضع 1 ملعقة صغيرة من الزيت في مقلاة على نار متوسطة، وأضف الفلفل والبصل واطهها لمدة 10 دقائق مع التحريك باستمرار.", "في هذه الأثناء، اخلط البيض والماء والزبادي والجبن معًا. أضف الدقيق مع التحريك لتحصل على عجينة سائلة.", "أضف الفلفل والبصل إلى العجينة السائلة وحرّك.", "ضع الزيت المتبقي في مقلاة كبيرة غير لاصقة. ضع في المقلاة ملاعق حلوى ممتلئة قليلًا من الخليط لتقليها لمدة 1-2 دقيقة، مع قلبها مرة واحدة بالملعقة المسطحة لتنضج الجهة الأخرى دقيقة إضافية.", "في هذه الأثناء، حضّر الصلصة بخلط البقدونس وعصير الليمون الأخضر وقشره والطماطم الطازجة في الخلاط، ثم أضف الفلفل الحار وحرّك."],
 ["عند طهي الفطائر، احرص على توزيع الفلفل والبصل بالتساوي في الخليط. يمكنك تحضيرها قبل 1 يوم كحد أقصى وتسخينها في الفرن لبضع دقائق قبل التقديم.", "حصص الفاكهة/الخضار لكل حصة: 0"], [])))
# 7434527
R.append((7434527,
("Ensalada niçoise de atún", "Una receta clásica francesa que es una excelente opción de almuerzo saludable para un día soleado.", "4", "275 g",
 ["450 g de papas nuevas, cortadas por la mitad (las más grandes en cuartos)", "200 g de ejotes finos, sin las puntas", "1 lechuga redonda pequeña, con las hojas separadas", "2 latas de 160 g de atún en agua, escurrido y desmenuzado", "8 aceitunas Kalamata, sin hueso y cortadas por la mitad", "1 cucharadita de mostaza Dijon", "5 cucharaditas de vinagre de sidra", "1 cucharada de aceite de oliva extra virgen", "½ cucharadita de mostaza en polvo inglesa", "½ diente de ajo pequeño, machacado", "¼ de cucharadita de hierbas de Provenza"],
 ["Ponga las papas en una olla grande, cúbralas con agua fría y déjelas hervir. Baje el fuego a medio y cocine durante 5 minutos. Agregue los ejotes y cocine 4 minutos, hasta que las papas estén tiernas y los ejotes estén cocidos pero aún firmes. Escurra y pase a un tazón grande.", "Mientras tanto, ponga todos los ingredientes del aderezo en un frasco limpio. Cierre con una tapa bien ajustada y agite hasta que se mezclen. Rocíe la mitad del aderezo sobre las papas y los ejotes y mezcle para integrar. Agregue la lechuga al tazón y mezcle de nuevo para cubrirla.", "Acomode la ensalada aderezada en una fuente o en una ensaladera grande, y cubra con el atún, las alcaparras y las aceitunas. Rocíe el aderezo restante y sirva."],
 ["Si no tiene atún, puede sustituirlo por cualquier tipo de pescado en lata.", "Puede sustituir las hierbas de Provenza por cualquier hierba seca.", "También puede usar camotes en lugar de papas nuevas."], []),
("سلطة التونة النيسواز", "وصفة فرنسية كلاسيكية تصلح غداءً صحيًا رائعًا في يوم مشمس.", "4", "275 غرام",
 ["450 غرام بطاطس صغيرة جديدة، مقطوعة إلى نصفين أو أرباع للحبات الأكبر", "200 غرام فاصوليا خضراء رفيعة، منزوعة الأطراف", "1 خسة مستديرة صغيرة، أوراقها مفصولة", "2 علبة تونة 160 غرام في ماء الينابيع، مصفاة ومفتتة", "8 حبات زيتون كالاماتا، منزوعة النوى ومقطوعة إلى نصفين", "1 ملعقة صغيرة خردل ديجون", "5 ملاعق صغيرة خل التفاح", "1 ملعقة كبيرة زيت زيتون بكر ممتاز", "½ ملعقة صغيرة مسحوق الخردل الإنجليزي", "½ فص ثوم صغير، مهروس", "¼ ملعقة صغيرة أعشاب بروفانس"],
 ["ضع البطاطس في قدر كبير، وغطّها بالماء البارد واتركها حتى تغلي. خفّض النار إلى متوسطة واطهها لمدة 5 دقائق. أضف الفاصوليا واطهها لمدة 4 دقائق حتى تنضج البطاطس وتنضج الفاصوليا مع بقائها متماسكة. صفّها وانقلها إلى وعاء كبير.", "في هذه الأثناء، ضع جميع مكونات التتبيلة في برطمان نظيف. أغلقه بغطاء محكم ورجّه حتى تمتزج المكونات. رشّ نصف التتبيلة على البطاطس والفاصوليا وقلّب حتى تتغطى. أضف الخس إلى الوعاء وقلّب مرة أخرى ليتغطى.", "رتّب السلطة المتبلة في طبق تقديم أو في وعاء سلطة كبير، ثم زيّنها بالتونة والكبر والزيتون. رشّ التتبيلة المتبقية وقدّمها."],
 ["إذا لم يتوفر لديك التونة، يمكنك استبدالها بأي نوع من الأسماك المعلبة.", "يمكنك استبدال أعشاب بروفانس بأي أعشاب مجففة.", "يمكنك أيضًا استخدام البطاطا الحلوة بدلًا من البطاطس الجديدة."], [])))
# 7439314
R.append((7439314,
("Batido de durazno y frambuesa", "Un batido de frutas es un acompañamiento ideal para el desayuno o el almuerzo. A los niños también les encanta.", "2", "288 g",
 ["1 lata de 213 g de duraznos en jugo, escurridos", "150 g de frambuesas frescas o congeladas", "1 envase de 150 g de yogur natural", "150 ml de leche semidescremada"],
 ["Licúe todos los ingredientes y sirva."],
 ["Para una versión sin lácteos, use leche de soya y un yogur de soya como alternativa.", "En un día de mucho calor, agregue de 8 a 10 cubos de hielo antes de licuar para obtener un granizado de frutas.", "Porciones de fruta/verdura por ración: 1"], []),
("سموذي الخوخ والتوت الأحمر", "سموذي الفاكهة مرافق مثالي للفطور أو الغداء. ويحبه الأطفال أيضًا.", "2", "288 غرام",
 ["1 علبة خوخ 213 غرام في عصيره، مصفاة", "150 غرام توت العليق الأحمر طازج أو مجمد", "1 علبة زبادي سادة 150 غرام", "150 مل حليب نصف منزوع الدسم"],
 ["اخلط جميع المكونات معًا في الخلاط وقدّمه."],
 ["للحصول على نسخة خالية من الألبان، استخدم حليب الصويا وبديل زبادي من الصويا.", "في يوم شديد الحرارة، أضف 8-10 مكعبات ثلج قبل الخلط للحصول على مشروب فواكه مثلّج.", "حصص الفاكهة/الخضار لكل حصة: 1"], [])))
# 7441520
R.append((7441520,
("Frituras de espinaca, maíz y garbanzo", "Un plato perfecto para la cena. Queda muy bien en pan pita con mucha ensalada.", "4", "164 g",
 ["2 cucharaditas de aceite de colza", "1 cebolla pequeña, rallada", "1 pimiento rojo, finamente picado", "1 huevo, batido", "150 g de espinaca congelada, descongelada, sin agua y picada en trozos grandes", "1 cucharadita de comino", "1 chile rojo, finamente picado", "80 g de maíz congelado, descongelado", "1 lata de 400 g de garbanzos, escurridos y bien machacados", "25 g de harina de garbanzo", "10 g de cilantro fresco, picado", "ensalada, para acompañar"],
 ["Ponga 1 cucharadita de aceite en una cacerola y agregue la cebolla. Cocine de 2 a 3 minutos, luego agregue el pimiento rojo y fría de 4 a 5 minutos más.", "Mientras tanto, ponga el huevo, la espinaca, el comino, el chile y el maíz dulce en un tazón y mezcle bien.", "Incorpore la cebolla y el pimiento rojo, luego agregue los garbanzos, la harina de garbanzo y el cilantro, y mezcle muy bien. Con las manos húmedas, forme 8 tortitas con la mezcla.", "Ponga el aceite restante en una sartén antiadherente grande a fuego medio. Coloque las frituras en la sartén y aplánelas ligeramente con una espátula hasta que tengan un grosor de ½ a 1 cm, para que se cocinen de manera uniforme.", "Cocine las frituras de 3 a 4 minutos, hasta que se doren ligeramente; luego voltéelas con cuidado y cocine el otro lado otros 3 a 4 minutos. Si lo desea, deje cocinar cada lado de 1 a 2 minutos más para que se forme una costra dorada. Sirva con ensalada."],
 ["La información nutricional anterior no incluye la ensalada ni el pan pita como sugerencia de presentación.", "Si no tiene una sartén lo suficientemente grande, puede cocinar las frituras en dos tandas. Colóquelas en un plato caliente y resérvelas hasta que estén todas listas.", "Puede servir las frituras tibias o frías.", "Si no tiene harina de garbanzo, puede usar harina de trigo común o integral.", "Instrucciones para congelar: Congele en porciones envueltas individualmente, con papel encerado entre cada fritura. Descongele por completo y recaliente hasta que estén muy calientes por completo.", "Porciones de fruta/verdura por ración: 2"], []),
("كعكات السبانخ والذرة والحمص", "طبق مثالي للعشاء. يناسب تقديمه في خبز البيتا مع الكثير من السلطة.", "4", "164 غرام",
 ["2 ملعقة صغيرة زيت اللفت", "1 بصلة صغيرة، مبشورة", "1 فلفل رومي أحمر، مفروم ناعمًا", "1 بيضة، مخفوقة", "150 غرام سبانخ مجمدة، مذوّبة ومعصورة من الماء ومفرومة فرمًا خشنًا", "1 ملعقة صغيرة كمون", "1 فلفل حار أحمر، مفروم ناعمًا", "80 غرام ذرة مجمدة، مذوّبة", "1 علبة حمص 400 غرام، مصفاة ومهروسة جيدًا", "25 غرام دقيق الحمص", "10 غرام كزبرة خضراء طازجة، مفرومة", "سلطة، للتقديم"],
 ["ضع 1 ملعقة صغيرة من الزيت في قدر، ثم أضف البصل. اطهه لمدة 2-3 دقائق، ثم أضف الفلفل الرومي الأحمر وقلّبه على النار لمدة 4-5 دقائق أخرى.", "في هذه الأثناء، ضع البيض والسبانخ والكمون والفلفل الحار والذرة في وعاء واخلط جيدًا.", "أضف البصل والفلفل الرومي الأحمر وحرّك، ثم أضف الحمص ودقيق الحمص والكزبرة واخلط جيدًا. بيدين مبللتين، شكّل الخليط إلى 8 أقراص.", "ضع الزيت المتبقي في مقلاة كبيرة غير لاصقة على نار متوسطة. ضع الكعكات في المقلاة واضغط عليها قليلًا بالملعقة المسطحة حتى يصبح سمكها ½-1 سم، لضمان نضجها بالتساوي.", "اطه الكعكات حتى يصبح لونها بنيًا فاتحًا لمدة 3-4 دقائق، ثم اقلبها بحرص واطه الجهة الأخرى لمدة 3-4 دقائق أخرى. وقد ترغب في ترك كل جهة 1-2 دقيقة إضافية للحصول على قشرة جميلة. قدّمها مع السلطة."],
 ["لا تشمل المعلومات الغذائية أعلاه السلطة أو خبز البيتا المقترح للتقديم.", "إذا لم يكن لديك مقلاة كبيرة بما يكفي، يمكنك طهي الكعكات على دفعتين. ضعها على طبق دافئ وأبقها جانبًا حتى تنتهي جميعها.", "يمكنك تقديم الكعكات دافئة أو باردة.", "إذا لم يتوفر لديك دقيق الحمص، يمكنك استخدام دقيق القمح العادي أو الكامل بدلًا منه.", "تعليمات التجميد: جمّدها في حصص ملفوفة بشكل فردي مع وضع ورق الزبدة بين كل كعكة وأخرى. ذوّبها جيدًا وأعد تسخينها حتى تصبح ساخنة جدًا في كل جزء منها.", "حصص الفاكهة/الخضار لكل حصة: 2"], [])))
# 7446273
R.append((7446273,
("Tartaletas pequeñas de cangrejo", "Estos sabrosos bocados son ideales como aperitivo para acompañar bebidas.", "36", "12 g",
 ["36 canastillas pequeñas de masa (mini croustades)", "1 huevo, batido", "4 cucharadas de crème fraîche semidescremada", "1 cucharada de cebollín fresco, cortado en trocitos", "una pizca de pimentón dulce", "1 cucharada de queso parmesano finamente rallado", "225 g de carne de cangrejo blanca fresca", "pimienta negra recién molida"],
 ["Precaliente el horno a 200 °C (marca de gas 6).", "Coloque las canastillas de masa en una bandeja para hornear. Bata juntos todos los demás ingredientes y use la mezcla para rellenar las canastillas.", "Hornee durante unos 15 minutos, hasta que el relleno esté apenas cuajado y comience a dorarse. Deje enfriar un poco y sirva."],
 ["Es mejor comerlas (o congelarlas) el mismo día para que la masa no se ablande.", "Para una opción vegetariana, sustituya el cangrejo por el mismo peso de cebollas o champiñones salteados en rebanadas finas.", "Si no encuentra canastillas de masa de un bocado, forre moldes pequeños para tartaletas con masa quebrada o masa filo extendida muy delgada (200 g).", "Porciones de fruta/verdura por ración: 0"], []),
("فطائر السلطعون الصغيرة", "هذه اللقيمات اللذيذة رائعة كمقبلات مع المشروبات.", "36", "12 غرام",
 ["36 قالب عجين صغير (كروستاد صغيرة)", "1 بيضة، مخفوقة", "4 ملاعق كبيرة كريمة فريش نصف دسمة", "1 ملعقة كبيرة ثوم معمر (شيفز) طازج، مقطع قطعًا صغيرة", "رشة بابريكا", "1 ملعقة كبيرة جبن بارميزان مبشور ناعمًا", "225 غرام لحم سلطعون أبيض طازج", "فلفل أسود مطحون طازجًا"],
 ["سخّن الفرن مسبقًا إلى 200° مئوية (علامة الغاز 6).", "ضع قوالب العجين على صينية خبز. اخفق جميع المكونات المتبقية معًا واستخدمها لحشو القوالب.", "اخبزها لمدة 15 دقيقة تقريبًا حتى تتماسك الحشوة وتبدأ في التحمير. اتركها تبرد قليلًا وقدّمها."],
 ["الأفضل تناولها (أو تجميدها) في اليوم نفسه حتى لا تصبح العجينة طرية.", "للحصول على خيار نباتي، استبدل السلطعون بالوزن نفسه من البصل أو الفطر المقطع شرائح رقيقة والمقلي قليلًا.", "إذا لم تجد قوالب عجين بحجم اللقمة، فبطّن قوالب فطائر صغيرة بعجينة بريزيه أو فيلو مفرودة بسمك رقيق جدًا (200 غرام).", "حصص الفاكهة/الخضار لكل حصة: 0"], [])))
# 7446938
R.append((7446938,
("Paletas cremosas de arándano azul y aguacate", "Estas deliciosas paletas cremosas se preparan con un batido espeso que se congela. Puede variarlas agregando su fruta o bayas favoritas.", "10", "78 g",
 ["2 aguacates pequeños (200 g), sin hueso y con la pulpa extraída", "200 g de arándanos azules congelados", "10 dátiles blandos, sin hueso", "250 ml de leche descremada (o la leche de su elección)", "2 cucharadas de jugo de limón verde"],
 ["Ponga todos los ingredientes en una licuadora y mezcle hasta que quede completamente suave.", "Reparta el batido en 10 moldes para paletas. Tape con la tapa, inserte los palitos y colóquelos en el congelador durante 8 horas, o hasta que estén congeladas.", "Disfrútelas de inmediato o guárdelas en el congelador para comerlas después."],
 ["Si desea agregar aún más valor nutricional a estas golosinas, añada dos ramilletes de coliflor congelada y cocida al vapor a la mezcla antes de licuar.", "Porciones de fruta/verdura por ración: 0"], []),
("مصاصات مثلجة كريمية بالتوت الأزرق والأفوكادو", "تُصنع هذه المثلجات الكريمية اللذيذة من سموذي كثيف يتم تجميده. يمكنك تنويعها بإضافة فاكهتك أو توتك المفضل.", "10", "78 غرام",
 ["2 حبة أفوكادو صغيرة (200 غرام)، منزوعة النوى ولبها مغروف", "200 غرام توت أزرق مجمد", "10 حبات تمر طري، منزوعة النوى", "250 مل حليب خالي الدسم (أو الحليب الذي تفضله)", "2 ملعقة كبيرة عصير ليمون أخضر"],
 ["ضع جميع المكونات في الخلاط واخلطها حتى تصبح ناعمة تمامًا.", "وزّع السموذي على 10 قوالب مصاصات مثلجة. غطِّها بالغطاء وأدخل أعواد المصاصات وانقلها إلى المجمد لمدة 8 ساعات أو حتى تتجمد.", "استمتع بها فورًا أو احفظها في المجمد لتناولها لاحقًا."],
 ["إذا أردت إضافة المزيد من القيمة الغذائية إلى هذه الحلوى، فأضف زهرتين من القرنبيط المجمد المطهو على البخار إلى الخليط قبل الخلط.", "حصص الفاكهة/الخضار لكل حصة: 0"], [])))
# 7447100
R.append((7447100,
("Verduras asadas ahumadas con yogur de sésamo", "Aproveche las verduras sobrantes para preparar este plato de inspiración del Medio Oriente, que seguramente deleitará su paladar.", "3", "324 g",
 ["1 zanahoria, en trozos", "200 g de alcachofas de Jerusalén, en trozos", "1 camote, en trozos", "2 cebollas moradas, en cuartos", "2 pimientos, rojo y verde, en cuartos", "1 cucharada de aceite de oliva", "2 cucharaditas colmadas de pimentón ahumado suave (dulce)", "2 cucharaditas de tahini", "4 cucharadas de yogur griego sin grasa (0 %)"],
 ["Ponga la zanahoria, las alcachofas, el camote, las cebollas y los pimientos en un tazón grande con el aceite y mezcle bien.", "Agregue el pimentón y mezcle de nuevo para que todas las verduras queden cubiertas.", "Extienda sobre una bandeja para hornear ligeramente engrasada y hornee en un horno precalentado a 180 °C (marca de gas 4) de 35 a 45 minutos, volteando de vez en cuando.", "Mientras tanto, mezcle el tahini con el yogur y resérvelo hasta que las verduras estén listas."],
 ["Use una alternativa vegetal al yogur para que este plato sea vegano.", "Sirva con garbanzos y pan pita integral o arroz para convertirlo en una comida completa.", "Porciones de fruta/verdura por ración: 2"], []),
("خضار مشوية بنكهة مدخنة مع زبادي السمسم", "استخدم الخضار المتبقية لتحضير هذا الطبق المستوحى من الشرق الأوسط، وسيرضي حتمًا ذوقك.", "3", "324 غرام",
 ["1 جزرة، مقطعة قطعًا كبيرة", "200 غرام خرشوف القدس، مقطع قطعًا كبيرة", "1 حبة بطاطا حلوة، مقطعة قطعًا كبيرة", "2 بصلة حمراء، مقطعة أرباعًا", "2 فلفل رومي، أحمر وأخضر، مقطع أرباعًا", "1 ملعقة كبيرة زيت زيتون", "2 ملعقة صغيرة مكدسة بابريكا مدخنة معتدلة (حلوة)", "2 ملعقة صغيرة طحينة", "4 ملاعق كبيرة زبادي يوناني خالٍ من الدسم 0%"],
 ["ضع الجزر وخرشوف القدس والبطاطا الحلوة والبصل والفلفل الرومي في وعاء كبير مع الزيت واخلط جيدًا.", "أضف البابريكا واخلط مرة أخرى لتتغطى جميع الخضار.", "افردها على صينية خبز مدهونة بقليل من الزيت واخبزها في فرن مسخّن مسبقًا على 180° مئوية (علامة الغاز 4) لمدة 35-45 دقيقة مع تقليبها من حين لآخر.", "في هذه الأثناء، اخلط الطحينة مع الزبادي واحتفظ بها حتى تنضج الخضار."],
 ["استخدم بديل زبادي نباتيًا لجعل هذا الطبق نباتيًا خالصًا.", "قدّمه مع الحمص وخبز البيتا بالقمح الكامل أو الأرز ليصبح وجبة كاملة.", "حصص الفاكهة/الخضار لكل حصة: 2"], [])))
# 7449009
R.append((7449009,
("Tajín de verduras y garbanzos", "Este sabroso plato bajo en grasa está lleno de sabores del norte de África.", "4", "339 g",
 ["1 cucharada de aceite", "2 dientes de ajo, machacados", "un cuarto de cucharadita de comino molido", "un cuarto de cucharadita de jengibre molido", "media cucharadita de chile en polvo", "450 g de verduras variadas cortadas en trozos pequeños: un calabacín grande, dos zanahorias medianas y una berenjena mediana", "100 ml de caldo de verduras bajo en sal", "1 lata de 400 g de garbanzos, escurridos y enjuagados", "100 g (aprox. 12) de orejones de albaricoque", "1 lata de 400 g de tomates picados", "1 cucharadita de pasta de harissa", "2 cucharadas de cilantro fresco, picado, para decorar", "pimienta negra recién molida"],
 ["Caliente el aceite en una sartén antiadherente. Agregue el ajo, el comino, el jengibre y el chile en polvo, y fría durante 2 minutos hasta que las especias desprendan su aroma.", "Agregue las verduras a la sartén y continúe friendo de 2 a 3 minutos.", "Vierta el caldo y agregue los garbanzos, los orejones y los tomates; deje que hierva y cocine a fuego lento de 10 a 12 minutos, hasta que las verduras estén apenas tiernas.", "Incorpore la pasta de harissa y sazone con abundante pimienta negra.", "Sirva las verduras sobre cuscús recién preparado, espolvoree con cilantro y sirva."],
 ["Sirva con cuscús, arroz o pan plano y abundante ensalada.", "Si no tiene pasta de harissa, puede usar un poco más de chile y/o ajo, junto con media cucharadita de menta seca y un buen chorrito de limón.", "En lugar de orejones de albaricoque, puede usar pasas.", "Instrucciones para congelar: Se puede congelar una vez cocido. Descongele en el refrigerador o en el microondas y recaliente bien hasta que esté muy caliente por completo.", "Porciones de fruta/verdura por ración: 4"], []),
("طاجن الخضار والحمص", "هذا الطبق اللذيذ قليل الدسم مليء بنكهات شمال أفريقيا.", "4", "339 غرام",
 ["1 ملعقة كبيرة زيت", "2 فص ثوم، مهروس", "¼ ملعقة صغيرة كمون مطحون", "¼ ملعقة صغيرة زنجبيل مطحون", "½ ملعقة صغيرة مسحوق الفلفل الحار", "450 غرام خضار مشكّلة مقطعة قطعًا بحجم اللقمة: كوسا كبيرة واحدة، وجزرتان متوسطتان، وباذنجانة متوسطة واحدة", "100 مل مرق خضار قليل الملح", "1 علبة حمص 400 غرام، مصفاة ومشطوفة", "100 غرام (حوالي 12 حبة) مشمش مجفف", "1 علبة طماطم مقطعة 400 غرام", "1 ملعقة صغيرة معجون هريسة", "2 ملعقة كبيرة كزبرة خضراء طازجة، مفرومة، للتزيين", "فلفل أسود مطحون طازجًا"],
 ["سخّن الزيت في مقلاة غير لاصقة. أضف الثوم والكمون والزنجبيل ومسحوق الفلفل الحار وقلّبها لمدة 2 دقيقة حتى تفوح رائحة التوابل.", "أضف الخضار إلى المقلاة واستمر في التقليب لمدة 2-3 دقائق.", "اسكب المرق وأضف الحمص والمشمش والطماطم، واتركه حتى يغلي ثم اتركه على نار هادئة لمدة 10-12 دقيقة حتى تنضج الخضار قليلًا.", "أضف معجون الهريسة وتبّل بكمية وفيرة من الفلفل الأسود.", "قدّم الخضار فوق كسكس محضّر طازجًا، ورشّ الكزبرة الخضراء وقدّمه."],
 ["قدّمه مع الكسكس أو الأرز أو الخبز المسطح والكثير من السلطة.", "إذا لم يتوفر لديك معجون الهريسة، يمكنك استخدام كمية أكبر قليلًا من الفلفل الحار و/أو الثوم مع ½ ملعقة صغيرة نعناع مجفف وعصرة ليمون وفيرة.", "بدلًا من المشمش، يمكنك استخدام الزبيب.", "تعليمات التجميد: يمكن تجميده بعد الطهي. ذوّبه في الثلاجة أو الميكروويف وأعد تسخينه جيدًا حتى يصبح ساخنًا جدًا في كل جزء منه.", "حصص الفاكهة/الخضار لكل حصة: 4"], [])))
build(1, R)
