from h import *
R=[]
R.append(build(6228270,
es=L("Papas fritas de nabo al horno","¿Le encantan las papas fritas frescas? ¡Pruebe esta alternativa baja en carbohidratos: papas fritas de nabo al horno! Al hornear los nabos quedan perfectamente crujientes, para un acompañamiento ideal para personas con diabetes.","6","1/2 taza",
["4 nabos medianos (pelados y cortados en bastones o gajos)","2 cucharadas de aceite de oliva","1 cucharadita de ajo en polvo","1 cucharadita de cebolla en polvo","1/2 cucharadita de pimentón ahumado","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Precaliente el horno a 425 grados F. Forre una bandeja para hornear con papel pergamino.","En un tazón grande, mezcle los bastones o gajos de nabo con el aceite de oliva hasta que queden bien cubiertos.","Extienda los nabos en una sola capa sobre la bandeja para hornear.","Espolvoree el ajo en polvo, la cebolla en polvo, el pimentón ahumado, la sal y la pimienta negra sobre los nabos. Mezcle para cubrirlos de manera uniforme.","Hornee en el horno precalentado de 20 a 25 minutos, o hasta que las papas fritas de nabo estén doradas y crujientes, volteándolas a la mitad del tiempo.","Retire del horno y deje enfriar unos minutos antes de servir."],[],[]),
ar=L("بطاطس مقلية من اللفت المخبوز","هل تحب البطاطس المقلية الطازجة؟ جرّب هذا البديل الأقل في الكربوهيدرات: أصابع اللفت المخبوزة! بخبز اللفت تصبح مقرمشة تمامًا لتكون طبق جانبي مناسبًا لمرضى السكري.","6","½ كوب",
["4 حبات لفت متوسطة (مقشرة ومقطعة إلى أصابع أو أرباع)","2 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة مسحوق الثوم","1 ملعقة صغيرة مسحوق البصل","½ ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية). بطّن صينية الخبز بورق زبدة.","في وعاء كبير، اخلط أصابع أو أرباع اللفت مع زيت الزيتون حتى تُغطى جيدًا.","وزّع اللفت في طبقة واحدة على صينية الخبز.","رشّ مسحوق الثوم ومسحوق البصل والبابريكا المدخنة والملح والفلفل الأسود فوق اللفت. قلّب حتى يتغطى بالتساوي.","اخبزه في الفرن المسخّن مسبقًا لمدة 20–25 دقيقة أو حتى تصبح أصابع اللفت ذهبية اللون ومقرمشة، مع قلبها في منتصف المدة.","أخرجه من الفرن واتركه يبرد بضع دقائق قبل التقديم."],[],[])))
R.append(build(6228432,
ar=L("آيس كريم الشوكولاتة الخالي من الألبان","الموز والأفوكادو وحليب جوز الهند هي المكونات السرية في هذه الوصفة. لتحويله إلى موس، ضعه في الثلاجة بدلًا من الفريزر وقدّمه مع ملعقة من الكريمة المخفوقة الخفيفة وبعض التوت الطازج فوقه.","8","¼ كوب",
["2 حبة موز متوسطة (ناضجة)","2 حبة أفوكادو متوسطة (ناضجة)","⅓ كوب حليب جوز الهند الخفيف","⅓ كوب مسحوق الكاكاو","¼ كوب بديل سكر قليل السعرات"],
["ضع جميع المكونات في محضّرة الطعام أو الخلاط وامزجها حتى تصبح ناعمة تمامًا، مع التوقف من حين لآخر لكشط جوانب المحضّرة.","إذا كانت لديك آلة لصنع الآيس كريم المنزلي، فاخلط المزيج في الآلة لمدة 10 دقائق ثم عبّئه في وعاء وضعه في الفريزر. وإذا لم تكن لديك آلة، فعبّئه في وعاء وضعه في الفريزر مباشرة.","عند التقديم، أخرج الآيس كريم من الفريزر قبل التقديم بحوالي 20 دقيقة ليذوب قليلًا فيسهل غرفه."],[],[])))
R.append(build(6229237,
es=L("Tazón de yogur griego con arándanos y linaza","Información nutricional de un tazón de yogur griego con arándanos y linaza","1","1 3/4 taza",
["2/3 taza de yogur griego natural","1 taza de arándanos azules","1 cucharada de linaza molida"],
["Ponga el yogur griego con una cuchara en un tazón mediano.","Cubra el yogur con los arándanos.","Espolvoree la linaza de manera uniforme por encima.","Mezcle todos los ingredientes hasta que estén bien combinados y sirva de inmediato."],[],[]),
ar=L("وعاء زبادي يوناني بالتوت الأزرق وبذور الكتان","المعلومات الغذائية لوعاء زبادي يوناني بالتوت الأزرق وبذور الكتان","1","1¾ كوب",
["⅔ كوب زبادي يوناني سادة","1 كوب توت أزرق","1 ملعقة كبيرة بذور كتان مطحونة"],
["ضع الزبادي اليوناني بالملعقة في وعاء تقديم متوسط الحجم.","ضع التوت الأزرق فوق الزبادي.","رشّ بذور الكتان بالتساوي على الوجه.","قلّب جميع المكونات معًا حتى تمتزج جيدًا، وقدّمه فورًا."],[],[])))
R.append(build(6229594,
ar=L("كونجي الأرز البني مع الأعشاب المقلية","الكونجي هو عصيدة أرز تقليدية. يُؤكل عادةً في وقت الإفطار، ولكن يمكن تناوله في أي وقت آخر من اليوم. وهو طريقة رائعة لجعل كمية قليلة من الأرز تكفي لعدد أكبر، ويمكن تناوله مع اللحم أو السمك أو الخضار أو البيض.","6","1 كوب",
["2 كوارت (نحو 2 لتر) ماء مفلتر","1 كوب أرز سوشي بني","1 ملعقة كبيرة زيت بذور العنب","2 أونصة زنجبيل طازج (مقشر ومقطع إلى شرائح رفيعة جدًا)","2 حبة بصل أخضر (مقطعة إلى شرائح رفيعة بطول 1 بوصة)","2 حبة فلفل تايلندي أحمر (منزوعة السيقان والبذور ومقطعة إلى حلقات رفيعة)","½ حزمة، نحو 1 كوب كزبرة خضراء (مقطوعة السيقان ومفرومة فرمًا خشنًا)"],
["املأ قدرًا كبيرًا بالماء. أضف الأرز وغطِّه وأوصله إلى الغليان على نار عالية. خفّض الحرارة إلى متوسطة واستمر في الطهي حتى تتفكك حبات الأرز ويثخن الحساء، نحو ساعة واحدة.","في هذه الأثناء، في مقلاة صغيرة على نار عالية، أضف الزيت وقلّب الزنجبيل والبصل الأخضر والفلفل حتى تفوح رائحتها ويصبح لونها ذهبيًا فاتحًا، 30-45 ثانية. أضف الكزبرة الخضراء واستمر في التقليب حتى تذبل فقط، نحو 30 ثانية أخرى. انقلها إلى وعاء.","اغرف بعض الكونجي في 6 أوعية فردية، وضع على كل وعاء نحو 1 ملعقة كبيرة من الأعشاب المقلية. اخلط الأعشاب مع العصيدة لتتوزع النكهات. قدّمه."],[],[])))
R.append(build(6229691,
ar=L("دجاج بالخل البلسمي مع الفطر","طبق الدجاج الرئيسي البسيط هذا اقتصادي وبداية مثالية لطبق صحي. قدّمه مع طبق خضار جانبي بسيط مثل الفاصوليا الخضراء على الطريقة الشرق أوسطية السهلة.","4","1 صدر دجاج مع ¼ كوب وافر من الفطر",
["1 رطل صدور دجاج منزوعة العظم والجلد (مقسمة إلى 4 حصص، وزن كل منها 4 أونصات)","1 ملعقة كبيرة زيت زيتون","¼ كوب دقيق متعدد الاستخدامات","1 ملعقة كبيرة سمن نباتي (مارجرين) (خالٍ من الدهون المتحولة)","10 أونصة فطر أبيض (شامبينيون) (مقطع شرائح)","¼ ملعقة صغيرة فلفل أسود","⅓ كوب خل بلسمي","½ كوب مرق دجاج قليل الصوديوم"],
["ضع صدر الدجاج في كيس بلاستيكي واطرقه بالمطرقة حتى يصبح رقيقًا.","سخّن زيت الزيتون على نار متوسطة إلى عالية في مقلاة.","غطِّ الدجاج بالدقيق على الجانبين. ضع الدجاج في المقلاة وقلّبه 5 دقائق على كل جانب. أخرج الدجاج من المقلاة وضعه جانبًا.","ذوّب السمن النباتي (المارجرين) في المقلاة. أضف الفطر والفلفل واطهِه لمدة 5 دقائق. أضف الخل البلسمي إلى المقلاة وأوصله إلى الغليان ليتبخر جزء من السائل.","أضف مرق الدجاج إلى المقلاة واتركه على نار هادئة دقيقتين إضافيتين. أعد صدور الدجاج إلى المقلاة واتركها على نار هادئة لمدة 5 دقائق."],[],[])))
R.append(build(6230599,
es=L("Tilapia al horno con verduras asadas","La tilapia es un pescado blanco suave y ligero que se cocina rápido y se encuentra fácilmente en la mayoría de los supermercados. Con tomates, verduras y hierbas, el pescado absorbe todos esos sabores mediterráneos mientras se cocina.","4","3 oz de pescado + 1-1/2 tazas de verduras",
["4 filetes pequeños de tilapia fresca","1/2 cucharadita de pimienta negra","1 cucharada de aceite de oliva","1/2 taza de cebolla dulce (picada en cubos)","2 tazas de berenjena (picada en cubos)","1 taza de calabacín (picado en cubos)","1 taza de pimiento rojo (picado en cubos)","1 lata (15 oz) de tomates asados al fuego (sin sal añadida)","1 cucharadita de orégano seco","1/4 cucharadita de sal kosher","1/2 cucharadita de ajo en polvo","1 taza de pimiento morrón naranja (picado en cubos)"],
["Precaliente el horno a 400 grados F.","Si es necesario, corte el pescado en 4 piezas y sazónelo por ambos lados con la pimienta. Reserve.","En una sartén grande apta para horno, caliente el aceite de oliva a fuego medio. Agregue la cebolla y saltéela durante 3 minutos, hasta que apenas empiece a ablandarse. Si no tiene una sartén grande apta para horno, pase el pescado y las verduras a una bandeja para hornear o a una cazuela para cocinarlos en el horno.","Agregue la berenjena a la cebolla y saltee durante 3 minutos, hasta que apenas empiece a ablandarse.","Agregue el calabacín, los pimientos, los tomates, el orégano, la sal y el ajo en polvo, y mezcle bien.","Acomode los filetes de pescado dentro de la mezcla de tomate y verduras.","Tape la sartén y colóquela en el horno. Hornee durante 15 minutos, hasta que las verduras y el pescado estén bien cocidos."],[],[]),
ar=L("سمك البلطي المخبوز مع الخضار المشوية","البلطي سمك أبيض خفيف الطعم يُطهى بسرعة ويتوفر بسهولة في معظم محلات البقالة. مع الطماطم والخضار والأعشاب، يكتسب السمك كل نكهات البحر المتوسط أثناء الطهي.","4","3 أونصات سمك + 1½ كوب خضار",
["4 شرائح صغيرة من سمك البلطي الطازج","½ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة زيت زيتون","½ كوب بصل حلو (مقطع مكعبات)","2 كوب باذنجان (مقطع مكعبات)","1 كوب كوسا (مقطعة مكعبات)","1 كوب فلفل أحمر (مقطع مكعبات)","1 علبة (15 أونصة) طماطم مشوية على النار (بدون ملح مضاف)","1 ملعقة صغيرة أوريجانو مجفف","¼ ملعقة صغيرة ملح كوشر","½ ملعقة صغيرة مسحوق الثوم","1 كوب فلفل رومي برتقالي (مقطع مكعبات)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (205° مئوية).","إذا لزم الأمر، قطّع السمك إلى 4 قطع وتبّله على الجانبين بالفلفل. ضعه جانبًا.","في مقلاة سوتيه كبيرة صالحة للفرن، سخّن زيت الزيتون على نار متوسطة. أضف البصل وقلّبه لمدة 3 دقائق حتى يبدأ بالذبول فقط. وإذا لم تكن لديك مقلاة كبيرة صالحة للفرن، فانقل السمك والخضار إلى صينية خبز أو وعاء فرن لطهيها في الفرن.","أضف الباذنجان إلى البصل وقلّبه لمدة 3 دقائق حتى يبدأ بالذبول فقط.","أضف الكوسا والفلفل والطماطم والأوريجانو والملح ومسحوق الثوم واخلط جيدًا.","ضع شرائح السمك برفق وسط خليط الطماطم والخضار.","غطِّ المقلاة وضعها في الفرن. اخبزه لمدة 15 دقيقة حتى تنضج الخضار والسمك تمامًا."],[],[])))
R.append(build(6231400,
ar=L("غازباتشو 2، 2، 2 اللذيذ","الغازباتشو حساء يُحضَّر أساسًا من الخضار غير النشوية. يُقدَّم باردًا ويمكن أن يكون وجبة خفيفة رائعة في الصيف. كما أنه طريقة سهلة لإضافة المزيد من الخضار إلى يومك!","6","½ كوب",
["2 رطل طماطم ناضجة","2 حبة كوسا متوسطة","2 حبة خيار كبيرة (غير مقشرة (إنجليزي أو بيوت محمية))","1 حبة بصل أحمر صغيرة","4 فص ثوم (مقشر)","1 حبة فلفل رومي أحمر كبيرة","1 ملعقة كبيرة خل بلسمي","1 كوب عصير خضار","1 رشة ملح","1 رشة فلفل أسود"],
["في محضّرة الطعام، افرم الخضار والثوم فرمًا ناعمًا على دفعات. ضعها في وعاء زجاجي كبير.","أضف الخل البلسمي وعصير الخضار والملح والفلفل. برّده في الثلاجة لمدة ساعة على الأقل."],[],[])))
R.append(build(6232942,
es=L("Tacos de pescado a la parrilla con salsa de fresa y mango","Esta receta de tacos de pescado resulta aún más vistosa cuando se cubre con una jugosa salsa de fresa y mango. Las fresas dulces y el mango tropical son la combinación perfecta para este festivo platillo de verano.","4","2 tacos y 1/4 taza de salsa",
["1 cucharada de aceite de oliva extra virgen","2 cucharadas para el adobo + 2 cucharadas para la salsa de jugo de limón fresco (uso dividido)","1 cucharadita para el adobo + 1/4 cucharadita para la salsa de ralladura de limón (recién rallada, uso dividido)","1/4 cucharadita de chile chipotle en polvo","1/2 cucharadita de comino molido","1/4 cucharadita de sal marina fina","1/4 cucharadita de pimienta negra recién molida","1 libra de filetes de bacalao (o un pescado blanco similar de carne hojaldrada)","8 tortillas de maíz pequeñas","1/2 taza de fresas (para la salsa, picadas)","1/2 taza de mango (para la salsa, picado)","1 chalote pequeño (para la salsa, picado finamente)","1/4 taza de cilantro fresco (para la salsa, picado)"],
["En un tazón mediano, bata el aceite, el jugo de limón, la ralladura de limón, el chile en polvo, el comino, la sal y la pimienta. Agregue el bacalao y déjelo marinar en el refrigerador de 15 a 20 minutos.","Mientras el pescado se marina, mezcle todos los ingredientes de la salsa en un tazón mediano.","Precaliente una parrilla al aire libre o una sartén para asar a fuego medio-alto.","Retire el bacalao del adobo y áselo de 3 a 4 minutos por un lado. Luego voltéelo y áselo de 1 a 2 minutos por el otro lado, o hasta que el pescado se desmenuce fácilmente con un tenedor.","Pase el bacalao a un plato y déjelo reposar 5 minutos; luego use un tenedor para desmenuzarlo en trozos del tamaño de un bocado.","Trabajando por tandas si es necesario, ase las tortillas 20 segundos cada una. Reparta el pescado en partes iguales entre las tortillas, decore con la salsa (unas 2 cucharadas por taco) y sirva."],[],[]),
ar=L("تاكو السمك المشوي مع صلصة الفراولة والمانجو","تصبح وصفة تاكو السمك هذه أكثر حيوية عند تغطيتها بصلصة الفراولة والمانجو العصيرية. التوت الحلو والمانجو الاستوائية هما المزيج المثالي لهذا الطبق الصيفي الاحتفالي.","4","2 تاكو و¼ كوب صلصة",
["1 ملعقة كبيرة زيت زيتون بكر ممتاز","2 ملعقة كبيرة للتتبيلة + 2 ملعقة كبيرة للصلصة عصير ليمون أخضر طازج (يُقسَّم)","1 ملعقة صغيرة للتتبيلة + ¼ ملعقة صغيرة للصلصة قشر ليمون أخضر (مبشور طازجًا، يُقسَّم)","¼ ملعقة صغيرة مسحوق فلفل التشيبوتلي الحار","½ ملعقة صغيرة كمون مطحون","¼ ملعقة صغيرة ملح بحري ناعم","¼ ملعقة صغيرة فلفل أسود مطحون طازجًا","1 رطل شرائح سمك القد (أو سمك أبيض مشابه سهل التفتت)","8 أقراص تورتيلا ذرة صغيرة","½ كوب فراولة (للصلصة، مفرومة)","½ كوب مانجو (للصلصة، مفرومة)","1 حبة كراث أخضر صغيرة (شالوت) (للصلصة، مفرومة ناعمًا)","¼ كوب كزبرة خضراء طازجة (للصلصة، مفرومة)"],
["في وعاء متوسط، اخفق الزيت وعصير الليمون وقشر الليمون ومسحوق الفلفل والكمون والملح والفلفل الأسود. أضف سمك القد وانقعه في الثلاجة لمدة 15–20 دقيقة.","بينما يتتبّل السمك، اخلط جميع مكونات الصلصة معًا في وعاء متوسط.","سخّن شواية خارجية أو مقلاة شواء على نار متوسطة إلى عالية.","أخرج سمك القد من التتبيلة واشوِه لمدة 3–4 دقائق على جانب واحد. ثم اقلبه واشوِه 1–2 دقيقة على الجانب الآخر، أو حتى يتفتت السمك بسهولة بالشوكة.","انقل سمك القد إلى طبق واتركه يستريح 5 دقائق، ثم استخدم شوكة لتفتيته إلى قطع بحجم اللقمة.","اشوِ أقراص التورتيلا لمدة 20 ثانية لكل قرص، على دفعات إذا لزم الأمر. وزّع السمك بالتساوي على الأقراص، وزيّنه بالصلصة (نحو 2 ملعقة كبيرة لكل تاكو) وقدّمه."],[],[])))
R.append(build(6233274,
ar=L("سمك مشوي بالليمون والزبدة على الهليون المشوي","قد تكون وصفة السمك السريعة والسهلة هذه الطبق الصيفي المثالي لأيام الأسبوع. بمكونات قليلة فقط، يمكنك إعداد وجبة جميلة وصحية للقلب ومناسبة لمرضى السكري في نحو 15 دقيقة.","4","3 أونصات سمك مطهو + 6–8 سيقان هليون + 1 ملعقة كبيرة من الإضافة",
["1 رطل سيقان هليون (مقطوعة الأطراف)","2 بخّة، 0.50 غرام بخاخ طهي غير لاصق","4 شرائح سمك قد كاملة (4 أونصات لكل منها، مشطوفة ومجففة بالتربيت)","1 ملعقة كبيرة قشر ليمون (من ليمونة متوسطة)","¼ كوب زبدة خفيفة بزيت الكانولا","2 ملعقة كبيرة عصير ليمون (من ليمونة متوسطة)"],
["سخّن شواية أو مقلاة شواء على نار متوسطة إلى عالية. غطِّ الهليون ببخاخ الطهي واطهِه 6–8 دقائق أو حتى يصبح طريًا ومقرمشًا قليلًا، مع تقليبه من حين لآخر. ضعه جانبًا على طبق تقديم ذي حواف وغطِّه ليبقى دافئًا.","غطِّ جانبَي السمك ببخاخ الطهي، ورشّ عليه ¼ ملعقة صغيرة فلفل أسود إن رغبت، واطهِه 3 دقائق على كل جانب أو حتى يصبح معتمًا في المنتصف.","في هذه الأثناء، اخلط الزبدة الخفيفة وقشر الليمون و¼ ملعقة صغيرة ملح إن رغبت في وعاء صغير.","وزّع مزيج الزبدة بالملعقة على الهليون وافرده عليه كله. ضع السمك فوقه واعصر عصير الليمون على السمك."],[],[])))
R.append(build(6233807,
es=L("Crepas rellenas de requesón y frutos rojos","¿Se le antoja algo dulce y salado para el desayuno? ¡Prepare estas crepas rellenas de requesón y frutos rojos! Son ricas en proteínas, lo que le ayudará a sentirse satisfecho toda la mañana.","4","2 crepas rellenas",
["1/2 taza de harina de almendra","1/2 taza de claras de huevo","1/2 taza de leche de almendra sin azúcar","2 cucharadas de aceite de oliva","2 cucharaditas de extracto de vainilla","1/16 cucharadita de sal","1 taza de requesón (sin grasa)","1 taza de frutos rojos mixtos"],
["Prepare las crepas. En una licuadora, combine la harina de almendra, la harina de coco, los huevos, la leche de almendra, el aceite de oliva, el extracto de vainilla y una pizca de sal. Licúe hasta obtener una mezcla suave.","Deje reposar la masa de las crepas en el refrigerador por lo menos 30 minutos.","Caliente una sartén antiadherente a fuego medio y rocíela ligeramente con aceite en aerosol.","Vierta una pequeña cantidad de masa en la sartén, girándola para cubrir el fondo de manera delgada y uniforme.","Cocine cada crepa de 1 a 2 minutos por cada lado, o hasta que esté ligeramente dorada. Repita con la masa restante.","Ponga el requesón con una cuchara sobre una mitad de cada crepa.","Agregue una capa de frutos rojos mixtos sobre el requesón.","Doble los lados y enrolle para cerrar cada crepa alrededor del relleno."],[],[]),
ar=L("كريب محشو بالجبن القريش والتوت","هل تشتهي شيئًا حلوًا ومالحًا على الإفطار؟ حضّر هذا الكريب المحشو بالجبن القريش والتوت! فهو غني بالبروتين الذي يساعدك على الشعور بالشبع طوال الصباح.","4","2 كريب محشو",
["½ كوب دقيق اللوز","½ كوب بياض البيض","½ كوب حليب لوز غير محلى","2 ملعقة كبيرة زيت زيتون","2 ملعقة صغيرة مستخلص الفانيليا","1/16 ملعقة صغيرة ملح","1 كوب جبن قريش (خالٍ من الدسم)","1 كوب توت مشكّل"],
["حضّر الكريب. في الخلاط، اخلط دقيق اللوز ودقيق جوز الهند والبيض وحليب اللوز وزيت الزيتون ومستخلص الفانيليا ورشة ملح. اخلطها حتى تصبح ناعمة.","اترك عجينة الكريب تستريح في الثلاجة لمدة 30 دقيقة على الأقل.","سخّن مقلاة غير لاصقة على نار متوسطة ورشّها قليلًا ببخاخ الطهي.","اسكب كمية صغيرة من العجين في المقلاة، مع تحريكها بحركة دائرية لتغطية القاع بطبقة رقيقة ومتساوية.","اطهِ كل كريب نحو 1–2 دقيقة على كل جانب أو حتى يصبح ذهبيًا فاتحًا. كرر العملية مع بقية العجين.","ضع الجبن القريش بالملعقة على نصف كل كريب.","أضف طبقة من التوت المشكّل فوق الجبن القريش.","اطوِ الجوانب ولفّ لإغلاق كل كريب حول الحشوة."],[],[])))
save('out_c7_part1.json',R)
