from mk import *
R=[]
R.append((9277390,"Jamur Portobello Vegan Isi Lasagna",
"Jamur portobello isi vegan ini penuh dengan isian ricotta bayam \"keju\" dan ditutup dengan saus bolognese yang kaya rasa untuk memuaskan keinginan Anda akan lasagna.",
"6 porsi","1 porsi",
["6 jamur portobello, dibersihkan dengan sikat",("Untuk Ricotta","1.5 cangkir kacang mete mentah"),("Untuk Ricotta","1 sendok makan cuka sari apel"),("Untuk Ricotta","¼ cangkir ragi nutrisi"),("Untuk Ricotta","¼ sendok teh bubuk bawang putih"),("Untuk Ricotta","¾ sendok teh garam laut"),("Untuk Ricotta","½ cangkir air"),("Untuk Ricotta","1 kemasan 5 ons bayam muda, sekitar 3-4 genggam besar atau 1 cangkir bayam layu"),("Untuk Saus Bolognese","1 cangkir saus tomat atau saus marinara favorit Anda"),("Untuk Saus Bolognese","½ cangkir kenari cincang"),("Untuk Saus Bolognese","¼ sendok teh garam laut"),("Untuk Saus Bolognese","¼ sendok teh basil kering"),("Untuk Saus Bolognese","¼ sendok teh oregano kering"),("Untuk Saus Bolognese","¼ sendok teh bubuk bawang putih"),("Hiasan Opsional","keju parmesan vegan"),("Hiasan Opsional","peterseli segar")],
["Panaskan oven terlebih dahulu hingga 400℉/204℃ dan alasi loyang besar dengan kertas roti.","Bersihkan jamur dengan sikat dan kerok bagian insangnya menggunakan sendok teh logam. Berhati-hatilah agar jamur tidak patah. Lalu letakkan jamur dengan sisi batang menghadap ke bawah di atas loyang. Taburi bagian atasnya dengan garam dan merica, lalu panggang selama 10 menit. Langkah ini membuat sebagian air keluar dari jamur sehingga nanti tidak berair.","Sementara itu, tumis bayam di wajan dengan api sedang hingga layu. Tambahkan satu atau dua tetes air jika diperlukan agar mulai layu. Aduk sesekali agar tidak lengket. Setelah layu, peras sebanyak mungkin cairan dari bayam menggunakan lap dapur bersih, kantong susu kacang, atau tisu dapur. Sisihkan.","Masukkan semua bahan ricotta KECUALI bayam ke dalam food processor. Proses hingga halus, kerok sisi wadah jika diperlukan. Setelah halus, tambahkan bayam dan pulse 3-4 kali agar tercampur. JANGAN diproses terlalu lama atau kejunya akan berwarna hijau.","Selanjutnya, campurkan semua bahan saus bolognese dalam mangkuk kecil. Aduk dan sisihkan.","Keluarkan jamur dari oven dan balikkan dengan sisi batang menghadap ke atas. Serap kelebihan air dengan menepuk-nepuk jamur menggunakan lap dapur bersih atau tisu dapur.","Bagi ricotta ke enam jamur. Lalu lapisi masing-masing dengan saus bolognese. Panggang jamur isi selama 10-12 menit, keluarkan dari oven, dan sajikan dengan peterseli segar, serpihan cabai merah, dan/atau keju parmesan vegan."],
["Jika Anda tidak memiliki food processor yang bertenaga kuat, rendam kacang mete dalam air mendidih selama 15-30 menit, lalu tiriskan, sebelum membuat keju ricotta.","Jika menggunakan bayam beku, takar sekitar 1 cangkir, cairkan, lalu peras sebanyak mungkin airnya menggunakan kantong susu kacang, lap dapur, atau tisu dapur.","Jangan memproses bayam terlalu lama saat membuat ricotta. Cukup pulse beberapa kali agar tercampur. Anda ingin melihat serat-serat bayam di dalam ricotta, bukan keju yang berwarna hijau.","Untuk menjadikannya hidangan pembuka, gunakan sekitar 2-3 kali lebih banyak kepala jamur portobello atau jamur cremini, tergantung ukurannya.","Jika ingin menyiapkan lebih awal, buat keju ricotta dan saus bolognese lalu simpan terpisah di lemari es selama 2-3 hari sebelumnya. Kemudian isi dan panggang jamur pada hari penyajian.","Sisa makanan dapat disimpan di lemari es selama 2-3 hari dalam wadah tertutup."],[]))
R.append((9279723,"Dip Bayam Artichoke Vegan [Bebas Minyak]",
"Dip bayam artichoke vegan yang creamy, meleleh, dan sangat lezat! Hidangan pembuka yang seru ini begitu lengket dan kenyal, sehingga tak seorang pun akan percaya bahwa ini vegan.",
"8 porsi","1 porsi",
["2 genggam besar bayam segar atau 2 cangkir bayam beku*","1 kaleng 13.5 ons hati artichoke dalam air, bukan yang dimarinasi (sekitar 1.5 cangkir)","1 cangkir kacang mete mentah","2 cangkir air","⅓ cangkir ragi nutrisi","½ cangkir pati tapioka atau tepung tapioka","3 siung bawang putih, dikupas","1 sendok makan cuka putih","1.5 sendok teh garam laut","¾ cangkir susu mete tanpa pemanis atau susu nabati pilihan Anda",("Hiasan Opsional","Keju Parmesan Vegan")],
["Tiriskan dan bilas artichoke, iris tipis, lalu sisihkan.","Masukkan semua bahan KECUALI artichoke dan bayam ke dalam blender berkecepatan tinggi. Proses hingga halus, adonan akan sangat cair tetapi akan mengental saat dimasak.","Tuang campuran ke dalam wajan antilengket, atau gunakan wajan tahan oven seperti wajan besi cor jika Anda ingin memanggang dip dengan broiler nanti. Masukkan artichoke iris dan bayam ke dalam wajan. Masak dengan api sedang sambil sering diaduk selama sekitar 5 menit hingga kental dan menggelembung.","OPSIONAL: Atur oven ke mode broil pada suhu tinggi. Lalu pindahkan dip ke wadah tahan oven (jika belum berada di dalamnya). Broil selama 2-5 menit hingga bagian atasnya kecokelatan dan menggelembung. Awasi dengan cermat agar tidak gosong. Keluarkan dari oven.","Taburi dengan keju parmesan vegan, jika digunakan. Lalu sajikan hangat dengan keripik tortilla, biskuit, sayuran mentah, roti, atau pendamping favorit Anda."],
["* Jika Anda menggunakan bayam beku, pastikan untuk memeras dan meniriskan air sebanyak mungkin sebelum memasukkannya ke wajan. Jika Anda tidak memiliki blender berkecepatan tinggi, rendam kacang mete dalam air mendidih selama 15-30 menit terlebih dahulu, lalu tiriskan dan gunakan sesuai petunjuk. Ini akan membantu melunakkannya sehingga lebih mudah diblender. Jika dip menjadi terlalu kental, tambahkan lebih banyak susu atau air ke wajan untuk mengencerkannya. Perlu diketahui bahwa dip akan mengeras saat dingin dan pemanasan ulang akan mengembalikan teksturnya yang lebih lembut. Untuk menambah kedalaman rasa, gunakan kaldu sayuran sebagai pengganti air. Untuk membuatnya pedas, tambahkan ½ sendok teh cabai cayenne atau 1-2 sendok teh saus pedas favorit Anda. Untuk dip beraroma asap, tambahkan 1 sendok teh paprika asap. Untuk menyiapkannya lebih awal, blender dan masak di atas kompor sesuai petunjuk lalu simpan di lemari es hingga diperlukan. Kemudian masukkan ke oven pada suhu 350°F/176°C untuk dipanaskan selama sekitar 10-15 menit. Kemudian broil selama tambahan 2-5 menit untuk mencokelatkan bagian atasnya, jika Anda mau. Simpan sisa makanan di lemari es dalam wadah tertutup selama 3-4 hari atau bekukan dalam wadah kedap udara yang aman untuk freezer hingga 3 bulan. Resep ini terinspirasi dari mozzarella vegan saya."],[]))
R.append((9279842,"Kentang Goreng Vegan dengan Topping Lengkap",
"Bersiaplah menikmati kentang goreng vegan dengan topping lengkap yang paling nikmat!",
"6 porsi","1 porsi",
[("Untuk Kentang Goreng","3 pon kentang russet"),("Untuk Kentang Goreng","2 sendok makan kaldu sayuran atau minyak alpukat"),("Untuk Kentang Goreng","½ sendok teh garam laut atau secukupnya"),("Untuk Topping","1 resep saus keju bebas kacang atau keju vegan pilihan Anda"),("Untuk Topping","½ cangkir kacang merah"),("Untuk Topping","½ cangkir buah zaitun hitam"),("Untuk Topping","½ cangkir jagung"),("Untuk Topping","1 tomat, dipotong dadu"),("Untuk Topping","1-2 daun bawang, diiris"),("Untuk Topping","1-2 jalapeño, diiris, opsional"),("Untuk Cocolan (opsional)","krim mete"),("Untuk Cocolan (opsional)","guacamole"),("Untuk Cocolan (opsional)","salsa")],
["Panaskan oven terlebih dahulu hingga 425℉/218℃ dengan mode convection roast dan alasi loyang besar dengan kertas roti.","Kupas atau sikat kentang hingga bersih, lalu iris menjadi kentang goreng menggunakan pemotong kentang goreng atau pisau tajam. Aduk dengan kaldu atau minyak dan garam. Lalu susun dalam satu lapisan di atas loyang. Panggang selama 20 menit, lalu balikkan, dan lanjutkan memanggang 10-15 menit lagi, atau hingga tingkat kerenyahan yang diinginkan tercapai.","Sementara itu, buat saus keju dan siapkan topping lainnya selagi kentang goreng dipanggang.","Penyajian: Gunakan piring saji besar atau loyang yang sama dengan yang Anda pakai untuk memanggang. Mulailah dengan kentang goreng, lalu sekitar setengah dari saus keju, kemudian taburkan semua topping lainnya dalam urutan apa pun yang Anda suka. Terakhir, tuangkan sisa saus keju di atasnya dan sajikan."],
["Susun kentang goreng dalam satu lapisan dengan sedikit jarak di antaranya agar kentang goreng panggang paling renyah dan tidak lengket. Untuk oven tanpa convection, perkirakan waktu memasak sedikit lebih lama. Teruslah memanggang hingga tingkat kerenyahan yang diinginkan tercapai."],[]))
R.append((9289404,"Kue Kering Halloween Sehat [Tak Ada yang Akan Tahu!]",
"Kue kering Halloween sehat adalah suguhan yang pas untuk menyenangkan anak-anak maupun orang dewasa!",
"26 kue kering","1 porsi",
["1.5 cangkir buncis (kacang arab), matang atau kalengan","2 pisang matang ukuran sedang (berat 230 gram dengan kulitnya)","¼ cangkir sirup maple","½ cangkir selai kacang, buatan sendiri atau beli jadi (atau ganti dengan selai kedelai agar bebas kacang)","2 sendok makan saus apel tanpa gula","1 cangkir oat gulung, bebas gluten jika diinginkan","3 genggam besar bayam muda","1 sendok teh baking powder",("Opsional","keping cokelat ATAU mata permen")],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi dua loyang dengan kertas roti.","Masukkan semuanya KECUALI bahan opsional ke dalam food processor dan proses hingga halus.","Gunakan sendok es krim kecil untuk menyendok adonan ke atas loyang. Anda akan mendapatkan sekitar 26 kue kering. Lalu dengan tangan yang sedikit basah atau punggung sendok, tekan kue kering dan bentuk menjadi lingkaran. Adonan tidak akan melebar banyak, jadi bentuklah sebelum dipanggang.","OPSIONAL: Jika menggunakan keping cokelat untuk mata, tambahkan sekarang pada kue kering Anda. Jika menggunakan mata permen, tambahkan SETELAH dipanggang.","Panggang selama 16-18 menit, lalu keluarkan kue kering dari oven dan tekan perlahan mata permen (jika digunakan) ke kue kering selagi masih hangat. Untuk membuat mulut, gunakan tusuk gigi atau ujung sendok atau garpu untuk menggores berbagai bentuk mulut pada setiap kue kering seram Anda. Lalu biarkan dingin."],
["Gunakan pisang yang SANGAT matang dan berbintik cokelat, karena tidak ada tambahan pemanis yang banyak.","Jika menggunakan mata permen, tekan ke kue kering segera setelah dikeluarkan dari oven, selagi masih hangat.","Buat bentuk mulut yang seru pada kue kering hijau Anda selagi masih hangat. Gunakan tusuk gigi atau ujung sendok atau garpu."],[]))
R.append((9291733,"Coleslaw Vegan Bebas Minyak",
"Coleslaw vegan yang creamy dan lezat, renyah, asam segar, dan sangat kaya rasa.",
"8 porsi","1 porsi",
["2 pon kubis ungu, sekitar 6-7 cangkir parutan","2 wortel besar, sekitar 1-2 cangkir parutan","1 cangkir mayo vegan bebas minyak buatan sendiri atau beli jadi","1.5 sendok makan sirup maple atau sirup kurma","1.5 sendok makan cuka putih","1 sendok makan mustard kuning","¼ sendok teh merica hitam"],
["Parut kubis dan wortel, lalu masukkan ke dalam mangkuk besar.","Dalam mangkuk kecil, campurkan mayo, sirup maple, cuka, mustard, dan merica hitam. Kocok hingga tercampur. Lalu tuang ke atas coleslaw dan aduk hingga terlapisi merata."],
["Untuk versi bebas minyak, gunakan mayo pepita saya untuk resep ini. Mayo kemasan biasanya mengandung BANYAK minyak.","Untuk pilihan tanpa mayo, cobalah coleslaw dengan dressing kacang kami.","Gunakan coleslaw parut kemasan agar persiapan lebih cepat. Gunakan 6-8 cangkir campuran favorit Anda.","Cicipi dressing sebelum menuangkannya ke salad dan sesuaikan bumbunya jika perlu. Anda menginginkan dressing yang rasanya sangat kuat karena sayurannya tidak dibumbui.","Untuk saladnya, saya menyukai kubis ungu karena warnanya yang cerah, tetapi Anda boleh menggunakan kubis hijau atau campuran keduanya, jika diinginkan. Tambahan lain meliputi peterseli, daun ketumbar, seledri, daun bawang, atau bawang merah.","Untuk dressing, Anda boleh menambahkan lebih banyak bumbu jika suka. Beberapa pilihan meliputi biji seledri, jintan, bubuk cabai, bubuk bawang putih, paprika asap, atau cabai cayenne.","Coleslaw vegan ini paling enak pada hari yang sama saat dibuat, namun sisanya dapat disimpan di lemari es hingga 3 hari.","Informasi nilai gizi sudah termasuk mayo pepita saya. Jika diganti dengan mayo kemasan, kalori dan lemaknya akan bertambah."],[]))
R.append((9293583,"Kentang Goreng Wortel Air Fryer [Bebas Minyak]",
"Alternatif kentang goreng yang lebih sehat yang akan memuaskan keinginan Anda dengan kalori dan lemak yang jauh lebih sedikit! Tidak perlu minyak untuk kentang goreng wortel air fryer yang renyah dan penuh cita rasa ini.",
"2 porsi","1 porsi",
["1 pon wortel, sekitar 3 wortel ukuran sedang/besar","1 sendok makan pati tapioka, juga dikenal sebagai tepung tapioka","½ sendok teh garam laut","½ sendok teh bubuk bawang putih","½ sendok teh bubuk bawang bombai","½ sendok teh thyme kering, opsional","1-2 sendok makan parmesan vegan, opsional",("Cocolan untuk menyajikan (opsional)","honey mustard vegan"),("Cocolan untuk menyajikan (opsional)","mayo sriracha")],
["Kupas dan potong wortel menjadi batang sepanjang 4 inci, tebal sekitar 1/4 inci agar matang merata.",("Petunjuk Air Fryer","Masukkan kentang goreng wortel dan semua bahan lainnya ke dalam mangkuk pencampur ukuran sedang dan aduk hingga terlapisi merata, lalu susun dalam keranjang dalam satu lapisan rata. (Boleh saling menumpuk.)"),("Petunjuk Air Fryer","Goreng dengan air fryer pada 400 derajat F (204 derajat C) selama 15-20 menit, hingga tingkat kerenyahan yang diinginkan tercapai, aduk sekali di pertengahan waktu."),("Petunjuk Oven","Panaskan oven terlebih dahulu hingga 450 derajat F (232 derajat C) dan alasi loyang besar dengan kertas roti."),("Petunjuk Oven","Masukkan pati tapioka, garam, bubuk bawang putih, bubuk bawang bombai, dan thyme ke dalam mangkuk dan aduk hingga semua wortel terlapisi merata. Lalu tebarkan wortel dalam satu lapisan di atas loyang yang sudah disiapkan, sisakan ruang di antara setiap batang agar tidak ada yang saling menumpuk."),("Petunjuk Oven","Panggang selama 20 menit, lalu keluarkan loyang dari oven, balikkan kentang goreng wortel dan taburi dengan keju parmesan vegan. Masukkan kembali ke oven selama 10 menit lagi, atau hingga tingkat kerenyahan yang diinginkan tercapai.")],
["Usahakan memotong kentang goreng wortel sama ukurannya agar matang merata. Pilihlah wortel yang lebarnya sama dari atas hingga bawah, jika memungkinkan. Waktu memasak akan bervariasi tergantung metode yang Anda gunakan (dipanggang di oven atau air fryer), serta ukuran kentang goreng wortel Anda. Anda dapat menyiapkan wortel hingga 1 hari sebelumnya dan menyimpannya di lemari es dalam mangkuk bersama bumbunya, sampai siap dipanggang. Jika Anda tidak menemukan pati atau tepung tapioka, Anda dapat menggantinya dengan tepung maizena dengan hasil yang serupa. Wortel ini paling enak saat baru dipanggang, tetapi Anda dapat menyimpan sisanya di lemari es hingga 3 hari."],[]))
R.append((9295060,"Salad Kentang Asparagus",
"Salad kentang asparagus yang cerah ini adalah perayaan sempurna cita rasa musim semi!",
"6 porsi","1 porsi",
[("Untuk salad kentang","2 pon kentang mini, disikat bersih (saya menggunakan campuran kentang merah dan kuning)"),("Untuk salad kentang","1 pon asparagus, ujungnya dipotong + dipotong 1 inci"),("Untuk salad kentang","1 cangkir kacang polong beku"),("Untuk salad kentang","2-3 sendok makan bawang merah, dipotong dadu"),("Untuk dressing","¼ cangkir air lemon"),("Untuk dressing","1 sendok makan tahini atau selai almond"),("Untuk dressing","1 sendok makan sirup maple"),("Untuk dressing","1 sendok teh mustard kuning"),("Untuk dressing","1 sendok teh bubuk bawang putih"),("Untuk dressing","1 sendok teh oregano kering"),("Untuk dressing","¼ cangkir chives segar, dicincang halus"),("Untuk dressing","garam + merica secukupnya")],
["Didihkan sepanci besar air asin.","Masukkan kacang polong dan asparagus, masak selama 2-3 menit. Lalu angkat menggunakan sendok berlubang dan pindahkan ke mangkuk pencampur besar.","Selanjutnya, masukkan kentang mini dan masak hingga empuk saat ditusuk garpu, sekitar 15-20 menit. Tiriskan dan bilas kentang hingga cukup dingin untuk dipegang.","Selagi kentang dimasak, masukkan bahan dressing ke dalam mangkuk kecil atau toples dan aduk rata. Jika perlu, tambahkan beberapa tetes air untuk mengencerkan dressing.","Iris kentang yang sudah matang menjadi dua (atau empat jika lebih besar) dan masukkan bersama bawang merah ke dalam mangkuk berisi kacang polong dan asparagus. Lalu tambahkan dressing dan aduk hingga terlapisi merata."],
["Cicipi dressing untuk garam dan merica sebelum dicampur dengan salad. Sesuaikan jika perlu.","Anda dapat menyiapkan salad kentang asparagus ini lebih awal dan menyimpannya di lemari es selama 1-2 hari sebelum disajikan."],[]))
R.append((9296884,"Sup Kembang Kol Panggang",
"Sup kembang kol panggang ini kaya rasa, lembut seperti beludru, dan ternyata sangat mudah dibuat.",
"4 porsi","1 porsi",
["6 cangkir kuntum kembang kol (sekitar 1 kepala kembang kol ukuran sedang)","1 bawang bombai kuning (dibelah empat)","3 siung bawang putih (biarkan dengan kulitnya)","4 cangkir kaldu sayuran rendah natrium","1 sendok makan pasta miso putih","1/3 cangkir ragi nutrisi","1-2 sendok makan air lemon (mulai dengan 1)","15 ons kacang cannellini putih (ditiriskan + dibilas)","garam dan merica (secukupnya)"],
["Panaskan oven terlebih dahulu hingga 425℉ dengan mode convection roast dan alasi loyang besar dengan kertas roti.","Potong kembang kol menjadi kuntum kecil agar cepat matang. Belah empat bawang bombai dan biarkan kulit bawang putih tetap menempel. Susun dalam satu lapisan di atas loyang dan panggang selama 20 menit, atau hingga keemasan.","Setelah dipanggang, pindahkan sayuran dan semua bahan lainnya ke blender, kerjakan secara bertahap jika perlu. Haluskan sup hingga lembut, tetapi sisakan beberapa potong kembang kol untuk hiasan mangkuk Anda jika diinginkan."],[],[]))
build(R,'/mnt/c/WSL/davita/translations/tid1/part1.json')
