from mk import *
R=[]
R.append((9297046,"Kentang Dadu Air Fryer",
"Hidangan pendamping yang pas untuk makanan apa pun, kentang dadu air fryer ini sulit ditolak.",
"2 porsi","1 porsi",
["1 pon kentang russet, dipotong dadu setengah inci (sekitar 3 kentang ukuran sedang)","2 sendok makan air lemon, sekitar setengah buah lemon besar","1 sendok teh bubuk bawang putih","½ sendok teh thyme kering","¼ sendok teh garam laut atau secukupnya","¼ sendok teh merica hitam atau secukupnya"],
["Kupas dan potong dadu kentang menjadi kubus sekitar setengah inci, usahakan ukurannya sama agar matang merata.","Masukkan ke dalam mangkuk dan rendam dengan air dingin selama 20 menit. Lalu tiriskan kentang dan keringkan dengan menepuk-nepuknya. Bilas dan keringkan mangkuk yang digunakan untuk merendam, lalu masukkan kembali kentang ke dalam mangkuk.","Tambahkan air lemon dan bumbu, lalu aduk rata hingga semua potongan terlapisi merata.","Sendok (jangan tuang) kentang berbumbu ke dalam keranjang air fryer dalam satu lapisan, lalu goreng dengan air fryer pada 400℉/204℃ selama 15-20 menit. Aduk atau goyangkan keranjang setiap 5 menit hingga tingkat kerenyahan yang diinginkan tercapai. Selamat menikmati!"],
["Potong kentang sama rata mungkin agar matang dan renyah merata.","Jangan lewatkan langkah perendaman karena membantu menghilangkan sebagian pati dari kentang dan menghasilkan kentang yang lebih renyah, tanpa perlu minyak.","Untuk kentang yang lebih renyah lagi, Anda boleh menambahkan 1 sendok teh minyak berkualitas baik seperti minyak alpukat ke dalam campuran. (Saya tidak menyarankan memasak dengan minyak zaitun karena titik asapnya yang rendah.)"],[]))
R.append((9305421,"Kue Kering Keping Cokelat Vegan [Bebas Minyak]",
"Hanya 8 bahan, dan 20 menit untuk kue kering nabati yang lezat + sehat. Kue ini empuk, lembut + bikin ketagihan!",
"20 kue kering","1 porsi",
[("Bahan Kering","180 gram tepung oat, bebas gluten jika diinginkan, sekitar 1.5 cangkir"),("Bahan Kering","1.5 sendok teh baking powder"),("Bahan Kering","¼ sendok teh garam laut"),("Bahan Basah","⅓ cangkir susu kedelai"),("Bahan Basah","⅓ cangkir sirup maple"),("Bahan Basah","¼ cangkir saus apel tanpa gula"),("Bahan Basah","1 sendok teh ekstrak vanila murni"),("Tambahan Opsional (Tapi Disarankan)","⅓ cangkir keping cokelat hitam")],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi loyang besar dengan kertas roti.","Kocok 3 bahan kering dalam mangkuk kecil dan sisihkan. Dalam mangkuk sedang yang terpisah, campurkan bahan basah dan aduk rata. Lalu, masukkan bahan kering dan keping cokelat ke dalam mangkuk berisi bahan basah, dan aduk hingga tercampur.","Gunakan sendok kue kering atau sendok makan untuk menyendok adonan ke atas loyang yang sudah disiapkan hingga menjadi sekitar 20 kue kering, sisakan jarak di antara setiap kue.","Panggang selama 10 menit, lalu keluarkan kue kering dari oven dan biarkan dingin selama 10 menit sebelum dipindahkan ke rak pendingin. Nikmati selagi hangat, atau biarkan hingga dingin pada suhu ruangan lalu nikmati."],
["Timbang tepung Anda untuk hasil yang paling akurat. Menyendok tepung langsung dari kantong sering kali membuat tepung terlalu banyak sehingga hasilnya kering. Jika Anda tidak memiliki timbangan dapur, sendokkan tepung ke dalam cangkir takar, lalu ratakan dengan punggung pisau.","Gunakan baking powder yang AKTIF. Setelah dibuka selama lebih dari 6 bulan di lemari dapur, baking powder akan mulai kehilangan keefektifannya.","Adonan Anda akan terlihat mirip adonan pancake, dan itu wajar. Ingat, ini adalah kue kering nabati rendah lemak dan bukan kue biasa yang penuh mentega.","Biarkan kue kering dingin selama 10 menit setelah dikeluarkan dari oven, sebelum disentuh. Waktu pendinginan ini akan membantu kue mengeras dan mengeras sempurna.","Paling baik disajikan dalam 1-2 hari, tetapi dapat disimpan 2-3 hari pada suhu ruangan, hingga 5 hari di lemari es, atau dibekukan hingga 3 bulan."],[]))
R.append((9306532,"Buncis Air Fryer",
"Buncis air fryer yang empuk renyah dengan aroma lemon. Kaya rasa, sangat mudah disiapkan, dan siap dalam 15 menit atau kurang.",
"4 porsi","1 porsi",
["14 ons (400 gram) buncis, ujungnya dipotong","2 sendok makan air lemon","¼ sendok teh bubuk bawang putih","¼ sendok teh garam laut atau secukupnya","¼ sendok teh merica hitam atau secukupnya",("Hiasan Opsional","1-2 sendok makan keju Parmesan vegan")],
["Potong ujung buncis dan masukkan ke dalam mangkuk pencampur ukuran sedang. Tambahkan air lemon dan bumbu lalu aduk hingga buncis terlapisi merata.","Masukkan ke dalam keranjang dan goreng dengan air fryer pada 380 derajat F (193 derajat C) selama 8-12 menit, hingga keemasan. Aduk di pertengahan waktu memasak.","Angkat buncis dari air fryer dan taburi dengan keju parmesan opsional, jika diinginkan. Selamat menikmati."],
["Tips cepat untuk memotong ujung buncis. Sejajarkan beberapa buncis sekaligus lalu potong ujungnya, kemudian putar dan potong sisi lainnya. Ini jauh lebih cepat daripada memotong satu per satu."],[]))
R.append((9307320,"Soy Curls Buffalo Renyah",
"Soy curls buffalo yang renyah, pedas, dan bikin ketagihan! Pas untuk hari pertandingan, kencan malam, atau malam apa pun!",
"6 porsi","1 porsi",
["8 ons soy curls","2 cangkir kaldu sayuran rendah natrium","2 sendok teh bubuk bawang putih","2 sendok teh bubuk bawang bombai","2 sendok teh paprika asap","2 sendok teh bumbu unggas (poultry seasoning)",("Saus Buffalo","½ cangkir saus pedas Frank's RedHot Original"),("Saus Buffalo","2 sendok makan selai almond atau selai mete atau tahini"),("Untuk Penyajian","dip ranch vegan"),("Untuk Penyajian","stik wortel dan seledri")],
["Panaskan oven terlebih dahulu hingga 400°F/204°C dengan mode convection bake dan alasi loyang besar (atau 2 loyang sedang) dengan kertas roti.","Campurkan kaldu sayuran, bubuk bawang putih, bubuk bawang bombai, paprika asap, dan bumbu unggas dalam gelas ukur besar atau mangkuk. Kocok rata hingga tercampur.","Lalu masukkan soy curls ke dalam mangkuk pencampur besar, tuang campuran kaldu di atasnya, dan aduk rata. Diamkan selama 10 menit, aduk setiap beberapa menit hingga cairan terserap.","Sambil menunggu soy curls menyerap cairan, masukkan saus pedas dan selai almond ke dalam mangkuk kecil dan aduk rata hingga halus. Lalu tuang saus buffalo yang baru dibuat ke atas soy curls yang sudah terhidrasi dan aduk hingga terlapisi merata.","Susun dalam satu lapisan di atas loyang, tanpa saling menumpuk. Panggang selama 20 menit, lalu balikkan dan panggang 12-15 menit lagi hingga tingkat kerenyahan yang diinginkan tercapai.","Sajikan dengan dressing ranch, wortel, dan stik seledri."],
["Jangan menuang soy curls buffalo dari mangkuk pencampur langsung ke loyang. Anda tidak ingin kelebihan cairan menggenang di loyang dan membuatnya kurang renyah.","Susun dalam satu lapisan dengan sedikit jarak di antaranya agar matang dengan renyah.","Saat membalik potongan kedelai, sekali lagi pastikan untuk menyusunnya dalam satu lapisan dengan jarak di antara setiap potongan agar paling renyah."],[]))
R.append((9310264,"Cupcake Labu Vegan Sehat",
"Cupcake labu vegan yang diam-diam sehat ini dibuat dengan bahan-bahan yang mengejutkan untuk menghasilkan hidangan penutup yang lezat sekaligus bergizi.",
"12 cupcake","1 porsi",
[("Bahan Basah","1 cangkir puree labu, bukan isian pai labu"),("Bahan Basah","¾ cangkir susu mete atau susu almond tanpa pemanis"),("Bahan Basah","½ cangkir sirup maple"),("Bahan Kering","175 gram tepung almond blanched yang sangat halus, sekitar 1 ¾ cangkir"),("Bahan Kering","150 gram tepung oat halus, sekitar 1 ¾ cangkir"),("Bahan Kering","2.5 sendok teh kayu manis"),("Bahan Kering","¼ sendok teh jahe bubuk"),("Bahan Kering","¼ sendok teh pala bubuk"),("Bahan Kering","⅛ sendok teh cengkih bubuk"),("Bahan Kering","2.5 sendok teh baking powder"),("Bahan Kering","¼ sendok teh garam laut"),("Bahan Frosting Krim Keju Vegan","340 gram (12 ons) tahu padat ekstra, gunakan yang bebas GMO jika memungkinkan"),("Bahan Frosting Krim Keju Vegan","¼ cangkir kacang mete mentah"),("Bahan Frosting Krim Keju Vegan","5-6 sendok makan sirup maple"),("Bahan Frosting Krim Keju Vegan","2 sendok teh ekstrak vanila murni")],
["Panaskan oven terlebih dahulu hingga 350°F/176°C dan alasi cetakan muffin dengan cup cupcake. Sisihkan.","Campurkan bahan basah dalam mangkuk pencampur besar dan kocok hingga tercampur. Lalu masukkan semua bahan kering dan aduk hingga tidak ada bagian tepung yang tersisa, tanpa mengaduk berlebihan. (Jangan khawatir dengan beberapa gumpalan.)","Bagi adonan cupcake ke 12 cetakan muffin dan panggang selama 22-24 menit, atau hingga tusuk gigi yang ditusukkan di tengah keluar bersih. Keluarkan dari oven dan biarkan dingin sepenuhnya sebelum diberi frosting.","Untuk membuat frosting, masukkan semua bahan ke dalam blender dan proses hingga benar-benar halus, mulailah dengan 5 sendok makan sirup maple. Cicipi dan tambahkan satu sendok makan sirup lagi jika Anda lebih suka yang lebih manis. Ingat agar tidak berlebihan, atau frosting akan terlalu encer untuk dipipping.","Jika frosting menjadi hangat saat diblender (ini bisa terjadi pada blender yang kuat), pindahkan ke mangkuk dan masukkan ke freezer selama 30 menit sebelum dipipping ke cupcake Anda."],
["Timbang tepung Anda untuk hasil yang paling akurat. Saya sangat menyarankan agar tidak mengandalkan takaran cangkir saat membuat kue. Jika Anda tidak memiliki timbangan dapur, Anda dapat menyendok tepung ke dalam cangkir takar dan menggunakan pisau untuk meratakan kelebihannya, dengan hasil yang serupa. Jangan menyendok langsung dari kantong! Saya menyarankan menggunakan tepung almond yang sangat halus dan tepung oat halus untuk tekstur terbaik. Saya juga pernah mencobanya dengan tepung oat buatan sendiri, dan meskipun hasilnya baik, tepung oat yang lebih halus akan menghasilkan remah yang lebih ringan dan lembut. Gunakan baking powder yang segar dan aktif. Baking powder yang sudah dibuka di lemari dapur selama lebih dari 6 bulan dapat mulai kehilangan keefektifannya. Jika Anda tidak memiliki blender yang bertenaga kuat, rendam kacang mete dalam air panas selama 30 menit sebelum memblender frosting. Ini akan membantu mengembang dan melunak sehingga lebih mudah diblender menjadi frosting yang halus. Pastikan untuk menekan tahu dengan sangat baik untuk membuang kelebihan cairan agar frosting tidak terlalu encer. Jika frosting menjadi hangat saat diblender (ini bisa terjadi pada blender yang kuat), pindahkan ke mangkuk dan masukkan ke freezer selama 30 menit sebelum memipingnya ke cupcake. Biarkan cupcake dingin di cetakan muffin setidaknya 20 menit sebelum disentuh. Lalu pindahkan ke rak pendingin hingga benar-benar dingin SEBELUM diberi frosting. Cupcake ini paling enak pada hari ke-1 hingga ke-2, tetapi Anda dapat menyimpan sisanya di lemari es hingga 4 hari. Simpan dalam wadah tertutup untuk menjaga kelembapan. Atau bekukan dalam wadah kedap udara yang aman untuk freezer hingga 3 bulan."],[]))
R.append((9315360,"Roti Pisang Gandum Hitam (Buckwheat)",
"Roti pisang buckwheat ini lezat, bergizi, dan pas untuk sarapan, camilan, atau hidangan penutup yang sehat.",
"12 potong","1 porsi",
[("Bahan Basah","1 cangkir pisang tumbuk, sekitar 3 pisang sedang atau 2 pisang besar"),("Bahan Basah","⅓ cangkir saus apel tanpa gula"),("Bahan Basah","⅓ cangkir susu kedelai atau almond atau mete"),("Bahan Kering","200 gram tepung buckwheat, sekitar 1.5 cangkir"),("Bahan Kering","¼ cangkir gula kelapa"),("Bahan Kering","2 sendok teh baking powder"),("Bahan Kering","1 sendok teh kayu manis"),("Topping Opsional","¼ cangkir kenari atau pecan cincang"),("Topping Opsional","pisang iris"),("Topping Opsional","gula kelapa untuk ditaburkan")],
["Panaskan oven terlebih dahulu hingga 350°F/176°C dan alasi loyang roti dengan kertas roti.","Haluskan pisang dan masukkan tepat 1 cangkir penuh ke dalam mangkuk sedang, lalu tambahkan susu dan saus apel. Aduk rata. Lalu masukkan semua bahan kering ke dalam mangkuk yang sama dan aduk hingga tercampur.","Tuang adonan ke dalam loyang roti yang sudah dialasi dan beri topping pisang iris, kenari, dan taburan gula kelapa. Pastikan untuk menekan topping dengan lembut ke bagian atas roti.","Panggang hingga tusuk gigi yang ditusukkan di tengah keluar hampir bersih dan kering, sekitar 40-50 menit, tergantung oven Anda."],
["Timbang tepung menggunakan timbangan dapur untuk hasil yang paling akurat. Menyendok tepung langsung dari kantong sering kali membuat tepung yang digunakan terlalu banyak dan dapat membuat roti ini kering dan padat.","Gunakan pisang yang sangat matang. Semakin banyak bintik cokelat, semakin baik, karena akan semakin manis. Karena resep ini menggunakan sangat sedikit pemanis, pastikan pisang Anda memberikan rasa manis yang cukup.","Takar pisang tumbuk Anda. Ukuran pisang sangat bervariasi. Jadi pastikan Anda menggunakan jumlah yang cukup untuk rasa manis dan kelembapan yang optimal. Takar untuk memastikan Anda menggunakan 1 cangkir penuh pisang tumbuk.","Gunakan baking powder yang segar + aktif! Baking powder yang sudah dibuka di lemari dapur selama lebih dari 6 bulan dapat mulai kehilangan keefektifannya.","Gunakan kertas roti untuk mengalasi loyang roti. Meskipun loyang antilengket seharusnya cukup, saya merasa roti jauh lebih mudah dikeluarkan dari loyang saat menggunakan kertas roti. Anda dapat dengan mudah mengangkat roti dan meletakkannya di rak kawat tanpa khawatir patah.","Setiap oven berbeda. Jadi pastikan untuk menguji kematangan roti pisang buckwheat Anda menggunakan tusuk gigi yang ditusukkan di tengah. Ketika keluar hampir kering, roti sudah matang.","Biarkan dingin. Beri waktu ekstra agar roti Anda dingin. Minimal 20-30 menit di rak pendingin disarankan agar roti benar-benar set dan jauh lebih mudah diiris.","Sisa roti dapat disimpan pada suhu ruangan selama 2-3 hari, di lemari es selama 4-5 hari, atau dibekukan dalam wadah kedap udara hingga 3 bulan."],[]))
R.append((9316983,"Sandwich Mentimun Vegan dengan Dill",
"Krim keju yang kental dan kaya dengan mentimun dan dill segar menjadikan ini sandwich mentimun vegan terbaik yang pernah Anda coba!",
"6 porsi","1 porsi",
["1 cangkir krim keju vegan","2 sendok makan dill segar, batang tebal dibuang dan dicincang","1 sendok makan daun bawang, diiris tipis","¼ sendok teh bubuk bawang putih","¼ sendok teh bubuk bawang bombai","garam + merica secukupnya","½ mentimun panjang, diiris tipis (sekitar 18 irisan)","6 lembar roti tawar gandum utuh"],
["Masukkan krim keju bersama dill, daun bawang, dan semua bumbu ke dalam mangkuk pencampur kecil. Aduk hingga tercampur. Cicipi garam dan merica, lalu tambahkan lagi jika diperlukan.","Opsional: Gunakan pisau tajam untuk memotong kulit roti agar menjadi sandwich mentimun klasik. Atau biarkan kulitnya untuk menambah tekstur dan serat.","Oleskan krim keju berbumbu secara melimpah pada 3 lembar roti sandwich, lalu susun irisan mentimun di atasnya dan taburi sedikit garam dan merica pada irisan mentimun jika diinginkan. Letakkan 3 lembar roti sisanya di atas mentimun.","Potong setiap sandwich menjadi dua atau empat bagian dan sajikan."],
["Gunakan mentimun Inggris, bukan mentimun lokal biasa. Yang pertama memiliki lebih sedikit biji dan kulit lebih tipis, sehingga tidak perlu dikupas atau dibuang bijinya. Yang kedua memiliki kulit lebih tebal dan biji yang pahit. Untuk versi bebas minyak: Resep ini bebas minyak sebagaimana tertulis, namun banyak roti tawar kemasan mengandung minyak, jadi pastikan untuk membaca daftar bahannya. Atau, Anda dapat membuat roti gandum utuh bebas minyak sendiri. Pastikan untuk melewatkan tambahan ara dan kenari dalam resep roti tersebut untuk keperluan sandwich ini. Anda boleh menggunakan krim keju vegan kemasan atau buatan sendiri. Jika menggunakan versi buatan sendiri, Anda memerlukan sekitar setengah dari resep kejunya untuk membuat sandwich ini. Sisa sandwich dapat disimpan di lemari es selama 2-3 hari dalam wadah tertutup atau kantong zip-top. Namun, sandwich ini paling enak pada hari yang sama saat dibuat."],[]))
R.append((9317037,"Tahu Renyah Pedas dengan Sayuran",
"Resep tahu renyah pedas ini kaya rasa dan lezat dengan potongan tahu keemasan dan sayuran cerah yang disajikan di atas mi zucchini.",
"4 porsi","1 porsi",
[("Untuk tahu renyah","12 ons (350 gram) tahu padat ekstra, bebas GMO jika memungkinkan"),("Untuk tahu renyah","1 sendok makan kecap asin rendah natrium atau Tamari untuk bebas gluten"),("Untuk tahu renyah","1 sendok makan saus pedas, saya suka Frank's atau sriracha"),("Untuk tahu renyah","2 sendok makan tepung maizena"),("Untuk tahu renyah","1 sendok teh bubuk bawang bombai"),("Untuk saus pedas","⅓ cangkir kecap asin rendah natrium atau Tamari untuk bebas gluten"),("Untuk saus pedas","¼ cangkir gula tebu atau gula pilihan"),("Untuk saus pedas","⅓ cangkir air"),("Untuk saus pedas","2 sendok makan cuka beras"),("Untuk saus pedas","2 sendok makan saus pedas, saya suka Frank's atau sriracha"),("Untuk saus pedas","1 sendok teh bubuk bawang putih"),("Untuk saus pedas","½ sendok teh serpihan cabai merah"),("Untuk saus pedas","2 sendok makan tepung maizena"),("Untuk penyajian","mi zucchini, nasi kembang kol, nasi cokelat, quinoa, atau barley"),("Untuk penyajian","sayuran pilihan Anda, saya menggunakan brokoli dan tomat anggur"),("Untuk penyajian","hiasi dengan biji wijen, chives, daun bawang, daun ketumbar dan/atau serpihan cabai merah")],
[("Tekan tahu","Potong tahu menjadi kubus setengah inci. Lalu letakkan beberapa tisu dapur atau lap dapur bersih di atas talenan dan susun kubus tahu dalam satu lapisan di atasnya. Sekarang tambahkan tisu dapur lagi di atas kubus dan letakkan talenan lain, piring datar, atau loyang di atasnya. Terakhir, letakkan sesuatu yang sangat berat di atasnya seperti wajan besi cor atau buku tebal. Tekan seperti ini selama 15 menit sementara Anda menyiapkan bahan lainnya."),("Untuk tahu","Panaskan oven terlebih dahulu hingga 425°F/218°C dengan mode convection bake dan alasi loyang dengan kertas roti."),("Untuk tahu","Masukkan kubus tahu yang sudah ditekan ke dalam mangkuk pencampur dan aduk perlahan dengan kecap asin dan saus pedas. Lalu tambahkan bubuk bawang bombai dan tepung maizena dan aduk perlahan."),("Untuk tahu","Susun kubus tahu yang sudah dilapisi dalam satu lapisan di atas loyang, sisakan jarak di antara setiap potongan. Panggang selama 20-25 menit, balikkan sekali setelah 10 menit. CATATAN: Jika Anda tidak memiliki oven convection, mungkin perlu waktu sedikit lebih lama untuk mencapai tingkat kerenyahan yang diinginkan."),("Untuk saus","Selagi tahu dipanggang, campurkan semua bahan saus dalam wajan dangkal, kocok hingga tercampur dan didihkan perlahan dengan api sedang-besar hingga mengental, sekitar 2-3 menit."),("Untuk saus","Masukkan tahu renyah yang sudah dipanggang ke dalam wajan berisi saus dan aduk hingga terlapisi."),("Untuk saus","Sajikan dengan biji-bijian, sayuran, dan hiasan pilihan Anda.")],
["Susun kubus tahu dalam satu lapisan dengan jarak di antara setiap potongan. Kubus tidak boleh saling bersentuhan di loyang agar mencapai tingkat kerenyahan maksimal.","Jika Anda tidak memiliki oven convection, mungkin perlu beberapa menit tambahan agar tahu menjadi renyah. Panggang hingga tingkat kerenyahan yang diinginkan tercapai.","Untuk tekstur terbaik, rencanakan untuk menikmati hidangan ini segera. Semakin lama direndam dalam saus, bagian luarnya yang renyah akan semakin berkurang."],[]))
build(R,'/mnt/c/WSL/davita/translations/tid1/part2.json')
