from mk import *
R=[]
R.append((9318277,"Pancake Vegan Paling Mudah dan Paling Empuk",
"Pancake vegan paling empuk bisa tersaji di piring Anda dalam waktu singkat dengan resep super sederhana yang hanya memakai 4 bahan ini.",
"10 pancake","1 pancake",
["1 cangkir tepung terigu serbaguna tanpa pemutih atau tepung gandum utuh","1 cangkir susu mete tanpa pemanis atau susu bebas susu sapi pilihan Anda","1 sendok makan baking powder","1 sendok makan gula kelapa tanpa pemurnian, opsional","1 sendok teh ekstrak vanila murni, opsional"],
["Masukkan tepung, gula, dan baking powder ke dalam mangkuk besar dan kocok hingga tercampur. Lalu tambahkan susu dan vanila, aduk hingga tercampur, jangan terlalu lama.","Panaskan wajan datar antilengket dengan api sedang dan setelah panas, tuang adonan dengan sendok sayur untuk membuat pancake berdiameter sekitar 4 inci. Masak selama sekitar 3-5 menit hingga muncul beberapa gelembung di permukaan. Lalu balikkan dan masak sisi lainnya selama 3-5 menit lagi hingga matang sempurna.","Sajikan dengan sirup maple atau buah segar dan selamat menikmati."],
["Jangan mengaduk adonan pancake terlalu lama. Jika ada beberapa gumpalan, itu tidak masalah. Jangan tergoda mengaduk sampai benar-benar halus karena dapat mengubah tekstur pancake Anda. Panaskan wajan atau griddle terlebih dahulu. Wajan harus panas sebelum adonan dituang agar tidak lengket dan matang merata. Gunakan api sedang untuk memasak pancake. Meskipun wajan harus panas, bukan berarti Anda harus memakai api besar. Hal ini dapat menyebabkan matang tidak merata, dengan bagian luar renyah dan bagian tengah lembek. Balikkan pancake HANYA SEKALI. Gelembung akan muncul di permukaan pancake tak lama setelah dimasak, tetapi tunggu hingga ada beberapa gelembung dan pancake telah dimasak setidaknya 3-4 menit sebelum dibalik. Terlalu sering membalik dapat membuatnya mengempis dan kehilangan keempukannya yang luar biasa. Pancake ini juga cocok dengan tepung gandum utuh. Teksturnya akan sedikit kurang empuk, tetapi tetap lezat. Pancake paling enak saat baru dibuat, tetapi Anda dapat menyimpan sisanya di lemari es dan memanaskannya kembali dengan pemanggang roti untuk dinikmati dalam 1-2 hari. Anda juga dapat membekukannya dan memanaskannya kembali dengan pemanggang roti langsung dari kondisi beku."],[]))
R.append((9320396,"Mi Zucchini Vegan dengan Saus Bolognese",
"Saus Bolognese sayuran yang mengenyangkan, kaya rasa, dan sangat lezat, disajikan di atas mi zucchini vegan hasil spiral, hidangan nyaman Anda tanpa rasa bersalah!",
"5 porsi","1 porsi",
["6 zucchini ukuran sedang","1 cangkir kenari atau biji labu mentah","½ cangkir tomat kering","4-5 cangkir kuntum kembang kol, sekitar setengah kembang kol ukuran sedang","8 ons jamur cremini, sekitar 8-10 jamur kecil","32 ons (4 cangkir) saus tomat atau puree tomat pilihan","1 sendok teh bubuk bawang putih","½ sendok teh oregano kering","½ sendok teh basil kering","garam + merica secukupnya",("Hiasan Opsional","keju parmesan vegan"),("Hiasan Opsional","serpihan cabai"),("Hiasan Opsional","basil atau peterseli segar")],
["Spiral zucchini menggunakan spiralizer. Letakkan mi dalam saringan yang diletakkan di atas mangkuk besar dan taburi zucchini dengan garam secara melimpah. Aduk dengan tangan dan sisihkan selama 30 menit atau lebih lama. (Jika dipersiapkan lebih awal, langkah ini dapat dilakukan beberapa jam sebelum memasak.)","Sementara itu, masukkan kenari dan tomat kering ke dalam food processor dan pulse hingga remah tetapi jangan diproses berlebihan. Biarkan tetap kasar. Pindahkan ke wajan dalam.","Kerjakan dalam beberapa tahap kecil dan proses kembang kol dan jamur berikutnya. Sekali lagi, Anda ingin menjaga teksturnya tetap remah dan tidak diproses berlebihan. Pindahkan ke wajan yang sama dengan campuran kenari dan tambahkan semua bumbu.","Aduk rata dan tumis selama 5-7 menit hingga sayuran lunak dan menyusut. Lalu tuangkan saus tomat dan didihkan perlahan selama 10-15 menit.","Terakhir, hangatkan mi zucchini perlahan dalam wajan selama 1-2 menit. JANGAN dimasak atau akan menjadi terlalu lunak. Cukup hangatkan saja. Lalu sajikan dengan saus bolognese."],
["Jangan memproses sayuran berlebihan. Saus ini paling enak dengan tekstur.","Jika ada potongan besar yang membandel saat memproses sayuran, masukkan ke dalam tahap berikutnya, daripada terus memprosesnya, agar sisanya tidak terproses berlebihan.","JANGAN memasak mi zucchini terlalu matang. Mi paling enak dengan sedikit gigitan.","Pindahkan zoodles ke mangkuk segera setelah dihangatkan. Jangan biarkan terlalu lama di wajan panas, atau bisa menjadi terlalu lunak.","Untuk versi bebas kacang, gunakan biji labu/pepita atau biji bunga matahari.","Untuk versi bebas minyak, gunakan tomat kering yang dikemas dalam kantong vakum, bukan yang dalam toples.","Simpan sisa saus dan zoodles dalam wadah terpisah agar tidak lembek, hingga 3 hari."],[]))
R.append((9322650,"Nugget Buncis Panggang [Bebas Alergen]",
"Nugget buncis yang renyah, kaya rasa, dan lezat ini sangat mudah dibuat dan dipanggang dengan sempurna.",
"3 porsi (menghasilkan 15 nugget)","1 porsi",
["1 kaleng 15 ons buncis, ditiriskan & dibilas (atau 1.5 cangkir buncis matang)","¼ cangkir tomat kering, dipadatkan perlahan","½ bawang merah kecil, dicincang kasar","2-3 siung bawang putih, dikupas","½ sendok teh bumbu unggas (poultry seasoning)","½ sendok teh garam laut","2 sendok makan oat gulung, bebas gluten jika diinginkan",("Saus Cocolan Opsional","mayo sriracha"),("Saus Cocolan Opsional","saus tomat"),("Saus Cocolan Opsional","honey mustard vegan")],
["Panaskan oven terlebih dahulu hingga 400 derajat F (204 derajat C) dan alasi loyang dengan kertas roti. Sisihkan.","Masukkan semua bahan ke dalam food processor dan pulse hingga tercincang halus dan tercampur, tetapi tidak menjadi puree. (Anda ingin mempertahankan sedikit tekstur.)","Remas campuran buncis menjadi bola seukuran bola golf di tangan Anda, lalu pipihkan perlahan dan bentuk menjadi cakram. Letakkan di atas loyang dan ulangi dengan sisa adonan. Anda akan mendapatkan 15 nugget.","Panggang selama 25-30 menit, balikkan sekali di pertengahan waktu. Sajikan dengan saus cocolan pilihan, dan selamat menikmati."],
["Perlu diketahui, nugget buncis ini TIDAK berasa seperti ayam. Nugget ini tidak dimaksudkan sebagai pengganti vegan untuk nugget ayam. Nugget ini lezat dan luar biasa dengan sendirinya! Jangan memproses bahan terlalu lama. Sisakan beberapa potongan yang lebih kasar untuk mendapatkan tekstur terbaik nugget buncis Anda. Berhati-hatilah saat membalik. Jangan memaksa membalik nugget jika tidak mudah terangkat dari kertas roti atau nugget bisa patah. Jika nugget tidak mudah terangkat, masukkan kembali loyang ke oven selama beberapa menit lagi dan coba lagi. Semakin lama dimasak, semakin mudah dibalik. Waktu memanggang akan bervariasi tergantung ukuran nugget Anda. Sisa nugget dapat disimpan di lemari es selama 3-4 hari dalam wadah tertutup atau dibekukan dalam wadah kedap udara hingga 3 bulan. Pisahkan lapisan nugget dengan kertas roti agar tidak lengket. Ukuran porsi adalah ⅓ resep, sekitar 5 nugget."],[]))
R.append((9323221,"Ayam Marsala Seitan",
"Hidangan klasik Italia versi vegan ini akan membuat Anda terpukau! Ayam marsala seitan ini lembap, empuk, kaya rasa, dan benar-benar bikin ketagihan!",
"6 porsi","1 porsi",
[("Untuk ayam seitan","½ cangkir kacang cannellini putih"),("Untuk ayam seitan","2 sendok makan tahini"),("Untuk ayam seitan","3 sendok makan ragi nutrisi"),("Untuk ayam seitan","2 sendok teh bubuk bawang bombai"),("Untuk ayam seitan","2 sendok teh bubuk bawang putih"),("Untuk ayam seitan","2 sendok teh bumbu unggas (poultry seasoning)"),("Untuk ayam seitan","1 sendok teh garam laut"),("Untuk ayam seitan","⅔ cangkir kaldu sayuran"),("Untuk ayam seitan","210 gram gluten gandum vital, sekitar 1 ¾ cangkir"),("Untuk cairan memasak","3-4 cangkir kaldu sayuran"),("Untuk saus Marsala","2 cangkir kaldu sayuran, dibagi"),("Untuk saus Marsala","½ cangkir kacang mete mentah"),("Untuk saus Marsala","1-2 sendok makan mentega vegan, opsional, gunakan air atau kaldu untuk bebas minyak"),("Untuk saus Marsala","8 ons jamur cremini, diiris"),("Untuk saus Marsala","2-3 siung bawang putih, dicincang halus"),("Untuk saus Marsala","⅛ sendok teh thyme kering"),("Untuk saus Marsala","⅔ cangkir Marsala"),("Untuk Penyajian (Opsional)","peterseli segar untuk hiasan")],
[("Untuk ayam seitan","Panaskan oven terlebih dahulu hingga 350 derajat F (177 derajat C)."),("Untuk ayam seitan","Masukkan semua bahan ayam vegan KECUALI gluten gandum vital ke dalam food processor dan proses hingga halus. Lalu tambahkan setengah dari gluten gandum vital dan pulse hingga tercampur. Tambahkan setengah sisanya dan pulse hingga tercampur lagi."),("Untuk ayam seitan","Pindahkan campuran ke permukaan bersih atau talenan dan uleni sekitar 30 detik, tetapi jangan berlebihan. Bentuk adonan menjadi silinder atau cakram dan bagi menjadi 6 potong dengan ukuran kira-kira sama. (Anda dapat menggunakan timbangan dapur jika ingin ukurannya tepat, tetapi tidak perlu.)"),("Untuk ayam seitan","Gunakan telapak tangan, atau penggiling adonan untuk memipihkan setiap potong menjadi bentuk \"fillet ayam\". Tidak perlu terlihat sempurna. Gilas tipis karena ukurannya akan hampir dua kali lipat saat dimasak."),("Untuk ayam seitan","Gunakan wadah tahan oven dengan tutup, seperti dutch oven, dan tambahkan lapisan tipis kaldu sayuran di dasarnya. Lalu susun fillet Anda di dalamnya, buat 2 lapisan, dan tambahkan kaldu secukupnya hingga menutupi seluruhnya sekitar satu inci di atas lapisan teratas. Pasang tutup dan panggang selama 80 menit lalu keluarkan dari oven."),("Untuk ayam seitan","Jika Anda menyiapkan ini lebih awal, pindahkan fillet ke wadah untuk didinginkan di lemari es semalaman dan selesaikan memasaknya pada hari penyajian. (Simpan kaldunya untuk diminum, rasanya enak, jangan dibuang! 😉)"),("Untuk saus Marsala","Selagi fillet berada di oven, siapkan saus Anda. Pertama, masukkan kacang mete bersama SATU cangkir kaldu sayuran ke dalam blender berkecepatan tinggi untuk membuat \"krim\" kocok Anda. Blender hingga halus dan sisihkan."),("Untuk saus Marsala","Dalam wajan besar dan dalam, lelehkan mentega Anda (jika digunakan) dan masukkan jamur iris, bawang putih, dan thyme. Tumis hingga jamur menyusut, sekitar 3-4 menit."),("Untuk saus Marsala","Lalu tuangkan Marsala, sisa satu cangkir kaldu, dan krim mete vegan yang baru Anda buat. Didihkan perlahan dengan api sedang selama 5-8 menit hingga sedikit mengental."),("Untuk saus Marsala","Setelah fillet keluar dari oven, pindahkan ke wajan berisi saus dan didihkan perlahan bersama selama 2-3 menit. Sajikan dengan peterseli segar dan selamat menikmati.")],
["Jika Anda tidak memiliki blender berkecepatan tinggi, rendam kacang mete terlebih dahulu dalam air panas selama 30 menit lalu tiriskan sebelum diblender agar lebih mudah hancur. Gunakan timbangan dapur untuk menimbang gluten gandum vital demi hasil dan tekstur yang paling akurat. Untuk kaldunya, pastikan menggunakan jenis yang sangat kaya rasa dan Anda sukai. Saya menyukai versi ini. Ayam seitan akan menyerap sebagian rasa kaldu saat dipanggang, jadi Anda tidak ingin menggunakan jenis yang hambar. Jangan menguleni adonan terlalu lama. Cukup hingga Anda melihat serat terbentuk, sekitar 30 detik. Untuk ukuran porsi yang sama, gunakan timbangan dapur saat membagi adonan menjadi enam potong. Tidak sepenuhnya diperlukan, hanya jika Anda ingin sempurna. Gunakan wadah tahan oven dengan tutup untuk memanggang. Jika Anda tidak memiliki wadah dengan tutup, gunakan wadah dalam tahan oven apa pun dan tutup bagian atasnya dengan selapis kertas roti, lalu aluminium foil. Gilas dada ayam vegan hingga tipis. Ukurannya akan hampir dua kali lipat di oven. Anda ingin fillet mendidih perlahan dalam kaldu dan TIDAK meluap karena mendidih keras. Memasaknya perlahan menghasilkan tekstur terbaik. Jangan menaikkan suhu oven untuk mencoba memasaknya lebih cepat. Sisa makanan dapat disimpan di lemari es dalam wadah tertutup selama 3-4 hari atau dibekukan dalam wadah kedap udara yang aman untuk freezer hingga 6 bulan."],[]))
R.append((9327187,"Kentang Penyet Air Fryer",
"Renyah di luar, empuk di tengah. Kentang penyet air fryer yang gurih dan beraroma bawang putih ini wajib dicoba!",
"4 porsi","1 porsi",
["1 pon kentang Yukon Gold, sekitar 4 kentang kecil","2 sendok makan mentega vegan atau margarin yang dilelehkan, ganti dengan minyak goreng jika diinginkan ATAU kaldu sayuran untuk bebas minyak","3 siung bawang putih, dikupas + dicincang halus","1 sendok teh peterseli kering","½ sendok teh garam laut atau secukupnya","¼ sendok teh merica hitam atau secukupnya"],
["Sikat kentang hingga sangat bersih karena Anda akan memakan kulitnya. Lalu masukkan ke dalam panci dan isi dengan air hingga satu inci di atas kentang. Tambahkan satu sendok teh garam dan didihkan. Masak hingga kentang dapat ditusuk garpu, tetapi masih utuh, sekitar 18 menit. JANGAN dimasak terlalu lama, atau kentang akan hancur saat dipenyet.","Selagi kentang dimasak, lelehkan mentega (jika digunakan) dalam panci kecil. Lalu campurkan bawang putih cincang dan bumbu dan sisihkan.","Tiriskan kentang dan pindahkan ke talenan untuk didinginkan selama beberapa menit, hingga mudah dipegang. Gunakan garpu besar atau penumbuk kentang untuk memenyet kentang dengan hati-hati hingga pipih setebal sekitar setengah inci. (Hati-hati: jangan menekan terlalu keras, atau kentang bisa pecah.)","Oleskan kedua sisi kentang dengan campuran mentega berbumbu Anda dan pindahkan ke keranjang, sisakan banyak ruang di antara setiap kentang. Goreng dengan air fryer pada 400 derajat F selama 8-12 menit, atau hingga tingkat kerenyahan yang diinginkan tercapai."],
["Garami air rebusan ATAU gunakan kaldu untuk merebus kentang agar rasanya lebih kaya. Gunakan kentang kecil untuk hasil terbaik. Kentang besar akan memakan waktu memasak lebih lama, tidak akan sekrispi itu, dan lebih sulit ditangani setelah dipenyet. Tempatkan kentang di keranjang dengan banyak ruang di antara setiap kentang, agar udara bersirkulasi dengan baik, dan agar Anda tidak perlu membaliknya. Biarkan kentang dingin selama beberapa menit setelah direbus agar lebih mudah ditangani dan dipenyet tanpa pecah."],[]))
R.append((9327887,"Salad Stroberi dengan Dressing Blueberry Basil",
"Manis, asam segar, dan penuh rasa segar, salad bayam stroberi dengan dressing blueberry basil ini adalah musim panas di setiap suapan.",
"4 porsi","1 porsi",
["5 ons bayam muda","1 pon stroberi segar (dibuang tangkainya dan diiris)","1/3 cangkir almond iris","1 cangkir blueberry","1/4 cangkir basil segar","2 sendok makan cuka anggur putih","1 sendok makan sirup maple (opsional)","garam + merica (secukupnya)"],
["Masukkan bayam muda, stroberi iris, dan almond ke dalam mangkuk atau piring saji.","Lalu, dalam blender kecil, blender semua bahan dressing salad. Cicipi garam dan merica, lalu sesuaikan jika perlu.","Siramkan dressing di atas salad, atau sajikan terpisah."],[],[]))
R.append((9328013,"Spaghetti Ubi Jalar [Aglio e Olio]",
"Pasta aglio e olio mendapat sentuhan sehat dengan spaghetti ubi jalar ini. Pedas, beraroma bawang putih dan, meski bernama demikian, bebas minyak!",
"4 porsi","1 porsi",
["4 ubi jalar ukuran sedang, gunakan ubi yang ramping dan panjang","¼ cangkir aquafaba atau kaldu sayuran","4-5 siung bawang putih, dicincang halus","2 sendok teh peterseli kering","1 sendok teh serpihan cabai merah atau secukupnya","½ sendok teh garam laut atau secukupnya","5 ons (142 gram) bayam muda, sekitar 4 cangkir dipadatkan",("Untuk Penyajian (opsional)","keju parmesan vegan"),("Untuk Penyajian (opsional)","serpihan cabai merah")],
["Kupas dan spiral ubi jalar menjadi spaghetti. Sisihkan.","Gunakan wajan besar dan masukkan aquafaba (atau kaldu), bersama bawang putih, peterseli, serpihan cabai, dan garam. Tumis dengan api sedang selama 2-3 menit, awasi dengan cermat agar tidak gosong.","Masukkan spaghetti ubi jalar ke dalam wajan dan aduk hingga terlapisi bumbu secara merata, lalu masak dengan api sedang-besar selama 5-7 menit, hingga sedikit lunak, tetapi jangan dimasak berlebihan. Tambahkan beberapa percikan air atau kaldu jika diperlukan, agar mi tidak lengket di wajan.","Matikan api dan masukkan bayam. Aduk hingga layu lalu sajikan."],
["Agar mudah dispiral, gunakan ubi jalar yang ramping, panjang, dan lurus. Atau Anda dapat membeli mi ubi jalar yang sudah dispiral dari toko bahan makanan untuk menghemat waktu. Jika menggunakan aquafaba kalengan yang mengandung garam, Anda mungkin perlu mengurangi garam dalam resep, lalu cicipi dan tambahkan lagi jika diperlukan. JANGAN memasak mi terlalu matang. Anda ingin mi empuk tetapi tetap renyah, dan tidak terlalu lunak, untuk tekstur terbaik dan menyerupai pasta 'al dente'. Jika Anda tidak punya bayam, Anda dapat menggantinya dengan sayuran hijau lain. Masak dahulu sayuran hijau jika diperlukan. Untuk rasa yang kurang pedas, kurangi serpihan cabai merah hingga setengahnya. Hidangan ini secara tradisional pedas, tetapi pastikan menyesuaikan pedasnya dengan selera dan toleransi Anda. Sisa makanan dapat disimpan di lemari es dalam wadah tertutup selama 3-4 hari."],[]))
R.append((9329195,"Sup Barley Lentil",
"Sup barley lentil yang hangat dan mengenyangkan ini penuh biji-bijian sehat, sayuran, dan bahan-bahan sederhana yang direbus menjadi hidangan yang menenangkan.",
"6 porsi","1 porsi",
["1 sendok makan minyak alpukat atau ¼ cangkir kaldu","1 bawang bombai kuning, dipotong dadu","2-3 siung bawang putih, dicincang halus","2 wortel besar, diiris","2 batang seledri, diiris","1 cangkir lentil hijau atau cokelat, dibilas + dipilah","½ cangkir barley mutiara","6 cangkir kaldu sayuran","1 cangkir saus tomat","2 lembar daun salam","1 sendok teh jintan","1 sendok teh paprika asap","5 ons bayam muda","1-2 sendok makan air lemon","garam + merica secukupnya"],
["Masukkan minyak goreng atau 1/4 cangkir kaldu ke dalam panci atau wajan Anda. Lalu tumis bawang bombai, bawang putih, wortel, dan seledri hingga lunak, sekitar 5 menit.","Masukkan lentil, barley, kaldu sayuran, saus tomat, daun salam, jintan, dan paprika ke dalam panci Anda dan aduk rata semuanya. Didihkan, lalu kecilkan api dan didihkan perlahan hingga lentil dan barley matang, sekitar 25 menit.","Matikan api dan buang daun salam. Lalu, aduk air lemon dan bayam segar hingga layu. Cicipi garam dan merica, lalu sesuaikan jika perlu."],
["Gunakan kaldu yang sangat kaya rasa! Jika kaldu Anda kurang berasa, pastikan menyesuaikan bumbunya.","Jika Anda tidak memiliki kaldu, Anda dapat membuatnya dengan resep bumbu kaldu mudah ini. (Saya sangat menyarankan kaldu ini karena rasanya yang luar biasa.)","Tergantung kekentalan yang Anda sukai, gunakan 6-8 cangkir kaldu sayuran. Untuk sup yang lebih kental, gunakan enam cangkir. Untuk sup yang lebih encer, gunakan delapan. Ingat: sup akan menyerap lebih banyak cairan saat dingin.","Sisa sup dapat disimpan di lemari es selama 3-4 hari atau dibekukan hingga 3 bulan."],[]))
R.append((9330923,"Selai Stroberi Tanpa Gula [Tanpa Pektin!]",
"Anda hanya memerlukan 2 bahan untuk selai stroberi tanpa gula yang sangat lezat ini!",
"28 porsi (2 sendok makan per porsi)","1 porsi",
["2 pon stroberi, dicuci & dibuang tangkainya (sekitar 5 cangkir dibelah empat)","⅓ cangkir biji chia","2 sendok makan sirup maple, opsional"],
["Belah empat stroberi dan masukkan ke dalam panci besar. Masak dengan api sedang selama 6-8 menit, hingga lunak dan menggelembung.","Lalu angkat dari api dan gunakan penumbuk kentang untuk menumbuk stroberi dengan lembut, tetapi tetap sisakan beberapa potongan buah yang kasar. Masukkan biji chia dan sirup maple, jika digunakan, lalu aduk rata.","Sisihkan agar sedikit dingin, lalu bagi selai ke dalam toples bersih yang kedap udara. Selai akan mengental sempurna setelah didinginkan di lemari es semalaman atau setidaknya 4 jam. Simpan di lemari es untuk digunakan dalam 1 minggu atau bekukan hingga 4 bulan."],
["Gunakan toples BERSIH untuk menyimpan selai stroberi Anda. Jika selai tampak sedikit berair setelah dimasak, jangan khawatir. Saat dingin, biji chia akan terus menyerap cairan dan menghasilkan selai kental dengan tekstur sempurna. Saya menggunakan biji chia hitam, karena paling mudah ditemukan di tempat saya tinggal. Biji ini sedikit menggelapkan warna selai, tetapi Anda dapat menggunakan biji chia putih untuk selai yang warnanya lebih cerah, jika tersedia. Untuk konsistensi yang sedikit lebih encer, kurangi biji chia menjadi ¼ cangkir. Menghasilkan sekitar 3.5 cangkir selai stroberi. Bagi ke dalam toples kecil dan simpan satu di lemari es lalu bekukan sisanya untuk digunakan nanti. Selai stroberi Anda dapat disimpan di lemari es selama 1 minggu, atau dibekukan hingga 4 bulan."],[]))
build(R,'/mnt/c/WSL/davita/translations/tid1/part3.json')
