from mk import *
R=[]
R.append((9390900,"Kembang Kol Asam Manis Vegan",
"Kembang kol asam manis vegan ini manis, lengket, dan sangat lezat!",
"4 porsi","1 porsi",
[("Untuk kembang kol","4 cangkir kuntum kembang kol, sekitar 1 kepala kecil dipotong seukuran gigitan"),("Untuk kembang kol","½ cangkir tepung beras cokelat"),("Untuk kembang kol","1 sendok teh bubuk bawang putih"),("Untuk kembang kol","1 sendok teh bubuk bawang bombai"),("Untuk kembang kol","½ sendok teh garam laut, opsional"),("Untuk kembang kol","½ cangkir air"),("Untuk saus asam manis vegan","½ cangkir sirup maple"),("Untuk saus asam manis vegan","¼ cangkir cuka beras"),("Untuk saus asam manis vegan","¼ cangkir tamari rendah natrium atau kecap asin jika tidak menghindari gluten"),("Untuk saus asam manis vegan","¼ cangkir saus tomat"),("Untuk saus asam manis vegan","1 sendok teh bubuk bawang putih"),("Untuk saus asam manis vegan","1 sendok makan tepung beras cokelat, opsional, untuk mengentalkan saus"),("Untuk saus asam manis vegan","1 paprika merah, diiris"),("Untuk saus asam manis vegan","1 cangkir nanas, dipotong dadu"),("Untuk Penyajian","nasi cokelat atau quinoa"),("Untuk Penyajian","daun bawang"),("Untuk Penyajian","biji wijen")],
["Panaskan oven terlebih dahulu hingga 425 derajat F (218 derajat C) dan alasi loyang dengan kertas roti.","Potong kembang kol menjadi potongan kecil seukuran gigitan dan sisihkan. Lalu masukkan sisa bahan kembang kol ke dalam mangkuk pencampur sedang dan kocok hingga tercampur, untuk membuat adonan basah. Masukkan potongan kembang kol ke dalam adonan dan aduk rata hingga semua potongan terlapisi merata.","Susun kembang kol yang sudah dilapisi di atas loyang dalam satu lapisan, tetapi jangan menuang semuanya dari mangkuk. Anda tidak ingin ada kelebihan adonan di loyang atau potongan bisa saling menempel dan mencegah kerenyahan.","Panggang selama 20-25 menit, balikkan sekali di pertengahan waktu hingga tingkat kerenyahan yang diinginkan tercapai.","Selagi kembang kol dipanggang, siapkan saus asam manis. Kocok semua bahan saus (kecuali paprika dan nanas) dalam mangkuk kecil atau gelas ukur dan sisihkan.","Lalu tumis paprika merah dan potongan nanas dalam wajan besar dengan satu sendok makan air atau kaldu, agar tidak lengket. Lakukan dengan api sedang-besar hingga sedikit kecokelatan. Lalu kecilkan api ke sedang-kecil dan tuang saus ke dalam wajan lalu didihkan perlahan hingga sedikit mengental, sekitar 5 menit.","Sekarang, kembang kol Anda seharusnya sudah siap. Masukkan ke dalam wajan berisi saus dan aduk perlahan hingga setiap potongan terlapisi merata.","Sajikan di atas nasi atau quinoa dan hiasi dengan biji wijen dan daun bawang."],
["Jangan menuang kembang kol ke loyang setelah dilapisi adonan. Anda tidak ingin ada kelebihan adonan di loyang, atau akan lengket di loyang, dan potongan bisa saling menempel, mengurangi bagian luar yang renyah. Luangkan waktu untuk menyusun kembang kol berlapis adonan dalam satu lapisan, satu potong demi satu potong, dengan banyak ruang di antaranya untuk hasil terbaik. Paling enak saat baru dibuat tetapi sisa makanan dapat disimpan di lemari es dalam wadah tertutup selama 3-4 hari."],[]))
R.append((9391250,"Salad Buncis Alpukat",
"Salad buncis alpukat yang segar dan cerah, kaya, penuh rasa, dan ternyata sangat mengenyangkan! Siap hanya dalam 15 menit.",
"3 porsi","1 porsi",
["1.5 cangkir buncis atau garbanzo, matang atau kalengan (sekitar 1 kaleng 15 ons)","1 alpukat ukuran sedang, dipotong dadu","1 tomat ukuran sedang, dipotong seukuran gigitan","¼ cangkir bawang merah, dipotong dadu","2-3 sendok makan basil segar, dicincang halus, opsional","1 sendok teh oregano kering","½ sendok teh garam laut atau secukupnya","¼ sendok teh bubuk bawang putih","2 sendok makan aquafaba"],
["Jika menggunakan buncis kalengan, tiriskan, tetapi sisihkan dua sendok makan aquafaba (cairan buncis). Jika menggunakan buncis matang, sisihkan air rebusannya.","Cincang bahan Anda dan masukkan ke dalam mangkuk sedang. Untuk alpukat, belah menjadi dua, buang bijinya, dan gunakan pisau untuk memotong daging buah menjadi kotak-kotak, langsung di dalam kulitnya. Lalu keruk dengan sendok dan masukkan ke dalam mangkuk Anda.","Aduk perlahan untuk mencampur dan mendistribusikan rasa secara merata. Nikmati segera."],
["Jika menggunakan buncis kalengan, gunakan yang tanpa garam, atau kurangi garam yang diminta dalam resep dan sesuaikan dengan selera. Jika menggunakan buncis matang, sisihkan air rebusannya untuk salad ini, dan hidangan mendatang. Saya memasak buncis tanpa garam dan membekukan aquafaba/air rebusan dalam cetakan es batu untuk digunakan nanti. Setelah beku, pindahkan es batu aquafaba ke wadah atau kantong zip-top dan simpan beku hingga diperlukan. Salad ini paling enak pada hari yang sama saat dibuat. Jika Anda berencana membuatnya lebih awal sebelum disajikan, peras air lemon pada alpukat Anda agar tidak menjadi cokelat."],[]))
R.append((9396324,"Pancake Pisang Buckwheat",
"Pancake pisang buckwheat yang empuk dan sangat lezat dengan hanya 6 bahan yang diperlukan.",
"8 pancake 4 inci","1 porsi",
["⅓ cangkir pisang tumbuk, sekitar 1 pisang ukuran sedang","1 cangkir susu nabati","2 sendok teh ekstrak vanila murni","120 gram tepung buckwheat, sekitar 1 cangkir","1 sendok teh baking powder","½ sendok teh kayu manis"],
["Tumbuk pisang dalam mangkuk pencampur sedang, lalu tambahkan susu dan vanila. Aduk rata. Lalu masukkan semua bahan kering dan aduk hingga tercampur, tetapi jangan khawatir jika masih ada beberapa gumpalan.","Diamkan adonan pancake selama 2-3 menit sementara Anda memanaskan wajan datar atau wajan antilengket dengan api sedang.","Tuang adonan dengan sendok sayur untuk membuat pancake berdiameter sekitar 3-4 inci dan masak hingga ada gelembung di atasnya dan tepinya tampak kecokelatan. Lalu balikkan dan lanjutkan memasak 2-3 menit lagi.","Sajikan dengan irisan pisang, beri, sirup maple, dan/atau kelapa parut."],
["Gunakan baking powder yang segar dan aktif. Baking powder yang sudah dibuka dan disimpan di lemari dapur selama beberapa bulan dapat mulai kehilangan keefektifannya.","Tidak perlu mengaduk adonan pancake terlalu lama. Jika ada beberapa gumpalan, itu tidak masalah. Cukup aduk hingga tercampur dan tidak ada bagian tepung yang tersisa.","Panaskan wajan atau griddle terlebih dahulu. Wajan harus panas sebelum adonan dituang agar tidak lengket dan matang merata.","Gunakan api sedang untuk memasak pancake. Meskipun wajan harus panas, bukan berarti Anda harus memakai api besar. Hal ini dapat menyebabkan matang tidak merata, dengan bagian luar renyah dan bagian tengah lembek.","Balikkan pancake HANYA SEKALI. Ketika tepinya kecokelatan dan ada beberapa gelembung di atasnya. Terlalu sering membalik dapat membuatnya mengempis dan menghasilkan tekstur pancake yang lebih padat.","Sisa makanan dapat disimpan di lemari es selama 2-3 hari, panaskan kembali dengan pemanggang roti, di atas griddle, atau di wajan di atas kompor. Atau bekukan dalam wadah kedap udara atau kantong ziptop setelah benar-benar dingin hingga suhu ruangan."],[]))
R.append((9396581,"Stik French Toast Vegan",
"Tanpa telur untuk stik french toast vegan yang sangat lezat ini! Cukup blender, celup, dan masak.",
"8 porsi","1 porsi",
["8 lembar roti tebal yang kokoh berumur 1 hari, saya menyukai roti Prancis atau sourdough, tetapi apa pun yang kokoh dan sedikit padat.","13.5 ons (400 ml) santan lite, jenis yang dikemas dalam kaleng","12 ons (350 gram) tahu padat ekstra","2-3 sendok makan sirup maple atau sirup kurma","2 sendok teh ekstrak vanila murni","½ sendok teh kayu manis bubuk",("Topping Opsional","blueberry, stroberi, raspberry segar atau irisan pisang"),("Topping Opsional","selai almond"),("Topping Opsional","sirup maple"),("Topping Opsional","gula bubuk")],
["Iris roti Anda menjadi strip setebal sekitar satu inci dan sisihkan.","Masukkan semua bahan lainnya (semuanya kecuali roti) ke dalam blender dan proses hingga halus.","Tuang campuran ke dalam mangkuk lebar dan dangkal, kerjakan dalam beberapa tahap jika perlu. Lalu celupkan beberapa stik roti Anda pada semua sisi, biarkan menyerap adonan selama 30-60 detik.","Panaskan griddle antilengket, wajan besar, atau wajan besi cor yang sudah berbumbu dengan api sedang. Olesi dengan lemak terlebih dahulu jika perlu. Lalu masak stik french toast Anda selama 2-3 menit di setiap sisi, kerjakan dalam beberapa tahap sesuai kebutuhan, tergantung ukuran griddle atau wajan Anda.","Sajikan dengan taburan gula bubuk, beri segar, sirup maple, atau nikmati begitu saja."],
["Gunakan roti yang kokoh dan lebih padat daripada roti tawar sandwich biasa dan potong stik Anda menjadi potongan setebal satu inci. Anda tidak ingin terlalu tipis atau bisa patah setelah direndam dalam adonan. Usahakan memotong stik french toast Anda menjadi potongan berukuran serupa agar matang merata. Pastikan memanaskan wajan atau griddle terlebih dahulu sebelum memasak french toast Anda. Jika tidak dipanaskan terlebih dahulu, adonan bisa jatuh dan lengket di wajan. Untuk rendah lemak, Anda dapat menggunakan susu nabati apa pun seperti susu almond atau susu kedelai sebagai pengganti santan. Resep akan tetap berhasil, tetapi tidak sekaya itu. Untuk bebas gluten, gunakan roti bebas gluten favorit Anda."],[]))
R.append((9397040,"Nanas Air Fryer",
"Nanas air fryer yang manis dan beraroma karamel! Hidangan penutup atau pendamping yang lebih sehat dan sempurna yang pasti ingin Anda lahap.",
"4 porsi","1 porsi",
["2 cangkir penuh nanas iris, dari sekitar ½ nanas kecil","1 sendok makan mentega vegan atau margarin, dilelehkan, opsional","2 sendok makan sirup maple","1 sendok teh kayu manis",("Saus Cocolan Cabai Jeruk Nipis Opsional","3 sendok makan krim mete atau mayo vegan"),("Saus Cocolan Cabai Jeruk Nipis Opsional","1 sendok makan air jeruk nipis, sekitar setengah jeruk nipis"),("Saus Cocolan Cabai Jeruk Nipis Opsional","½ sendok teh bubuk cabai")],
["Kupas, buang bagian tengah dan iris nanas Anda lalu masukkan sekitar 2 cangkir penuh ke dalam mangkuk pencampur.","Campurkan mentega yang dilelehkan, sirup maple dan kayu manis dalam mangkuk kecil, lalu tuang ke atas irisan nanas Anda. Aduk perlahan agar irisan terlapisi merata.","Lalu letakkan dalam satu lapisan (sedikit tumpang tindih tidak masalah) di keranjang air fryer Anda dan goreng dengan air fryer pada 380 derajat F selama 12-15 menit, atau hingga berkaramel. Balikkan nanas sekali di pertengahan waktu.","Nikmati hangat atau dingin, sebagai hidangan pendamping atau hidangan penutup.",("Saus Cocolan Opsional","Jika membuat saus cocolan cabai jeruk nipis, campurkan ketiga bahan dalam mangkuk kecil selagi nanas Anda dimasak.")],
["Jangan menuang irisan nanas ke dalam keranjang air fryer Anda. Sebaliknya, sendokkan satu per satu agar tidak patah, dan mencegah kelebihan cairan menetes ke bawah keranjang dan berasap. Sisa makanan dapat disimpan di lemari es dalam wadah tertutup selama 2-3 hari."],[]))
R.append((9401943,"Cara Membuat Keju Parmesan Vegan",
"Hanya segelintir bahan untuk keju Parmesan vegan terbaik! Asin, beraroma keju, dan sempurna untuk ditaburkan di atas apa saja!",
"12 porsi (menghasilkan sekitar 1 cangkir)","2 sdm",
["½ cangkir kacang mete mentah atau kacang pinus, atau almond blanched","3 sendok makan ragi nutrisi","½ sendok teh garam laut","⅛ sendok teh bubuk bawang putih, opsional"],
["Masukkan semua bahan ke dalam food processor dan proses hingga menjadi serbuk halus.","Simpan dalam wadah atau toples kedap udara di lemari es Anda dan sajikan dengan ditaburkan di atas hidangan favorit Anda."],
["Pastikan toples atau wadah Anda benar-benar bersih dan KERING untuk mencegah pembusukan akibat kelembapan saat menyimpan parmesan vegan Anda. Simpan di lemari es untuk menjaga kesegarannya. Jangan menggunakan herba atau rempah segar. Ini akan mencegah \"keju\" Anda tetap segar, dan akan lebih cepat busuk. Jika Anda tidak memiliki kacang mete, saya telah berhasil membuatnya dengan almond blanched dan kacang pinus dengan hasil yang serupa. Untuk bebas kacang, Anda dapat menggunakan biji bunga matahari mentah atau biji labu/pepita untuk menggantikan kacang mete dengan hasil yang serupa. Jika tanpa ragi nutrisi, Anda dapat menggunakan campuran bubuk jamur, bubuk bawang bombai, bubuk basil dan lebih banyak bubuk bawang putih. Perlu diingat bahwa ini akan mengurangi rasa kejunya, tetapi tetap memberikan kelezatan umami. Untuk rendah natrium, cukup kurangi garam menjadi setengahnya, atau garami sesuai selera Anda. Saya menyimpan milik saya di lemari es hingga 4 minggu, tetapi saya yakin akan bertahan lebih lama dari itu."],[]))
R.append((9405296,"Pasta Aglio e Olio (Pasta dengan Bawang Putih & Minyak)",
"Pasta Aglio e Olio adalah hidangan pasta klasik Italia yang menggunakan bawang putih tumis dan cabai pedas untuk menghadirkan rasa yang kuat dengan sensasi pedas!",
"6 porsi","1 porsi",
["1 pon penne atau pasta pilihan","1 brokoli besar, dipotong menjadi kuntum","¼ cangkir minyak zaitun extra virgin","4 siung bawang putih, dicincang halus","6-8 cabai kering atau secukupnya","¼ cangkir air rebusan pasta yang disisihkan"],
["Didihkan sepanci besar air yang diberi banyak garam dan masukkan pasta Anda, masak sesuai petunjuk kemasan hingga pasta al dente. Masukkan brokoli ke dalam panci ketika tersisa 8 menit waktu memasak pasta agar brokoli tidak terlalu matang. *Lihat catatan* Tiriskan pasta dan brokoli setelah matang, sisihkan 1/4 cangkir air rebusan pasta.","Sementara itu, masukkan minyak zaitun, bawang putih dan cabai ke dalam wajan besar dan tumis dengan api sedang hingga cabai dan bawang putih sedikit kecokelatan, sekitar 5 menit. Masukkan air rebusan pasta yang disisihkan, pasta dan brokoli ke dalam wajan. Tumis semuanya bersama, terus diaduk selama 1-2 menit.","Sajikan dengan tambahan serpihan cabai atau Keju Parmesan Vegan jika diinginkan."],
["Jika pasta Anda memerlukan 13 menit untuk dimasak, masukkan pasta ke dalam air mendidih dan masak selama 5 menit, lalu masukkan brokoli untuk dimasak selama 8 menit sisanya."],[]))
R.append((9406639,"Kue Kering Stroberi Vegan",
"Kue kering stroberi vegan yang lembut dan kenyal adalah suguhan sempurna untuk camilan tanpa rasa bersalah.",
"30 kue kering","1 porsi",
["1 cangkir pisang tumbuk, sekitar 3 pisang ukuran sedang","2 cangkir oat gulung","½ cangkir tahini atau selai kacang atau biji lainnya","¼ cangkir gula kelapa tanpa pemurnian","1 sendok makan ekstrak vanila murni","¼ cangkir stroberi, dipotong dadu","¼ cangkir keping cokelat vegan, opsional"],
["Panaskan oven terlebih dahulu hingga 350℉/176℃ dan alasi dua loyang kue dengan kertas roti.","Tumbuk pisang ke dalam mangkuk pencampur besar. Lalu masukkan oat, tahini, gula, vanila, dan aduk rata.","Lipat masuk stroberi dan keping cokelat jika digunakan.","Sendok adonan ke atas loyang yang sudah dialasi untuk membuat sekitar 30 kue kering. Lalu tekan setiap bulatan adonan kue untuk membentuknya, karena tidak akan melebar banyak di oven.","Panggang kue kering selama 8-10 menit lalu keluarkan dari oven dan diamkan selama 5-10 menit sebelum dipindahkan ke rak pendingin."],
["Gunakan pisang yang terlalu matang. Semakin matang pisang Anda, semakin banyak rasa, kemanisan, dan kelembapan yang ditambahkannya ke muffin pisang buncis Anda. Pisang berkulit cokelat paling baik.","Takar pisang tumbuk Anda untuk memastikan Anda menggunakan satu cangkir. Ukuran pisang sangat bervariasi. Dua pisang besar atau tiga pisang sedang cocok untuk saya.","Jangan memanggang kue kering terlalu lama, atau akan kering. Kue akan tampak kurang matang, tetapi ingat kue akan semakin mengeras saat dingin.","Biarkan kue kering dingin selama 5-10 menit sebelum memindahkannya ke rak kawat.","Simpan kue kering pada suhu ruangan selama 1-2 hari, di lemari es selama 4-5 hari, atau simpan beku hingga 3 bulan."],[]))
R.append((9406949,"Kue Kering Buncis Selai Kacang Sehat",
"Lembut dan empuk, manis sempurna, dan benar-benar SEHAT kue kering buncis ini! Suguhan tanpa rasa bersalah ini pas untuk sarapan, camilan atau hidangan penutup!",
"30 kue kering","1 kue kering",
["1 kaleng 13.5 ons buncis, ditiriskan & dibilas","2 pisang besar yang sangat matang","½ cangkir selai kacang halus, buatan sendiri atau beli jadi (atau ganti dengan selai kedelai untuk bebas kacang)","2 sendok makan sirup maple, opsional","1 sendok teh baking powder","2 sendok makan minyak kelapa atau saus apel","¾ cangkir oat steel cut instan atau oat gulung","1 sendok teh ekstrak vanila murni, opsional"],
["Panaskan oven terlebih dahulu hingga 350 derajat F dan alasi loyang besar dengan kertas roti.","Masukkan semua bahan ke dalam food processor dan proses hingga halus.","Menggunakan sendok teh logam, sendok campuran ke atas loyang yang sudah disiapkan dan bentuk kue kering Anda.","Panggang selama 18-22 menit, atau hingga sedikit keemasan di sekitar tepi. Biarkan kue kering dingin sepenuhnya agar mengeras sebelum disajikan."],
["Gunakan selai kacang yang dibuat hanya dari kacang tanah tanpa tambahan lemak atau gula. Beberapa merek \"alami\" tidak dibuat hanya dari kacang tanah, jadi selalu baca daftar bahannya. Atau tentu saja, Anda dapat membuatnya sendiri. Saya menggunakan kaleng 13.5 oz. Jika kaleng Anda lebih besar dan Anda ingin menggunakan semuanya agar tidak terbuang, Anda boleh. Namun, Anda memerlukan sedikit cairan tambahan untuk mengimbangi. Tambahkan 1-2 sendok makan minyak kelapa atau saus apel tanpa gula ke dalam campuran. Untuk bebas minyak, ganti minyak kelapa dengan saus apel tanpa gula. Resep asli menggunakan minyak kelapa, tetapi sejak itu saya mengujinya (berkali-kali) dengan saus apel dan sekarang justru lebih menyukainya dengan cara ini. Untuk bebas kacang, ganti selai kacang dengan selai biji bunga matahari atau tahini. Jika Anda tidak memiliki sirup maple murni tetapi tetap ingin menambahkan sedikit kemanisan ekstra, gunakan sirup agave, atau madu juga bisa, jika tidak vegan. Jika Anda mau, Anda dapat menambahkan ¼-1/3 cangkir keping cokelat, kismis, kacang cincang, atau kelapa parut. Pilih salah satu, dan jangan berlebihan atau adonan tidak akan menyatu dengan baik. Jika Anda menginginkan kue kering berukuran seragam, gunakan sendok kue kering. Saya menggunakan sendok kue kering kecil, yaitu seukuran 2 sendok teh. Kue kering buncis dapat disimpan tertutup pada suhu ruangan selama 2-3 hari, di lemari es selama 5-6 hari, atau dibekukan hingga 2 bulan dalam wadah kedap udara."],[]))
R.append((9410019,"Pico de Gallo Nanas",
"Sentuhan seru pada salsa menghadirkan pico de gallo nanas yang manis dan pedas ini. Menyegarkan dan manis dengan hanya 6 bahan yang diperlukan.",
"4 porsi","1 porsi",
["1.5 cangkir nanas, dipotong dadu","2 cangkir tomat, dipotong dadu, sekitar 2 tomat ukuran sedang","½ cangkir bawang bombai putih, dipotong dadu","⅓ cangkir daun ketumbar, dicincang","1-2 cabai jalapeño atau serrano, dicincang halus","1 sendok makan air jeruk nipis, sekitar setengah jeruk nipis besar","⅛ sendok teh garam laut atau secukupnya, opsional"],
["Potong dadu dan cincang semua bahan dan masukkan ke dalam mangkuk pencampur. Lalu peras air jeruk nipis segar di atasnya dan aduk rata agar tersebar merata.","Cicipi dan tambahkan 1/8 sendok teh garam, jika perlu, atau garami sesuai selera Anda. Aduk rata dan dinginkan di lemari es selama 1 jam atau sajikan langsung."],
["Agar kurang pedas, buang biji dan selaput cabai sebelum dicincang. Kenakan sarung tangan saat memegang cabai pedas, dan pastikan mencuci tangan dengan bersih setelah selesai. Hindari menyentuh mata dan wajah Anda! Diamkan pico Anda di lemari es selama 1 jam sebelum disajikan agar rasa-rasanya punya waktu untuk menyatu dengan baik."],[]))
build(R,'/mnt/c/WSL/davita/translations/tid1/part7.json')
