from h import *
L=[]
L.append(R(3093,"Sloppy Joe Kalkun Mudah","Nikmati hidangan gurih favorit keluarga yang merayakan kedai makan khas Amerika tempo dulu. Ahli gizi ginjal DaVita, Tammy dari Louisiana, membagikan resep ramah ginjal Sloppy Joe Kalkun Mudah.","6","1/6 resep di atas 1 roti hamburger",
["1/2 cangkir bawang merah bombai","1/2 cangkir paprika hijau","1-1/2 pon daging kalkun giling, 7% lemak","1 sendok makan bumbu Mrs. Dash® Chicken Grilling Blend","2 sendok makan gula merah","1 sendok makan saus Worcestershire","1 cangkir saus tomat rendah natrium","6 roti hamburger"],
["Cincang bawang bombai dan paprika.","Masukkan ke dalam wajan besar bersama kalkun dan masak dengan api sedang-besar hingga kalkun matang sempurna. Jangan ditiriskan.","Dalam mangkuk kecil, campurkan bumbu Mrs. Dash®, gula, saus Worcestershire, dan saus tomat.","Tambahkan bumbu ke campuran kalkun. Kecilkan api hingga mendidih perlahan dan masak selama 10 menit.","Bagi menjadi 6 porsi dan sajikan di atas roti hamburger."],
["Daging sapi giling tanpa lemak dapat digunakan sebagai pengganti daging kalkun giling. Buang lemaknya setelah daging sapi dicokelatkan pada langkah persiapan pertama.","Untuk menghemat waktu, gunakan bawang bombai dan paprika cincang beku.","Untuk diet protein lebih rendah, kurangi kalkun menjadi 1 pon atau porsi dapat disesuaikan dengan rencana diet Anda."],["3 daging","2 karbohidrat","1 sayuran, kalium sedang"]))
L.append(R(3095,"Apel Panggang Madu dengan Slow Cooker","Untuk keinginan makanan penutup Anda berikutnya, cobalah resep ramah ginjal Apel Panggang Madu dengan Slow Cooker. Resep Apel Panggang Madu dengan Slow Cooker kami dibuat secara eksklusif untuk DaVita.com oleh ahli gizi ginjal DaVita, Sara dari California. Versi modern dan ramah ginjal dari apel panggang klasik ini sempurna bagi mereka yang menjalani diet diabetes, dialisis, dan PGK non-dialisis.","4","6 potong apel matang",
["3 apel ukuran sedang","2 sendok teh kayu manis","1/3 cangkir madu","1 sendok makan mentega tanpa garam"],
["Buang bagian inti dan potong setiap apel menjadi 8 bagian lalu letakkan dalam slow cooker.","Taburkan kayu manis di atas potongan apel dan aduk hingga terlapisi.","Siram dengan madu, tambahkan mentega dan aduk.","Atur slow cooker pada suhu rendah, tutup dengan penutup dan masak selama 2 jam."],
["Resep ini juga dapat dibuat di oven. Masak pada suhu 325° F selama 45 hingga 60 menit."],["1 buah","1 tinggi kalori","1/2 lemak"]))
L.append(R(3097,"Kue Apel Jerman","Kue Apel Jerman adalah perpaduan apel manis yang diiris dan diaduk ke dalam adonan manis beraroma lemon-kayu manis yang kemudian dipanggang hingga cokelat keemasan. Kue ramah ginjal ini begitu lezat sehingga tidak memerlukan icing.","15","1 potong 3\" x 2-1/2\"",
["12 sendok makan mentega tanpa garam","3 apel gala ukuran sedang","1 cangkir gula","1 buah lemon","1 sendok teh ekstrak vanila","2 butir telur besar","2 cangkir tepung terigu serbaguna","2 sendok teh kayu manis","1 sendok teh soda kue","1/2 sendok teh garam"],
["Panaskan oven terlebih dahulu hingga 325° F. Olesi loyang 9 x 13 inci dengan lemak. Keluarkan mentega agar lunak. Kupas, buang inti, dan iris apel.","Dengan mixer, kocok mentega dan gula hingga lembut dan mengembang. Parut kulit lemon. Tambahkan parutan kulit lemon dan ekstrak vanila ke campuran mentega dan gula. Tambahkan satu telur dan terus kocok; tambahkan telur lainnya dan kocok.","Dalam mangkuk terpisah campurkan tepung, kayu manis, soda kue, dan garam. Tambahkan bahan kering secara bertahap ke campuran mentega hingga tercampur. Jangan mengaduk berlebihan.","Peras lemon; aduk jus ke dalam adonan. Aduk irisan apel.","Tuang adonan ke dalam loyang yang sudah diolesi lemak. Taburkan satu sendok makan gula di atasnya. Panggang selama 30 hingga 40 menit. Kue matang saat tusuk gigi yang ditusukkan ke tengah kue keluar bersih. Setelah kue dingin, potong menjadi 15 bagian dan sajikan."],
["Gunakan jenis apel pilihan Anda.","Potong kue menjadi 20 bagian untuk porsi karbohidrat yang lebih rendah (23 gram)."],["1 karbohidrat","1 tinggi kalori","2 lemak"]))
L.append(R(3099,"Smoothie Buah Super","Marlene, ahli gizi DaVita dari Florida, mengatakan ia merawat pasiennya seperti “induk ayam.” Dan, seperti kebanyakan ibu, ia suka menyediakan camilan yang baik untuk Anda. Smoothie Buah Super buatan Marlene adalah camilan ramah ginjal yang sempurna.","2","10 ons",
["8 ons Vanilla Nepro® dengan Carb Steady™, didinginkan","2 sendok takar protein whey 100%","1 cangkir persik beku atau campuran buah beri","1/2 cangkir es hancur, opsional"],
["Masukkan buah beku ke dalam blender.","Tambahkan Nepro® yang sudah dingin, protein whey, dan es hancur (jika diinginkan).","Blender hingga halus.","Tuang ke dalam gelas dan sajikan dengan sedotan."],
["Bekukan atau simpan di lemari es porsi yang tersisa untuk nanti.","Analisis resep menggunakan nilai untuk bubuk protein whey Beneprotein®, sendok takar ukuran 7 gram. Nilai nutrisi dapat sedikit bervariasi dengan produk serupa."],["2 daging","1 buah, rendah kalium","2 tinggi kalori"]))
L.append(R(3101,"Muffin Gingerbread","Muffin gingerbread ini pasti menjadi favorit hari raya selama bertahun-tahun mendatang. Jahe yang pedas berpadu dengan kayu manis dan gula merah menciptakan muffin ramah ginjal yang lezat dan sangat cocok untuk sarapan, makanan penutup, atau camilan.","12","1 muffin",
["2 butir telur besar","3/4 cangkir susu rendah lemak 1%","6 sendok makan minyak canola","1/2 cangkir gula merah, dipadatkan","4 sendok makan sirup jagung gelap","2 cangkir tepung terigu serbaguna","1 sendok makan baking powder","4 sendok teh jahe bubuk","1-1/2 sendok teh kayu manis bubuk"],
["Panaskan oven terlebih dahulu hingga 400° F. Olesi loyang muffin 12 cetakan dengan lemak atau alasi dengan cup kertas.","Dalam mangkuk sedang kocok ringan telur. Kocok susu, minyak, gula merah, dan sirup jagung.","Dalam mangkuk besar aduk tepung, baking powder, jahe, dan kayu manis. Buat cekungan di tengah bahan kering dan tuang bahan cair. Aduk perlahan hingga baru tercampur: jangan mengaduk berlebihan.","Sendokkan adonan ke dalam loyang muffin yang sudah disiapkan. Panggang dalam oven yang sudah dipanaskan sekitar 20 menit, hingga cokelat keemasan dan terasa padat saat disentuh.","Angkat dari oven dan biarkan muffin dingin dalam loyang selama 5 menit. Sajikan hangat dengan mentega atau krim keju."],
["Bekukan sisa muffin untuk camilan cepat nanti. Panaskan kembali dalam microwave selama 30-45 detik.","Muffin mengandung baking powder yang menyumbang kandungan fosfor. Tanyakan kepada ahli gizi Anda apakah Anda perlu minum pengikat fosfat saat muffin dimakan sebagai camilan."],["1 karbohidrat","1 tinggi kalori","1 lemak"]))
L.append(R(3103,"Latke Brokoli-Bawang Bombai (Pancake)","Ahli gizi ginjal Marjorie dari Arizona membagikan resep ramah ginjal Latke Brokoli-Bawang Bombai (pancake) yang menggunakan bawang bombai dan brokoli sebagai pengganti kentang untuk latke rendah kalium yang dapat dinikmati siapa saja, bahkan mereka yang menjalani diet ramah ginjal.","4","1 latke besar atau 2 latke kecil",
["3 cangkir kuntum brokoli","1/2 cangkir bawang bombai","2 butir telur besar","2 sendok makan tepung terigu serbaguna putih","2 sendok makan minyak zaitun"],
["Potong dadu brokoli dan cincang bawang bombai.","Rebus brokoli potong dadu dalam sedikit air selama 5 menit; tiriskan.","Pecahkan telur ke dalam mangkuk sedang dan kocok. Tambahkan tepung dan aduk rata.","Tambahkan brokoli dan bawang bombai lalu aduk ke dalam campuran tepung/telur hingga tercampur rata.","Tambahkan minyak zaitun ke dalam wajan dan panaskan.","Jatuhkan campuran per sendok ke dalam minyak panas, membuat 4 porsi yang sama (atau 8 porsi jika diinginkan latke yang lebih kecil).","Dengan spatula, pipihkan latke dan goreng hingga cokelat di kedua sisi.","Tiriskan di atas tisu dapur untuk menyerap kelebihan minyak.","Sajikan hangat."],
["Latke kentang (pancake), yang secara tradisional disajikan selama Hanukkah, mengandung lebih dari 600 mg kalium untuk porsi yang sebanding kecuali kentang direndam atau direbus untuk mengurangi kalium. Latke Brokoli-Bawang Bombai adalah alternatif rendah kalium yang baik.","Latke paling enak jika dimakan segera."],["1/2 daging","1 sayuran, kalium sedang","1 lemak"]))
L.append(R(3104,"Trail Mix Sarapan","Ahli gizi DaVita, Wai Yin, memastikan pasien dialisisnya memulai hari dengan sarapan. Ia membagikan resep cepat saji untuk dibawa bepergian, Trail Mix Sarapan. Hanya dengan 4 bahan, mudah dibuat dan dapat dimakan dengan atau tanpa susu atau pengganti susu yang lebih rendah kalium dan fosfor.","3","1 cangkir",
["1 cangkir sereal Corn Chex®","1 cangkir sereal Rice Chex®","1/2 cangkir sereal Cocoa Puffs®","1/2 cangkir kue beras mini (plain atau apel kayu manis)"],
["Dalam mangkuk sedang campurkan semua bahan.","Bagi menjadi porsi 1 cangkir.","Sajikan kering atau dengan pengganti susu favorit Anda."],
["Trail Mix Sarapan adalah alternatif sarapan yang bagus bagi pasien dialisis yang sering tidak sempat sarapan. Dapat dimakan sebagai camilan atau dengan pengganti susu sebagai sereal sarapan.","Berkreasilah dan cobalah berbagai sereal. Mintalah daftar sereal yang disetujui kepada ahli gizi Anda."],["2 karbohidrat"]))
L.append(R(3108,"Burger Buncis dengan Saus Tzatziki","Burger Buncis dengan Saus Tzatziki adalah pilihan sempurna untuk membantu meningkatkan serat dalam hidangan nabati.","4","1 burger dalam pita, 1/4 cangkir saus tzatziki",
["1/2 resep Saus Tzatziki dari resep di DaVita.com","15 ons buncis (chickpea) kalengan","4 daun bawang kecil atau 2 daun bawang besar","4 iris bawang merah bombai","1 butir telur besar","2 sendok makan tepung terigu serbaguna","1 sendok teh oregano kering","1/2 sendok teh jintan bubuk","1/4 sendok teh garam","2 sendok makan minyak zaitun","2 roti pita"],
["Siapkan Saus Tzatziki dan simpan di lemari es hingga siap digunakan.","Bilas dan tiriskan buncis. Pangkas dan iris daun bawang. Iris bawang bombai.","Dalam food processor, campurkan buncis, daun bawang, telur, tepung, oregano, jintan, dan garam. Blender dan pulse hingga terbentuk campuran kasar yang menyatu saat ditekan. Campuran akan lembap. Bentuk menjadi 4 patty.","Panaskan minyak zaitun dalam wajan dengan api sedang. Saat panas, masukkan patty. Masak hingga keemasan dan mulai renyah, 4 hingga 5 menit. Balik dan masak hingga cokelat keemasan dan renyah, 2 hingga 4 menit lagi.","Hangatkan pita dan potong masing-masing menjadi dua.","Rakit burger dengan membuka belahan pita dengan hati-hati. Potong satu burger buncis menjadi dua dan letakkan kedua belahan di dalam pita seperti pada gambar, beri topping saus tzatziki dan irisan bawang merah bombai."],
["Tambahkan selada dan mentimun untuk kerenyahan ekstra.","Buncis (chickpea) juga dikenal sebagai kacang garbanzo. Bandingkan label dan pilih produk dengan natrium terendah."],["1-1/2 karbohidrat","1 sayuran rendah kalium","1-1/2 lemak","1/2 susu"]))
L.append(R(3111,"Mi Beras Tiongkok","Dalam budaya Asia, hidangan mi yang tidak dipatahkan dimakan untuk membawa keberuntungan dan kesehatan di Tahun Baru. Resep Mi Beras Tiongkok yang ramah ginjal ini menjaga natrium tetap rendah dengan mengganti kecap asin tradisional dengan coconut aminos yang lebih rendah natrium.","6","1 cangkir",
["8 ons mi beras (rice sticks)","4 lembar daun dari kepala bok choy besar (1 cangkir dicincang)","4 batang seledri","1 wortel besar","1 bawang bombai ukuran sedang","5 siung bawang putih","4 sendok makan coconut aminos","3/4 cangkir kaldu sapi atau sayuran tanpa garam","2 sendok teh saus cabai Sriracha","1 sendok teh tepung maizena","3 sendok makan minyak canola","1 sendok teh minyak wijen","1 batang daun bawang"],
["Siapkan mi beras sesuai petunjuk kemasan (biasanya rendam mi dengan air dingin selama 20 menit lalu pisahkan).","Iris tipis bok choy, seledri, dan wortel. Potong dadu bawang bombai; cincang halus bawang putih.","Dalam mangkuk kecil, campurkan coconut aminos, kaldu, saus cabai, bawang putih, dan tepung maizena.","Panaskan wajan dengan api sedang-besar dan tambahkan minyak canola dan minyak wijen. Masukkan bawang bombai potong dadu dan masak hingga bening. Tambahkan irisan bok choy, seledri, dan wortel lalu tumis cepat hingga empuk tetapi masih renyah.","Tambahkan saus ke sayuran yang sudah matang dan aduk hingga tercampur.","Setelah mi beras melunak, pisahkan mi dan masukkan ke dalam wajan bersama saus dan sayuran. Aduk semuanya hingga tercampur.","Diamkan 15 menit sebelum disajikan agar rasanya meresap sempurna.","Iris daun bawang dan taburkan di atasnya sebagai hiasan sebelum disajikan."],
["Rice sticks juga dikenal sebagai mi beras.","Anda dapat mengganti mi beras dengan soba, udon, bihun, atau spageti. Masak sesuai petunjuk, bukan direndam.","Tambahkan tahu, udang, atau ayam untuk menjadikannya hidangan lengkap.","Coconut aminos menggantikan kecap asin atau tamari dalam resep ini untuk menjaga natrium tetap rendah."],["2 karbohidrat","1 sayuran, kalium sedang","1 lemak"]))
L.append(R(3113,"Falafel","Falafel, favorit Timur Tengah, serbaguna sebagai camilan, hidangan utama, atau topping salad. Bahan utamanya adalah buncis (chickpea), kacang-kacangan yang meningkatkan serat dan menambah kesehatan. Tambahkan saus bawang putih dan mentimun segar untuk rasa tambahan.","8","3 falafel",
["1 pon buncis (chickpea) kering","2 daun bawang","2 cangkir bawang bombai putih","1/2 cangkir peterseli","4 siung bawang putih","1/4 cangkir jus lemon","1-1/2 sendok makan tepung","3/4 sendok teh garam","1 sendok teh ketumbar","1 sendok makan jintan","1/4 sendok teh lada hitam","1/4 sendok teh cabai cayenne"],
["Rendam buncis dengan air dalam panci besar dan diamkan semalaman pada suhu ruang.","Cincang halus bawang bombai putih; cincang daun bawang, peterseli, dan bawang putih.","Tiriskan dan bilas buncis. Masukkan ke dalam food processor bersama daun bawang, bawang bombai putih, peterseli, bawang putih, jus lemon, tepung, garam, ketumbar, jintan, lada hitam, dan cabai cayenne.","Pulse hingga campuran mencapai tekstur tepung kasar hingga pasta. (Jangan memproses berlebihan). Anda mungkin perlu melakukannya dalam 2 kali tergantung ukuran food processor Anda. Setelah selesai, aduk dengan garpu dan buang potongan buncis yang besar.","Dinginkan campuran falafel di lemari es selama 2 jam.","Panaskan oven terlebih dahulu hingga 400° F.","Semprot loyang muffin dengan semprotan masak.","Gunakan sendok es krim atau bentuk campuran menjadi 24 bola; masukkan langsung ke dalam loyang muffin. Letakkan di oven dan panggang selama 7 menit. Angkat, balik falafel, lalu panggang 7 menit lagi."],
["Sajikan falafel dalam kantong roti pita dengan mentimun, selada, bawang bombai, dan saus bawang putih atau di atas salad.","Jika patty tidak terbentuk, Anda mungkin perlu memasukkannya kembali ke food processor hingga lebih menyerupai pasta. Hati-hati agar tidak diproses hingga bertekstur seperti hummus.","Anda dapat menambahkan lebih banyak tepung untuk membantu pengikatan.","Jika diinginkan, Anda dapat menggoreng falafel dalam minyak sebagai pengganti memanggang. Gunakan minyak goreng dengan titik asap tinggi seperti minyak biji anggur atau minyak kacang.","Gantikan falafel dengan makanan protein, bukan sebagai tambahan, untuk membantu menjaga asupan fosfor dan kalium sesuai target."],["1 daging","2 karbohidrat","1 sayuran, kalium tinggi"]))
L.append(R(3120,"Salad Kacang Polong Hijau","Kacang polong hijau yang manis, bawang merah bombai, dan sedikit irisan buah zaitun hitam serta keju mozzarella yang dipadukan dalam saus mayones yogurt yang lembut menjadikan resep Salad Kacang Polong Hijau ini sederhana namun lezat. Sempurna untuk makan siang, makan malam, atau dibawa ke acara potluck.","8","1/2 cangkir",
["1/4 cangkir bawang merah bombai","4 lembar daun kemangi segar","1/2 cangkir yogurt Yunani plain","1/4 cangkir mayones","3 cangkir kacang polong hijau beku","2.25 ons irisan zaitun hitam kalengan (opsional)","1/2 cangkir keju mozzarella parut (opsional)"],
["Cincang bawang bombai dan cincang halus kemangi.","Dalam mangkuk kecil campurkan mayones dan yogurt.","Masak kacang polong dalam air mendidih selama 2 hingga 3 menit. Tiriskan lalu campurkan kacang polong dengan saus mayones-yogurt selagi kacang polong masih hangat.","Tambahkan bawang bombai, kemangi, dan zaitun ke campuran kacang polong hijau dan aduk hingga bahan tercampur.","Taburkan keju mozzarella di atasnya dan simpan di lemari es hingga siap disajikan."],
["Tiga cangkir kacang polong hijau kira-kira 1 pon. Gunakan kacang polong hijau segar saat musimnya.","Pilih mayones berbasis minyak zaitun untuk menyertakan lemak sehat.","Gunakan peterseli sebagai pengganti kemangi jika diinginkan.","Dua sendok makan irisan almond juga dapat ditambahkan untuk faktor kerenyahan.","Tambahkan lada atau campuran bumbu herbal Mrs. Dash® untuk rasa sesuai selera."],["1 sayuran, rendah kalium","1-1/2 lemak"]))
L.append(R(3121,"Lumpia Segar Tahu","Lumpia yang ringan dan mengenyangkan ini menyediakan protein dari tahu, dan bersama sayuran, menambah pilihan segar bagi diet ginjal Anda.","6","2 lumpia",
["12 lembar selada romaine","2 wortel ukuran sedang","1/2 bawang merah bombai ukuran sedang","16 ons tahu padat","1/2 sendok makan jintan bubuk","1/2 sendok makan bawang putih granulasi","1/4 sendok teh garam laut","1/2 sendok teh lada hitam","1 sendok makan minyak zaitun","12 kulit rice paper untuk lumpia"],
["Cuci dan keringkan selada, lalu potong setiap lembar menjadi dua memanjang. Potong wortel gaya julienne. Iris bawang bombai. Sisihkan.","Didihkan 6 cangkir air dan sisihkan untuk merendam kulit rice paper nanti.","Tiriskan dan keringkan tahu dengan ditepuk-tepuk. Iris menjadi 12 potong, masing-masing sepanjang sekitar 4″.","Sebarkan tahu di piring dan bumbui secara merata dengan jintan, bawang putih granulasi, garam laut, dan lada hitam.","Panaskan wajan antilengket dengan minyak zaitun. Letakkan potongan tahu di wajan, sisi yang dibumbui menghadap ke bawah. Bumbui sisi lainnya dan goreng hingga bagian bawah kecokelatan ringan, sekitar 1 hingga 2 menit. Balik dan goreng hingga sisi kedua kecokelatan ringan. Letakkan tahu di piring untuk didinginkan.","Tuang air panas ke dalam mangkuk besar yang dangkal. Celupkan satu kulit rice paper ke dalam air panas. Setelah sedikit lunak, letakkan kulit di piring besar dan letakkan 2 belahan selada di tengah kulit. Taburkan 2 hingga 3 sendok makan wortel dan 1 hingga 2 sendok makan irisan bawang di atas selada. Letakkan satu potong tahu yang sudah dingin di atas sayuran.","Lipat sisi-sisinya ke dalam, lalu lipat bagian bawah ke atas dan gulung dengan kencang. Ulangi dengan sisa kulit rice paper, sayuran, dan potongan tahu.","Dinginkan di lemari es dan sajikan dingin dengan dressing rendah natrium favorit Anda."],
["Sajikan dengan 2 sendok makan dressing rendah natrium. Dressing miso jahe adalah pilihan yang baik.","Meskipun jumlah garam yang digunakan dalam resep ini minimal, beberapa orang mungkin ingin mengurangi kandungan natrium lebih lanjut dengan menggunakan bumbu bebas garam. Mrs. Dash dan Kirkland No Salt Seasoning adalah alternatif yang baik."],["1 daging","1 karbohidrat","1 sayuran, kalium sedang"]))
L.append(R(3122,"Oatmeal Stroberi dan Krim","Stroberi, oat, dan susu kedelai adalah bahan utama dalam hidangan satu piring tinggi serat ini. Oatmeal Stroberi dan Krim mungkin menjadi favorit sarapan Anda.","1","1-1/2 cangkir",
["1/2 cangkir stroberi segar","1 sendok teh gula (atau pemanis granulasi pilihan)","1/2 cangkir air","1/2 cangkir susu kedelai vanila","2 sendok makan krimer half & half","1/2 cangkir oat instan"],
["Cincang stroberi, lalu lumuri dengan gula atau pemanis granulasi. Sisihkan.","Campurkan air, susu kedelai, dan half & half dalam panci kecil. Didihkan perlahan dengan api sedang-besar.","Tambahkan stroberi dan didihkan.","Tambahkan oat dan masak 4 hingga 5 menit hingga kekentalan yang diinginkan."],
["Untuk rasa manis ekstra, siram dengan madu, agave, atau pemanis pilihan.","Cobalah raspberry atau blueberry sebagai pengganti stroberi saat musimnya.","Satu porsi dianggap sebagai hidangan satu piring. Jika disajikan sebagai hidangan pendamping, kurangi porsi menjadi 1/2 cangkir","Untuk diet bebas gluten, periksa label oatmeal untuk tulisan \"gluten-free\"."],["2 karbohidrat","1/2 buah, rendah kalium","1 alternatif susu"]))
L.append(R(3125,"Ikan Trout Api Unggun","Ahli gizi DaVita, Helen, tidak hanya mahir di dapur, tetapi ia juga dapat memberi tahu Anda cara berkeliling Colorado. Helen membagikan beberapa resep lezat yang ramah ginjal, seperti Ikan Trout Api Unggun, dan menyusun rencana perjalanan yang menyenangkan untuk mengunjungi negara bagian Rocky Mountain. Bahkan jika Anda tidak dapat pergi ke Colorado dalam waktu dekat, rekomendasinya akan membuat Anda merasa seperti sedang berlibur.","4","1 fillet, 3 ons matang",
["14 ons fillet ikan trout","1/2 sendok teh campuran bumbu Mrs. Dash® Garlic & Herb","1 buah lemon","2 daun bawang","1 batang seledri","1 wortel ukuran sedang"],
["Siapkan bara arang.","Iris lemon dan daun bawang. Cincang seledri dan potong wortel gaya julienne.","Letakkan ikan di tengah selembar besar foil (foil tugas berat paling cocok untuk api unggun). Taburi dengan bumbu Mrs. Dash.","Tata irisan lemon di atas fillet. Taburi dengan daun bawang, wortel, dan seledri.","Rapatkan foil dengan kencang. Letakkan di atas rak di atas bara api unggun selama 10 hingga 15 menit atau hingga ikan mudah terpisah dengan garpu. (Hati-hati saat membuka bungkusan karena uap akan keluar.)"],
["Panggang ikan di oven pada suhu 400° F selama 10 hingga 15 menit jika pemanggang arang tidak tersedia.","Jika Anda menjalani diet protein lebih rendah, kurangi porsi menjadi 2 ons (matang), 6 porsi untuk resep ini."],["3 daging","1/2 sayuran, kalium sedang"]))
L.append(R(3126,"Tumis Tahu Renyah","Tumis Tahu Renyah adalah pilihan vegetarian yang ramah ginjal. Ahli gizi DaVita, Jean dari Iowa, menciptakan Tumis Tahu Renyah untuk dibagikan kepada pasien ginjal yang mencari pilihan tanpa daging yang tetap menyediakan protein berkualitas tinggi untuk memenuhi kebutuhan diet dialisis.","4","1 cangkir tahu dan sayuran + 1/2 cangkir nasi",
["16 ons tahu ekstra padat","1/2 paprika merah","1 siung bawang putih","1-1/2 sendok makan kecap asin natrium dikurangi","1-1/2 sendok makan jus limau","2 sendok teh gula","2 sendok makan tepung maizena","2 putih telur","1/2 cangkir remah roti tanpa bumbu","1-1/2 sendok makan minyak canola","1 sendok makan minyak wijen","1 cangkir kuntum brokoli segar","1 sendok teh campuran bumbu herbal Mrs. Dash®","1/8 sendok teh lada hitam","1/8 sendok teh cabai cayenne","1/2 sendok teh biji wijen","2 cangkir nasi putih kukus"],
["Potong tahu menjadi dadu. Potong paprika menjadi strip dan cincang siung bawang putih.","Campurkan kecap asin natrium dikurangi, jus limau, dan gula dalam mangkuk kecil. Sisihkan.","Dalam tiga mangkuk terpisah, masukkan tepung maizena, putih telur, dan remah roti. Celupkan dadu tahu pertama ke dalam tepung maizena, lalu putih telur dan lapisi dengan remah roti.","Panaskan minyak canola dalam wajan atau wok dan tumis tahu yang sudah dilapisi hingga cokelat keemasan dan renyah. Angkat tahu dari wajan dan sisihkan.","Dalam wajan yang sama, tambahkan minyak wijen dan panaskan. Tumis brokoli dan strip paprika merah hingga empuk tetapi masih renyah. Tambahkan bawang putih cincang, campuran bumbu Mrs. Dash, lada hitam, dan cabai cayenne dan masak satu menit.","Masukkan kembali tahu ke wajan dan aduk bersama sayuran. Tuang campuran kecap-jus limau di atasnya, taburi dengan biji wijen dan aduk. Angkat dari api dan bagi menjadi 4 porsi. Sajikan dengan 1/2 cangkir nasi."],
["Ganti minyak wijen dengan minyak zaitun jika diinginkan.","Anda dapat membekukan tahu potong dadu untuk dicairkan dan ditumis nanti. Pembekuan memberi tahu tekstur yang lebih padat dan \"seperti daging\".","Gunakan bumbu bebas garam favorit Anda. Tips: Penzey’s Spices®, Mrs. Dash®, dan Tone’s® membuat berbagai bumbu bebas garam yang sangat baik. Hindari pengganti garam yang mengandung kalium klorida karena kandungan kaliumnya yang tinggi."],["2 daging","2-1/2 karbohidrat","1-1/2 sayuran, kalium sedang"]))
save(6,L)
