from h import *
L=[]
L.append(R(3128,"Punch Hangat Berempah","Apel adalah makanan serbaguna yang sangat baik untuk membantu Anda tetap sehat. Tidak ada yang mengalahkan rasa apel segar. Di tengah dinginnya musim gugur, apa yang lebih menghibur daripada secangkir Punch Hangat Berempah yang ramah ginjal, perpaduan lezat jus cranberry dan apel dengan sedikit kayu manis dan cengkih? Ini adalah minuman yang aromanya seenak rasanya.","14","1 cangkir",
["6 cangkir jus cranberry Ocean Spray® Natural Pure100% Unsweetened","8 cangkir jus apel","1/2 cangkir gula merah","4 batang kayu manis, dipatahkan","1- 1/2 sendok teh cengkih utuh"],
["Campurkan bahan-bahan dalam panci besar atau crock pot.","Panaskan hingga mendidih perlahan dan sajikan hangat."],
["Punch Hangat Berempah dapat dididihkan perlahan dalam crock pot hingga siap disajikan. Ini cara yang bagus untuk memenuhi rumah dengan aroma musim gugur.","Untuk versi karbohidrat lebih rendah, penderita diabetes dapat mengganti dengan minuman jus cranberry rendah kalori dan Splenda® brown sugar blend. Karbohidrat = 24 gram per porsi, 1-1/2 pilihan karbohidrat."],["2 buah, rendah kalium"]))
L.append(R(3139,"Frost on the Pumpkin Pie","Resep Frost on the Pumpkin Pie yang dikirim oleh ahli gizi ginjal DaVita, Diane dari Nebraska, adalah makanan penutup Halloween ramah ginjal yang tak tertahankan. Bawalah ke pesta Anda berikutnya.","16 (2 pai)","1/8 dari satu pai",
["2-1/2 cangkir remah biskuit graham","6 sendok makan gula","2 sendok teh kayu manis","1/2 sendok teh pala","1/2 sendok teh cengkih bubuk","2/3 cangkir mentega tanpa garam","16 ons Pillsbury® Creamy Supreme® Vanilla Frosting","1 cangkir sour cream","1 cangkir labu kuning kalengan","1/2 sendok teh jahe","3/4 cangkir krim kental"],
["Panaskan oven hingga 350º F.","Dalam mangkuk kecil, campurkan remah biskuit graham, gula, 1 sendok teh kayu manis, pala, 1/4 sendok teh cengkih, dan mentega leleh; aduk hingga tercampur. Sisihkan 4 sendok makan remah untuk topping.","Tekan sisa remah ke dasar dan sisi dua loyang pai 9 inci.","Panggang selama 6 menit. Dinginkan.","Dalam mangkuk besar, campurkan frosting, sour cream, labu kuning, 1 sendok teh kayu manis, jahe, dan 1/4 sendok teh cengkih. Tuang isian ke dalam kulit pai yang sudah disiapkan.","Letakkan mangkuk pengaduk dan pengocok hand-mixer di freezer selama 15 menit. Masukkan krim kental ke dalam mangkuk dan kocok hingga terbentuk puncak lembut. Bagi dan oleskan secara merata di atas setiap pai.","Taburkan remah biskuit graham yang disisihkan di atasnya.","Bekukan agar mengeras, lalu simpan di lemari es hingga siap disajikan.","Simpan sisa makanan penutup di lemari es."],
["Anda dapat membeli remah biskuit graham atau membuatnya sendiri dengan menghancurkan 36 keping persegi biskuit graham.","Untuk mengurangi lemak, gunakan whipped topping susu Reddi-Wip® sebagai pengganti krim kental dan lewati langkah #6. Alih-alih dioleskan pada pai, semprotkan sekitar 2 sendok makan pada setiap porsi tepat sebelum disajikan. Lemak berkurang menjadi 3 gram."],["2 karbohidrat","4 lemak","1 tinggi kalori"]))
L.append(R(3141,"Baking Powder Bebas Fosfor Buatan Sendiri","Ada banyak makanan yang dibatasi bagi penderita penyakit ginjal dan yang menjalani dialisis, tetapi berkat ahli gizi ginjal DaVita, Mary dari Kansas, resepnya untuk Baking Powder Bebas Fosfor Buatan Sendiri telah mengembalikan makanan seperti biskuit, tortilla, pancake, dan wafel ke menu Anda.","6","sekitar 1 sendok makan per resep (bervariasi tergantung jumlah porsi dan bahan lainnya)",
["1/4 cangkir cream of tartar","2 sendok makan soda kue"],
["Ayak cream of tartar dan soda kue bersama-sama menggunakan saringan halus.","Simpan dalam toples atau kantong kedap udara pada suhu ruang hingga siap digunakan."],
["Perhatikan bahwa jumlah dan nutrisi digunakan di seluruh resep, sehingga nilai nutrisi akan tersebar. Sebagian besar resep memerlukan kurang dari satu sendok makan baking powder untuk seluruh resep.","Resep baking powder ini menggunakan rasio 2 banding 1 antara cream of tartar dan soda kue. Untuk menggantikan satu sendok makan baking powder komersial dalam resep, gunakan 2 sendok teh cream of tartar dan 1 sendok teh soda kue.","Anda dapat menggunakan campuran ini dengan proporsi yang sama seperti baking powder komersial saat membuat kue, roti cepat saji, muffin, tortilla, pancake, dan wafel.","Cream of tartar adalah garam asam kalium dari asam tartarat, yang merupakan produk sampingan pembuatan anggur. Satu sendok teh mengandung 495 mg kalium. Saat menggunakan cream of tartar dengan soda kue untuk menggantikan baking powder yang mengandung fosfor, perlu diketahui bahwa kandungan kalium makanan akan lebih tinggi tetapi fosfor jauh lebih rendah."],["0"]))
L.append(R(3143,"Bar Apel","Makanan penutup sehat ramah ginjal yang lezat perlu dibagikan. Dan itulah yang dilakukan Sandra dari Minnesota dengan Bar Apelnya yang lezat, rendah kalium, dan menyehatkan.","18","1 bar, 3\" x 3\"",
["2 apel ukuran sedang","3/4 cangkir mentega tanpa garam","1 cangkir gula pasir","1 cangkir sour cream","1 sendok teh ekstrak vanila","1 sendok teh soda kue","1/2 sendok teh garam","2 cangkir tepung terigu serbaguna","1/2 cangkir gula merah","1 sendok teh kayu manis","2 sendok makan susu","1 cangkir gula halus"],
["Panaskan oven terlebih dahulu hingga 350° F.","Kupas dan cincang apel.","Kocok bersama 1/2 cangkir mentega dan gula pasir atau pengganti gula pasir.","Tambahkan sour cream, vanila, soda kue, garam, dan tepung. Aduk hingga tercampur; tambahkan apel cincang.","Tuang adonan ke dalam loyang 9” x 13” yang sudah diolesi lemak.","Dalam mangkuk kecil, remas bersama 2 sendok makan mentega yang sudah lunak, gula merah, dan kayu manis. Taburkan di atas adonan.","Panggang selama 35 hingga 40 menit. Biarkan dingin sepenuhnya.","Untuk membuat icing, campurkan 2 sendok makan mentega leleh, susu (atau pengganti susu), dan gula halus. Siramkan di atasnya dan potong makanan penutup menjadi 18 bar."],
["1 apel ukuran sedang menghasilkan 1 cangkir apel cincang.","Penderita diabetes dapat mengganti gula pasir dengan pengganti gula granulasi dan tidak menggunakan icing sehingga menurunkan kandungan karbohidrat menjadi 19 gram per porsi (1 pilihan karbohidrat). Berhati-hatilah dengan ukuran porsi."],["1/2 buah, rendah kalium","1 karbohidrat","2 lemak","1 tinggi kalori"]))
L.append(R(3146,"Batang Seledri Isi Kepiting","Cukup elegan untuk hidangan pembuka pesta namun cukup mudah untuk camilan cepat. Itulah ringkasan Batang Seledri Isi Kepiting dari tim ahli gizi DaVita. Cobalah hidangan pembuka ramah ginjal ini pada acara Anda berikutnya.","4","3 potong",
["4 batang seledri (ukuran sedang 8 inci)","1/4 cangkir daging kepiting","1 sendok makan bawang merah bombai","2 sendok teh mayones","1/2 sendok teh jus lemon","1/4 sendok teh paprika"],
["Pangkas ujung batang seledri. Tiriskan dan suwir daging kepiting. Cincang halus bawang bombai.","Dalam mangkuk kecil campurkan daging kepiting, bawang bombai, mayones, dan jus lemon.","Isi setiap batang seledri dengan 1 sendok makan campuran kepiting.","Potong setiap batang seledri menjadi 3 bagian.","Taburi potongan seledri isi kepiting dengan paprika sebelum disajikan."],
["Analisis resep menggunakan daging kepiting kalengan. Ganti dengan yang segar atau beku jika lebih suka.","Gandakan atau gandakan tiga kali resep ini untuk disajikan di pesta atau acara sosial."],["1 sayuran, rendah kalium"]))
L.append(R(3149,"Kentang Goreng dari Terong","Kentang Goreng Terong Renyah dari ahli gizi DaVita, Jill, adalah alternatif ramah ginjal yang menarik pengganti kentang dan sumber serat yang sangat baik.","6","7-8 potong",
["1 terong ukuran sedang","1 cangkir susu rendah lemak 1%","2 butir telur besar","3/4 cangkir tepung maizena","3/4 cangkir remah roti kering tanpa bumbu","3 sendok teh campuran kering dressing salad dan bumbu Hidden Valley Original Ranch®","1 sendok teh saus pedas Tabasco® (opsional)","1/2 cangkir minyak canola"],
["Kupas dan iris terong menjadi batang 3/4” sepanjang 4”. Bilas dan keringkan dengan ditepuk-tepuk.","Dalam mangkuk sedang, campurkan susu dan telur hingga tercampur rata; aduk saus pedas.","Dalam mangkuk lebar yang dangkal, campurkan tepung maizena, remah roti, dan campuran kering dressing salad Ranch.","Panaskan minyak dalam wajan dengan api besar.","Celupkan batang terong ke dalam campuran telur lalu gulingkan setiap potong dalam campuran remah roti.","Masukkan ke dalam minyak, balik secara teratur dan goreng 3 menit atau hingga cokelat keemasan.","Tiriskan di atas tisu dapur dan sajikan segera."],
["Ganti dengan 1/2 cangkir produk telur rendah kolesterol untuk menurunkan kandungan lemak dan kolesterol.","Kentang goreng jauh lebih tinggi kalium dibandingkan Kentang Goreng dari Zucchini."],["1 karbohidrat","1 sayuran, kalium sedang","2 lemak"]))
L.append(R(3151,"Sandwich Pita Tempe","Lain kali Anda ingin sandwich yang renyah dengan rasa kacang, cobalah Sandwich Pita Tempe, favorit vegetarian. Selain cocok untuk diet ramah ginjal, Sandwich Pita Tempe rendah kolesterol dan lemak jenuh serta tinggi serat sebesar 5.5 gram per porsi.","4","1/2 pita dengan 3 iris tempe",
["8 ons tempe","2 sendok makan minyak wijen","2 sendok makan cuka balsamik","1 bawang bombai kecil","1 paprika merah","1/2 cangkir jamur","2 lembar roti pita, ukuran 6 inci","4 sendok teh mayones"],
["Potong tempe menjadi 12 iris. Iris tipis bawang bombai, paprika, dan jamur.","Dalam wajan besar panaskan 1 sendok makan minyak wijen dengan api sedang. Masukkan irisan tempe dan masak setiap sisi selama 3 hingga 4 menit hingga kecokelatan. Tambahkan cuka balsamik dan masak satu menit; balik dan masak satu menit lagi. Angkat tempe dari wajan.","Tambahkan sisa minyak wijen ke wajan dan panaskan dengan api sedang. Masukkan bawang bombai, paprika, dan jamur lalu masak hingga empuk.","Potong pita menjadi dua dan buka untuk membentuk kantong. Oleskan setiap belahan dengan 1 sendok teh mayones. Tambahkan 3 potong tempe dan 1/4 campuran sayuran ke setiap belahan pita. Sajikan segera."],
["Untuk mengubah rasa, ganti minyak wijen dengan minyak beraroma favorit Anda.","Tempe dibuat dari kedelai utuh yang dicampur dengan beras atau millet, lalu difermentasi. Tempe memiliki rasa kacang dan menyerap rasa dari marinasi atau bumbu yang ditambahkan selama memasak."],["1-1/2 daging","1 karbohidrat","1-1/2 sayuran, kalium sedang","2 lemak"]))
L.append(R(3153,"Nasi Nanas","Tambahkan rasa tropis yang manis pada hidangan pendamping ramah ginjal Anda berikutnya. Nasi Nanas mudah dibuat dan memberikan kesan yang bagus.","6","1/2 cangkir",
["1 cangkir potongan kecil nanas kalengan dalam sari buah tanpa pemanis","3/4 cangkir beras putih butir panjang, belum dimasak","1-1/4 cangkir air"],
["Tiriskan nanas dan simpan sari buahnya.","Campurkan nanas, beras, sari nanas yang disimpan, dan air dalam panci.","Didihkan, tutup dan kecilkan api. Didihkan perlahan selama 20 hingga 25 menit, hingga semua air terserap dan nasi empuk."],
["Sajikan dengan salah satu resep kari."],["1 karbohidrat","1/2 buah, rendah kalium"]))
L.append(R(3167,"Olesan Asparagus","Inilah resep diet ginjal Olesan Asparagus yang menghasilkan sandwich kecil yang lezat dan menjadi favorit sebagai dip di pesta. Asparagus yang ramah ginjal dapat diganti dengan mentimun dalam resep ini untuk sensasi rasa yang berbeda.","16","2 sendok makan",
["6 ons krim keju","8 ons asparagus kalengan, rendah natrium","1/4 cangkir mayones","2 sendok makan bawang bombai","1 sendok makan jus lemon"],
["Keluarkan krim keju agar lunak.","Tiriskan asparagus dengan baik.","Campurkan semua bahan dalam food processor dan proses hingga tercampur. Pindahkan ke mangkuk, tutup dan simpan di lemari es semalaman.","Sajikan olesan dengan biskuit rendah natrium atau buat sandwich kecil."],
["Asparagus kalengan dapat diganti dengan asparagus segar atau beku. Rebus dalam air hingga asparagus cukup lunak untuk dilumatkan dengan garpu.","Resep ini dapat dibuat dengan mentimun potong dadu sebagai pengganti asparagus."],["1/2 sayuran, rendah kalium","1 lemak"]))
L.append(R(3168,"Saus Chile Colorado (Saus Cabai Merah Dasar)","Inilah resep ramah ginjal Saus Chile Colorado, yang tak lain adalah Saus Cabai Merah Dasar. Inilah yang memberikan cita rasa lezat dan khas pada resep chili Anda.","10","1/4 cangkir",
["3 sendok makan bawang bombai","1 siung bawang putih","2 sendok makan minyak canola","2 sendok makan tepung terigu serbaguna putih","1 sendok teh jintan bubuk","1/2 sendok teh oregano bubuk","1/2 cangkir bubuk cabai merah kering (ancho atau pasilla)","2-1/2 cangkir air","1/4 sendok teh garam","1 sendok teh gula"],
["Cincang halus bawang bombai dan cincang halus bawang putih.","Dalam panci sedang panaskan minyak canola dan tumis bawang bombai dan bawang putih hingga empuk.","Aduk tepung hingga tercampur; tambahkan jintan dan oregano. Masak dan aduk selama 3 menit lalu angkat dari api.","Tambahkan bubuk cabai dan aduk hingga tercampur. Kembalikan panci ke api dan tambahkan 2-1/2 cangkir air, garam, dan gula.","Didihkan saus, sambil terus diaduk. Kecilkan api dan didihkan perlahan selama 5 menit.","Simpan saus di lemari es hingga siap digunakan. Menghasilkan 2-1/2 cangkir."],
["Bubuk cabai mudah gosong jadi aduk sesering mungkin dan hati-hati agar panci tidak terlalu panas.","Buat bubuk cabai dari cabai kering atau gunakan bubuk cabai yang dibeli di toko. Perlu diketahui, bubuk cabai mengandung tambahan garam sehingga kandungan natriumnya akan lebih tinggi. Tidak usah menambahkan 1/4 sendok teh garam jika menggunakan bubuk cabai.","Saus tahan 1 minggu di lemari es.","Gunakan saus ini untuk membuat resep Chile Colorado."],["1/2 sayuran, kalium sedang","1/2 lemak"]))
save(7,L)
