from lib import *
R=[]
R.append((6452790,{
"es":L("Sorbete de limón","Este sorbete de limón bajo en carbohidratos es un postre helado refrescante y cítrico que aporta un estallido de sabor a limón sin mucha azúcar ni calorías. Disfrútelo como un refrigerio refrescante, ideal para satisfacer su gusto por lo dulce mientras sigue un plan de alimentación para la diabetes.","4","1/2 taza",
["4 limones (jugo)","1/2 taza de agua","2 cucharaditas de edulcorante líquido de stevia"],
["En un tazón, bata el jugo de limón, el agua y la stevia.","Vierta en una máquina para hacer helados y bata según las instrucciones del fabricante.","Para un sorbete suave, consúmalo de inmediato. Para una textura más firme, páselo a un recipiente apto para congelador y congele durante 2 horas."]),
"ar":L("سوربيه الليمون","هذا السوربيه بالليمون منخفض الكربوهيدرات حلوى مثلجة منعشة وحامضة تمنحك نكهة الحمضيات دون الكثير من السكر والسعرات الحرارية. استمتع به كوجبة خفيفة منعشة، فهو مثالي لإشباع رغبتك في تناول الحلوى أثناء اتباعك نظامًا غذائيًا لمرضى السكري.","4","½ كوب",
["4 ليمون (عصير)","½ كوب ماء","2 ملعقة صغيرة من محلّي الستيفيا السائل"],
["في وعاء، اخفق عصير الليمون والماء والستيفيا.","اسكب الخليط في آلة صنع الآيس كريم وحرّكه وفق تعليمات الشركة المصنعة.","للحصول على سوربيه ناعم، تناوله فورًا. وللحصول على قوام أكثر تماسكًا، انقله إلى وعاء صالح للتجميد وجمّده لمدة ساعتين."])}))
R.append((6453245,{
"es":L("Magdalenas saladas de huevo y verduras","Estas magdalenas saladas de huevo y verduras son un desayuno para llevar, lleno de fibra, proteína y verduras de colores. Con una base de harina integral, verduras ralladas y solo un toque de queso reducido en grasa, son saciantes sin ser pesadas. Su combinación equilibrada de nutrientes las convierte en una excelente opción para quienes controlan la diabetes. Esta es una receta DASH (Enfoque Dietético para Detener la Hipertensión), vegetariana y baja en grasa.","4","2 magdalenas",
["2 calabacines grandes (rallados y exprimidos hasta secarlos)","1 zanahoria grande (rallada)","1/4 taza de pimiento rojo (en cubitos finos)","1/4 taza de cebolla morada (en cubitos finos)","2 huevos grandes","2 onzas de claras de huevo líquidas","1/4 taza de leche baja en grasa","1/2 taza de harina integral","1/2 cucharadita de polvo para hornear","1/4 cucharadita de pimienta negra","1/8 cucharadita de pimentón ahumado","1/4 taza de queso cheddar rallado reducido en grasa"],
["Precaliente el horno a 375 °F (190 °C) y forre un molde para magdalenas con 8 capacillos de papel o engrase ligeramente los moldes con aceite en aerosol.","Ralle el calabacín y la zanahoria, y luego exprima el exceso de humedad con un paño limpio. Corte el pimiento rojo y la cebolla morada en cubitos y mezcle todas las verduras en un tazón.","En un tazón mediano, bata los huevos, las claras y la leche baja en grasa hasta que estén bien mezclados.","En otro tazón, mezcle la harina integral, el polvo para hornear, la pimienta negra y el pimentón ahumado.","Incorpore poco a poco los ingredientes secos a los ingredientes húmedos, revolviendo suavemente hasta que apenas se integren. Agregue las verduras ralladas y el queso cheddar a la masa, mezclando con movimientos envolventes hasta que se distribuyan de manera uniforme.","Divida la masa en partes iguales entre los 8 moldes preparados. Llene cada uno aproximadamente 3/4 de su capacidad.","Hornee de 18 a 22 minutos, o hasta que un palillo insertado en el centro de una magdalena salga limpio.","Deje enfriar las magdalenas en el molde durante 5 minutos y luego páselas a una rejilla. Sírvalas tibias o a temperatura ambiente."]),
"ar":L("مافن البيض والخضار المالح","مافن البيض والخضار المالح هذا وجبة فطور جاهزة للحمل، غنية بالألياف والبروتين والخضار الملونة. يعتمد على دقيق القمح الكامل والخضار المبشورة ولمسة بسيطة فقط من الجبن قليل الدسم، فهو مشبع دون أن يكون ثقيلًا. وتجعله تركيبته المتوازنة من العناصر الغذائية خيارًا ممتازًا لمن يتحكمون في مرض السكري. هذه وصفة DASH (النهج الغذائي لوقف ارتفاع ضغط الدم)، نباتية وقليلة الدسم.","4","2 مافن",
["2 كوسا كبيرة (مبشورة ومعصورة حتى تجف)","1 جزرة كبيرة (مبشورة)","¼ كوب فلفل رومي أحمر (مقطع مكعبات صغيرة جدًا)","¼ كوب بصل أحمر (مقطع مكعبات صغيرة جدًا)","2 بيضة كبيرة","2 أونصة بياض بيض سائل","¼ كوب حليب قليل الدسم","½ كوب دقيق القمح الكامل","½ ملعقة صغيرة بيكنج باودر","¼ ملعقة صغيرة فلفل أسود","⅛ ملعقة صغيرة بابريكا مدخنة","¼ كوب جبن شيدر مبشور قليل الدسم"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية) وبطّن قالب المافن بـ 8 قوالب ورقية أو ادهن التجاويف قليلًا ببخاخ الطهي.","اِبشر الكوسا والجزر، ثم اعصرهما بقطعة قماش نظيفة للتخلص من الرطوبة الزائدة. قطّع الفلفل الرومي الأحمر والبصل الأحمر مكعبات صغيرة واخلط جميع الخضار في وعاء.","في وعاء متوسط، اخفق البيض وبياض البيض والحليب قليل الدسم حتى يمتزجوا جيدًا.","في وعاء آخر، اخلط دقيق القمح الكامل والبيكنج باودر والفلفل الأسود والبابريكا المدخنة.","أضف المكونات الجافة تدريجيًا إلى المكونات الرطبة وقلّب برفق حتى تمتزج فقط. أضف الخضار المبشورة وجبن الشيدر إلى الخليط وقلّب برفق حتى تتوزع بالتساوي.","وزّع الخليط بالتساوي على قوالب المافن الثمانية المجهزة. املأ كل قالب بنحو ¾ سعته.","اخبز لمدة 18 إلى 22 دقيقة، أو حتى تخرج عود أسنان مغروس في وسط المافن نظيفة.","اترك المافن يبرد في القالب لمدة 5 دقائق، ثم انقله إلى رف شبكي. قدّمه دافئًا أو بدرجة حرارة الغرفة."])}))
R.append((6454224,{
"es":L("Chuletas de cordero con papas y verduras de primavera","El cordero es ideal para la temporada de Pascua y un gusto para cualquier otra época del año. Las chuletas de lomo de cordero son un corte tierno y magro que se cocina fácilmente a la parrilla. Son una buena opción para probar cuando se cansa del pollo y la carne de res de siempre. Sírvalas con verduras de primavera como espárragos y zanahorias.","4","1-2 chuletas de cordero + 1 papa, 5 espárragos y 2 zanahorias",
["1 cucharada + 2 cucharaditas de aceite de oliva extra virgen (dividido)","2 dientes de ajo (picados)","1/2 cucharadita de sal kosher","1/4 cucharadita de pimienta negra","3 cucharadas de romero fresco (picado, dividido)","1 libra de chuletas de lomo de cordero magras (sin la grasa)","1 rocío, 0.25 g de aceite en aerosol antiadherente","4 papas rojas pequeñas (en cuartos, con cáscara)","8 zanahorias medianas (partidas por la mitad)","1 manojo de espárragos (unos 20 tallos, recortados)"],
["Mezcle 1 cucharada de aceite de oliva, el ajo, la sal, la pimienta y el romero. Cubra por completo las chuletas de cordero y déjelas marinar durante 2 horas en el refrigerador. Sáquelas del refrigerador 30 minutos antes de asarlas a la parrilla.","Precaliente el horno a 450 °F. Rocíe una bandeja para hornear con aceite en aerosol.","Coloque las papas en un tazón y mézclelas con 1 cucharadita de aceite de oliva y 2 cucharadas de romero picado. Colóquelas en la bandeja, póngala en el centro del horno precalentado y ase durante 10 minutos.","En el mismo tazón, coloque las zanahorias y mézclelas con el aceite y el romero restantes. Agréguelas a las papas junto con los espárragos y continúe asando durante 10 minutos.","Mientras tanto, precaliente la parrilla y coloque las chuletas de cordero directamente sobre ella. Áselas durante 5 minutos, luego voltéelas y continúe asándolas de 3 a 5 minutos. Deben alcanzar una temperatura interna de 135 °F."]),
"ar":L("ريش لحم الضأن مع البطاطس وخضار الربيع","لحم الضأن مناسب جدًا لموسم عيد الفصح، وهو وجبة لذيذة في أي وقت آخر من السنة. ريش ضأن الخاصرة قطعة طرية وقليلة الدهن يسهل طهيها على الشواية. وهي خيار جيد لتجربته حين تملّ من الدجاج واللحم البقري المعتادين. قدّمها مع خضار الربيع مثل الهليون والجزر.","4","1-2 ريشة ضأن + 1 حبة بطاطس و5 سيقان هليون و2 جزرة",
["1 ملعقة كبيرة + 2 ملعقة صغيرة زيت زيتون بكر ممتاز (مقسمة)","2 فص ثوم (مفروم)","½ ملعقة صغيرة ملح كوشر","¼ ملعقة صغيرة فلفل أسود","3 ملاعق كبيرة إكليل الجبل (روزماري) طازج (مفروم، مقسم)","1 رطل ريش ضأن من الخاصرة قليلة الدهن (مزالة الدهون)","1 بخّة، 0.25 جم بخاخ طهي غير لاصق","4 حبات بطاطس حمراء صغيرة (مقطعة أرباعًا مع القشر)","8 جزرات متوسطة (مقطعة إلى نصفين)","1 حزمة هليون (نحو 20 ساقًا، مقصوصة)"],
["اخلط 1 ملعقة كبيرة من زيت الزيتون والثوم والملح والفلفل وإكليل الجبل. اغمر ريش الضأن بالخليط تمامًا واتركها تتتبّل لمدة ساعتين في الثلاجة. أخرجها من الثلاجة قبل الشوي بـ 30 دقيقة.","سخّن الفرن مسبقًا إلى 450° فهرنهايت (230° مئوية). رُشّ صينية الخبز ببخاخ الطهي.","ضع البطاطس في وعاء وقلّبها مع 1 ملعقة صغيرة من زيت الزيتون و2 ملعقة كبيرة من إكليل الجبل المفروم. ضعها على الصينية وأدخلها في وسط الفرن المسخّن مسبقًا واشوِها لمدة 10 دقائق.","في الوعاء نفسه، ضع الجزر وقلّبه مع باقي الزيت وإكليل الجبل. أضفه إلى البطاطس مع الهليون وتابع الشوي لمدة 10 دقائق.","في الأثناء، سخّن الشواية مسبقًا وضع ريش الضأن مباشرة عليها. اشوِها لمدة 5 دقائق، ثم اقلبها وتابع الشوي لمدة 3 إلى 5 دقائق. يجب أن تصل درجة حرارتها الداخلية إلى 135° فهرنهايت (55° مئوية)."])}))
R.append((6454316,{
"es":L("Coles de Bruselas ralladas estilo hawaiano","Hay varias maneras de cortar las coles de Bruselas en láminas finas. Una es a mano: simplemente recorte el extremo del tallo de cada col para que quede plana sobre la tabla de cortar. Luego, con un cuchillo de chef, córtela en rebanadas muy finas. (Recortar el extremo evita que ruede). Otra manera es usar un procesador de alimentos. ¡Simplemente coloque las coles en el conducto y deje que el accesorio para rebanar haga el trabajo!","6","1/2 taza",
["16 onzas de coles de Bruselas frescas","1 cucharada de aceite de canola","1 cucharada de azúcar morena","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","1 lata (8 onzas) de trocitos de piña en jugo (bien escurridos)","1 cucharada de nueces de macadamia (picadas)"],
["Corte la base del centro de las coles de Bruselas y luego córtelas en rebanadas muy finas con un cuchillo, o rebánelas en un procesador de alimentos.","En un sartén grande a fuego medio, caliente el aceite hasta que esté bien caliente. Saltee las coles de Bruselas de 5 a 7 minutos, o hasta que comiencen a dorarse, revolviendo de vez en cuando. Para que queden más crujientes, saltéelas un par de minutos más.","Agregue el azúcar morena, la sal, la pimienta y la piña. Cocine de 3 a 5 minutos, o hasta que estén calientes. Espolvoree con las nueces de macadamia y sirva."]),
"ar":L("كرنب بروكسل المقطع شرائح رفيعة على الطريقة الهاوايية","هناك عدة طرق لتقطيع كرنب بروكسل إلى شرائح رفيعة. إحداها باليد: قصّ طرف ساق كل حبة بحيث تستقر مسطحة على لوح التقطيع. ثم باستخدام سكين الطهاة، قطّعها إلى شرائح رفيعة جدًا. (قصّ الطرف يمنعها من التدحرج). وهناك طريقة أخرى هي استخدام محضّر الطعام. ما عليك سوى وضع الحبات في فتحة التغذية وترك ملحق التقطيع يقوم بالعمل!","6","½ كوب",
["16 أونصة كرنب بروكسل طازج","1 ملعقة كبيرة زيت كانولا","1 ملعقة كبيرة سكر بني","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 علبة (8 أونصات) قطع أناناس في عصيرها (مصفاة جيدًا)","1 ملعقة كبيرة مكاديميا (مفرومة)"],
["اقطع قواعد حبات كرنب بروكسل، ثم قطّعها إلى شرائح رفيعة جدًا بالسكين، أو قطّعها في محضّر الطعام.","في مقلاة كبيرة على نار متوسطة، سخّن الزيت حتى يسخن جيدًا. قلّب كرنب بروكسل لمدة 5 إلى 7 دقائق، أو حتى يبدأ بالتحمير، مع التحريك من حين لآخر. للحصول على كرنب أكثر قرمشة، قلّبه لبضع دقائق إضافية.","أضف السكر البني والملح والفلفل والأناناس وقلّب. اطهِ لمدة 3 إلى 5 دقائق، أو حتى يسخن جيدًا. رُشّ المكاديميا فوقه وقدّمه."])}))
R.append((6456214,{
"es":L("Bowls de fajitas de arroz de coliflor y frijoles","En esta comida vegana y apta para la diabetes, los frijoles aportan una deliciosa proteína de origen vegetal. Hacer arroz con coliflor es una excelente manera de obtener más nutrientes en su alimentación sin agregar carbohidratos adicionales. Cubra su bowl con un poco de cilantro fresco o salsa para darle un toque extra.","4","1 bowl",
["1 cabeza de coliflor (mediana)","2 cucharadas de aceite de oliva","1 lata (15 onzas) de frijoles negros (sin sal agregada, escurridos y enjuagados)","1 pimiento rojo mediano (en tiras finas)","1 pimiento amarillo mediano (en tiras finas)","1 cebolla morada mediana (en rodajas finas)","2 cucharaditas de comino molido","1 cucharadita de pimentón ahumado","1/2 cucharadita de chile en polvo","1/2 cucharadita de sal kosher","1/2 cucharadita de pimienta negra","1 limón verde mediano (partido por la mitad)","2 cucharadas de cilantro fresco (picado, para decorar)"],
["En un procesador de alimentos, pulse la coliflor hasta que parezca arroz. Reserve.","En un sartén grande, caliente el aceite de oliva a fuego medio. Agregue los pimientos en tiras y la cebolla morada. Saltee hasta que las verduras estén tiernas, unos 5 a 7 minutos.","Agregue al sartén la coliflor en forma de arroz. Espolvoree el comino molido, el pimentón ahumado, el chile en polvo, la sal kosher y la pimienta negra. Revuelva bien para mezclar.","Cocine la mezcla de coliflor de 8 a 10 minutos más, revolviendo de vez en cuando, hasta que la coliflor esté tierna.","Incorpore los frijoles negros y cocine de 3 a 5 minutos más, hasta que todo esté caliente.","Exprima el jugo del limón sobre la mezcla y revuelva.","Divida la mezcla de fajitas de arroz de coliflor y frijoles en bowls. Sirva de inmediato. Decore con cilantro fresco si lo desea."]),
"ar":L("أطباق فاهيتا بأرز القرنبيط والفاصوليا","في هذه الوجبة النباتية الصديقة لمرضى السكري، تضيف الفاصوليا بروتينًا نباتيًا لذيذًا إلى وجبتك. وصنع الأرز من القرنبيط طريقة رائعة للحصول على مزيد من العناصر الغذائية في نظامك الغذائي دون إضافة كربوهيدرات زائدة. زيّن طبقك بقليل من الكزبرة الخضراء الطازجة أو الصلصة لنكهة إضافية.","4","1 طبق",
["1 رأس قرنبيط (متوسط)","2 ملعقة كبيرة زيت زيتون","1 علبة (15 أونصة) فاصوليا سوداء (بدون ملح مضاف، مصفاة ومشطوفة)","1 حبة فلفل رومي أحمر متوسطة (مقطعة شرائح رفيعة)","1 حبة فلفل رومي أصفر متوسطة (مقطعة شرائح رفيعة)","1 حبة بصل أحمر متوسطة (مقطعة شرائح رفيعة)","2 ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة مسحوق الفلفل الحار","½ ملعقة صغيرة ملح كوشر","½ ملعقة صغيرة فلفل أسود","1 حبة ليمون أخضر متوسطة (مقطوعة إلى نصفين)","2 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة، للتزيين)"],
["في محضّر الطعام، اخلط القرنبيط على دفعات قصيرة حتى يشبه الأرز. اتركه جانبًا.","في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة. أضف شرائح الفلفل الرومي والبصل الأحمر. قلّب حتى تنضج الخضار وتصبح طرية، نحو 5 إلى 7 دقائق.","أضف قرنبيط الأرز إلى المقلاة. رُشّ الكمون المطحون والبابريكا المدخنة ومسحوق الفلفل الحار وملح الكوشر والفلفل الأسود. قلّب جيدًا للخلط.","اطهِ خليط القرنبيط لمدة 8 إلى 10 دقائق إضافية مع التحريك من حين لآخر، حتى يصبح القرنبيط طريًا.","أضف الفاصوليا السوداء واطهِ لمدة 3 إلى 5 دقائق إضافية حتى يسخن كل شيء جيدًا.","اعصر عصير الليمون الأخضر فوق الخليط وقلّب.","وزّع خليط فاهيتا أرز القرنبيط والفاصوليا في الأطباق. قدّمه فورًا. زيّنه بالكزبرة الخضراء الطازجة إن رغبت."])}))
R.append((6456614,{
"ar":L("دجاج وبطاطا حلوة في الطنجرة البطيئة اقتصادي","ليس لديك وقت للطهي؟ جرّب هذا الدجاج المطهو في الطنجرة البطيئة للعشاء. تمنح البطاطا الحلوة وخردل ديجون والسكر البني نكهة مميزة ولذيذة. وإضافة طبق جانبي من البروكلي والقرنبيط المطهوين على البخار تجعل هذه الوجبة متكاملة ولا تتطلب سوى أقل من 15 دقيقة من التحضير الفعلي.","4","1 فخذ دجاج مع 2-3 شرائح بطاطا حلوة و1 كوب من خليط البروكلي والقرنبيط",
["1 رطل أفخاذ دجاج بدون عظم وبدون جلد","1 حبة بصل متوسطة (مفرومة)","1 رطل بطاطا حلوة (مقشرة ومقطعة إلى شرائح دائرية كبيرة)","1½ كوب مرق دجاج قليل الصوديوم","3 ملاعق كبيرة بديل السكر البني قليل السعرات","¼ ملعقة صغيرة زعتر مجفف","2 ملعقة كبيرة خردل ديجون","1 ورقة غار","4 أكواب زهيرات بروكلي وقرنبيط طازجة أو مجمدة (مطهوة على البخار)"],
["ضع الدجاج في الطنجرة البطيئة. ضع البصل والبطاطا الحلوة فوق الدجاج.","أضف مرق الدجاج وخليط السكر البني والزعتر والخردل وورقة الغار. اطهِ على نار هادئة لمدة 5 إلى 6 ساعات أو حتى ينضج الدجاج.","أخرج ورقة الغار وقدّمه مع البروكلي والقرنبيط."])}))
R.append((6457517,{
"es":L("Champiñones rellenos de espinacas y queso feta","Los champiñones rellenos de espinacas y queso feta son un aperitivo delicioso y sabroso que combina el sabor terroso de los champiñones con un relleno cremoso y lleno de sabor. Estos bocadillos salados son un excelente aperitivo para fiestas, reuniones festivas o como un delicioso complemento para una mesa de tapas.","8","2 champiñones rellenos",
["16 champiñones cremini (baby bella) grandes (limpios y sin tallos)","1 cucharada de aceite de oliva","4 tazas de espinacas (picadas)","2 dientes de ajo (picados)","1/2 taza de queso feta (desmenuzado)","1/2 taza de queso parmesano (reducido en grasa, rallado)","2 cucharadas de yogur griego natural sin grasa","1/8 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Precaliente el horno a 375 grados F y forre una bandeja para hornear con papel pergamino.","En un sartén, caliente 1 cucharada de aceite de oliva a fuego medio. Agregue el ajo picado y las espinacas picadas, y saltee de 2 a 3 minutos hasta que las espinacas se marchiten y se evapore el exceso de humedad. Retire el sartén del fuego.","En un tazón, combine las espinacas y el ajo salteados con el queso feta desmenuzado, el queso parmesano rallado, el yogur griego natural, la sal y la pimienta. Asegúrese de que todos los ingredientes estén bien mezclados.","Tome los champiñones limpios y rellene cada sombrero con la mezcla de espinacas y queso, presionando suavemente.","Coloque los champiñones rellenos en la bandeja preparada. Si lo desea, puede rociarlos ligeramente con aceite en aerosol para ayudar a que se doren.","Hornee los champiñones rellenos en el horno precalentado durante aproximadamente 15 a 20 minutos, o hasta que estén tiernos y el relleno esté caliente y ligeramente dorado."]),
"ar":L("فطر محشو بالسبانخ وجبن الفيتا","الفطر المحشو بالسبانخ وجبن الفيتا مقبّلات لذيذة وشهية تجمع بين نكهة الفطر الترابية وحشوة كريمية غنية بالنكهة. تُعد هذه اللقيمات المالحة مقبّلات ممتازة للحفلات والتجمعات في المناسبات، أو إضافة لذيذة إلى مائدة التاباس.","8","2 حبة فطر محشوة",
["16 حبة فطر كريميني (بيبي بيلا) كبيرة (منظفة ومزالة السيقان)","1 ملعقة كبيرة زيت زيتون","4 أكواب سبانخ (مفرومة)","2 فص ثوم (مفروم)","½ كوب جبن فيتا (مفتت)","½ كوب جبن بارميزان (قليل الدسم، مبشور)","2 ملعقة كبيرة زبادي يوناني سادة خالٍ من الدسم","⅛ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية) وبطّن صينية الخبز بورق الزبدة.","في مقلاة، سخّن 1 ملعقة كبيرة من زيت الزيتون على نار متوسطة. أضف الثوم المفروم والسبانخ المفرومة وقلّب لمدة 2 إلى 3 دقائق حتى تذبل السبانخ وتتبخر الرطوبة الزائدة. ارفع المقلاة عن النار.","في وعاء الخلط، اخلط السبانخ والثوم المقلّبين مع جبن الفيتا المفتت وجبن البارميزان المبشور والزبادي اليوناني السادة والملح والفلفل. تأكد من امتزاج جميع المكونات جيدًا.","خذ حبات الفطر المنظفة واملأ كل غطاء بخليط السبانخ والجبن، مع الضغط عليه برفق.","رتّب حبات الفطر المحشوة على الصينية المجهزة. إن رغبت، يمكنك رشّها قليلًا ببخاخ الطهي للمساعدة على التحمير.","اخبز الفطر المحشو في الفرن المسخّن مسبقًا لمدة 15 إلى 20 دقيقة تقريبًا، أو حتى يصبح طريًا وتسخن الحشوة وتتحمر قليلًا."])}))
R.append((6457837,{
"es":L("Granizado de sandía y limón verde","¡Pruebe esta alternativa refrescante a las bebidas azucaradas! Está hecho con sandía fresca para lograr un sabor ligeramente dulce sin azúcar agregada, además de limón verde cítrico y menta fresca. ¡Perfecto para un caluroso día de verano!","4","6 onzas (aproximadamente 3/4 de taza)",
["2 tazas de sandía","2 tazas de hielo","1/4 taza de jugo de limón verde (de aproximadamente 2 limones)","2 cucharadas de hojas de menta fresca (y más para decorar)"],
["Licúe la sandía, el hielo, el jugo de limón verde y la menta en una licuadora hasta obtener la consistencia de un granizado. Sirva en vasos y decore con una ramita de menta (opcional)."]),
"ar":L("سلاش البطيخ والليمون الأخضر","جرّب هذا البديل المنعش للمشروبات السكرية! يُحضّر من البطيخ الطازج للحصول على مذاق حلو خفيف دون سكر مضاف، مع الليمون الأخضر المنعش والنعناع البارد. مثالي ليوم صيفي حار!","4","6 أونصات (نحو ¾ كوب)",
["2 كوب بطيخ","2 كوب ثلج","¼ كوب عصير ليمون أخضر (من نحو 2 ليمونة)","2 ملعقة كبيرة أوراق نعناع طازجة (والمزيد للتزيين)"],
["اخلط البطيخ والثلج وعصير الليمون الأخضر والنعناع في الخلاط حتى تحصل على قوام السلاش. اسكبه في الأكواب وزيّنه بغصن نعناع (اختياري)."])}))
R.append((6458377,{
"es":L("Hamburguesas de pavo con espinacas y queso feta","Estas hamburguesas de espinacas y queso feta son una alternativa más saludable a las hamburguesas de carne de res tradicionales. Sírvalas sobre hojas de lechuga para una comida baja en carbohidratos, o en un pan integral si su plan de alimentación lo permite. ¡Estas deliciosas hamburguesas seguramente serán un éxito con toda la familia!","4","1 hamburguesa",
["12 onzas de espinacas congeladas (descongeladas)","8 onzas de carne molida de pavo magra","1/4 taza de cebolla morada (finamente picada)","2 dientes de ajo (picados)","1 huevo entero (batido)","2 cucharadas de pan molido integral","1/4 cucharadita de pimienta negra","2 cucharadas de queso feta reducido en grasa (desmenuzado)","1 cucharada de aceite de oliva (para freír)"],
["Exprima el exceso de agua de las espinacas descongeladas.","En un tazón grande, mezcle las espinacas escurridas, el pavo molido, la cebolla morada, el ajo, el huevo batido, el pan molido, el queso feta y la pimienta.","Forme 4 hamburguesas del mismo tamaño.","Caliente el aceite de oliva en un sartén grande a fuego medio. Cocine las hamburguesas de 4 a 5 minutos por lado, hasta que estén bien cocidas y de un color dorado intenso."]),
"ar":L("برغر الديك الرومي بالسبانخ وجبن الفيتا","هذا البرغر بالسبانخ وجبن الفيتا بديل أكثر صحة لأقراص اللحم البقري المعتادة. قدّمه على أوراق الخس لوجبة منخفضة الكربوهيدرات، أو في خبز القمح الكامل إذا كان نمطك الغذائي يسمح بذلك. هذا البرغر اللذيذ سيحظى بالتأكيد بإعجاب العائلة كلها!","4","1 برغر",
["12 أونصة سبانخ مجمدة (مذابة)","8 أونصات لحم ديك رومي مفروم قليل الدسم","¼ كوب بصل أحمر (مفروم ناعمًا)","2 فص ثوم (مفروم)","1 بيضة كاملة (مخفوقة)","2 ملعقة كبيرة فتات خبز القمح الكامل","¼ ملعقة صغيرة فلفل أسود","2 ملعقة كبيرة جبن فيتا قليل الدسم (مفتت)","1 ملعقة كبيرة زيت زيتون (للقلي)"],
["اعصر السبانخ المذابة للتخلص من الماء الزائد.","في وعاء كبير، اخلط السبانخ المصفاة ولحم الديك الرومي المفروم والبصل الأحمر والثوم والبيض المخفوق وفتات الخبز وجبن الفيتا والفلفل.","شكّل الخليط 4 أقراص متساوية.","سخّن زيت الزيتون في مقلاة كبيرة على نار متوسطة. اطهِ الأقراص لمدة 4 إلى 5 دقائق لكل جانب حتى تنضج تمامًا وتتحمر بلون ذهبي داكن."])}))
R.append((6459025,{
"es":L("Tiras de pollo con yogur, limón y especias","Con un toque ácido y ahumado, estos tiernos bocados de pollo son una cena fácil para las noches de verano entre semana. Mezcle el pollo con la marinada por la mañana y estará listo para ir a la parrilla por la noche. Sírvalo con una guarnición de ensalada fresca de brócoli.","4","2 tiras",
["8 filetes de pechuga de pollo enteros ((aproximadamente 1 libra))","1 taza de yogur griego natural sin grasa","2 cucharadas de jugo de limón","1 cucharada de ralladura de limón","1 cucharada de pimentón","1 cucharada de jengibre fresco (rallado)","1 cucharadita de comino molido","1/2 cucharadita de ajo en polvo","1/2 cucharadita de sal","1 limón mediano (en cuartos, opcional, para servir)"],
["Combine todos los ingredientes, excepto los cuartos de limón, en una bolsa de plástico resellable de un galón. Cierre bien y agite de un lado a otro hasta que el pollo esté bien cubierto. Refrigere durante 8 horas.","Caliente a fuego medio-alto una plancha acanalada bien cubierta con aceite en aerosol. Saque el pollo de la marinada, deseche la marinada y áselo 3 minutos por cada lado, o hasta que ya no esté rosado en el centro. Sirva con los cuartos de limón, si lo desea."]),
"ar":L("أصابع الدجاج بالزبادي والليمون والتوابل","أصابع الدجاج الطرية هذه ذات النكهة الحامضة والمدخنة عشاء سهل لأمسيات الصيف في أيام الأسبوع. قلّب الدجاج في التتبيلة في الصباح ليكون جاهزًا للشوي في المساء. قدّمه مع طبق جانبي من سلطة البروكلي الطازجة.","4","2 إصبع دجاج",
["8 قطع صدر دجاج كاملة ((نحو 1 رطل))","1 كوب زبادي يوناني سادة خالٍ من الدسم","2 ملعقة كبيرة عصير ليمون","1 ملعقة كبيرة قشر ليمون مبشور","1 ملعقة كبيرة بابريكا","1 ملعقة كبيرة زنجبيل طازج (مبشور)","1 ملعقة صغيرة كمون مطحون","½ ملعقة صغيرة مسحوق الثوم","½ ملعقة صغيرة ملح","1 حبة ليمون متوسطة (مقطعة أرباعًا، اختيارية، للتقديم)"],
["اخلط جميع المكونات، ما عدا أرباع الليمون، في كيس بلاستيكي محكم الإغلاق سعة جالون. أغلقه جيدًا وحرّكه ذهابًا وإيابًا حتى يتغطى الدجاج جيدًا. ضعه في الثلاجة لمدة 8 ساعات.","سخّن مقلاة شواء مدهونة بسخاء ببخاخ الطهي على نار متوسطة إلى عالية. أخرج الدجاج من التتبيلة وتخلص منها، واشوِه لمدة 3 دقائق على كل جانب أو حتى يختفي اللون الوردي من الوسط. قدّمه مع أرباع الليمون إن رغبت."])}))
R.append((6459632,{
"es":L("Huevo duro","Los huevos son un alimento naturalmente apto para la diabetes, rico en proteína y bajo en carbohidratos. Además, son excelentes ingredientes en muchas recetas diferentes, incluida nuestra ensalada de huevo fácil. Parece que hay cientos de recetas de huevos duros en internet, pero esta de la chef Jennifer Lamplough es nuestra favorita porque es casi infalible y da resultados constantes. ¿Su secreto? Compre y refrigere los huevos que piensa cocer de 10 días a 2 semanas antes de cocerlos. Los huevos más viejos se cuecen y se pelan mejor que los huevos frescos. Además, si se cuecen de más, la yema desarrolla un anillo verdoso alrededor. Esto asusta a muchos cocineros primerizos, pero no se preocupe. Es perfectamente seguro comerlo; solo significa que se cocieron un poco de más.","6","1 huevo",
["6 huevos grandes","4 tazas de agua"],
["Coloque los huevos en una sola capa en el fondo de una olla grande y cúbralos con agua fría de modo que haya aproximadamente una pulgada de agua sobre los huevos.","Coloque la olla sobre un quemador de la estufa, pero antes de encender el fuego, programe un temporizador para 20 minutos.","Inicie el temporizador y luego encienda el fuego al máximo y lleve a hervor. Cuando hierva, reduzca a fuego lento y deje cocer a fuego lento hasta que suene el temporizador.","Cuando suene el temporizador, escurra de inmediato el agua de la olla y luego sacuda suavemente los huevos dentro de la olla para quebrar las cáscaras.","Cúbralos con agua con hielo y déjelos reposar en el agua con hielo durante 15 minutos.","Escurra el agua con hielo, luego haga rodar suavemente cada huevo sobre una toalla de papel para aflojar la cáscara y pele el huevo.","Guárdelos en un recipiente hermético en el refrigerador hasta por una semana."]),
"ar":L("بيض مسلوق","البيض غذاء مناسب لمرضى السكري بطبيعته، وهو غني بالبروتين ومنخفض الكربوهيدرات. كما أنه مكوّن رائع في العديد من الوصفات المختلفة، ومنها وصفتنا لسلطة البيض السهلة. يبدو أن هناك مئات الوصفات للبيض المسلوق على الإنترنت، لكن هذه الوصفة من الشيف جينيفر لامبلو هي المفضلة لدينا لأنها شبه مضمونة وتعطي نتائج ثابتة. سرّها؟ اشترِ البيض الذي تنوي سلقه وضعه في الثلاجة قبل سلقه بمدة تتراوح بين 10 أيام وأسبوعين. فالبيض الأقدم يُسلق ويُقشّر بصورة أفضل من البيض الطازج. كما أن الإفراط في سلقه يجعل صفار البيض يكتسب حلقة مخضرّة حوله. وهذا يخيف كثيرًا من الطهاة المبتدئين، لكن لا داعي للقلق. فتناوله آمن تمامًا، وهو يعني فقط أن البيض سُلق أكثر قليلًا من اللازم.","6","1 بيضة",
["6 بيضات كبيرة","4 أكواب ماء"],
["ضع البيض في طبقة واحدة في قاع قدر كبير وغطّه بالماء البارد بحيث يعلو الماء البيض بنحو بوصة واحدة.","ضع القدر على موقد الطباخ، ولكن قبل تشغيل النار اضبط المؤقت على 20 دقيقة.","شغّل المؤقت ثم اجعل النار على أعلى درجة واتركه حتى يغلي. عندما يغلي، اخفض النار إلى غليان هادئ واتركه على الغليان الهادئ حتى يرن المؤقت.","عندما يرن المؤقت، صفِّ الماء من القدر فورًا ثم هزّ البيض برفق داخل القدر لتشقق القشور.","غطِّه بماء مثلج واتركه في الماء المثلج لمدة 15 دقيقة.","صفِّ الماء المثلج، ثم دحرج كل بيضة برفق على منديل ورقي لتفكيك القشرة، ثم قشّر البيضة.","احفظه في وعاء محكم الإغلاق في الثلاجة لمدة تصل إلى أسبوع."])}))
R.append((6460004,{
"es":L("Papas fritas de camote al horno con especias y salsa de yogur baja en grasa","Deliciosamente sazonadas, estas no son las papas fritas de camote de siempre. Servidas con una salsa cremosa y ligeramente ácida para mojar, esta guarnición le encantará preparar durante todo el año.","6","1/2 taza de papas fritas de camote + 2 cucharadas de salsa para mojar",
["2 camotes grandes (pelados y cortados en bastones)","1 cucharada de aceite de oliva","1 cucharadita de pimentón ahumado","1/2 cucharadita de semillas de comino","1/2 cucharadita de ajo en polvo","1/2 cucharadita de cebolla en polvo","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","1 rocío, 0.25 g de aceite en aerosol antiadherente","1/2 taza de yogur griego natural sin grasa","1 cucharada de jugo de limón","1 cucharadita de miel de maple","1/2 cucharadita de comino molido"],
["Precaliente el horno a 425 grados F y forre una bandeja para hornear con papel pergamino.","En un tazón grande, mezcle los bastones de camote con el aceite de oliva, el pimentón ahumado, el comino, el ajo en polvo, la cebolla en polvo, la sal y la pimienta negra hasta que queden cubiertos de manera uniforme.","Acomode los bastones de camote sazonados en una sola capa sobre la bandeja preparada, asegurándose de que no queden amontonados.","Rocíe ligeramente los bastones con aceite en aerosol para que queden más crujientes.","Hornee en el horno precalentado de 20 a 25 minutos, o hasta que los bastones de camote estén dorados y crujientes, volteándolos a la mitad del tiempo.","Para la salsa: en un tazón pequeño, bata el yogur griego bajo en grasa, el jugo de limón, la miel de maple y el comino molido.","Sirva la salsa a un lado."]),
"ar":L("أصابع البطاطا الحلوة المخبوزة بالتوابل مع صلصة غمس بالزبادي قليل الدسم","هذه ليست أصابع البطاطا الحلوة المعتادة، فهي متبّلة بنكهة لذيذة. وتُقدَّم مع صلصة غمس كريمية وحامضة قليلًا، وهي طبق جانبي سترغب في تحضيره طوال العام.","6","½ كوب أصابع بطاطا حلوة + 2 ملعقة كبيرة صلصة غمس",
["2 حبة بطاطا حلوة كبيرة (مقشرة ومقطعة على شكل أصابع)","1 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة بابريكا مدخنة","½ ملعقة صغيرة بذور كمون","½ ملعقة صغيرة مسحوق الثوم","½ ملعقة صغيرة مسحوق البصل","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود","1 بخّة، 0.25 جم بخاخ طهي غير لاصق","½ كوب زبادي يوناني سادة خالٍ من الدسم","1 ملعقة كبيرة عصير ليمون","1 ملعقة صغيرة شراب القيقب","½ ملعقة صغيرة كمون مطحون"],
["سخّن الفرن مسبقًا إلى 425 درجة فهرنهايت (220° مئوية) وبطّن صينية الخبز بورق الزبدة.","في وعاء كبير، قلّب أصابع البطاطا الحلوة مع زيت الزيتون والبابريكا المدخنة والكمون ومسحوق الثوم ومسحوق البصل والملح والفلفل الأسود حتى تتغطى بالتساوي.","رتّب أصابع البطاطا الحلوة المتبّلة في طبقة واحدة على الصينية المجهزة، مع التأكد من عدم تكدّسها.","رُشّ الأصابع قليلًا ببخاخ الطهي لمزيد من القرمشة.","اخبزها في الفرن المسخّن مسبقًا لمدة 20 إلى 25 دقيقة أو حتى تصبح أصابع البطاطا الحلوة ذهبية اللون ومقرمشة، مع قلبها في منتصف المدة.","لصلصة الغمس: في وعاء صغير، اخفق الزبادي اليوناني قليل الدسم وعصير الليمون وشراب القيقب والكمون المطحون.","قدّم صلصة الغمس على الجانب."])}))
dump(1,R)
