from h import *
O=[]
O.append(R(6306893,
("Salsa de frutos rojos","Esta salsa de frutos rojos es fresca, colorida y llena de dulzura natural. La mezcla de frutos rojos aporta un sabor vivo, mientras que las especias y el jugo fresco de limón verde logran un buen equilibrio entre dulce y ácido. Es fácil de preparar y combina muy bien con platos a la parrilla o como un aderezo ligero y refrescante.","5","1/4 de taza",
["1/4 de cucharadita de chile en polvo","1/4 de cucharadita de pimienta negra","1/4 de cucharadita de sal","1 cucharada de jugo fresco de limón verde","1/4 de taza de cilantro fresco (picado fino)","1/4 de taza de cebolla morada (en cubitos)","1/4 de aguacate mediano (en cubitos)","1/2 taza de fresas congeladas (descongeladas y escurridas)","1/2 taza de arándanos azules congelados (sin azúcar añadida, descongelados y escurridos)"],
["Mezcle todos los ingredientes en un tazón pequeño y sirva de inmediato, o refrigere durante 30 minutos para que se mezclen los sabores antes de servir."],[],[]),
("صلصة التوت","صلصة التوت هذه منعشة وملوّنة وغنية بالحلاوة الطبيعية. يضفي مزيج التوت نكهة زاهية، بينما تمنح التوابل وعصير الليمون الأخضر الطازج توازنًا لطيفًا بين الحلو والحامض. سهلة التحضير وتتناسب جيدًا مع الأطباق المشوية أو كإضافة خفيفة ومنعشة.","5","¼ كوب",
["¼ ملعقة صغيرة مسحوق الفلفل الحار","¼ ملعقة صغيرة فلفل أسود","¼ ملعقة صغيرة ملح","1 ملعقة كبيرة عصير ليمون أخضر طازج","¼ كوب كزبرة خضراء طازجة (مفرومة ناعمًا)","¼ كوب بصل أحمر (مقطّع مكعبات)","¼ حبة أفوكادو متوسطة (مقطّعة مكعبات)","½ كوب فراولة مجمدة (مذابة ومصفّاة)","½ كوب توت أزرق مجمد (بدون سكر مضاف، مذاب ومصفّى)"],
["اخلط جميع المكونات في وعاء صغير وقدّمها فورًا، أو ضعها في الثلاجة لمدة 30 دقيقة لتتمازج النكهات قبل التقديم."],[],[])))
O.append(R(6309151,None,
("دجاج بالعسل وخردل الحجر المطحون","جرّب دجاج العسل والخردل البسيط وغني النكهة الذي ستحبه العائلة. قدّمه مع حبوب كاملة وخضار غير نشوية للحصول على وجبة متكاملة.","6","حوالي نصف صدر دجاج",
["1 ملعقة كبيرة زيت زيتون","2 ملعقة كبيرة خردل ديجون","2 ملعقة كبيرة خردل ديجون خشن","1 ملعقة كبيرة عسل","1 ملعقة كبيرة عصير ليمون","2 رطل صدور دجاج (بدون عظم وبدون جلد، منظّفة جيدًا)"],
["اخلط جميع مكونات التتبيلة في وعاء متوسط، وضعها في كيس بلاستيكي كبير محكم الإغلاق. انقع صدور الدجاج في التتبيلة لمدة 30 دقيقة على الأقل، أو طوال الليل في الثلاجة للحصول على أفضل نتيجة.","سخّن الشواية مسبقًا على حرارة متوسطة إلى عالية وضع الدجاج على شبكة الشواء. اطهه على حرارة مباشرة (مع إغلاق غطاء الشواية) لمدة 8-10 دقائق لكل جانب، أو حتى تبلغ درجة الحرارة الداخلية 165° فهرنهايت (75° مئوية)."],[],[])))
O.append(R(6309831,
("Plátano pequeño","Información nutricional del plátano","1","1 plátano pequeño",["1 plátano pequeño"],[],[],[]),
("موزة صغيرة","المعلومات الغذائية للموز","1","موزة صغيرة",["1 موزة صغيرة"],[],[],[])))
O.append(R(6310729,None,
("حساء الخضار المفضل","تحضير الحساء طريقة رائعة للاستفادة من بعض الخضار الموجودة في الثلاجة أو الخزانة وتوفير بعض المال. هذا الحساء رائع كما هو، ويمكنك أيضًا استبدال بعض مكوناته بمكونات أخرى من الثلاجة تحتاج إلى استهلاك.","14","1 كوب",
["½ رطل لحم بقري مفروم (من الكتف)","7 أكواب طماطم (مقشّرة ومقطّعة)","4 أكواب ماء","1 علبة (14.5 أونصة) فاصوليا خضراء مقطّعة (بدون ملح مضاف، مصفّاة ومشطوفة)","1 علبة (15 أونصة) بازلاء (بدون ملح مضاف، مصفّاة ومشطوفة)","1 علبة (15 أونصة) ذرة (بدون ملح مضاف، مصفّاة ومشطوفة)","2 حبة جزر متوسطة (مقشّرة ومقطّعة)","1 عود كرفس (مقطّع)","3 حبات بطاطس متوسطة (5 أونصات لكل حبة، مقشّرة ومقطّعة مكعبات)","1 حبة بصل متوسطة (مقطّعة مكعبات)","¼ كوب أرز جاف","⅛ ملعقة صغيرة فلفل أسود","⅛ ملعقة صغيرة رقائق فلفل أحمر مجروش","½ ملعقة صغيرة ملح","½ ملعقة صغيرة مسحوق الثوم"],
["ضع اللحم المفروم في قدر حساء سعة 2 غالون وحمّره على حرارة متوسطة. أخرج اللحم وصفّه جيدًا من الدهن. امسح بقايا الدهن من القدر.","أعد اللحم إلى القدر، ثم أضف الطماطم والماء. اترك الخليط حتى يغلي على نار هادئة واطهه مغطى حتى تلين الطماطم ويتكوّن مرق غني بالعصارة، لمدة 20 دقيقة تقريبًا.","أضف المكونات المتبقية، وغطِّ القدر، واستمر في الطهي 60 دقيقة إضافية لتتمازج النكهات."],[],[])))
O.append(R(6311044,None,
("دجاج مشوي في قدر واحد مع قرع الأكورن","ستملأ التفاحات والقرفة في هذا الطبق الرئيسي المالح المطهو في قدر واحد منزلك برائحة الخريف اللذيذة.","4","1 فخذ دجاج + 2 شريحة قرع أكورن + حوالي 4 شرائح تفاح",
["4 أفخاذ دجاج بدون عظم وبدون جلد (4 أونصات لكل فخذ)","1 ملعقة صغيرة روزماري مجفف","1 بخّة (0.25 غرام) من بخاخ الطهي غير اللاصق","1 ملعقة صغيرة زيت الكانولا","1 حبة قرع أكورن متوسطة (1¼ رطل)","1 حبة تفاح غرانى سميث متوسطة أو أي تفاح حامض آخر (منزوعة القلب ومقطّعة شرائح)","1 ملعقة كبيرة عسل","¼ ملعقة صغيرة قرفة مطحونة","½ كوب ماء"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية).","تبّل الدجاج بالروزماري. رشّ قدرًا هولنديًا أو قدرًا صالحًا للفرن ببخاخ الطهي وأضف الزيت. سخّنه على حرارة متوسطة إلى عالية. ضع الدجاج في القدر وحمّره لمدة 3 دقائق لكل جانب.","اقطع قرع الأكورن إلى نصفين بالطول وأخرج البذور بملعقة. اقطع كل نصف إلى أربعة أرباع، وتخلّص من الأطراف.","ضع قرع الأكورن وشرائح التفاح حول الدجاج. رشّ العسل بالتساوي على القرع وشرائح التفاح، ثم رشّها بالقرفة. اسكب الماء فوق الدجاج.","اخبزه في الفرن لمدة 45 دقيقة بدون غطاء. عند التقديم، اسكب بعضًا من العصارة فوق الدجاج والقرع والتفاح."],[],[])))
O.append(R(6311574,None,
("تارتات القرع الصغيرة","لن يعرف أحد أن هذه الحلوى البسيطة مناسبة لمرضى السكري! إنها حلوى مميزة للمناسبات والأعياد!","30","1 تارت",
["8 أونصات جبن كريمي خفيف (ليّن)","30 قطعة بسكويت فانيلا صغيرة كاملة","¼ كوب كريمة حامضة خفيفة","¼ كوب بديل سكر قليل السعرات","1 بيضة كبيرة","½ ملعقة صغيرة خلاصة الفانيليا","¾ كوب قرع معلّب نقي","½ ملعقة صغيرة قرفة مطحونة","⅛ ملعقة صغيرة جوزة الطيب المطحونة"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية).","بطّن قالب المافن الصغير بكاسات ورقية للخبز، وضع رقاقة Nilla واحدة في قاع كل كأس.","في وعاء متوسط، أضف المكونات المتبقية واخلطها بخلاط كهربائي حتى تصبح ناعمة.","املأ كل كأس مافن بخليط القرع والجبن الكريمي.","ضع قالب المافن في الفرن واخبزه لمدة 30 دقيقة أو حتى ينضج. قدّمه باردًا."],[],[])))
O.append(R(6311769,
("Tortilla de grano entero","Información nutricional de una tortilla de grano entero","1","1 tortilla de 6 pulgadas",["1 tortilla de grano entero de 6 pulgadas"],[],[],[]),
("خبز التورتيلا بالحبوب الكاملة","المعلومات الغذائية لخبز التورتيلا بالحبوب الكاملة","1","1 قطعة تورتيلا قطرها 6 بوصات",["1 قطعة تورتيلا بالحبوب الكاملة قطرها 6 بوصات"],[],[],[])))
O.append(R(6311954,
("Pollo con maní y arroz de coliflor","¿Se le antoja comida asiática pero no quiere tantos carbohidratos? ¡Pruebe esta versión más saludable del pollo con maní que sustituye el arroz blanco por arroz de coliflor! La coliflor es una excelente alternativa baja en carbohidratos al arroz y aporta una porción adicional de verduras nutritivas a este plato clásico.","4","1/2 taza de arroz de coliflor y 1 taza de pollo con salsa de maní",
["1 porción de aceite en aerosol antiadherente","1 libra de pechuga de pollo (cortada en cubos)","1/2 cebolla amarilla mediana (en cubitos)","2 dientes de ajo (picados)","2 cucharaditas de jengibre fresco (rallado)","1 cucharadita de aceite de ajonjolí tostado","1 cucharadita de salsa tailandesa de chile y ajo","1 1/2 cucharaditas de salsa de soya","1 cucharada de mantequilla de maní","2 cucharadas de leche de coco","2 cucharadas de leche de almendras sin azúcar","14 1/2 onzas de tomates en cubitos enlatados (escurridos)","1/4 de taza de cilantro fresco (picado)","2 tazas de \"arroz\" de coliflor","1 cucharada de maní (picado, opcional)"],
["Rocíe una sartén grande con aceite en aerosol y caliéntela a fuego medio. Agregue el pollo y cocínelo, revolviendo con frecuencia, hasta que esté dorado. Pase el pollo a un plato y vuelva a poner la sartén a fuego medio.","Agregue el aceite de ajonjolí y añada la cebolla, el ajo, el jengibre y la salsa de chile y ajo. Cocine, revolviendo de vez en cuando, hasta que la cebolla se ablande, de 4 a 5 minutos.","Agregue la salsa de soya, la mantequilla de maní, la leche de coco, la leche de almendras y los tomates. Revuelva hasta que la salsa quede cremosa y la mantequilla de maní esté bien distribuida.","Deje que hierva a fuego lento. Regrese el pollo a la sartén y agregue el cilantro picado. Reduzca el fuego a bajo y cocine a fuego lento hasta que la salsa espese, de 3 a 4 minutos.","Sirva el pollo sobre el arroz de coliflor y decore con el maní y más cilantro, si lo desea."],[],[]),
("دجاج بالفول السوداني مع أرز القرنبيط","هل تشتهي الطعام الآسيوي ولكنك لا تريد كل هذه الكربوهيدرات؟ جرّب هذه النسخة الأكثر صحة من دجاج الفول السوداني التي تستبدل الأرز الأبيض بأرز القرنبيط المفروم! القرنبيط بديل رائع قليل الكربوهيدرات للأرز، ويضيف حصة إضافية من الخضار المغذية إلى هذا الطبق الكلاسيكي.","4","½ كوب أرز القرنبيط و1 كوب من الدجاج مع صلصة الفول السوداني",
["1 رشة من بخاخ الطهي غير اللاصق","1 رطل صدور دجاج (مقطّعة مكعبات)","½ حبة بصل أصفر متوسطة (مقطّعة مكعبات)","2 فص ثوم (مفروم)","2 ملعقة صغيرة زنجبيل طازج (مبشور)","1 ملعقة صغيرة زيت سمسم محمّص","1 ملعقة صغيرة صلصة الفلفل الحار والثوم على الطريقة التايلاندية","1½ ملعقة صغيرة صلصة الصويا","1 ملعقة كبيرة زبدة الفول السوداني","2 ملعقة كبيرة حليب جوز الهند","2 ملعقة كبيرة حليب اللوز غير المحلى","14½ أونصة طماطم معلّبة مقطّعة مكعبات (مصفّاة)","¼ كوب كزبرة خضراء طازجة (مفرومة)","2 كوب \"أرز\" القرنبيط","1 ملعقة كبيرة فول سوداني (مفروم، اختياري)"],
["رشّ مقلاة كبيرة ببخاخ الطهي وسخّنها على حرارة متوسطة. أضف الدجاج واطهه مع التحريك المتكرر حتى يصبح ذهبي اللون. انقل الدجاج إلى طبق وأعد المقلاة إلى حرارة متوسطة.","أضف زيت السمسم وحرّك معه البصل والثوم والزنجبيل وصلصة الفلفل الحار والثوم. اطهِ مع التحريك من حين لآخر حتى يذبل البصل، لمدة 4-5 دقائق.","أضف صلصة الصويا وزبدة الفول السوداني وحليب جوز الهند وحليب اللوز والطماطم. حرّك حتى تصبح الصلصة كريمية وتتوزع زبدة الفول السوداني بالكامل.","اتركه حتى يغلي على نار هادئة. أعد الدجاج إلى المقلاة وأضف الكزبرة الخضراء المفرومة. خفّض الحرارة إلى منخفضة واتركه على نار هادئة حتى تثخن الصلصة، لمدة 3-4 دقائق.","قدّم الدجاج فوق أرز القرنبيط وزيّنه بالفول السوداني والمزيد من الكزبرة الخضراء، إذا رغبت."],[],[])))
O.append(R(6313311,
("Ensalada de pollo y piña a la parrilla","Esta ensalada de pollo y piña a la parrilla logra el equilibrio perfecto entre sabores dulces, ahumados y ácidos. El pollo magro a la parrilla, las hojas verdes ricas en fibra y la piña naturalmente dulce hacen que el plato sea a la vez saciante y ligero. Es una opción refrescante para las personas con diabetes, ya que aporta proteína y productos frescos sin elevar la glucosa en la sangre (azúcar en la sangre).","4","4 onzas de pollo + 2 tazas de ensalada",
["1 libra de pechuga de pollo deshuesada y sin piel (aproximadamente 2 pechugas medianas)","3 cucharadas de aceite de oliva (divididas)","1/2 cucharadita de pimentón molido","1/4 de cucharadita de sal","1/8 de cucharadita de pimienta negra","1/2 piña fresca entera (cortada en rectángulos largos [de aproximadamente 1/2 pulgada de grosor])","8 tazas de hojas verdes mixtas","1/2 cebolla morada pequeña (en rodajas finas)","2 cucharadas de jugo fresco de limón verde","1 cucharadita de edulcorante de fruta del monje","2 cucharadas de cilantro fresco (picado)"],
["Unte las pechugas de pollo con 1 cucharada de aceite de oliva y sazónelas con el pimentón, la sal y la pimienta negra.","Caliente una parrilla o una plancha acanalada a fuego medio-alto. Ase el pollo de 6 a 7 minutos por lado, o hasta que esté completamente cocido (temperatura interna de 165° F). Retírelo de la parrilla y déjelo reposar durante 5 minutos antes de cortarlo.","Mientras el pollo reposa, ase la piña de 2 a 3 minutos por lado, o hasta que esté caramelizada y con las marcas de la parrilla.","Distribuya las hojas verdes mixtas de manera uniforme en 4 platos o en una fuente grande. Esparza la cebolla morada en rodajas sobre las hojas verdes.","Corte el pollo a la parrilla en tiras delgadas y la piña en trozos pequeños. Divídalos en partes iguales sobre la ensalada.","En un tazón pequeño, bata 2 cucharadas de aceite de oliva, el jugo de limón verde y el edulcorante de fruta del monje. Rocíe el aderezo sobre la ensalada.","Espolvoree el cilantro picado sobre la ensalada y sirva de inmediato."],[],[]),
("سلطة الدجاج والأناناس المشوي","تحقق سلطة الدجاج والأناناس المشوي هذه توازنًا مثاليًا بين النكهات الحلوة والمدخنة والحامضة. يجعل الدجاج المشوي قليل الدهن والخضار الورقية الغنية بالألياف والأناناس الحلو طبيعيًا هذا الطبق مشبعًا وخفيفًا في آن واحد. إنه خيار منعش لمرضى السكري، إذ يوفر البروتين والخضار والفواكه دون رفع مستوى الجلوكوز في الدم (سكر الدم).","4","4 أونصات دجاج + 2 كوب سلطة",
["1 رطل صدور دجاج بدون عظم وبدون جلد (حوالي صدرين متوسطين)","3 ملعقة كبيرة زيت زيتون (مقسّمة)","½ ملعقة صغيرة بابريكا مطحونة","¼ ملعقة صغيرة ملح","⅛ ملعقة صغيرة فلفل أسود","½ حبة أناناس طازجة (مقطّعة إلى مستطيلات طويلة [بسمك حوالي ½ بوصة])","8 أكواب خضار ورقية مشكّلة","½ حبة بصل أحمر صغيرة (مقطّعة شرائح رفيعة)","2 ملعقة كبيرة عصير ليمون أخضر طازج","1 ملعقة صغيرة محلّي فاكهة الراهب","2 ملعقة كبيرة كزبرة خضراء طازجة (مفرومة)"],
["افرك صدور الدجاج بملعقة كبيرة واحدة من زيت الزيتون وتبّلها بالبابريكا والملح والفلفل الأسود.","سخّن شواية أو مقلاة شواء على حرارة متوسطة إلى عالية. اشوِ الدجاج لمدة 6-7 دقائق لكل جانب، أو حتى ينضج تمامًا (درجة الحرارة الداخلية 165° فهرنهايت (75° مئوية)). أخرجه من الشواية واتركه يرتاح لمدة 5 دقائق قبل تقطيعه.","بينما يرتاح الدجاج، اشوِ الأناناس لمدة 2-3 دقائق لكل جانب، أو حتى يتكرمل وتظهر عليه علامات الشواء.","وزّع الخضار الورقية المشكّلة بالتساوي على 4 أطباق أو على طبق تقديم كبير. انثر شرائح البصل الأحمر فوق الخضار.","قطّع الدجاج المشوي إلى شرائح رفيعة وقطّع الأناناس إلى قطع بحجم اللقمة. وزّعها بالتساوي فوق السلطة.","في وعاء صغير، اخفق 2 ملعقة كبيرة من زيت الزيتون مع عصير الليمون الأخضر ومحلّي فاكهة الراهب. اسكب الصلصة فوق السلطة.","رشّ الكزبرة الخضراء المفرومة فوق السلطة وقدّمها فورًا."],[],[])))
O.append(R(6314398,
("Ensalada de brócoli y manzana","Esta receta, apta para los riñones, es una de las favoritas de los niños. Cortar en cubitos, picar y mezclar es todo lo que necesita para preparar la ensalada de brócoli y manzana. Esta receta saludable es baja en sodio y llena de sabor. Precaución: esta receta contiene nueces.","8","3/4 de taza",
["3/4 de taza de yogur griego natural sin grasa","1/4 de taza de mayonesa","1 cucharada de miel","2 cucharadas de vinagre de manzana","4 tazas de brócoli (ramitos frescos)","1 manzana mediana","1/2 taza de cebolla morada (en rodajas)","1/2 taza de arándanos rojos secos (sin azúcar)","1/4 de taza de nueces (picadas)"],
["En un tazón grande, bata el yogur, la mayonesa, la miel, el vinagre y el perejil.","Recorte los ramitos de brócoli y córtelos en trozos pequeños del tamaño de un bocado. Corte las manzanas sin pelar en cubitos pequeños del tamaño de un bocado. Pique el perejil fresco.","Agregue los demás ingredientes y mézclelos bien con la mezcla de yogur. Refrigere para que se enfríe y se mezclen los sabores. Revuelva justo antes de servir."],[],[]),
("سلطة البروكلي والتفاح","هذه الوصفة المناسبة لمرضى الكلى مفضلة لدى الأطفال. قطّع وافرم وحرّك، هذا كل ما تحتاجه لتحضير سلطة البروكلي والتفاح. هذه الوصفة الصحية قليلة الصوديوم وغنية بالنكهة. تنبيه: تحتوي هذه الوصفة على الجوز.","8","¾ كوب",
["¾ كوب زبادي يوناني سادة خالي الدسم","¼ كوب مايونيز","1 ملعقة كبيرة عسل","2 ملعقة كبيرة خل التفاح","4 أكواب بروكلي (زهيرات طازجة)","1 حبة تفاح متوسطة","½ كوب بصل أحمر (مقطّع شرائح)","½ كوب توت بري مجفف (بدون سكر)","¼ كوب جوز (مفروم)"],
["في وعاء كبير، اخفق الزبادي والمايونيز والعسل والخل والبقدونس معًا.","قلّم زهيرات البروكلي وقطّعها إلى قطع صغيرة بحجم اللقمة. قطّع التفاح غير المقشّر إلى مكعبات صغيرة بحجم اللقمة. افرم البقدونس الطازج.","أضف المكونات المتبقية وقلّبها جيدًا مع خليط الزبادي. ضعها في الثلاجة لتبرد وتتمازج النكهات. حرّكها مباشرة قبل التقديم."],[],[])))
O.append(R(6315562,None,
("رقائق الكيل بالتوابل الخمس الصينية","مسحوق التوابل الخمس الصيني هو مزيج من خمس توابل: اليانسون النجمي والقرنفل والقرفة وفلفل سيتشوان والشمر. وهو يمنح الأطباق مذاقًا حلوًا ومالحًا وحامضًا ومرًّا وحادًّا. ليس لديك منه؟ جرّب مسحوق التوابل الثلاث الآسيوي المبسّط: اخلط كميات متساوية من القرنفل المطحون والزنجبيل والقرفة. كلا الخليطين مثالي لطبق رقائق الكيل الجانبي هذا، فهو مصدر غني بالعناصر الغذائية ومليء بالنكهة.","2","3 أكواب",
["⅛ ملعقة صغيرة ملح بحري","1 حزمة كيل (بعد إزالة السيقان والعروق القاسية، ومقطّعة إلى قطع كبيرة بحجم اللقمة (5 قطع مرصوصة))","1 ملعقة كبيرة زيت زيتون بكر ممتاز","¼ ملعقة صغيرة مسحوق التوابل الخمس الصيني"],
["سخّن الفرن مسبقًا إلى 300° فهرنهايت (150° مئوية). ضع الكيل في وعاء كبير وقلّبه جيدًا مع الزيت ومسحوق التوابل الخمس والملح.","رتّب الأوراق في طبقة واحدة على صينيتي خبز كبيرتين. اخبزها حتى تصبح الأوراق مقرمشة، لمدة 20 دقيقة تقريبًا.","انقل الصينيتين إلى رفوف التبريد لتبرد، ثم قدّمها."],[],[])))
O.append(R(6316003,None,
("طاجن قرع السباغيتي","يمكنك تحويل هذا الطبق إلى طبق نباتي بحذف النقانق وإضافة خضار إضافية مثل الفلفل الرومي والبصل والهليون.","9","قطعة بحجم 3×3 بوصات تقريبًا",
["1 بخّة (0.25 غرام) من بخاخ الطهي غير اللاصق","5 رطل قرع سباغيتي","1 ملعقة كبيرة زيت زيتون","2 قطعة نقانق دجاج بالطريقة الإيطالية (حوالي 3 أونصات لكل قطعة، مقطّعة مكعبات)","1 فص ثوم (مفروم)","8 أونصات فطر أبيض (فطر الأزرار) (مقطّع شرائح)","2 ملعقة كبيرة دقيق","2 كوب حليب خالي الدسم","½ كوب جبن موزاريلا (قليل الدسم، مبشور، مقسّم)","1 ملعقة صغيرة ملح (اختياري)","¼ ملعقة صغيرة فلفل أسود","¼ كوب ريحان طازج (مفروم)","¼ كوب جبن بارميزان (مبشور)"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية). ادهن صينية خبز ببخاخ الطهي.","املأ صينية الخبز بالماء بارتفاع 1 بوصة. اقطع القرع إلى نصفين بالطول. ضع القرع على الصينية وجانب القطع إلى الأسفل واشوِه لمدة ساعة واحدة.","أخرج لب القرع المشوي من القشرة. تخلّص من القشرة ومن أي بذور وضع اللب في وعاء كبير. اتركه جانبًا.","ادهن صينية خبز أخرى (9×9) ببخاخ الطهي. اتركها جانبًا.","بينما يُشوى القرع، ضع زيت الزيتون في قدر متوسط على حرارة متوسطة إلى عالية. قلِّ نقانق الدجاج حتى تبدأ بالاحمرار.","أضف الثوم والفطر وقلّبها حتى يلين الفطر ويتبخر كل السائل.","رشّ الدقيق على خليط الفطر والنقانق واطهه لمدة 2-3 دقائق مع التحريك المستمر.","أضف الحليب واخفق بقوة مع كشط القطع العالقة من قاع القدر. اتركه حتى يغلي.","خفّض الحرارة إلى هادئة واتركه على نار هادئة لمدة 3-4 دقائق. أضف ¼ كوب من جبن الموزاريلا وحرّك حتى يذوب. أضف الملح والفلفل والريحان وحرّك.","اسكب الصلصة فوق قرع السباغيتي المطهو وقلّب حتى يتجانس الخليط.","اسكب الخليط في الصينية المجهزة، وغطِّ وجهه بما تبقى من جبن الموزاريلا وجبن البارميزان. اخبزه لمدة 45 دقيقة أو حتى يصبح الجبن ذهبي اللون ويصبح الطاجن فقاعيًا ومحمرًّا عند الأطراف.","قطّعه إلى 9 مربعات متساوية."],[],[])))
dump(O,"/mnt/c/WSL/davita/translations/out_c9_part1.json")
