from lib import build
R = []
FVH = "@FV"
# 7523019
R.append((7523019,
("Filetes de cordero estofados al estilo italiano", "Un plato aromático con hierbas y rico en tomate, que realza todo el sabor del cordero.", "4", "301 g",
 ["2 cucharaditas de aceite de colza", "4 cebollas moradas, cortadas en cuartos", "4 filetes de cordero (aprox. 500 g), sin grasa", "1 cucharada de harina", "4 dientes de ajo, en rodajas", "1 ramita grande de romero, desmenuzada, y un poco más para servir, o 1 cucharadita rasa de romero seco", "1 cucharadita colmada de orégano", "1 cubito de caldo de cordero disuelto en 500 ml de agua", "1 lata de 400 g de tomates picados", "1 cucharada de vinagre balsámico", "1 buena pizca de pimienta"],
 ["Precaliente el horno a 180 °C (gas 4). Agregue 1 cucharadita del aceite a una sartén a fuego bajo-medio, añada las cebollas y dórelas suavemente durante 3-4 minutos, volteándolas con frecuencia. Reserve.", "Cubra el cordero con la harina y agregue el aceite restante a la sartén. Cocine de 2 a 3 minutos por cada lado.", "Regrese las cebollas a la sartén y añada el ajo, el romero y el orégano. Incorpore el caldo y deje que hierva suavemente.", "Agregue los tomates, el vinagre balsámico y la pimienta.", "Coloque todo en una fuente apta para horno y cocine de 45 a 50 minutos. Decore con un poco de romero fresco y sirva."],
 ["Si lo prefiere, puede cocinar todo el plato en la estufa: simplemente cocine a fuego lento de 45 a 50 minutos. Tenga cuidado de que no se seque por completo; agregue un poco de agua si es necesario.", "Queda muy bien con muslos de pollo sin piel.", "Instrucciones para congelar: se puede congelar una vez cocido. Descongele en el refrigerador o en el microondas y recaliente hasta que esté muy caliente por completo.", FVH], []),
("شرائح لحم الضأن المطهوة ببطء على الطريقة الإيطالية", "طبق غني بالأعشاب والطماطم يُبرز النكهة الكاملة للحم الضأن.", "4", "301 غ",
 ["2 ملعقة صغيرة من زيت اللفت", "4 حبات بصل أحمر، مقطعة إلى أرباع", "4 شرائح من لحم الضأن (حوالي 500 غ)، منزوعة الدهن", "1 ملعقة كبيرة من الدقيق", "4 فصوص ثوم، مقطعة إلى شرائح", "غصن كبير من إكليل الجبل، ممزق إلى قطع، وقليل منه للتقديم، أو 1 ملعقة صغيرة مستوية من إكليل الجبل المجفف", "1 ملعقة صغيرة مكدسة من الأوريجانو", "1 مكعب مرق لحم ضأن مذاب في 500 مل من الماء", "1 علبة (400 غ) من الطماطم المقطعة", "1 ملعقة كبيرة من الخل البلسمي", "رشة كبيرة من الفلفل"],
 ["سخّن الفرن مسبقًا على 180° مئوية (درجة الغاز 4). ضع 1 ملعقة صغيرة من الزيت في مقلاة على نار هادئة إلى متوسطة، وأضف البصل وحمّره بلطف لمدة 3-4 دقائق مع تقليبه باستمرار. ضعه جانبًا.", "غطِّ لحم الضأن بالدقيق، وأضف الزيت المتبقي إلى المقلاة. اطهه لمدة 2-3 دقائق على كل جانب.", "أعد البصل إلى المقلاة، وأضف الثوم وإكليل الجبل والأوريجانو. أضف المرق مع التحريك واتركه يغلي بهدوء.", "أضف الطماطم والخل البلسمي والفلفل.", "ضع الخليط في طبق مقاوم للحرارة واطهه لمدة 45-50 دقيقة. زيّنه بقليل من إكليل الجبل الطازج وقدّمه."],
 ["يمكنك طهي الطبق بالكامل على الموقد إن أردت، فقط دعه يغلي على نار هادئة لمدة 45-50 دقيقة. احرص على ألا يجف تمامًا، وأضف قليلًا من الماء عند الحاجة.", "يناسب هذا الطبق أيضًا أفخاذ الدجاج منزوعة الجلد.", "تعليمات التجميد: يمكن تجميده بعد الطهي. اتركه يذوب في الثلاجة أو في الميكروويف، ثم أعد تسخينه حتى يصبح ساخنًا جدًا في كل جزء منه.", FVH], [])))
# 7523365
R.append((7523365,
("Ensalada vibrante de sandía, tomate y piñones", "Un complemento delicioso y vistoso para su mesa; esta ensalada de sandía con sabor vibrante es el plato perfecto para el verano.", "4", "252 g",
 ["7 tomates cherry, partidos por la mitad", "1 cucharada de vinagre balsámico", "½ lima, solo el jugo", "2 cucharadas de menta picada", "6 hojas grandes de albahaca, desgarradas en trozos grandes", "500 g de sandía sin semillas, sin cáscara y cortada en 24 trozos del tamaño de un bocado: peso comestible 380 g", "½ caja de fresas, unas 7, sin el cáliz y cortadas en cuartos", "½ pepino, recortado", "100 g de edamame (frijoles de soya), descongelado", "20 g de piñones tostados"],
 ["Mezcle los tomates, el vinagre balsámico, el jugo de lima, la menta y la albahaca, y vierta todo en un plato para servir. Esparza por encima la sandía y las fresas.", "Con un pelador de verduras, saque tiras largas de pepino y colóquelas sobre la ensalada. Esparza por encima el edamame y los piñones tostados, y sirva."],
 [FVH], []),
("سلطة البطيخ والطماطم والصنوبر المنعشة", "إضافة لذيذة وجذابة لمائدتك، وهذه سلطة البطيخ المنعشة هي الطبق المثالي للصيف.", "4", "252 غ",
 ["7 حبات طماطم كرزية، مقطعة إلى نصفين", "1 ملعقة كبيرة من الخل البلسمي", "½ حبة ليمون أخضر، العصير فقط", "2 ملعقة كبيرة من النعناع المفروم", "6 أوراق ريحان كبيرة، ممزقة تمزيقًا خشنًا", "500 غ من البطيخ الخالي من البذور، منزوع القشرة ومقطع إلى 24 قطعة بحجم اللقمة: الوزن الصالح للأكل 380 غ", "½ علبة فراولة، حوالي 7 حبات، منزوعة الأعناق ومقطعة إلى أرباع", "½ حبة خيار، مقشرة الأطراف", "100 غ من فول الإدامامي، مذاب من التجميد", "20 غ من الصنوبر المحمص"],
 ["اخلط الطماطم والخل البلسمي وعصير الليمون الأخضر والنعناع والريحان معًا، وانقلها إلى طبق التقديم. وزّع البطيخ والفراولة فوقها.", "باستخدام مقشرة الخضار، اصنع شرائح طويلة من الخيار ورتّبها فوق السلطة. وزّع فوقها فول الإدامامي والصنوبر المحمص وقدّمها."],
 [FVH], [])))
# 7524534
R.append((7524534,
("Paté de champiñones", "Este paté fácil y bajo en grasa es el entrante vegetariano perfecto.", "4", "81 g",
 ["1 cucharada de aceite de oliva", "50 g de chalotas, finamente picadas", "125 g de champiñones shiitake, en rodajas finas", "75 g de champiñones castaña, en rodajas finas", "1 diente de ajo, machacado", "1 buena pizca de pimienta blanca", "1 cucharadita de salsa de soya reducida en sal", "1 cucharada de perejil fresco, finamente picado", "50 g de queso crema untable semidescremado"],
 ["Agregue el aceite a una sartén a fuego medio, luego añada las chalotas y revuelva con frecuencia durante 5 minutos, hasta que se doren.", "Agregue todos los champiñones y suba un poco el fuego. Cocine de 3 a 4 minutos, hasta que los champiñones estén blandos y se haya evaporado el líquido que sueltan.", "Agregue el ajo y la pimienta, cocine un minuto más, luego añada la salsa de soya y el perejil, mezcle, retire del fuego y deje enfriar.", "Coloque los champiñones en una tabla de cortar y píquelos finamente; luego páselos a un tazón con el queso crema, mezcle y refrigere. Sirva con pan tostado."],
 ["Este paté también rinde de 15 a 20 canapés excelentes. Para canapés sin trigo, pruebe usar papitas al horno: corte las papas cocidas por la mitad, saque un poco de la pulpa y rellene el centro con el paté.", "Para un paté sin gluten, use tamari sin gluten y reducido en sal en lugar de la salsa de soya en esta receta.", "Instrucciones para congelar: descongele en el refrigerador antes de servir.", FVH], []),
("باتيه الفطر", "هذا الباتيه السهل قليل الدسم هو المقبلات النباتية المثالية.", "4", "81 غ",
 ["1 ملعقة كبيرة من زيت الزيتون", "50 غ من الإشالوت (البصل الفرنسي)، مفروم ناعمًا", "125 غ من فطر الشيتاكي، مقطع إلى شرائح رقيقة", "75 غ من فطر الكستناء، مقطع إلى شرائح رقيقة", "1 فص ثوم، مهروس", "رشة كبيرة من الفلفل الأبيض", "1 ملعقة صغيرة من صلصة الصويا قليلة الملح", "1 ملعقة كبيرة من البقدونس الطازج، مفروم ناعمًا", "50 غ من الجبن الكريمي نصف الدسم"],
 ["ضع الزيت في مقلاة على نار متوسطة، ثم أضف الإشالوت وقلّبه باستمرار لمدة 5 دقائق حتى يحمرّ.", "أضف كل أنواع الفطر وارفع النار قليلًا. اطهه لمدة 3-4 دقائق حتى يصبح الفطر طريًا ويتبخر أي سائل خرج منه.", "أضف الثوم والفلفل، واطهه دقيقة أخرى، ثم أضف صلصة الصويا والبقدونس وقلّب، ثم ارفعه عن النار واتركه يبرد.", "ضع الفطر على لوح التقطيع وافرمه ناعمًا، ثم انقله إلى وعاء مع الجبن الكريمي وقلّب ثم ضعه في الثلاجة. قدّمه مع الخبز المحمص."],
 ["يكفي هذا الباتيه أيضًا لتحضير 15-20 قطعة كانابيه رائعة. للحصول على كانابيه خالٍ من القمح، جرّب استخدام حبات البطاطس الصغيرة المخبوزة: اقطع البطاطس المطبوخة إلى نصفين، وأخرج قليلًا من لبّها، ثم املأ الوسط بالباتيه.", "للحصول على باتيه خالٍ من الغلوتين، استخدم صلصة التاماري الخالية من الغلوتين وقليلة الملح بدلًا من صلصة الصويا في هذه الوصفة.", "تعليمات التجميد: اتركه يذوب في الثلاجة قبل التقديم.", FVH], [])))
# 7525579
R.append((7525579,
("Huevos para el desayuno con aguacate y frijoles negros", "Una versión sencilla pero deliciosa de aguacate con huevos, con un toque de chile.", "2", "322 g",
 ["1 aguacate grande", "2 huevos pequeños", "1 cucharadita de aceite de colza", "½ chile rojo, sin semillas y en rodajas finas", "200 g de frijoles negros enlatados en agua", "8 tomates cherry, picados en trozos grandes", "½ cucharadita de pasta de chipotle", "2 cebollas verdes, en rodajas finas"],
 ["Precaliente el horno a 200 °C (gas 6). Parta el aguacate por la mitad, quite el hueso y saque 1 cucharada de pulpa de cada mitad (resérvela para otra receta). Coloque cada mitad en un molde individual (ramequín) para que quede derecha. Casque un huevo en cada una y hornee de 12 a 15 minutos, hasta que la yema esté cuajada.", "Caliente el aceite en una sartén pequeña antiadherente. Agregue el chile y cocine hasta que se ablande. Añada los frijoles con el líquido de la lata, los tomates y la pasta de chipotle. Cocine a fuego lento durante 5 minutos, hasta que todo esté caliente y los tomates empiecen a ablandarse.", "Arme el plato y esparza por encima las cebollas verdes."],
 ["Si sus huevos son un poco grandes, separe las yemas, coloque una yema en cada aguacate, bata las claras con un tenedor para romperlas y úselas para llenar el hueco de cada aguacate.", "Los grupos de riesgo, como los bebés, los niños, las mujeres embarazadas, los adultos mayores y las personas enfermas, deben evitar los huevos crudos o poco cocidos, a menos que tengan la garantía de que fueron producidos bajo el programa de garantía de calidad Lion Code.", FVH], []),
("بيض الإفطار مع الأفوكادو والفاصوليا السوداء", "طريقة بسيطة ولذيذة لتحضير الأفوكادو مع البيض، مع لمسة من الفلفل الحار.", "2", "322 غ",
 ["1 حبة أفوكادو كبيرة", "2 بيضة صغيرة", "1 ملعقة صغيرة من زيت اللفت", "½ حبة فلفل أحمر حار، منزوعة البذور ومقطعة إلى شرائح رفيعة", "200 غ من الفاصوليا السوداء المعلبة في الماء", "8 حبات طماطم كرزية، مقطعة تقطيعًا خشنًا", "½ ملعقة صغيرة من معجون التشيبوتلي", "2 حبة بصل أخضر، مقطعة إلى شرائح رفيعة"],
 ["سخّن الفرن مسبقًا على 200° مئوية (درجة الغاز 6). اقطع الأفوكادو إلى نصفين، وانزع النواة، وأخرج ملعقة كبيرة واحدة من اللب من كل نصف (احتفظ بها لوصفة أخرى). ضع كل نصف في قالب صغير (رامكن) ليبقى قائمًا. اكسر بيضة في كل نصف واخبزه لمدة 12-15 دقيقة حتى يتماسك الصفار.", "سخّن الزيت في مقلاة صغيرة غير لاصقة. أضف الفلفل الحار واطهه حتى يلين. أضف الفاصوليا مع سائل العلبة، والطماطم، ومعجون التشيبوتلي. اطهه على نار هادئة لمدة 5 دقائق حتى يسخن الخليط وتبدأ الطماطم في الليونة.", "رتّب الطبق في صحن ووزّع البصل الأخضر فوقه."],
 ["إذا كانت البيضات كبيرة بعض الشيء، فافصل الصفار، وضع صفارًا واحدًا في كل نصف أفوكادو، واخفق البياض بالشوكة لتكسيره، واستخدمه لملء التجويف في كل نصف.", "ينبغي للفئات المعرّضة للخطر، مثل الرضّع والأطفال والحوامل وكبار السن والمرضى، تجنّب البيض النيئ أو غير المطهو جيدًا (ذي القلب الطري)، ما لم يكن هناك ما يضمن إنتاجه وفق نظام ضمان الجودة «Lion Code».", FVH], [])))
# 7532555
R.append((7532555,
("Barras de frutas y nueces", "Estas barras masticables son una merienda ideal.", "16", "58 g",
 ["450 g de manzanas para comer, peladas, sin corazón y cocidas en compota (425 g)", "5 cucharadas de jugo de naranja", "225 g de frutas secas variadas (por ejemplo, albaricoques, dátiles, arándanos rojos), picadas en trozos grandes", "100 g de nueces variadas (por ejemplo, almendras, avellanas), picadas", "75 g de harina integral con levadura", "25 g de coco rallado seco", "1 cucharada de aceite de colza"],
 ["Precaliente el horno a 180 ºC (gas 4), engrase ligeramente un molde cuadrado de 20 cm y fórrelo con papel.", "Coloque todos los ingredientes en un tazón y mezcle.", "Vierta la mezcla con una cuchara en el molde.", "Alise la superficie y presione ligeramente; luego hornee de 35 a 40 minutos, hasta que esté dorado y firme.", "Marque 16 porciones. Deje enfriar en el molde. Sirva cuando se haya enfriado un poco."],
 ["Para cocer las manzanas: pélelas, quíteles el corazón y píquelas; luego póngalas en una olla con 2 cucharadas de agua. Tape y cocine a fuego lento, revolviendo con frecuencia, de 10 a 15 minutos.", "Las manzanas cocidas se congelan bien, así que puede preparar una tanda y congelarla hasta que la necesite.", "Instrucciones para congelar: descongele durante 2 horas antes de servir, o descongele en el microondas o en un horno a temperatura moderada.", FVH], []),
("ألواح الفاكهة والمكسرات", "هذه الألواح اللذيذة القابلة للمضغ وجبة خفيفة مثالية.", "16", "58 غ",
 ["450 غ من التفاح الصالح للأكل، مقشر ومنزوع القلب ومسلوق حتى يلين (425 غ)", "5 ملاعق كبيرة من عصير البرتقال", "225 غ من الفاكهة المجففة المشكلة (مثل المشمش والتمر والتوت البري)، مقطعة تقطيعًا خشنًا", "100 غ من المكسرات المشكلة (مثل اللوز والبندق)، مفرومة", "75 غ من دقيق القمح الكامل الذاتي الانتفاخ", "25 غ من جوز الهند المجفف المبشور", "1 ملعقة كبيرة من زيت اللفت"],
 ["سخّن الفرن مسبقًا على 180° مئوية (درجة الغاز 4)، ثم ادهن قالب خَبز مربعًا بطول 20 سم دهنًا خفيفًا وبطّنه بالورق.", "ضع جميع المكونات في وعاء واخلطها معًا.", "اسكب الخليط بالملعقة في القالب.", "سوِّ السطح واضغط عليه قليلًا، ثم اخبزه لمدة 35-40 دقيقة حتى يصبح ذهبي اللون ومتماسكًا.", "قسّمه بعلامات إلى 16 قطعة. اتركه في القالب ليبرد. قدّمه عندما يبرد قليلًا."],
 ["لسلق التفاح: قشّره وانزع قلبه وقطّعه، ثم ضعه في قدر مع 2 ملعقة كبيرة من الماء. غطِّه واطهه على نار هادئة مع التحريك باستمرار لمدة 10-15 دقيقة.", "يمكن تجميد التفاح المسلوق بشكل جيد، لذا يمكنك تحضير كمية وتجميدها حتى تحتاج إليها.", "تعليمات التجميد: اتركه يذوب لمدة ساعتين قبل التقديم، أو أذبه في الميكروويف أو في فرن على حرارة معتدلة.", FVH], [])))
# 7533762
R.append((7533762,
("Pollo tandoori con verduras", "Todo va al horno al mismo tiempo, lo que hace de este un plato muy sencillo y sabroso.", "2", "594 g",
 ["300 g de pechuga de pollo sin piel", "1 cucharada de yogur natural bajo en grasa", "1 cucharadita de pimentón", "1 cucharadita de comino molido", "1 cucharadita de cúrcuma", "4 tomates, partidos por la mitad", "1 cucharadita de garam masala", "1 cucharadita de aceite de colza", "2 cebollas moradas grandes, cortadas en cuartos", "1 pimiento rojo, cortado en 8 trozos"],
 ["Precaliente el horno a 200 °C (gas 6). Corte el pollo en cubos y póngalo en un tazón con el yogur, el pimentón, el comino y la cúrcuma; mezcle bien para cubrir el pollo.", "Espolvoree los tomates con el garam masala.", "Engrase ligeramente una bandeja para hornear y distribuya uniformemente la cebolla y el pimiento; luego coloque los trozos de pollo sobre la cebolla y el pimiento, y ponga los tomates encima.", "Ase durante 15 minutos, o hasta que el pollo esté bien cocido, y sirva con arroz basmati o ensalada."],
 ["Use pasta de curry si no tiene todas las especias, o agregue jengibre fresco rallado y ajo machacado para darle más sabor.", "Puede mezclar el pollo, las especias y el yogur en una bolsa para alimentos y guardarlo en el refrigerador unas horas antes de empezar a cocinar, lo que ayuda a que los sabores se integren.", "Los platos picantes normalmente no necesitan sal adicional, lo que significa que son mejores para su corazón.", "El pollo sin piel es rico en proteínas y tiene casi la mitad de la grasa y de la grasa saturada que el pollo con piel.", "Instrucciones para congelar: se puede congelar una vez cocido. Descongele en el refrigerador o en el microondas y recaliente bien hasta que esté muy caliente por completo.", FVH], []),
("دجاج التندوري مع الخضار", "يدخل كل شيء إلى الفرن في الوقت نفسه، مما يجعل هذا الطبق بسيطًا ولذيذًا جدًا.", "2", "594 غ",
 ["300 غ من صدور الدجاج منزوعة الجلد", "1 ملعقة كبيرة من الزبادي الطبيعي قليل الدسم", "1 ملعقة صغيرة من البابريكا", "1 ملعقة صغيرة من الكمون المطحون", "1 ملعقة صغيرة من الكركم", "4 حبات طماطم، مقطعة إلى نصفين", "1 ملعقة صغيرة من الجارام ماسالا", "1 ملعقة صغيرة من زيت اللفت", "2 حبة بصل أحمر كبيرة، مقطعة إلى أرباع", "1 حبة فلفل رومي أحمر، مقطعة إلى 8 قطع"],
 ["سخّن الفرن مسبقًا على 200° مئوية (درجة الغاز 6). قطّع الدجاج إلى مكعبات وضعه في وعاء مع الزبادي والبابريكا والكمون والكركم، ثم اخلط جيدًا ليتغطى الدجاج.", "رشّ الطماطم بالجارام ماسالا.", "ادهن صينية الخَبز بقليل من الزيت ووزّع البصل والفلفل الرومي عليها بالتساوي، ثم ضع قطع الدجاج فوق البصل والفلفل، ورتّب الطماطم فوقها.", "اشوِ لمدة 15 دقيقة، أو حتى ينضج الدجاج تمامًا، وقدّمه مع أرز البسمتي أو السلطة."],
 ["استخدم معجون الكاري إن لم تكن لديك كل التوابل، أو أضف زنجبيلًا طازجًا مبشورًا وثومًا مهروسًا لمزيد من النكهة.", "يمكنك خلط الدجاج والتوابل والزبادي في كيس طعام وحفظها في الثلاجة لبضع ساعات قبل البدء بالطهي، مما يساعد على تشرّب النكهات.", "لا تحتاج الأطباق الحارة عادةً إلى إضافة الملح، مما يعني أنها أفضل لقلبك.", "الدجاج منزوع الجلد غني بالبروتين ويحتوي على نصف كمية الدهون والدهون المشبعة تقريبًا مقارنة بالدجاج بالجلد.", "تعليمات التجميد: يمكن تجميده بعد الطهي. اتركه يذوب في الثلاجة أو في الميكروويف، ثم أعد تسخينه جيدًا حتى يصبح ساخنًا جدًا في كل جزء منه.", FVH], [])))
# 7534224
R.append((7534224,
("Curry jamaiquino de mariscos", "Este plato de cocción lenta reúne algunos de los ingredientes más queridos de Jamaica para lograr un plato dulce, picante y sensacional. Esta receta fue seleccionada en colaboración con Slimming World.", "4", "447 g",
 ["1 cebolla grande, finamente picada", "2 dientes de ajo, machacados", "1 trozo de 5 cm de raíz de jengibre fresco, pelado y rallado", "1 chile verde medianamente picante, sin semillas y finamente picado", "1 cucharada de curry en polvo (el picante a su gusto)", "½ cucharadita de cada uno: canela molida, hojuelas de chile seco y cúrcuma molida", "¼ de cucharadita de clavo molido o pimienta de Jamaica", "2 cucharaditas de semillas de nigela", "1 cucharadita rasa de edulcorante granulado (opcional)", "200 g de tomates picados", "200 ml de leche de coco reducida en grasa", "175 g de okra, cada una cortada en 3-4 trozos en diagonal", "100 g de espinaca baby, y unas hojas más para servir", "200 g de tomates cherry, partidos por la mitad", "200 g de camarones crudos pelados", "400 g de filetes firmes de pescado blanco, sin piel ni espinas, cortados en trozos grandes", "1 cucharada de jugo de lima"],
 ["Ponga la cebolla, el ajo, el jengibre, el chile, el curry en polvo y las especias, el edulcorante, los tomates picados, la leche de coco y un poco de pimienta en la olla de cocción lenta. Mezcle bien, tape y cocine a temperatura alta durante 1 hora.", "Agregue la okra, tape de nuevo y cocine 2 horas más.", "Incorpore la espinaca, los tomates cherry y los camarones. Sazone ligeramente los trozos de pescado con pimienta y colóquelos encima del curry. Tape de nuevo y cocine 1 hora más, hasta que los camarones y el pescado cambien de color y estén bien cocidos.", "Incorpore el jugo de lima y esparza por encima las hojas de espinaca restantes para servir."],
 ["Si no tiene una olla de cocción lenta, ponga todos los ingredientes hasta la leche de coco en una olla grande antiadherente o en una cacerola, tape y cocine a fuego lento durante 30 minutos. Agregue la okra, tape y cocine a fuego lento 30 minutos más. Incorpore la espinaca, los tomates cherry y los camarones, y luego coloque el pescado encima. Tape y cocine a fuego lento durante 5 minutos o hasta que los camarones y el pescado estén bien cocidos.", "Tenga cuidado con las mezclas de especias o condimentos que tienen azúcar, sal, harina o aceite añadidos. Elija mezclas de especias hechas solo con hierbas y especias.", FVH], []),
("كاري المأكولات البحرية الجامايكي", "يجمع هذا الطبق المطهو ببطء بعضًا من أحب المكونات الجامايكية للحصول على طبق حلو وحار ورائع! تم اختيار هذه الوصفة بالشراكة مع Slimming World.", "4", "447 غ",
 ["1 حبة بصل كبيرة، مفرومة ناعمًا", "2 فص ثوم، مهروس", "قطعة من جذر الزنجبيل الطازج بطول 5 سم، مقشرة ومبشورة", "1 حبة فلفل أخضر حار متوسط الحرارة، منزوعة البذور ومفرومة ناعمًا", "1 ملعقة كبيرة من مسحوق الكاري (حسب درجة الحرارة التي تفضلها)", "½ ملعقة صغيرة من كل من القرفة المطحونة ورقائق الفلفل الحار المجفف والكركم المطحون", "¼ ملعقة صغيرة من القرنفل المطحون أو البهار الجامايكي", "2 ملعقة صغيرة من حبة البركة", "1 ملعقة صغيرة مستوية من المُحلّي الحبيبي (اختياري)", "200 غ من الطماطم المقطعة", "200 مل من حليب جوز الهند قليل الدسم", "175 غ من البامية، كل حبة مقطعة قطريًا إلى 3-4 قطع", "100 غ من السبانخ الصغيرة، وبعض الأوراق الإضافية للتقديم", "200 غ من الطماطم الكرزية، مقطعة إلى نصفين", "200 غ من الروبيان النيئ المقشر", "400 غ من فيليه السمك الأبيض المتماسك، منزوع الجلد والعظم، مقطع إلى قطع كبيرة", "1 ملعقة كبيرة من عصير الليمون الأخضر"],
 ["ضع البصل والثوم والزنجبيل والفلفل الحار ومسحوق الكاري والتوابل والمُحلّي والطماطم المقطعة وحليب جوز الهند وقليلًا من الفلفل للتتبيل في قدر الطهي البطيء. قلّب جيدًا، وغطِّ القدر، واطهه على الدرجة العالية لمدة ساعة واحدة.", "أضف البامية، وغطِّ القدر مرة أخرى، واطهه ساعتين إضافيتين.", "أضف السبانخ والطماطم الكرزية والروبيان مع التحريك. تبّل قطع السمك قليلًا بالفلفل وضعها فوق الكاري. غطِّ القدر مرة أخرى واطهه ساعة إضافية حتى يتغير لون الروبيان والسمك وينضجا تمامًا.", "أضف عصير الليمون الأخضر مع التحريك، ثم وزّع أوراق السبانخ الإضافية فوقه وقدّمه."],
 ["إذا لم يكن لديك قدر للطهي البطيء، فضع جميع المكونات حتى حليب جوز الهند في قدر كبير غير لاصق أو في وعاء طهي، وغطِّه واتركه يغلي على نار هادئة لمدة 30 دقيقة. أضف البامية، وغطِّه واتركه يغلي على نار هادئة 30 دقيقة أخرى. أضف السبانخ والطماطم الكرزية والروبيان مع التحريك، ثم ضع السمك فوقها. غطِّه واتركه يغلي على نار هادئة لمدة 5 دقائق أو حتى ينضج الروبيان والسمك تمامًا.", "انتبه إلى خلطات التوابل/التتبيلات التي تحتوي على سكر أو ملح أو دقيق أو زيت مضاف. اختر خلطات التوابل المصنوعة من الأعشاب والتوابل فقط.", FVH], [])))
# 7534283
R.append((7534283,
("Kebabs de doner", "Olvídese de la comida para llevar y prepare su propia versión más saludable.", "4", "349 g",
 ["1 cucharadita colmada de orégano", "1 cucharadita de canela molida", "½ cucharadita de comino molido", "½ cucharadita de hojuelas de chile", "1 buena pizca de pimienta blanca", "2 dientes de ajo, machacados", "ralladura y jugo de ½ limón", "1 huevo, ligeramente batido", "½ rebanada de pan integral, desmenuzada", "250 g de carne molida de cordero con 10 % de grasa", "4 panes pita integrales (70 g cada uno)", "4 porciones grandes de ensalada (pepino, 100 g de lechuga iceberg, 300 g de tomates y 150 g de cebolla morada)", "jugo de ½ limón, para servir"],
 ["Ponga el orégano, la canela, el comino, el chile, la pimienta, el ajo, la ralladura y el jugo de limón en un tazón, junto con el huevo y el pan desmenuzado. Mezcle bien con un tenedor, deshaciendo aún más el pan.", "Incorpore el cordero y déjelo reposar 10 minutos. Mezcle de nuevo y déle forma de rollo de unos 6 cm de diámetro y 13.5 cm de largo.", "Colóquelo en una bandeja para hornear y cocínelo en el horno precalentado a 190 °C (gas 5) de 25 a 30 minutos.", "Deje enfriar 5 minutos, luego córtelo en rebanadas finas y rellene los panes pita con abundante ensalada. Rocíe con jugo de limón y sirva."],
 ["Puede usar la ensalada que más le guste. Para darle un toque crujiente, use repollo crudo, lechuga, cebolla morada y pepino en tiras finas, mezclados con jugo de limón.", "Para las salsas (en la foto): Salsa de tahini: ponga 2 cucharaditas de tahini en un plato y mezcle poco a poco 3 cucharadas de yogur bajo en grasa y una pizca de pimienta blanca. Salsa de tomate: mezcle un tomate grande finamente picado con 1 cucharada de salsa de tomate (kétchup) y un chorrito de salsa de chile.", FVH], []),
("كباب الدونر", "انسَ الوجبات الجاهزة، وحضّر نسختك الصحية الخاصة.", "4", "349 غ",
 ["1 ملعقة صغيرة مكدسة من الأوريجانو", "1 ملعقة صغيرة من القرفة المطحونة", "نصف ملعقة صغيرة من الكمون المطحون", "نصف ملعقة صغيرة من رقائق الفلفل الحار", "رشة كبيرة من الفلفل الأبيض", "2 فص ثوم، مهروس", "برش قشر وعصير نصف ليمونة", "1 بيضة، مخفوقة قليلًا", "نصف شريحة من خبز القمح الكامل، مفتتة", "250 غ من لحم الضأن المفروم بنسبة دهون 10%", "4 أرغفة خبز بيتا من القمح الكامل (70 غ لكل رغيف)", "4 حصص كبيرة من السلطة (خيار، و100 غ من خس آيسبرغ، و300 غ من الطماطم، و150 غ من البصل الأحمر)", "عصير نصف ليمونة، للتقديم"],
 ["ضع الأوريجانو والقرفة والكمون والفلفل الحار والفلفل الأبيض والثوم وبشر قشر الليمون وعصيره في وعاء، مع البيضة والخبز المفتت. اخلط جيدًا بالشوكة مع تفتيت الخبز أكثر.", "أضف لحم الضأن واخلطه، ثم اتركه جانبًا لمدة 10 دقائق. اخلطه مرة أخرى وشكّله على هيئة رغيف قطره حوالي 6 سم وطوله 13.5 سم.", "ضعه على صينية خَبز واطهه في فرن مسخّن مسبقًا على 190° مئوية (درجة الغاز 5) لمدة 25-30 دقيقة.", "اتركه يبرد لمدة 5 دقائق، ثم قطّعه إلى شرائح رفيعة واحشه في أرغفة البيتا مع كمية وافرة من السلطة. رشّ عليه عصير الليمون وقدّمه."],
 ["يمكنك استخدام أي سلطة تحبها. لإضافة قوام مقرمش رائع، استخدم الملفوف النيئ المقطع شرائح رفيعة والخس والبصل الأحمر والخيار، مخلوطة بعصير الليمون.", "بالنسبة للصلصات (كما في الصورة): صلصة الطحينة: ضع 2 ملعقة صغيرة من الطحينة في طبق، ثم اخلط معها تدريجيًا 3 ملاعق كبيرة من الزبادي قليل الدسم ورشة من الفلفل الأبيض. صلصة الطماطم: اخلط حبة طماطم كبيرة مفرومة ناعمًا مع 1 ملعقة كبيرة من الكاتشب وقليل من صلصة الفلفل الحار.", FVH], [])))
# 7534585
R.append((7534585,
("Escalope de pollo con salsa de ajo y perejil", "Dele más sabor al pollo sencillo con esta salsa fácil y deliciosa que está lista en minutos.", "2", "153 g",
 ["1 pechuga de pollo grande, sin piel y sin hueso (aprox. 220 g)", "2 cucharaditas de aceite de colza", "4 dientes de ajo, machacados", "1 cebolla verde, finamente picada", "25 g de perejil fresco, finamente picado", "1 buena pizca de pimienta", "jugo de ½ limón", "1 cucharada de yogur griego sin grasa (0 %)"],
 ["Coloque la pechuga de pollo entre dos trozos de plástico adherente y golpéela con un mazo o rodillo hasta formar un escalope plano de aprox. 4-5 mm de grosor. Luego divídalo en 2 porciones iguales.", "Unte los trozos de pechuga con 1 cucharadita del aceite. Colóquelos en una sartén o plancha caliente y cocine de 2 a 3 minutos por cada lado.", "Mientras tanto, en una sartén pequeña caliente la cucharadita de aceite restante, agregue el ajo y las cebollas verdes y cocine durante 2 minutos, hasta que las cebollas estén blandas. Luego añada el perejil y revuelva durante 1 minuto.", "Agregue la pimienta, el jugo de limón y 1 cucharada de agua. Incorpore el yogur.", "Ponga el pollo en un plato y sirva con la salsa."],
 ["Esto queda muy bien con escalopes de pavo, de res o de cerdo. También puede probar la salsa con pescado a la parrilla.", "Al \"golpear\" la carne se ablanda y el filete se cocina mucho más rápido, por lo que es ideal para las barbacoas.", FVH], []),
("إسكالوب الدجاج مع صلصة الثوم والبقدونس", "أضف نكهة مميزة إلى الدجاج العادي بهذه الصلصة السهلة واللذيذة التي تكون جاهزة في دقائق.", "2", "153 غ",
 ["1 صدر دجاج كبير منزوع الجلد والعظم (حوالي 220 غ)", "2 ملعقة صغيرة من زيت اللفت", "4 فصوص ثوم، مهروسة", "1 حبة بصل أخضر، مفرومة ناعمًا", "25 غ من البقدونس الطازج، مفروم ناعمًا", "رشة كبيرة من الفلفل", "عصير نصف ليمونة", "1 ملعقة كبيرة من الزبادي اليوناني الخالي من الدسم (0%)"],
 ["ضع صدر الدجاج بين قطعتين من غلاف التغليف البلاستيكي واطرقه بمطرقة اللحم أو بشوبك العجين ليصبح شريحة إسكالوب مسطحة بسمك حوالي 4-5 مم. ثم اقسمه إلى حصتين متساويتين.", "افرد قطعتي صدر الدجاج بملعقة صغيرة واحدة من الزيت. ضعهما على مقلاة ساخنة أو مقلاة شواء واطهِهما 2-3 دقائق على كل جانب.", "في هذه الأثناء، سخّن الملعقة الصغيرة المتبقية من الزيت في مقلاة صغيرة، وأضف الثوم والبصل الأخضر واطهِهما لمدة دقيقتين حتى يلين البصل. ثم أضف البقدونس وقلّب لمدة دقيقة واحدة.", "أضف الفلفل وعصير الليمون و1 ملعقة كبيرة من الماء. أضف الزبادي مع التحريك.", "ضع الدجاج في صحن وقدّمه مع الصلصة."],
 ["يناسب هذا الطبق أيضًا شرائح إسكالوب الديك الرومي أو لحم البقر أو لحم الخنزير. أو جرّب الصلصة مع السمك المشوي.", "الطرق على اللحم يجعله طريًا ويجعل الفيليه أسرع بكثير في النضج، لذا فهو مثالي للشواء في الهواء الطلق.", FVH], [])))
# 7536929
R.append((7536929,
("Pollo al limón y hierbas con garbanzos", "Este plato refrescante está lleno de hierbas y combina muy bien con verduras a la parrilla.", "2", "326 g",
 ["2 pechugas de pollo sin hueso y sin piel, de aprox. 125 g cada una", "ralladura y jugo de 1 limón", "1 diente de ajo, machacado", "1 cucharadita de aceite de oliva", "1 cucharadita de semillas de mostaza negra", "1 cucharadita de semillas de comino", "4 cebollas verdes, picadas", "400 g de garbanzos, escurridos y enjuagados", "3 cucharadas de hierbas frescas variadas, picadas", "1 pizca de cúrcuma", "2 cucharadas de crème fraîche semidescremada", "pimienta negra recién molida"],
 ["Coloque el pollo en un recipiente no metálico, agregue la ralladura y el jugo de limón y el ajo, mezcle y deje reposar 30 minutos.", "Caliente el aceite en una sartén antiadherente, añada las semillas de mostaza y de comino y fríalas durante 1 minuto, hasta que desprendan su aroma.", "Agregue el pollo a la sartén y fríalo 2 minutos por cada lado. Luego añada el adobo a la sartén junto con 200 ml de agua hirviendo, tape y cocine a fuego lento de 7 a 8 minutos, volteando de vez en cuando, hasta que esté bien cocido.", "Agregue los demás ingredientes, cocine 2 minutos más, sazone bien y sirva."],
 ["Si necesita espesar un poco la salsa, aplaste unos cuantos garbanzos con un tenedor e incorpórelos.", "Sirva con verduras de diferentes colores para darle más atractivo y valor nutritivo.", "Instrucciones para congelar: se puede congelar una vez cocido. Luego descongele en el refrigerador o en el microondas y recaliente hasta que esté muy caliente por completo.", FVH], []),
("دجاج بالليمون والأعشاب مع الحمص", "هذا الطبق المنعش مليء بالأعشاب ويُقدَّم بشكل رائع مع الخضار المشوية.", "2", "326 غ",
 ["2 صدر دجاج منزوع العظم والجلد، حوالي 125 غ لكل صدر", "قشر مبشور وعصير ليمونة واحدة", "1 فص ثوم، مهروس", "1 ملعقة صغيرة من زيت الزيتون", "1 ملعقة صغيرة من بذور الخردل الأسود", "1 ملعقة صغيرة من بذور الكمون", "4 حبات بصل أخضر، مفرومة", "400 غ من الحمص، مصفّى ومشطوف", "3 ملاعق كبيرة من الأعشاب الطازجة المشكلة، مفرومة", "رشة من الكركم", "2 ملعقة كبيرة من الكريمة الحامضة (كريم فريش) نصف الدسم", "فلفل أسود مطحون طازجًا"],
 ["ضع الدجاج في طبق غير معدني، وأضف قشر الليمون وعصيره والثوم، واخلطها واتركها جانبًا لمدة 30 دقيقة.", "سخّن الزيت في مقلاة غير لاصقة، وأضف بذور الخردل وبذور الكمون وقلّبها لمدة دقيقة واحدة حتى تفوح رائحتها.", "أضف الدجاج إلى المقلاة وقلّبه لمدة دقيقتين على كل جانب. ثم أضف التتبيلة إلى المقلاة مع 200 مل من الماء المغلي، وغطِّها واتركها على نار هادئة لمدة 7-8 دقائق مع تقليب الدجاج من وقت لآخر حتى ينضج تمامًا.", "أضف باقي المكونات، واطهِها دقيقتين إضافيتين، وتبّل جيدًا وقدّم."],
 ["إذا احتجت إلى تثخين الصلصة قليلًا، فاهرس بضع حبات من الحمص بالشوكة وأضفها مع التحريك.", "قدّمه مع خضار متنوعة الألوان لإضافة جاذبية وقيمة غذائية أكبر.", "تعليمات التجميد: يمكن تجميده بعد الطهي. ثم أذبه في الثلاجة أو في الميكروويف وأعد تسخينه حتى يصبح ساخنًا جدًا في كل جزء منه.", FVH], [])))
# 7540200
R.append((7540200,
("Brochetas de tofu marinado", "Una alternativa vegetariana a las brochetas de carne, con tofu marinado y tomillo fresco.", "6", "156 g",
 ["1 cucharada de aceite de oliva", "1 cucharada de vinagre balsámico", "1 diente de ajo, machacado", "1 cucharadita de tomillo fresco", "1 paquete de 200 g de tofu (firme), escurrido y cortado en 12 cubos", "1 pimiento rojo (150 g), cortado en trozos", "1 pimiento amarillo (150 g), cortado en trozos", "2 calabacines (250 g), cortados en trozos", "1 cebolla morada (150 g), cortada en 8 gajos"],
 ["En un tazón no metálico, mezcle el aceite, el vinagre, el ajo y el tomillo.", "Agregue el tofu al tazón, cúbralo con el adobo y deje reposar al menos 10 minutos. Remoje los palillos de madera en agua para que no se quemen.", "Ensarte alternadamente el tofu marinado y los demás ingredientes en los palillos y cocine a la parrilla a temperatura media durante unos 10 minutos, hasta que empiecen a chamuscarse, volteando de vez en cuando."],
 ["Para darle un toque chino, pruebe agregar 1 cucharadita colmada de cinco especias chinas al adobo.", FVH], []),
("أسياخ التوفو المتبّل", "بديل نباتي لأسياخ اللحم باستخدام التوفو المتبّل والزعتر الطازج.", "6", "156 غ",
 ["1 ملعقة كبيرة من زيت الزيتون", "1 ملعقة كبيرة من الخل البلسمي", "1 فص ثوم، مهروس", "1 ملعقة صغيرة من الزعتر الطازج", "عبوة 200 غ من التوفو (المتماسك)، مصفّى ومقطع إلى 12 مكعبًا", "1 حبة فلفل رومي أحمر (150 غ)، مقطعة إلى قطع", "1 حبة فلفل رومي أصفر (150 غ)، مقطعة إلى قطع", "2 حبة كوسا (250 غ)، مقطعة إلى قطع", "1 حبة بصل أحمر (150 غ)، مقطعة إلى 8 أشرطة"],
 ["في وعاء غير معدني، اخلط الزيت والخل والثوم والزعتر معًا.", "أضف التوفو إلى الوعاء وغطِّه بالتتبيلة واتركه جانبًا لمدة 10 دقائق على الأقل. انقع الأسياخ الخشبية في الماء لمنعها من الاحتراق.", "اغرس مكعبات التوفو المتبّلة وباقي المكونات بالتناوب في الأسياخ واشوِها على شواية بحرارة متوسطة لمدة 10 دقائق تقريبًا حتى تبدأ في التفحّم قليلًا، مع تقليبها من وقت لآخر."],
 ["للحصول على لمسة صينية، جرّب إضافة 1 ملعقة صغيرة مكدسة من توابل الخمس الصينية إلى التتبيلة.", FVH], [])))
# 7540419
R.append((7540419,
("Harira", "Popular durante el Ramadán, esta sopa marroquí tradicional y contundente es nutritiva, reconfortante e hidratante.", "6", "537 g",
 ["1 cucharada de aceite de oliva", "200 g de cebolla, picada", "500 g de cordero magro, cortado en cubos de 1 cm", "3 pimientos (rojo, amarillo y verde), picados", "2 zanahorias, en cubos", "1 berenjena, cortada en cubos de 2 cm", "3 dientes de ajo, picados", "1 cucharadita colmada de pimentón", "1 cucharadita colmada de comino", "1 cucharadita bien llena de cúrcuma", "1 cucharadita colmada de canela", "1 lata de 400 g de tomates picados", "1 cubito de caldo de verduras (sin gluten)", "1.5 litros de agua hirviendo", "1 lata de 400 g de garbanzos, escurridos", "1 lata de 400 g de lentejas verdes, escurridas", "1 envase de 170 g de yogur griego sin grasa (0 %)", "1 manojo de 30 g de cilantro fresco, picado", "gajos de limón"],
 ["Caliente el aceite en una olla grande, añada la cebolla y cocine durante 5 minutos, hasta que empiece a dorarse.", "Agregue el cordero y cocine 7 minutos más, revolviendo con frecuencia.", "Ahora añada los pimientos, las zanahorias y la berenjena, mezcle bien y cocine durante 5 minutos.", "Luego agregue el ajo, el pimentón, el comino, la cúrcuma y la canela. Mezcle bien, después añada los tomates, desmenuce el cubito de caldo e incorpore el agua.", "Deje que hierva, revuelva y tape. Baje el fuego y cocine a fuego lento durante 1 hora; luego agregue los garbanzos y las lentejas, con su líquido. Mezcle bien y cocine 30 minutos más.", "Mientras tanto, mezcle el yogur y el cilantro.", "Sirva la sopa en tazones y cubra con una cucharada del yogur con cilantro y un chorrito de limón."],
 ["Para una versión vegetariana, sustituya el cordero por un paquete de tofu marinado o ahumado y una lata de frijoles variados.", "La harira también queda muy bien con pollo o res.", "Se conserva en el refrigerador de 2 a 3 días; sabe aún mejor al día siguiente de prepararla.", "Instrucciones para congelar: se puede congelar una vez cocida. Descongele en el refrigerador o en el microondas y recaliente hasta que esté muy caliente por completo.", FVH], []),
("حريرة", "تحظى هذه الشوربة المغربية التقليدية الدسمة بشعبية كبيرة خلال شهر رمضان، وهي مغذية ومهدئة ومرطّبة.", "6", "537 غ",
 ["1 ملعقة كبيرة من زيت الزيتون", "200 غ من البصل، مفروم", "500 غ من لحم الضأن الخالي من الدهن، مقطع إلى مكعبات بطول 1 سم", "3 حبات فلفل رومي – أحمر وأصفر وأخضر، مفرومة", "2 حبة جزر، مقطعة إلى مكعبات", "1 حبة باذنجان، مقطعة إلى مكعبات بطول 2 سم", "3 فصوص ثوم، مفرومة", "1 ملعقة صغيرة مكدسة من البابريكا", "1 ملعقة صغيرة مكدسة من الكمون", "1 ملعقة صغيرة ممتلئة من الكركم", "1 ملعقة صغيرة مكدسة من القرفة", "1 علبة (400 غ) من الطماطم المقطعة", "1 مكعب مرق خضار (خالٍ من الغلوتين)", "1.5 لتر من الماء المغلي", "1 علبة (400 غ) من الحمص، مصفّى", "1 علبة (400 غ) من العدس الأخضر، مصفّى", "1 عبوة (170 غ) من الزبادي اليوناني الخالي من الدسم (0%)", "حزمة 30 غ من الكزبرة الخضراء الطازجة، مفرومة", "أرباع ليمون"],
 ["سخّن الزيت في قدر كبير، وأضف البصل واطهه لمدة 5 دقائق حتى يبدأ في التحمير.", "أضف لحم الضأن واطهه 7 دقائق إضافية مع التحريك باستمرار.", "أضف الآن الفلفل الرومي والجزر والباذنجان، واخلط جيدًا واطهِها لمدة 5 دقائق.", "بعد ذلك، أضف الثوم والبابريكا والكمون والكركم والقرفة. اخلط جيدًا، ثم أضف الطماطم وفتّت مكعب المرق فوقها وأضف الماء مع التحريك.", "اتركها تغلي، وحرّك وغطِّ القدر. اخفض النار واتركها على نار هادئة لمدة ساعة واحدة، ثم أضف الحمص والعدس مع سائلهما. اخلط جيدًا واطهِها 30 دقيقة إضافية.", "في هذه الأثناء، اخلط الزبادي مع الكزبرة الخضراء.", "اغرف الشوربة في أوعية وضع فوقها ملعقة من الزبادي بالكزبرة وقليلًا من عصير الليمون."],
 ["للحصول على نسخة نباتية، استبدل لحم الضأن بعبوة من التوفو المتبّل أو المدخّن وعلبة من الفاصوليا المشكلة.", "تناسب الحريرة أيضًا الدجاج أو لحم البقر.", "تُحفظ في الثلاجة لمدة 2-3 أيام، ويكون مذاقها أفضل في اليوم التالي للتحضير.", "تعليمات التجميد: يمكن تجميدها بعد الطهي. اتركها تذوب في الثلاجة أو في الميكروويف، ثم أعد تسخينها حتى تصبح ساخنة جدًا في كل جزء منها.", FVH], [])))
if __name__ == "__main__":
    build(1, R)
