from h import *
R=[]
R.append((6992159,{
"es":L("Pita mediterránea de pollo",
"¡Aproveche el pollo sobrante en este sándwich sencillo y delicioso! Es un almuerzo rápido y fácil ideal para trabajar desde casa, o una cena para una noche ocupada entre semana. Si no tiene salsa tzatziki, puede usar yogur griego natural. Duplique el sabor: ¡use las sobras de nuestra receta de pollo marinado en yogur griego para obtener aún más sabor!",
"4","1 pita tipo bolsillo (incluye 1/2 pan pita, 2 1/2 oz de pollo, 2 cucharadas de salsa, 1/2 taza de verduras y 2 cucharadas de almendras)",
["2 tazas de pollo cocido (en cubos)","1/2 taza de salsa tzatziki baja en grasa (o yogur griego natural sin grasa)","2 pitas integrales enteras tipo bolsillo (cortadas por la mitad para obtener 4 bolsillos de pita)","1 taza de pepino (en cubos)","1 taza de tomate (en cubos)","1/2 taza de almendras tostadas en seco (sin sal, rebanadas)"],
["En un tazón mediano, mezcle el pollo y la salsa tzatziki. Rellene cada bolsillo de pita con 1/2 taza de la mezcla de pollo.","Cubra cada bolsillo de pita relleno con 1/4 taza de pepino, 1/4 taza de tomate y 2 cucharadas de almendras rebanadas."]),
"ar":L("خبز بيتا بالدجاج على الطريقة المتوسطية",
"أعد استخدام بقايا الدجاج في هذا الساندويتش البسيط واللذيذ! إنه غداء سريع وسهل مثالي للعمل من المنزل، أو عشاء لليالي الأسبوع المزدحمة. وإذا لم يكن لديك صلصة التزاتزيكي، يمكنك استخدام الزبادي اليوناني السادة بدلًا منها. ضاعف النكهة: استخدم بقايا وصفة الدجاج المتبّل بالزبادي اليوناني لمزيد من النكهة!",
"4","1 جيب بيتا (يشمل ½ رغيف بيتا، 2½ أونصة دجاج، 2 ملعقة كبيرة صلصة، ½ كوب خضار و2 ملعقة كبيرة لوز)",
["2 كوب دجاج مطبوخ (مقطع مكعبات)","½ كوب صلصة تزاتزيكي قليلة الدسم (أو زبادي يوناني سادة خالٍ من الدسم)","2 رغيف بيتا كامل من الحبوب الكاملة على شكل جيب (مقطوعة إلى نصفين للحصول على 4 جيوب بيتا)","1 كوب خيار (مقطع مكعبات)","1 كوب طماطم (مقطعة مكعبات)","½ كوب لوز محمص جاف (غير مملح، مقطع شرائح)"],
["في وعاء خلط متوسط، اخلط الدجاج مع صلصة التزاتزيكي. احشُ كل جيب بيتا بـ ½ كوب من خليط الدجاج.","ضع فوق كل جيب بيتا محشو ¼ كوب خيار و¼ كوب طماطم و2 ملعقة كبيرة لوز مقطع شرائح."])}))
R.append((6992179,{
"ar":L("دجاج مغطى بالبارميزان",
"وصفة دجاج غنية بالنكهة ومتعددة الاستخدامات، قدّمها كطبق رئيسي مع الخضار أو فوق السلطة. وهي أيضًا مناسبة للأطفال وأكثر صحة بكثير من أي ناجتس دجاج مجمد.",
"6","2 شريحة دجاج",
["1 بخّة، 0.25 غرام بخاخ طهي غير لاصق","½ كوب دقيق الذرة","⅓ كوب جبن بارميزان (مبشور طازجًا)","½ ملعقة صغيرة مسحوق الثوم","¼ ملعقة صغيرة فلفل أسود","3 بياض بيض كبير","1½ رطل صدور دجاج منزوعة العظم والجلد (مقطعة إلى 12 شريحة رفيعة)"],
["سخّن الفرن مسبقًا إلى 425° فهرنهايت (220° مئوية). رشّ صينية الخَبز ببخاخ الطهي.","في طبق مسطح، اخلط دقيق الذرة وجبن البارميزان ومسحوق الثوم والفلفل الأسود.","في طبق خَبز مسطح آخر، اخفق بياض البيض.","اغمس شريحة صدر الدجاج في خليط البيض ثم غطِّها جيدًا بخليط دقيق الذرة. غطِّها جيدًا وضعها على صينية الخَبز. كرّر العملية مع جميع شرائح الدجاج.","رشّ شرائح الدجاج ببخاخ الطهي. اخبزها 15 إلى 20 دقيقة أو حتى تنضج؛ اقلب قطع الدجاج في منتصف مدة الطهي."])}))
R.append((6992930,{
"es":L("Huevos rellenos con pesto",
"Los huevos rellenos con pesto son una versión sabrosa y elegante de la receta clásica. La combinación de pesto, mayonesa y mostaza Dijon crea un relleno cremoso y con un toque picante que combina de maravilla con la riqueza natural de los huevos cocidos. Estos huevos rellenos son un excelente aperitivo para fiestas o un sabroso complemento para su brunch.",
"8","2 mitades",
["8 huevos grandes","1/4 taza de mayonesa light","2 cucharadas de salsa pesto (de frasco)","1 cucharadita de mostaza Dijon","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra"],
["Coloque los huevos en una sola capa en una cacerola y cúbralos con agua. Deje que el agua hierva, luego reduzca el fuego a bajo, tape y cocine a fuego lento de 10 a 12 minutos.","Pase los huevos cocidos a un baño de agua con hielo para que se enfríen.","Cuando los huevos estén fríos, pélelos y córtelos por la mitad a lo largo. Retire las yemas y colóquelas en un tazón.","En el tazón con las yemas, agregue la mayonesa, el pesto de albahaca preparado, la mostaza Dijon, la sal y la pimienta. Machaque y mezcle los ingredientes hasta que quede suave.","Con una cuchara o una manga pastelera, rellene las claras ahuecadas con el relleno de pesto.","Refrigere los huevos rellenos por lo menos 30 minutos antes de servir."]),
"ar":L("بيض محشي بالبيستو",
"البيض المحشي بالبيستو لمسة لذيذة وأنيقة على الوصفة الكلاسيكية. يخلق المزج بين البيستو والمايونيز وخردل الديجون حشوة كريمية منعشة تتناغم بشكل رائع مع الغنى الطبيعي للبيض المسلوق. يُعد هذا البيض المحشي مقبلات رائعة للحفلات أو إضافة لذيذة لمائدة الفطور المتأخر.",
"8","2 نصف",
["8 بيضات كبيرة","¼ كوب مايونيز خفيف","2 ملعقة كبيرة صلصة بيستو (جاهزة في برطمان)","1 ملعقة صغيرة خردل ديجون","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["ضع البيض في طبقة واحدة في قدر وغطِّه بالماء. اترك الماء حتى يغلي، ثم خفّف النار إلى هادئة، وغطِّ القدر، واتركه على نار هادئة لمدة 10 إلى 12 دقيقة.","انقل البيض المسلوق إلى حمام ماء مثلج ليبرد.","بعد أن يبرد البيض، قشّره واقطعه إلى نصفين طوليًا. أخرج الصفار وضعه في وعاء.","في الوعاء الذي فيه الصفار، أضف المايونيز وبيستو الريحان الجاهز وخردل الديجون والملح والفلفل. اهرس المكونات واخلطها معًا حتى تصبح ناعمة.","املأ بياض البيض المفرغ بحشوة البيستو باستخدام ملعقة أو كيس تزيين.","ضع البيض المحشي في الثلاجة لمدة 30 دقيقة على الأقل قبل التقديم."])}))
R.append((6993572,{
"ar":L("سوفليه البيض",
"هذا سوفليه بيض خفيف ورقيق مع إضافة الخضار.",
"4","¼ السوفليه",
["1 بخّة، 0.25 غرام بخاخ طهي غير لاصق","2 كوب كرنب أجعد طازج (مفروم)","½ حبة بصل صغيرة (مقطعة شرائح رفيعة)","½ ملعقة صغيرة ملح (اختياري)","½ ملعقة صغيرة أعشاب بروفانس","1 كوب فتات سجق ديك رومي مطبوخ","1 كوب بديل البيض","4 بياض بيض كبير","½ ملعقة صغيرة كريم التارتار"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية).","رشّ مقلاة بخاخ الطهي وضعها على نار متوسطة. قلّب الكرنب والبصل حتى ينضج البصل فقط، لمدة 5 إلى 6 دقائق تقريبًا. أضف الملح (اختياري) وأعشاب بروفانس وسجق الديك الرومي. ضعه جانبًا ليبرد.","بمجرد أن تبرد الخضار واللحم، حرّك فيها بديل البيض وضعها جانبًا.","في وعاء نظيف، اخلط بياض البيض مع كريم التارتار. باستخدام خلاط كهربائي، اخفق بياض البيض حتى تتكون قمم صلبة.","اطوِ بياض البيض برفق في خليط البيض والخضار، واسكبه في طبق خَبز دائري سعته 2½ كوارت. (يمكنك أيضًا استخدام طبق مربع مقاس 8 بوصات. احرص على ألا ترش طبق الخَبز ببخاخ الطهي وإلا فلن ينتفخ السوفليه.)","اخبز لمدة 30 دقيقة. قطّع السوفليه إلى أربع قطع متساوية وقدّمه فورًا.","ملاحظة: سيهبط السوفليه قليلًا بعد إخراجه من الفرن، وهذا طبيعي."])}))
R.append((6994119,{
"es":L("Tilapia a la parrilla con salsa crujiente de maíz y arúgula",
"Esta tilapia a la parrilla es un platillo fresco y sabroso que encaja en el patrón de alimentación bajo en grasa y bajo en carbohidratos. Los tiernos filetes de tilapia se asan a la perfección y se sirven con una vibrante salsa de maíz crujiente, tomates, cebolla y cilantro, todo sobre una cama de arúgula de sabor picante.",
"4","4 oz de tilapia, 3/4 taza de salsa, 1 taza de arúgula",
["2 tazas de granos de maíz frescos o congelados (descongelados si están congelados)","1 pimiento rojo mediano (en cubos)","1/2 cebolla morada pequeña (en cubos finos)","1 chile jalapeño pequeño (en cubos finos)","2 cucharadas de vinagre de arroz sin sazonar","1 cucharada de aceite de oliva","1/4 taza de cilantro fresco (picado)","4 filetes (de 4 a 5 oz cada uno) de tilapia (frescos o congelados, descongelados)","1 rociada de aceite en aerosol antiadherente","1 cucharadita de comino molido","1 cucharadita de pimentón ahumado","1/4 cucharadita de ajo en polvo","1/4 cucharadita de pimienta negra","4 tazas de arúgula tierna"],
["En un tazón grande, combine el maíz, el pimiento rojo, la cebolla morada, el jalapeño, el vinagre de arroz, el aceite de oliva y el cilantro. Mezcle bien y reserve.","Seque los filetes de tilapia con una toalla de papel. Rocíelos con aceite en aerosol por ambos lados. Espolvoree de manera uniforme con el comino, el pimentón ahumado, el ajo en polvo y la pimienta negra.","Precaliente una parrilla o una plancha acanalada a fuego medio-alto. Rocíe la plancha con aceite. Ase la tilapia de 3 a 4 minutos por lado, o hasta que el pescado se desmenuce fácilmente con un tenedor. Retire del fuego y deje reposar un minuto.","Divida la arúgula entre 4 platos. Coloque un filete de tilapia asado sobre la arúgula. Vierta con una cuchara la salsa crujiente de maíz sobre el pescado y alrededor de él."]),
"ar":L("سمك البلطي المشوي مع صلصة الذرة المقرمشة والجرجير",
"سمك البلطي المشوي هذا طبق طازج وغني بالنكهة يناسب النمط الغذائي القليل الدهون والقليل الكربوهيدرات. تُشوى شرائح البلطي الطرية بإتقان وتُقدَّم مع صلصة نابضة بالحياة من الذرة المقرمشة والطماطم والبصل والكزبرة الخضراء، وكلها فوق فراش من الجرجير ذي الطعم اللاذع.",
"4","4 أونصة سمك بلطي، ¾ كوب صلصة، 1 كوب جرجير",
["2 كوب حبوب ذرة طازجة أو مجمدة (تُذاب إن كانت مجمدة)","1 حبة فلفل رومي أحمر متوسطة (مقطعة مكعبات)","½ حبة بصل أحمر صغيرة (مقطعة مكعبات صغيرة جدًا)","1 حبة فلفل هالبينو صغيرة (مقطعة مكعبات صغيرة جدًا)","2 ملعقة كبيرة خل الأرز غير المتبّل","1 ملعقة كبيرة زيت زيتون","¼ كوب كزبرة خضراء طازجة (مفرومة)","4 شرائح (4 إلى 5 أونصة لكل شريحة) سمك بلطي (طازج أو مجمد، مُذاب)","1 بخّة بخاخ طهي غير لاصق","1 ملعقة صغيرة كمون مطحون","1 ملعقة صغيرة بابريكا مدخنة","¼ ملعقة صغيرة مسحوق الثوم","¼ ملعقة صغيرة فلفل أسود","4 كوب جرجير صغير"],
["في وعاء كبير، اخلط الذرة والفلفل الرومي الأحمر والبصل الأحمر والهالبينو وخل الأرز وزيت الزيتون والكزبرة الخضراء. قلّبها جيدًا وضعها جانبًا.","جفّف شرائح البلطي بمنشفة ورقية. رشّها ببخاخ الطهي من الجانبين. رشّ عليها بالتساوي الكمون والبابريكا المدخنة ومسحوق الثوم والفلفل الأسود.","سخّن شواية أو مقلاة شواء مسبقًا على نار متوسطة إلى عالية. رشّ المقلاة بالزيت. اشوِ البلطي لمدة 3 إلى 4 دقائق لكل جانب، أو حتى يتفتت السمك بسهولة بالشوكة. ارفعه عن النار واتركه يرتاح دقيقة.","وزّع الجرجير على 4 أطباق. ضع شريحة بلطي مشوية فوق الجرجير. اسكب صلصة الذرة المقرمشة بالملعقة فوق السمك وحوله."])}))
R.append((6994243,{
"es":L("Avena horneada con arándanos azules y almendra",
"Una avena horneada sustanciosa hecha con avena, chía, linaza y semillas de cáñamo, mezclada con arándanos azules y cubierta con yogur griego sin grasa y almendras tostadas. Este desayuno rico en fibra y proteína ofrece una nutrición equilibrada con grasas saludables para el corazón y sin azúcares añadidos.",
"6","1 rebanada de 1.5\" x 5\"",
["6 cucharadas de almendras en tiras","2 huevos enteros","1/2 taza de leche de almendra sin azúcar","1 cucharadita de extracto de vainilla","2 cucharadas de sustituto de azúcar morena sin azúcar","1/4 taza de semillas de chía","2 cucharadas de linaza molida","1/2 taza de avena en hojuelas","1/4 taza de semillas de cáñamo peladas","1/4 taza de harina de almendra","1 cucharadita de canela molida","1 cucharadita de polvo de hornear","1/8 cucharadita de sal","3/4 taza de arándanos azules Dole®","1 1/2 tazas de yogur griego natural sin grasa"],
["Precaliente el horno a 350 grados F (175 grados C). Engrase o forre un molde para pan de 9x5 pulgadas.","Extienda las almendras en una bandeja para hornear con borde. Tuéstelas en el horno de 5 a 8 minutos, hasta que estén ligeramente doradas y aromáticas.","En un tazón mediano, bata los huevos, la leche de almendra, la vainilla y el sustituto de azúcar morena sin azúcar hasta obtener una mezcla suave y cremosa.","En un tazón grande, mezcle las semillas de chía, la linaza, la avena en hojuelas, las semillas de cáñamo, la harina de almendra, la canela, el polvo de hornear y la sal.","Vierta la mezcla húmeda sobre los ingredientes secos y revuelva hasta que se integren por completo. La masa se espesará ligeramente a medida que la chía y la linaza absorban el líquido.","Incorpore con suavidad los arándanos azules.","Extienda la mezcla de manera uniforme en el molde preparado. Hornee de 30 a 35 minutos, girando el molde a la mitad del tiempo, hasta que el centro esté firme y la parte superior esté ligeramente dorada y comience a agrietarse.","Deje enfriar la avena 10 minutos antes de cortarla en 6 porciones iguales. Sirva caliente, cubierta con 1/4 taza de yogur griego bajo en grasa y 1 cucharada de almendras en tiras por porción. Envuelva las sobras una vez frías y guárdelas en el refrigerador."]),
"ar":L("شوفان مخبوز بالتوت الأزرق واللوز",
"شوفان مخبوز مشبع مصنوع من الشوفان وبذور الشيا والكتان والقنب، مع التوت الأزرق، ومزيّن بالزبادي اليوناني الخالي من الدسم واللوز المحمص. توفر وجبة الإفطار الغنية بالألياف والبروتين هذه تغذية متوازنة مع دهون صحية للقلب ودون سكر مضاف.",
"6","شريحة 1.5\" × 5\"",
["6 ملعقة كبيرة لوز مقطع شرائح رفيعة","2 بيضة كاملة","½ كوب حليب لوز غير محلى","1 ملعقة صغيرة خلاصة الفانيليا","2 ملعقة كبيرة بديل السكر البني الخالي من السكر","¼ كوب بذور الشيا","2 ملعقة كبيرة بذور كتان مطحونة","½ كوب شوفان مجروش","¼ كوب بذور القنب المقشرة","¼ كوب دقيق لوز","1 ملعقة صغيرة قرفة مطحونة","1 ملعقة صغيرة بيكنج باودر","⅛ ملعقة صغيرة ملح","¾ كوب توت أزرق من Dole®","1½ كوب زبادي يوناني سادة خالٍ من الدسم"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية). ادهن قالب خبز مقاس 9×5 بوصة بالزيت أو بطّنه بورق.","وزّع اللوز على صينية خَبز ذات حواف. حمّصه في الفرن لمدة 5 إلى 8 دقائق، حتى يصبح بنيًا فاتحًا وتفوح رائحته.","في وعاء متوسط، اخفق البيض وحليب اللوز والفانيليا وبديل السكر البني الخالي من السكر حتى يصبح الخليط ناعمًا وكريميًا.","في وعاء كبير، اخلط بذور الشيا وبذور الكتان والشوفان المجروش وبذور القنب ودقيق اللوز والقرفة والبيكنج باودر والملح.","اسكب الخليط السائل فوق المكونات الجافة وحرّك حتى يمتزج تمامًا. سيزداد سُمك العجينة قليلًا مع امتصاص بذور الشيا والكتان للسائل.","أضف التوت الأزرق برفق.","وزّع الخليط بالتساوي في قالب الخبز المجهز. اخبزه لمدة 30 إلى 35 دقيقة، مع تدوير القالب في منتصف المدة، حتى يتماسك الوسط ويصبح وجهه ذهبيًا فاتحًا ويبدأ في التشقق.","اترك الشوفان يبرد 10 دقائق قبل تقطيعه إلى 6 حصص متساوية. قدّمه دافئًا مع ¼ كوب زبادي يوناني قليل الدسم و1 ملعقة كبيرة لوز مقطع شرائح رفيعة لكل حصة. لفّ الباقي بعد أن يبرد واحفظه في الثلاجة."])}))
R.append((6994909,{
"ar":L("طاجن الدجاج بالناتشوز",
"طاجن الدجاج بالناتشوز قليل الدهن هذا طبق دافئ ومريح مصنوع من الدجاج والفاصولياء والخضار والتوابل القوية. يحمل كل نكهات الناتشوز مخبوزة في وجبة واحدة سهلة. وهو بسيط التحضير ومثالي لعشاء مشبع ومناسب للعائلة.",
"6","1 كوب",
["1 بخّة، 0.25 غرام بخاخ طهي غير لاصق","⅛ ملعقة صغيرة فلفل أسود","1 رطل صدور دجاج منزوعة العظم والجلد (مقطعة قطعًا صغيرة)","1 علبة (14.5 أونصة) طماطم محمصة على النار","1 علبة (15 أونصة) فاصولياء سوداء بدون ملح مضاف (مصفّاة ومشطوفة)","2 ملعقة صغيرة مسحوق الفلفل الحار (تشيلي)","½ ملعقة صغيرة كمون","½ ملعقة صغيرة مسحوق الثوم","⅔ كوب جبن شيدر (مبشور، قليل الدسم)","1½ أونصة رقائق التورتيلا (حوالي 24 رقاقة، مفتّتة)"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية). رشّ طبق خَبز سعته 2½ كوارت ببخاخ الطهي.","تبّل الدجاج بالفلفل الأسود. رشّ مقلاة كبيرة ببخاخ الطهي وسخّنها على نار متوسطة إلى عالية. أضف الدجاج واطهِه لمدة 8 دقائق.","أضف الطماطم المقطعة والفاصولياء السوداء ومسحوق الفلفل الحار والكمون ومسحوق الثوم إلى المقلاة. خفّض النار إلى هادئة واتركها تغلي بهدوء لمدة 5 دقائق.","اسكب خليط الدجاج في طبق الخَبز. انثر الجبن فوقه ثم غطِّه بالتورتيلا المفتّتة. اخبزه لمدة 12 دقيقة أو حتى يذوب الجبن."])}))
R.append((6995196,{
"es":L("Agua de pepino y limón",
"¡Dele vida al agua infusionándola con fruta y hierbas! Agregar rebanadas de pepino, limón y hierbas frescas le da un sabor sutil al agua natural sin añadir azúcar ni calorías. ¡Pruebe otras combinaciones como sandía y romero, piña y menta, o cualquier otra que se le ocurra!",
"10","1 taza (8 oz)",
["1 pepino mediano","1 limón","1/4 taza de hojas de albahaca fresca","1/4 taza de hojas de menta fresca","10 tazas (80 oz) de agua"],
["Corte el pepino y el limón en rebanadas finas y colóquelas en una jarra grande.","Aplaste suavemente con la mano las hojas de albahaca y menta y agréguelas a la jarra. Llene con 10 tazas de agua.","Refrigere el agua toda la noche antes de servir para que se infusionen bien los sabores."]),
"ar":L("ماء بالخيار والليمون",
"أضفِ الحيوية إلى الماء بنقعه مع الفاكهة والأعشاب! تضيف شرائح الخيار والليمون والأعشاب الطازجة نكهة خفيفة للماء العادي دون إضافة أي سكر أو سعرات حرارية. جرّب تركيبات أخرى مثل البطيخ وإكليل الجبل، أو الأناناس والنعناع، أو أي شيء آخر يخطر ببالك!",
"10","1 كوب (8 أونصة)",
["1 حبة خيار متوسطة","1 حبة ليمون","¼ كوب أوراق ريحان طازجة","¼ كوب أوراق نعناع طازجة","10 كوب (80 أونصة) ماء"],
["قطّع الخيار والليمون إلى شرائح رفيعة وضعها في إبريق كبير.","اهرس أوراق الريحان والنعناع برفق بيدك وأضفها إلى الإبريق. أضف 10 أكواب من الماء.","ضع الماء في الثلاجة طوال الليل قبل التقديم لتتشرب النكهات تمامًا."])}))
R.append((6996404,{
"es":L("Mantequilla de almendra","Información nutricional de 1 cucharada de mantequilla de almendra","1","1 cucharada",["1 cucharada de mantequilla de almendra"],[]),
"ar":L("زبدة اللوز","معلومات غذائية عن 1 ملعقة كبيرة من زبدة اللوز","1","1 ملعقة كبيرة",["1 ملعقة كبيرة زبدة لوز"],[])}))
R.append((6999413,{
"ar":L("تونة مشوية بصلصة البيستو",
"هذه التونة المشوية بصلصة البيستو وجبة سريعة وغنية بالنكهة تبدو مميزة لكنها سهلة التحضير. تنضج التونة في دقائق قليلة وتتناغم جيدًا مع البيستو الطازج الغني بالأعشاب. إنها طريقة بسيطة للاستمتاع بطبق عالي البروتين وقليل الكربوهيدرات، خفيف ومشبع ومليء بالنكهات المنعشة. قدّمها مع خضار غير نشوية مفضلة لديك وحبوب كاملة لوجبة متوازنة.",
"4","1 شريحة تونة",
["1 ملعقة كبيرة زيت زيتون","1 رطل شرائح تونة أهي (مقسمة إلى 4 حصص، 4 أونصة لكل حصة)","4 ملعقة كبيرة صلصة بيستو جاهزة (في برطمان)"],
["سخّن زيت الزيتون في مقلاة على نار متوسطة إلى عالية.","ضع شرائح التونة في الزيت الساخن وحمّرها لمدة 3 إلى 4 دقائق على جانب واحد. اقلب التونة وادهن كل شريحة بـ 1 ملعقة كبيرة من صلصة البيستو. اطهِها 3 إلى 4 دقائق إضافية."])}))
save("out_c26_part3.json",R)
