import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes1')
from h import *
X=[]
X.append(r(9373393,"Muffins veganos saludables de calabacín","Disfrute lo bueno de los muffins veganos saludables de calabacín, perfectos para el desayuno, el postre o la botana.","12 muffins","1 muffin",
[("Ingredientes secos","2 tazas de harina de avena, sin gluten si lo prefiere"),("Ingredientes secos","¼ taza de semillas de linaza, enteras o molidas*"),("Ingredientes secos","1 cucharadita de canela"),("Ingredientes secos","¼ cucharadita de nuez moscada"),("Ingredientes secos","1.5 cucharaditas de polvo para hornear"),("Ingredientes secos","½ cucharadita de bicarbonato de sodio"),("Ingredientes secos","⅛ cucharadita de sal marina"),("Ingredientes secos","½ taza de nueces pecanas o nueces de Castilla picadas, opcional pero recomendado"),
("Ingredientes húmedos","2 tazas de calabacín rallado (aprox. 1 calabacín mediano)"),("Ingredientes húmedos","⅓ taza de miel de maple"),("Ingredientes húmedos","¼ taza de puré de manzana sin azúcar"),("Ingredientes húmedos","¾ taza de leche de soya")],
["Precaliente el horno a 350℉/176℃ y engrase un molde para muffins.**(vea las notas si evita el aceite)",
"Exprima el exceso de humedad del calabacín rallado sobre un tazón o sobre el fregadero de la cocina. Luego colóquelo en un tazón con los demás ingredientes húmedos y mezcle.",
"Bata los ingredientes secos en otro tazón y agréguelos al tazón de los ingredientes húmedos. Revuelva hasta que no queden grumos de harina, sin mezclar en exceso. Deje reposar la masa 10 minutos; espesará ligeramente. Luego revuélvala rápidamente antes de dividirla entre los 12 moldes para muffins.",
"Hornee de 18 a 22 minutos, o hasta que un palillo insertado en el centro salga limpio y seco. Deje que los muffins se enfríen al menos 10 minutos en el molde y luego páselos a una rejilla para que sigan enfriándose."],
["Use polvo para hornear activo para lograr el máximo esponjamiento. El polvo para hornear que lleva abierto en la despensa más de 6 meses puede comenzar a perder su efectividad.","Puede usar semillas de linaza enteras o molidas para estos muffins. Las semillas enteras aportan más textura crujiente, y las molidas ofrecen los máximos beneficios para la salud.","Puede rallar el calabacín con un rallador de caja o un procesador de alimentos; ambos están bien.","Para que sea sin soya, use leche de almendra o de anacardo.","Para que sea sin frutos secos, simplemente omita las nueces o use chispas de chocolate o fruta seca para dar más dulzor.","Deje reposar la masa 10 minutos antes de ponerla con una cuchara en el molde para muffins para obtener muffins más esponjosos. Revuélvala rápidamente después de 10 minutos y luego divida y hornee.","Estos muffins NO son muy dulces, así que si le gustan los dulces, recomiendo usar chispas de chocolate en lugar de las nueces picadas.","**Si tiene un molde para muffins antiadherente de buena calidad y relativamente nuevo, no necesitará engrasarlo. Lo probé de ambas formas y mis muffins no se pegaron al molde. Sin embargo, DEBE esperar 10 minutos antes de intentar pasar los muffins a la rejilla de enfriamiento. Los muffins se conservan tapados a temperatura ambiente hasta por 3 días, refrigerados hasta por 1 semana y congelados en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9375021,"Pan vegano de plátano con chispas de chocolate","¡Una receta infalible para un pan vegano de plátano con chispas de chocolate perfectamente húmedo y delicioso!","12 rebanadas (1 pan de 5\"9\")","1 rebanada",
[("Ingredientes húmedos","5 plátanos (bananas) medianos muy maduros (aprox. 1.5 tazas machacados)"),("Ingredientes húmedos","⅓ taza de leche de soya o la leche de su preferencia"),("Ingredientes húmedos","⅓ taza de puré de manzana sin azúcar"),("Ingredientes húmedos","¼ taza de miel de maple"),("Ingredientes húmedos","2 cucharaditas de extracto puro de vainilla"),
("Ingredientes secos","½ taza de avena cortada de cocción rápida o avena en hojuelas, sin gluten si lo prefiere"),("Ingredientes secos","1.5 tazas de harina de trigo integral o harina de avena para que sea sin gluten, ¡ambas funcionan muy bien!"),("Ingredientes secos","½ cucharadita de sal marina"),("Ingredientes secos","1 cucharadita de polvo para hornear"),("Ingredientes secos","1 cucharadita de bicarbonato de sodio"),
("Para cubrir (opcional)","¼ taza de chispas de chocolate semiamargo sin lácteos")],
["Precaliente el horno a 350 grados F y forre un molde para pan de 5\"x 9\" con papel pergamino.",
"En un tazón grande, machaque los plátanos y combine todos los ingredientes húmedos. Mezcle bien.",
"Al mismo tazón, agregue los ingredientes secos y mezcle solo hasta integrar, sin mezclar en exceso. (¡Unos cuantos grumos están bien!)",
"Vierta la mezcla en el molde para pan y alise suavemente la parte superior con una espátula de silicón. Luego espolvoree las chispas de chocolate encima (si las usa) y presione muy suavemente.",
"Hornee de 45 a 55 minutos hasta que esté ligeramente dorado y un palillo insertado en el centro salga limpio. Luego retire del horno y deje enfriar 10 minutos antes de sacar el pan del molde, usando el papel pergamino para ayudar a levantarlo. Continúe enfriando en una rejilla durante al menos 20-30 minutos antes de rebanar."],
["Después de verter la masa en el molde para pan, golpéelo suavemente unas cuantas veces sobre una superficie plana para llenar cualquier hueco en el pan. El tiempo de cocción variará según el tamaño de su molde, así que siempre verifique el punto de cocción insertando un palillo en el centro para ver si sale limpio. Asegúrese de dejar reposar el pan de plátano al menos 30 minutos para facilitar el rebanado. El tiempo de reposo permite que el pan se asiente por completo. Si no encuentra chispas de chocolate sin lácteos, puede usar trozos de chocolate, o tomar cualquier barra de chocolate vegano y partirla usted mismo en trozos. Para que sea sin gluten, use harina de avena certificada sin gluten y, si no tiene a la mano, puede moler avena sin gluten en una licuadora o procesador de alimentos hasta lograr una consistencia de harina. Para que sea sin soya, use leche de almendra, de anacardo o la de su elección. Si no es amante del chocolate, omita las chispas de chocolate. O cubra el pan con rodajas de plátano, nueces de Castilla o nueces pecanas. Guarde las sobras a temperatura ambiente hasta por 3 días, bien envueltas. En el refrigerador hasta por 1 semana o congele hasta por 3 meses."],[]))
X.append(r(9376343,"Pimientos \"sin rellenar\" en Instant Pot","¡Todo el gran sabor de los pimientos rellenos, pero más fácil que nunca! Estos pimientos «sin rellenar» en Instant Pot, también conocidos como cazuela de pimientos rellenos, son abundantes, reconfortantes y total y absolutamente deliciosos.","4 porciones","1 porción",
["1 cebolla amarilla en rodajas","3 dientes de ajo picados","3 pimientos morrones en rodajas (de cualquier color)","8 onzas (227 gramos) de champiñones cremini o blancos en rebanadas (aprox. 6-8 champiñones)","¾ taza de trozos de nueces de Castilla","1 taza de arroz integral crudo","1 ¼ taza de caldo de verduras bajo en sodio","1 taza de salsa de tomate o puré de tomate de su elección","1 cucharadita de comino","1.5 cucharaditas de chile en polvo","1.5 cucharaditas de pimentón ahumado","½ cucharadita de sal marina","¼ cucharadita de pimienta de cayena, opcional"],
["Ponga su Instant Pot en la función de saltear y agregue un par de cucharadas de agua o caldo a la olla. Coloque dentro la cebolla, el ajo, los pimientos, los champiñones, las nueces de Castilla y todos los condimentos. Luego saltee de 2 a 3 minutos, hasta que estén ligeramente suaves.",
"Agregue los demás ingredientes (caldo, salsa de tomate y arroz), mezcle bien y cierre la tapa. Coloque la válvula en la posición de sellado y cocine a presión durante 22 minutos. (Tardará unos 8 minutos en acumular presión antes de que la olla comience la cuenta regresiva.) Cuando termine el temporizador, deje que la presión se libere de forma natural durante 10 minutos. Luego libere rápidamente la presión restante y retire la tapa cuando sea seguro hacerlo. Disfrute."],
["No corte las verduras demasiado delgadas. Se cocinarán por un buen rato en la olla, así que resistirán mejor la cocción si están en cortes gruesos. Como alternativa, si prefiere las verduras crujientes, retírelas de la olla una vez salteadas, cocine el arroz a presión en el caldo y la salsa de tomate, luego regrese las verduras y mezcle bien. Asegúrese de empujar hacia abajo cualquier grano de arroz suelto en los lados de la olla antes de cocinar a presión. Todo debe estar cubierto por el líquido para una cocción uniforme. Si ya liberó la presión y olvidó hacer la liberación natural de 10 minutos, simplemente presione saltear y, revolviendo con frecuencia, continúe cocinando de 3 a 5 minutos para absorber el exceso de líquido. O deje reposar unos 10 minutos. El arroz seguirá absorbiendo el líquido mientras reposa y se enfría. Las sobras se conservan refrigeradas hasta por 3 días, y puede recalentarlas en la estufa o en su Instant Pot."],[]))
X.append(r(9379335,"Panqueques de aguacate","Estos panqueques de aguacate están llenos de bondad y son una versión fresca de un clásico del desayuno.","8 panqueques","1 porción",
["½ aguacate machacado","⅓ taza de plátano (banana) machacado (aprox. 1 plátano mediano)","1 taza de leche de soya o la leche sin lácteos de su preferencia","120 gramos de harina de trigo integral (aprox. 1 taza)","1 cucharada de azúcar de caña o azúcar de coco sin refinar","2 cucharaditas de polvo para hornear"],
["Precaliente la plancha a fuego medio. Luego machaque el plátano y el aguacate en un tazón mediano y vierta la leche. Mezcle bien.","A continuación, agregue la harina, el azúcar y el polvo para hornear. Luego revuelva hasta integrar, sin mezclar en exceso.","Vierta la masa con un cucharón sobre la plancha precalentada, haciendo panqueques de aproximadamente 4 pulgadas de diámetro. Cocine de 4 a 5 minutos hasta que los bordes estén dorados y haya varias burbujas en la superficie.","Luego voltee y continúe cocinando hasta que los panqueques estén bien cocidos."],
["Pese la harina para obtener los resultados más precisos. Sacarla de la bolsa con la taza suele hacer que se use demasiada harina porque se compacta en la taza medidora.","Si no tiene una báscula de cocina, ponga la harina con una cuchara en la taza medidora y raspe la parte superior con un cuchillo, pero no la saque directamente de la bolsa.","Use polvo para hornear fresco y activo. El polvo para hornear que se ha abierto y lleva varios meses en la despensa puede comenzar a perder su efectividad.","No es necesario mezclar en exceso la masa de los panqueques. Si quedan algunos grumos, está perfectamente bien. Solo mezcle hasta integrar y que no queden grumos de harina.","Precaliente la sartén o la plancha. Debe estar caliente antes de verter la masa para evitar que se pegue y para una cocción uniforme.","Use fuego medio para cocinar los panqueques. Aunque la sartén debe estar caliente, eso no significa que deba usar fuego alto. Esto puede provocar una cocción despareja, con el exterior crujiente y el centro blando.","Voltee los panqueques UNA SOLA VEZ cuando los bordes estén dorados y haya varias burbujas en la superficie. Voltearlos con demasiada frecuencia puede hacer que se desinflen y que la textura del panqueque sea más densa.","Las sobras se conservan en el refrigerador de 2 a 3 días o congeladas hasta por 3 meses."],[]))
X.append(r(9380481,"Cena de garbanzos en una sola bandeja","Las verduras asadas y los garbanzos forman una combinación ganadora en esta fantástica cena en una sola bandeja.","4 porciones","1 porción",
["1.5 tazas de garbanzos (cocidos o enlatados (aprox. 1 lata de 15 onzas))","1 paquete de 8 onzas (227 g) de champiñones (partidos por la mitad)","1 pinta de tomates cherry (aprox. 2 tazas)","1 libra de papas amarillas pequeñas (partidas por la mitad (en cuartos si son más grandes))","1 calabacín (cortado a lo largo y en cuartos)","1 pimiento morrón rojo (cortado en trozos de 1 pulgada)","1/4 taza de jugo de limón","1/4 taza de caldo de verduras","1/2 cucharadita de ajo en polvo","1/2 cucharadita de cebolla en polvo","1/2 cucharadita de orégano","1/2 cucharadita de romero triturado","sal + pimienta (al gusto)"],
["Precaliente el horno a 425°F/218°C en la función de asado con convección y cubra una bandeja grande para hornear con papel pergamino.","Ponga todas las verduras picadas y los garbanzos en un tazón grande, luego agregue todos los ingredientes del adobo y mezcle bien.","Pase todo en una sola capa a la bandeja, pero no lo vierta de golpe desde el tazón. No conviene que quede demasiado exceso de adobo en la bandeja. Ase durante 20 minutos, retire la bandeja del horno y voltee todo. Luego ase otros 10 minutos, o hasta alcanzar el punto de cocción deseado.","Sirva tal cual, o con arroz, o en tortillas de harina enrolladas."],[],[]))
X.append(r(9388632,"Ensalada de pimientos morrones asados","Ahumada, dulce e irresistiblemente vibrante: esta ensalada de pimientos morrones asados es un platillo sencillo pero atrevido que trae color y sabor a la mesa.","4 porciones","1 porción",
["4 pimientos rojos asados en rebanadas finas","1.5 tazas de garbanzos (aprox. 1 lata de 15 onzas)","⅓ taza de cebolla morada picada en cubos","1 pinta (12 onzas) de tomates cherry heirloom partidos por la mitad",
("Para el aderezo","2 cucharadas de aquafaba o aceite de oliva"),("Para el aderezo","¼ taza de jugo de limón (aprox. 1 limón mediano)"),("Para el aderezo","2 dientes de ajo picados"),("Para el aderezo","2 cucharadas de albahaca fresca picada"),("Para el aderezo","1 cucharadita de orégano seco"),("Para el aderezo","¼ cucharadita de hojuelas de pimiento rojo, opcional"),("Para el aderezo","sal + pimienta al gusto")],
["Ponga los pimientos en rebanadas, los garbanzos, la cebolla y los tomates cherry partidos por la mitad en un tazón.","Luego, en un tazón pequeño o frasco, combine todos los ingredientes del aderezo.","Mezcle la ensalada con el aderezo hasta que quede cubierta de manera uniforme, y sirva."],
["Si no tiene pimientos rojos asados a la mano, hornee o ase (broil) pimientos morrones rojos en el horno hasta que estén suaves y la piel se haya ennegrecido. Luego pele la piel cuando estén lo suficientemente fríos para hacerlo y corte los pimientos en rebanadas muy finas.","Las sobras se conservan en el refrigerador de 2 a 3 días en un recipiente hermético."],[]))
X.append(r(9388968,"Muffins veganos de frambuesa [sin aceite]","¡Estos muffins veganos de frambuesa logran un equilibrio perfecto entre dulzor y acidez, con una humedad increíble y un sabor irresistible!","12 muffins","1 porción",
["1 taza de leche de soya","2 cucharaditas de jugo de limón o vinagre de sidra de manzana","1 cucharada de ralladura de limón (de aprox. 1 limón grande)","⅓ taza de puré de manzana sin azúcar","270 gramos de harina de avena (aprox. 3 tazas, con cuchara y nivelada)","½ taza de azúcar de coco sin refinar o azúcar morena","2 cucharaditas de polvo para hornear","½ cucharadita de bicarbonato de sodio","1.5 tazas de frambuesas frescas",("Glaseado opcional","½ taza de azúcar glas"),("Glaseado opcional","2 cucharaditas de jugo de limón")],
["Precaliente el horno a 375℉/190℃ y tome un molde para muffins con capacidad para 12 muffins. Si no tiene un molde antiadherente, use capacillos de papel o engrase los moldes.",
"Combine la leche de soya y el jugo de limón en un tazón grande y reserve durante 5 minutos para que espese y se cuaje. (Esto hace un suero de leche vegano.)",
"Luego agregue la ralladura de limón y el puré de manzana al tazón de la leche cuajada y mezcle.",
"A continuación, agregue la harina, el azúcar, el polvo para hornear y el bicarbonato. Mezcle hasta integrar, sin mezclar en exceso. Luego incorpore suavemente las frambuesas con movimientos envolventes.",
"Divida la masa entre los 12 moldes para muffins y hornee de 20 a 22 minutos, hasta que un palillo insertado en el centro salga limpio. Retire del horno y deje enfriar al menos 20 minutos antes de pasarlos con cuidado a una rejilla de enfriamiento. Los muffins son delicados, así que deje que se enfríen antes de pasarlos.",
"Si usa el glaseado opcional, mezcle el azúcar y el jugo de limón en un tazón pequeño. Una vez que los muffins estén completamente fríos, rocíelos con el glaseado y déjelos reposar unos minutos para que el azúcar se endurezca, y disfrute."],
["¡Pese la harina con una báscula de cocina para obtener los resultados más precisos! Sacar la harina de la bolsa con la taza la compacta y podría significar que se usa demasiada harina, lo que podría dar como resultado un muffin más denso.","Use polvo para hornear FRESCO + ACTIVO. El polvo para hornear que lleva abierto en la despensa más de 6 meses puede perder su efectividad.","Deje que los muffins se enfríen en el molde durante al menos 20 minutos antes de pasarlos a una rejilla de enfriamiento. Estos muffins son delicados cuando están tibios, así que deles tiempo para enfriarse y evitar que se rompan.","Si usa el glaseado opcional, asegúrese de que los muffins estén completamente fríos primero y glaséelos justo antes de servir. Guardar los muffins glaseados en un recipiente sellado hará que el glaseado se derrita.","Los muffins se conservan en un recipiente sellado a temperatura ambiente de 2 a 3 días, refrigerados hasta por 1 semana o congelados hasta por 3 meses. Inspirados en mis Muffins de limón y arándanos azules."],[]))
X.append(r(9389046,"Sopa de betabel asado con eneldo [sin aceite]","La sopa de betabel asado es hermosa y acogedora con su color rojo magníficamente vibrante. Es naturalmente dulce, con un toque ácido de limón y eneldo. Perfectamente cremosa, deliciosa y satisfactoria.","4 porciones","1 porción",
["1.5 libras de betabeles (remolachas) (aprox. 8-10 betabeles pequeños/medianos)","1 cucharada de mantequilla vegana (omita y saltee en agua o caldo para que sea sin aceite)","1 cebolla amarilla picada en cubos","1 zanahoria grande pelada + picada en cubos","1 tallo de apio picado en cubos","2.5 tazas de caldo de verduras bajo en sodio","3 cucharadas de eneldo fresco o 2 cucharaditas de eneldo seco","½ cucharadita de sal marina","3 cucharadas de jugo de limón (aprox. 1 limón mediano)",("Guarniciones opcionales","crema de anacardo"),("Guarniciones opcionales","más eneldo fresco")],
["Precaliente el horno a 425℉/218℃ en la función de asado con convección. Si no tiene un horno con convección o una función de asado, simplemente use la función de hornear, dejando un poco más de tiempo para que los betabeles queden tiernos.",
"Frote/lave los betabeles y corte los extremos. Si sus betabeles son grandes, córtelos por la mitad para que se cocinen más rápido; de lo contrario, déjelos enteros. Con papel aluminio, haga bolsitas para contener los betabeles y colóquelas en una bandeja para hornear. Doble hacia arriba los lados del papel aluminio para evitar que el tinte rojo de los betabeles se esparza y ensucie. (Consulte las fotos del proceso arriba, si es necesario.) Espolvoree los betabeles con sal y pimienta y ase hasta que estén tiernos al pincharlos con un tenedor. Esto tardará de 30 a 60 minutos, según qué tan frescos (los betabeles más frescos se cocinan más rápido) y qué tan grandes sean.",
"Mientras se asan los betabeles, derrita la mantequilla (si la usa) en una sartén y agregue la cebolla, la zanahoria y el apio picados. Saltee hasta que estén suaves, unos 5-7 minutos. Luego reserve.",
"Retire los betabeles del horno y déjelos enfriar ligeramente, justo lo suficiente para poder manipularlos. Luego pele los betabeles (la piel se desprenderá fácilmente una vez asados) y colóquelos en la licuadora. Agregue las verduras salteadas y TODOS los demás ingredientes a la licuadora y procese hasta que quede suave. Trabaje en tandas, si es necesario.",
"Sirva con crema de anacardo y más eneldo fresco si lo desea. ¡Disfrute!"],
["Para ahorrar tiempo, ase y pele los betabeles 1-2 días antes. Luego, cuando quiera preparar la sopa, saltee las demás verduras y licúe.","Deje la piel a los betabeles al asarlos. Es más fácil pelarlos después de asarlos. (Use guantes al pelar para evitar que los dedos queden rojos.)","Para que sea sin aceite, simplemente omita la mantequilla y saltee en agua o caldo.","Las sobras se conservan en el refrigerador hasta por 4 días o congeladas en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9389346,"Estofado de verduras estilo pay en olla de cocción lenta","Una versión con menos calorías y menos carbohidratos de su pay de verduras favorito. Este estofado ofrece los mismos grandes sabores pero en una versión sin gluten para olla de cocción lenta.","6 porciones","1 porción",
["1 cebolla amarilla finamente picada","6 zanahorias peladas y en cubos","2 libras de papas amarillas peladas y cortadas en cubos de media pulgada","1 taza de maíz congelado","1 taza de chícharos (guisantes) congelados","4 tazas de caldo de verduras bajo en sodio","½ cucharadita de sal marina o al gusto","1 cucharadita de ajo en polvo","½ cucharadita de salvia seca","½ cucharadita de tomillo seco","4 cucharadas de agua","4 cucharadas de maicena","½ taza de leche de anacardo sin azúcar o la leche de su preferencia"],
[("Instrucciones para olla de cocción lenta","Ponga todos los ingredientes, excepto el agua, la maicena y la leche, en su olla de cocción lenta. Cocine a temperatura baja durante 8 horas."),
("Instrucciones para olla de cocción lenta","Cambie la olla de cocción lenta a temperatura alta. Luego, en un tazón pequeño o frasco, combine el agua y la maicena y mezcle bien. Agregue esta mezcla a la olla de cocción lenta y cocine a temperatura alta durante 30 minutos. Esto espesará el estofado."),
("Instrucciones para olla de cocción lenta","Apague la olla de cocción lenta, incorpore la leche y sirva."),
("Instrucciones para Instant Pot","Ponga todos los ingredientes, excepto el agua, la maicena y la leche, en la olla y cocine a alta presión durante 6 minutos."),
("Instrucciones para Instant Pot","Mientras tanto, bata el agua y la maicena en un tazón pequeño y reserve."),
("Instrucciones para Instant Pot","Cuando termine el temporizador, libere rápidamente la válvula de vapor y abra la tapa cuando sea seguro hacerlo. Cambie la olla a la función de saltear y vierta la mezcla de maicena en la olla y saltee durante 5 minutos, revolviendo con frecuencia. Luego apague la olla, incorpore la leche y disfrute.")],
["La maicena es necesaria para espesar el caldo. Si no puede consumir maicena, puede sustituirla por harina de trigo todo uso o harina de arroz integral al doble de la cantidad. (Es decir, 8 cucharadas de harina y agua para la mezcla.) Las ollas de cocción lenta varían mucho, así que si ve que las verduras no están lo bastante suaves después de varias horas de cocción a temperatura baja, cambie el aparato a temperatura alta durante el tiempo de cocción restante. Para agregar proteína, añada frijoles blancos enlatados o lentejas hacia el final de la cocción. O puede usar tofu sedoso licuado para reemplazar la leche. Para hacer este platillo aún más rico (aunque esto aumentará el contenido de grasa), use leche de coco enlatada (light para menos grasa) para reemplazar la leche de anacardo al final de la cocción. Las sobras se conservan refrigeradas hasta por 4 días, o congeladas hasta por 3 meses. Puede sustituir las papas por camotes (batatas), o hacer una mezcla mitad y mitad, si lo prefiere."],[]))
X.append(r(9390900,"Coliflor vegana agridulce","¡Esta coliflor vegana agridulce es dulce, pegajosa y tan increíblemente deliciosa!","4 porciones","1 porción",
[("Para la coliflor","4 tazas de floretes de coliflor (aprox. 1 cabeza pequeña cortada en trozos del tamaño de un bocado)"),("Para la coliflor","½ taza de harina de arroz integral"),("Para la coliflor","1 cucharadita de ajo en polvo"),("Para la coliflor","1 cucharadita de cebolla en polvo"),("Para la coliflor","½ cucharadita de sal marina, opcional"),("Para la coliflor","½ taza de agua"),
("Para la salsa vegana agridulce","½ taza de miel de maple"),("Para la salsa vegana agridulce","¼ taza de vinagre de arroz"),("Para la salsa vegana agridulce","¼ taza de tamari bajo en sodio o salsa de soya si no evita el gluten"),("Para la salsa vegana agridulce","¼ taza de salsa de tomate (kétchup)"),("Para la salsa vegana agridulce","1 cucharadita de ajo en polvo"),("Para la salsa vegana agridulce","1 cucharada de harina de arroz integral, opcional, para espesar la salsa"),("Para la salsa vegana agridulce","1 pimiento morrón rojo en rodajas"),("Para la salsa vegana agridulce","1 taza de piña cortada en cubos"),
("Para servir","arroz integral o quinoa"),("Para servir","cebollita verde"),("Para servir","semillas de ajonjolí")],
["Precaliente el horno a 425 grados F (218 grados C) y cubra una bandeja para hornear con papel pergamino.",
"Corte la coliflor en trozos pequeños, del tamaño de un bocado, y reserve. Luego ponga los demás ingredientes de la coliflor en un tazón mediano y bata para integrar, para hacer el rebozado. Ponga los trozos de coliflor en el rebozado y mezcle bien para cubrirlos de manera uniforme.",
"Acomode la coliflor rebozada en la bandeja en una sola capa, pero no la vierta toda de golpe desde el tazón. No conviene que quede exceso de rebozado en la bandeja o puede pegarse y evitar que quede crujiente.",
"Hornee de 20 a 25 minutos, volteándola una vez a la mitad del tiempo, hasta lograr la textura crujiente deseada.",
"Mientras se hornea la coliflor, prepare la salsa agridulce. Bata todos los ingredientes de la salsa (excepto el pimiento y la piña) en un tazón pequeño o taza medidora y reserve.",
"Luego saltee el pimiento rojo y los trozos de piña en una sartén grande con una cucharada de agua o caldo, para evitar que se peguen. Hágalo a fuego medio-alto hasta que se doren ligeramente. Luego reduzca el fuego a medio-bajo, vierta la salsa en la sartén y cocine a fuego lento hasta que espese ligeramente, aprox. 5 minutos.",
"Para entonces, la coliflor ya debería estar lista. Agréguela a la sartén con la salsa y mezcle suavemente para cubrir cada pieza de manera uniforme.",
"Sirva sobre arroz o quinoa y decore con semillas de ajonjolí y cebollita verde."],
["No vierta la coliflor sobre la bandeja para hornear una vez cubierta con el rebozado. No conviene que quede exceso de rebozado en la bandeja, o se pegará a la bandeja y los trozos pueden pegarse entre sí, lo que reduce su exterior crujiente. Tómese el tiempo para colocar la coliflor rebozada en una sola capa, un trozo a la vez, con mucho espacio entre ellos para obtener los mejores resultados. Sabe mejor recién hecha, pero las sobras se conservan refrigeradas en un recipiente sellado de 3 a 4 días."],[]))
X.append(r(9391250,"Ensalada de garbanzos y aguacate","¡Una ensalada fresca y vibrante de garbanzos y aguacate, rica, sabrosa y sorprendentemente saciante! Lista en solo 15 minutos.","3 porciones","1 porción",
["1.5 tazas de garbanzos cocidos o enlatados (aprox. 1 lata de 15 onzas)","1 aguacate mediano en cubos","1 tomate mediano cortado en trozos del tamaño de un bocado","¼ taza de cebolla morada picada en cubos","2-3 cucharadas de albahaca fresca finamente picada, opcional","1 cucharadita de orégano seco","½ cucharadita de sal marina o al gusto","¼ cucharadita de ajo en polvo","2 cucharadas de aquafaba"],
["Si usa garbanzos enlatados, escúrralos, pero reserve dos cucharadas de la aquafaba (el líquido de los garbanzos). Si usa garbanzos cocidos, reserve el líquido de cocción.","Pique los ingredientes y póngalos en un tazón mediano. Para el aguacate, córtelo por la mitad, quite el hueso y use un cuchillo para cortar la pulpa en cuadros, directamente en la cáscara. Luego sáquela con una cuchara y póngala en el tazón.","Revuelva suavemente para combinar y distribuir los sabores de manera uniforme. Disfrute de inmediato."],
["Si usa garbanzos enlatados, use los que no tienen sal, o disminuya la sal indicada en la receta y ajuste al gusto. Si usa garbanzos cocidos, reserve el líquido de cocción para esta ensalada y para comidas futuras. Yo cocino mis garbanzos sin sal y congelo la aquafaba/líquido de cocción en charolas para cubos de hielo para uso futuro. Una vez congelados, pase los cubos de aquafaba a un recipiente o bolsa con cierre y manténgalos congelados hasta que los necesite. Esta ensalada sabe mejor el mismo día en que se prepara. Si planea prepararla antes de servir, exprima jugo de limón sobre el aguacate para evitar que se oscurezca."],[]))
X.append(r(9396324,"Panqueques de plátano con trigo sarraceno","Panqueques de plátano (banana) con trigo sarraceno, esponjosos e increíblemente deliciosos, con solo 6 ingredientes.","8 panqueques de 4 pulgadas","1 porción",
["⅓ taza de plátano (banana) machacado (aprox. 1 plátano mediano)","1 taza de leche sin lácteos","2 cucharaditas de extracto puro de vainilla","120 gramos de harina de trigo sarraceno (aprox. 1 taza)","1 cucharadita de polvo para hornear","½ cucharadita de canela"],
["Machaque el plátano en un tazón mediano y luego agregue la leche y la vainilla. Mezcle bien. Luego agregue todos los ingredientes secos y revuelva hasta integrar, pero no se preocupe si todavía quedan algunos grumos.","Deje reposar la masa de los panqueques de 2 a 3 minutos mientras precalienta la plancha o sartén antiadherente a fuego medio.","Vierta la masa con un cucharón para hacer panqueques de aprox. 3-4 pulgadas de diámetro y cocine hasta que haya burbujas en la superficie y los bordes se vean dorados. Luego voltee y continúe cocinando otros 2-3 minutos.","Sirva con rodajas de plátano, frutos rojos, miel de maple y/o coco rallado."],
["Use polvo para hornear fresco y activo. El polvo para hornear que se ha abierto y lleva varios meses en la despensa puede comenzar a perder su efectividad.","No es necesario mezclar en exceso la masa de los panqueques. Si quedan algunos grumos, está perfectamente bien. Solo mezcle hasta integrar y que no queden grumos de harina.","Precaliente la sartén o la plancha. Debe estar caliente antes de verter la masa para evitar que se pegue y para una cocción uniforme.","Use fuego medio para cocinar los panqueques. Aunque la sartén debe estar caliente, eso no significa que deba usar fuego alto. Esto puede provocar una cocción despareja, con el exterior crujiente y el centro blando.","Voltee los panqueques UNA SOLA VEZ. Cuando los bordes estén dorados y haya varias burbujas en la superficie. Voltearlos con demasiada frecuencia puede hacer que se desinflen y dar como resultado una textura de panqueque más densa.","Las sobras se conservan en el refrigerador de 2 a 3 días; recaliente en la tostadora, en una plancha o en una sartén en la estufa. O congele en recipientes herméticos o bolsas con cierre una vez que se hayan enfriado por completo a temperatura ambiente."],[]))
X.append(r(9396581,"Palitos veganos de pan francés (french toast)","¡No se necesitan huevos para estos palitos veganos de pan francés (french toast) increíblemente deliciosos! Solo licúe, sumerja y cocine.","8 porciones","1 porción",
["8 rebanadas de pan resistente y grueso del día anterior (me gusta el pan francés o de masa madre, pero cualquiera que sea resistente y un poco denso)","13.5 onzas (400 ml) de leche de coco light, de la que viene en lata","1 bloque de 12 onzas (350 gramos) de tofu extra firme","2-3 cucharadas de miel de maple o jarabe de dátil","2 cucharaditas de extracto puro de vainilla","½ cucharadita de canela molida",("Coberturas opcionales","arándanos azules, fresas, frambuesas frescos o plátanos en rodajas"),("Coberturas opcionales","mantequilla de almendra"),("Coberturas opcionales","miel de maple"),("Coberturas opcionales","azúcar glas")],
["Corte el pan en tiras de aprox. una pulgada de grosor y reserve.","Ponga todos los demás ingredientes (todo excepto el pan) en la licuadora y procese hasta que quede suave.","Vierta la mezcla en un tazón ancho y poco profundo, trabajando en tandas si es necesario. Luego sumerja varios de sus palitos de pan por todos los lados, dejando que absorban la mezcla durante 30-60 segundos.","Caliente una plancha antiadherente, sartén grande o sartén de hierro fundido bien curada a fuego medio. Engrase primero si es necesario. Luego cocine los palitos de pan francés de 2 a 3 minutos por cada lado, trabajando en tantas tandas como sea necesario, según el tamaño de su plancha o sartén.","Sirva con un poco de azúcar glas espolvoreada, frutos rojos frescos, miel de maple, o disfrútelos tal cual."],
["Use pan que sea resistente y más denso que el pan de caja normal para sándwich y corte los palitos en piezas de una pulgada de grosor. No conviene que queden demasiado delgados o pueden romperse después de remojarse en la mezcla. Haga lo posible por cortar los palitos de pan francés en piezas de tamaño similar para una cocción uniforme. Asegúrese de precalentar la sartén o plancha antes de cocinar el pan francés. Si no la precalienta, la mezcla puede caerse y quedar pegada a la sartén. Para que sea bajo en grasa, puede usar cualquier leche sin lácteos, como leche de almendra o de soya, en lugar de la de coco. La receta funcionará muy bien, pero no quedará tan rica. Para que sea sin gluten, use su pan sin gluten favorito."],[]))
X.append(r(9397040,"Piña en freidora de aire","¡Piña en freidora de aire dulce y acaramelada! Un postre o acompañamiento más saludable, absolutamente perfecto, que querrá devorar.","4 porciones","1 porción",
["2 tazas colmadas de piña en rebanadas (de aprox. ½ piña pequeña)","1 cucharada de mantequilla vegana o margarina derretida, opcional","2 cucharadas de miel de maple","1 cucharadita de canela",("Dip opcional de chile y lima","3 cucharadas de crema de anacardo o mayonesa vegana"),("Dip opcional de chile y lima","1 cucharada de jugo de lima (aprox. media lima)"),("Dip opcional de chile y lima","½ cucharadita de chile en polvo")],
["Pele, quite el centro y corte en rebanadas la piña y coloque aproximadamente 2 tazas colmadas en un tazón.","Combine la mantequilla derretida, la miel de maple y la canela en un tazón pequeño, luego viértala sobre las rebanadas de piña. Mezcle suavemente para cubrir las rebanadas de manera uniforme.","Luego colóquelas en una sola capa (si se encimen ligeramente no hay problema) en la canasta de la freidora y cocine en la freidora de aire a 380 grados F durante 12-15 minutos, o hasta que estén acarameladas. Voltee la piña una vez a la mitad del tiempo.","Disfrute tibia o fría, como acompañamiento o postre.",
("Dip opcional","Si prepara el dip de chile y lima, combine los 3 ingredientes en un tazón pequeño mientras se cocina la piña.")],
["No vierta las rebanadas de piña en la canasta de la freidora de golpe. En su lugar, colóquelas una a la vez con una cuchara para evitar que se rompan y para evitar que el exceso de líquido gotee debajo de la canasta y eche humo. Las sobras se conservan refrigeradas en un recipiente sellado de 2 a 3 días."],[]))
X.append(r(9401943,"Cómo preparar queso parmesano vegano","¡Solo un puñado de ingredientes para el mejor queso parmesano vegano! Es salado, con sabor a queso y perfecto para espolvorear sobre todo.","12 porciones (rinde aprox. 1 taza)","2 cdas.",
["½ taza de anacardos (nueces de la India) crudos o piñones, o almendras sin piel","3 cucharadas de levadura nutricional","½ cucharadita de sal marina","⅛ cucharadita de ajo en polvo, opcional"],
["Ponga todos los ingredientes en un procesador de alimentos y procese hasta obtener una harina fina.","Guarde en un recipiente hermético o frasco en el refrigerador y sirva espolvoreado sobre sus platillos favoritos."],
["Asegúrese de que su frasco o recipiente esté completamente limpio y SECO para evitar que se eche a perder por la humedad al guardar su parmesano vegano. Guárdelo en el refrigerador para conservar la frescura. No use hierbas frescas ni especias. Esto evitará que su «queso» se conserve fresco y se echará a perder más pronto. Si no tiene anacardos, lo he preparado con éxito con almendras sin piel y piñones, con resultados similares. Para que sea sin frutos secos, puede usar semillas de girasol crudas o semillas de calabaza/pepitas para reemplazar los anacardos, con resultados similares. Si no tiene levadura nutricional, puede usar una mezcla de polvo de hongos, cebolla en polvo, albahaca en polvo y más ajo en polvo. Tenga en cuenta que esto reducirá el sabor a queso, pero aun así aportará un delicioso sabor umami. Para que sea bajo en sodio, simplemente reduzca la sal a la mitad, o sale a su gusto. Yo lo he mantenido refrigerado hasta por 4 semanas, pero estoy segura de que duraría incluso más que eso."],[]))
save(4,X)
