import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes1')
from h import *
X=[]
X.append(r(9405296,"Pasta aglio e olio (pasta con ajo y aceite)","La pasta aglio e olio es un platillo clásico italiano de pasta que usa ajo salteado y chiles picantes para ofrecer un sabor intenso con mucho carácter.","6 porciones","1 porción",
["1 libra de penne o la pasta de su elección","1 brócoli grande cortado en floretes","¼ taza de aceite de oliva extra virgen","4 dientes de ajo picados","6-8 chiles secos o al gusto","¼ taza del agua de cocción de la pasta reservada"],
["Hierva una olla grande con agua con abundante sal y agregue la pasta, cocinándola según las instrucciones del paquete para obtener pasta al dente. Agregue el brócoli a la olla cuando falten 8 minutos para que se cocine la pasta, para que el brócoli no se cocine de más. *Vea las notas* Escurra la pasta y el brócoli una vez cocidos, reservando 1/4 taza del agua de la pasta.","Mientras tanto, ponga el aceite de oliva, el ajo y los chiles en una sartén grande y saltee a fuego medio hasta que los chiles y el ajo estén ligeramente dorados, aprox. 5 minutos. Agregue a la sartén el agua de pasta reservada, la pasta y el brócoli. Saltee todo junto, mezclando constantemente durante 1-2 minutos.","Sirva con más hojuelas de chile o queso parmesano vegano si lo desea."],
["Si su pasta necesita 13 minutos para cocerse, agregue la pasta al agua hirviendo y cocine durante 5 minutos, luego agregue el brócoli para que se cocine los 8 minutos restantes."],[]))
X.append(r(9406639,"Galletas veganas de fresa","Las galletas veganas de fresa, suaves y masticables, son el postre perfecto para una botana sin culpa.","30 galletas","1 porción",
["1 taza de plátano (banana) machacado (aprox. 3 plátanos medianos)","2 tazas de avena en hojuelas","½ taza de tahini u otra mantequilla de frutos secos o semillas","¼ taza de azúcar de coco sin refinar","1 cucharada de extracto puro de vainilla","¼ taza de fresas picadas en cubos","¼ taza de chispas de chocolate vegano, opcional"],
["Precaliente el horno a 350℉/176℃ y cubra dos bandejas para galletas con papel pergamino.","Machaque los plátanos en un tazón grande. Luego agregue la avena, el tahini, el azúcar y la vainilla, y mezcle bien.","Incorpore con movimientos envolventes las fresas y las chispas de chocolate si las usa.","Ponga porciones de la mezcla en la bandeja forrada para hacer aproximadamente 30 galletas. Luego presione cada bolita de masa para darles forma, ya que no se extenderán mucho en el horno.","Hornee las galletas de 8 a 10 minutos y luego retírelas del horno y déjelas reposar de 5 a 10 minutos antes de pasarlas a una rejilla de enfriamiento."],
["Use plátanos muy maduros. Mientras más maduros estén, más sabor, dulzor y humedad aportarán a sus galletas. Los plátanos con cáscara marrón funcionan mejor.","Mida el plátano machacado para asegurarse de que está usando una taza. El tamaño de los plátanos varía mucho. Dos plátanos grandes o tres medianos me funcionan.","No hornee de más las galletas, o quedarán secas. Parecerán poco cocidas, pero recuerde que se endurecen más al enfriarse.","Deje que las galletas se enfríen de 5 a 10 minutos antes de pasarlas a una rejilla de enfriamiento.","Guarde las galletas a temperatura ambiente de 1 a 2 días, refrigeradas de 4 a 5 días, o congeladas hasta por 3 meses."],[]))
X.append(r(9406949,"Galletas saludables de garbanzo y mantequilla de cacahuate","¡Galletas de garbanzo suaves y esponjosas, perfectamente dulces y realmente SALUDABLES! ¡Este postre sin culpa es perfecto para el desayuno, la botana o el postre!","30 galletas","1 galleta",
["1 lata de 13.5 onzas de garbanzos escurridos y enjuagados","2 plátanos (bananas) grandes muy maduros","½ taza de mantequilla de cacahuate (maní) cremosa, casera o comprada (o sustituya por mantequilla de soya para que sea sin frutos secos)","2 cucharadas de miel de maple, opcional","1 cucharadita de polvo para hornear","2 cucharadas de aceite de coco o puré de manzana","¾ taza de avena cortada de cocción rápida o avena en hojuelas","1 cucharadita de extracto puro de vainilla, opcional"],
["Precaliente el horno a 350 grados F y cubra una bandeja grande para hornear con papel pergamino.","Ponga todos los ingredientes en el procesador de alimentos y procese hasta que quede suave.","Con una cucharadita de metal, ponga porciones de la mezcla sobre la bandeja preparada y forme las galletas.","Hornee de 18 a 22 minutos, o hasta que estén ligeramente doradas alrededor de los bordes. Deje que las galletas se enfríen por completo para que se endurezcan antes de servir."],
["Use mantequilla de cacahuate hecha solo con cacahuates y sin grasa ni azúcar añadidas. Algunas marcas «naturales» no se elaboran solo con cacahuates, así que siempre lea los ingredientes. O, por supuesto, puede prepararla usted mismo. Yo uso una lata de 13.5 oz. Si su lata es más grande y desea usarla toda para no desperdiciar, puede hacerlo. Sin embargo, necesitará un poco de líquido adicional para compensar. Agregue otras 1-2 cucharadas de aceite de coco o de puré de manzana sin azúcar a la mezcla. Para que sea sin aceite, sustituya el aceite de coco por puré de manzana sin azúcar. La receta original lleva aceite de coco, pero desde entonces la he probado (muchas veces) con puré de manzana y ahora, de hecho, las prefiero así. Para que sea sin frutos secos, sustituya la mantequilla de cacahuate por mantequilla de girasol o tahini. Si no tiene miel de maple pura pero aun así desea agregar un poco más de dulzor, use jarabe de agave, o también funciona la miel de abeja, si no es vegano. Si lo desea, puede agregar ¼-1/3 taza de chispas de chocolate, pasas, frutos secos picados o coco rallado. Elija uno y no se exceda, o la masa no se mantendrá tan bien. Si desea galletas uniformes, use un cucharón para galletas. Yo uso un cucharón pequeño para galletas, que equivale a 2 cucharaditas. Las galletas de garbanzo se conservan tapadas a temperatura ambiente de 2 a 3 días, refrigeradas de 5 a 6 días, o congeladas hasta por 2 meses en un recipiente hermético."],[]))
X.append(r(9410019,"Pico de gallo de piña","Una versión divertida de la salsa le trae este pico de gallo de piña dulce y picante. Es refrescante y dulce, con solo 6 ingredientes.","4 porciones","1 porción",
["1.5 tazas de piña picada en cubos","2 tazas de tomate picado en cubos (aprox. 2 tomates medianos)","½ taza de cebolla blanca picada en cubos","⅓ taza de cilantro picado","1-2 chiles jalapeños o serranos finamente picados","1 cucharada de jugo de lima (aprox. media lima grande)","⅛ cucharadita de sal marina o al gusto, opcional"],
["Pique en cubos y corte todos los ingredientes y póngalos en un tazón. Luego exprima el jugo fresco de lima encima y mezcle bien para distribuirlo de manera uniforme.","Pruebe y agregue 1/8 cucharadita de sal, si es necesario, o sale a su gusto. Mezcle bien y refrigere durante 1 hora o sirva de inmediato."],
["Para que sea menos picante, quite las semillas y las membranas del chile antes de picarlo. Use guantes al manipular chiles picantes y asegúrese de lavarse bien las manos al terminar. ¡Evite tocarse los ojos y la cara! Deje reposar el pico de gallo en el refrigerador durante 1 hora antes de servir para dar tiempo a que los sabores se mezclen bien."],[]))
X.append(r(9412428,"Salsa de mango y habanero","La salsa de mango y habanero es la mezcla PERFECTA de dulce y picante. ¡Deliciosa y totalmente adictiva con solo 7 ingredientes!","6 porciones","1 porción",
["1 ¾ tazas de mango picado en cubos (de aprox. 1 mango grande y maduro)","1.5 tazas de tomate picado en cubos (de aprox. 2 tomates roma)","½ taza de cebolla morada picada en cubos","1 chile habanero muy finamente picado","½ taza de cilantro fresco picado (ligeramente compactado, sin los tallos gruesos)","2 cucharadas de jugo de lima (aprox. 1 lima grande)","½ cucharadita de sal marina o al gusto"],
["Si tiene un procesador de alimentos pequeño, le recomiendo mucho usarlo para picar finamente el chile habanero. Esto reduce al mínimo el contacto del chile con las manos. Quite el tallo y corte el chile por la mitad. Luego procese.","Si no tiene un procesador pequeño, puede cortarlo a mano. Sin embargo, recomiendo usar guantes al manipular chiles picantes, si es posible. Asegúrese de lavarse bien las manos después de picar.","Ponga todos los ingredientes picados, el jugo de lima y la sal en un tazón mediano y mezcle bien para distribuir los sabores de manera uniforme. Sirva de inmediato o refrigere durante 1 hora para enfriar."],
["Si usa mango congelado, asegúrese de descongelarlo por completo primero. Para que sea menos picante, quite las semillas del chile habanero o use chile jalapeño en su lugar. Use guantes al manipular chiles picantes, si es posible, y asegúrese de lavarse bien las manos al terminar. Evite tocarse la cara. Si no tiene guantes, intente usar una hoja de plástico adherente alrededor de las manos."],[]))
X.append(r(9413497,"Risotto de arroz integral con verduras en Instant Pot","¡Un soñado risotto de arroz integral en Instant Pot que usted y su familia amarán!","6 porciones","1 porción",
["1.5 tazas de arroz basmati integral enjuagado","4 tazas de verduras mixtas congeladas (yo uso una mezcla de maíz/chícharos/zanahoria/ejotes)","4 tazas de caldo de verduras bajo en sodio","1 cucharadita de cebolla en polvo","1 cucharadita de ajo en polvo","¼ cucharadita de orégano seco","1 cucharada de mantequilla vegana o margarina, opcional","sal + pimienta al gusto",("Guarniciones (opcional)","perejil fresco"),("Guarniciones (opcional)","queso parmesano vegano")],
["Ponga todo, excepto la mantequilla, en su olla de presión y revuelva. Cierre la tapa y asegúrese de que la válvula esté en la posición de sellado. Luego programe a alta presión durante 22 minutos. La olla tardará unos 15-20 minutos en alcanzar la presión.","Cuando termine el temporizador, deje que la olla de presión libere la presión de forma natural durante 10 minutos. Después de 10 minutos, libere rápidamente la presión restante colocando la válvula en la posición de ventilación y abra la tapa cuando sea seguro hacerlo.","Incorpore la mantequilla si la usa, pruebe y agregue sal y pimienta si es necesario. Sirva decorado con perejil fresco y/o queso parmesano."],
["Dese el tiempo suficiente. Aunque el tiempo de cocción está programado a 22 minutos, tardará otros 15-20 minutos en alcanzar la presión y luego 10 minutos de liberación natural. Las sobras se conservan refrigeradas en un recipiente sellado de 3 a 4 días. Recaliente en la estufa o use la función de saltear de su Instant Pot."],[]))
X.append(r(9416487,"Queso crema vegano de tofu [sin aceite]","Un queso crema vegano de tofu espeso y cremoso, perfecto para untar y mojar. Es sabroso, lleno de sabor y delicioso.","20 porciones de 2 cucharadas","2 cucharadas",
["16 onzas de tofu firme, sin OGM si es posible","¼ taza de anacardos (nueces de la India) crudos o almendras sin piel o semillas de girasol","2 cucharadas de pasta de miso","1.5 cucharadas de jugo de limón","1.5 cucharadas de vinagre de sidra de manzana","¼ cucharadita de sal marina",("Sabores opcionales","½ cucharadita de cebolla en polvo"),("Sabores opcionales","½ cucharadita de ajo en polvo"),("Sabores opcionales","½ cucharadita de eneldo seco")],
["Ponga todo en el tazón de un procesador de alimentos y procese hasta que quede suave, raspando los lados según sea necesario.","Refrigere durante una hora o más para enfriar y espesar."],
["Asegúrese de escurrir y secar con palmaditas el tofu para evitar exceso de líquido en su queso crema de tofu. Se busca una pasta espesa que realmente se parezca al producto real. Use un procesador de alimentos en lugar de una licuadora. Será más difícil licuar de manera suave en una licuadora debido a los pocos ingredientes líquidos. Además, es más difícil sacar las pastas espesas de una licuadora, donde hay menos espacio entre las cuchillas. Refrigere al menos una hora antes de usar. Esto ayudará a que se firme y espese. Almacenamiento: Refrigere su queso crema de tofu en un recipiente sellado o frasco de vidrio de 5 a 7 días.","Para conservarlo por más tiempo, sepárelo en porciones más pequeñas y congele todas menos una en recipientes herméticos aptos para congelador hasta por 3 meses. Mantenga 1 en el refrigerador para uso inmediato. Descongele las porciones restantes según las necesite."],[]))
X.append(r(9419746,"Chips de betabel en freidora de aire [sin aceite]","¡Chips de betabel en freidora de aire crujientes y deliciosos, con una textura crocante satisfactoria!","2 porciones","1 porción",
["½ libra de betabeles (remolachas) rojos (aprox. 2 betabeles medianos)","½ cucharada de aquafaba, opcional","¼ cucharadita de sal marina"],
["Frote los betabeles y corte los extremos con un cuchillo afilado. No es necesario pelarlos. Luego use una mandolina para cortar los betabeles en rebanadas muy finas para hacer chips. Deben quedar delgados como papel para obtener los mejores resultados.","Coloque los betabeles en rebanadas en un tazón y mézclelos con la aquafaba y la sal. Luego acomódelos en una sola capa (si se encimen ligeramente no hay problema) en la canasta de la freidora de aire, trabajando en tandas si es necesario.","Cocine los chips de betabel en la freidora de aire a 350°F/176°C durante 10-12 minutos, agitando o mezclando a la mitad del tiempo. Los chips están listos cuando se han enroscado hacia arriba, se han encogido considerablemente y se sienten secos al tacto. Retírelos de la canasta y déjelos reposar a temperatura ambiente. Se pondrán más crujientes al enfriarse."],
["Las rebanadas de betabel pueden encimarse ligeramente porque se encogerán considerablemente, pero no las apile ni las encime demasiado o no quedarán tan crujientes. El grosor de sus chips de betabel determinará el tiempo de cocción y el nivel de textura crujiente. Corte los betabeles lo más delgados posible, o use una herramienta, como una mandolina, para cortarlos fácilmente. Los chips están listos cuando sus bordes se han enroscado y las rebanadas se sienten secas al tacto. No cocine de más los chips de betabel o tendrán un sabor amargo. Se pondrán un poco más crujientes después de retirar la canasta de la freidora de aire y dejar enfriar los chips."],[]))
X.append(r(9419806,"Galletas de betabel [galletas veganas red velvet]","Estas deliciosas galletas de betabel son una versión saludable de las galletas red velvet. Son suaves, masticables y de color natural gracias al betabel dulce y terroso, en lugar de colorante.","22 galletas","1 porción",
[("Ingredientes húmedos","1.5 tazas de betabel (remolacha) picado en cubos (usé una lata de 400 ml)"),("Ingredientes húmedos","⅓ taza de azúcar de caña"),("Ingredientes húmedos","2 cucharaditas de extracto puro de vainilla"),("Ingredientes húmedos","1 cucharadita de vinagre de sidra de manzana"),
("Ingredientes secos","150 gramos de harina de avena (aprox. 1.5 tazas)"),("Ingredientes secos","3 cucharadas de cacao en polvo crudo sin azúcar"),("Ingredientes secos","2 cucharaditas de polvo para hornear"),("Ingredientes secos","½ cucharadita de bicarbonato de sodio"),
("Opcional","½ taza de chispas de chocolate blanco vegano")],
["Precaliente el horno a 350℉/176℃ y cubra una bandeja grande para hornear con papel pergamino.","Ponga los ingredientes húmedos en la licuadora y procese hasta que quede suave. Luego vierta en un tazón.","Agregue los ingredientes secos al mismo tazón y revuelva hasta integrar. Luego incorpore con movimientos envolventes las chispas de chocolate, si las usa.","Use un cucharón para galletas para colocar la masa sobre la bandeja forrada con papel pergamino, dejando espacio entre cada galleta para que se extiendan.","Hornee las galletas de betabel de 10 a 12 minutos, hasta que estén ligeramente firmes al tacto. Luego retírelas del horno y déjelas enfriar durante 10 minutos antes de manipularlas."],
["Pese la harina para obtener los resultados más precisos. Si no tiene una báscula de cocina, ponga la harina con una cuchara en la taza medidora y use un cuchillo para raspar el exceso, con resultados similares. ¡No la saque directamente de la bolsa!","Si usa betabel enlatado, asegúrese de que no sea encurtido. Use betabel enlatado solo en agua, sin vinagre ni aceite, ya que eso alteraría el sabor.","Use polvo para hornear fresco y activo. El polvo para hornear que lleva abierto en la despensa más de 6 meses puede perder su efectividad.","Deje que las galletas se enfríen en la bandeja durante al menos 10 minutos antes de manipularlas. Son delicadas y necesitan tiempo para asentarse antes de pasarlas a una rejilla de enfriamiento.","Las sobras se conservan a temperatura ambiente de 1 a 2 días, hasta 5 días en el refrigerador, o hasta 3 meses congeladas."],[]))
X.append(r(9421240,"Papas caseras fritas en freidora de aire [opción sin aceite]","Las papas caseras crujientes y deliciosas en freidora de aire son comida reconfortante en su máxima expresión. ¡Más saludables que las fritas en aceite, con una opción sin aceite!","3 porciones","1 porción",
["1 lb de papas amarillas peladas y cortadas en trozos de media pulgada","⅓ taza de cebolla amarilla picada en cubos gruesos (aprox. la mitad de una cebolla pequeña)","½ taza de pimiento rojo picado en cubos gruesos (aprox. la mitad de un pimiento mediano)","¾ cucharadita de sal marina","¼ cucharadita de pimienta negra","½ cucharadita de pimentón","½ cucharadita de ajo en polvo","2 cucharadas de aceite de aguacate u otro aceite de cocina, opcional",("Guarniciones opcionales","cebollín, perejil o más sal, si es necesario")],
["Pele y corte las papas en trozos de aproximadamente media pulgada y póngalas en un tazón grande. Cúbralas con agua fría y déjelas remojar durante 20 minutos. Luego escúrralas, enjuáguelas con agua fría y colóquelas sobre un paño de cocina limpio y seco y séquelas con palmaditas. Seque el tazón y regrese las papas al tazón.","Ahora agregue todos los demás ingredientes al mismo tazón y mezcle bien para cubrir de manera uniforme.","Colóquelas en la canasta y cocine en la freidora de aire a 400°F/204°C durante 15-20 minutos, hasta que estén cocidas y logren la textura crujiente deseada. Sacuda la canasta o revuelva las papas cada 5 minutos para una cocción uniforme."],
["Para obtener mejores resultados, tómese el tiempo de remojar y enjuagar las papas antes de cocinarlas. Esto le dará las papas caseras más crujientes en freidora de aire. Corte las papas lo más parejas posible para una cocción uniforme. Los cubos de media pulgada funcionan bien para una cocción rápida y quedarán muy crujientes. No pique la cebolla y el pimiento demasiado pequeños o se quemarán y podrían caer por los orificios de su canasta. Si no desea trozos más grandes, agréguelos solo cuando las papas lleven aproximadamente la mitad de la cocción. Las freidoras de aire varían en potencia, así que siempre revise las papas mientras se cocinan. Yo uso una Ninja Foodi de 8 qt y las mías quedan perfectas a los 20 minutos. Los modelos más pequeños pueden cocinar más rápido. Juegue con el sazón para agregar sabor. Las he mantenido sencillas, pero si desea cambiar los sabores, puede sustituir el pimentón por pimentón ahumado y/o agregar un poco de cebolla en polvo, chile en polvo, comino o pimienta de cayena. Saben mejor recién hechas, pero las sobras se conservan en el refrigerador de 3 a 4 días en un recipiente sellado. Recaliente en la canasta de la freidora de aire o en un horno tostador."],[]))
X.append(r(9421474,"Crema de chocolate de garbanzo [Nutella sin frutos secos]","Una crema de chocolate de garbanzo (también conocida como Nutella sin frutos secos) cremosa, rica, achocolatada y deliciosa.","12 porciones (aprox. 2 cucharadas por porción/total aprox. 1.5 tazas)","1 porción",
["1 lata de 15 onzas de garbanzos escurridos + enjuagados","3 cucharadas de cacao en polvo crudo sin azúcar","4 cucharadas de miel de maple","2 cucharaditas de extracto puro de vainilla","¼ cucharadita de sal marina","1-2 cucharadas de agua si desea una consistencia más fluida"],
["Ponga todo, excepto el agua, en el tazón del procesador de alimentos y procese hasta integrar. Deténgase para raspar los lados del tazón según sea necesario y continúe procesando hasta que quede suave.","Si desea una consistencia más fluida, agregue 1-2 cucharadas de agua.","Pase su Nutella sin frutos secos a un frasco de vidrio limpio y seco o a un recipiente hermético."],
["No olvide raspar los lados del tazón del procesador de alimentos durante el procesado. Esto asegurará una textura suave. Agregue una cucharada de agua a la vez si es necesario para la textura y/o una consistencia más fluida.","Guarde su crema de chocolate de garbanzo en un recipiente o frasco de vidrio sellado en el refrigerador hasta por 1 semana. Congélela hasta por 3 meses."],[]))
X.append(r(9422406,"Batido sin plátano","Aquí tiene una receta de batido sabroso, con frutos rojos y lleno de proteína, sin plátano. Es delicioso, se puede ajustar fácilmente a su gusto y es 100% saludable.","2 porciones (rinde aprox. 4 tazas)","1 porción",
["1 ¼ taza de leche de anacardo sin azúcar o la leche vegetal de su preferencia","1 taza de arándanos azules congelados","1 taza de fresas congeladas","1 taza de piña congelada","⅓ taza de nueces pecanas, nueces de Castilla o almendras","2 cucharadas de jugo de lima recién exprimido (aprox. 1 lima pequeña)","1 cucharada de semillas de cáñamo peladas, opcional"],
["Ponga todos los ingredientes en la licuadora y procese a velocidad alta hasta que quede suave. ¡Disfrute!"],
["Licuar fruta congelada funciona mejor con una licuadora de alta velocidad. Si no tiene una licuadora de alta velocidad, es posible que necesite un poco más de líquido para que todo se mueva. Comience con la cantidad indicada y agregue más según sea necesario. Si sustituye alguna de las frutas congeladas por fruta fresca, disminuya un poco el líquido al principio y agregue más, si es necesario. Agregue un puñado de cubos de hielo si usa principalmente fruta fresca. Un batido sin plátano no quedará tan espeso si usa solo opciones de fruta fresca. Siéntase libre de sustituir cualquiera de las frutas congeladas según lo que tenga en su congelador. Mango, frambuesas, cerezas o frutos rojos mixtos funcionan bien. Si no tiene nueces pecanas, puede usar nueces de Castilla, anacardos, almendras o nueces de macadamia. También puede sustituir los frutos secos crudos por mantequilla de frutos secos. Pruebe 2 cucharadas de mantequilla de cacahuate, mantequilla de almendra, mantequilla de nuez pecana o cualquiera de sus mantequillas de frutos secos favoritas. Para más dulzor, agregue 2-3 dátiles sin hueso o 1-2 cucharaditas de miel de maple."],[]))
X.append(r(9422469,"Galletas de harina de almendra y mantequilla de cacahuate [sin gluten]","Con bordes crujientes y centros húmedos, estas galletas de harina de almendra y mantequilla de cacahuate están repletas de sabor. ¡Solo se necesitan 6 ingredientes y 20 minutos!","16 galletas","1 porción",
["½ taza de mantequilla de cacahuate (maní) natural, cremosa o con trozos (sin sal)","4 cucharadas de miel de maple","2 cucharaditas de vainilla","150 gramos de harina de almendra (aprox. 1.5 tazas)","½ cucharadita de bicarbonato de sodio","¼ cucharadita de sal marina"],
["Precaliente el horno a 350 grados F y cubra una bandeja para galletas con papel pergamino.","En un tazón mediano, ponga la mantequilla de cacahuate, la miel de maple y la vainilla, y mezcle bien. Use un tenedor o una espátula de silicón para asegurarse de que los ingredientes estén bien combinados.","En otro tazón pequeño, bata juntos la harina de almendra, el bicarbonato de sodio y la sal. Luego agregue los ingredientes secos al tazón de los húmedos. Mezcle bien. La masa quedará pegajosa y espesa, pero siga mezclando hasta integrar.","Divida la mezcla en 16 bolitas de masa y colóquelas en la bandeja. Luego, con un tenedor ligeramente húmedo, presione cada bolita para formar un patrón entrecruzado en la parte superior de cada galleta.","Hornee durante 10 minutos, luego retire del horno y deje enfriar 10 minutos y no toque las galletas durante este tiempo. Después de los 10 minutos de reposo, pase las galletas a una rejilla de enfriamiento otros 5-10 minutos. Este período de enfriamiento es crucial para que las galletas se asienten por completo y para que los bordes queden bien crujientes."],
["Use la medida en peso de la harina siempre que sea posible. Esto garantizará los resultados más precisos. Si DEBE usar medidas por volumen, asegúrese de poner la harina de almendra con una cuchara y nivelarla. No la saque directamente con la taza medidora o podría terminar con demasiada harina. Si tiene dificultades para mezclar la masa con una cuchara o espátula, use las manos para ayudar a incorporar los ingredientes. La masa quedará ligeramente pegajosa y espesa. Divida la masa como se muestra en la foto 7 de arriba si le importa que las galletas tengan aproximadamente el mismo tamaño. Estas casi no se extienden, así que asegúrese de darles forma al tamaño y grosor que desee antes de hornear. Al hacer el patrón entrecruzado, moje el tenedor con agua antes de presionar la masa. Esto ayudará a evitar que el tenedor se pegue. Sumerja el tenedor en un poco de agua después de cada pocas galletas. No hornee de más las galletas. Sí, se sentirán suaves e incluso podrían verse poco cocidas, pero así es exactamente como deben estar. ¡Asegúrese de dejar enfriar las galletas! No las toque mientras están en el horno ni durante al menos 10 minutos después de sacarlas del horno. Cuando pasen los 10 minutos, páselas con mucho cuidado a una rejilla de enfriamiento para que sigan enfriándose. Este tiempo adicional es crucial para que las galletas tengan los bordes crujientes. Como mínimo, déjelas 5 minutos en la rejilla de enfriamiento, pero 10 es mejor."],[]))
X.append(r(9425725,"Hash browns caseros en freidora de aire [opción sin aceite]","¿Listo para los hash browns más crujientes y crocantes? Hechos desde cero en su freidora de aire con solo 3 ingredientes para las MEJORES tortitas de papa hash brown de la historia.","2 porciones","1 porción",
["1 lb de papas amarillas (aprox. 2 papas medianas)","1.5 cucharadas de aceite de aguacate o el aceite de cocina de su elección *vea las notas para la opción sin aceite","½ cucharadita de sal marina","½ cucharadita de cebolla en polvo, opcional"],
["Llene un tazón grande con agua fría y pele las papas. (O frótelas si desea dejarles la cáscara.)","Luego, con un rallador de caja, ralle las papas en el tazón con agua. Revuelva rápidamente y déjelas reposar 20 minutos. Ahora escurra en un colador y enjuague muy bien con agua fría.","Pase las papas ralladas a un paño de cocina limpio o a toallas de papel y exprímalas o presiónelas para secarlas. Deben quedar lo más secas posible para obtener los hash browns más crujientes.","Ahora regrese las papas al mismo tazón (séquelo primero) y agregue el aceite (si lo usa) y los condimentos. Mezcle bien.","Engrase o rocíe la canasta (si es necesario) y coloque dentro las papas sazonadas. Use una espátula de silicón para extender y presionar las tiras de papa en una capa uniforme y cocine a 370 grados durante 12-18 minutos, hasta que estén doradas. ¡No es necesario voltearlas! ¡Disfrute!"],
["No omita el remojo. Remojar las papas en agua fría ayuda a eliminar el almidón, lo que dará como resultado papas más crujientes. Así que asegúrese de remojar durante 20 minutos y también de enjuagarlas después. ¡Séquelas muy bien! Nuevamente, para obtener la máxima textura crujiente, asegúrese de que las tiras de papa estén bien secas. Use un paño de cocina limpio para exprimir el líquido. Extienda las papas en una capa uniforme para que se doren de manera pareja. Las zonas más gruesas pueden no quedar tan crujientes. Estoy usando una Ninja Foodi de 8 qt y mi hash brown queda crujiente a los 18-20 minutos. Si usa una canasta de freidora de aire más pequeña, puede cocinar más rápido. Comience a revisar alrededor de los 10-15 minutos y cocine hasta lograr la textura crujiente deseada. Para freidoras de aire más pequeñas, es posible que deba trabajar en dos tandas. Para hash browns picantes, agregue ¼ cucharadita de pimienta de cayena. Para hash browns ahumados, agregue ½ cucharadita de pimentón ahumado. *Si evita el aceite y usa una freidora de aire antiadherente, esta receta también funciona sin el aceite. La probé en mi Ninja Foodi y no se pega. Use una espátula de silicón para separar suavemente los bordes y se desprenderá con facilidad. Tenga en cuenta que quedará un poco menos crujiente de esta manera. Esta receta es naturalmente vegana, sin gluten, sin soya, sin frutos secos y libre de todos los alérgenos comunes. ***EDICIÓN 28 de feb. de 2021 – Se redujo la temperatura de 400 grados a 370 grados F. Algunos usuarios notaron que se cocinaba demasiado rápido. Esto variará según el modelo de su freidora. Si ya la ha preparado antes a 400 grados sin problemas, puede seguir haciéndolo."],[]))
X.append(r(9426064,"Cupcakes veganos saludables de chocolate","Los cupcakes veganos de chocolate más saludables que existen, ¡pero son simplemente increíbles!","12 cupcakes","1 porción",
[("Ingredientes húmedos","6 cucharadas de puré de camote (batata) (de aprox. 1 camote mediano de pulpa naranja, asado)"),("Ingredientes húmedos","¾ taza de leche de almendra u otra leche vegetal"),("Ingredientes húmedos","½ taza de miel de maple"),
("Ingredientes secos","150 gramos de harina de almendra blanqueada (aprox. 1.5 tazas)"),("Ingredientes secos","130 gramos de harina de avena (aprox. 1.5 tazas)"),("Ingredientes secos","⅓ taza de cacao en polvo crudo sin azúcar"),("Ingredientes secos","2.5 cucharaditas de polvo para hornear"),("Ingredientes secos","¼ cucharadita de sal marina"),
("Para el glaseado","1 taza de frijoles negros cocidos o enlatados"),("Para el glaseado","2 cucharadas de cacao en polvo crudo sin azúcar"),("Para el glaseado","¼ taza de miel de maple")],
[("Antes de comenzar","Para preparar el camote: Precaliente el horno a 425°F/218°C. Luego frote bien el camote para limpiarlo, colóquelo en una bandeja para hornear y áselo aprox. 35-45 minutos, o hasta que se pueda atravesar fácilmente con un tenedor. O, si tiene una freidora de aire, puede cocinarlo en ella con este método para ahorrar tiempo. Reserve."),
("Para los cupcakes","Precaliente el horno a 350°F/176°C y forre un molde para muffins con capacillos de papel pergamino."),
("Para los cupcakes","Pele el camote o saque la pulpa y macháquela en un plato. Luego mida seis cucharadas (no más) para usar en la masa y colóquelas en un tazón grande. Agregue la leche y la miel de maple al mismo tazón y bata para integrar."),
("Para los cupcakes","A continuación, agregue todos los ingredientes secos al mismo tazón y revuelva hasta integrar."),
("Para los cupcakes","Divida la masa entre los 12 moldes para muffins y hornee de 20 a 22 minutos, o hasta que un palillo insertado en el centro salga limpio. Reserve para que se enfríen por completo antes de glasearlos."),
("Para el glaseado","Ponga todos los ingredientes del glaseado en una licuadora de alta velocidad o procesador de alimentos y licúe hasta que quede suave. Una vez que los cupcakes se hayan enfriado, use una manga pastelera para glasearlos y disfrute.")],
["Pese la harina para obtener los resultados más precisos. Le recomiendo encarecidamente que no dependa de las medidas en tazas al hornear. Si no tiene una báscula de cocina, puede poner la harina con una cuchara en la taza medidora y usar un cuchillo para raspar el exceso, con resultados similares. ¡No la saque directamente de la bolsa! Use polvo para hornear fresco y activo. El polvo para hornear que lleva abierto en la despensa más de 6 meses puede comenzar a perder su efectividad. Si es posible, ase el camote un día antes, o varias horas antes de hornear los cupcakes. Deje que los cupcakes se enfríen en el molde para muffins durante al menos 10 minutos antes de manipularlos. Luego páselos a una rejilla de enfriamiento para que se enfríen por completo ANTES de glasearlos. Saben mejor los días 1-2, pero puede guardar las sobras en el refrigerador hasta por 4 días. Guárdelos en un recipiente sellado para conservar la humedad. O congele los cupcakes sin glasear en un recipiente hermético apto para congelador hasta por 3 meses. Recomiendo preparar el glaseado fresco antes de servir."],[]))
save(5,X)
