import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/tes1')
from h import *
X=[]
X.append(r(9477520,"Sopa de pimiento rojo asado y tomate","¡Una sopa de pimiento rojo asado y tomate increíblemente sabrosa! Es cremosa, fresca, reconfortante y totalmente aromática.","4 porciones","1 porción",
["3 pimientos morrones rojos en cuartos","1 libra de tomates madurados en la planta o tomates ciruela en cuartos (aprox. 5-7 tomates ciruela)","1 cebolla amarilla en cuartos","4 dientes de ajo grandes SIN PELAR","1 cucharada de aceite de aguacate, opcional, *para que sea sin aceite, omita y use caldo en su lugar","½ cucharadita de perejil seco","½ cucharadita de albahaca seca","3 tazas de caldo de verduras bajo en sodio","¼ taza de anacardos (nueces de la India) crudos","sal + pimienta al gusto",("Guarniciones opcionales","albahaca o perejil fresco"),("Guarniciones opcionales","crutones")],
["Precaliente el horno a 425 grados F en la función de horneado con convección y cubra una bandeja grande para hornear con papel pergamino. Acomode las verduras en una sola capa, rocíe con el aceite (si lo usa) y espolvoree con el perejil y la albahaca.","Ase las verduras de 30 a 40 minutos, o hasta que la piel de los pimientos se haya ennegrecido un poco, luego retire del horno. Pele los pimientos una vez que estén lo suficientemente fríos para tocarlos. (La piel se desprenderá con facilidad, pero si hay algún trozo difícil, déjelo.)","Pele el ajo (saldrá con mucha facilidad una vez asado) y colóquelo en la licuadora, junto con TODOS los demás ingredientes, excepto las guarniciones. Licúe hasta que quede suave, pruebe para ver si necesita sal y pimienta y ajuste si es necesario.","Sirva decorada con albahaca fresca, crutones, galletas saladas o pimienta negra."],
["Para que sea sin aceite, rocíe las verduras con caldo en su lugar, pero asegúrese de revisarlas con frecuencia y agregar más agua o caldo si es necesario. No pele el ajo antes de asarlo o podría quemarse. La cáscara se desprenderá con mucha facilidad una vez asado. Use tomates frescos y maduros para obtener los mejores resultados. Los enlatados o en frasco no funcionarán bien aquí. Asegúrese de que la piel de los pimientos esté bien ennegrecida para que se desprenda con facilidad. Puede colocarlos en un tazón con un paño de cocina encima para que se suden después de asarlos, si tiene dificultad para pelarlos. Licúe la sopa un par de minutos adicionales si tiene una licuadora de alta velocidad para calentarla más, si las verduras se han enfriado. Si no tiene una licuadora de alta velocidad, remoje los anacardos en agua hirviendo durante 20-30 minutos y luego escúrralos antes de agregarlos a la licuadora. (Puede hacerlo mientras se asan las verduras.) Las sobras se conservan refrigeradas hasta por 4 días, o congeladas en un recipiente hermético apto para congelador hasta por 3 meses."],[]))
X.append(r(9479544,"Puré de papa en Instant Pot sin escurrir","¡No hay nada más fácil que esto! El puré de papa en Instant Pot está listo en un abrir y cerrar de ojos, sin necesidad de escurrir. Cocine y haga puré, todo en 1 olla para obtener papas perfectas, ¡SIEMPRE!","6 porciones","1 porción",
["3 libras de papas Yukon Gold o papas amarillas","1 taza de caldo de verduras bajo en sodio","⅓ taza de leche de soya o la de su elección","1 cucharadita de sal marina","½ cucharadita de ajo en polvo, opcional","1-2 cucharadas de mantequilla vegana o margarina, opcional",("Guarniciones opcionales","cebollín fresco"),("Guarniciones opcionales","romero fresco"),("Guarniciones opcionales","mantequilla derretida"),("Guarniciones opcionales","salsa gravy de cebolla")],
["Pele las papas y córtelas en trozos de una pulgada. Colóquelas en la olla con el caldo y cierre la tapa, colocando la válvula en la posición de sellado. Programe a alta presión durante 6 minutos. (Tardará unos 10 minutos en alcanzar la presión, y luego el temporizador comenzará la cuenta regresiva.) Cuando termine el temporizador, libere la presión rápidamente y abra la tapa cuando sea seguro hacerlo.","Agregue la leche, la sal y cualquier ingrediente opcional. Luego haga puré con un prensapapas hasta que quede suave y cremoso. Pruebe y agregue más sal, si es necesario, y sirva caliente."],
["*Esta receta, tal como está escrita, es para un modelo de Instant Pot de 6 qt. Si usa un modelo de 8 qt, aumente el caldo a 1.5 tazas. Si duplica las papas, NO es necesario duplicar el caldo. Solo duplique las papas y deje el caldo en 1 taza o 1.5 tazas, según el tamaño de su modelo. Para el mejor puré de papa sin escurrir, ¡pese las papas! Esto dará los mejores resultados, ya que pueden variar mucho de tamaño. Si no tiene una báscula de cocina y necesita calcularlo a ojo, use 10 papas Yukon Gold de tamaño promedio para obtener aproximadamente 3 lb. Haga lo posible por cortar los trozos de tamaño similar. Para una cocción uniforme, no conviene que algunos trozos sean demasiado grandes u otros demasiado pequeños. ¡No machaque demasiado las papas! Una vez que estén suaves, estará listo. Procesarlas o machacarlas en exceso puede dar una textura pegajosa, ¡y nadie quiere eso! Hágalo extra cremoso. Agregue una cucharada de crema de anacardo o queso crema vegano al puré de papa y revuelva para obtener más cremosidad. Las sobras se conservan refrigeradas de 3 a 4 días o congeladas, en un recipiente hermético, hasta por 3 meses."],[]))
X.append(r(9480093,"Pan socca sin aceite (pan plano de garbanzo)","El pan plano socca es esponjoso, sabroso y versátil. Úselo como panqueques, pan pita, masa de pizza o córtelo en triángulos y sumérjalo en su dip favorito.","2 panes planos de 7\"","1 porción",
["1 taza de harina de garbanzo (yo muelo garbanzos crudos en mi Vitamix)","1 taza de agua","¼ cucharadita de cebolla en polvo (omita para panqueques)","¼ cucharadita de ajo en polvo (omita para panqueques)","½ cucharadita de sal marina (omita para panqueques)",
("Coberturas opcionales para pizza de socca","pesto casero"),("Coberturas opcionales para pizza de socca","tomate picado en cubos"),("Coberturas opcionales para pizza de socca","pimiento picado en cubos"),("Coberturas opcionales para pizza de socca","cebollita verde en rodajas"),("Coberturas opcionales para pizza de socca","queso parmesano vegano"),
("Coberturas opcionales para panqueques de socca","miel de maple"),("Coberturas opcionales para panqueques de socca","frutos rojos frescos"),("Coberturas opcionales para panqueques de socca","mermelada de arándanos azules y chía"),("Coberturas opcionales para panqueques de socca","mantequilla de almendra"),
("Dips opcionales para mojar","guacamole"),("Dips opcionales para mojar","dip de pepinillo al eneldo"),("Dips opcionales para mojar","crema de anacardo")],
["Combine la harina de garbanzo y los condimentos (si los usa; omita para panqueques) en un tazón. Luego agregue el agua y mezcle bien. Deje reposar la masa 5 minutos mientras calienta su plancha antiadherente.","Cuando su plancha esté caliente, vierta la mitad de la masa para cada pan plano. Obtendrá dos círculos de aproximadamente 6-7 pulgadas cada uno. Cocine de 4 a 5 minutos hasta que los bordes se vean cocidos y haya varias burbujas en la superficie. Voltee con cuidado, raspando primero alrededor de los bordes para asegurarse de que no esté pegado.","Cocine el otro lado otros 3-4 minutos, hasta que esté dorado y bien cocido. Pase a un plato o tabla para cortar y sirva como desee, según el método que esté usando."],
["Deje reposar la masa al menos 10 minutos antes de cocinar. Asegúrese de que su plancha esté muy caliente antes de verter la masa encima. Asegúrese también de que su plancha sea antiadherente; de lo contrario, es posible que necesite engrasarla. Una plancha más vieja y muy usada eventualmente perderá su capacidad antiadherente, así que use su propio criterio, ya que usted conoce mejor sus utensilios. En caso de duda, engrase las placas o haga una prueba con una pequeña cantidad de masa primero. Al voltear la socca, raspe primero alrededor de los bordes para asegurarse de que no esté pegada. Luego voltee. Siéntase libre de agregar más condimentos, como comino, chile en polvo o pimienta de cayena, para realzar el sabor si prepara una opción salada. Si prepara los panqueques de socca, omita todos los condimentos mencionados y puede usar una pizca de canela o nuez moscada en su lugar. Las coberturas y dips opcionales no están incluidos en la información nutricional."],[]))
X.append(r(9483756,"Batido de mango y espinacas [que no sabe a verde]","Esta sencilla receta de batido verde de mango y espinacas no «sabe» a verde. Está endulzado de manera natural, es absolutamente delicioso y está lleno de ingredientes «buenos para usted».","2 porciones (aprox. 4 tazas)","1 porción",
["1 plátano (banana) fresco","2 puñados grandes de espinacas baby","1 taza de trozos de mango congelado","1 taza de trozos de fresa congelados o fresas enteras","1 cucharada de mantequilla de cacahuate (maní) cremosa","1.5 tazas de leche de anacardo sin azúcar o la leche vegetal de su preferencia"],
["Ponga todos los ingredientes en la licuadora y procese hasta que quede suave y cremoso. Disfrute frío."],
["Puede sustituir el plátano fresco por congelado si no tiene fresco a la mano. Así tendrá un poco menos de sabor a plátano, pero aun así el dulzor que aporta. También puede necesitar un poco más de leche o algo de agua para que quede suave cuando use más ingredientes congelados. Para la leche, puede sustituirla por cualquier leche que tenga y prefiera. Hágalo apto para niños. Como comemos primero con los ojos, a los niños puede no gustarles beber un batido verde, así que diviértase con él y llámelo «batido Hulk» o «Tortuga Ninja» o lo que sea que les guste. 🙂 Para que sea sin cacahuate, sustituya la mantequilla de cacahuate por mantequilla de almendra u otra mantequilla de frutos secos de su elección. Para que sea completamente sin frutos secos, sustituya la mantequilla de cacahuate por mantequilla de girasol u otra mantequilla de semillas de su elección, y sustituya la leche de anacardo por leche de avena, de coco o de soya. ¡Use lo que tenga! Si no tiene espinacas, pero tiene col rizada (kale), pruebe con esa. O si tiene mango y fresas frescos, pero no congelados, ¡úselos! Haga suyo este batido de mango y espinacas. Solo recuerde aumentar o disminuir los líquidos según corresponda al ajustar la proporción de ingredientes frescos y congelados."],[]))
X.append(r(9484573,"Calabaza butternut en freidora de aire [¡de dos maneras!]","¡Dos maneras de prepararla, salada o dulce! De cualquier forma, quedará muy impresionado con esta calabaza butternut en freidora de aire. Ambas versiones son increíblemente deliciosas y sencillas de preparar.","4 porciones","1 porción",
[("Versión salada","2 lb de calabaza butternut (aprox. 4 tazas en cubos de media pulgada)"),("Versión salada","2 cucharadas de caldo de verduras bajo en sodio"),("Versión salada","½ cucharadita de sal marina"),("Versión salada","½ cucharadita de pimentón ahumado"),("Versión salada","½ cucharadita de ajo en polvo"),("Versión salada","½ cucharadita de chile en polvo"),("Versión salada","½ cucharadita de cebolla en polvo"),
("Versión dulce","2 lb de calabaza butternut (aprox. 4 tazas en cubos de media pulgada)"),("Versión dulce","2 cucharadas de miel de maple"),("Versión dulce","1 cucharadita de canela"),("Versión dulce","⅛ cucharadita de nuez moscada"),("Versión dulce","⅛ cucharadita de sal marina")],
["Pele y corte la calabaza butternut en cubos de media pulgada. Vea las fotos paso a paso arriba si es necesario.","Coloque los cubos en un tazón grande junto con todos los condimentos de la opción que esté preparando. Mezcle bien y colóquelos en la canasta de su freidora de aire en una capa uniforme.","Cocine a 400 grados F durante 15-20 minutos, según su modelo, y mezcle bien a la mitad del tiempo. La calabaza está lista cuando está tierna al pincharla con un tenedor y crujiente alrededor de los bordes."],
["Corte la calabaza lo más uniforme posible para una cocción pareja. Si deja algunos trozos demasiado grandes, terminará con algunos trozos más duros. No necesitan ser perfectos, pero trate de cortarlos de un tamaño lo más similar posible. Para una cocción más rápida, corte los trozos aún más pequeños que la media pulgada que recomiendo. Las freidoras de aire varían en potencia, así que comience a revisar alrededor de los 15 minutos. La calabaza está lista cuando está tierna al pincharla con un tenedor y los bordes están dorados y crujientes. Para ahorrar tiempo, puede comprar calabaza butternut ya cortada en cubos en su supermercado, pero de todos modos querrá cortarlos en cubos más pequeños. Las sobras se conservan refrigeradas de 3 a 4 días. Puede recalentar en la freidora de aire o usar un horno tostador. La información nutricional corresponde a ¼ de la versión salada. La versión dulce tiene 131 calorías por porción."],[]))
X.append(r(9490339,"Ensalada vegana de tacos","Si se le antoja algo fresco, satisfactorio y lleno de sabor, ¡esta ensalada vegana de tacos es su respuesta!","4 porciones","1 porción",
[("Para la «carne» de tacos","1 lata de 15 onzas de garbanzos escurridos + enjuagados"),("Para la «carne» de tacos","1 taza de nueces pecanas"),("Para la «carne» de tacos","3 cucharadas de salsa de soya baja en sodio o tamari si es sin gluten"),("Para la «carne» de tacos","1 cucharadita de comino molido"),("Para la «carne» de tacos","1 cucharadita de pimentón ahumado"),("Para la «carne» de tacos","1 cucharadita de chile en polvo"),("Para la «carne» de tacos","1 cucharadita de ajo en polvo"),
("Para la ensalada","5 tazas de lechuga iceberg picada"),("Para la ensalada","1 lata de 15 onzas de frijoles negros escurridos + enjuagados"),("Para la ensalada","1 taza de tomates cherry partidos por la mitad"),("Para la ensalada","½ taza de maíz, congelado y descongelado o enlatado"),("Para la ensalada","⅓ taza de cebolla morada picada en cubos"),
("Para el aderezo (elija 1 o más)","salsa"),("Para el aderezo (elija 1 o más)","crema fresca vegana"),("Para el aderezo (elija 1 o más)","guacamole"),("Para el aderezo (elija 1 o más)","crema agria vegana"),
("Coberturas opcionales","jalapeño, rebanadas de aguacate, cilantro fresco, totopos o tiras de tortilla")],
["Ponga todos los ingredientes de la «carne» de tacos en el procesador de alimentos y pulse hasta que estén picados, pero aún desmenuzados y con mucha textura. No procese en exceso. Pruebe para ver si necesita sal y pimienta, y agregue un poco si es necesario.","Pase la «carne» a un tazón grande y agregue todos los demás ingredientes de la ensalada al mismo tazón. Mezcle bien.","Elija un aderezo de las opciones indicadas arriba, o cualquier otro que prefiera. Si planea tener sobras, recomiendo servir el aderezo en cada tazón, en lugar de mezclarlo con la ensalada, para poder guardarlos por separado y evitar que se humedezca."],
["No procese en exceso la «carne» de tacos. No se busca que quede licuada, así que pulse hasta que esté desmenuzada y conserve mucha textura para obtener los mejores resultados.","Guarde la ensalada y el aderezo de su elección por separado para evitar que la ensalada se humedezca.","Las sobras se conservan en el refrigerador de 3 a 4 días. La información nutricional incluye la «carne» de tacos y los ingredientes de la ensalada sin el aderezo ni las coberturas opcionales adicionales. La información nutricional del aderezo variará según lo que elija. Encontrará esa información nutricional debajo de cada receta de aderezo."],[]))
X.append(r(9491703,"Bolitas de energía de matcha","Impulse su día con estas bolitas de energía de matcha verdes y sin horno.","20 bolitas","1 porción",
["1 taza de dátiles sin hueso, ligeramente compactados","1 taza de anacardos (nueces de la India) crudos","2 cucharadas de proteína en polvo de semillas de calabaza o la proteína en polvo de su elección o harina de almendra","1 cucharada de matcha en polvo","1 cucharadita de extracto puro de vainilla","2-4 cucharadas de agua",("Opcional","¼ taza de pistaches picados para rodar")],
["Ponga todo, excepto el agua, en el procesador de alimentos y pulse hasta que todo se desmenuce sin hacerse puré. Luego agregue 2 cucharadas de agua y pulse hasta integrar.","Toque la mezcla y, si está lo bastante pegajosa para formar bolitas, no agregue más agua. Si todavía se siente demasiado seca, agregue otra cucharadita a la vez hasta que pueda formar bolitas.","Forme con la mezcla pequeñas bolitas del tamaño de un bocado, aprox. 1 cucharada de masa por bolita. Debe obtener alrededor de 20 porciones.","Opcional: Pase algunas o todas las bolitas por la mezcla de pistaches triturados si lo desea.","Refrigere durante 1 hora o más y disfrute."],
["Si sus dátiles están muy secos, remójelos en agua caliente durante 10-15 minutos y luego escúrralos antes de agregarlos al procesador de alimentos. Esto ayudará a ablandarlos y a procesarlos con más facilidad.","No procese en exceso la mezcla. Estas bolitas de energía de matcha saben mejor con un poco de textura.","Use las manos ligeramente húmedas para dar forma a las bolitas y evitar que se peguen. La masa quedará pegajosa, lo cual es normal."],[]))
X.append(r(9492507,"Asado vegano con champiñones","Ultra carnoso y lleno de sabores umami gracias a los champiñones y la pasta de miso, el asado vegano definitivo que le hará agua la boca.","8 porciones","1 porción",
["1 taza de frijoles blancos cannellini","1 paquete de 227 gramos (8 onzas) de champiñones cremini o baby bella","¾ taza de caldo de verduras (use un caldo salado, de buena calidad y sabroso)","4 dientes de ajo pelados","1 cucharada de pasta de miso blanco","1 cucharada de tahini","¼ taza de levadura nutricional","2 cucharaditas de cebolla en polvo","1 cucharadita de salvia seca","1 cucharadita de tomillo seco","1 cucharadita de romero seco triturado","½ cucharadita de pimienta negra","280 gramos de gluten de trigo vital (aprox. 2 ¼ tazas)"],
["Ponga TODOS los ingredientes EXCEPTO el gluten de trigo vital en un procesador de alimentos y procese hasta que quede casi suave. Luego agregue el gluten de trigo vital, la mitad a la vez, y pulse hasta que esté casi integrado. (No tiene que ser perfecto.)","Pase la mezcla a una tabla para cortar limpia u otra superficie limpia. Luego amase la masa con las manos durante 2-3 minutos. Dele forma de rollo de aprox. 4 pulgadas de ancho y 8 pulgadas de largo.","Envuélvalo bien ajustado con papel pergamino y luego con papel aluminio y retuerza los extremos para asegurarlo. (Vea las fotos del proceso arriba como referencia.) Luego elija UN método de cocción de los siguientes.",
("Instrucciones para Instant Pot","Agregue una taza de agua al fondo de su Instant Pot y coloque la rejilla encima. Luego coloque el asado vegano envuelto sobre la rejilla. Cierre la tapa, asegúrese de que la válvula esté en la posición de sellado y programe en «vapor» (steam) durante 60 minutos. Deje que la olla libere la presión de forma natural y luego ábrala cuando sea seguro hacerlo. (Tardará aprox. 10-12 minutos en liberarse de forma natural.) Pase el asado a una tabla para cortar y DÉJELO REPOSAR 10 minutos antes de rebanar."),
("Instrucciones para hornear","Precaliente el horno a 375℉/190℃ y coloque el asado de seitán envuelto sobre una bandeja para hornear. Hornee en la rejilla central durante 45 minutos. Luego voltéelo y hornee otros 45 minutos. Retire del horno y DÉJELO REPOSAR 10 minutos antes de rebanar."),
("Instrucciones para cocinar al vapor","Hierva una olla grande con un par de pulgadas de agua y coloque dentro su canasta vaporera. Asegúrese de que la canasta no toque el agua. Una vez que hierva, reduzca el fuego para mantener un hervor suave/fuego lento, coloque dentro el asado vegano envuelto y ponga la tapa encima. Cocine al vapor durante 35 minutos, luego voltéelo y cocine al vapor otros 35-45 minutos. Revise el nivel de agua de vez en cuando y agregue agua caliente según sea necesario. Una vez cocido, pase su asado vegano a una tabla para cortar y DÉJELO REPOSAR 10 minutos antes de rebanar.")],
["Pese el gluten de trigo vital para obtener los resultados más precisos. Si debe medir con tazas, asegúrese de poner la harina con una cuchara y nivelarla. NO la saque directamente de la bolsa o terminará con más de la necesaria.","Asegúrese de usar un caldo muy sabroso y salado, ya que no se agrega otra sal. Si solo tiene caldo bajo en sodio a la mano, agregue ½-1 cucharadita de sal.","Para comprobar el punto de cocción: Despegue suavemente el papel aluminio; el asado de seitán debe verse liso. Presiónelo con el dedo o con pinzas para comprobar la firmeza. (¡Cuidado, estará MUY CALIENTE!) Debe sentirse firme pero ceder un poco a la presión. Seguirá endureciéndose al enfriarse.","Las sobras se conservan refrigeradas hasta por 5 días. O congele el asado vegano en un recipiente hermético apto para congelador hasta por 3 meses. Puede congelarlo entero o en rebanadas."],[]))
X.append(r(9497075,"Jugo de apio y piña","No hay nada como un jugo recién hecho, ¡y este jugo de apio y piña es FAN-tástico!","3 porciones (rinde aprox. 3.5 tazas)","1 porción",
["1 libra de piña (aprox. media piña mediana)","1 libra de apio (aprox. 4 tallos grandes)","1 manzana Granny Smith mediana en cuartos y sin semillas","½ pulgada de jengibre fresco"],
["Lave bien los productos y corte la piña en tiras o trozos. Los tallos de apio caben sin cortarlos. Luego corte la manzana en cuartos y quite las semillas.","Comience extrayendo el jugo de la piña PRIMERO y luego continúe con la manzana, el jengibre y el apio.","Revuelva rápidamente su jugo y disfrútelo de inmediato."],
["No use una licuadora. Una licuadora hará un batido, no jugo. Use un extractor de jugos masticador de alta calidad, como el Sana 727, para obtener los mejores resultados. Los extractores masticadores (o lentos) extraen el jugo lentamente y no agregan calor. El calor puede destruir nutrientes de sus productos, por lo que no obtendría el beneficio completo. Prepare la cantidad de jugo que planea consumir, no más. El jugo recién hecho sin conservadores no se conserva mucho tiempo y, para obtener los máximos beneficios para la salud, debe disfrutarse de inmediato. Para acelerar el tiempo de preparación del jugo, puede lavar y cortar los productos la noche anterior y refrigerarlos en un recipiente sellado. Luego, por la mañana, sus frutas y verduras estarán preparadas y listas para pasar por el extractor de jugos."],[]))
X.append(r(9498029,"Sopa picante de camote","¡Deliciosa, cremosa y realmente PICANTE! Esta sopa picante de camote es abundante y sabrosa, increíblemente reconfortante y perfecta para una cena de otoño (o de cualquier época).","6 porciones","1 porción",
["1 cebolla amarilla pelada y en cuartos","1 jalapeño","2 lbs de camotes (batatas) pelados y cortados en cubos de 1 pulgada (aprox. 4 camotes medianos, o 5 tazas en cubos)","1.5 lb de calabaza bellota (acorn) pelada y cortada en cubos de 1 pulgada (aprox. 1 calabaza pequeña o 3 tazas en cubos)","4 tazas de floretes de coliflor (aprox. 1 coliflor pequeña)","1 cucharadita de ajo en polvo","½ cucharadita de chile en polvo","¼ cucharadita de canela","¼ cucharadita de jengibre molido","6 tazas de caldo de verduras bajo en sodio","sal + pimienta al gusto",("Guarniciones opcionales","crema de anacardo"),("Guarniciones opcionales","cebollín o perejil")],
["Precaliente el horno a 450 grados F en la función de horneado con convección.","Acomode las verduras preparadas en una bandeja grande forrada con papel pergamino. Espolvoree generosamente con sal y pimienta. Luego hornee de 20 a 25 minutos, hasta que estén tiernas al pincharlas con un tenedor y doradas.","Corte el tallo del jalapeño y pase las verduras cocidas a una olla junto con el caldo y todos los condimentos. Haga puré con una licuadora de inmersión. O use una licuadora de vaso, trabajando en tandas para hacer puré la sopa.","Sirva decorada con crema de anacardo y hierbas frescas, si lo desea."],
["Para que sea menos picante, quite las semillas del jalapeño antes de licuarlo en su sopa. Pese los camotes y la calabaza para obtener mejores resultados. Como los camotes y la calabaza varían mucho de tamaño, el peso dará la consistencia más precisa. Si tiene una licuadora de inmersión, puede pasar las verduras asadas y los demás ingredientes a una olla y hacer puré la sopa en una sola tanda. Para licuar con una licuadora de vaso, trabaje en tantas tandas como sea necesario. (Yo pude hacerlo en dos tandas.) Solo asegúrese de reservar un poco de caldo para cada tanda, ya que su licuadora necesitará algo de líquido para hacer puré la sopa. Una vez que cada tanda esté hecha puré, pásela a una olla o recipiente lo bastante grande para toda su sopa y mezcle bien para distribuir los condimentos de manera uniforme. Para ahorrar tiempo de preparación, puede comprar calabaza y camote ya cortados en cubos en su supermercado. O puede prepararlo con anticipación pelando y cortando sus verduras hasta con 2 días de anticipación. Las sobras se conservan refrigeradas 3 días o puede congelarlas hasta por 3 meses."],[]))
X.append(r(9506425,"Salsa de betabel asado para pasta","Esta salsa vegana de betabel para pasta es un platillo vibrante y cremoso preparado con betabeles asados, ajo, cebolla y caldo de verduras, licuados hasta lograr una textura suave.","4 porciones","1 porción",
["3 tazas de betabel (remolacha) en cubos (aprox. 2 betabeles medianos)","1 cebolla amarilla en cuartos","4 dientes de ajo (¡déjeles la cáscara!)","1 taza de caldo de verduras","⅓ taza de anacardos (nueces de la India) crudos","1 cucharada de vinagre de vino blanco o 2-3 cucharadas de jugo de limón","2 cucharadas de levadura nutricional","sal + pimienta al gusto","250 gramos (½ libra) de espagueti o la pasta de su elección",("Para decorar (opcional)","cebollín fresco, albahaca fresca, tomillo fresco, menta fresca o las hierbas de su elección"),("Para decorar (opcional)","queso parmesano vegano"),("Para decorar (opcional)","ralladura de limón, hojuelas de pimiento rojo, aceite de oliva")],
["Precaliente el horno a 425℉/218℃ en la función de asado con convección y cubra una bandeja para hornear con papel pergamino. (Si no tiene un horno con convección, deje más tiempo para asar.)","Pele y corte los betabeles en cubos pequeños de media pulgada y acomódelos en una sola capa en la bandeja junto con la cebolla en cuartos y los dientes de ajo. Ase las verduras de 25 a 30 minutos, hasta que estén doradas y los betabeles estén tiernos al pincharlos con un tenedor.","Mientras tanto, hierva una olla grande con agua con abundante sal y cocine la pasta según las instrucciones del paquete para obtener pasta «al dente». Escúrrala PERO reserve aproximadamente 1/2 taza del agua de la pasta, y reserve. Regrese la pasta escurrida a la olla.","Para entonces, las verduras ya deberían estar listas, así que agréguelas a la licuadora con todos los demás ingredientes de la salsa y procese hasta que quede suave y cremosa. Si es necesario, agregue un poco del agua de pasta reservada para aligerar la salsa. Luego vierta la salsa en la olla con la pasta y revuelva hasta que quede cubierta de manera uniforme.","Sirva con las guarniciones de su elección."],
["Sale el agua de la pasta. Asegúrese de agregar suficiente sal a la olla de agua para obtener la mejor textura y sabor. Aquí hay una útil guía para ayudarle a salar el agua perfectamente cada vez.","Cocine la pasta al dente. ¡No la cocine de más! Al dente significa que la pasta aún está firme una vez cocida, lo que da una textura óptima en cada bocado. Para asegurarse de que la pasta no se cocine de más, comience a probarla unos minutos antes de que el paquete indique que estará lista. Debe estar tierna, pero aún firme.","Reserve un poco del agua de la pasta al escurrir la pasta cocida para aligerar la salsa si es necesario.","Si no tiene una licuadora potente de alta velocidad, remoje primero los anacardos en agua caliente durante 20 minutos, luego escúrralos y úselos según las indicaciones.","Las sobras se conservan en el refrigerador de 3 a 4 días. No recomiendo poner la pasta en el congelador, ya que altera su textura. Sin embargo, si prepara salsa extra, la salsa se puede congelar en un recipiente hermético hasta por 3 meses."],[]))
X.append(r(9508036,"Harina de arroz integral: ¡la alternativa perfecta sin gluten!","¡La harina de arroz integral es fácil de preparar en casa y es un excelente sustituto para una opción sin gluten! Además, es económica, con solo 1 ingrediente.","4 tazas","1 porción",
["La cantidad deseada de arroz integral (yo normalmente preparo unas 4 tazas a la vez)"],
["Ponga el arroz en su licuadora de alta potencia y procese a velocidad alta hasta lograr una consistencia de harina.","Úsela para reemplazar la harina de trigo en sus recetas favoritas."],
["Guarde la harina sobrante en un recipiente hermético en su despensa para usar según sea necesario. La información nutricional corresponde a aprox. ½ taza de harina."],[]))
X.append(r(9508489,"Panes veganos integrales para hamburguesa","¡Panes veganos saludables para hamburguesa hechos con harina de trigo integral, sin aceite, sin mantequilla, sin huevos y sin levadura!","6 panes","1 porción",
[("Ingredientes secos","270 gramos de harina de trigo integral (aprox. 2 + ¼ tazas (más un poco para espolvorear))"),("Ingredientes secos","2 cucharaditas de polvo para hornear"),("Ingredientes secos","¼ cucharadita de bicarbonato de sodio"),("Ingredientes secos","1 cucharadita de sal marina"),("Ingredientes secos","½ cucharadita de ajo en polvo, opcional"),
("Ingredientes húmedos","¼ taza de puré de manzana sin azúcar"),("Ingredientes húmedos","2 cucharadas de tahini"),("Ingredientes húmedos","⅔ taza de leche de soya sin azúcar o leche de almendra o la leche vegetal de su preferencia"),
("Barniz vegano opcional (en lugar de huevo) + cobertura","2 cucharadas de leche de soya sin azúcar o la leche vegetal de su preferencia"),("Barniz vegano opcional (en lugar de huevo) + cobertura","½ cucharadita de miel de maple"),("Barniz vegano opcional (en lugar de huevo) + cobertura","½ cucharada de semillas de ajonjolí"),("Barniz vegano opcional (en lugar de huevo) + cobertura","½ cucharada de semillas de amapola")],
["Precaliente el horno a 400 grados F y cubra una bandeja para hornear con papel pergamino.","Cierna todos los ingredientes secos en un tazón grande. Luego agregue los ingredientes húmedos al mismo tazón y revuelva hasta formar una bola de masa. Quedará un poco pegajosa.","Espolvoree un poco de harina sobre una tabla para cortar limpia o una encimera. Luego coloque encima la bola de masa y amase durante 30-45 segundos, espolvoreando más harina, según sea necesario. No amase en exceso.","Ahora divida la masa en 6 piezas iguales y dé a cada pieza forma de disco redondo y aplanado y colóquelas en la bandeja preparada.","OPCIONAL: Combine las 2 cucharadas de leche vegetal con la miel de maple en un tazón pequeño y barnice con una brocha cada uno de sus panes veganos para hamburguesa. Luego espolvoree los panes con las semillas.","Hornee en el horno precalentado de 22 a 25 minutos, hasta que estén dorados. Luego retire del horno, deje enfriar ligeramente y disfrute."],
["Pese la harina para obtener los resultados más precisos. Sacar la harina de la bolsa con tazas medidoras suele hacer que se use demasiada y produce resultados secos y densos. No amase en exceso la masa. Amasar en exceso puede dar resultados densos y chiclosos. Para un pan más suave, use harina de trigo integral blanca, también conocida como harina integral para repostería. O pruebe 50 por ciento de harina de trigo integral y 50 por ciento de harina blanca todo uso sin blanquear. Estos panes veganos para hamburguesa saben mejor el mismo día en que se preparan, pero puede mantenerlos a temperatura ambiente en una bolsa con cierre de 2 a 3 días. O congelarlos en un recipiente hermético hasta por 3 meses y descongelarlos según sea necesario."],[]))
X.append(r(9515780,"Macarrones veganos con queso y calabaza butternut [sin aceite]","¡Macarrones veganos con queso y calabaza butternut saludables, sabrosos y deliciosos!","6 porciones","1 porción",
["450 gramos de macarrones o pasta cavatappi o la de su elección, sin gluten si lo prefiere",
("Para la salsa","2 libras de calabaza butternut pelada y cortada en cubos de 1 pulgada (aprox. 5 tazas en cubos)"),("Para la salsa","¼ taza de anacardos (nueces de la India) crudos"),("Para la salsa","½ taza de levadura nutricional"),("Para la salsa","1 cucharadita de ajo en polvo"),("Para la salsa","1 cucharadita de cebolla en polvo"),("Para la salsa","1 cucharadita de pimentón ahumado"),("Para la salsa","¾-1 taza de leche de anacardo sin azúcar o la leche de su preferencia"),("Para la salsa","½ cucharadita de sal marina o al gusto"),
("Para decorar (opcional)","queso parmesano vegano"),("Para decorar (opcional)","salvia fresca"),("Para decorar (opcional)","pimentón ahumado")],
["Hierva una olla grande con agua con sal y cocine la pasta según las instrucciones del paquete para obtener pasta al dente. Escurra, regrese a la olla y reserve.","Mientras tanto, ponga la calabaza en una olla pequeña, cubra con agua y hierva durante 8 minutos, o hasta que se pueda atravesar fácilmente con un tenedor. Luego escúrrala y agréguela a la licuadora, junto con todos los demás ingredientes de la salsa, comenzando con 3/4 taza de la leche. Licúe hasta que quede suave y agregue más leche si es necesario para una consistencia más fluida.","Luego vierta la salsa sobre la pasta, mezcle bien y sirva con la guarnición que desee. (Reserve 1-2 tazas de la salsa si desea agregar más encima de cada tazón al servir.)"],
["Sale el agua de la pasta. Asegúrese de agregar suficiente sal a la olla de agua para obtener la mejor textura y sabor. Aquí hay una útil guía para ayudarle a salar el agua perfectamente cada vez. Si no tiene una licuadora potente, agregue los anacardos a la misma olla con la calabaza y hierva hasta que la calabaza esté cocida. Esto ablandará los anacardos y ayudará a que se licúen de manera más suave. Es posible que necesite más o menos leche, según el tamaño de su calabaza. Mientras la pasta reposa con la salsa, seguirá absorbiéndola. Por eso, si planea tener sobras, reserve una taza de la salsa en un recipiente aparte antes de mezclarla con la pasta. Agregue la salsa reservada a una sartén con la pasta sobrante al recalentar para devolverla a un estado cremoso. Las sobras se conservan refrigeradas de 3 a 4 días. Puede congelar la salsa hasta por 3 meses en un recipiente hermético apto para congelador. No recomiendo congelar la pasta, ya que altera la textura."],[]))
X.append(r(9517824,"Elote en freidora de aire","El elote en freidora de aire es delicioso, fácil de preparar y sabe como si lo hubieran asado a la parrilla, ¡pero sin necesidad de encender el asador! Muy fácil y listo en un abrir y cerrar de ojos.","3 porciones","1 porción",
["3 elotes (mazorcas de maíz) sin hojas","1-2 cucharaditas de margarina vegana o el aceite de su elección, opcional"],
["Quite las hojas a los elotes y córtelos por la mitad si es necesario para que quepan en la canasta de su freidora. Si caben enteros, no es necesario cortarlos. Si la usa, unte los elotes con margarina o aceite, con una brocha de silicón. O rocíelos con aceite en aerosol para cocinar. (opcional)","Coloque los elotes en la canasta y cocine en la freidora de aire a 380 grados F durante 12-15 minutos. Gire los elotes alrededor de los 8-10 minutos y continúe girándolos cada par de minutos hacia el final de la cocción, para asegurarse de que no se quemen.","Sirva tibios tal cual, o con mantequilla, crema fresca, cilantro, canela o cualquiera de sus coberturas favoritas."],
["Elija elotes frescos, con granos más gruesos. Las hojas deben estar bien enrolladas, de color verde brillante, y sin ponerse amarillas ni secas. Según el modelo de su freidora de aire, puede cortar los elotes por la mitad para acomodarlos por espacio, si es necesario. La cantidad de elotes y el modelo de freidora afectarán el tiempo de cocción, así que comience a revisar los elotes alrededor de los 10 minutos. Para que sea sin aceite, omita la margarina o el aceite y unte un poco de caldo de verduras sobre los elotes en su lugar, para mantenerlos húmedos mientras se cocinan."],[]))
X.append(r(9517941,"Hamburguesa de seitán para asar a la parrilla","¡Una hamburguesa de seitán jugosa, abundante e increíblemente sabrosa que resistirá en la parrilla!","8 hamburguesas de seitán","1 porción",
[("Para las hamburguesas de seitán","¾ taza de frijoles negros cocidos o enlatados"),("Para las hamburguesas de seitán","4 onzas de champiñones blancos"),("Para las hamburguesas de seitán","2 cucharadas de pasta de miso blanco"),("Para las hamburguesas de seitán","1 cucharada de tahini"),("Para las hamburguesas de seitán","2 cucharaditas de cebolla en polvo"),("Para las hamburguesas de seitán","2 cucharaditas de ajo en polvo"),("Para las hamburguesas de seitán","2 cucharaditas de pimentón ahumado"),("Para las hamburguesas de seitán","½ taza de caldo de verduras"),("Para las hamburguesas de seitán","280 gramos de gluten de trigo vital (aprox. 2 ¼ tazas)"),
("Para cocinar","3-4 tazas de caldo de verduras a temperatura ambiente"),
("Para servir","panes veganos para hamburguesa"),("Para servir","lechuga, tomate, pepinillos, cebolla, aguacate"),("Para servir","mayonesa picante vegana")],
["Precaliente el horno a 350 grados F (177 C).","Ponga todos los ingredientes de las hamburguesas de seitán, EXCEPTO el gluten de trigo vital, en un procesador de alimentos y procese hasta que quede suave. Luego agregue aproximadamente la mitad del gluten de trigo vital y procese hasta que quede casi suave. Después agregue la mitad restante y procese hasta que esté casi integrado, sin procesar en exceso.","Pase la mezcla a una superficie limpia, como una tabla para cortar o una encimera, y amase la masa durante unos 30 segundos, sin exagerar. Una vez que vea hebras de gluten, la masa está lista. (Vea las fotos del proceso arriba como referencia.)","Divida en 8 piezas iguales para una cocción uniforme. Yo uso una báscula de cocina para que queden perfectamente iguales, pero no es necesario. Puede hacerlo a ojo.","Forme una bola con cada pieza y luego use un rodillo para aplanar cada una en forma de hamburguesa. Se expandirán durante la cocción, así que hágalas un poco más planas de lo que quiere que sea el resultado final. Al estirar las hamburguesas, debe verlas recuperar un poco su forma.","Use un recipiente apto para horno con tapa, como una olla holandesa, y agregue una capa delgada de caldo de verduras en el fondo. Luego acomode las hamburguesas de seitán encima, agregando más caldo entre las capas de hamburguesas. Agregue suficiente caldo para asegurarse de que las hamburguesas queden completamente cubiertas.","Luego ponga la tapa y hornee en el horno precalentado durante 80 minutos, volteándolas con cuidado a los 40 minutos. Tenga mucho cuidado al voltearlas para evitar romperlas. Cuando terminen los 80 minutos, retire del horno.","Si las prepara con anticipación, pase las hamburguesas a un recipiente para refrigerarlas durante la noche y termine de cocinarlas el día en que las sirva. (Reserve el caldo para beberlo, es delicioso, ¡no lo tire! ;) )","Trátelas como hamburguesas crudas. NO están listas para comer directamente al salir del horno. Termine su hamburguesa de seitán en la parrilla o en una sartén. Unte un poco de aceite para evitar que se peguen y espolvoree con sal y pimienta, si lo desea. Luego áselas a la parrilla o fríalas en la sartén unos minutos por cada lado hasta que estén doradas y calientes por dentro.","Disfrute con panes para hamburguesa y todas sus coberturas favoritas."],
["Si es posible, prepare sus hamburguesas un día antes de asarlas. Saben mejor cuando se refrigeran durante la noche y se asan al día siguiente. Sin embargo, siguen siendo excelentes si se asan inmediatamente después de prepararlas. Pese el gluten de trigo vital para obtener los resultados más precisos. Depender de las medidas en tazas podría dar como resultado una hamburguesa de seitán seca y densa, ya que al medir tiende a compactarse más harina en las tazas que al pesarla. Use un caldo salado y sabroso para obtener los mejores resultados, ya que no se agrega otra sal a esta receta. Trate de dividir la mezcla en 8 piezas de igual tamaño para una cocción uniforme y hamburguesas de tamaño similar. Si desea que queden perfectas, use una báscula de cocina para pesar las piezas. Extienda las hamburguesas bastante planas, ya que crecerán y casi se duplicarán en tamaño durante la cocción. Las hamburguesas deben cocinarse a fuego lento en el caldo y NO hervir con fuerza, para que se cocinen lentamente, con la mejor textura. No aumente la temperatura del horno para tratar de cocinarlas más rápido. Sus hamburguesas de seitán se conservan en el refrigerador de 4 a 5 días o pueden congelarse, colocadas en capas con papel pergamino para evitar que se peguen, hasta por 3 meses."],[]))
X.append(r(9518240,"Mezcla de caldo de verduras en polvo para sopa","¡Este caldo de verduras en polvo es su solución de mezcla para sopa! Es saludable, sin grasa y está listo en 5 minutos. ¡Nunca más compre caldo comprado en tienda!","10 porciones de 1 cucharadita","1 porción",
["2 cucharadas de levadura nutricional","2 cucharadas de sal marina o use 1 cucharada para la opción baja en sodio","1 cucharadita de perejil seco","1 cucharadita de cebolla en polvo","1 cucharadita de ajo en polvo","½ cucharadita de semillas de apio, no sal de apio","1 hoja de laurel seca","¼ cucharadita de pimienta negra, opcional pero recomendada"],
["Ponga todos los ingredientes en una licuadora pequeña o procesador de alimentos y licúe hasta lograr una consistencia de polvo, aprox. 20 segundos.","Guarde en un frasco limpio o recipiente sellado en su despensa.","Para preparar caldo, combine 1 cucharadita de la mezcla para sopa con 1 taza de agua caliente."],
["Para un caldo de verduras en polvo bajo en sodio, use 1 cucharada de sal para una reducción del 50% de sodio o use media cucharada de sal para reducir el sodio en un 75%. Duplique, triplique o cuadruplique la receta según lo desee. Me gusta preparar una tanda grande a la vez para tener siempre un poco a la mano, listo para sopas, cazuelas, verduras y más. Guarde su mezcla en un frasco o recipiente LIMPIO y SECO. Guárdela en un lugar fresco y oscuro, como su despensa, o si vive en un clima húmedo, puede guardarla en el refrigerador para mantener la frescura. Use su mezcla en polvo para sopa para reemplazar el caldo de verduras en cualquier receta. Solo combine 1 cucharadita de su mezcla con 1 taza de agua caliente por cada taza indicada. Si omite licuar hasta obtener un polvo y mezcla los condimentos en un tazón, necesitará aproximadamente una cucharada de mezcla para sopa por cada taza de agua caliente. Al licuarse, las especias quedan más concentradas, y 1 cucharadita por cada taza de agua funciona bien. Use más o menos según su gusto. Además, asegúrese de omitir la hoja de laurel si decide omitir el licuado. Para una versión de caldo de «pollo», agregue 1 cucharadita de condimento para aves. O ½ cucharadita de salvia, y ¼ cucharadita de tomillo y de romero cada uno."],[]))
save(7,X)
