import sys;sys.path.insert(0,'/mnt/c/WSL/davita/translations/c0')
from h import *
R=[]
R.append(build(0,{
"es":("Claras de huevo revueltas (3)","Información nutricional de las claras de huevo revueltas","1","3 claras de huevo revueltas",
["3 huevos enteros"],
["Rompa 3 huevos y separe las claras en un tazón pequeño.","Bata las claras hasta que se vean un poco espumosas.","Caliente una sartén antiadherente a fuego medio y rocíela ligeramente con aceite en aerosol para cocinar.","Vierta las claras en la sartén.","Déjelas cocinar unos segundos y luego revuélvalas suavemente con una espátula.","Siga cocinando y revolviendo hasta que las claras estén firmes y no quede líquido.","Retire del fuego y sirva caliente."],[],[]),
"ar":("بياض البيض المقلي (3)","معلومات غذائية عن بياض البيض المقلي","1","3 بياضات بيض مقلية",
["3 بيضات كاملة"],
["اكسر 3 بيضات وافصل البياض في وعاء صغير.","اخفق بياض البيض حتى يبدو رغويًا قليلًا.","سخّن مقلاة غير لاصقة على نار متوسطة ورشّها قليلًا برذاذ الطهي.","اسكب بياض البيض في المقلاة.","اتركه ينضج لبضع ثوانٍ، ثم قلّبه برفق بملعقة مسطحة.","واصل الطهي والتقليب حتى يصبح بياض البيض متماسكًا ولا يبقى فيه سائل.","ارفعه عن النار وقدّمه دافئًا."],[],[])}))
R.append(build(1,{
"es":("Espinacas salteadas","Nunca había sido tan fácil agregar verduras verdes sin almidón a su plato que con estas sencillas espinacas salteadas. Listas en minutos, son una excelente opción para las comidas entre semana, apta para personas con diabetes.","4","1 taza",
["2 cucharadas de aceite de oliva","2 dientes de ajo (en rodajas)","1 libra de espinacas congeladas (lavadas y sin tallos)","1/4 de cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["En una sartén grande, caliente el aceite de oliva a fuego medio.","Agregue el ajo a la sartén y saltéelo de 1 a 2 minutos, hasta que desprenda su aroma.","Agregue las espinacas frescas a la sartén por tandas, dejando que cada tanda se marchite antes de añadir más.","Mezcle suavemente las espinacas para cubrirlas con el aceite de oliva y el ajo.","Continúe salteando de 2 a 3 minutos, o hasta que las espinacas estén marchitas y tiernas.","Sazone con sal y pimienta negra al gusto. Mezcle para combinar.","Si lo desea, sirva con gajos de limón a un lado."],[],[]),
"ar":("سبانخ مسوتّاة","لم يكن من قبل أسهل من هذا أن تضيف خضارًا ورقية خالية من النشا إلى طبقك بفضل هذه السبانخ المسوتّاة البسيطة. تجهز في دقائق، وهي خيار رائع ومناسب لمرضى السكري لوجبات أيام الأسبوع.","4","1 كوب",
["2 ملعقة كبيرة زيت زيتون","2 فص ثوم (مقطّع إلى شرائح)","1 رطل سبانخ مجمدة (مغسولة ومنزوعة السيقان)","¼ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة.","أضف الثوم إلى المقلاة وسوّته لمدة 1–2 دقيقة حتى تفوح رائحته.","أضف السبانخ الطازجة إلى المقلاة على دفعات، واترك كل دفعة تذبل قبل إضافة المزيد.","قلّب السبانخ برفق لتتغلف بزيت الزيتون والثوم.","واصل التسوية لمدة 2–3 دقائق أو حتى تذبل السبانخ وتصبح طرية.","تبّل بالملح والفلفل الأسود حسب الرغبة. قلّب لمزج المكونات.","قدّمها مع شرائح الليمون جانبًا إن رغبت."],[],[])}))
R.append(build(2,{
"es":("Plato de bocadillos estilo griego con salsa para mojar","Es un refrigerio ligero y refrescante que equilibra a la perfección los granos integrales con sabores frescos y salados.","1","1/2 pan pita integral (unas 2 oz), 2 cucharadas de salsa tzatziki, 1 taza de tomates cherry",
["2 oz de pan pita integral","2 cucharadas de salsa tzatziki baja en grasa","1 taza de tomates cherry"],
["Para obtener el mejor sabor, tueste ligeramente el pan pita integral en una tostadora o en el horno hasta que esté caliente y ligeramente flexible.","Corte el pan pita en triángulos (cuñas) y colóquelos en un plato junto a un tazón pequeño de tzatziki y los tomates cherry enteros para mojar.","Disfrútelo de inmediato mientras el pan pita esté caliente."],[],[]),
"ar":("طبق تغميس على الطريقة اليونانية","وجبة خفيفة منعشة تجمع بتوازن مثالي بين الحبوب الكاملة والنكهات الباردة اللذيذة.","1","½ رغيف بيتا من الحبوب الكاملة (حوالي 2 أونصة)، 2 ملعقة كبيرة صلصة تزاتزيكي، 1 كوب طماطم كرزية",
["2 أونصة خبز بيتا من الحبوب الكاملة","2 ملعقة كبيرة صلصة تزاتزيكي قليلة الدسم","1 كوب طماطم كرزية"],
["للحصول على أفضل نكهة، حمّص خبز البيتا من الحبوب الكاملة قليلًا في محمصة الخبز أو الفرن حتى يصبح دافئًا ومرنًا قليلًا.","قطّع خبز البيتا إلى مثلثات (أسافين) وضعها في طبق بجانب وعاء صغير من التزاتزيكي والطماطم الكرزية الكاملة للتغميس.","تناوله فورًا ما دام الخبز دافئًا."],[],[])}))
R.append(build(3,{
"es":("Ensalada niçoise de tofu","Esta versión fresca de la ensalada niçoise, baja en grasa y vegetariana, usa tofu sellado en lugar de atún como proteína de origen vegetal, e incluye ingredientes clásicos como ejotes crujientes, papas tiernas y huevos duros. En lugar del vinagre habitual, un aderezo francés cremoso sin grasa aporta un toque ácido sin grasa saturada adicional. Es una comida apta para personas con diabetes, llena de fibra, color y textura crujiente.","4","4 tazas de verduras, 3 oz de tofu",
["1 libra de papas rojas pequeñas (partidas por la mitad)","2 huevos grandes","12 oz de ejotes frescos (sin las puntas)","6 tazas de lechuga mantecosa (picada)","1 taza de tomates cherry (partidos por la mitad)","1/2 taza de pepino (en rodajas finas)","1/2 oz de aceitunas Kalamata (partidas por la mitad)","1/2 taza de aderezo cremoso estilo francés sin grasa","12 oz de tofu extra firme (prensado y cortado en tiras de 1/2 pulgada)","2 cucharaditas de salsa de soya baja en sodio","1 cucharadita de mostaza Dijon","1/2 cucharadita de ajo en polvo","1 pizca de pimienta negra"],
["Prepare las papas, los huevos y los ejotes: Coloque las papas partidas por la mitad en una olla con agua fría. Deje que hierva y cocine de 10 a 12 minutos, o hasta que estén tiernas. En los últimos 8 minutos de cocción, baje los huevos con cuidado. En los últimos 2 minutos, agregue los ejotes. Escurra todo, pase los ejotes a un baño de agua con hielo y enfríe los huevos en agua fría. Pele los huevos una vez fríos y córtelos en cuartos.","Prepare y cocine el tofu: En un plato hondo, bata la salsa de soya, la mostaza Dijon, el aceite de oliva, el ajo en polvo y la pimienta negra. Agregue las rebanadas de tofu y deje marinar de 5 a 10 minutos. Caliente una sartén antiadherente a fuego medio-alto. Selle el tofu de 3 a 4 minutos por lado, hasta que esté dorado y ligeramente crujiente. Reserve.","Arme la ensalada: En una fuente grande o en platos individuales, acomode la lechuga, las papas, los ejotes, los tomates, los pepinos, las aceitunas y los huevos. Coloque encima las rebanadas de tofu sellado. Rocíe con el aderezo justo antes de servir."],[],[]),
"ar":("سلطة نيسواز بالتوفو","هذه نسخة منعشة وقليلة الدسم ونباتية من سلطة نيسواز، تستخدم التوفو المحمّر بدلًا من التونة للحصول على بروتين نباتي، وتضم مكونات كلاسيكية مثل الفاصولياء الخضراء المقرمشة والبطاطس الطرية والبيض المسلوق. وبدلًا من الصلصة المعتادة، تضيف صلصة فرنسية كريمية خالية من الدسم نكهة حامضة منعشة دون دهون مشبعة إضافية. إنها وجبة مناسبة لمرضى السكري، غنية بالألياف واللون والقرمشة.","4","4 أكواب خضار، 3 أونصة توفو",
["1 رطل بطاطس حمراء صغيرة (مقطّعة إلى نصفين)","2 بيضة كبيرة","12 أونصة فاصولياء خضراء طازجة (مقطوعة الأطراف)","6 أكواب خس زبدي (مفروم)","1 كوب طماطم كرزية (مقطّعة إلى نصفين)","½ كوب خيار (مقطّع إلى شرائح رفيعة)","½ أونصة زيتون كالاماتا (مقطّع إلى نصفين)","½ كوب صلصة سلطة فرنسية كريمية خالية من الدسم","12 أونصة توفو صلب جدًا (معصور ومقطّع إلى شرائح بعرض ½ بوصة)","2 ملعقة صغيرة صلصة صويا قليلة الصوديوم","1 ملعقة صغيرة خردل ديجون","½ ملعقة صغيرة مسحوق الثوم","1 رشة فلفل أسود"],
["حضّر البطاطس والبيض والفاصولياء الخضراء: ضع البطاطس المقطعة إلى نصفين في قدر به ماء بارد. اتركه حتى يغلي ثم اطهِه لمدة 10–12 دقيقة أو حتى تصبح البطاطس طرية. في آخر 8 دقائق من الغلي، أنزل البيض برفق. وفي آخر دقيقتين، أضف الفاصولياء الخضراء. صفِّ كل شيء، وانقل الفاصولياء الخضراء إلى حمام من الماء المثلج، وبرّد البيض في ماء بارد. قشّر البيض بعد أن يبرد وقطّعه إلى أرباع.","حضّر التوفو واطهِه: في طبق مسطح، اخفق صلصة الصويا وخردل ديجون وزيت الزيتون ومسحوق الثوم والفلفل الأسود. أضف شرائح التوفو واتركها تتتبل لمدة 5–10 دقائق. سخّن مقلاة غير لاصقة على نار متوسطة إلى عالية. حمّر التوفو لمدة 3–4 دقائق لكل جانب حتى يصبح ذهبي اللون ومقرمشًا قليلًا. ضعه جانبًا.","اجمع السلطة: في طبق تقديم كبير أو أطباق فردية، رتّب الخس والبطاطس والفاصولياء الخضراء والطماطم والخيار والزيتون والبيض. ضع شرائح التوفو المحمّر في الأعلى. رشّ الصلصة قبل التقديم مباشرة."],[],[])}))
R.append(build(4,{
"es":("Ensalada Cobb de pollo","Esta clásica ensalada Cobb de pollo es una opción apta para personas con diabetes para una comida satisfactoria. Rica en proteínas y sabor, es lo bastante saciante como para mantenerle lleno durante horas.","6","1-1/3 tazas",
["1 cucharada de aceite de oliva","1 cucharadita de orégano seco","1 cucharadita de ajo en polvo","1/4 de cucharadita de pimienta negra","1 libra de pechugas de pollo deshuesadas y sin piel","8 tazas de hojas verdes tiernas para ensalada","1 taza de tomates cherry (partidos por la mitad)","1 taza de pepino (en cubos)","1/2 taza de cebolla morada (finamente picada)","1 aguacate mediano (en cubos)","1/4 de taza de aceitunas Kalamata (sin hueso y en rodajas)","2 huevos duros grandes (en rodajas)","1/2 taza de vinagreta balsámica light"],
["Precaliente una parrilla o una plancha acanalada a fuego medio-alto.","En un tazón, mezcle el aceite de oliva, el orégano seco, el ajo en polvo, la sal y la pimienta negra.","Unte las pechugas de pollo con la mezcla de aceite de oliva.","Ase el pollo unos 6 a 8 minutos por lado, o hasta que esté bien cocido y alcance una temperatura interna de 165 grados F.","Deje reposar el pollo unos minutos antes de cortarlo en tiras.","En un tazón grande, acomode las hojas verdes mixtas, los tomates cherry partidos por la mitad, el pepino en cubos, la cebolla morada finamente rebanada, el aguacate en cubos y las aceitunas Kalamata en rodajas.","Coloque las tiras de pollo asado sobre la ensalada.","Agregue los huevos duros en rodajas.","Rocíe la ensalada con la vinagreta balsámica."],[],[]),
"ar":("سلطة كوب بالدجاج","سلطة كوب الكلاسيكية بالدجاج خيار مناسب لمرضى السكري لوجبة مشبعة. وهي غنية بالبروتين والنكهة، ومشبعة بما يكفي لتبقيك ممتلئًا لساعات.","6","1⅓ كوب",
["1 ملعقة كبيرة زيت زيتون","1 ملعقة صغيرة أوريجانو مجفف","1 ملعقة صغيرة مسحوق الثوم","¼ ملعقة صغيرة فلفل أسود","1 رطل صدور دجاج منزوعة العظم والجلد","8 أكواب أوراق سلطة صغيرة","1 كوب طماطم كرزية (مقطّعة إلى نصفين)","1 كوب خيار (مقطّع مكعبات)","½ كوب بصل أحمر (مفروم ناعمًا)","1 حبة أفوكادو متوسطة (مقطّعة مكعبات)","¼ كوب زيتون كالاماتا (منزوع النوى ومقطّع إلى شرائح)","2 بيضة مسلوقة كبيرة (مقطّعة إلى شرائح)","½ كوب صلصة الخل البلسمي الخفيفة"],
["سخّن شواية أو مقلاة شواء على نار متوسطة إلى عالية.","في وعاء، اخلط زيت الزيتون والأوريجانو المجفف ومسحوق الثوم والملح والفلفل الأسود.","افرد خليط زيت الزيتون على صدور الدجاج بفرشاة.","اشوِ الدجاج لمدة 6-8 دقائق تقريبًا لكل جانب أو حتى ينضج تمامًا وتصل حرارته الداخلية إلى 165 درجة فهرنهايت (75 درجة مئوية).","اترك الدجاج يرتاح بضع دقائق قبل تقطيعه إلى شرائح طويلة.","في وعاء كبير، رتّب أوراق السلطة المشكلة والطماطم الكرزية المقطعة إلى نصفين والخيار المقطع مكعبات والبصل الأحمر المقطع إلى شرائح رفيعة والأفوكادو المقطع مكعبات وزيتون كالاماتا المقطع إلى شرائح.","رتّب شرائح الدجاج المشوي فوق السلطة.","أضف شرائح البيض المسلوق.","رشّ السلطة بصلصة الخل البلسمي."],[],[])}))
R.append(build(5,{
"es":("Nuevas hormiguitas en un tronco","¡Un clásico refrigerio para niños con un toque especial! Las cerezas secas aportan dulzura, y las grasas saludables y la proteína de la mantequilla de almendras lo convierten en un refrigerio de media tarde perfecto y equilibrado.","1","2 tallos de apio con cobertura",
["2 tallos de apio (recortados y lavados)","1-1/2 cucharadas de mantequilla de almendras","2 cucharaditas de cerezas secas sin azúcar"],
["Rellene cada tallo de apio con la mantequilla de frutos secos y cúbralo con la fruta seca. Sirva de inmediato."],[],[]),
"ar":("نمل جديد على جذع","وجبة كلاسيكية يحبها الأطفال بلمسة جديدة! تضيف الكرز المجفف حلاوة، وتجعلها الدهون الصحية والبروتين في زبدة اللوز وجبة خفيفة متوازنة ومثالية بعد الظهر.","1","ساقان من الكرفس محشوان ومزينان",
["2 ساق كرفس (مقطوعة الأطراف ومغسولة)","1½ ملعقة كبيرة زبدة اللوز","2 ملعقة صغيرة كرز مجفف غير محلى"],
["املأ كل ساق كرفس بزبدة المكسرات وزيّنها بالفاكهة المجففة. قدّمها فورًا."],[],[])}))
R.append(build(6,{
"ar":("شوربة الخضار الجذرية المحمّصة","يساعد تحميص الخضار في هذه الوصفة على إبراز نكهة الشوربة إلى أقصى حد. والأفضل من ذلك أن جميع هذه الخضار متوفرة بكثرة خلال أشهر الشتاء.","8","1½ كوب",
["1 رشة (0.25 غرام) رذاذ طهي غير لاصق","1 حبة صغيرة (حوالي 1 رطل) قرع الجوز (مقشّرة ومنزوعة البذور ومقطّعة إلى قطع بحجم 1 بوصة)","2 حبة لفت صغيرة (مقشّرة ومقطّعة إلى قطع بحجم 1 بوصة)","2 حبة جزر أبيض متوسطة (مقشّرة ومقطّعة إلى قطع بحجم 1 بوصة)","2 حبة جزر متوسطة (مقشّرة ومقطّعة إلى قطع بحجم 1 بوصة)","1 حبة بصل كبيرة (مقشّرة ومقطّعة مكعبات)","3 ساق كرفس (مقطّعة مكعبات)","½ رأس ملفوف أخضر (مفروم)","4 فص ثوم (مفروم)","1 ملعقة كبيرة زيت زيتون","1 ملعقة كبيرة أعشاب بروفانس","2 كوارت مرق خضار قليل الصوديوم","1 ملعقة كبيرة خل الشيري","1 ملعقة صغيرة ملح","½ ملعقة صغيرة فلفل أسود"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (200° مئوية). ادهن صينية خبز كبيرة (أو صينيتين متوسطتين) برذاذ الطهي. ضعها جانبًا.","في وعاء كبير، اخلط جميع الخضار، بما فيها الثوم، مع زيت الزيتون وأعشاب بروفانس. اسكبها على صينية الخبز المجهزة وحمّصها لمدة 45 دقيقة أو حتى تنضج تمامًا وتبدأ في التحمير.","بعد أن تنتهي الخضار من التحميص، اسكبها في قدر شوربة كبير. اخلطها مع مرق الخضار واتركها حتى تغلي. خفّف الحرارة واتركها تغلي على نار هادئة لمدة 10 دقائق.","اهرس الشوربة بخلاط يدوي أو على دفعات في خلاط عادي.","تبّل الشوربة بخل الشيري والملح والفلفل."],[],[])}))
R.append(build(7,{
"es":("Revuelto de tofu con calabacín y tomates cherry","Esta es una receta vegetariana, vegana, baja en carbohidratos y muy baja en carbohidratos que presenta un colorido revuelto de tofu, un desayuno abundante de origen vegetal, rico en proteínas y fibra gracias al tofu extra firme y las verduras frescas. La cúrcuma aporta un sabor cálido y terroso y un tono dorado sin necesidad de huevos. Es una opción nutritiva y consciente de los carbohidratos que ayuda a mantener estables los niveles de glucosa en la sangre (azúcar en la sangre) de las personas con diabetes.","4","2 tazas",
["2 cucharadas de aceite de oliva","1 cebolla amarilla mediana (en cubos)","2 calabacines medianos (cortados en medias lunas)","3 dientes de ajo (picados)","1 cucharadita de cúrcuma","1 cucharadita de sal","1/2 cucharadita de albahaca","1/2 cucharadita de orégano fresco","12 oz de tofu extra firme","1 taza de tomates cherry (partidos por la mitad)"],
["Caliente una sartén grande a fuego medio y agregue el aceite de oliva.","Agregue la cebolla, el calabacín, el ajo y las especias a la sartén. Desmenuce el tofu con los dedos sobre la sartén y mezcle para combinar. Saltee hasta que las verduras estén suaves, de 5 a 7 minutos.","Retire del fuego e incorpore los tomates cherry."],[],[]),
"ar":("خليط التوفو المقلي مع الكوسا والطماطم الكرزية","هذه وصفة نباتية وخالية من منتجات الحيوان وقليلة الكربوهيدرات جدًا، تقدم خليط توفو ملونًا مقلّبًا يُعدّ فطورًا نباتيًا مشبعًا غنيًا بالبروتين والألياف من التوفو الصلب جدًا والخضار الطازجة. تضيف الكركم نكهة دافئة ترابية ولونًا ذهبيًا دون الحاجة إلى البيض. إنه خيار مغذٍّ يراعي الكربوهيدرات ويساعد على استقرار مستويات الجلوكوز (سكر الدم) لدى مرضى السكري.","4","2 كوب",
["2 ملعقة كبيرة زيت زيتون","1 حبة بصل أصفر متوسطة (مقطّعة مكعبات)","2 حبة كوسا متوسطة (مقطّعة إلى أنصاف أقمار)","3 فص ثوم (مفروم)","1 ملعقة صغيرة كركم","1 ملعقة صغيرة ملح","½ ملعقة صغيرة ريحان","½ ملعقة صغيرة أوريجانو طازج","12 أونصة توفو صلب جدًا","1 كوب طماطم كرزية (مقطّعة إلى نصفين)"],
["سخّن مقلاة كبيرة على نار متوسطة وأضف زيت الزيتون.","أضف البصل والكوسا والثوم والتوابل إلى المقلاة. فتّت التوفو بأصابعك داخل المقلاة وقلّب لمزج المكونات. سوِّ الخليط حتى تلين الخضار، لمدة 5-7 دقائق.","ارفع المقلاة عن النار وأضف الطماطم الكرزية مع التقليب."],[],[])}))
R.append(build(8,{
"es":("Repollo salteado con aderezo de vinagre de manzana","Repollo salteado con un aderezo de vinagre de manzana, donde la suave textura crujiente del repollo se une al sabor ácido de un aderezo lleno de sabor. Este plato apto para personas con diabetes es lo bastante fácil para una comida entre semana.","6","1 taza",
["2 cucharadas de aceite de oliva","1 repollo morado pequeño (en rodajas finas)","2 cucharadas de vinagre de sidra de manzana","1 cucharada de mostaza Dijon","1 cucharada de miel de maple","1/2 cucharadita de semillas de alcaravea","1/2 cucharadita de sal","1/4 de cucharadita de pimienta negra"],
["En una sartén grande, caliente el aceite de oliva a fuego medio.","Agregue el repollo en rodajas finas a la sartén y mézclelo para cubrirlo con el aceite.","Saltee el repollo de 10 a 12 minutos, o hasta que esté tierno pero todavía un poco crujiente.","En un tazón pequeño, bata el vinagre de sidra de manzana, la mostaza Dijon, la miel de maple y las semillas de alcaravea.","Vierta el aderezo de vinagre de sidra sobre el repollo salteado. Mezcle para cubrirlo de manera uniforme.","Sazone con la sal y la pimienta negra.","Continúe salteando de 2 a 3 minutos más para que se mezclen los sabores."],[],[]),
"ar":("ملفوف مسوتّى مع صلصة خل التفاح","ملفوف مسوتّى مغطى بصلصة خل التفاح، حيث تلتقي القرمشة الخفيفة للملفوف بنكهة الصلصة الحامضة اللذيذة. هذا الطبق المناسب لمرضى السكري سهل بما يكفي لوجبة أيام الأسبوع.","6","1 كوب",
["2 ملعقة كبيرة زيت زيتون","1 رأس ملفوف أحمر صغير (مقطّع إلى شرائح رفيعة)","2 ملعقة كبيرة خل التفاح","1 ملعقة كبيرة خردل ديجون","1 ملعقة كبيرة شراب القيقب","½ ملعقة صغيرة بذور الكراوية","½ ملعقة صغيرة ملح","¼ ملعقة صغيرة فلفل أسود"],
["في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة.","أضف شرائح الملفوف الرفيعة إلى المقلاة وقلّبها لتتغلف بالزيت.","سوِّ الملفوف لمدة 10–12 دقيقة أو حتى يصبح طريًا مع بقاء قليل من القرمشة.","في وعاء صغير، اخفق خل التفاح وخردل ديجون وشراب القيقب وبذور الكراوية.","اسكب صلصة خل التفاح على الملفوف المسوتّى. قلّب لتتغلف بالتساوي.","تبّل بالملح والفلفل الأسود.","واصل التسوية لمدة 2–3 دقائق إضافية لتمتزج النكهات."],[],[])}))
R.append(build(9,{
"es":("Mini sándwiches de ensalada de pollo","Esta versión más ligera de la ensalada de pollo usa yogur griego ácido y mayonesa light junto con otros ingredientes saludables y llenos de sabor. Para una comida más baja en carbohidratos, sirva esta ensalada de pollo sobre hojas de lechuga en lugar de panecillos para mini sándwiches.","6","1 mini sándwich",
["2 tazas de pollo cocido (picado)","1 tallo de apio (en cubos pequeños)","2 cucharadas de cebolla morada (en cubos pequeños)","1/3 de taza de arándanos rojos secos","2 cucharadas de almendras en rodajas (sin sal)","1/4 de taza de yogur griego natural sin grasa","1/4 de taza de mayonesa light","1 cucharadita de mostaza Dijon","1 cucharada de jugo de limón (de 1/2 limón mediano)","pimienta negra recién molida al gusto","6 panecillos integrales para mini sándwiches","1 tomate mediano (cortado en 6 rebanadas)"],
["Mezcle todos los ingredientes, excepto los panecillos y el tomate, en un tazón mediano.","Sirva 1/3 de taza de ensalada de pollo en cada panecillo, cubierto con 1 rebanada de tomate."],[],[]),
"ar":("ساندويتشات صغيرة بسلطة الدجاج","تستخدم هذه النسخة الأخف من سلطة الدجاج الزبادي اليوناني الحامض والمايونيز الخفيف مع مكونات صحية أخرى ولذيذة! للحصول على وجبة أقل في الكربوهيدرات، قدّم سلطة الدجاج هذه على أوراق الخس بدلًا من خبز الساندويتشات الصغيرة.","6","1 ساندويتش صغير",
["2 كوب دجاج مطبوخ (مفروم)","1 ساق كرفس (مقطّعة مكعبات صغيرة)","2 ملعقة كبيرة بصل أحمر (مقطّع مكعبات صغيرة)","⅓ كوب توت بري مجفف","2 ملعقة كبيرة لوز شرائح (غير مملح)","¼ كوب زبادي يوناني سادة خالٍ من الدسم","¼ كوب مايونيز خفيف","1 ملعقة صغيرة خردل ديجون","1 ملعقة كبيرة عصير ليمون (من ½ ليمونة متوسطة)","فلفل أسود مطحون طازجًا حسب الذوق","6 أرغفة ساندويتش صغيرة من القمح الكامل","1 حبة طماطم متوسطة (مقطّعة إلى 6 شرائح)"],
["اخلط جميع المكونات ما عدا الخبز والطماطم في وعاء خلط متوسط.","قدّم ⅓ كوب من سلطة الدجاج في كل رغيف ساندويتش صغير، وضع فوقها 1 شريحة طماطم."],[],[])}))
R.append(build(10,{
"ar":("غموس الأفوكادو والخيار","هذه مقبلات خفيفة ولذيذة تُعد تمهيدًا رائعًا لأمسية رومانسية. ويمكنك تناولها كوجبة خفيفة في أي يوم آخر أيضًا. شرائح الخيار أو الهندباء البلجيكية رائعة أيضًا للتغميس!","2","¼ كوب غموس + شريحة خبز واحدة",
["½ حبة أفوكادو صغيرة","1 حبة خيار مخلل (مثل كيربي) أو ⅓ حبة خيار صغيرة)","2 ملعقة كبيرة كريمة حامضة (خالية من الدسم)","1 ملعقة صغيرة نعناع طازج مفروم أو ¼ ملعقة صغيرة نعناع مجفف (مفتت)","1 ملعقة صغيرة عصير ليمون أخضر","⅛ ملعقة صغيرة ملح","⅛ ملعقة صغيرة بذور الكرفس","⅛ ملعقة صغيرة فلفل أسود","2 شريحة خبز قمح كامل (خبز ساندويتش رقيق)"],
["في وعاء متوسط، اهرس الأفوكادو بالشوكة حتى تحصل على القوام المطلوب (خشن قليلًا أو ناعم).","افرم الخيار المخلل ناعمًا، أو قشّر الخيار العادي وانزع بذوره وافرمه ناعمًا. (يجب أن تحصل على حوالي ⅓ كوب.) أضف الخيار وبقية المكونات إلى الأفوكادو مع التحريك. ادهن الخليط على الخبز الرقيق وقدّمه فورًا، أو غطِّه وضعه في الثلاجة حتى 8 ساعات.","نصيحة الطاهي: لحفظ الأفوكادو المتبقي، رشّ السطح المكشوف بعصير الليمون الأصفر الطازج أو الليمون الأخضر أو الخل الأبيض. غطِّه بإحكام بغلاف بلاستيكي أو ضعه في وعاء محكم الإغلاق وضعه في الثلاجة. يمكن أن يبقى صالحًا لمدة 1-2 يوم."],[],[])}))
R.append(build(11,{
"ar":("حمص بالفاصولياء السوداء","لماذا نكتفي بالحمص؟ استبدله بالفاصولياء السوداء وأضف قليلًا من الكمون للحصول على نسخة جديدة منعشة من الحمص. قدّمه مع أعواد الخضار الطازجة للتغميس.","8","2 ملعقة كبيرة حمص + ¼ حبة خيار متوسطة + ¼ حبة جزر متوسطة",
["1 ملعقة كبيرة زيت زيتون","⅛ ملعقة صغيرة فلفل أسود","1 ملعقة كبيرة طحينة","½ ملعقة صغيرة كمون","1 علبة (15 أونصة) فاصولياء سوداء (قليلة الصوديوم، مشطوفة ومصفّاة)","¼ ملعقة صغيرة مسحوق الثوم","2 ملعقة كبيرة ماء","2 حبة خيار متوسطة (مقطّعة إلى أعواد)","2 حبة جزر متوسطة (مقطّعة إلى أعواد)"],
["ضع جميع المكونات في محضّر الطعام واخلطها حتى تصبح ناعمة. أضف المزيد من الماء إذا كان القوام كثيفًا جدًا.","قدّمه مع أعواد الجزر والخيار."],[],[])}))
R.append(build(12,{
"es":("Huevos rellenos con Dijon y rábano picante","Los huevos rellenos son un excelente refrigerio o aperitivo bajo en carbohidratos. ¡Y son perfectos para la época de Pascua si le sobran muchos huevos teñidos! Esta versión tradicional lleva mostaza Dijon y rábano picante para dar más sabor sin mucha sal añadida. Sustituimos la mayor parte de la mayonesa por yogur natural para un relleno más ligero.","6","2 mitades",
["6 huevos grandes","1 cucharada de vinagre blanco","6 cucharadas de yogur natural (sin grasa)","1 cucharada de mayonesa light","1 cucharada de cebollín fresco (picado)","2 cucharaditas de mostaza Dijon","1/2 cucharadita de rábano picante","1/4 de cucharadita de cúrcuma","1/8 de cucharadita de pimentón"],
["Para preparar los huevos: Coloque los huevos en una cacerola lo bastante grande para que no queden apretados. Agregue agua hasta cubrirlos unos 1 pulgada por encima. Tape la olla y deje que hierva. Una vez que el agua hierva, después de unos 6 a 7 minutos, retire la olla del fuego y colóquela sobre un quemador apagado. Agregue el vinagre al agua (para ayudar a pelar los huevos). Deje reposar los huevos en el agua caliente de 20 a 30 minutos.","Prepare un tazón grande con agua con hielo. Con una espumadera, pase los huevos al baño de agua con hielo y déjelos enfriar de 15 a 20 minutos. Saque con cuidado cada huevo del agua con hielo y golpee suavemente la cáscara hasta que se agriete por todas partes (pero sin pelarlo). Vuelva a colocar los huevos agrietados en el baño de agua con hielo (prepare uno nuevo si es necesario) durante 10 minutos. Saque los huevos del agua con hielo y ruédelos suavemente entre las palmas de las manos. Las cáscaras deben desprenderse con facilidad. Deseche las cáscaras.","Corte cada huevo por la mitad y retire las yemas. Deseche una yema y ponga las cinco restantes en un tazón. Coloque las claras en una fuente, con el lado cortado hacia arriba.","Triture las yemas con el yogur, la mayonesa, el cebollín, la mostaza, el rábano picante, la cúrcuma, la sal y la pimienta. Rellene las claras con la mezcla de yemas, con una cuchara o una manga pastelera. Espolvoree ligeramente con pimentón."],[],[]),
"ar":("بيض محشي بخردل ديجون والفجل الحار","البيض المحشي وجبة خفيفة أو مقبلات رائعة قليلة الكربوهيدرات. ومثالي لموسم عيد الفصح إذا كان لديك الكثير من البيض الملوّن المتبقي! تتميز هذه الوصفة التقليدية بخردل ديجون المنعش والفجل الحار لإضافة نكهة دون الكثير من الملح المضاف. استبدلنا معظم المايونيز بالزبادي السادة للحصول على حشوة أخف.","6","نصفان",
["6 بيضات كبيرة","1 ملعقة كبيرة خل أبيض","6 ملاعق كبيرة زبادي سادة (خالٍ من الدسم)","1 ملعقة كبيرة مايونيز خفيف","1 ملعقة كبيرة ثوم معمر (كراث) طازج (مفروم ناعمًا)","2 ملعقة صغيرة خردل ديجون","½ ملعقة صغيرة فجل حار","¼ ملعقة صغيرة كركم","⅛ ملعقة صغيرة بابريكا"],
["لتحضير البيض: ضع البيض في قدر يتسع له بحيث لا يكون مزدحمًا. أضف ماءً يغطي البيض بحوالي 1 بوصة. غطِّ القدر واتركه حتى يغلي. بعد أن يبدأ الماء بالغليان، بعد حوالي 6 إلى 7 دقائق، ارفع القدر عن النار وضعه على موقد غير مستخدم. أضف الخل إلى الماء (للمساعدة على تقشير البيض). اترك البيض في الماء الساخن لمدة 20 إلى 30 دقيقة.","جهّز وعاءً كبيرًا من الماء المثلج. باستخدام ملعقة مثقبة، انقل البيض إلى حمام الماء المثلج واتركه يبرد لمدة 15 إلى 20 دقيقة. أخرج كل بيضة برفق من الماء المثلج، واطرق قشرتها برفق حتى تتشقق من كل الجوانب (دون تقشيرها). أعد البيض المتشقق إلى حمام الماء المثلج (جهّز حمامًا جديدًا إذا لزم الأمر) لمدة 10 دقائق. أخرج البيض من الماء المثلج ودحرجه برفق بين راحتيك. يجب أن تنزلق القشور بسهولة. تخلص من القشور.","اقطع كل بيضة إلى نصفين وأخرج الصفار. تخلص من صفار واحد وضع الخمسة المتبقية في وعاء. ضع بياض البيض في طبق تقديم، والجانب المقطوع إلى الأعلى.","اهرس الصفار مع الزبادي والمايونيز والثوم المعمر والخردل والفجل الحار والكركم والملح والفلفل. املأ بياض البيض بخليط الصفار بالملعقة أو بكيس التزيين. رشّ البابريكا برفق."],[],[])}))
save(1,R)
