from h import *
R=[]
R.append((6710331,{
"es":L("Ensalada de espinacas y cebolla morada con aderezo de limón y semillas de amapola",
"Disfrute una explosión de frescura con nuestra ensalada de espinacas y cebolla morada acompañada de un aderezo cítrico de limón y semillas de amapola. Al mezclarse, esta ensalada le invita a saborear la deliciosa combinación de texturas y sabores, y es un complemento refrescante para su comida.",
"4","1 taza",
["8 tazas de espinacas tiernas","1 cebolla morada pequeña (en rodajas finas)","1/2 taza de tomates cherry (partidos por la mitad)","1/4 taza de almendras en láminas (tostadas)","1/4 taza de arándanos rojos secos (sin azúcar añadida)","2 cucharadas de aceite de oliva","1 cucharada de jugo de limón (fresco)","1/2 cucharada de mostaza Dijon","1 cucharadita de miel","1/2 cucharadita de semillas de amapola","1/4 cucharadita de sal","1/2 cucharadita de pimienta negra"],
["En un tazón grande para ensalada, mezcle las espinacas tiernas frescas, la cebolla morada en rodajas finas, los tomates cherry partidos por la mitad, las almendras en láminas tostadas y los arándanos rojos secos.","En un tazón pequeño, bata juntos el aceite de oliva, el jugo de limón fresco, la mostaza Dijon, la miel, las semillas de amapola, la sal y la pimienta negra.","Vierta el aderezo sobre la ensalada. Mezcle suavemente para que se cubra de manera uniforme.","Deje reposar la ensalada durante 10 minutos para que se mezclen los sabores."]),
"ar":L("سلطة السبانخ والبصل الأحمر مع صلصة الليمون وبذور الخشخاش",
"استمتع بنكهة منعشة مع سلطة السبانخ والبصل الأحمر المقدَّمة مع صلصة الليمون الحامضة وبذور الخشخاش. عند خلط المكونات معًا، تدعوك هذه السلطة إلى تذوّق المزيج الرائع من القوام والنكهات، لتكون إضافة منعشة إلى وجبتك.",
"4","1 كوب",
["8 أكواب من السبانخ الصغيرة","1 بصلة حمراء صغيرة (مقطعة إلى شرائح رفيعة)","½ كوب من الطماطم الكرزية (مقطعة إلى نصفين)","¼ كوب من شرائح اللوز (محمّصة)","¼ كوب من التوت البري المجفف (بدون سكر مضاف)","2 ملعقة كبيرة من زيت الزيتون","1 ملعقة كبيرة من عصير الليمون (طازج)","½ ملعقة كبيرة من خردل ديجون","1 ملعقة صغيرة من العسل","½ ملعقة صغيرة من بذور الخشخاش","¼ ملعقة صغيرة من الملح","½ ملعقة صغيرة من الفلفل الأسود"],
["في وعاء سلطة كبير، اخلط السبانخ الصغيرة الطازجة والبصل الأحمر المقطع إلى شرائح رفيعة والطماطم الكرزية المقطعة إلى نصفين وشرائح اللوز المحمّصة والتوت البري المجفف.","في وعاء صغير، اخفق معًا زيت الزيتون وعصير الليمون الطازج وخردل ديجون والعسل وبذور الخشخاش والملح والفلفل الأسود.","اسكب الصلصة فوق السلطة. قلّب برفق حتى تتغطى المكونات بالتساوي.","اترك السلطة لمدة 10 دقائق حتى تتمازج النكهات."])}))
R.append((6711007,{
"ar":L("تابيوكا اللوز مع الموز والذرة",
"هذه التابيوكا المحضّرة بحليب اللوز مستوحاة من حساء التابيوكا الكلاسيكي بحليب جوز الهند الذي يُقدَّم في كثير من أنحاء آسيا. نسخة حليب اللوز هذه أخف بكثير من الأصلية ولذيذة بالقدر نفسه. جرّبها مع فواكه أخرى، أو حتى مع البطاطا الحلوة والقلقاس!",
"16","½ كوب",
["8 أكواب من حليب اللوز غير المحلّى","⅓ كوب من لؤلؤ التابيوكا","3 ملاعق كبيرة من شراب الأغاف","½ ملعقة صغيرة من الملح الخشن (كوشير)","2 حبة موز ناضجة (مقشرة ومقطعة)","1 كوب من حبات الذرة الصفراء الحلوة الطازجة أو المجمدة","1 ملعقة صغيرة من بذور السمسم (محمّصة)"],
["في قدر كبير، أضف حليب اللوز واتركه حتى يغلي على نار عالية. خفّف الحرارة إلى متوسطة-منخفضة وأضف لؤلؤ التابيوكا مع التحريك المستمر لإبقائه منفصلًا. أضف سكر النخيل والملح وواصل الطهي حتى يصبح اللؤلؤ شفافًا تمامًا، نحو 30 دقيقة.","أطفئ النار وحرّك الموز والذرة داخل الخليط. قدّمها مزيّنة ببذور السمسم المحمّصة."])}))
R.append((6711224,{
"es":L("Parfait de yogur sin azúcar con frutos rojos frescos",
"¡Este parfait sin azúcar es una manera deliciosa y saludable de comenzar el día! Preparado con stevia para endulzar, yogur griego natural, frutos rojos frescos y los ingredientes crujientes que usted prefiera, es una opción deliciosa para quienes desean reducir su consumo de azúcar. También puede cubrir este parfait con semillas de chía, coco rallado o nueces picadas. Personalícelo aún más cambiando los arándanos azules por su fruto rojo favorito, como frambuesas o fresas. ¡Disfrute esta comida matutina saludable y fácil, o úsela como merienda a media tarde!",
"1","1 parfait",
["1 taza de yogur griego natural sin grasa","1/2 taza de arándanos azules frescos","5 gotas de edulcorante líquido de stevia","2 cucharaditas de almendras en láminas (opcional)"],
["En un tazón, mezcle con una cuchara el yogur griego y el SweetLeaf Sweet Drops Clear hasta obtener una consistencia cremosa.","Tome un vaso alto o un tazón pequeño para su parfait y coloque una capa de yogur en el fondo. Agregue frutos rojos y nueces (opcional) entre las capas de yogur hasta llegar a la parte superior. ¡Disfrútelo!","Consejo: ¡Un parfait terminado se conserva muy bien en el refrigerador, ideal para preparar comidas con anticipación y llevar!"]),
"ar":L("بارفيه الزبادي الخالي من السكر مع التوت الطازج",
"هذا البارفيه الخالي من السكر طريقة لذيذة وصحية لبدء يومك! يُحضَّر بالستيفيا للتحلية والزبادي اليوناني الطبيعي والتوت الطازج وإضافات مقرمشة من اختيارك، وهو خيار لذيذ لكل من يرغب في تقليل تناول السكر. يمكنك أيضًا تزيين هذا البارفيه ببذور الشيا أو جوز الهند المبشور أو المكسرات المفرومة. ويمكنك تخصيصه أكثر باستبدال التوت الأزرق بنوع التوت المفضل لديك مثل توت العليق أو الفراولة. استمتع بهذه الوجبة الصباحية الصحية والسهلة أو بوصفها وجبة خفيفة في منتصف النهار!",
"1","1 بارفيه",
["1 كوب من الزبادي اليوناني الطبيعي خالي الدسم","½ كوب من التوت الأزرق الطازج","5 قطرات من محلّي الستيفيا السائل","2 ملعقة صغيرة من شرائح اللوز (اختياري)"],
["في وعاء، اخلط الزبادي اليوناني مع SweetLeaf Sweet Drops Clear بملعقة حتى يصبح الخليط كريميًا.","خذ كوبًا طويلًا أو وعاءً صغيرًا للبارفيه وضع طبقة من الزبادي في القاع. أضف التوت والمكسرات (اختياري) بين طبقات الزبادي حتى تصل إلى أعلى الكوب. بالهناء والعافية!","نصيحة: يُحفظ البارفيه الجاهز جيدًا في الثلاجة، وهو مناسب لتحضير الوجبات مسبقًا وتناولها أثناء التنقل!"])}))
R.append((6712842,{
"es":L("Ensalada de zanahoria con aderezo de naranja",
"Disfrute los sabores brillantes y cítricos de esta ensalada de zanahoria con aderezo de naranja. La combinación de hierbas frescas, naranja dulce y zanahorias crujientes la convierte en un complemento refrescante y nutritivo para cualquier comida.",
"4","1 taza",
["4 tazas de zanahorias (ralladas)","1/4 taza de cilantro fresco (picado)","1/4 taza de menta fresca (picada)","1/4 taza de cebolla morada (picada)","1/4 taza de jugo de naranja","2 cucharadas de aceite de oliva","1 cucharada de miel","1 cucharadita de ralladura de naranja","1/4 cucharadita de sal","1/2 cucharadita de pimienta negra"],
["En un tazón grande, mezcle las zanahorias ralladas, el cilantro picado, la menta picada y la cebolla morada picada.","En un tazón pequeño, bata juntos el jugo de naranja, el aceite de oliva, la miel, la ralladura de naranja, la sal y la pimienta negra.","Vierta el aderezo sobre la mezcla de zanahoria y revuelva para combinar."]),
"ar":L("سلطة الجزر مع صلصة البرتقال",
"استمتع بالنكهات المنعشة والحامضة في سلطة الجزر مع صلصة البرتقال. يجعل مزيج الأعشاب الطازجة والبرتقال الحلو والجزر المقرمش هذه السلطة إضافة منعشة ومغذية لأي وجبة.",
"4","1 كوب",
["4 أكواب من الجزر (مبشور)","¼ كوب من الكزبرة الخضراء الطازجة (مفرومة)","¼ كوب من النعناع الطازج (مفروم)","¼ كوب من البصل الأحمر (مفروم)","¼ كوب من عصير البرتقال","2 ملعقة كبيرة من زيت الزيتون","1 ملعقة كبيرة من العسل","1 ملعقة صغيرة من قشر البرتقال المبشور","¼ ملعقة صغيرة من الملح","½ ملعقة صغيرة من الفلفل الأسود"],
["في وعاء كبير، اخلط الجزر المبشور والكزبرة الخضراء المفرومة والنعناع المفروم والبصل الأحمر المفروم.","في وعاء صغير، اخفق معًا عصير البرتقال وزيت الزيتون والعسل وقشر البرتقال المبشور والملح والفلفل الأسود.","اسكب الصلصة فوق خليط الجزر وقلّب حتى تتجانس المكونات."])}))
R.append((6713059,{
"es":L("Roscas integrales de pimienta negra y semillas de hinojo (Taralli integrali con pepe e finocchio)",
"Las provincias del sur de Italia —Lazio, Molise, Apulia, Basilicata, Campania, Abruzos y Calabria— comparten la tradición de servir taralli, panes crujientes parecidos a galletas saladas, con los aperitivos. Antiguamente, secar estas galletas era una forma de conservarlas. Hoy en día son cuestión de gusto y tradición. En Calabria, estas galletas se preparan para la fiesta de San Antonio. Las formas tradicionales incluyen anillos, cuerdas, trenzas, palitos y herraduras. Envueltos en bolsas transparentes de celofán con un lindo lazo, los taralli son un obsequio elegante.",
"2","3 roscas de pan",
["2 1/2 cucharaditas de levadura seca activa","3/4 taza de agua tibia (dividida)","2 tazas de harina integral o mezcla para hornear sin gluten, y más para la superficie de trabajo","1 cucharada de pimienta negra (recién molida)","2 cucharaditas de semillas de hinojo","1/4 cucharadita de hojuelas de chile rojo trituradas","1/2 cucharadita de sal marina sin refinar","3 1/2 cucharadas de aceite de oliva extra virgen (dividido)","1 clara de huevo grande (ligeramente batida)"],
["En un tazón pequeño, disuelva la levadura en 1/4 taza de agua tibia.","Coloque la harina, la pimienta, las semillas de hinojo, las hojuelas de chile y la sal en un tazón grande. Agregue la mezcla de levadura, 1/2 taza adicional de agua tibia y 3 cucharadas de aceite de oliva. Mezcle bien para integrar y formar una masa.","Vuelque la masa sobre una superficie ligeramente enharinada. Amase con energía, agregando un poco más de harina si es necesario, durante unos 8–10 minutos, hasta que la masa quede suave y elástica.","Unte un tazón grande con la 1/2 cucharadita restante de aceite de oliva y coloque la masa dentro. Voltee la masa para cubrirla con el aceite, y tape con envoltura plástica y paños de cocina limpios. Deje que leude hasta duplicar su tamaño, aproximadamente 1 ½ horas.","Precaliente el horno a 375 °F.","Saque la masa del tazón y separe un trozo pequeño. Forme una cuerda de 6 pulgadas, aproximadamente del grosor de un lápiz, y dele forma de círculo. Presione bien los extremos para unirlos y coloque la rosca en una bandeja para hornear sin engrasar. Repita con el resto de la masa. Cubra las roscas con un paño de cocina limpio y deje que leuden hasta duplicar su tamaño, aproximadamente 1 hora.","Barnice la parte superior de las roscas con la clara de huevo y hornee hasta que estén ligeramente doradas, de 15 a 20 minutos. Retírelas, déjelas enfriar sobre una rejilla y guárdelas en un recipiente bien tapado hasta por un mes."]),
"ar":L("حلقات الكراكر بالقمح الكامل والفلفل الأسود وبذور الشمر (تارالي إنتيغرالي كون بيبي إي فينوكيو)",
"تشترك أقاليم جنوب إيطاليا، وهي لاتسيو وموليزي وبوليا وباسيليكاتا وكامبانيا وأبروتسو وكالابريا، في تقليد تقديم التارالي، وهي خبز مقرمش يشبه الكراكر، مع المقبلات. في الماضي كان تجفيف هذا الكراكر وسيلة لحفظه. أما اليوم فهو مسألة ذوق وتقليد. وفي كالابريا يُحضَّر هذا الكراكر احتفالًا بعيد القديس أنطونيوس. ومن الأشكال التقليدية له الحلقات والحبال والضفائر والأعواد وحدوات الحصان. وعند تغليف التارالي بأكياس سيلوفان شفافة وربطها بشريط جميل تصبح هدية أنيقة.",
"2","3 حلقات خبز",
["2½ ملعقة صغيرة من الخميرة الجافة النشطة","¾ كوب من الماء الفاتر (مقسّم)","2 أكواب من دقيق القمح الكامل أو خليط الخبز الخالي من الغلوتين، وكمية إضافية لسطح العمل","1 ملعقة كبيرة من الفلفل الأسود (مطحون طازجًا)","2 ملعقة صغيرة من بذور الشمر","¼ ملعقة صغيرة من رقائق الفلفل الحار الأحمر المجروشة","½ ملعقة صغيرة من ملح البحر غير المكرر","3½ ملاعق كبيرة من زيت الزيتون البكر الممتاز (مقسّم)","1 بياض بيضة كبيرة (مخفوق قليلًا)"],
["في وعاء صغير، أذب الخميرة في ¼ كوب من الماء الفاتر.","ضع الدقيق والفلفل وبذور الشمر ورقائق الفلفل الحار والملح في وعاء كبير. أضف خليط الخميرة و½ كوب إضافي من الماء الفاتر و3 ملاعق كبيرة من زيت الزيتون. اخلط جيدًا حتى تتجانس المكونات وتتكوّن العجينة.","اقلب العجينة على سطح مرشوش بقليل من الدقيق. اعجنها بقوة، مع إضافة قليل من الدقيق عند الحاجة، لمدة 8–10 دقائق تقريبًا حتى تصبح ناعمة ومرنة.","ادهن وعاءً كبيرًا بـ½ ملعقة صغيرة المتبقية من زيت الزيتون وضع العجينة داخله. قلّب العجينة لتتغطى بالزيت، ثم غطِّ الوعاء بغلاف بلاستيكي ومناشف مطبخ نظيفة. اتركها حتى يتضاعف حجمها، نحو 1½ ساعة.","سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية).","أخرج العجينة من الوعاء واقطع منها قطعة صغيرة. شكّلها على هيئة حبل بطول 6 بوصات وبسُمك قلم الرصاص تقريبًا، ثم شكّله على هيئة دائرة. اضغط الطرفين معًا بإحكام وضع الحلقة على صينية خبز غير مدهونة. كرّر العملية مع بقية العجينة. غطِّ الحلقات بمنشفة مطبخ نظيفة واتركها حتى يتضاعف حجمها، نحو ساعة.","افرد بياض البيض على وجه الحلقات بفرشاة واخبزها حتى تصبح ذهبية فاتحة، من 15 إلى 20 دقيقة. أخرجها واتركها تبرد على رف سلكي، ثم احفظها في وعاء محكم الغطاء لمدة تصل إلى شهر."])}))
R.append((6714664,{
"es":L("Bacalao con estragón y mostaza",
"La salsa de mostaza con limón aporta un sabor brillante a este bacalao asado. Se cocina rápidamente, por lo que es una comida fácil pero elegante para entre semana. Sírvalo con papas asadas y brócoli.",
"4","4 oz de pescado",
["1 limón mediano (cortado en gajos)","1/4 cucharadita de pimienta negra","1/4 cucharadita de sal","1 libra de filetes de bacalao (cortados en 4 porciones)","1 diente de ajo (picado)","1 cucharada de jugo de limón","1 cucharada de agua","1 1/2 cucharadas de aceite de oliva (dividido)","1/2 cucharada de mantequilla (blanda)","1 cucharada de estragón fresco (finamente picado)","2 cucharadas de mostaza Dijon de grano grueso"],
["Precaliente el horno a 450 °F.","En un tazón pequeño, mezcle la mostaza, el estragón, la mantequilla, 1 cucharada del aceite de oliva, el agua, el jugo de limón y el ajo; reserve.","Espolvoree el bacalao con la sal y la pimienta. En un sartén poco profundo que pueda ir al horno, caliente la 1/2 cucharada restante de aceite de oliva a fuego medio-alto. Agregue el bacalao y dórelo por un lado durante 4 minutos. Voltee el bacalao y dórelo durante 2 minutos por el otro lado.","Vierta la salsa de mostaza sobre el bacalao y coloque el sartén en el horno; áselo de 2 a 3 minutos. Sirva el bacalao con los gajos de limón."]),
"ar":L("سمك القد بالطرخون والخردل",
"تضيف صلصة الخردل بالليمون نكهة منعشة إلى سمك القد المشوي هذا. يُطهى بسرعة، فهو وجبة سهلة وأنيقة في الوقت نفسه لأيام الأسبوع. قدّمه مع البطاطس المشوية والبروكلي.",
"4","4 أونصات من السمك",
["1 ليمونة متوسطة (مقطعة إلى أرباع)","¼ ملعقة صغيرة من الفلفل الأسود","¼ ملعقة صغيرة من الملح","1 رطل من شرائح سمك القد (مقطعة إلى 4 حصص)","1 فص ثوم (مفروم)","1 ملعقة كبيرة من عصير الليمون","1 ملعقة كبيرة من الماء","1½ ملعقة كبيرة من زيت الزيتون (مقسّمة)","½ ملعقة كبيرة من الزبدة (طرية)","1 ملعقة كبيرة من الطرخون الطازج (مفروم ناعمًا)","2 ملعقة كبيرة من خردل ديجون الخشن"],
["سخّن الفرن مسبقًا إلى 450° فهرنهايت (230° مئوية).","في وعاء صغير، اخلط الخردل والطرخون والزبدة و1 ملعقة كبيرة من زيت الزيتون والماء وعصير الليمون والثوم؛ واتركه جانبًا.","رشّ سمك القد بالملح والفلفل. في مقلاة عميقة قليلًا تصلح للفرن، سخّن ½ ملعقة كبيرة المتبقية من زيت الزيتون على نار متوسطة إلى عالية. أضف السمك واكتفِ بتحميره من جانب واحد لمدة 4 دقائق. اقلب السمك وحمّره من الجانب الآخر لمدة دقيقتين.","اسكب صلصة الخردل فوق السمك وضع المقلاة في الفرن؛ واشوِه من 2 إلى 3 دقائق. قدّم السمك مع أرباع الليمون."])}))
R.append((6715369,{
"ar":L("التزاتزيكي والخضار",
"صلصة التزاتزيكي المتوسطية التقليدية مثالية لتغميس الخضار قليلة الكربوهيدرات وغير النشوية. ويمكن أيضًا استخدامها طبقة علوية على السلطات أو الساندويتشات أو اللفائف.",
"16","2 ملعقة كبيرة من التزاتزيكي + نحو ⅓ كوب من الخضار",
["2 كوب من الزبادي العادي (خالي الدسم)","½ خيارة متوسطة (مقشرة ومنزوعة البذور ومفرومة)","2 فص ثوم (كبير، مفروم)","½ ملعقة صغيرة من الشبت المجفف (يمكن استخدام 1 ملعقة كبيرة من الشبت الطازج المفروم بدلًا منه)","¼ ملعقة صغيرة من الملح","2 ملعقة صغيرة من عصير الليمون","1 ملعقة صغيرة من زيت الزيتون","6 أكواب من الخضار الطازجة (اختر تشكيلة: فاصولياء خضراء طازجة (مطهوة على البخار قليلًا)، فلفل أخضر أو أحمر أو أصفر، جزر، كرفس، كوسا، قرع أصفر، طماطم، خيار، فجل، بروكلي، وقرنبيط)"],
["قبل التقديم بـ12–24 ساعة، بطّن مصفاة بفلتر قهوة ورقي أو بقطعة قماش شاش للجبن. ضعها فوق وعاء. ضع الزبادي بالملعقة داخل فلتر القهوة وغطِّه وضعه في الثلاجة لمدة 12–14 ساعة.","سيصبح الزبادي الآن سميكًا. تخلّص من السائل المتجمع في الأسفل أو استخدمه في الحساء أو الخبز. أخرج الزبادي من الفلتر وضعه في وعاء صغير.","اخلط الخيار والثوم والشبت والملح وعصير الليمون وزيت الزيتون في الزبادي. ضعه في الثلاجة لمدة ساعة قبل التقديم.","قدّمه مع تشكيلة من الخضار مثل: الفاصولياء الخضراء الطازجة (مطهوة على البخار قليلًا)، والفلفل الرومي الأخضر أو الأحمر أو الأصفر، والجزر، والكرفس، والكوسا، والقرع الأصفر، والطماطم، والخيار، والفجل، والبروكلي، والقرنبيط."])}))
R.append((6715874,{
"es":L("Zanahorias al vapor",
"Información nutricional de las zanahorias al vapor",
"1","1/2 taza",
["1/2 taza de zanahorias"],
["Lave y pele las zanahorias.","Córtelas en rodajas, bastones o trozos pequeños para que se cocinen de manera uniforme.","Coloque una canasta vaporera en una olla y agregue aproximadamente una pulgada de agua.","Lleve el agua a ebullición a fuego medio.","Agregue las zanahorias a la canasta vaporera y tape la olla con una tapa.","Cocine las zanahorias al vapor durante unos 5–10 minutos, o hasta que estén tiernas al pincharlas con un tenedor.","Retire del fuego y sirva caliente."]),
"ar":L("جزر مطهو على البخار",
"المعلومات الغذائية للجزر المطهو على البخار",
"1","½ كوب",
["½ كوب من الجزر"],
["اغسل الجزر وقشّره.","قطّعه إلى شرائح أو أعواد أو قطع صغيرة لينضج بالتساوي.","ضع سلة بخار في قدر وأضف نحو بوصة واحدة من الماء.","اترك الماء حتى يغلي على نار متوسطة.","أضف الجزر إلى سلة البخار وغطِّ القدر بغطائه.","اطهِ الجزر على البخار لمدة 5–10 دقائق تقريبًا، أو حتى يلين عند وخزه بشوكة.","ارفعه عن النار وقدّمه دافئًا."])}))
R.append((6716322,{
"es":L("Bowl de desayuno de inspiración mexicana",
"Con un toque cítrico y un ligero picante, este bowl de desayuno de inspiración mexicana es un deleite para el paladar. Con verduras frescas y arroz de coliflor, es una manera baja en carbohidratos de comenzar el día.",
"4","1/4 de la receta (aproximadamente 245 g)",
["2 cucharadas de aceite de canola","1/2 taza de cebolla amarilla (en cubos)","1 1/2 tazas de arroz de coliflor congelado (arroz de coliflor)","1/2 taza de pimientos (en cubos)","2/3 taza de frijoles negros (escurridos y enjuagados)","1/2 cucharadita de comino molido","1/2 cucharadita de chile en polvo","1/2 cucharadita de pimienta negra","1/8 cucharadita de sal kosher","4 huevos grandes","1/2 taza de salsa","1/2 taza de cilantro fresco","1 lima entera (cortada en gajos, para servir)"],
["En un sartén, caliente el aceite a fuego medio.","Agregue la cebolla en cubos y cocine hasta que se ablande.","Incorpore el arroz de coliflor y cocine de 3 a 5 minutos, hasta que empiece a ablandarse.","Agregue al sartén los pimientos en cubos, los frijoles negros, el comino molido y el chile en polvo. Cocine otros 3–5 minutos. Sazone la mezcla con sal y pimienta.","Empuje la mezcla hacia un lado del sartén para formar huecos para los huevos.","Rompa un huevo en cada hueco y cocine hasta que las claras estén firmes pero las yemas aún estén líquidas. Si lo desea, tape el sartén para que los huevos se cocinen de manera más uniforme.","Cuando los huevos estén cocidos a su gusto, retire el sartén del fuego.","Divida el huevo, el arroz de coliflor y la mezcla de verduras en cuatro tazones.","Cubra cada tazón con salsa y cilantro fresco, si lo usa. Sirva con gajos de lima a un lado."]),
"ar":L("طبق إفطار مستوحى من المطبخ المكسيكي",
"بنكهته الحامضة ولمسته الخفيفة من التوابل الحارة، هذا الطبق المستوحى من المطبخ المكسيكي متعة للذوق. مع الخضار الطازجة وأرز القرنبيط، فهو طريقة قليلة الكربوهيدرات لبدء يومك.",
"4","¼ الوصفة (نحو 245 غ)",
["2 ملعقة كبيرة من زيت الكانولا","½ كوب من البصل الأصفر (مقطع مكعبات)","1½ كوب من أرز القرنبيط المجمد (أرز القرنبيط)","½ كوب من الفلفل الرومي (مقطع مكعبات)","⅔ كوب من الفاصولياء السوداء (مصفاة ومشطوفة)","½ ملعقة صغيرة من الكمون المطحون","½ ملعقة صغيرة من مسحوق الفلفل الحار (تشيلي)","½ ملعقة صغيرة من الفلفل الأسود","⅛ ملعقة صغيرة من الملح الخشن (كوشير)","4 بيضات كبيرة","½ كوب من الصلصة (سالسا)","½ كوب من الكزبرة الخضراء الطازجة","1 ليمونة خضراء كاملة (مقطعة إلى أرباع، للتقديم)"],
["في مقلاة، سخّن الزيت على نار متوسطة.","أضف البصل المقطع مكعبات واطهِه حتى يذبل.","أضف أرز القرنبيط وقلّبه واطهِه من 3 إلى 5 دقائق حتى يبدأ بالليونة.","أضف الفلفل الرومي المقطع مكعبات والفاصولياء السوداء والكمون المطحون ومسحوق الفلفل الحار إلى المقلاة. اطهِ لمدة 3–5 دقائق إضافية. تبّل الخليط بالملح والفلفل.","ادفع الخليط إلى جانب المقلاة لتصنع حفرًا للبيض.","اكسر بيضة في كل حفرة واطهِها حتى يتماسك البياض بينما يبقى الصفار سائلًا. إن رغبت، غطِّ المقلاة ليُطهى البيض بشكل أكثر تجانسًا.","عندما ينضج البيض حسب رغبتك، ارفع المقلاة عن النار.","وزّع البيض وأرز القرنبيط وخليط الخضار على أربعة أوعية.","ضع فوق كل وعاء الصلصة والكزبرة الخضراء الطازجة، إن رغبت. قدّمه مع أرباع الليمون الأخضر على الجانب."])}))
R.append((6719399,{
"ar":L("سموذي فواكه الصيف",
"استفد من فواكه الصيف الطازجة لتحضير سموذي منعش! أو استخدم الفواكه المجمدة لتستمتع بنكهات الصيف في أي وقت من السنة.",
"4","1 كوب",
["1 كوب من التوت الأزرق الطازج","1 كوب من الفراولة الطازجة المفرومة","2 حبة خوخ (مقشرة ومنزوعة النواة ومفرومة)","6 أونصات من الزبادي اليوناني بنكهة الخوخ (خالي الدسم)","1 كوب من حليب اللوز (غير محلّى)","2 ملعقة كبيرة من بذور الكتان المطحونة","½ كوب من الثلج"],
["ضع جميع المكونات في الخلاط وامزجها حتى تصبح ناعمة."])}))
R.append((6720715,{
"ar":L("سلطة الخيار والطماطم الصيفية البسيطة",
"لا تدع بساطة هذه السلطة تخدعك، فهي بسيطة لكنها منعشة ولذيذة بشكل لا يصدّق. إنها طبق جانبي مثالي لحفلات الشواء الصيفية!",
"4","1 كوب",
["1 خيارة كبيرة (مقشرة ومقطعة إلى نصفين)","10½ أونصات من الطماطم الكرزية","¼ كوب من البصل الأحمر (مقطع مكعبات)","2 ملعقة كبيرة من خل النبيذ الأحمر","⅛ ملعقة صغيرة من الفلفل الأسود","1 ملعقة كبيرة من زيت الزيتون","⅛ ملعقة صغيرة من الملح الخشن (كوشير)"],
["اقطع كل نصف خيارة إلى نصفين ثم إلى قطع كبيرة. اقطع الطماطم الكرزية إلى نصفين.","ضع الخيار في وعاء السلطة مع الطماطم الكرزية والبصل الأحمر المقطع مكعبات.","في وعاء صغير، اخفق معًا خل النبيذ الأحمر والفلفل الأسود وزيت الزيتون والملح. اسكب الصلصة فوق السلطة وقدّمها."])}))
R.append((6722950,{
"ar":L("حساء العدس المتوسطي",
"العدس مصدر صحي جدًا للكربوهيدرات وغني بالألياف. يمكن تجميد هذا الحساء جيدًا إن أردت الاحتفاظ بجزء منه ليوم آخر.",
"8","نحو 1 كوب",
["2 ملعقة صغيرة من زيت الكانولا","1 بصلة متوسطة (مقطعة مكعبات)","2 فص ثوم (مفروم)","6 أونصات من نقانق الديك الرومي الإيطالية (أخرج اللحم من الغلاف، مقطعة)","32 أونصة من مرق الدجاج قليل الصوديوم (منخفض الصوديوم، خالي الدسم)","1 علبة من الطماطم المعلبة المقطعة (14 أونصة، مقطعة مكعبات)","3 أكواب من الماء","1 كوب من العدس الجاف","½ ملعقة صغيرة من الفلفل الأسود","¼ ملعقة صغيرة من الأوريجانو المجفف","1 ورقة غار"],
["سخّن الزيت في قدر حساء كبير على نار متوسطة إلى عالية. أضف البصل وقلّبه لمدة 3 دقائق أو حتى يصبح شفافًا. أضف الثوم وقلّبه لمدة 30 ثانية.","أضف نقانق الديك الرومي الإيطالية واطهِها نحو 8 دقائق حتى تتحمّر. أضف بقية المكونات.","اترك الحساء حتى يغلي؛ ثم خفّف الحرارة واتركه على نار هادئة لمدة 15 دقيقة."])}))
save("out_c20_part1.json",R)
