from h import *
R=[]
R.append((6724295,{
"es":L("Ejotes franceses con avellanas (Fagiolini alle nocciole)",
"La combinación clásica de ejotes y avellanas es tan saludable como sabrosa. En Italia se encuentran variaciones de este plato durante la temporada adecuada. Las avellanas son uno de los cultivos más antiguos de Europa; existen registros de su comercio desde los puertos de Génova que se remontan al siglo XI. En la actualidad, Turquía e Italia producen la mayor parte de las avellanas del mundo.",
"6","1/2 taza",
["1 1/2 libras de ejotes franceses (haricots verts) (con los extremos del tallo recortados)","2 cucharadas de aceite de oliva extra virgen (dividido)","1 cebolla amarilla mediana (en cubos)","1/2 cucharadita de sal marina","1/8 cucharadita de pimienta negra (recién molida)","1/3 taza de avellanas, sin piel"],
["Precaliente el horno a 375 °F.","Lleve a ebullición una olla con agua. Agregue los ejotes franceses. Reduzca el fuego a medio y cocine hasta que estén apenas tiernos, de 3 a 4 minutos. Escúrralos y sumérjalos en un baño de agua con hielo para enfriarlos. Escúrralos y reserve. (Esto se puede hacer con un día de anticipación).","Caliente 1 cucharada de aceite en un sartén grande y ancho a fuego medio. Agregue la cebolla, la sal y la pimienta, y cocine, revolviendo de vez en cuando, hasta que la cebolla esté dorada claro, de 4 a 5 minutos.","Mientras tanto, coloque las avellanas en una bandeja para hornear y tuéstelas en el horno hasta que se oscurezcan, de 5 a 7 minutos. Pique grueso y reserve.","En un sartén grande, caliente la 1 cucharada restante de aceite de oliva a fuego medio-alto. Agregue los ejotes franceses y cocine, revolviendo de vez en cuando, hasta que se calienten por completo, aproximadamente 3 minutos. Agregue la cebolla cocida y las avellanas y cocine 1 minuto más. Pase a un platón y sirva."]),
"ar":L("فاصولياء خضراء رفيعة مع البندق (فاجيوليني آلي نوتشوليه)",
"المزيج الكلاسيكي من الفاصولياء الخضراء والبندق صحي بقدر ما هو لذيذ. وتوجد أصناف مختلفة من هذا الطبق في أنحاء إيطاليا خلال الموسم المناسب. يُعد البندق من أقدم المحاصيل المزروعة في أوروبا؛ وتعود السجلات التي تذكر تجارته عبر ميناء جنوة إلى القرن الحادي عشر. وفي الوقت الحاضر، تنتج تركيا وإيطاليا معظم البندق في العالم.",
"6","½ كوب",
["1½ رطل من الفاصولياء الخضراء الرفيعة (هاريكو فير) (مع قطع أطراف السيقان)","2 ملعقة كبيرة من زيت الزيتون البكر الممتاز (مقسّمة)","1 بصلة صفراء متوسطة (مقطعة مكعبات)","½ ملعقة صغيرة من ملح البحر","⅛ ملعقة صغيرة من الفلفل الأسود (مطحون طازجًا)","⅓ كوب من البندق، منزوع القشرة"],
["سخّن الفرن مسبقًا إلى 375° فهرنهايت (190° مئوية).","اترك قدرًا من الماء حتى يغلي. أضف الفاصولياء الخضراء الرفيعة. خفّف الحرارة إلى متوسطة واطهِها حتى تلين قليلًا، من 3 إلى 4 دقائق. صفِّها وضعها في حمام من الماء المثلّج لتبرد. صفِّها واتركها جانبًا. (يمكن تحضير هذه الخطوة قبل يوم كامل).","سخّن 1 ملعقة كبيرة من الزيت في مقلاة كبيرة وواسعة على نار متوسطة. أضف البصل والملح والفلفل واطهِ مع التقليب من حين لآخر حتى يصبح البصل بنيًّا ذهبيًّا فاتحًا، من 4 إلى 5 دقائق.","في هذه الأثناء، ضع البندق في صينية خبز وحمّصه في الفرن حتى يغمق لونه، من 5 إلى 7 دقائق. افرمه فرمًا خشنًا واتركه جانبًا.","في مقلاة كبيرة، سخّن 1 ملعقة كبيرة المتبقية من زيت الزيتون على نار متوسطة إلى عالية. أضف الفاصولياء الخضراء الرفيعة واطهِ مع التقليب من حين لآخر حتى تسخن تمامًا، نحو 3 دقائق. أضف البصل المطهو والبندق واطهِ دقيقة إضافية واحدة. انقلها إلى طبق التقديم وقدّمها."])}))
R.append((6724403,{
"ar":L("موس الشوكولاتة بالزبادي اليوناني",
"هل تُحضّر حلوى لمناسبة خاصة؟ يمكن تحضير هذه الحلوى المشبعة مسبقًا وحفظها في الثلاجة. وقبل التقديم مباشرة، وزّعها في حصص وضع فوقها الكريمة المخفوقة.",
"6","⅓ كوب مكتنز مع ⅓ كوب من توت العليق و1 ملعقة كبيرة من الكريمة المخفوقة",
["6 ألواح صغيرة من الشوكولاتة الداكنة الخالية من السكر (مفرومة)","2 كوب من الزبادي اليوناني الطبيعي خالي الدسم (خالي الدسم)","2 ملعقة كبيرة من العسل أو 4 أكياس من المحلّي الصناعي","1 ملعقة صغيرة من خلاصة الفانيليا","¼ كوب من الحليب منزوع الدسم","6 ملاعق كبيرة من الكريمة المخفوقة (خالية الدسم)","2 كوب من توت العليق الطازج"],
["ضع الشوكولاتة المفرومة في وعاء صالح للميكروويف. سخّن الشوكولاتة في الميكروويف على درجة حرارة عالية لمدة دقيقة واحدة ثم قلّبها. إن لم تذب تمامًا، سخّنها 30 ثانية أخرى ثم قلّبها حتى تذوب جميع القطع. وإن لم تذب بعد، سخّنها 30 ثانية أخرى وواصل التقليب، فقط حتى تذوب القطع الموجودة في الشوكولاتة. لا تفرط في تسخينها.","في وعاء خلط متوسط، اخفق الزبادي اليوناني بخلاط كهربائي حتى يصبح هشًّا. أضف العسل والفانيليا والحليب، واخفق أكثر، ثم أضف الشوكولاتة بكميات صغيرة، مع الخفق بين كل إضافة وأخرى.","بعد خلط كل الشوكولاتة في الزبادي، قسّم الموس إلى 6 حصص وضع فوق كل حصة ⅓ كوب من توت العليق و1 ملعقة كبيرة من الكريمة المخفوقة"])}))
R.append((6726437,{
"es":L("Champiñones rellenos",
"Este aperitivo bajo en carbohidratos seguramente gustará a todos. Las recetas de champiñones rellenos suelen tener muchas calorías, pero la salchicha de pavo y el queso reducido en grasa de esta receta ayudan a ahorrar calorías sin perder un sabor intenso.",
"6","1 champiñón",
["1 rociada, 0.25 g de aceite antiadherente en aerosol para cocinar","6 champiñones blancos (de botón) extragrandes (aproximadamente 8 oz)","2 cucharaditas de aceite de oliva (dividido)","2 cucharaditas de vinagre balsámico","1/4 de cebolla pequeña (en cubos)","1/4 de pimiento verde mediano (en cubos)","2 oz de salchicha magra de pavo para desayuno","2 cucharadas de pan rallado sin gluten","1 cucharada de queso mozzarella rallado reducido en grasa","1 cucharada de queso parmesano rallado"],
["Precaliente el horno a 325 grados F. Rocíe con aceite en aerosol una fuente cuadrada para hornear.","Quite los tallos de los champiñones y píquelos finamente. Reserve los tallos.","Coloque los sombreros de los champiñones en un tazón y mézclelos con 1 cucharadita de aceite de oliva y el vinagre balsámico. Reserve los sombreros.","Caliente la cucharadita restante de aceite de oliva en un sartén mediano a fuego medio. Agregue la cebolla, el pimiento verde y los tallos de los champiñones y saltee durante 3 minutos. Agregue la salchicha y cocine otros 8 a 10 minutos, revolviendo con frecuencia, hasta que la salchicha esté completamente dorada.","Agregue el pan rallado, revolviendo para combinarlo de manera uniforme con todos los demás ingredientes. Incorpore el queso mozzarella y deje que se derrita.","Retire el sartén del fuego e incorpore el queso parmesano.","Rellene generosamente cada champiñón con la mezcla de salchicha (aproximadamente 1 cucharada colmada por sombrero). Acomode los champiñones en la fuente para hornear y hornee durante 40 minutos o hasta que el relleno esté crujiente por encima."]),
"ar":L("فطر محشو",
"هذه المقبلات قليلة الكربوهيدرات ستنال بالتأكيد إعجاب الجميع. وصفات الفطر المحشو عادةً مليئة بالسعرات الحرارية، لكن نقانق الديك الرومي والجبن قليل الدسم في هذه الوصفة تساعد على توفير السعرات مع الحفاظ على نكهة قوية.",
"6","1 حبة فطر",
["1 رشة، 0.25 غ من بخاخ الطهي غير اللاصق","6 حبات فطر أبيض (فطر الأزرار) كبيرة جدًا (نحو 8 أونصات)","2 ملعقة صغيرة من زيت الزيتون (مقسّمة)","2 ملعقة صغيرة من خل البلسميك","¼ بصلة صغيرة (مقطعة مكعبات)","¼ حبة فلفل رومي أخضر متوسطة (مقطعة مكعبات)","2 أونصة من نقانق الإفطار الخالية من الدهن المصنوعة من الديك الرومي","2 ملعقة كبيرة من فتات الخبز الخالي من الغلوتين","1 ملعقة كبيرة من جبن الموزاريلا المبشور قليل الدسم","1 ملعقة كبيرة من جبن البارميزان المبشور"],
["سخّن الفرن مسبقًا إلى 325 درجة فهرنهايت (165° مئوية). رشّ طبق خبز مربعًا ببخاخ الطهي.","انزع سيقان الفطر وافرمها ناعمًا. اترك السيقان جانبًا.","ضع قبعات الفطر في وعاء وقلّبها مع 1 ملعقة صغيرة من زيت الزيتون وخل البلسميك. اترك القبعات جانبًا.","سخّن ملعقة زيت الزيتون الصغيرة المتبقية في مقلاة متوسطة على نار متوسطة. أضف البصل والفلفل الأخضر وسيقان الفطر وقلّبها لمدة 3 دقائق. أضف النقانق واطهِ لمدة 8 إلى 10 دقائق إضافية مع التقليب المتكرر حتى تتحمّر النقانق تمامًا.","أضف فتات الخبز مع التقليب ليتجانس مع بقية المكونات. أضف جبن الموزاريلا وحرّكه حتى يذوب.","ارفع المقلاة عن النار وأضف جبن البارميزان مع التحريك.","املأ كل حبة فطر بسخاء بخليط النقانق (نحو 1 ملعقة كبيرة مكتنزة لكل قبعة). رتّب الفطر في طبق الخبز واخبزه لمدة 40 دقيقة أو حتى تصبح الحشوة مقرمشة من الأعلى."])}))
R.append((6726593,{
"es":L("Ensalada griega con garbanzos",
"Disfrute los sabores del Mediterráneo con esta versión apta para personas con diabetes de la ensalada griega con garbanzos. Llena de proteína de origen vegetal y verduras frescas, es un plato rápido y fácil que sacia lo suficiente como para ser una comida completa.",
"4","1 tazón",
["1 cabeza de lechuga romana (en tiras)","4 tomates roma (tipo pera) medianos (maduros, cortados en gajos)","1 pepino mediano (en cubos)","1 pimiento rojo mediano (picado)","1/2 cebolla morada mediana (en rodajas finas)","1/2 taza de aceitunas negras (en rodajas)","2 cucharadas de queso feta (desmenuzado)","1 lata (15 oz) de garbanzos en lata (sin sal añadida, escurridos y enjuagados)","2 cucharadas de aceite de oliva extra virgen","1 cucharada de vinagre de vino tinto","1 cucharadita de orégano seco","1/4 cucharadita de pimienta negra"],
["En un tazón grande para ensalada, mezcle la lechuga romana, los tomates, el pepino, el pimiento rojo, la cebolla morada, las aceitunas, el queso feta y los garbanzos.","En un tazón pequeño, bata juntos el aceite de oliva extra virgen, el vinagre de vino tinto, el orégano seco y la pimienta para preparar el aderezo.","Vierta el aderezo sobre la ensalada y mezcle suavemente hasta que todos los ingredientes queden bien cubiertos."]),
"ar":L("سلطة يونانية بالحمص",
"استمتع بنكهات البحر المتوسط مع هذه النسخة المناسبة لمرضى السكري من السلطة اليونانية بالحمص. وهي غنية بالبروتين النباتي والخضار الطازجة، وطبق سريع وسهل ومشبع بما يكفي ليكون وجبة كاملة.",
"4","1 وعاء",
["1 رأس خس روماني (مقطع شرائح)","4 حبات طماطم روما (برقوقية) متوسطة (ناضجة، مقطعة إلى أرباع)","1 خيارة متوسطة (مقطعة مكعبات)","1 حبة فلفل رومي أحمر متوسطة (مفرومة)","½ بصلة حمراء متوسطة (مقطعة إلى شرائح رفيعة)","½ كوب من الزيتون الأسود (مقطع شرائح)","2 ملعقة كبيرة من جبن الفيتا (مفتّت)","1 علبة (15 أونصة) من الحمص المعلب (بدون ملح مضاف، مصفّى ومشطوف)","2 ملعقة كبيرة من زيت الزيتون البكر الممتاز","1 ملعقة كبيرة من خل النبيذ الأحمر","1 ملعقة صغيرة من الأوريجانو المجفف","¼ ملعقة صغيرة من الفلفل الأسود"],
["في وعاء سلطة كبير، اخلط الخس الروماني والطماطم والخيار والفلفل الرومي الأحمر والبصل الأحمر والزيتون وجبن الفيتا والحمص.","في وعاء صغير، اخفق معًا زيت الزيتون البكر الممتاز وخل النبيذ الأحمر والأوريجانو المجفف والفلفل لتحضير الصلصة.","اسكب الصلصة فوق السلطة وقلّب برفق حتى تتغطى جميع المكونات جيدًا."])}))
R.append((6729043,{
"es":L("Garbanzos cacio e pepe",
"Todo el sabor a pimienta y queso del clásico cacio e pepe, reinventado con garbanzos crujientes para un plato rápido y satisfactorio, alto en fibra y lleno de sabor salado de inspiración italiana.",
"6","1/2 taza",
["1 1/2 cucharadas de aceite de oliva","2 latas (15 oz) de garbanzos en lata (sin sal añadida, escurridos y enjuagados)","2 cucharaditas de pimienta negra (recién molida)","1/2 taza de queso pecorino romano (finamente rallado)","1/4 cucharadita de sal"],
["En un sartén grande, caliente el aceite de oliva a fuego medio.","Agregue al sartén los garbanzos escurridos y enjuagados, extendiéndolos en una sola capa.","Saltee los garbanzos de 5 a 7 minutos, revolviendo de vez en cuando, hasta que estén ligeramente dorados y un poco crujientes.","Espolvoree la pimienta negra recién molida sobre los garbanzos y mezcle para cubrirlos.","Agregue al sartén el queso pecorino romano finamente rallado. Mezcle los garbanzos hasta que queden cubiertos de manera uniforme con el queso.","Cocine otros 2–3 minutos, hasta que el queso se derrita y forme una cobertura cremosa.","Sazone con sal.","Retire el sartén del fuego."]),
"ar":L("حمص بالجبن والفلفل الأسود (كاتشو إي بيبي)",
"كل نكهة الفلفل والجبن في طبق كاتشو إي بيبي الكلاسيكي، بحلّة جديدة مع الحمص المقرمش، لطبق سريع ومُشبع غني بالألياف ومليء بالنكهة المالحة المستوحاة من المطبخ الإيطالي.",
"6","½ كوب",
["1½ ملعقة كبيرة من زيت الزيتون","2 علبة (15 أونصة) من الحمص المعلب (بدون ملح مضاف، مصفّى ومشطوف)","2 ملعقة صغيرة من الفلفل الأسود (مطحون طازجًا)","½ كوب من جبن البيكورينو رومانو (مبشور ناعمًا)","¼ ملعقة صغيرة من الملح"],
["في مقلاة كبيرة، سخّن زيت الزيتون على نار متوسطة.","أضف الحمص المصفّى والمشطوف إلى المقلاة، ووزّعه في طبقة واحدة.","قلّب الحمص لمدة 5–7 دقائق مع التحريك من حين لآخر حتى يصبح ذهبيًّا فاتحًا ومقرمشًا قليلًا.","رشّ الفلفل الأسود المطحون طازجًا فوق الحمص وقلّبه ليتغطى به.","أضف جبن البيكورينو رومانو المبشور ناعمًا إلى المقلاة. قلّب الحمص حتى يتغطى بالجبن بالتساوي.","واصل الطهي لمدة 2–3 دقائق إضافية حتى يذوب الجبن ويشكّل طبقة كريمية.","تبّل بالملح.","ارفع المقلاة عن النار."])}))
R.append((6730582,{
"es":L("Huevos a la turca con yogur griego con hierbas",
"Esta versión de los huevos a la turca combina en capas yogur griego cremoso con hierbas, huevos pochados en su punto y un chorrito de aceite de oliva aromático con especias. La combinación de yogur y huevos, ricos en proteína, resulta en un desayuno que sacia y es apto para controlar la glucosa en la sangre (azúcar en la sangre). Servido con pan de granos germinados o solo, es una opción sabrosa para quienes desean equilibrar los carbohidratos sin sacrificar el sabor.",
"4","1 huevo + 1/2 taza de yogur con hierbas",
["2 tazas de yogur griego natural sin grasa","2 dientes de ajo (picados)","2 cucharadas de hierbas frescas (picadas, como eneldo o perejil, y más para decorar)","1 cucharadita de ralladura de limón","2 cucharadas de aceite de oliva","1 cucharadita de pimentón ahumado","1/2 cucharadita de comino","1/2 cucharadita de hojuelas de pimiento rojo triturado (opcional)","4 huevos grandes","2 cucharadas de vinagre blanco","1/2 cucharadita de sal","1/2 cucharadita de pimienta negra","2 rebanadas de pan Ezekiel de granos germinados"],
["En un tazón mediano, mezcle el yogur griego, el ajo, las hierbas frescas y la ralladura de limón. Sazone con 1/4 de cucharadita de sal y 1/4 de cucharadita de pimienta. Reserve a temperatura ambiente.","Prepare el aceite con especias. En una sartén pequeña a fuego bajo, caliente el aceite de oliva con el pimentón, el comino y las hojuelas de pimiento rojo. Revuelva durante 30 segundos hasta que desprenda aroma. Retire del fuego y reserve.","Llene una cacerola mediana con 2–3 pulgadas de agua y lleve a un hervor suave. Agregue el vinagre. Rompa los huevos en tazones pequeños. Revuelva el agua en círculos y deslice los huevos con cuidado. Cocine de 3 a 4 minutos, hasta que las claras estén firmes pero las yemas aún estén líquidas. Con una espumadera, pase los huevos a un plato forrado con toallas de papel.","Divida la mezcla de yogur griego entre los tazones. Cubra con los huevos pochados y rocíe con el aceite de oliva con especias. Decore con más hierbas frescas y con la 1/4 de cucharadita restante de sal y la 1/4 de cucharadita restante de pimienta negra.","Acompañe cada porción con 1/2 rebanada de pan integral de granos germinados."]),
"ar":L("البيض التركي مع الزبادي اليوناني بالأعشاب",
"هذه نسخة مبتكرة من البيض التركي تضع طبقات من الزبادي اليوناني الكريمي بالأعشاب مع بيض مسلوق على طريقة البوشيه بإتقان وقليل من زيت الزيتون المعطّر بالتوابل. يجعل مزيج الزبادي والبيض الغنيين بالبروتين منه إفطارًا مشبعًا ومناسبًا لضبط مستوى الغلوكوز في الدم (سكر الدم). يُقدَّم مع خبز الحبوب المنبّتة أو وحده، وهو خيار لذيذ لمن يرغب في موازنة الكربوهيدرات دون التضحية بالطعم.",
"4","1 بيضة + ½ كوب من الزبادي بالأعشاب",
["2 كوب من الزبادي اليوناني الطبيعي خالي الدسم","2 فص ثوم (مفروم)","2 ملعقة كبيرة من الأعشاب الطازجة (مفرومة، مثل الشبت أو البقدونس، وكمية إضافية للتزيين)","1 ملعقة صغيرة من قشر الليمون المبشور","2 ملعقة كبيرة من زيت الزيتون","1 ملعقة صغيرة من البابريكا المدخنة","½ ملعقة صغيرة من الكمون","½ ملعقة صغيرة من رقائق الفلفل الأحمر المجروشة (اختياري)","4 بيضات كبيرة","2 ملعقة كبيرة من الخل الأبيض","½ ملعقة صغيرة من الملح","½ ملعقة صغيرة من الفلفل الأسود","2 شريحة من خبز إزيكيل المنبّت"],
["في وعاء متوسط، اخلط الزبادي اليوناني والثوم والأعشاب الطازجة وقشر الليمون المبشور. تبّل بـ¼ ملعقة صغيرة من الملح و¼ ملعقة صغيرة من الفلفل. اتركه جانبًا في درجة حرارة الغرفة.","حضّر الزيت المتبّل. في قدر صغير على نار هادئة، سخّن زيت الزيتون مع البابريكا والكمون ورقائق الفلفل الأحمر. حرّك لمدة 30 ثانية حتى تفوح الرائحة. ارفعه عن النار واتركه جانبًا.","املأ قدرًا متوسطًا بـ2-3 بوصات من الماء واتركه حتى يصل إلى غليان هادئ. أضف الخل. اكسر البيض في أوعية صغيرة. حرّك الماء بحركة دائرية ثم أنزل البيض برفق. اطهِه لمدة 3-4 دقائق حتى يتماسك البياض ويبقى الصفار سائلًا. استخدم ملعقة مثقبة لنقل البيض إلى طبق مبطن بمناشف ورقية.","وزّع خليط الزبادي اليوناني على الأوعية. ضع فوقه البيض المسلوق وانثر زيت الزيتون المتبّل. زيّنه بمزيد من الأعشاب الطازجة و¼ ملعقة صغيرة المتبقية من الملح و¼ ملعقة صغيرة المتبقية من الفلفل الأسود.","قدّم مع كل حصة ½ شريحة من خبز الحبوب الكاملة المنبّتة."])}))
R.append((6732979,{
"ar":L("أجنحة دجاج حارة مخبوزة مع صلصة الكزبرة والليمون الأخضر",
"هذه نسخة مناسبة لمرضى السكري من أجنحة الدجاج على طريقة بوفالو، تستغني عن القلي العميق وتقدّم أجنحة بنية ذهبية لذيذة بشكل لا يصدّق بالقدر المناسب من التوابل. أحضر المناديل الورقية، فهذه وجبة لذيذة ليوم المباراة ستعجبك وتعجب بقية المشجعين! وبدلًا من صلصة الجبن الأزرق، نقترح استخدام صلصة الكزبرة والليمون الأخضر اللذيذة لدينا.",
"8","3 أجنحة أو دبابيس، 2 ملعقة كبيرة من الصلصة",
["2 رشة، 0.5 غ من بخاخ الطهي غير اللاصق","2 رطل من أجنحة الدجاج الكاملة","½ كوب من مربى المشمش بدون سكر مضاف (مخفض السكر)","1 ملعقة كبيرة من الثوم (مفروم، احتفظ بـ½ ملعقة صغيرة)","1 ملعقة كبيرة من صلصة الصويا قليلة الصوديوم","1 ملعقة صغيرة من صلصة الفلفل والثوم على الطريقة التايلندية","2 ملعقة كبيرة من عصير الليمون الأخضر (مقسّمة)","½ ملعقة صغيرة من الفلفل الأسود (مقسّمة)","1 كوب من الزبادي اليوناني الطبيعي خالي الدسم (خالي الدسم)","¼ كوب من الكزبرة الخضراء الطازجة (مفرومة)"],
["سخّن الفرن مسبقًا إلى 375 درجة فهرنهايت (190° مئوية).","رشّ صينية خبز ببخاخ الطهي. انزع الجلد عن الأجنحة. ضع أجنحة الدجاج في طبقة واحدة على الصينية وارشّها مرة أخرى ببخاخ الطهي.","اخبزها لمدة 10 دقائق. وبينما يُخبز الدجاج، اخفق معًا مربى المشمش و2½ ملعقة صغيرة من الثوم وصلصة الصويا وصلصة الفلفل والثوم وعصير الليمون الأخضر و¼ ملعقة صغيرة من الفلفل الأسود المطحون، واتركه جانبًا.","بعد أن تبقى الأجنحة في الفرن لمدة 10 دقائق، اطلها بسخاء بخليط مربى المشمش. أعدها إلى الفرن لمدة 15 دقيقة أخرى أو حتى تنضج الأجنحة تمامًا ويتكرمل الطلاء.","في وعاء صغير، اخفق معًا الزبادي اليوناني و1 ملعقة كبيرة من عصير الليمون الأخضر والكزبرة الخضراء و¼ ملعقة صغيرة من الفلفل الأسود المطحون. قدّم صلصة التغميس مع الأجنحة الحارة."])}))
R.append((6733514,{
"es":L("Pechuga de pavo con especias y chutney de manzana",
"Esta pechuga de pavo con especias y chutney de manzana es una sabrosa mezcla de salado y dulce. El pavo se sazona con especias cálidas, mientras que el chutney de manzana aporta un toque de dulzor natural. Es una manera fácil de añadir un sabor intenso a una comida sencilla, muy baja en grasa y baja en carbohidratos.",
"16","3 oz de pavo + 2 cucharadas de chutney",
["1 pechuga, de aproximadamente 4–6 libras de pechuga de pavo","3 cucharadas de jugo de naranja","2 1/2 cucharaditas de jengibre fresco (pelado y rallado, dividido)","1 1/4 cucharaditas de canela molida (dividida)","1 1/4 cucharaditas de clavo molido (dividido)","1 cucharadita de pimienta de Jamaica molida","1/4 cucharadita de sal","1/4 cucharadita de pimienta negra","1 cebolla morada mediana (finamente picada)","1/3 taza de azúcar morena","1/4 taza de vinagre de arroz","2 cucharadas de pasas","1/4 cucharadita de hojuelas de pimiento rojo trituradas","3 tazas de manzana (en cubos)"],
["Precaliente el horno a 400 grados F. Seque la pechuga de pavo con toallas de papel y colóquela sobre una rejilla dentro de una bandeja de asar poco profunda. Afloje la piel introduciendo los dedos y empujando suavemente entre la piel y la carne.","En un tazón pequeño, mezcle el jugo de naranja, 2 cucharaditas del jengibre, 1 cucharadita de la canela, 1 cucharadita del clavo, la pimienta de Jamaica, la sal y la pimienta negra. Frote esta mezcla sobre la carne de la pechuga, debajo de la piel. Ase la pechuga sin tapar durante aproximadamente 1 hora y 15 minutos, o hasta que un termómetro para carne marque 170 grados F, cuidando que no toque el hueso del pecho. Revise el pavo cada 15 minutos más o menos mientras se asa para evitar que se dore en exceso. Cubra con papel aluminio si la carne de la pechuga empieza a dorarse demasiado. Después de 30 minutos de asado, también puede bajar el horno a 350 grados si el pavo se está cocinando demasiado rápido.","Mientras tanto, prepare el chutney. En una cacerola, mezcle la cebolla morada, el azúcar morena, el vinagre de arroz, las pasas, la 1/2 cucharadita restante de jengibre, la 1/4 de cucharadita restante de canela, la 1/4 de cucharadita restante de clavo y el pimiento rojo triturado, y lleve a ebullición. Tape, reduzca el fuego y cocine a fuego lento durante 5 minutos. Retire la cacerola del fuego y deje enfriar durante 10 minutos. Incorpore las manzanas con movimientos envolventes.","Pase la pechuga de pavo a una fuente y déjela reposar, cubierta sin apretar con papel aluminio, durante unos 10 minutos antes de servir.","Para servir, rebane el pavo, deseche la piel y sírvalo con el chutney. Guarde la 1 taza restante de chutney, tapada, en el refrigerador hasta por tres días."]),
"ar":L("صدر ديك رومي متبّل مع شتني التفاح",
"صدر الديك الرومي المتبّل مع شتني التفاح مزيج لذيذ بين المالح والحلو. يُتبّل الديك الرومي ببهارات دافئة، بينما يضيف شتني التفاح لمسة من الحلاوة الطبيعية. إنها طريقة سهلة لإضفاء نكهة قوية على وجبة بسيطة قليلة الدسم جدًا وقليلة الكربوهيدرات.",
"16","3 أونصات من الديك الرومي + 2 ملعقة كبيرة من الشتني",
["1 صدر، نحو 4-6 أرطال من صدر الديك الرومي","3 ملاعق كبيرة من عصير البرتقال","2½ ملعقة صغيرة من الزنجبيل الطازج (مقشر ومبشور، مقسّم)","1¼ ملعقة صغيرة من القرفة المطحونة (مقسّمة)","1¼ ملعقة صغيرة من القرنفل المطحون (مقسّم)","1 ملعقة صغيرة من بهار الأليسبايس المطحون","¼ ملعقة صغيرة من الملح","¼ ملعقة صغيرة من الفلفل الأسود","1 بصلة حمراء متوسطة (مفرومة ناعمًا)","⅓ كوب من السكر البني","¼ كوب من خل الأرز","2 ملعقة كبيرة من الزبيب","¼ ملعقة صغيرة من رقائق الفلفل الأحمر المجروشة","3 أكواب من التفاح (مقطع مكعبات)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية). جفّف صدر الديك الرومي بالتربيت عليه وضعه على رف داخل صينية شواء قليلة العمق. افصل الجلد برفق بإدخال أصابعك ودفعها بين الجلد واللحم.","في وعاء صغير، اخلط عصير البرتقال و2 ملعقة صغيرة من الزنجبيل و1 ملعقة صغيرة من القرفة و1 ملعقة صغيرة من القرنفل والأليسبايس والملح والفلفل الأسود. افرك هذا الخليط على لحم الصدر تحت الجلد. اشوِ الصدر مكشوفًا لمدة ساعة و15 دقيقة تقريبًا، أو حتى يسجّل ميزان حرارة اللحم 170 درجة فهرنهايت (75° مئوية)، مع الحرص على ألا يلامس عظمة الصدر. افحص الديك الرومي كل 15 دقيقة تقريبًا أثناء الشواء لتجنّب الإفراط في التحمير. غطِّه بورق الألمنيوم إذا بدأ لحم الصدر يحمرّ أكثر من اللازم. وبعد 30 دقيقة من الشواء، يمكنك أيضًا خفض حرارة الفرن إلى 350 درجة (175° مئوية) إذا كان الديك الرومي ينضج بسرعة كبيرة.","في هذه الأثناء، حضّر الشتني. في قدر، اخلط البصل الأحمر والسكر البني وخل الأرز والزبيب و½ ملعقة صغيرة المتبقية من الزنجبيل و¼ ملعقة صغيرة المتبقية من القرفة و¼ ملعقة صغيرة المتبقية من القرنفل والفلفل الأحمر المجروش، واتركه حتى يغلي. غطِّه وخفّف الحرارة واتركه على نار هادئة لمدة 5 دقائق. ارفع القدر عن النار واتركه يبرد لمدة 10 دقائق. أضف التفاح وقلّبه برفق.","انقل صدر الديك الرومي إلى طبق التقديم واتركه يستريح مغطى بورق الألمنيوم دون إحكام لمدة 10 دقائق تقريبًا قبل التقديم.","للتقديم، قطّع الديك الرومي إلى شرائح وتخلّص من الجلد وقدّمه مع الشتني. احفظ الكوب الواحد المتبقي من الشتني مغطى في الثلاجة لمدة تصل إلى ثلاثة أيام."])}))
R.append((6733698,{
"es":L("Wraps de lechuga con ensalada de pollo, arándanos azules y almendras",
"Dele vida a su almuerzo y reciba un impulso de color azul. Se alegrará mucho de haberlo hecho cuando pruebe estos cremosos wraps de lechuga con ensalada de pollo, arándanos azules y almendras. Una delicia crujiente y llena de sabor que además encaja en un plan de alimentación apto para personas con diabetes. En lugar de mayonesa, estos wraps llevan yogur como base para reducir las calorías y la grasa, además de ser una excelente fuente de vitamina A. ¡A disfrutar lo crujiente!",
"4","1/2 taza de pollo por hoja de lechuga; 2 hojas de lechuga por porción",
["1/2 taza de yogur griego natural sin grasa","1/4 taza de albahaca fresca (picada)","1/2 cucharadita de sal (kosher)","1/4 cucharadita de pimienta negra","3 tazas de pollo cocido (picado)","3 tazas de arándanos azules","1/2 taza de apio (picado)","1/4 taza de cebollín (cebolla verde) (picado)","8 hojas de lechuga","2 cucharadas de almendras (en láminas y tostadas)"],
["En un tazón, mezcle el yogur, la albahaca, la sal y la pimienta hasta integrar.","Agregue el pollo, los arándanos azules, el apio y el cebollín, y mezcle hasta que todo quede cubierto de manera uniforme.","Acomode las hojas de lechuga en una fuente para servir y cúbralas con la mezcla de pollo, repartiéndola en partes iguales entre las hojas de lechuga.","Cubra con las almendras."]),
"ar":L("لفائف الخس بسلطة الدجاج والتوت الأزرق واللوز",
"أضف الحيوية إلى حقيبة غدائك وتناول جرعة من اللون الأزرق. ستسعد كثيرًا بذلك عندما تتذوق لفائف الخس هذه بسلطة الدجاج الكريمية مع التوت الأزرق واللوز. لذة مقرمشة ومليئة بالنكهة تناسب أيضًا خطة غذائية مناسبة لمرضى السكري. وبدلًا من المايونيز، تعتمد هذه اللفائف على الزبادي لتقليل السعرات الحرارية والدهون، فضلًا عن كونه مصدرًا ممتازًا لفيتامين أ. استمتع بالقرمشة!",
"4","½ كوب من الدجاج لكل ورقة خس؛ ورقتا خس لكل حصة",
["½ كوب من الزبادي اليوناني الطبيعي خالي الدسم","¼ كوب من الريحان الطازج (مفروم)","½ ملعقة صغيرة من الملح (كوشير)","¼ ملعقة صغيرة من الفلفل الأسود","3 أكواب من الدجاج المطبوخ (مفروم)","3 أكواب من التوت الأزرق","½ كوب من الكرفس (مفروم)","¼ كوب من البصل الأخضر (مفروم)","8 أوراق خس","2 ملعقة كبيرة من اللوز (شرائح ومحمّص)"],
["في وعاء، اخلط الزبادي والريحان والملح والفلفل حتى يتجانس الخليط.","أضف الدجاج والتوت الأزرق والكرفس والبصل الأخضر وقلّب حتى تتغطى المكونات بالتساوي.","رتّب أوراق الخس في طبق التقديم وضع فوقها خليط الدجاج، موزعًا بالتساوي بين أوراق الخس.","زيّنها باللوز."])}))
R.append((6734922,{
"es":L("17 uvas","Información nutricional de las uvas","1","17 uvas",["17 uvas enteras"],[]),
"ar":L("17 حبة عنب","المعلومات الغذائية للعنب","1","17 حبة عنب",["17 حبة عنب كاملة"],[])}))
R.append((6736641,{
"en":L("Chickpea Salad - Quick Recipe",
"Beans and legumes are among the healthiest carbohydrates you can eat if you have diabetes. Most people say they like beans, but they are not sure how to include more of them in their diet. Try this delicious salad packed with fiber, protein and flavor!",
"16",None,
["1 can chickpea (garbanzo) beans (16-ounce, rinsed and drained)","2 tbsp light mayonnaise","1/2 lemon (juiced)","1/4 cup red bell pepper (diced)","1/4 cup celery (diced)","1 pinch ground black pepper","1 pinch cayenne pepper (if you prefer less spicy, use paprika)","2 cucumber(s) (peeled and sliced into rounds)"],
["In a medium salad bowl, mix all the salad ingredients.","In a small bowl, whisk the dressing ingredients. Pour over the bean mixture and toss to coat."]),
"ar":L("سلطة الحمص - وصفة سريعة",
"تُعد الفاصولياء والبقوليات من أكثر الكربوهيدرات صحةً التي يمكنك تناولها إذا كنت مصابًا بالسكري. يقول معظم الناس إنهم يحبون الفاصولياء، لكنهم غير متأكدين من كيفية إدخالها بشكل أكبر في نظامهم الغذائي. جرّب هذه السلطة اللذيذة المليئة بالألياف والبروتين والنكهة!",
"16",None,
["1 علبة من الحمص (16 أونصة، مشطوفة ومصفّاة)","2 ملعقة كبيرة من المايونيز الخفيف","½ ليمونة (معصورة)","¼ كوب من الفلفل الرومي الأحمر (مقطع مكعبات)","¼ كوب من الكرفس (مقطع مكعبات)","1 رشة من الفلفل الأسود المطحون","1 رشة من فلفل كايين (إن كنت تفضّل أقل حرارة، فاستخدم البابريكا)","2 خيارة (مقشرة ومقطعة إلى شرائح دائرية)"],
["في وعاء سلطة متوسط، اخلط جميع مكونات السلطة.","في وعاء صغير، اخفق مكونات الصلصة. اسكبها فوق خليط الحمص وقلّب حتى يتغطى."])}))
R.append((6736784,{
"es":L("Espárragos a la parrilla con ajonjolí",
"Esta sencilla receta de espárragos recibe una doble dosis de sabor a ajonjolí: primero se mezclan los espárragos con aceite de ajonjolí tostado y luego se terminan con semillas de ajonjolí tostadas. Póngalos en la parrilla junto con este pollo a la parrilla con miel y lima, o con la proteína que usted elija. La parrilla les da un delicioso sabor ahumado natural, pero también puede asar los espárragos en el horno. Al comprar espárragos para asar a la parrilla, busque tallos más gruesos, ya que serán más fáciles de manejar en la parrilla.",
"2","unos 12 tallos",
["12 oz (unos 24 tallos) de espárragos (con los extremos recortados)","2 cucharaditas de aceite de ajonjolí tostado","1/8 cucharadita de sal","1/2 cucharadita de semillas de ajonjolí"],
["Precaliente una parrilla exterior o una sartén parrilla.","Coloque los tallos de espárragos y el aceite en una fuente de 9 × 13 pulgadas. Mezcle con unas pinzas para cubrirlos.","Ase los espárragos a la parrilla (por tandas, si es necesario) a fuego directo medio-alto hasta que estén apenas cocidos y ligeramente dorados, aproximadamente 6–8 minutos en total, girándolos solo cuando sea necesario.","Retire los tallos de la parrilla y devuélvalos a la fuente, espolvoree con la sal y las semillas de ajonjolí, y sirva."]),
"ar":L("هليون مشوي بالسمسم",
"تحصل وصفة الهليون البسيطة هذه على جرعة مضاعفة من نكهة السمسم، إذ يُقلَّب الهليون أولًا بزيت السمسم المحمّص ثم يُزيَّن في النهاية ببذور السمسم المحمّصة. ضعه على الشواية مع هذا الدجاج المشوي بالعسل والليمون الأخضر، أو مع أي بروتين تختاره. يمنح الشوي نكهة مدخنة طبيعية لذيذة، ويمكنك أيضًا تحميص الهليون في الفرن. عند شراء الهليون للشوي، ابحث عن السيقان الأكثر سُمكًا، فهي أسهل في التعامل معها على الشواية.",
"2","نحو 12 ساقًا",
["12 أونصة (نحو 24 ساقًا) من الهليون (مقطوعة الأطراف)","2 ملعقة صغيرة من زيت السمسم المحمّص","⅛ ملعقة صغيرة من الملح","½ ملعقة صغيرة من بذور السمسم"],
["سخّن شواية خارجية أو مقلاة شواء مسبقًا.","ضع سيقان الهليون والزيت في طبق مقاس 9 × 13 بوصة. قلّبها بملقط لتتغطى.","اشوِ الهليون (على دفعات إن لزم) على حرارة مباشرة متوسطة إلى عالية حتى ينضج بالكاد ويتحمّر قليلًا، نحو 6–8 دقائق في المجموع، مع تقليبه عند الحاجة فقط.","أخرج السيقان من الشواية وأعدها إلى الطبق، ورشّ عليها الملح وبذور السمسم، ثم قدّمها."])}))
save("out_c20_part2.json",R)
