from h import *
R=[]
R.append((6743973,{
"es":L("Sopa pho en frasco de vidrio",
"Si busca un almuerzo rápido para llevar que sea todo menos común, esta sopa pho en frasco de vidrio le caerá de maravilla. Para ahorrar tiempo, puede preparar varios de estos frascos con anticipación y disfrutarlos durante toda la semana. Busque fideos de arroz instantáneos para esta sopa. Si no encuentra fideos instantáneos, hierva brevemente (precocine) fideos de arroz comunes y rocíelos con un poco de aceite en aerosol antes de colocarlos en el frasco. En lugar del caldo en cubo, use caldo de res sin sal añadida.",
"1","3 oz de carne de res + 2 tazas de verduras + 1 oz de fideos + 1 taza de caldo",
["1 cucharadita de caldo de res en polvo sin sodio","1 cucharadita de jengibre fresco (en rodajas)","1 oz de fideos de arroz instantáneos","3 oz de bistec magro (cocido, cortado en tiras delgadas)","1/2 taza de champiñones cremini (baby bella) (en rodajas)","1/4 taza de repollo verde (en rodajas finas)","1/4 taza de pimiento rojo (en rodajas finas)","1/4 taza de zanahorias (ralladas)","2 cucharadas de edamame fresco sin cáscara","1 tallo de cebollín (cebolla verde) (en rodajas)","2 cucharadas de cilantro fresco","1 cucharadita de salsa de soya","1 cucharadita de jugo de lima fresco","1 taza de agua hirviendo"],
["Use un frasco de vidrio grande (de boca ancha, de 24 a 32 oz) con tapa de cierre hermético.","Coloque en capas los ingredientes secos en el frasco de la siguiente manera: el caldo en polvo (si lo usa), la raíz de jengibre, los fideos de arroz, la carne de res cocida, los champiñones, los pimientos, el repollo, las zanahorias, el cebollín y el cilantro. Selle bien y coloque en el refrigerador hasta el momento de usar.","En un recipiente pequeño aparte, mezcle la salsa de soya y el jugo de lima, y colóquelo en el refrigerador.","Cuando esté listo para preparar la sopa, saque el frasco del refrigerador al menos 15 minutos antes de prepararla. Caliente una taza de agua tibia (o caldo de res) en el microondas hasta que hierva. Incorpore la salsa de soya y el jugo de lima.","Vierta la mezcla de agua y salsa de soya en el frasco y ciérrelo bien de nuevo. Agítelo suavemente para asegurarse de que los fideos queden cubiertos de líquido. Déjelo reposar de 2 a 3 minutos o hasta que los fideos se ablanden. También puede calentar el agua (o el caldo) en una cacerola mediana hasta que hierva. Vierta los ingredientes del frasco en la cacerola y revuelva hasta combinar y hasta que los fideos se ablanden. Sirva en un tazón y disfrute."]),
"ar":L("حساء فو في برطمان زجاجي",
"إن كنت تبحث عن وجبة غداء سريعة تأخذها معك وتكون بعيدة كل البعد عن المألوف، فسيعجبك حساء الفو في البرطمان الزجاجي هذا. لتوفير الوقت، يمكنك تحضير عدد من هذه البرطمانات مسبقًا والاستمتاع بها طوال الأسبوع. ابحث عن شعيرية الأرز الفورية لهذا الحساء. وإذا لم تجد الشعيرية الفورية، فاسلق شعيرية الأرز العادية سلقًا خفيفًا (غليًا قصيرًا) ورشّها بقليل من بخاخ الطهي قبل وضعها في البرطمان. وبدلًا من مكعبات المرق، استخدم مرق اللحم البقري بدون ملح مضاف.",
"1","3 أونصات من لحم البقر + 2 كوب من الخضار + 1 أونصة من الشعيرية + 1 كوب من المرق",
["1 ملعقة صغيرة من مرق لحم البقر الخالي من الصوديوم","1 ملعقة صغيرة من الزنجبيل الطازج (مقطع شرائح)","1 أونصة من شعيرية الأرز الفورية","3 أونصات من شريحة اللحم الخالية من الدهن (مطبوخة، مقطعة إلى شرائح رفيعة)","½ كوب من فطر كريميني (بيبي بيلا) (مقطع شرائح)","¼ كوب من الملفوف الأخضر (مقطع شرائح رفيعة)","¼ كوب من الفلفل الرومي الأحمر (مقطع شرائح رفيعة)","¼ كوب من الجزر (مبشور)","2 ملعقة كبيرة من الإدامامي الطازج منزوع القشر","1 ساق بصل أخضر (مقطعة شرائح)","2 ملعقة كبيرة من الكزبرة الخضراء الطازجة","1 ملعقة صغيرة من صلصة الصويا","1 ملعقة صغيرة من عصير الليمون الأخضر الطازج","1 كوب من الماء المغلي"],
["استخدم برطمانًا زجاجيًّا كبيرًا (واسع الفوهة سعة 24 إلى 32 أونصة) بغطاء محكم الإغلاق.","ضع المكونات الجافة في طبقات داخل البرطمان بالترتيب التالي: مرق اللحم (إن استخدمته)، وجذر الزنجبيل، وشعيرية الأرز، ولحم البقر المطبوخ، والفطر، والفلفل، والملفوف، والجزر، والبصل الأخضر، والكزبرة الخضراء. أغلقه بإحكام وضعه في الثلاجة حتى وقت الاستخدام.","في وعاء صغير منفصل، اخلط صلصة الصويا وعصير الليمون الأخضر وضعه في الثلاجة.","عندما تكون مستعدًا لتحضير الحساء، أخرج البرطمان من الثلاجة قبل التحضير بـ15 دقيقة على الأقل. سخّن كوبًا من الماء الدافئ (أو مرق اللحم) في الميكروويف حتى يغلي. أضف صلصة الصويا وعصير الليمون الأخضر وحرّك.","اسكب خليط الماء وصلصة الصويا في البرطمان وأغلقه بإحكام مرة أخرى. حرّكه برفق للتأكد من أن الشعيرية مغطاة بالسائل. اتركه لمدة 2-3 دقائق أو حتى تلين الشعيرية. أو يمكنك تسخين الماء (أو المرق) في قدر متوسط حتى يغلي. اسكب محتويات البرطمان في القدر وحرّك حتى تمتزج المكونات وتلين الشعيرية. اسكب الحساء في وعاء واستمتع به."])}))
R.append((6744025,{
"es":L("Huevos revueltos suaves con hierbas sobre tostada",
"¡Las hierbas frescas convierten unos huevos revueltos comunes en algo especial! Use las hierbas que tenga a la mano, o pruebe cualquiera de estas parejas dinámicas: perejil y menta, eneldo y cebollino, perejil y estragón, o menta y albahaca.\n\nPara obtener los huevos revueltos más esponjosos, intente doblarlos suavemente en lugar de revolverlos continuamente. Lo único que debe hacer es raspar lentamente los huevos batidos mientras se cocinan, con una espátula de silicona flexible, una fila a la vez, mientras dobla (¡voltea con suavidad!) la porción de huevo cocida sobre la porción más líquida. Continúe solo hasta que ya no quede nada líquido.",
"2","1 tostada con cobertura",
["2 rebanadas de pan integral de granos germinados o de trigo integral","1 cucharadita de aceite de oliva","2 huevos grandes","1/8 cucharadita de sal","1/4 taza de hierbas frescas picadas (sin apretar)"],
["Tueste el pan en una tostadora o en un horno tostador hasta el punto deseado.","Mientras se tuesta el pan, prepare los huevos: caliente bien el aceite en un sartén antiadherente mediano a fuego medio-bajo. Vierta los huevos en el sartén caliente y cocine mientras revuelve (o dobla) suavemente la mezcla hasta que los huevos ya no estén líquidos, pero todavía estén húmedos, de 1 1/2 a 2 minutos aproximadamente. Retire el sartén del fuego, espolvoree con la sal e incorpore suavemente (o doble) las hierbas.","Pase las tostadas a los platos. Cubra cada tostada con la mitad de los huevos con hierbas. Si lo desea, espolvoree con pimienta negra recién molida al gusto. Sirva."]),
"ar":L("بيض مخفوق طري بالأعشاب على التوست",
"تحوّل الأعشاب الطازجة البيض المخفوق العادي إلى شيء مميز! استخدم أي أعشاب لديك، أو جرّب أيًّا من هذه الثنائيات المميزة: البقدونس والنعناع، أو الشبت والثوم المعمر (الشيف)، أو البقدونس والطرخون، أو النعناع والريحان.\n\nللحصول على أكثر بيض مخفوق هشاشة، جرّب طيّه برفق بدلًا من تحريكه باستمرار. كل ما عليك فعله هو كشط البيض المخفوق ببطء أثناء طهيه باستخدام ملعقة سيليكون مرنة، صفًّا واحدًا في كل مرة، مع طيّ (قلب برفق!) الجزء المطهو من البيض فوق الجزء الأكثر سيولة. واصل ذلك فقط حتى لا يبقى أي جزء سائل.",
"2","1 شريحة توست مغطاة",
["2 شريحة من خبز الحبوب الكاملة المنبّتة أو خبز القمح الكامل","1 ملعقة صغيرة من زيت الزيتون","2 بيضة كبيرة","⅛ ملعقة صغيرة من الملح","¼ كوب من الأعشاب الطازجة المفرومة (غير مضغوطة)"],
["حمّص الخبز في محمصة خبز أو فرن محمصة حتى الدرجة التي تريدها.","بينما يُحمَّص الخبز، حضّر البيض: سخّن الزيت جيدًا في مقلاة متوسطة غير لاصقة على نار متوسطة إلى منخفضة. اسكب البيض في المقلاة الساخنة واطهِه مع تحريك الخليط (أو طيّه) برفق حتى لا يعود البيض سائلًا لكنه يبقى رطبًا، نحو 1½–2 دقيقة. ارفع المقلاة عن النار ورشّ الملح وأضف الأعشاب مع التحريك (أو الطيّ) برفق.","انقل شرائح التوست إلى الأطباق. ضع فوق كل شريحة نصف كمية البيض بالأعشاب. إن رغبت، رشّ الفلفل الأسود المطحون طازجًا حسب الذوق. قدّمها."])}))
R.append((6745584,{
"es":L("Ensalada de hinojo, rábano y naranja",
"Esta ensalada colorida está llena de sabores sorprendentes: dulzor de la naranja, riqueza del hinojo y un poco de picante del rábano y la arúgula.",
"6","1 taza",
["2 cucharadas de vinagre de jerez","2 cucharadas de aceite de oliva","1 cucharadita de miel","1/2 cucharadita de sal","1/4 cucharadita de pimienta negra","2 naranjas navel (aproximadamente 1 1/2 libras en total) (peladas y cortadas en gajos)","1 bulbo grande de hinojo (aproximadamente 1 libra) (cortado a la mitad, sin el centro y en rodajas finas)","6 rábanos enteros (en rodajas finas)","1/4 taza de menta fresca picada","5 oz (aproximadamente 6 tazas) de arúgula tierna"],
["Bata juntos el vinagre, el aceite, la miel, la sal y la pimienta en un tazón grande. Agregue las naranjas, el hinojo, los rábanos y la menta; mezcle hasta que todo esté bien integrado.","Sirva sobre una cama de arúgula."]),
"ar":L("سلطة الشمر والفجل والبرتقال",
"هذه السلطة الملونة مليئة بالنكهات المدهشة، حلاوة من البرتقال، وغنى من الشمر، ولمسة خفيفة من الحرارة من الفجل والجرجير.",
"6","1 كوب",
["2 ملعقة كبيرة من خل الشيري","2 ملعقة كبيرة من زيت الزيتون","1 ملعقة صغيرة من العسل","½ ملعقة صغيرة من الملح","¼ ملعقة صغيرة من الفلفل الأسود","2 حبة برتقال سرّة (نحو 1½ رطل في المجموع) (مقشرة ومقطعة إلى أرباع)","1 بصلة شمر كبيرة (نحو 1 رطل) (مقطوعة إلى نصفين ومنزوعة القلب ومقطعة إلى شرائح رفيعة)","6 حبات فجل كاملة (مقطعة إلى شرائح رفيعة)","¼ كوب من النعناع الطازج المفروم","5 أونصات (نحو 6 أكواب) من الجرجير الصغير"],
["اخفق الخل والزيت والعسل والملح والفلفل معًا في وعاء كبير. أضف البرتقال والشمر والفجل والنعناع؛ وقلّب حتى تمتزج المكونات جيدًا.","قدّمها فوق طبقة من الجرجير."])}))
R.append((6746805,{
"es":L("Cobbler para el clima fresco",
"«Esta es mi versión de un crumble de manzana clásico», dice la autora de libros de cocina y experta en nutrición Katie Cavuto. «Pero quise rendir homenaje al dulzor natural de la fruta en lugar de echarle azúcar. El polvo de arrurruz espesa este relleno de fruta entera, y el jengibre fresco, la canela y la ralladura de naranja aportan sabores intensos a este postre. Y la cobertura aporta algo más que textura crujiente; con avena, harina de trigo integral, semillas de calabaza, almendras y jarabe de maple, es una manera sabrosa de obtener sus nutrientes».",
"18","3/4 taza",
["6 manzanas medianas y/o peras (peladas, sin corazón y en rodajas)","1 taza de arándanos rojos y/o cerezas sin hueso (frescos o congelados)","1 cucharada de polvo de arrurruz","2 cucharaditas de canela molida (dividida)","1 cucharadita de jengibre fresco (rallado)","1 cucharadita de ralladura de naranja (recién rallada)","1 taza de harina de almendra","2 tazas de avena en hojuelas tradicional (sin gluten)","1/2 taza de harina de trigo integral","1/4 taza de semillas de calabaza (sin sal, tostadas)","1/4 taza de almendras (crudas, en láminas)","1/4 cucharadita de sal marina fina","2 cucharadas de aceite de canola","1 cucharada de aceite de oliva extra virgen","1/3 taza de jarabe de maple puro (de preferencia grado B)"],
["Precaliente el horno a 350 °F.","Para preparar el relleno, mezcle toda la fruta, el polvo de arrurruz, 1 cucharadita de canela, el jengibre y la ralladura de naranja en un tazón mediano. Extienda el relleno en el fondo de una fuente para hornear de 8 x 12 pulgadas.","Para preparar la cobertura, mezcle la harina de almendra, la avena, la harina, las semillas de calabaza, las almendras, 1 cucharadita de canela y la sal en otro tazón mediano. Rocíe el aceite de canola, el aceite de oliva y el jarabe de maple, y mezcle hasta que todo esté bien integrado.","Desmorone la cobertura sobre el relleno y hornee durante 40 minutos, o hasta que la cobertura esté dorada y la fruta burbujee. Saque el cobbler del horno y déjelo enfriar durante 10 minutos antes de servir."]),
"ar":L("كوبلر لأيام الطقس البارد",
"«هذه نسختي من كرامبل التفاح الكلاسيكي»، تقول مؤلفة كتب الطبخ وخبيرة التغذية كاتي كافوتو. «لكنني أردت أن أُكرّم الحلاوة الطبيعية للفاكهة بدلًا من الإكثار من السكر. يعمل مسحوق الأروروت على تكثيف حشوة الفاكهة الكاملة هذه، ويمنح الزنجبيل الطازج والقرفة وقشر البرتقال المبشور نكهات قوية لهذه الحلوى. والطبقة العلوية تضيف أكثر من مجرد القرمشة؛ فمع الشوفان ودقيق القمح الكامل وبذور القرع واللوز وشراب القيقب، هي طريقة لذيذة للحصول على العناصر الغذائية».",
"18","¾ كوب",
["6 حبات تفاح و/أو كمثرى متوسطة (مقشرة ومنزوعة القلب ومقطعة شرائح)","1 كوب من التوت البري و/أو الكرز منزوع النوى (طازج أو مجمد)","1 ملعقة كبيرة من مسحوق الأروروت","2 ملعقة صغيرة من القرفة المطحونة (مقسّمة)","1 ملعقة صغيرة من الزنجبيل الطازج (مبشور)","1 ملعقة صغيرة من قشر البرتقال (مبشور طازجًا)","1 كوب من دقيق اللوز","2 كوب من الشوفان المسطّح التقليدي (خالٍ من الغلوتين)","½ كوب من دقيق القمح الكامل","¼ كوب من بذور القرع (غير مملحة، محمّصة)","¼ كوب من اللوز (نيء، شرائح)","¼ ملعقة صغيرة من ملح البحر الناعم","2 ملعقة كبيرة من زيت الكانولا","1 ملعقة كبيرة من زيت الزيتون البكر الممتاز","⅓ كوب من شراب القيقب الطبيعي (يُفضَّل الدرجة B)"],
["سخّن الفرن مسبقًا إلى 350° فهرنهايت (175° مئوية).","لتحضير الحشوة، قلّب جميع الفواكه ومسحوق الأروروت و1 ملعقة صغيرة من القرفة والزنجبيل وقشر البرتقال في وعاء متوسط. افرد الحشوة في قاع طبق خبز مقاس 8 × 12 بوصة.","لتحضير الطبقة العلوية، اخلط دقيق اللوز والشوفان والدقيق وبذور القرع واللوز و1 ملعقة صغيرة من القرفة والملح في وعاء متوسط آخر. أضف زيت الكانولا وزيت الزيتون وشراب القيقب وامزج حتى يتجانس الخليط.","فتّت الطبقة العلوية فوق الحشوة واخبز لمدة 40 دقيقة، أو حتى تصبح الطبقة العلوية بنية وتغلي الفاكهة. أخرج الكوبلر من الفرن واتركه جانبًا ليبرد لمدة 10 دقائق قبل التقديم."])}))
R.append((6747790,{
"es":L("Salmón glaseado con naranja y romero con brócoli rabe tierno (broccolini)",
"Este salmón glaseado con naranja y romero con broccolini es una sabrosa combinación de sabores cítricos, herbales y salados. Es un plato saludable y elegante, perfecto para una cena fácil entre semana.",
"4","1 filete de 6 oz + 1/2 manojo de broccolini",
["2 manojos de broccolini (1 libra en total)","1 cucharada de aceite de oliva","4 filetes enteros de salmón (6 onzas cada uno)","1 cucharada de ralladura de naranja","1/2 taza de jugo de naranja fresco (de unas 2 naranjas, exprimidas)","1/2 taza de caldo de pollo bajo en sodio","1 cucharada + 2 cucharaditas de sustituto de azúcar morena","3 dientes de ajo (picados)","1 cucharada de maicena","1 cucharada de romero fresco (finamente picado)","2 cucharaditas de semillas de linaza enteras","1/4 cucharadita de sal kosher","1/8 cucharadita de pimienta negra"],
["Precaliente el horno a 400 °F. Forre una bandeja para hornear con papel pergamino o papel aluminio.","Coloque el broccolini en un lado de la bandeja y rocíelo con el aceite de oliva.","Seque el salmón con toallas de papel y colóquelo en el otro lado de la bandeja.","Combine la ralladura de naranja, el jugo de naranja, el caldo, el sustituto de azúcar morena, el ajo, el romero, la maicena y la linaza en una cacerola pequeña a fuego medio. Cocine, batiendo de vez en cuando, hasta que la salsa se reduzca a la mitad y espese, de 8 a 10 minutos. Debe adherirse a una cuchara.","Unte la salsa sobre el salmón con una brocha. Coloque la bandeja en el horno y hornee hasta que el salmón alcance una temperatura interna de 145 °F y el broccolini esté tierno, de 6 a 10 minutos. Sazone con sal y pimienta."]),
"ar":L("سلمون مطلي بالبرتقال والإكليل مع البروكولليني",
"هذا السلمون المطلي بالبرتقال وإكليل الجبل مع البروكولليني مزيج لذيذ من نكهات الحمضيات والأعشاب والنكهة المالحة. إنه طبق صحي وأنيق مثالي لعشاء سهل في أيام الأسبوع.",
"4","1 شريحة 6 أونصات + ½ حزمة بروكولليني",
["2 حزمة بروكولليني (1 رطل في المجموع)","1 ملعقة كبيرة من زيت الزيتون","4 شرائح سلمون كاملة (6 أونصات لكل منها)","1 ملعقة كبيرة من قشر البرتقال المبشور","½ كوب من عصير البرتقال الطازج (من حبتي برتقال تقريبًا، معصورتين)","½ كوب من مرق الدجاج قليل الصوديوم","1 ملعقة كبيرة + 2 ملعقة صغيرة من بديل السكر البني","3 فص ثوم (مفروم)","1 ملعقة كبيرة من نشا الذرة","1 ملعقة كبيرة من إكليل الجبل الطازج (مفروم ناعمًا)","2 ملعقة صغيرة من بذور الكتان الكاملة","¼ ملعقة صغيرة من الملح الخشن (كوشير)","⅛ ملعقة صغيرة من الفلفل الأسود"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (205° مئوية). بطّن صينية خبز بورق زبدة أو ورق ألمنيوم.","ضع البروكولليني على جانب واحد من الصينية ورشّ عليه زيت الزيتون.","جفّف السلمون بمناشف ورقية وضعه على الجانب الآخر من الصينية.","اخلط قشر البرتقال وعصير البرتقال والمرق وبديل السكر البني والثوم وإكليل الجبل ونشا الذرة وبذور الكتان في قدر صغير على نار متوسطة. اطهِ مع الخفق من حين لآخر حتى تتقلص الصلصة إلى النصف وتتكاثف، من 8 إلى 10 دقائق. ينبغي أن تلتصق بالملعقة.","افرد الصلصة على السلمون بفرشاة. ضع الصينية في الفرن واخبز حتى تصل درجة حرارة السلمون الداخلية إلى 145° فهرنهايت (65° مئوية) ويلين البروكولليني، من 6 إلى 10 دقائق. تبّل بالملح والفلفل."])}))
R.append((6749490,{
"es":L("Wraps de clara de huevo con quinoa, espinacas y hummus",
"Estos wraps de clara de huevo son una alternativa fresca y saciante a los wraps tradicionales de desayuno, con una mezcla de quinoa y espinacas con hierbas, hummus cremoso y tomate jugoso. Usar claras de huevo como envoltura mantiene la comida baja en carbohidratos y grasa saturada. Es una opción equilibrada que apoya el control de la glucosa en la sangre (azúcar en la sangre) y a la vez ofrece mucho sabor y textura. Es una receta baja en grasa y mediterránea.",
"2","1 wrap",
["1/2 taza de quinoa","1 taza de claras de huevo","1/8 cucharadita de sal","1/4 taza de cebollino fresco (finamente picado)","2 tazas de espinacas tiernas","1 taza de perejil de hoja plana (hojas)","1 rociada de aceite antiadherente en aerosol para cocinar","2 cucharadas de hummus","1 tomate entero (en rodajas finas)"],
["Enjuague la quinoa con agua fría.","En una cacerola mediana, lleve 1 taza de agua a ebullición. Agregue la quinoa, reduzca el fuego a bajo, tape y cocine a fuego lento durante unos 15 minutos, o hasta que se absorba el agua. Retire del fuego y déjela reposar tapada durante 5 minutos. Esponje con un tenedor.","En un tazón, bata juntas las claras de huevo, la sal y el cebollino picado.","Caliente un sartén antiadherente de 10 pulgadas a fuego medio-bajo y cubra ligeramente con aceite antiadherente en aerosol.","Vierta la mitad de la mezcla de huevo en el sartén, moviéndolo en círculos para cubrir el fondo de manera uniforme. Cocine hasta que el fondo esté apenas cuajado y la parte superior esté ligeramente húmeda, aproximadamente 3–4 minutos. Voltee el wrap con cuidado y cocine 10 segundos más. Pase a un plato y repita con el resto de la mezcla de huevo.","En un procesador de alimentos, combine las espinacas tiernas y las hojas de perejil. Pulse hasta que estén finamente picadas. Incorpore con movimientos envolventes a la quinoa cocida.","Para armar, coloque cada wrap de huevo extendido sobre una superficie limpia. Unte una cucharada generosa de hummus de limón sobre la mitad de cada wrap. Reparta con una cuchara la mitad de la mezcla de quinoa sobre el hummus, presionando suavemente para que se adhiera. Cubra con rodajas de tomate. Doble los wraps por la mitad sobre el relleno y luego doble una vez más para formar un doblez en cuartos."]),
"ar":L("لفائف بياض البيض بالكينوا والسبانخ والحمص بطحينة",
"لفائف بياض البيض هذه بديل منعش ومشبع للفائف الإفطار التقليدية، وتحتوي على خليط من الكينوا والسبانخ بالأعشاب مع الحمص بطحينة الكريمي والطماطم العصيرية. يساعد استخدام بياض البيض كغلاف على إبقاء الوجبة قليلة الكربوهيدرات والدهون المشبعة. إنه خيار متوازن يدعم التحكم في مستوى الغلوكوز في الدم (سكر الدم) مع تقديم الكثير من النكهة والقوام. هذه وصفة قليلة الدسم ومتوسطية.",
"2","1 لفافة",
["½ كوب من الكينوا","1 كوب من بياض البيض","⅛ ملعقة صغيرة من الملح","¼ كوب من الثوم المعمر الطازج (الشيف) (مفروم ناعمًا)","2 كوب من السبانخ الصغيرة","1 كوب من البقدونس المسطح الأوراق (أوراق)","1 رشة من بخاخ الطهي غير اللاصق","2 ملعقة كبيرة من الحمص بطحينة","1 حبة طماطم كاملة (مقطعة إلى شرائح رفيعة)"],
["اشطف الكينوا بالماء البارد.","في قدر متوسط، اترك 1 كوب من الماء حتى يغلي. أضف الكينوا وخفّف الحرارة إلى منخفضة وغطِّ القدر واتركها على نار هادئة نحو 15 دقيقة، أو حتى يُمتص الماء. ارفعها عن النار واتركها مغطاة لمدة 5 دقائق. فكّكها بشوكة.","في وعاء، اخفق بياض البيض والملح والثوم المعمر المفروم.","سخّن مقلاة غير لاصقة مقاس 10 بوصات على نار متوسطة إلى منخفضة وادهنها قليلًا ببخاخ الطهي غير اللاصق.","اسكب نصف خليط البيض في المقلاة مع تحريكها بحركة دائرية ليغطي القاع بالتساوي. اطهِه حتى يتماسك القاع بالكاد ويبقى الوجه العلوي رطبًا قليلًا، نحو 3–4 دقائق. اقلب اللفافة بحذر واطهِها 10 ثوانٍ إضافية. انقلها إلى طبق وكرّر العملية مع بقية خليط البيض.","في محضّرة الطعام، ضع السبانخ الصغيرة وأوراق البقدونس. شغّلها على نبضات حتى تتفرّم ناعمًا. أضفها إلى الكينوا المطبوخة وقلّب برفق.","للتجميع، افرد كل لفافة بيض على سطح نظيف. ادهن ملعقة كبيرة سخية من الحمص بطحينة بالليمون على نصف كل لفافة. وزّع نصف خليط الكينوا فوق الحمص بالملعقة، مع الضغط برفق ليلتصق. ضع فوقه شرائح الطماطم. اطوِ اللفائف إلى نصفين فوق الحشوة، ثم اطوِها مرة أخرى لتحصل على طيّة رُبعية."])}))
R.append((6750704,{
"es":L("Tacos de maíz y calabacín",
"Estos tacos vegetarianos están llenos de verduras frescas de verano. Son una excelente manera de aprovechar cualquier verdura sobrante que tenga por ahí, y puede sustituirlas por otras verduras que tenga en el refrigerador.",
"6","1 taco",
["1 cucharada de aceite de oliva (dividida)","3 mazorcas medianas de maíz (sin hojas y con los granos cortados de la mazorca; deseche los olotes)","1/4 cucharadita de chile en polvo","1/2 cucharadita de comino molido","1/2 taza de cebolla dulce (finamente picada)","1 calabacín mediano (sin pelar y cortado en trozos de 1/2 pulgada)","2 tomates medianos (sin semillas y cortados en trozos de 1/2 pulgada)","1 cucharada de orégano fresco (finamente picado)","6 tortillas de maíz pequeñas","1/4 taza de yogur griego natural sin grasa","1/2 taza de salsa"],
["En un sartén grande, caliente 2 cucharaditas del aceite a fuego medio. Agregue el maíz y saltéelo durante 3 minutos. Agregue el comino y el chile en polvo y saltee durante 2 minutos. Retire la mezcla de maíz del sartén.","Agregue el aceite de oliva restante al sartén y agregue la cebolla. Saltee la cebolla durante 5 minutos, hasta que esté suave. Agregue el calabacín y saltee durante 3 minutos. Agregue los tomates y saltee durante 2 minutos. Agregue el orégano y saltee durante 1 minuto; incorpore la mezcla de maíz reservada.","Divida la mezcla de maíz entre las tortillas calientes y cubra cada taco con 2 cucharaditas de yogur y 2 cucharaditas de salsa cruda.","Consejo del cocinero: ¡Use el microondas para preparar el maíz fresco! De cada mazorca, corte aproximadamente 1 pulgada del extremo del tallo. Coloque hasta 3 mazorcas a la vez en un recipiente apto para microondas y caliente a temperatura alta durante 6 minutos. Saque el maíz del microondas y déjelo enfriar lo suficiente para poder manipularlo. Sosteniendo la mazorca por las hojas, apriétela y sacúdala suavemente y el maíz saldrá de una sola vez. Si quedan algunas barbas, frote la mazorca de arriba abajo con toallas de papel para quitar las hebras."]),
"ar":L("تاكو الذرة والكوسا",
"تاكو نباتي مليء بخضار الصيف الطازجة. إنها طريقة رائعة للاستفادة من أي خضار زائدة لديك، ويمكنك استبدالها بخضار أخرى موجودة في ثلاجتك.",
"6","1 تاكو",
["1 ملعقة كبيرة من زيت الزيتون (مقسّمة)","3 كيزان ذرة متوسطة (منزوعة القشور وتُقطع الحبات من الكيزان؛ تخلّص من الكيزان)","¼ ملعقة صغيرة من مسحوق الفلفل الحار (تشيلي)","½ ملعقة صغيرة من الكمون المطحون","½ كوب من البصل الحلو (مفروم ناعمًا)","1 حبة كوسا متوسطة (غير مقشرة ومقطعة إلى قطع بحجم ½ بوصة)","2 حبة طماطم متوسطة (منزوعة البذور ومقطعة إلى قطع بحجم ½ بوصة)","1 ملعقة كبيرة من الأوريجانو الطازج (مفروم ناعمًا)","6 أقراص تورتيا ذرة صغيرة","¼ كوب من الزبادي اليوناني الطبيعي خالي الدسم","½ كوب من الصلصة (سالسا)"],
["في مقلاة كبيرة، سخّن 2 ملعقة صغيرة من الزيت على نار متوسطة. أضف الذرة وقلّبها لمدة 3 دقائق. أضف الكمون ومسحوق الفلفل الحار وقلّب لمدة دقيقتين. أخرج خليط الذرة من المقلاة.","أضف زيت الزيتون المتبقي إلى المقلاة ثم أضف البصل. قلّب البصل لمدة 5 دقائق حتى يلين. أضف الكوسا وقلّب لمدة 3 دقائق. أضف الطماطم وقلّب لمدة دقيقتين. أضف الأوريجانو وقلّب لمدة دقيقة واحدة؛ ثم أضف خليط الذرة المحتفظ به وحرّك.","وزّع خليط الذرة على أقراص التورتيا الدافئة وضع فوق كل تاكو 2 ملعقة صغيرة من الزبادي و2 ملعقة صغيرة من صلصة سالسا كروضا (الطازجة).","نصيحة الطاهي: استخدم الميكروويف لتحضير الذرة الطازجة! من كل كوز، اقطع نحو 1 بوصة من طرف الساق. ضع حتى 3 كيزان من الذرة في المرة الواحدة في وعاء صالح للميكروويف وسخّنها على درجة حرارة عالية لمدة 6 دقائق. أخرج الذرة من الميكروويف واتركها تبرد بما يكفي للإمساك بها. أمسك بالقشرة واضغط برفق وهزّ، وستخرج الذرة دفعة واحدة. وإن بقيت بعض الخيوط، فافرك الكوز من الأعلى إلى الأسفل بمناديل ورقية لإزالتها."])}))
R.append((6751867,{
"es":L("Bocaditos de salmón ahumado y pepino",
"Si le encantan el bagel con lox, pruebe esta alternativa baja en carbohidratos con salmón ahumado y queso crema sobre rodajas de pepino. Son excelentes aperitivos para recibir invitados, ¡o un refrigerio solo para usted!",
"6","4 bocaditos de pepino",
["1 pepino grande","1/4 taza de eneldo fresco (dividido)","4 oz de queso crema light","1 cucharadita de ralladura de limón","1 cucharadita de jugo de limón","1/4 cucharadita de pimienta negra","4 oz de salmón ahumado en frío (cortado en 24 trozos)"],
["Corte los extremos del pepino. Córtelo en 24 rodajas de aproximadamente 1/4 de pulgada de grosor.","Pique 2 cucharadas del eneldo y colóquelo en un tazón mediano. Quite los tallos del resto del eneldo y sepárelo en ramitas pequeñas. Reserve las ramitas.","En el tazón mediano con el eneldo picado, agregue el queso crema, la ralladura y el jugo de limón y la pimienta.","Unte aproximadamente 1 cucharadita de la mezcla de queso crema sobre cada rodaja de pepino. Cubra cada una con un trozo de salmón y decore con una ramita de eneldo. Acomode en una fuente y ¡disfrute!"]),
"ar":L("لقيمات السلمون المدخن والخيار",
"إذا كنت تحب البيغل مع السلمون المدخن (لوكس)، فجرّب هذا البديل القليل الكربوهيدرات المكوَّن من السلمون المدخن والجبن الكريمي على شرائح الخيار. وهي مقبلات رائعة عند استضافة الضيوف، أو وجبة خفيفة لك وحدك!",
"6","4 لقيمات خيار",
["1 خيارة كبيرة","¼ كوب من الشبت الطازج (مقسّم)","4 أونصات من الجبن الكريمي الخفيف","1 ملعقة صغيرة من قشر الليمون المبشور","1 ملعقة صغيرة من عصير الليمون","¼ ملعقة صغيرة من الفلفل الأسود","4 أونصات من السلمون المدخن على البارد (مقطع إلى 24 قطعة)"],
["اقطع طرفي الخيار. قطّعه إلى 24 شريحة دائرية بسُمك ¼ بوصة تقريبًا.","افرم 2 ملعقة كبيرة من الشبت وضعها في وعاء متوسط. انزع السيقان من بقية الشبت وافصله إلى أغصان صغيرة. اترك الأغصان جانبًا.","في الوعاء المتوسط الذي يحتوي على الشبت المفروم، أضف الجبن الكريمي وقشر الليمون وعصيره والفلفل.","ادهن نحو 1 ملعقة صغيرة من خليط الجبن الكريمي على كل شريحة خيار. ضع فوق كل واحدة قطعة سلمون وزيّنها بغصن شبت. رتّبها في طبق التقديم واستمتع بها!"])}))
R.append((6752392,{
"ar":L("إنتشيلادا الخضار المشوية في الفرن",
"هذا الطبق على طريقة الصينية نباتي، وسيحظى بإعجاب كبير لدى العائلة!",
"6","⅙ الصينية",
["2 ملعقة صغيرة من زيت الكانولا أو زيت الفول السوداني غير المكرر","1 حبة بصل حلو كبيرة (مقطعة مكعبات)","1 كوب من صلصة التوماتيلو (سالسا فيردي) الخفيفة أو المتوسطة الحرارة حسب اختيارك (مقسّمة)","1 رطل من فطر كريميني أو الفطر الأبيض (مقطع شرائح)","1 حبة فلفل بوبلانو كاملة (مفرومة)","2 حبة فلفل رومي أصفر أو برتقالي متوسطة (مفرومة)","5 أكواب مكتنزة من السبانخ الصغيرة الطازجة (5 أونصات)","1 علبة فاصولياء بنتو (15 أونصة، مشطوفة برفق ومصفّاة (1½ كوب))","3 ملاعق كبيرة من الكزبرة الخضراء الطازجة (مفرومة)","1 ملعقة صغيرة من أوراق الأوريجانو الطازجة (مفرومة ناعمًا)","½ ملعقة صغيرة من الكمون","¼ ملعقة صغيرة من الملح الخشن (كوشير)","12 قرص تورتيا ذرة صغير (6 بوصات)","½ كوب من جبن مونتيري جاك أو بيبر جاك (2 أونصة، مبشور)"],
["سخّن الفرن مسبقًا إلى 400 درجة فهرنهايت (205° مئوية).","سخّن الزيت في مقلاة كبيرة وعميقة غير لاصقة على نار متوسطة إلى عالية. أضف البصل وقلّبه حتى يلين، نحو 3 دقائق، ثم أضف الفلفل وواصل التقليب 5 دقائق أخرى حتى يلين. انقله إلى وعاء مقاوم للحرارة.","أضف الفطر إلى المقلاة وقلّبه حتى يلين، نحو 5 دقائق أخرى. أضف السبانخ وقلّب حتى تذبل بالكاد، نحو دقيقة واحدة. أضف الفاصولياء والكزبرة الخضراء والأوريجانو والكمون والملح، وقلّب حتى تمتزج تمامًا وتسخن، نحو دقيقة واحدة. أضف الفلفل والبصل وحرّك. عدّل التتبيل.","افرد ½ كوب من الصلصة في طبق خبز مقاس 9×13 بوصة. رتّب 6 أقراص تورتيا لتغطي قاع الطبق. وزّع نصف خليط الخضار فوقها بالتساوي. رتّب أقراص التورتيا الستة المتبقية فوقها. غطِّها بـ½ كوب المتبقي من الصلصة. وزّع خليط الخضار المتبقي فوقها بالتساوي. رشّ الجبن عليها. اخبزها حتى تنضج تمامًا ويذوب الجبن، نحو 20 دقيقة.","قطّع الصينية إلى 6 حصص وقدّمها."])}))
R.append((6754918,{
"es":L("Plátanos macho y chile poblano asados con salsa de guayaba",
"Este plato dulce, ahumado y sabroso es perfecto como acompañamiento de cerdo o pollo asado. Los plátanos machos se parecen a un plátano común, pero tienen más almidón y se disfrutan mejor asados o cocidos. Normalmente se encuentran en la cocina caribeña o africana, y están disponibles en muchos supermercados de EE. UU.",
"8","1 pieza de plátano macho + 1 cucharada de salsa",
["2 plátanos machos medianos","2 hojas de papel aluminio (lo bastante grandes para envolver un plátano)","1 chile poblano mediano (cortado en cubos de 1/4 de pulgada)","1 cucharadita de aceite de aguacate","3/4 taza de caldo de pollo (sin sal)","1/4 taza de chalotes (finamente picados)","1 diente de ajo (pelado y finamente picado)","1/4 taza de guayaba en cubos (cubos de 1/4 de pulgada)","1/4 taza de vinagre de arroz","1/2 cucharadita de sal kosher","1 cucharadita de pimienta negra (triturada)","1/2 taza de queso fresco (desmenuzado)","2 cucharaditas de cilantro (finamente picado)"],
["Precaliente el horno a 400 °F.","Corte las puntas de los plátanos. Introduzca la punta de un cuchillo de pelar unos 1/2 pulgada en cada plátano y recórralo de arriba abajo. Envuelva cada plátano en una hoja de papel aluminio. Áselos en el horno durante 30 minutos, luego sáquelos del horno y reserve. Deje el horno encendido.","Lave y seque el chile poblano. Frote aceite de aguacate por fuera del chile y colóquelo (con cuidado) sobre una llama o en el horno hasta que la parte exterior se chamusque. Una vez chamuscado, colóquelo en un tazón y tápelo hasta que el vapor afloje la piel. Pase el chile bajo agua fría para quitar lo chamuscado y luego píquelo en cubos.","En una cacerola pequeña, agregue el caldo, los chalotes, el ajo, el chile poblano y la guayaba, y lleve a un hervor fuerte a fuego lento. Cocine hasta que se forme una pasta suave, unos 5 minutos. Agregue el vinagre de arroz, la sal y la pimienta, y bata bien para asegurarse de que no queden grumos en la salsa. Reduzca el fuego a bajo y siga cocinando por 2 minutos. Vierta la salsa en una licuadora y lícuela hasta que esté suave.","Quite el papel aluminio de los plátanos y corte cada uno en 4 partes iguales. Abra con cuidado el plátano a lo largo del corte. Agregue 1 cucharada de salsa de guayaba, cubra con queso fresco y decore con cilantro. ¡Disfrute!"]),
"ar":L("موز الطبخ وفلفل البوبلانو المشويان مع صلصة الجوافة",
"هذا الطبق الحلو والمدخّن والشهي مثالي كطبق جانبي للحم الخنزير أو الدجاج المشوي. يشبه موز الطبخ الموز العادي لكنه يحتوي على نسبة أعلى من النشا، ويُستمتع به أكثر عند شيّه أو طهيه. ستجده عادةً في المطبخ الكاريبي أو الأفريقي، وهو متوفر في كثير من متاجر البقالة في الولايات المتحدة.",
"8","1 قطعة موز طبخ + 1 ملعقة كبيرة من الصلصة",
["2 حبة موز طبخ متوسطة","2 ورقة ألمنيوم (كبيرة بما يكفي للف حبة موز طبخ)","1 حبة فلفل بوبلانو متوسطة (مقطعة إلى مكعبات بحجم ¼ بوصة)","1 ملعقة صغيرة من زيت الأفوكادو","¾ كوب من مرق الدجاج (غير مملح)","¼ كوب من الكراث الفرنسي (الشالوت) (مفروم ناعمًا)","1 فص ثوم (مقشر ومفروم ناعمًا)","¼ كوب من مكعبات الجوافة (مكعبات بحجم ¼ بوصة)","¼ كوب من خل الأرز","½ ملعقة صغيرة من الملح الخشن (كوشير)","1 ملعقة صغيرة من الفلفل الأسود (مجروش)","½ كوب من الجبن الأبيض الطازج (كيسو فريسكو) (مفتّت)","2 ملعقة صغيرة من الكزبرة الخضراء (مفرومة ناعمًا)"],
["سخّن الفرن مسبقًا إلى 400° فهرنهايت (205° مئوية).","اقطع أطراف حبات موز الطبخ. أدخل رأس سكين التقشير نحو ½ بوصة في كل حبة واشقّها من الأعلى إلى الأسفل. لف كل حبة بورقة ألمنيوم. اشوها في الفرن لمدة 30 دقيقة، ثم أخرجها من الفرن واتركها جانبًا. أبقِ الفرن مشغّلًا.","اغسل فلفل البوبلانو وجفّفه. افرك الجزء الخارجي من الفلفل بزيت الأفوكادو وضعه (بحذر) فوق لهب أو في الفرن حتى يتفحّم سطحه الخارجي. بعد أن يتفحّم الفلفل، ضعه في وعاء وغطِّه حتى يُرخي البخار القشرة. مرّر الفلفل تحت الماء البارد لإزالة الجزء المتفحّم، ثم قطّعه مكعبات.","في قدر صغير، أضف المرق والكراث الفرنسي والثوم وفلفل البوبلانو والجوافة، واتركها حتى تصل إلى غليان هادئ متواصل. اطهِ حتى تتكوّن عجينة ناعمة، نحو 5 دقائق. أضف خل الأرز والملح والفلفل واخفق جيدًا للتأكد من عدم وجود تكتلات في الصلصة. خفّف الحرارة إلى منخفضة وواصل الطهي لمدة دقيقتين. اسكب الصلصة في الخلاط وامزجها حتى تصبح ناعمة.","انزع ورق الألمنيوم عن موز الطبخ وقطّع كل حبة إلى 4 أجزاء متساوية. افتح حبة الموز برفق على طول الشق. أضف 1 ملعقة كبيرة من صلصة الجوافة، وضع فوقها الجبن الأبيض الطازج، وزيّنها بالكزبرة الخضراء. بالهناء والعافية!"])}))
R.append((6756951,{
"es":L("Bowl de desayuno salado de huevo y verduras",
"Un bowl de desayuno es una buena forma de aprovechar las verduras que le sobren. Este bowl muy bajo en carbohidratos obtiene un impulso de sabor de las especias, la salchicha de pollo, los champiñones y los huevos. Rocíe un poco de jugo de lima por encima para un toque cítrico.",
"2","2 huevos + 1 salchicha + 1 1/2 tazas de verduras",
["1 taza de sustituto de huevo","1/8 cucharadita de pimentón ahumado","1/4 cucharadita de ajo en polvo","2 salchichas de pollo para desayuno","1/4 taza de requesón al 1% de grasa, sin sal","1/4 taza de cebolla (picada)","1/2 taza de champiñones cremini (baby bella) (en rodajas)","1 taza de espinacas tiernas (picadas)","6 tomates cherry enteros (partidos por la mitad)","1/2 aguacate entero (en rebanadas)","1 cucharadita de cebollino fresco","1 cucharadita de jugo de lima (opcional)"],
["En un sartén antiadherente, cocine el sustituto de huevo a fuego medio, revolviendo para hacer huevo revuelto. Incorpore el pimentón y el ajo en polvo.","Rocíe un sartén mediano con aceite en aerosol y caliente a fuego medio. Agregue las salchichas y cocine hasta que se doren. Retírelas del sartén y agregue las cebollas y los champiñones. Cocine hasta que se doren, unos 5 minutos. Agregue las espinacas y cocine solo hasta que se marchiten. Retire del fuego.","Divida los huevos entre dos tazones. Rebane las salchichas y coloque una en cada tazón. Agregue la mitad del resto a cada tazón: el requesón, la mezcla de espinacas y champiñones, los tomates cherry y el aguacate. Espolvoree con cebollino. Rocíe con jugo de lima si lo desea."]),
"ar":L("طبق إفطار مالح بالبيض والخضار",
"طبق الإفطار طريقة جيدة للاستفادة من الخضار الزائدة لديك. يكتسب هذا الطبق القليل جدًا من الكربوهيدرات دفعة من النكهة من التوابل ونقانق الدجاج والفطر والبيض. رش القليل من عصير الليمون الأخضر فوقه للحصول على لقمة منعشة.",
"2","2 بيضة + 1 قطعة نقانق + 1½ كوب من الخضار",
["1 كوب من بديل البيض","⅛ ملعقة صغيرة من البابريكا المدخنة","¼ ملعقة صغيرة من مسحوق الثوم","2 قطعة نقانق دجاج للإفطار","¼ كوب من الجبن القريش بنسبة دهون 1%، غير مملح","¼ كوب من البصل (مفروم)","½ كوب من فطر كريميني (بيبي بيلا) (مقطع شرائح)","1 كوب من السبانخ الصغيرة (مفرومة)","6 حبات طماطم كرزية كاملة (مقطعة إلى نصفين)","½ حبة أفوكادو كاملة (مقطعة شرائح)","1 ملعقة صغيرة من الثوم المعمر الطازج (الشيف)","1 ملعقة صغيرة من عصير الليمون الأخضر (اختياري)"],
["في مقلاة غير لاصقة، اطهِ بديل البيض على نار متوسطة مع التحريك ليصبح بيضًا مخفوقًا. أضف البابريكا ومسحوق الثوم وقلّب.","رشّ مقلاة متوسطة ببخاخ الطهي وسخّنها على نار متوسطة. أضف قطع النقانق واطهِها حتى تتحمّر. أخرجها من المقلاة وأضف البصل والفطر. اطهِ حتى يتحمّرا، نحو 5 دقائق. أضف السبانخ واطهِ حتى تذبل فقط. ارفعها عن النار.","وزّع البيض على وعاءين. قطّع النقانق إلى شرائح وضع قطعة في كل وعاء. أضف نصف بقية المكونات إلى كل وعاء: الجبن القريش وخليط السبانخ والفطر والطماطم الكرزية والأفوكادو. رش الثوم المعمر. رش عصير الليمون الأخضر إن رغبت."])}))
R.append((6757804,{
"es":L("Salteado de camarones con limón y tomillo con arroz de coliflor",
"Este sabroso salteado de camarones con limón y tomillo usa ingredientes aptos para personas con diabetes, como arroz de coliflor y hierbas frescas, para que su cena no eleve bruscamente sus niveles de glucosa en la sangre (azúcar en la sangre). Disfrute sabores cítricos e ingredientes saludables que le ayudarán a seguir su plan de alimentación para la diabetes sin sacrificar el sabor. Puede personalizar fácilmente este salteado con su proteína favorita, como pollo, o con una alternativa de origen vegetal como el tofu. Si usa camarones, trate de usar camarones frescos en lugar de congelados para mantener bajos los niveles de sodio. ¡Pruebe hoy mismo esta receta fácil!",
"4","2 tazas",
["2 oz de aceite de oliva","2 tazas de verduras mixtas (como pimientos, chícharos dulces y zanahorias) (en rodajas)","2 cebollines (cebolla verde) enteros (en rodajas)","2 dientes de ajo (picados)","1 libra de camarones grandes frescos (que no hayan sido congelados) (pelados y desvenados)","12 oz de arroz de coliflor congelado","1 cucharada de salsa de soya","1 cucharada de hojas de tomillo fresco (más 4 ramitas para decorar)","1 jugo de 1 limón entero","1/8 cucharadita de sal","1/4 cucharadita de pimienta negra","1 limón entero (cortado en cuartos, para decorar)"],
["En un sartén grande o wok, caliente el aceite de oliva a fuego medio. Agregue las verduras mixtas y el cebollín en rodajas al sartén. Saltee de 3 a 4 minutos, hasta que las verduras estén tiernas pero crujientes.","Agregue el ajo picado y saltee de 1 a 2 minutos, hasta que desprenda aroma.","Agregue los camarones al sartén y cocine unos 3 a 4 minutos, hasta que se pongan rosados y opacos.","Agregue el arroz de coliflor al sartén. Cocine unos 3 a 4 minutos, revolviendo de vez en cuando, hasta que el arroz de coliflor esté tierno.","Incorpore la salsa de soya, las hojas de tomillo fresco, el jugo de limón, la sal y la pimienta negra. Revuelva todo para combinar bien y calentar.","Decore con ramitas de tomillo fresco y cuartos de limón, si lo desea."]),
"ar":L("مقلي الروبيان بالليمون والزعتر مع أرز القرنبيط",
"يستخدم مقلي الروبيان اللذيذ بالليمون والزعتر هذا مكونات مناسبة لمرضى السكري مثل أرز القرنبيط والأعشاب الطازجة لضمان ألا يرفع عشاؤك مستويات الغلوكوز في الدم (سكر الدم). استمتع بنكهات حمضية منعشة ومكونات صحية تساعدك على اتباع خطتك الغذائية للسكري دون التضحية بالنكهة. يمكنك بسهولة تخصيص هذا المقلي ببروتينك المفضل مثل الدجاج أو ببديل نباتي مثل التوفو. وإذا استخدمت الروبيان، فحاول استخدام روبيان طازج بدلًا من المجمد للحفاظ على انخفاض مستويات الصوديوم. جرّب هذه الوصفة السهلة اليوم!",
"4","2 كوب",
["2 أونصة من زيت الزيتون","2 كوب من الخضار المشكلة (مثل الفلفل الرومي والبازلاء السكرية والجزر) (مقطعة شرائح)","2 حبة بصل أخضر (مقطعة شرائح)","2 فص ثوم (مفروم)","1 رطل من الروبيان الكبير الطازج (غير المجمد سابقًا) (مقشر ومنزوع الأمعاء)","12 أونصة من القرنبيط المفروم المجمد","1 ملعقة كبيرة من صلصة الصويا","1 ملعقة كبيرة من أوراق الزعتر الطازجة (إضافة إلى 4 أغصان للتزيين)","1 عصير ليمونة واحدة كاملة","⅛ ملعقة صغيرة من الملح","¼ ملعقة صغيرة من الفلفل الأسود","1 ليمونة كاملة (مقطعة إلى أرباع، للتزيين)"],
["في مقلاة كبيرة أو وعاء ووك، سخّن زيت الزيتون على نار متوسطة. أضف الخضار المشكلة وشرائح البصل الأخضر إلى المقلاة. قلّبها لمدة 3–4 دقائق حتى تصبح الخضار طرية ومقرمشة.","أضف الثوم المفروم وقلّب لمدة 1–2 دقيقة حتى تفوح رائحته.","أضف الروبيان إلى المقلاة واطهِه نحو 3–4 دقائق حتى يتحول لونه إلى الوردي ويصبح معتمًا.","أضف أرز القرنبيط إلى المقلاة. اطهِ نحو 3–4 دقائق مع التحريك من حين لآخر حتى يلين أرز القرنبيط.","أضف صلصة الصويا وأوراق الزعتر الطازجة وعصير الليمون والملح والفلفل الأسود وحرّك. قلّب كل شيء معًا ليمتزج جيدًا ويسخن.","زيّنه بأغصان الزعتر الطازجة وأرباع الليمون، إن رغبت."])}))
R.append((6758436,{
"es":L("Troncos de apio con almendras y arándanos rojos",
"Una nueva versión del refrigerio de la infancia, «hormigas en un tronco»; esta versión para adultos se prepara con queso crema, arándanos rojos secos y almendras. Usamos queso crema batido de frutos rojos mixtos, pero el natural también funcionaría. El queso crema batido tiene menos grasa y calorías, y es más fácil de untar gracias al proceso de batido. ¡Experimente con diferentes frutas secas y nueces para encontrar su favorita!",
"4","3 piezas",
["4 tallos de apio (lavados y recortados)","4 cucharadas de queso crema batido de frutos rojos mixtos","24 arándanos rojos secos enteros","12 almendras enteras sin sal"],
["Rellene cada tallo de apio con 1 cucharada de queso crema y luego corte cada tallo en 3 partes iguales. Cubra cada pieza con 1 almendra y 2 arándanos rojos secos. Sirva de inmediato, o tape y refrigere hasta el momento de servir."]),
"ar":L("أعواد الكرفس باللوز والتوت البري",
"لمسة جديدة على الوجبة الخفيفة التي نعرفها منذ الطفولة، «النمل على جذع»؛ هذه النسخة للكبار مصنوعة من الجبن الكريمي والتوت البري المجفف واللوز. استخدمنا جبنًا كريميًّا مخفوقًا بنكهة التوت المشكل، لكن السادة يصلح أيضًا. الجبن الكريمي المخفوق أقل دسمًا وسعراتٍ حرارية وأسهل في الدهن بفضل عملية الخفق. جرّب أنواعًا مختلفة من الفواكه المجففة والمكسرات لتجد المفضلة لديك!",
"4","3 قطع",
["4 سيقان كرفس (مغسولة ومقطوعة الأطراف)","4 ملاعق كبيرة من الجبن الكريمي المخفوق بنكهة التوت المشكل","24 حبة توت بري مجفف كاملة","12 حبة لوز كاملة غير مملحة"],
["املأ كل ساق كرفس بـ1 ملعقة كبيرة من الجبن الكريمي، ثم اقطع كل ساق إلى 3 قطع متساوية. ضع فوق كل قطعة حبة لوز واحدة وحبتين من التوت البري المجفف. قدّمها فورًا، أو غطِّها وضعها في الثلاجة حتى وقت التقديم."])}))
save("out_c20_part4.json",R)
